(function(){'use strict';
const form=document.getElementById('tourSearch'),status=document.getElementById('status'),results=document.getElementById('results');
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function price(v){const n=parseInt(String(v||'').replace(/\D/g,''),10);return n?new Intl.NumberFormat('ru-RU').format(n):'';}
function image(html){if(!html)return'';const m=String(html).match(/src=['"]([^'"]+)/i);return m?m[1]:'';}
function showStatus(text){status.hidden=false;status.textContent=text;}
function render(tours){results.innerHTML='';if(!Array.isArray(tours)||!tours.length){results.innerHTML='<div class="empty">Туры пока не получены.</div>';return;}tours.forEach(t=>{const img=image(t.hotel_img);const card=document.createElement('article');card.className='hotel-card';card.innerHTML='<div class="hotel-photo">'+(img?'<img src="'+esc(img)+'" alt="">':'')+'</div><div><div class="hotel-title">'+esc(t.hotel_name||t.name||'Отель')+'</div><div class="hotel-place">'+esc([t.country_name,t.region_name,t.resort_name].filter(Boolean).join(', '))+'</div><div class="hotel-rating">'+(t.hotel_star?esc(t.hotel_star)+'★ ':'')+(t.hotel_rate?'Рейтинг '+esc(t.hotel_rate):'')+'</div><div class="hotel-price">'+price(t.price)+' <small>руб.</small></div></div>';results.appendChild(card);});}
form.addEventListener('submit',async function(e){e.preventDefault();const button=form.querySelector('.primary');button.disabled=true;results.innerHTML='';showStatus('Запускаем поиск…');try{const fd=new FormData(form);fd.set('search_start','Искать туры');const r=await fetch(window.V2_CONFIG.ajax,{method:'POST',body:fd,credentials:'same-origin'});const data=await r.json();if(Array.isArray(data.tours)){showStatus('Найдено вариантов: '+data.tours.length);render(data.tours);}else{showStatus(data.message||data.error||'Поиск запущен. Подключаем следующий этап получения результатов.');}}catch(err){showStatus('Не удалось выполнить поиск: '+err.message);}finally{button.disabled=false;}});
})();
