(function(){'use strict';
const form=document.getElementById('tourSearch'),status=document.getElementById('status'),results=document.getElementById('results');
let reqid=0,timer=0,lastTours=[];
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function price(v){const n=parseInt(String(v||'').replace(/\D/g,''),10);return n?new Intl.NumberFormat('ru-RU').format(n):'';}
function image(html){if(!html)return'';const m=String(html).match(/src=['"]([^'"]+)/i);return m?m[1]:'';}
function showStatus(text){status.hidden=false;status.textContent=text;}
async function post(data){const body=new URLSearchParams();Object.keys(data).forEach(k=>{const v=data[k];if(Array.isArray(v)){v.forEach(x=>body.append(k+'[]',x));}else if(v!==undefined&&v!==null){body.append(k,v);}});const r=await fetch(window.V2_CONFIG.ajax,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:body.toString(),credentials:'same-origin'});if(!r.ok)throw new Error('HTTP '+r.status);return await r.json();}
function tourRow(t){const tid=t.id||t.tid||t.tourid||t.tour_id||'';const date=t.date||t.datefrom||t.date_from||t.flydate||'';const nights=t.nights||t.night||t.days||'';const meal=t.meal||t.food||t.meal_name||'';const room=t.room||t.room_name||t.placement||'';return '<div class="tour-row"><div class="tour-meta"><strong>'+esc(date||'Вариант тура')+'</strong><span>'+esc([nights?(nights+' ноч.'):'',meal,room].filter(Boolean).join(' · '))+'</span></div><div class="tour-action"><b>'+price(t.price)+' ₽</b><button type="button" class="choose-tour" data-tid="'+esc(tid)+'">Выбрать тур</button></div></div>';}
async function openTours(card,hid,button){const box=card.querySelector('.hotel-tours');if(box.dataset.loaded==='1'){box.hidden=!box.hidden;button.textContent=box.hidden?'Посмотреть туры':'Скрыть туры';return;}button.disabled=true;button.textContent='Загружаем…';box.hidden=false;box.innerHTML='<div class="tour-loading">Получаем варианты туров…</div>';try{const data=await post({get_hotel_tours:1,req:reqid,hid:hid});const tours=Array.isArray(data.tours)?data.tours:[];box.dataset.loaded='1';box.innerHTML=tours.length?tours.map(tourRow).join(''):'<div class="tour-loading">Для этого отеля варианты не получены.</div>';button.textContent='Скрыть туры';}catch(err){box.innerHTML='<div class="tour-loading">Ошибка загрузки: '+esc(err.message)+'</div>';button.textContent='Повторить';}finally{button.disabled=false;}}
function render(tours){lastTours=Array.isArray(tours)?tours.slice():[];results.innerHTML='';if(!lastTours.length){results.innerHTML='<div class="empty">Туры пока не получены.</div>';return;}lastTours.forEach(t=>{const img=image(t.hotel_img),hid=t.id||t.hotel_id||t.hid||'';const card=document.createElement('article');card.className='hotel-card';card.dataset.hid=hid;card.innerHTML='<div class="hotel-main"><div class="hotel-photo">'+(img?'<img src="'+esc(img)+'" alt="">':'')+'</div><div class="hotel-body"><div class="hotel-title">'+esc(t.hotel||t.hotel_name||t.name||'Отель')+'</div><div class="hotel-place">'+esc([t.country,t.resort].filter(Boolean).join(', '))+'</div><div class="hotel-rating">'+(t.hotel_star?esc(t.hotel_star)+'★ ':'')+(t.hotel_rate?'Рейтинг '+esc(t.hotel_rate):'')+'</div><div class="hotel-bottom"><div class="hotel-price">от '+price(t.price)+' <small>₽</small></div><button type="button" class="show-tours">Посмотреть туры</button></div></div></div><div class="hotel-tours" hidden></div>';results.appendChild(card);});}
function buildSearchData(){const fd=new FormData(form),stars=fd.get('stars'),food=fd.get('food');return{search_create:1,city:fd.get('from'),country:fd.get('country'),datefrom:fd.get('dateFrom'),datetill:fd.get('dateTo'),nightsmin:fd.get('daysFrom'),nightsmax:fd.get('daysTill'),adults:fd.get('count_people')||2,children:0,children_ages:[],resort:[],hotel:[],stars:stars?[stars]:[],food:food?[food]:[],price_from:fd.get('price_from')||'',price_till:fd.get('price_till')||'',hide_reg_tours:0,params_changed:(stars||food||fd.get('price_from')||fd.get('price_till'))?'1':'0'};}
async function fetchCurrent(){if(!reqid)return;const data=await post({search_result:1,reqid:reqid,page:1,upd:true});if(Array.isArray(data.tours))render(data.tours);return data;}
async function poll(){if(!reqid)return;try{const data=await post({search_update:1,reqid:reqid});const percent=Math.max(0,Math.min(100,parseInt(data.percent||0,10)));const total=parseInt(data.tcount||0,10);showStatus('Поиск: '+percent+'% · найдено туров: '+total);if(Array.isArray(data.tours)&&data.tours.length)render(data.tours);if(percent>=100){if(!lastTours.length||total>lastTours.length)await fetchCurrent();showStatus('Поиск завершён · найдено туров: '+total);form.querySelector('.primary').disabled=false;return;}timer=setTimeout(poll,3000);}catch(err){showStatus('Ошибка обновления поиска: '+err.message);form.querySelector('.primary').disabled=false;}}
results.addEventListener('click',function(e){const show=e.target.closest('.show-tours');if(show){const card=show.closest('.hotel-card');if(!reqid||!card)return;openTours(card,card.dataset.hid,show);return;}const choose=e.target.closest('.choose-tour');if(choose){const card=choose.closest('.hotel-card');const tid=choose.dataset.tid;if(!tid){showStatus('У варианта нет идентификатора тура.');return;}showStatus('Тур выбран. Следующим этапом подключаем собственную карточку выбранного тура и заявку.');}});
form.addEventListener('submit',async function(e){e.preventDefault();if(timer)clearTimeout(timer);reqid=0;lastTours=[];results.innerHTML='';const button=form.querySelector('.primary');button.disabled=true;showStatus('Запускаем поиск…');try{const data=await post(buildSearchData());reqid=parseInt(data.reqid||0,10);const percent=parseInt(data.percent||0,10);const total=parseInt(data.tcount||0,10);if(Array.isArray(data.tours)&&data.tours.length)render(data.tours);if(!reqid)throw new Error(data.error||data.message||'backend не вернул reqid');showStatus('Поиск: '+percent+'% · найдено туров: '+total);if(percent>=100){if(!lastTours.length)await fetchCurrent();button.disabled=false;}else{timer=setTimeout(poll,3000);}}catch(err){showStatus('Не удалось выполнить поиск: '+err.message);button.disabled=false;}});
})();
