(function(){'use strict';
const rt=window.V2Runtime;if(!rt)return;
const form=document.getElementById('tourSearch'),childCount=document.getElementById('childCount'),childAges=document.getElementById('childAges'),serviceBox=document.getElementById('hotelServices'),serviceCount=document.getElementById('serviceCount'),extras=form&&form.querySelector('details.extras');if(!form)return;
const api=async(action,params)=>{const local=window.V2LocalCatalogApi&&window.V2LocalCatalogApi.load;if(local){if(action==='regions'&&!(params&&params.arrivalId)){try{return await local(action,params);}catch(e){console.warn('local regions',e);}}if(action==='subregions'){try{return await local(action,params);}catch(e){console.warn('local subregions',e);}}if(action==='hotels'&&params&&params.countryId&&params.regionId){try{return await local(action,params);}catch(e){console.warn('local hotels',e);}}}return rt.api(action,params);};let revision=0,recovery=null,criticalReady=false,advancedKey='',mealsLoaded=false;
function active(token){return token===revision;}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function optionName(x){return x&&(x.russianName||x.fullRussianName||x.name||x.nameGenitive||x.fullName||x.id)||'';}
function fillSelect(el,items,placeholder,preferred){if(!el)return;const current=String(preferred!==undefined?preferred:el.value||''),arr=Array.isArray(items)?items:[];el.innerHTML='<option value="">'+esc(placeholder)+'</option>'+arr.map(x=>'<option value="'+esc(x.id)+'">'+esc(optionName(x))+'</option>').join('');if(current&&arr.some(x=>String(x.id)===current))el.value=current;}
async function loadDepartures(){try{const r=await fetch('/data/departures-v1.php',{headers:{Accept:'application/json'},credentials:'same-origin'});if(!r.ok)throw new Error('local departures '+r.status);const d=await r.json();if(d&&d.ok&&Array.isArray(d.items)&&d.items.length)return d.items;}catch(e){console.warn('local departures',e);}return api('departures',{departureCountryId:1});}
function clearRecovery(){if(recovery&&recovery.isConnected)recovery.remove();recovery=null;}
function showRecovery(message){if(!recovery||!recovery.isConnected){recovery=document.createElement('section');recovery.className='status catalog-recovery';recovery.setAttribute('role','alert');recovery.innerHTML='<div class="search-progress-error"><div class="search-progress-error-copy"><strong>Не удалось обновить направления</strong><span></span></div><button type="button" class="search-progress-retry catalog-retry">Повторить загрузку</button></div>';form.insertAdjacentElement('afterend',recovery);recovery.querySelector('.catalog-retry').addEventListener('click',()=>{const btn=recovery&&recovery.querySelector('.catalog-retry');if(btn){btn.disabled=true;btn.textContent='Загружаем…';}init();});}const text=recovery.querySelector('.search-progress-error-copy span');if(text)text.textContent=message||'Проверьте соединение и попробуйте ещё раз.';const btn=recovery.querySelector('.catalog-retry');if(btn){btn.disabled=false;btn.textContent='Повторить загрузку';}}
function clearDependentCatalogs(){advancedKey='';fillSelect(form.elements.arrival,[],'Любой аэропорт');fillSelect(form.elements.region,[],'Все курорты');fillSelect(form.elements.subregion,[],'Сначала выберите курорт');fillSelect(form.elements.hotel,[],'Сначала выберите курорт');fillSelect(form.elements.operator,[],'Все операторы');fillSelect(form.elements.hotel_type,[],'Любой тип');renderHotelServices([]);}
function destinationKey(){return [form.elements.from&&form.elements.from.value||'',form.elements.country&&form.elements.country.value||'',form.elements.onlyDirect&&form.elements.onlyDirect.checked?'1':'0',form.elements.onlyCharter&&form.elements.onlyCharter.checked?'1':'0'].join('|');}
function advancedOpen(){return !!(extras&&extras.open);}
async function loadCountries(token){const from=form.elements.from,country=form.elements.country;if(!from||!country||!active(token))return;const previous=country.value;try{const d=await api('countries',{departureId:from.value,onlyDirect:!!(form.elements.onlyDirect&&form.elements.onlyDirect.checked),onlyCharter:!!(form.elements.onlyCharter&&form.elements.onlyCharter.checked)});if(!active(token))return;fillSelect(country,d,'Выберите страну',previous);if(!country.value&&Array.isArray(d)&&d.length)country.value=String(d[0].id);criticalReady=true;clearRecovery();}catch(e){if(active(token)){criticalReady=false;fillSelect(country,[],'Не удалось загрузить страны');clearDependentCatalogs();showRecovery('Список стран для выбранного города вылета недоступен. Повторите загрузку, прежде чем запускать новый поиск.');}throw e;}}
async function loadArrivals(token){const el=form.elements.arrival;if(!el||!active(token))return;const departure=form.elements.from&&form.elements.from.value,country=form.elements.country&&form.elements.country.value;if(!departure||!country){fillSelect(el,[],'Любой аэропорт');return;}try{let list=await api('arrivals',{departureId:departure,onlyDirect:!!(form.elements.onlyDirect&&form.elements.onlyDirect.checked),onlyCharter:!!(form.elements.onlyCharter&&form.elements.onlyCharter.checked)});if(!active(token))return;if(Array.isArray(list))list=list.filter(x=>String(x&&x.countryId||'')===String(country));fillSelect(el,list,'Любой аэропорт');}catch(e){if(active(token)){fillSelect(el,[],'Любой аэропорт');console.warn('arrivals',e);}}}
async function loadRegions(token){const el=form.elements.region,country=form.elements.country&&form.elements.country.value;if(!el||!active(token))return;if(!country){fillSelect(el,[],'Все курорты');return;}try{const list=await api('regions',{countryId:country,arrivalId:form.elements.arrival&&form.elements.arrival.value||''});if(active(token))fillSelect(el,list,'Все курорты');}catch(e){if(active(token)){fillSelect(el,[],'Все курорты');console.warn('regions',e);}}}
async function loadSubregions(token){const el=form.elements.subregion,country=form.elements.country&&form.elements.country.value,region=form.elements.region&&form.elements.region.value;if(!el||!active(token))return;if(!country||!region){fillSelect(el,[],region?'Все районы':'Сначала выберите курорт');return;}try{const list=await api('subregions',{countryId:country,regionId:region});if(active(token))fillSelect(el,list,'Все районы');}catch(e){if(active(token)){fillSelect(el,[],'Все районы');console.warn('subregions',e);}}}
function catalogRating(v){return({'2':'3','3':'3.5','4':'4','5':'4.5'})[String(v||'')]||'';}
async function loadHotelTypes(token){const el=form.elements.hotel_type,country=form.elements.country&&form.elements.country.value;if(!el||!active(token))return;if(!country){fillSelect(el,[],'Любой тип');return;}try{const list=await api('hotel_types',{countryId:country});if(active(token))fillSelect(el,list,'Любой тип');}catch(e){if(active(token)){fillSelect(el,[],'Любой тип');console.warn('hotel_types',e);}}}
async function loadHotels(token){const el=form.elements.hotel,country=form.elements.country&&form.elements.country.value,region=form.elements.region&&form.elements.region.value,subregion=form.elements.subregion&&form.elements.subregion.value;if(!el||!active(token))return;if(!country||!region){fillSelect(el,[],'Сначала выберите курорт');return;}try{let list=await api('hotels',{countryId:country,regionId:region,category:form.elements.stars&&form.elements.stars.value||'',rating:catalogRating(form.elements.rating&&form.elements.rating.value),types:form.elements.hotel_type&&form.elements.hotel_type.value?[form.elements.hotel_type.value]:[],limit:100});if(!active(token))return;if(subregion&&Array.isArray(list))list=list.filter(x=>String(x&&x.subRegion&&x.subRegion.id||'')===String(subregion));fillSelect(el,list,'Любой отель');}catch(e){if(active(token)){fillSelect(el,[],'Любой отель');console.warn('hotels',e);}}}
function updateServiceCount(){if(!serviceCount)return;const n=form.querySelectorAll('input[name="hotel_service[]"]:checked').length;serviceCount.textContent=n?n+' выбрано':'не выбраны';}
function renderHotelServices(groups){if(!serviceBox)return;const chosen=new Set(Array.from(form.querySelectorAll('input[name="hotel_service[]"]:checked')).map(x=>String(x.value))),list=Array.isArray(groups)?groups:[];if(!list.length){serviceBox.innerHTML='<div class="service-loading">Нет доступных фильтров услуг для выбранного направления.</div>';updateServiceCount();return;}serviceBox.innerHTML=list.map(group=>'<div class="service-group"><strong>'+esc(group.name||'Услуги')+'</strong><div class="service-items">'+(Array.isArray(group.items)?group.items:[]).map(item=>'<label class="service-check"><input type="checkbox" name="hotel_service[]" value="'+esc(item.id)+'"'+(chosen.has(String(item.id))?' checked':'')+'><span>'+esc(item.name||item.id)+'</span></label>').join('')+'</div></div>').join('');updateServiceCount();}
async function loadHotelServices(token){if(!serviceBox||!active(token))return;const country=form.elements.country&&form.elements.country.value,region=form.elements.region&&form.elements.region.value;if(!country){renderHotelServices([]);return;}serviceBox.innerHTML='<div class="service-loading">Загружаем доступные услуги…</div>';try{const groups=await api('hotel_services',{countryId:country,regionIds:region?[region]:[]});if(active(token))renderHotelServices(groups);}catch(e){if(active(token)){serviceBox.innerHTML='<div class="service-loading">Не удалось загрузить услуги отелей.</div>';console.warn('hotel_services',e);}}}
async function loadOperators(token){const el=form.elements.operator;if(!el||!active(token))return;try{const list=await api('operators',{departureId:form.elements.from.value,countryId:form.elements.country.value});if(active(token))fillSelect(el,list,'Все операторы');}catch(e){if(active(token)){fillSelect(el,[],'Все операторы');console.warn('operators',e);}}}
async function loadMeals(token){const el=form.elements.food;if(!el||!active(token))return false;try{const list=await api('meals',{});if(active(token))fillSelect(el,list,'Любое');return active(token);}catch(e){if(active(token))console.warn('meals',e);return false;}}
async function refreshDestination(token){if(!active(token))return;await loadArrivals(token);if(!active(token))return;await Promise.all([loadRegions(token),loadOperators(token),loadHotelTypes(token)]);if(!active(token))return;await loadSubregions(token);if(!active(token))return;await Promise.all([loadHotels(token),loadHotelServices(token)]);}
async function ensureAdvanced(token,force){if(!active(token)||!criticalReady||!advancedOpen())return;const key=destinationKey();if(force||advancedKey!==key){await refreshDestination(token);if(!active(token))return;advancedKey=key;}if(!mealsLoaded)mealsLoaded=await loadMeals(token);}
async function init(){const token=++revision;criticalReady=false;try{const from=form.elements.from,prev=from.value,deps=await loadDepartures();if(!active(token))return;fillSelect(from,deps,'Город вылета',prev);if(!from.value&&Array.isArray(deps)&&deps.length)from.value=String(deps[0].id);await loadCountries(token);if(!active(token))return;clearDependentCatalogs();if(advancedOpen())await ensureAdvanced(token,true);if(active(token)){form.dataset.catalogSource='anytour-departures';clearRecovery();}}catch(e){if(active(token)){form.dataset.catalogSource='partial';const from=form.elements.from,country=form.elements.country;if(from&&(!from.options.length||String(from.options[from.selectedIndex]&&from.options[from.selectedIndex].textContent||'').includes('Загружаем')))fillSelect(from,[],'Не удалось загрузить города');if(country&&(!country.value||String(country.options[country.selectedIndex]&&country.options[country.selectedIndex].textContent||'').includes('Загружаем')))fillSelect(country,[],'Не удалось загрузить страны');if(!country||!country.value)clearDependentCatalogs();showRecovery('Города или страны сейчас не загрузились. Повторите загрузку — введённые даты и состав туристов сохранятся.');console.warn('V2 catalogs:',e.message);}}}
function renderChildAges(){if(!childCount||!childAges)return;const previous=Array.from(childAges.querySelectorAll('select[name="child_age[]"]')).map(el=>String(el.value)),count=Math.max(0,Math.min(3,Number(childCount.value)||0));childAges.hidden=count===0;childAges.innerHTML='';for(let i=0;i<count;i++){const selected=previous[i]!==undefined?previous[i]:'7',label=document.createElement('label');label.className='field child-age';label.innerHTML='<span>Возраст ребёнка '+(i+1)+'</span><select name="child_age[]">'+Array.from({length:18},(_,age)=>'<option value="'+age+'"'+(String(age)===selected?' selected':'')+'>'+age+(age===1?' год':age>=2&&age<=4?' года':' лет')+'</option>').join('')+'</select>';childAges.appendChild(label);}}
async function handleChange(e){if(e.target===childCount){renderChildAges();return true;}if(e.target.name==='hotel_service[]'){updateServiceCount();return true;}let token;if(e.target.name==='from'||e.target.name==='onlyDirect'||e.target.name==='onlyCharter'){token=++revision;criticalReady=false;clearDependentCatalogs();await loadCountries(token);if(active(token)&&advancedOpen())await ensureAdvanced(token,true);return true;}if(e.target.name==='country'){token=++revision;criticalReady=!!(form.elements.country&&form.elements.country.value);clearDependentCatalogs();if(active(token)&&advancedOpen())await ensureAdvanced(token,true);return true;}if(e.target.name==='arrival'){token=++revision;advancedKey='';await loadRegions(token);if(active(token))await loadSubregions(token);if(active(token))await Promise.all([loadHotels(token),loadHotelServices(token)]);return true;}if(e.target.name==='region'){token=++revision;advancedKey='';await loadSubregions(token);if(active(token))await Promise.all([loadHotels(token),loadHotelServices(token)]);return true;}if(e.target.name==='subregion'){token=++revision;await loadHotels(token);return true;}if((e.target.name==='stars'||e.target.name==='rating'||e.target.name==='hotel_type')&&form.elements.region&&form.elements.region.value){token=++revision;await loadHotels(token);return true;}return false;}
if(extras)extras.addEventListener('toggle',()=>{if(!extras.open||!criticalReady)return;const token=++revision;ensureAdvanced(token,false).catch(err=>console.warn('advanced catalogs',err));});
window.V2Catalogs={init,refreshDestination:()=>{const token=++revision;return refreshDestination(token);},handleChange,renderChildAges,updateServiceCount,get revision(){return revision;},get advancedLoaded(){return !!advancedKey;},version:2};
})();
