(function(){'use strict';
const enabled=new URLSearchParams(location.search).get('directSearch')==='1';if(!enabled)return;
const form=document.getElementById('tourSearch'),status=document.getElementById('status'),results=document.getElementById('results'),selected=document.getElementById('selectedTour');if(!form||!status||!results)return;
let searchId=0,pollTimer=0;
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));}
function money(v){const n=Number(v||0);return n?new Intl.NumberFormat('ru-RU').format(n):'';}
async function api(action,params){const q=new URLSearchParams({action});Object.entries(params||{}).forEach(([k,v])=>{if(v!==''&&v!==null&&v!==undefined)q.append(k,String(v));});const r=await fetch(window.V2_CONFIG.api+'?'+q.toString(),{credentials:'same-origin'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||('API HTTP '+r.status));return d;}
function show(text){status.hidden=false;status.textContent='DIRECT · '+text;}
function params(){const f=new FormData(form);return{departureId:f.get('from'),countryId:f.get('country'),dateFrom:f.get('dateFrom'),dateTo:f.get('dateTo'),nightsFrom:f.get('daysFrom'),nightsTo:f.get('daysTill'),adults:f.get('count_people')||2,meal:f.get('food')||'',hotelCategory:f.get('stars')||'',priceFrom:f.get('price_from')||'',priceTo:f.get('price_till')||'',currency:'RUB',onlyCharter:f.get('onlyCharter')?'true':'false',onlyDirect:f.get('onlyDirect')?'true':'false'};}
function tourRow(t){const meal=t.meal&&(t.meal.russianName||t.meal.fullRussianName||t.meal.name)||'',op=t.operator&&(t.operator.russianName||t.operator.name)||'';return '<div class="tour-row"><div class="tour-meta"><strong>'+esc(t.date||'Вариант тура')+'</strong><span>'+esc([t.nights?t.nights+' ноч.':'',meal,t.roomType||'',t.placement||'',op,t.isCharter?'чартер':''].filter(Boolean).join(' · '))+'</span></div><div class="tour-action"><b>'+money(t.price)+' ₽</b><button type="button" class="direct-tour" data-tid="'+esc(t.id||'')+'">Выбрать тур</button></div></div>';}
function render(items){results.innerHTML='';if(!Array.isArray(items)||!items.length){results.innerHTML='<div class="empty">Прямой Tourvisor API пока не вернул туры.</div>';return;}items.forEach(h=>{const card=document.createElement('article');card.className='hotel-card';const img=h.picturelink||'';card.innerHTML='<div class="hotel-main"><div class="hotel-photo">'+(img?'<img src="'+esc(img)+'" alt="">':'')+'</div><div class="hotel-body"><div class="hotel-title">'+esc(h.name||'Отель')+'</div><div class="hotel-place">'+esc([h.country&&h.country.name,h.region&&h.region.name,h.subRegion&&h.subRegion.name].filter(Boolean).join(', '))+'</div><div class="hotel-rating">'+(h.category?esc(h.category)+'★ ':'')+(h.rating?'Рейтинг '+esc(h.rating):'')+(h.seaDistance?' · море '+esc(h.seaDistance)+' м':'')+'</div><div class="hotel-bottom"><div class="hotel-price">от '+money(h.price)+' <small>₽</small></div></div></div></div><div class="hotel-tours">'+((h.tours||[]).map(tourRow).join('')||'<div class="tour-loading">Нет вариантов</div>')+'</div>';results.appendChild(card);});}
async function loadResults(){if(!searchId)return;const d=await api('search_results',{searchId,limit:25});render(d);}
async function poll(){if(!searchId)return;try{const s=await api('search_status',{searchId});const p=Math.max(0,Math.min(100,Number(s.progress||0)));show('Поиск: '+p+'%'+(s.minPrice?' · от '+money(s.minPrice)+' ₽':'')+' · '+esc(s.status||''));if(p>0)await loadResults();if(p>=100||String(s.status||'').toLowerCase()==='complete'){form.querySelector('.primary').disabled=false;show('Поиск завершён · 100%');await loadResults();return;}pollTimer=setTimeout(poll,2500);}catch(e){show('Ошибка статуса: '+e.message);form.querySelector('.primary').disabled=false;}}
async function showTour(tid){if(!tid)return;selected.hidden=false;selected.innerHTML='<div class="selected-loading">DIRECT · загружаем тур…</div>';selected.scrollIntoView({behavior:'smooth',block:'start'});try{const t=await api('tour',{tourId:tid,currency:'RUB'}),h=t.hotel||{},meal=t.meal&&(t.meal.russianName||t.meal.fullRussianName||t.meal.name)||'',op=t.operator&&(t.operator.russianName||t.operator.name)||'';selected.innerHTML='<button type="button" class="back-results">← К результатам</button><div class="selected-head"><div><span class="eyebrow">DIRECT TOURVISOR</span><h2>'+esc(h.name||t.name||'Тур')+'</h2><p>'+esc([h.country&&h.country.name,h.region&&h.region.name].filter(Boolean).join(', '))+'</p></div><div class="selected-price">'+money(t.price)+' ₽</div></div><div class="facts"><div><span>Вылет</span><b>'+esc(t.date||'—')+'</b></div><div><span>Ночей</span><b>'+esc(t.nights||'—')+'</b></div><div><span>Питание</span><b>'+esc(meal||'—')+'</b></div><div><span>Номер</span><b>'+esc(t.roomType||'—')+'</b></div><div><span>Размещение</span><b>'+esc(t.placement||'—')+'</b></div><div><span>Оператор</span><b>'+esc(op||'—')+'</b></div></div>';}catch(e){selected.innerHTML='<div class="selected-loading">DIRECT · ошибка загрузки тура: '+esc(e.message)+'</div>';}}
form.insertAdjacentHTML('afterbegin','<div class="status" style="margin-bottom:12px">Тестовый режим: прямой Tourvisor API. Обычный V2-поиск не переключён.</div>');
form.addEventListener('submit',async e=>{e.preventDefault();e.stopImmediatePropagation();if(pollTimer)clearTimeout(pollTimer);results.innerHTML='';selected.hidden=true;selected.innerHTML='';searchId=0;const btn=form.querySelector('.primary');btn.disabled=true;show('Запускаем прямой поиск…');try{const d=await api('search_start',params());searchId=Number(d.searchId||0);if(!searchId)throw new Error('Tourvisor не вернул searchId');show('Поиск запущен · ID '+searchId);pollTimer=setTimeout(poll,1200);}catch(e2){show('Не удалось запустить поиск: '+e2.message);btn.disabled=false;}},true);
results.addEventListener('click',e=>{const b=e.target.closest('.direct-tour');if(b){e.preventDefault();e.stopImmediatePropagation();showTour(b.dataset.tid);}},true);
selected.addEventListener('click',e=>{if(e.target.closest('.back-results'))results.scrollIntoView({behavior:'smooth',block:'start'});},true);
})();