(function(){'use strict';
const qs=new URLSearchParams(location.search),enabled=qs.get('legacySearch')!=='1';if(!enabled)return;
const form=document.getElementById('tourSearch'),status=document.getElementById('status'),results=document.getElementById('results'),selected=document.getElementById('selectedTour'),tools=document.getElementById('resultsTools'),summary=document.getElementById('resultSummary'),sortSelect=document.getElementById('sortResults'),childCount=document.getElementById('childCount'),childAges=document.getElementById('childAges');if(!form||!status||!results)return;
let searchId=0,pollTimer=0,currentTour=null,flightVariants=[],selectedFlightIndex=0,lastItems=[];
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function money(v){const n=Number(v||0);return n?new Intl.NumberFormat('ru-RU').format(n):'';}
function clean(v){return String(v||'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();}
async function api(action,params){const q=new URLSearchParams({action});Object.entries(params||{}).forEach(([k,v])=>{if(v===''||v===null||v===undefined)return;if(Array.isArray(v)){v.forEach(x=>{if(x!==''&&x!==null&&x!==undefined)q.append(k+'[]',String(x));});}else q.append(k,String(v));});const r=await fetch(window.V2_CONFIG.api+'?'+q.toString(),{credentials:'same-origin'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||('API HTTP '+r.status));return d;}
function show(text){status.hidden=false;status.textContent=text;}
function optionName(x){return x&&(x.russianName||x.fullRussianName||x.name||x.nameGenitive||x.fullName||x.id)||'';}
function fillSelect(el,items,placeholder,preferred){if(!el)return;const current=String(preferred!==undefined?preferred:el.value||'');const arr=Array.isArray(items)?items:[];el.innerHTML='<option value="">'+esc(placeholder)+'</option>'+arr.map(x=>'<option value="'+esc(x.id)+'">'+esc(optionName(x))+'</option>').join('');if(current&&arr.some(x=>String(x.id)===current))el.value=current;}
async function loadCountries(){const from=form.elements.from,country=form.elements.country;if(!from||!country)return;const previous=country.value;const d=await api('countries',{departureId:from.value,onlyDirect:form.elements.onlyDirect&&form.elements.onlyDirect.checked,onlyCharter:form.elements.onlyCharter&&form.elements.onlyCharter.checked});fillSelect(country,d,'Выберите страну',previous);if(!country.value&&Array.isArray(d)&&d.length)country.value=String(d[0].id);}
async function loadRegions(){const el=form.elements.region;if(!el)return;const country=form.elements.country&&form.elements.country.value;if(!country){fillSelect(el,[],'Все курорты');return;}try{fillSelect(el,await api('regions',{countryId:country}),'Все курорты');}catch(e){fillSelect(el,[],'Все курорты');console.warn('regions',e);}}
async function loadSubregions(){const el=form.elements.subregion;if(!el)return;const country=form.elements.country&&form.elements.country.value,region=form.elements.region&&form.elements.region.value;if(!country||!region){fillSelect(el,[],region?'Все районы':'Сначала выберите курорт');return;}try{fillSelect(el,await api('subregions',{countryId:country,regionId:region}),'Все районы');}catch(e){fillSelect(el,[],'Все районы');console.warn('subregions',e);}}
function catalogRating(v){return({'2':'3','3':'3.5','4':'4','5':'4.5'})[String(v||'')]||'';}
async function loadHotels(){const el=form.elements.hotel;if(!el)return;const country=form.elements.country&&form.elements.country.value,region=form.elements.region&&form.elements.region.value,subregion=form.elements.subregion&&form.elements.subregion.value;if(!country||!region){fillSelect(el,[],'Сначала выберите курорт');return;}try{let list=await api('hotels',{countryId:country,regionId:region,category:form.elements.stars&&form.elements.stars.value||'',rating:catalogRating(form.elements.rating&&form.elements.rating.value),limit:100});if(subregion&&Array.isArray(list))list=list.filter(x=>String(x&&x.subRegion&&x.subRegion.id||'')===String(subregion));fillSelect(el,list,'Любой отель');}catch(e){fillSelect(el,[],'Любой отель');console.warn('hotels',e);}}
async function loadOperators(){const el=form.elements.operator;if(!el)return;try{fillSelect(el,await api('operators',{departureId:form.elements.from.value,countryId:form.elements.country.value}),'Все операторы');}catch(e){fillSelect(el,[],'Все операторы');console.warn('operators',e);}}
async function loadMeals(){const el=form.elements.food;if(!el)return;try{fillSelect(el,await api('meals',{}),'Любое');}catch(e){console.warn('meals',e);}}
async function refreshDestinationCatalogs(){await Promise.all([loadRegions(),loadOperators()]);await loadSubregions();await loadHotels();}
async function initCatalogs(){try{const from=form.elements.from,prev=from.value,deps=await api('departures',{departureCountryId:1});fillSelect(from,deps,'Город вылета',prev);if(!from.value&&Array.isArray(deps)&&deps.length)from.value=String(deps[0].id);await loadCountries();await Promise.all([refreshDestinationCatalogs(),loadMeals()]);form.dataset.catalogSource='tourvisor-direct';}catch(e){form.dataset.catalogSource='partial';console.warn('V2 catalogs:',e.message);}}
function renderChildAges(){if(!childCount||!childAges)return;const count=Math.max(0,Math.min(3,Number(childCount.value)||0));childAges.hidden=count===0;childAges.innerHTML='';for(let i=0;i<count;i++){const label=document.createElement('label');label.className='field child-age';label.innerHTML='<span>Возраст ребёнка '+(i+1)+'</span><select name="child_age[]">'+Array.from({length:18},(_,age)=>'<option value="'+age+'"'+(age===7?' selected':'')+'>'+age+(age===1?' год':age>=2&&age<=4?' года':' лет')+'</option>').join('')+'</select>';childAges.appendChild(label);}}
function params(){const f=new FormData(form),ages=f.getAll('child_age[]').map(v=>Number(v)).filter(v=>Number.isFinite(v));return{departureId:f.get('from'),countryId:f.get('country'),dateFrom:f.get('dateFrom'),dateTo:f.get('dateTo'),nightsFrom:f.get('daysFrom'),nightsTo:f.get('daysTill'),adults:f.get('count_people')||2,childs:ages,meal:f.get('food')||'',hotelCategory:f.get('stars')||'',hotelRating:f.get('rating')||'',regionIds:f.get('region')?[f.get('region')]:[],subregionIds:f.get('subregion')?[f.get('subregion')]:[],hotelIds:f.get('hotel')?[f.get('hotel')]:[],operatorIds:f.get('operator')?[f.get('operator')]:[],priceFrom:f.get('price_from')||'',priceTo:f.get('price_till')||'',currency:'RUB',onlyCharter:f.get('onlyCharter')?'true':'false',onlyDirect:f.get('onlyDirect')?'true':'false'};}
function tourRow(t){const meal=t.meal&&(t.meal.russianName||t.meal.fullRussianName||t.meal.name)||'',op=t.operator&&(t.operator.russianName||t.operator.name)||'';return '<div class="tour-row"><div class="tour-meta"><strong>'+esc(t.date||'Вариант тура')+'</strong><span>'+esc([t.nights?t.nights+' ноч.':'',meal,t.roomType||'',t.placement||'',op,t.isCharter?'чартер':''].filter(Boolean).join(' · '))+'</span></div><div class="tour-action"><b>'+money(t.price)+' ₽</b><button type="button" class="direct-tour" data-tid="'+esc(t.id||'')+'">Выбрать</button></div></div>';}
function sortedItems(items){const mode=sortSelect?sortSelect.value:'price',copy=(Array.isArray(items)?items:[]).slice();copy.sort((a,b)=>{if(mode==='rating')return Number(b.rating||0)-Number(a.rating||0)||Number(a.price||0)-Number(b.price||0);if(mode==='stars')return Number(b.category||0)-Number(a.category||0)||Number(a.price||0)-Number(b.price||0);return Number(a.price||0)-Number(b.price||0);});return copy;}
function render(items){lastItems=Array.isArray(items)?items.slice():[];results.innerHTML='';if(tools)tools.hidden=!lastItems.length;if(summary)summary.textContent=lastItems.length?'Показано отелей: '+lastItems.length:'Актуальные варианты';if(!lastItems.length){results.innerHTML='<div class="empty"><strong>Пока ничего не нашли</strong><span>Попробуйте расширить даты, ночи или убрать часть фильтров.</span></div>';return;}sortedItems(lastItems).forEach(h=>{const card=document.createElement('article');card.className='hotel-card';const img=h.picturelink||'',rating=Number(h.rating||0),cat=Number(h.category||0);card.innerHTML='<div class="hotel-main"><div class="hotel-photo">'+(img?'<img src="'+esc(img)+'" alt="" loading="lazy">':'<div class="photo-placeholder">ANYTOUR</div>')+(cat?'<span class="stars-badge">'+esc(cat)+'★</span>':'')+'</div><div class="hotel-body"><div class="hotel-title">'+esc(h.name||'Отель')+'</div><div class="hotel-place">'+esc([h.country&&h.country.name,h.region&&h.region.name,h.subRegion&&h.subRegion.name].filter(Boolean).join(' · '))+'</div><div class="hotel-tags">'+(rating?'<span>★ '+esc(rating)+'</span>':'')+(h.seaDistance?'<span>Море '+esc(h.seaDistance)+' м</span>':'')+(h.tours&&h.tours.length?'<span>'+h.tours.length+' вариант'+(h.tours.length===1?'':'а')+'</span>':'')+'</div><div class="hotel-bottom"><div><small>Стоимость тура</small><div class="hotel-price">от '+money(h.price)+' <small>₽</small></div></div></div></div></div><div class="hotel-tours">'+((h.tours||[]).map(tourRow).join('')||'<div class="tour-loading">Нет доступных вариантов</div>')+'</div>';results.appendChild(card);});}
async function loadResults(){if(!searchId)return;const d=await api('search_results',{searchId,limit:25});render(d);}
async function poll(){if(!searchId)return;try{const s=await api('search_status',{searchId});const p=Math.max(0,Math.min(100,Number(s.progress||0)));show('Ищем лучшие предложения · '+p+'%'+(s.minPrice?' · от '+money(s.minPrice)+' ₽':'') );if(p>0)await loadResults();if(p>=100||String(s.status||'').toLowerCase()==='complete'){form.querySelector('.primary').disabled=false;show('Поиск завершён · предложения актуальны на сейчас');await loadResults();return;}pollTimer=setTimeout(poll,2500);}catch(e){show('Ошибка статуса: '+e.message);form.querySelector('.primary').disabled=false;}}
function portText(p){if(!p)return '—';const name=p.shortName||p.name||'',id=p.id||'';return esc(name+(id?' ('+id+')':''));}
function segmentHtml(f,label){if(!f||typeof f!=='object')return '';const company=f.company&&f.company.name||'',num=f.number||'',plane=f.plane||'',dep=f.departure||{},arr=f.arrival||{},baggage=f.baggage!==undefined&&f.baggage!==null?f.baggage+' кг':'—',carry=f.carryOn||'—';return '<div class="flight-segment"><div class="flight-segment-title"><strong>'+esc(label)+'</strong><span>'+esc([company,num,plane].filter(Boolean).join(' · '))+'</span></div><div class="flight-route"><div><b>'+portText(dep.port)+'</b><span>'+esc([dep.date,dep.time].filter(Boolean).join(' · ')||'—')+'</span></div><div class="flight-arrow">→</div><div><b>'+portText(arr.port)+'</b><span>'+esc([arr.date,arr.time].filter(Boolean).join(' · ')||'—')+'</span></div></div><div class="flight-baggage">Багаж: <b>'+esc(baggage)+'</b> · Ручная кладь: <b>'+esc(carry)+'</b></div></div>';}
function variantHtml(v,i){const fwd=Array.isArray(v.forward)?v.forward:[],back=Array.isArray(v.backward)?v.backward:[],priceObj=v.price||{},fuelObj=v.fuelCharge||{},priceValue=priceObj.value!==undefined?priceObj.value:priceObj,fuelValue=fuelObj.value!==undefined?fuelObj.value:fuelObj,checked=i===selectedFlightIndex?' checked':'',active=i===selectedFlightIndex?' is-selected':'';return '<div class="flight-variant'+active+'" data-flight-index="'+i+'"><label class="flight-choice"><input type="radio" name="v2flight" value="'+i+'"'+checked+'><span><strong>Вариант '+(i+1)+(v.isDefault?' · основной':'')+'</strong>'+(priceValue?'<small>'+money(priceValue)+' ₽</small>':'')+'</span></label>'+fwd.map((f,j)=>segmentHtml(f,j===0?'Туда':'Пересадка туда')).join('')+back.map((f,j)=>segmentHtml(f,j===0?'Обратно':'Пересадка обратно')).join('')+(fuelValue?'<div class="flight-fuel">Топливный сбор: <b>'+money(fuelValue)+' ₽</b></div>':'')+'</div>';}
function renderFlights(data){const box=selected.querySelector('.tour-flights');if(!box)return;let list=[];if(Array.isArray(data))list=data;else if(data&&Array.isArray(data.flights))list=data.flights;else if(data&&Array.isArray(data.items))list=data.items;flightVariants=list;if(!list.length){box.innerHTML='<strong>Авиарейсы</strong><p>Tourvisor не вернул детали рейсов для этого тура.</p>';return;}const def=list.findIndex(v=>v&&v.isDefault);selectedFlightIndex=def>=0?def:0;box.innerHTML='<div class="section-heading"><strong>Авиарейсы</strong><span>Выбранный вариант попадёт в заявку</span></div><div class="flight-variants">'+list.map(variantHtml).join('')+'</div>';}
async function loadFlights(tid,btn){if(!tid||!btn)return;btn.disabled=true;btn.textContent='Загружаем рейсы…';const box=selected.querySelector('.tour-flights');if(box)box.innerHTML='<strong>Авиарейсы</strong><p>Запрашиваем актуальные данные у туроператора…</p>';try{const d=await api('flights',{tourId:tid,currency:'RUB'});renderFlights(d);}catch(e){if(box)box.innerHTML='<strong>Авиарейсы</strong><p>Не удалось получить рейсы: '+esc(e.message)+'</p><button type="button" class="load-flights" data-tid="'+esc(tid)+'">Повторить запрос</button>';}}
function selectFlight(index){selectedFlightIndex=Math.max(0,Math.min(flightVariants.length-1,Number(index)||0));selected.querySelectorAll('.flight-variant').forEach((node,i)=>{node.classList.toggle('is-selected',i===selectedFlightIndex);const radio=node.querySelector('input[name="v2flight"]');if(radio)radio.checked=i===selectedFlightIndex;});}
function flightLegText(f,label){if(!f)return '';const dep=f.departure||{},arr=f.arrival||{},company=f.company&&f.company.name||'',depPort=dep.port||{},arrPort=arr.port||{};return label+': '+[company,f.number,f.plane].filter(Boolean).join(' · ')+'; '+[depPort.shortName||depPort.name,depPort.id].filter(Boolean).join(' ')+' '+[dep.date,dep.time].filter(Boolean).join(' ')+' → '+[arrPort.shortName||arrPort.name,arrPort.id].filter(Boolean).join(' ')+' '+[arr.date,arr.time].filter(Boolean).join(' ')+'; багаж '+(f.baggage!=null?f.baggage+' кг':'—')+', ручная кладь '+(f.carryOn||'—');}
function selectedFlightData(){const v=flightVariants[selectedFlightIndex];if(!v)return{flight:'',flightPrice:'',flightFuel:''};const parts=[];(Array.isArray(v.forward)?v.forward:[]).forEach((f,i)=>parts.push(flightLegText(f,i===0?'Туда':'Пересадка туда')));(Array.isArray(v.backward)?v.backward:[]).forEach((f,i)=>parts.push(flightLegText(f,i===0?'Обратно':'Пересадка обратно')));const p=v.price||{},fuel=v.fuelCharge||{};return{flight:parts.filter(Boolean).join(' | '),flightPrice:p&&p.value!==undefined?p.value:p||'',flightFuel:fuel&&fuel.value!==undefined?fuel.value:fuel||''};}
function attribution(){const p=new URLSearchParams(location.search),cookie=Object.fromEntries(document.cookie.split(';').map(v=>v.trim().split('=').map(decodeURIComponent)).filter(a=>a.length===2));return{yclid:p.get('yclid')||'',yaclient:cookie._ym_uid||'',utm_source:p.get('utm_source')||'',utm_medium:p.get('utm_medium')||'',utm_campaign:p.get('utm_campaign')||'',utm_content:p.get('utm_content')||'',utm_term:p.get('utm_term')||''};}
function leadPayload(fd){const t=currentTour||{},h=t.hotel||{},meal=t.meal&&(t.meal.russianName||t.meal.fullRussianName||t.meal.name)||'',op=t.operator&&(t.operator.russianName||t.operator.name)||'';return Object.assign({name:fd.get('name')||'',phone:fd.get('phone')||'',comment:fd.get('comment')||'',tourId:t.id||'',searchId:searchId||'',hotel:h.name||t.name||'',country:h.country&&h.country.name||'',region:h.region&&h.region.name||'',departure:t.departure&&t.departure.name||'',date:t.date||'',nights:t.nights||'',adults:t.adults||'',childs:t.childs||'',meal:meal,roomType:t.roomType||'',placement:t.placement||'',operator:op,price:t.price||'',currency:'RUB',page:location.href},selectedFlightData(),attribution());}
async function submitLead(leadForm){const btn=leadForm.querySelector('button[type="submit"]'),msg=leadForm.querySelector('.lead-message');btn.disabled=true;msg.textContent='Отправляем заявку…';let sent=false;try{const r=await fetch('/poisk-turov-test/v2/lead-adapter.php',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(leadPayload(new FormData(leadForm)))}),d=await r.json().catch(()=>({}));if(!r.ok||!d.ok||!d.writes)throw new Error(d.error||'Заявка не была записана');sent=true;msg.textContent='Заявка отправлена менеджеру. Номер заявки: '+(d.leadId||'—');btn.textContent='Заявка отправлена';leadForm.dataset.sent='1';}catch(e){msg.textContent='Не удалось отправить заявку: '+e.message;}finally{if(!sent)btn.disabled=false;}}
async function showTour(tid){if(!tid)return;currentTour=null;flightVariants=[];selectedFlightIndex=0;selected.hidden=false;selected.innerHTML='<div class="selected-loading">Загружаем тур…</div>';selected.scrollIntoView({behavior:'smooth',block:'start'});try{const t=await api('tour',{tourId:tid,currency:'RUB'});currentTour=t;const h=t.hotel||{},meal=t.meal&&(t.meal.russianName||t.meal.fullRussianName||t.meal.name)||'',op=t.operator&&(t.operator.russianName||t.operator.name)||'',place=[h.country&&h.country.name,h.region&&h.region.name,h.subRegion&&h.subRegion.name].filter(Boolean).join(' · '),desc=clean(t.hotelDescription),pic=t.picture||h.picturelink||'',people=[t.adults?t.adults+' взр.':'',t.childs?t.childs+' дет.':''].filter(Boolean).join(' + '),flightType=t.isCharter?'Чартер':'Регулярный/не указан';selected.innerHTML='<button type="button" class="back-results">← Вернуться к предложениям</button><div class="selected-head"><div><span class="eyebrow">ВЫБРАННЫЙ ТУР</span><h2>'+esc(h.name||t.name||'Тур')+'</h2><p>'+esc(place)+'</p></div><div class="selected-price"><small>Стоимость</small>'+money(t.price)+' ₽</div></div>'+(pic?'<div class="selected-picture"><img src="'+esc(pic)+'" alt=""></div>':'')+'<div class="facts"><div><span>Вылет из</span><b>'+esc(t.departure&&t.departure.name||'—')+'</b></div><div><span>Дата</span><b>'+esc(t.date||'—')+'</b></div><div><span>Ночей</span><b>'+esc(t.nights||'—')+'</b></div><div><span>Туристы</span><b>'+esc(people||'—')+'</b></div><div><span>Питание</span><b>'+esc(meal||'—')+'</b></div><div><span>Номер</span><b>'+esc(t.roomType||'—')+'</b></div><div><span>Размещение</span><b>'+esc(t.placement||'—')+'</b></div><div><span>Оператор</span><b>'+esc(op||'—')+'</b></div><div><span>Перелёт</span><b>'+esc(flightType)+'</b></div><div><span>Топливный сбор</span><b>'+(t.fuelCharge?money(t.fuelCharge)+' ₽':'—')+'</b></div></div>'+(desc?'<div class="hotel-desc">'+esc(desc)+'</div>':'')+'<div class="tour-flights"><div class="section-heading"><strong>Авиарейсы</strong><span>Можно выбрать конкретный вариант</span></div><button type="button" class="load-flights secondary" data-tid="'+esc(tid)+'">Показать рейсы</button></div><form class="lead-form"><div class="section-heading"><strong>Оставить заявку</strong><span>Менеджер получит выбранный тур и рейс</span></div><div class="lead-fields"><label>Имя<input name="name" maxlength="120" autocomplete="name"></label><label>Телефон<input name="phone" type="tel" required maxlength="40" autocomplete="tel" placeholder="+7 999 123-45-67"></label></div><label>Комментарий<textarea name="comment" maxlength="1000" rows="3" placeholder="Необязательно"></textarea></label><button type="submit" class="primary">Отправить заявку</button><p class="lead-message"></p></form>';}catch(e){selected.innerHTML='<button type="button" class="back-results">← К результатам</button><div class="selected-loading">Ошибка загрузки тура: '+esc(e.message)+'</div>';}}
form.addEventListener('change',async e=>{if(e.target===childCount){renderChildAges();return;}if(e.target.name==='from'||e.target.name==='onlyDirect'||e.target.name==='onlyCharter'){try{await loadCountries();await refreshDestinationCatalogs();}catch(x){console.warn(x);}return;}if(e.target.name==='country'){await refreshDestinationCatalogs();return;}if(e.target.name==='region'){await loadSubregions();await loadHotels();return;}if(e.target.name==='subregion'){await loadHotels();return;}if((e.target.name==='stars'||e.target.name==='rating')&&form.elements.region&&form.elements.region.value){await loadHotels();}});
if(sortSelect)sortSelect.addEventListener('change',()=>render(lastItems));
form.addEventListener('submit',async e=>{e.preventDefault();e.stopImmediatePropagation();if(pollTimer)clearTimeout(pollTimer);results.innerHTML='<div class="skeleton-grid">'+Array.from({length:4},()=>'<div class="skeleton-card"></div>').join('')+'</div>';if(tools)tools.hidden=true;selected.hidden=true;selected.innerHTML='';currentTour=null;flightVariants=[];searchId=0;const btn=form.querySelector('.primary');btn.disabled=true;show('Запускаем поиск Tourvisor…');try{const d=await api('search_start',params());searchId=Number(d.searchId||0);if(!searchId)throw new Error('Tourvisor не вернул searchId');show('Поиск запущен · собираем предложения');pollTimer=setTimeout(poll,1000);}catch(e2){results.innerHTML='';show('Не удалось запустить поиск: '+e2.message);btn.disabled=false;}},true);
results.addEventListener('click',e=>{const b=e.target.closest('.direct-tour');if(b){e.preventDefault();showTour(b.dataset.tid);}},true);
selected.addEventListener('change',e=>{if(e.target&&e.target.name==='v2flight')selectFlight(e.target.value);},true);
selected.addEventListener('submit',e=>{const lf=e.target.closest('.lead-form');if(lf){e.preventDefault();if(lf.dataset.sent==='1')return;submitLead(lf);}},true);
selected.addEventListener('click',e=>{const variant=e.target.closest('.flight-variant');if(variant){selectFlight(variant.dataset.flightIndex);return;}const flight=e.target.closest('.load-flights');if(flight){e.preventDefault();loadFlights(flight.dataset.tid,flight);return;}if(e.target.closest('.back-results'))results.scrollIntoView({behavior:'smooth',block:'start'});},true);
renderChildAges();initCatalogs();
})();