(function(){'use strict';
const hotelData=new Map();
const nativeFetch=window.fetch.bind(window);
function key(v){return String(v||'').trim().toLowerCase();}
function clean(v){return String(v||'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
window.fetch=async function(input,init){const response=await nativeFetch(input,init);try{const url=typeof input==='string'?input:(input&&input.url)||'';if(url.indexOf('action=search_results')!==-1){response.clone().json().then(list=>{if(!Array.isArray(list))return;list.forEach(h=>hotelData.set(key(h&&h.name),h||{}));decorateAll();}).catch(()=>{});}}catch(e){}return response;};
function mapUrl(h){const lat=Number(h.latitude||(h.common&&h.common.latitude)||0),lon=Number(h.longitude||(h.common&&h.common.longitude)||0);if(lat&&lon)return 'https://yandex.ru/maps/?pt='+encodeURIComponent(lon+','+lat)+'&z=15&l=map';return 'https://yandex.ru/maps/?text='+encodeURIComponent([h.name,h.region&&h.region.name,h.country&&h.country.name].filter(Boolean).join(', '));}
function decorate(card){if(!card||card.dataset.hotelActions==='1')return;const title=card.querySelector('.hotel-title');if(!title)return;const h=hotelData.get(key(title.textContent));if(!h)return;card.dataset.hotelActions='1';const desc=clean(h.hotelDescription||'');const actions=document.createElement('div');actions.className='hotel-actions';let html='';if(desc)html+='<button type="button" class="hotel-info-toggle">Об отеле</button>';html+='<a class="hotel-map-link" href="'+esc(mapUrl(h))+'" target="_blank" rel="noopener noreferrer">На карте</a>';actions.innerHTML=html;const main=card.querySelector('.hotel-main');if(main)main.insertAdjacentElement('afterend',actions);else card.prepend(actions);if(desc){const detail=document.createElement('div');detail.className='hotel-inline-detail';detail.hidden=true;detail.innerHTML='<div class="hotel-inline-detail-text">'+esc(desc)+'</div>';actions.insertAdjacentElement('afterend',detail);const btn=actions.querySelector('.hotel-info-toggle');btn.addEventListener('click',()=>{const open=detail.hidden;detail.hidden=!open;btn.textContent=open?'Скрыть описание':'Об отеле';});}}
function decorateAll(){document.querySelectorAll('#results .hotel-card').forEach(decorate);}
const results=document.getElementById('results');if(results)new MutationObserver(decorateAll).observe(results,{childList:true,subtree:true});document.addEventListener('DOMContentLoaded',decorateAll);
})();