<?php
require($_SERVER['DOCUMENT_ROOT'].'/bitrix/modules/main/include/prolog_before.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/site_conf.php');
require_once(__DIR__.'/assets.php');
require_once(__DIR__.'/form-defaults.php');
require_once(__DIR__.'/analytics-config.php');
require_once(__DIR__.'/privacy-config.php');
$siteParams=is_array($params??null)?$params:[];$form=v2_form_defaults($_GET,$siteParams);function e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}$from=(int)$form['from'];$country=(int)$form['country'];$metrikaCounter=v2_metrika_counter_id();$privacyUrl=v2_privacy_url();
?><!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Поиск туров — AnyTour</title><link rel="stylesheet" href="<?=e(v2_asset('app.css'))?>"><link rel="stylesheet" href="<?=e(v2_asset('enhancements.css'))?>"><link rel="stylesheet" href="<?=e(v2_asset('room-details.css'))?>"><link rel="stylesheet" href="<?=e(v2_asset('selected-tour-ux.css'))?>"><link rel="stylesheet" href="<?=e(v2_asset('design-v1.css'))?>"><link rel="stylesheet" href="<?=e(v2_asset('hotel-details-design.css'))?>"><link rel="stylesheet" href="<?=e(v2_asset('tour-design-v1.css'))?>"><link rel="stylesheet" href="<?=e(v2_asset('search-states-design.css'))?>"><link rel="stylesheet" href="<?=e(v2_asset('anytour-brand.css'))?>"><link rel="stylesheet" href="<?=e(v2_asset('anytour-results-brand.css'))?>"><link rel="stylesheet" href="<?=e(v2_asset('anytour-checkout-brand.css'))?>"><link rel="stylesheet" href="<?=e(v2_asset('header-design-v2.css'))?>"><link rel="stylesheet" href="<?=e(v2_asset('header-compact.css'))?>"></head><body>
<main class="v2-shell">
<header class="v2-head v2-head-compact"><a class="anytour-brand anytour-brand-compact" href="/" aria-label="AnyTour"><span class="anytour-logo-wrap"><img class="anytour-logo" src="<?=e(v2_asset('Layer_1.png'))?>" alt="AnyTour"></span></a><div class="compact-head-actions"><span class="compact-head-label">Поиск туров</span><a class="compact-head-cta" href="#tourSearch">Подобрать тур</a></div></header>
<form id="tourSearch" class="search-card" autocomplete="off"><?=bitrix_sessid_post()?>
<div class="search-section-title"><span>Куда и когда</span><small>Основные параметры</small></div>
<div class="main-fields">
<label class="field field-wide"><span>Вылет из</span><select name="from" data-v2-catalog="departures"><option value="<?=e($from)?>" selected>Загружаем города…</option></select></label>
<label class="field field-wide"><span>Страна</span><select name="country" data-v2-catalog="countries"><option value="<?=e($country)?>" selected>Загружаем страны…</option></select></label>
<label class="field"><span>Вылет с</span><input type="date" name="dateFrom" value="<?=e($form['date_from'])?>"></label>
<label class="field"><span>Вылет до</span><input type="date" name="dateTo" value="<?=e($form['date_till'])?>"></label>
<label class="field"><span>Ночей от</span><input type="number" min="1" max="28" name="daysFrom" value="<?=e($form['nights_from'])?>"></label>
<label class="field"><span>Ночей до</span><input type="number" min="1" max="28" name="daysTill" value="<?=e($form['nights_till'])?>"></label>
<label class="field"><span>Взрослых</span><select name="count_people"><?php for($i=1;$i<=6;$i++):?><option value="<?=$i?>" <?=$i===(int)$form['count_people']?'selected':''?>><?=$i?></option><?php endfor;?></select></label>
<label class="field"><span>Детей</span><select name="child_count" id="childCount"><option value="0" selected>Без детей</option><option value="1">1 ребёнок</option><option value="2">2 ребёнка</option><option value="3">3 ребёнка</option></select></label>
</div><div id="childAges" class="child-ages" hidden></div>
<details class="extras" open><summary>Фильтры отдыха <span>курорт, отель, питание и перелёт</span></summary><div class="extra-grid">
<label class="field"><span>Аэропорт прилёта</span><select name="arrival"><option value="">Любой аэропорт</option></select></label><label class="field"><span>Курорт / регион</span><select name="region"><option value="">Все курорты</option></select></label><label class="field"><span>Район / субкурорт</span><select name="subregion"><option value="">Все районы</option></select></label><label class="field"><span>Конкретный отель</span><select name="hotel"><option value="">Любой отель</option></select></label><label class="field"><span>Туроператор</span><select name="operator"><option value="">Все операторы</option></select></label><label class="field"><span>Тип отеля</span><select name="hotel_type"><option value="">Любой тип</option></select></label><label class="field"><span>Категория отеля</span><select name="stars"><option value="">Любая</option><option value="2">2★ и выше</option><option value="3">3★ и выше</option><option value="4">4★ и выше</option><option value="5">5★</option></select></label><label class="field"><span>Рейтинг отеля</span><select name="rating"><option value="">Любой</option><option value="2">от 3.0</option><option value="3">от 3.5</option><option value="4">от 4.0</option><option value="5">от 4.5</option></select></label><label class="field"><span>Питание</span><select name="food"><option value="">Любое</option></select></label><label class="field"><span>Цена от</span><input type="number" min="0" step="1000" name="price_from" placeholder="Например 80000"></label><label class="field"><span>Цена до</span><input type="number" min="0" step="1000" name="price_till" placeholder="Например 180000"></label><div class="field"><span>Перелёт</span><div class="toggle-row"><label class="toggle"><input type="checkbox" name="onlyDirect" value="1"><span>Прямой</span></label><label class="toggle"><input type="checkbox" name="onlyCharter" value="1"><span>Чартер</span></label></div></div></div><details class="service-picker"><summary>Услуги отеля <span id="serviceCount">не выбраны</span></summary><div id="hotelServices" class="service-groups"><div class="service-loading">Загружаем доступные услуги…</div></div></details></details>
<button class="primary search-submit" type="submit"><span>Найти туры</span><small>показать актуальные предложения</small></button></form><section id="status" class="status" hidden></section><section id="resultsTools" class="results-tools" hidden><div><strong>Предложения</strong><span id="resultSummary">Актуальные варианты</span></div><label>Сортировка <select id="sortResults"><option value="price">Сначала дешевле</option><option value="rating">По рейтингу</option><option value="stars">По звёздам</option></select></label></section><section id="results" class="results"></section><section id="selectedTour" class="selected-tour" hidden></section></main>
<script>window.V2_CONFIG={api:'/poisk-turov-test/v2/api-v2.php',leadApi:'/poisk-turov-test/v2/lead-adapter-v2.php',privacyUrl:<?=json_encode($privacyUrl,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?>,metrikaCounter:<?=json_encode($metrikaCounter,JSON_UNESCAPED_SLASHES)?>};</script><script src="<?=e(v2_asset('runtime-v3.js'))?>"></script><script src="<?=e(v2_asset('analytics-v3.js'))?>"></script><script src="<?=e(v2_asset('results-renderer-v4.js'))?>"></script><script src="<?=e(v2_asset('search-continue-v6.js'))?>"></script><script src="<?=e(v2_asset('hotel-actions-v3.js'))?>"></script><script src="<?=e(v2_asset('room-details-v2.js'))?>"></script><script src="<?=e(v2_asset('tour-controller-v4.js'))?>"></script><script src="<?=e(v2_asset('flight-price-sync-v1.js'))?>"></script><script src="<?=e(v2_asset('catalogs-v2.js'))?>"></script><script src="<?=e(v2_asset('search-lifecycle-v6.js'))?>"></script><script src="<?=e(v2_asset('accessibility.js'))?>"></script></body></html>