(function(){'use strict';
const cache=new Map(),nativeFetch=window.fetch.bind(window);
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function clean(v){return String(v||'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();}
async function api(ids){const q=new URLSearchParams({action:'rooms'});ids.forEach(id=>q.append('ids[]',String(id)));const r=await nativeFetch((window.V2_CONFIG&&window.V2_CONFIG.api||'api.php')+'?'+q.toString(),{credentials:'same-origin'}),d=await r.json().catch(()=>[]);if(!r.ok)throw new Error((d&&d.error)||('API HTTP '+r.status));return Array.isArray(d)?d:[];}
function gallery(images,name){const a=(Array.isArray(images)?images:[]).filter(Boolean).slice(0,10);if(!a.length)return'';return '<div class="room-gallery"><div class="room-gallery-main"><img src="'+esc(a[0])+'" alt="'+esc(name||'Номер')+'"></div>'+(a.length>1?'<div class="room-gallery-thumbs">'+a.map((x,i)=>'<button type="button" data-src="'+esc(x)+'" class="room-gallery-thumb'+(i?'':' is-active')+'"><img src="'+esc(x)+'" alt=""></button>').join('')+'</div>':'')+'</div>';}
function html(r){const facts=[r.area?['Площадь',r.area+' м²']:null,r.roomCount?['Комнат',r.roomCount]:null,r.bedroomCount?['Спален',r.bedroomCount]:null,r.hasBalcony?['Балкон','Есть']:null,r.hasKitchen?['Кухня','Есть']:null].filter(Boolean);return '<div class="room-detail-card">'+gallery(r.images,r.name)+'<div class="room-detail-body"><div class="section-heading"><strong>'+esc(r.name||'Описание номера')+'</strong><span>'+esc(r.location||r.viewDescription||'')+'</span></div>'+(facts.length?'<div class="room-facts">'+facts.map(x=>'<div><span>'+esc(x[0])+'</span><b>'+esc(x[1])+'</b></div>').join('')+'</div>':'')+(clean(r.description)?'<p>'+esc(clean(r.description))+'</p>':'')+(clean(r.sleepingPlaces)?'<p><b>Спальные места:</b> '+esc(clean(r.sleepingPlaces))+'</p>':'')+(clean(r.services)?'<p><b>В номере:</b> '+esc(clean(r.services))+'</p>':'')+(clean(r.comment)?'<p class="room-comment">'+esc(clean(r.comment))+'</p>':'')+'</div></div>';}
function roomIds(t){const ids=[];['roomId','roomTypeId'].forEach(k=>{const v=t&&t[k];if(Number(v)>0)ids.push(Number(v));});if(t&&t.room&&Number(t.room.id)>0)ids.push(Number(t.room.id));return [...new Set(ids)];}
async function decorate(t){const selected=document.getElementById('selectedTour');if(!selected||!t)return;const ids=roomIds(t);if(!ids.length)return;let host=selected.querySelector('.room-details-host');if(!host){host=document.createElement('div');host.className='room-details-host';const flights=selected.querySelector('.tour-flights');(flights||selected.querySelector('.lead-form')||selected).insertAdjacentElement(flights?'beforebegin':'beforebegin',host);}host.innerHTML='<div class="room-detail-loading">Загружаем описание номера…</div>';try{const missing=ids.filter(id=>!cache.has(id));if(missing.length)(await api(missing)).forEach(r=>{if(r&&r.id)cache.set(Number(r.id),r);});const rooms=ids.map(id=>cache.get(id)).filter(Boolean);host.innerHTML=rooms.length?rooms.map(html).join(''):'<div class="room-detail-loading">Для выбранного номера подробное описание не заполнено.</div>';host.querySelectorAll('.room-gallery-thumb').forEach(btn=>btn.addEventListener('click',()=>{const card=btn.closest('.room-detail-card'),main=card&&card.querySelector('.room-gallery-main img');if(main)main.src=btn.dataset.src||main.src;card&&card.querySelectorAll('.room-gallery-thumb').forEach(x=>x.classList.toggle('is-active',x===btn));}));}catch(e){host.innerHTML='<div class="room-detail-loading">Описание номера временно недоступно.</div>';}}
window.addEventListener('v2:tour-selected',e=>decorate(e.detail&&e.detail.tour));
})();