(function(){'use strict';
const cache=new Map(),nativeFetch=window.fetch.bind(window);let lastTour=null,decorateTimer=0;
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function clean(v){return String(v||'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();}
async function api(ids){const q=new URLSearchParams({action:'rooms'});ids.forEach(id=>q.append('ids[]',String(id)));const r=await nativeFetch((window.V2_CONFIG&&window.V2_CONFIG.api||'api.php')+'?'+q.toString(),{credentials:'same-origin'}),d=await r.json().catch(()=>[]);if(!r.ok)throw new Error((d&&d.error)||('API HTTP '+r.status));return Array.isArray(d)?d:[];}
window.fetch=async function(input,init){const response=await nativeFetch(input,init);try{const url=typeof input==='string'?input:(input&&input.url)||'';if(url.indexOf('action=tour')!==-1&&url.indexOf('action=tours')===-1){response.clone().json().then(t=>{if(t&&typeof t==='object'){lastTour=t;scheduleDecorate();}}).catch(()=>{});}}catch(e){}return response;};
function gallery(images,name){const a=(Array.isArray(images)?images:[]).filter(Boolean).slice(0,10);if(!a.length)return'';return '<div class="room-gallery"><div class="room-gallery-main"><img src="'+esc(a[0])+'" alt="'+esc(name||'Номер')+'" loading="lazy"></div>'+(a.length>1?'<div class="room-gallery-thumbs">'+a.map((x,i)=>'<button type="button" data-src="'+esc(x)+'" class="room-gallery-thumb'+(i?'':' is-active')+'"><img src="'+esc(x)+'" alt="" loading="lazy"></button>').join('')+'</div>':'')+'</div>';}
function html(r){const facts=[r.area?['Площадь',r.area+' м²']:null,r.roomCount?['Комнат',r.roomCount]:null,r.bedroomCount?['Спален',r.bedroomCount]:null,r.hasBalcony?['Балкон','Есть']:null,r.hasKitchen?['Кухня','Есть']:null].filter(Boolean);return '<div class="room-detail-card">'+gallery(r.images,r.name)+'<div class="room-detail-body"><div class="section-heading"><strong>'+esc(r.name||'Описание номера')+'</strong><span>'+esc(r.location||r.viewDescription||'')+'</span></div>'+(facts.length?'<div class="room-facts">'+facts.map(x=>'<div><span>'+esc(x[0])+'</span><b>'+esc(x[1])+'</b></div>').join('')+'</div>':'')+(clean(r.description)?'<p>'+esc(clean(r.description))+'</p>':'')+(clean(r.sleepingPlaces)?'<p><b>Спальные места:</b> '+esc(clean(r.sleepingPlaces))+'</p>':'')+(clean(r.services)?'<p><b>В номере:</b> '+esc(clean(r.services))+'</p>':'')+(clean(r.comment)?'<p class="room-comment">'+esc(clean(r.comment))+'</p>':'')+'</div></div>';}
function roomIds(t){const ids=[];['roomId','roomTypeId'].forEach(k=>{const v=t&&t[k];if(Number(v)>0)ids.push(Number(v));});if(t&&t.room&&Number(t.room.id)>0)ids.push(Number(t.room.id));return [...new Set(ids)];}
async function decorate(t){const selected=document.getElementById('selectedTour');if(!selected||!t||selected.hidden)return false;const flights=selected.querySelector('.tour-flights'),lead=selected.querySelector('.lead-form');if(!flights&&!lead)return false;const ids=roomIds(t);if(!ids.length)return true;let host=selected.querySelector('.room-details-host');if(!host){host=document.createElement('div');host.className='room-details-host';const anchor=flights||lead;if(anchor)anchor.insertAdjacentElement('beforebegin',host);else selected.appendChild(host);}if(host.dataset.tourId===String(t.id||'')&&host.dataset.loaded==='1')return true;host.dataset.tourId=String(t.id||'');host.dataset.loaded='0';host.innerHTML='<div class="room-detail-loading">Загружаем описание номера…</div>';try{const missing=ids.filter(id=>!cache.has(id));if(missing.length)(await api(missing)).forEach(r=>{if(r&&r.id)cache.set(Number(r.id),r);});const rooms=ids.map(id=>cache.get(id)).filter(Boolean);host.innerHTML=rooms.length?rooms.map(html).join(''):'<div class="room-detail-loading">Для выбранного номера подробное описание не заполнено.</div>';host.dataset.loaded='1';host.querySelectorAll('.room-gallery-thumb').forEach(btn=>btn.addEventListener('click',()=>{const card=btn.closest('.room-detail-card'),main=card&&card.querySelector('.room-gallery-main img');if(main)main.src=btn.dataset.src||main.src;card&&card.querySelectorAll('.room-gallery-thumb').forEach(x=>x.classList.toggle('is-active',x===btn));}));}catch(e){host.innerHTML='<div class="room-detail-loading">Описание номера временно недоступно.</div>';host.dataset.loaded='1';}return true;}
function scheduleDecorate(){if(decorateTimer)clearTimeout(decorateTimer);let tries=0;const run=async()=>{tries++;if(await decorate(lastTour))return;if(tries<20)decorateTimer=setTimeout(run,100);};decorateTimer=setTimeout(run,0);}
window.addEventListener('v2:tour-selected',e=>{lastTour=e.detail&&e.detail.tour||lastTour;scheduleDecorate();});
const selected=document.getElementById('selectedTour');if(selected)new MutationObserver(()=>{if(lastTour)scheduleDecorate();}).observe(selected,{childList:true,subtree:true});
function loadTourController(){if(document.querySelector('script[data-v2-tour-controller]'))return;const s=document.createElement('script');s.src='/poisk-turov-test/v2/tour-controller.js?v=1';s.dataset.v2TourController='1';document.body.appendChild(s);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',loadTourController,{once:true});else loadTourController();
})();