(function(){'use strict';
if(window.V2Runtime&&Number(window.V2Runtime.version||0)>=3)return;
const listeners=new Map(),state={searchId:0},baseFetch=window.fetch.bind(window),DEFAULT_TIMEOUT=48000;
const ACTION_TIMEOUTS={search_start:50000,search_continue:50000,flights:50000,search_status:48000,search_results:48000,tour:48000,hotel_details:48000,rooms:48000,departures:48000,countries:48000,arrivals:48000,regions:48000,subregions:48000,meals:48000,operators:48000,hotel_types:48000,hotel_services:48000,hotels:48000,dates:48000};
function actionFrom(input){try{const raw=typeof input==='string'?input:(input&&input.url)||'';if(!raw)return'';return new URL(raw,location.href).searchParams.get('action')||'';}catch(e){return'';}}
function timeoutFor(action,override){if(override!==undefined&&override!==null&&override!==''){const n=Number(override);return Number.isFinite(n)&&n>=0?n:(ACTION_TIMEOUTS[action]||DEFAULT_TIMEOUT);}return ACTION_TIMEOUTS[action]||DEFAULT_TIMEOUT;}
function retryPolicy(){return window.V2RetryPolicy&&typeof window.V2RetryPolicy.shouldRetry==='function'?window.V2RetryPolicy:null;}
function wait(ms){return new Promise(resolve=>setTimeout(resolve,Math.max(0,Number(ms)||0)));}
function emit(action,data,response){const set=listeners.get(action);if(!set)return;set.forEach(fn=>{try{fn(data,response);}catch(e){console.warn('V2Runtime listener',action,e);}});}
async function observedFetch(input,init){const action=actionFrom(input),response=await baseFetch(input,init);if(action){response.clone().json().then(data=>emit(action,data,response)).catch(()=>{});}return response;}
function build(action,params){const q=new URLSearchParams({action});Object.entries(params||{}).forEach(([k,v])=>{if(v===''||v===null||v===undefined)return;if(Array.isArray(v)){v.forEach(x=>{if(x!==''&&x!==null&&x!==undefined)q.append(k+'[]',String(x));});}else q.append(k,String(v));});return (window.V2_CONFIG&&window.V2_CONFIG.api||'api.php')+'?'+q.toString();}
async function requestOnce(action,url,baseOptions,timeout){const opts=Object.assign({},baseOptions),hasExternalSignal=!!opts.signal;let controller=null,timer=0;if(!hasExternalSignal&&typeof AbortController!=='undefined'&&timeout>0){controller=new AbortController();opts.signal=controller.signal;timer=setTimeout(()=>controller.abort(),timeout);}try{const r=await observedFetch(url,opts),d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d&&d.error||('API HTTP '+r.status));e.status=r.status;e.data=d;e.code='HTTP_ERROR';throw e;}return d;}catch(e){if(e&&e.name==='AbortError'){const x=new Error('Tourvisor не ответил вовремя');x.code='TIMEOUT';x.timeout=timeout;x.action=action;throw x;}if(e&&e.code)throw e;const x=e instanceof Error?e:new Error(String(e||'Network error'));x.code='NETWORK_ERROR';x.action=action;throw x;}finally{if(timer)clearTimeout(timer);}}
async function api(action,params,options){const opts=Object.assign({credentials:'same-origin'},options||{}),timeout=timeoutFor(action,opts.timeout),url=build(action,params);delete opts.timeout;let attempt=0;while(true){try{return await requestOnce(action,url,opts,timeout);}catch(e){const policy=retryPolicy();if(!policy||!policy.shouldRetry(action,e,attempt))throw e;const delay=typeof policy.delayFor==='function'?policy.delayFor(attempt):500;attempt++;await wait(delay);}}}
function on(action,fn){if(!listeners.has(action))listeners.set(action,new Set());listeners.get(action).add(fn);return()=>{const set=listeners.get(action);if(set)set.delete(fn);};}
function setSearchId(id){state.searchId=Number(id||0);}
const runtime={api,on,state,setSearchId,build,fetch:observedFetch,timeoutFor,retryPolicy,actionTimeouts:Object.assign({},ACTION_TIMEOUTS),version:3,defaultTimeout:DEFAULT_TIMEOUT};
window.V2Runtime=runtime;window.V2RuntimeV3=runtime;
})();