<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/scripts/diagnostics/andromeda_original_transport_facts.php';
$n = 0;
$check = static function(bool $condition, string $label) use (&$n): void { ++$n; if (!$condition) throw new RuntimeException('FAIL ' . $label); };
$context = ['operatorKey'=>'115','tourKey'=>'110211811','checkIn'=>'2026-09-19','nights'=>7,'adult'=>2,'child'=>0,'currency'=>'RUB'];
$read = static fn(array $p, ?array $c=null): array => AnyTourAndromedaOriginalTransportFacts::fromJson(json_encode($p, JSON_THROW_ON_ERROR), $c ?? $context);
$reject = static function(callable $call, string $label) use ($check): void { try { $call(); } catch (Throwable $e) { $check(true,$label); return; } $check(false,$label); };
$transport = ['type'=>'ttAvia','uid'=>'PRIVATE_UID','clients'=>[['name'=>'PRIVATE_NAME']], 'details'=>[['detail'=>[['markup'=>'160','currency'=>'USD']]]]];
$payload = ['claimDocument'=>[['tourKey'=>'110211811','transports'=>[['transport'=>[$transport]]]]], 'variants'=>[['transports'=>[['transport'=>[$transport]]]]], 'sid'=>'PRIVATE_SID'];
$r=$read($payload);
$check($r['transport_count']===2,'current and original alternatives');
$check(array_column($r['transports'],'scope')===['current','alternative'],'scope not mixed');
$f=$r['transports'][0]['details'][0];
$check($f['path']==='claimDocument[0].transports[0].transport[0].details[0].detail[0]','exact nested source path');
$check($f['money_fields']['markup']['value']==='160','markup preserved');
$check($f['money_fields']['currency']['value']==='USD','currency preserved');
$check($r['claim_bindings'][0]['tourKey_matches']===true,'tourKey corroborated');
$check($r['context']['nights']===7 && $r['context']['adult']===2,'PRICE context retained');
$check($r['fuel_interpretation']==='not_established' && !$r['finalPriceReady'] && !$r['arithmetic_applied'],'no fuel or final price claim');
$check(!str_contains(json_encode($r),'PRIVATE'),'no private values leaked');
$check($r['supplier_calls']===0,'pure inspection');
foreach ([0, '0', '0.00', -0.0] as $v) {
    $r=$read(['transport'=>['details'=>['markup'=>$v,'currency'=>'RUB']]]);
    $check($r['transports'][0]['details'][0]['money_fields']['markup']['state']==='reported_zero','explicit zero');
}
foreach ([true,false,'', 'not-money', '1e5'] as $v) {
    $r=$read(['transport'=>['details'=>['markup'=>$v]]]);
    $check($r['transports'][0]['details'][0]['money_fields']['markup']['state']==='invalid','invalid is not zero');
}
$r=$read(['transport'=>['details'=>['currency'=>'USD']]]);
$check($r['transports'][0]['details'][0]['money_fields']['markup']['state']==='missing','missing is not zero');
$r=$read(['transport'=>['details'=>['markup'=>null]]]);
$check($r['transports'][0]['details'][0]['money_fields']['markup']['state']==='null','null is not zero');
$r=$read(['transport'=>['type'=>'ttTrain','currency'=>'RUB','details'=>['markup'=>'-12.50']]]);
$check($r['transports'][0]['type']==='ttTrain','no ttAvia-only filter');
$check($r['transports'][0]['details'][0]['money_fields']['markup']['value']==='-12.50','signed value retained');
$check(!isset($r['transports'][0]['details'][0]['money_fields']['currency']),'no inherited currency');
$r=$read(['transport'=>['details'=>['markup'=>['amount'=>'42.50','currency'=>'EUR','uid'=>'PRIVATE_NESTED']]]]);
$m=$r['transports'][0]['details'][0]['money_fields']['markup'];
$check($m['state']==='structured' && $m['items'][0]['amount']['value']==='42.50','structured markup money retained');
$check(!str_contains(json_encode($r),'PRIVATE'),'structured markup sanitized');
$r=$read(['claimDocument'=>[['transports'=>[['transport'=>[['type'=>'ttAvia']]]]]]]);
$check(!$r['claim_bindings'][0]['tourKey_matches'],'missing claim identity not invented');
$check($r['transports'][0]['details_state']==='missing','missing detail container explicit');
$r=$read(['transport'=>['details'=>'broken']]);
$check(!$r['shape_complete'] && $r['transports'][0]['details_state']==='invalid','broken detail shape exposed');
$r=$read(['transport'=>['details'=>[['detail'=>[12,['markup'=>0,'currency'=>'RUB']]]]]]);
$check(!$r['shape_complete'] && count($r['transports'][0]['details'])===1,'malformed sibling not silently complete');
$r=$read(['transport'=>[['details'=>[]],['details'=>null]]]);
$check($r['transports'][0]['details']===[] && $r['transports'][1]['details_state']==='null','empty and null distinguished');
$reject(fn()=>$read(['claimDocument'=>[['tourKey'=>'99']]]),'mismatched tourKey blocked');
$reject(fn()=>$read(['claimDocument'=>[['operatorKey'=>'342']]]),'mismatched operator blocked');
$reject(fn()=>$read(['error'=>'PRIVATE_ERROR']),'supplier error blocked');
$reject(fn()=>$read(['transport'=>[]],array_replace($context,['checkIn'=>'2026-02-30'])),'invalid date blocked');
$reject(fn()=>$read(['transport'=>[]],array_replace($context,['adult'=>true])),'bool party blocked');
$reject(fn()=>AnyTourAndromedaOriginalTransportFacts::fromJson('{"x":}', $context),'invalid JSON blocked');
$reject(fn()=>AnyTourAndromedaOriginalTransportFacts::fromJson(str_repeat(' ',2097153),$context),'oversized input blocked');
$raw='{"transport":{"details":{"markup":0,"currency":"RUB"}}}';
$r=AnyTourAndromedaOriginalTransportFacts::fromJson($raw,$context);
$check($r['raw_reply_sha256']===hash('sha256',$raw),'exact byte provenance');
$check($r['transports'][0]['scope']==='unspecified','root selection role not guessed');
$source=file_get_contents(dirname(__DIR__).'/scripts/diagnostics/andromeda_original_transport_facts.php');
$check(!preg_match('/(?:getFlights|changeService|curl_exec|file_put_contents|fsockopen)\s*\(/',$source),'no network or mutation');
$r=$read(['transport'=>['details'=>['markup'=>0,'currency'=>'RUB','unit'=>'party','included'=>'true','quantity'=>2]]]);
$f=$r['transports'][0]['details'][0]['money_fields'];
$check($f['unit']['value']==='party' && $f['included']['value']==='true','reported unit and inclusion retained');
$check($f['quantity']['value']==='2','quantity retained without multiplication');
$r=$read(['transport'=>['details'=>['markup'=>0,'unit'=>'PRIVATE_UNIT']]]);
$check($r['transports'][0]['details'][0]['money_fields']['unit']['state']==='unrecognized','unknown unit not guessed');
$reject(fn()=>$read(['claimDocument'=>[['checkIn'=>'2026-09-20']]]),'date mismatch blocked');
$reject(fn()=>$read(['claimDocument'=>[['nights'=>8]]]),'nights mismatch blocked');
$reject(fn()=>$read(['claimDocument'=>[['adult'=>3]]]),'party mismatch blocked');
$reject(fn()=>$read(['claimDocument'=>[['child'=>true]]]),'boolean context echo rejected');
echo 'ANDROMEDA_ORIGINAL_TRANSPORT_FACTS_OK checks='.$n.PHP_EOL;
