<?php
declare(strict_types=1);
require_once __DIR__.'/../scripts/catalog/anytour_offer_scope_index_install_v1.php';
function scope_need(bool $ok,string $label):void{if(!$ok)throw new RuntimeException('CHECK_FAILED:'.$label);}
function scope_sql(PDO $pdo,string $path):void{$raw=(string)file_get_contents($path);$raw=preg_replace('/^\s*--.*$/m','',$raw);foreach(array_filter(array_map('trim',explode(';',(string)$raw))) as $sql)$pdo->exec($sql);}
function scope_expect(callable $fn,string $needle,string $label):void{try{$fn();}catch(Throwable $e){scope_need(str_contains($e->getMessage(),$needle),$label.':'.$e->getMessage());return;}throw new RuntimeException('CHECK_FAILED:'.$label.':no_error');}
$dsn=(string)getenv('ANYTOUR_SCOPE_INDEX_TEST_DSN');$password=(string)getenv('ANYTOUR_SCOPE_INDEX_TEST_PASSWORD');if(!str_starts_with($dsn,'mysql:'))throw new RuntimeException('fixture DSN required');
$pdo=new PDO($dsn,'root',$password,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_EMULATE_PREPARES=>false,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
$pdo->exec('SET FOREIGN_KEY_CHECKS=0');foreach(['anytour_offer_scopes','anytour_offers','anytour_offer_scope_state','anytour_offer_refreshes','anytour_offer_store_control','anytour_hotel_sources','anytour_hotels','anytour_catalog_control'] as $t)$pdo->exec("DROP TABLE IF EXISTS `$t`");$pdo->exec('SET FOREIGN_KEY_CHECKS=1');
scope_sql($pdo,__DIR__.'/../v2/data/migrations/20260916-anytour-canonical-catalog.sql');scope_sql($pdo,__DIR__.'/../v2/data/migrations/20260916-anytour-offer-store.sql');scope_sql($pdo,__DIR__.'/../v2/data/migrations/20260917-anytour-offer-store-v2.sql');
$profile='{"name":"Fixture"}';$pdo->prepare('INSERT INTO anytour_hotels(profile_json,profile_sha256,created_at,updated_at) VALUES(?,?,UTC_TIMESTAMP(),UTC_TIMESTAMP())')->execute([$profile,hash('sha256',$profile)]);$hotel=(int)$pdo->lastInsertId();$source='{"fixture":true}';$pdo->prepare("INSERT INTO anytour_hotel_sources(namespace,external_key,anytour_hotel_id,acquired_via,source_json,source_sha256,first_seen_at,last_seen_at) VALUES('legacy_catalog','101',?,'fixture',?,?,UTC_TIMESTAMP(),UTC_TIMESTAMP())")->execute([$hotel,$source,hash('sha256',$source)]);
$d=str_repeat('a',64);$token=str_repeat('b',64);$pdo->prepare("INSERT INTO anytour_offer_refreshes(refresh_token,provider,scope_sha256,status,started_at,lease_expires_at,completed_at) VALUES(?, 'tourvisor', ?, 'complete', UTC_TIMESTAMP(), DATE_ADD(UTC_TIMESTAMP(),INTERVAL 5 MINUTE), UTC_TIMESTAMP())")->execute([$token,$d]);$pdo->prepare("INSERT INTO anytour_offer_scope_state(provider,scope_sha256,active_refresh_token,latest_complete_refresh_token,revision,updated_at) VALUES('tourvisor',?,NULL,?,1,UTC_TIMESTAMP())")->execute([$d,$token]);
$before=anytour_scope_index_existing_counts($pdo);scope_need($before['anytour_offer_refreshes']===1&&$before['anytour_offer_scope_state']===1,'nonempty existing state');
$states=[];$result=anytour_scope_index_install($pdo,static function(array $s)use(&$states):void{$states[]=$s;});
scope_need($result['status']==='scope_index_installed_verified'&&$result['offerStoreSchemaVersion']===2,'installed');scope_need($result['existingCounts']===$before,'existing counts unchanged');scope_need($result['catalogCounts']===['activeHotels'=>1,'sourceLinks'=>1],'catalog unchanged');scope_need($result['scopeIndexRows']===0&&$result['oldScopeBackfill']===0,'no backfill');scope_need(anytour_scope_index_schema_valid(anytour_scope_index_schema($pdo)),'exact schema');scope_need(array_column($states,'status')===['verified_before_ddl','ddl_attempting','ddl_completed'],'durable phase hooks');
scope_expect(fn()=>anytour_scope_index_install($pdo,static function(array $s):void{}),'already exists','replay refused');
$pdo->exec('DROP TABLE anytour_offer_scopes');$pdo->exec('CREATE TABLE anytour_offer_scopes(scope_sha256 CHAR(64) PRIMARY KEY) ENGINE=InnoDB');scope_expect(fn()=>anytour_scope_index_install($pdo,static function(array $s):void{}),'already exists','partial table refused');
$pdo->exec('DROP TABLE anytour_offer_scopes');scope_need(str_starts_with(anytour_scope_index_statement(),'CREATE TABLE IF NOT EXISTS anytour_offer_scopes'),'pinned one statement');
echo "ANYTOUR_SCOPE_INDEX_INSTALL_OK schema=2 refreshes=1 states=1 backfill=0 replay_refused=1 partial_refused=1\n";
