<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/scripts/diagnostics/hotel_match_live30_common4_anex_writer_v5.php';
$dsn=getenv('MATCH_ANEX_WRITER_TEST_DSN');if($dsn!=='mysql:host=127.0.0.1;port=3306;dbname=match_anex_writer;charset=utf8mb4')throw new RuntimeException('isolated_mysql_required');
$db=new PDO($dsn,'root','root',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
function awok(bool $v,string $m):void{if(!$v)throw new RuntimeException($m);}
function awtarget(int $id):array{return ['id'=>$id,'name'=>'HOTEL '.$id,'country_id'=>4,'country_name'=>'Турция','region_id'=>20,'region_name'=>'Сиде','subregion_id'=>200,'subregion_name'=>'Сиде','category'=>'5','is_active'=>1];}
function awanchor(int $id):array{$ej=hmc4aw_json(['tv'=>$id]);return ['supplier_namespace'=>'andromeda_catalog','external_hotel_id'=>(string)(900000+$id),'local_hotel_id'=>$id,'decision_status'=>'accepted','catalog_sha256'=>hash('sha256','cat-'.$id),'evidence_sha256'=>hash('sha256',$ej),'evidence_json'=>$ej];}
function awmanifest():array{$out=[];for($i=1;$i<=5;$i++){$tv=1000+$i;$a=awanchor($tv);$out[]=['anex_hotel_id'=>(string)(30000+$i),'catalog_hotel_id'=>$tv,'source_operation'=>'child','source_result_sha256'=>str_repeat('a',64),'batch'=>1,'search_id_sha256'=>str_repeat('b',64),'tour_id_sha256'=>str_repeat('c',64),'operator_link_sha256'=>str_repeat('d',64),'operator_link_host'=>'agent.anextour.ru','query_keys'=>['hotellist'],'target'=>awtarget($tv),'unanimous_catalog_sha256'=>$a['catalog_sha256'],'anchors'=>hmc4aw_anchor_list([$a])];}return $out;}
function awseed(PDO $db):void{
 foreach(['anex_search_hotel_observations','anex_review_pair_exclusions','anex_hotel_decisions','anex_hotel_search_mappings','andromeda_hotel_identities','catalog_hotels'] as $t)$db->exec("DELETE FROM $t");
 $h=$db->prepare('INSERT INTO catalog_hotels VALUES(?,?,?,?,?,?,?,?,?,1)');$a=$db->prepare('INSERT INTO andromeda_hotel_identities(supplier_namespace,external_hotel_id,local_hotel_id,decision_status,catalog_sha256,evidence_sha256,evidence_json) VALUES(?,?,?,?,?,?,?)');
 foreach(awmanifest() as $m){$t=$m['target'];$h->execute([$t['id'],$t['name'],$t['country_id'],$t['country_name'],$t['region_id'],$t['region_name'],$t['subregion_id'],$t['subregion_name'],$t['category']]);$x=awanchor($m['catalog_hotel_id']);$a->execute([$x['supplier_namespace'],$x['external_hotel_id'],$x['local_hotel_id'],$x['decision_status'],$x['catalog_sha256'],$x['evidence_sha256'],$x['evidence_json']]);}
}
try{
 foreach(['anex_search_hotel_observations','anex_review_pair_exclusions','anex_hotel_decisions','anex_hotel_search_mappings','andromeda_hotel_identities','catalog_hotels'] as $t)$db->exec("DROP TABLE IF EXISTS $t");
 $db->exec("CREATE TABLE catalog_hotels(id INT PRIMARY KEY,name VARCHAR(500),country_id INT,country_name VARCHAR(100),region_id INT NULL,region_name VARCHAR(200),subregion_id INT NULL,subregion_name VARCHAR(200) NULL,category VARCHAR(20),is_active TINYINT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 $db->exec("CREATE TABLE andromeda_hotel_identities(supplier_namespace VARCHAR(40),external_hotel_id VARCHAR(32),local_hotel_id INT NULL,decision_status VARCHAR(16),catalog_sha256 CHAR(64),evidence_sha256 CHAR(64),evidence_json MEDIUMTEXT,PRIMARY KEY(supplier_namespace,external_hotel_id),KEY(local_hotel_id)) ENGINE=InnoDB");
 $db->exec("CREATE TABLE anex_hotel_search_mappings(anex_hotel_id BIGINT PRIMARY KEY,catalog_hotel_id INT,match_class VARCHAR(64),scope VARCHAR(32),approval_policy VARCHAR(100),source_row_digest CHAR(64),mapping_digest CHAR(64),enabled TINYINT) ENGINE=InnoDB");
 $db->exec("CREATE TABLE anex_hotel_decisions(anex_hotel_id BIGINT PRIMARY KEY,decision_status VARCHAR(32),catalog_hotel_id INT NULL) ENGINE=InnoDB");
 $db->exec("CREATE TABLE anex_review_pair_exclusions(anex_hotel_id BIGINT,catalog_hotel_id INT,PRIMARY KEY(anex_hotel_id,catalog_hotel_id)) ENGINE=InnoDB");
 $db->exec("CREATE TABLE anex_search_hotel_observations(anex_hotel_id BIGINT PRIMARY KEY) ENGINE=InnoDB");
 awseed($db);$m=awmanifest();$r=hmc4aw_write($db,$m,str_repeat('1',40),null);awok($r['state']==='committed_verified'&&$r['inserted']===5&&$r['registry_readback_verified'],'commit');
 $reg=AnyTourAnexSearchMappingRegistry::fromPdo($db);foreach($m as $x)awok($reg->resolve('anex_online',$x['anex_hotel_id'],'preview')===$x['catalog_hotel_id'],'registry');
 $replay=false;try{hmc4aw_write($db,$m,str_repeat('1',40),null);}catch(RuntimeException $e){$replay=str_contains($e->getMessage(),'source_mapping_present');}awok($replay,'replay');
 awseed($db);$db->exec("INSERT INTO anex_hotel_decisions VALUES(30001,'rejected',NULL)");$ok=false;try{hmc4aw_write($db,$m,str_repeat('1',40),null);}catch(RuntimeException $e){$ok=str_contains($e->getMessage(),'manual_source_protected');}awok($ok&&(int)$db->query('SELECT COUNT(*) FROM anex_hotel_search_mappings')->fetchColumn()===0,'manual_rollback');
 awseed($db);$db->exec("INSERT INTO anex_review_pair_exclusions VALUES(30001,1001)");$ok=false;try{hmc4aw_write($db,$m,str_repeat('1',40),null);}catch(RuntimeException $e){$ok=str_contains($e->getMessage(),'pair_excluded');}awok($ok&&(int)$db->query('SELECT COUNT(*) FROM anex_hotel_search_mappings')->fetchColumn()===0,'exclusion_rollback');
 awseed($db);$db->exec("UPDATE andromeda_hotel_identities SET evidence_sha256=REPEAT('f',64) WHERE local_hotel_id=1001");$ok=false;try{hmc4aw_write($db,$m,str_repeat('1',40),null);}catch(RuntimeException $e){$ok=str_contains($e->getMessage(),'anchor_evidence_hash_drift');}awok($ok&&(int)$db->query('SELECT COUNT(*) FROM anex_hotel_search_mappings')->fetchColumn()===0,'anchor_rollback');
 awseed($db);$db->exec("CREATE TRIGGER reject_last BEFORE INSERT ON anex_hotel_search_mappings FOR EACH ROW BEGIN IF NEW.anex_hotel_id=30005 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='late'; END IF; END");$ok=false;try{hmc4aw_write($db,$m,str_repeat('1',40),null);}catch(RuntimeException $e){$ok=str_starts_with($e->getMessage(),'rolled_back_no_write:');}awok($ok&&(int)$db->query('SELECT COUNT(*) FROM anex_hotel_search_mappings')->fetchColumn()===0,'atomic');$db->exec('DROP TRIGGER reject_last');
 echo json_encode(['status'=>'passed','rows'=>5,'supplier_calls'=>0,'production_writes'=>0]),PHP_EOL;
}finally{if($db->inTransaction())$db->rollBack();foreach(['anex_search_hotel_observations','anex_review_pair_exclusions','anex_hotel_decisions','anex_hotel_search_mappings','andromeda_hotel_identities','catalog_hotels'] as $t)$db->exec("DROP TABLE IF EXISTS $t");}
