<?php
declare(strict_types=1);
require_once __DIR__.'/../scripts/diagnostics/hotel_match_live30_raw_operator_bridge_v79.php';
$n=0;function ck79(bool $b,string $s):void{global$n;$n++;if(!$b)throw new RuntimeException('test_'.$s);}
function fixture79():array{
 $idx=[];$hot=[];$entries=[];
 foreach(['operator_5','operator_115','operator_315','operator_342']as$i=>$ns){$id=$i+101;$cat=(string)($i+201);$native=(string)($i+301);$source=['schema'=>'operator-original-price-bridge/1','country_id'=>4,'source'=>['id'=>$native,'operator_key'=>substr($ns,9)],'operation_id'=>'hotel-match-operator-original-store-1971-20260915-v2','source_operation_id'=>'hotel-match-operator-original-batch-1971-20260915-v2','source_result_sha256'=>'f379062abd43c36e6feb792f8e0313466ddd579a1959cfe814e90b863a43968e','catalog_reference_kind'=>'price_capture','decision'=>['state'=>'pending','local_hotel_id'=>null,'country_id'=>4,'anchors'=>[],'reason'=>'no_anchor'],'provider_bridges'=>[]];$raw=o79_json(['source'=>'approved_fixture']);
  $anchor=['supplier_namespace'=>'andromeda_catalog','external_hotel_id'=>$cat,'local_hotel_id'=>$id,'decision_status'=>'accepted','catalog_sha256'=>str_repeat('c',64),'evidence_sha256'=>hash('sha256',$raw),'evidence_json'=>$raw];$idx['andromeda_catalog|'.$cat]=$anchor;$key=$ns.'|'.$native;$old=null;
  if($i>=2){$raw=o79_json($source);$old=['supplier_namespace'=>$ns,'external_hotel_id'=>$native,'local_hotel_id'=>null,'decision_status'=>'pending','catalog_sha256'=>str_repeat('d',64),'evidence_sha256'=>hash('sha256',$raw),'evidence_json'=>$raw];$idx[$key]=$old;}
  $entries[$key]=['key'=>$key,'ns'=>$ns,'native'=>$native,'catalog_id'=>$cat,'id'=>$id,'anchor'=>o79_pin($anchor),'prior'=>$old?o79_pin($old):null,'holds'=>[],'proof'=>['source_file'=>'fixture-only','sha256'=>str_repeat('a',64),'json_pointer'=>'/PRICES/0'],'live_proof'=>[]];$hot[$id]=['id'=>$id,'name'=>'Fixture '.$id,'country_name'=>'Турция','category'=>4,'is_active'=>1];
 }return[$entries,$idx,$hot];
}
[$en,$idx,$hot]=fixture79();$keys=array_keys($en);$e=$en[$keys[0]];
foreach($en as$k=>$x)ck79(o79_classify($x,$idx,$hot,[],[])['status']===(isset($idx[$k])?'update':'insert'),'eligible_'.$k);
$r=['hotelKey'=>201,'operatorKey'=>5,'original'=>['operatorKey'=>5,'hotelKey'=>301]];ck79(o79_fact($r,'201','operator_5','301'),'exact_raw');ck79(!o79_fact($r,'201','anex','301'),'no_direct_anex_namespace');ck79(!o79_fact($r,'201','operator_115','301'),'operator_mismatch');$r['isOperatorHotelKey']=true;ck79(!o79_fact($r,'201','operator_5','301'),'operator_key_not_canonical');$r['isOperatorHotelKey']=false;$r['original']['operatorKey']=315;ck79(!o79_fact($r,'201','operator_5','301'),'original_operator_mismatch');
foreach(['anchor_drift','manual','excluded','inactive','country','raw_missing','source_occupied','source_appeared']as$mode){$a=$idx;$h=$hot;$x=$e;$m=[];$ex=[];switch($mode){case'anchor_drift':$a['andromeda_catalog|201']['local_hotel_id']=999;break;case'manual':$m[101]=true;break;case'excluded':$ex[101]=true;break;case'inactive':$h[101]['is_active']=0;break;case'country':$h[101]['country_name']='Россия';break;case'raw_missing':$x['proof']=null;break;case'source_occupied':case'source_appeared':$a[$keys[0]]=$idx['andromeda_catalog|201'];$a[$keys[0]]['supplier_namespace']='operator_5';$a[$keys[0]]['external_hotel_id']='301';$a[$keys[0]]['local_hotel_id']=999;break;}ck79(o79_classify($x,$a,$h,$m,$ex)['status']==='hold',$mode);}
$old=$idx[$keys[2]];ck79(o79_auto($old),'automatic_import');$ev=json_decode($old['evidence_json'],true);$ev['decision']['manual']=true;$old['evidence_json']=o79_json($ev);$old['evidence_sha256']=hash('sha256',$old['evidence_json']);ck79(!o79_auto($old),'nested_manual_marker');$old=$idx[$keys[2]];$old['evidence_sha256']=str_repeat('0',64);ck79(!o79_auto($old),'bad_evidence_digest');
ck79(o79_pointer(['PRICES'=>[['hotelKey'=>201]]],'/PRICES/0')===['hotelKey'=>201],'json_pointer');
echo 'PURE_ASSERTIONS='.$n."\n";
if(getenv('MATCH79_TEST_DSN')){
 ck79(getenv('GITHUB_ACTIONS')==='true','hosted_only');$db=new PDO(getenv('MATCH79_TEST_DSN'),'root','match79-test',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);ck79($db->query('SELECT DATABASE()')->fetchColumn()==='match79_test','test_database');
 foreach(['andromeda_hotel_identities','catalog_hotels','anex_hotel_decisions','anex_review_pair_exclusions']as$t)$db->exec('DROP TABLE IF EXISTS '.$t);
 $db->exec("CREATE TABLE andromeda_hotel_identities(supplier_namespace VARCHAR(80) NOT NULL,external_hotel_id VARCHAR(80) NOT NULL,local_hotel_id INT NULL,decision_status VARCHAR(20) NOT NULL,catalog_sha256 CHAR(64) NOT NULL,evidence_sha256 CHAR(64) NOT NULL,evidence_json LONGTEXT NOT NULL,PRIMARY KEY(supplier_namespace,external_hotel_id)) ENGINE=InnoDB");
 $db->exec('CREATE TABLE catalog_hotels(id INT PRIMARY KEY,name VARCHAR(240),country_name VARCHAR(100),category INT,is_active INT) ENGINE=InnoDB');foreach(['anex_hotel_decisions','anex_review_pair_exclusions']as$t)$db->exec('CREATE TABLE '.$t.'(catalog_hotel_id INT PRIMARY KEY) ENGINE=InnoDB');
 $seed=function()use($db,$idx,$hot){foreach(['andromeda_hotel_identities','catalog_hotels','anex_hotel_decisions','anex_review_pair_exclusions']as$t)$db->exec('DELETE FROM '.$t);foreach($idx as$r)$db->prepare('INSERT INTO andromeda_hotel_identities VALUES(?,?,?,?,?,?,?)')->execute(array_values($r));foreach($hot as$r)$db->prepare('INSERT INTO catalog_hotels VALUES(?,?,?,?,?)')->execute(array_values($r));};
 $run=function()use($db,$en){$d=sys_get_temp_dir().'/match79-'.bin2hex(random_bytes(5));mkdir($d,0700);return o79_execute($db,$en,str_repeat('a',40),$d);};
 $seed();$before=$db->query('SELECT * FROM andromeda_hotel_identities ORDER BY supplier_namespace,external_hotel_id')->fetchAll(PDO::FETCH_ASSOC);$db->exec("CREATE TRIGGER fail_last BEFORE UPDATE ON andromeda_hotel_identities FOR EACH ROW BEGIN IF NEW.supplier_namespace='operator_342' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='fixture_late_error'; END IF; END");$r=$run();ck79($r['state']==='rolled_back_no_writes'&&$r['database_writes']===0,'late_error_rolls_back_inserts_and_updates');ck79($db->query('SELECT * FROM andromeda_hotel_identities ORDER BY supplier_namespace,external_hotel_id')->fetchAll(PDO::FETCH_ASSOC)===$before,'rollback_preserves_every_row');$db->exec('DROP TRIGGER fail_last');
 $r=$run();ck79($r['state']==='committed_readback_verified'&&$r['database_writes']===4&&$r['inserted']===2&&$r['updated']===2,'mixed_commit');ck79($r['primary_identities_unchanged']&&$r['unrelated_identities_unchanged']&&$r['prior_evidence_preserved'],'primary_and_history_preserved');$r=$run();ck79($r['state']==='completed_no_new_writes'&&count($r['already'])===4,'idempotent_noop');
 $seed();$db->exec('INSERT INTO anex_hotel_decisions VALUES(101)');$r=$run();ck79($r['database_writes']===3&&count($r['held'])===1,'manual_row_isolated');
 $seed();$db->exec("UPDATE andromeda_hotel_identities SET local_hotel_id=999,decision_status='accepted' WHERE supplier_namespace='operator_315'");$r=$run();ck79($r['database_writes']===3&&count($r['held'])===1,'foreign_operator_isolated');ck79((int)$db->query("SELECT local_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace='operator_315'")->fetchColumn()===999,'foreign_operator_preserved');
 $seed();$db->exec("UPDATE andromeda_hotel_identities SET local_hotel_id=999 WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id='201'");$r=$run();ck79($r['database_writes']===3&&count($r['held'])===1,'anchor_drift_isolated');
 echo 'WITH_MYSQL_ASSERTIONS='.$n."\n";
}
