<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/scripts/diagnostics/hotel_match_tv_live30_target_catalog_v2.php';
$checks=0;
function tcv2check(bool $ok,string $name): void {global $checks;++$checks;if(!$ok)throw new RuntimeException('target_catalog_v2_test:'.$name);}
tcv2check(TC30V2_OP==='int-andromeda-match-live30-target-catalog-v2-20261001-v1','fixed_operation');
tcv2check(tc30v2_reasons(['name'=>'GOOD','latitude'=>36.8,'longitude'=>31.3],[])===[],'valid_row');
tcv2check(tc30v2_reasons(['name'=>'BAD','latitude'=>91,'longitude'=>31.3],[])===['invalid_coordinates'],'coordinate_hold');
tcv2check(tc30v2_reasons(['name'=>'https://bad','latitude'=>36.8,'longitude'=>31.3],[])===['invalid_text'],'text_hold');
echo 'TV_TARGET_CATALOG_V2_PURE_PASS '.$checks."\n";
if(getenv('MATCH_TV_CATALOG_V2_MYSQL_TEST')!=='1')exit(0);
$db=new PDO('mysql:host=127.0.0.1;port=33306;dbname=match_primary_fixture;charset=utf8mb4','root','match-fixture-only',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
$tables=['catalog_hotels','tour_operator_identity_observations','andromeda_hotel_identities','anex_hotel_decisions','anex_review_pair_exclusions'];foreach($tables as $table)$db->exec('DROP TABLE IF EXISTS '.$table);
$db->exec('CREATE TABLE catalog_hotels (id BIGINT PRIMARY KEY,name VARCHAR(600),country_id INT,country_name VARCHAR(600),region_name VARCHAR(600),subregion_name VARCHAR(600),category INT,is_active INT,latitude DOUBLE NULL,longitude DOUBLE NULL) ENGINE=InnoDB');
$db->exec('CREATE TABLE tour_operator_identity_observations (hotel_id BIGINT,last_seen_at DATETIME) ENGINE=InnoDB');
$db->exec('CREATE TABLE andromeda_hotel_identities (supplier_namespace VARCHAR(64),external_hotel_id VARCHAR(64),local_hotel_id BIGINT NULL,decision_status VARCHAR(32)) ENGINE=InnoDB');
$db->exec('CREATE TABLE anex_hotel_decisions (catalog_hotel_id BIGINT NULL) ENGINE=InnoDB');
$db->exec('CREATE TABLE anex_review_pair_exclusions (catalog_hotel_id BIGINT NULL) ENGINE=InnoDB');
$db->exec("INSERT INTO catalog_hotels VALUES (1,'GOOD HOTEL',4,'Турция','Сиде',NULL,4,1,36.8,31.3),(2,'BAD GEO',4,'Турция','Сиде',NULL,4,1,91,31.3),(3,'OLD',4,'Турция','Сиде',NULL,4,1,36.8,31.3)");
$db->exec("INSERT INTO tour_operator_identity_observations VALUES (1,UTC_TIMESTAMP()),(2,UTC_TIMESTAMP()),(3,DATE_SUB(UTC_TIMESTAMP(),INTERVAL 31 DAY))");
$db->exec("INSERT INTO andromeda_hotel_identities VALUES ('andromeda_catalog','9501',1,'accepted')");
$db->exec('INSERT INTO anex_hotel_decisions VALUES (1)');$db->exec('INSERT INTO anex_review_pair_exclusions VALUES (2)');
$before=[];foreach($tables as $table)$before[$table]=$db->query('SELECT * FROM '.$table)->fetchAll(PDO::FETCH_ASSOC);
$out=tc30v2_current($db);
tcv2check($out['cohort_count']===2&&count($out['rows'])===1&&count($out['held'])===1,'complete_partition');
tcv2check($out['rows'][0]['id']===1&&$out['rows'][0]['accepted_samo_ids']===['9501']&&$out['rows'][0]['manual_hold']===true,'valid_projection');
tcv2check($out['held'][0]===['id'=>2,'reasons'=>['invalid_coordinates']],'strict_hold');
tcv2check(!$db->inTransaction(),'read_transaction_closed');
foreach($tables as $table)tcv2check($before[$table]===$db->query('SELECT * FROM '.$table)->fetchAll(PDO::FETCH_ASSOC),'rows_unchanged_'.$table);
echo 'TV_TARGET_CATALOG_V2_MYSQL_PASS '.$checks."\n";
