<?php
declare(strict_types=1);
require_once __DIR__.'/../scripts/diagnostics/hotel_match_result28_v95.php';
$n94=0;function t94(bool$b,string$m):void{global$n94;$n94++;if(!$b)throw new RuntimeException('test_'.$m);}
function d94():string{$d=sys_get_temp_dir().'/match94-'.bin2hex(random_bytes(8));w76_need(mkdir($d,0700),'fixture_dir');return$d;}
function e94(int$id,int$op,string$n):array{return['tv_hotel_id'=>$id,'operator_id'=>$op,'namespace'=>$op===43?'operator_342':'anex','positive_native_candidates'=>[$n],'state'=>'detail_identity_verified','link_state'=>'captured_single_native','search_id_sha256'=>str_repeat('a',64),'tour_id_sha256'=>str_repeat('b',64),'operator_link_sha256'=>str_repeat('c',64),'operator_link_host'=>$op===43?'searchtour.intourist.ru':'agent.anextour.ru','query_keys'=>[$op===43?'hotels':'HOTELLIST']];}
$root=d94();mkdir($root.'/hotel-match-fixture');$path=$root.'/hotel-match-fixture/raw-proof.json';$raw=['PRICES'=>[['hotelKey'=>501,'operatorKey'=>342,'original'=>['operatorKey'=>342,'hotelKey'=>701]],['hotelKey'=>502,'operatorKey'=>342,'original'=>['operatorKey'=>342,'hotelKey'=>702]]]];file_put_contents($path,w76_json($raw));$rawSha=hash_file('sha256',$path);
$hot=[];$src=[];foreach([1=>'Unique Alpha Palace',2=>'Unique Beta Palace',3=>'Unique Gamma Palace']as$id=>$name){$hot[$id]=['id'=>$id,'name'=>$name,'country_id'=>4,'country_name'=>'Турция','region_name'=>'Стамбул','subregion_name'=>'','category'=>4,'is_active'=>1,'latitude'=>null,'longitude'=>null];if($id===3)continue;$cat=(string)(500+$id);$j=w76_json(['source'=>['id'=>$cat,'name'=>$name,'state'=>'Турция','town'=>'Фатих','starKey'=>4],'reason'=>'no_unique_country_name']);$src[$cat]=['supplier_namespace'=>'andromeda_catalog','external_hotel_id'=>$cat,'local_hotel_id'=>null,'decision_status'=>'pending','catalog_sha256'=>str_repeat('d',64),'evidence_sha256'=>hash('sha256',$j),'evidence_json'=>$j];}
$v=['native_facts'=>[],'current_identities'=>array_values($src)];foreach([501,502]as$i=>$cat)$v['native_facts'][]=['catalog_id'=>(string)$cat,'supplier_namespace'=>'operator_342','native_id'=>(string)(701+$i),'evidence'=>[['source_file'=>'operations/hotel-match-fixture/raw-proof.json','sha256'=>$rawSha,'json_pointer'=>'/PRICES/'.$i]]];
$p=w84_bind([e94(1,43,'701'),e94(2,43,'702'),e94(3,13,'303')],$v,$root);$co=['source_ids'=>['501'=>time(),'502'=>time(),'599'=>time()],'complete'=>true,'cohort_completed_at_utc'=>gmdate('c')];
$c=['sources'=>[],'targets'=>[],'operators'=>[],'hotels'=>$hot,'live'=>[1=>true,2=>true,3=>true],'manual'=>[],'exclusions'=>[]];foreach($src as$cat=>$r)$c['sources'][$cat]=[$r];
t94(count(M95_ANEX)===22&&count(M95_SAMO)===6,'bounded47');t94(!isset(M95_SAMO[144804])&&!isset(M95_ANEX[928]),'excluded_scope');t94(count($p['candidates'])===2&&count($p['direct'])===1,'fixture_binding');
foreach($p['candidates']as$e)t94(m94_classify($e,$c,$co)['status']==='ready','one_operator_enough');
$bad=$p['candidates'][0];$bad['proofs']=[];t94(m94_classify($bad,$c,$co)['status']==='hold','proof_required');$bad=$p['candidates'][0];$bad['expected_name']='Wrong';t94(m94_classify($bad,$c,$co)['status']==='hold','pinned_target_name');
foreach(['category','country','name','manual','excluded','occupied','hash','source_id','source_drift','inactive']as$case){$cc=$c;$e=$p['candidates'][0];if($case==='category')$cc['hotels'][1]['category']=5;if($case==='country')$cc['hotels'][1]['country_name']='Египет';if($case==='name')$cc['hotels'][1]['name']='Different Building';if($case==='manual')$cc['manual'][1]=true;if($case==='excluded')$cc['exclusions'][1]=true;if($case==='occupied'){$cc['sources']['501'][0]['decision_status']='accepted';$cc['sources']['501'][0]['local_hotel_id']=999;}if($case==='hash')$cc['sources']['501'][0]['evidence_sha256']=str_repeat('0',64);if($case==='source_id'){$j=json_decode($cc['sources']['501'][0]['evidence_json'],true);$j['source']['id']='999';$b=w76_json($j);$cc['sources']['501'][0]['evidence_json']=$b;$cc['sources']['501'][0]['evidence_sha256']=hash('sha256',$b);}if($case==='source_drift')$e['prior_scan']['catalog_sha256']=str_repeat('f',64);if($case==='inactive')$cc['hotels'][1]['is_active']=0;t94(m94_classify($e,$cc,$co)['status']==='hold',$case);}
$legacy=$src['501'];$j=json_decode($legacy['evidence_json'],true);$j+=['candidate_ids'=>[],'geography'=>['status'=>'unknown'],'operation_id'=>'andromeda-1759-country6-20260910-v1','target_name'=>null];$j['reason']='no_unique_name';$legacy['evidence_json']=w76_json($j);$legacy['evidence_sha256']=hash('sha256',$legacy['evidence_json']);$cc=$c;$cc['sources']['501']=[$legacy];$e=$p['candidates'][0];$e['prior_scan']=$legacy;t94(m94_classify($e,$cc,$co)['status']==='ready','exact_legacy_auto');$cc['manual'][1]=true;t94(m94_classify($e,$cc,$co)['status']==='hold','legacy_does_not_override_manual');$cc=$c;$j['manual']=true;$legacy['evidence_json']=w76_json($j);$legacy['evidence_sha256']=hash('sha256',$legacy['evidence_json']);$cc['sources']['501']=[$legacy];$e['prior_scan']=$legacy;t94(m94_classify($e,$cc,$co)['status']==='hold','unknown_origin_protected');
$bad=$v;$f=$bad['native_facts'][0];$f['catalog_id']='999';$bad['native_facts'][]=$f;$mix=w84_bind([e94(1,43,'701'),e94(2,43,'702')],$bad,$root);t94(count($mix['candidates'])===1&&count($mix['held'])===1,'samo_collision_isolated');$mix=w84_bind([e94(1,43,'701'),e94(9,43,'701'),e94(2,43,'702')],$v,$root);t94(count($mix['candidates'])===1&&count($mix['held'])===2,'tv_collision_isolated');
$edge=e94(1,43,'701');$doc=['provider_calls'=>1,'database_writes'=>0,'mapping_writes'=>0,'edges'=>[$edge]];t94(m94_result_edge($doc,$edge)===0,'pinned_raw_result_binding');
foreach(['tamper','duplicate','not_acquisition']as$case){$j=$doc;$x=$edge;if($case==='tamper')$x['operator_link_sha256']=str_repeat('e',64);if($case==='duplicate')$j['edges'][]=$edge;if($case==='not_acquisition')$j['provider_calls']=0;try{m94_result_edge($j,$x);t94(false,'bad_authority');}catch(RuntimeException$e){t94(in_array($e->getMessage(),['raw_edge_result_binding','tv_result_not_acquisition'],true),'reject_'.$case);}}
$idx=['by_native'=>[],'by_hotel'=>[],'edges'=>[],'rejected'=>[]];$doc['operation']='hotel-match-fixture';m95_index_doc($doc,'hotel-match-fixture',str_repeat('a',64),$idx);t94(isset($idx['edges'][1][43]['701']),'result_without_sidecar');t94($idx['edges'][1][43]['701'][0]['source_json_pointer']==='/edges/0','original_result_pointer');$badDoc=$doc;$badDoc['edges'][0]['operator_link_host']='other.invalid';$idx2=['by_native'=>[],'by_hotel'=>[],'edges'=>[],'rejected'=>[]];m95_index_doc($badDoc,'hotel-match-fixture',str_repeat('a',64),$idx2);t94($idx2['edges']===[]&&isset($idx2['rejected'][1][43]['701']),'wrong_host_not_accepted');
echo "M95_PURE_PASS $n94\n";
$dsn=(string)getenv('MATCH95_TEST_DSN');if($dsn==='')exit(0);w76_need(getenv('GITHUB_ACTIONS')==='true'&&$dsn==='mysql:host=127.0.0.1;port=3306;dbname=match95_test;charset=utf8mb4','disposable_localhost_only');$db=new PDO($dsn,'root','match95-test',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);w76_need($db->query('SELECT DATABASE()')->fetchColumn()==='match95_test','fixture_database');
$tables=['anex_review_pair_exclusions','anex_hotel_decisions','anex_hotel_search_mappings','andromeda_hotel_identities','tour_operator_identity_observations','catalog_hotels'];foreach($tables as$t)$db->exec('DROP TABLE IF EXISTS '.$t);
$db->exec('CREATE TABLE catalog_hotels(id INT PRIMARY KEY,name VARCHAR(240),country_id INT,country_name VARCHAR(100),region_name VARCHAR(100),subregion_name VARCHAR(100),category INT,is_active INT,latitude DECIMAL(12,8) NULL,longitude DECIMAL(12,8) NULL) ENGINE=InnoDB');
$db->exec('CREATE TABLE andromeda_hotel_identities(supplier_namespace VARCHAR(80) NOT NULL,external_hotel_id VARCHAR(80) NOT NULL,local_hotel_id INT NULL,decision_status VARCHAR(20) NOT NULL,catalog_sha256 CHAR(64) NOT NULL,evidence_sha256 CHAR(64) NOT NULL,evidence_json LONGTEXT NOT NULL,PRIMARY KEY(supplier_namespace,external_hotel_id)) ENGINE=InnoDB');
$db->exec('CREATE TABLE anex_hotel_search_mappings(anex_hotel_id INT PRIMARY KEY,catalog_hotel_id INT,match_class VARCHAR(100),scope VARCHAR(32),approval_policy VARCHAR(100),source_row_digest CHAR(64),mapping_digest CHAR(64),enabled INT,KEY(catalog_hotel_id)) ENGINE=InnoDB');
$db->exec('CREATE TABLE anex_hotel_decisions(anex_hotel_id INT PRIMARY KEY,catalog_hotel_id INT NULL,decision_status VARCHAR(32)) ENGINE=InnoDB');$db->exec('CREATE TABLE anex_review_pair_exclusions(anex_hotel_id INT,catalog_hotel_id INT,PRIMARY KEY(anex_hotel_id,catalog_hotel_id)) ENGINE=InnoDB');$db->exec('CREATE TABLE tour_operator_identity_observations(hotel_id INT PRIMARY KEY,last_seen_at DATETIME) ENGINE=InnoDB');
$seed=function()use($db,$tables,$hot,$src){foreach($tables as$t)$db->exec('DELETE FROM '.$t);foreach($hot as$h){$db->prepare('INSERT INTO catalog_hotels VALUES(?,?,?,?,?,?,?,?,?,?)')->execute(array_values($h));$db->prepare('INSERT INTO tour_operator_identity_observations VALUES(?,UTC_TIMESTAMP())')->execute([$h['id']]);}foreach($src as$r)$db->prepare('INSERT INTO andromeda_hotel_identities VALUES(?,?,?,?,?,?,?)')->execute(array_values($r));$db->prepare('INSERT INTO anex_hotel_search_mappings VALUES(?,?,?,?,?,?,?,?)')->execute([101,1,W75_CLASS,'preview',W75_POLICY,str_repeat('e',64),str_repeat('f',64),1]);};
$run=function(array$input)use($db,$co){$d=d94();return[m95_write($db,$input,$co,str_repeat('a',40),$d),$d];};$snapshot=function()use($db,$tables){$out=[];foreach($tables as$t)$out[$t]=$db->query('SELECT * FROM '.$t.' ORDER BY 1,2')->fetchAll(PDO::FETCH_ASSOC);return w76_hash($out);};
$seed();$before=$snapshot();$db->exec("CREATE TRIGGER fail_last BEFORE INSERT ON anex_hotel_search_mappings FOR EACH ROW BEGIN IF NEW.anex_hotel_id=303 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='fixture_late_error'; END IF; END");[$r,$d]=$run($p);t94($r['state']==='rolled_back_no_writes'&&$r['database_writes']===0,'mixed_late_rollback');t94($snapshot()===$before,'rollback_all_unchanged');t94(!is_file($d.'/commit-attempt.json'),'no_commit_after_error');$db->exec('DROP TRIGGER fail_last');
[$r,$d]=$run($p);t94($r['state']==='committed_readback_verified','mixed_commit_'.w76_json($r));t94($r['mapping_writes']===3&&$r['primary_samo_writes']===2&&$r['direct_anex_writes']===1,'exact3');t94($r['coverage_before']['full_triple']===0&&$r['coverage_after']['full_triple']===1,'actual_triple');t94($r['samo_after']['unresolved_primary_sources']===1,'actual_source_delta');t94($r['unrelated_identities_and_mappings_unchanged']&&$r['prior_evidence_preserved'],'unchanged_history');t94(is_file($d.'/commit-attempt.json'),'durable_commit');
[$r]=$run($p);t94($r['state']==='completed_no_new_writes'&&$r['mapping_writes']===0&&count($r['already'])===3,'fixture_noop');
$seed();$db->exec("UPDATE andromeda_hotel_identities SET local_hotel_id=999,decision_status='accepted' WHERE external_hotel_id='501'");[$r]=$run($p);t94($r['mapping_writes']===2&&count($r['held'])===1,'occupied_isolated');t94((int)$db->query("SELECT local_hotel_id FROM andromeda_hotel_identities WHERE external_hotel_id='501'")->fetchColumn()===999,'occupied_unchanged');
$seed();$db->exec("INSERT INTO anex_hotel_decisions VALUES(909,1,'rejected')");[$r]=$run($p);t94($r['mapping_writes']===2&&count($r['held'])===1,'manual_isolated');
$seed();$db->exec("INSERT INTO anex_review_pair_exclusions VALUES(909,1)");[$r]=$run($p);t94($r['mapping_writes']===2&&count($r['held'])===1,'exclusion_isolated');
$seed();$or=$src['501'];$or['supplier_namespace']='operator_342';$or['external_hotel_id']='701';$or['local_hotel_id']=999;$or['decision_status']='accepted';$db->prepare('INSERT INTO andromeda_hotel_identities VALUES(?,?,?,?,?,?,?)')->execute(array_values($or));[$r]=$run($p);t94($r['mapping_writes']===2&&count($r['held'])===1,'operator_other_isolated');
$seed();$db->exec("INSERT INTO anex_hotel_decisions VALUES(303,NULL,'rejected')");[$r]=$run($p);t94($r['mapping_writes']===2&&$r['direct_anex_writes']===0&&count($r['held'])===1,'direct_manual_isolated');
$seed();$db->exec('UPDATE catalog_hotels SET category=5 WHERE id=1');[$r]=$run($p);t94($r['mapping_writes']===2&&count($r['held'])===1,'category_isolated');
$seed();$bad=$p;$bad['candidates'][0]['prior_scan']['evidence_sha256']=str_repeat('f',64);[$r]=$run($bad);t94($r['mapping_writes']===2&&count($r['held'])===1,'source_drift_isolated');
echo "M95_MYSQL_PASS $n94\n";
