<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/scripts/diagnostics/hotel_match_common4_mass_writer_v14.php';
$dsn=getenv('MATCH_C14_TEST_DSN');if($dsn!=='mysql:host=127.0.0.1;port=3306;dbname=match_c14;charset=utf8mb4')throw new RuntimeException('isolated_mysql_required');
$db=new PDO($dsn,'root','root',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
function c14ok(bool $v,string $m):void{if(!$v)throw new RuntimeException($m);}
function c14target(int $id):array{return ['id'=>$id,'name'=>'HOTEL '.$id,'country_id'=>4,'country_name'=>'Турция','region_id'=>20,'region_name'=>'Сиде','subregion_id'=>200,'subregion_name'=>'Сиде','category'=>'5','is_active'=>1];}
function c14anchor(int $id):array{$raw=hmc14_json(['tv'=>$id]);return ['supplier_namespace'=>'andromeda_catalog','external_hotel_id'=>(string)(900000+$id),'local_hotel_id'=>$id,'decision_status'=>'accepted','catalog_sha256'=>hash('sha256','cat'.$id),'evidence_sha256'=>hash('sha256',$raw),'evidence_json'=>$raw];}
function c14audit(int $n):array{$rows=[];for($i=1;$i<=$n;$i++){$tv=1000+$i;$ns=$i%3===1?'bgoperator':($i%3===2?'operator_315':'operator_342');$op=HMC14_ALLOWED[$ns];$a=c14anchor($tv);$rows[]=['kind'=>'identity','writer_ready'=>true,'status'=>'current_missing_edge','anchor_state'=>'canonical_anchor_ok','safe_to_write_now'=>false,'supplier_namespace'=>$ns,'external_hotel_id'=>(string)(800000+$i),'tv_hotel_id'=>$tv,'operator_id'=>$op,'source_operation'=>'child','source_result_sha256'=>str_repeat('a',64),'batch'=>1,'search_id_sha256'=>str_repeat('b',64),'tour_id_sha256'=>str_repeat('c',64),'operator_link_sha256'=>str_repeat('d',64),'catalog_hotel'=>c14target($tv),'unanimous_catalog_sha256'=>$a['catalog_sha256'],'anchors'=>[hmc14_anchor_projection($a)]];}return ['operation'=>'hotel-match-common4-mass-current-1971-20260924-v13','state'=>'completed_read_only_mass_current','rows'=>$rows];}
function c14seed(PDO $db,int $n):void{$db->exec('DELETE FROM andromeda_hotel_identities');$db->exec('DELETE FROM anex_hotel_decisions');$db->exec('DELETE FROM catalog_hotels');$h=$db->prepare('INSERT INTO catalog_hotels VALUES(?,?,?,?,?,?,?,?,?,1)');$a=$db->prepare('INSERT INTO andromeda_hotel_identities(supplier_namespace,external_hotel_id,local_hotel_id,decision_status,catalog_sha256,evidence_sha256,evidence_json) VALUES(?,?,?,?,?,?,?)');for($i=1;$i<=$n;$i++){$tv=1000+$i;$t=c14target($tv);$h->execute([$t['id'],$t['name'],$t['country_id'],$t['country_name'],$t['region_id'],$t['region_name'],$t['subregion_id'],$t['subregion_name'],$t['category']]);$x=c14anchor($tv);$a->execute([$x['supplier_namespace'],$x['external_hotel_id'],$x['local_hotel_id'],$x['decision_status'],$x['catalog_sha256'],$x['evidence_sha256'],$x['evidence_json']]);}}
try{
 foreach(['anex_hotel_decisions','andromeda_hotel_identities','catalog_hotels'] as $x)$db->exec("DROP TABLE IF EXISTS $x");
 $db->exec("CREATE TABLE catalog_hotels(id INT PRIMARY KEY,name VARCHAR(500),country_id INT,country_name VARCHAR(100),region_id INT NULL,region_name VARCHAR(200),subregion_id INT NULL,subregion_name VARCHAR(200) NULL,category VARCHAR(20),is_active TINYINT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 $db->exec("CREATE TABLE andromeda_hotel_identities(supplier_namespace VARCHAR(40),external_hotel_id VARCHAR(32),local_hotel_id INT NULL,decision_status VARCHAR(16),catalog_sha256 CHAR(64),evidence_sha256 CHAR(64),evidence_json MEDIUMTEXT,PRIMARY KEY(supplier_namespace,external_hotel_id),KEY(local_hotel_id)) ENGINE=InnoDB");
 $db->exec("CREATE TABLE anex_hotel_decisions(anex_hotel_id BIGINT PRIMARY KEY,catalog_hotel_id INT NULL,decision_status VARCHAR(32)) ENGINE=InnoDB");
 $n=7;$audit=c14audit($n);$manifest=hmc14_manifest($audit,$n);c14seed($db,$n);$r=hmc14_write($db,$manifest,str_repeat('1',40),str_repeat('2',64));c14ok($r['state']==='committed_verified'&&$r['inserted']===$n&&array_sum($r['inserted_by_namespace'])===$n,'commit');
 $replay=false;try{hmc14_write($db,$manifest,str_repeat('1',40),str_repeat('2',64));}catch(RuntimeException $e){$replay=str_contains($e->getMessage(),'source_key_now_present');}c14ok($replay,'replay');
 c14seed($db,$n);$db->exec("UPDATE andromeda_hotel_identities SET evidence_sha256=REPEAT('f',64) WHERE local_hotel_id=1001");$ok=false;try{hmc14_write($db,$manifest,str_repeat('1',40),str_repeat('2',64));}catch(RuntimeException $e){$ok=str_contains($e->getMessage(),'anchor_evidence_hash_drift');}c14ok($ok&&(int)$db->query("SELECT COUNT(*) FROM andromeda_hotel_identities WHERE supplier_namespace<>'andromeda_catalog'")->fetchColumn()===0,'anchor_rollback');
 c14seed($db,$n);$db->exec("CREATE TRIGGER reject_last BEFORE INSERT ON andromeda_hotel_identities FOR EACH ROW BEGIN IF NEW.supplier_namespace<>'andromeda_catalog' AND NEW.external_hotel_id='800007' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='late'; END IF; END");$ok=false;try{hmc14_write($db,$manifest,str_repeat('1',40),str_repeat('2',64));}catch(RuntimeException $e){$ok=str_starts_with($e->getMessage(),'rolled_back_no_write:');}c14ok($ok&&(int)$db->query("SELECT COUNT(*) FROM andromeda_hotel_identities WHERE supplier_namespace<>'andromeda_catalog'")->fetchColumn()===0,'atomic');$db->exec('DROP TRIGGER reject_last');
 echo json_encode(['status'=>'passed','rows'=>$n,'supplier_calls'=>0,'production_writes'=>0]),PHP_EOL;
}finally{if($db->inTransaction())$db->rollBack();foreach(['anex_hotel_decisions','andromeda_hotel_identities','catalog_hotels'] as $x)$db->exec("DROP TABLE IF EXISTS $x");}
