<?php
declare(strict_types=1);
putenv('MATCH_LIVE_ANDROMEDA_V5_TEST_LIBRARY=1');
require_once __DIR__.'/../scripts/diagnostics/hotel_match_live_andromeda_residual_review_v5.php';
function tl5(bool $ok,string $msg):void{if(!$ok)throw new RuntimeException($msg);}
$core=[4=>'Турция'];$hotels=[10=>['id'=>10,'country_id'=>4,'country_name'=>'Турция','region_name'=>'Белек','subregion_name'=>'','name'=>'INNVISTA HOTEL BELEK','category'=>'5*','latitude'=>36.86,'longitude'=>31.05],11=>['id'=>11,'country_id'=>4,'country_name'=>'Турция','region_name'=>'Стамбул','subregion_name'=>'','name'=>'OTHER HOTEL','category'=>'4*','latitude'=>41.0,'longitude'=>29.0]];$forms=[10=>['INNVISTA HOTEL BELEK','INNVISTA'],11=>['OTHER HOTEL']];$exact=[4=>[mcr_norm('INNVISTA')=>[10],mcr_norm('INNVISTA HOTEL BELEK')=>[10],mcr_norm('OTHER HOTEL')=>[11]]];$tokens=[];foreach($forms as $id=>$ls)foreach($ls as $raw)foreach(mcr_tokens($raw) as $t)$tokens[4][$t][$id]=true;$geo=mcr_geo_exact_index($hotels,$forms);$state=['77'=>['country_id'=>4,'winner'=>10,'total'=>10,'share'=>1.0]];
$e=['source'=>['stateKey'=>'77','name'=>'Innvista','frequency'=>7]];$raw=json_encode($e,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);$row=['external_hotel_id'=>'700','evidence_sha256'=>hash('sha256',$raw),'evidence_json'=>$raw];$r=mlar5_classify($row,$state,$core,$hotels,$forms,$exact,$tokens,$geo,[]);tl5(($r['route']??'')==='auto_accept_candidate'&&(int)$r['target']===10,'direct exact');tl5((int)$r['frequency']===7,'frequency');
$e2=['source'=>['stateKey'=>'77','name'=>'Innvista','frequency'=>9]];$raw2=json_encode($e2,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);$row2=['external_hotel_id'=>'701','evidence_sha256'=>hash('sha256',$raw2),'evidence_json'=>$raw2];$bridges=['701'=>[['operator_315','123',10,str_repeat('a',64)]]];$r=mlar5_classify($row2,$state,$core,$hotels,$forms,$exact,$tokens,$geo,$bridges);tl5(($r['reason']??'')==='accepted_operator_native_bridge'&&(int)$r['target']===10,'operator bridge');
$conf=['701'=>[['operator_315','123',10,str_repeat('a',64)],['operator_342','456',11,str_repeat('b',64)]]];$r=mlar5_classify($row2,$state,$core,$hotels,$forms,$exact,$tokens,$geo,$conf);tl5(($r['route']??'')==='hard_conflict'&&($r['reason']??'')==='accepted_operator_bridge_target_conflict','bridge conflict');
$src=(string)file_get_contents(__DIR__.'/../scripts/diagnostics/hotel_match_live_andromeda_residual_review_v5.php');foreach(['START TRANSACTION READ ONLY',"decision_status='pending'",'mcr_select_candidate(','mlar5_operator_bridges(',"'operator_5_writes'=>0","'mapping_writes'=>0"] as $needle)tl5(str_contains($src,$needle),'source guard '.$needle);tl5(!preg_match('/(?:curl_|fsockopen|stream_socket_client|broninit|booking\(|lead\(|\bINSERT\b|\bUPDATE\b|\bDELETE\b|\bREPLACE\b)/i',$src),'read only no external');
echo "MATCH_LIVE_ANDROMEDA_RESIDUAL_V5_TEST_OK\n";
