<?php
declare(strict_types=1);
require_once __DIR__.'/../scripts/diagnostics/hotel_match_raw_native_pending11_v78.php';
$count=0;
function ck(bool $b,string $n):void{global$count;$count++;if(!$b)throw new RuntimeException('test_'.$n);}
function fixture78():array{$entries=[];$c=['sources'=>[],'targets'=>[],'operators'=>[],'hotels'=>[],'manual'=>[],'exclusions'=>[]];foreach(W78_PAIRS as$id=>$cat){$h=['id'=>$id,'name'=>'Example Unique Hotel '.$id,'country_id'=>4,'country_name'=>'Турция','region_name'=>'Стамбул','subregion_name'=>'','category'=>4,'is_active'=>1,'latitude'=>null,'longitude'=>null];$src=['id'=>$cat,'name'=>'Example Unique Hotel '.$id,'state'=>'Турция','starKey'=>4,'town'=>'Фатих'];$ev=['source'=>$src,'reason'=>'no_unique_country_name'];$r=['supplier_namespace'=>'andromeda_catalog','external_hotel_id'=>$cat,'local_hotel_id'=>null,'decision_status'=>'pending','catalog_sha256'=>str_repeat('a',64),'evidence_sha256'=>hash('sha256',w76_json($ev)),'evidence_json'=>w76_json($ev)];$e=['id'=>$id,'catalog_id'=>$cat,'prepare_holds'=>[],'proofs'=>[['namespace'=>'operator_315','native_id'=>(string)$id,'tv'=>['kind'=>'independent_tv_audit']]],'operator_facts'=>[],'prior'=>$r,'history'=>$ev,'target'=>w76_target($h),'live_samo'=>true];$entries[$id]=$e;$c['sources'][$cat]=[$r];$c['hotels'][$id]=$h;}return[$entries,$c];}
[$entries,$c]=fixture78();foreach($entries as$e)ck(w78_classify($e,$c)['status']==='ready','one_proof_no_anex_or_exact_town_'.$e['id']);
$first=array_key_first($entries);$e=$entries[$first];$cat=$e['catalog_id'];
foreach(['source_conflict','target_conflict','manual','category','evidence','name','proof']as$mode){$x=$c;$y=$e;switch($mode){case'source_conflict':$x['sources'][$cat][0]['local_hotel_id']=999;break;case'target_conflict':$x['targets'][$first]=[['external_hotel_id'=>'999']];break;case'manual':$x['manual'][$first]=true;break;case'category':$x['hotels'][$first]['category']=5;break;case'evidence':$x['sources'][$cat][0]['evidence_json']='{}';break;case'name':$x['hotels'][$first]['name']='Different';break;case'proof':$y['proofs']=[];break;}ck(w78_classify($y,$x)['status']==='hold',$mode);}
$x=$c;$x['sources'][$cat][0]['local_hotel_id']=$first;$x['sources'][$cat][0]['decision_status']='accepted';ck(w78_classify($e,$x)['status']==='already','already_same');
$opEv=['schema'=>'operator-original-price-bridge/1','country_id'=>4,'source'=>['id'=>'55','operator_key'=>'315','name'=>'Example'],'operation_id'=>'hotel-match-operator-original-store-1971-20260915-v2','source_operation_id'=>'hotel-match-operator-original-batch-1971-20260915-v2','source_result_sha256'=>'f379062abd43c36e6feb792f8e0313466ddd579a1959cfe814e90b863a43968e','catalog_reference_kind'=>'price_capture','decision'=>['state'=>'pending','local_hotel_id'=>null,'country_id'=>4,'anchors'=>[],'reason'=>'no_anchor'],'provider_bridges'=>[]];$or=['supplier_namespace'=>'operator_315','external_hotel_id'=>'55','local_hotel_id'=>null,'decision_status'=>'pending','catalog_sha256'=>str_repeat('b',64),'evidence_sha256'=>hash('sha256',w76_json($opEv)),'evidence_json'=>w76_json($opEv)];ck(w78_auto_operator($or),'automatic_original_store');$or['decision_status']='rejected';ck(!w78_auto_operator($or),'operator_rejected');
$ev=json_decode($c['sources'][$cat][0]['evidence_json'],true);$ev['candidate_ids']=[];$ev['target_name']=null;$r=$c['sources'][$cat][0];$r['evidence_json']=w76_json($ev);$r['evidence_sha256']=hash('sha256',$r['evidence_json']);ck(w78_auto($r),'actual_empty_candidate_fields');$ev['candidate_ids']=[999];$r['evidence_json']=w76_json($ev);$r['evidence_sha256']=hash('sha256',$r['evidence_json']);ck(!w78_auto($r),'nonempty_candidates_hold');
$context=['context'=>['rows'=>[]]];$full=['remaining_queues'=>['live_30d'=>['rows'=>[['tv_hotel_id'=>17383,'name'=>'Conrad','country'=>'Турция','category'=>5]]]]];$hs=w78_hotels($context,$full);ck(isset($hs[17383])&&$hs[17383]['name']==='Conrad','missing_both_target_not_excluded');$e2=$e;$e2['target']=w78_target($c['hotels'][$first]);ck(w78_classify($e2,$c)['status']==='ready','bounded_target_projection');
$ev['candidate_ids']=[];$ev['manual']=true;$r['evidence_json']=w76_json($ev);$r['evidence_sha256']=hash('sha256',$r['evidence_json']);ck(!w78_auto($r),'manual_marker_hold');
ck(w78_fact(['hotelKey'=>650,'operatorKey'=>315,'original'=>['operatorKey'=>315,'hotelKey'=>245225]],'650','operator_315','245225'),'raw_identity');ck(!w78_fact(['hotelKey'=>650,'operatorKey'=>315,'original'=>['operatorKey'=>342,'hotelKey'=>245225]],'650','operator_315','245225'),'raw_operator_mix');ck(!w78_fact(['hotelKey'=>650,'operatorKey'=>315,'isOperatorHotelKey'=>true,'original'=>['hotelKey'=>245225]],'650','operator_315','245225'),'native_namespace_not_catalog');ck(w78_ptr(['PRICES'=>[['id'=>1]]],'/PRICES/0')===['id'=>1],'pointer');
ck(w78_name('Darkhill','DARK HILL HOTEL LALELI'),'name_spacing');ck(w78_name("Cook's Club El Gouna",'COOKS CLUB EL GOUNA ADULTS ONLY 16+'),'name_apostrophe');ck(!w78_name('Other Property','Unrelated Building'),'name_negative');
echo 'PURE_ASSERTIONS='.$count."\n";
if(getenv('MATCH78_TEST_DSN')){
 ck(getenv('GITHUB_ACTIONS')==='true','hosted_only');$db=new PDO(getenv('MATCH78_TEST_DSN'),'root','match78-test',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);ck($db->query('SELECT DATABASE()')->fetchColumn()==='match78_test','test_database');
 foreach(['andromeda_hotel_identities','catalog_hotels','anex_hotel_decisions','anex_review_pair_exclusions']as$t)$db->exec('DROP TABLE IF EXISTS '.$t);
 $db->exec("CREATE TABLE andromeda_hotel_identities(supplier_namespace VARCHAR(80) NOT NULL,external_hotel_id VARCHAR(80) NOT NULL,local_hotel_id INT NULL,decision_status VARCHAR(20) NOT NULL,catalog_sha256 CHAR(64) NOT NULL,evidence_sha256 CHAR(64) NOT NULL,evidence_json LONGTEXT NOT NULL,PRIMARY KEY(supplier_namespace,external_hotel_id)) ENGINE=InnoDB");
 $db->exec('CREATE TABLE catalog_hotels(id INT PRIMARY KEY,name VARCHAR(240),country_id INT,country_name VARCHAR(100),region_name VARCHAR(100),subregion_name VARCHAR(100),category INT,is_active INT,latitude DECIMAL(12,8) NULL,longitude DECIMAL(12,8) NULL) ENGINE=InnoDB');
 foreach(['anex_hotel_decisions','anex_review_pair_exclusions']as$t)$db->exec('CREATE TABLE '.$t.'(catalog_hotel_id INT PRIMARY KEY) ENGINE=InnoDB');
 $insert=function()use($db,$c){$db->exec('DELETE FROM andromeda_hotel_identities');$db->exec('DELETE FROM catalog_hotels');foreach($c['sources']as$rows){$r=$rows[0];$db->prepare('INSERT INTO andromeda_hotel_identities VALUES(?,?,?,?,?,?,?)')->execute(array_values($r));}foreach($c['hotels']as$h)$db->prepare('INSERT INTO catalog_hotels VALUES(?,?,?,?,?,?,?,?,?,?)')->execute(array_values($h));};
 $run=function(array$en)use($db){$p=sys_get_temp_dir().'/match78-'.bin2hex(random_bytes(5));mkdir($p,0700);return w78_execute($db,$en,str_repeat('a',40),$p,false);};
 $insert();$before=$db->query('SELECT * FROM andromeda_hotel_identities ORDER BY external_hotel_id')->fetchAll(PDO::FETCH_ASSOC);
 $db->exec("CREATE TRIGGER fail_last BEFORE UPDATE ON andromeda_hotel_identities FOR EACH ROW BEGIN IF NEW.local_hotel_id=28649 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='fixture_late_error'; END IF; END");$r=$run($entries);ck($r['state']==='rolled_back_no_writes'&&$r['database_writes']===0,'late_rollback');ck($db->query('SELECT * FROM andromeda_hotel_identities ORDER BY external_hotel_id')->fetchAll(PDO::FETCH_ASSOC)===$before,'rollback_unchanged');$db->exec('DROP TRIGGER fail_last');
 $r=$run($entries);ck($r['state']==='committed_readback_verified'&&$r['database_writes']===11&&count($r['rows'])===11,'all11_commit');ck($r['prior_evidence_preserved']&&$r['unrelated_identities_unchanged'],'preserved');$r=$run($entries);ck($r['state']==='completed_no_new_writes'&&count($r['already'])===11,'idempotent_noop');
 $insert();$db->exec("UPDATE andromeda_hotel_identities SET local_hotel_id=999,decision_status='accepted' WHERE external_hotel_id='650'");$r=$run($entries);ck($r['state']==='committed_readback_verified'&&$r['database_writes']===10&&count($r['held'])===1,'conflict_does_not_block10');ck((int)$db->query("SELECT local_hotel_id FROM andromeda_hotel_identities WHERE external_hotel_id='650'")->fetchColumn()===999,'foreign_preserved');
 $insert();$db->exec('INSERT INTO anex_hotel_decisions VALUES(17383)');$r=$run($entries);ck($r['database_writes']===10&&count($r['held'])===1,'manual_protected');
 echo 'WITH_MYSQL_ASSERTIONS='.$count."\n";
}
