<?php
define('ACF_LIBRARY_ONLY',true);require __DIR__.'/../scripts/diagnostics/hotel_andromeda_category_fix_reconcile.php';
$dsn=getenv('ANEX_LINK_TEST_DSN');if($dsn!=='mysql:host=127.0.0.1;port=3306;dbname=anex_link_test;charset=utf8mb4')throw new RuntimeException('isolated_only');$db=new PDO($dsn,'root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
$tables=['andromeda_hotel_identities','anex_review_pair_exclusions','anex_hotel_decisions','anex_hotel_search_mappings','anex_hotels','hotel_aliases','catalog_hotel_details','catalog_hotels','catalog_countries'];foreach($tables as $t)$db->exec('DROP TABLE IF EXISTS '.$t);function ckacf($v,$m){if(!$v)throw new RuntimeException($m);}
try{
$db->exec('CREATE TABLE catalog_countries(id INT PRIMARY KEY,name VARCHAR(100)) ENGINE=InnoDB');$q=$db->prepare('INSERT INTO catalog_countries VALUES(?,?)');foreach(FC_COUNTRIES as $id=>$name)$q->execute([$id,$name]);
$db->exec("CREATE TABLE catalog_hotels(id INT PRIMARY KEY,country_id INT,country_name VARCHAR(100),name VARCHAR(255),normalized_name VARCHAR(255),region_name VARCHAR(150),subregion_name VARCHAR(150),category INT NULL,latitude DECIMAL(10,7) NULL,longitude DECIMAL(10,7) NULL,is_active INT) ENGINE=InnoDB");$db->exec('CREATE TABLE catalog_hotel_details(hotel_id INT PRIMARY KEY,latitude DECIMAL(10,7) NULL,longitude DECIMAL(10,7) NULL) ENGINE=InnoDB');$db->exec('CREATE TABLE hotel_aliases(id INT AUTO_INCREMENT PRIMARY KEY,hotel_id INT,alias VARCHAR(255),normalized_alias VARCHAR(255)) ENGINE=InnoDB');$db->exec('CREATE TABLE anex_hotels(anex_hotel_id INT PRIMARY KEY) ENGINE=InnoDB');$db->exec('CREATE TABLE anex_hotel_search_mappings(anex_hotel_id INT PRIMARY KEY,catalog_hotel_id INT,match_class VARCHAR(32),scope VARCHAR(16),approval_policy VARCHAR(64),source_row_digest CHAR(64),mapping_digest CHAR(64),enabled INT) ENGINE=InnoDB');$db->exec('CREATE TABLE anex_hotel_decisions(anex_hotel_id INT PRIMARY KEY,catalog_hotel_id INT NULL,decision_status VARCHAR(16)) ENGINE=InnoDB');$db->exec('CREATE TABLE anex_review_pair_exclusions(anex_hotel_id INT,catalog_hotel_id INT,PRIMARY KEY(anex_hotel_id,catalog_hotel_id)) ENGINE=InnoDB');$db->exec("CREATE TABLE andromeda_hotel_identities(supplier_namespace VARCHAR(40),external_hotel_id VARCHAR(32),local_hotel_id INT NULL,decision_status VARCHAR(16),catalog_sha256 CHAR(64),evidence_sha256 CHAR(64),evidence_json MEDIUMTEXT,PRIMARY KEY(supplier_namespace,external_hotel_id)) ENGINE=InnoDB");
$h=$db->prepare("INSERT INTO catalog_hotels VALUES(?,4,'Турция',?,?,?,?,?,?,?,1)");for($i=1;$i<=9;$i++){$n='SEASIDE RESIDENCE '.$i;$h->execute([1000+$i,$n,strtolower($n),'Аланья','Аланья',3,36.5,31.5]);}
$anchor=fc_json(['source'=>['id'=>'8000','name'=>'ANCHOR HOTEL','star'=>'3','starKey'=>3]]);$db->prepare("INSERT INTO andromeda_hotel_identities VALUES('andromeda_catalog','8000',1001,'accepted',REPEAT('a',64),?,?)")->execute([hash('sha256',$anchor),$anchor]);$ins=$db->prepare("INSERT INTO andromeda_hotel_identities VALUES('andromeda_catalog',?,NULL,'pending',REPEAT('a',64),?,?)");
for($i=2;$i<=8;$i++){$ev=fc_json(['source'=>['id'=>(string)(8000+$i),'name'=>'SEASIDE RESIDENCE '.$i.' APARTMENTS','lName'=>'SEASIDE RESIDENCE '.$i,'town'=>'Аланья','star'=>'Apts','starKey'=>16],'candidate_ids'=>[1000+$i],'geography'=>['town'=>'Аланья']]);$ins->execute([(string)(8000+$i),hash('sha256',$ev),$ev]);}
$ev=fc_json(['source'=>['id'=>'8009','name'=>'SEASIDE RESIDENCE 9 HOTEL','town'=>'Аланья','star'=>'4','starKey'=>4],'candidate_ids'=>[1009],'geography'=>['town'=>'Аланья']]);$ins->execute(['8009',hash('sha256',$ev),$ev]);
ckacf(acf_numeric_category(['star'=>'Apts','starKey'=>16])===null,'Apts must not be parsed from starKey');ckacf(acf_numeric_category(['star'=>'4','starKey'=>4])===4,'numeric star');$r=acf_reconcile($db,'category-fix-test');ckacf($r['status']==='completed'&&$r['readback_verified']===true,'completed');ckacf($r['accepted_total']===7,'seven type-label false conflicts');ckacf($r['andromeda']['true_numeric_mismatch']===1,'numeric mismatch blocked');ckacf((int)$db->query("SELECT COUNT(*) FROM andromeda_hotel_identities WHERE external_hotel_id='8009' AND decision_status='pending'")->fetchColumn()===1,'real mismatch remains pending');echo fc_json(['status'=>'passed','accepted'=>$r['accepted_total'],'numeric_mismatch_blocked'=>$r['andromeda']['true_numeric_mismatch'],'supplier_calls'=>0]),"\n";
}finally{if($db->inTransaction())$db->rollBack();foreach($tables as $t)$db->exec('DROP TABLE IF EXISTS '.$t);}
