'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
global.window={addEventListener(){},dispatchEvent(){},requestAnimationFrame(fn){fn();}};
global.document={readyState:'loading',documentElement:{dataset:{}},body:null,addEventListener(){},getElementById(){return null;},querySelector(){return null;}};
global.CustomEvent=function CustomEvent(){};
require('../v2/results-renderer-v5.js');
const api=window.V2Results;
const freeze=value=>{if(value&&typeof value==='object'){Object.values(value).forEach(freeze);Object.freeze(value);}return value;};
const tour=freeze({id:'first',date:'2026-09-16',nights:7,price:62400,meal:{name:'BB',fullName:'Завтраки'},roomType:'STANDARD',placement:'DBL',adults:2,childs:0,isCharter:true,operator:{name:'Fun&Sun (RU)'}});
const other=freeze({...tour,id:'second',nights:10,price:74900,meal:{name:'AI',fullName:'Всё включено'},operator:'ANEX TOUR',isCharter:false});
const hotel=freeze({id:'hotel',name:'Проверочный отель',price:62400,tours:[tour,other]});
const original=JSON.stringify(hotel);
const summary=api.toursHtml(hotel);
assert.match(summary,/hotel-offers-summary/);
assert.doesNotMatch(summary,/class="tour-row"|data-tid=|data-operator-brand=|Итого за тур|16\.09\.2026|7 ноч\.|Завтраки|Чартер/,'collapsed multi-offer hotel must not borrow one tour conditions or actions');
assert.equal((summary.match(/class="hotel-price"/g)||[]).length,1);
assert.match(summary,/от 62(?:\s| )?400/);
assert.match(summary,/Показать варианты · 2/);
for(const offer of [tour,other]){
  const row=api.tourRow(offer);
  assert.doesNotMatch(row,/от |7–10|Разные варианты перелёта|Завтрак · Всё включено/,'individual offer never inherits aggregate fields');
  assert.match(row,new RegExp(' · '+offer.nights+' ноч\\.'));
  assert.ok(row.includes('data-tid="'+offer.id+'"'));
  assert.ok(row.includes(api.money(offer.price)));
  assert.ok(row.includes(offer.meal.fullName));
  assert.match(row,new RegExp(offer.isCharter?'Чартер':'Регулярный рейс'));
  assert.equal((row.match(/class="hotel-price"/g)||[]).length,1);
  assert.match(row,/<small>Номер<\/small><b>STANDARD · DBL<\/b>/,'room and placement stay together as one exact offer fact');
  assert.match(row,/<small>Источник<\/small><b>Tourvisor<\/b>/,'exact offer keeps provider source distinct from tour operator');
  assert.doesNotMatch(row,/<small>(?:Туристы|Размещение)<\/small>/,'exact offer does not repeat search party or a second placement field');
}
assert.equal(api.operatorIdentity({provider:'anex'}),null,'provider is not tour operator');
assert.equal(api.operatorIdentity({operator:'ANEX SERVICES'}).logo,'','unknown similar name is not branded');
assert.equal(api.operatorIdentity({operator:'НТК Интурист'}).key,'intourist');
assert.equal(api.operatorIdentity({operator:'Библио Глобус'}).key,'biblio-globus');
const fallback=api.tourRow({...tour,operator:'<img onerror="bad()">'});
assert.doesNotMatch(fallback,/<img onerror/);
assert.match(fallback,/&lt;img/,'unknown operator names remain escaped');
assert.doesNotMatch(api.tourRow({...tour,provider:'andromeda',selectionEnabled:false}),/class="direct-tour"/,'existing provider selection guard stays authoritative');
assert.equal(JSON.stringify(hotel),original,'frozen original identities, dates, prices and parameters are unchanged');
const assets=path.join(__dirname,'../v2/assets/operator-logos');
const provenance=JSON.parse(fs.readFileSync(path.join(assets,'provenance.json')));
assert.equal(provenance.artwork_modified,false);
assert.equal(provenance.assets.length,4);
for(const asset of provenance.assets){
  const data=fs.readFileSync(path.join(assets,asset.file));
  assert.equal(crypto.createHash('sha256').update(data).digest('hex'),asset.sha256,asset.file+' matches stored artwork provenance');
  assert.equal(data.length,asset.size);
  if(asset.file.endsWith('.svg')){
    const text=data.toString();
    assert.match(text,/<svg\b/);
    assert.doesNotMatch(text,/\r/,'stored SVG uses LF line endings');
    assert.doesNotMatch(text,/[ \t]+$/m,'stored SVG has no trailing whitespace');
    assert.doesNotMatch(text,/<(?:script|foreignObject|iframe|image)\b|\son\w+\s*=|(?:href|xlink:href)\s*=\s*["'](?:https?:|\/\/|data:)|url\(\s*["']?https?:/i,'brand SVG must be passive and self-contained');
  }else assert.equal(data.subarray(0,8).toString('hex'),'89504e470d0a1a0a');
}
console.log('SEARCH3_OPERATOR_CARDS_OK collapsed_hotel_level=1 compact_exact_offers=1 brands=4 provider_not_operator=1 frozen_source=1');
