'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
global.window={addEventListener(){},dispatchEvent(){},requestAnimationFrame(fn){fn();}};
global.document={readyState:'loading',documentElement:{dataset:{}},body:null,addEventListener(){},getElementById(){return null;},querySelector(){return null;}};
global.CustomEvent=function CustomEvent(){};
require('../v2/results-renderer-v5.js');
const api=window.V2Results;
const freeze=value=>{if(value&&typeof value==='object'){Object.values(value).forEach(freeze);Object.freeze(value);}return value;};
const tour=freeze({id:'first',date:'2026-09-16',nights:7,price:62400,meal:{name:'BB',fullName:'Завтраки'},roomType:'STANDARD',placement:'DBL',adults:2,childs:0,isCharter:true,operator:{name:'Fun&Sun (RU)'}});
const other=freeze({...tour,id:'second',nights:10,price:74900,meal:{name:'AI',fullName:'Всё включено'},operator:'ANEX TOUR',isCharter:false});
const hotel=freeze({id:'hotel',name:'Проверочный отель',price:62400,tours:[tour,other]});
const original=JSON.stringify(hotel);
assert.equal(api.hotelSummary(hotel).nights,'7–10 ноч.');
assert.equal(api.hotelSummary(hotel).meal,'BB · AI');
assert.equal(api.hotelSummary(hotel).flight,'Возможны чартеры');
assert.equal(api.hotelSummary(hotel).party,'2 взрослых');
assert.equal(api.hotelSummary(hotel).date,'16.09.2026');
assert.equal(api.hotelSummary({...hotel,tours:[tour,{...other,date:'2026-09-17'}]}).date,'Несколько дат вылета');
assert.equal(api.hotelSummary({...hotel,tours:[tour,{...other,nights:null}]}).nights,'Уточняется');
assert.equal(api.hotelSummary({...hotel,tours:[tour,{...other,date:''}]}).date,'Дата уточняется');
assert.equal(api.hotelSummary({...hotel,tours:[tour,{...other,meal:''}]}).meal,'Уточняется по варианту');
assert.equal(api.hotelSummary({...hotel,tours:[tour,{...other,adults:undefined}]}).party,'');
const summary=api.hotelSummaryHtml(hotel);
assert.match(summary,/class="hotel-trip-summary"/);
assert.doesNotMatch(summary,/class="tour-row|direct-tour|Лучшее предложение|Доступные варианты/,'hotel summary is not represented as an exact offer');
assert.equal((summary.match(/За весь тур/g)||[]).length,1);
assert.match(summary,/от 62\s?400/);
assert.match(summary,/data-operator-brand="funsun"/);
assert.match(summary,/data-operator-brand="anex"/);
assert.doesNotMatch(summary,/intourist|biblio-globus/,'do not add operators absent from this hotel');
for(const offer of [tour,other]){
  const row=api.tourRow(offer);
  assert.doesNotMatch(row,/от |7–10|Возможны чартеры|BB · AI/,'individual offer never inherits aggregate fields');
  assert.match(row,new RegExp(' · '+offer.nights+' ноч\\.'));
  assert.ok(row.includes('data-tid="'+offer.id+'"'));
  assert.ok(row.includes(api.money(offer.price)));
  assert.ok(row.includes(offer.meal.fullName));
  assert.equal((row.match(/class="hotel-price"/g)||[]).length,1);
}
assert.equal(api.operatorIdentity({provider:'anex'}),null,'provider is not tour operator');
assert.equal(api.operatorIdentity({operator:'ANEX SERVICES'}).logo,'','unknown similar name is not branded');
assert.equal(api.operatorIdentity({operator:'НТК Интурист'}).key,'intourist');
assert.equal(api.operatorIdentity({operator:'Библио Глобус'}).key,'biblio-globus');
assert.equal(api.hotelOperators({tours:[tour,{...tour,operator:'FUN&SUN'},other]}).length,2,'exact aliases deduplicate brands');
const fallback=api.hotelOperatorsHtml({tours:[{operator:'<img onerror="bad()">'}]});
assert.doesNotMatch(fallback,/<img /);
assert.match(fallback,/&lt;img/,'unknown names are escaped, not interpreted as markup');
assert.doesNotMatch(api.tourRow({...tour,provider:'andromeda',selectionEnabled:false}),/class="direct-tour"/,'existing provider selection guard stays authoritative');
assert.equal(JSON.stringify(hotel),original,'frozen original identities, dates, prices and parameters are unchanged');
const assets=path.join(__dirname,'../v2/assets/operator-logos');
const provenance=JSON.parse(fs.readFileSync(path.join(assets,'provenance.json')));
assert.equal(provenance.artwork_modified,false);
assert.equal(provenance.assets.length,4);
for(const asset of provenance.assets){
  const data=fs.readFileSync(path.join(assets,asset.file));
  assert.equal(crypto.createHash('sha256').update(data).digest('hex'),asset.sha256,asset.file+' matches stored artwork provenance');
  assert.equal(data.length,asset.size);
  if(asset.file.endsWith('.svg')){
    const text=data.toString();
    assert.match(text,/<svg\b/);
    assert.doesNotMatch(text,/\r/,'stored SVG uses LF line endings');
    assert.doesNotMatch(text,/[ \t]+$/m,'stored SVG has no trailing whitespace');
    assert.doesNotMatch(text,/<(?:script|foreignObject|iframe|image)\b|\son\w+\s*=|(?:href|xlink:href)\s*=\s*["'](?:https?:|\/\/|data:)|url\(\s*["']?https?:/i,'brand SVG must be passive and self-contained');
  }else assert.equal(data.subarray(0,8).toString('hex'),'89504e470d0a1a0a');
}
console.log('SEARCH3_OPERATOR_CARDS_OK aggregate=1 exact_offers=1 brands=4 provider_not_operator=1 frozen_source=1');
