<?php
declare(strict_types=1);
require_once __DIR__.'/../v2/site-page-shell-v1.php';
require_once __DIR__.'/../v2/seo-turkey-launch-dossier-v1.php';
require_once __DIR__.'/../v2/seo-second-wave-country-launch-dossier-v1.php';
function production_launch_fail(string $m):void{fwrite(STDERR,"SEO_PRODUCTION_CONTROLLED_LAUNCH_FAIL:$m\n");exit(1);}
$_SERVER['HTTP_HOST']='anytoour.ru';$_SERVER['DOCUMENT_ROOT']='/tmp/seo-production-launch-no-site-conf';
$turkey=v2_seo_turkey_launch_paths();$secondWave=v2_seo_second_wave_country_launch_paths();$sep=v2_seo_seasonal_september_launch_paths();$oct=v2_seo_seasonal_october_launch_paths();$seasonal=array_merge($sep,$oct);$expected=v2_seo_controlled_launch_paths();
if(count($turkey)!==6||count($secondWave)!==2||count($sep)!==2||count($oct)!==2||count($expected)!==12)production_launch_fail('launch_scope_count');
if($sep!==['/country/turkey/antalya/september/','/country/maldives/september/']||$oct!==['/country/turkey/antalya/october/','/country/maldives/october/'])production_launch_fail('seasonal_scope');
foreach($expected as $path){$_SERVER['REQUEST_URI']=$path;$ctx=sp_context($path,'Test','Test');if(!str_starts_with((string)($ctx['robots']??''),'index,follow'))production_launch_fail('launch_path_noindex:'.$path);}
foreach(['/poisk-turov/','/country/oae/','/country/turkey/hotel/rogue-hotel-999999/','/country/maldives/hotel/the-westin-maldives-miriandhoo-resort-65108/'] as $path){$_SERVER['REQUEST_URI']=$path;$ctx=sp_context($path,'Test','Test');if(!str_starts_with((string)($ctx['robots']??''),'noindex,follow'))production_launch_fail('non_launch_path_indexable:'.$path);}
$tmp=sys_get_temp_dir().'/seo-launch-rollback-'.bin2hex(random_bytes(4));mkdir($tmp,0700,true);file_put_contents($tmp.'/site_conf.php',"<?php\n\$params=['SEO_TURKEY_LAUNCH'=>false];\n");$_SERVER['DOCUMENT_ROOT']=$tmp;
foreach(array_merge(['/country/turkey/','/country/egypt/','/country/maldives/'],$seasonal) as $path){$_SERVER['REQUEST_URI']=$path;$ctx=sp_context($path,'Test','Test');if(!str_starts_with((string)($ctx['robots']??''),'noindex,follow'))production_launch_fail('rollback_override_failed:'.$path);}@unlink($tmp.'/site_conf.php');@rmdir($tmp);
$xml=file_get_contents(__DIR__.'/../v2/sitemap.xml');if($xml===false)production_launch_fail('sitemap_missing');preg_match_all('#<loc>([^<]+)</loc>#',$xml,$matches);$actual=array_values($matches[1]??[]);$expectedUrls=array_map(static fn(string $path):string=>'https://anytoour.ru'.$path,$expected);sort($actual,SORT_STRING);sort($expectedUrls,SORT_STRING);if($actual!==$expectedUrls||count($actual)!==12)production_launch_fail('sitemap_allowlist_drift');if(str_contains($xml,'/hotel/')||str_contains($xml,'/poisk-turov/'))production_launch_fail('sitemap_protected_route_leak');
$turkeyNow=1788368460;$turkeyDossier=v2_seo_turkey_launch_dossier($turkeyNow);if(($turkeyDossier['state']??'')!=='controlled_country_resort_launch_authorized'||($turkeyDossier['paths']??[])!==$turkey||count($turkeyDossier['rows']??[])!==6)production_launch_fail('turkey_dossier');if(($turkeyDossier['hotel_tours_indexation_allowed']??true)!==false)production_launch_fail('turkey_hotel_boundary');
$secondWaveNow=1788385200;$secondDossier=v2_seo_second_wave_country_launch_dossier($secondWaveNow);if(($secondDossier['state']??'')!=='second_wave_country_prelaunch_authorized'||($secondDossier['paths']??[])!==$secondWave)production_launch_fail('second_wave_dossier');if(($secondDossier['hotel_tours_indexation_allowed']??true)!==false)production_launch_fail('second_wave_hotel_boundary');
$snapshotSource=file_get_contents(__DIR__.'/../v2/seo-offer-snapshot-v1.php');$countryPageSource=file_get_contents(__DIR__.'/../v2/country-page-v1.php');$calendarSource=file_get_contents(__DIR__.'/../v2/seo-price-calendar-v1.php');if($snapshotSource===false||$countryPageSource===false||$calendarSource===false)production_launch_fail('country_offer_source_missing');
foreach(['function v2_seo_country_snapshot_offers',"s.page_type='country'",'s.expires_at>=NOW()',"s.currency='RUB'"] as $needle)if(!str_contains($snapshotSource,$needle))production_launch_fail('country_snapshot_contract:'.$needle);
foreach(["require_once __DIR__ . '/seo-offer-snapshot-v1.php'","require_once __DIR__ . '/seo-price-calendar-v1.php'",'v2_seo_country_snapshot_offers($countryId, 12)','array_slice($offerCandidates, 0, 6)','data-country-offer-snapshot','v2_seo_render_price_calendar'] as $needle)if(!str_contains($countryPageSource,$needle))production_launch_fail('country_offer_render_contract:'.$needle);
foreach(['tour_price_observations','INTERVAL 72 HOUR','v2_price_calendar_build','cachedPriceIsFinal'] as $needle)if(!str_contains($calendarSource,$needle))production_launch_fail('country_calendar_contract:'.$needle);
if(str_contains($countryPageSource,'tourvisor-client-v1.php')||str_contains($countryPageSource,'v2_data_tv_')||str_contains($countryPageSource,'curl_'))production_launch_fail('country_page_live_provider_call');
foreach($sep as $path)if(str_contains($path,'/hotel/')||!str_ends_with($path,'/september/'))production_launch_fail('september_path_boundary');foreach($oct as $path)if(str_contains($path,'/hotel/')||!str_ends_with($path,'/october/'))production_launch_fail('october_path_boundary');
echo "SEO_PRODUCTION_CONTROLLED_LAUNCH_OK paths=12 turkey=6 secondWave=2 seasonal=4 october=2 sitemap=12 hotelTours=0 rollback=1 evidence=1 countryOffers=firstPartyFreshOnly calendar=firstParty72h visibleCards=6\n";
