from pathlib import Path

source = Path('v2/site-footer-v1.css')
text = source.read_text()
old = '@media(max-width:640px){html body .ds2-site-footer[data-site-footer="shared"]{width:calc(100% - 20px)!important;margin-top:24px!important;border-radius:20px 20px 0 0!important}.ds2-site-footer[data-site-footer] .ds2-site-footer__inner{grid-template-columns:minmax(0,1fr);padding:28px 18px 22px;gap:24px}.ds2-site-footer[data-site-footer] .ds2-site-footer__brand>strong{font-size:18px}.ds2-site-footer[data-site-footer] .ds2-site-footer__navigation{border-left:0;border-top:1px solid #ffffff26;padding:20px 0 0;gap:16px}.ds2-site-footer[data-site-footer] .ds2-site-footer__support{flex-direction:column;align-items:flex-start;gap:0}.ds2-site-footer[data-site-footer] .ds2-site-footer__apps{grid-template-columns:1fr 1fr;gap:10px}.ds2-site-footer[data-site-footer] .ds2-site-footer__apps>div{grid-column:1/-1;margin-bottom:4px}.ds2-site-footer[data-site-footer] .ds2-site-footer__apps>a{min-width:0;padding:7px 9px;gap:6px}.ds2-site-footer[data-site-footer] .ds2-site-footer__store-icon{flex-basis:25px}.ds2-site-footer[data-site-footer] .ds2-site-footer__store-icon svg{width:25px;height:25px}.ds2-site-footer[data-site-footer] .ds2-site-footer__store-label b{font-size:14px}.ds2-site-footer[data-site-footer] .ds2-site-footer__store-label small{font-size:9px}.ds2-site-footer[data-site-footer] .ds2-site-footer__bottom{padding:16px 18px;flex-direction:column;align-items:flex-start}.ds2-site-footer[data-site-footer] .ds2-site-footer__payments{order:-1}}'
new = '@media(max-width:640px){html body .ds2-site-footer[data-site-footer="shared"]{width:calc(100% - 20px)!important;margin-top:20px!important;border-radius:20px 20px 0 0!important}.ds2-site-footer[data-site-footer] .ds2-site-footer__inner{grid-template-columns:minmax(0,1fr);padding:22px 18px 16px;gap:16px}.ds2-site-footer[data-site-footer] .ds2-site-footer__brand{gap:8px}.ds2-site-footer[data-site-footer] .ds2-site-footer__logo img{width:150px}.ds2-site-footer[data-site-footer] .ds2-site-footer__brand>strong{font-size:18px}.ds2-site-footer[data-site-footer] .ds2-site-footer__brand p{font-size:13px;line-height:1.5}.ds2-site-footer[data-site-footer] .ds2-site-footer__socials{gap:12px;margin-top:2px}.ds2-site-footer[data-site-footer] .ds2-site-footer__socials a{min-height:60px;gap:5px}.ds2-site-footer[data-site-footer] .ds2-site-footer__social-icon{width:40px;height:40px}.ds2-site-footer[data-site-footer] .ds2-site-footer__navigation{border-left:0;border-top:1px solid #ffffff26;padding:14px 0 0;gap:12px}.ds2-site-footer[data-site-footer] .ds2-site-footer__navigation strong{margin-bottom:6px}.ds2-site-footer[data-site-footer] .ds2-site-footer__support{flex-direction:row;align-items:center;flex-wrap:wrap;gap:4px 14px}.ds2-site-footer[data-site-footer] .ds2-site-footer__support>strong{margin:0}.ds2-site-footer[data-site-footer] .ds2-site-footer__apps{grid-template-columns:1fr 1fr;gap:8px;padding-top:16px}.ds2-site-footer[data-site-footer] .ds2-site-footer__apps>div{grid-column:1/-1;margin-bottom:0}.ds2-site-footer[data-site-footer] .ds2-site-footer__apps>a{min-width:0;min-height:48px;padding:6px 8px;gap:5px}.ds2-site-footer[data-site-footer] .ds2-site-footer__store-icon{flex-basis:24px}.ds2-site-footer[data-site-footer] .ds2-site-footer__store-icon svg{width:24px;height:24px}.ds2-site-footer[data-site-footer] .ds2-site-footer__store-label b{font-size:14px}.ds2-site-footer[data-site-footer] .ds2-site-footer__store-label small{font-size:9px}.ds2-site-footer[data-site-footer] .ds2-site-footer__bottom{padding:12px 18px 14px;flex-direction:row;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:8px 12px}.ds2-site-footer[data-site-footer] .ds2-site-footer__payments{order:0}}'
if text.count(old) != 1:
    raise SystemExit('mobile footer density anchor mismatch')
source.write_text(text.replace(old, new, 1))
