<?php
declare(strict_types=1);

require_once __DIR__.'/hotel_match_current_supplier_fuzzy_bridge.php';

const HMCA_OPERATION='hotel-match-user-seen-common4-samo-catalog-strong-acquire-1971-20260918-v6';
const HMCA_ROW_LIMIT=100000;
const HMCA_MAX_CATALOG_CALLS=400;
const HMCA_EXCLUDED_COUNTRIES=[46=>true,47=>true];
const HMCA_V3_RESULT='79812e2b71e8d0c201a7e5ff3132d1b68f3d6d00961c1dc26d7bca438e8d3d10';
const HMCA_V3_ARTIFACT=10525638655;
const HMCA_STRONG_MIN_SCORE=82;
const HMCA_STRONG_MIN_MARGIN=12;
const HMCA_STRONG_MIN_SYMMETRIC=0.75;

function hmca_rows(PDO $pdo,string $sql,array $params=[]): array {$s=$pdo->prepare($sql);$s->execute(array_values($params));$r=$s->fetchAll(PDO::FETCH_ASSOC)?:[];if(count($r)>HMCA_ROW_LIMIT)throw new RuntimeException('row_budget');return $r;}
function hmca_table(PDO $pdo,string $t): bool {$s=$pdo->prepare('SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? LIMIT 1');$s->execute([$t]);return $s->fetchColumn()!==false;}
function hmca_scalar(mixed $v,int $max=255): string {return is_scalar($v)?mb_substr(trim((string)$v),0,$max,'UTF-8'):'';}
function hmca_norm(string $v): string {$n=mb_strtolower(trim($v),'UTF-8');$n=strtr($n,['ё'=>'е','&'=>' ','+'=>' ','_'=>' ','-'=>' ','’'=>"'",'`'=>"'"]);$n=preg_replace('/[^\p{L}\p{N}]+/u',' ',$n)??$n;return trim(preg_replace('/\s+/u',' ',$n)??$n);}
function hmca_durable(string $path,array $v): string {$raw=json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n";$f=@fopen($path,'x+b');if(!$f)throw new RuntimeException('durable_exists');try{if(fwrite($f,$raw)!==strlen($raw)||!fflush($f))throw new RuntimeException('durable_write');if(function_exists('fsync')&&!fsync($f))throw new RuntimeException('durable_sync');rewind($f);if(stream_get_contents($f)!==$raw)throw new RuntimeException('durable_readback');}finally{fclose($f);}return hash('sha256',$raw);}
function hmca_product_hold(string $name): ?string {$raw=mb_strtolower(trim($name),'UTF-8');$n=hmca_norm($name);if(preg_match('/^(roulette|рулетка)(\s|$)/u',$n))return 'roulette_product_marker';if(!preg_match('/^(fortuna|фортуна)(\s|$)/u',$n))return null;if(preg_match('/^(fortuna|фортуна)\s+[1-5]\s*[*★]/u',$raw))return 'fortuna_star_product_marker';$tokens=preg_split('/\s+/u',$n,-1,PREG_SPLIT_NO_EMPTY)?:[];$physical=(bool)preg_match('/\b(hotel|hotels|otel|отель|resort)\b/u',$n);return $physical&&count($tokens)>=3?null:'fortuna_product_marker';}
function hmca_valid_key(string $n): bool {$generic=['hotel'=>1,'hotels'=>1,'otel'=>1,'отель'=>1,'resort'=>1,'spa'=>1,'apart'=>1,'apartment'=>1,'guesthouse'=>1,'guest'=>1,'house'=>1];$parts=preg_split('/\s+/u',$n,-1,PREG_SPLIT_NO_EMPTY)?:[];$sub=0;foreach($parts as $p)if(!isset($generic[$p])&&mb_strlen($p,'UTF-8')>=2)$sub++;return $n!==''&&mb_strlen($n,'UTF-8')>=4&&$sub>=1;}
function hmca_name_variants(string $name): array {
    $out=[];$add=function(string $v,string $why)use(&$out){$n=hmca_norm($v);if(hmca_valid_key($n))$out[$n][$why]=true;};$add($name,'canonical_full');
    if(preg_match('/^(.+?)\s*\((?:EX\.?|FORMERLY|БЫВШ\.?)[^)]*\)/iu',$name,$m))$add($m[1],'canonical_current');
    if(preg_match_all('/\((?:EX\.?|FORMERLY|БЫВШ\.?)\s*([^)]*)\)/iu',$name,$ms))foreach($ms[1] as $inside)foreach(preg_split('/[;|\/]+/u',$inside)?:[] as $part)$add($part,'explicit_former');
    $flat=[];foreach($out as $key=>$reasons){$rs=array_keys($reasons);sort($rs,SORT_STRING);$flat[$key]=$rs;}return $flat;
}
function hmca_aliases(string $value,array $map): array {$n=hmca_norm($value);$out=[$n=>true];foreach($map as $group)if(in_array($n,array_map('hmca_norm',$group),true))foreach($group as $v)$out[hmca_norm($v)]=true;return array_keys($out);}
function hmca_country_aliases(string $v): array {return hmca_aliases($v,[['Турция','Turkey','Turkiye','Türkiye'],['Египет','Egypt'],['ОАЭ','UAE','United Arab Emirates','Объединенные Арабские Эмираты'],['Мальдивы','Maldives'],['Вьетнам','Vietnam'],['Таиланд','Thailand'],['Куба','Cuba'],['Шри-Ланка','Sri Lanka'],['Катар','Qatar'],['Китай','China'],['Маврикий','Mauritius'],['Индонезия','Indonesia'],['Тунис','Tunisia'],['Индия','India'],['Танзания','Tanzania'],['Узбекистан','Uzbekistan'],['Марокко','Morocco'],['Сейшелы','Seychelles']]);}
function hmca_departure_aliases(string $v): array {return hmca_aliases($v,[['Москва','Moscow'],['Санкт-Петербург','Санкт Петербург','Saint Petersburg','St Petersburg'],['Екатеринбург','Yekaterinburg','Ekaterinburg'],['Казань','Kazan'],['Новосибирск','Novosibirsk'],['Самара','Samara'],['Уфа','Ufa'],['Челябинск','Chelyabinsk'],['Нижний Новгород','Nizhny Novgorod'],['Минеральные Воды','Mineralnye Vody'],['Пермь','Perm'],['Тюмень','Tyumen'],['Омск','Omsk'],['Красноярск','Krasnoyarsk'],['Иркутск','Irkutsk']]);}
function hmca_unique_dict_id(array $rows,array $aliases): ?int {$want=array_fill_keys($aliases,true);$hits=[];foreach($rows as $r){if(!is_array($r))continue;$id=(int)($r['id']??0);$name=hmca_norm(hmca_scalar($r['name']??'',180));if($id>0&&isset($want[$name]))$hits[$id]=true;}return count($hits)===1?(int)array_key_first($hits):null;}

function hmca_sources(array $v,array &$out): void {foreach($v as $k=>$x){if(($k==='source'||$k==='source_candidate')&&is_array($x))$out[]=$x;if(is_array($x))hmca_sources($x,$out);}}
function hmca_best_source(array $e): array {$xs=[];hmca_sources($e,$xs);$best=[];$score=-1;foreach($xs as $s){$x=0;if(hmca_scalar($s['townKey']??'',64)!=='')$x+=3;if(hmca_scalar($s['name']??$s['lName']??'',220)!=='')$x+=2;if(hmca_scalar($s['stateKey']??'',64)!=='')$x+=1;if($x>$score){$score=$x;$best=$s;}}return $best;}
function hmca_consensus(array $set): ?string {$x=array_keys($set);return count($x)===1?(string)$x[0]:null;}
function hmca_number_sig(string $key): array {$out=[];foreach(preg_split('/\s+/u',$key,-1,PREG_SPLIT_NO_EMPTY)?:[] as $t)if(preg_match('/^[0-9]+$/D',$t))$out[$t]=true;$x=array_map('strval',array_keys($out));sort($x,SORT_STRING);return $x;}
function hmca_qualifier_sig(string $key): array {$q=['annex'=>1,'beach'=>1,'garden'=>1,'gardens'=>1,'north'=>1,'south'=>1,'posh'=>1,'adult'=>1,'adults'=>1,'pool'=>1,'sea'=>1,'view'=>1,'prestige'=>1,'aquamarine'=>1,'family'=>1,'deluxe'=>1,'suite'=>1,'club'=>1,'royal'=>1];$out=[];foreach(preg_split('/\s+/u',$key,-1,PREG_SPLIT_NO_EMPTY)?:[] as $t)if(isset($q[$t]))$out[$t]=true;$x=array_keys($out);sort($x,SORT_STRING);return $x;}
function hmca_rankable_name(string $v): bool {$n=hmca_norm($v);if($n===''||preg_match('/\\p{L}/u',$n)!==1||!hmca_valid_key($n))return false;$keys=hmsb_keys($v);if(!$keys)return false;foreach($keys as $k)if(!is_string($k)||preg_match('/\\p{L}/u',$k)!==1)return false;return true;}
function hmca_town_labels(array $row): array {$out=[];foreach(['name','lName','label','title','region','regionName','parent','parentName'] as $k){$v=hmca_scalar($row[$k]??'',160);if($v!=='')$out[$v]=true;}return array_keys($out);}
function hmca_geo(array $provider,array $local,array $crosswalk,array $crossConflicts): array {
    $townKey=(string)($provider['town_key']??'');$ck=(int)$local['country_id'].'|'.$townKey;
    if($townKey!==''&&isset($crossConflicts[$ck]))return ['clean'=>false,'route'=>'accepted_town_crosswalk_conflict','direct'=>false,'crosswalk'=>false];
    $direct=fc_place($provider['town_labels']??[],[(string)($local['region_name']??''),(string)($local['subregion_name']??'')]);
    $cross=$townKey!==''?($crosswalk[$ck]??null):null;$crossOk=false;
    if(is_array($cross)){
        $rid=(int)($local['region_id']??0);$sid=(int)($local['subregion_id']??0);
        $crossOk=(($cross['region_id']!==null&&$rid===$cross['region_id'])||($cross['subregion_id']!==null&&$sid===$cross['subregion_id']));
        if(!$crossOk)return ['clean'=>false,'route'=>'accepted_town_crosswalk_mismatch','direct'=>$direct,'crosswalk'=>false];
    }
    return ['clean'=>$direct||$crossOk,'route'=>$direct?'direct_townto_label':($crossOk?'accepted_town_crosswalk':'geography_unproven'),'direct'=>$direct,'crosswalk'=>$crossOk];
}

function hmca_catalog_call(array $session,string $action,array $params,int &$calls,float &$last): array {if(++$calls>HMCA_MAX_CATALOG_CALLS)throw new RuntimeException('catalog_call_budget');$wait=1.05-(microtime(true)-$last);if($wait>0)usleep((int)ceil($wait*1000000));$last=microtime(true);$tr=new AnyTourAndromedaTransport(false,false);$cl=new AnyTourAndromedaClient($tr,true);$cl->restorePrivateSession($session);return $cl->catalog($action,$params);}

if(in_array('--self-test',$argv??[],true)){
    if(hmca_product_hold('FORTUNA MARMARIS')===null||hmca_product_hold('FORTUNA HOTEL PHU QUOC')!==null)throw new RuntimeException('product_filter');
    $v=hmca_name_variants('SUN BAY (EX. SUN MARIS PARK)');if(!isset($v['sun bay'],$v['sun maris park']))throw new RuntimeException('name_variants');
    if(!in_array('turkey',hmca_country_aliases('Турция'),true)||!in_array('tanzania',hmca_country_aliases('Танзания'),true)||!in_array('uzbekistan',hmca_country_aliases('Узбекистан'),true)||!in_array('moscow',hmca_departure_aliases('Москва'),true))throw new RuntimeException('aliases');
    if(HMCA_MAX_CATALOG_CALLS!==400||!isset(HMCA_EXCLUDED_COUNTRIES[46],HMCA_EXCLUDED_COUNTRIES[47]))throw new RuntimeException('global_limits');
    $ti=[];$tn=[];hmsbf_add_target($ti,$tn,4,1,['Grand Sunrise Beach Palace']);hmsbf_add_target($ti,$tn,4,2,['Grand Sunrise City Hotel']);
    $rr=hmsbf_rank(['Sunrise Grand Beach'],4,$ti,$tn);if(($rr['status']??'')!=='ranked'||(int)($rr['best']['local_id']??0)!==1)throw new RuntimeException('strong_rank');
    if(hmca_number_sig('royal 2 sea')!==['2']||hmca_qualifier_sig('family sea view deluxe')!==['deluxe','family','sea','view'])throw new RuntimeException('strong_guards');
    if(hmca_rankable_name('12345')||hmca_rankable_name('Hotel 123')||!hmca_rankable_name('Hotel Alpha 123'))throw new RuntimeException('rankable_name');
    echo "MATCH_COMMON4_SAMO_CATALOG_STRONG_ACQUIRE_SELFTEST_OK\n";exit(0);
}
if(PHP_SAPI!=='cli')exit(2);

require_once __DIR__.'/andromeda-client.php';
require_once __DIR__.'/andromeda-transport.php';

$opDir=(string)getenv('MATCH_OPERATION_DIR');$sourceSha=(string)getenv('MATCH_SOURCE_SHA');$root=realpath((string)getenv('ANYTOUR_ROOT'));$registryPath=realpath((string)getenv('MATCH_MAPPING_REGISTRY_PATH'));
if(!$root||$opDir===''||!preg_match('/^[a-f0-9]{40}$/D',$sourceSha)||!is_string($registryPath)||!is_file($registryPath)||!is_dir($opDir)||!is_file($opDir.'/reservation.json'))throw new RuntimeException('runtime_guard');
$res=json_decode((string)file_get_contents($opDir.'/reservation.json'),true,32,JSON_THROW_ON_ERROR);if(($res['operation']??'')!==HMCA_OPERATION||($res['state']??'')!=='reserved_before_provider_access')throw new RuntimeException('reservation_guard');
require_once $registryPath;$dbf=is_file($root.'/data/db-v1.php')?$root.'/data/db-v1.php':$root.'/v2/data/db-v1.php';require_once $dbf;$pdo=v2_data_db();$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
foreach(['tour_price_observations','catalog_hotels','catalog_departures','hotel_aliases','anex_hotel_search_mappings','anex_hotel_decisions','andromeda_hotel_identities'] as $t)if(!hmca_table($pdo,$t))throw new RuntimeException('missing_'.$t);
$providerAccess=false;$calls=0;$loginCalls=0;$catalogCalls=0;$last=0.0;
try{
    $pdo->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$pdo->exec('START TRANSACTION READ ONLY');
    $registry=AnyTourAnexSearchMappingRegistry::fromPdo($pdo);$anexTargets=[];foreach(hmca_rows($pdo,'SELECT anex_hotel_id FROM anex_hotel_search_mappings UNION SELECT anex_hotel_id FROM anex_hotel_decisions') as $r){$x=$registry->resolve('anex_online',(string)$r['anex_hotel_id'],'preview');if(is_int($x)&&$x>0)$anexTargets[$x]=true;}
    $identityRows=hmca_rows($pdo,"SELECT supplier_namespace,external_hotel_id,local_hotel_id,decision_status,evidence_sha256,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog'");$occupied=[];foreach($identityRows as $r){$e=hmca_scalar($r['external_hotel_id']??'',64);if($e!=='')$occupied[$e][]=['local_hotel_id'=>$r['local_hotel_id']===null?null:(int)$r['local_hotel_id'],'decision_status'=>hmca_scalar($r['decision_status']??'',60),'evidence_sha256'=>hmca_scalar($r['evidence_sha256']??'',80)];}
    $andTargets=[];foreach($identityRows as $r)if(($r['decision_status']??'')==='accepted'&&$r['local_hotel_id']!==null)$andTargets[(int)$r['local_hotel_id']]=true;
    $seen=[];foreach(hmca_rows($pdo,"SELECT hotel_id,MAX(observed_at) last_observed_at,COUNT(*) observation_rows FROM tour_price_observations WHERE source='user_search' GROUP BY hotel_id") as $r){$id=(int)$r['hotel_id'];if($id>0)$seen[$id]=['last'=>(string)$r['last_observed_at'],'rows'=>(int)$r['observation_rows']];}
    $ids=array_keys($seen);if(!$ids)throw new RuntimeException('no_seen');$ph=implode(',',array_fill(0,count($ids),'?'));
    $frontier=[];foreach(hmca_rows($pdo,"SELECT id,country_id,country_name,region_id,region_name,subregion_id,subregion_name,name,is_active FROM catalog_hotels WHERE id IN ($ph)",$ids) as $r){$id=(int)$r['id'];if((int)$r['is_active']!==1||isset(HMCA_EXCLUDED_COUNTRIES[(int)$r['country_id']])||isset($anexTargets[$id])||isset($andTargets[$id])||hmca_product_hold((string)$r['name'])!==null)continue;$frontier[$id]=['hotel_id'=>$id,'hotel_name'=>(string)$r['name'],'country_id'=>(int)$r['country_id'],'country_name'=>(string)$r['country_name'],'region_id'=>$r['region_id']===null?null:(int)$r['region_id'],'region_name'=>(string)($r['region_name']??''),'subregion_id'=>$r['subregion_id']===null?null:(int)$r['subregion_id'],'subregion_name'=>(string)($r['subregion_name']??''),'user_observation_rows'=>$seen[$id]['rows'],'last_user_observed_at'=>$seen[$id]['last']];}
    $fids=array_keys($frontier);if(!$fids)throw new RuntimeException('frontier_empty');$fh=implode(',',array_fill(0,count($fids),'?'));
    $priceRows=hmca_rows($pdo,"SELECT hotel_id,operator_id,departure_id,country_id,departure_date,nights,adults,children_count,child_ages_signature,room_type,observed_at,COUNT(*) OVER(PARTITION BY hotel_id,operator_id) hotel_operator_rows FROM tour_price_observations WHERE source='user_search' AND hotel_id IN ($fh) AND departure_date>=CURRENT_DATE AND operator_id IN(13,18,25,43) ORDER BY observed_at DESC",$fids);
    $departures=[];foreach(hmca_rows($pdo,'SELECT id,name FROM catalog_departures WHERE is_active=1') as $r)$departures[(int)$r['id']]=(string)$r['name'];
    $tv=[13=>['family'=>'anex','samo_operator_id'=>5],18=>['family'=>'biblio','samo_operator_id'=>115],25=>['family'=>'funsun','samo_operator_id'=>315],43=>['family'=>'intourist','samo_operator_id'=>342]];
    $contexts=[];$targetLocals=[];$countryNames=[];$countryIds=[];
    foreach($priceRows as $r){$hid=(int)$r['hotel_id'];$oid=(int)$r['operator_id'];$dep=(int)$r['departure_id'];$country=(int)$r['country_id'];if(!isset($frontier[$hid],$tv[$oid])||!isset($departures[$dep])||$country!==$frontier[$hid]['country_id'])continue;$key=$dep.'|'.$country;$contexts[$key]['departure_id']=$dep;$contexts[$key]['departure_name']=$departures[$dep];$contexts[$key]['country_id']=$country;$contexts[$key]['country_name']=$frontier[$hid]['country_name'];$contexts[$key]['target_local_ids'][$hid]=true;$contexts[$key]['operators'][$tv[$oid]['family']]=true;$targetLocals[$hid]=true;$countryNames[$country]=$frontier[$hid]['country_name'];$countryIds[$country]=true;}
    if(!$contexts)throw new RuntimeException('no_future_common4_contexts');
    $cids=array_keys($countryIds);$cph=implode(',',array_fill(0,count($cids),'?'));
    $allLocal=[];$localNames=[];$tokenIndex=[];$targetNames=[];
    foreach(hmca_rows($pdo,"SELECT id,country_id,country_name,name,region_id,region_name,subregion_id,subregion_name,category FROM catalog_hotels WHERE is_active=1 AND country_id IN ($cph)",$cids) as $r){$lid=(int)$r['id'];$cid=(int)$r['country_id'];$allLocal[$lid]=$r;$localNames[$lid][(string)$r['name']]=true;}
    foreach(hmca_rows($pdo,"SELECT a.hotel_id,a.alias,h.country_id FROM hotel_aliases a JOIN catalog_hotels h ON h.id=a.hotel_id WHERE h.is_active=1 AND h.country_id IN ($cph)",$cids) as $r){$lid=(int)$r['hotel_id'];$v=trim((string)$r['alias']);if($v!==''&&isset($allLocal[$lid]))$localNames[$lid][$v]=true;}
    foreach($localNames as $lid=>$set){$h=$allLocal[$lid];$rankable=array_values(array_filter(array_keys($set),fn($v)=>is_string($v)&&hmca_rankable_name($v)));if($rankable)hmsbf_add_target($tokenIndex,$targetNames,(int)$h['country_id'],(int)$lid,$rankable);}
    $townSets=[];$townCrossConflicts=[];$acceptedTownRows=0;
    foreach($identityRows as $r){if(($r['decision_status']??'')!=='accepted'||$r['local_hotel_id']===null)continue;$lid=(int)$r['local_hotel_id'];$h=$allLocal[$lid]??null;if(!$h)continue;try{$e=json_decode((string)($r['evidence_json']??''),true,128,JSON_THROW_ON_ERROR);}catch(Throwable){continue;}$s=hmca_best_source($e);if(!$s)continue;$tk=hmca_scalar($s['townKey']??$s['town_key']??$s['supplier_town_id']??'',64);if($tk==='')continue;$key=(int)$h['country_id'].'|'.$tk;$rid=(int)($h['region_id']??0);$sid=(int)($h['subregion_id']??0);if($rid>0)$townSets[$key]['region'][(string)$rid]=true;if($sid>0)$townSets[$key]['sub'][(string)$sid]=true;$townSets[$key]['rows']=($townSets[$key]['rows']??0)+1;$acceptedTownRows++;}
    $townCrosswalk=[];foreach($townSets as $key=>$x){$rg=$x['region']??[];$sb=$x['sub']??[];$r=hmca_consensus($rg);$s=hmca_consensus($sb);if(($rg&&$r===null)||($sb&&$s===null)){$townCrossConflicts[$key]=true;continue;}if($r!==null||$s!==null)$townCrosswalk[$key]=['region_id'=>$r===null?null:(int)$r,'subregion_id'=>$s===null?null:(int)$s,'accepted_rows'=>(int)($x['rows']??0)];}
    $pdo->rollBack();

    $stdin=file('php://stdin',FILE_IGNORE_NEW_LINES);$username=trim((string)($stdin[0]??''));$password=trim((string)($stdin[1]??''));unset($stdin);
    if($username===''||$password==='')throw new RuntimeException('credentials_missing');
    $providerAccess=true;$loginCalls=1;$calls=1;$tr=new AnyTourAndromedaTransport(false,false);$login=new AnyTourAndromedaClient($tr,true);$login->login($username,$password);$session=$login->privateSession();unset($username,$password,$login,$tr);if(!$session)throw new RuntimeException('login_session');
    $townPayload=hmca_catalog_call($session,'townfrom',[],$catalogCalls,$last);$calls++;
    $townRows=$townPayload['TOWNFROM'];$departureBindings=[];$unboundDepartures=[];
    $neededDeps=[];foreach($contexts as $c)$neededDeps[(int)$c['departure_id']]=$c['departure_name'];
    foreach($neededDeps as $depId=>$depName){$pid=hmca_unique_dict_id($townRows,hmca_departure_aliases($depName));if($pid)$departureBindings[$depId]=['provider_departure_id'=>$pid,'provider_departure_name'=>$depName];else $unboundDepartures[$depId]=$depName;}

    $stateBindings=[];$unboundStates=[];$stateCatalogs=[];
    foreach($departureBindings as $depId=>$binding){$reply=hmca_catalog_call($session,'state',['TOWNFROMINC'=>$binding['provider_departure_id']],$catalogCalls,$last);$calls++;$stateCatalogs[$depId]=$reply['STATE'];$neededCountries=[];foreach($contexts as $c)if((int)$c['departure_id']===$depId)$neededCountries[(int)$c['country_id']]=$c['country_name'];foreach($neededCountries as $cid=>$cname){$sid=hmca_unique_dict_id($reply['STATE'],hmca_country_aliases($cname));if($sid)$stateBindings[$depId.'|'.$cid]=['provider_state_id'=>$sid,'country_name'=>$cname];else$unboundStates[$depId.'|'.$cid]=$cname;}}

    $providerByPair=[];$pairMeta=[];
    foreach($contexts as $key=>$ctx){$dep=(int)$ctx['departure_id'];$cid=(int)$ctx['country_id'];if(!isset($departureBindings[$dep],$stateBindings[$key]))continue;$pd=$departureBindings[$dep]['provider_departure_id'];$ps=$stateBindings[$key]['provider_state_id'];$reply=hmca_catalog_call($session,'all',['TOWNFROMINC'=>$pd,'STATEINC'=>$ps],$catalogCalls,$last);$calls++;$hotels=$reply['HOTELS'];$towns=[];foreach(($reply['TOWNTO']??[]) as $t){if(!is_array($t))continue;$tid=hmca_scalar($t['id']??'',64);if($tid!=='')$towns[$tid]=hmca_town_labels($t);} $rows=[];foreach($hotels as $h){if(!is_array($h))continue;$id=hmca_scalar($h['id']??'',64);$name=hmca_scalar($h['name']??'',220);$lname=hmca_scalar($h['lName']??'',220);if(!preg_match('/^[1-9][0-9]{0,31}$/D',$id)||hmca_product_hold($name)!==null)continue;$names=array_values(array_filter([$name,$lname],fn($v)=>is_string($v)&&hmca_rankable_name($v)));if(!$names)continue;$tk=hmca_scalar($h['townKey']??'',64);$rows[]=['external_hotel_id'=>$id,'supplier_name'=>$name,'source_names'=>$names,'town_key'=>$tk?:null,'town_labels'=>$tk!==''?($towns[$tk]??[]):[],'star_key'=>hmca_scalar($h['starKey']??'',64)?:null];}$providerByPair[$key]=$rows;$pairMeta[$key]=['departure_id'=>$dep,'departure_name'=>$ctx['departure_name'],'provider_departure_id'=>$pd,'country_id'=>$cid,'country_name'=>$ctx['country_name'],'provider_state_id'=>$ps,'provider_hotel_rows'=>count($hotels),'provider_town_rows'=>count($towns),'target_local_count'=>count($ctx['target_local_ids'])];}

    $candidateByPair=[];$localCandidateEvidence=[];$providerToLocals=[];$reasonCounts=[];$rankedRows=0;
    foreach($providerByPair as $key=>$providerRows){$ctx=$contexts[$key];$cid=(int)$ctx['country_id'];foreach($providerRows as $p){$rank=hmsbf_rank($p['source_names'],$cid,$tokenIndex,$targetNames);if(($rank['status']??'')!=='ranked'){$reasonCounts['rank_'.$rank['status']]=($reasonCounts['rank_'.$rank['status']]??0)+1;continue;}$rankedRows++;$best=$rank['best']??[];$hid=(int)($best['local_id']??0);if($hid<1||!isset($ctx['target_local_ids'][$hid],$frontier[$hid])){$reasonCounts['best_not_current_context_target']=($reasonCounts['best_not_current_context_target']??0)+1;continue;}
        if((int)($best['score']??0)<HMCA_STRONG_MIN_SCORE||(int)($best['common']??0)<2||(float)($best['symmetric']??0)<HMCA_STRONG_MIN_SYMMETRIC||(int)($rank['margin']??0)<HMCA_STRONG_MIN_MARGIN){$reasonCounts['below_strong_threshold']=($reasonCounts['below_strong_threshold']??0)+1;continue;}
        if(($best['qualifier_conflict']??false)||hmca_qualifier_sig((string)($best['source_key']??''))!==hmca_qualifier_sig((string)($best['target_key']??''))){$reasonCounts['qualifier_conflict']=($reasonCounts['qualifier_conflict']??0)+1;continue;}
        if(hmca_number_sig((string)($best['source_key']??''))!==hmca_number_sig((string)($best['target_key']??''))){$reasonCounts['number_conflict']=($reasonCounts['number_conflict']??0)+1;continue;}
        $local=$frontier[$hid];$geo=hmca_geo($p,$local,$townCrosswalk,$townCrossConflicts);if(!$geo['clean']){$reasonCounts[$geo['route']]=($reasonCounts[$geo['route']]??0)+1;continue;}
        $ext=$p['external_hotel_id'];$occ=$occupied[$ext]??[];$blocked=false;$occReasons=[];foreach($occ as $o){$st=$o['decision_status']??'';$ol=$o['local_hotel_id']??null;if($st==='accepted'&&$ol!==null&&(int)$ol!==$hid){$blocked=true;$occReasons[]='accepted_elsewhere';}elseif(in_array($st,['conflict','rejected','excluded'],true)){$blocked=true;$occReasons[]='current_'.$st;}elseif($ol!==null&&(int)$ol!==$hid){$blocked=true;$occReasons[]='occupied_other_local';}}
        if($blocked){$reasonCounts['current_identity_hold']=($reasonCounts['current_identity_hold']??0)+1;continue;}
        $ev=$local+['external_hotel_id'=>$ext,'supplier_name'=>$p['supplier_name'],'provider_departure_id'=>$pairMeta[$key]['provider_departure_id'],'provider_state_id'=>$pairMeta[$key]['provider_state_id'],'departure_id'=>$pairMeta[$key]['departure_id'],'departure_name'=>$pairMeta[$key]['departure_name'],'town_key'=>$p['town_key'],'town_labels'=>$p['town_labels'],'star_key'=>$p['star_key'],'score'=>(int)$best['score'],'common_tokens'=>(int)$best['common'],'symmetric_coverage'=>(float)$best['symmetric'],'runner_up_local_id'=>$rank['runner_up']['local_id']??null,'runner_up_score'=>$rank['runner_up']['score']??null,'margin'=>(int)$rank['margin'],'best_source_key'=>$best['source_key'],'best_target_key'=>$best['target_key'],'geography'=>$geo,'current_identity_holds'=>array_values(array_unique($occReasons))];
        $candidateByPair[$key][$hid.'|'.$ext]=$ev;$localCandidateEvidence[$hid][$ext][]=['pair'=>$key,'score'=>$ev['score'],'margin'=>$ev['margin'],'geo_route'=>$geo['route']];$providerToLocals[$ext][$hid]=true;
    }}
    $safe=[];$ambiguous=[];foreach($localCandidateEvidence as $hid=>$byExt){if(count($byExt)!==1){$ambiguous[]=['hotel_id'=>$hid,'hotel_name'=>$frontier[$hid]['hotel_name'],'reason'=>'multiple_provider_ids','external_hotel_ids'=>array_keys($byExt)];continue;}$ext=(string)array_key_first($byExt);if(count($providerToLocals[$ext]??[])!==1){$ambiguous[]=['hotel_id'=>$hid,'hotel_name'=>$frontier[$hid]['hotel_name'],'reason'=>'provider_id_multiple_target_locals','external_hotel_id'=>$ext,'local_ids'=>array_keys($providerToLocals[$ext])];continue;}$examples=[];foreach($candidateByPair as $pair=>$rows)if(isset($rows[$hid.'|'.$ext]))$examples[]=$rows[$hid.'|'.$ext];$base=$examples[0]??null;if(!$base)continue;$safe[]=$base+['independent_context_count'=>count($examples),'context_evidence'=>array_map(fn($e)=>['departure_id'=>$e['departure_id'],'departure_name'=>$e['departure_name'],'provider_departure_id'=>$e['provider_departure_id'],'provider_state_id'=>$e['provider_state_id'],'score'=>$e['score'],'margin'=>$e['margin'],'geo_route'=>$e['geography']['route']],$examples)];}
    usort($safe,fn($a,$b)=>$b['user_observation_rows']<=>$a['user_observation_rows'] ?: $b['independent_context_count']<=>$a['independent_context_count'] ?: $b['score']<=>$a['score'] ?: $a['hotel_id']<=>$b['hotel_id']);
    $familyPotential=[];foreach($priceRows as $r){$hid=(int)$r['hotel_id'];$oid=(int)$r['operator_id'];if(isset($targetLocals[$hid],$tv[$oid]))$familyPotential[$tv[$oid]['family']][$hid]=true;}
    $result=['operation'=>HMCA_OPERATION,'state'=>'completed_read_only','source_sha'=>$sourceSha,'provider_access'=>true,'login_calls'=>$loginCalls,'catalog_calls'=>$catalogCalls,'provider_calls'=>$calls,'price_calls'=>0,'tourvisor_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true,'frontier_count'=>count($frontier),'future_real_common4_locals'=>count($targetLocals),'context_pair_count'=>count($contexts),'bound_departure_count'=>count($departureBindings),'unbound_departures'=>$unboundDepartures,'bound_pair_count'=>count($pairMeta),'unbound_states'=>$unboundStates,'pair_meta'=>$pairMeta,'family_potential_unique_hotels'=>array_map('count',$familyPotential),'strong_catalog_candidate_count'=>count($safe),'strong_catalog_candidates'=>$safe,'ranked_provider_rows'=>$rankedRows,'accepted_town_crosswalk_keys'=>count($townCrosswalk),'accepted_town_crosswalk_conflicts'=>count($townCrossConflicts),'accepted_town_evidence_rows'=>$acceptedTownRows,'ambiguous_candidate_count'=>count($ambiguous),'ambiguous_candidates'=>array_slice($ambiguous,0,200),'hold_reason_counts'=>$reasonCounts,'operator_binding_provenance'=>['artifact_id'=>HMCA_V3_ARTIFACT,'result_sha256'=>HMCA_V3_RESULT,'tv_to_samo'=>['13'=>5,'18'=>115,'25'=>315,'43'=>342]]];
}catch(Throwable $e){if(isset($pdo)&&$pdo->inTransaction())$pdo->rollBack();$result=['operation'=>HMCA_OPERATION,'state'=>$providerAccess?'terminal_failed_no_replay':'failed_before_provider_access','source_sha'=>$sourceSha,'reason'=>preg_replace('/[^a-z0-9_\-]/i','_',mb_substr($e->getMessage(),0,100)),'provider_access'=>$providerAccess,'login_calls'=>$loginCalls,'catalog_calls'=>$catalogCalls,'provider_calls'=>$calls,'price_calls'=>0,'tourvisor_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>$providerAccess];}
$sha=hmca_durable($opDir.'/result.json',$result);hmca_durable($opDir.'/receipt.json',['operation'=>HMCA_OPERATION,'state'=>$result['state'],'result_sha256'=>$sha,'provider_access'=>$result['provider_access'],'provider_calls'=>$result['provider_calls'],'price_calls'=>0,'tourvisor_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>$result['no_replay']]);echo json_encode($result,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";exit(($result['state']??'')==='completed_read_only'?0:2);
