<?php
declare(strict_types=1);
putenv('MATCH_OPERATOR_ANCHOR_V4_TEST_LIBRARY=1');
require_once __DIR__.'/hotel_match_operator_current_anchor_review_v4.php';

const OCAR6_OP='hotel-match-operator-current-anchor-review-1971-20260915-v6';
function ocar6_json(array $v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";}
function ocar6_write(string $file,array $v):string{$raw=ocar6_json($v);$f=@fopen($file,'x+b');if(!$f)throw new RuntimeException('exclusive_file');try{if(fwrite($f,$raw)!==strlen($raw)||!fflush($f))throw new RuntimeException('write');if(function_exists('fsync')&&!fsync($f))throw new RuntimeException('sync');rewind($f);if(stream_get_contents($f)!==$raw)throw new RuntimeException('readback');}finally{fclose($f);}return hash('sha256',$raw);}
if(getenv('MATCH_OPERATOR_ANCHOR_V6_TEST_LIBRARY')==='1')return;
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
$op=(string)getenv('MATCH_OPERATION_ID');$sha=(string)getenv('MATCH_SOURCE_SHA');if($op!==OCAR6_OP||!preg_match('/^[0-9a-f]{40}$/D',$sha))throw new RuntimeException('operation_environment');$home=(string)getenv('HOME');if($home==='')throw new RuntimeException('home');$dir=$home.'/.anytoour-match/operations/'.OCAR6_OP;$res=json_decode((string)@file_get_contents($dir.'/reservation.json'),true,32,JSON_THROW_ON_ERROR);if(($res['operation_id']??'')!==OCAR6_OP||($res['source_sha']??'')!==$sha||($res['state']??'')!=='reserved_before_db_access')throw new RuntimeException('reservation');$root=realpath(getcwd());if(!$root||basename($root)!=='anytoour.ru')throw new RuntimeException('root');require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION READ ONLY');
try{$pending=opb_query($db,"SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace IN ('operator_315','operator_342') AND decision_status='pending' AND local_hotel_id IS NULL ORDER BY supplier_namespace,external_hotel_id");$anchors=[];foreach(opb_query($db,"SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IS NOT NULL ORDER BY external_hotel_id") as $a)$anchors[(string)$a['external_hotel_id']]=$a;$hotels=[];foreach(opb_query($db,'SELECT id,country_id,name,latitude,longitude,is_active FROM catalog_hotels WHERE is_active=1 ORDER BY id') as $h)$hotels[(int)$h['id']]=$h;$x=ocar4_evaluate($pending,$anchors,$hotels);$result=['schema'=>'hotel-match-operator-current-anchor-review/6','operation_id'=>OCAR6_OP,'source_sha'=>$sha,'state'=>'completed_read_only','server_current'=>true,'examined'=>count($pending),'safe_count'=>count($x['safe']),'safe_by_operator'=>$x['safe_by_operator'],'safe'=>$x['safe'],'holds_count'=>count($x['holds']),'hold_reasons'=>$x['hold_reasons'],'holds'=>$x['holds'],'db_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'external_calls'=>0,'booking_calls'=>0,'operator_5_writes'=>0,'no_replay'=>true,'completed_at'=>gmdate('c')];$hash=ocar6_write($dir.'/result.json',$result);$raw=(string)file_get_contents($dir.'/result.json');$ok=hash('sha256',$raw)===$hash;ocar6_write($dir.'/receipt.json',['operation_id'=>OCAR6_OP,'source_sha'=>$sha,'state'=>'completed_read_only','result_sha256'=>$hash,'readback_verified'=>$ok,'examined'=>count($pending),'safe_count'=>count($x['safe']),'db_writes'=>0,'supplier_calls'=>0,'operator_5_writes'=>0,'no_replay'=>true]);if(!$ok)throw new RuntimeException('readback');$db->rollBack();echo ocar6_json(['state'=>'completed_read_only','examined'=>count($pending),'safe_count'=>count($x['safe']),'safe_by_operator'=>$x['safe_by_operator'],'hold_reasons'=>$x['hold_reasons'],'result_sha256'=>$hash]);}catch(Throwable $e){if($db->inTransaction())$db->rollBack();if(!is_file($dir.'/failure.json'))ocar6_write($dir.'/failure.json',['operation_id'=>OCAR6_OP,'source_sha'=>$sha,'state'=>'read_only_failed','error_class'=>get_class($e),'reason'=>preg_match('/^[A-Za-z0-9_]+$/D',$e->getMessage())?$e->getMessage():'sanitized_error','db_writes'=>0,'supplier_calls'=>0,'operator_5_writes'=>0,'no_replay'=>true]);throw$e;}
