<?php
declare(strict_types=1);
const V41_OP='hotel-match-tv-samo-fingerprint-collision-refinement-1971-20260925-v41';
const V41_V40B_OP='hotel-match-tv-samo-fingerprint-correction-readiness-1971-20260925-v40b';
function v41_need(bool $v,string $m):void{if(!$v)throw new RuntimeException($m);}
function v41_json(mixed $v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
function v41_load(string $p):array{$v=json_decode((string)file_get_contents($p),true,256,JSON_THROW_ON_ERROR);v41_need(is_array($v),'json_shape');return$v;}
function v41_save(string $p,array $v):string{$raw=v41_json($v)."\n";$f=@fopen($p,'x+b');v41_need($f!==false,'exclusive_create');try{v41_need(fwrite($f,$raw)===strlen($raw)&&fflush($f),'write');if(function_exists('fsync'))v41_need(fsync($f),'sync');}finally{fclose($f);}return hash('sha256',$raw);}
function v41_shared(array $direct,array $current):array{$out=[];foreach($direct as$ns=>$ids){$a=array_map('strval',is_array($ids)?$ids:[]);$b=array_map('strval',is_array($current[$ns]??null)?$current[$ns]:[]);$x=array_values(array_unique(array_intersect($a,$b)));sort($x,SORT_NATURAL);if($x)$out[$ns]=$x;}return$out;}
function v41_classify(array $r):array{$shared=v41_shared($r['v37_direct_fingerprints']??[],$r['current_operator_lanes']??[]);$d=$r['candidate_current_distance_m']??null;$j=(float)($r['candidate_current_name_jaccard']??0);if($shared){$status=($d!==null&&(float)$d<=100&&$j>=0.4)?'duplicate_local_hold':'conflicting_operator_identity_hold';}else$status='correction_ready';return['status'=>$status,'shared_current_direct_fingerprints'=>$shared,'candidate_current_distance_m'=>$d,'candidate_current_name_jaccard'=>$j];}
function v41_execute(string $resultPath,string $receiptPath,string $sourceSha):array{$raw=(string)file_get_contents($resultPath);$sha=hash('sha256',$raw);$r=json_decode($raw,true,256,JSON_THROW_ON_ERROR);$q=v41_load($receiptPath);v41_need(is_array($r)&&($r['operation']??'')===V41_V40B_OP&&($r['state']??'')==='completed_read_only_fingerprint_correction_readiness','v40b_state');v41_need(($q['result_sha256']??'')===$sha&&($q['readback_verified']??false)===true,'v40b_receipt');v41_need((int)($r['input_count']??0)===4,'input_count');$rows=[];$counts=[];foreach($r['rows']??[] as$x){if(!is_array($x))continue;$y=v41_classify($x);$status=$y['status'];$counts[$status]=($counts[$status]??0)+1;$rows[]=['andromeda_catalog_id'=>(string)($x['andromeda_catalog_id']??''),'candidate_local_hotel_id'=>(int)($x['candidate_local_hotel_id']??0),'current_local_hotel_id'=>(int)($x['current_local_hotel_id']??0),'status'=>$status,'shared_current_direct_fingerprints'=>$y['shared_current_direct_fingerprints'],'candidate_current_distance_m'=>$y['candidate_current_distance_m'],'candidate_current_name_jaccard'=>$y['candidate_current_name_jaccard'],'safe_to_write_now'=>false];}v41_need(count($rows)===4,'rows');ksort($counts);usort($rows,fn($a,$b)=>[$a['status'],$a['andromeda_catalog_id']]<=>[$b['status'],$b['andromeda_catalog_id']]);return['operation'=>V41_OP,'state'=>'completed_read_only_fingerprint_collision_refinement','generated_at_utc'=>gmdate('c'),'source_sha'=>$sourceSha,'v40b_result_sha256'=>$sha,'input_count'=>4,'status_counts'=>$counts,'correction_ready_count'=>(int)($counts['correction_ready']??0),'duplicate_local_hold_count'=>(int)($counts['duplicate_local_hold']??0),'conflicting_operator_identity_hold_count'=>(int)($counts['conflicting_operator_identity_hold']??0),'rows'=>$rows,'provider_http_calls'=>0,'database_reads'=>0,'database_writes'=>0,'mapping_writes'=>0,'safe_to_write_now'=>false];}
function v41_self_test():void{$x=v41_classify(['v37_direct_fingerprints'=>['operator_315'=>['1']],'current_operator_lanes'=>['operator_315'=>['1']],'candidate_current_distance_m'=>6,'candidate_current_name_jaccard'=>0.7]);v41_need($x['status']==='duplicate_local_hold','dup');$x=v41_classify(['v37_direct_fingerprints'=>['operator_342'=>['2']],'current_operator_lanes'=>['operator_342'=>['2']],'candidate_current_distance_m'=>1200,'candidate_current_name_jaccard'=>0.2]);v41_need($x['status']==='conflicting_operator_identity_hold','conflict');$x=v41_classify(['v37_direct_fingerprints'=>['operator_342'=>['2']],'current_operator_lanes'=>[]]);v41_need($x['status']==='correction_ready','ready');}
if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__){if(in_array('--self-test',$argv??[],true)){v41_self_test();echo"MATCH_TV_SAMO_FINGERPRINT_COLLISION_REFINEMENT_V41_SELFTEST_OK\n";exit;}v41_need(($argv[1]??'')==='--execute','disabled');$dir=(string)getenv('MATCH_OPERATION_DIR');$res=(string)getenv('MATCH_V40B_RESULT');$rec=(string)getenv('MATCH_V40B_RECEIPT');$sha=(string)getenv('MATCH_SOURCE_SHA');v41_need(is_dir($dir)&&basename($dir)===V41_OP&&is_file($res)&&is_file($rec)&&preg_match('/^[0-9a-f]{40}$/D',$sha)===1,'runtime_scope');try{$r=v41_execute($res,$rec,$sha);$h=v41_save($dir.'/result.json',$r);v41_save($dir.'/receipt.json',['operation'=>V41_OP,'state'=>$r['state'],'result_sha256'=>$h,'readback_verified'=>hash_file('sha256',$dir.'/result.json')===$h,'provider_accessed'=>false,'provider_http_calls'=>0,'database_reads'=>0,'database_writes'=>0,'mapping_writes'=>0]);echo v41_json(['state'=>$r['state'],'status_counts'=>$r['status_counts'],'rows'=>$r['rows']])."\n";}catch(Throwable$e){$f=['operation'=>V41_OP,'state'=>'failed_read_only_fingerprint_collision_refinement','reason'=>preg_replace('/[^A-Za-z0-9_.:-]+/','_',mb_substr($e->getMessage(),0,160,'UTF-8')),'provider_http_calls'=>0,'database_reads'=>0,'database_writes'=>0,'mapping_writes'=>0];$h=v41_save($dir.'/result.json',$f);v41_save($dir.'/receipt.json',['operation'=>V41_OP,'state'=>$f['state'],'result_sha256'=>$h,'readback_verified'=>true,'provider_accessed'=>false,'provider_http_calls'=>0,'database_reads'=>0,'database_writes'=>0,'mapping_writes'=>0]);fwrite(STDERR,$f['reason']."\n");exit(2);}}
