<?php
declare(strict_types=1);
const D11_OP='hotel-match-didim-live11-samo-tv-1971-20260919-v2';
const D11_MAX_SAMO=30,D11_MAX_PAGES=12,D11_MAX_DETAIL=40;
if(in_array('--self-test',$argv??[],true)){require_once __DIR__.'/hotel_match_operator_fingerprint_room_evidence_v1.php';require_once __DIR__.'/hotel_match_tv_samo_common4_full_drain_v1.php';require_once __DIR__.'/hotel_match_didim_live11_helpers_v2.php';d11_need(d11_url_ids('https://x.test/hotel/784528?foo=1')===['784528'],'url');d11_need(d11_name('ABC HOTEL')==='abc','name');echo"DIDIM_LIVE11_SELFTEST_OK\n";exit(0);}
if(PHP_SAPI!=='cli')exit(2);
$dir=(string)getenv('MATCH_OPERATION_DIR');$root=realpath((string)getenv('ANYTOUR_ROOT'));$sha=(string)getenv('MATCH_SOURCE_SHA');if(!is_dir($dir)||basename($dir)!==D11_OP||!is_string($root)||!is_dir($root)||!preg_match('/^[a-f0-9]{40}$/D',$sha))throw new RuntimeException('runtime');
$res=json_decode((string)file_get_contents($dir.'/reservation.json'),true,32,JSON_THROW_ON_ERROR);if(($res['operation']??'')!==D11_OP||($res['state']??'')!=='reserved_before_provider_access')throw new RuntimeException('reservation');
require_once $root.'/config.php';require_once $dir.'/payload/hotel_match_operator_fingerprint_room_evidence_v1.php';require_once $dir.'/payload/hotel_match_tv_samo_common4_full_drain_v1.php';require_once $dir.'/payload/hotel_match_didim_live11_helpers_v2.php';require_once $dir.'/payload/andromeda-network-transport-failure.php';require_once $dir.'/payload/andromeda-transport.php';require_once $dir.'/payload/andromeda-client.php';require_once $dir.'/payload/tourvisor-client-v1.php';
$in=file('php://stdin',FILE_IGNORE_NEW_LINES);$user=trim((string)($in[0]??''));$pass=trim((string)($in[1]??''));unset($in);d11_need($user!==''&&$pass!=='','credentials');
$samoCalls=0;$tvCalls=0;$manifest=[];$providerAccess=false;
try{
 $providerAccess=true;$tr=new AnyTourAndromedaTransport(false);$cat=new AnyTourAndromedaClient(function(string $u,array $o)use($tr,&$samoCalls){d11_need(++$samoCalls<=D11_MAX_SAMO,'samo_cap');return$tr($u,$o);},true);$cat->login($user,$pass);unset($user,$pass);
 $catalogPath=realpath((string)getenv('MATCH_CATALOG_PATH'));d11_need(is_string($catalogPath)&&is_file($catalogPath)&&hash_file('sha256',$catalogPath)==='564da2af9cb248a6860b1705285f106d4f022ffbbac36a7fcfe2630d91a74b39','catalog_input');$all=json_decode((string)file_get_contents($catalogPath),true,64,JSON_THROW_ON_ERROR);
 $town=hmc_dict((array)($all['TOWNTO']??[]),['Дидим','Didim']);d11_need(count($town)===1,'didim_samo_bind');
 $map=hmc_operator_map((array)($all['OPERATORS']??[]));$families=['anex','biblio','funsun','intourist'];foreach($families as$f)d11_need(isset($map['unique'][$f]),'samo_operator_'.$f);$samoById=[];$opIds=[];foreach($families as$f){$r=$map['unique'][$f];$samoById[(string)$r['id']]=['family'=>$f,'name'=>$r['name']];$opIds[]=(string)$r['id'];}sort($opIds,SORT_NATURAL);
 $ci=is_array($all['CHECKIN_BEG']??null)?$all['CHECKIN_BEG']:[];$start=DateTimeImmutable::createFromFormat('!d.m.Y',(string)($ci['start']??''),new DateTimeZone('UTC'));$avail=(string)($ci['available']??'');d11_need($start instanceof DateTimeImmutable&&preg_match('/^[01]+$/D',$avail)&&strlen($avail)>=4,'samo_date_mask');$date=null;for($off=3;$off<min(strlen($avail),91);$off++)if($avail[$off]==='1'){$date=$start->modify('+'.$off.' day')->format('Y-m-d');break;}d11_need(is_string($date),'samo_no_available_date');$ymd=str_replace('-','',$date);$session=$cat->privateSession();d11_need(is_array($session),'samo_session');
 $samo=[];$pages=null;for($p=1;$p<=D11_MAX_PAGES;$p++){$pt=new AnyTourAndromedaTransport(true);$cl=new AnyTourAndromedaClient(function(string $u,array $o)use($pt,&$samoCalls){d11_need(++$samoCalls<=D11_MAX_SAMO,'samo_cap');return$pt($u,$o);},true);$cl->restorePrivateSession($session);$reply=$cl->price(['TOWNFROMINC'=>1,'STATEINC'=>5,'TOWNTOINC'=>(string)$town[0]['id'],'CHECKIN_BEG'=>$ymd,'CHECKIN_END'=>$ymd,'NIGHTS_FROM'=>7,'NIGHTS_TILL'=>7,'ADULT'=>2,'CHILD'=>0,'CURRENCYINC'=>643,'OPERATORS'=>implode(',',$opIds),'PACKETTYPE'=>0,'GROUP_BY'=>32,'PAGE'=>$p]);d11_raw($dir,'samo-price-'.$p,$reply,$manifest);$pages=(int)($reply['PAGES_COUNT']??0);d11_need($pages<=D11_MAX_PAGES,'samo_page_cap');foreach((array)($reply['PRICES']??[])as$r)if(is_array($r)&&($x=d11_samo_row($r,$samoById))!==null)$samo[]=$x;if($pages===0||$p>=$pages)break;}
 $uniq=[];foreach($samo as$x)$uniq[$x['samo_hotel_id'].'|'.$x['operator_family']]=$x;$samo=array_values($uniq);$hotelIds=array_values(array_unique(array_column($samo,'samo_hotel_id')));
 if(!$samo){$result=['operation'=>D11_OP,'state'=>'completed_samo_empty','route'=>['departure'=>'Москва','country'=>'Турция','resort'=>'Дидим','date'=>$date,'nights'=>7,'adults'=>2,'children'=>0],'samo_calls'=>$samoCalls,'tourvisor_calls'=>0,'samo_live_pairs'=>0,'samo_live_hotels'=>0,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true];}
 else{
  $tvOps=d11_tv_call($dir,'/operators',['departureId'=>1,'countryId'=>4],'tv-operators',$tvCalls,$manifest);$tvMap=hmc_operator_map(hmc_rows($tvOps,['operators','items','results']));foreach($families as$f)d11_need(isset($tvMap['unique'][$f]),'tv_operator_'.$f);$tvById=[];$tvOpIds=[];foreach($families as$f){$r=$tvMap['unique'][$f];$tvById[(string)$r['id']]=['family'=>$f,'name'=>$r['name']];$tvOpIds[]=(int)$r['id'];}sort($tvOpIds,SORT_NUMERIC);
  $regions=d11_tv_call($dir,'/regions',['countryId'=>4],'tv-regions',$tvCalls,$manifest);$didim=hmc_dict(hmc_rows($regions,['regions','items','results']),['Дидим','Didim']);d11_need(count($didim)===1,'didim_tv_bind');
  $td=d11_tv_drain($dir,['departureId'=>1,'countryId'=>4,'dateFrom'=>$date,'dateTo'=>$date,'nightsFrom'=>7,'nightsTo'=>7,'adults'=>2,'currency'=>'RUB','onlyCharter'=>false,'regionIds'=>[(int)$didim[0]['id']],'operatorIds'=>$tvOpIds],$tvCalls,$manifest);
  $pairs=d11_tv_pairs($td['rows'],$tvById);$details=[];$detailCount=0;foreach($pairs as$p){if($detailCount>=D11_MAX_DETAIL)break;$d=d11_tv_call($dir,'/tours/'.rawurlencode($p['tour_id']),['currency'=>'RUB'],'tv-detail-'.(++$detailCount),$tvCalls,$manifest);$p['detail_urls']=d11_urls($d);$p['operator_link_native_ids']=array_values(array_unique(array_merge(...array_map('d11_url_ids',$p['detail_urls']))));$details[]=$p;}
  $join=d11_join($samo,$details);$states=[];foreach($join as$j)$states[$j['state']]=($states[$j['state']]??0)+1;
  $result=['operation'=>D11_OP,'state'=>'completed_read_only','route'=>['departure'=>'Москва','country'=>'Турция','resort'=>'Дидим','samo_town_id'=>$town[0]['id'],'tv_region_id'=>$didim[0]['id'],'date'=>$date,'nights'=>7,'adults'=>2,'children'=>0],'samo_calls'=>$samoCalls,'tourvisor_calls'=>$tvCalls,'samo_pages'=>$pages,'samo_live_pairs'=>count($samo),'samo_live_hotels'=>count($hotelIds),'samo_live'=>$samo,'tourvisor_search_id'=>$td['search_id'],'tourvisor_fully_drained'=>$td['fully_drained'],'tourvisor_rounds'=>$td['rounds'],'tourvisor_live_hotels'=>count($td['rows']),'tourvisor_hotel_operator_pairs'=>count($pairs),'tourvisor_details'=>count($details),'tv_detail_evidence'=>$details,'join_state_counts'=>$states,'join'=>$join,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true];
 }
 $mh=hmc_write($dir.'/raw-manifest.json',['files'=>$manifest]);$result['raw_manifest_sha256']=$mh;
}catch(Throwable $e){$result=['operation'=>D11_OP,'state'=>$providerAccess?'terminal_failed_no_replay':'failed_before_provider_access','reason'=>preg_replace('/[^A-Za-z0-9_.:-]/','_',mb_substr($e->getMessage(),0,120,'UTF-8')),'samo_calls'=>$samoCalls,'tourvisor_calls'=>$tvCalls,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>$providerAccess];if($manifest&&!file_exists($dir.'/raw-manifest.json'))$result['raw_manifest_sha256']=hmc_write($dir.'/raw-manifest.json',['files'=>$manifest]);}
$rh=hmc_write($dir.'/result.json',$result);hmc_write($dir.'/receipt.json',['operation'=>D11_OP,'state'=>$result['state'],'result_sha256'=>$rh,'samo_calls'=>$result['samo_calls'],'tourvisor_calls'=>$result['tourvisor_calls'],'database_writes'=>0,'mapping_writes'=>0,'raw_manifest_sha256'=>$result['raw_manifest_sha256']??null,'no_replay'=>$result['no_replay']]);echo hmc_json(['state'=>$result['state'],'route'=>$result['route']??null,'samo_live_hotels'=>$result['samo_live_hotels']??null,'tourvisor_live_hotels'=>$result['tourvisor_live_hotels']??null,'join_state_counts'=>$result['join_state_counts']??null,'reason'=>$result['reason']??null])."\n";exit(in_array($result['state'],['completed_read_only','completed_samo_empty'],true)?0:2);
