<?php
declare(strict_types=1);
error_reporting(0);ob_start();
const OP='hotel-match-core8-current-bulk-reconcile-1971-20260912-v1';
function nt($v):string{$s=mb_strtolower(trim((string)$v),'UTF-8');$s=strtr($s,['ё'=>'е','é'=>'e','è'=>'e','ê'=>'e','á'=>'a','à'=>'a','ä'=>'a','â'=>'a','ö'=>'o','ô'=>'o','ü'=>'u','ú'=>'u','ç'=>'c','ş'=>'s','ğ'=>'g','ı'=>'i','&'=>' and ']);preg_match_all('/[\p{L}\p{N}]+/u',$s,$m);$drop=['hotel','hotels','resort','resorts','spa','otel','отель','отели','гостиница','the','by'];$t=array_values(array_filter($m[0]??[],static fn($x)=>$x!==''&&!in_array($x,$drop,true)));return implode(' ',$t);}
function variants($v):array{$s=trim((string)$v);if($s==='')return[];$a=[$s];if(preg_match_all('/\(\s*(?:ex|ех)\s*\.?\s*([^)]{2,180})\)/iu',$s,$m))foreach($m[1]as$x)$a[]=trim((string)$x);$z=preg_replace('/\s*\(\s*(?:ex|ех)\s*\.?\s*[^)]{2,180}\)\s*/iu',' ',$s);if(is_string($z)&&trim($z)!=='')$a[]=trim($z);$out=[];foreach($a as$x){$n=nt($x);if($n!==''&&mb_strlen($n,'UTF-8')>=3)$out[$n]=true;}return array_keys($out);}
function coord(array$r):?array{$lat=$lon=null;foreach(['latitude','lat','geo_lat','hotel_latitude','coord_lat']as$k)if(isset($r[$k])&&is_numeric($r[$k])){$lat=(float)$r[$k];break;}foreach(['longitude','lon','lng','geo_lon','hotel_longitude','coord_lon']as$k)if(isset($r[$k])&&is_numeric($r[$k])){$lon=(float)$r[$k];break;}return $lat!==null&&$lon!==null?[$lat,$lon]:null;}
function km(array$a,array$b):float{$r=6371.0;$p1=deg2rad($a[0]);$p2=deg2rad($b[0]);$dp=deg2rad($b[0]-$a[0]);$dl=deg2rad($b[1]-$a[1]);$q=sin($dp/2)**2+cos($p1)*cos($p2)*sin($dl/2)**2;return 2*$r*asin(min(1,sqrt($q)));}
function canonGeo($v):array{$s=nt($v);$map=['стамбул'=>'istanbul','istanbul'=>'istanbul','анталия'=>'antalya','antalya'=>'antalya','кемер'=>'kemer','kemer'=>'kemer','аланья'=>'alanya','alanya'=>'alanya','сиде'=>'side','side'=>'side','белек'=>'belek','belek'=>'belek','лалели'=>'laleli','laleli'=>'laleli','фатих'=>'fatih','fatih'=>'fatih','султанахмет'=>'sultanahmet','sultanahmet'=>'sultanahmet','таксим'=>'taksim','taksim'=>'taksim','хургада'=>'hurghada','hurghada'=>'hurghada','шарм'=>'sharm','sharm'=>'sharm','сома'=>'soma','soma'=>'soma','сафага'=>'safaga','safaga'=>'safaga','набк'=>'nabq','nabq'=>'nabq','дубай'=>'dubai','dubai'=>'dubai','фуджейра'=>'fujairah','fujairah'=>'fujairah','рас аль хайма'=>'ras al khaimah','ras al khaimah'=>'ras al khaimah','пхукет'=>'phuket','phuket'=>'phuket','паттайя'=>'pattaya','pattaya'=>'pattaya','мальдивы'=>'maldives','maldives'=>'maldives','куба'=>'cuba','cuba'=>'cuba','вьетнам'=>'vietnam','vietnam'=>'vietnam','шри ланка'=>'sri lanka','sri lanka'=>'sri lanka'];$out=[];foreach($map as$k=>$c)if(str_contains($s,$k))$out[$c]=true;foreach(explode(' ',$s)as$x)if(mb_strlen($x,'UTF-8')>=4)$out[$x]=true;return array_keys($out);}
function geoScore(array$a,array$h):int{$s=canonGeo(((string)($a['api_region']??$a['region_name']??'')).' '.((string)($a['api_town']??$a['town_name']??'')));$t=canonGeo(((string)($h['region_name']??'')).' '.((string)($h['subregion_name']??'')));if(!$s||!$t)return 0;$is=array_intersect($s,$t);return count(array_unique($is));}
function core8($name):bool{$n=nt($name);$keys=['египет','egypt','турция','turkey','таиланд','thailand','оаэ','united arab emirates','uae','вьетнам','vietnam','шри ланка','sri lanka','мальдивы','maldives','куба','cuba'];foreach($keys as$k)if($n===nt($k)||str_contains($n,nt($k)))return true;return false;}
$pdo=null;try{$root=realpath(getcwd());if(!$root||basename($root)!=='anytoour.ru')throw new RuntimeException('root');$db=is_file($root.'/data/db-v1.php')?$root.'/data/db-v1.php':$root.'/v2/data/db-v1.php';require_once$db;$pdo=v2_data_db();$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->exec('START TRANSACTION READ ONLY');
$hot=[];$byName=[];$coreCounts=[];$q=$pdo->query('SELECT * FROM catalog_hotels WHERE is_active=1');foreach($q->fetchAll(PDO::FETCH_ASSOC)as$h){if(!core8($h['country_name']??''))continue;$id=(int)$h['id'];$hot[$id]=$h;$coreCounts[(string)$h['country_name']]=($coreCounts[(string)$h['country_name']]??0)+1;foreach(variants($h['name']??'')as$n)$byName[$n][$id]=true;}
$aq=$pdo->query('SELECT hotel_id,alias FROM hotel_aliases');foreach($aq->fetchAll(PDO::FETCH_ASSOC)as$x){$id=(int)$x['hotel_id'];if(!isset($hot[$id]))continue;foreach(variants($x['alias']??'')as$n)$byName[$n][$id]=true;}
$bridge=[];$bq=$pdo->query("SELECT local_hotel_id,COUNT(*) c FROM andromeda_hotel_identities WHERE decision_status='accepted' AND local_hotel_id IS NOT NULL GROUP BY local_hotel_id");foreach($bq->fetchAll(PDO::FETCH_ASSOC)as$x)$bridge[(int)$x['local_hotel_id']]=(int)$x['c'];
$mapped=[];foreach($pdo->query('SELECT DISTINCT anex_hotel_id FROM anex_hotel_search_mappings')->fetchAll(PDO::FETCH_COLUMN)as$x)$mapped[(int)$x]=true;$dec=[];foreach($pdo->query('SELECT DISTINCT anex_hotel_id FROM anex_hotel_decisions')->fetchAll(PDO::FETCH_COLUMN)as$x)$dec[(int)$x]=true;$ex=[];foreach($pdo->query('SELECT DISTINCT anex_hotel_id FROM anex_review_pair_exclusions')->fetchAll(PDO::FETCH_COLUMN)as$x)$ex[(int)$x]=true;
$all=$pdo->query('SELECT * FROM anex_hotels')->fetchAll(PDO::FETCH_ASSOC);$safe=[];$needs=0;$protected=0;$noExact=0;$ambiguous=0;$coordBlocked=0;$reasonCounts=[];
foreach($all as$a){$aid=(int)($a['anex_hotel_id']??0);if($aid<=0)continue;if(isset($mapped[$aid])||isset($dec[$aid])||isset($ex[$aid])){$protected++;continue;}$name=(string)($a['api_name']??$a['name']??'');$ids=[];$matchedNorm=[];foreach(variants($name)as$n){foreach(array_keys($byName[$n]??[])as$id){$ids[(int)$id]=true;$matchedNorm[(int)$id][]=$n;}}$ids=array_keys($ids);if(!$ids){$noExact++;continue;}$ac=coord($a);$eval=[];foreach($ids as$id){$h=$hot[$id];$hc=coord($h);$dist=($ac&&$hc)?km($ac,$hc):null;$geo=geoScore($a,$h);$and=$bridge[$id]??0;if($dist!==null&&$dist>5){$coordBlocked++;continue;}$score=0;$why=[];if($dist!==null&&$dist<=0.25){$score+=100;$why[]='coord_250m';}elseif($dist!==null&&$dist<=1){$score+=80;$why[]='coord_1km';}elseif($dist!==null&&$dist<=5){$score+=30;$why[]='coord_5km';}if($geo>=2){$score+=50;$why[]='geo2';}elseif($geo===1){$score+=25;$why[]='geo1';}if($and>0){$score+=45;$why[]='accepted_andromeda_bridge';}$eval[]=['id'=>$id,'score'=>$score,'dist'=>$dist,'geo'=>$geo,'bridge'=>$and,'why'=>$why,'h'=>$h];}
if(!$eval){$needs++;continue;}usort($eval,fn($x,$y)=>$y['score']<=>$x['score'] ?: (($x['dist']??999999)<=>($y['dist']??999999)));$best=$eval[0];$second=$eval[1]??null;$margin=$best['score']-($second['score']??0);$strong=($best['dist']!==null&&$best['dist']<=1)||$best['geo']>=1||$best['bridge']>0;$unique=count($eval)===1;$safeRule=$strong&&($unique||$margin>=35)&&$best['score']>=25;if(!$safeRule){$ambiguous++;$needs++;continue;}$reason=$best['dist']!==null&&$best['dist']<=1?'exact_alias_plus_coord':($best['geo']>=1&&$best['bridge']>0?'exact_alias_plus_geo_plus_andromeda':($best['geo']>=1?'exact_alias_plus_geo':'exact_alias_plus_andromeda'));$reasonCounts[$reason]=($reasonCounts[$reason]??0)+1;$h=$best['h'];$safe[]=['anex_id'=>$aid,'anex_name'=>$name,'api_region'=>$a['api_region']??null,'api_town'=>$a['api_town']??null,'target_local_id'=>(int)$h['id'],'target_name'=>$h['name'],'country'=>$h['country_name'],'region'=>$h['region_name']??null,'subregion'=>$h['subregion_name']??null,'coordinate_distance_km'=>$best['dist']===null?null:round($best['dist'],3),'geo_score'=>$best['geo'],'accepted_andromeda_bridge_count'=>$best['bridge'],'candidate_count'=>count($eval),'score'=>$best['score'],'margin'=>$margin,'reason'=>$reason,'matched_normalizations'=>array_values(array_unique($matchedNorm[(int)$h['id']]??[]))];}
$pdo->exec('ROLLBACK');usort($safe,fn($a,$b)=>($b['score']<=>$a['score']) ?: (($a['coordinate_distance_km']??999999)<=>($b['coordinate_distance_km']??999999)));$out=['status'=>'completed','operation_id'=>OP,'catalog_anex_rows'=>count($all),'protected_anex_rows'=>$protected,'core8_active_hotels'=>count($hot),'core8_country_counts'=>$coreCounts,'safe_count'=>count($safe),'needs_extra_count'=>$needs,'no_exact_candidate_count'=>$noExact,'ambiguous_count'=>$ambiguous,'coordinate_blocked_candidate_count'=>$coordBlocked,'reason_counts'=>$reasonCounts,'safe_rows'=>$safe,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true];}catch(Throwable$e){if($pdo instanceof PDO&&$pdo->inTransaction())$pdo->rollBack();$out=['status'=>'failed','operation_id'=>OP,'safe_message'=>substr($e->getMessage(),0,180),'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true];}while(ob_get_level())ob_end_clean();echo 'CORE8_BULK:'.json_encode($out,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";exit(($out['status']??'')==='completed'?0:2);
