<?php
declare(strict_types=1);
const OP='hotel-match-operator-authority-protection-audit-1971-20260917-v1';
const IDS=['83006','2000038836','1441','156280','2000040737','2000034129','2000084135','44577','2000068282','2000079658'];
function rq(bool $ok,string $why):void{if(!$ok)throw new RuntimeException($why);}
function js(array $x):string{return json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";}
function wr(string $p,array $x):string{$raw=js($x);$f=@fopen($p,'x+b');rq(is_resource($f),'exclusive_output');try{rq(fwrite($f,$raw)===strlen($raw)&&fflush($f),'output_write');if(function_exists('fsync'))rq(fsync($f),'output_sync');rewind($f);rq(stream_get_contents($f)===$raw,'output_readback');}finally{fclose($f);}return hash('sha256',$raw);}
function q(PDO $db,string $sql,array $a=[]):array{$s=$db->prepare($sql);$s->execute(array_values($a));$r=$s->fetchAll(PDO::FETCH_ASSOC);rq(count($r)<1000,'query_budget');return$r;}
function scalar_summary($v){if($v===null)return null;if(is_bool($v)||is_int($v)||is_float($v))return$v;if(is_string($v)){if(strlen($v)>160)return substr($v,0,160).'…';return$v;}return gettype($v);}
function walk($v,string $path,array &$out,int $d=0):void{rq($d<=32,'depth');if(!is_array($v))return;foreach($v as$k=>$x){$p=$path===''?(string)$k:$path.'.'.$k;$s=preg_match('/manual|exclude|exclusion|conflict|reject|review|protect/i',(string)$k)===1;if($s){$out[]=['path'=>$p,'type'=>gettype($x),'value'=>is_array($x)?['nonempty'=>$x!==[],'count'=>count($x)]:scalar_summary($x)];}if(is_array($x))walk($x,$p,$out,$d+1);}}
function main():void{
 rq(PHP_SAPI==='cli'&&getenv('MATCH_OPERATION_ID')===OP,'operation_guard');$sha=(string)getenv('MATCH_SOURCE_SHA');rq(preg_match('/^[a-f0-9]{40}$/D',$sha)===1,'source_guard');
 $dir=(string)getenv('HOME').'/.anytoour-match/operations/'.OP;$rp=$dir.'/reservation.json';rq(is_file($rp)&&!is_link($rp)&&realpath($rp)===$rp&&filesize($rp)<16384,'reservation_path');$res=json_decode((string)file_get_contents($rp),true,32,JSON_THROW_ON_ERROR);rq(($res['operation_id']??'')===OP&&($res['source_sha']??'')===$sha&&($res['state']??'')==='reserved_before_db_access','reservation');
 $root=realpath(getcwd());rq(is_string($root)&&basename($root)==='anytoour.ru','project_guard');$bp=$root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');rq(realpath($bp)===$bp&&!is_link($bp),'bootstrap');require_once$bp;$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');
 $rows=[];$all=[];
 foreach(IDS as$id){$r=q($db,"SELECT external_hotel_id,local_hotel_id,decision_status,evidence_sha256,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=?",[$id]);rq(count($r)===1,'authority_row_count');$x=$r[0];$e=json_decode((string)$x['evidence_json'],true,64,JSON_THROW_ON_ERROR);rq(is_array($e),'evidence_shape');$paths=[];walk($e,'',$paths);$target=null;if($x['local_hotel_id']!==null){$h=q($db,"SELECT id,country_id,name,is_active FROM catalog_hotels WHERE id=?",[(int)$x['local_hotel_id']]);rq(count($h)===1,'target_row_count');$target=['id'=>(int)$h[0]['id'],'country_id'=>(int)$h[0]['country_id'],'name'=>(string)$h[0]['name'],'is_active'=>(int)$h[0]['is_active']];}$rows[]=['andromeda_id'=>$id,'local_hotel_id'=>$x['local_hotel_id']===null?null:(int)$x['local_hotel_id'],'decision_status'=>(string)$x['decision_status'],'evidence_sha256'=>(string)$x['evidence_sha256'],'target'=>$target,'suspicious_paths'=>$paths,'suspicious_path_count'=>count($paths)];foreach($paths as$p)$all[$p['path']]=($all[$p['path']]??0)+1;}
 $db->commit();ksort($all);$out=['operation_id'=>OP,'source_sha'=>$sha,'state'=>'completed_read_only','authority_count'=>count($rows),'rows'=>$rows,'path_frequency'=>$all,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'read_at_utc'=>gmdate('c'),'no_replay'=>true];$rh=wr($dir.'/result.json',$out);wr($dir.'/receipt.json',['operation_id'=>OP,'source_sha'=>$sha,'state'=>'completed_read_only','result_sha256'=>$rh,'readback_verified'=>true,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);echo js(['state'=>'completed_read_only','authority_count'=>count($rows),'path_frequency'=>$all,'result_sha256'=>$rh]);
}
if(in_array('--self-test',$argv??[],true)){$o=[];walk(['a'=>['manual_checked'=>true,'review'=>['status'=>'clean']],'conflict'=>false],'',$o);rq(count($o)===3,'walk');echo"1 protection-audit self-test PASS\n";exit;}main();
