<?php
declare(strict_types=1);
/* MATCH-only v2: materially different provider window, durable per-request checkpoints, no DB writes. */
putenv('MATCH_AME_TEST_LIBRARY=1');
require_once __DIR__.'/hotel_match_andromeda_operator_evidence_mass_v1.php';
const AME2_OP='hotel-match-andromeda-operator-evidence-mass-1971-20260915-v2';
const AME2_MAX_PRICE_CALLS=300;
function ame2_safe_error(Throwable $e):array{$m=$e->getMessage();return['class'=>get_class($e),'reason'=>preg_match('/^[A-Za-z0-9_.:-]{1,120}$/D',$m)?$m:'sanitized_supplier_failure'];}
function ame2_run(string $queueFile,string $outDir):void{
    require_once __DIR__.'/../../app/integrations/andromeda-client.php';require_once __DIR__.'/../../app/integrations/andromeda-transport.php';
    $sha=(string)getenv('GITHUB_SHA');$attempt=(string)getenv('GITHUB_RUN_ATTEMPT');$reservation=json_decode((string)file_get_contents($outDir.'/reservation.json'),true,32,JSON_THROW_ON_ERROR);
    if(($reservation['operation_id']??'')!==AME2_OP||($reservation['source_sha']??'')!==$sha||($reservation['state']??'')!=='reserved_before_supplier_access'||$attempt!=='1')throw new RuntimeException('reservation');
    $q=json_decode((string)file_get_contents($queueFile),true,64,JSON_THROW_ON_ERROR);if(($q['state']??'')!=='queue_completed_read_only'||count($q['queue']??[])<100)throw new RuntimeException('queue_contract');
    $groups=[];$country=[];foreach($q['queue'] as $x){$id=(string)$x['andromeda_hotel_id'];$sk=(string)$x['state_key'];if(!preg_match('/^[1-9][0-9]{0,19}$/D',$id)||!preg_match('/^[1-9][0-9]{0,9}$/D',$sk))throw new RuntimeException('queue_identity');$groups[$sk][]=$id;$country[$id]=(int)$x['country_id'];}
    $operators=['5','342'];$facts=[];$pages=[];$errors=[];$calls=[];$seen=[];$priceCalls=0;$last=0.0;$responseDigest='';
    $transport=function(string $url,array $opts)use(&$calls,&$last,&$responseDigest):array{parse_str((string)parse_url($url,PHP_URL_QUERY),$qq);$action=(string)($qq['action']??'');if(!in_array($action,['login','price'],true))throw new RuntimeException('action');$wait=0.85-(microtime(true)-$last);if($wait>0)usleep((int)ceil($wait*1000000));$last=microtime(true);$i=count($calls);$calls[]=['action'=>$action,'status'=>null];$t=new AnyTourAndromedaTransport(true);try{$r=$t($url,$opts);$calls[$i]['status']=$r['status'];if($action==='price'){$responseDigest=hash('sha256',$r['body']);$calls[$i]['response_sha256']=$responseDigest;}return$r;}catch(Throwable $e){$calls[$i]['error']=ame2_safe_error($e);throw$e;}};
    try{$client=new AnyTourAndromedaClient($transport,true);$client->login(getenv('ANDROMEDA_USERNAME')?:'',getenv('ANDROMEDA_PASSWORD')?:'');$session=$client->privateSession();}catch(Throwable $e){$err=ame2_safe_error($e);$result=['schema'=>'hotel-match-andromeda-operator-evidence-mass/2','operation_id'=>AME2_OP,'source_sha'=>$sha,'state'=>'stopped_no_retry','phase'=>'login','error'=>$err,'queue_sha256'=>hash_file('sha256',$queueFile),'queue_count'=>count($q['queue']),'supplier_calls'=>count($calls),'price_calls'=>0,'unique_pair_count'=>0,'database_writes'=>0,'mapping_writes'=>0,'tourvisor_calls'=>0,'all_calls'=>0,'booking_calls'=>0,'no_replay'=>true];$digest=ame_write($outDir.'/result.json',$result);ame_write($outDir.'/receipt.json',['operation_id'=>AME2_OP,'source_sha'=>$sha,'state'=>'stopped_no_retry','result_sha256'=>$digest,'readback_verified'=>true,'database_writes'=>0,'no_replay'=>true]);echo ame_json(['state'=>'stopped_no_retry','phase'=>'login']);exit(2);}
    foreach($groups as $sk=>$ids)foreach($operators as $op)foreach(ame_chunks($ids) as $chunk){$wanted=array_fill_keys($chunk,true);$resolved=[];for($page=1;$page<=2;$page++){
        if($priceCalls>=AME2_MAX_PRICE_CALLS){$errors[]=['reason'=>'price_budget','state_key'=>(int)$sk,'operator_key'=>$op,'page'=>$page];break 4;}
        $params=['TOWNFROMINC'=>1,'STATEINC'=>(int)$sk,'CHECKIN_BEG'=>'20260929','CHECKIN_END'=>'20261005','NIGHTS_FROM'=>7,'NIGHTS_TILL'=>10,'ADULT'=>2,'CHILD'=>0,'CURRENCYINC'=>643,'OPERATORS'=>$op,'HOTELS'=>implode(',',$chunk),'GROUP_BY'=>32,'PACKETTYPE'=>0,'PAGE'=>$page];AnyTourAndromedaClient::validatePriceParams($params);$req=hash('sha256',ame_json($params));if(isset($seen[$req]))throw new RuntimeException('request_replay');$seen[$req]=true;$idx=$priceCalls;$priceCalls++;
        ame_write($outDir.'/request-'.str_pad((string)$idx,3,'0',STR_PAD_LEFT).'.json',['operation_id'=>AME2_OP,'source_sha'=>$sha,'state'=>'reserved_before_supplier_access','request_index'=>$idx,'request_sha256'=>$req,'params'=>$params,'no_replay'=>true]);
        try{$c=new AnyTourAndromedaClient($transport,true);$c->restorePrivateSession($session);$reply=$c->price($params);$valid=0;foreach($reply['PRICES'] as $row){$id=(string)($row['hotelKey']??'');$f=ame_native_fact($row,$wanted,$op,$country[$id]??0,$req,$responseDigest);if(!$f)continue;$key=$op.'|'.strtolower($f['native_hotel_id']).'|'.$f['andromeda_hotel_id'];$facts[$key]=$f;$resolved[$f['andromeda_hotel_id']]=true;$valid++;}$summary=['request_index'=>$idx,'state_key'=>(int)$sk,'operator_key'=>$op,'page'=>$page,'params'=>$params,'hotel_count'=>count($chunk),'returned_rows'=>count($reply['PRICES']),'valid_rows'=>$valid,'resolved_count'=>count($resolved),'pages_count'=>$reply['PAGES_COUNT'],'request_sha256'=>$req,'response_sha256'=>$responseDigest];$pages[]=$summary;ame_write($outDir.'/response-'.str_pad((string)$idx,3,'0',STR_PAD_LEFT).'.json',$summary);if(count($resolved)===count($wanted)||$page>=$reply['PAGES_COUNT'])break;}
        catch(Throwable $e){$err=ame2_safe_error($e)+['request_index'=>$idx,'state_key'=>(int)$sk,'operator_key'=>$op,'page'=>$page,'request_sha256'=>$req];$errors[]=$err;ame_write($outDir.'/failure-'.str_pad((string)$idx,3,'0',STR_PAD_LEFT).'.json',$err+['operation_id'=>AME2_OP,'source_sha'=>$sha,'state'=>'supplier_request_failed_no_retry','no_replay'=>true]);break;}
    }}
    $byOp=[];$covered=[];foreach($facts as $f){$byOp[$f['operator_key']]=($byOp[$f['operator_key']]??0)+1;$covered[$f['andromeda_hotel_id']]=true;}ksort($byOp,SORT_NATURAL);
    $result=['schema'=>'hotel-match-andromeda-operator-evidence-mass/2','operation_id'=>AME2_OP,'source_sha'=>$sha,'state'=>'completed','queue_sha256'=>hash_file('sha256',$queueFile),'queue_count'=>count($q['queue']),'queue_frequency_sum'=>$q['frequency_sum']??null,'operators'=>$operators,'supplier_calls'=>count($calls),'price_calls'=>$priceCalls,'failed_request_count'=>count($errors),'errors'=>$errors,'unique_pair_count'=>count($facts),'covered_andromeda_count'=>count($covered),'by_operator'=>$byOp,'pages'=>$pages,'facts'=>array_values($facts),'database_writes'=>0,'mapping_writes'=>0,'tourvisor_calls'=>0,'all_calls'=>0,'booking_calls'=>0,'no_replay'=>true,'completed_at'=>gmdate('c')];$digest=ame_write($outDir.'/result.json',$result);$verified=hash_equals($digest,hash_file('sha256',$outDir.'/result.json'));ame_write($outDir.'/receipt.json',['operation_id'=>AME2_OP,'source_sha'=>$sha,'state'=>'completed','result_sha256'=>$digest,'readback_verified'=>$verified,'queue_count'=>count($q['queue']),'unique_pair_count'=>count($facts),'failed_request_count'=>count($errors),'supplier_calls'=>count($calls),'database_writes'=>0,'no_replay'=>true]);if(!$verified)throw new RuntimeException('result_readback');echo ame_json(['state'=>'completed','queue_count'=>count($q['queue']),'unique_pairs'=>count($facts),'covered_andromeda'=>count($covered),'by_operator'=>$byOp,'price_calls'=>$priceCalls,'failed_requests'=>count($errors),'result_sha256'=>$digest]);
}
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}$mode=$argv[1]??'';if($mode==='run')ame2_run((string)($argv[2]??''),(string)($argv[3]??''));else throw new RuntimeException('mode');
