<?php
declare(strict_types=1);
const OP='hotel-match-andromeda-state116-capture-bridge-1971-20260916-v1';
const OLD='andromeda-1759-country6-20260910-v1-sri-lanka';
function j($v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
function putnew(string $p,$v):string{$raw=j($v)."\n";$f=@fopen($p,'x');if(!$f)throw new RuntimeException('durable_create_failed');try{if(fwrite($f,$raw)!==strlen($raw))throw new RuntimeException('durable_write_failed');fflush($f);}finally{fclose($f);}if(file_get_contents($p)!==$raw)throw new RuntimeException('durable_readback_failed');return hash('sha256',$raw);}
function readj(string $p):array{if(is_link($p)||!is_file($p)||filesize($p)>20000000)throw new RuntimeException('sealed_file_missing');$x=json_decode((string)file_get_contents($p),true,128,JSON_THROW_ON_ERROR);if(!is_array($x))throw new RuntimeException('sealed_json_invalid');return$x;}
function dbpath(string $r):string{foreach([$r.'/data/db-v1.php',$r.'/v2/data/db-v1.php'] as $p)if(is_file($p))return$p;throw new RuntimeException('db_bootstrap_missing');}
function norm($v):string{$s=mb_strtolower((string)$v,'UTF-8');$s=strtr($s,['ё'=>'е','é'=>'e','è'=>'e','ê'=>'e','á'=>'a','à'=>'a','ä'=>'a','â'=>'a','ö'=>'o','ô'=>'o','ü'=>'u','ú'=>'u','ç'=>'c','ş'=>'s','ğ'=>'g','ı'=>'i']);preg_match_all('/[\p{L}\p{N}]+/u',$s,$m);$w=array_values(array_filter($m[0]??[],fn($x)=>!in_array($x,['hotel','hotels','resort','resorts','spa','the','and'],true)));return implode(' ',$w);}
function forms($v):array{$s=(string)$v;$out=[norm($s)];if(preg_match('/\(\s*(?:ex|ех)\.?\s+([^()]+)\)/ui',$s,$m))$out[]=norm($m[1]);return array_values(array_unique(array_filter($out)));}
if(in_array('--self-test',$argv??[],true)){if(norm('Amaya Beach Resort & SPA')!=='amaya beach'||forms('A (Ex. B Hotel)')!==['a','b'])throw new RuntimeException('norm_test');echo"PASS\n";exit(0);}
$op=(string)getenv('OPERATION_ID');$sha=(string)getenv('MATCH_SOURCE_SHA');if($op!==OP||!preg_match('/^[0-9a-f]{40}$/D',$sha))throw new RuntimeException('operation_guard');$root=(string)realpath(getcwd());if($root===''||basename($root)!=='anytoour.ru')throw new RuntimeException('root_guard');$base=rtrim((string)getenv('HOME'),'/').'/.anytoour-match/operations';$dir=$base.'/'.$op;if(!is_dir($base)||!mkdir($dir,0700))throw new RuntimeException('operation_exists');putnew($dir.'/reservation.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'reserved_before_private_capture_and_db','read_only'=>true,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);
$db=null;try{$cfg=require $root.'/_preview/search3-anex-candidate/.andromeda-private.php';$catalogPath=$cfg['catalog_path']??null;if(!is_string($catalogPath)||$catalogPath==='')throw new RuntimeException('private_catalog_config_missing');$private=(string)realpath(dirname($catalogPath));if($private===''||strpos($private,$root.'/')!==0)throw new RuntimeException('private_root_guard');$old=$private.'/'.OLD;$capture=readj($old.'/capture.json');$plan=readj($old.'/plan.json');$receipt=readj($old.'/result.json');
if(($receipt['status']??null)!=='imported'||($receipt['readback_verified']??false)!==true)throw new RuntimeException('sealed_import_not_verified');$country=(int)($capture['country_id']??0);$supplier=(string)($capture['supplier_country_id']??'');$catalogSha=(string)($plan['catalog_sha256']??'');if($country<1||$supplier===''||$catalogSha===''||(int)($plan['country_id']??0)!==$country||(string)($plan['supplier_country_id']??'')!==$supplier)throw new RuntimeException('sealed_scope_invalid');
require_once dbpath($root);$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');$s=$db->prepare("SELECT external_hotel_id,evidence_json,evidence_sha256,catalog_sha256 FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='pending' AND local_hotel_id IS NULL ORDER BY external_hotel_id");$s->execute();$pending=$s->fetchAll(PDO::FETCH_ASSOC)?:[];$h=$db->prepare('SELECT id,name,country_id,category,is_active FROM catalog_hotels WHERE country_id=? AND is_active=1 ORDER BY id');$h->execute([$country]);$hotels=$h->fetchAll(PDO::FETCH_ASSOC)?:[];$a=$db->prepare('SELECT a.hotel_id,a.alias FROM hotel_aliases a JOIN catalog_hotels h ON h.id=a.hotel_id WHERE h.country_id=? AND h.is_active=1 ORDER BY a.hotel_id,a.alias');$a->execute([$country]);$aliases=$a->fetchAll(PDO::FETCH_ASSOC)?:[];$occ=$db->query("SELECT local_hotel_id,external_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IS NOT NULL")->fetchAll(PDO::FETCH_ASSOC)?:[];$db->exec('ROLLBACK');
$index=[];$hotelBy=[];foreach($hotels as $x){$id=(int)$x['id'];$hotelBy[$id]=$x;foreach(forms($x['name']) as $f)$index[$f][$id]=true;}foreach($aliases as $x){$id=(int)$x['hotel_id'];if(isset($hotelBy[$id]))foreach(forms($x['alias']) as $f)$index[$f][$id]=true;}$occupied=[];foreach($occ as $x)$occupied[(int)$x['local_hotel_id']][]=(string)$x['external_hotel_id'];
$stateRows=[];$catalogs=[];foreach($pending as $r){try{$e=json_decode((string)$r['evidence_json'],true,128,JSON_THROW_ON_ERROR);}catch(Throwable){continue;}$src=$e['source']??null;if(!is_array($src)||(string)($src['stateKey']??'')!=='116')continue;$stateRows[]=['row'=>$r,'source'=>$src];$catalogs[(string)$r['catalog_sha256']]=true;}
$bridgeProven=($supplier==='116'&&count($catalogs)===1&&isset($catalogs[$catalogSha]));$prepared=[];$routes=[];$targetUse=[];$rows=[];foreach($stateRows as $z){$r=$z['row'];$src=$z['source'];$cands=[];$matched=[];foreach(array_merge(forms($src['name']??''),forms($src['lName']??'')) as $f)foreach(array_keys($index[$f]??[]) as $id){$cands[(int)$id]=true;$matched[$f]=true;}$ids=array_keys($cands);sort($ids,SORT_NUMERIC);$route='hold_capture_bridge_unproven';$candidate=null;if($bridgeProven){if(count($ids)===1){$candidate=(int)$ids[0];if(!empty($occupied[$candidate]))$route='hold_andromeda_target_occupied';else{$route='guard_passed_prepared';$targetUse[$candidate][]=(string)$r['external_hotel_id'];}}elseif(count($ids)>1)$route='hold_exact_ambiguous';else$route='hold_no_exact_country_match';}$routes[$route]=($routes[$route]??0)+1;$row=['external_hotel_id'=>(string)$r['external_hotel_id'],'source_name'=>(string)($src['name']??''),'source_state_key'=>(string)($src['stateKey']??''),'sealed_country_id'=>$bridgeProven?$country:null,'candidate_local_id'=>$candidate,'candidate_local_name'=>$candidate!==null?(string)$hotelBy[$candidate]['name']:null,'matched_forms'=>array_keys($matched),'route'=>$route,'evidence_sha256'=>(string)$r['evidence_sha256'],'catalog_sha256'=>(string)$r['catalog_sha256']];$rows[]=$row;if($route==='guard_passed_prepared')$prepared[]=$row;}
$final=[];foreach($prepared as $r){if(count(array_unique($targetUse[$r['candidate_local_id']]??[]))>1){$routes['hold_pending_target_collision']=($routes['hold_pending_target_collision']??0)+1;$routes['guard_passed_prepared']--;continue;}$final[]=$r;}ksort($routes);$result=['schema'=>'hotel-match-andromeda-state116-capture-bridge/1','operation_id'=>$op,'source_sha'=>$sha,'state'=>'completed_read_only','sealed_source_operation'=>OLD,'sealed_capture_sha256'=>hash_file('sha256',$old.'/capture.json'),'sealed_plan_sha256'=>hash_file('sha256',$old.'/plan.json'),'sealed_result_sha256'=>hash_file('sha256',$old.'/result.json'),'sealed_import_readback_verified'=>true,'sealed_country_id'=>$country,'sealed_supplier_country_id'=>$supplier,'sealed_catalog_sha256'=>$catalogSha,'current_state116_pending_count'=>count($stateRows),'current_state116_catalog_sha256s'=>array_keys($catalogs),'capture_bridge_proven'=>$bridgeProven,'route_counts'=>$routes,'guard_passed_prepared_count'=>count($final),'guard_passed_prepared'=>$final,'rows'=>$rows,'safe_to_write_now'=>false,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'booking_calls'=>0,'lead_calls'=>0,'no_replay'=>true];$digest=putnew($dir.'/result.json',$result);putnew($dir.'/receipt.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'completed_read_only','result_sha256'=>$digest,'readback_verified'=>hash('sha256',(string)file_get_contents($dir.'/result.json'))===$digest,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);echo j(['state'=>'completed_read_only','sealed_country_id'=>$country,'sealed_supplier_country_id'=>$supplier,'capture_bridge_proven'=>$bridgeProven,'current_state116_pending_count'=>count($stateRows),'route_counts'=>$routes,'guard_passed_prepared_count'=>count($final)])."\n";
}catch(Throwable $e){try{if($db instanceof PDO&&$db->inTransaction())$db->rollBack();}catch(Throwable){}$f=['operation_id'=>$op,'source_sha'=>$sha,'state'=>'failed_read_only','error_class'=>get_class($e),'error_message'=>$e->getMessage(),'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true];$digest=putnew($dir.'/failure.json',$f);putnew($dir.'/receipt.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'failed_read_only','failure_sha256'=>$digest,'readback_verified'=>true,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);fwrite(STDERR,"HMAP_FAILED ".$e->getMessage()."\n");exit(2);}
