<?php
declare(strict_types=1);
const A74_OP='hotel-match-current15-samo82-anex-1971-20260927-v74b';
const S15=[125=>'2000062991',1181=>'2000028206',1229=>'5464',1772=>'37255',4326=>'309768',7958=>'2000026726',13947=>'2000046831',55945=>'2000037585',56479=>'2000093384',65341=>'2000106034',67304=>'2000055490',76753=>'2000087342',108356=>'269426',116886=>'2000103169',121109=>'2000090159'];
function qq(PDO $d,string $s,array $a=[]):array{$q=$d->prepare($s);if(!$q||!$q->execute(array_values($a)))throw new RuntimeException('query');return $q->fetchAll(PDO::FETCH_ASSOC);}
function main(array $v):int{
 if(($v[1]??'')!=='--execute')throw new RuntimeException('disabled');$root=getenv('ANYTOUR_ROOT');$dir=getenv('MATCH_OPERATION_DIR');$head=getenv('MATCH_SOURCE_SHA');if(!is_dir($root)||!is_dir($dir)||basename($dir)!==A74_OP)throw new RuntimeException('scope');
 $anex=json_decode(file_get_contents((string)getenv('MATCH_ANEX82')),true,128,JSON_THROW_ON_ERROR);$list=$anex['direct_anex_candidates']??[];if(count($list)!==82)throw new RuntimeException('anex82');$a82=[];foreach($list as $x){$id=(int)$x['local_hotel_id'];$native=(string)$x['anex_hotel_id'];if(isset($a82[$id]))throw new RuntimeException('dup_anex');$a82[$id]=$native;}
 require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION READ ONLY');
 $sids=array_keys(S15);$scats=array_values(S15);$aids=array_keys($a82);$anids=array_values($a82);$allIds=array_values(array_unique(array_merge($sids,$aids)));$ih=implode(',',array_fill(0,count($allIds),'?'));$sch=implode(',',array_fill(0,count($scats),'?'));$anh=implode(',',array_fill(0,count($anids),'?'));
 $idents=qq($db,"SELECT supplier_namespace,external_hotel_id,local_hotel_id,decision_status FROM andromeda_hotel_identities WHERE local_hotel_id IN ($ih) OR (supplier_namespace='andromeda_catalog' AND external_hotel_id IN ($sch)) ORDER BY supplier_namespace,external_hotel_id",array_merge($allIds,$scats));$src=[];$tcat=[];foreach($idents as $r){if($r['supplier_namespace']==='andromeda_catalog'){$src[(string)$r['external_hotel_id']][]=$r;$tcat[(int)$r['local_hotel_id']][]=$r;}}
 $srows=[];$sc=[];foreach(S15 as $id=>$cat){$s=$src[$cat]??[];$t=$tcat[$id]??[];$st='ready_source_missing';if($s){$same=array_values(array_filter($s,fn($r)=>(int)$r['local_hotel_id']===$id));$other=array_values(array_filter($s,fn($r)=>(int)$r['local_hotel_id']!==$id));if($other)$st='source_conflict';elseif($same&&$same[0]['decision_status']==='accepted')$st='already_accepted';elseif($same)$st='ready_pending_same';}elseif($t)$st='target_catalog_occupied';$sc[$st]=($sc[$st]??0)+1;$srows[]=['local_hotel_id'=>$id,'catalog_id'=>$cat,'status'=>$st];}
 $op5=[];foreach(qq($db,"SELECT external_hotel_id,local_hotel_id,decision_status FROM andromeda_hotel_identities WHERE supplier_namespace='operator_5' AND (local_hotel_id IN ($ih) OR external_hotel_id IN ($anh))",array_merge($allIds,$anids)) as $x)$op5[(string)$x['external_hotel_id']][]=$x;
 $maps=[];foreach(qq($db,"SELECT anex_hotel_id,catalog_hotel_id,decision_status FROM anex_hotel_search_mappings WHERE anex_hotel_id IN ($anh) OR catalog_hotel_id IN ($ih)",array_merge($anids,$allIds)) as $x)$maps[(string)$x['anex_hotel_id']][]=$x;
 $arows=[];$ac=[];foreach($a82 as $id=>$native){$claims=[];foreach($op5[$native]??[] as $x)if(($x['decision_status']??'')==='accepted')$claims[]=(int)$x['local_hotel_id'];foreach($maps[$native]??[] as $x)if(($x['decision_status']??'')==='accepted')$claims[]=(int)$x['catalog_hotel_id'];$claims=array_values(array_unique($claims));$st='ready_missing';if($claims)$st=(count($claims)===1&&$claims[0]===$id)?'already_accepted_same':'source_conflict';$ac[$st]=($ac[$st]??0)+1;$arows[]=['local_hotel_id'=>$id,'anex_hotel_id'=>$native,'status'=>$st,'current_claims'=>$claims];}
 $db->rollBack();ksort($sc);ksort($ac);$out=['operation'=>A74_OP,'state'=>'completed_read_only_current','source_sha'=>$head,'samo_counts'=>$sc,'anex_counts'=>$ac,'samo_rows'=>$srows,'anex_rows'=>$arows,'database_writes'=>0,'mapping_writes'=>0,'provider_http_calls'=>0];$raw=json_encode($out,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";file_put_contents($dir.'/result.json',$raw);file_put_contents($dir.'/receipt.json',json_encode(['operation'=>A74_OP,'state'=>$out['state'],'result_sha256'=>hash('sha256',$raw),'database_writes'=>0,'mapping_writes'=>0,'provider_http_calls'=>0])."\n");echo json_encode(['samo'=>$sc,'anex'=>$ac])."\n";return 0;}
if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__)exit(main($argv));
