<?php
declare(strict_types=1);
require_once __DIR__.'/andromeda_country_expansion.php';
require_once __DIR__.'/hotel_match_retained_candidates_write_v86.php';
const V91_OP='hotel-match-samo-missing-source-current-catalog-audit-1971-20260928-v91';
const V91_CAT='2000086118';const V91_LOCAL=144804;const V91_NS='operator_315';const V91_NATIVE='858106';
function v91_need(bool$b,string$m):void{if(!$b)throw new RuntimeException($m);}
function v91_find(mixed$x,string$id,string$path='',int$d=0,array&$hits=[]):void{if($d>10||!is_array($x))return;if(isset($x['id'])&&(string)$x['id']===$id&&isset($x['name']))$hits[]=['path'=>$path,'row'=>$x];foreach($x as$k=>$v)if(is_array($v))v91_find($v,$id,$path.'/'.str_replace(['~','/'],['~0','~1'],(string)$k),$d+1,$hits);}
function v91_main(array$argv):int{v91_need(($argv[1]??'')==='--execute','disabled');$root=(string)getenv('ANYTOUR_ROOT');$dir=(string)getenv('MATCH_OPERATION_DIR');$head=(string)getenv('MATCH_SOURCE_SHA');v91_need(is_dir($root)&&basename($root)==='anytoour.ru'&&is_dir($dir)&&basename($dir)===V91_OP&&preg_match('/^[a-f0-9]{40}$/D',$head),'scope');foreach(['result.json','receipt.json']as$f)v91_need(!file_exists($dir.'/'.$f),'no_replay');
 $cfg=require $root.'/_preview/search3-anex-candidate/.andromeda-private.php';v91_need(is_array($cfg)&&is_string($cfg['catalog_path']??null),'config');$p=$cfg['catalog_path'];v91_need(is_file($p)&&!is_link($p)&&filesize($p)>0&&filesize($p)<=67108864,'catalog_file');$raw=file_get_contents($p);$j=json_decode($raw,true,128,JSON_THROW_ON_ERROR);v91_need(is_array($j),'catalog_json');$hits=[];v91_find($j,V91_CAT,'',0,$hits);
 require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->exec('START TRANSACTION READ ONLY');try{$source=w76_q($db,"SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=?",[V91_CAT]);$op=w76_q($db,"SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace=? AND external_hotel_id=?",[V91_NS,V91_NATIVE]);$hotel=w76_q($db,'SELECT id,name,country_id,country_name,region_name,subregion_name,category,is_active FROM catalog_hotels WHERE id=?',[V91_LOCAL]);$manual=w76_q($db,'SELECT * FROM anex_hotel_decisions WHERE catalog_hotel_id=?',[V91_LOCAL]);$exc=w76_q($db,'SELECT * FROM anex_review_pair_exclusions WHERE catalog_hotel_id=?',[V91_LOCAL]);$db->rollBack();}catch(Throwable$e){if($db->inTransaction())$db->rollBack();throw$e;}
 $out=['operation'=>V91_OP,'state'=>'completed_read_only_current_catalog_source','source_sha'=>$head,'generated_at_utc'=>gmdate('c'),'catalog_path_basename'=>basename($p),'catalog_bytes'=>strlen($raw),'catalog_file_sha256'=>hash('sha256',$raw),'catalog_canonical_sha256'=>ce_hash($j),'catalog_exact_id_hits'=>count($hits),'catalog_hits'=>array_slice($hits,0,5),'current_source_rows'=>$source,'current_operator_rows'=>$op,'target'=>$hotel[0]??null,'manual_count'=>count($manual),'exclusion_count'=>count($exc),'provider_http_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'safe_to_write_now'=>false,'no_replay'=>true];$sha=w76_save($dir.'/result.json',$out);w76_save($dir.'/receipt.json',['operation'=>V91_OP,'state'=>$out['state'],'source_sha'=>$head,'result_sha256'=>$sha,'provider_http_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true]);echo w76_json(array_diff_key($out,['catalog_hits'=>true,'current_source_rows'=>true,'current_operator_rows'=>true]))."\n";return 0;}
if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__)exit(v91_main($argv));