<?php
declare(strict_types=1);
if (!defined('FC_LIBRARY_ONLY')) define('FC_LIBRARY_ONLY', true);
require_once __DIR__ . '/hotel_match_anex_andromeda_direct_catalog_hardened.php';

const HMADMSA_OPERATION='hotel-match-anex-andromeda-direct-missing-side-accept-1971-20260911-v1';
const HMADMSA_SOURCE_OPERATION=HMADCR_OPERATION;
const HMADMSA_MAX_WRITES=40;
const HMADMSA_SOURCE_COUNT=29;

function hmadmsa_transactional(PDO $db):void{
    $tables=['catalog_hotels','anex_hotel_search_mappings','anex_hotel_decisions','anex_review_pair_exclusions','anex_hotels','anex_search_hotel_observations','andromeda_hotel_identities','andromeda_search_hotel_observations'];$q=$db->prepare("SELECT ENGINE FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?");foreach($tables as$t){$q->execute([$t]);$e=$q->fetchColumn();if($e===false||strcasecmp((string)$e,'InnoDB')!==0)throw new RuntimeException('required_transactional_table:'.$t);}
}
function hmadmsa_actionable(array $r):bool{
    if(!in_array((string)($r['bucket']??''),['high_confidence','strong_candidate'],true))return false;if(!in_array((string)($r['validation']??''),['anex_only','andromeda_only'],true))return false;
    return in_array((string)($r['reason']??''),['direct_exact_3plus','direct_translit_exact_3plus','direct_exact_geo','direct_translit_exact_geo','direct_exact_no_geo'],true);
}
function hmadmsa_allow(array $source):array{
    if(($source['status']??null)!=='completed'||($source['operation_id']??null)!==HMADMSA_SOURCE_OPERATION||($source['database_writes']??null)!==0||($source['mapping_writes']??null)!==0||($source['supplier_calls']??null)!==0)throw new RuntimeException('source_invalid');
    $out=[];foreach(($source['pairs']??[]) as$r){if(!hmadmsa_actionable($r))continue;$aid=(int)($r['anex_hotel_id']??0);$and=(string)($r['andromeda_external_id']??'');if($aid<1||$and==='')throw new RuntimeException('source_row_invalid');$k=$aid.'|'.$and;if(isset($out[$k]))throw new RuntimeException('source_duplicate');$out[$k]=$r;}if(count($out)!==HMADMSA_SOURCE_COUNT)throw new RuntimeException('source_count:'.count($out));return$out;
}
function hmadmsa_current_anex(PDO $db):array{
    $local=[];foreach($db->query('SELECT anex_hotel_id,catalog_hotel_id FROM anex_hotel_search_mappings WHERE enabled=1')->fetchAll(PDO::FETCH_ASSOC)as$r)$local[(int)$r['anex_hotel_id']][(int)$r['catalog_hotel_id']]=true;foreach($db->query("SELECT anex_hotel_id,catalog_hotel_id FROM anex_hotel_decisions WHERE decision_status='accepted' AND catalog_hotel_id IS NOT NULL")->fetchAll(PDO::FETCH_ASSOC)as$r)$local[(int)$r['anex_hotel_id']][(int)$r['catalog_hotel_id']]=true;return$local;
}
function hmadmsa_accept(PDO $db,array $source,string $operation=HMADMSA_OPERATION,int $maxWrites=HMADMSA_MAX_WRITES):array{
    if($operation!==HMADMSA_OPERATION)throw new RuntimeException('operation_scope');if($maxWrites<1||$maxWrites>HMADMSA_MAX_WRITES)throw new RuntimeException('write_limit_config');$allow=hmadmsa_allow($source);$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);hmadmsa_transactional($db);$db->exec('SET SESSION innodb_lock_wait_timeout=20');$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$before=fc_coverage($db);$writtenAn=[];$writtenAnd=[];$stats=['allow'=>count($allow),'current_rechecked'=>0,'stale'=>0,'direct_target_changed'=>0,'locality_block'=>0,'validation_changed'=>0,'manual_or_mapped'=>0,'pair_exclusion'=>0,'target_occupied'=>0,'local_invalid'=>0,'target_collision'=>0,'planned'=>0,'planned_anex'=>0,'planned_andromeda'=>0,'written'=>0,'written_anex'=>0,'written_andromeda'=>0,'live_written'=>0];$skip=[];
    try{$db->beginTransaction();
        $db->query("SELECT external_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' ORDER BY external_hotel_id FOR UPDATE")->fetchAll(PDO::FETCH_COLUMN);$db->query('SELECT anex_hotel_id FROM anex_hotel_decisions ORDER BY anex_hotel_id FOR UPDATE')->fetchAll(PDO::FETCH_COLUMN);$db->query('SELECT anex_hotel_id FROM anex_hotel_search_mappings ORDER BY anex_hotel_id FOR UPDATE')->fetchAll(PDO::FETCH_COLUMN);$db->query('SELECT anex_hotel_id,catalog_hotel_id FROM anex_review_pair_exclusions ORDER BY anex_hotel_id,catalog_hotel_id FOR UPDATE')->fetchAll(PDO::FETCH_ASSOC);
        $andRows=hmadcrh_supplier_rows($db);$index=hmadcr_build_index($andRows);$locality=hmadcrh_locality_common($andRows);$anLocal=hmadmsa_current_anex($db);
        $manual=array_fill_keys(array_map('intval',$db->query('SELECT anex_hotel_id FROM anex_hotel_decisions')->fetchAll(PDO::FETCH_COLUMN)),true);$mapped=array_fill_keys(array_map('intval',$db->query('SELECT anex_hotel_id FROM anex_hotel_search_mappings WHERE enabled=1')->fetchAll(PDO::FETCH_COLUMN)),true);$excluded=[];foreach($db->query('SELECT anex_hotel_id,catalog_hotel_id FROM anex_review_pair_exclusions')->fetchAll(PDO::FETCH_ASSOC)as$r)$excluded[(int)$r['anex_hotel_id']][(int)$r['catalog_hotel_id']]=true;
        $andClaims=[];foreach($db->query("SELECT external_hotel_id,local_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IS NOT NULL")->fetchAll(PDO::FETCH_ASSOC)as$r)$andClaims[(int)$r['local_hotel_id']][]=(string)$r['external_hotel_id'];$anClaims=[];foreach($db->query('SELECT anex_hotel_id,catalog_hotel_id FROM anex_hotel_search_mappings WHERE enabled=1')->fetchAll(PDO::FETCH_ASSOC)as$r)$anClaims[(int)$r['catalog_hotel_id']][]=(int)$r['anex_hotel_id'];foreach($db->query("SELECT anex_hotel_id,catalog_hotel_id FROM anex_hotel_decisions WHERE decision_status='accepted' AND catalog_hotel_id IS NOT NULL")->fetchAll(PDO::FETCH_ASSOC)as$r)$anClaims[(int)$r['catalog_hotel_id']][]=(int)$r['anex_hotel_id'];
        $staging=[];foreach($db->query('SELECT * FROM anex_hotels')->fetchAll(PDO::FETCH_ASSOC)as$s)$staging[(int)$s['anex_hotel_id']]=$s;$anObs=[];foreach($db->query('SELECT * FROM anex_search_hotel_observations ORDER BY search_count DESC,last_seen_utc DESC,anex_hotel_id')->fetchAll(PDO::FETCH_ASSOC)as$o){$id=(int)$o['anex_hotel_id'];if(!isset($anObs[$id]))$anObs[$id]=$o;}
        $localQ=$db->prepare('SELECT id,country_id,name FROM catalog_hotels WHERE id=? AND is_active=1');$planned=[];
        foreach($allow as$key=>$a){$aid=(int)$a['anex_hotel_id'];$expectedAnd=(string)$a['andromeda_external_id'];$expectedValidation=(string)$a['validation'];$stage=$staging[$aid]??[];$obs=$anObs[$aid]??[];$country=(int)($obs['country_id']??0);if(!isset(HMADCR_CORE8[$country]))$country=(int)(fc_country($stage['api_country']??'')??0);if(!isset(HMADCR_CORE8[$country])){$stats['stale']++;$skip[$key]='country';continue;}$names=hmadcr_expand_names(array_values(array_unique(array_filter([(string)($obs['hotel_name']??''),(string)($stage['api_name']??''),(string)($stage['xml_name']??''),(string)($stage['xml_alternate_name']??'')],static fn($v)=>trim($v)!==''))));if(!$names){$stats['stale']++;$skip[$key]='names';continue;}$sourceRow=['external_id'=>$aid,'country_id'=>$country,'names'=>$names,'places'=>array_values(array_unique(array_filter([(string)($stage['api_region']??''),(string)($stage['api_town']??''),(string)($obs['region_name']??'')],static fn($v)=>trim($v)!==''))),'latitude'=>fc_num($stage['latitude']??null),'longitude'=>fc_num($stage['longitude']??null),'live'=>!empty($obs),'observation_count'=>(int)($obs['search_count']??0),'local_ids'=>array_map('intval',array_keys($anLocal[$aid]??[]))];$d=hmadcr_decide($sourceRow,$country,$andRows,$index);$stats['current_rechecked']++;if(!hmadmsa_actionable($d+['validation'=>$d['validation']??''])){$stats['stale']++;$skip[$key]='current_not_actionable';continue;}if((string)($d['andromeda_external_id']??'')!==$expectedAnd){$stats['direct_target_changed']++;$skip[$key]='andromeda_target_changed';continue;}if((string)($d['validation']??'')!==$expectedValidation){$stats['validation_changed']++;$skip[$key]='validation_changed';continue;}$targetRow=$andRows[$expectedAnd]??null;if(!$targetRow){$stats['stale']++;$skip[$key]='andromeda_missing';continue;}$anchors=hmadcrh_identity_anchors($d['pair']??[],$targetRow,$locality);if((int)$anchors['identity_aligned']<2){$stats['locality_block']++;$skip[$key]='identity_anchors';continue;}
            $local=0;$direction='';if($expectedValidation==='anex_only'){if(count($sourceRow['local_ids'])!==1||$targetRow['local_id']!==null){$stats['validation_changed']++;continue;}$local=(int)$sourceRow['local_ids'][0];$direction='andromeda';$occupied=array_values(array_filter($andClaims[$local]??[],static fn($x)=>$x!==$expectedAnd));if($occupied){$stats['target_occupied']++;continue;}}
            else{if($sourceRow['local_ids']||$targetRow['local_id']===null){$stats['validation_changed']++;continue;}$local=(int)$targetRow['local_id'];$direction='anex';if(isset($manual[$aid])||isset($mapped[$aid])){$stats['manual_or_mapped']++;continue;}if(isset($excluded[$aid][$local])){$stats['pair_exclusion']++;continue;}$occupied=array_values(array_filter($anClaims[$local]??[],static fn($x)=>(int)$x!==$aid));if($occupied){$stats['target_occupied']++;continue;}}
            $localQ->execute([$local]);$lh=$localQ->fetch(PDO::FETCH_ASSOC);if(!$lh||(int)$lh['country_id']!==$country){$stats['local_invalid']++;continue;}$planned[$key]=['direction'=>$direction,'anex_id'=>$aid,'andromeda_id'=>$expectedAnd,'local_id'=>$local,'country_id'=>$country,'local_name'=>$lh['name'],'live'=>(bool)$sourceRow['live']||(bool)($targetRow['live']??false),'reason'=>$d['reason'],'pair'=>$d['pair'],'anchors'=>$anchors,'validation'=>$expectedValidation,'source_names'=>$sourceRow['names'],'andromeda_names'=>$targetRow['names']];}
        $by=[];foreach($planned as$k=>$p)$by[$p['direction'].':'.$p['local_id']][]=$k;foreach($by as$ks)if(count($ks)>1)foreach($ks as$k){unset($planned[$k]);$stats['target_collision']++;}$stats['planned']=count($planned);foreach($planned as$p)$stats[$p['direction']==='anex'?'planned_anex':'planned_andromeda']++;if(count($planned)>$maxWrites)throw new RuntimeException('write_scope_limit');
        $insertAn=$db->prepare("INSERT INTO anex_hotel_search_mappings(anex_hotel_id,catalog_hotel_id,match_class,scope,approval_policy,source_row_digest,mapping_digest,enabled) VALUES(?,?,'strong_candidate','preview',?,?,?,1)");$mapDigest=fc_hash([$operation,'direct_anex_andromeda_missing_side_v1']);$updateAnd=$db->prepare("UPDATE andromeda_hotel_identities SET local_hotel_id=?,decision_status='accepted',evidence_sha256=?,evidence_json=? WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=? AND decision_status='pending' AND local_hotel_id IS NULL AND evidence_sha256 <=> ?");$identityQ=$db->prepare("SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=?");
        foreach($planned as$k=>$p){$ev=['operation_id'=>$operation,'lane'=>'MATCH','evidence'=>'direct_anex_andromeda_supplier_pair','source_operation'=>HMADMSA_SOURCE_OPERATION,'anex_hotel_id'=>$p['anex_id'],'andromeda_external_id'=>$p['andromeda_id'],'local_hotel_id'=>$p['local_id'],'local_name'=>$p['local_name'],'country_id'=>$p['country_id'],'direct_reason'=>$p['reason'],'identity_anchors'=>$p['anchors'],'validation_before'=>$p['validation'],'server_current_recomputed'=>true];if($p['direction']==='anex'){$aid=(int)$p['anex_id'];if(isset($manual[$aid])||isset($mapped[$aid])||isset($excluded[$aid][$p['local_id']]))throw new RuntimeException('anex_protection_changed:'.$aid);$digest=fc_hash($ev);$insertAn->execute([$aid,$p['local_id'],FC_POLICY,$digest,$mapDigest]);if($insertAn->rowCount()!==1)throw new RuntimeException('anex_insert_not_one:'.$aid);$writtenAn[$aid]=['target'=>$p['local_id'],'source_row_digest'=>$digest,'mapping_digest'=>$mapDigest,'live'=>$p['live']];$mapped[$aid]=true;$stats['written_anex']++;}
            else{$external=$p['andromeda_id'];$identityQ->execute([$external]);$cur=$identityQ->fetch(PDO::FETCH_ASSOC);if(!$cur||($cur['decision_status']??'')!=='pending'||$cur['local_hotel_id']!==null)throw new RuntimeException('andromeda_state_changed:'.$external);$prior=fc_evidence($cur['evidence_json']??'');$json=fc_json(['prior_evidence'=>$prior,'promotion'=>$ev]);$sha=hash('sha256',$json);$old=$cur['evidence_sha256']??null;$updateAnd->execute([$p['local_id'],$sha,$json,$external,$old]);if($updateAnd->rowCount()!==1)throw new RuntimeException('andromeda_cas_failed:'.$external);$writtenAnd[$external]=['target'=>$p['local_id'],'evidence_sha256'=>$sha,'live'=>$p['live']];$stats['written_andromeda']++;}$stats['written']++;if($p['live'])$stats['live_written']++;}
        if($stats['written']>$maxWrites)throw new RuntimeException('write_scope_limit');$db->commit();
    }catch(Throwable$e){if($db->inTransaction())$db->rollBack();throw$e;}
    $ra=$db->prepare('SELECT catalog_hotel_id,source_row_digest,mapping_digest,enabled FROM anex_hotel_search_mappings WHERE anex_hotel_id=?');foreach($writtenAn as$id=>$x){$ra->execute([(int)$id]);$v=$ra->fetch(PDO::FETCH_ASSOC);if(!$v||(int)$v['catalog_hotel_id']!==$x['target']||(int)$v['enabled']!==1||!hash_equals($x['source_row_digest'],(string)$v['source_row_digest'])||!hash_equals($x['mapping_digest'],(string)$v['mapping_digest']))throw new RuntimeException('anex_readback:'.$id);$writtenAn[$id]['readback']='verified';}
    $ri=$db->prepare("SELECT local_hotel_id,decision_status,evidence_sha256 FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=?");foreach($writtenAnd as$id=>$x){$ri->execute([(string)$id]);$v=$ri->fetch(PDO::FETCH_ASSOC);if(!$v||(int)$v['local_hotel_id']!==$x['target']||$v['decision_status']!=='accepted'||!hash_equals($x['evidence_sha256'],(string)$v['evidence_sha256']))throw new RuntimeException('andromeda_readback:'.$id);$writtenAnd[$id]['readback']='verified';}
    $after=fc_coverage($db);return['status'=>'completed','operation_id'=>$operation,'mode'=>'direct_supplier_missing_side_one_transaction','supplier_calls'=>0,'database_writes'=>$stats['written'],'mapping_writes'=>$stats['written'],'historical_operations_replayed'=>false,'source_operation'=>HMADMSA_SOURCE_OPERATION,'before'=>$before,'after'=>$after,'stats'=>$stats,'written_anex'=>$writtenAn,'written_andromeda'=>$writtenAnd,'skipped'=>$skip,'guards'=>['source_allowlist_count'=>HMADMSA_SOURCE_COUNT,'only_one_side_local'=>true,'neither_side_writes'=>false,'different_local_writes'=>false,'fuzzy_only_writes'=>false,'server_current_direct_recompute'=>true,'locality_hardened'=>true,'same_provider_target_occupancy_blocks'=>true,'manual_and_exclusions_protected'=>true,'one_transaction'=>true,'post_commit_per_row_readback'=>true]];
}
if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__){fwrite(STDERR,"library_only: use guarded missing-side workflow\n");exit(64);}
