<?php
declare(strict_types=1);
const CSP_OP='hotel-match-userseen-context-schema-1971-20260919-v1';
function csp_need(bool $x,string $w):void{if(!$x)throw new RuntimeException($w);}
function csp_write(string $p,array $v):string{$raw=json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n";$f=fopen($p,'xb');fwrite($f,$raw);fflush($f);if(function_exists('fsync'))fsync($f);fclose($f);return hash('sha256',$raw);}
if(in_array('--self-test',$argv??[],true)){echo"CONTEXT_SCHEMA_SELFTEST_OK\n";exit(0);}
$dir=(string)getenv('MATCH_OPERATION_DIR');$root=realpath((string)getenv('ANYTOUR_ROOT'));csp_need(PHP_SAPI==='cli'&&is_dir($dir)&&basename($dir)===CSP_OP&&is_string($root),'runtime');require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION READ ONLY');
$s=$db->query("SELECT TABLE_NAME,COLUMN_NAME,DATA_TYPE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND (LOWER(TABLE_NAME) REGEXP 'search|tourvisor|observ|offer' OR LOWER(COLUMN_NAME) REGEXP 'search_id|tour_id|departure|checkin|nights|hotel_id|operator') ORDER BY TABLE_NAME,ORDINAL_POSITION");$rows=$s->fetchAll(PDO::FETCH_ASSOC)?:[];$by=[];foreach($rows as$r)$by[$r['TABLE_NAME']][]=['name'=>$r['COLUMN_NAME'],'type'=>$r['DATA_TYPE']];$tables=[];
foreach($by as$t=>$cols){if(!preg_match('/^[A-Za-z0-9_]+$/D',$t))continue;$names=array_column($cols,'name');$score=0;foreach(['search_id','tour_id','hotel_id','catalog_hotel_id','local_hotel_id','departure_id','date_from','departure_date','nights','operator_id','observed_at','last_seen_at']as$k)if(in_array($k,$names,true))$score++;if($score<2)continue;$cnt=(int)$db->query('SELECT COUNT(*) FROM '.$t)->fetchColumn();$allowed=array_values(array_filter($names,fn($x)=>preg_match('/^(id|search_id|tour_id|hotel_id|catalog_hotel_id|local_hotel_id|departure_id|country_id|region_id|subregion_id|operator_id|operator_key|date_from|date_to|departure_date|checkin|checkin_date|nights|nights_from|nights_till|adults|children|children_count|child_ages|observed_at|last_seen_at|created_at|updated_at)$/i',$x)));$sample=[];if($allowed){$sel=implode(',',array_slice($allowed,0,20));$q=$db->query('SELECT '.$sel.' FROM '.$t.' ORDER BY 1 DESC LIMIT 3');$sample=$q->fetchAll(PDO::FETCH_ASSOC)?:[];}$tables[]=['table'=>$t,'score'=>$score,'row_count'=>$cnt,'columns'=>$cols,'sample'=>$sample];}
$db->rollBack();usort($tables,fn($a,$b)=>[$b['score'],$b['row_count']]<=>[$a['score'],$a['row_count']]);$out=['operation'=>CSP_OP,'state'=>'completed_read_only','provider_calls'=>0,'database_writes'=>0,'tables'=>$tables];$rh=csp_write($dir.'/result.json',$out);csp_write($dir.'/receipt.json',['operation'=>CSP_OP,'state'=>'completed_read_only','result_sha256'=>$rh,'provider_calls'=>0,'database_writes'=>0]);echo json_encode(['tables'=>array_map(fn($x)=>[$x['table'],$x['score'],$x['row_count']],$tables)],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";
