<?php
declare(strict_types=1);
if (!defined('FC_LIBRARY_ONLY')) define('FC_LIBRARY_ONLY', true);
require_once __DIR__ . '/hotel_match_global_graph_review.php';

const GM3_OPERATION = 'hotel-match-global-missing-third-review-2333-20260913-v1';

function gm3_similarity(string $a,string $b): array {
    $aa=array_values(array_unique(ggr_tokens($a)));$bb=array_values(array_unique(ggr_tokens($b)));
    $as=array_fill_keys($aa,true);$bs=array_fill_keys($bb,true);$shared=count(array_intersect_key($as,$bs));$union=count($as+$bs);
    return [$union?$shared/$union:0.0,$shared,count($aa),count($bb)];
}
function gm3_sym_qualifier_conflict(array $a,array $b): bool {
    $qa=[];$qb=[];foreach($a as $n)$qa+=ggr_qualifiers((string)$n);foreach($b as $n)$qb+=ggr_qualifiers((string)$n);
    foreach(array_keys($qa) as $q)if(!isset($qb[$q]))return true;foreach(array_keys($qb) as $q)if(!isset($qa[$q]))return true;return false;
}
function gm3_target_index(array $targetSet,array $localNames,array $hotels): array {
    $tokenIndex=[];$names=[];$count=0;
    foreach(array_keys($targetSet) as $lid){$lid=(int)$lid;if(!isset($hotels[$lid]))continue;$country=(int)$hotels[$lid]['country_id'];$nn=array_keys($localNames[$lid]??[]);$nn[]=(string)$hotels[$lid]['name'];$nn=array_values(array_unique(array_filter($nn,static fn($v)=>trim((string)$v)!=='')));$names[$lid]=$nn;foreach($nn as $n)foreach(array_unique(ggr_tokens((string)$n)) as $tok)if(strlen($tok)>=2)$tokenIndex[$country][$tok][$lid]=true;$count++;}
    return [$tokenIndex,$names,$count];
}
function gm3_rank(int $country,array $sourceNames,array $tokenIndex,array $targetNames): array {
    $ids=[];foreach($sourceNames as $n)foreach(array_unique(ggr_tokens((string)$n)) as $tok)foreach(array_keys($tokenIndex[$country][$tok]??[]) as $lid)$ids[(int)$lid]=true;
    $rank=[];foreach(array_keys($ids) as $lid){$best=[0.0,0,'',''];foreach($sourceNames as $s)foreach($targetNames[$lid]??[] as $t){[$score,$shared]=gm3_similarity((string)$s,(string)$t);if($score>$best[0]||($score===$best[0]&&$shared>$best[1]))$best=[$score,$shared,(string)$s,(string)$t];}$rank[]=['local_hotel_id'=>(int)$lid,'score'=>round($best[0],6),'shared'=>(int)$best[1],'source_name'=>$best[2],'target_name'=>$best[3]];}
    usort($rank,static fn($a,$b)=>$b['score']<=>$a['score'] ?: $b['shared']<=>$a['shared'] ?: $a['local_hotel_id']<=>$b['local_hotel_id']);return $rank;
}
function gm3_anex_geo_model(PDO $db,array $hotels): array {
    $st=[];foreach($db->query('SELECT anex_hotel_id,api_region,api_town FROM anex_hotels')->fetchAll(PDO::FETCH_ASSOC) as $r)$st[(int)$r['anex_hotel_id']]=$r;
    $counts=[];$rows=0;foreach($db->query('SELECT anex_hotel_id,catalog_hotel_id FROM anex_hotel_search_mappings WHERE enabled=1')->fetchAll(PDO::FETCH_ASSOC) as $m){$eid=(int)$m['anex_hotel_id'];$lid=(int)$m['catalog_hotel_id'];if(!isset($hotels[$lid]))continue;$src=$st[$eid]??[];$sp=[];foreach([$src['api_region']??'',$src['api_town']??''] as $v){$k=ggr_translit((string)$v);if($k!=='')$sp[$k]=true;}$tp=[];foreach([$hotels[$lid]['region_name']??'',$hotels[$lid]['subregion_name']??''] as $v){$k=ggr_translit((string)$v);if($k!=='')$tp[$k]=true;}foreach(array_keys($sp) as $s)foreach(array_keys($tp) as $t)$counts[$s][$t]=($counts[$s][$t]??0)+1;$rows++;}
    $model=[];foreach($counts as $s=>$dist){$total=array_sum($dist);arsort($dist);$model[$s]=['total'=>$total,'dist'=>$dist,'top'=>(string)array_key_first($dist),'top_count'=>(int)reset($dist)];}return[$model,$rows];
}
function gm3_geo(array $source,array $target,array $model): array {
    $guard=mbr_target_guard($source,$target);if($guard['coordinate_conflict'])return ['type'=>'hard_coordinate_conflict','distance_m'=>$guard['distance_m']];
    $places=array_map('strval',$source['places']??[]);$g=ggr_geo_evidence($places,$target,$model,$guard['distance_m']);return $g+['distance_m'=>$guard['distance_m']];
}
function gm3_accept_rank(array $rank,array $sourceNames,array $targetNames,array $source,array $target,array $geoModel): ?array {
    $best=$rank[0]??null;if(!$best)return null;$second=(float)($rank[1]['score']??0);$margin=(float)$best['score']-$second;
    if((float)$best['score']<0.88||(int)$best['shared']<2||$margin<0.20)return null;
    if(gm3_sym_qualifier_conflict($sourceNames,$targetNames))return null;
    $geo=gm3_geo($source,$target,$geoModel);if(($geo['type']??'none')==='hard_coordinate_conflict'||($geo['type']??'none')==='none')return null;
    $maxTokens=0;foreach($sourceNames as $n)$maxTokens=max($maxTokens,count(ggr_tokens((string)$n)));if($maxTokens<2&&($geo['type']??'')!=='coordinate')return null;
    return ['best'=>$best,'second_score'=>round($second,6),'margin'=>round($margin,6),'geo_evidence'=>$geo,'target'=>mbr_row_target($target),'name_evidence'=>'provider_to_provider_fuzzy_unique_large_margin'];
}
function gm3_review(PDO $db,string $operation): array {
    if($operation!==GM3_OPERATION)throw new RuntimeException('operation_scope');$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION READ ONLY');
    try{
        $coverage=fc_coverage($db);[$hotels,$names,$strict,$broad,$places,$catalogScope]=mbr_catalog($db);$shaCountry=fc_sha_countries($db);[$anexLocal,$androLocal]=mbr_local_sets($db);$anexOnly=array_diff_key($anexLocal,$androLocal);$androOnly=array_diff_key($androLocal,$anexLocal);[$anexIdx,$anexNames]=ggr_provider_name_index($db,'anex',$hotels);[$androIdx,$androNames]=ggr_provider_name_index($db,'andromeda',$hotels);[$anexToken,$anexTargetNames,$anexTargets]=gm3_target_index($anexOnly,$anexNames,$hotels);[$androToken,$androTargetNames,$androTargets]=gm3_target_index($androOnly,$androNames,$hotels);[$androGeo,$androLearnRows]=ggr_learn_geo($db,$hotels);[$anexGeo,$anexLearnRows]=gm3_anex_geo_model($db,$hotels);
        $manual=array_fill_keys(array_map('intval',$db->query('SELECT anex_hotel_id FROM anex_hotel_decisions')->fetchAll(PDO::FETCH_COLUMN)),true);$existing=array_fill_keys(array_map('intval',$db->query('SELECT anex_hotel_id FROM anex_hotel_search_mappings')->fetchAll(PDO::FETCH_COLUMN)),true);$excluded=[];foreach($db->query('SELECT anex_hotel_id,catalog_hotel_id FROM anex_review_pair_exclusions')->fetchAll(PDO::FETCH_ASSOC) as $x)$excluded[(int)$x['anex_hotel_id']][(int)$x['catalog_hotel_id']]=true;$st=[];foreach($db->query('SELECT * FROM anex_hotels')->fetchAll(PDO::FETCH_ASSOC) as $r)$st[(int)$r['anex_hotel_id']]=$r;
        $safe=[];$stats=['anex_examined'=>0,'andromeda_examined'=>0,'ranked_anex'=>0,'ranked_andromeda'=>0,'qualifier_or_geo_or_margin_blocked'=>0];$seen=[];
        $considerAnex=function(int $id,int $country,array $source)use(&$safe,&$stats,$androToken,$androTargetNames,$hotels,$anexGeo,$excluded){$stats['anex_examined']++;$srcNames=array_values(array_unique(array_filter(array_map('strval',$source['names']??[]),static fn($v)=>trim($v)!=='')));$rank=gm3_rank($country,$srcNames,$androToken,$androTargetNames);if(!$rank)return;$stats['ranked_anex']++;$lid=(int)$rank[0]['local_hotel_id'];if(isset($excluded[$id][$lid])||!isset($hotels[$lid])){$stats['qualifier_or_geo_or_margin_blocked']++;return;}$ev=gm3_accept_rank($rank,$srcNames,$androTargetNames[$lid]??[],$source,$hotels[$lid],$anexGeo);if($ev===null){$stats['qualifier_or_geo_or_margin_blocked']++;return;}$safe[]=['provider'=>'anex','external_id'=>$id,'country_id'=>$country,'observed'=>(bool)($source['observed']??false),'search_count'=>(int)($source['search_count']??0),'source_names'=>$srcNames,'source_places'=>$source['places']??[],'graph_rule'=>'missing_third_andromeda_provider_fuzzy']+$ev;};
        foreach($db->query('SELECT * FROM anex_search_hotel_observations ORDER BY search_count DESC,last_seen_utc DESC,anex_hotel_id')->fetchAll(PDO::FETCH_ASSOC) as $o){$id=(int)$o['anex_hotel_id'];$country=(int)$o['country_id'];if(!isset(MBR_CORE8[$country])||isset($manual[$id])||isset($existing[$id]))continue;$seen[$id]=true;$s=$st[$id]??[];$considerAnex($id,$country,['observed'=>true,'search_count'=>(int)$o['search_count'],'names'=>[$o['hotel_name'],$s['api_name']??'',$s['xml_name']??'',$s['xml_alternate_name']??''],'places'=>[$s['api_region']??'',$s['api_town']??''],'latitude'=>$s['latitude']??null,'longitude'=>$s['longitude']??null]);}
        foreach($st as $id=>$s){if(isset($seen[$id])||isset($manual[$id])||isset($existing[$id]))continue;$country=fc_country($s['api_country']??'');if(!$country||!isset(MBR_CORE8[$country]))continue;$considerAnex((int)$id,$country,['observed'=>false,'search_count'=>0,'names'=>[$s['api_name']??'',$s['xml_name']??'',$s['xml_alternate_name']??''],'places'=>[$s['api_region']??'',$s['api_town']??''],'latitude'=>$s['latitude']??null,'longitude'=>$s['longitude']??null]);}
        $latest=[];foreach($db->query("SELECT * FROM andromeda_search_hotel_observations WHERE supplier_namespace='andromeda_catalog' ORDER BY observed_at_utc DESC,external_hotel_id")->fetchAll(PDO::FETCH_ASSOC) as $o){$eid=(string)$o['external_hotel_id'];if(!isset($latest[$eid]))$latest[$eid]=$o;}
        foreach($db->query("SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='pending' AND local_hotel_id IS NULL ORDER BY external_hotel_id")->fetchAll(PDO::FETCH_ASSOC) as $r){$eid=(string)$r['external_hotel_id'];$ob=$latest[$eid]??null;$country=(int)($ob['country_id']??0);if(!isset(MBR_CORE8[$country]))$country=(int)($shaCountry[$r['catalog_sha256']]??0);if(!isset(MBR_CORE8[$country]))continue;$stats['andromeda_examined']++;$e=fc_evidence($r['evidence_json']??'');[$evNames,$evPlaces,$coords]=ggr_source_geo($e);$srcNames=$evNames;if($ob&&trim((string)($ob['hotel_name']??''))!=='')$srcNames[]=(string)$ob['hotel_name'];$srcNames=array_values(array_unique(array_filter($srcNames,static fn($v)=>trim((string)$v)!=='')));$rank=gm3_rank($country,$srcNames,$anexToken,$anexTargetNames);if(!$rank)continue;$stats['ranked_andromeda']++;$lid=(int)$rank[0]['local_hotel_id'];if(!isset($hotels[$lid]))continue;$source=['names'=>$srcNames,'places'=>$evPlaces];if($ob)$source+=$ob;if($coords){$source['latitude']=$coords[0][0];$source['longitude']=$coords[0][1];}$ev=gm3_accept_rank($rank,$srcNames,$anexTargetNames[$lid]??[],$source,$hotels[$lid],$androGeo);if($ev===null){$stats['qualifier_or_geo_or_margin_blocked']++;continue;}$safe[]=['provider'=>'andromeda','external_id'=>$eid,'country_id'=>$country,'source_names'=>$srcNames,'source_places'=>$evPlaces,'graph_rule'=>'missing_third_anex_provider_fuzzy']+$ev;}
        $dedup=[];foreach($safe as $r)$dedup[$r['provider'].':'.$r['external_id']]=$r;$safe=array_values($dedup);usort($safe,static fn($a,$b)=>(int)($b['search_count']??0)<=>(int)($a['search_count']??0) ?: strcmp((string)$a['provider'],(string)$b['provider']) ?: strcmp((string)$a['external_id'],(string)$b['external_id']));$providers=['anex'=>0,'andromeda'=>0];$geo=[];foreach($safe as $r){$providers[$r['provider']]++;$t=(string)($r['geo_evidence']['type']??'none');$geo[$t]=($geo[$t]??0)+1;}ksort($geo);
        $db->commit();return ['status'=>'completed','operation_id'=>$operation,'mode'=>'server_current_missing_third_provider_graph_read_only','database_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'catalog_scope'=>$catalogScope,'coverage'=>$coverage,'missing_third_targets'=>['anex_tv_only'=>$anexTargets,'andromeda_tv_only'=>$androTargets],'learned_geo'=>['andromeda_accepted_rows'=>$androLearnRows,'andromeda_source_places'=>count($androGeo),'anex_accepted_rows'=>$anexLearnRows,'anex_source_places'=>count($anexGeo)],'examined'=>$stats,'counts'=>['safe_consolidated_delta'=>count($safe),'safe_anex'=>$providers['anex'],'safe_andromeda'=>$providers['andromeda']],'safe_geo_evidence'=>$geo,'safe_candidates'=>$safe,'guards'=>['provider_to_provider_only'=>true,'same_provider_target_missing_required'=>true,'score_min'=>0.88,'shared_tokens_min'=>2,'margin_min'=>0.20,'symmetric_qualifier_guard'=>true,'coordinate_conflict_block_m'=>5000,'learned_geo_support_min'=>3,'learned_geo_confidence_min'=>0.95,'single_token_without_coordinate_rejected'=>true,'manual_existing_exclusion_protected'=>true,'database_write'=>false]];
    }catch(Throwable $e){if($db->inTransaction())$db->rollBack();return ['status'=>'failed','operation_id'=>$operation,'database_writes'=>0,'supplier_calls'=>0,'reason'=>in_array($e->getMessage(),['operation_scope','country_contract_changed','hotel_scope_limit','alias_scope_limit'],true)?$e->getMessage():'runtime_failure','error_class'=>get_class($e)];}
}
if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__){$root=realpath(__DIR__.'/../..');require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$out=gm3_review(v2_data_db(),getenv('OPERATION_ID')?:GM3_OPERATION);echo json_encode($out,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT)."\n";exit(($out['status']??'')==='completed'?0:1);}
