<?php
declare(strict_types=1);
require_once __DIR__.'/hotel_match_samo_live30_common4_acquire_v1.php';
require_once __DIR__.'/hotel_match_retained93_primary_write_v84.php';
const M118B_OP='hotel-match-samo-unresolved111-acquire-1971-20260928-v118b';
const M118B_REFRESH_OP='hotel-match-samo-live30-native-refresh-1971-20260928-v117f';
const M118B_REFRESH_SHA='4b9e6c7f4905f8b3cdb25988a226ffa55774157f1d66519dad521dcc5b7fb7c0';
const M118B_OPS=[5=>'operator_5',115=>'operator_115',315=>'operator_315',342=>'operator_342'];
function m118b_need(bool$b,string$m):void{if(!$b)throw new RuntimeException($m);}
function m118b_plan(string$ops):array{
 $x=w84_read($ops.'/'.M118B_REFRESH_OP.'/result.json',M118B_REFRESH_SHA,33554432);m118b_need(($x['state']??'')==='completed_retained_native_scan'&&($x['live30_catalog_sources']??0)===1895&&($x['live30_unmapped_catalog_sources']??0)===111,'refresh');
 $rows=[];$pairs=0;
 foreach($x['source_frontier'] as$s){if(($s['current_accepted_locals']??[])!==[])continue;$cid=(string)$s['catalog_id'];$states=[];$opsSeen=[];
  foreach($s['contexts']??[]as$c){foreach($c['provider_requests']??[]as$p){$v=(int)($p['params']['STATEINC']??0);if($v>0)$states[$v]=true;}$o=(int)($c['offer']['operator_ref']??0);if(isset(M118B_OPS[$o]))$opsSeen[$o]=true;}
  if(count($states)!==1||!$opsSeen)continue;$state=(int)array_key_first($states);$opids=array_keys($opsSeen);sort($opids,SORT_NUMERIC);$pairs+=count($opids);$rows[]=['catalog_id'=>$cid,'stateinc'=>$state,'operator_ids'=>$opids];
 }
 m118b_need(count($rows)===111&&$pairs===127,'plan_counts');usort($rows,fn($a,$b)=>[(int)$a['stateinc'],(int)$a['catalog_id']]<=>[(int)$b['stateinc'],(int)$b['catalog_id']]);return$rows;
}
function m118b_groups(array$rows):array{$b=[];foreach($rows as$r)foreach($r['operator_ids']as$o)$b[$r['stateinc'].'|'.$o][]=$r['catalog_id'];$out=[];foreach($b as$k=>$ids){[$s,$o]=array_map('intval',explode('|',$k));sort($ids,SORT_NATURAL);for($i=0;$i<count($ids);$i+=12)$out[]=['stateinc'=>$s,'operator_id'=>$o,'hotel_ids'=>array_slice($ids,$i,12)];}usort($out,fn($a,$b)=>[$a['stateinc'],$a['operator_id'],(int)$a['hotel_ids'][0]]<=>[$b['stateinc'],$b['operator_id'],(int)$b['hotel_ids'][0]]);return$out;}
function m118b_main(array$a):int{
 m118b_need(($a[1]??'')==='--execute','disabled');$root=(string)getenv('ANYTOUR_ROOT');$dir=(string)getenv('MATCH_OPERATION_DIR');$head=(string)getenv('MATCH_SOURCE_SHA');m118b_need(is_dir($root)&&basename($root)==='anytoour.ru'&&is_dir($dir)&&basename($dir)===M118B_OP&&preg_match('/^[a-f0-9]{40}$/D',$head),'scope');foreach(['result.json','receipt.json']as$f)m118b_need(!file_exists($dir.'/'.$f),'no_replay');$rv=slc4a_load($dir.'/reservation.json');m118b_need(($rv['operation']??'')===M118B_OP&&($rv['state']??'')==='reserved_before_provider','reservation');
 $rows=m118b_plan(dirname($dir));$groups=m118b_groups($rows);m118b_need(count($groups)===14,'group_count');$app=dirname(__DIR__,2).'/app/integrations';require_once $app.'/andromeda-client.php';require_once $app.'/andromeda-transport.php';$cfg=slc4a_private_config($root);$private=dirname((string)$cfg['catalog_path']);$townfrom=slc4a_moscow_departure((string)$cfg['catalog_path']);$from=(new DateTimeImmutable('tomorrow',new DateTimeZone('Europe/Moscow')))->format('Ymd');$to=(new DateTimeImmutable('tomorrow +20 days',new DateTimeZone('Europe/Moscow')))->format('Ymd');$calls=0;$last=0.0;$evidence=$dir.'/evidence-private';mkdir($evidence,0700,true);
 $call=function(string$url,array$opts)use($private,$dir,&$calls,&$last){$q=[];parse_str((string)parse_url($url,PHP_URL_QUERY),$q);$action=(string)($q['action']??'unknown');$next=$calls+1;m118b_need($next<=500,'http_cap');slc4a_budget($private,$next,$action);$calls=$next;slc4a_save($dir.'/http-'.str_pad((string)$calls,4,'0',STR_PAD_LEFT).'-reserved.json',['operation'=>M118B_OP,'call'=>$calls,'action'=>$action,'state'=>'reserved_before_http']);$wait=1.05-(microtime(true)-$last);if($wait>0)usleep((int)ceil($wait*1000000));$tr=new AnyTourAndromedaTransport(true);$last=microtime(true);return$tr($url,$opts);};
 $edge=[];foreach($rows as$r)foreach($r['operator_ids']as$o)$edge[$r['catalog_id'].'|'.$o]=['catalog_id'=>$r['catalog_id'],'stateinc'=>$r['stateinc'],'operator_id'=>$o,'namespace'=>M118B_OPS[$o],'returned_catalog'=>false,'native_ids'=>[],'price_rows'=>0,'evidence'=>[]];
 $batchOut=[];$errors=0;$state='failed_before_provider';$reason=null;
 try{slc4a_save($dir.'/login-reserved.json',['operation'=>M118B_OP,'state'=>'reserved_before_login']);$login=new AnyTourAndromedaClient($call,true);$login->login((string)$cfg['username'],(string)$cfg['password']);$session=$login->privateSession();m118b_need($session!==[],'login');slc4a_save($dir.'/login-result.json',['operation'=>M118B_OP,'state'=>'login_succeeded']);
  foreach($groups as$bi=>$g){$batch=$bi+1;$requested=array_fill_keys($g['hotel_ids'],true);$pages=0;$pcLast=null;$bs='complete';$err=null;
   for($page=1;$page<=1000;$page++){$params=['TOWNFROMINC'=>$townfrom,'STATEINC'=>$g['stateinc'],'CHECKIN_BEG'=>$from,'CHECKIN_END'=>$to,'NIGHTS_FROM'=>7,'NIGHTS_TILL'=>7,'ADULT'=>2,'CHILD'=>0,'CURRENCYINC'=>643,'PACKETTYPE'=>0,'PAGE'=>$page,'OPERATORS'=>(string)$g['operator_id'],'HOTELS'=>implode(',',$g['hotel_ids']),'GROUP_BY'=>32];slc4a_save($dir.'/batch-'.str_pad((string)$batch,3,'0',STR_PAD_LEFT).'-page-'.$page.'-reserved.json',['operation'=>M118B_OP,'batch'=>$batch,'page'=>$page,'state'=>'reserved_before_price']);
    try{$cl=new AnyTourAndromedaClient($call,true);$cl->restorePrivateSession($session);$reply=$cl->price($params);}catch(Throwable$e){$bs='supplier_error';$err=preg_replace('/[^A-Za-z0-9_.:-]+/','_',mb_substr($e->getMessage(),0,100,'UTF-8'));$errors++;break;}
    $pages++;$pc=(int)($reply['PAGES_COUNT']??-1);m118b_need($pc>=0&&$pc<=1000,'pages_count');$pcLast=$pc;$raw=slc4a_json($reply);$hash=hash('sha256',$raw);$file='batch-'.str_pad((string)$batch,3,'0',STR_PAD_LEFT).'-page-'.$page.'.json';file_put_contents($evidence.'/'.$file,$raw."\n",LOCK_EX);
    foreach(($reply['PRICES']??[])as$price){if(!is_array($price))continue;$b=slc4a_bridge($price,$g['operator_id'],$requested);if(($b['catalog_id']??null)===null)continue;$k=$b['catalog_id'].'|'.$g['operator_id'];if(!isset($edge[$k]))continue;$edge[$k]['price_rows']++;if($b['state']==='exact_catalog_to_native'){$edge[$k]['returned_catalog']=true;$edge[$k]['native_ids'][$b['native_id']]=true;$edge[$k]['evidence'][]=['file'=>'evidence-private/'.$file,'sha256'=>$hash,'page'=>$page];}elseif($b['state']==='catalog_only')$edge[$k]['returned_catalog']=true;}
    if($pc===0||$page>=$pc)break;
   }$batchOut[]=['batch'=>$batch,'state'=>$bs,'reason'=>$err,'stateinc'=>$g['stateinc'],'operator_id'=>$g['operator_id'],'hotel_count'=>count($g['hotel_ids']),'pages_count'=>$pcLast,'pages_drained'=>$pages];
  }$state=$errors===0?'completed_read_only':'completed_read_only_partial';
 }catch(Throwable$e){$reason=preg_replace('/[^A-Za-z0-9_.:-]+/','_',mb_substr($e->getMessage(),0,140,'UTF-8'));$state=$calls>0?'terminal_failed_no_replay':'failed_before_provider';}
 $edges=[];$counts=[];$single=0;foreach($edge as$e){$ids=array_keys($e['native_ids']);sort($ids,SORT_NATURAL);unset($e['native_ids']);$e['positive_native_candidates']=$ids;$e['state']=count($ids)===1?'captured_single_native':(count($ids)>1?'captured_ambiguous_native':($e['returned_catalog']?'catalog_only':'not_returned_in_context'));$e['safe_to_write_now']=false;$edges[]=$e;$counts[$e['state']]=($counts[$e['state']]??0)+1;if($e['state']==='captured_single_native')$single++;}ksort($counts);
 $out=['operation'=>M118B_OP,'state'=>$state,'reason'=>$reason,'source_sha'=>$head,'generated_at_utc'=>gmdate('c'),'unresolved_source_count'=>111,'planned_pair_count'=>127,'planned_group_count'=>14,'townfrom'=>$townfrom,'checkin_beg'=>$from,'checkin_end'=>$to,'samo_http_calls'=>$calls,'provider_http_calls'=>$calls,'batch_error_count'=>$errors,'edge_state_counts'=>$counts,'captured_single_native_count'=>$single,'batches'=>$batchOut,'edges'=>$edges,'database_writes'=>0,'mapping_writes'=>0,'safe_to_write_now'=>false,'no_replay'=>$calls>0];
 $h=slc4a_save($dir.'/result.json',$out);slc4a_save($dir.'/receipt.json',['operation'=>M118B_OP,'state'=>$state,'result_sha256'=>$h,'provider_http_calls'=>$calls,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>$calls>0]);echo slc4a_json(array_diff_key($out,['batches'=>true,'edges'=>true]))."\n";return in_array($state,['completed_read_only','completed_read_only_partial'],true)?0:2;
}
if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__)exit(m118b_main($argv));
