<?php
declare(strict_types=1);

const V39_OP='hotel-match-samo-registry-current-bridge-audit-1971-20260925-v39';
const V39_V38_OP='hotel-match-samo-registry-consensus-1971-20260925-v38';
const V39_V38_SHA='fcb21a9ac50d3b1777db003f28d555d106ec8a81';
const V39_FRONTIER_OP='hotel-match-business-live30-frontier-plan-1971-20260925-v33';
const V39_FRONTIER_SHA='5001297e29a920acc2d565e45fec0e4d0a5b2244e0ba60a860941be882ad1c77';
const V39_NS=['operator_5'=>true,'operator_115'=>true,'operator_315'=>true,'operator_342'=>true];

function v39_need(bool $v,string $m):void{if(!$v)throw new RuntimeException($m);}
function v39_json(mixed $v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
function v39_save(string $p,array $v):string{$raw=v39_json($v)."\n";$f=@fopen($p,'x+b');v39_need($f!==false,'exclusive_create');try{v39_need(fwrite($f,$raw)===strlen($raw)&&fflush($f),'durable_write');if(function_exists('fsync'))v39_need(fsync($f),'durable_sync');}finally{fclose($f);}return hash('sha256',$raw);}
function v39_load(string $p):array{$v=json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);v39_need(is_array($v),'json_shape');return$v;}
function v39_id(mixed $v):?string{$s=trim((string)$v);return preg_match('/^[1-9][0-9]{0,21}$/D',$s)===1?$s:null;}
function v39_int(mixed $v):?int{$s=v39_id($v);if($s===null||strlen($s)>9)return null;$n=(int)$s;return$n>0?$n:null;}
function v39_query(PDO $db,string $sql,array $args=[]):array{$st=$db->prepare($sql);$st->execute(array_values($args));return$st->fetchAll(PDO::FETCH_ASSOC)?:[];}
function v39_excluded(string $v):bool{return preg_match('/^(?:россия|абхазия|russia|russian federation|abkhazia)$/iu',trim($v))===1;}
function v39_sha(string $s):bool{return preg_match('/^[0-9a-f]{64}$/D',$s)===1;}
function v39_frontier(array $f):array{
    v39_need(($f['operation']??'')===V39_FRONTIER_OP,'frontier_op');v39_need(($f['state']??'')==='completed_read_only_business_live30_frontier_plan','frontier_state');v39_need((int)($f['non_full_triple_total']??0)===1737,'frontier_total');v39_need(($f['target_set_sha256']??'')===V39_FRONTIER_SHA,'frontier_sha');$exp=['tv_samo_missing_anex'=>777,'tv_anex_missing_samo'=>234,'tv_only_missing_both'=>726];v39_need(($f['bucket_counts']??null)===$exp,'frontier_buckets');$out=[];foreach($f['rows']??[] as $r){if(!is_array($r))continue;$id=v39_int($r['local_hotel_id']??null);$b=(string)($r['bucket']??'');if($id!==null&&isset($exp[$b]))$out[$id]=$b;}v39_need(count($out)===1737,'frontier_rows');return$out;
}
function v39_v38_rows(array $r):array{
    v39_need(($r['operation']??'')===V39_V38_OP,'v38_op');v39_need(($r['state']??'')==='completed_read_only_samo_registry_consensus','v38_state');v39_need(($r['source_sha']??'')===V39_V38_SHA,'v38_source_sha');v39_need((int)($r['frontier_total']??0)===1737&&($r['frontier_target_sha256']??'')===V39_FRONTIER_SHA,'v38_frontier');foreach(['provider_http_calls','tourvisor_calls','samo_calls','anex_calls','andromeda_calls','database_writes','mapping_writes'] as $k)v39_need((int)($r[$k]??-1)===0,'v38_zero_'.$k);v39_need(($r['safe_to_write_now']??null)===false,'v38_safe');$out=[];foreach($r['rows']??[] as $x){if(!is_array($x))continue;$n=(int)($x['consensus_operator_count']??0);$st=(string)($x['status']??'');if($n>=2&&preg_match('/^registry_[234]plus_review$/D',$st)===1)$out[]=$x;}v39_need(count($out)===551,'v38_multi_count');return$out;
}
function v39_current(PDO $db,array $frontier):array{
    $db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION READ ONLY');try{
        $active=[];foreach(v39_query($db,"SELECT id,name,country_name,region_name,subregion_name,category,is_active FROM catalog_hotels WHERE is_active=1") as $r){$id=(int)$r['id'];if(isset($frontier[$id]))$active[$id]=$r;}
        $catalogSource=[];$catalogTarget=[];$catalogNonAccepted=[];$registry=[];
        foreach(v39_query($db,"SELECT supplier_namespace,external_hotel_id,local_hotel_id,decision_status,catalog_sha256,evidence_sha256,evidence_json FROM andromeda_hotel_identities ORDER BY supplier_namespace,external_hotel_id,local_hotel_id") as $r){$ns=(string)$r['supplier_namespace'];$ext=(string)$r['external_hotel_id'];if($ns==='andromeda_catalog'){$catalogSource[$ext][]=$r;if(($r['decision_status']??'')==='accepted'&&$r['local_hotel_id']!==null)$catalogTarget[(int)$r['local_hotel_id']][]=$r;elseif(($r['decision_status']??'')!=='accepted')$catalogNonAccepted[$ext][]=($r['decision_status']??'');continue;}if(!isset(V39_NS[$ns])||($r['decision_status']??'')!=='accepted'||$r['local_hotel_id']===null)continue;$raw=(string)($r['evidence_json']??'');$eh=(string)($r['evidence_sha256']??'');$valid=v39_sha($eh)&&hash('sha256',$raw)===$eh;$ops=[];if($valid){preg_match_all('/hotel-match-[a-z0-9_.-]+/i',$raw,$m);$ops=array_values(array_unique($m[0]??[]));sort($ops,SORT_STRING);$ops=array_slice($ops,0,8);}$registry[$ns.'|'.$ext][]=['local_hotel_id'=>(int)$r['local_hotel_id'],'evidence_sha256'=>$eh,'evidence_valid'=>$valid,'operations'=>$ops,'catalog_sha256'=>(string)($r['catalog_sha256']??'')];}
        $manual=[];foreach(v39_query($db,"SELECT DISTINCT catalog_hotel_id FROM anex_hotel_decisions WHERE catalog_hotel_id IS NOT NULL") as $r)$manual[(int)$r['catalog_hotel_id']]=true;$db->rollBack();return compact('active','catalogSource','catalogTarget','catalogNonAccepted','registry','manual');
    }catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw$e;}
}
function v39_lane_current(string $ns,array $lane,int $target,array $cur):array{
    if(($lane['state']??'')!=='registry_unique')return['state'=>'input_lane_not_unique'];$native=v39_id($lane['native_id']??null);if($native===null)return['state'=>'input_native_invalid'];$rows=$cur['registry'][$ns.'|'.$native]??[];$targets=[];$evidence=[];foreach($rows as $r){$targets[(int)$r['local_hotel_id']]=true;$evidence[]=['evidence_sha256'=>$r['evidence_sha256'],'evidence_valid'=>$r['evidence_valid'],'operations'=>$r['operations'],'catalog_sha256'=>$r['catalog_sha256']];}if(count($targets)===0)return['state'=>'current_registry_missing','native_id'=>$native,'evidence'=>$evidence];if(count($targets)>1)return['state'=>'current_registry_collision','native_id'=>$native,'targets'=>array_map('intval',array_keys($targets)),'evidence'=>$evidence];$now=(int)array_key_first($targets);if($now!==$target)return['state'=>'current_registry_target_drift','native_id'=>$native,'target'=>$now,'evidence'=>$evidence];foreach($evidence as $e)if(!$e['evidence_valid'])return['state'=>'current_registry_invalid_evidence','native_id'=>$native,'target'=>$now,'evidence'=>$evidence];return['state'=>'current_registry_exact','native_id'=>$native,'target'=>$now,'evidence'=>$evidence];
}
function v39_classify(array $in,array $frontier,array $cur):array{
    $src=v39_id($in['andromeda_catalog_id']??null);$target=v39_int($in['candidate_local_hotel_id']??null);v39_need($src!==null&&$target!==null,'input_identity');$expected=(int)$in['consensus_operator_count'];$lanes=[];$good=0;$invalid=false;foreach(V39_NS as $ns=>$_){$lane=$in['lanes'][$ns]??null;if(!is_array($lane)||($lane['state']??'')!=='registry_unique')continue;$x=v39_lane_current($ns,$lane,$target,$cur);$lanes[$ns]=$x;if($x['state']==='current_registry_exact')$good++;else$invalid=true;}$status='hold_current_registry_drift';$reason='current_registry_drift';$bucket=$frontier[$target]??null;
    if(!$invalid&&$good===$expected&&$good>=2){$srcRows=$cur['catalogSource'][$src]??[];$same=array_filter($srcRows,fn($r)=>(($r['decision_status']??'')==='accepted'&&(int)($r['local_hotel_id']??0)===$target));$other=array_filter($srcRows,fn($r)=>(($r['decision_status']??'')==='accepted'&&(int)($r['local_hotel_id']??0)!==$target));$targetRows=$cur['catalogTarget'][$target]??[];$foreignTarget=array_filter($targetRows,fn($r)=>(string)($r['external_hotel_id']??'')!==$src);
        if($same){$status='already_resolved_same';$reason='source_already_maps_target';}
        elseif($other){$status='hold_source_occupied';$reason='source_maps_other_target';}
        elseif(isset($cur['catalogNonAccepted'][$src])){$status='hold_source_nonaccepted_history';$reason='source_has_nonaccepted_row';}
        elseif($foreignTarget){$status='hold_target_samo_occupied';$reason='target_has_other_andromeda_catalog';}
        elseif($bucket===null){$status='hold_target_outside_frontier';$reason='target_not_v33_frontier';}
        elseif(!isset($cur['active'][$target])||v39_excluded((string)($cur['active'][$target]['country_name']??''))){$status='hold_target_inactive_or_excluded';$reason='target_not_eligible';}
        elseif(isset($cur['manual'][$target])){$status='hold_manual_target';$reason='manual_target_protected';}
        elseif($bucket==='tv_samo_missing_anex'){$status='hold_unexpected_samo_bucket_without_anchor';$reason='v33_bucket_already_samo';}
        elseif(in_array($bucket,['tv_anex_missing_samo','tv_only_missing_both'],true)){$status='deterministic_current_missing';$reason='multi_operator_consensus_anchorless_target';}
        else{$status='hold_unknown_bucket';$reason='bucket';}
    }
    return['andromeda_catalog_id'=>$src,'candidate_local_hotel_id'=>$target,'frontier_bucket'=>$bucket,'operator_count'=>$expected,'current_exact_operator_count'=>$good,'status'=>$status,'reason'=>$reason,'lanes'=>$lanes,'safe_to_write_now'=>false];
}
function v39_execute(PDO $db,array $v38,array $frontierDoc,string $sourceSha):array{
    $frontier=v39_frontier($frontierDoc);$inputs=v39_v38_rows($v38);$cur=v39_current($db,$frontier);$rows=[];$status=[];$byOps=['2'=>0,'3'=>0,'4'=>0];$byBucket=['tv_anex_missing_samo'=>0,'tv_only_missing_both'=>0,'tv_samo_missing_anex'=>0];foreach($inputs as $in){$r=v39_classify($in,$frontier,$cur);$rows[]=$r;$status[$r['status']]=($status[$r['status']]??0)+1;if($r['status']==='deterministic_current_missing'){$byOps[(string)$r['operator_count']]++;if(isset($byBucket[$r['frontier_bucket']]))$byBucket[$r['frontier_bucket']]++;}}ksort($status);usort($rows,fn($a,$b)=>[$a['status'],$a['candidate_local_hotel_id'],$a['andromeda_catalog_id']]<=>[$b['status'],$b['candidate_local_hotel_id'],$b['andromeda_catalog_id']]);return['operation'=>V39_OP,'state'=>'completed_read_only_samo_registry_current_bridge_audit','generated_at_utc'=>gmdate('c'),'source_sha'=>$sourceSha,'v38_source_sha'=>V39_V38_SHA,'input_multi_operator_count'=>count($inputs),'frontier_total'=>count($frontier),'candidate_status_counts'=>$status,'deterministic_current_missing_count'=>(int)($status['deterministic_current_missing']??0),'deterministic_by_operator_count'=>$byOps,'deterministic_by_v33_bucket'=>$byBucket,'rows'=>$rows,'provider_http_calls'=>0,'tourvisor_calls'=>0,'samo_calls'=>0,'anex_calls'=>0,'andromeda_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'safe_to_write_now'=>false];
}
function v39_self_test():void{
    $lane=['state'=>'registry_unique','native_id'=>'7'];$cur=['registry'=>['operator_315|7'=>[['local_hotel_id'=>100,'evidence_sha256'=>str_repeat('a',64),'evidence_valid'=>true,'operations'=>[],'catalog_sha256'=>str_repeat('b',64)]],'operator_342|8'=>[['local_hotel_id'=>100,'evidence_sha256'=>str_repeat('c',64),'evidence_valid'=>true,'operations'=>[],'catalog_sha256'=>str_repeat('b',64)]]],'catalogSource'=>[],'catalogTarget'=>[],'catalogNonAccepted'=>[],'active'=>[100=>['country_name'=>'Турция']],'manual'=>[]];$in=['andromeda_catalog_id'=>'900','candidate_local_hotel_id'=>100,'consensus_operator_count'=>2,'lanes'=>['operator_315'=>$lane,'operator_342'=>['state'=>'registry_unique','native_id'=>'8']]];$r=v39_classify($in,[100=>'tv_only_missing_both'],$cur);v39_need($r['status']==='deterministic_current_missing'&&$r['current_exact_operator_count']===2,'deterministic');$cur['catalogTarget'][100]=[['external_hotel_id'=>'901','local_hotel_id'=>100,'decision_status'=>'accepted']];$r=v39_classify($in,[100=>'tv_only_missing_both'],$cur);v39_need($r['status']==='hold_target_samo_occupied','occupied');
}
if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__){if(in_array('--self-test',$argv??[],true)){v39_self_test();echo"MATCH_SAMO_REGISTRY_CURRENT_BRIDGE_AUDIT_V39_SELFTEST_OK\n";exit;}v39_need(($argv[1]??'')==='--execute','disabled');$root=(string)getenv('ANYTOUR_ROOT');$dir=(string)getenv('MATCH_OPERATION_DIR');$v38p=(string)getenv('MATCH_V38_RESULT');$v38sha=(string)getenv('MATCH_V38_RESULT_SHA');$fp=(string)getenv('MATCH_FRONTIER_RESULT');$fsha=(string)getenv('MATCH_FRONTIER_RESULT_SHA');$sha=(string)getenv('MATCH_SOURCE_SHA');v39_need(is_dir($root)&&is_dir($dir)&&basename($dir)===V39_OP&&is_file($v38p)&&v39_sha($v38sha)&&hash_file('sha256',$v38p)===$v38sha&&is_file($fp)&&v39_sha($fsha)&&hash_file('sha256',$fp)===$fsha&&preg_match('/^[0-9a-f]{40}$/D',$sha)===1,'runtime_scope');$res=v39_load($dir.'/reservation.json');v39_need(($res['operation']??'')===V39_OP&&($res['state']??'')==='reserved_before_read_only_audit','reservation');require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');try{$out=v39_execute(v2_data_db(),v39_load($v38p),v39_load($fp),$sha);$h=v39_save($dir.'/result.json',$out);v39_save($dir.'/receipt.json',['operation'=>V39_OP,'state'=>$out['state'],'result_sha256'=>$h,'readback_verified'=>hash_file('sha256',$dir.'/result.json')===$h,'provider_accessed'=>false,'provider_http_calls'=>0,'database_writes'=>0,'mapping_writes'=>0]);echo v39_json(['state'=>$out['state'],'candidate_status_counts'=>$out['candidate_status_counts'],'deterministic_current_missing_count'=>$out['deterministic_current_missing_count'],'deterministic_by_operator_count'=>$out['deterministic_by_operator_count'],'deterministic_by_v33_bucket'=>$out['deterministic_by_v33_bucket']])."\n";}catch(Throwable$e){$f=['operation'=>V39_OP,'state'=>'failed_read_only_samo_registry_current_bridge_audit','reason'=>preg_replace('/[^A-Za-z0-9_.:-]+/','_',mb_substr($e->getMessage(),0,180,'UTF-8')),'provider_http_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'safe_to_write_now'=>false];$h=v39_save($dir.'/result.json',$f);v39_save($dir.'/receipt.json',['operation'=>V39_OP,'state'=>$f['state'],'result_sha256'=>$h,'readback_verified'=>true,'provider_accessed'=>false,'provider_http_calls'=>0,'database_writes'=>0,'mapping_writes'=>0]);fwrite(STDERR,$f['reason']."\n");exit(2);}}
