<?php
declare(strict_types=1);
const U153_OP='hotel-match-userseen153-anex-samo-1971-20260919-v1',U153_ROUTER='d69b80d4c47dc1406b50184ff811bb8665bafda6a6e64bc407c1c130e874bb1e',U153_MAX_CALLS=180,U153_MAX_PRICE=150,U153_MAX_PAGES=8;
require_once __DIR__.'/hotel_match_userseen153_anex_samo_helpers_v1.php';require_once __DIR__.'/hotel_match_userseen153_anex_samo_core_v1.php';
if(in_array('--self-test',$argv??[],true)){lm_need(u153_dict([['id'=>1,'name'=>'China']],['China'])===1,'dict');echo"USERSEEN153_SELFTEST_OK\n";exit(0);}
$dir=(string)getenv('MATCH_OPERATION_DIR');$root=realpath((string)getenv('ANYTOUR_ROOT'));$rp=realpath((string)getenv('MATCH_ROUTER_PATH'));$sha=(string)getenv('MATCH_SOURCE_SHA');lm_need(PHP_SAPI==='cli'&&is_dir($dir)&&basename($dir)===U153_OP&&is_string($root)&&is_string($rp)&&hash_file('sha256',$rp)===U153_ROUTER&&preg_match('/^[a-f0-9]{40}$/D',$sha),'runtime');$res=json_decode((string)file_get_contents($dir.'/reservation.json'),true,32,JSON_THROW_ON_ERROR);lm_need(($res['operation']??'')===U153_OP&&($res['state']??'')==='reserved_before_provider_access','reservation');
require_once $dir.'/payload/andromeda-network-transport-failure.php';require_once $dir.'/payload/andromeda-transport.php';require_once $dir.'/payload/andromeda-client.php';$router=json_decode((string)file_get_contents($rp),true,128,JSON_THROW_ON_ERROR);lm_need(($router['state']??'')==='completed_read_only'&&($router['routed_count']??0)===153,'router');$stdin=file('php://stdin',FILE_IGNORE_NEW_LINES);$user=trim((string)($stdin[0]??''));$pass=trim((string)($stdin[1]??''));unset($stdin);lm_need($user!==''&&$pass!=='','credentials');
try{$result=u153_run($dir,$root,$router,$user,$pass,$sha);}catch(Throwable $e){$ledger=is_file($dir.'/provider-calls.jsonl')?file($dir.'/provider-calls.jsonl',FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES):[];$result=['operation'=>U153_OP,'state'=>$ledger?'terminal_failed_no_replay':'failed_before_provider_access','source_sha'=>$sha,'router_sha256'=>U153_ROUTER,'reason'=>preg_replace('/[^A-Za-z0-9_.:-]/','_',lm_text($e->getMessage(),120)),'provider_calls'=>count($ledger),'price_calls'=>count(array_filter($ledger,fn($x)=>str_contains($x,'"kind":"price"'))),'tourvisor_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>(bool)$ledger];if(is_file($dir.'/raw-manifest.json'))$result['raw_manifest_sha256']=hash_file('sha256',$dir.'/raw-manifest.json');}
$rh=lm_json_file($dir.'/result.json',$result);lm_json_file($dir.'/receipt.json',['operation'=>U153_OP,'state'=>$result['state'],'result_sha256'=>$rh,'provider_calls'=>$result['provider_calls'],'price_calls'=>$result['price_calls'],'tourvisor_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'raw_manifest_sha256'=>$result['raw_manifest_sha256']??null,'no_replay'=>$result['no_replay']]);echo json_encode(['state'=>$result['state'],'active'=>$result['current_active_targets']??null,'provider_calls'=>$result['provider_calls'],'price_calls'=>$result['price_calls'],'state_counts'=>$result['state_counts']??null,'reason'=>$result['reason']??null],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";exit(($result['state']??'')==='completed_read_only'?0:2);
