<?php
declare(strict_types=1);

const OP='hotel-match-global-originalkey-crossprovider-1971-20260916-v1';
const OPERATOR_NS=['operator_5','operator_315','operator_342','operator_115'];
function jj($v){return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
function putj($p,$v){$s=jj($v)."\n";$f=@fopen($p,'x');if(!$f)throw new RuntimeException('durable_open');fwrite($f,$s);fflush($f);fclose($f);if(file_get_contents($p)!==$s)throw new RuntimeException('durable_readback');return hash('sha256',$s);}
function dbpath($r){foreach([$r.'/data/db-v1.php',$r.'/v2/data/db-v1.php']as$p)if(is_file($p))return$p;throw new RuntimeException('db_missing');}
function qa($d,$s,$p=[]){$q=$d->prepare($s);$q->execute($p);return$q->fetchAll(PDO::FETCH_ASSOC)?:[];}
function ev($s){try{$v=json_decode((string)$s,true,128,JSON_THROW_ON_ERROR);return is_array($v)?$v:[];}catch(Throwable){return[];}}
function src($e){return is_array($e['source']??null)?$e['source']:$e;}
function first($a,$ks){foreach($ks as$k)if(isset($a[$k])&&is_scalar($a[$k])&&trim((string)$a[$k])!=='')return trim((string)$a[$k]);return null;}
function marker($v){if(!is_array($v))return false;foreach($v as$k=>$x){$k=mb_strtolower((string)$k,'UTF-8');if(in_array($k,['manual','manual_decision','excluded','exclusion','rejected','protected','pair_exclusion','conflict'],true)&&($x===true||$x===1||$x==='1'||(is_string($x)&&trim($x)!==''&&!in_array(mb_strtolower(trim($x),'UTF-8'),['false','none','no','0'],true))))return true;if(is_array($x)&&marker($x))return true;}return false;}
function norm($s){$s=mb_strtolower((string)$s,'UTF-8');$s=strtr($s,['ё'=>'е','é'=>'e','è'=>'e','á'=>'a','à'=>'a','ä'=>'a','ö'=>'o','ü'=>'u','ç'=>'c','ş'=>'s','ğ'=>'g','ı'=>'i','ñ'=>'n']);$s=preg_replace('/[^\p{L}\p{N}]+/u',' ',$s)??$s;return trim(preg_replace('/\s+/u',' ',$s)??$s);}
function toks($s){$g=['hotel','hotels','resort','resorts','spa','the','and','by','отель','спа'];return array_values(array_unique(array_diff(explode(' ',norm($s)),$g,[''])));}
function sig($s){$q=['annex','beach','garden','gardens','north','south','east','west','adult','adults','only','family','palace','park','villa','villas','suite','suites','club','wing','aqua','aquapark','aquamarine','pool','private'];$qq=array_values(array_intersect(toks($s),$q));preg_match_all('/(?<!\p{L})\d+(?!\p{L})/u',norm($s),$m);$nn=array_values(array_unique($m[0]??[]));sort($qq);sort($nn);return[$qq,$nn];}
function nameguard($a,$b){if(!$a||!$b)return['ok'=>true,'reason'=>'missing_name_nonblocking'];[$aq,$an]=sig($a);[$bq,$bn]=sig($b);if($aq!==$bq)return['ok'=>false,'reason'=>'qualifier_conflict','source'=>$aq,'target'=>$bq];if(($an||$bn)&&$an!==$bn)return['ok'=>false,'reason'=>'numeric_conflict','source'=>$an,'target'=>$bn];return['ok'=>true,'reason'=>'compatible'];}
function num($v){return is_scalar($v)&&is_numeric((string)$v)?(float)$v:null;}
function coords($e){$o=[];$ss=[];$s=src($e);if($s)$ss[]=$s;foreach(['geography','geo','coordinates']as$k)if(is_array($e[$k]??null))$ss[]=$e[$k];foreach($ss as$v){$a=num($v['latitude']??$v['lat']??$v['hotelLatitude']??null);$b=num($v['longitude']??$v['lng']??$v['lon']??$v['hotelLongitude']??null);if($a!==null&&$b!==null&&abs($a)<=90&&abs($b)<=180&&!($a==0.0&&$b==0.0))$o[]=[$a,$b];}return$o;}
function km($a,$b,$c,$d){$r=6371.0088;$p1=deg2rad($a);$p2=deg2rad($c);$h=sin(deg2rad($c-$a)/2)**2+cos($p1)*cos($p2)*sin(deg2rad($d-$b)/2)**2;return 2*$r*asin(min(1,sqrt($h)));}
function statekey($e){return(string)(first(src($e),['stateKey','state_id','countryKey'])??'');}
function corelabel($name,$slug){$x=norm((string)$name.' '.(string)$slug);$tests=['egypt'=>['египет','egypt','egipet'],'turkey'=>['турция','turkey','turtsiya'],'thailand'=>['таиланд','thailand','tailand'],'uae'=>['оаэ','uae','oae','emirates'],'vietnam'=>['вьетнам','vietnam','vetnam'],'sri_lanka'=>['шри ланка','sri lanka','shri lanka'],'maldives'=>['мальдивы','maldives','maldivy'],'cuba'=>['куба','cuba','kuba']];foreach($tests as$k=>$vv)foreach($vv as$v)if(str_contains($x,$v))return$k;return null;}
function bridgeids($e,$ns,$local){$out=[];$schema=(string)($e['schema']??'');if($schema==='operator-original-price-bridge/1'){foreach(($e['provider_bridges']??[])as$f){if(!is_array($f)||($f['action']??null)!=='price'||($f['is_operator_hotel_key']??true)!==false)continue;$op=(string)($f['operator_key']??'');if('operator_'.$op!==$ns)continue;$id=$f['andromeda_hotel_id']??null;if(is_scalar($id)&&preg_match('/^[1-9][0-9]{0,19}$/D',(string)$id))$out[(string)$id]=['schema'=>$schema,'request_sha256'=>$f['request_sha256']??null,'response_sha256'=>$f['response_sha256']??null];}}elseif($schema==='received-nonanex-exact-missing-native/1'){$s=is_array($e['source']??null)?$e['source']:[];$d=is_array($e['decision']??null)?$e['decision']:[];$id=$s['andromeda_hotel_id']??null;if(($s['supplier_namespace']??null)===$ns&&is_scalar($id)&&preg_match('/^[1-9][0-9]{0,19}$/D',(string)$id)&&(int)($d['local_hotel_id']??0)===$local)$out[(string)$id]=['schema'=>$schema,'request_sha256'=>$s['request_sha256']??null,'response_sha256'=>$s['response_sha256']??null];}return$out;}
if(in_array('--self-test',$argv??[],true)){if(corelabel('Шри-Ланка','sri-lanka')!=='sri_lanka')throw new RuntimeException('country');$e=['schema'=>'operator-original-price-bridge/1','provider_bridges'=>[['operator_key'=>'115','action'=>'price','is_operator_hotel_key'=>false,'andromeda_hotel_id'=>'99']]];if(!isset(bridgeids($e,'operator_115',1)['99']))throw new RuntimeException('bridge');echo"PASS\n";exit;}
$op=(string)getenv('OPERATION_ID');$sha=(string)getenv('MATCH_SOURCE_SHA');if($op!==OP||!preg_match('/^[0-9a-f]{40}$/D',$sha))throw new RuntimeException('guard');$root=realpath(getcwd());$base=rtrim((string)getenv('HOME'),'/').'/.anytoour-match/operations';if(!$root||basename($root)!=='anytoour.ru'||!is_dir($base))throw new RuntimeException('root');$dir=$base.'/'.$op;if(!mkdir($dir,0700))throw new RuntimeException('exists');putj($dir.'/reservation.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'reserved_before_db_access','read_only'=>true,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);
$db=null;try{require_once dbpath($root);$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');$core=[];$coreLabels=[];foreach(qa($db,'SELECT id,name,slug FROM catalog_countries WHERE is_active=1 ORDER BY id')as$c){$lab=corelabel($c['name']??'',$c['slug']??'');if($lab!==null){$core[(int)$c['id']]=true;$coreLabels[(int)$c['id']]=$lab;}}if(count($core)!==8)throw new RuntimeException('core8_country_resolution');
$stateCounts=[];$accepted=qa($db,"SELECT i.evidence_json,h.country_id FROM andromeda_hotel_identities i JOIN catalog_hotels h ON h.id=i.local_hotel_id WHERE i.supplier_namespace='andromeda_catalog' AND i.decision_status='accepted' AND i.local_hotel_id IS NOT NULL AND h.is_active=1");foreach($accepted as$r){$e=ev($r['evidence_json']);$st=statekey($e);$cid=(int)$r['country_id'];if($st!==''&&isset($core[$cid]))$stateCounts[$st][$cid]=($stateCounts[$st][$cid]??0)+1;}$stateAuthority=[];$stateStats=[];foreach($stateCounts as$st=>$cc){arsort($cc);$ids=array_keys($cc);$best=(int)$ids[0];$n=(int)$cc[$best];$total=array_sum($cc);$second=(int)($cc[$ids[1]??-1]??0);$ratio=$total?$n/$total:0;$stateStats[$st]=['best_country_id'=>$best,'label'=>$coreLabels[$best]??null,'best'=>$n,'second'=>$second,'total'=>$total,'ratio'=>round($ratio,4)];if($n>=5&&$ratio>=0.98&&($n-$second)>=5)$stateAuthority[$st]=$best;}
$pending=[];foreach(qa($db,"SELECT external_hotel_id,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='pending' AND local_hotel_id IS NULL ORDER BY external_hotel_id")as$r){$e=ev($r['evidence_json']);$st=statekey($e);if(isset($stateAuthority[$st]))$pending[(string)$r['external_hotel_id']]=['e'=>$e,'state'=>$st,'country_id'=>$stateAuthority[$st]];}
$support=[];$opRows=0;$recognized=0;foreach(qa($db,"SELECT supplier_namespace,external_hotel_id,local_hotel_id,evidence_json,evidence_sha256 FROM andromeda_hotel_identities WHERE supplier_namespace IN ('operator_5','operator_315','operator_342','operator_115') AND decision_status='accepted' AND local_hotel_id IS NOT NULL ORDER BY supplier_namespace,external_hotel_id")as$r){$opRows++;$ns=(string)$r['supplier_namespace'];$local=(int)$r['local_hotel_id'];$e=ev($r['evidence_json']);$ids=bridgeids($e,$ns,$local);if($ids)$recognized++;foreach($ids as$aid=>$meta)if(isset($pending[$aid]))$support[$aid][$local][]=['supplier_namespace'=>$ns,'native_id'=>(string)$r['external_hotel_id'],'schema'=>$meta['schema'],'evidence_sha256'=>(string)$r['evidence_sha256'],'request_sha256'=>$meta['request_sha256'],'response_sha256'=>$meta['response_sha256']];}
$localIds=[];foreach($support as$ls)foreach(array_keys($ls)as$id)$localIds[(int)$id]=1;$hotels=[];if($localIds)foreach(qa($db,'SELECT id,country_id,name,latitude,longitude,is_active FROM catalog_hotels WHERE id IN ('.implode(',',array_fill(0,count($localIds),'?')).')',array_keys($localIds))as$h)$hotels[(int)$h['id']]=$h;$occupied=[];foreach(qa($db,"SELECT external_hotel_id,local_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IS NOT NULL")as$r)$occupied[(int)$r['local_hotel_id']][]=(string)$r['external_hotel_id'];$db->exec('ROLLBACK');
$rows=[];$cnt=[];$prov=[];foreach($pending as$aid=>$p){$e=$p['e'];$s=src($e);$name=first($s,['name','hotelName','title']);$ls=$support[$aid]??[];$route='no_originalkey_operator_bridge';$target=null;$d=[];if(marker($e))$route='hold_source_protected';elseif(count($ls)>1){$route='hold_ambiguous_operator_targets';$d['candidate_local_ids']=array_map('intval',array_keys($ls));}elseif(count($ls)===1){$target=(int)array_key_first($ls);$h=$hotels[$target]??null;if(!$h||(int)$h['is_active']!==1||(int)$h['country_id']!==$p['country_id'])$route='hold_target_country_or_activity';elseif(!empty($occupied[$target])){$route='hold_existing_andromeda_occupancy';$d['occupying_ids']=$occupied[$target];}else{$ng=nameguard($name,(string)$h['name']);if(!$ng['ok']){$route='hold_'.$ng['reason'];$d['name_guard']=$ng;}else{$ds=[];foreach(coords($e)as$c){$la=num($h['latitude']);$lo=num($h['longitude']);if($la===null||$lo===null||($la==0.0&&$lo==0.0))break;$ds[]=round(km($c[0],$c[1],$la,$lo),3);}if(array_filter($ds,fn($x)=>$x>5)){$route='hold_coordinate_gt5km';$d['distances_km']=$ds;}else{$route='provisional';$d['distances_km']=$ds;$prov[]=['i'=>count($rows),'id'=>$target,'aid'=>$aid];}}}}$cnt[$route]=($cnt[$route]??0)+1;$rows[]=['external_hotel_id'=>$aid,'source_name'=>$name,'state_key'=>$p['state'],'country_id'=>$p['country_id'],'candidate_local_id'=>$target,'candidate_local_name'=>$target&&isset($hotels[$target])?$hotels[$target]['name']:null,'route'=>$route,'operator_support'=>$target!==null?($ls[$target]??[]):[],'details'=>$d];}
$use=[];foreach($prov as$v)$use[$v['id']][$v['aid']]=1;$prepared=[];foreach($prov as$v){$old=$rows[$v['i']]['route'];$cnt[$old]--;if(count($use[$v['id']])>1)$rows[$v['i']]['route']='hold_pending_target_collision';else{$rows[$v['i']]['route']='guard_passed_originalkey_crossprovider';$prepared[]=$rows[$v['i']];}$cnt[$rows[$v['i']]['route']]=($cnt[$rows[$v['i']]['route']]??0)+1;}foreach($cnt as$k=>$v)if($v===0)unset($cnt[$k]);ksort($cnt);$res=['schema'=>'global-originalkey-crossprovider-census/1','operation_id'=>$op,'source_sha'=>$sha,'state'=>'completed_read_only','core8_countries'=>$coreLabels,'state_authority'=>$stateStats,'authoritative_states'=>$stateAuthority,'current_pending_core8'=>count($pending),'operator_accepted_rows_scanned'=>$opRows,'operator_rows_with_recognized_originalkey'=>$recognized,'pending_with_operator_bridge'=>count($support),'route_counts'=>$cnt,'prepared_count'=>count($prepared),'prepared'=>$prepared,'rows'=>$rows,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'booking_calls'=>0,'lead_calls'=>0,'safe_to_write_now'=>false,'no_replay'=>true];$dg=putj($dir.'/result.json',$res);putj($dir.'/receipt.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'completed_read_only','result_sha256'=>$dg,'readback_verified'=>true,'prepared_count'=>count($prepared),'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);echo jj(['state'=>'completed_read_only','pending'=>count($pending),'operator_bridge'=>count($support),'prepared_count'=>count($prepared),'route_counts'=>$cnt])."\n";}catch(Throwable$e){try{if($db instanceof PDO&&$db->inTransaction())$db->rollBack();}catch(Throwable){}$f=['state'=>'failed_read_only','error_class'=>get_class($e),'error_message'=>$e->getMessage(),'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true];$dg=putj($dir.'/failure.json',$f);putj($dir.'/receipt.json',['state'=>'failed_read_only','failure_sha256'=>$dg,'readback_verified'=>true,'no_replay'=>true]);fwrite(STDERR,"GLOBAL_ORIGINALKEY_FAILED\n");exit(2);}