<?php
declare(strict_types=1);
const A28_OP='hotel-match-new28-samo-accept-1971-20260920-v1';
const A28_INPUT='d84a73ac32edcd8a3390b8e643f01ed140d263ca11ceba67e97874b85089c936';
const A28_INDIA='8409bc681cb9976c59956adc91ffd10db87182e0f21d97cc170e65a5cae5f8ec';
function a28_need(bool $b,string $s):void{if(!$b)throw new RuntimeException($s);}
function a28_json(array $a):string{return json_encode($a,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n";}
function a28_hash(array $a):string{return hash('sha256',a28_json($a));}
function a28_save(string $p,array $a):string{$b=a28_json($a);$f=fopen($p,'xb');a28_need(is_resource($f),'exclusive_file');try{a28_need(fwrite($f,$b)===strlen($b)&&fflush($f),'file_write');if(function_exists('fsync'))a28_need(fsync($f),'file_sync');}finally{fclose($f);}a28_need(file_get_contents($p)===$b,'file_readback');return hash('sha256',$b);}
function a28_load(string $p,?string $sha=null):array{if($sha!==null)a28_need(hash_file('sha256',$p)===$sha,'input_hash');$r=json_decode((string)file_get_contents($p),true,128,JSON_THROW_ON_ERROR);a28_need(is_array($r),'input_shape');return$r;}
function a28_norm(string $s):string{$s=function_exists('mb_strtolower')?mb_strtolower($s,'UTF-8'):strtr(strtolower($s),array_combine(preg_split('//u','АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ',-1,PREG_SPLIT_NO_EMPTY),preg_split('//u','абвгдеёжзийклмнопрстуфхцчшщъыьэюя',-1,PREG_SPLIT_NO_EMPTY)));return trim(preg_replace('/[^\p{L}\p{N}]+/u',' ',str_replace('ё','е',$s))??'');}
function a28_star(mixed $v):?int{return is_scalar($v)&&preg_match('/^\s*([1-5])(?:\s|\*|$)/u',(string)$v,$m)===1?(int)$m[1]:null;}
function a28_distance(array $source,array $target):?float {
 foreach(['latitude','longitude'] as$k)if(!isset($source[$k],$target[$k])||!is_numeric($source[$k])||!is_numeric($target[$k]))return null;
 $a=(float)$source['latitude'];$b=(float)$source['longitude'];$c=(float)$target['latitude'];$d=(float)$target['longitude'];
 if(!is_finite($a)||!is_finite($b)||!is_finite($c)||!is_finite($d)||abs($a)>90||abs($c)>90||abs($b)>180||abs($d)>180||($a==0.0&&$b==0.0)||($c==0.0&&$d==0.0))return null;
 $x=sin(deg2rad($c-$a)/2)**2+cos(deg2rad($a))*cos(deg2rad($c))*sin(deg2rad($d-$b)/2)**2;return 6371*2*asin(sqrt(max(0.0,min(1.0,$x))));
}
function a28_same_context(array $r,array $c):bool{return (string)($r['checkIn']??'')===DateTimeImmutable::createFromFormat('!Y-m-d',$c['departure_date'])->format('d.m.Y')&&(int)($r['nights']??-1)===(int)$c['nights']&&(int)($r['adult']??-1)===(int)$c['adults']&&(int)($r['child']??-1)===(int)$c['children_count'];}
/** Reconstruct canonical/native proof from sealed raw HTTP, never trust its prior classification. */
function a28_proofs(string $folder):array{
 $r=a28_load($folder.'/result.json',A28_INPUT);$q=a28_load($folder.'/receipt.json');a28_need($r['state']==='completed_read_only'&&$q['result_sha256']===A28_INPUT&&$r['provider_calls']===38&&$r['input_count']===31,'acquisition_receipt');$out=[];
 foreach($r['dossiers'] as$d){if(!isset($d['bridge']))continue;$sid=(string)$d['bridge']['requested_samo_id'];$id=(int)$d['local_hotel_id'];$c=$d['context'];a28_need($id>0&&$id!==420&&($c['source']??'')==='user_search'&&(string)$c['operator_id']==='13','target_context');
  $file=$d['bridge']['raw_http_file'];a28_need(preg_match('/^raw-http-[0-9]{3}-price\.json$/D',$file)===1,'http_filename');$http=a28_load($folder.'/'.$file);$stem=str_replace(['raw-http-','.json'],['call-',''],$file);$call=a28_load($folder.'/'.$stem.'-reservation.json');$receipt=a28_load($folder.'/'.$stem.'-receipt.json');a28_need($http['status']===200&&$receipt['body_sha256']===hash('sha256',$http['body']),'http_receipt');$body=json_decode($http['body'],true,128,JSON_THROW_ON_ERROR);$params=$call['params'];
  foreach(['HOTELS'=>$sid,'OPERATORS'=>'5','TOWNFROMINC'=>(string)$d['samo_townfrom_id'],'STATEINC'=>(string)$d['state_id'],'CHECKIN_BEG'=>str_replace('-','',$c['departure_date']),'CHECKIN_END'=>str_replace('-','',$c['departure_date']),'NIGHTS_FROM'=>(string)$c['nights'],'NIGHTS_TILL'=>(string)$c['nights'],'ADULT'=>(string)$c['adults'],'CHILD'=>(string)$c['children_count'],'PAGE'=>'1'] as$k=>$v)a28_need((string)($params[$k]??'')===$v,'request_context');
  $cf=$d['catalog_file'];a28_need(preg_match('/^raw-catalog-[a-f0-9]{12}\.json$/D',$cf)===1,'catalog_filename');$cat=a28_load($folder.'/'.$cf,$d['country_raw']['name']==='Индия'?A28_INDIA:null);$operators=array_values(array_filter($cat['OPERATORS'],static fn($o)=>(string)($o['id']??'')==='5'&&a28_norm((string)($o['name']??''))==='anex tour'));a28_need(count($operators)===1,'catalog_operator');$src=array_values(array_filter($cat['HOTELS'],static fn($h)=>(string)($h['id']??'')===$sid));a28_need(count($src)===1&&(string)$src[0]['stateKey']===(string)$params['STATEINC'],'catalog_identity_country');$src=$src[0];
  $rows=[];$natives=[];$reasons=[];foreach($body['PRICES'] as$row){if(!is_array($row)||(string)($row['hotelKey']??'')!==$sid||(string)($row['operatorKey']??'')!=='5'||!a28_same_context($row,$c))continue;$rows[]=$row;$native=(string)($row['original']['hotelKey']??'');if(preg_match('/^[1-9][0-9]{0,9}$/D',$native)!==1)$reasons[]='invalid_native_id';else$natives[$native]=true;if(($row['isOperatorHotelKey']??null)!==0)$reasons[]='canonical_namespace_unproven';if(a28_norm((string)($row['operator']??''))!=='anex tour')$reasons[]='operator_name_conflict';if((string)($row['samoTownKey']??'')!==(string)$src['townKey'])$reasons[]='canonical_town_conflict';}
  $nativeIds=array_map('strval',array_keys($natives));sort($nativeIds,SORT_NATURAL);if($rows===[]||$nativeIds===[])$reasons[]='no_exact_rows';if(array_diff($nativeIds,array_map('strval',$d['anex_native_ids'])))$reasons[]='native_not_in_retained_anchors';
  $out[]=['local_hotel_id'=>$id,'samo_hotel_id'=>$sid,'native_ids'=>$nativeIds,'target_snapshot'=>$d['hotel_raw'],'source_catalog'=>$src,'catalog_sha256'=>hash_file('sha256',$folder.'/'.$cf),'catalog_file'=>$cf,'context'=>$c,'request'=>$call,'operator_catalog'=>$operators[0],'response_file'=>$file,'response_sha256'=>hash_file('sha256',$folder.'/'.$file),'body_sha256'=>$receipt['body_sha256'],'rows'=>$rows,'saved_proof_holds'=>array_values(array_unique($reasons))];
 }
 a28_need(count($out)===28&&count(array_unique(array_column($out,'samo_hotel_id')))===28&&count(array_unique(array_column($out,'local_hotel_id')))===28,'proof_count_uniqueness');return$out;
}
function a28_guard(array $p,?array $h,array $all,array $dec,array $exc,array $resolved):array{
 $why=$p['saved_proof_holds'];$id=$p['local_hotel_id'];$sid=$p['samo_hotel_id'];$src=$p['source_catalog'];
 if($h===null||(int)($h['is_active']??0)!==1||$id===420)$why[]='inactive_or_missing_target';
 if($h!==null){foreach(['name','country_id','country_name','region_id','region_name','subregion_id','subregion_name','category','latitude','longitude'] as$k)if((string)($h[$k]??'')!==(string)($p['target_snapshot'][$k]??''))$why[]='target_fact_drift';if(a28_norm((string)$src['state'])!==a28_norm((string)$h['country_name']))$why[]='country_conflict';if(in_array(a28_norm((string)$h['country_name']),['россия','абхазия'],true))$why[]='excluded_country';
  $km=a28_distance($src,$h);if($km!==null&&$km>5)$why[]='hard_coordinate_conflict';$town=a28_norm((string)$src['town']);$geo=false;foreach(['region_name','subregion_name']as$k){$local=a28_norm((string)($h[$k]??''));if($town!==''&&$local!==''&&str_contains(' '.$local.' ',' '.$town.' '))$geo=true;}if(!$geo)$why[]='concrete_geo_unproven';
  $stars=[];$s=a28_star($src['star']??null);if($s!==null)$stars[$s]=true;foreach($p['rows']as$row){$s=a28_star($row['star']??null);if($s!==null)$stars[$s]=true;}foreach(array_keys($stars)as$s)if($s!==(int)$h['category'])$why[]='actual_star_label_conflict';
 }
 foreach($p['native_ids']as$n)if(($resolved[$n]??null)!==$id)$why[]='current_native_mapping_conflict';
 foreach($all as$row){$ns=(string)$row['supplier_namespace'];$external=(string)$row['external_hotel_id'];if($ns==='andromeda_catalog'&&$external===$sid)$why[]='canonical_source_already_present';if((int)($row['local_hotel_id']??0)===$id)$why[]='target_identity_already_present';if($ns==='operator_5'&&in_array($external,$p['native_ids'],true))$why[]='provider_native_existing_decision';}
 foreach(['manual_decision'=>$dec,'pair_exclusion'=>$exc]as$reason=>$rows)foreach($rows as$row)if((int)($row['catalog_hotel_id']??0)===$id||in_array((string)($row['anex_hotel_id']??''),$p['native_ids'],true))$why[]=$reason;
 return array_values(array_unique($why));
}
function a28_rows(PDO $db,string $sql,array $params=[]):array{$q=$db->prepare($sql);$q->execute(array_values($params));$rows=$q->fetchAll(PDO::FETCH_ASSOC);a28_need(count($rows)<=50000,'db_row_cap');return$rows;}
function a28_projection(PDO $db):array{$rows=a28_rows($db,"SELECT i.supplier_namespace,i.external_hotel_id,i.decision_status,i.local_hotel_id AS catalog_hotel_id,h.id AS existing_catalog_hotel_id FROM andromeda_hotel_identities i LEFT JOIN catalog_hotels h ON h.id=i.local_hotel_id WHERE i.decision_status IN ('accepted','rejected') ORDER BY i.supplier_namespace,i.external_hotel_id LIMIT 50001");return$rows;}
function a28_resolve_samo(array $projection,string $sid):?int{$resolver=AnyTourAndromedaHotelResolver::fromRows($projection,a28_hash($projection));$p=$resolver->apply(['provider'=>'andromeda','selection_enabled'=>false,'offers'=>[['provider'=>'andromeda','selection_enabled'=>false,'local_hotel_id'=>null,'supplier_namespace'=>'andromeda_catalog','external_hotel_id'=>$sid]]]);return$p['offers'][0]['local_hotel_id'];}
if(($argv[1]??'')==='--inspect'){$proofs=a28_proofs($argv[2]);$counts=[];foreach($proofs as$p){$resolved=array_fill_keys($p['native_ids'],$p['local_hotel_id']);$why=a28_guard($p,$p['target_snapshot'],[],[],[],$resolved);$key=$why?implode('|',$why):'offline_candidate_not_write_authority';$counts[$key]=($counts[$key]??0)+1;}echo a28_json(['proofs'=>count($proofs),'counts'=>$counts]);exit(0);}
if(($argv[1]??'')==='--self-test'){
 $h=['id'=>1,'is_active'=>1,'name'=>'EXAMPLE','country_id'=>3,'country_name'=>'Индия','region_id'=>18,'region_name'=>'Север Гоа','subregion_id'=>340,'subregion_name'=>'Морджим бич','category'=>3,'latitude'=>'15','longitude'=>'73'];$p=['local_hotel_id'=>1,'samo_hotel_id'=>'2','native_ids'=>['3','4'],'target_snapshot'=>$h,'source_catalog'=>['state'=>'Индия','town'=>'Морджим','star'=>'3'],'rows'=>[['star'=>'3 ***']],'saved_proof_holds'=>[]];$resolve=['3'=>1,'4'=>1];a28_need(a28_guard($p,$h,[],[],[],$resolve)===[],'alias_consensus');$cases=0;
 foreach(['canonical_source_already_present'=>[['supplier_namespace'=>'andromeda_catalog','external_hotel_id'=>'2','local_hotel_id'=>null,'decision_status'=>'pending']],'target_identity_already_present'=>[['supplier_namespace'=>'andromeda_catalog','external_hotel_id'=>'99','local_hotel_id'=>1,'decision_status'=>'accepted']],'provider_native_existing_decision'=>[['supplier_namespace'=>'operator_5','external_hotel_id'=>'4','local_hotel_id'=>null,'decision_status'=>'rejected']]]as$expected=>$rows){a28_need(in_array($expected,a28_guard($p,$h,$rows,[],[],$resolve),true),'identity_guard');$cases++;}
 a28_need(in_array('manual_decision',a28_guard($p,$h,[],[['anex_hotel_id'=>3,'catalog_hotel_id'=>99]],[],$resolve),true),'manual');a28_need(in_array('pair_exclusion',a28_guard($p,$h,[],[],[['anex_hotel_id'=>99,'catalog_hotel_id'=>1]],$resolve),true),'exclusion');a28_need(in_array('current_native_mapping_conflict',a28_guard($p,$h,[],[],[],['3'=>1,'4'=>9]),true),'no_token_drop');
 $bad=$p;$bad['source_catalog']['town']='Коломбо';a28_need(in_array('concrete_geo_unproven',a28_guard($bad,$h,[],[],[],$resolve),true),'geo');$bad=$p;$bad['rows'][0]['star']='5 *****';a28_need(in_array('actual_star_label_conflict',a28_guard($bad,$h,[],[],[],$resolve),true),'stars');$bad=$p;$bad['source_catalog']['state']='Грузия';a28_need(in_array('country_conflict',a28_guard($bad,$h,[],[],[],$resolve),true),'country');$bad=$p;$bad['saved_proof_holds']=['canonical_namespace_unproven'];a28_need(in_array('canonical_namespace_unproven',a28_guard($bad,$h,[],[],[],$resolve),true),'namespace');$bad=$h;$bad['is_active']=0;a28_need(in_array('inactive_or_missing_target',a28_guard($p,$bad,[],[],[],$resolve),true),'active');a28_need(a28_star('2000000028')===null&&a28_star('-')===null,'not_star_key');$bad=$p;$bad['source_catalog']['latitude']='40';$bad['source_catalog']['longitude']='70';a28_need(in_array('hard_coordinate_conflict',a28_guard($bad,$h,[],[],[],$resolve),true),'hard_geo');a28_need(a28_distance(['latitude'=>'0','longitude'=>'0'],$h)===null,'unknown_not_zero_geo');echo "MATCH_NEW28_ACCEPT_GUARDS_OK 15\n";exit(0);
}
a28_need(PHP_SAPI==='cli'&&getenv('MATCH_OPERATION_ID')===A28_OP,'operation');$dir=rtrim((string)getenv('HOME'),'/').'/.anytoour-match/operations/'.A28_OP;a28_need(realpath((string)getenv('MATCH_OPERATION_DIR'))===$dir,'op_directory');$sha=(string)getenv('MATCH_SOURCE_SHA');a28_need(preg_match('/^[a-f0-9]{40}$/D',$sha)===1,'source_sha');$reservation=a28_load($dir.'/reservation.json');a28_need(($reservation['operation_id']??'')===A28_OP&&($reservation['source_sha']??'')===$sha&&($reservation['state']??'')==='reserved_before_db_access'&&($reservation['mapping_write_cap']??null)===28,'reservation');
$base=['operation_id'=>A28_OP,'source_sha'=>$sha,'input_sha256'=>A28_INPUT,'provider_calls'=>0,'tourvisor_calls'=>0,'samo_calls'=>0,'direct_anex_calls'=>0,'anex_mapping_writes'=>0,'no_replay'=>true];$db=null;$attempted=false;$committed=false;$writes=0;$skipped=[];$plan=[];
try{
 a28_save($dir.'/execution-reservation.json',$base+['state'=>'started_before_db_access']);$proofs=a28_proofs($dir.'/input');a28_save($dir.'/proofs.json',$base+['proofs'=>$proofs]);$root=realpath(getcwd());a28_need(is_string($root)&&basename($root)==='anytoour.ru','root');require_once dirname(__DIR__,2).'/app/integrations/anex-search-mapping-registry.php';require_once dirname(__DIR__,2).'/app/integrations/andromeda-hotel-resolver.php';require_once(is_file($root.'/data/db-v1.php')?$root.'/data/db-v1.php':$root.'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
 foreach(['andromeda_hotel_identities','anex_hotel_search_mappings','anex_hotel_decisions','anex_review_pair_exclusions','catalog_hotels']as$t){$eng=a28_rows($db,'SELECT ENGINE FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?',[$t]);a28_need(count($eng)===1&&strtoupper((string)$eng[0]['ENGINE'])==='INNODB','engine');}
 $db->exec('SET SESSION innodb_lock_wait_timeout=10');$db->exec('SET TRANSACTION ISOLATION LEVEL SERIALIZABLE');$db->beginTransaction();$all=a28_rows($db,'SELECT * FROM andromeda_hotel_identities ORDER BY supplier_namespace,external_hotel_id LIMIT 50001 FOR UPDATE');$before=[];foreach($all as$row)$before[$row['supplier_namespace'].':'.$row['external_hotel_id']]=a28_hash($row);
 $ids=array_column($proofs,'local_hotel_id');$natives=[];foreach($proofs as$p)foreach($p['native_ids']as$n)$natives[$n]=true;$natives=array_keys($natives);$tp=implode(',',array_fill(0,count($ids),'?'));$np=implode(',',array_fill(0,count($natives),'?'));$hot=[];foreach(a28_rows($db,"SELECT * FROM catalog_hotels WHERE id IN ($tp) ORDER BY id FOR UPDATE",$ids)as$h)$hot[(int)$h['id']]=$h;
 $maps=a28_rows($db,"SELECT * FROM anex_hotel_search_mappings WHERE anex_hotel_id IN ($np) OR catalog_hotel_id IN ($tp) FOR UPDATE",array_merge($natives,$ids));$dec=a28_rows($db,"SELECT * FROM anex_hotel_decisions WHERE anex_hotel_id IN ($np) OR catalog_hotel_id IN ($tp) FOR UPDATE",array_merge($natives,$ids));$exc=a28_rows($db,"SELECT * FROM anex_review_pair_exclusions WHERE anex_hotel_id IN ($np) OR catalog_hotel_id IN ($tp) FOR UPDATE",array_merge($natives,$ids));$anex=AnyTourAnexSearchMappingRegistry::fromPdo($db);$resolved=[];foreach($natives as$n)$resolved[(string)$n]=$anex->resolve('anex_online',(string)$n,'preview');
 foreach($proofs as$p){$why=a28_guard($p,$hot[$p['local_hotel_id']]??null,$all,$dec,$exc,$resolved);if($why){$skipped[]=['local_hotel_id'=>$p['local_hotel_id'],'samo_hotel_id'=>$p['samo_hotel_id'],'native_ids'=>$p['native_ids'],'reasons'=>$why];continue;}$representatives=[];foreach($p['rows']as$row){$native=(string)$row['original']['hotelKey'];if(!isset($representatives[$native]))$representatives[$native]=$row;}$e=$p;unset($e['rows']);$e['native_representative_rows']=$representatives;$e['raw_row_count']=count($p['rows']);$e['operation_id']=A28_OP;$e['rule']='canonical_samo_raw_namespace0_current_anex_all_native_consensus';$e['acquisition_artifact']=10607703828;$e['acquisition_sha256']=A28_INPUT;$e['current_target']=$hot[$p['local_hotel_id']];$e['current_anex_resolution']=array_intersect_key($resolved,array_fill_keys($p['native_ids'],true));$ej=a28_json($e);a28_need(strlen($ej)<60000,'evidence_size');$plan[$p['samo_hotel_id']]=['local_hotel_id'=>$p['local_hotel_id'],'native_ids'=>$p['native_ids'],'catalog_sha256'=>$p['catalog_sha256'],'evidence_sha256'=>hash('sha256',$ej),'evidence_json'=>$ej];}
 a28_save($dir.'/capture.json',$base+['identity_hashes_before'=>$before,'current_hotels'=>$hot,'current_anex_rows'=>$maps,'current_manual_rows'=>$dec,'current_exclusion_rows'=>$exc,'current_native_resolution'=>$resolved]);$planHash=a28_save($dir.'/plan.json',$base+['mapping_write_cap'=>28,'safe_writes'=>$plan,'skipped'=>$skipped]);
 if($plan===[]){$db->rollBack();$out=$base+['state'=>'completed_no_safe_delta','mapping_writes'=>0,'database_writes'=>0,'accepted_delta'=>0,'readback_verified'=>true,'skipped'=>$skipped,'plan_sha256'=>$planHash];}
 else{
  foreach($plan as$sid=>$p){$q=$db->prepare("INSERT INTO andromeda_hotel_identities(supplier_namespace,external_hotel_id,local_hotel_id,decision_status,catalog_sha256,evidence_sha256,evidence_json) VALUES('andromeda_catalog',?,?,'accepted',?,?,?)");$q->execute([(string)$sid,$p['local_hotel_id'],$p['catalog_sha256'],$p['evidence_sha256'],$p['evidence_json']]);a28_need($q->rowCount()===1,'insert_row_count');$writes++;}
  $projection=a28_projection($db);foreach($plan as$sid=>$p)a28_need(a28_resolve_samo($projection,(string)$sid)===$p['local_hotel_id'],'precommit_canonical_resolver');$unchanged=[];foreach(a28_rows($db,'SELECT * FROM andromeda_hotel_identities ORDER BY supplier_namespace,external_hotel_id LIMIT 50001')as$row){$key=$row['supplier_namespace'].':'.$row['external_hotel_id'];if(!($row['supplier_namespace']==='andromeda_catalog'&&isset($plan[(string)$row['external_hotel_id']])))$unchanged[$key]=a28_hash($row);}a28_need($unchanged===$before,'prior_identities_changed');$checkpoint=a28_save($dir.'/pre-commit.json',$base+['plan_sha256'=>$planHash,'writes_uncommitted'=>$writes,'prior_identity_count'=>count($before),'state'=>'ready_to_commit']);$attempted=true;$db->commit();$committed=true;
  $db->exec('START TRANSACTION READ ONLY');$projection=a28_projection($db);$anex=AnyTourAnexSearchMappingRegistry::fromPdo($db);$verified=[];$allAfter=a28_rows($db,'SELECT * FROM andromeda_hotel_identities ORDER BY supplier_namespace,external_hotel_id LIMIT 50001');$oldAfter=[];foreach($allAfter as$row){$sid=(string)$row['external_hotel_id'];$key=$row['supplier_namespace'].':'.$sid;if($row['supplier_namespace']==='andromeda_catalog'&&isset($plan[$sid])){$p=$plan[$sid];a28_need($row['decision_status']==='accepted'&&(int)$row['local_hotel_id']===$p['local_hotel_id']&&$row['catalog_sha256']===$p['catalog_sha256']&&$row['evidence_sha256']===$p['evidence_sha256']&&hash('sha256',$row['evidence_json'])===$p['evidence_sha256']&&$row['evidence_json']===$p['evidence_json'],'row_readback');a28_need(a28_resolve_samo($projection,$sid)===$p['local_hotel_id'],'samo_resolver_readback');foreach($p['native_ids']as$n)a28_need($anex->resolve('anex_online',$n,'preview')===$p['local_hotel_id'],'anex_resolver_readback');$verified[]=['samo_hotel_id'=>$sid,'local_hotel_id'=>$p['local_hotel_id'],'native_ids'=>$p['native_ids'],'evidence_sha256'=>$p['evidence_sha256'],'row_sha256'=>a28_hash($row)];}else$oldAfter[$key]=a28_hash($row);}a28_need(count($verified)===$writes&&$oldAfter===$before,'postcommit_preserved_and_count');$db->rollBack();a28_save($dir.'/readback.json',$base+['verified_rows'=>$verified,'prior_identity_count'=>count($before)]);$out=$base+['state'=>'committed_verified','database_writes'=>$writes,'mapping_writes'=>$writes,'accepted_delta'=>$writes,'unique_samo_local_delta'=>$writes,'triple_delta'=>$writes,'written'=>$verified,'skipped'=>$skipped,'prior_identity_count'=>count($before),'plan_sha256'=>$planHash,'precommit_sha256'=>$checkpoint,'readback_verified'=>true];
 }
}catch(Throwable $e){if($db&&$db->inTransaction())$db->rollBack();$reason=preg_match('/^[A-Za-z0-9_]+$/D',$e->getMessage())?$e->getMessage():'database_or_runtime_error';$out=$base+['state'=>$committed?'committed_unverified':($attempted?'commit_outcome_unknown':'rolled_back_or_prewrite_failed'),'reason'=>$reason,'error_class'=>get_class($e),'database_writes'=>$committed?$writes:($attempted?null:0),'mapping_writes'=>$committed?$writes:($attempted?null:0),'writes_attempted'=>$writes,'readback_verified'=>false];}
$rh=a28_save($dir.'/result.json',$out);a28_save($dir.'/receipt.json',$base+['state'=>$out['state'],'result_sha256'=>$rh,'mapping_writes'=>$out['mapping_writes'],'database_writes'=>$out['database_writes'],'readback_verified'=>$out['readback_verified']]);echo a28_json(['state'=>$out['state'],'mapping_writes'=>$out['mapping_writes'],'skipped_count'=>isset($out['skipped'])?count($out['skipped']):null,'reason'=>$out['reason']??null,'result_sha256'=>$rh]);exit(in_array($out['state'],['committed_verified','completed_no_safe_delta'],true)?0:2);
