<?php
declare(strict_types=1);
const R208_OP='hotel-match-userseen208-context-router-1971-20260919-v1',R208_FRONTIER='3c022aeef67301e6e24de1f78380e9252221ba933b964d4963e9a778a9686e64',R208_TOWNFROM='1d6865923bd54cf32e20b386419328636d684d530ed0ebfa313fc69788c2b661';
function r208_need(bool $x,string $w):void{if(!$x)throw new RuntimeException($w);}
function r208_norm(string $s):string{$s=function_exists('mb_strtolower')?mb_strtolower(trim($s),'UTF-8'):strtolower(trim($s));$s=strtr($s,['ё'=>'е','-'=>' ','_'=>' ']);return trim(preg_replace('/[^\p{L}\p{N}]+/u',' ',$s)??$s);}
function r208_write(string $p,array $v):string{$raw=json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n";$f=fopen($p,'xb');fwrite($f,$raw);fflush($f);if(function_exists('fsync'))fsync($f);fclose($f);return hash('sha256',$raw);}
function r208_rows(PDO $db,string $sql,array $p=[]):array{$s=$db->prepare($sql);$s->execute(array_values($p));return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}
if(in_array('--self-test',$argv??[],true)){r208_need(r208_norm('Санкт-Петербург')==='санкт петербург','norm');echo"USERSEEN208_ROUTER_SELFTEST_OK\n";exit(0);}
$dir=(string)getenv('MATCH_OPERATION_DIR');$root=realpath((string)getenv('ANYTOUR_ROOT'));$fp=realpath((string)getenv('MATCH_FRONTIER_PATH'));$tp=realpath((string)getenv('MATCH_TOWNFROM_PATH'));r208_need(PHP_SAPI==='cli'&&is_dir($dir)&&basename($dir)===R208_OP&&is_string($root)&&is_string($fp)&&hash_file('sha256',$fp)===R208_FRONTIER&&is_string($tp)&&hash_file('sha256',$tp)===R208_TOWNFROM,'runtime');
$front=json_decode((string)file_get_contents($fp),true,128,JSON_THROW_ON_ERROR);$tf=json_decode((string)file_get_contents($tp),true,64,JSON_THROW_ON_ERROR);$targets=[];foreach((array)$front['frontier']as$x)if(($x['route']??'')==='user_seen_needs_anex_context')$targets[(int)$x['tv_hotel_id']]=$x;r208_need(count($targets)===208,'targets208');
require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION READ ONLY');$ids=array_keys($targets);$ph=implode(',',array_fill(0,count($ids),'?'));$closed=[];foreach(r208_rows($db,"SELECT local_hotel_id,external_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IN ($ph)",$ids)as$r)$closed[(int)$r['local_hotel_id']][]=(string)$r['external_hotel_id'];$active=array_values(array_diff($ids,array_keys($closed)));$ah=implode(',',array_fill(0,count($active),'?'));
$obs=r208_rows($db,"SELECT id,source,search_id,departure_id,country_id,region_id,subregion_id,hotel_id,tour_id,departure_date,nights,adults,children_count,child_ages_signature,operator_id,observed_at FROM tour_price_observations WHERE source='user_search' AND hotel_id IN ($ah) AND observed_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) AND departure_date>=DATE_ADD(CURDATE(),INTERVAL 1 DAY) AND price>0 ORDER BY hotel_id,observed_at DESC,departure_date ASC,id DESC",$active);$depIds=[];foreach($obs as$o)$depIds[(int)$o['departure_id']]=true;$deps=[];if($depIds){$dh=implode(',',array_fill(0,count($depIds),'?'));foreach(r208_rows($db,"SELECT id,name,is_active FROM catalog_departures WHERE id IN ($dh)",array_keys($depIds))as$d)$deps[(int)$d['id']]=$d;}$db->rollBack();
$town=[];foreach((array)$tf['TOWNFROM']as$t){if(!is_array($t)||!preg_match('/^[1-9][0-9]*$/D',(string)($t['id']??'')))continue;foreach(['name','lName']as$k){$n=r208_norm((string)($t[$k]??''));if($n!=='')$town[$n][(string)$t['id']]=$t;}}$bindings=[];$unbound=[];foreach($deps as$id=>$d){if((int)$d['is_active']!==1){$unbound[$id]='inactive';continue;}$hits=$town[r208_norm((string)$d['name'])]??[];if(count($hits)!==1){$unbound[$id]='binding_'.count($hits);continue;}$sid=(int)array_key_first($hits);$bindings[$id]=['tv_departure_name'=>$d['name'],'samo_townfrom_id'=>$sid,'samo_name'=>current($hits)['name']??null];}
$chosen=[];$candidateCounts=[];foreach($obs as$o){$hid=(int)$o['hotel_id'];$t=$targets[$hid]??null;if(!$t||(int)$o['country_id']!==(int)$t['country_id'])continue;$candidateCounts[$hid]=($candidateCounts[$hid]??0)+1;$dep=(int)$o['departure_id'];if(isset($chosen[$hid])||!isset($bindings[$dep]))continue;$chosen[$hid]=['tv_hotel_id'=>$hid,'hotel_name'=>$t['hotel_name'],'country_id'=>(int)$t['country_id'],'country_name'=>$t['country_name'],'region_id'=>(int)$t['region_id'],'subregion_id'=>$t['subregion_id'],'category'=>(int)$t['category'],'anex_hotel_ids'=>array_map('strval',(array)$t['anex_hotel_ids']),'observation_count'=>(int)$t['user_search']['observation_rows'],'context'=>['observation_id'=>(int)$o['id'],'observed_at'=>$o['observed_at'],'search_id'=>(int)$o['search_id'],'tour_id'=>(string)$o['tour_id'],'generic_operator_id'=>(int)$o['operator_id'],'departure_id'=>$dep,'departure_name'=>$bindings[$dep]['tv_departure_name'],'samo_townfrom_id'=>$bindings[$dep]['samo_townfrom_id'],'departure_date'=>$o['departure_date'],'nights'=>(int)$o['nights'],'adults'=>(int)$o['adults'],'children_count'=>(int)$o['children_count'],'child_ages_signature'=>(string)$o['child_ages_signature']],'safe_to_query_anex_context'=>true,'safe_to_write_now'=>false];}
$refresh=[];foreach($active as$id)if(!isset($chosen[$id])){$t=$targets[$id];$refresh[]=['tv_hotel_id'=>$id,'hotel_name'=>$t['hotel_name'],'country_name'=>$t['country_name'],'observation_count'=>(int)$t['user_search']['observation_rows'],'future_generic_rows'=>$candidateCounts[$id]??0,'reason'=>($candidateCounts[$id]??0)>0?'only_unbound_departures':'no_recent_future_user_search_context'];}usort($refresh,fn($a,$b)=>[$b['observation_count'],$a['tv_hotel_id']]<=>[$a['observation_count'],$b['tv_hotel_id']]);$routed=array_values($chosen);usort($routed,fn($a,$b)=>[$b['observation_count'],$b['context']['observed_at'],$a['tv_hotel_id']]<=>[$a['observation_count'],$a['context']['observed_at'],$b['tv_hotel_id']]);$groups=[];foreach($routed as$r){$c=$r['context'];$k=implode('|',[$c['departure_id'],$r['country_id'],$c['departure_date'],$c['nights'],$c['adults'],$c['children_count'],$c['child_ages_signature']]);$groups[$k]=($groups[$k]??0)+1;}$out=['operation'=>R208_OP,'state'=>'completed_read_only','provider_calls'=>0,'tourvisor_calls'=>0,'database_writes'=>0,'input_targets'=>208,'current_already_accepted'=>count($closed),'current_active_targets'=>count($active),'routed_count'=>count($routed),'refresh_queue_count'=>count($refresh),'bound_departure_count'=>count($bindings),'context_group_count'=>count($groups),'departure_bindings'=>$bindings,'routed'=>$routed,'refresh_queue'=>$refresh];$rh=r208_write($dir.'/result.json',$out);r208_write($dir.'/receipt.json',['operation'=>R208_OP,'state'=>'completed_read_only','result_sha256'=>$rh,'provider_calls'=>0,'tourvisor_calls'=>0,'database_writes'=>0]);echo json_encode(['current_already_accepted'=>count($closed),'routed_count'=>count($routed),'refresh_queue_count'=>count($refresh),'bound_departure_count'=>count($bindings),'context_group_count'=>count($groups)],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";
