<?php
declare(strict_types=1);
const L95_OP='hotel-match-live95-direct-current-1971-20260919-v1',L95_RESULT='05ff5be9057a1485f07ee0f3a0ac12e2e8f74b21a81ed2f3d5556ba61e84bd47';
function l95_need(bool $x,string $w):void{if(!$x)throw new RuntimeException($w);}
function l95_write(string $p,array $v):string{$raw=json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n";$f=fopen($p,'xb');l95_need(is_resource($f),'open');fwrite($f,$raw);fflush($f);if(function_exists('fsync'))fsync($f);fclose($f);return hash('sha256',$raw);}
function l95_rows(PDO $db,string $sql,array $p=[]):array{$s=$db->prepare($sql);$s->execute(array_values($p));return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}
function l95_star(array $h):?int{foreach(['star','starLName','category']as$k){if(!isset($h[$k]))continue;if(preg_match('/([1-5])/u',(string)$h[$k],$m))return(int)$m[1];}return null;}
if(in_array('--self-test',$argv??[],true)){l95_need(l95_star(['starLName'=>'5*'])===5,'star');echo"LIVE95_CURRENT_SELFTEST_OK\n";exit(0);}
$dir=(string)getenv('MATCH_OPERATION_DIR');$root=realpath((string)getenv('ANYTOUR_ROOT'));$input=realpath((string)getenv('MATCH_RESULT_PATH'));$cats=realpath((string)getenv('MATCH_CATALOG_DIR'));l95_need(PHP_SAPI==='cli'&&is_dir($dir)&&basename($dir)===L95_OP&&is_string($root)&&is_string($input)&&hash_file('sha256',$input)===L95_RESULT&&is_string($cats),'runtime');
$r=json_decode((string)file_get_contents($input),true,128,JSON_THROW_ON_ERROR);l95_need(($r['state']??'')==='completed_read_only','input_state');$direct=[];foreach((array)$r['dossiers']as$d){if(($d['state']??'')!=='direct_native_bridge')continue;l95_need(count($d['direct_bridges']??[])===1,'direct_one');$b=$d['direct_bridges'][0];$sid=(string)$b['samo_hotel_id'];$native=(string)$b['native_operator_hotel_id'];$tv=(int)$d['tv_hotel_id'];l95_need($sid!==''&&$native!==''&&$tv>0,'direct_shape');$direct[$sid]=['samo_hotel_id'=>$sid,'native_anex_id'=>$native,'tv_hotel_id'=>$tv,'tv_name'=>$d['hotel_name'],'country'=>$d['country'],'region_name'=>$d['region_name'],'subregion_name'=>$d['subregion_name'],'context'=>$d['context'],'provider_fact'=>$b];}l95_need(count($direct)===95,'direct95');
$countryByFile=['raw-catalog-a2dc2cf490.json'=>'Катар','raw-catalog-490f3ae3b6.json'=>'Маврикий','raw-catalog-dfd0573e11.json'=>'Египет','raw-catalog-ed0216a76e.json'=>'Вьетнам','raw-catalog-095b0b9746.json'=>'Индия','raw-catalog-44073d4b69.json'=>'Тунис','raw-catalog-4099cf97a5.json'=>'Узбекистан','raw-catalog-9c8cdbecb6.json'=>'ОАЭ','raw-catalog-b41ea69d28.json'=>'Казахстан','raw-catalog-turkey-retained.json'=>'Турция'];
$sourceFacts=[];$dups=[];foreach($countryByFile as$file=>$country){$p=$cats.'/'.$file;l95_need(is_file($p),'catalog_'.$file);$j=json_decode((string)file_get_contents($p),true,64,JSON_THROW_ON_ERROR);foreach((array)$j['HOTELS']as$h){$id=(string)($h['id']??'');if(!isset($direct[$id]))continue;if(isset($sourceFacts[$id])){$dups[$id]=true;continue;}$sourceFacts[$id]=['country'=>$country,'hotel'=>$h];}}l95_need(count($sourceFacts)===95,'source_facts95');
$sources=array_keys($direct);$targets=array_values(array_map(fn($x)=>$x['tv_hotel_id'],$direct));$natives=array_values(array_map(fn($x)=>$x['native_anex_id'],$direct));$sp=implode(',',array_fill(0,count($sources),'?'));$tp=implode(',',array_fill(0,count($targets),'?'));$np=implode(',',array_fill(0,count($natives),'?'));
require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION READ ONLY');
$src=l95_rows($db,"SELECT supplier_namespace,external_hotel_id,local_hotel_id,decision_status,catalog_sha256,evidence_sha256,created_at FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id IN ($sp)",$sources);
$occ=l95_rows($db,"SELECT supplier_namespace,external_hotel_id,local_hotel_id,decision_status FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IN ($tp)",$targets);
$hot=l95_rows($db,"SELECT id,name,country_id,country_name,region_name,subregion_name,category,is_active FROM catalog_hotels WHERE id IN ($tp)",$targets);
$maps=l95_rows($db,"SELECT * FROM anex_hotel_search_mappings WHERE anex_hotel_id IN ($np) OR catalog_hotel_id IN ($tp)",array_merge($natives,$targets));
$dec=l95_rows($db,"SELECT * FROM anex_hotel_decisions WHERE anex_hotel_id IN ($np) OR catalog_hotel_id IN ($tp)",array_merge($natives,$targets));
$exc=l95_rows($db,"SELECT * FROM anex_review_pair_exclusions WHERE anex_hotel_id IN ($np) OR catalog_hotel_id IN ($tp)",array_merge($natives,$targets));$db->rollBack();
$srcBy=[];foreach($src as$x)$srcBy[(string)$x['external_hotel_id']]=$x;$occBy=[];foreach($occ as$x)$occBy[(int)$x['local_hotel_id']][]=$x;$hotBy=[];foreach($hot as$x)$hotBy[(int)$x['id']]=$x;$mapBy=[];foreach($maps as$x)if((int)($x['enabled']??1)===1)$mapBy[(string)$x['anex_hotel_id']][]=$x;$decPairs=[];foreach($dec as$x)$decPairs[(string)$x['anex_hotel_id'].'|'.(int)$x['catalog_hotel_id']]=true;$excPairs=[];foreach($exc as$x)$excPairs[(string)$x['anex_hotel_id'].'|'.(int)$x['catalog_hotel_id']]=true;
$rows=[];$counts=[];$safe=[];foreach($direct as$sid=>$p){$tv=$p['tv_hotel_id'];$native=$p['native_anex_id'];$cur=$srcBy[$sid]??null;$target=$hotBy[$tv]??null;$source=$sourceFacts[$sid];$reasons=[];$state='candidate';
 if(isset($dups[$sid]))$reasons[]='source_catalog_duplicate';
 if($source['country']!==$p['country'])$reasons[]='source_country_mismatch';
 if(!$target||(int)$target['is_active']!==1)$reasons[]='target_inactive_or_missing';
 elseif((string)$target['country_name']!==$p['country'])$reasons[]='target_country_mismatch';
 $ss=l95_star($source['hotel']);$ts=$target?((int)$target['category']?:null):null;if($ss!==null&&$ts!==null&&$ss!==$ts)$reasons[]='category_mismatch';
 $mm=$mapBy[$native]??[];$exact=array_values(array_filter($mm,fn($x)=>(int)$x['catalog_hotel_id']===$tv));if(count($exact)!==1||count($mm)!==1)$reasons[]='anex_mapping_not_unique_exact';
 $pair=$native.'|'.$tv;if(isset($decPairs[$pair]))$reasons[]='anex_decision_present';if(isset($excPairs[$pair]))$reasons[]='anex_exclusion_present';
 $otherOcc=array_values(array_filter($occBy[$tv]??[],fn($x)=>(string)$x['external_hotel_id']!==$sid));if($otherOcc)$reasons[]='target_occupied_other_samo';
 if($cur!==null){if($cur['decision_status']==='accepted'&&(int)$cur['local_hotel_id']===$tv)$state='already_accepted';elseif($cur['decision_status']==='accepted')$reasons[]='source_accepted_other_target';elseif($cur['decision_status']==='pending'&&$cur['local_hotel_id']===null){}else$reasons[]='source_existing_protected_state';}
 if($state!=='already_accepted')$state=$reasons?'hold':'safe_candidate';$counts[$state]=($counts[$state]??0)+1;$row=['samo_hotel_id'=>$sid,'native_anex_id'=>$native,'tv_hotel_id'=>$tv,'tv_name'=>$p['tv_name'],'country'=>$p['country'],'source_catalog_name'=>$source['hotel']['name']??($source['hotel']['lName']??null),'source_town'=>$source['hotel']['town']??null,'source_star'=>$ss,'target'=>$target,'current_source'=>$cur,'target_occupants'=>$occBy[$tv]??[],'current_anex_mapping'=>$exact,'hold_reasons'=>$reasons,'state'=>$state,'safe_to_write_now'=>false];$rows[]=$row;if($state==='safe_candidate')$safe[]=['samo_hotel_id'=>$sid,'native_anex_id'=>$native,'tv_hotel_id'=>$tv];}
$out=['operation'=>L95_OP,'state'=>'completed_read_only','provider_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'input_direct95'=>95,'state_counts'=>$counts,'safe_candidate_count'=>count($safe),'safe_candidates'=>$safe,'rows'=>$rows,'input_result_sha256'=>L95_RESULT];$rh=l95_write($dir.'/result.json',$out);l95_write($dir.'/receipt.json',['operation'=>L95_OP,'state'=>'completed_read_only','result_sha256'=>$rh,'provider_calls'=>0,'database_writes'=>0,'mapping_writes'=>0]);echo json_encode(['state'=>'completed_read_only','state_counts'=>$counts,'safe_candidate_count'=>count($safe)],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";
