<?php
declare(strict_types=1);
require_once __DIR__.'/hotel_match_retained_mass47_v94.php';
require_once __DIR__.'/hotel_match_live30_common4_gap_matrix_v1.php';
const M114F_OP='hotel-match-mass-current-reconcile-audit-1971-20260928-v114f';
const M114_NATIVE_OP='hotel-match-live30-retained-native-union-1971-20260927-v77';
const M114_NATIVE_SHA='d40fbe2e0240a5df194ac838376a3425a8f4e80f2426a757560fe369011107f7';
const M114_ACQ=['hotel-match-anexonly200-acquire-1971-20260928-v109'=>'aa0365674e2f57775cbc7c5f0ab7a2d0781fc2826febc0c55214a726ea0b75a4','hotel-match-anexonly-tail-acquire-1971-20260928-v112'=>'ecbba8c5c9dc03f9d4729aabefd0afa1dbfdc67828a66ff429ccb452aab678fd'];
function m114f_need(bool$b,string$m):void{if(!$b)throw new RuntimeException($m);}
function m114_ns(int$o):?string{return match($o){18=>'operator_115',25=>'operator_315',43=>'operator_342',default=>null};}
function m114_main(array$a):int{
 m114f_need(($a[1]??'')==='--execute','disabled');$root=(string)getenv('ANYTOUR_ROOT');$dir=(string)getenv('MATCH_OPERATION_DIR');$head=(string)getenv('MATCH_SOURCE_SHA');m114f_need(is_dir($root)&&basename($root)==='anytoour.ru'&&is_dir($dir)&&basename($dir)===M114F_OP&&preg_match('/^[a-f0-9]{40}$/D',$head),'scope');foreach(['result.json','receipt.json']as$f)m114f_need(!file_exists($dir.'/'.$f),'no_replay');
 require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$matrix=hmc4_execute($db);m114f_need(($matrix['state']??'')==='completed_read_only_common4_gap_matrix'&&($matrix['live30_non_triple_total']??0)>0,'matrix');$ops=dirname($dir);
 $gap=[];$tv=[];$names=[];foreach($matrix['rows']as$r){$id=(int)$r['tv_hotel_id'];$gap[$id]=$r['gap_bucket'];$names[$id]=$r['name'];foreach([[13,'anex'],[18,'biblio'],[25,'funsun'],[43,'intourist']]as[$op,$key]){$l=$r['lanes'][$key]??[];$ids=array_values(array_unique(array_merge($l['accepted_external_ids']??[],$l['saved_exact_external_ids']??[])));if(count($ids)===1)$tv[$id][$op][(string)$ids[0]][]=['kind'=>'current_matrix','state'=>$l['state']];}}
 foreach(M114_ACQ as$opn=>$sha){$x=w84_read($ops.'/'.$opn.'/result.json',$sha,33554432);m114f_need(($x['state']??'')==='completed_read_only','acq');foreach($x['edges']as$i=>$e){if(($e['link_state']??'')!=='captured_single_native'||count($e['positive_native_candidates']??[])!==1||w84_edge_reasons($e))continue;$id=(int)$e['tv_hotel_id'];if(isset($gap[$id]))$tv[$id][(int)$e['operator_id']][(string)$e['positive_native_candidates'][0]][]=['kind'=>'acquisition','operation'=>$opn,'result_sha256'=>$sha,'json_pointer'=>'/edges/'.$i];}}
 $v=w84_read($ops.'/'.M114_NATIVE_OP.'/result.json',M114_NATIVE_SHA,67108864);m114f_need(($v['state']??'')==='completed_retained_native_scan','native');$native=[];foreach($v['native_facts']as$f)$native[(string)$f['supplier_namespace']][(string)$f['native_id']][(string)$f['catalog_id']]=$f;
 $db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION READ ONLY');
 try{$ident=$db->query("SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace IN ('andromeda_catalog','operator_115','operator_315','operator_342') ORDER BY supplier_namespace,external_hotel_id")->fetchAll(PDO::FETCH_ASSOC);m114f_need(is_array($ident)&&count($ident)<=120000,'identity_scope_limit');$idx=w76_index($ident);$targets=[];foreach($ident as$r)if($r['supplier_namespace']==='andromeda_catalog'&&$r['local_hotel_id']!==null&&$r['decision_status']==='accepted')$targets[(int)$r['local_hotel_id']][(string)$r['external_hotel_id']]=true;$manual=[];foreach(w76_q($db,'SELECT catalog_hotel_id FROM anex_hotel_decisions WHERE catalog_hotel_id IS NOT NULL')as$r)$manual[(int)$r['catalog_hotel_id']]=true;$excluded=[];foreach(w76_q($db,'SELECT catalog_hotel_id FROM anex_review_pair_exclusions')as$r)$excluded[(int)$r['catalog_hotel_id']]=true;$gids=array_keys($gap);$gph=implode(',',array_fill(0,count($gids),'?'));$hot=[];foreach(w76_q($db,\"SELECT id,name,country_name,category,is_active FROM catalog_hotels WHERE is_active=1 AND id IN ($gph)\",$gids)as$r)$hot[(int)$r['id']]=$r;$co=w84_live_sources($root);$effective=AnyTourMatchAnexEffectiveCoverage::fromPdo($db);$db->rollBack();}catch(Throwable$e){if($db->inTransaction())$db->rollBack();throw$e;}
 $owners=[];foreach($tv as$id=>$os)foreach($os as$op=>$ns)foreach($ns as$n=>$p)$owners[$op][$n][$id]=true;$samo=[];$direct=[];$holds=[];
 foreach($tv as$id=>$os)foreach($os as$op=>$ns)foreach($ns as$n=>$proofs){if(count($owners[$op][$n])!==1){$holds[]=['kind'=>'tv_native_collision','local_hotel_id'=>$id,'operator_id'=>$op,'native_id'=>$n];continue;}if($op===13){if(in_array($gap[$id],['samo_only','neither'],true))$direct[$id.'|'.$n]=['kind'=>'direct_ANEX','local_hotel_id'=>$id,'anex_hotel_id'=>$n,'proofs'=>$proofs];continue;}$sns=m114_ns($op);$cats=$native[$sns][$n]??[];if(count($cats)!==1)continue;$cat=(string)array_key_first($cats);try{$raw=w84_raw($ops,$cats[$cat],$cat,$sns,$n);}catch(Throwable){continue;}$k=$id.'|'.$cat;if(!isset($samo[$k]))$samo[$k]=['kind'=>'SAMO','local_hotel_id'=>$id,'catalog_id'=>$cat,'proofs'=>[],'operator_facts'=>[]];$samo[$k]['proofs'][]=['operator_id'=>$op,'namespace'=>$sns,'native_id'=>$n,'tv'=>$proofs,'samo'=>$raw];$samo[$k]['operator_facts'][$sns.'|'.$n]=['ns'=>$sns,'native'=>$n];}
 $byId=[];$byCat=[];foreach($samo as$k=>$e){$byId[$e['local_hotel_id']][$e['catalog_id']]=true;$byCat[$e['catalog_id']][$e['local_hotel_id']]=true;}foreach(array_keys($samo)as$k){$e=$samo[$k];if(count($byId[$e['local_hotel_id']])!==1||count($byCat[$e['catalog_id']])!==1){$holds[]=$e+['reasons'=>['cross_operator_catalog_conflict']];unset($samo[$k]);}}
 $readyS=[];foreach($samo as$e){$id=$e['local_hotel_id'];$cat=$e['catalog_id'];$why=[];$row=$idx['andromeda_catalog|'.$cat]??null;if($row&&$row['decision_status']==='accepted'&&$row['local_hotel_id']!==null&&(int)$row['local_hotel_id']===$id)continue;if(!$row||!w76_evidence_valid($row))$why[]='canonical_source_missing_or_invalid';elseif($row['decision_status']!=='pending'||$row['local_hotel_id']!==null)$why[]='canonical_source_occupied';foreach($targets[$id]??[]as$x=>$v)if($x!==$cat)$why[]='target_other_canonical';if(isset($manual[$id]))$why[]='manual_target';if(isset($excluded[$id]))$why[]='excluded_target';if(!isset($co['source_ids'][$cat]))$why[]='outside_samo_live30';$h=$hot[$id]??null;if(!$h)$why[]='target_inactive';if($row&&$h){$j=json_decode((string)$row['evidence_json'],true);$s=$j['source']??[];if(w76_text($s['state']??'')!==w76_text($h['country_name']))$why[]='country_conflict';if((int)($s['starKey']??0)!==(int)$h['category'])$why[]='category_conflict';if(!w78_name((string)($s['name']??''),(string)$h['name'])&&!w78_name((string)($s['lName']??''),(string)$h['name']))$why[]='name_conflict';}foreach($e['operator_facts']as$f){$or=$idx[$f['ns'].'|'.$f['native']]??null;if($or&&$or['decision_status']==='accepted'&&($or['local_hotel_id']===null||(int)$or['local_hotel_id']!==$id))$why[]='operator_other_target';}$why=array_values(array_unique($why));if($why)$holds[]=$e+['reasons'=>$why];else{$e['source_evidence_sha256']=$row['evidence_sha256'];$e['source_catalog_sha256']=$row['catalog_sha256'];$readyS[]=$e;}}
 $readyA=[];foreach($direct as$e){$id=$e['local_hotel_id'];$n=$e['anex_hotel_id'];$why=[];$src=$effective['by_anex'][$n]??[];$tar=$effective['by_local'][$id]??[];if($src&&!isset($src[$id]))$why[]='anex_source_other_target';foreach($tar as$x=>$v)if((string)$x!==$n)$why[]='target_other_anex';if(isset($manual[$id]))$why[]='manual_target';if(isset($excluded[$id]))$why[]='excluded_target';if(!$hot[$id])$why[]='target_inactive';if($why)$holds[]=$e+['reasons'=>array_values(array_unique($why))];elseif(!$src)$readyA[]=$e;}
 $out=['operation'=>M114F_OP,'state'=>'completed_read_only_mass_reconcile_audit','source_sha'=>$head,'generated_at_utc'=>gmdate('c'),'provider_http_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'coverage_current'=>['tv_live30_total'=>$matrix['tv_live30_total'],'full_triple'=>$matrix['tv_live30_total']-$matrix['live30_non_triple_total'],'remaining'=>$matrix['live30_non_triple_total'],'gap_bucket_counts'=>$matrix['gap_bucket_counts']],'samo_live30_current'=>w84_samo_census($ident,$co),'tv_hotels_with_exact_evidence'=>count($tv),'ready_samo_count'=>count($readyS),'ready_direct_anex_count'=>count($readyA),'ready_total'=>count($readyS)+count($readyA),'hold_count'=>count($holds),'ready_samo'=>$readyS,'ready_direct_anex'=>$readyA,'holds'=>$holds,'no_replay'=>true];$sha=w76_save($dir.'/result.json',$out);w76_save($dir.'/receipt.json',['operation'=>M114F_OP,'state'=>$out['state'],'source_sha'=>$head,'result_sha256'=>$sha,'provider_http_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true]);echo w76_json(array_diff_key($out,['ready_samo'=>true,'ready_direct_anex'=>true,'holds'=>true,'samo_live30_current'=>true]))."\n";return 0;
}
if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__)exit(m114_main($argv));
