<?php
declare(strict_types=1);
const OP='hotel-match-v9-provider178-write-1971-20260921-v1';
const INPUT_SHA='8cb977214acf20bd93226103d752119d0615bb49692aa95191ede30bec4a0d1d';
const INPUT_OP='hotel-match-v9-provider178-precommit-audit-1971-20260921-v1';
const MIN_WRITE=100;
function need(bool $v,string $m):void{if(!$v)throw new RuntimeException($m);}
function ordered(mixed $v):mixed{if(is_array($v)){if(!array_is_list($v))ksort($v,SORT_STRING);foreach($v as&$x)$x=ordered($x);unset($x);}return$v;}
function canon(mixed $v):string{return json_encode(ordered($v),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
function rh(array $r):string{return hash('sha256',canon($r)."\n");}
function savej(string $p,array $v):string{$b=json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";$f=fopen($p,'xb');need(is_resource($f),'record_open');need(fwrite($f,$b)===strlen($b),'record_write');fflush($f);if(function_exists('fsync'))fsync($f);fclose($f);need(hash_file('sha256',$p)===hash('sha256',$b),'record_readback');return hash('sha256',$b);}
function rows(PDO $db,string $sql,array $p=[]):array{$s=$db->prepare($sql);$s->execute(array_values($p));return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}
function excluded_country(string $s):bool{return in_array(trim($s),['Россия','Абхазия','россия','абхазия','Russia','RUSSIA','Russian Federation','Abkhazia','russia','russian federation','abkhazia'],true);}
function facts_equal(array $a,array $b):bool{foreach(['id','name','country_id','country_name','region_name','subregion_name','category','is_active']as$k)if((string)($a[$k]??'')!==(string)($b[$k]??''))return false;return true;}
function guard_tables(PDO $db):array{$ts=array_map('current',rows($db,'SHOW TABLES'));$g=array_values(array_filter($ts,fn($t)=>preg_match('/(?:andromeda|hotel).*(?:decision|review|exclusion)|(?:decision|review|exclusion).*(?:andromeda|hotel)/i',(string)$t)));sort($g,SORT_STRING);return$g;}
function validate_input(array $in):array{
 need(($in['operation']??'')===INPUT_OP&&($in['state']??'')==='completed_read_only','input_operation');
 need((int)($in['seed_candidates']??0)===178&&(int)($in['current_core_safe']??0)===178&&($in['writer_threshold_met']??false)===true,'input_counts');
 need(($in['discovered_guard_tables']??[])===['anex_hotel_decisions'],'input_guard_tables');
 $rs=$in['rows']??[];need(is_array($rs)&&count($rs)===178,'input_rows');$keys=[];$tvop=[];
 foreach($rs as$r){need(is_array($r)&&($r['current_state']??'')==='core_safe','input_not_core_safe');$ns=(string)($r['supplier_namespace']??'');need(in_array($ns,['operator_315','operator_342'],true),'namespace');$ext=(string)($r['native_hotel_id']??'');need(preg_match('/^[1-9][0-9]{0,31}$/D',$ext)===1,'native_id');$tv=(int)($r['tv_hotel_id']??0);need($tv>0&&(int)($r['current_target']['id']??0)===$tv,'target_id');$k=$ns.'|'.$ext;need(!isset($keys[$k]),'duplicate_source');$keys[$k]=true;$tk=$tv.'|'.$ns;need(!isset($tvop[$tk]),'duplicate_target_namespace');$tvop[$tk]=true;$a=$r['canonical_anchor']??null;need(is_array($a)&&preg_match('/^[A-Za-z0-9_-]{1,32}$/D',(string)($a['external_hotel_id']??''))===1,'canonical_anchor');need((string)($r['input_canonical_anchor']['external_hotel_id']??'')===(string)$a['external_hotel_id'],'canonical_input_drift');need(preg_match('/^[a-f0-9]{64}$/D',(string)($r['operator_link_sha256']??''))===1,'link_sha');}
 return$rs;
}
if(($argv[1]??'')==='--self-test'){
 need(canon(['b'=>1,'a'=>2])==='{"a":2,"b":1}','canon');need(excluded_country('Россия')&&!excluded_country('Турция'),'country');
 $fixture=['operation'=>INPUT_OP,'state'=>'completed_read_only','seed_candidates'=>178,'current_core_safe'=>178,'writer_threshold_met'=>true,'discovered_guard_tables'=>['anex_hotel_decisions'],'rows'=>[]];
 for($i=1;$i<=178;$i++)$fixture['rows'][]=['current_state'=>'core_safe','supplier_namespace'=>$i%2?'operator_315':'operator_342','native_hotel_id'=>(string)(100000+$i),'tv_hotel_id'=>$i,'current_target'=>['id'=>$i],'input_canonical_anchor'=>['external_hotel_id'=>(string)(200000+$i)],'canonical_anchor'=>['external_hotel_id'=>(string)(200000+$i)],'operator_link_sha256'=>str_repeat('a',64)];
 need(count(validate_input($fixture))===178,'fixture');echo"V9_PROVIDER178_WRITE_SELFTEST_OK\n";exit;
}
need(PHP_SAPI==='cli'&&($argv[1]??'')==='--execute','disabled');
$root=realpath((string)getenv('ANYTOUR_ROOT'));$inp=realpath((string)getenv('MATCH_INPUT_PATH'));$dir=(string)getenv('MATCH_OPERATION_DIR');$sourceSha=(string)getenv('MATCH_SOURCE_SHA');
need(is_string($root)&&basename($root)==='anytoour.ru','root');need(is_string($inp)&&hash_file('sha256',$inp)===INPUT_SHA,'input_sha');need(is_dir($dir)&&basename($dir)===OP,'opdir');need(preg_match('/^[a-f0-9]{40}$/D',$sourceSha)===1,'source_sha');
$in=json_decode((string)file_get_contents($inp),true,512,JSON_THROW_ON_ERROR);$seeds=validate_input($in);
require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');require_once __DIR__.'/andromeda-hotel-resolver.php';
$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET SESSION innodb_lock_wait_timeout=15');$db->exec('SET TRANSACTION ISOLATION LEVEL SERIALIZABLE');
$base=['operation'=>OP,'source_sha'=>$sourceSha,'input_operation'=>INPUT_OP,'input_sha256'=>INPUT_SHA,'provider_calls'=>0,'tourvisor_calls'=>0,'samo_calls'=>0,'andromeda_calls'=>0];
$committed=false;$safe=[];$holds=[];$inserted=[];$beforeHashes=[];$evidenceByKey=[];
try{
 $db->beginTransaction();
 $guards=guard_tables($db);need($guards===['anex_hotel_decisions'],'guard_table_drift');
 $all=rows($db,'SELECT supplier_namespace,external_hotel_id,local_hotel_id,decision_status,catalog_sha256,evidence_sha256,evidence_json,created_at FROM andromeda_hotel_identities ORDER BY supplier_namespace,external_hotel_id FOR UPDATE');$byKey=[];$acceptedTarget=[];$canonicalByTarget=[];
 foreach($all as$r){$k=$r['supplier_namespace'].'|'.$r['external_hotel_id'];need(!isset($byKey[$k]),'duplicate_identity');$byKey[$k]=$r;$beforeHashes[$k]=rh($r);if($r['decision_status']==='accepted'&&$r['local_hotel_id']!==null){$tk=$r['supplier_namespace'].'|'.(int)$r['local_hotel_id'];$acceptedTarget[$tk][]=$r;if($r['supplier_namespace']==='andromeda_catalog')$canonicalByTarget[(int)$r['local_hotel_id']][]=$r;}}
 $ids=array_values(array_unique(array_map(fn($r)=>(int)$r['tv_hotel_id'],$seeds)));sort($ids,SORT_NUMERIC);$hot=[];foreach(array_chunk($ids,400)as$c){$ph=implode(',',array_fill(0,count($c),'?'));foreach(rows($db,"SELECT id,name,country_id,country_name,region_name,subregion_name,category,is_active FROM catalog_hotels WHERE id IN ($ph) ORDER BY id FOR UPDATE",$c)as$h)$hot[(int)$h['id']]=$h;}
 foreach($seeds as$s){$tv=(int)$s['tv_hotel_id'];$ns=(string)$s['supplier_namespace'];$ext=(string)$s['native_hotel_id'];$k=$ns.'|'.$ext;$reason=null;$target=$hot[$tv]??null;$canonRows=$canonicalByTarget[$tv]??[];$expected=$s['canonical_anchor'];
  if(isset($byKey[$k]))$reason='provider_source_now_present';
  elseif(!$target||(int)$target['is_active']!==1)$reason='target_inactive_or_missing';
  elseif(excluded_country((string)$target['country_name']))$reason='target_excluded_country';
  elseif(!facts_equal($target,(array)$s['current_target']))$reason='target_facts_drift';
  elseif(count($acceptedTarget[$ns.'|'.$tv]??[])!==0)$reason='provider_namespace_target_occupied';
  elseif(count($canonRows)!==1)$reason='canonical_anchor_count_'.count($canonRows);
  else{$a=$canonRows[0];if((string)$a['external_hotel_id']!==(string)$expected['external_hotel_id']||(string)$a['catalog_sha256']!==(string)$expected['catalog_sha256']||(string)$a['evidence_sha256']!==(string)$expected['evidence_sha256']||rh($a)!==(string)$expected['row_sha256'])$reason='canonical_anchor_drift';}
  if($reason!==null){$holds[]=['supplier_namespace'=>$ns,'native_hotel_id'=>$ext,'tv_hotel_id'=>$tv,'reason'=>$reason];continue;}
  $a=$canonRows[0];$e=['operation_id'=>OP,'rule'=>'direct_tourvisor_provider_native_to_exact_tv_target_plus_independent_current_canonical_samo_anchor','input_operation'=>INPUT_OP,'input_result_sha256'=>INPUT_SHA,'tv_hotel_id'=>$tv,'operator_id'=>(int)$s['operator_id'],'supplier_namespace'=>$ns,'external_hotel_id'=>$ext,'tour_id'=>(string)$s['tour_id'],'search_batch'=>(int)$s['batch'],'operator_link_sha256'=>(string)$s['operator_link_sha256'],'target'=>['id'=>$tv,'name'=>$target['name'],'country_id'=>(int)$target['country_id'],'country_name'=>$target['country_name'],'region_name'=>$target['region_name'],'subregion_name'=>$target['subregion_name'],'category'=>$target['category']===null?null:(int)$target['category']],'canonical_samo_anchor'=>['supplier_namespace'=>'andromeda_catalog','external_hotel_id'=>(string)$a['external_hotel_id'],'local_hotel_id'=>$tv,'catalog_sha256'=>(string)$a['catalog_sha256'],'evidence_sha256'=>(string)$a['evidence_sha256'],'row_sha256'=>rh($a)],'identity_separation'=>'provider_native_id_not_equal_or_inferred_as_samo_id'];$ej=canon($e);$eh=hash('sha256',$ej);$safe[]=$s;$evidenceByKey[$k]=['json'=>$ej,'sha'=>$eh,'catalog_sha256'=>(string)$a['catalog_sha256']];
 }
 $holdCounts=[];foreach($holds as$h)$holdCounts[$h['reason']]=($holdCounts[$h['reason']]??0)+1;ksort($holdCounts);$safeCount=count($safe);
 savej($dir.'/capture.json',$base+['input_candidates'=>178,'current_safe'=>$safeCount,'holds'=>$holds,'hold_counts'=>$holdCounts,'identity_rows_before'=>count($all),'identity_rows_before_sha256'=>hash('sha256',canon($beforeHashes)),'guard_tables'=>$guards]);
 savej($dir.'/plan.json',$base+['state'=>$safeCount>=MIN_WRITE?'ready_to_write':'below_mass_threshold','minimum_write_threshold'=>MIN_WRITE,'planned_writes'=>$safeCount,'hold_counts'=>$holdCounts,'safe_keys'=>array_map(fn($s)=>$s['supplier_namespace'].'|'.$s['native_hotel_id'],$safe)]);
 if($safeCount<MIN_WRITE){$db->rollBack();$out=$base+['state'=>'completed_no_write_below_threshold','input_candidates'=>178,'current_safe'=>$safeCount,'holds'=>$holds,'hold_counts'=>$holdCounts,'database_writes'=>0,'mapping_writes'=>0,'readback_verified'=>false];$sha=savej($dir.'/result.json',$out);savej($dir.'/receipt.json',['operation'=>OP,'state'=>$out['state'],'result_sha256'=>$sha,'input_candidates'=>178,'current_safe'=>$safeCount,'database_writes'=>0,'mapping_writes'=>0,'provider_calls'=>0]);echo json_encode(['state'=>$out['state'],'current_safe'=>$safeCount,'hold_counts'=>$holdCounts],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";exit(0);}
 $ins=$db->prepare("INSERT INTO andromeda_hotel_identities (supplier_namespace,external_hotel_id,local_hotel_id,decision_status,catalog_sha256,evidence_sha256,evidence_json) VALUES (?,?,?,'accepted',?,?,?)");
 foreach($safe as$s){$k=$s['supplier_namespace'].'|'.$s['native_hotel_id'];$e=$evidenceByKey[$k];$ins->execute([(string)$s['supplier_namespace'],(string)$s['native_hotel_id'],(int)$s['tv_hotel_id'],$e['catalog_sha256'],$e['sha'],$e['json']]);need($ins->rowCount()===1,'insert_count');$inserted[$k]=['supplier_namespace'=>(string)$s['supplier_namespace'],'external_hotel_id'=>(string)$s['native_hotel_id'],'local_hotel_id'=>(int)$s['tv_hotel_id'],'evidence_sha256'=>$e['sha'],'catalog_sha256'=>$e['catalog_sha256']];}
 $after=rows($db,'SELECT supplier_namespace,external_hotel_id,local_hotel_id,decision_status,catalog_sha256,evidence_sha256,evidence_json,created_at FROM andromeda_hotel_identities ORDER BY supplier_namespace,external_hotel_id');need(count($after)===count($all)+$safeCount,'row_count_after_insert');$afterOld=[];$seenNew=[];foreach($after as$r){$k=$r['supplier_namespace'].'|'.$r['external_hotel_id'];if(isset($beforeHashes[$k]))$afterOld[$k]=rh($r);elseif(isset($inserted[$k])){$seenNew[$k]=$r;}else throw new RuntimeException('unexpected_new_identity');}need($afterOld===$beforeHashes,'prior_identity_changed');need(count($seenNew)===$safeCount,'new_identity_count');
 foreach($inserted as$k=>$x){$r=$seenNew[$k]??null;need(is_array($r)&&(int)$r['local_hotel_id']===$x['local_hotel_id']&&$r['decision_status']==='accepted'&&$r['catalog_sha256']===$x['catalog_sha256']&&$r['evidence_sha256']===$x['evidence_sha256']&&hash('sha256',$r['evidence_json'])===$x['evidence_sha256'],'uncommitted_readback');}
 savej($dir.'/pre-commit.json',$base+['state'=>'ready_to_commit','planned_writes'=>$safeCount,'holds'=>$holds,'hold_counts'=>$holdCounts,'prior_identities_preserved'=>count($beforeHashes),'inserted_uncommitted'=>$safeCount,'inserted_keys_sha256'=>hash('sha256',canon(array_keys($inserted)))]);
 $db->commit();$committed=true;
 $db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION READ ONLY');
 $proj=rows($db,"SELECT i.supplier_namespace,i.external_hotel_id,i.decision_status,i.local_hotel_id AS catalog_hotel_id,h.id AS existing_catalog_hotel_id,i.catalog_sha256,i.evidence_sha256,i.evidence_json FROM andromeda_hotel_identities i LEFT JOIN catalog_hotels h ON h.id=i.local_hotel_id WHERE i.decision_status IN ('accepted','rejected') ORDER BY i.supplier_namespace,i.external_hotel_id");$by=[];$resolverRows=[];foreach($proj as$r){$k=$r['supplier_namespace'].'|'.$r['external_hotel_id'];$by[$k]=$r;$resolverRows[]=['supplier_namespace'=>$r['supplier_namespace'],'external_hotel_id'=>$r['external_hotel_id'],'decision_status'=>$r['decision_status'],'catalog_hotel_id'=>$r['catalog_hotel_id'],'existing_catalog_hotel_id'=>$r['existing_catalog_hotel_id']];}
 $resolver=AnyTourAndromedaHotelResolver::fromRows($resolverRows,hash('sha256',canon($resolverRows)));$verified=0;$resolverVerified=0;$post=[];
 foreach($inserted as$k=>$x){$r=$by[$k]??null;need(is_array($r)&&(int)$r['catalog_hotel_id']===$x['local_hotel_id']&&(int)$r['existing_catalog_hotel_id']===$x['local_hotel_id']&&$r['decision_status']==='accepted'&&$r['catalog_sha256']===$x['catalog_sha256']&&$r['evidence_sha256']===$x['evidence_sha256']&&hash('sha256',$r['evidence_json'])===$x['evidence_sha256'],'post_commit_row');$page=$resolver->apply(['provider'=>'andromeda','selection_enabled'=>false,'offers'=>[['provider'=>'andromeda','selection_enabled'=>false,'local_hotel_id'=>null,'supplier_namespace'=>$x['supplier_namespace'],'external_hotel_id'=>$x['external_hotel_id']]]]);need((int)$page['offers'][0]['local_hotel_id']===$x['local_hotel_id'],'resolver_readback');$verified++;$resolverVerified++;$post[]=['supplier_namespace'=>$x['supplier_namespace'],'external_hotel_id'=>$x['external_hotel_id'],'local_hotel_id'=>$x['local_hotel_id'],'evidence_sha256'=>$x['evidence_sha256']];}
 foreach($safe as$s){$tv=(int)$s['tv_hotel_id'];$expected=$s['canonical_anchor'];$cr=array_values(array_filter($proj,fn($r)=>$r['supplier_namespace']==='andromeda_catalog'&&$r['decision_status']==='accepted'&&(int)$r['catalog_hotel_id']===$tv));need(count($cr)===1&&(string)$cr[0]['external_hotel_id']===(string)$expected['external_hotel_id']&&(string)$cr[0]['catalog_sha256']===(string)$expected['catalog_sha256']&&(string)$cr[0]['evidence_sha256']===(string)$expected['evidence_sha256'],'post_canonical_anchor');}
 $db->rollBack();$out=$base+['state'=>'committed_verified','input_candidates'=>178,'current_safe'=>$safeCount,'holds'=>$holds,'hold_counts'=>$holdCounts,'database_writes'=>$safeCount,'mapping_writes'=>$safeCount,'accepted_delta'=>$safeCount,'post_commit_verified'=>$verified,'resolver_verified'=>$resolverVerified,'readback_verified'=>true,'written_rows'=>$post];$sha=savej($dir.'/result.json',$out);savej($dir.'/receipt.json',['operation'=>OP,'source_sha'=>$sourceSha,'state'=>'committed_verified','result_sha256'=>$sha,'input_candidates'=>178,'current_safe'=>$safeCount,'hold_counts'=>$holdCounts,'database_writes'=>$safeCount,'mapping_writes'=>$safeCount,'accepted_delta'=>$safeCount,'post_commit_verified'=>$verified,'resolver_verified'=>$resolverVerified,'readback_verified'=>true,'provider_calls'=>0]);echo json_encode(['state'=>'committed_verified','accepted_delta'=>$safeCount,'hold_counts'=>$holdCounts,'post_commit_verified'=>$verified,'resolver_verified'=>$resolverVerified,'result_sha256'=>$sha],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";
}catch(Throwable $e){if($db->inTransaction())$db->rollBack();$state=$committed?'post_commit_verification_failed_no_replay':'rolled_back_no_write';$msg=preg_replace('/[^A-Za-z0-9_:-]/','_',get_class($e).':'.$e->getMessage());try{savej($dir.'/failure.json',$base+['state'=>$state,'error'=>$msg,'committed'=>$committed,'planned_safe'=>count($safe),'attempted_inserts'=>count($inserted),'database_writes'=>$committed?count($inserted):0,'mapping_writes'=>$committed?count($inserted):0]);}catch(Throwable){}fwrite(STDERR,$state."\n");exit(2);}
