<?php
declare(strict_types=1);
function u153_dict(array $rows,array $aliases):?int{try{return lm_dict($rows,$aliases);}catch(Throwable $e){return null;}}
function u153_run(string $dir,string $root,array $router,string $user,string $pass,string $sha):array{
 $input=(array)$router['routed'];lm_need(count($input)===153,'input153');$ids=array_values(array_unique(array_map(fn($x)=>(int)$x['tv_hotel_id'],$input)));sort($ids);$ph=implode(',',array_fill(0,count($ids),'?'));
 require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION READ ONLY');$hot=[];foreach(lm_rows($db,"SELECT id,name,country_name,region_name,subregion_name,is_active FROM catalog_hotels WHERE id IN ($ph)",$ids)as$h)$hot[(int)$h['id']]=$h;$aliases=[];foreach(lm_rows($db,"SELECT hotel_id,alias FROM hotel_aliases WHERE hotel_id IN ($ph)",$ids)as$a)if(($v=trim((string)$a['alias']))!=='')$aliases[(int)$a['hotel_id']][]=$v;$closed=[];foreach(lm_rows($db,"SELECT external_hotel_id,local_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IN ($ph)",$ids)as$r)$closed[(int)$r['local_hotel_id']][]=(string)$r['external_hotel_id'];$db->rollBack();
 $active=[];$skipped=[];foreach($input as$x){$id=(int)$x['tv_hotel_id'];if(!isset($hot[$id])||(int)$hot[$id]['is_active']!==1){$skipped[]=['tv_hotel_id'=>$id,'state'=>'target_inactive'];continue;}if(isset($closed[$id])){$skipped[]=['tv_hotel_id'=>$id,'state'=>'already_accepted','samo_ids'=>$closed[$id]];continue;}$x['current_hotel']=$hot[$id];$x['current_aliases']=$aliases[$id]??[];$active[]=$x;}lm_need($active!==[],'no_active');
 $calls=0;$prices=0;$manifest=[];$reserve=function(string $kind,array $meta=[])use(&$calls,$dir){$calls++;lm_need($calls<=U153_MAX_CALLS,'call_cap');lm_write($dir.'/provider-calls.jsonl',json_encode(['seq'=>$calls,'kind'=>$kind,'at_utc'=>gmdate('c'),'meta'=>$meta],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",false);};
 $ca=['Китай'=>['Китай','China'],'Турция'=>['Турция','Turkey','Turkiye','Türkiye'],'Таиланд'=>['Таиланд','Thailand'],'Индия'=>['Индия','India'],'Катар'=>['Катар','Qatar'],'Вьетнам'=>['Вьетнам','Vietnam'],'Тунис'=>['Тунис','Tunisia'],'Мальдивы'=>['Мальдивы','Maldives'],'Танзания'=>['Танзания','Tanzania'],'Египет'=>['Египет','Egypt'],'ОАЭ'=>['ОАЭ','Объединенные Арабские Эмираты','United Arab Emirates','UAE']];
 $reserve('login');$login=new AnyTourAndromedaClient(new AnyTourAndromedaTransport(false,false),true);$login->login($user,$pass);$session=$login->privateSession();lm_need($session!==[],'session');
 $deps=[];$pairs=[];foreach($active as$x){$c=$x['context'];$dep=(int)$c['departure_id'];$deps[$dep]=(int)$c['samo_townfrom_id'];$pairs[$dep.'|'.$x['country_name']]=[$dep,(string)$x['country_name']];}
 $states=[];foreach($deps as$dep=>$samoDep){$reserve('state',['dep'=>$dep,'samo_dep'=>$samoDep]);$cl=new AnyTourAndromedaClient(new AnyTourAndromedaTransport(false,false),true);$cl->restorePrivateSession($session);$st=$cl->catalog('state',['TOWNFROMINC'=>$samoDep]);lm_raw($dir,'state-d'.$dep,$st,$manifest);$states[$dep]=$st;}
 $catalogs=[];$unavailable=[];foreach($pairs as$pk=>[$dep,$country]){if(!isset($ca[$country])){$unavailable[$pk]='country_alias_missing';continue;}$sid=u153_dict($states[$dep]['STATE'],$ca[$country]);if($sid===null){$unavailable[$pk]='country_not_available';continue;}$reserve('catalog',['dep'=>$dep,'country'=>$country,'state'=>$sid]);$cl=new AnyTourAndromedaClient(new AnyTourAndromedaTransport(false,false),true);$cl->restorePrivateSession($session);$all=$cl->catalog('all',['TOWNFROMINC'=>$deps[$dep],'STATEINC'=>$sid]);lm_raw($dir,'catalog-'.substr(hash('sha256',$pk),0,12),$all,$manifest);$op=false;foreach((array)$all['OPERATORS']as$o)if((string)($o['id']??'')==='5'&&str_contains(lm_norm(lm_text($o['name']??($o['lName']??''),100)),'anex'))$op=true;if(!$op){$unavailable[$pk]='anex_operator_unavailable';continue;}$catalogs[$pk]=['state'=>$sid,'provider'=>lm_provider((array)$all['HOTELS'],lm_towns((array)$all['TOWNTO']))];}
 $plans=[];$groups=[];foreach($active as$x){$id=(int)$x['tv_hotel_id'];$c=$x['context'];$dep=(int)$c['departure_id'];$country=(string)$x['country_name'];$pk=$dep.'|'.$country;$base=['tv_hotel_id'=>$id,'hotel_name'=>$x['current_hotel']['name'],'country'=>$country,'region_name'=>$x['current_hotel']['region_name'],'subregion_name'=>$x['current_hotel']['subregion_name'],'departure_id'=>$dep,'departure_name'=>$c['departure_name'],'samo_townfrom_id'=>(int)$c['samo_townfrom_id'],'anex_hotel_ids'=>array_map('strval',(array)$x['anex_hotel_ids']),'context'=>$c,'facts'=>[]];if(!isset($catalogs[$pk])){$plans[$id]=$base+['pair_unavailable'=>$unavailable[$pk]??'unknown','retrieval_mode'=>'none','candidates'=>[],'candidate_ids'=>[],'group_key'=>null];continue;}$cand=lm_candidates($x['current_hotel'],$x['current_aliases'],$catalogs[$pk]['provider']);$cids=array_keys($cand['candidates']);$gk=implode('|',[$dep,$country,$c['departure_date'],$c['nights'],$c['adults'],$c['children_count'],$c['child_ages_signature']]);$plans[$id]=$base+['pair_unavailable'=>null,'retrieval_mode'=>$cand['mode'],'candidates'=>$cand['candidates'],'candidate_ids'=>$cids,'group_key'=>$gk];if(!$cids)continue;$groups[$gk]['dep']=$dep;$groups[$gk]['country']=$country;$groups[$gk]['context']=$c;$groups[$gk]['targets'][]=$id;foreach($cids as$cid)$groups[$gk]['candidate_ids'][$cid]=true;}
 foreach($groups as$gk=>&$g){$allIds=array_keys($g['candidate_ids']);sort($allIds,SORT_NATURAL);$g['chunks']=[];foreach(array_chunk($allIds,30)as$ci=>$chunk){$dep=$g['dep'];$pk=$dep.'|'.$g['country'];$c=$g['context'];$params=['TOWNFROMINC'=>$deps[$dep],'STATEINC'=>$catalogs[$pk]['state'],'CHECKIN_BEG'=>str_replace('-','',(string)$c['departure_date']),'CHECKIN_END'=>str_replace('-','',(string)$c['departure_date']),'NIGHTS_FROM'=>(int)$c['nights'],'NIGHTS_TILL'=>(int)$c['nights'],'ADULT'=>(int)$c['adults'],'CHILD'=>(int)$c['children_count'],'CURRENCYINC'=>643,'OPERATORS'=>'5','HOTELS'=>implode(',',$chunk),'PACKETTYPE'=>0,'PAGE'=>1];if((int)$c['children_count']>0){$ages=(string)$c['child_ages_signature'];lm_need(preg_match('/^[0-9]+(?:,[0-9]+)*$/D',$ages)===1&&count(explode(',',$ages))===(int)$c['children_count'],'ages');$params['AGES']=$ages;}$needed=array_fill_keys($chunk,true);$seen=[];$pages=0;$pcnt=null;
   for($p=1;$p<=U153_MAX_PAGES;$p++){lm_need(++$prices<=U153_MAX_PRICE,'price_cap');$params['PAGE']=$p;$reserve('price',['group'=>substr(hash('sha256',$gk),0,12),'chunk'=>$ci,'page'=>$p]);$cl=new AnyTourAndromedaClient(new AnyTourAndromedaTransport(true,false),true);$cl->restorePrivateSession($session);$reply=$cl->price($params);lm_raw($dir,'price-'.substr(hash('sha256',$gk),0,10).'-c'.$ci.'-p'.$p,$reply,$manifest);$pages++;$pcnt=(int)$reply['PAGES_COUNT'];foreach((array)$reply['PRICES']as$row){if(!is_array($row)||!($fact=lm_fact($row,'5')))continue;$sid=$fact['samo_hotel_id'];if(!isset($needed[$sid]))continue;$seen[$sid]=true;foreach($g['targets']as$tid)if(isset($plans[$tid]['candidates'][$sid]))$plans[$tid]['facts'][]=$fact;}if(!array_diff_key($needed,$seen)||$pcnt===0||$p>=$pcnt)break;}
   $g['chunks'][]=['candidate_ids'=>$chunk,'pages_read'=>$pages,'pages_count_reported'=>$pcnt,'seen_candidate_ids'=>array_keys($seen),'pagination_incomplete'=>(bool)(array_diff_key($needed,$seen)&&$pcnt!==null&&$pages<$pcnt)];}unset($g['candidate_ids']);}unset($g);
 $counts=[];$dossiers=[];foreach($plans as$p){$direct=[];$returned=[];$incomplete=false;if($p['group_key']!==null&&isset($groups[$p['group_key']]))foreach($groups[$p['group_key']]['chunks']as$ch)if($ch['pagination_incomplete'])$incomplete=true;foreach($p['facts']as$f){$returned[$f['samo_hotel_id']]=true;if($f['native_operator_hotel_id']!==null&&in_array((string)$f['native_operator_hotel_id'],$p['anex_hotel_ids'],true))$direct[$f['samo_hotel_id']]=$f;}$state=$p['pair_unavailable']!==null?'pair_unavailable':(!$p['candidate_ids']?'no_catalog_candidate':($incomplete?'pagination_hold':(!$returned?'not_returned_exact_context':(count($direct)===1?'direct_native_bridge':(count($direct)>1?'ambiguous_direct_bridge':'returned_without_native_match')))));$counts[$state]=($counts[$state]??0)+1;$dossiers[]=['tv_hotel_id'=>$p['tv_hotel_id'],'hotel_name'=>$p['hotel_name'],'country'=>$p['country'],'departure_id'=>$p['departure_id'],'departure_name'=>$p['departure_name'],'samo_townfrom_id'=>$p['samo_townfrom_id'],'anex_hotel_ids'=>$p['anex_hotel_ids'],'context'=>$p['context'],'pair_unavailable'=>$p['pair_unavailable'],'retrieval_mode'=>$p['retrieval_mode'],'queried_candidate_ids'=>$p['candidate_ids'],'returned_samo_ids'=>array_keys($returned),'direct_bridges'=>array_values($direct),'state'=>$state,'safe_to_write_now'=>false];}
 $mh=lm_json_file($dir.'/raw-manifest.json',['files'=>$manifest]);return['operation'=>U153_OP,'state'=>'completed_read_only','source_sha'=>$sha,'router_sha256'=>U153_ROUTER,'input_routed153'=>153,'current_active_targets'=>count($active),'current_skipped'=>count($skipped),'skipped'=>$skipped,'departure_count'=>count($deps),'pair_count'=>count($pairs),'unavailable_pairs'=>$unavailable,'group_count'=>count($groups),'provider_calls'=>$calls,'price_calls'=>$prices,'tourvisor_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'state_counts'=>$counts,'dossiers'=>$dossiers,'raw_manifest_sha256'=>$mh,'no_replay'=>true];
}
