<?php
declare(strict_types=1);

const C4U2_OP='hotel-match-common4-usersearch-frontier-current-1971-20260919-v2';
const C4U2_MAX_ROWS=250000;
const C4U2_ROUTES=[
  13=>['operator'=>'anex','ns'=>'operator_5'],
  25=>['operator'=>'funsun','ns'=>'operator_315'],
  18=>['operator'=>'biblio_globus','ns'=>'operator_115'],
  43=>['operator'=>'intourist','ns'=>'operator_342'],
];
function c4u2_req(bool $ok,string $why):void{if(!$ok)throw new RuntimeException($why);}
function c4u2_json(array $x):string{return json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";}
function c4u2_write(string $p,array $x):string{$raw=c4u2_json($x);$f=@fopen($p,'x+b');c4u2_req(is_resource($f),'exclusive_output');try{c4u2_req(fwrite($f,$raw)===strlen($raw)&&fflush($f),'output_write');if(function_exists('fsync'))c4u2_req(fsync($f),'output_sync');rewind($f);c4u2_req(stream_get_contents($f)===$raw,'output_readback');}finally{fclose($f);}return hash('sha256',$raw);}
function c4u2_read(string $p):array{c4u2_req(!is_link($p)&&realpath($p)===$p&&is_file($p),'input_path');$raw=file_get_contents($p);c4u2_req(is_string($raw)&&strlen($raw)<=1048576,'input_read');$x=json_decode($raw,true,64,JSON_THROW_ON_ERROR);c4u2_req(is_array($x),'input_shape');return$x;}
function c4u2_q(PDO $db,string $sql,array $args=[]):array{$q=$db->prepare($sql);$q->execute(array_values($args));$rows=$q->fetchAll(PDO::FETCH_ASSOC)?:[];c4u2_req(count($rows)<=C4U2_MAX_ROWS,'row_budget');return$rows;}
function c4u2_opaque(string $name):bool{return preg_match('/(?:^|[^\p{L}])(?:FORTUNA|ROULETTE|ФОРТУНА|РУЛЕТКА)(?:$|[^\p{L}])/iu',$name)===1;}
function c4u2_main():void{
  c4u2_req(PHP_SAPI==='cli'&&(string)getenv('MATCH_OPERATION_ID')===C4U2_OP,'operation_guard');
  $sha=(string)getenv('MATCH_SOURCE_SHA');c4u2_req(preg_match('/^[0-9a-f]{40}$/D',$sha)===1,'source_sha');
  $dir=rtrim((string)getenv('HOME'),'/').'/.anytoour-match/operations/'.C4U2_OP;
  $res=c4u2_read($dir.'/reservation.json');c4u2_req(($res['operation_id']??'')===C4U2_OP&&($res['source_sha']??'')===$sha&&($res['state']??'')==='reserved_before_db_access','reservation_guard');
  $root=realpath(getcwd());c4u2_req(is_string($root)&&basename($root)==='anytoour.ru','root_guard');
  require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');
  $db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
  $out=['operation_id'=>C4U2_OP,'source_sha'=>$sha,'state'=>'failed_no_replay','no_replay'=>true,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'samo_calls'=>0];
  try{
    $db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');
    $db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');
    foreach(['tour_price_observations','andromeda_hotel_identities','catalog_hotels']as$t){$r=c4u2_q($db,'SELECT ENGINE FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?',[$t]);c4u2_req(count($r)===1&&strtoupper((string)$r[0]['ENGINE'])==='INNODB','table_contract_'.$t);}
    $cnt=c4u2_q($db,"SELECT COUNT(*) c FROM tour_price_observations WHERE source='user_search' AND operator_id IN (13,18,25,43)");$rawCount=(int)($cnt[0]['c']??0);c4u2_req($rawCount<=C4U2_MAX_ROWS,'observation_budget_exceeded');
    $obs=c4u2_q($db,"SELECT p.hotel_id,p.operator_id,p.country_id,p.region_id,p.subregion_id,p.departure_id,p.departure_date,p.nights,p.adults,p.children_count,p.child_ages_signature,p.search_id,p.tour_id,p.observed_at,h.name hotel_name,h.is_active FROM tour_price_observations p JOIN catalog_hotels h ON h.id=p.hotel_id WHERE p.source='user_search' AND p.operator_id IN (13,18,25,43) ORDER BY p.observed_at DESC,p.hotel_id,p.operator_id");
    $acceptedRows=c4u2_q($db,"SELECT supplier_namespace,local_hotel_id,external_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace IN ('operator_5','operator_115','operator_315','operator_342') AND decision_status='accepted' AND local_hotel_id IS NOT NULL");
    $accepted=[];foreach($acceptedRows as$r){$local=(int)$r['local_hotel_id'];if($local>0)$accepted[(string)$r['supplier_namespace'].':'.$local][]=(string)$r['external_hotel_id'];}
    $today=(new DateTimeImmutable('now',new DateTimeZone('Europe/Moscow')))->format('Y-m-d');$edges=[];$opaque=[];
    foreach($obs as$r){$op=(int)$r['operator_id'];$hid=(int)$r['hotel_id'];if(!isset(C4U2_ROUTES[$op])||$hid<=0)continue;$name=trim((string)$r['hotel_name']);$key=$op.':'.$hid;if(c4u2_opaque($name)){$opaque[$key]=true;continue;}$route=C4U2_ROUTES[$op];if(!isset($edges[$key]))$edges[$key]=['tv_hotel_id'=>$hid,'hotel_name'=>$name,'is_active'=>(int)$r['is_active']===1,'operator_id'=>$op,'operator'=>$route['operator'],'target_supplier_namespace'=>$route['ns'],'latest_observed_at'=>(string)$r['observed_at'],'observation_rows'=>0,'latest_future_context'=>null];$edges[$key]['observation_rows']++;if((string)$r['departure_date']>=$today&&$edges[$key]['latest_future_context']===null)$edges[$key]['latest_future_context']=['departure_id'=>(int)$r['departure_id'],'country_id'=>(int)$r['country_id'],'region_id'=>$r['region_id']===null?null:(int)$r['region_id'],'subregion_id'=>$r['subregion_id']===null?null:(int)$r['subregion_id'],'departure_date'=>(string)$r['departure_date'],'nights'=>(int)$r['nights'],'adults'=>(int)$r['adults'],'children_count'=>(int)$r['children_count'],'child_ages_signature'=>(string)$r['child_ages_signature'],'search_id'=>(int)$r['search_id'],'tour_id'=>$r['tour_id']===null?null:(string)$r['tour_id'],'observed_at'=>(string)$r['observed_at']];}
    $missing=[];$resolved=[];$by=[];
    foreach($edges as$e){$o=$e['operator'];$by[$o]??=['observed_edges'=>0,'accepted_same_provider'=>0,'missing_edges'=>0,'actionable_future'=>0,'observed_only'=>0];$by[$o]['observed_edges']++;$aKey=$e['target_supplier_namespace'].':'.$e['tv_hotel_id'];if(isset($accepted[$aKey])){$e['accepted_external_hotel_ids']=array_values(array_unique($accepted[$aKey]));$resolved[]=$e;$by[$o]['accepted_same_provider']++;}else{$e['actionable_future']=$e['is_active']&&is_array($e['latest_future_context']);$missing[]=$e;$by[$o]['missing_edges']++;if($e['actionable_future'])$by[$o]['actionable_future']++;else$by[$o]['observed_only']++;}}
    usort($missing,fn($a,$b)=>(!empty($b['actionable_future'])<=>!empty($a['actionable_future']))?:strcmp((string)$b['latest_observed_at'],(string)$a['latest_observed_at'])?:((int)$b['observation_rows']<=>(int)$a['observation_rows'])?:((int)$a['tv_hotel_id']<=>(int)$b['tv_hotel_id']));
    $contexts=[];foreach($missing as$e){if(empty($e['actionable_future']))continue;$c=$e['latest_future_context'];$k=implode('|',[$e['operator_id'],$c['departure_id'],$c['country_id'],$c['departure_date'],$c['nights'],$c['adults'],$c['children_count'],$c['child_ages_signature']]);if(!isset($contexts[$k]))$contexts[$k]=['operator'=>$e['operator'],'operator_id'=>$e['operator_id'],'target_supplier_namespace'=>$e['target_supplier_namespace'],'departure_id'=>$c['departure_id'],'country_id'=>$c['country_id'],'departure_date'=>$c['departure_date'],'nights'=>$c['nights'],'adults'=>$c['adults'],'children_count'=>$c['children_count'],'child_ages_signature'=>$c['child_ages_signature'],'hotel_ids'=>[]];$contexts[$k]['hotel_ids'][]=$e['tv_hotel_id'];}
    foreach($contexts as&$c){$c['hotel_ids']=array_values(array_unique(array_map('intval',$c['hotel_ids'])));sort($c['hotel_ids'],SORT_NUMERIC);$c['hotel_count']=count($c['hotel_ids']);$c['identity_batches_up_to_30']=(int)ceil($c['hotel_count']/30);}unset($c);$contexts=array_values($contexts);usort($contexts,fn($a,$b)=>($b['hotel_count']<=>$a['hotel_count'])?:strcmp($a['operator'],$b['operator']));
    $db->commit();$out+=['state'=>'completed_read_only','read_at_utc'=>gmdate('c'),'today_moscow'=>$today,'current_tv_to_samo_routes'=>['13'=>'operator_5','25'=>'operator_315','18'=>'operator_115','43'=>'operator_342'],'raw_user_search_observation_rows'=>$rawCount,'unique_user_search_operator_hotel_edges'=>count($edges),'opaque_fortuna_roulette_edges_excluded'=>count($opaque),'accepted_same_provider_edges'=>count($resolved),'missing_same_provider_edges'=>count($missing),'by_operator'=>$by,'actionable_context_groups'=>count($contexts),'actionable_contexts'=>$contexts,'missing_edges'=>$missing];
  }catch(Throwable $e){if($db->inTransaction())$db->rollBack();$out['reason']=preg_match('/^[A-Za-z0-9_:.-]+$/D',$e->getMessage())?$e->getMessage():'sanitized_error';}
  $hash=c4u2_write($dir.'/result.json',$out);c4u2_write($dir.'/receipt.json',['operation_id'=>C4U2_OP,'source_sha'=>$sha,'state'=>$out['state'],'result_sha256'=>$hash,'readback_verified'=>hash('sha256',(string)file_get_contents($dir.'/result.json'))===$hash,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'samo_calls'=>0,'no_replay'=>true]);echo json_encode(['state'=>$out['state'],'raw_rows'=>$out['raw_user_search_observation_rows']??null,'unique_edges'=>$out['unique_user_search_operator_hotel_edges']??null,'accepted_edges'=>$out['accepted_same_provider_edges']??null,'missing_edges'=>$out['missing_same_provider_edges']??null,'by_operator'=>$out['by_operator']??null,'context_groups'=>$out['actionable_context_groups']??null,'result_sha256'=>$hash],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n";exit($out['state']==='completed_read_only'?0:2);
}
if(($argv[1]??'')==='--self-test'){c4u2_req(c4u2_opaque('Fortuna Antalya'),'opaque');c4u2_req(!c4u2_opaque('Family Hotel'),'normal');c4u2_req(C4U2_ROUTES[25]['ns']==='operator_315','route');echo"hotel-match-common4-usersearch-frontier-current-v2: PASS\n";exit(0);}if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__)c4u2_main();
