<?php
declare(strict_types=1);
const OP='hotel-match-current-ambiguous108-audit-1971-20260922-v1';
function need(bool $ok,string $code):void{if(!$ok)throw new RuntimeException($code);}
function loadj(string $p):array{$v=json_decode((string)file_get_contents($p),true,64,JSON_THROW_ON_ERROR);need(is_array($v),'json');return $v;}
function savej(string $p,array $v):string{$b=json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";$f=fopen($p,'xb');need(is_resource($f),'exclusive');need(fwrite($f,$b)===strlen($b)&&fflush($f),'write');if(function_exists('fsync'))need(fsync($f),'fsync');fclose($f);return hash('sha256',$b);}
function q(PDO $db,string $sql,array $args=[]):array{$s=$db->prepare($sql);$s->execute(array_values($args));return $s->fetchAll(PDO::FETCH_ASSOC)?:[];}
if(($argv[1]??'')==='--self-test'){echo "OK\n";exit(0);}need(($argv[1]??'')==='--execute','mode');
$root=realpath((string)getenv('ANYTOUR_ROOT'));$dir=realpath((string)getenv('MATCH_OPERATION_DIR'));$sha=(string)getenv('MATCH_SOURCE_SHA');need($root!==false&&$dir!==false&&basename($dir)===OP&&preg_match('/^[a-f0-9]{40}$/D',$sha)===1,'scope');
$input=loadj($dir.'/payload/ambiguous.json');$res=loadj($dir.'/payload/reservation.json');need(count($input)===108,'input_count');need(($res['operation']??'')===OP&&($res['source_sha']??'')===$sha&&($res['input_sha256']??'')===hash_file('sha256',$dir.'/payload/ambiguous.json'),'reservation');
require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');
$ids=[];$targets=[];foreach($input as $e){foreach($e['positive_native_candidates'] as $id)$ids[(string)$e['supplier_namespace'].'|'.(string)$id]=true;$targets[(int)$e['tv_hotel_id']]=true;}
$rows=q($db,"SELECT supplier_namespace,external_hotel_id,local_hotel_id,decision_status,evidence_sha256 FROM andromeda_hotel_identities WHERE supplier_namespace IN ('operator_315','operator_342') ORDER BY supplier_namespace,external_hotel_id");
$manual=q($db,'SELECT catalog_hotel_id,decision_status,decided_by,decision_note FROM anex_hotel_decisions ORDER BY catalog_hotel_id');$db->rollBack();
$byKey=[];foreach($rows as $r)$byKey[(string)$r['supplier_namespace'].'|'.(string)$r['external_hotel_id']][]=$r;$manualBy=[];foreach($manual as $r)if($r['catalog_hotel_id']!==null)$manualBy[(int)$r['catalog_hotel_id']][]=$r;
$out=[];$counts=[];$resolvedKeys=[];$resolvedHotels=[];
foreach($input as $e){$tv=(int)$e['tv_hotel_id'];$ns=(string)$e['supplier_namespace'];$same=[];$else=[];$candidateFacts=[];foreach($e['positive_native_candidates'] as $id){$key=$ns.'|'.(string)$id;$facts=$byKey[$key]??[];$candidateFacts[]=['native_id'=>(string)$id,'current_rows'=>$facts];foreach($facts as $r){if(($r['decision_status']??'')!=='accepted'||$r['local_hotel_id']===null)continue;if((int)$r['local_hotel_id']===$tv)$same[(string)$id]=true;else$else[(string)$id][(int)$r['local_hotel_id']]=true;}}
 if(isset($manualBy[$tv]))$state='manual_protected';elseif(count($same)===1&&count($else)===0)$state='resolved_existing_same_target';elseif(count($same)>1)$state='multiple_same_target';elseif(count($else)>0)$state='candidate_elsewhere';else$state='no_current_candidate';
 $counts[$state]=($counts[$state]??0)+1;if($state==='resolved_existing_same_target'){$resolvedKeys[]=$ns.'|'.array_key_first($same);$resolvedHotels[$tv]=true;}
 $out[]=['tv_hotel_id'=>$tv,'operator_id'=>(int)$e['operator_id'],'supplier_namespace'=>$ns,'operator_link_sha256'=>(string)$e['operator_link_sha256'],'link_state'=>(string)$e['link_state'],'positive_native_candidates'=>array_values(array_map('strval',$e['positive_native_candidates'])),'same_target_native'=>array_keys($same),'elsewhere_native'=>$else,'manual_protected'=>isset($manualBy[$tv]),'classification'=>$state,'candidate_facts'=>$candidateFacts];}
ksort($counts);sort($resolvedKeys,SORT_STRING);$result=['operation'=>OP,'state'=>'completed_read_only','source_sha'=>$sha,'input_edges'=>count($input),'unique_tv_hotels'=>count($targets),'counts'=>$counts,'resolved_existing_keys'=>$resolvedKeys,'resolved_existing_unique_hotels'=>count($resolvedHotels),'rows'=>$out,'supplier_calls'=>0,'tourvisor_calls'=>0,'andromeda_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true];$rh=savej($dir.'/result.json',$result);savej($dir.'/receipt.json',['operation'=>OP,'state'=>'completed_read_only','source_sha'=>$sha,'result_sha256'=>$rh,'counts'=>$counts,'resolved_existing_unique_hotels'=>count($resolvedHotels),'supplier_calls'=>0,'database_writes'=>0,'mapping_writes'=>0]);echo json_encode(['counts'=>$counts,'resolved_existing_unique_hotels'=>count($resolvedHotels),'result_sha256'=>$rh],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";