<?php
declare(strict_types=1);

// Requires fc_* helpers from hotel_full_catalog_reconcile.php in the caller.
const FD_OPERATION = 'hotel-full-catalog-delta-1759-20260911-v2';

function fd_tokens($v): array { return fc_tokens($v, true); }
function fd_key($v): string { $t=fd_tokens($v); sort($t,SORT_STRING); return implode(' ',$t); }
function fd_similarity($a,$b): array {
    $a=array_fill_keys(array_unique(fd_tokens($a)),1);$b=array_fill_keys(array_unique(fd_tokens($b)),1);
    $shared=count(array_intersect_key($a,$b));$union=count($a+$b);return [$union?$shared/$union:0.0,$shared];
}
function fd_places(array $hotels): array {
    $out=[];foreach($hotels as $id=>$h)foreach([$h['region_name']??'',$h['subregion_name']??''] as $p){$p=fc_norm($p);if($p!=='')$out[(int)$h['country_id']][$p][(int)$id]=1;}return $out;
}
function fd_andromeda_bridge(PDO $db): array {
    $out=[];$q=$db->query("SELECT i.local_hotel_id,i.evidence_json,h.country_id FROM andromeda_hotel_identities i JOIN catalog_hotels h ON h.id=i.local_hotel_id WHERE i.supplier_namespace='andromeda_catalog' AND i.decision_status='accepted' AND i.local_hotel_id IS NOT NULL AND h.country_id IN(1,2,4,8,9,10,12,16) FOR UPDATE");
    while($r=$q->fetch(PDO::FETCH_ASSOC)){$s=fc_source($r);foreach([$s['name']??'',$s['lName']??''] as $name){$k=fd_key($name);if($k!=='')$out[(int)$r['country_id']][$k][(int)$r['local_hotel_id']]=1;}}return $out;
}
function fd_anex_bridge(PDO $db): array {
    $out=[];$sql="SELECT m.catalog_hotel_id,s.api_name,s.xml_name,s.xml_alternate_name,h.country_id FROM anex_hotel_search_mappings m LEFT JOIN anex_hotels s ON s.anex_hotel_id=m.anex_hotel_id JOIN catalog_hotels h ON h.id=m.catalog_hotel_id WHERE m.enabled=1 AND h.country_id IN(1,2,4,8,9,10,12,16) UNION ALL SELECT d.catalog_hotel_id,s.api_name,s.xml_name,s.xml_alternate_name,h.country_id FROM anex_hotel_decisions d LEFT JOIN anex_hotels s ON s.anex_hotel_id=d.anex_hotel_id JOIN catalog_hotels h ON h.id=d.catalog_hotel_id WHERE d.decision_status='accepted' AND h.country_id IN(1,2,4,8,9,10,12,16)";
    foreach($db->query($sql)->fetchAll(PDO::FETCH_ASSOC) as $r)foreach([$r['api_name'],$r['xml_name'],$r['xml_alternate_name']] as $name){$k=fd_key($name);if($k!=='')$out[(int)$r['country_id']][$k][(int)$r['catalog_hotel_id']]=1;}return $out;
}
function fd_best(array $candidateIds,array $sourceNames,array $names,array $meta): array {
    $best=[0.0,0,null,null,false];$second=0.0;
    foreach($candidateIds as $id){$score=0.0;$shared=0;foreach($sourceNames as $a)foreach($names[$id]??[] as $b){[$s,$n]=fd_similarity($a,$b);if($s>$score){$score=$s;$shared=$n;}}$m=$meta[$id]??[null,false];if($score>$best[0]){$second=$best[0];$best=[$score,$shared,(int)$id,$m[0],$m[1]];}elseif($score>$second)$second=$score;}
    return [$best,$second];
}
function fd_reconcile(PDO $db,string $operation): array {
    fc_require_tables($db);$need=['anex_search_hotel_observations'];$q=$db->prepare("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND ENGINE='InnoDB'");foreach($need as $t){$q->execute([$t]);if((int)$q->fetchColumn()!==1)throw new RuntimeException('required_transactional_table_missing');}
    $db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET SESSION innodb_lock_wait_timeout=20');$before=fc_coverage($db);$committed=false;$writes=0;
    try{
        $db->beginTransaction();[$hotels,$names,$strict,$broad,$scope]=fc_catalog($db);$places=fd_places($hotels);
        $manual=array_fill_keys(array_map('intval',$db->query('SELECT anex_hotel_id FROM anex_hotel_decisions ORDER BY anex_hotel_id FOR UPDATE')->fetchAll(PDO::FETCH_COLUMN)),1);$existing=array_fill_keys(array_map('intval',$db->query('SELECT anex_hotel_id FROM anex_hotel_search_mappings ORDER BY anex_hotel_id FOR UPDATE')->fetchAll(PDO::FETCH_COLUMN)),1);$excluded=[];foreach($db->query('SELECT anex_hotel_id,catalog_hotel_id FROM anex_review_pair_exclusions ORDER BY anex_hotel_id,catalog_hotel_id FOR UPDATE')->fetchAll(PDO::FETCH_ASSOC) as $x)$excluded[(int)$x['anex_hotel_id']][(int)$x['catalog_hotel_id']]=1;
        $andBridge=fd_andromeda_bridge($db);$insert=$db->prepare("INSERT INTO anex_hotel_search_mappings(anex_hotel_id,catalog_hotel_id,match_class,scope,approval_policy,source_row_digest,mapping_digest,enabled) VALUES(?,?,'strong_candidate','preview',?,?,?,1)");$mapDigest=fc_hash([$operation,'post_core8_delta_v2']);$anRows=[];
        $anex=['remaining_staging_core'=>0,'accepted'=>0,'andromeda_bridge'=>0,'tight_coord_name'=>0,'place_name_margin'=>0,'geo_conflict'=>0,'ambiguous'=>0,'pair_excluded'=>0];
        $q=$db->query("SELECT s.* FROM anex_hotels s LEFT JOIN anex_hotel_search_mappings m ON m.anex_hotel_id=s.anex_hotel_id LEFT JOIN anex_hotel_decisions d ON d.anex_hotel_id=s.anex_hotel_id WHERE m.anex_hotel_id IS NULL AND d.anex_hotel_id IS NULL ORDER BY s.anex_hotel_id FOR UPDATE");
        while($s=$q->fetch(PDO::FETCH_ASSOC)){$country=fc_country($s['api_country']??'');if(!$country||!isset(FC_COUNTRIES[$country]))continue;$anex['remaining_staging_core']++;$id=(int)$s['anex_hotel_id'];$sourceNames=array_values(array_filter([$s['api_name']??'',$s['xml_name']??'',$s['xml_alternate_name']??'']));$target=null;$rule=null;
            $bridge=[];foreach($sourceNames as $name){$k=fd_key($name);if($k!=='')foreach(array_keys($andBridge[$country][$k]??[]) as $x)$bridge[(int)$x]=1;}if(count($bridge)===1){$x=(int)array_key_first($bridge);$h=$hotels[$x]??null;$dist=$h?fc_dist($s['latitude'],$s['longitude'],$h['latitude'],$h['longitude']):null;if($h&&($dist===null||$dist<=5000)){$target=$x;$rule='accepted_andromeda_bridge';}}
            if($target===null){$candidateMeta=[];foreach($hotels as $x=>$h){if((int)$h['country_id']!==$country)continue;$dist=fc_dist($s['latitude'],$s['longitude'],$h['latitude'],$h['longitude']);$place=fc_place([$s['api_region'],$s['api_town']],[$h['region_name'],$h['subregion_name']]);if(($dist!==null&&$dist<=1000)||$place)$candidateMeta[(int)$x]=[$dist,$place];}[$best,$second]=fd_best(array_keys($candidateMeta),$sourceNames,$names,$candidateMeta);if($best[2]!==null&&$best[0]-$second>=0.15){if($best[3]!==null&&$best[3]<=200&&$best[0]>=0.75&&$best[1]>=2){$target=$best[2];$rule='tight_coord_name_margin';}elseif($best[4]&&$best[0]>=0.82&&$best[1]>=2){$target=$best[2];$rule='place_name_margin';}}}
            if($target===null){$anex['ambiguous']++;continue;}$h=$hotels[$target];$dist=fc_dist($s['latitude'],$s['longitude'],$h['latitude'],$h['longitude']);if($dist!==null&&$dist>5000){$anex['geo_conflict']++;continue;}if(isset($excluded[$id][$target])){$anex['pair_excluded']++;continue;}if($rule==='accepted_andromeda_bridge')$anex['andromeda_bridge']++;elseif($rule==='tight_coord_name_margin')$anex['tight_coord_name']++;else$anex['place_name_margin']++;
            $ev=['operation_id'=>$operation,'provider'=>'anex','rule'=>$rule,'anex_hotel_id'=>$id,'country_id'=>$country,'source_fingerprint'=>$s['source_fingerprint'],'names'=>$sourceNames,'region'=>$s['api_region'],'town'=>$s['api_town'],'distance_m'=>$dist===null?null:round($dist,1),'target'=>$target];$digest=fc_hash($ev);$insert->execute([$id,$target,FC_POLICY,$digest,$mapDigest]);$anRows[$id]=[$target,$digest];$existing[$id]=1;$anex['accepted']++;$writes++;}
        $observed=['remaining_no_staging_core'=>0,'accepted'=>0,'andromeda_bridge'=>0,'ambiguous'=>0,'pair_excluded'=>0];$q=$db->query("SELECT o.* FROM anex_search_hotel_observations o LEFT JOIN anex_hotels s ON s.anex_hotel_id=o.anex_hotel_id LEFT JOIN anex_hotel_search_mappings m ON m.anex_hotel_id=o.anex_hotel_id LEFT JOIN anex_hotel_decisions d ON d.anex_hotel_id=o.anex_hotel_id WHERE s.anex_hotel_id IS NULL AND m.anex_hotel_id IS NULL AND d.anex_hotel_id IS NULL ORDER BY o.search_count DESC,o.anex_hotel_id FOR UPDATE");
        while($o=$q->fetch(PDO::FETCH_ASSOC)){$country=(int)$o['country_id'];if(!isset(FC_COUNTRIES[$country]))continue;$observed['remaining_no_staging_core']++;$tokens=fd_tokens($o['hotel_name']);if(count($tokens)<2){$observed['ambiguous']++;continue;}$k=fd_key($o['hotel_name']);$bridge=array_map('intval',array_keys($andBridge[$country][$k]??[]));if(count($bridge)!==1){$observed['ambiguous']++;continue;}$target=$bridge[0];$id=(int)$o['anex_hotel_id'];if(isset($excluded[$id][$target])){$observed['pair_excluded']++;continue;}$ev=['operation_id'=>$operation,'provider'=>'anex','rule'=>'observed_accepted_andromeda_bridge','anex_hotel_id'=>$id,'country_id'=>$country,'hotel_name'=>$o['hotel_name'],'search_count'=>(int)$o['search_count'],'last_seen_utc'=>$o['last_seen_utc'],'target'=>$target];$digest=fc_hash($ev);$insert->execute([$id,$target,FC_POLICY,$digest,$mapDigest]);$anRows[$id]=[$target,$digest];$existing[$id]=1;$observed['accepted']++;$observed['andromeda_bridge']++;$writes++;}
        $anexBridge=fd_anex_bridge($db);$shaCountry=fc_sha_countries($db);$update=$db->prepare("UPDATE andromeda_hotel_identities SET local_hotel_id=?,decision_status='accepted',evidence_sha256=?,evidence_json=? WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=? AND decision_status='pending' AND local_hotel_id IS NULL AND evidence_sha256=?");$andRows=[];$and=['pending'=>0,'accepted'=>0,'fuzzy_saved_geo'=>0,'fuzzy_anex_bridge'=>0,'category_conflict'=>0,'candidate_conflict'=>0,'ambiguous'=>0];
        $q=$db->query("SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='pending' AND local_hotel_id IS NULL ORDER BY external_hotel_id FOR UPDATE");while($r=$q->fetch(PDO::FETCH_ASSOC)){$and['pending']++;$prior=fc_evidence($r['evidence_json']);$s=$prior['source']??[];if(!is_array($s))$s=[];$country=$shaCountry[$r['catalog_sha256']]??null;if(!$country||!isset(FC_COUNTRIES[$country])){$and['ambiguous']++;continue;}$sourceNames=array_values(array_filter([$s['name']??'',$s['lName']??'']));$geo=$prior['geography']??[];$original=array_values(array_unique(array_map('intval',$prior['candidate_ids']??[])));$pool=[];if($original){foreach($original as $x)if(isset($hotels[$x])&&(int)$hotels[$x]['country_id']===$country)$pool[$x]=1;}else{foreach([$s['town']??'',$geo['town']??'',$geo['parent']??''] as $place){$place=fc_norm($place);foreach(array_keys($places[$country][$place]??[]) as $x)$pool[(int)$x]=1;}}
            $candidateMeta=[];foreach(array_keys($pool) as $x){$h=$hotels[$x];$place=fc_place([$s['town']??'',$geo['town']??'',$geo['parent']??''],[$h['region_name'],$h['subregion_name']]);if($place)$candidateMeta[$x]=[null,true];}[$best,$second]=fd_best(array_keys($candidateMeta),$sourceNames,$names,$candidateMeta);$target=null;$rule=null;if($best[2]!==null&&$best[0]>=0.82&&$best[1]>=2&&$best[0]-$second>=0.15){$sourceCat=fc_category($s);$targetCat=$hotels[$best[2]]['category']===null?null:(int)$hotels[$best[2]]['category'];if($sourceCat&&$targetCat&&$sourceCat!==$targetCat){$and['category_conflict']++;}else{$target=$best[2];$rule='fuzzy_saved_geo_margin';}}
            if($target===null){$scores=[];foreach($sourceNames as $name)foreach($anexBridge[$country]??[] as $key=>$ids){[$score,$shared]=fd_similarity($name,$key);if($score>=0.90&&$shared>=2)foreach(array_keys($ids) as $x)$scores[(int)$x]=max($scores[(int)$x]??0,$score);}if($scores){arsort($scores);$ids=array_keys($scores);$top=$scores[$ids[0]];$runner=$scores[$ids[1]]??0;if($top-$runner>=0.10){$x=(int)$ids[0];$place=isset($hotels[$x])&&fc_place([$s['town']??'',$geo['town']??'',$geo['parent']??''],[$hotels[$x]['region_name'],$hotels[$x]['subregion_name']]);$sourceCat=fc_category($s);$targetCat=isset($hotels[$x])&&$hotels[$x]['category']!==null?(int)$hotels[$x]['category']:null;if($place&&!($sourceCat&&$targetCat&&$sourceCat!==$targetCat)&&(!$original||in_array($x,$original,true))){$target=$x;$rule='fuzzy_accepted_anex_bridge';}}}}
            if($target===null){$and['ambiguous']++;continue;}if($original&&$rule!=='fuzzy_accepted_anex_bridge'&&!in_array($target,$original,true)){$and['candidate_conflict']++;continue;}$promotion=['operation_id'=>$operation,'source'=>'post_core8_delta','rule'=>$rule,'country_id'=>$country,'target'=>$target];$ev=['prior_evidence'=>$prior,'promotion'=>$promotion];$json=fc_json($ev);$hash=hash('sha256',$json);$update->execute([$target,$hash,$json,(string)$r['external_hotel_id'],$r['evidence_sha256']]);if($update->rowCount()!==1)throw new RuntimeException('andromeda_concurrent_change');$andRows[(string)$r['external_hotel_id']]=[$target,$hash];$and['accepted']++;if($rule==='fuzzy_saved_geo_margin')$and['fuzzy_saved_geo']++;else$and['fuzzy_anex_bridge']++;$writes++;}
        $db->commit();$committed=true;
        $q=$db->prepare("SELECT catalog_hotel_id,source_row_digest,enabled FROM anex_hotel_search_mappings WHERE anex_hotel_id=? AND scope='preview' AND approval_policy=?");foreach($anRows as $id=>$expected){$q->execute([$id,FC_POLICY]);$v=$q->fetch(PDO::FETCH_ASSOC);if(!$v||(int)$v['catalog_hotel_id']!==$expected[0]||$v['source_row_digest']!==$expected[1]||(int)$v['enabled']!==1)throw new RuntimeException('anex_readback');}
        $q=$db->prepare("SELECT local_hotel_id,decision_status,evidence_sha256 FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=?");foreach($andRows as $id=>$expected){$q->execute([$id]);$v=$q->fetch(PDO::FETCH_ASSOC);if(!$v||(int)$v['local_hotel_id']!==$expected[0]||$v['decision_status']!=='accepted'||$v['evidence_sha256']!==$expected[1])throw new RuntimeException('andromeda_readback');}
        return ['status'=>'completed','operation_id'=>$operation,'catalog_scope'=>$scope,'anex_staging'=>$anex,'anex_observed_no_staging'=>$observed,'andromeda'=>$and,'accepted_total'=>$anex['accepted']+$observed['accepted']+$and['accepted'],'database_writes'=>$writes,'readback_verified'=>true,'supplier_calls'=>0,'before'=>$before,'after'=>fc_coverage($db)];
    }catch(Throwable $e){if(!$committed&&$db->inTransaction())$db->rollBack();return ['status'=>$committed?'committed_readback_failed':'failed_rolled_back','operation_id'=>$operation,'database_writes'=>$committed?$writes:0,'readback_verified'=>false,'supplier_calls'=>0,'reason'=>in_array($e->getMessage(),['required_transactional_table_missing','country_contract_changed','hotel_scope_limit','alias_scope_limit','andromeda_concurrent_change'],true)?$e->getMessage():'runtime_failure'];}
}
function fd_main(): array {
    $raw=file_get_contents('php://stdin',false,null,0,4097);$req=json_decode((string)$raw,true,16,JSON_THROW_ON_ERROR);if(($req['operation_id']??'')!==FD_OPERATION||!in_array($req['phase']??'',['apply','receipt'],true))throw new RuntimeException('request_scope');$root=realpath(getcwd());if(!$root||basename($root)!=='anytoour.ru')throw new RuntimeException('root');$config=require $root.'/_preview/search3-anex-candidate/.andromeda-private.php';$private=realpath(dirname($config['catalog_path']));if(!$private||strpos($private,$root.DIRECTORY_SEPARATOR)===0)throw new RuntimeException('private_state');$dir=$private.'/'.FD_OPERATION;if($req['phase']==='receipt'){if(is_file($dir.'/result.json'))return json_decode((string)file_get_contents($dir.'/result.json'),true,64,JSON_THROW_ON_ERROR);return ['status'=>is_file($dir.'/reservation.json')?'reserved_or_unknown':'not_started','operation_id'=>FD_OPERATION,'supplier_calls'=>0];}if(is_dir($dir)||!mkdir($dir,0700))throw new RuntimeException('operation_already_reserved');fc_write_once($dir.'/reservation.json',['operation_id'=>FD_OPERATION,'state'=>'reserved_before_database','scope'=>FC_COUNTRIES,'supplier_calls'=>0]);$helper=realpath($root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php'));if(!$helper||strpos($helper,$root.DIRECTORY_SEPARATOR)!==0)throw new RuntimeException('db_helper');require_once $helper;$db=v2_data_db();$result=fd_reconcile($db,FD_OPERATION);fc_write_once($dir.'/result.json',$result);return $result;
}
if(!defined('FD_LIBRARY_ONLY')){error_reporting(0);ob_start();try{$out=fd_main();}catch(Throwable $e){$out=['status'=>'failed','operation_id'=>FD_OPERATION,'reason'=>in_array($e->getMessage(),['operation_already_reserved'],true)?$e->getMessage():'runtime_failure','supplier_calls'=>0];}while(ob_get_level())ob_end_clean();echo fc_json($out),"\n";exit(in_array($out['status']??'', ['completed','empty'],true)?0:1);}
