<?php
declare(strict_types=1);
if (!defined('FC_LIBRARY_ONLY')) define('FC_LIBRARY_ONLY', true);
require_once __DIR__ . '/hotel_match_residual_ensemble_review.php';
require_once __DIR__ . '/hotel_match_anex_direct_details_coordinate_accept.php';

const HMREA_OPERATION = 'hotel-match-residual-ensemble-accept-1971-20260911-v1';
const HMREA_SOURCE_OPERATION = 'hotel-match-residual-ensemble-review-1971-20260911-v1';
const HMREA_SOURCE_RESULT_SHA256 = '94e4416d5e27d4454828288118beb2b89f52cdfcb570846b2cfed749132aec74';
const HMREA_MAX_WRITES = 100;

function hmrea_require_transactional(PDO $db): void {
    $tables=['catalog_hotels','catalog_hotel_details','hotel_aliases','anex_hotel_search_mappings','anex_hotel_decisions','anex_review_pair_exclusions','anex_hotels','anex_search_hotel_observations','andromeda_hotel_identities','andromeda_search_hotel_observations'];
    $q=$db->prepare("SELECT ENGINE FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?");
    foreach($tables as $table){$q->execute([$table]);$engine=$q->fetchColumn();if($engine===false)throw new RuntimeException('required_table_missing:'.$table);if(strcasecmp((string)$engine,'InnoDB')!==0)throw new RuntimeException('required_table_not_innodb:'.$table);}
}
function hmrea_identity_counts(PDO $db): array {
    $out=['accepted'=>0,'pending'=>0,'conflict'=>0];foreach($db->query("SELECT decision_status,COUNT(*) n FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' GROUP BY decision_status")->fetchAll(PDO::FETCH_ASSOC) as $r){$s=(string)$r['decision_status'];if(isset($out[$s]))$out[$s]=(int)$r['n'];}return $out;
}
function hmrea_source_rows(array $mass): array {
    if(($mass['status']??null)!=='completed'||($mass['operation_id']??null)!==HMREA_SOURCE_OPERATION||($mass['database_writes']??null)!==0||($mass['mapping_writes']??null)!==0||($mass['supplier_calls']??null)!==0||($mass['historical_operations_replayed']??null)!==false||!is_array($mass['buckets']['auto_accept']??null)||(int)($mass['counts']['auto_accept']??-1)!==40||(int)($mass['counts']['auto_anex']??-1)!==37||(int)($mass['counts']['auto_andromeda']??-1)!==3)throw new RuntimeException('mass_source_invalid');
    $rows=[];foreach($mass['buckets']['auto_accept'] as $row){$provider=(string)($row['provider']??'');$external=(string)($row['external_id']??'');$target=(int)($row['target_local_hotel_id']??0);$sources=$row['evidence_sources']??null;if(!in_array($provider,['anex','andromeda'],true)||$external===''||$target<1||!is_array($sources)||!$sources)throw new RuntimeException('mass_source_row_invalid');$key=hmre_key($provider,$external);if(isset($rows[$key]))throw new RuntimeException('mass_source_duplicate');$rows[$key]=$row;}if(count($rows)!==40)throw new RuntimeException('mass_source_count_invalid');return $rows;
}
function hmrea_latin(string $v): string {
    $v=mb_strtolower($v,'UTF-8');return strtr($v,['щ'=>'shch','ш'=>'sh','ч'=>'ch','ц'=>'ts','ю'=>'yu','я'=>'ya','ё'=>'e','ж'=>'zh','х'=>'kh','а'=>'a','б'=>'b','в'=>'v','г'=>'g','д'=>'d','е'=>'e','з'=>'z','и'=>'i','й'=>'y','к'=>'k','л'=>'l','м'=>'m','н'=>'n','о'=>'o','п'=>'p','р'=>'r','с'=>'s','т'=>'t','у'=>'u','ф'=>'f','ы'=>'y','э'=>'e','ь'=>'','ъ'=>'','ї'=>'yi','і'=>'i','є'=>'ye','ґ'=>'g']);
}
function hmrea_place_tokens(array $row): array {
    $out=[];foreach(['source_region','source_town','target_region','target_subregion'] as $key){$v=(string)($row[$key]??'');foreach([$v,hmrea_latin($v)] as $x)foreach(hmasr_tokens($x) as $token)$out[$token]=true;}return $out;
}
function hmrea_identity_anchor(array $name,array $row): bool {
    $shared=array_values(array_intersect($name['source_tokens']??[],$name['target_tokens']??[]));if(count($shared)<1)return false;$places=hmrea_place_tokens($row);$weak=array_fill_keys(['beach','aqua','aquapark','park','club','garden','gardens','palace','royal','grand','family','city','view','blue','sun','sea','holiday','elite','adults','adult','only','apart','aparts','suite','suites','wellness'],true);foreach($shared as $token){$latin=fc_norm(hmrea_latin((string)$token));if(isset($places[$token])||($latin!==''&&isset($places[$latin]))||isset($weak[$token])||($latin!==''&&isset($weak[$latin])))continue;return true;}return false;
}
function hmrea_coordinate_revalidate(array $source,int $expectedTarget,array $hotels,array $names,array $countryHotels,array $tokenFrequency,array $andromedaLocal,array $excluded,array $claimed): array {
    $aid=(int)($source['anex_hotel_id']??0);$country=(int)($source['country_id']??0);$slat=hmasr_coord($source['source_latitude']??null);$slon=hmasr_coord($source['source_longitude']??null);if($aid<1||!isset(HMASR_CORE8[$country])||$slat===null||$slon===null)return ['ok'=>false,'reason'=>'coordinate_source_invalid'];
    $detail=['name'=>(string)($source['source_name']??''),'region'=>(string)($source['source_region']??''),'town'=>(string)($source['source_town']??''),'latitude'=>$slat,'longitude'=>$slon];$near=[];
    foreach($countryHotels[$country]??[] as $hid){$h=$hotels[$hid];$tlat=hmasr_coord($h['latitude']??null);$tlon=hmasr_coord($h['longitude']??null);if($tlat===null||$tlon===null)continue;$d=fc_dist($slat,$slon,$tlat,$tlon);if($d!==null&&(float)$d<=HMADDCR_PHYSICAL_SCAN_M)$near[(int)$hid]=(float)$d;}
    $cluster=count(array_filter($near,static fn($d)=>(float)$d<=HMADDCR_ONE_TOKEN_CLUSTER_M));$safe=[];
    foreach($near as $hid=>$distance){$hid=(int)$hid;if(isset($excluded[$hid]))continue;if(array_filter(array_keys($claimed[$hid]??[]),static fn($x)=>(int)$x!==$aid))continue;$c=hmaddcr_candidate($detail,$hotels[$hid],$names[$hid]??[(string)$hotels[$hid]['name']],isset($andromedaLocal[$hid]),$tokenFrequency[$country]??[],$cluster);if($c===null||($c['blocked']??null)!==null)continue;$c+=['target_local_hotel_id'=>$hid,'target_name'=>$hotels[$hid]['name'],'target_region'=>$hotels[$hid]['region_name'],'target_subregion'=>$hotels[$hid]['subregion_name']];$safe[]=$c;}
    if(count($safe)!==1)return ['ok'=>false,'reason'=>count($safe)>1?'coordinate_ambiguous':'coordinate_no_safe_target'];$best=$safe[0];if((int)$best['target_local_hotel_id']!==$expectedTarget)return ['ok'=>false,'reason'=>'coordinate_target_changed'];if((string)$best['route']!==(string)($source['rule']??''))return ['ok'=>false,'reason'=>'coordinate_route_changed'];
    $identityRow=['source_region'=>$detail['region'],'source_town'=>$detail['town'],'target_region'=>$best['target_region'],'target_subregion'=>$best['target_subregion']];if($best['route']==='two_token_direct_coordinate'&&!hmrea_identity_anchor($best['name'],$identityRow))return ['ok'=>false,'reason'=>'coordinate_identity_anchor_block'];
    return ['ok'=>true,'reason'=>'coordinate_current_verified','evidence'=>['route'=>$best['route'],'distance_m'=>$best['distance_m'],'name'=>$best['name'],'place_match'=>$best['place_match'],'andromeda_bridge'=>$best['andromeda_bridge'],'physical_near_count'=>$best['physical_near_count']]];
}
function hmrea_sold_rows(array $sold): array {
    if(($sold['status']??null)!=='completed'||($sold['operation_id']??null)!==HMRE_SOLD_OPERATION||($sold['database_writes']??null)!==0||!is_array($sold['prepared']??null)||count($sold['prepared'])!==3)throw new RuntimeException('sold_source_invalid');$out=[];foreach($sold['prepared'] as $r){$id=(int)($r['anex_hotel_id']??0);if($id<1||isset($out[$id]))throw new RuntimeException('sold_source_rows_invalid');$out[$id]=$r;}return $out;
}
function hmrea_sold_revalidate(int $aid,int $expectedTarget,array $soldRow,array $directSources,array $hotels,array $names): array {
    if((int)($soldRow['target_local_hotel_id']??0)!==$expectedTarget||(int)($soldRow['matched_sold_date_count']??0)<1)return ['ok'=>false,'reason'=>'sold_source_target_changed'];$src=$directSources[$aid]??null;if(!is_array($src)||!is_array($src['detail']??null))return ['ok'=>false,'reason'=>'sold_direct_detail_missing'];$d=$src['detail'];$country=(int)($src['context']['country_id']??0);if(!isset($hotels[$expectedTarget])||(int)$hotels[$expectedTarget]['country_id']!==$country)return ['ok'=>false,'reason'=>'sold_country_target_changed'];$target=$hotels[$expectedTarget];$sourceName=trim((string)($d['name']??''));if($sourceName==='')return ['ok'=>false,'reason'=>'sold_name_missing'];$name=hmasr_best_name(hmasr_variants($sourceName),$names[$expectedTarget]??[(string)$target['name']]);if(!($name['critical_ok']??false)||(int)($name['shared']??0)<2)return ['ok'=>false,'reason'=>'sold_identity_weak'];$row=['source_region'=>(string)($d['region']??''),'source_town'=>(string)($d['town']??''),'target_region'=>(string)($target['region_name']??''),'target_subregion'=>(string)($target['subregion_name']??'')];if(!hmrea_identity_anchor($name,$row))return ['ok'=>false,'reason'=>'sold_identity_anchor_block'];$slat=hmasr_coord($d['latitude']??null);$slon=hmasr_coord($d['longitude']??null);$tlat=hmasr_coord($target['latitude']??null);$tlon=hmasr_coord($target['longitude']??null);if($slat===null||$slon===null||$tlat===null||$tlon===null)return ['ok'=>false,'reason'=>'sold_coordinates_missing'];$distance=fc_dist($slat,$slon,$tlat,$tlon);if($distance===null||(float)$distance>250.0)return ['ok'=>false,'reason'=>'sold_coordinate_guard'];$place=fc_place([(string)($d['region']??''),(string)($d['town']??'')],[(string)($target['region_name']??''),(string)($target['subregion_name']??'')]);if(!$place&&(float)$distance>100.0)return ['ok'=>false,'reason'=>'sold_geo_guard'];return ['ok'=>true,'reason'=>'same_sold_date_current_verified','evidence'=>['matched_sold_dates'=>$soldRow['matched_sold_dates']??[],'distance_m'=>round((float)$distance,2),'place_match'=>$place,'name'=>$name,'andromeda_bridge'=>(bool)($soldRow['andromeda_bridge']??false)]];
}
function hmrea_strict_revalidate(string $provider,string $external,int $expectedTarget,array $ctx): array {
    if($provider==='anex'){
        $aid=(int)$external;$o=$ctx['anex_obs'][$aid]??null;$s=$ctx['staging'][$aid]??[];$country=(int)($o['country_id']??0);if(!isset(MBR_CORE8[$country]))$country=(int)(fc_country($s['api_country']??'')??0);if(!isset(MBR_CORE8[$country]))return ['ok'=>false,'reason'=>'strict_country_unknown'];$source=['observed'=>$o!==null,'search_count'=>(int)($o['search_count']??0),'last_seen_utc'=>$o['last_seen_utc']??null,'names'=>[(string)($o['hotel_name']??''),(string)($s['api_name']??''),(string)($s['xml_name']??''),(string)($s['xml_alternate_name']??'')],'places'=>[(string)($s['api_region']??''),(string)($s['api_town']??'')],'latitude'=>$s['latitude']??null,'longitude'=>$s['longitude']??null];$row=mbr_review_anex($source,$aid,$country,$ctx['hotels'],$ctx['names'],$ctx['strict'],$ctx['broad'],$ctx['places']);if(msr_safe_auto($row)&&hmre_target_id($row)===$expectedTarget)return ['ok'=>true,'reason'=>'strict_current_verified','evidence'=>$row];$bridge=msr_reverse_anex_bridge($row,$source,$ctx['andromeda_bridge_index'],$ctx['hotels']);if($bridge!==null&&msr_safe_auto($bridge)&&hmre_target_id($bridge)===$expectedTarget)return ['ok'=>true,'reason'=>'strict_reverse_bridge_verified','evidence'=>$bridge];return ['ok'=>false,'reason'=>'strict_current_changed'];
    }
    if($provider==='andromeda'){
        $r=$ctx['and_pending'][$external]??null;if(!is_array($r))return ['ok'=>false,'reason'=>'strict_andromeda_not_pending'];$obs=$ctx['and_obs'][$external]??null;$country=(int)($obs['country_id']??0);if(!isset(MBR_CORE8[$country]))$country=(int)($ctx['sha_country'][$r['catalog_sha256']]??0);if(!isset(MBR_CORE8[$country]))return ['ok'=>false,'reason'=>'strict_country_unknown'];$row=mbr_review_andromeda($r,$obs,$country,$ctx['hotels'],$ctx['names'],$ctx['strict'],$ctx['places']);if(msr_safe_auto($row)&&hmre_target_id($row)===$expectedTarget)return ['ok'=>true,'reason'=>'strict_current_verified','evidence'=>$row];$prior=fc_evidence($r['evidence_json']??'');$coordSource=$prior['source']??[];if(!is_array($coordSource))$coordSource=[];if($obs)$coordSource+=$obs;$bridge=msr_cross_provider_bridge($row,$coordSource,$ctx['anex_bridge_index'],$ctx['hotels']);if($bridge!==null&&msr_safe_auto($bridge)&&hmre_target_id($bridge)===$expectedTarget)return ['ok'=>true,'reason'=>'strict_cross_provider_bridge_verified','evidence'=>$bridge];return ['ok'=>false,'reason'=>'strict_current_changed'];
    }
    return ['ok'=>false,'reason'=>'strict_provider_invalid'];
}
function hmrea_accept(PDO $db,array $mass,array $coord,array $sold,array $direct,array $directPlan,string $operation=HMREA_OPERATION,int $maxWrites=HMREA_MAX_WRITES): array {
    if($operation!==HMREA_OPERATION)throw new RuntimeException('operation_scope');if($maxWrites<1||$maxWrites>HMREA_MAX_WRITES)throw new RuntimeException('write_scope_limit_config');$allowed=hmrea_source_rows($mass);$coordRows=hmaddca_source_rows($coord);$soldRows=hmrea_sold_rows($sold);$directSources=hmasr_source_payload($direct,$directPlan);$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);hmrea_require_transactional($db);$db->exec('SET SESSION innodb_lock_wait_timeout=20');$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$beforeCoverage=fc_coverage($db);$beforeIdentity=hmrea_identity_counts($db);$writtenAn=[];$writtenAnd=[];$stats=['source_allowed'=>count($allowed),'protected'=>0,'not_pending'=>0,'country_other'=>0,'inactive_target'=>0,'pair_excluded'=>0,'target_already_claimed'=>0,'coordinate_guard'=>0,'coordinate_identity_anchor_block'=>0,'sold_guard'=>0,'strict_guard'=>0,'unknown_source'=>0,'target_collision'=>0,'planned'=>0,'planned_anex'=>0,'planned_andromeda'=>0,'written'=>0,'written_anex'=>0,'written_andromeda'=>0,'live_written'=>0];$skipReasons=[];
    try{
        $db->beginTransaction();
        $manual=array_fill_keys(array_map('intval',$db->query('SELECT anex_hotel_id FROM anex_hotel_decisions ORDER BY anex_hotel_id FOR UPDATE')->fetchAll(PDO::FETCH_COLUMN)),true);$existing=[];$anexClaimed=[];foreach($db->query('SELECT anex_hotel_id,catalog_hotel_id FROM anex_hotel_search_mappings WHERE enabled=1 ORDER BY anex_hotel_id FOR UPDATE')->fetchAll(PDO::FETCH_ASSOC) as $r){$aid=(int)$r['anex_hotel_id'];$hid=(int)$r['catalog_hotel_id'];$existing[$aid]=true;$anexClaimed[$hid][$aid]=true;}foreach($db->query("SELECT anex_hotel_id,catalog_hotel_id,decision_status FROM anex_hotel_decisions WHERE catalog_hotel_id IS NOT NULL ORDER BY anex_hotel_id FOR UPDATE")->fetchAll(PDO::FETCH_ASSOC) as $r)if((string)$r['decision_status']==='accepted')$anexClaimed[(int)$r['catalog_hotel_id']][(int)$r['anex_hotel_id']]=true;$excluded=[];foreach($db->query('SELECT anex_hotel_id,catalog_hotel_id FROM anex_review_pair_exclusions ORDER BY anex_hotel_id,catalog_hotel_id FOR UPDATE')->fetchAll(PDO::FETCH_ASSOC) as $r)$excluded[(int)$r['anex_hotel_id']][(int)$r['catalog_hotel_id']]=true;
        $andPending=[];$andClaimed=[];foreach($db->query("SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' ORDER BY external_hotel_id FOR UPDATE")->fetchAll(PDO::FETCH_ASSOC) as $r){$external=(string)$r['external_hotel_id'];if((string)$r['decision_status']==='pending'&&$r['local_hotel_id']===null)$andPending[$external]=$r;if((string)$r['decision_status']==='accepted'&&$r['local_hotel_id']!==null)$andClaimed[(int)$r['local_hotel_id']][$external]=true;}
        $hotels=[];$rawNames=[];$countryHotels=[];$tokenSets=[];foreach($db->query('SELECT h.id,h.country_id,h.name,h.region_name,h.subregion_name,h.category,COALESCE(d.latitude,h.latitude) latitude,COALESCE(d.longitude,h.longitude) longitude FROM catalog_hotels h LEFT JOIN catalog_hotel_details d ON d.hotel_id=h.id WHERE h.is_active=1 AND h.country_id IN (1,2,4,8,9,10,12,16) ORDER BY h.country_id,h.id FOR UPDATE')->fetchAll(PDO::FETCH_ASSOC) as $h){$hid=(int)$h['id'];$country=(int)$h['country_id'];$hotels[$hid]=$h;$rawNames[$hid]=[(string)$h['name']];$countryHotels[$country][]=$hid;}foreach($db->query('SELECT a.hotel_id,a.alias,a.normalized_alias,h.country_id FROM hotel_aliases a JOIN catalog_hotels h ON h.id=a.hotel_id WHERE h.is_active=1 AND h.country_id IN (1,2,4,8,9,10,12,16) ORDER BY h.country_id,a.hotel_id,a.id FOR UPDATE')->fetchAll(PDO::FETCH_ASSOC) as $a){$hid=(int)$a['hotel_id'];foreach([(string)$a['alias'],(string)$a['normalized_alias']] as $alias)if(trim($alias)!=='')$rawNames[$hid][]=$alias;}$names=[];foreach($hotels as $hid=>$h){$country=(int)$h['country_id'];$names[$hid]=hmaddcr_target_names((string)$h['name'],$rawNames[$hid]??[]);foreach($names[$hid] as $name)foreach(hmasr_tokens($name) as $token)$tokenSets[$country][$token][$hid]=true;}$tokenFrequency=[];foreach($tokenSets as $country=>$tokens)foreach($tokens as $token=>$ids)$tokenFrequency[$country][$token]=count($ids);
        [$catalogHotels,$catalogNames,$strict,$broad,$places,$catalogScope]=mbr_catalog($db);$shaCountry=fc_sha_countries($db);[$anexLocal,$andromedaLocal]=mbr_local_sets($db);$anexBridgeIndex=msr_bridge_index($anexLocal,$catalogHotels,$catalogNames);$andromedaBridgeIndex=msr_bridge_index($andromedaLocal,$catalogHotels,$catalogNames);
        $staging=[];foreach($db->query('SELECT * FROM anex_hotels ORDER BY anex_hotel_id')->fetchAll(PDO::FETCH_ASSOC) as $r)$staging[(int)$r['anex_hotel_id']]=$r;$anObs=[];foreach($db->query('SELECT * FROM anex_search_hotel_observations ORDER BY search_count DESC,last_seen_utc DESC,anex_hotel_id')->fetchAll(PDO::FETCH_ASSOC) as $r){$id=(int)$r['anex_hotel_id'];if(!isset($anObs[$id]))$anObs[$id]=$r;}$andObs=[];foreach($db->query("SELECT * FROM andromeda_search_hotel_observations WHERE supplier_namespace='andromeda_catalog' ORDER BY observed_at_utc DESC,external_hotel_id")->fetchAll(PDO::FETCH_ASSOC) as $r){$id=(string)$r['external_hotel_id'];if(!isset($andObs[$id]))$andObs[$id]=$r;}
        $ctx=['hotels'=>$catalogHotels,'names'=>$catalogNames,'strict'=>$strict,'broad'=>$broad,'places'=>$places,'sha_country'=>$shaCountry,'anex_bridge_index'=>$anexBridgeIndex,'andromeda_bridge_index'=>$andromedaBridgeIndex,'staging'=>$staging,'anex_obs'=>$anObs,'and_obs'=>$andObs,'and_pending'=>$andPending];$planned=[];
        foreach($allowed as $key=>$src){$provider=(string)$src['provider'];$external=(string)$src['external_id'];$target=(int)$src['target_local_hotel_id'];$country=(int)$src['country_id'];$fail=null;if(!isset($hotels[$target])){$fail='inactive_target';$stats['inactive_target']++;}elseif((int)$hotels[$target]['country_id']!==$country){$fail='country_other';$stats['country_other']++;}elseif($provider==='anex'){ $aid=(int)$external;if(isset($manual[$aid])||isset($existing[$aid])){$fail='protected';$stats['protected']++;}elseif(isset($excluded[$aid][$target])){$fail='pair_excluded';$stats['pair_excluded']++;}elseif(array_filter(array_keys($anexClaimed[$target]??[]),static fn($x)=>(int)$x!==$aid)){$fail='target_already_claimed';$stats['target_already_claimed']++;}}
            elseif($provider==='andromeda'){if(!isset($andPending[$external])){$fail='not_pending';$stats['not_pending']++;}elseif(array_filter(array_keys($andClaimed[$target]??[]),static fn($x)=>(string)$x!==$external)){$fail='target_already_claimed';$stats['target_already_claimed']++;}}else{$fail='unknown_source';$stats['unknown_source']++;}
            $verified=[];if($fail===null){foreach($src['evidence_sources'] as $evSource){if($evSource==='direct_details_coordinate'){if($provider!=='anex'||!isset($coordRows[(int)$external])){$r=['ok'=>false,'reason'=>'coordinate_source_missing'];}else{$r=hmrea_coordinate_revalidate($coordRows[(int)$external],$target,$hotels,$names,$countryHotels,$tokenFrequency,$andromedaLocal,$excluded[(int)$external]??[],$anexClaimed);}if(!($r['ok']??false)){$fail=(string)$r['reason'];$stats['coordinate_guard']++;if($fail==='coordinate_identity_anchor_block')$stats['coordinate_identity_anchor_block']++;break;}$verified[$evSource]=$r['evidence'];}
                    elseif($evSource==='same_sold_date_tourvisor'){if($provider!=='anex'||!isset($soldRows[(int)$external])){$r=['ok'=>false,'reason'=>'sold_source_missing'];}else{$r=hmrea_sold_revalidate((int)$external,$target,$soldRows[(int)$external],$directSources,$hotels,$names);}if(!($r['ok']??false)){$fail=(string)$r['reason'];$stats['sold_guard']++;break;}$verified[$evSource]=$r['evidence'];}
                    elseif($evSource==='current_strict'){$r=hmrea_strict_revalidate($provider,$external,$target,$ctx);if(!($r['ok']??false)){$fail=(string)$r['reason'];$stats['strict_guard']++;break;}$verified[$evSource]=['reason'=>$r['reason'],'rule'=>$r['evidence']['reason']??$r['evidence']['candidate_class']??null];}
                    else{$fail='unknown_evidence_source';$stats['unknown_source']++;break;}}}
            if($fail!==null){$skipReasons[$fail]=($skipReasons[$fail]??0)+1;continue;}$planned[$key]=['provider'=>$provider,'external_id'=>$external,'country_id'=>$country,'target'=>$target,'target_name'=>$hotels[$target]['name'],'live'=>(bool)($src['live']??false),'observation_count'=>(int)($src['observation_count']??0),'last_seen_utc'=>$src['last_seen_utc']??null,'evidence_sources'=>$src['evidence_sources'],'verified'=>$verified,'prior_mass_reason'=>$src['reason']??null];}
        $targets=[];foreach($planned as $key=>$row)$targets[$row['provider'].':'.$row['target']][]=$key;foreach($targets as $keys)if(count($keys)>1){$stats['target_collision']+=count($keys);throw new RuntimeException('same_provider_target_collision');}$stats['planned']=count($planned);$stats['planned_anex']=count(array_filter($planned,static fn($r)=>$r['provider']==='anex'));$stats['planned_andromeda']=count($planned)-$stats['planned_anex'];if($stats['planned']>$maxWrites)throw new RuntimeException('write_scope_limit');
        $insertAn=$db->prepare("INSERT INTO anex_hotel_search_mappings (anex_hotel_id,catalog_hotel_id,match_class,scope,approval_policy,source_row_digest,mapping_digest,enabled) VALUES(?,?,'strong_candidate','preview',?,?,?,1)");$mappingDigest=fc_hash([$operation,'residual_ensemble_current_revalidated_v1']);$updateAnd=$db->prepare("UPDATE andromeda_hotel_identities SET local_hotel_id=?,decision_status='accepted',evidence_sha256=?,evidence_json=? WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=? AND decision_status='pending' AND local_hotel_id IS NULL AND evidence_sha256 <=> ?");
        foreach($planned as $key=>$row){$provider=$row['provider'];$external=$row['external_id'];$target=(int)$row['target'];$evidence=['operation_id'=>$operation,'lane'=>'MATCH','provider'=>$provider,'external_id'=>$external,'country_id'=>$row['country_id'],'target'=>$target,'target_name'=>$row['target_name'],'evidence_sources'=>$row['evidence_sources'],'revalidated'=>$row['verified'],'observation_count'=>$row['observation_count'],'last_seen_utc'=>$row['last_seen_utc'],'source_operation'=>HMREA_SOURCE_OPERATION,'source_result_sha256'=>HMREA_SOURCE_RESULT_SHA256,'server_current'=>true];if($provider==='anex'){$aid=(int)$external;$digest=fc_hash($evidence);$insertAn->execute([$aid,$target,MBR_POLICY,$digest,$mappingDigest]);if($insertAn->rowCount()!==1)throw new RuntimeException('anex_insert_not_one:'.$aid);$writtenAn[$aid]=['target'=>$target,'source_row_digest'=>$digest,'mapping_digest'=>$mappingDigest,'live'=>$row['live'],'sources'=>$row['evidence_sources']];$existing[$aid]=true;$anexClaimed[$target][$aid]=true;$stats['written_anex']++;}else{$cur=$andPending[$external]??null;if(!$cur)throw new RuntimeException('andromeda_pending_missing:'.$external);$prior=fc_evidence($cur['evidence_json']??'');$payload=['prior_evidence'=>$prior,'promotion'=>$evidence];$json=fc_json($payload);$sha=hash('sha256',$json);$old=$cur['evidence_sha256'];$updateAnd->execute([$target,$sha,$json,$external,$old]);if($updateAnd->rowCount()!==1)throw new RuntimeException('andromeda_concurrency_guard_failed:'.$external);$writtenAnd[$external]=['target'=>$target,'evidence_sha256'=>$sha,'live'=>$row['live'],'sources'=>$row['evidence_sources']];$andClaimed[$target][$external]=true;$stats['written_andromeda']++;}if($row['live'])$stats['live_written']++;}
        $stats['written']=$stats['written_anex']+$stats['written_andromeda'];if($stats['written']>$maxWrites)throw new RuntimeException('write_scope_limit');$db->commit();
    }catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
    $readAn=$db->prepare('SELECT catalog_hotel_id,source_row_digest,mapping_digest,enabled,scope,approval_policy FROM anex_hotel_search_mappings WHERE anex_hotel_id=?');foreach($writtenAn as $aid=>$expected){$readAn->execute([(int)$aid]);$actual=$readAn->fetch(PDO::FETCH_ASSOC);if(!$actual||(int)$actual['catalog_hotel_id']!==$expected['target']||(int)$actual['enabled']!==1||$actual['scope']!=='preview'||$actual['approval_policy']!==MBR_POLICY||!hash_equals($expected['source_row_digest'],(string)$actual['source_row_digest'])||!hash_equals($expected['mapping_digest'],(string)$actual['mapping_digest']))throw new RuntimeException('anex_post_commit_readback_failed:'.$aid);$writtenAn[$aid]['readback']='verified';}
    $readAnd=$db->prepare("SELECT local_hotel_id,decision_status,evidence_sha256 FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=?");foreach($writtenAnd as $external=>$expected){$readAnd->execute([(string)$external]);$actual=$readAnd->fetch(PDO::FETCH_ASSOC);if(!$actual||(int)$actual['local_hotel_id']!==$expected['target']||$actual['decision_status']!=='accepted'||!hash_equals($expected['evidence_sha256'],(string)$actual['evidence_sha256']))throw new RuntimeException('andromeda_post_commit_readback_failed:'.$external);$writtenAnd[$external]['readback']='verified';}
    $afterCoverage=fc_coverage($db);$afterIdentity=hmrea_identity_counts($db);ksort($skipReasons);return ['status'=>'committed_readback_verified','operation_id'=>$operation,'database_writes'=>$stats['written'],'mapping_writes'=>$stats['written'],'supplier_calls'=>0,'historical_operations_replayed'=>false,'source_operation'=>HMREA_SOURCE_OPERATION,'source_result_sha256'=>HMREA_SOURCE_RESULT_SHA256,'stats'=>$stats,'skip_reasons'=>$skipReasons,'anex_rows'=>$writtenAn,'andromeda_rows'=>$writtenAnd,'before'=>['coverage'=>$beforeCoverage,'identity'=>$beforeIdentity],'after'=>['coverage'=>$afterCoverage,'identity'=>$afterIdentity],'post_commit_readback_verified'=>count($writtenAn)+count($writtenAnd)===$stats['written']];
}
