<?php
declare(strict_types=1);
const H6_OP='hotel-match-refresh55-hold6-current-1971-20260920-v1';
const H6_INPUT_SHA='3144fbbfe9a886bb94954d8a12147119172f570285ae7622edf2ffb8ed16657a';
function h6_need(bool $x,string $w):void{if(!$x)throw new RuntimeException($w);}
function h6_write(string $p,array $v):string{$b=json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n";$f=fopen($p,'xb');h6_need(is_resource($f),'open');try{h6_need(fwrite($f,$b)===strlen($b)&&fflush($f),'write');if(function_exists('fsync'))h6_need(fsync($f),'sync');}finally{fclose($f);}return hash('sha256',$b);}
function h6_rows(PDO $db,string $q,array $p=[]):array{$s=$db->prepare($q);$s->execute(array_values($p));return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}
function h6_norm(string $s):string{$s=function_exists('mb_strtoupper')?mb_strtoupper($s,'UTF-8'):strtoupper($s);$s=preg_replace('/[^\pL\pN]+/u',' ',$s)??$s;$parts=preg_split('/\s+/u',trim($s))?:[];$drop=['HOTEL'=>1,'RESORT'=>1,'SPA'=>1,'VILLAS'=>1,'VILLA'=>1,'THE'=>1,'AND'=>1];$parts=array_values(array_filter($parts,fn($x)=>$x!==''&&!isset($drop[$x])));return implode(' ',$parts);}
function h6_place(array $row):string{return h6_norm((string)($row['source_catalog']['hotel']['town']??''));}
function h6_operator_ids(array $row):array{$x=[];foreach((array)($row['operator_proofs']??[])as$p)$x[(int)($p['operator_id']??0)]=true;unset($x[0]);$r=array_keys($x);sort($r,SORT_NUMERIC);return$r;}
if(in_array('--self-test',$argv??[],true)){h6_need(h6_norm('Safaya Luxury Villas')==='SAFAYA LUXURY','norm');h6_need(h6_norm('Amani Boutique Hotel')==='AMANI BOUTIQUE','generic');echo"REFRESH55_HOLD6_SELFTEST_OK\n";exit(0);}
$dir=(string)getenv('MATCH_OPERATION_DIR');$root=realpath((string)getenv('ANYTOUR_ROOT'));$input=realpath((string)getenv('MATCH_INPUT_PATH'));
h6_need(PHP_SAPI==='cli'&&is_dir($dir)&&basename($dir)===H6_OP&&is_string($root)&&is_string($input)&&hash_file('sha256',$input)===H6_INPUT_SHA,'runtime');
$in=json_decode((string)file_get_contents($input),true,128,JSON_THROW_ON_ERROR);h6_need(($in['state']??null)==='completed_read_only'&&($in['state_counts']??[])===['safe_candidate'=>26,'hold'=>6],'input_state');
$holds=array_values(array_filter((array)$in['rows'],fn($r)=>($r['state']??null)==='hold'));h6_need(count($holds)===6,'hold6');
$sources=[];$targets=[];$natives=[];$inputPairs=[];foreach($holds as$r){$sid=(string)$r['samo_hotel_id'];$tv=(int)$r['tv_hotel_id'];$sources[$sid]=true;$targets[$tv]=true;$inputPairs[$sid.'|'.$tv]=$r;foreach((array)$r['operator_proofs']as$op)if(($op['operator']??null)==='anex')foreach((array)$op['native_proofs']as$p){$n=(string)($p['native_token']??'');if(preg_match('/^[1-9][0-9]{0,7}$/D',$n))$natives[$n]=true;}}
h6_need(count($sources)===6&&count($targets)===5&&count($natives)===4,'input_cardinality');
$sp=implode(',',array_fill(0,count($sources),'?'));$tp=implode(',',array_fill(0,count($targets),'?'));$np=implode(',',array_fill(0,count($natives),'?'));
require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION READ ONLY');
$srcCur=h6_rows($db,"SELECT supplier_namespace,external_hotel_id,local_hotel_id,decision_status,catalog_sha256,evidence_sha256 FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id IN ($sp)",array_keys($sources));
$targetOcc=h6_rows($db,"SELECT supplier_namespace,external_hotel_id,local_hotel_id,decision_status,catalog_sha256,evidence_sha256 FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IN ($tp)",array_keys($targets));
$maps=h6_rows($db,"SELECT * FROM anex_hotel_search_mappings WHERE anex_hotel_id IN ($np) OR catalog_hotel_id IN ($tp)",array_merge(array_keys($natives),array_keys($targets)));
$dec=h6_rows($db,"SELECT * FROM anex_hotel_decisions WHERE anex_hotel_id IN ($np) OR catalog_hotel_id IN ($tp)",array_merge(array_keys($natives),array_keys($targets)));
$exc=h6_rows($db,"SELECT * FROM anex_review_pair_exclusions WHERE anex_hotel_id IN ($np) OR catalog_hotel_id IN ($tp)",array_merge(array_keys($natives),array_keys($targets)));
$altIds=$targets;foreach($maps as$m){$id=(int)($m['catalog_hotel_id']??0);if($id>0)$altIds[$id]=true;}$ap=implode(',',array_fill(0,count($altIds),'?'));$hot=h6_rows($db,"SELECT id,name,country_name,region_name,subregion_name,category,is_active FROM catalog_hotels WHERE id IN ($ap)",array_keys($altIds));$db->rollBack();
$srcBy=[];foreach($srcCur as$x)$srcBy[(string)$x['external_hotel_id']][]=$x;$occBy=[];foreach($targetOcc as$x)$occBy[(int)$x['local_hotel_id']][]=$x;$mapBy=[];foreach($maps as$x)$mapBy[(string)$x['anex_hotel_id']][]=$x;$hotBy=[];foreach($hot as$x)$hotBy[(int)$x['id']]=$x;$decBy=[];foreach($dec as$x)$decBy[(string)$x['anex_hotel_id'].'|'.(int)$x['catalog_hotel_id']][]=$x;$excBy=[];foreach($exc as$x)$excBy[(string)$x['anex_hotel_id'].'|'.(int)$x['catalog_hotel_id']][]=$x;
$targetCompetitors=[];foreach($holds as$r)$targetCompetitors[(int)$r['tv_hotel_id']][]=(string)$r['samo_hotel_id'];
$outRows=[];$classes=[];$reviewCandidates=[];foreach($holds as$r){$sid=(string)$r['samo_hotel_id'];$tv=(int)$r['tv_hotel_id'];$ops=h6_operator_ids($r);$srcName=(string)($r['source_catalog']['hotel']['name']??'');$tvName=(string)($r['target']['name']??$r['tv_name']??'');$sn=h6_norm($srcName);$tn=h6_norm($tvName);$nameEqual=$sn===$tn;$nameCompatible=$nameEqual||($sn!==''&&$tn!==''&&(str_contains($sn,$tn)||str_contains($tn,$sn)));$town=h6_place($r);$region=h6_norm((string)($r['target']['region_name']??''));$sub=h6_norm((string)($r['target']['subregion_name']??''));$placeCompatible=$town!==''&&($town===$region||$town===$sub||str_contains($region,$town)||str_contains($sub,$town));$current=$srcBy[$sid]??[];$occupants=array_values(array_filter($occBy[$tv]??[],fn($x)=>(string)$x['external_hotel_id']!==$sid));$nativeFacts=[];$nativeConflicts=[];$manual=[];$excluded=[];foreach((array)$r['operator_proofs']as$op){if(($op['operator']??null)!=='anex')continue;foreach((array)$op['native_proofs']as$p){$n=(string)$p['native_token'];$mm=$mapBy[$n]??[];$mview=[];foreach($mm as$m){$tid=(int)$m['catalog_hotel_id'];$mview[]=['anex_hotel_id'=>(string)$m['anex_hotel_id'],'catalog_hotel_id'=>$tid,'target'=>$hotBy[$tid]??null,'match_class'=>$m['match_class']??null,'approval_policy'=>$m['approval_policy']??null,'scope'=>$m['scope']??null,'enabled'=>(int)($m['enabled']??0),'source'=>$m['source']??null,'source_operation'=>$m['source_operation']??null];}$nativeFacts[$n]=$mview;$exact=array_values(array_filter($mview,fn($m)=>$m['catalog_hotel_id']===$tv&&(int)$m['enabled']===1));$other=array_values(array_filter($mview,fn($m)=>$m['catalog_hotel_id']!==$tv&&(int)$m['enabled']===1));if(count($exact)!==1||$other)$nativeConflicts[$n]=['exact_count'=>count($exact),'other_enabled'=>$other,'all'=>$mview];$k=$n.'|'.$tv;if(isset($decBy[$k]))$manual[$n]=$decBy[$k];if(isset($excBy[$k]))$excluded[$n]=$excBy[$k];}}
 $reasons=(array)$r['hold_reasons'];$class='protected_hold';$candidateReason=null;if($current){foreach($current as$c)if(($c['decision_status']??null)==='accepted'&&(int)($c['local_hotel_id']??0)===$tv){$class='already_accepted';break;}}
 if($class!=='already_accepted'&&!$occupants&&!$manual&&!$excluded){$onlyCategory=$reasons===['category_mismatch'];$onlyAnex=$reasons===['anex_mapping_not_unique_exact'];if($onlyCategory&&count($ops)>=2&&$nameCompatible&&($placeCompatible||$sub!=='')){$class='review_candidate';$candidateReason='dual_operator_exact_name_category_only';}elseif($onlyAnex&&count($ops)>=2&&$nameCompatible){$class='review_candidate';$candidateReason='dual_operator_exact_name_with_aux_anex_mapping_conflict';}}
 $classes[$class]=($classes[$class]??0)+1;$row=['samo_hotel_id'=>$sid,'tv_hotel_id'=>$tv,'source_name'=>$srcName,'target_name'=>$tvName,'operator_ids'=>$ops,'name_key_equal'=>$nameEqual,'name_key_compatible'=>$nameCompatible,'source_town'=>$r['source_catalog']['hotel']['town']??null,'target_region'=>$r['target']['region_name']??null,'target_subregion'=>$r['target']['subregion_name']??null,'place_compatible'=>$placeCompatible,'input_hold_reasons'=>$reasons,'current_source_rows'=>$current,'current_target_occupants'=>$occupants,'native_mapping_evidence'=>$nativeFacts,'native_mapping_conflicts'=>$nativeConflicts,'manual_rows'=>$manual,'exclusion_rows'=>$excluded,'target_competing_samo_ids'=>$targetCompetitors[$tv]??[],'classification'=>$class,'candidate_reason'=>$candidateReason,'safe_to_write_now'=>false];$outRows[]=$row;if($class==='review_candidate')$reviewCandidates[]=['samo_hotel_id'=>$sid,'tv_hotel_id'=>$tv,'candidate_reason'=>$candidateReason,'operator_ids'=>$ops];}
ksort($classes);$out=['operation'=>H6_OP,'state'=>'completed_read_only','input_sha256'=>H6_INPUT_SHA,'provider_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'hold_count'=>6,'classification_counts'=>$classes,'review_candidate_count'=>count($reviewCandidates),'review_candidates'=>$reviewCandidates,'rows'=>$outRows];$rh=h6_write($dir.'/result.json',$out);h6_write($dir.'/receipt.json',['operation'=>H6_OP,'state'=>'completed_read_only','result_sha256'=>$rh,'provider_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'readback_verified'=>true,'no_replay'=>true]);echo json_encode(['classification_counts'=>$classes,'review_candidate_count'=>count($reviewCandidates),'result_sha256'=>$rh],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";
