<?php
declare(strict_types=1);error_reporting(0);ob_start();
const OP='hotel-match-mass-bridge-auto-accept-1971-20260912-v1';
const POLICY='owner_exact_and_strong_20260908';
const XMLSHA='1a450d8fb5f39af147fea500f8f965c83f84f3188de04b6f7aa9845a0350e445';
$drop=['hotel','hotels','resort','resorts','spa','otel','отель','отели','гостиница','the','by'];
function n($v){global $drop;$s=mb_strtolower(trim((string)$v),'UTF-8');$s=strtr($s,['ё'=>'е','é'=>'e','è'=>'e','ê'=>'e','á'=>'a','à'=>'a','ä'=>'a','â'=>'a','ö'=>'o','ô'=>'o','ü'=>'u','ú'=>'u','ç'=>'c','ş'=>'s','ğ'=>'g','ı'=>'i','&'=>' and ']);preg_match_all('/[\p{L}\p{N}]+/u',$s,$m);return implode(' ',array_filter($m[0]??[],fn($x)=>$x!==''&&!in_array($x,$drop,true)));}
function v($s){$s=trim((string)$s);if($s==='')return[];$a=[$s];if(preg_match_all('/\(\s*(?:ex|ех)\s*\.?\s*([^)]{2,180})\)/iu',$s,$m))$a=array_merge($a,$m[1]);$a[]=preg_replace('/\s*\(\s*(?:ex|ех)\s*\.?\s*[^)]{2,180}\)\s*/iu',' ',$s);$o=[];foreach($a as$x){$z=n($x);if(mb_strlen($z,'UTF-8')>=3)$o[$z]=1;}return array_keys($o);}
function c($x){$z=n($x);$m=['egypt'=>['египет','egypt'],'turkey'=>['турция','turkey','türkiye','turkiye'],'thailand'=>['таиланд','thailand'],'uae'=>['оаэ','объединенные арабские эмираты','united arab emirates','uae'],'vietnam'=>['вьетнам','vietnam','viet nam'],'srilanka'=>['шри ланка','sri lanka'],'maldives'=>['мальдивы','maldives'],'cuba'=>['куба','cuba']];foreach($m as$k=>$a)foreach($a as$y)if($z===n($y))return$k;return null;}
function g($x){$o=[];foreach(explode(' ',n($x))as$t)if(mb_strlen($t,'UTF-8')>=4)$o[$t]=1;return array_keys($o);}
function co($r){$a=$b=null;foreach(['latitude','lat','geo_lat','hotel_latitude','coord_lat']as$k)if(isset($r[$k])&&is_numeric($r[$k])){$a=(float)$r[$k];break;}foreach(['longitude','lon','lng','geo_lon','hotel_longitude','coord_lon']as$k)if(isset($r[$k])&&is_numeric($r[$k])){$b=(float)$r[$k];break;}return$a!==null&&$b!==null?[$a,$b]:null;}
function km($a,$b){$r=6371.;$p1=deg2rad($a[0]);$p2=deg2rad($b[0]);$q=sin(deg2rad($b[0]-$a[0])/2)**2+cos($p1)*cos($p2)*sin(deg2rad($b[1]-$a[1])/2)**2;return 2*$r*asin(min(1,sqrt($q)));}
function src($x,$d=0){if($d>12||!is_array($x))return[];$o=[];if(isset($x['name'])&&(isset($x['id'])||isset($x['hotelKey'])))$o[]=$x;foreach($x as$k=>$y)if(is_array($y)&&!in_array((string)$k,['candidates','targets','local','hotels','offers'],true))$o=array_merge($o,src($y,$d+1));return$o;}
function mean($a){$z=0;foreach($a as$x){$i=0;foreach(explode(' ',$x)as$t)if(mb_strlen($t,'UTF-8')>=3)$i++;$z=max($z,$i);}return$z;}
$pdo=null;$done=false;$phase='init';
try{
 $raw=file_get_contents('php://stdin');if(hash('sha256',$raw)!==XMLSHA)throw new Exception('xml_sha');$xml=json_decode($raw,true,512,JSON_THROW_ON_ERROR);if(count($xml['matches']??[])<30000)throw new Exception('xml_count');
 $root=realpath(getcwd());if(!$root||basename($root)!=='anytoour.ru')throw new Exception('root');require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$pdo=v2_data_db();$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->exec('SET SESSION innodb_lock_wait_timeout=15');$pdo->beginTransaction();$phase='guards';
 $h=[];$idx=[];$hv=[];foreach($pdo->query('SELECT * FROM catalog_hotels WHERE is_active=1 FOR UPDATE')->fetchAll(PDO::FETCH_ASSOC)as$r){$cc=c($r['country_name']??'');if(!$cc)continue;$id=(int)$r['id'];$r['_c']=$cc;$h[$id]=$r;foreach(v($r['name'])as$x){$idx[$cc][$x][$id]=1;$hv[$id][$x]=1;}}foreach($pdo->query('SELECT hotel_id,alias FROM hotel_aliases')->fetchAll(PDO::FETCH_ASSOC)as$r){$id=(int)$r['hotel_id'];if(!isset($h[$id]))continue;foreach(v($r['alias'])as$x){$idx[$h[$id]['_c']][$x][$id]=1;$hv[$id][$x]=1;}}
 $used=[];foreach(['anex_hotel_search_mappings','anex_hotel_decisions','anex_review_pair_exclusions']as$t)foreach($pdo->query("SELECT anex_hotel_id FROM $t FOR UPDATE")->fetchAll(PDO::FETCH_COLUMN)as$x)$used[(int)$x]=1;$st=[];foreach($pdo->query('SELECT * FROM anex_hotels FOR UPDATE')->fetchAll(PDO::FETCH_ASSOC)as$r)$st[(int)$r['anex_hotel_id']]=$r;
 $bridge=[];foreach($pdo->query("SELECT * FROM andromeda_hotel_identities WHERE decision_status='accepted' AND local_hotel_id IS NOT NULL FOR UPDATE")->fetchAll(PDO::FETCH_ASSOC)as$a){$lid=(int)$a['local_hotel_id'];if(!isset($h[$lid]))continue;$e=json_decode((string)$a['evidence_json'],true);if(!is_array($e))continue;foreach(src($e)as$s){if((string)($s['id']??$s['hotelKey']??'')!==(string)$a['external_hotel_id'])continue;$sv=array_unique(array_merge(v($s['name']??''),v($s['lName']??'')));if(!array_intersect($sv,array_keys($hv[$lid]??[])))continue;$sc=c($s['state']??'');if($sc&&$sc!==$h[$lid]['_c'])continue;$a1=co($s);$a2=co($h[$lid]);$d=$a1&&$a2?km($a1,$a2):null;if($d!==null&&$d>5)continue;$go=array_intersect(g(($s['town']??'').' '.($s['region']??'')),g(($h[$lid]['region_name']??'').' '.($h[$lid]['subregion_name']??'')));if($d===null&&!$go)continue;$bridge[$lid]=1;}}
 $ok=[];$skip=[];foreach($xml['matches']as$m){$aid=(int)($m['external_id']??0);if($aid<=0||isset($used[$aid]))continue;$cc=c($m['country']??'');if(!$cc)continue;$cand=[];$mn=[];foreach(array_unique(array_merge(v($m['name']??''),v($m['alternate_name']??'')))as$x)foreach(array_keys($idx[$cc][$x]??[])as$lid){$cand[$lid]=1;$mn[$lid][$x]=1;}if(count($cand)!==1){$skip['not_unique']=($skip['not_unique']??0)+1;continue;}$lid=(int)array_key_first($cand);if(empty($bridge[$lid])){$skip['no_bridge']=($skip['no_bridge']??0)+1;continue;}$go=array_intersect(g($m['town']??''),g(($h[$lid]['region_name']??'').' '.($h[$lid]['subregion_name']??'')));$d=null;if(isset($st[$aid])){$sc=c($st[$aid]['api_country']??'');if($sc&&$sc!==$cc){$skip['country']=($skip['country']??0)+1;continue;}$a1=co($st[$aid]);$a2=co($h[$lid]);if($a1&&$a2){$d=km($a1,$a2);if($d>5){$skip['coord']=($skip['coord']??0)+1;continue;}}}if(trim((string)($m['town']??''))!==''&&!$go&&$d===null){$skip['geo']=($skip['geo']??0)+1;continue;}$names=array_keys($mn[$lid]);if(mean($names)<3&&!($d!==null&&$d<=1)&&count($go)<2){$skip['weak']=($skip['weak']??0)+1;continue;}$ok[]=[$aid,$lid,$m['name']??null,$m['alternate_name']??null,$m['country']??null,$m['town']??null,$h[$lid]['name'],$names,array_values($go),$d];}
 if(count($ok)<100)throw new Exception('safe_delta_'.count($ok));$ins=$pdo->prepare('INSERT INTO anex_hotel_search_mappings(anex_hotel_id,catalog_hotel_id,match_class,scope,approval_policy,source_row_digest,mapping_digest,enabled) VALUES(?,?,?,?,?,?,?,1)');$wr=[];
 foreach($ok as$r){[$aid,$lid,$sn,$an,$ct,$tw,$tn,$ns,$go,$d]=$r;$sd=hash('sha256',json_encode([OP,$aid,$sn,$an,$ct,$tw,$lid,$tn,$ns,$go,$d],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));$md=hash('sha256',json_encode([$aid,$lid,'strong_candidate','preview',POLICY,$sd],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));$ins->execute([$aid,$lid,'strong_candidate','preview',POLICY,$sd,$md]);if($ins->rowCount()!==1)throw new Exception('insert_'.$aid);$wr[]=[$aid,$lid,$md];}
 $pdo->commit();$done=true;$phase='readback';$pdo->exec('START TRANSACTION READ ONLY');$q=$pdo->prepare('SELECT catalog_hotel_id,mapping_digest,enabled FROM anex_hotel_search_mappings WHERE anex_hotel_id=?');foreach($wr as[$aid,$lid,$md]){$q->execute([$aid]);$z=$q->fetchAll(PDO::FETCH_ASSOC);if(count($z)!==1||(int)$z[0]['catalog_hotel_id']!==$lid||(int)$z[0]['enabled']!==1||$z[0]['mapping_digest']!==$md)throw new Exception('readback_'.$aid);}$pdo->exec('ROLLBACK');$out=['status'=>'accepted','operation_id'=>OP,'planned'=>count($ok),'written'=>count($wr),'skip'=>$skip,'readback'=>true,'database_writes'=>count($wr),'mapping_writes'=>count($wr),'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true];
}catch(Throwable$e){if($pdo instanceof PDO&&$pdo->inTransaction())$pdo->rollBack();$out=['status'=>'failed','operation_id'=>OP,'phase'=>$phase,'commit_completed'=>$done,'safe_message'=>substr($e->getMessage(),0,160),'database_writes'=>$done?null:0,'mapping_writes'=>$done?null:0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true];}
while(ob_get_level())ob_end_clean();echo 'MATCH_MASS_AUTO:'.json_encode($out,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";exit(($out['status']??'')==='accepted'?0:2);
