<?php
declare(strict_types=1);
const OP='hotel-match-current-cross-provider-exact-mass-1971-20260912-v1';
const POLICY='owner_current_exact_cross_provider_20260912';
const CAP=1500;
function j($v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
function h($v):string{return hash('sha256',j($v));}
function save_once(string $path,array $data):void{$f=fopen($path,'x');if(!$f)throw new RuntimeException('receipt_exists');chmod($path,0600);$raw=j($data)."\n";fwrite($f,$raw);fflush($f);if(function_exists('fsync'))fsync($f);fclose($f);if(file_get_contents($path)!==$raw)throw new RuntimeException('receipt_readback');}
function txt($v):string{$s=mb_strtolower(trim((string)$v),'UTF-8');$s=str_replace(['ё','&'],['е',' and '],$s);preg_match_all('/[\p{L}\p{N}]+/u',$s,$m);return implode(' ',$m[0]);}
function norm($v):string{$drop=['hotel'=>1,'hotels'=>1,'resort'=>1,'resorts'=>1,'spa'=>1,'the'=>1,'and'=>1,'by'=>1,'otel'=>1,'отель'=>1,'отели'=>1,'гостиница'=>1];$w=[];foreach(explode(' ',txt($v)) as$x)if($x!==''&&!isset($drop[$x]))$w[]=$x;sort($w,SORT_STRING);return implode(' ',$w);}
function forms($v):array{$s=(string)$v;$re='/\(\s*(?:ex|ех|formerly|быв)\s*[.:\-]?\s*([^)]*)\)/iu';preg_match_all($re,$s,$m);$o=[];foreach(array_merge([$s,preg_replace($re,' ',$s)],$m[1]??[]) as$x){$n=norm($x);if($n!=='')$o[$n]=1;}return array_keys($o);}
function country($v):?string{$s=txt($v);$m=['egypt'=>['египет','egypt'],'turkey'=>['турция','turkey','turkiye'],'thailand'=>['таиланд','thailand'],'uae'=>['оаэ','united arab emirates','uae','объединенные арабские эмираты'],'vietnam'=>['вьетнам','vietnam','viet nam'],'srilanka'=>['шри ланка','sri lanka'],'maldives'=>['мальдивы','maldives'],'cuba'=>['куба','cuba']];foreach($m as$k=>$a)if(in_array($s,$a,true))return$k;return null;}
function geo($v):string{return implode(' ',array_values(array_diff(explode(' ',txt($v)),['','о','остров','island','город','г'])));}
function point(array$r):?array{$a=$r['latitude']??$r['lat']??null;$b=$r['longitude']??$r['lon']??$r['lng']??null;if(!is_numeric($a)||!is_numeric($b))return null;$a=(float)$a;$b=(float)$b;return abs($a)<=90&&abs($b)<=180&&($a!=0||$b!=0)?[$a,$b]:null;}
function dist(array$a,array$b):?float{$x=point($a);$y=point($b);if(!$x||!$y)return null;$p=deg2rad($x[0]);$q=deg2rad($y[0]);$z=sin(($q-$p)/2)**2+cos($p)*cos($q)*sin(deg2rad($y[1]-$x[1])/2)**2;return12742*asin(min(1,sqrt($z)));}
function sources($e,int$d=0):array{if(!is_array($e)||$d>12)return[];$o=[];if(isset($e['name'])&&(isset($e['id'])||isset($e['hotelKey'])))$o[]=$e;foreach($e as$k=>$v)if(is_array($v)&&!in_array((string)$k,['candidates','targets','local','hotels','offers'],true))$o=array_merge($o,sources($v,$d+1));return$o;}
function and_source(array$r):?array{$e=json_decode((string)$r['evidence_json'],true);if(!is_array($e))return null;$ss=array_values(array_filter(sources($e),fn($s)=>(string)($s['id']??$s['hotelKey']??'')===(string)$r['external_hotel_id']));if(count($ss)!==1)return null;$s=$ss[0];$cc=country($s['state']??'');if(!$cc)return null;return['names'=>array_filter([$s['name']??null,$s['lName']??null]),'cc'=>$cc,'geo'=>array_filter([$s['town']??null,$s['region']??null]),'latitude'=>$s['latitude']??$s['lat']??null,'longitude'=>$s['longitude']??$s['lon']??null];}
function names(array$a):array{$o=[];foreach($a as$v)foreach(forms($v) as$n)$o[$n]=1;return array_keys($o);}
function geo_overlap(array$a,array$b):bool{$x=array_filter(array_map('geo',$a),fn($v)=>$v!==''&&country($v)===null);$y=array_filter(array_map('geo',$b),fn($v)=>$v!==''&&country($v)===null);return(bool)array_intersect($x,$y);}
if(in_array('--self-test',$_SERVER['argv']??[],true)){if(norm('ABC HOTEL SPA')!==norm('ABC RESORT')||norm('ABC BEACH')===norm('ABC GARDEN'))exit(2);echo"MATCH mass exact self-test PASS\n";exit;}
error_reporting(0);ob_start();$db=null;$dir=null;$commitAttempted=false;$committed=false;$written=[];$skipped=[];
try{
 if(PHP_SAPI!=='cli')throw new RuntimeException('cli_only');$root=realpath(getcwd());if(!$root||basename($root)!=='anytoour.ru')throw new RuntimeException('root');$home=realpath((string)getenv('HOME'));if(!$home)throw new RuntimeException('home');$base=$home.'/.anytoour-match/operations';if(!is_dir($base)&&!mkdir($base,0700,true))throw new RuntimeException('receipt_root');$dir=$base.'/'.OP;if(file_exists($dir)||!mkdir($dir,0700)){$dir=null;throw new RuntimeException('prior_operation_no_replay');}save_once($dir.'/reservation.json',['operation_id'=>OP,'state'=>'reserved_before_db_access','cap'=>CAP,'no_replay'=>true]);
 require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET SESSION innodb_lock_wait_timeout=15');$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->beginTransaction();
 $hot=[];$alias=[];$index=[];$countryIds=[];foreach($db->query('SELECT id,name,country_id,country_name,region_name,subregion_name,latitude,longitude,is_active FROM catalog_hotels WHERE is_active=1')->fetchAll(PDO::FETCH_ASSOC)as$r){$cc=country($r['country_name']);if(!$cc)continue;$id=(int)$r['id'];$hot[$id]=$r;$countryIds[(string)$r['country_id']]=$cc;$alias[$id]=forms($r['name']);}foreach($db->query('SELECT hotel_id,alias FROM hotel_aliases')->fetchAll(PDO::FETCH_ASSOC)as$r){$id=(int)$r['hotel_id'];if(isset($hot[$id]))$alias[$id]=array_values(array_unique(array_merge($alias[$id],forms($r['alias']))));}foreach($alias as$id=>$ns){$cc=country($hot[$id]['country_name']);foreach($ns as$n)$index[$cc][$n][$id]=1;}
 $maps=$db->query('SELECT anex_hotel_id,catalog_hotel_id,enabled FROM anex_hotel_search_mappings ORDER BY anex_hotel_id,catalog_hotel_id FOR UPDATE')->fetchAll(PDO::FETCH_ASSOC);$mapBy=[];$anexByLocal=[];foreach($maps as$r){$mapBy[(string)$r['anex_hotel_id']][]=$r;if((int)$r['enabled']===1)$anexByLocal[(int)$r['catalog_hotel_id']][]=(string)$r['anex_hotel_id'];}
 $prot=[];foreach($db->query('SELECT anex_hotel_id FROM anex_hotel_decisions FOR UPDATE')->fetchAll(PDO::FETCH_ASSOC)as$r)$prot[(string)$r['anex_hotel_id']]=1;foreach($db->query('SELECT anex_hotel_id FROM anex_review_pair_exclusions FOR UPDATE')->fetchAll(PDO::FETCH_ASSOC)as$r)$prot[(string)$r['anex_hotel_id']]=1;
 $staging=[];foreach($db->query('SELECT * FROM anex_hotels ORDER BY anex_hotel_id FOR UPDATE')->fetchAll(PDO::FETCH_ASSOC)as$r)$staging[(string)$r['anex_hotel_id']]=$r;$obs=[];foreach($db->query('SELECT anex_hotel_id,hotel_name,country_id FROM anex_search_hotel_observations ORDER BY anex_hotel_id FOR UPDATE')->fetchAll(PDO::FETCH_ASSOC)as$r)$obs[(string)$r['anex_hotel_id']]=$r;
 $andAll=$db->query("SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' ORDER BY external_hotel_id FOR UPDATE")->fetchAll(PDO::FETCH_ASSOC);$andBy=[];$andAcceptedLocal=[];foreach($andAll as$r){$andBy[(string)$r['external_hotel_id']]=$r;if($r['decision_status']==='accepted'&&$r['local_hotel_id']!==null)$andAcceptedLocal[(int)$r['local_hotel_id']][]=$r;}
 $anexSource=[];foreach($staging as$id=>$r){$cc=country($r['api_country']??'');if(!$cc){$o=$obs[$id]??null;$cc=$o?$countryIds[(string)($o['country_id']??'')]??null:null;}if(!$cc)continue;$anexSource[$id]=['names'=>array_filter([$r['api_name']??null,$r['xml_name']??null,$r['xml_alternate_name']??null,$obs[$id]['hotel_name']??null]),'cc'=>$cc,'geo'=>array_filter([$r['api_town']??null,$r['api_region']??null]),'latitude'=>$r['latitude']??null,'longitude'=>$r['longitude']??null];}
 $safe=[];
 foreach($anexSource as$aid=>$s){if(isset($mapBy[$aid])||isset($prot[$aid]))continue;$forms=names($s['names']);$hits=[];foreach($forms as$n)foreach(array_keys($index[$s['cc']][$n]??[])as$lid)$hits[$lid]=1;if(count($hits)!==1)continue;$lid=(int)array_key_first($hits);$target=$hot[$lid];$d=dist($s,$target);if($d!==null&&$d>5)continue;$bridge=null;foreach($andAcceptedLocal[$lid]??[]as$ar){$bs=and_source($ar);if(!$bs||$bs['cc']!==$s['cc'])continue;if(!array_intersect($forms,names($bs['names'])))continue;if(!geo_overlap($s['geo'],$bs['geo']))continue;$bd=dist($bs,$target);if($bd!==null&&$bd>5)continue;$bridge=$ar;break;}if($bridge)$safe[]=['provider'=>'anex','external_id'=>$aid,'local_id'=>$lid,'bridge_id'=>(string)$bridge['external_hotel_id'],'rule'=>'native_exact_plus_accepted_andromeda_exact_country_geo'];if(count($safe)>CAP)throw new RuntimeException('cap');}
 foreach($andAll as$ar){if($ar['decision_status']!=='pending'||$ar['local_hotel_id']!==null)continue;$s=and_source($ar);if(!$s)continue;$forms=names($s['names']);$hits=[];foreach($forms as$n)foreach(array_keys($index[$s['cc']][$n]??[])as$lid)$hits[$lid]=1;if(count($hits)!==1)continue;$lid=(int)array_key_first($hits);$target=$hot[$lid];$d=dist($s,$target);if($d!==null&&$d>5)continue;$bridgeAid=null;foreach($anexByLocal[$lid]??[]as$aid){$as=$anexSource[$aid]??null;if(!$as||$as['cc']!==$s['cc'])continue;if(!array_intersect($forms,names($as['names'])))continue;if(!geo_overlap($s['geo'],$as['geo']))continue;$ad=dist($as,$target);if($ad!==null&&$ad>5)continue;$bridgeAid=$aid;break;}if($bridgeAid)$safe[]=['provider'=>'andromeda','external_id'=>(string)$ar['external_hotel_id'],'local_id'=>$lid,'bridge_id'=>$bridgeAid,'rule'=>'native_exact_plus_enabled_anex_exact_country_geo'];if(count($safe)>CAP)throw new RuntimeException('cap');}
 $seen=[];$safe=array_values(array_filter($safe,function($r)use(&$seen){$k=$r['provider'].':'.$r['external_id'];if(isset($seen[$k]))return false;$seen[$k]=1;return true;}));
 $ins=$db->prepare('INSERT INTO anex_hotel_search_mappings(anex_hotel_id,catalog_hotel_id,match_class,scope,approval_policy,source_row_digest,mapping_digest,enabled) VALUES(?,?,?,?,?,?,?,1)');$upd=$db->prepare("UPDATE andromeda_hotel_identities SET local_hotel_id=?,decision_status='accepted',evidence_json=?,evidence_sha256=? WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=? AND local_hotel_id IS NULL AND decision_status='pending' AND evidence_sha256=?");
 foreach($safe as$r){$lid=(int)$r['local_id'];if($r['provider']==='anex'){$aid=$r['external_id'];if(isset($mapBy[$aid])||isset($prot[$aid])){$skipped[]=$r+['reason'=>'stale_or_protected'];continue;}$proof=['operation_id'=>OP]+$r;$sd=h($proof);$md=h(['anex_hotel_id'=>(int)$aid,'catalog_hotel_id'=>$lid,'scope'=>'preview','approval_policy'=>POLICY,'source_row_digest'=>$sd]);$ins->execute([(int)$aid,$lid,'exact_cross_provider','preview',POLICY,$sd,$md]);if($ins->rowCount()!==1)throw new RuntimeException('anex_insert_count');$written[]=$r+['mapping_digest'=>$md,'source_row_digest'=>$sd];}
  else{$id=$r['external_id'];$cur=$andBy[$id]??null;if(!$cur||$cur['decision_status']!=='pending'||$cur['local_hotel_id']!==null){$skipped[]=$r+['reason'=>'stale_or_protected'];continue;}$prior=json_decode((string)$cur['evidence_json'],true);$proof=['operation_id'=>OP]+$r;$ej=j(['prior_evidence'=>$prior,'proof'=>$proof]);$eh=hash('sha256',$ej);$upd->execute([$lid,$ej,$eh,$id,$cur['evidence_sha256']]);if($upd->rowCount()!==1)throw new RuntimeException('andromeda_update_count');$written[]=$r+['evidence_sha256'=>$eh];}
 }
 save_once($dir.'/precommit-intent.json',['operation_id'=>OP,'prepared'=>count($safe),'written'=>$written,'skipped'=>$skipped,'no_replay'=>true]);$commitAttempted=true;$db->commit();$committed=true;
 $db->exec('START TRANSACTION READ ONLY');foreach($written as$w){if($w['provider']==='anex'){$q=$db->prepare('SELECT catalog_hotel_id,enabled,mapping_digest,source_row_digest FROM anex_hotel_search_mappings WHERE anex_hotel_id=?');$q->execute([$w['external_id']]);$x=$q->fetchAll(PDO::FETCH_ASSOC);if(count($x)!==1||(int)$x[0]['catalog_hotel_id']!==(int)$w['local_id']||(int)$x[0]['enabled']!==1||$x[0]['mapping_digest']!==$w['mapping_digest'])throw new RuntimeException('readback_anex');}else{$q=$db->prepare("SELECT local_hotel_id,decision_status,evidence_sha256 FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=?");$q->execute([$w['external_id']]);$x=$q->fetch(PDO::FETCH_ASSOC);if(!$x||(int)$x['local_hotel_id']!==(int)$w['local_id']||$x['decision_status']!=='accepted'||$x['evidence_sha256']!==$w['evidence_sha256'])throw new RuntimeException('readback_andromeda');}}$db->exec('ROLLBACK');
 $counts=['anex'=>0,'andromeda'=>0];foreach($written as$w)++$counts[$w['provider']];$out=['status'=>'accepted','operation_id'=>OP,'prepared'=>count($safe),'written_count'=>count($written),'provider_counts'=>$counts,'skipped_count'=>count($skipped),'readback_verified'=>true,'database_writes'=>count($written),'mapping_writes'=>count($written),'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true];save_once($dir.'/result.json',$out);
}catch(Throwable$e){try{if($db instanceof PDO&&$db->inTransaction())$db->rollBack();}catch(Throwable$ignored){}$out=['status'=>$commitAttempted?'commit_outcome_requires_readback':'rolled_back_or_not_started','operation_id'=>OP,'safe_message'=>preg_match('/^[a-z0-9_]+$/D',$e->getMessage())?$e->getMessage():'guard_failure','commit_attempted'=>$commitAttempted,'commit_confirmed'=>$committed,'database_writes'=>$commitAttempted?null:0,'mapping_writes'=>$commitAttempted?null:0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true];if($dir&&is_dir($dir)&&!file_exists($dir.'/failure.json')){try{save_once($dir.'/failure.json',$out);}catch(Throwable$ignored){}}}
while(ob_get_level())ob_end_clean();echo 'MATCH_MASS_EXACT:'.j($out).PHP_EOL;exit(($out['status']??'')==='accepted'?0:2);
