<?php
declare(strict_types=1);
const HMPB_OPERATION='hotel-match-user-seen-common4-pending-evidence-bridge-1971-20260918-v2';
const HMPB_LIMIT=100000;
const HMPB_EXCLUDED_COUNTRIES=[46=>true,47=>true];
const HMPB_GENERIC=['hotel'=>1,'hotels'=>1,'otel'=>1,'отель'=>1,'resort'=>1,'resorts'=>1,'spa'=>1];
const HMPB_QUALIFIERS=['annex'=>1,'beach'=>1,'garden'=>1,'gardens'=>1,'north'=>1,'south'=>1,'east'=>1,'west'=>1,'adult'=>1,'adults'=>1,'only'=>1,'family'=>1,'pool'=>1,'sea'=>1,'view'=>1,'deluxe'=>1,'suite'=>1,'suites'=>1,'villa'=>1,'villas'=>1,'palace'=>1,'park'=>1,'club'=>1,'city'=>1,'premium'=>1,'select'=>1];
function hmpb_rows(PDO $p,string $q,array $a=[]): array {$s=$p->prepare($q);$s->execute(array_values($a));$r=$s->fetchAll(PDO::FETCH_ASSOC)?:[];if(count($r)>HMPB_LIMIT)throw new RuntimeException('row_budget');return $r;}
function hmpb_norm(string $v): string {$v=mb_strtolower(trim($v),'UTF-8');$v=strtr($v,['ё'=>'е','&'=>' ','+'=>' ','_'=>' ','-'=>' ','’'=>"'",'`'=>"'"]);$v=preg_replace('/[^\p{L}\p{N}]+/u',' ',$v)??$v;return trim(preg_replace('/\s+/u',' ',$v)??$v);}
function hmpb_generic(string $v): string {$t=preg_split('/\s+/u',hmpb_norm($v),-1,PREG_SPLIT_NO_EMPTY)?:[];$t=array_values(array_filter($t,fn($x)=>!isset(HMPB_GENERIC[$x])));return implode(' ',$t);}
function hmpb_valid(string $n): bool {$t=preg_split('/\s+/u',$n,-1,PREG_SPLIT_NO_EMPTY)?:[];if(!$t)return false;$sub=0;$long=false;foreach($t as $x){if(!isset(HMPB_GENERIC[$x])){$sub++;if(mb_strlen($x,'UTF-8')>=7)$long=true;}}return mb_strlen($n,'UTF-8')>=4&&($sub>=2||($sub===1&&$long));}
function hmpb_forms(string $name): array {$bases=[];$addBase=function(string $v,string $why)use(&$bases){$n=hmpb_norm($v);if($n!=='')$bases[$n][$why]=true;};$addBase($name,'full');if(preg_match('/^(.+?)\s*\((?:EX\.?|FORMERLY|БЫВШ\.?)[^)]*\)/iu',$name,$m))$addBase($m[1],'current');if(preg_match_all('/\((?:EX\.?|FORMERLY|БЫВШ\.?)\s*([^)]*)\)/iu',$name,$ms))foreach($ms[1] as $x)foreach(preg_split('/[;|\/]+/u',$x)?:[] as $p)$addBase($p,'former');$out=[];foreach($bases as $n=>$rs){if(hmpb_valid($n))foreach(array_keys($rs) as $r)$out[$n][$r]=true;$g=hmpb_generic($n);if($g!==$n&&hmpb_valid($g))foreach(array_keys($rs) as $r)$out[$g]['generic_'.$r]=true;}foreach($out as $k=>$rs){$x=array_keys($rs);sort($x,SORT_STRING);$out[$k]=$x;}return $out;}
function hmpb_tokens(string $v): array {return preg_split('/\s+/u',hmpb_norm($v),-1,PREG_SPLIT_NO_EMPTY)?:[];}
function hmpb_qualifiers(string $v): array {$o=[];foreach(hmpb_tokens($v) as $t)if(isset(HMPB_QUALIFIERS[$t]))$o[$t]=true;$x=array_keys($o);sort($x,SORT_STRING);return $x;}
function hmpb_numbers(string $v): array {$o=[];foreach(hmpb_tokens($v) as $t)if(preg_match('/^[0-9]+$/D',$t))$o[$t]=true;$x=array_keys($o);sort($x,SORT_STRING);return $x;}
function hmpb_product(string $n): bool {return (bool)preg_match('/^(?:fortuna|фортуна|roulette|рулетка|рулет)(?:\s|$)/u',hmpb_norm($n));}
function hmpb_first_array(array $v,string $key): ?array {if(isset($v[$key])&&is_array($v[$key]))return $v[$key];foreach($v as $x)if(is_array($x)){if(array_is_list($x)){foreach($x as $y)if(is_array($y)){if(isset($y[$key])&&is_array($y[$key]))return $y[$key];}}}else{$r=hmpb_first_array($x,$key);if($r!==null)return $r;}}return null;}
function hmpb_scalar(array $a,array $keys): ?string {foreach($keys as $k)if(isset($a[$k])&&(is_string($a[$k])||is_int($a[$k]))){$s=trim((string)$a[$k]);if($s!=='')return $s;}return null;}
function hmpb_source(array $e): array {$s=hmpb_first_array($e,'source');if($s!==null)return $s;$s=hmpb_first_array($e,'source_candidate');return $s??[];}
function hmpb_durable(string $path,array $v): string {$raw=json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n";$f=@fopen($path,'x+b');if(!$f)throw new RuntimeException('durable_exists');try{if(fwrite($f,$raw)!==strlen($raw)||!fflush($f))throw new RuntimeException('durable_write');if(function_exists('fsync')&&!fsync($f))throw new RuntimeException('durable_sync');rewind($f);if(stream_get_contents($f)!==$raw)throw new RuntimeException('durable_readback');}finally{fclose($f);}return hash('sha256',$raw);}
function hmpb_consensus(array $set): ?string {$x=array_keys($set);return count($x)===1?(string)$x[0]:null;}
if(in_array('--self-test',$argv??[],true)){if(!isset(hmpb_forms('SUN BAY HOTEL (EX. SUN MARIS PARK)')['sun bay'],hmpb_forms('SUN BAY HOTEL (EX. SUN MARIS PARK)')['sun maris park']))throw new RuntimeException('forms');if(hmpb_qualifiers('Grand Sea View Hotel')!==['sea','view'])throw new RuntimeException('qual');$e=['wrap'=>['source'=>['name'=>'X','stateKey'=>7]]];if((hmpb_source($e)['stateKey']??null)!==7)throw new RuntimeException('source');echo"MATCH_PENDING_EVIDENCE_BRIDGE_V2_SELFTEST_OK\n";exit;}
$root=realpath((string)getenv('ANYTOUR_ROOT'));$opDir=(string)getenv('MATCH_OPERATION_DIR');$reg=realpath((string)getenv('MATCH_MAPPING_REGISTRY_PATH'));$sourceSha=(string)getenv('MATCH_SOURCE_SHA');if(!$root||$opDir===''||!is_string($reg)||!is_file($reg)||!preg_match('/^[a-f0-9]{40}$/D',$sourceSha)||is_dir($opDir)||!mkdir($opDir,0700,true))throw new RuntimeException('runtime_guard');hmpb_durable($opDir.'/reservation.json',['operation'=>HMPB_OPERATION,'state'=>'reserved_before_db_read','source_sha'=>$sourceSha,'provider_access'=>false,'no_replay'=>true]);require_once $reg;$dbf=is_file($root.'/data/db-v1.php')?$root.'/data/db-v1.php':$root.'/v2/data/db-v1.php';require_once $dbf;$pdo=v2_data_db();$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$pdo->exec('START TRANSACTION READ ONLY');
try{
 $registry=AnyTourAnexSearchMappingRegistry::fromPdo($pdo);$anex=[];foreach(hmpb_rows($pdo,'SELECT anex_hotel_id FROM anex_hotel_search_mappings UNION SELECT anex_hotel_id FROM anex_hotel_decisions') as $r){$x=$registry->resolve('anex_online',(string)$r['anex_hotel_id'],'preview');if(is_int($x)&&$x>0)$anex[$x]=true;}
 $identity=hmpb_rows($pdo,"SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' ORDER BY external_hotel_id");$and=[];$pending=[];foreach($identity as $r){if(($r['decision_status']??'')==='accepted'&&$r['local_hotel_id']!==null)$and[(int)$r['local_hotel_id']]=true;if(($r['decision_status']??'')==='pending'&&$r['local_hotel_id']===null)$pending[(string)$r['external_hotel_id']]=$r;}
 $seen=[];foreach(hmpb_rows($pdo,"SELECT hotel_id,COUNT(*) rows_count,MAX(observed_at) last_seen FROM tour_price_observations WHERE source='user_search' GROUP BY hotel_id") as $r)$seen[(int)$r['hotel_id']]=['rows'=>(int)$r['rows_count'],'last'=>(string)$r['last_seen']];$ids=array_keys($seen);$ph=implode(',',array_fill(0,count($ids),'?'));$front=[];foreach(hmpb_rows($pdo,"SELECT id,country_id,country_name,region_id,region_name,subregion_id,subregion_name,name,category,is_active FROM catalog_hotels WHERE id IN ($ph)",$ids) as $h){$id=(int)$h['id'];$cid=(int)$h['country_id'];if((int)$h['is_active']!==1||isset(HMPB_EXCLUDED_COUNTRIES[$cid])||isset($anex[$id])||isset($and[$id])||hmpb_product((string)$h['name']))continue;$front[$id]=$h+['observation_rows'=>$seen[$id]['rows'],'last_observed_at'=>$seen[$id]['last']];}
 $fids=array_keys($front);$common=[];if($fids){$fh=implode(',',array_fill(0,count($fids),'?'));foreach(hmpb_rows($pdo,"SELECT DISTINCT hotel_id FROM tour_price_observations WHERE source='user_search' AND hotel_id IN ($fh) AND departure_date>=CURRENT_DATE AND operator_id IN(13,18,25,43)",$fids) as $r)$common[(int)$r['hotel_id']]=true;}$targets=array_intersect_key($front,$common);$countries=[];foreach($targets as $h)$countries[(int)$h['country_id']]=true;if(!$targets)throw new RuntimeException('no_targets');
 $cids=array_keys($countries);$cph=implode(',',array_fill(0,count($cids),'?'));$all=[];$forms=[];$index=[];foreach(hmpb_rows($pdo,"SELECT id,country_id,country_name,region_id,region_name,subregion_id,subregion_name,name,category,is_active FROM catalog_hotels WHERE is_active=1 AND country_id IN ($cph)",$cids) as $h){$id=(int)$h['id'];$all[$id]=$h;$forms[$id][(string)$h['name']]=hmpb_forms((string)$h['name']);foreach($forms[$id][(string)$h['name']] as $k=>$why)$index[(int)$h['country_id']][$k][$id][(string)$h['name']]=$why;}
 foreach(hmpb_rows($pdo,"SELECT a.hotel_id,a.alias,h.country_id FROM hotel_aliases a JOIN catalog_hotels h ON h.id=a.hotel_id WHERE h.is_active=1 AND h.country_id IN ($cph)",$cids) as $a){$id=(int)$a['hotel_id'];$raw=trim((string)$a['alias']);if(!isset($all[$id])||$raw==='')continue;$forms[$id][$raw]=hmpb_forms($raw);foreach($forms[$id][$raw] as $k=>$why)$index[(int)$a['country_id']][$k][$id][$raw]=$why;}
 $acceptedState=[];$acceptedTown=[];$acceptedEvidence=0;foreach($identity as $r){if(($r['decision_status']??'')!=='accepted'||$r['local_hotel_id']===null)continue;$lid=(int)$r['local_hotel_id'];$h=$all[$lid]??null;if(!$h)continue;try{$e=json_decode((string)$r['evidence_json'],true,128,JSON_THROW_ON_ERROR);}catch(Throwable $x){continue;}$s=hmpb_source($e);if(!$s)continue;$state=hmpb_scalar($s,['stateKey','provider_state_id','supplier_state_id']);$town=hmpb_scalar($s,['townKey','town_key','supplier_town_id']);if($state!==null)$acceptedState[$state][(string)$h['country_id']]=true;if($town!==null){$key=$h['country_id'].'|'.$town;$acceptedTown[$key]['region_ids'][(string)($h['region_id']??'')]=true;$acceptedTown[$key]['subregion_ids'][(string)($h['subregion_id']??'')]=true;$acceptedTown[$key]['rows']++;}$acceptedEvidence++;}
 $stateCountry=[];$stateConflict=0;foreach($acceptedState as $k=>$set){$v=hmpb_consensus($set);if($v!==null)$stateCountry[$k]=(int)$v;else$stateConflict++;}
 $townConsensus=[];$townConflict=0;foreach($acceptedTown as $k=>$x){$regions=$x['region_ids'];unset($regions['']);$subs=$x['subregion_ids'];unset($subs['']);$region=hmpb_consensus($regions);$sub=hmpb_consensus($subs);if($region===null&&$sub===null){$townConflict++;continue;}$townConsensus[$k]=['region_id'=>$region===null?null:(int)$region,'subregion_id'=>$sub===null?null:(int)$sub,'accepted_rows'=>(int)$x['rows']];}
 $raw=[];$reasons=[];foreach($pending as $ext=>$r){try{$e=json_decode((string)$r['evidence_json'],true,128,JSON_THROW_ON_ERROR);}catch(Throwable $x){$reasons['invalid_evidence']=($reasons['invalid_evidence']??0)+1;continue;}$s=hmpb_source($e);if(!$s){$reasons['no_source']=($reasons['no_source']??0)+1;continue;}$sid=hmpb_scalar($s,['id','hotelKey','external_hotel_id']);if($sid!==null&&$sid!==$ext){$reasons['source_id_mismatch']=($reasons['source_id_mismatch']??0)+1;continue;}$stateKey=hmpb_scalar($s,['stateKey','provider_state_id','supplier_state_id']);$cid=$stateKey!==null?($stateCountry[$stateKey]??0):0;if($cid===0){$stateName=hmpb_norm((string)(hmpb_scalar($s,['state','country','country_name'])??''));$hits=[];if($stateName!=='')foreach($countries as $cc=>$_){foreach($all as $h)if((int)$h['country_id']===$cc&&hmpb_norm((string)$h['country_name'])===$stateName){$hits[$cc]=true;break;}}if(count($hits)===1)$cid=(int)array_key_first($hits);}if($cid===0||!isset($countries[$cid])){$reasons['country_unresolved_or_outside']=($reasons['country_unresolved_or_outside']??0)+1;continue;}
  $sourceNames=[];foreach(['name','lName','hotel_name'] as $k){$v=trim((string)($s[$k]??''));if($v!=='')$sourceNames[$v]=true;}if(!$sourceNames){$reasons['no_source_name']=($reasons['no_source_name']??0)+1;continue;}$candidateLocals=[];$matched=[];foreach(array_keys($sourceNames) as $sn)foreach(hmpb_forms($sn) as $key=>$why)foreach($index[$cid][$key]??[] as $lid=>$rawForms){if(isset($targets[$lid])){$candidateLocals[(int)$lid]=true;foreach($rawForms as $rawForm=>$localWhy)$matched[(int)$lid][]=['key'=>$key,'source_name'=>$sn,'target_form'=>$rawForm,'source_reasons'=>$why,'target_reasons'=>$localWhy];}}
  if(count($candidateLocals)!==1){$reasons[count($candidateLocals)>1?'ambiguous_name':'no_strict_name_match']=($reasons[count($candidateLocals)>1?'ambiguous_name':'no_strict_name_match']??0)+1;continue;}$lid=(int)array_key_first($candidateLocals);$h=$targets[$lid];$goodMatch=null;foreach($matched[$lid]??[] as $m){if(hmpb_qualifiers($m['source_name'])===hmpb_qualifiers($m['target_form'])&&hmpb_numbers($m['source_name'])===hmpb_numbers($m['target_form'])){$goodMatch=$m;break;}}if($goodMatch===null){$reasons['qualifier_or_number_conflict']=($reasons['qualifier_or_number_conflict']??0)+1;continue;}$star=hmpb_scalar($s,['star','category']);if($star!==null&&preg_match('/^[1-5]$/D',$star)&&$h['category']!==null&&(int)$h['category']>=1&&(int)$h['category']<=5&&(int)$star!==(int)$h['category']){$reasons['star_conflict']=($reasons['star_conflict']??0)+1;continue;}
  $townKey=hmpb_scalar($s,['townKey','town_key','supplier_town_id']);$townName=hmpb_norm((string)(hmpb_scalar($s,['town','town_name','region_name'])??''));$direct=$townName!==''&&in_array($townName,array_filter([hmpb_norm((string)$h['region_name']),hmpb_norm((string)$h['subregion_name'])]),true);$cross=null;if($townKey!==null)$cross=$townConsensus[$cid.'|'.$townKey]??null;$crossOk=$cross!==null&&(($cross['region_id']!==null&&(int)($h['region_id']??0)===$cross['region_id'])||($cross['subregion_id']!==null&&(int)($h['subregion_id']??0)===$cross['subregion_id']));if(!$direct&&!$crossOk){$reasons[$cross!==null?'town_crosswalk_conflict':'geography_unproven']=($reasons[$cross!==null?'town_crosswalk_conflict':'geography_unproven']??0)+1;continue;}
  $raw[]=['external_hotel_id'=>$ext,'local_hotel_id'=>$lid,'local_name'=>(string)$h['name'],'country_id'=>$cid,'country_name'=>(string)$h['country_name'],'region_id'=>$h['region_id']===null?null:(int)$h['region_id'],'region_name'=>(string)$h['region_name'],'subregion_id'=>$h['subregion_id']===null?null:(int)$h['subregion_id'],'subregion_name'=>(string)$h['subregion_name'],'category'=>$h['category']===null?null:(int)$h['category'],'source_names'=>array_keys($sourceNames),'state_key'=>$stateKey,'town_key'=>$townKey,'source_town'=>$townName?:null,'geography_route'=>$direct?'direct_town_label':'accepted_town_crosswalk','town_crosswalk'=>$cross,'match'=>$goodMatch,'observation_rows'=>(int)$h['observation_rows'],'pending_evidence_sha256'=>(string)($r['evidence_sha256']??'')];}
 $extLoc=[];$locExt=[];foreach($raw as $x){$extLoc[$x['external_hotel_id']][$x['local_hotel_id']]=true;$locExt[$x['local_hotel_id']][$x['external_hotel_id']]=true;}$safe=[];$collision=[];foreach($raw as $x){if(count($extLoc[$x['external_hotel_id']])!==1||count($locExt[$x['local_hotel_id']])!==1){$collision[]=$x;continue;}$safe[]=$x;}usort($safe,fn($a,$b)=>$b['observation_rows']<=>$a['observation_rows']?:$a['local_hotel_id']<=>$b['local_hotel_id']);ksort($reasons);$pdo->rollBack();
 $result=['operation'=>HMPB_OPERATION,'status'=>'read_only_complete','source_sha'=>$sourceSha,'current_unresolved_real'=>count($front),'current_common4_residual'=>count($targets),'pending_examined'=>count($pending),'accepted_evidence_rows_examined'=>$acceptedEvidence,'state_crosswalk_keys'=>count($stateCountry),'state_crosswalk_conflicts'=>$stateConflict,'town_crosswalk_keys'=>count($townConsensus),'town_crosswalk_conflicts'=>$townConflict,'raw_candidate_count'=>count($raw),'safe_one_to_one_count'=>count($safe),'safe_candidates'=>$safe,'collision_holds'=>array_slice($collision,0,200),'reason_counts'=>$reasons,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0];
}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$result=['operation'=>HMPB_OPERATION,'status'=>'failed_read_only','reason'=>preg_replace('/[^a-z0-9_\-]/i','_',mb_substr($e->getMessage(),0,120)),'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0];}
$sha=hmpb_durable($opDir.'/result.json',$result);hmpb_durable($opDir.'/receipt.json',['operation'=>HMPB_OPERATION,'status'=>$result['status'],'result_sha256'=>$sha,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);echo json_encode($result,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";exit(($result['status']??'')==='read_only_complete'?0:2);
