<?php
declare(strict_types=1);
require_once __DIR__.'/hotel_match_retained_candidates_write_v86.php';
const V92_OP='hotel-match-samo-missing-source-retained-scan-1971-20260928-v92';
const V92_CAT='2000086118';
function v92_need(bool$b,string$m):void{if(!$b)throw new RuntimeException($m);}
function v92_find(mixed$x,string$id,string$ptr='',int$d=0,array&$out=[]):void{if($d>10||!is_array($x))return;if(isset($x['id'])&&(string)$x['id']===$id&&isset($x['name']))$out[]=['json_pointer'=>$ptr,'row'=>$x];foreach($x as$k=>$v)if(is_array($v))v92_find($v,$id,$ptr.'/'.str_replace(['~','/'],['~0','~1'],(string)$k),$d+1,$out);}
function v92_main(array$argv):int{v92_need(($argv[1]??'')==='--execute','disabled');$root=(string)getenv('ANYTOUR_ROOT');$dir=(string)getenv('MATCH_OPERATION_DIR');$head=(string)getenv('MATCH_SOURCE_SHA');v92_need(is_dir($root)&&basename($root)==='anytoour.ru'&&is_dir($dir)&&basename($dir)===V92_OP&&preg_match('/^[a-f0-9]{40}$/D',$head),'scope');foreach(['result.json','receipt.json']as$f)v92_need(!file_exists($dir.'/'.$f),'no_replay');
 $cfg=require $root.'/_preview/search3-anex-candidate/.andromeda-private.php';v92_need(is_array($cfg)&&is_string($cfg['catalog_path']??null),'config');$private=dirname($cfg['catalog_path']);$ops=dirname($dir);$roots=[$private,$ops];$files=0;$bytes=0;$matches=[];$bad=0;$seen=[];
 foreach($roots as$base){$baseReal=realpath($base);if(!$baseReal)continue;$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($baseReal,FilesystemIterator::SKIP_DOTS));foreach($it as$f){if(!$f->isFile()||$f->isLink()||!str_ends_with($f->getFilename(),'.json'))continue;$path=$f->getPathname();if(str_contains($path,'/'.$dir.'/'))continue;$sz=$f->getSize();if($sz<=0||$sz>16777216)continue;$files++;$bytes+=$sz;v92_need($files<=40000&&$bytes<=2147483648,'scan_budget');$raw=file_get_contents($path);$sha=hash('sha256',$raw);if(isset($seen[$sha]))continue;$seen[$sha]=true;if(!str_contains($raw,V92_CAT))continue;try{$j=json_decode($raw,true,128,JSON_THROW_ON_ERROR);}catch(Throwable){$bad++;continue;}$hits=[];v92_find($j,V92_CAT,'',0,$hits);foreach($hits as$h){$rel=str_starts_with($path,$ops.'/')?'operations/'.substr($path,strlen($ops)+1):'private/'.basename($path);$matches[]=['source_file'=>$rel,'file_sha256'=>$sha,'file_bytes'=>$sz,'json_pointer'=>$h['json_pointer'],'row'=>$h['row'],'file_canonical_sha256'=>w76_hash($j)];if(count($matches)>=20)break 2;}}
 }
 $out=['operation'=>V92_OP,'state'=>'completed_retained_missing_source_scan','source_sha'=>$head,'generated_at_utc'=>gmdate('c'),'files_examined'=>$files,'bytes_examined'=>$bytes,'unique_file_hashes'=>count($seen),'invalid_matching_json'=>$bad,'match_count'=>count($matches),'matches'=>$matches,'provider_http_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'safe_to_write_now'=>false,'no_replay'=>true];$sha=w76_save($dir.'/result.json',$out);w76_save($dir.'/receipt.json',['operation'=>V92_OP,'state'=>$out['state'],'source_sha'=>$head,'result_sha256'=>$sha,'provider_http_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true]);echo w76_json(array_diff_key($out,['matches'=>true]))."\n";return 0;}
if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__)exit(v92_main($argv));