<?php
declare(strict_types=1);

const HMTS_OPERATION='hotel-match-user-seen-common4-token-set-bridge-1971-20260918-v1';
const HMTS_LIMIT=100000;
const HMTS_EXCLUDED=[46=>true,47=>true];
const HMTS_GENERIC=['hotel'=>1,'hotels'=>1,'otel'=>1,'отель'=>1,'отели'=>1,'resort'=>1,'resorts'=>1,'spa'=>1];

function hmts_rows(PDO $p,string $q,array $a=[]): array {$s=$p->prepare($q);$s->execute(array_values($a));$r=$s->fetchAll(PDO::FETCH_ASSOC)?:[];if(count($r)>HMTS_LIMIT)throw new RuntimeException('row_budget');return $r;}
function hmts_norm(string $v): string {
    $v=mb_strtolower(trim($v),'UTF-8');
    $v=strtr($v,['ё'=>'е','é'=>'e','è'=>'e','ê'=>'e','ë'=>'e','á'=>'a','à'=>'a','ä'=>'a','â'=>'a','ã'=>'a','å'=>'a','ö'=>'o','ô'=>'o','ó'=>'o','ò'=>'o','õ'=>'o','ü'=>'u','ú'=>'u','ù'=>'u','û'=>'u','ç'=>'c','ş'=>'s','ğ'=>'g','ı'=>'i','İ'=>'i','ñ'=>'n','&'=>' ','+'=>' ','_'=>' ','-'=>' ']);
    $v=preg_replace('/[^\p{L}\p{N}]+/u',' ',$v)??$v;return trim(preg_replace('/\s+/u',' ',$v)??$v);
}
function hmts_product(string $v): bool {return (bool)preg_match('/^(?:fortuna|фортуна|roulette|рулетка|рулет)(?:\s|$)/u',hmts_norm($v));}
function hmts_forms(string $name): array {
    $raw=[];$add=static function(string $x)use(&$raw){$n=hmts_norm($x);if($n!=='')$raw[$n]=true;};$add($name);
    if(preg_match('/^(.+?)\s*\((?:EX\.?|FORMERLY|БЫВШ\.?)[^)]*\)/iu',$name,$m))$add($m[1]);
    if(preg_match_all('/\((?:EX\.?|FORMERLY|БЫВШ\.?)\s*([^)]*)\)/iu',$name,$m))foreach($m[1] as $x)foreach(preg_split('/[;|\/]+/u',$x)?:[] as $y)$add($y);
    $out=[];foreach(array_keys($raw) as $n){$t=preg_split('/\s+/u',$n,-1,PREG_SPLIT_NO_EMPTY)?:[];$t=array_values(array_filter($t,static fn($x)=>!isset(HMTS_GENERIC[$x])));if(!$t)continue;sort($t,SORT_STRING);$k=implode(' ',$t);if(mb_strlen($k,'UTF-8')>=4)$out[$k]=true;}return array_keys($out);
}
function hmts_scalar(array $a,array $keys): ?string {foreach($keys as $k)if(array_key_exists($k,$a)&&(is_string($a[$k])||is_int($a[$k]))){$v=trim((string)$a[$k]);if($v!=='')return $v;}return null;}
function hmts_id(mixed $v): ?string {if(!(is_int($v)||is_string($v)))return null;$s=trim((string)$v);return preg_match('/^[1-9][0-9]{0,31}$/D',$s)?$s:null;}
function hmts_sources(array $v,array &$out): void {foreach($v as $k=>$x){if(($k==='source'||$k==='source_candidate')&&is_array($x))$out[]=$x;if(is_array($x))hmts_sources($x,$out);}}
function hmts_route(array $s,string $ext): ?string {
    foreach(['hotelKey','external_hotel_id'] as $k)if(array_key_exists($k,$s)){ $seen=hmts_id($s[$k]); return $seen!==null&&hash_equals($ext,$seen)?$k:null; }
    if(array_key_exists('id',$s)){ $seen=hmts_id($s['id']); return $seen!==null&&hash_equals($ext,$seen)?'id':null; }
    return null;
}
function hmts_bound_source(array $e,string $ext): array {$xs=[];hmts_sources($e,$xs);$m=[];foreach($xs as $s){$r=hmts_route($s,$ext);if($r===null)continue;$score=$r==='hotelKey'?30:($r==='external_hotel_id'?20:10);if(hmts_scalar($s,['name','lName','hotel_name'])!==null)$score+=4;if(hmts_scalar($s,['stateKey','state','country'])!==null)$score+=2;if(hmts_scalar($s,['townKey','town'])!==null)$score++;$m[]=['source'=>$s,'route'=>$r,'score'=>$score];}if(!$m)return['source'=>[],'route'=>null];usort($m,fn($a,$b)=>$b['score']<=>$a['score']);return['source'=>$m[0]['source'],'route'=>$m[0]['route']];}
function hmts_best_source(array $e): array {$xs=[];hmts_sources($e,$xs);$best=[];$score=-1;foreach($xs as $s){$x=0;if(hmts_scalar($s,['hotelKey','external_hotel_id','id'])!==null)$x+=4;if(hmts_scalar($s,['name','lName','hotel_name'])!==null)$x+=3;if(hmts_scalar($s,['stateKey','state','country'])!==null)$x+=2;if(hmts_scalar($s,['townKey','town'])!==null)$x++;if($x>$score){$score=$x;$best=$s;}}return$best;}
function hmts_consensus(array $set): ?string {$x=array_keys($set);return count($x)===1?(string)$x[0]:null;}
function hmts_historical_candidates(array $e): array {$out=[];$walk=function(array $v)use(&$walk,&$out):void{foreach($v as $k=>$x){if($k==='candidate_ids'&&is_array($x))foreach($x as $id){$s=hmts_id($id);if($s!==null)$out[$s]=true;}if(is_array($x))$walk($x);}};$walk($e);$ids=array_keys($out);sort($ids,SORT_STRING);return$ids;}
function hmts_save(string $path,array $v): string {$raw=json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n";$f=@fopen($path,'x+b');if(!$f)throw new RuntimeException('durable_exists');try{if(fwrite($f,$raw)!==strlen($raw)||!fflush($f))throw new RuntimeException('durable_write');if(function_exists('fsync')&&!fsync($f))throw new RuntimeException('durable_sync');rewind($f);if(stream_get_contents($f)!==$raw)throw new RuntimeException('durable_readback');}finally{fclose($f);}return hash('sha256',$raw);}

if(in_array('--self-test',$argv??[],true)){
    $a=hmts_forms('THE GRAND HOTEL BEACH');$b=hmts_forms('Beach Grand The Resort');if(count(array_intersect($a,$b))!==1)throw new RuntimeException('order');
    if(count(array_intersect(hmts_forms('DELUXE SEA VIEW HOTEL 2'),hmts_forms('SEA VIEW DELUXE 2 RESORT')))!==1)throw new RuntimeException('qualifier_number');
    if(count(array_intersect(hmts_forms('DELUXE SEA VIEW 2'),hmts_forms('DELUXE SEA VIEW 3')))!==0)throw new RuntimeException('number_preserved');
    if(hmts_route(['id'=>'OFFER','hotelKey'=>123],'123')!=='hotelKey'||hmts_route(['id'=>123,'hotelKey'=>999],'123')!==null)throw new RuntimeException('identity');
    $e=['candidate_ids'=>[7,'8'],'nested'=>['candidate_ids'=>[8,9]]];if(hmts_historical_candidates($e)!==['7','8','9'])throw new RuntimeException('historical');
    echo "MATCH_COMMON4_TOKEN_SET_BRIDGE_SELFTEST_OK\n";exit(0);
}
if(PHP_SAPI!=='cli')exit(2);
$root=realpath((string)getenv('ANYTOUR_ROOT'));$op=(string)getenv('MATCH_OPERATION_DIR');$reg=realpath((string)getenv('MATCH_MAPPING_REGISTRY_PATH'));$sha=(string)getenv('MATCH_SOURCE_SHA');
if(!$root||$op===''||!is_string($reg)||!is_file($reg)||!preg_match('/^[a-f0-9]{40}$/D',$sha)||is_dir($op)||!mkdir($op,0700,true))throw new RuntimeException('runtime_guard');
hmts_save($op.'/reservation.json',['operation'=>HMTS_OPERATION,'state'=>'reserved_before_db_read','source_sha'=>$sha,'provider_access'=>false,'no_replay'=>true]);
require_once $reg;$dbf=is_file($root.'/data/db-v1.php')?$root.'/data/db-v1.php':$root.'/v2/data/db-v1.php';require_once $dbf;$pdo=v2_data_db();$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$pdo->exec('START TRANSACTION READ ONLY');
try{
    $registry=AnyTourAnexSearchMappingRegistry::fromPdo($pdo);$anex=[];foreach(hmts_rows($pdo,'SELECT anex_hotel_id FROM anex_hotel_search_mappings UNION SELECT anex_hotel_id FROM anex_hotel_decisions') as $r){$x=$registry->resolve('anex_online',(string)$r['anex_hotel_id'],'preview');if(is_int($x)&&$x>0)$anex[$x]=true;}
    $identity=hmts_rows($pdo,"SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' ORDER BY external_hotel_id");$and=[];$pending=[];foreach($identity as $r){if(($r['decision_status']??'')==='accepted'&&$r['local_hotel_id']!==null)$and[(int)$r['local_hotel_id']]=true;if(($r['decision_status']??'')==='pending'&&$r['local_hotel_id']===null)$pending[(string)$r['external_hotel_id']]=$r;}
    $seen=[];foreach(hmts_rows($pdo,"SELECT hotel_id,COUNT(*) n,MAX(observed_at) last_seen FROM tour_price_observations WHERE source='user_search' GROUP BY hotel_id") as $r)$seen[(int)$r['hotel_id']]=['n'=>(int)$r['n'],'last'=>(string)$r['last_seen']];$ids=array_keys($seen);if(!$ids)throw new RuntimeException('no_seen');$ph=implode(',',array_fill(0,count($ids),'?'));
    $front=[];foreach(hmts_rows($pdo,"SELECT id,country_id,country_name,region_id,region_name,subregion_id,subregion_name,name,category,is_active FROM catalog_hotels WHERE id IN ($ph)",$ids) as $h){$id=(int)$h['id'];$cid=(int)$h['country_id'];if((int)$h['is_active']!==1||isset(HMTS_EXCLUDED[$cid])||isset($anex[$id])||isset($and[$id])||hmts_product((string)$h['name']))continue;$front[$id]=$h+['observation_rows'=>$seen[$id]['n'],'last_observed_at'=>$seen[$id]['last']];}
    $fids=array_keys($front);if(!$fids)throw new RuntimeException('frontier_empty');$fh=implode(',',array_fill(0,count($fids),'?'));$common=[];foreach(hmts_rows($pdo,"SELECT DISTINCT hotel_id FROM tour_price_observations WHERE source='user_search' AND hotel_id IN ($fh) AND departure_date>=CURRENT_DATE AND operator_id IN(13,18,25,43)",$fids) as $r)$common[(int)$r['hotel_id']]=true;$targets=array_intersect_key($front,$common);if(!$targets)throw new RuntimeException('no_targets');
    $countries=[];foreach($targets as $h)$countries[(int)$h['country_id']]=true;$cids=array_keys($countries);$cph=implode(',',array_fill(0,count($cids),'?'));$all=[];$index=[];$countryNames=[];
    foreach(hmts_rows($pdo,"SELECT id,country_id,country_name,region_id,region_name,subregion_id,subregion_name,name,category,is_active FROM catalog_hotels WHERE is_active=1 AND country_id IN ($cph)",$cids) as $h){$id=(int)$h['id'];$cid=(int)$h['country_id'];$all[$id]=$h;$countryNames[$cid][hmts_norm((string)$h['country_name'])]=true;foreach(hmts_forms((string)$h['name']) as $k)$index[$cid][$k][$id][(string)$h['name']]=true;}
    foreach(hmts_rows($pdo,"SELECT a.hotel_id,a.alias,h.country_id FROM hotel_aliases a JOIN catalog_hotels h ON h.id=a.hotel_id WHERE h.is_active=1 AND h.country_id IN ($cph)",$cids) as $a){$id=(int)$a['hotel_id'];$raw=trim((string)$a['alias']);if($raw==='')continue;foreach(hmts_forms($raw) as $k)$index[(int)$a['country_id']][$k][$id][$raw]=true;}
    $stateSets=[];$townSets=[];$acceptedEvidence=0;foreach($identity as $r){if(($r['decision_status']??'')!=='accepted'||$r['local_hotel_id']===null)continue;$lid=(int)$r['local_hotel_id'];$h=$all[$lid]??null;if(!$h)continue;try{$e=json_decode((string)$r['evidence_json'],true,128,JSON_THROW_ON_ERROR);}catch(Throwable $x){continue;}$s=hmts_best_source($e);if(!$s)continue;$sk=hmts_scalar($s,['stateKey','provider_state_id','supplier_state_id']);$tk=hmts_scalar($s,['townKey','town_key','supplier_town_id']);if($sk!==null)$stateSets[$sk][(string)$h['country_id']]=true;if($tk!==null){$k=$h['country_id'].'|'.$tk;$townSets[$k]['region'][(string)($h['region_id']??'')]=true;$townSets[$k]['sub'][(string)($h['subregion_id']??'')]=true;$townSets[$k]['rows']=($townSets[$k]['rows']??0)+1;}$acceptedEvidence++;}
    $state=[];$stateConf=0;foreach($stateSets as $k=>$set){$v=hmts_consensus($set);if($v===null)$stateConf++;else$state[$k]=(int)$v;}$town=[];$townConf=0;foreach($townSets as $k=>$x){$rg=$x['region'];unset($rg['']);$sb=$x['sub'];unset($sb['']);$r=hmts_consensus($rg);$s=hmts_consensus($sb);if($r===null&&$s===null){$townConf++;continue;}$town[$k]=['region_id'=>$r===null?null:(int)$r,'subregion_id'=>$s===null?null:(int)$s,'accepted_rows'=>(int)$x['rows']];}
    $raw=[];$reasons=[];$routes=[];$hist=['agree'=>0,'disagree'=>0,'empty'=>0,'contains'=>0];foreach($pending as $extKey=>$r){$ext=hmts_id($extKey);if($ext===null){$reasons['invalid_external_id']=($reasons['invalid_external_id']??0)+1;continue;}try{$e=json_decode((string)$r['evidence_json'],true,128,JSON_THROW_ON_ERROR);}catch(Throwable $x){$reasons['invalid_evidence']=($reasons['invalid_evidence']??0)+1;continue;}$bound=hmts_bound_source($e,$ext);$s=$bound['source'];$route=$bound['route'];if(!$s||$route===null){$reasons['source_hotel_identity_unproven']=($reasons['source_hotel_identity_unproven']??0)+1;continue;}$routes[$route]=($routes[$route]??0)+1;
        $sk=hmts_scalar($s,['stateKey','provider_state_id','supplier_state_id']);$cid=$sk!==null?($state[$sk]??0):0;if($cid===0){$label=hmts_norm((string)(hmts_scalar($s,['state','country','country_name'])??''));$hits=[];if($label!=='')foreach($countryNames as $cc=>$names)if(isset($names[$label]))$hits[$cc]=true;if(count($hits)===1)$cid=(int)array_key_first($hits);}if($cid===0||!isset($countries[$cid])){$reasons['country_unresolved_or_outside']=($reasons['country_unresolved_or_outside']??0)+1;continue;}
        $sourceNames=[];foreach(['name','lName','hotel','hotel_name'] as $k){$v=trim((string)($s[$k]??''));if($v!=='')$sourceNames[$v]=true;}if(!$sourceNames){$reasons['no_source_name']=($reasons['no_source_name']??0)+1;continue;}$candidates=[];$matches=[];foreach(array_keys($sourceNames) as $sn)foreach(hmts_forms($sn) as $key)foreach($index[$cid][$key]??[] as $lid=>$rawForms){$candidates[(int)$lid]=true;foreach(array_keys($rawForms) as $rf)$matches[(int)$lid][]=['token_set'=>$key,'source_name'=>$sn,'target_form'=>$rf];}
        if(count($candidates)!==1){$reason=count($candidates)>1?'ambiguous_token_set':'no_exact_token_set';$reasons[$reason]=($reasons[$reason]??0)+1;continue;}$lid=(int)array_key_first($candidates);if(!isset($targets[$lid])){$reasons['unique_match_not_current_target']=($reasons['unique_match_not_current_target']??0)+1;continue;}$h=$targets[$lid];$tk=hmts_scalar($s,['townKey','town_key','supplier_town_id']);$tn=hmts_norm((string)(hmts_scalar($s,['town','town_name','region_name'])??''));$direct=$tn!==''&&in_array($tn,array_filter([hmts_norm((string)$h['region_name']),hmts_norm((string)$h['subregion_name'])]),true);$cross=$tk===null?null:($town[$cid.'|'.$tk]??null);$crossOk=$cross!==null&&(($cross['region_id']!==null&&(int)($h['region_id']??0)===$cross['region_id'])||($cross['subregion_id']!==null&&(int)($h['subregion_id']??0)===$cross['subregion_id']));if(!$direct&&!$crossOk){$reason=$cross!==null?'town_crosswalk_conflict':'geography_unproven';$reasons[$reason]=($reasons[$reason]??0)+1;continue;}
        $old=hmts_historical_candidates($e);if(!$old)$hist['empty']++;elseif($old===[(string)$lid])$hist['agree']++;elseif(in_array((string)$lid,$old,true))$hist['contains']++;else$hist['disagree']++;
        $raw[]=['external_hotel_id'=>$ext,'source_identity_route'=>$route,'local_hotel_id'=>$lid,'local_name'=>(string)$h['name'],'country_id'=>$cid,'country_name'=>(string)$h['country_name'],'region_id'=>$h['region_id']===null?null:(int)$h['region_id'],'region_name'=>(string)$h['region_name'],'subregion_id'=>$h['subregion_id']===null?null:(int)$h['subregion_id'],'subregion_name'=>(string)$h['subregion_name'],'source_names'=>array_keys($sourceNames),'source_town'=>$tn?:null,'state_key'=>$sk,'town_key'=>$tk,'geography_route'=>$direct?'direct_town_label':'accepted_town_crosswalk','matches'=>$matches[$lid]??[],'historical_candidate_ids'=>$old,'historical_candidate_agrees'=>$old===[(string)$lid],'observation_rows'=>(int)$h['observation_rows'],'pending_evidence_sha256'=>(string)($r['evidence_sha256']??'')];}
    $extLoc=[];$locExt=[];foreach($raw as $x){$extLoc[$x['external_hotel_id']][$x['local_hotel_id']]=true;$locExt[$x['local_hotel_id']][$x['external_hotel_id']]=true;}$safe=[];$holds=[];foreach($raw as $x){if(count($extLoc[$x['external_hotel_id']])!==1||count($locExt[$x['local_hotel_id']])!==1){$holds[]=$x;continue;}$safe[]=$x;}usort($safe,fn($a,$b)=>$b['observation_rows']<=>$a['observation_rows']?:$a['local_hotel_id']<=>$b['local_hotel_id']);ksort($routes);ksort($reasons);$pdo->rollBack();
    $result=['operation'=>HMTS_OPERATION,'status'=>'read_only_complete','source_sha'=>$sha,'current_unresolved_real'=>count($front),'current_common4_residual'=>count($targets),'pending_examined'=>count($pending),'accepted_evidence_rows_examined'=>$acceptedEvidence,'source_identity_route_counts'=>$routes,'state_crosswalk_keys'=>count($state),'state_crosswalk_conflicts'=>$stateConf,'town_crosswalk_keys'=>count($town),'town_crosswalk_conflicts'=>$townConf,'raw_candidate_count'=>count($raw),'safe_one_to_one_count'=>count($safe),'safe_candidates'=>$safe,'collision_holds'=>array_slice($holds,0,200),'historical_candidate_diagnostics'=>$hist,'reason_counts'=>$reasons,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0];
}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$result=['operation'=>HMTS_OPERATION,'status'=>'failed_read_only','source_sha'=>$sha,'reason'=>preg_replace('/[^a-z0-9_\-]/i','_',mb_substr($e->getMessage(),0,120)),'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0];}
$d=hmts_save($op.'/result.json',$result);hmts_save($op.'/receipt.json',['operation'=>HMTS_OPERATION,'status'=>$result['status'],'result_sha256'=>$d,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);echo json_encode($result,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";exit(($result['status']??'')==='read_only_complete'?0:2);
