<?php
declare(strict_types=1);
/** MATCH #1971 — strict CURRENT pre-write audit for 28 immutable strong evidence pairs. READ ONLY. */
const HMPW_OPERATION='hotel-match-strong-prewrite-audit-1971-20260912-v1';
const HMPW_MAX_HOTELS=200000;
const HMPW_MAX_ALIASES=1000000;

function hmpw_int($v): ?int {return is_numeric($v)&&(int)$v>0?(int)$v:null;}
function hmpw_table(PDO $pdo,string $t): bool {$q=$pdo->prepare('SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?');$q->execute([$t]);return $q->fetchColumn()!==false;}
function hmpw_cols(PDO $pdo,string $t): array {$q=$pdo->query('SHOW COLUMNS FROM `'.$t.'`');return $q?$q->fetchAll(PDO::FETCH_COLUMN):[];}
function hmpw_pick(array $cols,array $want): ?string {foreach($want as $c)if(in_array($c,$cols,true))return $c;return null;}
function hmpw_translit(string $s): string {$m=['а'=>'a','б'=>'b','в'=>'v','г'=>'g','д'=>'d','е'=>'e','ё'=>'e','ж'=>'zh','з'=>'z','и'=>'i','й'=>'y','к'=>'k','л'=>'l','м'=>'m','н'=>'n','о'=>'o','п'=>'p','р'=>'r','с'=>'s','т'=>'t','у'=>'u','ф'=>'f','х'=>'h','ц'=>'ts','ч'=>'ch','ш'=>'sh','щ'=>'shch','ъ'=>'','ы'=>'y','ь'=>'','э'=>'e','ю'=>'yu','я'=>'ya'];return strtr(mb_strtolower($s,'UTF-8'),$m);}
function hmpw_norm(string $s,bool $generic=false): string {$s=mb_strtoupper(str_replace(['ё','Ё','&'],['е','Е',' AND '],trim($s)),'UTF-8');$s=preg_replace('/[^\p{L}\p{N}]+/u',' ',$s)??$s;$p=preg_split('/\s+/u',trim($s),-1,PREG_SPLIT_NO_EMPTY)?:[];if($generic){$g=['HOTEL'=>1,'HOTELS'=>1,'RESORT'=>1,'SPA'=>1,'OTEL'=>1,'ОТЕЛЬ'=>1,'ОТЕЛЯ'=>1];$p=array_values(array_filter($p,static fn($x)=>!isset($g[$x])));}return implode(' ',$p);}
function hmpw_country(string $s): ?string {$n=hmpw_norm($s);$map=['EGYPT'=>['EGYPT','ЕГИПЕТ'],'TURKEY'=>['TURKEY','TURKIYE','TÜRKIYE','ТУРЦИЯ'],'THAILAND'=>['THAILAND','ТАИЛАНД'],'UAE'=>['UAE','UNITED ARAB EMIRATES','ОАЭ','ОБЪЕДИНЕННЫЕ АРАБСКИЕ ЭМИРАТЫ'],'VIETNAM'=>['VIETNAM','VIET NAM','ВЬЕТНАМ'],'SRILANKA'=>['SRI LANKA','ШРИ ЛАНКА'],'MALDIVES'=>['MALDIVES','МАЛЬДИВЫ'],'CUBA'=>['CUBA','КУБА']];foreach($map as $k=>$v)if(in_array($n,$v,true))return $k;return null;}
function hmpw_geo(array $fields): array {$o=[];foreach($fields as $field){if(!is_scalar($field))continue;$raw=trim((string)$field);if($raw==='')continue;$parts=[$raw];foreach(preg_split('/[-\/,;()]+/u',$raw,-1,PREG_SPLIT_NO_EMPTY)?:[] as $p)if(mb_strlen(trim($p),'UTF-8')>=3)$parts[]=trim($p);foreach($parts as $p)foreach([$p,hmpw_translit($p)] as $x){$n=hmpw_norm($x,true);if($n!=='')$o[$n]=true;}}return array_keys($o);}
function hmpw_keys(string $name,array $geo): array {$seed=[];$base=hmpw_norm($name,true);if($base!=='')$seed[$base]=true;$without=preg_replace('/\s*\([^)]*\)\s*/u',' ',$name)??$name;$n=hmpw_norm($without,true);if($n!=='')$seed[$n]=true;for($i=0;$i<3;$i++){foreach(array_keys($seed) as $vv)foreach($geo as $gg){$v=(string)$vv;$g=(string)$gg;if($g===''||$v===$g)continue;if(str_starts_with($v,$g.' '))$seed[trim(substr($v,strlen($g)))]=true;if(str_ends_with($v,' '.$g))$seed[trim(substr($v,0,-strlen($g)))]=true;}}return array_values(array_filter(array_keys($seed),static fn($x)=>(string)$x!==''));}
function hmpw_walk($v,array &$names,array &$geo,int $depth=0): void {if($depth>10||!is_array($v))return;foreach($v as $k=>$x){$key=mb_strtolower((string)$k,'UTF-8');if(is_scalar($x)){if(in_array($key,['name','lname','hotel','hotelname','hotel_name'],true)&&trim((string)$x)!=='')$names[(string)$x]=true;if(in_array($key,['region','regionname','region_name','town','townname','town_name','city','cityname','resort','resortname'],true)&&trim((string)$x)!=='')$geo[(string)$x]=true;}elseif(is_array($x))hmpw_walk($x,$names,$geo,$depth+1);}}
function hmpw_query_ids(PDO $pdo,string $table,string $idCol,array $ids,array $wanted): array {if(!$ids||!hmpw_table($pdo,$table))return [];$cols=hmpw_cols($pdo,$table);if(!in_array($idCol,$cols,true))return [];$sel=array_values(array_unique(array_merge([$idCol],array_intersect($wanted,$cols))));$out=[];foreach(array_chunk(array_values($ids),500) as $c){$q=$pdo->prepare('SELECT `'.implode('`,`',$sel).'` FROM `'.$table.'` WHERE `'.$idCol.'` IN ('.implode(',',array_fill(0,count($c),'?')).')');$q->execute($c);foreach($q->fetchAll(PDO::FETCH_ASSOC) as $r)$out[]=$r;}return $out;}
function hmpw_manifest(string $p): array {$m=json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);if(($m['schema']??'')!=='hotel-match-current-strong-prewrite/1'||($m['not_write_authority']??false)!==true||count($m['pairs']??[])!==28||($m['source_result_sha256']??'')!=='0195a9965c881ce1367da98cf2b21183eea7fe502cb824c64912084f9d649040')throw new RuntimeException('manifest_guard');return $m;}
function hmpw_digest(array $v): string {ksort($v);return hash('sha256',json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR));}

function hmpw_run(PDO $pdo,array $manifest): array {
    $pairs=$manifest['pairs'];$targetCounts=[];foreach($pairs as $p)$targetCounts[(int)$p['proposed_local_id']]=($targetCounts[(int)$p['proposed_local_id']]??0)+1;
    $catalogCols=hmpw_cols($pdo,'catalog_hotels');$wanted=array_values(array_intersect(['id','name','country_id','country_name','region_name','subregion_name','category','rating','is_active','latitude','longitude','lat','lon','lng'],$catalogCols));
    $rows=$pdo->query('SELECT `'.implode('`,`',$wanted).'` FROM catalog_hotels WHERE is_active=1 LIMIT '.(HMPW_MAX_HOTELS+1))->fetchAll(PDO::FETCH_ASSOC);if(count($rows)>HMPW_MAX_HOTELS)throw new RuntimeException('catalog_bound');$locals=[];$index=[];
    foreach($rows as $r){$id=hmpw_int($r['id']??null);if(!$id)continue;$geo=hmpw_geo([$r['region_name']??'',$r['subregion_name']??'']);$r['_geo']=$geo;$r['_aliases']=[];$locals[$id]=$r;foreach(hmpw_keys((string)($r['name']??''),$geo) as $k)$index[(string)($r['country_id']??'')][(string)$k][$id]=true;}
    if(hmpw_table($pdo,'hotel_aliases')){$c=hmpw_cols($pdo,'hotel_aliases');$nc=hmpw_pick($c,['alias','name']);if($nc&&in_array('hotel_id',$c,true)){$ar=$pdo->query('SELECT hotel_id,`'.$nc.'` alias FROM hotel_aliases LIMIT '.(HMPW_MAX_ALIASES+1))->fetchAll(PDO::FETCH_ASSOC);if(count($ar)>HMPW_MAX_ALIASES)throw new RuntimeException('alias_bound');foreach($ar as $a){$id=hmpw_int($a['hotel_id']??null);if(!$id||!isset($locals[$id]))continue;$alias=(string)$a['alias'];$locals[$id]['_aliases'][]=$alias;foreach(hmpw_keys($alias,$locals[$id]['_geo']) as $k)$index[(string)$locals[$id]['country_id']][(string)$k][$id]=true;}}}
    $anIds=[];$andIds=[];foreach($pairs as $p){if($p['provider']==='anex')$anIds[]=(int)$p['external_hotel_id'];else $andIds[]=(string)$p['external_hotel_id'];}
    $stage=[];foreach(hmpw_query_ids($pdo,'anex_hotels','anex_hotel_id',$anIds,['api_name','xml_name','xml_alternate_name','api_country','api_region','api_town']) as $r)$stage[(int)$r['anex_hotel_id']]=$r;
    $aobs=[];foreach(hmpw_query_ids($pdo,'anex_search_hotel_observations','anex_hotel_id',$anIds,['hotel_name','country_id','country_name','region_name']) as $r)$aobs[(int)$r['anex_hotel_id']][]=$r;
    $dec=[];if(hmpw_table($pdo,'anex_hotel_decisions'))foreach(hmpw_query_ids($pdo,'anex_hotel_decisions','anex_hotel_id',$anIds,['catalog_hotel_id','decision_status','status','decision']) as $r)$dec[(int)$r['anex_hotel_id']][]=$r;
    $exc=[];if(hmpw_table($pdo,'anex_review_pair_exclusions')){$c=hmpw_cols($pdo,'anex_review_pair_exclusions');$lc=in_array('catalog_hotel_id',$c,true)?'catalog_hotel_id':(in_array('local_hotel_id',$c,true)?'local_hotel_id':null);if($lc)foreach(hmpw_query_ids($pdo,'anex_review_pair_exclusions','anex_hotel_id',$anIds,[$lc]) as $r){$a=(int)$r['anex_hotel_id'];$l=hmpw_int($r[$lc]??null);if($l)$exc[$a][$l]=true;}}
    $and=[];foreach(hmpw_query_ids($pdo,'andromeda_hotel_identities','external_hotel_id',$andIds,['supplier_namespace','country_id','local_hotel_id','decision_status','evidence_json']) as $r)$and[(string)$r['external_hotel_id']][]=$r;
    $andObs=[];foreach(hmpw_query_ids($pdo,'andromeda_search_hotel_observations','external_hotel_id',$andIds,['supplier_namespace','hotel_name','country_id','country_name','region_name']) as $r)$andObs[(string)$r['external_hotel_id']][]=$r;
    $registry=AnyTourAnexSearchMappingRegistry::fromPdo($pdo);$resolve=$registry->previewResolver();
    $out=['status'=>'read_only_complete','operation_id'=>HMPW_OPERATION,'source_result_sha256'=>$manifest['source_result_sha256'],'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'safe'=>[],'blocked'=>[],'counts'=>[]];
    foreach($pairs as $p){$provider=(string)$p['provider'];$eid=(string)$p['external_hotel_id'];$target=(int)$p['proposed_local_id'];$row=['provider'=>$provider,'external_hotel_id'=>$eid,'proposed_local_id'=>$target,'duplicate_target_count'=>$targetCounts[$target]??1,'matched_keys'=>$p['matched_keys']];$block=null;if(!isset($locals[$target]))$block='target_inactive';else{$t=$locals[$target];$tcid=(int)($t['country_id']??0);$targetClass=hmpw_country((string)($t['country_name']??''));$names=[];$geo=[];$countryIds=[];$countryClasses=[];
        if($provider==='anex'){$current=$resolve('anex_online',$eid);if(is_int($current)&&$current>0)$block=$current===$target?'already_same':'target_drift';if(!$block&&!empty($dec[(int)$eid]))$block='manual_protected';if(!$block&&isset($exc[(int)$eid][$target]))$block='excluded';$s=$stage[(int)$eid]??[];foreach(['api_name','xml_name','xml_alternate_name'] as $k)if(trim((string)($s[$k]??''))!=='')$names[(string)$s[$k]]=true;foreach(['api_region','api_town'] as $k)if(trim((string)($s[$k]??''))!=='')$geo[(string)$s[$k]]=true;if(($cc=hmpw_country((string)($s['api_country']??'')))!==null)$countryClasses[$cc]=true;foreach($aobs[(int)$eid]??[] as $o){if(trim((string)($o['hotel_name']??''))!=='')$names[(string)$o['hotel_name']]=true;if(($i=hmpw_int($o['country_id']??null))!==null)$countryIds[$i]=true;if(($cc=hmpw_country((string)($o['country_name']??'')))!==null)$countryClasses[$cc]=true;if(trim((string)($o['region_name']??''))!=='')$geo[(string)$o['region_name']]=true;}}
        else{$entries=$and[$eid]??[];$namespaces=[];$states=[];$localsSeen=[];foreach($entries as $e){$namespaces[(string)($e['supplier_namespace']??'')]=true;$states[(string)($e['decision_status']??'')]=true;if(($i=hmpw_int($e['country_id']??null))!==null)$countryIds[$i]=true;if(($i=hmpw_int($e['local_hotel_id']??null))!==null)$localsSeen[$i]=true;$raw=json_decode((string)($e['evidence_json']??''),true);if(is_array($raw))hmpw_walk($raw,$names,$geo);}if(!$block&&(count($namespaces)!==1||!isset($namespaces['andromeda_catalog'])))$block='namespace_guard';if(!$block&&isset($states['conflict']))$block='conflict';if(!$block&&$localsSeen)$block=isset($localsSeen[$target])?'already_same':'target_drift';if(!$block&&$states&&!isset($states['pending']))$block='status_not_pending';foreach($andObs[$eid]??[] as $o){if(trim((string)($o['hotel_name']??''))!=='')$names[(string)$o['hotel_name']]=true;if(($i=hmpw_int($o['country_id']??null))!==null)$countryIds[$i]=true;if(($cc=hmpw_country((string)($o['country_name']??'')))!==null)$countryClasses[$cc]=true;if(trim((string)($o['region_name']??''))!=='')$geo[(string)$o['region_name']]=true;}}
        if(!$block&&$countryIds&&(!isset($countryIds[$tcid])||count($countryIds)!==1))$block='country_id_conflict';if(!$block&&$countryClasses&&($targetClass===null||!isset($countryClasses[$targetClass])||count($countryClasses)!==1))$block='country_name_conflict';if(!$block&&!$countryIds&&!$countryClasses)$block='country_authority_missing';
        $expected=[];foreach($p['source_names'] as $n)$expected[hmpw_norm((string)$n,false)]=true;$currentNames=[];foreach(array_keys($names) as $n)$currentNames[hmpw_norm((string)$n,false)]=true;if(!$block&&!array_intersect_key($expected,$currentNames))$block='source_name_changed';
        $geoForms=hmpw_geo(array_keys($geo));$sourceKeys=[];foreach(array_keys($names) as $n)foreach(hmpw_keys($n,$geoForms) as $k)$sourceKeys[(string)$k]=true;$targetKeys=[];foreach(array_merge([(string)$t['name']],$t['_aliases']) as $n)foreach(hmpw_keys($n,$t['_geo']) as $k)$targetKeys[(string)$k]=true;$expectedKeys=array_fill_keys(array_map('strval',$p['matched_keys']),true);if(!$block&&!array_intersect_key($expectedKeys,$sourceKeys))$block='source_key_changed';if(!$block&&!array_intersect_key($expectedKeys,$targetKeys))$block='target_key_changed';
        if(!$block){$cands=[];foreach(array_keys($expectedKeys) as $k)foreach($index[(string)$tcid][$k]??[] as $lid=>$_)$cands[(int)$lid]=true;if(count($cands)!==1||!isset($cands[$target]))$block='current_uniqueness_changed';}
        $sourceDigest=hmpw_digest(['provider'=>$provider,'external'=>$eid,'names'=>array_values(array_keys($currentNames)),'geo'=>array_values(array_keys($geo)),'country_ids'=>array_values(array_keys($countryIds)),'country_classes'=>array_values(array_keys($countryClasses))]);$aliases=$t['_aliases'];sort($aliases);$targetDigest=hmpw_digest(['id'=>$target,'name'=>(string)$t['name'],'aliases'=>$aliases,'country_id'=>$tcid,'country_name'=>(string)($t['country_name']??''),'region_name'=>(string)($t['region_name']??''),'subregion_name'=>(string)($t['subregion_name']??''),'category'=>$t['category']??null,'rating'=>$t['rating']??null,'is_active'=>(int)($t['is_active']??0)]);$row+=['source_digest'=>$sourceDigest,'target_digest'=>$targetDigest,'country_authority'=>['ids'=>array_map('intval',array_keys($countryIds)),'classes'=>array_values(array_keys($countryClasses))],'current_source_names'=>array_values(array_keys($names))];}
        $bucket=$block??'safe_prewrite';$out['counts'][$bucket]=($out['counts'][$bucket]??0)+1;if($block)$row['block_reason']=$block;$out[$block?'blocked':'safe'][]=$row;}
    ksort($out['counts']);$out['safe_count']=count($out['safe']);return $out;
}

if(in_array('--self-test',$_SERVER['argv']??[],true)){if(hmpw_norm('Martinenz Hotel.',true)!=='MARTINENZ')exit(2);if(!in_array('HOLIDAY INN VANA NAVA',hmpw_keys('Holiday Inn Resort Vana Nava Hua Hin',hmpw_geo(['Хуа Хин'])),true))exit(3);if(hmpw_country('Турция')!=='TURKEY')exit(4);echo "MATCH strong prewrite audit self-test PASS; network=0 database=0\n";exit(0);}

if(!defined('HMPW_LIBRARY_ONLY')){error_reporting(0);$pdo=null;try{if(PHP_SAPI!=='cli')throw new RuntimeException('cli_only');$root=realpath(getcwd());if(!$root||basename($root)!=='anytoour.ru')throw new RuntimeException('root');$manifest=hmpw_manifest(getenv('HMPW_MANIFEST_PATH')?:$root.'/reports/hotel-match-current-strong-prewrite-1971.json');require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');require_once $root.'/app/integrations/anex-search-mapping-registry.php';$pdo=v2_data_db();$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$pdo->exec('START TRANSACTION READ ONLY');$r=hmpw_run($pdo,$manifest);$pdo->rollBack();$pdo=null;echo 'HMPW_JSON:'.json_encode($r,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR).PHP_EOL;}catch(Throwable $e){if($pdo instanceof PDO&&$pdo->inTransaction())$pdo->rollBack();echo 'HMPW_JSON:'.json_encode(['status'=>'failed','operation_id'=>HMPW_OPERATION,'reason'=>preg_replace('/[^A-Za-z0-9_:. -]/','?',substr($e->getMessage(),0,180)),'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0],JSON_UNESCAPED_SLASHES).PHP_EOL;exit(2);}}
