<?php
declare(strict_types=1);
if (!defined('FC_LIBRARY_ONLY')) define('FC_LIBRARY_ONLY', true);
require_once __DIR__ . '/hotel_match_anex_andromeda_direct_catalog_hardened.php';

const HMAMGR_OPERATION='hotel-match-anex-andromeda-mutual-graph-review-1971-20260911-v1';
const HMAMGR_FUZZY_MIN=0.90;
const HMAMGR_MARGIN_MIN=0.18;
const HMAMGR_COORD_BLOCK_M=5000.0;
const HMAMGR_COORD_DIRECT_M=1000.0;

function hmamgr_validation(array $a,array $b):string{
 $a=array_values(array_unique(array_map('intval',$a)));$b=array_values(array_unique(array_map('intval',$b)));if($a&&$b)return array_intersect($a,$b)?'same_local':'different_local';if($a)return'anex_only';if($b)return'andromeda_only';return'neither_side';
}
function hmamgr_andromeda_rows(PDO $db):array{
 $sha=fc_sha_countries($db);$obs=[];$cnt=[];foreach($db->query("SELECT * FROM andromeda_search_hotel_observations WHERE supplier_namespace='andromeda_catalog' ORDER BY observed_at_utc DESC,external_hotel_id")->fetchAll(PDO::FETCH_ASSOC)as$o){$id=(string)$o['external_hotel_id'];$cnt[$id]=($cnt[$id]??0)+1;if(!isset($obs[$id]))$obs[$id]=$o;}$rows=[];foreach($db->query("SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' ORDER BY external_hotel_id")->fetchAll(PDO::FETCH_ASSOC)as$r){$id=(string)$r['external_hotel_id'];$o=$obs[$id]??null;$country=(int)($o['country_id']??0);if(!isset(HMADCR_CORE8[$country]))$country=(int)($sha[$r['catalog_sha256']]??0);if(!isset(HMADCR_CORE8[$country]))continue;$s=hmgcr_andromeda_source($r,$o);$names=hmadcr_expand_names($s['names']);if(!$names)continue;$local=($r['decision_status']==='accepted'&&$r['local_hotel_id']!==null)?[(int)$r['local_hotel_id']]:[];$rows[$id]=['id'=>$id,'country_id'=>$country,'names'=>$names,'places'=>$s['places'],'latitude'=>$s['latitude'],'longitude'=>$s['longitude'],'category'=>$s['category'],'live'=>(int)($cnt[$id]??0)>0,'observation_count'=>(int)($cnt[$id]??0),'local_ids'=>$local];}return$rows;
}
function hmamgr_anex_rows(PDO $db):array{
 $local=[];foreach($db->query('SELECT anex_hotel_id,catalog_hotel_id FROM anex_hotel_search_mappings WHERE enabled=1')->fetchAll(PDO::FETCH_ASSOC)as$r)$local[(int)$r['anex_hotel_id']][(int)$r['catalog_hotel_id']]=true;foreach($db->query("SELECT anex_hotel_id,catalog_hotel_id FROM anex_hotel_decisions WHERE decision_status='accepted' AND catalog_hotel_id IS NOT NULL")->fetchAll(PDO::FETCH_ASSOC)as$r)$local[(int)$r['anex_hotel_id']][(int)$r['catalog_hotel_id']]=true;$obs=[];$cnt=[];foreach($db->query('SELECT * FROM anex_search_hotel_observations ORDER BY search_count DESC,last_seen_utc DESC,anex_hotel_id')->fetchAll(PDO::FETCH_ASSOC)as$o){$id=(int)$o['anex_hotel_id'];$cnt[$id]=max((int)($cnt[$id]??0),(int)($o['search_count']??0));if(!isset($obs[$id]))$obs[$id]=$o;}$stage=[];foreach($db->query('SELECT * FROM anex_hotels ORDER BY anex_hotel_id')->fetchAll(PDO::FETCH_ASSOC)as$s)$stage[(int)$s['anex_hotel_id']]=$s;$ids=[];foreach(array_keys($stage)as$id)$ids[$id]=true;foreach(array_keys($obs)as$id)$ids[$id]=true;$rows=[];foreach(array_keys($ids)as$id){$s=$stage[$id]??[];$o=$obs[$id]??[];$country=(int)($o['country_id']??0);if(!isset(HMADCR_CORE8[$country]))$country=(int)(fc_country($s['api_country']??'')??0);if(!isset(HMADCR_CORE8[$country]))continue;$names=hmadcr_expand_names(array_values(array_unique(array_filter([(string)($o['hotel_name']??''),(string)($s['api_name']??''),(string)($s['xml_name']??''),(string)($s['xml_alternate_name']??'')],static fn($v)=>trim($v)!==''))));if(!$names)continue;$rows[(string)$id]=['id'=>(string)$id,'country_id'=>$country,'names'=>$names,'places'=>array_values(array_unique(array_filter([(string)($s['api_region']??''),(string)($s['api_town']??''),(string)($o['region_name']??'')],static fn($v)=>trim($v)!==''))),'latitude'=>fc_num($s['latitude']??null),'longitude'=>fc_num($s['longitude']??null),'live'=>isset($obs[$id]),'observation_count'=>(int)($cnt[$id]??0),'local_ids'=>array_map('intval',array_keys($local[$id]??[]))];}return$rows;
}
function hmamgr_index(array $rows):array{return hmadcr_build_index(array_map(static fn($r)=>['country_id'=>$r['country_id'],'names'=>$r['names'],'places'=>$r['places']],$rows));}
function hmamgr_candidates(array $source,array $targets,array $index):array{
 $ids=hmadcr_candidate_ids(['names'=>$source['names'],'places'=>$source['places']],(int)$source['country_id'],$index,160);$out=[];foreach($ids as$id){$id=(string)$id;if(!isset($targets[$id]))continue;$t=$targets[$id];$pair=hmadcr_best_pair($source['names'],$t['names'],$source['places'],$t['places']);if(!($pair['critical_ok']??false)||($pair['rank_score']??0)<=0)continue;$distance=fc_dist($source['latitude'],$source['longitude'],$t['latitude'],$t['longitude']);$place=hmgcr_place($source['places'],$t['places']);$validation=hmamgr_validation($source['local_ids'],$t['local_ids']);$direct=$place||($distance!==null&&(float)$distance<=HMAMGR_COORD_DIRECT_M);$route=null;if($distance!==null&&(float)$distance>HMAMGR_COORD_BLOCK_M){$route='coordinate_conflict';}elseif(($pair['exact_bag']??false)&&(int)$pair['shared']>=3)$route='mutual_exact_3plus';elseif(($pair['exact_bag']??false)&&(int)$pair['shared']>=2&&$direct)$route='mutual_exact_geo';elseif(($pair['exact_bag']??false)&&(int)$pair['shared']>=2)$route='mutual_exact_no_geo';elseif((int)$pair['aligned']>=3&&(float)$pair['fuzzy_score']>=HMAMGR_FUZZY_MIN&&(float)$pair['char_similarity']>=HMAMGR_FUZZY_MIN&&$direct)$route='mutual_high_fuzzy_geo';$out[$id]=['target_id'=>$id,'pair'=>$pair,'distance_m'=>$distance===null?null:round((float)$distance,2),'place_match'=>$place,'validation'=>$validation,'route'=>$route,'target'=>$t];}return$out;
}
function hmamgr_choose(array $source,array $targets,array $index,array $locality):array{
 $pool=hmamgr_candidates($source,$targets,$index);$eligible=[];$hard=[];foreach($pool as$id=>$c){if($c['route']==='coordinate_conflict'){$hard[$id]=$c;continue;}if($c['route']===null)continue;$anchors=hmadcrh_identity_anchors($c['pair'],$c['target'],$locality);$c['identity_anchors']=$anchors;if((int)$anchors['identity_aligned']<2)continue;if($c['validation']==='different_local'){$hard[$id]=$c;continue;}$eligible[$id]=$c;}if(!$eligible)return['bucket'=>$hard?'hard_conflict':'unresolved','reason'=>$hard?'mutual_existing_or_coordinate_conflict':'no_mutual_safe_candidate','hard'=>$hard];
 $exact=array_filter($eligible,static fn($c)=>str_starts_with((string)$c['route'],'mutual_exact_'));$candidate=null;$margin=1.0;if($exact){if(count($exact)===1)$candidate=reset($exact);else{$same=array_values(array_filter($exact,static fn($c)=>$c['validation']==='same_local'));if(count($same)===1)$candidate=$same[0];else{$geo=array_values(array_filter($exact,static fn($c)=>(bool)$c['place_match']||($c['distance_m']!==null&&(float)$c['distance_m']<=HMAMGR_COORD_DIRECT_M)));if(count($geo)===1)$candidate=$geo[0];else return['bucket'=>'ambiguous','reason'=>'multiple_mutual_exact_candidates','candidate_count'=>count($exact)];}}
 }else{$vals=array_values($eligible);usort($vals,static fn($a,$b)=>$b['pair']['rank_score']<=>$a['pair']['rank_score']?:$b['pair']['aligned']<=>$a['pair']['aligned']);$candidate=$vals[0];$second=$vals[1]??null;$margin=$second?(float)$candidate['pair']['rank_score']-(float)$second['pair']['rank_score']:1.0;if($margin<HMAMGR_MARGIN_MIN)return['bucket'=>'ambiguous','reason'=>'mutual_fuzzy_margin_small','score_margin'=>round($margin,6)];}
 return['bucket'=>'candidate','reason'=>$candidate['route'],'target_id'=>$candidate['target_id'],'score_margin'=>round($margin,6),'candidate'=>$candidate];
}
function hmamgr_review(PDO $db,string $operation=HMAMGR_OPERATION):array{
 if($operation!==HMAMGR_OPERATION)throw new RuntimeException('operation_scope');$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION READ ONLY');try{$coverage=fc_coverage($db);$an=hmamgr_anex_rows($db);$and=hmamgr_andromeda_rows($db);$anIndex=hmamgr_index($an);$andIndex=hmamgr_index($and);$anLoc=hmadcrh_locality_common($an);$andLoc=hmadcrh_locality_common($and);$prepared=[];$amb=[];$hard=[];$stats=['anex_rows'=>count($an),'andromeda_rows'=>count($and),'examined'=>0,'mutual_pairs'=>0,'same_local'=>0,'new_one_side'=>0,'new_neither_side'=>0,'hard_conflict'=>0,'ambiguous'=>0,'live_new'=>0,'route_exact_3plus'=>0,'route_exact_geo'=>0,'route_exact_no_geo'=>0,'route_high_fuzzy_geo'=>0];
 foreach($an as$aid=>$a){$stats['examined']++;$forward=hmamgr_choose($a,$and,$andIndex,$andLoc);if(($forward['bucket']??'')!=='candidate'){if(($forward['bucket']??'')==='hard_conflict'){$hard[]=['anex_hotel_id'=>(int)$aid,'stage'=>'forward']+$forward;$stats['hard_conflict']++;}elseif(($forward['bucket']??'')==='ambiguous'){$amb[]=['anex_hotel_id'=>(int)$aid,'stage'=>'forward']+$forward;$stats['ambiguous']++;}continue;}$andId=(string)$forward['target_id'];$b=$and[$andId];$reverse=hmamgr_choose($b,$an,$anIndex,$anLoc);if(($reverse['bucket']??'')!=='candidate'||(string)($reverse['target_id']??'')!==(string)$aid){$amb[]=['anex_hotel_id'=>(int)$aid,'andromeda_external_id'=>$andId,'stage'=>'reverse','forward'=>$forward,'reverse'=>$reverse];$stats['ambiguous']++;continue;}$validation=hmamgr_validation($a['local_ids'],$b['local_ids']);if($validation==='different_local'){$hard[]=['anex_hotel_id'=>(int)$aid,'andromeda_external_id'=>$andId,'reason'=>'mutual_existing_local_conflict','forward'=>$forward,'reverse'=>$reverse];$stats['hard_conflict']++;continue;}$route=(string)$forward['reason'];$row=['anex_hotel_id'=>(int)$aid,'andromeda_external_id'=>$andId,'country_id'=>(int)$a['country_id'],'validation'=>$validation,'route'=>$route,'anex_local_ids'=>$a['local_ids'],'andromeda_local_ids'=>$b['local_ids'],'anex_names'=>$a['names'],'andromeda_names'=>$b['names'],'anex_places'=>$a['places'],'andromeda_places'=>$b['places'],'anex_live'=>$a['live'],'andromeda_live'=>$b['live'],'anex_observation_count'=>$a['observation_count'],'andromeda_observation_count'=>$b['observation_count'],'forward'=>$forward,'reverse'=>$reverse];$prepared[]=$row;$stats['mutual_pairs']++;if($validation==='same_local')$stats['same_local']++;elseif($validation==='neither_side'){$stats['new_neither_side']++;if($a['live']||$b['live'])$stats['live_new']++;}else{$stats['new_one_side']++;if($a['live']||$b['live'])$stats['live_new']++;}$rk='route_'.str_replace('mutual_','',$route);if(isset($stats[$rk]))$stats[$rk]++;}
 $byAnd=[];foreach($prepared as$i=>$r)$byAnd[$r['andromeda_external_id']][]=$i;$collisions=0;$keep=[];foreach($prepared as$i=>$r){if(count($byAnd[$r['andromeda_external_id']])>1){$collisions++;$amb[]=$r+['stage'=>'post_mutual_collision','reason'=>'post_mutual_target_collision'];$stats['ambiguous']++;}else$keep[]=$r;}$prepared=$keep;$stats['post_mutual_collision_demotions']=$collisions;$stats['mutual_pairs']=count($prepared);$db->commit();return['status'=>'completed','operation_id'=>$operation,'mode'=>'current_core8_anex_andromeda_mutual_graph_read_only','database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'historical_operations_replayed'=>false,'coverage'=>$coverage,'stats'=>$stats,'prepared'=>$prepared,'hard_conflicts'=>$hard,'ambiguous'=>$amb,'guards'=>['mutual_unique_winner_required'=>true,'locality_hardened_non_local_identity_anchors_min'=>2,'coordinate_conflict_block_m'=>HMAMGR_COORD_BLOCK_M,'critical_qualifiers_preserved'=>['ANNEX','BEACH','GARDEN','NORTH','SOUTH'],'generic_hotel_resort_spa_non_identity'=>true,'existing_local_ids_validation_only'=>true,'different_local_hard_block'=>true,'stars_not_identity'=>true,'core8_only'=>true]];}catch(Throwable$e){if($db->inTransaction())$db->rollBack();throw$e;}
}
if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__){fwrite(STDERR,"library_only: use guarded mutual graph workflow\n");exit(64);}
