<?php
declare(strict_types=1);
require_once __DIR__.'/hotel_match_live30_common4_gap_matrix_v1.php';require_once __DIR__.'/hotel_match_retained93_primary_write_v84.php';
const M101_OP='hotel-match-newcontext-samoonly-third200-plan-1971-20260928-v101';const M101_LEDGER='8da64bc3ac54d707d335b8808b171f46a02ba0464536681bc40b741136df935c';
const M101_P1='4d4e0f8ea69c71d07a773f9063565f5ba51620c2290584647956928bfe5736c1';const M101_P2='17c8384a1d3fb59d2fe47f72409ac2e9f4c969166c450090f3079f93b5d31f9a';
function m101_need(bool$b,string$m):void{if(!$b)throw new RuntimeException($m);}
function m101_main(array$a):int{
 m101_need(($a[1]??'')==='--execute','disabled');$root=(string)getenv('ANYTOUR_ROOT');$dir=(string)getenv('MATCH_OPERATION_DIR');$head=(string)getenv('MATCH_SOURCE_SHA');m101_need(is_dir($root)&&basename($root)==='anytoour.ru'&&is_dir($dir)&&basename($dir)===M101_OP,'scope');foreach(['result.json','receipt.json']as$f)m101_need(!file_exists($dir.'/'.$f),'no_replay');$ops=dirname($dir);
 $l=w84_read($ops.'/hotel-match-request-ledger-1971-20260928-v93/result.json',M101_LEDGER,33554432);$p1=w84_read($ops.'/hotel-match-newcontext-samoonly200-plan-1971-20260928-v96/result.json',M101_P1,16777216);$p2=w84_read($ops.'/hotel-match-newcontext-samoonly-next200-plan-1971-20260928-v99/result.json',M101_P2,16777216);m101_need(count($p1['rows'])===200&&count($p2['rows'])===200,'prior');
 $used=[];foreach([$p1,$p2]as$p)foreach($p['rows']as$r)$used[(int)$r['tv_hotel_id']]=true;m101_need(count($used)===400,'prior_unique');
 require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$m=hmc4_execute(v2_data_db());$cur=[];foreach($m['rows']as$r)$cur[(int)$r['tv_hotel_id']]=$r;$req=[];foreach($l['requests']as$q)foreach($q['hotel_ids']as$id)$req[(int)$id][]=$q;$rank=['Турция'=>1,'Таиланд'=>2,'Вьетнам'=>3,'Китай'=>4,'ОАЭ'=>5,'Египет'=>6,'Мальдивы'=>7,'Катар'=>8];$rows=[];$replay=0;
 foreach($l['rows']as$r){$id=(int)$r['tv_hotel_id'];if(isset($used[$id])||!isset($cur[$id])||($cur[$id]['gap_bucket']??'')!=='samo_only'||!in_array(13,array_map('intval',$r['missing_operator_ids']??[]),true)||!empty($r['lanes']['13']['retained_exact']))continue;$cids=[];foreach($req[$id]??[]as$q){$cid=(int)($q['context']['countryId']??0);if($cid)$cids[$cid]=($cids[$cid]??0)+1;}arsort($cids);$cid=(int)(array_key_first($cids)??0);if(!$cid)continue;$dup=false;foreach($req[$id]??[]as$q){$x=$q['context'];if((int)($x['departureId']??0)===1&&(int)($x['countryId']??0)===$cid&&($x['dateFrom']??'')==='2026-10-15'&&($x['dateTo']??'')==='2026-10-15'&&(int)($x['nightsFrom']??0)===7&&(int)($x['nightsTo']??0)===7&&(int)($x['adults']??0)===2&&($x['childs']??[])===[]){$dup=true;break;}}if($dup){$replay++;continue;}$missing=[];foreach([13,18,25,43]as$op)if(in_array($op,array_map('intval',$r['missing_operator_ids']??[]),true)&&empty($r['lanes'][(string)$op]['retained_exact']))$missing[]=$op;if(!in_array(13,$missing,true))continue;$rows[]=['tv_hotel_id'=>$id,'hotel_name'=>$r['hotel_name'],'country_id'=>$cid,'country'=>$r['country'],'departure_id'=>1,'departure_date'=>'2026-10-15','nights'=>7,'adults'=>2,'children_count'=>0,'child_ages_signature'=>'','missing_operator_ids'=>$missing,'gap_bucket'=>'samo_only','rank'=>$rank[$r['country']]??99];}
 usort($rows,fn($x,$y)=>[$x['rank'],$x['tv_hotel_id']]<=>[$y['rank'],$y['tv_hotel_id']]);$eligible=count($rows);$rows=array_slice($rows,0,200);foreach($rows as&$r)unset($r['rank']);unset($r);m101_need(count($rows)===200,'scope200');$countries=[];foreach($rows as$r)$countries[$r['country']]=($countries[$r['country']]??0)+1;
 $out=['operation'=>M101_OP,'state'=>'completed_read_only_third200_plan','source_sha'=>$head,'generated_at_utc'=>gmdate('c'),'current_tv_total'=>$m['tv_live30_total'],'current_nontriple'=>$m['live30_non_triple_total'],'prior_scope_excluded'=>400,'eligible_after_prior_scopes'=>$eligible,'excluded_exact_context_replay'=>$replay,'scope_count'=>200,'country_counts'=>$countries,'tourvisor_account'=>'TOURVISOR_ANEX_JWT','operator_filter_sent'=>false,'continue_calls'=>0,'dates_calls'=>0,'provider_http_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'rows'=>$rows];$sha=w76_save($dir.'/result.json',$out);w76_save($dir.'/receipt.json',['operation'=>M101_OP,'state'=>$out['state'],'source_sha'=>$head,'result_sha256'=>$sha,'provider_http_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true]);echo w76_json(array_diff_key($out,['rows'=>true]))."\n";return 0;
}
if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__)exit(m101_main($argv));
