<?php
declare(strict_types=1);
error_reporting(0);ob_start();
const OP='hotel-match-live-unresolved-exact-bridge-review-1971-20260912-v1';
function norm($v):string{$s=mb_strtolower(trim((string)$v),'UTF-8');$s=strtr($s,['ё'=>'е','&'=>' and ','hotell'=>'hotel','otel'=>'hotel','aquapark'=>'aqua park','waterpark'=>'water park']);$s=preg_replace('/\(\s*(?:ex|ех|formerly|быв)\s*[.:\-]?\s*[^)]*\)/iu',' ',$s);preg_match_all('/[\p{L}\p{N}]+/u',$s,$m);$drop=['hotel','hotels','resort','resorts','spa','otel','отель','отели','гостиница','the','by','and'];$w=array_values(array_filter($m[0]??[],fn($x)=>$x!==''&&!in_array($x,$drop,true)));return implode(' ',$w);}
function variants($v):array{$s=(string)$v;$a=[$s];if(preg_match_all('/\(\s*(?:ex|ех|formerly|быв)\s*[.:\-]?\s*([^)]*)\)/iu',$s,$m))foreach($m[1]as$x)$a[]=$x;$o=[];foreach($a as$x){$n=norm($x);if($n!=='')$o[$n]=1;}return array_keys($o);}
function quals($v):array{$q=['beach','garden','mountain','palace','park','club','villa','villas','suite','suites','family','adult','adults','only','north','south','east','west','wing','aqua'];$o=[];foreach(explode(' ',norm($v))as$w)if(in_array($w,$q,true)||preg_match('/^\d+$/',$w))$o[$w]=1;ksort($o);return array_keys($o);}
function bridgeNames(array$r):array{$raw=(string)($r['evidence_json']??'');$e=json_decode($raw,true);if(!is_array($e)||hash('sha256',$raw)!==(string)($r['evidence_sha256']??''))return[];$id=(string)$r['external_hotel_id'];$stack=[$e];$out=[];$guard=0;while($stack&&$guard++<5000){$v=array_pop($stack);if(!is_array($v))continue;if(isset($v['name'])&&(string)($v['id']??$v['hotelKey']??'')===$id){foreach([$v['name']??null,$v['lName']??null]as$n)foreach(variants($n)as$f)$out[$f]=1;}foreach($v as$k=>$x)if(is_array($x)&&!in_array((string)$k,['candidates','targets','local','hotels','offers'],true))$stack[]=$x;}return array_keys($out);}
$pdo=null;try{$root=realpath(getcwd());if(!$root||basename($root)!=='anytoour.ru')throw new RuntimeException('root');require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$pdo=v2_data_db();$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$pdo->exec('START TRANSACTION READ ONLY');
$protected=[];foreach($pdo->query('SELECT DISTINCT anex_hotel_id FROM anex_hotel_search_mappings')->fetchAll(PDO::FETCH_COLUMN)as$x)$protected[(int)$x]=1;foreach($pdo->query('SELECT DISTINCT anex_hotel_id FROM anex_hotel_decisions')->fetchAll(PDO::FETCH_COLUMN)as$x)$protected[(int)$x]=1;foreach($pdo->query('SELECT DISTINCT anex_hotel_id FROM anex_review_pair_exclusions')->fetchAll(PDO::FETCH_COLUMN)as$x)$protected[(int)$x]=1;
$locals=[];$idx=[];$names=[];foreach($pdo->query('SELECT id,name,country_id,country_name,region_name,subregion_name,is_active FROM catalog_hotels WHERE is_active=1')->fetchAll(PDO::FETCH_ASSOC)as$h){$lid=(int)$h['id'];$locals[$lid]=$h;foreach(variants($h['name'])as$n){$idx[(int)$h['country_id']][$n][$lid]=1;$names[$lid][$n]=1;}}foreach($pdo->query('SELECT a.hotel_id,a.alias,h.country_id FROM hotel_aliases a JOIN catalog_hotels h ON h.id=a.hotel_id WHERE h.is_active=1')->fetchAll(PDO::FETCH_ASSOC)as$a){$lid=(int)$a['hotel_id'];foreach(variants($a['alias'])as$n){$idx[(int)$a['country_id']][$n][$lid]=1;$names[$lid][$n]=1;}}
$peer=[];$q=$pdo->query('SELECT o.hotel_name,o.country_id,m.catalog_hotel_id FROM anex_search_hotel_observations o JOIN anex_hotel_search_mappings m ON m.anex_hotel_id=o.anex_hotel_id');foreach($q->fetchAll(PDO::FETCH_ASSOC)as$r){foreach(variants($r['hotel_name'])as$n)$peer[(int)$r['country_id']][$n][(int)$r['catalog_hotel_id']]=1;}
$andro=[];$q=$pdo->query("SELECT external_hotel_id,local_hotel_id,evidence_sha256,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IS NOT NULL");foreach($q->fetchAll(PDO::FETCH_ASSOC)as$r){$lid=(int)$r['local_hotel_id'];foreach(bridgeNames($r)as$n)$andro[$n][$lid]=1;}
$obs=$pdo->query('SELECT anex_hotel_id,hotel_name,country_id,search_count,last_seen_utc FROM anex_search_hotel_observations ORDER BY search_count DESC,last_seen_utc DESC,anex_hotel_id')->fetchAll(PDO::FETCH_ASSOC);$safe=[];$review=[];$reasons=[];
foreach($obs as$r){$aid=(int)$r['anex_hotel_id'];if(isset($protected[$aid]))continue;$name=(string)$r['hotel_name'];$cid=(int)$r['country_id'];$fs=variants($name);$low=(bool)preg_match('/\b(fortuna|roulette|рулетка|тур\s|tour\s)\b/iu',$name);$cand=[];$peers=[];$ands=[];foreach($fs as$f){foreach(array_keys($idx[$cid][$f]??[])as$lid)$cand[$lid]=1;foreach(array_keys($peer[$cid][$f]??[])as$lid)$peers[$lid]=1;foreach(array_keys($andro[$f]??[])as$lid)if(isset($locals[$lid])&&(int)$locals[$lid]['country_id']===$cid)$ands[$lid]=1;}$all=array_values(array_unique(array_merge(array_keys($cand),array_keys($peers),array_keys($ands))));$lid=null;$reason='no_unique_evidence';$ok=false;if(!$low&&count($all)===1){$lid=(int)$all[0];$tokens=array_values(array_filter(explode(' ',norm($name)),fn($x)=>mb_strlen($x,'UTF-8')>=3));$sourceQ=quals($name);$targetQ=[];foreach(array_keys($names[$lid]??[])as$n)$targetQ=array_values(array_unique(array_merge($targetQ,quals($n))));sort($targetQ);$qconf=(bool)array_diff($sourceQ,$targetQ);$hasLocal=isset($cand[$lid]);$hasPeer=isset($peers[$lid]);$hasAnd=isset($ands[$lid]);if($qconf)$reason='qualifier_conflict';elseif(count($tokens)<2&&!$hasPeer)$reason='low_information_name';elseif($hasPeer&&($hasLocal||$hasAnd)){$reason='exact_peer_plus_local_or_andromeda';$ok=true;}elseif($hasLocal&&$hasAnd){$reason='exact_local_plus_andromeda';$ok=true;}elseif($hasPeer&&count($tokens)>=2){$reason='exact_existing_anex_peer';$ok=true;}else$reason='single_source_only';}elseif($low)$reason='low_information_source';elseif(count($all)>1)$reason='ambiguous_exact_targets';
$row=['anex_hotel_id'=>$aid,'hotel_name'=>$name,'country_id'=>$cid,'search_count'=>(int)$r['search_count'],'last_seen_utc'=>$r['last_seen_utc'],'local_hotel_id'=>$lid,'local_name'=>$lid!==null?($locals[$lid]['name']??null):null,'evidence'=>['local_exact'=>$lid!==null&&isset($cand[$lid]),'existing_anex_peer'=>$lid!==null&&isset($peers[$lid]),'andromeda_exact'=>$lid!==null&&isset($ands[$lid])],'reason'=>$reason];$reasons[$reason]=($reasons[$reason]??0)+1;if($ok)$safe[]=$row;else$review[]=$row;}
$pdo->exec('ROLLBACK');$out=['status'=>'completed','operation_id'=>OP,'safe_count'=>count($safe),'needs_extra_count'=>count($review),'reason_counts'=>$reasons,'safe_rows'=>$safe,'needs_extra_top'=>array_slice($review,0,120),'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true];}catch(Throwable$e){if($pdo instanceof PDO&&$pdo->inTransaction())$pdo->rollBack();$out=['status'=>'failed','operation_id'=>OP,'safe_message'=>'live_unresolved_exact_bridge_review_failed','database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true];}while(ob_get_level())ob_end_clean();echo 'LIVE_EXACT_REVIEW:'.json_encode($out,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";exit(($out['status']??'')==='completed'?0:2);
