<?php
declare(strict_types=1);
if (!defined('FC_LIBRARY_ONLY')) define('FC_LIBRARY_ONLY', true);
require_once __DIR__ . '/hotel_match_current_bulk_review.php';

const HMTOI_OPERATION = 'hotel-match-tourvisor-anex-operator-identity-review-2333-20260914-v1';

function hmtoi_latin(string $v): string {
    $v=mb_strtolower(trim($v),'UTF-8');
    return strtr($v,['щ'=>'shch','ш'=>'sh','ч'=>'ch','ц'=>'ts','ю'=>'yu','я'=>'ya','ё'=>'e','ж'=>'zh','х'=>'kh','а'=>'a','б'=>'b','в'=>'v','г'=>'g','д'=>'d','е'=>'e','з'=>'z','и'=>'i','й'=>'y','к'=>'k','л'=>'l','м'=>'m','н'=>'n','о'=>'o','п'=>'p','р'=>'r','с'=>'s','т'=>'t','у'=>'u','ф'=>'f','ы'=>'y','э'=>'e','ь'=>'','ъ'=>'']);
}
function hmtoi_tokens(string $v): array {
    $v=preg_replace('/\s*\(\s*(?:ex|ех)\s*\.?\s+[^()]+\)\s*$/ui',' ',hmtoi_latin($v));
    preg_match_all('/[\p{L}\p{N}]+/u',fc_norm($v),$m);
    $generic=['hotel'=>1,'hotels'=>1,'otel'=>1,'resort'=>1,'resorts'=>1,'spa'=>1];
    $out=[];foreach($m[0]??[] as $t){if($t!==''&&!isset($generic[$t]))$out[$t]=1;}return array_keys($out);
}
function hmtoi_key(string $v,bool $bag=false): string { $t=hmtoi_tokens($v);if($bag)sort($t,SORT_STRING);return implode(' ',$t); }
function hmtoi_numbers(string $v): array { $out=[];foreach(hmtoi_tokens($v) as $t)if(ctype_digit($t))$out[(string)((int)$t)]=1;$x=array_keys($out);sort($x,SORT_NATURAL);return $x; }
function hmtoi_critical(string $v): array {
    $aliases=['annexe'=>'annex','gardens'=>'garden','beaches'=>'beach'];$keep=['annex'=>1,'beach'=>1,'garden'=>1,'north'=>1,'south'=>1];$out=[];
    foreach(hmtoi_tokens($v) as $t){$t=$aliases[$t]??$t;if(isset($keep[$t]))$out[$t]=1;}ksort($out);return array_keys($out);
}
function hmtoi_pair_ok(string $a,string $b): bool { return hmtoi_numbers($a)===hmtoi_numbers($b) && hmtoi_critical($a)===hmtoi_critical($b); }
function hmtoi_similarity(string $a,string $b): array {
    $x=array_fill_keys(hmtoi_tokens($a),1);$y=array_fill_keys(hmtoi_tokens($b),1);$shared=count(array_intersect_key($x,$y));$union=count($x+$y);return [$union?$shared/$union:0.0,$shared];
}
function hmtoi_best_pair(array $left,array $right): array {
    $best=['score'=>0.0,'shared'=>0,'source'=>'','target'=>'','exact'=>false,'bag_exact'=>false,'pair_ok'=>false];
    foreach($left as $a)foreach($right as $b){$a=(string)$a;$b=(string)$b;if(trim($a)===''||trim($b)==='')continue;[$s,$sh]=hmtoi_similarity($a,$b);$exact=hmtoi_key($a,false)!==''&&hmtoi_key($a,false)===hmtoi_key($b,false);$bag=hmtoi_key($a,true)!==''&&hmtoi_key($a,true)===hmtoi_key($b,true);$ok=hmtoi_pair_ok($a,$b);$rank=($exact?3:($bag?2:0))+$s;
        $bestRank=($best['exact']?3:($best['bag_exact']?2:0))+$best['score'];if($rank>$bestRank||($rank===$bestRank&&$sh>$best['shared']))$best=['score'=>round($s,6),'shared'=>$sh,'source'=>$a,'target'=>$b,'exact'=>$exact,'bag_exact'=>$bag,'pair_ok'=>$ok];}
    return $best;
}
function hmtoi_extract_codes(array $r): array {
    $params=[];$query=trim((string)($r['operator_link_query']??''));if($query===''){$url=trim((string)($r['operator_link']??''));$p=$url!==''?parse_url($url):false;$query=is_array($p)?(string)($p['query']??''):'';}
    if($query!==''){parse_str($query,$params);}
    $values=[];foreach($params as $k=>$v){$key=strtolower((string)$k);if(!in_array($key,['hotelcode','hotellist'],true))continue;foreach(is_array($v)?$v:[$v] as $raw)foreach(preg_split('/[,;\s]+/',(string)$raw,-1,PREG_SPLIT_NO_EMPTY) as $part)if(ctype_digit($part)&&(int)$part>0)$values[(int)$part]=1;}
    if(!$values){$url=(string)($r['operator_link']??'');if(preg_match_all('/(?:hotelcode|hotellist)=([0-9]+)/i',$url,$m))foreach($m[1] as $x)if((int)$x>0)$values[(int)$x]=1;}
    $out=array_map('intval',array_keys($values));sort($out,SORT_NUMERIC);return $out;
}
function hmtoi_table_exists(PDO $db,string $table): bool { $q=$db->prepare('SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?');$q->execute([$table]);return (int)$q->fetchColumn()===1; }
function hmtoi_country_from_sha(PDO $db): array { return fc_sha_countries($db); }
function hmtoi_target(array $h): array { return ['local_hotel_id'=>(int)$h['id'],'name'=>(string)$h['name'],'country_id'=>(int)$h['country_id'],'region'=>(string)$h['region_name'],'subregion'=>(string)$h['subregion_name'],'category'=>$h['category']===null?null:(int)$h['category']]; }
function hmtoi_review(PDO $db,string $operation=HMTOI_OPERATION): array {
    if($operation!==HMTOI_OPERATION)throw new RuntimeException('operation_scope');$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
    [$hotels,$catalogNames,$strict,$broad,$places,$scope]=mbr_catalog($db);$shaCountry=hmtoi_country_from_sha($db);
    $stats=['operator_table_present'=>0,'operator_rows_total'=>0,'anex_operator_rows'=>0,'anex_operator_rows_with_link'=>0,'anex_operator_rows_with_code'=>0,'unique_codes'=>0,'ambiguous_codes'=>0,'accepted_code_same_target'=>0,'accepted_code_target_conflict'=>0,'direct_unresolved_examined'=>0,'direct_unresolved_safe'=>0,'direct_unresolved_blocked'=>0,'live_andromeda_examined'=>0,'live_andromeda_ranked'=>0,'live_andromeda_safe'=>0,'live_andromeda_medium'=>0];
    $blocked=[];$directSafe=[];$liveSafe=[];$liveMedium=[];
    if(!hmtoi_table_exists($db,'tour_operator_identity_observations'))return ['status'=>'completed','operation_id'=>$operation,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'historical_operations_replayed'=>false,'stats'=>$stats,'blocked_reasons'=>['operator_identity_table_missing'=>1],'safe_count'=>0,'direct_anex_safe'=>[],'live_andromeda_safe'=>[],'live_andromeda_medium'=>[],'coverage'=>fc_coverage($db)];
    $stats['operator_table_present']=1;$stats['operator_rows_total']=(int)$db->query('SELECT COUNT(*) FROM tour_operator_identity_observations')->fetchColumn();
    $obsRows=$db->query("SELECT * FROM tour_operator_identity_observations WHERE country_id IN (1,2,4,8,9,10,12,16) AND (LOWER(COALESCE(operator_name,'')) LIKE '%anex%' OR LOWER(COALESCE(operator_link_host,'')) LIKE '%anex%') ORDER BY last_seen_at DESC,id DESC")->fetchAll(PDO::FETCH_ASSOC);$stats['anex_operator_rows']=count($obsRows);
    $codeTargets=[];$localEvidence=[];
    foreach($obsRows as $o){$link=trim((string)($o['operator_link']??''));if($link!=='')$stats['anex_operator_rows_with_link']++;$codes=hmtoi_extract_codes($o);if(!$codes)continue;$stats['anex_operator_rows_with_code']++;foreach($codes as $code){$lid=(int)$o['hotel_id'];if(!isset($hotels[$lid])||(int)$hotels[$lid]['country_id']!==(int)$o['country_id'])continue;$codeTargets[$code][$lid]=($codeTargets[$code][$lid]??0)+(int)max(1,(int)($o['observation_count']??1));$localEvidence[$lid]['codes'][$code]=1;$localEvidence[$lid]['names'][(string)($o['hotel_name']??'')]=1;$localEvidence[$lid]['places'][(string)($o['region_name']??'')]=1;$localEvidence[$lid]['places'][(string)($o['subregion_name']??'')]=1;$localEvidence[$lid]['last_seen']=max((string)($localEvidence[$lid]['last_seen']??''),(string)($o['last_seen_at']??''));}}
    foreach($codeTargets as $code=>$targets){if(count($targets)===1)$stats['unique_codes']++;else$stats['ambiguous_codes']++;}
    foreach($localEvidence as $lid=>&$e){$e['codes']=array_map('intval',array_keys($e['codes']??[]));$e['names']=array_values(array_filter(array_keys($e['names']??[]),static fn($v)=>trim((string)$v)!==''));$e['places']=array_values(array_filter(array_keys($e['places']??[]),static fn($v)=>trim((string)$v)!==''));}unset($e);

    $anyDecision=[];foreach($db->query('SELECT anex_hotel_id FROM anex_hotel_decisions')->fetchAll(PDO::FETCH_COLUMN) as $id)$anyDecision[(int)$id]=1;
    $anyMapping=[];$acceptedCodeLocal=[];$occupiedLocal=[];
    foreach($db->query("SELECT anex_hotel_id,catalog_hotel_id,enabled FROM anex_hotel_search_mappings WHERE scope='preview'")->fetchAll(PDO::FETCH_ASSOC) as $m){$code=(int)$m['anex_hotel_id'];$lid=(int)$m['catalog_hotel_id'];$anyMapping[$code]=1;if((int)$m['enabled']===1&&!isset($anyDecision[$code])){$acceptedCodeLocal[$code][$lid]=1;$occupiedLocal[$lid][$code]=1;}}
    foreach($db->query("SELECT anex_hotel_id,catalog_hotel_id FROM anex_hotel_decisions WHERE decision_status='accepted' AND catalog_hotel_id IS NOT NULL")->fetchAll(PDO::FETCH_ASSOC) as $m){$code=(int)$m['anex_hotel_id'];$lid=(int)$m['catalog_hotel_id'];$acceptedCodeLocal[$code][$lid]=1;$occupiedLocal[$lid][$code]=1;}
    $exclusions=[];foreach($db->query('SELECT anex_hotel_id,catalog_hotel_id FROM anex_review_pair_exclusions')->fetchAll(PDO::FETCH_ASSOC) as $x)$exclusions[(int)$x['anex_hotel_id']][(int)$x['catalog_hotel_id']]=1;
    foreach($codeTargets as $code=>$targets)if(count($targets)===1&&isset($acceptedCodeLocal[(int)$code])){$lid=(int)array_key_first($targets);$acc=array_keys($acceptedCodeLocal[(int)$code]);if(count($acc)===1&&(int)$acc[0]===$lid)$stats['accepted_code_same_target']++;else$stats['accepted_code_target_conflict']++;}

    $anexRows=[];foreach($db->query('SELECT * FROM anex_hotels')->fetchAll(PDO::FETCH_ASSOC) as $r)$anexRows[(int)$r['anex_hotel_id']]=$r;
    foreach($codeTargets as $code=>$targets){$code=(int)$code;if(count($targets)!==1||!isset($anexRows[$code])||isset($anyDecision[$code])||isset($anyMapping[$code]))continue;$stats['direct_unresolved_examined']++;$lid=(int)array_key_first($targets);$target=$hotels[$lid]??null;if(!$target){$blocked['operator_target_missing_catalog']=($blocked['operator_target_missing_catalog']??0)+1;continue;}$source=$anexRows[$code];$country=fc_country($source['api_country']??'');if($country===null||$country!==(int)$target['country_id']){$stats['direct_unresolved_blocked']++;$blocked['direct_code_country_conflict']=($blocked['direct_code_country_conflict']??0)+1;continue;}if(isset($exclusions[$code][$lid])){$stats['direct_unresolved_blocked']++;$blocked['pair_exclusion']=($blocked['pair_exclusion']??0)+1;continue;}$other=array_diff(array_map('intval',array_keys($occupiedLocal[$lid]??[])),[$code]);if($other){$stats['direct_unresolved_blocked']++;$blocked['target_occupied_other_anex']=($blocked['target_occupied_other_anex']??0)+1;continue;}
        $sourceNames=array_values(array_unique(array_filter([(string)($source['api_name']??''),(string)($source['xml_name']??''),(string)($source['xml_alternate_name']??'')],static fn($v)=>trim($v)!=='')));$targetNames=array_values(array_unique(array_merge($catalogNames[$lid]??[], $localEvidence[$lid]['names']??[])));$pair=hmtoi_best_pair($sourceNames,$targetNames);if(!$pair['pair_ok']){$stats['direct_unresolved_blocked']++;$blocked['meaningful_or_numeric_qualifier_conflict']=($blocked['meaningful_or_numeric_qualifier_conflict']??0)+1;continue;}
        $guard=mbr_target_guard($source,$target);if($guard['coordinate_conflict']){$stats['direct_unresolved_blocked']++;$blocked['coordinate_conflict_gt_5km']=($blocked['coordinate_conflict_gt_5km']??0)+1;continue;}$sourcePlaces=[(string)($source['api_region']??''),(string)($source['api_town']??'')];$targetPlaces=array_merge([(string)$target['region_name'],(string)$target['subregion_name']],$localEvidence[$lid]['places']??[]);$place=fc_place($sourcePlaces,$targetPlaces);$strongName=$pair['exact']||$pair['bag_exact']||($pair['score']>=0.82&&$pair['shared']>=2);$strongGeo=$place||($guard['distance_m']!==null&&$guard['distance_m']<=1000);if(!$strongName&&!$strongGeo){$stats['direct_unresolved_blocked']++;$blocked['direct_code_without_name_or_geo_corroboration']=($blocked['direct_code_without_name_or_geo_corroboration']??0)+1;continue;}
        $directSafe[]=['provider'=>'anex','external_id'=>$code,'target'=>hmtoi_target($target),'operator_observation_count'=>array_sum($targets),'operator_last_seen'=>$localEvidence[$lid]['last_seen']??null,'operator_codes'=>$localEvidence[$lid]['codes']??[],'source_names'=>$sourceNames,'source_places'=>$sourcePlaces,'best_name'=>$pair,'direct_place'=>(bool)$place,'guard'=>$guard,'reason'=>'saved_tourvisor_anex_operator_link_direct_code'];$stats['direct_unresolved_safe']++;}

    $anchoredLocals=[];foreach($localEvidence as $lid=>$e){foreach($e['codes'] as $code){$targets=$codeTargets[$code]??[];$acc=$acceptedCodeLocal[$code]??[];if(count($targets)===1&&count($acc)===1&&(int)array_key_first($targets)===(int)$lid&&(int)array_key_first($acc)===(int)$lid){$anchoredLocals[(int)$lid]=$e;break;}}}
    $andOccupied=[];foreach($db->query("SELECT DISTINCT local_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IS NOT NULL")->fetchAll(PDO::FETCH_COLUMN) as $lid)$andOccupied[(int)$lid]=1;
    $latest=[];$obsCount=[];foreach($db->query("SELECT * FROM andromeda_search_hotel_observations WHERE supplier_namespace='andromeda_catalog' ORDER BY observed_at_utc DESC,external_hotel_id")->fetchAll(PDO::FETCH_ASSOC) as $o){$id=(string)$o['external_hotel_id'];$obsCount[$id]=($obsCount[$id]??0)+1;if(!isset($latest[$id]))$latest[$id]=$o;}
    foreach($db->query("SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='pending' AND local_hotel_id IS NULL ORDER BY external_hotel_id")->fetchAll(PDO::FETCH_ASSOC) as $r){$external=(string)$r['external_hotel_id'];$oc=(int)($obsCount[$external]??0);if($oc<=0)continue;$stats['live_andromeda_examined']++;$obs=$latest[$external]??null;$country=(int)($obs['country_id']??0);if(!isset(MBR_CORE8[$country]))$country=(int)($shaCountry[$r['catalog_sha256']]??0);if(!isset(MBR_CORE8[$country]))continue;$prior=fc_evidence($r['evidence_json']??'');$src=$prior['source']??[];if(!is_array($src))$src=[];$geo=$prior['geography']??[];if(!is_array($geo))$geo=[];$sourceNames=array_values(array_unique(array_filter([(string)($src['name']??''),(string)($src['lName']??''),(string)($obs['hotel_name']??'')],static fn($v)=>trim($v)!=='')));$sourcePlaces=array_values(array_unique(array_filter([(string)($src['town']??''),(string)($geo['town']??''),(string)($geo['parent']??''),(string)($obs['region_name']??'')],static fn($v)=>trim($v)!=='')));
        $rank=[];foreach($anchoredLocals as $lid=>$e){if(isset($andOccupied[$lid])||!isset($hotels[$lid])||(int)$hotels[$lid]['country_id']!==$country)continue;$tn=array_values(array_unique(array_merge($catalogNames[$lid]??[],$e['names']??[])));$pair=hmtoi_best_pair($sourceNames,$tn);if($pair['score']<=0&&!$pair['exact']&&!$pair['bag_exact'])continue;$rank[]=['lid'=>$lid,'pair'=>$pair,'names'=>$tn];}usort($rank,static function($a,$b){$ra=($a['pair']['exact']?3:($a['pair']['bag_exact']?2:0))+$a['pair']['score'];$rb=($b['pair']['exact']?3:($b['pair']['bag_exact']?2:0))+$b['pair']['score'];return $rb<=>$ra ?: $b['pair']['shared']<=>$a['pair']['shared'] ?: $a['lid']<=>$b['lid'];});$best=$rank[0]??null;if(!$best)continue;$stats['live_andromeda_ranked']++;$second=$rank[1]['pair']['score']??0.0;$lid=(int)$best['lid'];$target=$hotels[$lid];$pair=$best['pair'];if(!$pair['pair_ok']){$blocked['live_andromeda_qualifier_or_numeric_conflict']=($blocked['live_andromeda_qualifier_or_numeric_conflict']??0)+1;continue;}$guard=mbr_target_guard($src+($obs?:[]),$target);if($guard['coordinate_conflict']){$blocked['live_andromeda_coordinate_conflict_gt_5km']=($blocked['live_andromeda_coordinate_conflict_gt_5km']??0)+1;continue;}$targetPlaces=array_merge([(string)$target['region_name'],(string)$target['subregion_name']],$anchoredLocals[$lid]['places']??[]);$place=fc_place($sourcePlaces,$targetPlaces);$margin=$pair['score']-(float)$second;$row=['provider'=>'andromeda','external_id'=>$external,'observation_count'=>$oc,'source_names'=>$sourceNames,'source_places'=>$sourcePlaces,'target'=>hmtoi_target($target),'anex_operator_codes'=>$anchoredLocals[$lid]['codes']??[],'anex_operator_last_seen'=>$anchoredLocals[$lid]['last_seen']??null,'best_name'=>$pair,'margin'=>round($margin,6),'direct_place'=>(bool)$place,'guard'=>$guard];
        if(($pair['exact']||$pair['bag_exact'])&&$pair['shared']>=1){$row['reason']='live_andromeda_exact_name_to_saved_anex_operator_anchor';$liveSafe[]=$row;$stats['live_andromeda_safe']++;continue;}if($pair['score']>=0.88&&$pair['shared']>=2&&$margin>=0.18&&$place){$row['reason']='live_andromeda_strong_fuzzy_geo_to_saved_anex_operator_anchor';$liveSafe[]=$row;$stats['live_andromeda_safe']++;continue;}if($pair['score']>=0.80&&$pair['shared']>=2&&$margin>=0.12&&$place){$row['reason']='live_andromeda_medium_fuzzy_geo_to_saved_anex_operator_anchor';$liveMedium[]=$row;$stats['live_andromeda_medium']++;continue;}}
    $sort=static fn($a,$b)=>(int)($b['observation_count']??$b['operator_observation_count']??0)<=>(int)($a['observation_count']??$a['operator_observation_count']??0) ?: (int)$a['target']['local_hotel_id']<=>(int)$b['target']['local_hotel_id'];usort($directSafe,$sort);usort($liveSafe,$sort);usort($liveMedium,$sort);arsort($blocked);
    return ['status'=>'completed','operation_id'=>$operation,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'historical_operations_replayed'=>false,'stats'=>$stats,'blocked_reasons'=>$blocked,'operator_anchor_locals'=>count($anchoredLocals),'safe_count'=>count($directSafe)+count($liveSafe),'direct_anex_safe_count'=>count($directSafe),'live_andromeda_safe_count'=>count($liveSafe),'live_andromeda_medium_count'=>count($liveMedium),'direct_anex_safe'=>$directSafe,'live_andromeda_safe'=>$liveSafe,'live_andromeda_medium'=>$liveMedium,'coverage'=>fc_coverage($db),'catalog_scope'=>$scope];
}
