<?php
declare(strict_types=1);
const OR78_OP='hotel-match-pending11-origin-read-1971-20260927-v78';
const OR78_CATS=['650','3060','67775','201859','218356','240679','2000023232','2000050217','2000065684','2000067202','2000073592'];
function or78_need(bool $ok,string $r):void{if(!$ok)throw new RuntimeException($r);}
function or78_save(string$p,array$x):string{$s=json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n";$f=fopen($p,'x+b');or78_need($f!==false,'exclusive');or78_need(fwrite($f,$s)===strlen($s)&&fflush($f),'write');fclose($f);return hash('sha256',$s);}
if(($argv[1]??'')==='--self-test'){or78_need(count(OR78_CATS)===11,'scope');echo "OR78_SELF_TEST_OK\n";exit;}
or78_need(($argv[1]??'')==='--execute','disabled');$root=(string)getenv('ANYTOUR_ROOT');$dir=(string)getenv('MATCH_OPERATION_DIR');$sha=(string)getenv('MATCH_SOURCE_SHA');or78_need(is_dir($root)&&is_dir($dir)&&basename($dir)===OR78_OP&&preg_match('/^[a-f0-9]{40}$/D',$sha)===1,'scope');$res=json_decode(file_get_contents($dir.'/reservation.json'),true,32,JSON_THROW_ON_ERROR);or78_need($res['operation']===OR78_OP&&$res['source_sha']===$sha,'reservation');or78_save($dir.'/execution-started.json',['operation'=>OR78_OP]);
require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->exec('START TRANSACTION READ ONLY');$q=$db->prepare("SELECT supplier_namespace,external_hotel_id,local_hotel_id,decision_status,evidence_json,evidence_sha256 FROM andromeda_hotel_identities WHERE (supplier_namespace='andromeda_catalog' AND external_hotel_id IN (".implode(',',array_fill(0,11,'?')).")) OR (supplier_namespace='operator_315' AND external_hotel_id IN ('245225','75663','30946','29950','30923','778466','688987','573708','789199','859610')) OR (supplier_namespace='operator_342' AND external_hotel_id IN ('21978','743','19652','17362','17390','17163','27835')) ORDER BY supplier_namespace,external_hotel_id");$q->execute(OR78_CATS);$rows=[];foreach($q->fetchAll(PDO::FETCH_ASSOC)as$r){$raw=$r['evidence_json'];or78_need(hash('sha256',$raw)===$r['evidence_sha256'],'digest');$ev=json_decode($raw,true,128,JSON_THROW_ON_ERROR);unset($r['evidence_json']);$r['top_fields']=array_keys($ev);$r['top_values']=[];foreach($ev as$k=>$v){if($k==='source')continue;if(preg_match('/token|secret|password|credential|session|login|email|phone/i',(string)$k)){$r['top_values'][$k]='REDACTED';continue;}$r['top_values'][$k]=is_scalar($v)||$v===null?$v:['type'=>get_debug_type($v),'keys'=>is_array($v)?array_keys($v):[]];}$rows[]=$r;}$db->rollBack();$out=['operation'=>OR78_OP,'source_sha'=>$sha,'state'=>'completed_read_only','rows'=>$rows,'database_writes'=>0,'mapping_writes'=>0,'provider_http_calls'=>0,'no_replay'=>true];$h=or78_save($dir.'/result.json',$out);or78_save($dir.'/receipt.json',['operation'=>OR78_OP,'source_sha'=>$sha,'state'=>$out['state'],'result_sha256'=>$h,'database_writes'=>0,'provider_http_calls'=>0]);echo json_encode(['state'=>$out['state'],'rows'=>count($rows)])."\n";
