<?php
declare(strict_types=1);
// One pending canonical identity, supported by a retained native ANEX/PRICE bridge.
const HMR_OP='hotel-match-ramada-native-accept-1971-20260919-v1';
const HMR_CURRENT='abbc4d63c90fb08111bddceb8b84a6f5183315246244807b5d307454d60d29ae';
const HMR_CATALOG='45fe75aca798b5e66fc2422206fa9620cc09c0a4711c014598e696e9a4d60606';
const HMR_ROW='dcedbcb012e0c1975ae52f9bbe3835e8e56f27a5dab1afa983b82f61dca40cde';
const HMR_EVIDENCE='42444f4a8541641ccd8dc4f7e2771de1c430420709f4e6bc93457048b11945ec';
const HMR_BRIDGE_ROW='50142b95d5918ff152e4ecf18fe813f212663f4eb9ed83b688b36571f18cc095';
const HMR_BRIDGE_EVIDENCE='021f252d3a9ae6da807c2a1f48a2170faa828a24b0a5d54641009fc88422bf45';
const HMR_COMPETITORS=[1441,17594,21810,28671,52913,75560,79029,81253,103490];
function hmr_need(bool $ok,string $why):void{if(!$ok)throw new RuntimeException($why);}
function hmr_json(mixed $v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
function hmr_hash(mixed $v):string{return hash('sha256',hmr_json($v)."\n");}
function hmr_order(mixed $v):mixed{if(is_array($v)){if(!array_is_list($v))ksort($v,SORT_STRING);foreach($v as&$x)$x=hmr_order($x);unset($x);}return $v;}
function hmr_save(string $path,array $v):string{$b=hmr_json($v)."\n";$f=fopen($path,'xb');hmr_need(is_resource($f),'exclusive_record');try{hmr_need(fwrite($f,$b)===strlen($b)&&fflush($f),'record_write');if(function_exists('fsync'))hmr_need(fsync($f),'record_sync');}finally{fclose($f);}hmr_need(hash_file('sha256',$path)===hash('sha256',$b),'record_readback');return hash('sha256',$b);}
function hmr_rows(PDO $db,string $sql,array $params=[],int $cap=50000):array{hmr_need(str_starts_with($sql,'SELECT '),'select_only');$s=$db->prepare($sql);$s->execute($params);$r=$s->fetchAll(PDO::FETCH_ASSOC);hmr_need(count($r)<=$cap,'read_cap');return $r;}
function hmr_family(string $name):bool{return preg_match('/\b(?:ramada|рамада)\b/iu',$name)===1&&preg_match('/\b(?:plaza|плаза)\b/iu',$name)===1;}
function hmr_exact_name(string $name):bool{$n=trim(preg_replace('/[^a-z0-9]+/',' ',strtolower($name))??'');return in_array($n,['ramada plaza by windham antalya','ramada plaza by wyndham antalya'],true);}
function hmr_reconstruct(array $row):array{$out=[];foreach(['supplier_namespace','external_hotel_id','local_hotel_id','decision_status','catalog_sha256','evidence_sha256']as$k)$out[$k]=$row[$k];$out['evidence_json']=$row['supplier_namespace']==='operator_5'?json_encode($row['evidence'],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n":hmr_json($row['evidence']);$out['created_at']=$row['created_at'];return $out;}
function hmr_guard(array $old,array $bridge,array $hotels,array $aliases,array $identities,array $guards,?int $anex,array $catalog,array $expected):array{
 hmr_need(($old['supplier_namespace']??null)==='andromeda_catalog'&&(string)($old['external_hotel_id']??'')==='190031'&&($old['decision_status']??null)==='pending'&&array_key_exists('local_hotel_id',$old)&&$old['local_hotel_id']===null,'pending_only');
 hmr_need(hmr_hash($old)===HMR_ROW&&$old['evidence_sha256']===HMR_EVIDENCE&&hash('sha256',$old['evidence_json'])===HMR_EVIDENCE,'pending_row_drift');
 $prior=json_decode($old['evidence_json'],true,64,JSON_THROW_ON_ERROR);$keys=array_keys($prior);sort($keys);hmr_need($keys===['candidate_ids','reason','source','target_name']&&$prior['candidate_ids']===[]&&$prior['reason']==='no_unique_country_name'&&$prior['target_name']===null,'prior_protection');
 hmr_need(($bridge['supplier_namespace']??null)==='operator_5'&&(string)($bridge['external_hotel_id']??'')==='8365'&&($bridge['decision_status']??null)==='pending'&&array_key_exists('local_hotel_id',$bridge)&&$bridge['local_hotel_id']===null,'bridge_protection');
 hmr_need(hmr_hash($bridge)===HMR_BRIDGE_ROW&&$bridge['evidence_sha256']===HMR_BRIDGE_EVIDENCE&&hash('sha256',$bridge['evidence_json'])===HMR_BRIDGE_EVIDENCE,'bridge_drift');
 $be=json_decode($bridge['evidence_json'],true,64,JSON_THROW_ON_ERROR);hmr_need(($be['schema']??null)==='operator-original-price-bridge/1'&&($be['country_id']??null)===4&&count($be['provider_bridges']??[])===1,'bridge_schema');$edge=$be['provider_bridges'][0];
 hmr_need(($edge['operator_key']??null)==='5'&&($edge['native_hotel_id']??null)==='8365'&&($edge['andromeda_hotel_id']??null)==='190031'&&($edge['is_operator_hotel_key']??null)===false&&($edge['country_id']??null)===4&&($edge['town']??null)==='Анталья'&&($edge['action']??null)==='price'&&($edge['source']??null)==='live_price'&&hmr_exact_name($edge['hotel_name']??'')&&hmr_exact_name($edge['original_name']??''),'native_bridge_binding');
 hmr_need(($edge['request_sha256']??null)==='242f6c22caaef6bd81669e248eb59b3d10b18679515d2a858bc06117fbfdb3e6'&&($edge['response_sha256']??null)==='ba0a765299ee18b025e82dee97a317da2ecb7a03a9c26113119e2645c6ee61e2','native_bridge_provenance');
 $sources=[];$reverse=[];$sourceFamily=[];$countryCount=0;foreach($catalog['HOTELS']as$h){$id=(string)$h['id'];hmr_need(!isset($sources[$id]),'duplicate_source');$sources[$id]=$h;if((string)$h['stateKey']==='5'){++$countryCount;if(hmr_family($h['name'])||hmr_family($h['lName']??'')){$sourceFamily[]=$h;if($h['town']==='Анталья')$reverse[]=$id;}}}
 hmr_need(count($sources)===3260&&$countryCount===3257,'catalog_complete');$source=$sources['190031']??null;hmr_need(is_array($source)&&(string)$source['stateKey']==='5'&&$source['state']==='Турция'&&$source['star']==='5'&&$source['starLName']==='5*'&&(string)$source['townKey']==='5'&&$source['town']==='Анталья'&&hmr_exact_name($source['name'])&&hmr_exact_name($source['lName']),'source_facts');
 hmr_need(hmr_hash(hmr_order($source))===hmr_hash(hmr_order($prior['source'])),'source_drift');hmr_need($reverse===['190031'],'reverse_source_competition');
 $by=[];$family=[];foreach($hotels as$h){$id=(int)$h['id'];hmr_need(!isset($by[$id]),'duplicate_local');$by[$id]=$h;if((int)$h['country_id']===4&&(int)$h['is_active']===1&&hmr_family($h['name']))$family[$id]=true;}
 foreach($aliases as$a){$id=(int)$a['hotel_id'];if(isset($by[$id])&&(int)$by[$id]['country_id']===4&&(int)$by[$id]['is_active']===1&&hmr_family($a['alias']))$family[$id]=true;}
 $ids=array_keys($family);sort($ids,SORT_NUMERIC);hmr_need($ids===HMR_COMPETITORS,'full_country_competition');$sameTown=[];$competitors=[];
 foreach($ids as$id){hmr_need(isset($expected[$id])&&hmr_hash($by[$id])===hmr_hash($expected[$id]),'local_facts_drift');$competitors[]=$by[$id];if($by[$id]['region_name']==='Анталья')$sameTown[]=$id;}
 hmr_need($sameTown===[1441],'local_geography_competition');$target=$by[1441];hmr_need((int)$target['country_id']===4&&(int)$target['is_active']===1&&(int)$target['category']===5&&$target['region_name']==='Анталья'&&hmr_exact_name($target['name']),'target_facts');
 $sc=0;$bc=0;foreach($identities as$r){hmr_need($r['local_hotel_id']===null||(int)$r['local_hotel_id']!==1441,'target_occupied');if($r['supplier_namespace']==='andromeda_catalog'&&(string)$r['external_hotel_id']==='190031'){++$sc;hmr_need(hmr_hash($r)===HMR_ROW,'current_row_drift');}if($r['supplier_namespace']==='operator_5'&&(string)$r['external_hotel_id']==='8365'){++$bc;hmr_need(hmr_hash($r)===HMR_BRIDGE_ROW,'current_bridge_drift');}}
 hmr_need($sc===1&&$bc===1,'source_bridge_count');hmr_need($anex===1441,'effective_anex');hmr_need(($guards['anex_hotel_decisions']??null)===[]&&($guards['anex_review_pair_exclusions']??null)===[],'manual_or_exclusion');
 $ms=$guards['anex_hotel_search_mappings']??[];hmr_need(count($ms)===1,'anex_count');$m=$ms[0];hmr_need((int)$m['anex_hotel_id']===8365&&(int)$m['catalog_hotel_id']===1441&&(int)$m['enabled']===1&&$m['scope']==='preview'&&$m['match_class']==='strong_candidate'&&$m['approval_policy']==='owner_exact_and_strong_20260908'&&$m['mapping_digest']==='27aee5eece162988663a6fda10eb8f515138e3e56513d199f613f1aea177e692'&&$m['source_row_digest']==='8dabb71368e3950899c587c63431b31ea7b51e338b51341c46a861ba12acfcb5','anex_drift');
 return ['source'=>$source,'target'=>$target,'all_name_competitors'=>$competitors,'reverse_source_ids'=>$reverse,'catalog_family'=>$sourceFamily,'native_price_bridge'=>$edge,'bridge_row_sha256'=>HMR_BRIDGE_ROW,'independent_anex'=>['anex_id'=>8365,'local_id'=>1441,'mapping_digest'=>$m['mapping_digest'],'effective'=>true],'source_coordinates'=>null,'geography'=>'explicit_country_and_Antalya_town','prior_evidence'=>$prior];
}
$dir=(string)getenv('MATCH_OPERATION_DIR');
if(in_array('--self-test',$argv??[],true)){
 hmr_need(hash_file('sha256',$dir.'/current.json')===HMR_CURRENT&&hash_file('sha256',$dir.'/catalog.json')===HMR_CATALOG,'fixture_digest');$c=json_decode((string)file_get_contents($dir.'/current.json'),true,64,JSON_THROW_ON_ERROR);$cat=json_decode((string)file_get_contents($dir.'/catalog.json'),true,64,JSON_THROW_ON_ERROR);
 $row=array_values(array_filter($c['rows'],fn($r)=>$r['external_hotel_id']==='190031'))[0]['current_row'];$old=hmr_reconstruct($row);$bridge=hmr_reconstruct($c['operator_5_rows']['operator_5:8365']);hmr_need(hmr_hash($old)===HMR_ROW&&hmr_hash($bridge)===HMR_BRIDGE_ROW,'reconstructed_rows');
 $expected=[];foreach($c['country_hotels']as$h)if(in_array((int)$h['id'],HMR_COMPETITORS,true))$expected[(int)$h['id']]=$h;
 $guards=[];foreach($c['anex_guards']as$k=>$rs)$guards[$k]=array_values(array_filter($rs,fn($r)=>(int)$r['anex_hotel_id']===8365||(int)($r['catalog_hotel_id']??0)===1441));
 $args=[$old,$bridge,$c['country_hotels'],$c['country_aliases'],[$old,$bridge],$guards,1441,$cat,$expected];hmr_guard(...$args);$tests=1;$cases=[];
 foreach(['accepted','conflict','rejected','manual','']as$v){$x=$args;$x[0]['decision_status']=$v;$cases[]=$x;}
 foreach([0,1441,999]as$v){$x=$args;$x[0]['local_hotel_id']=$v;$cases[]=$x;}
 foreach(['supplier_namespace'=>'operator_5','external_hotel_id'=>'8365','evidence_sha256'=>str_repeat('0',64),'catalog_sha256'=>str_repeat('0',64)]as$k=>$v){$x=$args;$x[0][$k]=$v;$cases[]=$x;}
 foreach(['decision_status'=>'accepted','local_hotel_id'=>1441,'external_hotel_id'=>'190031','evidence_json'=>'{}']as$k=>$v){$x=$args;$x[1][$k]=$v;$cases[]=$x;}
 $x=$args;$x[4][]=['supplier_namespace'=>'operator_315','external_hotel_id'=>'99','local_hotel_id'=>1441];$cases[]=$x;$x=$args;$x[4]=[$old];$cases[]=$x;$x=$args;$x[6]=null;$cases[]=$x;
 foreach(['anex_hotel_decisions','anex_review_pair_exclusions']as$k){$x=$args;$x[5][$k]=[['catalog_hotel_id'=>1441]];$cases[]=$x;}
 foreach(['enabled'=>0,'catalog_hotel_id'=>999,'approval_policy'=>'unapproved','mapping_digest'=>str_repeat('0',64)]as$k=>$v){$x=$args;$x[5]['anex_hotel_search_mappings'][0][$k]=$v;$cases[]=$x;}
 foreach(['is_active'=>0,'country_id'=>1,'category'=>4,'region_name'=>'Стамбул','name'=>'RAMADA RESORT LARA']as$k=>$v){$x=$args;foreach($x[2]as&$h)if((int)$h['id']===1441)$h[$k]=$v;unset($h);$cases[]=$x;}
 $x=$args;$h=$expected[1441];$h['id']=999999;$x[2][]=$h;$cases[]=$x;$x=$args;$x[3][]=['hotel_id'=>1229,'alias'=>'Ramada Plaza Antalya','source'=>'test'];$cases[]=$x;
 $x=$args;foreach($x[7]['HOTELS']as&$h)if((string)$h['id']==='5464'){$h['name']='Ramada Plaza Antalya';$h['lName']='Ramada Plaza Antalya';$h['town']='Анталья';}unset($h);$cases[]=$x;
 $x=$args;foreach($x[7]['HOTELS']as&$h)if((string)$h['id']==='190031')$h['star']='4';unset($h);$cases[]=$x;
 foreach($cases as$i=>$x){$failed=false;try{hmr_guard(...$x);}catch(Throwable $e){$failed=true;}hmr_need($failed,'negative_'.(string)$i);++$tests;}
 hmr_need(!hmr_exact_name('Ramada Plaza by Wyndham Antalya Annex')&&!hmr_exact_name('Ramada Resort Antalya')&&!hmr_exact_name('Ramada Plaza Istanbul'),'qualifiers_preserved');++$tests;
 echo 'HMR_SELFTEST_OK checks='.$tests."\n";exit(0);
}
hmr_need(PHP_SAPI==='cli'&&is_dir($dir)&&!is_link($dir)&&basename($dir)===HMR_OP,'operation_dir');$sha=(string)getenv('MATCH_SOURCE_SHA');hmr_need(preg_match('/^[a-f0-9]{40}$/D',$sha)===1,'source_sha');
$db=null;$committed=false;$attempted=false;$updated=false;$base=['operation'=>HMR_OP,'source_sha'=>$sha,'provider_calls'=>0,'no_replay'=>true];
try{
 $reservation=json_decode((string)file_get_contents($dir.'/reservation.json'),true,32,JSON_THROW_ON_ERROR);hmr_need(($reservation['operation']??null)===HMR_OP&&($reservation['source_sha']??null)===$sha&&($reservation['source_sha256']??null)===hash_file('sha256',__FILE__),'reservation');
 hmr_need(hash_file('sha256',$dir.'/current.json')===HMR_CURRENT&&hash_file('sha256',$dir.'/catalog.json')===HMR_CATALOG,'input_digest');$current=json_decode((string)file_get_contents($dir.'/current.json'),true,64,JSON_THROW_ON_ERROR);$catalog=json_decode((string)file_get_contents($dir.'/catalog.json'),true,64,JSON_THROW_ON_ERROR);
 foreach(['andromeda-hotel-resolver.php','anex-search-mapping-registry.php']as$name){hmr_need(isset($reservation['dependencies'][$name])&&hash_file('sha256',$dir.'/'.$name)===$reservation['dependencies'][$name],'dependency_hash');require_once $dir.'/'.$name;}
 $root=realpath((string)getenv('ANYTOOUR_ROOT'));hmr_need(is_string($root)&&basename($root)==='anytoour.ru','root');$boot=$root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');hmr_need(is_file($boot),'db_bootstrap');require_once $boot;
 $db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL SERIALIZABLE');$db->beginTransaction();
 $all=hmr_rows($db,'SELECT * FROM andromeda_hotel_identities ORDER BY supplier_namespace,external_hotel_id LIMIT 50001 FOR UPDATE');$old=null;$bridge=null;foreach($all as$r){if($r['supplier_namespace']==='andromeda_catalog'&&(string)$r['external_hotel_id']==='190031')$old=$r;if($r['supplier_namespace']==='operator_5'&&(string)$r['external_hotel_id']==='8365')$bridge=$r;}hmr_need(is_array($old)&&is_array($bridge),'sources_missing');
 $hotels=hmr_rows($db,'SELECT id,name,country_id,country_name,region_name,subregion_name,category,latitude,longitude,is_active FROM catalog_hotels WHERE country_id=4 ORDER BY id LIMIT 30001 FOR UPDATE',[],30000);
 $aliases=hmr_rows($db,'SELECT a.hotel_id,a.alias,a.source FROM hotel_aliases a JOIN catalog_hotels h ON h.id=a.hotel_id WHERE h.country_id=4 ORDER BY a.hotel_id,a.alias,a.source LIMIT 100001 FOR UPDATE',[],100000);
 $guards=[];foreach(['anex_hotel_search_mappings','anex_hotel_decisions','anex_review_pair_exclusions']as$table)$guards[$table]=hmr_rows($db,"SELECT * FROM $table WHERE anex_hotel_id=8365 OR catalog_hotel_id=1441 ORDER BY anex_hotel_id,catalog_hotel_id LIMIT 1001 FOR UPDATE",[],1000);
 $expected=[];foreach($current['country_hotels']as$h)if(in_array((int)$h['id'],HMR_COMPETITORS,true))$expected[(int)$h['id']]=$h;$anex=AnyTourAnexSearchMappingRegistry::fromPdo($db);$proof=hmr_guard($old,$bridge,$hotels,$aliases,$all,$guards,$anex->resolve('anex_online','8365','preview'),$catalog,$expected);
 $before=[];foreach($all as$r){$key=$r['supplier_namespace'].':'.$r['external_hotel_id'];hmr_need(!isset($before[$key]),'duplicate_identity');$before[$key]=hmr_hash($r);}hmr_save($dir.'/capture.json',$base+['prior_row'=>$old,'bridge_row'=>$bridge,'identity_hashes'=>$before,'anex_guards'=>$guards,'proof'=>$proof,'current_sha256'=>HMR_CURRENT,'catalog_sha256'=>HMR_CATALOG]);
 $evidence=['operation_id'=>HMR_OP,'rule'=>'retained_native_price_bridge_and_current_canonical_identity','prior_row_sha256'=>HMR_ROW,'prior_catalog_sha256'=>$old['catalog_sha256'],'prior_evidence_sha256'=>HMR_EVIDENCE,'current_read_sha256'=>HMR_CURRENT,'catalog_sha256'=>HMR_CATALOG,'proof'=>$proof];$ej=hmr_json($evidence);$eh=hash('sha256',$ej);
 hmr_save($dir.'/plan.json',$base+['pending_only'=>true,'expected_previous_row_sha256'=>HMR_ROW,'supplier_namespace'=>'andromeda_catalog','external_hotel_id'=>'190031','local_hotel_id'=>1441,'decision_status'=>'accepted','catalog_sha256'=>HMR_CATALOG,'evidence_sha256'=>$eh,'evidence_json'=>$ej]);
 $s=$db->prepare("UPDATE andromeda_hotel_identities SET local_hotel_id=1441,decision_status='accepted',catalog_sha256=?,evidence_sha256=?,evidence_json=? WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id='190031' AND decision_status='pending' AND local_hotel_id IS NULL AND catalog_sha256=? AND evidence_sha256=? AND evidence_json=?");$s->execute([HMR_CATALOG,$eh,$ej,$old['catalog_sha256'],HMR_EVIDENCE,$old['evidence_json']]);hmr_need($s->rowCount()===1,'conditional_update_count');$updated=true;
 $after=hmr_rows($db,'SELECT * FROM andromeda_hotel_identities ORDER BY supplier_namespace,external_hotel_id LIMIT 50001');$preserved=[];foreach($after as$r){$key=$r['supplier_namespace'].':'.$r['external_hotel_id'];if($key!=='andromeda_catalog:190031')$preserved[$key]=hmr_hash($r);}$others=$before;unset($others['andromeda_catalog:190031']);hmr_need(count($after)===count($all)&&$others===$preserved,'other_identities_changed');
 hmr_save($dir.'/pre-commit.json',$base+['updated_uncommitted'=>1,'evidence_sha256'=>$eh,'prior_identities_preserved'=>count($others),'prior_identity_hashes_sha256'=>hmr_hash($others)]);$attempted=true;$db->commit();$committed=true;$db->exec('START TRANSACTION READ ONLY');
 $rows=hmr_rows($db,"SELECT i.*,h.id AS existing_catalog_hotel_id FROM andromeda_hotel_identities i LEFT JOIN catalog_hotels h ON h.id=i.local_hotel_id WHERE i.decision_status IN ('accepted','rejected') ORDER BY i.supplier_namespace,i.external_hotel_id LIMIT 50001");$projection=[];$written=null;foreach($rows as$r){$projection[]=['supplier_namespace'=>$r['supplier_namespace'],'external_hotel_id'=>$r['external_hotel_id'],'decision_status'=>$r['decision_status'],'catalog_hotel_id'=>$r['local_hotel_id'],'existing_catalog_hotel_id'=>$r['existing_catalog_hotel_id']];if($r['supplier_namespace']==='andromeda_catalog'&&(string)$r['external_hotel_id']==='190031')$written=$r;}
 hmr_need(is_array($written)&&(int)$written['local_hotel_id']===1441&&$written['decision_status']==='accepted'&&$written['catalog_sha256']===HMR_CATALOG&&$written['evidence_sha256']===$eh&&hash('sha256',$written['evidence_json'])===$eh,'post_commit_row');
 $resolver=AnyTourAndromedaHotelResolver::fromRows($projection,hmr_hash($projection));$page=$resolver->apply(['provider'=>'andromeda','selection_enabled'=>false,'offers'=>[['provider'=>'andromeda','selection_enabled'=>false,'local_hotel_id'=>null,'supplier_namespace'=>'andromeda_catalog','external_hotel_id'=>'190031']]]);hmr_need($page['offers'][0]['local_hotel_id']===1441,'post_commit_resolver');$anex=AnyTourAnexSearchMappingRegistry::fromPdo($db);hmr_need($anex->resolve('anex_online','8365','preview')===1441,'post_commit_anex');
 $bridgeAfter=hmr_rows($db,"SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace='operator_5' AND external_hotel_id='8365'");hmr_need(count($bridgeAfter)===1&&hmr_hash($bridgeAfter[0])===HMR_BRIDGE_ROW,'post_commit_bridge_preserved');$counts=hmr_rows($db,'SELECT decision_status,COUNT(*) AS n FROM andromeda_hotel_identities GROUP BY decision_status ORDER BY decision_status');$db->rollBack();
 $out=$base+['state'=>'committed_verified','committed_at_utc'=>gmdate('c'),'database_writes'=>1,'mapping_writes'=>1,'accepted_delta'=>1,'pending_delta'=>-1,'unique_samo_local_delta'=>1,'triple_delta'=>1,'prior_identities_preserved'=>count($others),'prior_identity_hashes_sha256'=>hmr_hash($others),'identity_status_counts'=>$counts,'row'=>$written,'effective_resolver_target'=>1441,'anex_effective_target'=>1441,'bridge_preserved'=>true,'readback_verified'=>true];
}catch(Throwable $e){if($db instanceof PDO&&$db->inTransaction())$db->rollBack();$reason=$e instanceof RuntimeException&&preg_match('/^[a-z0-9_]{1,80}$/D',$e->getMessage())?$e->getMessage():'operation_failed';$out=$base+['state'=>$committed?'committed_unverified':($attempted?'commit_outcome_unknown':'rolled_back_or_prewrite_failed'),'reason'=>$reason,'database_writes'=>$committed?1:($attempted?null:0),'mapping_writes'=>$committed?1:($attempted?null:0),'update_attempted'=>$updated,'readback_verified'=>false];}
$hash=hmr_save($dir.'/result.json',$out);hmr_save($dir.'/receipt.json',$base+['state'=>$out['state'],'result_sha256'=>$hash,'mapping_writes'=>$out['mapping_writes'],'readback_verified'=>$out['readback_verified']]);echo hmr_json(['state'=>$out['state'],'mapping_writes'=>$out['mapping_writes'],'result_sha256'=>$hash,'reason'=>$out['reason']??null])."\n";exit($out['state']==='committed_verified'?0:2);
