<?php
declare(strict_types=1);
putenv('MATCH_TEST_LIBRARY=1');
putenv('MATCH_STATE_CONSENSUS_TEST_LIBRARY=1');
require_once __DIR__.'/hotel_match_state_country_consensus.php';

const MSA_OP='hotel-match-state-country-consensus-apply-1971-20260915-v1';
const MSA_REVIEW_OP='hotel-match-state-country-consensus-1971-20260915-v3';
const MSA_REVIEW_SHA256='5338dd98e15fb15db67547122d684eb5d51ec5e78e011efb5f30223417df4d79';
const MSA_PLAN_COUNT=17;
const MSA_POLICY='owner_exact_and_strong_20260908';

function msa_json(array $v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";}
function msa_write(string $file,array $v):string{$raw=msa_json($v);$f=@fopen($file,'x+b');if(!$f)throw new RuntimeException('exclusive_file');try{if(fwrite($f,$raw)!==strlen($raw)||!fflush($f))throw new RuntimeException('write');if(function_exists('fsync')&&!fsync($f))throw new RuntimeException('sync');rewind($f);if(stream_get_contents($f)!==$raw)throw new RuntimeException('readback');}finally{fclose($f);}return hash('sha256',$raw);}
function msa_review(string $path):array{$raw=@file_get_contents($path);if(!is_string($raw)||hash('sha256',$raw)!==MSA_REVIEW_SHA256)throw new RuntimeException('review_hash');$r=json_decode($raw,true,64,JSON_THROW_ON_ERROR);if(!is_array($r)||($r['operation_id']??'')!==MSA_REVIEW_OP||($r['state']??'')!=='completed_read_only'||($r['no_replay']??false)!==true||($r['db_writes']??-1)!==0||($r['mapping_writes']??-1)!==0||count($r['candidates']??[])!==MSA_PLAN_COUNT)throw new RuntimeException('review_contract');return$r;}
function msa_plan(array $review):array{$out=[];foreach($review['candidates']??[] as $r){if(!is_array($r)||($r['supplier_namespace']??'')!=='andromeda_catalog'||($r['route']??'')!=='auto_accept_candidate')throw new RuntimeException('plan_row');$id=(string)($r['external_hotel_id']??'');$target=(int)($r['target']??0);if(!preg_match('/^[1-9][0-9]{0,19}$/D',$id)||$target<=0)throw new RuntimeException('plan_identity');if(isset($out[$id])&&(int)$out[$id]['target']!==$target)throw new RuntimeException('plan_conflict');$out[$id]=$r;}if(count($out)!==MSA_PLAN_COUNT)throw new RuntimeException('plan_count');return$out;}
function msa_resolve(array $e,int $cid,array $hotels,array $forms,array $exact,array $tokenIndex,array $geoExact,array $aliases,array $countrylessExact,array $countrylessTokens):array{$names=mcr_names($e);$points=mcr_points($e);$explicit=msc_explicit_countries($names,$aliases);if($explicit&&$explicit!==[$cid])return['route'=>'hard_conflict','reason'=>'row_explicit_country_conflict','explicit_country_ids'=>$explicit];$base=mcr_select_candidate($names,$cid,$points,$hotels,$forms,$exact,$tokenIndex,$geoExact);if(($base['route']??'')!=='needs_extra_evidence')return$base;$geo=msc_countryless_select($names,$cid,$points,$hotels,$forms,$aliases,$countrylessExact,$countrylessTokens);return($geo['route']??'')==='needs_extra_evidence'?$base:$geo;}
function msa_coverage(PDO $db):array{$a=msc_query($db,"SELECT DISTINCT m.catalog_hotel_id id FROM anex_hotel_search_mappings m WHERE m.enabled=1 AND m.scope='preview' AND m.approval_policy=? AND NOT EXISTS(SELECT 1 FROM anex_hotel_decisions d WHERE d.anex_hotel_id=m.anex_hotel_id) AND NOT EXISTS(SELECT 1 FROM anex_review_pair_exclusions x WHERE x.anex_hotel_id=m.anex_hotel_id AND x.catalog_hotel_id=m.catalog_hotel_id) UNION SELECT d.catalog_hotel_id id FROM anex_hotel_decisions d WHERE d.decision_status='accepted' AND d.catalog_hotel_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM anex_review_pair_exclusions x WHERE x.anex_hotel_id=d.anex_hotel_id AND x.catalog_hotel_id=d.catalog_hotel_id)",[MSA_POLICY]);$d=msc_query($db,"SELECT DISTINCT local_hotel_id id FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IS NOT NULL");$aa=array_map('intval',array_column($a,'id'));$dd=array_map('intval',array_column($d,'id'));return['anex_unique_local'=>count($aa),'andromeda_unique_local'=>count($dd),'all_three'=>count(array_intersect($aa,$dd))];}
function msa_readback_ok(array $r,int $target):bool{$e=mcr_evidence((string)($r['evidence_json']??''));return($r['decision_status']??'')==='accepted'&&(int)($r['local_hotel_id']??0)===$target&&($e['match_promotion']['operation_id']??'')===MSA_OP&&(int)($e['match_promotion']['target_local_hotel_id']??0)===$target;}

if(getenv('MATCH_STATE_APPLY_TEST_LIBRARY')==='1')return;
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
$op=(string)getenv('MATCH_OPERATION_ID');$sha=(string)getenv('MATCH_SOURCE_SHA');if($op!==MSA_OP||!preg_match('/^[0-9a-f]{40}$/D',$sha))throw new RuntimeException('operation_or_source_guard');$home=(string)getenv('HOME');if($home==='')throw new RuntimeException('home');$dir=$home.'/.anytoour-match/operations/'.MSA_OP;$reviewPath=$home.'/.anytoour-match/operations/'.MSA_REVIEW_OP.'/result.json';$res=mcr_evidence((string)@file_get_contents($dir.'/reservation.json'));if(($res['operation_id']??'')!==MSA_OP||($res['source_sha']??'')!==$sha||($res['state']??'')!=='reserved_before_db_access'||(int)($res['planned_rows']??-1)!==MSA_PLAN_COUNT||($res['review_result_sha256']??'')!==MSA_REVIEW_SHA256)throw new RuntimeException('reservation');$review=msa_review($reviewPath);$plans=msa_plan($review);$root=realpath(getcwd());if(!$root||basename($root)!=='anytoour.ru')throw new RuntimeException('root');require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET SESSION innodb_lock_wait_timeout=30');$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->beginTransaction();$committed=false;
try{
    $eng=array_column(msc_query($db,"SELECT TABLE_NAME,ENGINE FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME IN ('andromeda_hotel_identities','catalog_hotels','hotel_aliases')"),'ENGINE','TABLE_NAME');foreach(['andromeda_hotel_identities','catalog_hotels','hotel_aliases'] as $t)if(strtoupper((string)($eng[$t]??''))!=='INNODB')throw new RuntimeException('transaction_table_'.$t);
    $coreIds=[];foreach(msc_query($db,'SELECT id,name FROM catalog_countries WHERE is_active=1 ORDER BY id') as $c)if(mcr_is_core8_name((string)$c['name']))$coreIds[(int)$c['id']]=(string)$c['name'];if(count($coreIds)<6)throw new RuntimeException('core8');$marks=implode(',',array_fill(0,count($coreIds),'?'));
    $hotels=[];$forms=[];foreach(msc_query($db,"SELECT id,country_id,country_name,region_id,region_name,subregion_id,subregion_name,name,category,latitude,longitude FROM catalog_hotels WHERE is_active=1 AND country_id IN ($marks) ORDER BY country_id,id",array_keys($coreIds)) as $h){$id=(int)$h['id'];$hotels[$id]=$h;$forms[$id]=[(string)$h['name']];}foreach(msc_query($db,"SELECT a.hotel_id,a.alias FROM hotel_aliases a JOIN catalog_hotels h ON h.id=a.hotel_id WHERE h.is_active=1 AND h.country_id IN ($marks) ORDER BY a.hotel_id,a.id",array_keys($coreIds)) as $a){$id=(int)$a['hotel_id'];if(isset($forms[$id]))$forms[$id][]=(string)$a['alias'];}
    $exact=[];$tokenIndex=[];foreach($forms as $id=>$list){$cid=(int)$hotels[$id]['country_id'];foreach(array_unique($list) as $raw){$n=mcr_norm((string)$raw);if($n==='')continue;$exact[$cid][$n][]=$id;foreach(mcr_tokens((string)$raw) as $t)$tokenIndex[$cid][$t][$id]=true;}}$geoExact=mcr_geo_exact_index($hotels,$forms);$aliases=msc_country_aliases($coreIds);[$countrylessExact,$countrylessTokens]=msc_countryless_indexes($hotels,$forms,$aliases);
    $pending=msc_query($db,"SELECT supplier_namespace,external_hotel_id,local_hotel_id,decision_status,evidence_sha256,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='pending' AND local_hotel_id IS NULL ORDER BY external_hotel_id FOR UPDATE");$byId=[];foreach($pending as $r)$byId[(string)$r['external_hotel_id']]=$r;$inferred=msc_marker_consensus($pending,$coreIds);$before=msa_coverage($db);$valid=[];$holds=[];
    foreach($plans as $id=>$plan){$cur=$byId[$id]??null;if(!$cur){$holds[]=['external_hotel_id'=>$id,'reason'=>'current_state_protected_or_missing'];continue;}if((string)$cur['evidence_sha256']!==(string)$plan['evidence_sha256']){$holds[]=['external_hotel_id'=>$id,'reason'=>'evidence_sha_changed'];continue;}$e=mcr_evidence((string)$cur['evidence_json']);$sk=mcr_state_key($e);$inf=$sk!==null?($inferred[$sk]??null):null;if(!$inf||$sk!==(string)($plan['state_key']??'')||(int)$inf['country_id']!==(int)($plan['inferred_country_id']??0)){$holds[]=['external_hotel_id'=>$id,'reason'=>'state_country_consensus_changed'];continue;}$cid=(int)$inf['country_id'];$sel=msa_resolve($e,$cid,$hotels,$forms,$exact,$tokenIndex,$geoExact,$aliases,$countrylessExact,$countrylessTokens);if(($sel['route']??'')!=='auto_accept_candidate'||(int)($sel['target']??0)!==(int)$plan['target']){$holds[]=['external_hotel_id'=>$id,'reason'=>'candidate_changed','current_route'=>$sel['route']??null,'current_reason'=>$sel['reason']??null,'current_target'=>$sel['target']??null];continue;}$target=(int)$sel['target'];if(!isset($hotels[$target])||(int)$hotels[$target]['country_id']!==$cid){$holds[]=['external_hotel_id'=>$id,'reason'=>'target_country_or_activity_changed'];continue;}$valid[$id]=['cur'=>$cur,'evidence'=>$e,'target'=>$target,'selection'=>$sel,'inference'=>$inf];}
    $up=$db->prepare("UPDATE andromeda_hotel_identities SET local_hotel_id=?,decision_status='accepted',evidence_sha256=?,evidence_json=? WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=? AND decision_status='pending' AND local_hotel_id IS NULL AND evidence_sha256 <=> ?");$written=[];
    foreach($valid as $id=>$x){$prior=$x['evidence'];if(isset($prior['match_promotion'])){$holds[]=['external_hotel_id'=>$id,'reason'=>'promotion_field_already_present'];continue;}$promotion=['operation_id'=>MSA_OP,'rule'=>(string)$x['selection']['reason'],'target_local_hotel_id'=>(int)$x['target'],'review_operation_id'=>MSA_REVIEW_OP,'review_result_sha256'=>MSA_REVIEW_SHA256,'server_current_revalidated'=>true,'state_key'=>mcr_state_key($prior),'state_country_inference'=>$x['inference'],'coordinate_conflict_gt5km_blocked'=>true,'qualifiers_preserved'=>true,'distance_km'=>$x['selection']['distance_km']??null,'score'=>$x['selection']['score']??null,'margin'=>$x['selection']['margin']??null];$new=$prior;$new['match_promotion']=$promotion;$json=msa_json($new);$newSha=hash('sha256',$json);$up->execute([(int)$x['target'],$newSha,$json,$id,$x['cur']['evidence_sha256']]);if($up->rowCount()!==1)throw new RuntimeException('concurrency_'.$id);$written[]=['external_hotel_id'=>$id,'target'=>(int)$x['target'],'new_sha'=>$newSha,'rule'=>$promotion['rule']];}
    $db->commit();$committed=true;$read=[];foreach($written as $w){$r=msc_query($db,"SELECT external_hotel_id,local_hotel_id,decision_status,evidence_sha256,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=?",[$w['external_hotel_id']]);if(count($r)!==1||!msa_readback_ok($r[0],(int)$w['target'])||(string)$r[0]['evidence_sha256']!==$w['new_sha'])throw new RuntimeException('post_commit_'.$w['external_hotel_id']);$read[]=['external_hotel_id'=>$w['external_hotel_id'],'local_hotel_id'=>(int)$r[0]['local_hotel_id'],'decision_status'=>$r[0]['decision_status'],'evidence_sha256'=>$r[0]['evidence_sha256'],'rule'=>$w['rule']];}$after=msa_coverage($db);$rules=[];foreach($read as $r)$rules[$r['rule']]=($rules[$r['rule']]??0)+1;ksort($rules);
    $result=['schema'=>'hotel-match-state-country-consensus-apply/1','operation_id'=>MSA_OP,'source_sha'=>$sha,'state'=>'completed_committed','server_current'=>true,'review_operation_id'=>MSA_REVIEW_OP,'review_result_sha256'=>MSA_REVIEW_SHA256,'planned'=>count($plans),'validated'=>count($valid),'written'=>count($read),'holds_count'=>count($holds),'holds'=>$holds,'written_by_rule'=>$rules,'coverage_before'=>$before,'coverage_after'=>$after,'post_commit_readback'=>$read,'supplier_calls'=>0,'tourvisor_calls'=>0,'external_calls'=>0,'booking_calls'=>0,'operator_5_writes'=>0,'mapping_writes'=>count($read),'no_replay'=>true,'completed_at'=>gmdate('c')];$hash=msa_write($dir.'/result.json',$result);$raw=(string)file_get_contents($dir.'/result.json');$ok=hash('sha256',$raw)===$hash&&count((mcr_evidence($raw))['post_commit_readback']??[])===count($read);$receipt=['operation_id'=>MSA_OP,'source_sha'=>$sha,'state'=>'completed_committed','result_sha256'=>$hash,'readback_verified'=>$ok,'planned'=>count($plans),'written'=>count($read),'holds_count'=>count($holds),'post_commit_rows'=>count($read),'operator_5_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'external_calls'=>0,'booking_calls'=>0,'no_replay'=>true,'completed_at'=>gmdate('c')];msa_write($dir.'/receipt.json',$receipt);if(!$ok)throw new RuntimeException('result_readback');echo msa_json(['operation_id'=>MSA_OP,'state'=>'completed_committed','planned'=>count($plans),'validated'=>count($valid),'written'=>count($read),'holds'=>count($holds),'written_by_rule'=>$rules,'coverage_before'=>$before,'coverage_after'=>$after,'result_sha256'=>$hash]);
}catch(Throwable $e){if(!$committed&&$db->inTransaction())$db->rollBack();if(!$committed&&!is_file($dir.'/failure.json'))msa_write($dir.'/failure.json',['operation_id'=>MSA_OP,'source_sha'=>$sha,'state'=>'rolled_back','error_class'=>get_class($e),'error'=>substr($e->getMessage(),0,300),'supplier_calls'=>0,'tourvisor_calls'=>0,'external_calls'=>0,'booking_calls'=>0,'db_writes'=>0,'no_replay'=>true,'failed_at'=>gmdate('c')]);throw $e;}
