<?php
declare(strict_types=1);error_reporting(0);ob_start();
const OP='hotel-match-live4-exact-bridge-accept-1971-20260912-v2';const POLICY='owner_exact_and_strong_20260908';
function n($v):string{$s=mb_strtolower(trim((string)$v),'UTF-8');$s=strtr($s,['ё'=>'е','&'=>' and ','hotell'=>'hotel','otel'=>'hotel']);$s=preg_replace('/\(\s*(?:ex|ех|formerly|быв)\s*[.:\-]?\s*[^)]*\)/iu',' ',$s);preg_match_all('/[\p{L}\p{N}]+/u',$s,$m);$drop=['hotel','hotels','resort','resorts','spa','otel','отель','отели','гостиница','the','by','and'];return implode(' ',array_filter($m[0]??[],fn($x)=>$x!==''&&!in_array($x,$drop,true)));}
function bn(array$r):array{$raw=(string)$r['evidence_json'];$e=json_decode($raw,true);if(!is_array($e)||hash('sha256',$raw)!==(string)$r['evidence_sha256'])return[];$id=(string)$r['external_hotel_id'];$st=[$e];$o=[];$g=0;while($st&&$g++<5000){$v=array_pop($st);if(!is_array($v))continue;if(isset($v['name'])&&(string)($v['id']??$v['hotelKey']??'')===$id){foreach([$v['name']??null,$v['lName']??null]as$x){$z=n($x);if($z!=='')$o[$z]=1;}}foreach($v as$k=>$x)if(is_array($x)&&!in_array((string)$k,['candidates','targets','local','hotels','offers'],true))$st[]=$x;}return array_keys($o);}
$want=[32599=>[46679,'grand pamir'],32692=>[70291,'almina inn'],32734=>[17456,'grand washington'],794=>[229,'grand hurghada']];$pdo=null;$committed=false;$phase='init';try{$root=realpath(getcwd());if(!$root||basename($root)!=='anytoour.ru')throw new Exception('root');require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$pdo=v2_data_db();$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->exec('SET SESSION innodb_lock_wait_timeout=15');$pdo->beginTransaction();$phase='guards';
$prot=[];foreach(['anex_hotel_search_mappings','anex_hotel_decisions','anex_review_pair_exclusions']as$t)foreach($pdo->query("SELECT anex_hotel_id FROM $t FOR UPDATE")->fetchAll(PDO::FETCH_COLUMN)as$x)$prot[(int)$x]=1;
$oq=$pdo->prepare('SELECT hotel_name,country_id FROM anex_search_hotel_observations WHERE anex_hotel_id=? ORDER BY search_count DESC,last_seen_utc DESC');$hq=$pdo->prepare('SELECT id,name,country_id,is_active FROM catalog_hotels WHERE id=? FOR UPDATE');$andq=$pdo->prepare("SELECT external_hotel_id,evidence_sha256,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id=?");$rows=[];
foreach($want as$aid=>$spec){[$lid,$expected]=$spec;if(isset($prot[$aid]))throw new Exception('became_protected_'.$aid);$oq->execute([$aid]);$oo=$oq->fetchAll(PDO::FETCH_ASSOC);if(!$oo)throw new Exception('observation_missing_'.$aid);$countries=[];$names=[];foreach($oo as$o){$countries[(int)$o['country_id']]=1;$z=n($o['hotel_name']);if($z!=='')$names[$z]=1;}if(count($countries)!==1||count($names)!==1||!isset($names[$expected]))throw new Exception('observation_conflict_'.$aid);$cid=(int)array_key_first($countries);$hq->execute([$lid]);$h=$hq->fetch(PDO::FETCH_ASSOC);if(!$h||(int)$h['is_active']!==1||(int)$h['country_id']!==$cid)throw new Exception('local_'.$aid);
$peer=[];$pq=$pdo->prepare('SELECT o.hotel_name,m.catalog_hotel_id FROM anex_search_hotel_observations o JOIN anex_hotel_search_mappings m ON m.anex_hotel_id=o.anex_hotel_id WHERE o.country_id=?');$pq->execute([$cid]);foreach($pq->fetchAll(PDO::FETCH_ASSOC)as$p)if(n($p['hotel_name'])===$expected)$peer[(int)$p['catalog_hotel_id']]=1;$andq->execute([$lid]);$and=false;foreach($andq->fetchAll(PDO::FETCH_ASSOC)as$ar)if(in_array($expected,bn($ar),true)){$and=true;break;}$peerSame=isset($peer[$lid]);$peerOther=array_diff(array_keys($peer),[$lid]);if($peerOther)throw new Exception('peer_conflict_'.$aid);if(!$and||($aid!==794&&!$peerSame))throw new Exception('evidence_'.$aid);$rows[]=[$aid,$lid,$expected,$h['name'],$and,$peerSame];}
if(count($rows)!==4)throw new Exception('count');$ins=$pdo->prepare('INSERT INTO anex_hotel_search_mappings(anex_hotel_id,catalog_hotel_id,match_class,scope,approval_policy,source_row_digest,mapping_digest,enabled) VALUES(?,?,?,?,?,?,?,1)');$written=[];foreach($rows as[$aid,$lid,$expected,$lname,$and,$peer]){$sd=hash('sha256',json_encode([OP,$aid,$lid,$expected,$lname,$and,$peer],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));$md=hash('sha256',json_encode([$aid,$lid,'exact','preview',POLICY,$sd],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));$ins->execute([$aid,$lid,'exact','preview',POLICY,$sd,$md]);if($ins->rowCount()!==1)throw new Exception('insert_'.$aid);$written[]=[$aid,$lid,$md];}$pdo->commit();$committed=true;$phase='readback';$pdo->exec('START TRANSACTION READ ONLY');$q=$pdo->prepare('SELECT catalog_hotel_id,mapping_digest,enabled FROM anex_hotel_search_mappings WHERE anex_hotel_id=?');foreach($written as[$aid,$lid,$md]){$q->execute([$aid]);$z=$q->fetchAll(PDO::FETCH_ASSOC);if(count($z)!==1||(int)$z[0]['catalog_hotel_id']!==$lid||(int)$z[0]['enabled']!==1||$z[0]['mapping_digest']!==$md)throw new Exception('readback_'.$aid);}$pdo->exec('ROLLBACK');$out=['status'=>'accepted','operation_id'=>OP,'planned'=>4,'written'=>4,'readback'=>true,'pairs'=>array_map(fn($r)=>[$r[0],$r[1]],$written),'database_writes'=>4,'mapping_writes'=>4,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true];}catch(Throwable$e){if($pdo instanceof PDO&&$pdo->inTransaction())$pdo->rollBack();$out=['status'=>'failed','operation_id'=>OP,'phase'=>$phase,'commit_completed'=>$committed,'safe_message'=>substr($e->getMessage(),0,120),'database_writes'=>$committed?null:0,'mapping_writes'=>$committed?null:0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true];}while(ob_get_level())ob_end_clean();echo 'LIVE4_ACCEPT_V2:'.json_encode($out,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";exit(($out['status']??'')==='accepted'?0:2);
