<?php
declare(strict_types=1);
if (!defined('FC_LIBRARY_ONLY')) define('FC_LIBRARY_ONLY', true);
require_once __DIR__ . '/hotel_match_former_name_review.php';

const HMFNA_OPERATION = 'hotel-match-former-name-accept-1971-20260911-v1';

function hmfna_require_transactional(PDO $db): void {
    $tables=['catalog_hotels','catalog_hotel_details','hotel_aliases','anex_hotel_search_mappings','anex_hotel_decisions','anex_review_pair_exclusions','anex_hotels','anex_search_hotel_observations','andromeda_hotel_identities','andromeda_search_hotel_observations'];
    $q=$db->prepare("SELECT ENGINE FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?");
    foreach($tables as $table){$q->execute([$table]);$engine=$q->fetchColumn();if($engine===false)throw new RuntimeException('required_table_missing:'.$table);if(strcasecmp((string)$engine,'InnoDB')!==0)throw new RuntimeException('required_table_not_innodb:'.$table);}
}
function hmfna_identity_counts(PDO $db): array {
    $out=['accepted'=>0,'pending'=>0,'conflict'=>0];
    foreach($db->query("SELECT decision_status,COUNT(*) n FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' GROUP BY decision_status")->fetchAll(PDO::FETCH_ASSOC) as $row){$s=(string)$row['decision_status'];if(array_key_exists($s,$out))$out[$s]=(int)$row['n'];}
    return $out;
}
function hmfna_candidate_safe(array $row): bool {
    if(!in_array((string)($row['provider']??''),['anex','andromeda'],true))return false;
    if(!isset(MBR_CORE8[(int)($row['country_id']??0)])||(int)($row['target_local_hotel_id']??0)<=0)return false;
    $source=(string)($row['source_name']??'');$former=(string)($row['former_name']??'');$key=hmfn_key($source);if($key===''||$key!==hmfn_key($former))return false;
    if(hmfn_critical($source)!==hmfn_critical($former))return false;
    $tokens=array_values(array_unique(hmfn_tokens($source)));if(!$tokens)return false;
    $distance=$row['distance_m']??null;$place=(bool)($row['place_match']??false);if(!($place||($distance!==null&&(float)$distance<=1000.0)))return false;if($distance!==null&&(float)$distance>5000.0)return false;
    if(count($tokens)===1){$token=(string)$tokens[0];if(strlen($token)<6||!($row['single_token_coordinate_anchor']??false)||$distance===null||(float)$distance>100.0)return false;if(($row['rule']??'')!=='exact_former_name_single_distinctive_coordinate')return false;}
    else{if(($row['rule']??'')!=='exact_former_name_multi_token_direct_geo')return false;}
    return true;
}
function hmfna_andromeda_evidence(string $operation,array $row,array $prior): array {
    return ['prior_evidence'=>$prior,'promotion'=>['operation_id'=>$operation,'lane'=>'MATCH','provider'=>'andromeda','rule'=>$row['rule'],'country_id'=>(int)$row['country_id'],'target'=>(int)$row['target_local_hotel_id'],'source_name'=>$row['source_name'],'former_name'=>$row['former_name'],'identity_tokens'=>$row['identity_tokens']??[],'distance_m'=>$row['distance_m']??null,'place_match'=>(bool)($row['place_match']??false),'single_token_coordinate_anchor'=>(bool)($row['single_token_coordinate_anchor']??false),'existing_anex_tourvisor_bridge'=>(bool)($row['existing_opposite_provider_bridge']??false),'source_category'=>$row['source_category']??null,'target_category'=>$row['target_category']??null,'category_mismatch'=>(bool)($row['category_mismatch']??false),'observation_count'=>(int)($row['observation_count']??0),'last_seen_utc'=>$row['last_seen_utc']??null,'server_current'=>true]];
}
function hmfna_anex_evidence(string $operation,array $row): array {
    return ['operation_id'=>$operation,'lane'=>'MATCH','provider'=>'anex','rule'=>$row['rule'],'anex_hotel_id'=>(int)$row['external_id'],'country_id'=>(int)$row['country_id'],'target'=>(int)$row['target_local_hotel_id'],'source_name'=>$row['source_name'],'former_name'=>$row['former_name'],'identity_tokens'=>$row['identity_tokens']??[],'distance_m'=>$row['distance_m']??null,'place_match'=>(bool)($row['place_match']??false),'single_token_coordinate_anchor'=>(bool)($row['single_token_coordinate_anchor']??false),'existing_andromeda_tourvisor_bridge'=>(bool)($row['existing_opposite_provider_bridge']??false),'source_category'=>$row['source_category']??null,'target_category'=>$row['target_category']??null,'category_mismatch'=>(bool)($row['category_mismatch']??false),'search_count'=>(int)($row['observation_count']??0),'last_seen_utc'=>$row['last_seen_utc']??null,'server_current'=>true];
}
function hmfna_accept(PDO $db,string $operation=HMFNA_OPERATION,int $maxWrites=100): array {
    if($operation!==HMFNA_OPERATION)throw new RuntimeException('operation_scope');if($maxWrites<1||$maxWrites>100)throw new RuntimeException('write_scope_limit_config');
    $db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);hmfna_require_transactional($db);$db->exec('SET SESSION innodb_lock_wait_timeout=20');$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');
    $beforeCoverage=fc_coverage($db);$beforeIdentity=hmfna_identity_counts($db);$andRows=[];$anRows=[];$writes=0;$liveWrites=0;$bridgeWrites=0;$planned=['andromeda'=>0,'anex'=>0];$skipped=['andromeda_not_safe'=>0,'andromeda_stale'=>0,'anex_not_safe'=>0,'anex_protected'=>0,'anex_pair_excluded'=>0];
    try{
        $db->beginTransaction();
        [$hotels,$names]=$fc=fc_catalog($db);[$formerIndex,$formerSegments]=hmfn_index($hotels,$names);$shaCountry=fc_sha_countries($db);
        $db->query("SELECT external_hotel_id FROM andromeda_search_hotel_observations WHERE supplier_namespace='andromeda_catalog' ORDER BY external_hotel_id FOR UPDATE")->fetchAll(PDO::FETCH_COLUMN);[$latest,$counts,$lastSeen]=mlp_observations($db);
        $pending=$db->query("SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='pending' AND local_hotel_id IS NULL ORDER BY external_hotel_id FOR UPDATE")->fetchAll(PDO::FETCH_ASSOC);
        $db->query("SELECT external_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IS NOT NULL ORDER BY external_hotel_id FOR UPDATE")->fetchAll(PDO::FETCH_COLUMN);[$anexLocal,$andromedaLocal]=mbr_local_sets($db);
        $manual=array_fill_keys(array_map('intval',$db->query('SELECT anex_hotel_id FROM anex_hotel_decisions ORDER BY anex_hotel_id FOR UPDATE')->fetchAll(PDO::FETCH_COLUMN)),true);$existing=array_fill_keys(array_map('intval',$db->query('SELECT anex_hotel_id FROM anex_hotel_search_mappings ORDER BY anex_hotel_id FOR UPDATE')->fetchAll(PDO::FETCH_COLUMN)),true);$excluded=[];foreach($db->query('SELECT anex_hotel_id,catalog_hotel_id FROM anex_review_pair_exclusions ORDER BY anex_hotel_id,catalog_hotel_id FOR UPDATE')->fetchAll(PDO::FETCH_ASSOC) as $x)$excluded[(int)$x['anex_hotel_id']][(int)$x['catalog_hotel_id']]=true;
        $staging=[];foreach($db->query('SELECT * FROM anex_hotels ORDER BY anex_hotel_id FOR UPDATE')->fetchAll(PDO::FETCH_ASSOC) as $s)$staging[(int)$s['anex_hotel_id']]=$s;$observed=[];foreach($db->query('SELECT * FROM anex_search_hotel_observations ORDER BY search_count DESC,last_seen_utc DESC,anex_hotel_id FOR UPDATE')->fetchAll(PDO::FETCH_ASSOC) as $o){$id=(int)$o['anex_hotel_id'];if(!isset($observed[$id]))$observed[$id]=$o;}
        $andSafe=[];foreach($pending as $r){$external=(string)$r['external_hotel_id'];$obs=$latest[$external]??null;$obsCount=(int)($counts[$external]??0);$country=(int)($obs['country_id']??0);if(!isset(MBR_CORE8[$country]))$country=(int)($shaCountry[$r['catalog_sha256']]??0);if(!isset(MBR_CORE8[$country]))continue;[$prior,$source,$sourceNames,$sourcePlaces,$sourceCategory,$coordSource]=mlp_source_context($r,$obs);$found=hmfn_match($sourceNames,$sourcePlaces,$coordSource,$country,$formerIndex,$hotels);if($found['candidate']===null)continue;$c=$found['candidate'];$mismatch=$sourceCategory!==null&&$c['target_category']!==null&&$sourceCategory!==$c['target_category'];$row=array_merge(['provider'=>'andromeda','external_id'=>$external,'country_id'=>$country,'observation_count'=>$obsCount,'last_seen_utc'=>$lastSeen[$external]??null,'source_names'=>$sourceNames,'source_places'=>$sourcePlaces,'source_category'=>$sourceCategory,'category_mismatch'=>$mismatch,'existing_opposite_provider_bridge'=>isset($anexLocal[(int)$c['target_local_hotel_id']]),'prior_evidence'=>$prior,'prior_evidence_sha256'=>$r['evidence_sha256']??null],$c);if(!hmfna_candidate_safe($row)){$skipped['andromeda_not_safe']++;continue;}$andSafe[]=$row;}
        $anSafe=[];$ids=array_values(array_unique(array_merge(array_keys($observed),array_keys($staging))));sort($ids,SORT_NUMERIC);foreach($ids as $id){$id=(int)$id;if(isset($manual[$id])||isset($existing[$id]))continue;$s=$staging[$id]??[];$o=$observed[$id]??null;$country=(int)($o['country_id']??0);if(!isset(MBR_CORE8[$country]))$country=(int)(fc_country($s['api_country']??'')??0);if(!isset(MBR_CORE8[$country]))continue;$sourceNames=array_values(array_unique(array_filter([(string)($o['hotel_name']??''),(string)($s['api_name']??''),(string)($s['xml_name']??''),(string)($s['xml_alternate_name']??'')],static fn($v)=>trim($v)!=='')));$sourcePlaces=array_values(array_unique(array_filter([(string)($s['api_region']??''),(string)($s['api_town']??''),(string)($o['region_name']??'')],static fn($v)=>trim($v)!=='')));$coordSource=array_merge($s,$o??[]);$found=hmfn_match($sourceNames,$sourcePlaces,$coordSource,$country,$formerIndex,$hotels,$excluded[$id]??[]);if($found['candidate']===null)continue;$c=$found['candidate'];$sourceCategory=mbr_numeric_category($s);if($sourceCategory===null&&$o)$sourceCategory=mbr_numeric_category($o);$mismatch=$sourceCategory!==null&&$c['target_category']!==null&&$sourceCategory!==$c['target_category'];$row=array_merge(['provider'=>'anex','external_id'=>$id,'country_id'=>$country,'observation_count'=>(int)($o['search_count']??0),'last_seen_utc'=>$o['last_seen_utc']??null,'source_names'=>$sourceNames,'source_places'=>$sourcePlaces,'source_category'=>$sourceCategory,'category_mismatch'=>$mismatch,'existing_opposite_provider_bridge'=>isset($andromedaLocal[(int)$c['target_local_hotel_id']])],$c);if(!hmfna_candidate_safe($row)){$skipped['anex_not_safe']++;continue;}if(isset($excluded[$id][(int)$c['target_local_hotel_id']])){$skipped['anex_pair_excluded']++;continue;}$anSafe[]=$row;}
        $planned=['andromeda'=>count($andSafe),'anex'=>count($anSafe)];if(array_sum($planned)>$maxWrites)throw new RuntimeException('write_scope_limit');
        $selectAnd=$db->prepare("SELECT local_hotel_id,decision_status,evidence_sha256,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=? FOR UPDATE");$updateAnd=$db->prepare("UPDATE andromeda_hotel_identities SET local_hotel_id=?,decision_status='accepted',evidence_sha256=?,evidence_json=? WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=? AND decision_status='pending' AND local_hotel_id IS NULL AND evidence_sha256 <=> ?");
        foreach($andSafe as $row){$external=(string)$row['external_id'];$target=(int)$row['target_local_hotel_id'];$selectAnd->execute([$external]);$cur=$selectAnd->fetch(PDO::FETCH_ASSOC);if(!$cur||$cur['decision_status']!=='pending'||$cur['local_hotel_id']!==null){$skipped['andromeda_stale']++;continue;}$prior=fc_evidence($cur['evidence_json']??'');$evidence=hmfna_andromeda_evidence($operation,$row,$prior);$json=fc_json($evidence);$sha=hash('sha256',$json);$old=$cur['evidence_sha256'];$updateAnd->execute([$target,$sha,$json,$external,$old]);if($updateAnd->rowCount()!==1)throw new RuntimeException('andromeda_concurrency_guard_failed:'.$external);$andRows[$external]=['target'=>$target,'evidence_sha256'=>$sha,'rule'=>$row['rule'],'live'=>(int)$row['observation_count']>0,'bridge'=>(bool)$row['existing_opposite_provider_bridge']];$writes++;if((int)$row['observation_count']>0)$liveWrites++;if($row['existing_opposite_provider_bridge'])$bridgeWrites++;}
        $insert=$db->prepare("INSERT INTO anex_hotel_search_mappings (anex_hotel_id,catalog_hotel_id,match_class,scope,approval_policy,source_row_digest,mapping_digest,enabled) VALUES(?,?,'strong_candidate','preview',?,?,?,1)");$mappingDigest=fc_hash([$operation,'explicit_former_name_accept_v1']);foreach($anSafe as $row){$id=(int)$row['external_id'];$target=(int)$row['target_local_hotel_id'];if(isset($manual[$id])||isset($existing[$id])){$skipped['anex_protected']++;continue;}if(isset($excluded[$id][$target])){$skipped['anex_pair_excluded']++;continue;}$evidence=hmfna_anex_evidence($operation,$row);$digest=fc_hash($evidence);$insert->execute([$id,$target,MBR_POLICY,$digest,$mappingDigest]);if($insert->rowCount()!==1)throw new RuntimeException('anex_insert_not_one:'.$id);$anRows[$id]=['target'=>$target,'source_row_digest'=>$digest,'rule'=>$row['rule'],'live'=>(int)$row['observation_count']>0,'bridge'=>(bool)$row['existing_opposite_provider_bridge']];$existing[$id]=true;$writes++;if((int)$row['observation_count']>0)$liveWrites++;if($row['existing_opposite_provider_bridge'])$bridgeWrites++;}
        if($writes>$maxWrites)throw new RuntimeException('write_scope_limit');$db->commit();
    }catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
    $readAnd=$db->prepare("SELECT local_hotel_id,decision_status,evidence_sha256 FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=?");foreach($andRows as $external=>$expected){$readAnd->execute([$external]);$actual=$readAnd->fetch(PDO::FETCH_ASSOC);if(!$actual||(int)$actual['local_hotel_id']!==$expected['target']||$actual['decision_status']!=='accepted'||!hash_equals($expected['evidence_sha256'],(string)$actual['evidence_sha256']))throw new RuntimeException('andromeda_post_commit_readback_failed:'.$external);$andRows[$external]['readback']='verified';}
    $readAn=$db->prepare('SELECT catalog_hotel_id,source_row_digest,enabled FROM anex_hotel_search_mappings WHERE anex_hotel_id=?');foreach($anRows as $id=>$expected){$readAn->execute([(int)$id]);$actual=$readAn->fetch(PDO::FETCH_ASSOC);if(!$actual||(int)$actual['catalog_hotel_id']!==$expected['target']||(int)$actual['enabled']!==1||!hash_equals($expected['source_row_digest'],(string)$actual['source_row_digest']))throw new RuntimeException('anex_post_commit_readback_failed:'.$id);$anRows[$id]['readback']='verified';}
    $afterCoverage=fc_coverage($db);$afterIdentity=hmfna_identity_counts($db);return ['status'=>'committed_readback_verified','operation_id'=>$operation,'database_writes'=>$writes,'supplier_calls'=>0,'historical_operations_replayed'=>false,'former_segments_indexed'=>$formerSegments,'planned'=>$planned,'skipped'=>$skipped,'live_writes'=>$liveWrites,'bridge_writes'=>$bridgeWrites,'andromeda_rows'=>$andRows,'anex_rows'=>$anRows,'before'=>['coverage'=>$beforeCoverage,'identity'=>$beforeIdentity],'after'=>['coverage'=>$afterCoverage,'identity'=>$afterIdentity]];
}
