<?php
declare(strict_types=1);
const L20_OP='hotel-match-live20-nonmoscow-anex-samo-1971-20260919-v1',L20_FRONTIER='3c022aeef67301e6e24de1f78380e9252221ba933b964d4963e9a778a9686e64',L20_TOWNFROM='1d6865923bd54cf32e20b386419328636d684d530ed0ebfa313fc69788c2b661',L20_MAX_CALLS=80,L20_MAX_PRICE=50,L20_MAX_PAGES=8;
require_once __DIR__.'/hotel_match_live20_nonmoscow_anex_samo_helpers_v1.php';
require_once __DIR__.'/hotel_match_live20_nonmoscow_core_v1.php';
if(in_array('--self-test',$argv??[],true)){lm_need(lm_norm('Санкт-Петербург')==='санкт петербург','norm');echo"LIVE20_NONMOSCOW_SELFTEST_OK\n";exit(0);}
$dir=(string)getenv('MATCH_OPERATION_DIR');$root=realpath((string)getenv('ANYTOUR_ROOT'));$fp=realpath((string)getenv('MATCH_FRONTIER_PATH'));$tfp=realpath((string)getenv('MATCH_TOWNFROM_PATH'));$sha=(string)getenv('MATCH_SOURCE_SHA');
lm_need(PHP_SAPI==='cli'&&is_dir($dir)&&basename($dir)===L20_OP&&is_string($root)&&is_string($fp)&&hash_file('sha256',$fp)===L20_FRONTIER&&is_string($tfp)&&hash_file('sha256',$tfp)===L20_TOWNFROM&&preg_match('/^[a-f0-9]{40}$/D',$sha),'runtime');
$res=json_decode((string)file_get_contents($dir.'/reservation.json'),true,32,JSON_THROW_ON_ERROR);lm_need(($res['operation']??'')===L20_OP&&($res['state']??'')==='reserved_before_provider_access','reservation');
require_once $dir.'/payload/andromeda-network-transport-failure.php';require_once $dir.'/payload/andromeda-transport.php';require_once $dir.'/payload/andromeda-client.php';
$front=json_decode((string)file_get_contents($fp),true,128,JSON_THROW_ON_ERROR);$tf=json_decode((string)file_get_contents($tfp),true,64,JSON_THROW_ON_ERROR);lm_need(($front['state']??'')==='completed_read_only','frontier');
$stdin=file('php://stdin',FILE_IGNORE_NEW_LINES);$user=trim((string)($stdin[0]??''));$pass=trim((string)($stdin[1]??''));unset($stdin);lm_need($user!==''&&$pass!=='','credentials');
try{$result=l20_run($dir,$root,$front,$tf,$user,$pass,$sha);}catch(Throwable $e){$ledger=is_file($dir.'/provider-calls.jsonl')?file($dir.'/provider-calls.jsonl',FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES):[];$result=['operation'=>L20_OP,'state'=>$ledger?'terminal_failed_no_replay':'failed_before_provider_access','source_sha'=>$sha,'frontier_sha256'=>L20_FRONTIER,'townfrom_sha256'=>L20_TOWNFROM,'reason'=>preg_replace('/[^A-Za-z0-9_.:-]/','_',lm_text($e->getMessage(),120)),'provider_calls'=>count($ledger),'price_calls'=>count(array_filter($ledger,fn($x)=>str_contains($x,'"kind":"price"'))),'tourvisor_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>(bool)$ledger];if(is_file($dir.'/raw-manifest.json'))$result['raw_manifest_sha256']=hash_file('sha256',$dir.'/raw-manifest.json');}
$rh=lm_json_file($dir.'/result.json',$result);lm_json_file($dir.'/receipt.json',['operation'=>L20_OP,'state'=>$result['state'],'result_sha256'=>$rh,'provider_calls'=>$result['provider_calls'],'price_calls'=>$result['price_calls'],'tourvisor_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'raw_manifest_sha256'=>$result['raw_manifest_sha256']??null,'no_replay'=>$result['no_replay']]);echo json_encode(['state'=>$result['state'],'active'=>$result['current_active_targets']??null,'provider_calls'=>$result['provider_calls'],'price_calls'=>$result['price_calls'],'state_counts'=>$result['state_counts']??null,'reason'=>$result['reason']??null],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";exit(($result['state']??'')==='completed_read_only'?0:2);
