<?php
declare(strict_types=1);
const OP='hotel-match-biblio-samo30-1971-20260921-v2', IDS=[1096,1098,1102,1105,1108,1111,1113,1114,1118,1134,1137,1139,1140,1141,1143,1146,1161,1162,1177,1245,1246,1249,1250,1252,1257,1262,1279,1282,1284,1292];
function n($x,$m){if(!$x)throw new RuntimeException($m);} function j($p){$x=json_decode(file_get_contents($p),true,32,JSON_THROW_ON_ERROR);n(is_array($x),'json');return $x;}
function w($p,$x){$b=json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";$f=fopen($p,'xb');n($f&&fwrite($f,$b)===strlen($b)&&fflush($f),'write');fclose($f);return hash('sha256',$b);}
function q($d,$s,$p=[]){$x=$d->prepare($s);$x->execute($p);return $x->fetchAll(PDO::FETCH_ASSOC)?:[];}
function norm($s){$s=str_replace(['Ё','ё'],'е',trim((string)$s));$s=function_exists('mb_strtolower')?mb_strtolower($s,'UTF-8'):strtolower($s);return preg_replace('/[^\p{L}\p{N}]+/u','',$s)??'';}
function one($rows,$aliases){$a=array_map('norm',$aliases);$m=[];foreach($rows as $r)if(isset($r['id'],$r['name'])&&in_array(norm($r['name']),$a,true))$m[(string)$r['id']]=true;n(count($m)===1,'dict');return (int)array_key_first($m);}
function budget($root){$p=$root.'/monthly-requests.json';$l=fopen($p.'.lock','c');n($l&&flock($l,LOCK_EX),'budget_lock');try{$m=gmdate('Y-m');$s=is_file($p)?j($p):[];if(($s['month']??'')!==$m)$s=['month'=>$m,'reserved_requests'=>0,'monthly_limit'=>5000000,'scope'=>'this_integration'];n(($s['reserved_requests']??0)<5000000,'quota');$s['reserved_requests']++;$tmp=$p.'.'.bin2hex(random_bytes(4));file_put_contents($tmp,json_encode($s,JSON_THROW_ON_ERROR));chmod($tmp,0600);rename($tmp,$p);}finally{flock($l,LOCK_UN);fclose($l);}}
if(($argv[1]??'')==='--self-test'){n(count(IDS)===30&&count(array_unique(IDS))===30,'ids');echo "OK\n";exit;} n(($argv[1]??'')==='--execute','mode');
$root=realpath(getenv('ANYTOUR_ROOT'));$dir=realpath(getenv('MATCH_OPERATION_DIR'));$sha=getenv('MATCH_SOURCE_SHA');n($root&&basename($root)==='anytoour.ru'&&$dir&&basename($dir)===OP&&preg_match('/^[a-f0-9]{40}$/',$sha),'scope');
$res=j("$dir/payload/reservation.json");n($res['operation']===OP&&$res['source_sha']===$sha&&$res['script_sha256']===hash_file('sha256',__FILE__),'res');w("$dir/started.json",['operation'=>OP,'state'=>'started_no_replay','source_sha'=>$sha]);
$base=['operation'=>OP,'source_sha'=>$sha,'tv_ids'=>IDS,'tourvisor_calls'=>0,'anex_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true];$calls=0;
try{
 require_once $root.(is_file("$root/data/db-v1.php")?'/data/db-v1.php':'/v2/data/db-v1.php');$app="$dir/payload";require_once "$app/andromeda-client.php";require_once "$app/andromeda-transport.php";
 $d=v2_data_db();$d->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$d->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$d->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');$ph=implode(',',array_fill(0,30,'?'));
 $hs=q($d,"SELECT id,country_id,name,is_active FROM catalog_hotels WHERE id IN ($ph) ORDER BY id",IDS);$as=q($d,"SELECT external_hotel_id,local_hotel_id,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IN ($ph) ORDER BY local_hotel_id",IDS);$ms=q($d,"SELECT catalog_hotel_id FROM anex_hotel_decisions WHERE catalog_hotel_id IN ($ph)",IDS);$d->rollBack();
 n(count($hs)===30&&!$ms,'current_targets');$h=[];foreach($hs as $x){n((int)$x['is_active']===1,'inactive');$h[(int)$x['id']]=$x;}$a=[];foreach($as as $x)$a[(int)$x['local_hotel_id']][]=$x;n(count($a)===30,'anchors');
 $country=null;$plan=[];foreach(IDS as $tv){n(count($a[$tv]??[])===1,'anchor_unique');$x=$a[$tv][0];$ev=json_decode($x['evidence_json'],true,16,JSON_THROW_ON_ERROR);$s=$ev['source']??[];n((int)($s['stateKey']??0)===5&&(string)($s['id']??'')===(string)$x['external_hotel_id'],'anchor_state');$country??=(int)$h[$tv]['country_id'];n($country===(int)$h[$tv]['country_id'],'country');$plan[]=['tv'=>$tv,'canonical'=>(string)$x['external_hotel_id'],'name'=>(string)$h[$tv]['name']];}
 $v2=$root.'/v2';$cfg=require "$v2/.andromeda-private.php";n(($cfg['enabled']??false)===true&&is_string($cfg['catalog_path']??null),'config');$cp=$country===1?$cfg['catalog_path']:dirname($cfg['catalog_path']).'/countries/'.$country.'.json';$saved=j($cp);n((int)($saved['all']['params']['STATEINC']??0)===5,'state');
 $dep=one($saved['townfrom']['payload']['TOWNFROM']??[],['Москва','Moscow']);$biblio=one($saved['all']['payload']['OPERATORS']??[],['Библио-Глобус','Библио Глобус','Biblio Globus']);$hc=[];foreach($saved['all']['payload']['HOTELS']??[] as $x)$hc[(string)$x['id']]=true;foreach($plan as $x)n(isset($hc[$x['canonical']]),'hotel_dict');
 $transport=new AnyTourAndromedaTransport(true);$wrap=function($url,$opts)use($transport,$cfg,&$calls){budget(dirname($cfg['catalog_path']));$calls++;return $transport($url,$opts);};
 w("$dir/login-reserved.json",['operation'=>OP,'state'=>'reserved_before_login','call_index'=>1]);$login=new AnyTourAndromedaClient($wrap,true);$login->login($cfg['username'],$cfg['password']);$session=$login->privateSession();n($session,'login');w("$dir/login-result.json",['operation'=>OP,'state'=>'login_succeeded','call_index'=>1]);
 $rows=[];foreach($plan as $i=>$x){$idx=$i+2;$rp="$dir/call-".$x['tv']."-reserved.json";w($rp,['operation'=>OP,'state'=>'reserved_before_price','call_index'=>$idx,'tv'=>$x['tv'],'canonical'=>$x['canonical']]);
  $cl=new AnyTourAndromedaClient($wrap,true);$cl->restorePrivateSession($session);$p=['TOWNFROMINC'=>$dep,'STATEINC'=>5,'CHECKIN_BEG'=>'20261007','CHECKIN_END'=>'20261007','NIGHTS_FROM'=>7,'NIGHTS_TILL'=>7,'ADULT'=>2,'CHILD'=>0,'CURRENCYINC'=>643,'PACKETTYPE'=>0,'PAGE'=>1,'OPERATORS'=>(string)$biblio,'HOTELS'=>$x['canonical']];$r=$cl->price($p);$native=[];$seen=[];foreach($r['PRICES'] as $z){if((string)($z['operatorKey']??'')!==(string)$biblio)continue;$id=(string)($z['hotelKey']??'');$io=(string)($z['isOperatorHotelKey']??'');if($id===''||!in_array($io,['0','1'],true))continue;$k=$io.'|'.$id;if(!isset($seen[$k])){$seen[$k]=true;$native[]=['hotelKey'=>$id,'isOperatorHotelKey'=>$io,'hotel'=>(string)($z['hotel']??''),'operator'=>(string)($z['operator']??'')];}}
  $state=count($native)===1&&$native[0]['isOperatorHotelKey']==='1'?'unique_operator_native':(count($native)?'nonunique_or_catalog_only':'not_returned');$row=$x+['state'=>$state,'provider_operator_id'=>$biblio,'price_page'=>(int)$r['PAGE'],'pages_count'=>(int)$r['PAGES_COUNT'],'identities'=>$native,'response_sha256'=>hash('sha256',json_encode($r,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR))];w("$dir/call-".$x['tv']."-result.json",$row);$rows[]=$row;
 }
 $c=[];foreach($rows as $x)$c[$x['state']]=($c[$x['state']]??0)+1;ksort($c);$out=$base+['state'=>'completed_read_only','andromeda_calls'=>$calls,'provider_operator_id'=>$biblio,'departure_id'=>$dep,'country_id'=>$country,'counts'=>$c,'rows'=>$rows];$rh=w("$dir/result.json",$out);w("$dir/receipt.json",$base+['state'=>'completed_read_only','andromeda_calls'=>$calls,'result_sha256'=>$rh,'counts'=>$c]);echo json_encode(['calls'=>$calls,'counts'=>$c,'result_sha256'=>$rh])."\n";
}catch(Throwable $e){w("$dir/failure.json",$base+['state'=>'failed_no_replay','andromeda_calls'=>$calls,'error_class'=>get_class($e)]);exit(1);}
