<?php
declare(strict_types=1);
/* MATCH-only read-only guard review for PR2535 dossiers. No supplier transport or DB mutation. */
const MRG_OP='hotel-match-received-union-guards-1971-20260915-v1';
const MRG_CORE=[1,2,4,8,9,10,12,16];
const MRG_GENERIC=['hotel','hotels','resort','resorts','spa','the','and','by','club','suite','suites','apart','apartment','apartments','отель','спа'];
const MRG_QUALIFIERS=['annex','annexe','beach','garden','gardens','north','south','east','west','posh','palm','palms','mountain','family','junior','deluxe','aqua','aquamarine','royal','grand','premium','select','palace','park','bay','island','village'];
function mrg_json(array $x):string{return json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";}
function mrg_write(string $dir,string $name,array $doc):string{$raw=mrg_json($doc);$f=fopen($dir.'/'.$name,'x+b');if(!$f)throw new RuntimeException('exclusive_output');try{if(fwrite($f,$raw)!==strlen($raw)||!fflush($f))throw new RuntimeException('output_write');if(function_exists('fsync')&&!fsync($f))throw new RuntimeException('output_sync');rewind($f);if(stream_get_contents($f)!==$raw)throw new RuntimeException('output_readback');}finally{fclose($f);}return hash('sha256',$raw);}
function mrg_q(PDO $db,string $sql,array $args=[]):array{$q=$db->prepare($sql);$q->execute($args);return $q->fetchAll(PDO::FETCH_ASSOC);}
function mrg_fold(string $s):string{$s=mb_strtolower(trim($s),'UTF-8');$s=strtr($s,['ё'=>'е','é'=>'e','è'=>'e','ê'=>'e','á'=>'a','à'=>'a','ä'=>'a','ö'=>'o','ó'=>'o','ü'=>'u','ú'=>'u','ç'=>'c','ş'=>'s','ğ'=>'g','ı'=>'i']);$s=preg_replace('/\s*\(\s*(?:ex|ех|former|бывш\.?)\b[^)]*\)\s*$/ui','',$s)??$s;$s=preg_replace('/[^\p{L}\p{N}]+/u',' ',$s)??$s;return trim(preg_replace('/\s+/u',' ',$s)??$s);}
function mrg_tokens(string $s):array{$f=mrg_fold($s);if($f==='')return[];$t=preg_split('/\s+/u',$f)?:[];$t=array_values(array_unique(array_diff($t,MRG_GENERIC)));sort($t,SORT_STRING);return$t;}
function mrg_qual(array $t):array{$q=[];foreach($t as $x)if(in_array($x,MRG_QUALIFIERS,true)||preg_match('/^[0-9]+$/D',$x))$q[]=$x;$q=array_values(array_unique($q));sort($q,SORT_STRING);return$q;}
function mrg_jaccard(array $a,array $b):float{$u=array_unique(array_merge($a,$b));if(!$u)return 0.0;return count(array_intersect($a,$b))/count($u);}
function mrg_name_score(string $source,string $local):array{$a=mrg_tokens($source);$b=mrg_tokens($local);$q1=mrg_qual($a);$q2=mrg_qual($b);$exact=$a&&$a===$b;$score=mrg_jaccard($a,$b);$shared=count(array_intersect($a,$b));$qual=($q1===$q2);return['exact'=>$exact,'score'=>$score,'shared'=>$shared,'qualifier_match'=>$qual,'source_tokens'=>$a,'local_tokens'=>$b,'source_qualifiers'=>$q1,'local_qualifiers'=>$q2];}
function mrg_scalar_names($v,array &$out,string $key='',int $depth=0):void{if($depth>12)return;if(is_array($v)){foreach($v as $k=>$c)mrg_scalar_names($c,$out,(string)$k,$depth+1);return;}if(!is_scalar($v))return;$lk=mb_strtolower($key,'UTF-8');if(preg_match('/(?:^|_)(?:name|lname|hotel|hotel_name|alias|former_name)$/u',$lk)||in_array($lk,['aliases','names','former','former_names'],true)){ $s=trim((string)$v);if($s!==''&&mb_strlen($s,'UTF-8')<=300)$out[$s]=true;}}
function mrg_coords($v,array &$out,int $depth=0):void{if(!is_array($v)||$depth>12)return;$lat=$v['latitude']??$v['lat']??null;$lon=$v['longitude']??$v['lng']??$v['lon']??null;if(is_numeric($lat)&&is_numeric($lon)){ $a=(float)$lat;$b=(float)$lon;if(abs($a)<=90&&abs($b)<=180&&!($a==0.0&&$b==0.0))$out[sprintf('%.7f,%.7f',$a,$b)]=[$a,$b];}foreach($v as $c)if(is_array($c))mrg_coords($c,$out,$depth+1);}
function mrg_distance(float $a,float $b,float $c,float $d):float{[$a,$b,$c,$d]=array_map('deg2rad',[$a,$b,$c,$d]);return 6371*2*asin(min(1,sqrt(sin(($c-$a)/2)**2+cos($a)*cos($c)*sin(($d-$b)/2)**2)));}
function mrg_truthy_guard($v,string $key='',int $depth=0):bool{if($depth>12)return false;if(is_array($v)){foreach($v as $k=>$c)if(mrg_truthy_guard($c,(string)$k,$depth+1))return true;return false;}$lk=mb_strtolower($key,'UTF-8');if(!preg_match('/manual|exclude|exclusion|conflict|reject|review/u',$lk))return false;if(is_bool($v))return$v;if(is_numeric($v))return((float)$v)!==0.0;if(is_string($v))return trim($v)!==''&&!in_array(mb_strtolower(trim($v),'UTF-8'),['0','false','none','no','null'],true);return false;}
function mrg_geo(array $ev,array $local):array{$values=[];$walk=function($v,$key='',int $d=0)use(&$walk,&$values){if($d>10)return;if(is_array($v)){foreach($v as $k=>$c)$walk($c,(string)$k,$d+1);return;}if(!is_scalar($v))return;$lk=mb_strtolower($key,'UTF-8');if(preg_match('/state|town|region|subregion|atoll|district|area/u',$lk)){ $s=trim((string)$v);if($s!==''&&!is_numeric($s)&&mb_strlen($s,'UTF-8')<=200)$values[$s]=true;}};$walk($ev);$localVals=array_filter([(string)($local['region_name']??''),(string)($local['subregion_name']??'')]);$supported=false;$conflict=false;$tested=0;foreach(array_keys($values) as $a){$ta=mrg_tokens($a);if(!$ta)continue;foreach($localVals as $b){$tb=mrg_tokens($b);if(!$tb)continue;$tested++;if(array_intersect($ta,$tb)){$supported=true;break 2;}}}if($tested>0&&!$supported)$conflict=true;return['supported'=>$supported,'conflict'=>$conflict,'source_values'=>array_keys($values),'local_values'=>array_values($localVals),'tested_pairs'=>$tested];}
function mrg_anchor_guard(array $anchor,array $local):array{$reasons=[];$support=[];$ev=json_decode((string)($anchor['evidence_json']??''),true)?:[];$names=[];mrg_scalar_names($ev,$names);if(isset($anchor['_latest_name'])&&is_string($anchor['_latest_name'])&&trim($anchor['_latest_name'])!=='')$names[$anchor['_latest_name']]=true;$localName=(string)$local['name'];$scores=[];$best=null;foreach(array_keys($names) as $n){$s=mrg_name_score($n,$localName);$scores[$n]=$s;if($best===null||$s['score']>$best['score'])$best=$s+['source_name'=>$n];}
    if(!$best){$reasons[]='no_current_source_name';}else{if(!$best['qualifier_match'])$reasons[]='primary_qualifier_or_numeric_conflict';if($best['exact'])$support[]='exact_normalized_name';elseif($best['score']>=0.86&&$best['shared']>=2&&$best['qualifier_match'])$support[]='strong_name_similarity';else $reasons[]='weak_or_ambiguous_primary_name';}
    $coords=[];mrg_coords($ev,$coords);$max=0.0;$min=null;if(is_numeric($local['latitude']??null)&&is_numeric($local['longitude']??null)){foreach($coords as [$a,$b]){$d=mrg_distance($a,$b,(float)$local['latitude'],(float)$local['longitude']);$max=max($max,$d);$min=$min===null?$d:min($min,$d);if($d>5.0){$reasons[]='coordinate_conflict_gt5km';break;}}if($min!==null&&$max<=5.0)$support[]='all_saved_coordinates_within_5km';}
    $geo=mrg_geo($ev,$local);if($geo['supported'])$support[]='parent_geography_support';elseif($geo['conflict']&&!in_array('exact_normalized_name',$support,true))$reasons[]='parent_geography_conflict_or_unresolved';
    if(mrg_truthy_guard($ev))$reasons[]='manual_review_conflict_marker_in_evidence';
    if((int)$local['is_active']!==1)$reasons[]='local_inactive';if((int)$anchor['country_id']!==(int)$local['country_id'])$reasons[]='country_conflict';
    $reasons=array_values(array_unique($reasons));$support=array_values(array_unique($support));$safe=!$reasons&&(in_array('exact_normalized_name',$support,true)||(in_array('strong_name_similarity',$support,true)&&(in_array('all_saved_coordinates_within_5km',$support,true)||in_array('parent_geography_support',$support,true))));
    return['safe'=>$safe,'reasons'=>$reasons,'support'=>$support,'best_name'=>$best,'coordinate_count'=>count($coords),'coordinate_min_km'=>$min,'coordinate_max_km'=>$coords?$max:null,'geography'=>$geo];}
function mrg_relation_guard(array $row,array $anchors,array $locals,array $nativeByKey,array $occupancy):array{$f=$row['fact'];$op=(string)$f['operator_key'];$native=(string)$f['native_hotel_id'];$aid=(string)$f['andromeda_hotel_id'];$ns='operator_'.$op;$reasons=[];$a=$anchors[$aid]??null;if(!$a||$a['decision_status']!=='accepted'||$a['local_hotel_id']===null)return['safe'=>false,'reasons'=>['current_anchor_not_accepted']];$lid=(int)$a['local_hotel_id'];$local=$locals[$lid]??null;if(!$local)return['safe'=>false,'reasons'=>['current_local_missing']];$ng=mrg_anchor_guard($a,$local);if(!$ng['safe'])$reasons=array_merge($reasons,$ng['reasons']?:['anchor_identity_not_independently_safe']);$nativeRow=$nativeByKey[$ns.'|'.mb_strtolower($native,'UTF-8')]??null;if($nativeRow){if($nativeRow['decision_status']==='accepted')$reasons[]='existing_native_accepted_protected';elseif($nativeRow['decision_status']!=='pending'||$nativeRow['local_hotel_id']!==null)$reasons[]='existing_native_nonpending_protected';$nev=json_decode((string)($nativeRow['evidence_json']??''),true)?:[];if(mrg_truthy_guard($nev))$reasons[]='native_manual_review_conflict_marker';}
    $occ=$occupancy[$ns.'|'.$lid]??[];foreach($occ as $ext)if(mb_strtolower((string)$ext,'UTF-8')!==mb_strtolower($native,'UTF-8')){$reasons[]='same_provider_target_occupied';break;}
    foreach([(string)($f['hotel_name']??''),(string)($f['original_name']??'')] as $name){if(trim($name)==='')continue;$s=mrg_name_score($name,(string)$local['name']);if(!$s['qualifier_match'])$reasons[]='provider_primary_qualifier_or_numeric_conflict';if(!$s['exact']&&!($s['score']>=0.72&&$s['shared']>=1))$reasons[]='provider_name_has_no_local_anchor';}
    $reasons=array_values(array_unique($reasons));return['safe'=>!$reasons,'reasons'=>$reasons,'local_hotel_id'=>$lid,'anchor_guard'=>$ng,'current_native'=>$nativeRow,'same_provider_occupancy'=>$occ];}
function mrg_anchor_candidates(array $anchor,array $localsByCountry,array $occupancy):array{$country=(int)$anchor['country_id'];$pool=$localsByCountry[$country]??[];$ev=json_decode((string)($anchor['evidence_json']??''),true)?:[];$names=[];mrg_scalar_names($ev,$names);if(isset($anchor['_latest_name'])&&trim((string)$anchor['_latest_name'])!=='')$names[(string)$anchor['_latest_name']]=true;$coords=[];mrg_coords($ev,$coords);$rank=[];foreach($pool as $h){$best=0.0;$exact=false;$qual=true;$shared=0;foreach(array_keys($names) as $n){$s=mrg_name_score($n,(string)$h['name']);if($s['score']>$best){$best=$s['score'];$exact=$s['exact'];$qual=$s['qualifier_match'];$shared=$s['shared'];}}$dist=null;if($coords&&is_numeric($h['latitude'])&&is_numeric($h['longitude']))foreach($coords as [$a,$b]){$d=mrg_distance($a,$b,(float)$h['latitude'],(float)$h['longitude']);$dist=$dist===null?$d:min($dist,$d);}if($exact||$best>=0.82||($dist!==null&&$dist<=1.0))$rank[]=['local_hotel_id'=>(int)$h['id'],'name'=>$h['name'],'score'=>$best,'exact'=>$exact,'qualifier_match'=>$qual,'shared'=>$shared,'distance_km'=>$dist,'local'=>$h];}
    usort($rank,fn($a,$b)=>($b['exact']<=>$a['exact'])?:($b['score']<=>$a['score'])?:(($a['distance_km']??999)<=>($b['distance_km']??999))?:($a['local_hotel_id']<=>$b['local_hotel_id']));$top=$rank[0]??null;$second=$rank[1]??null;$reasons=[];$safe=false;if(!$top)$reasons[]='no_catalog_candidate';else{if(!$top['qualifier_match'])$reasons[]='qualifier_or_numeric_conflict';$occupied=$occupancy['andromeda_catalog|'.$top['local_hotel_id']]??[];foreach($occupied as $ext)if((string)$ext!==(string)$anchor['external_hotel_id']){$reasons[]='same_provider_target_occupied';break;}$guard=mrg_anchor_guard($anchor,$top['local']);if(!$guard['safe'])$reasons=array_merge($reasons,$guard['reasons']?:['identity_guard_not_safe']);$margin=$second?$top['score']-$second['score']:1.0;if(!$top['exact']&& !($top['score']>=0.92&&$top['shared']>=2&&$margin>=0.12&&(($top['distance_km']!==null&&$top['distance_km']<=5.0)||$guard['geography']['supported'])))$reasons[]='fuzzy_margin_or_independent_support_insufficient';$reasons=array_values(array_unique($reasons));$safe=!$reasons;return['safe'=>$safe,'reasons'=>$reasons,'candidate'=>$top,'second'=>$second?array_diff_key($second,['local'=>true]):null,'anchor_guard'=>$guard,'margin'=>$margin,'occupancy'=>$occupied];}return['safe'=>false,'reasons'=>$reasons,'candidate'=>null,'second'=>null,'margin'=>null];}
if(in_array('--self-test',$argv??[],true)){$s=mrg_name_score('Royal Beach Hotel 2','Royal Beach 2');if(!$s['exact']||!$s['qualifier_match'])throw new RuntimeException('name_exact');$s=mrg_name_score('Royal Beach 2','Royal Beach 3');if($s['qualifier_match'])throw new RuntimeException('numeric_qualifier');$d=mrg_distance(36.713018,31.563078,36.713018,31.563078);if($d>0.001)throw new RuntimeException('distance');$x=[];mrg_coords(['source'=>['lat'=>1,'lng'=>2]],$x);if(count($x)!==1)throw new RuntimeException('coords');echo "4 guard self-tests PASS\n";exit;}
$op=getenv('MATCH_OPERATION_ID')?:'';$sha=getenv('MATCH_SOURCE_SHA')?:'';$manifestSha=getenv('MATCH_MANIFEST_SHA')?:'';$dir=getenv('HOME').'/.anytoour-match/operations/'.MRG_OP;if($op!==MRG_OP||!preg_match('/^[0-9a-f]{40}$/D',$sha)||!preg_match('/^[0-9a-f]{64}$/D',$manifestSha)||!is_file($dir.'/reservation.json')||!is_file($dir.'/manifest.json'))throw new RuntimeException('reservation_required');if(!hash_equals($manifestSha,hash_file('sha256',$dir.'/manifest.json')))throw new RuntimeException('manifest_digest');$res=json_decode(file_get_contents($dir.'/reservation.json'),true,32,JSON_THROW_ON_ERROR);if(($res['operation_id']??null)!==$op||($res['source_sha']??null)!==$sha||($res['state']??null)!=='reserved_before_db_access'||($res['manifest_sha256']??null)!==$manifestSha)throw new RuntimeException('reservation_mismatch');$manifest=json_decode(file_get_contents($dir.'/manifest.json'),true,128,JSON_THROW_ON_ERROR);if(($manifest['operation_id']??null)!==$op||count($manifest['relation_rows']??[])!==93)throw new RuntimeException('manifest_contract');
$db=null;$phase='bootstrap';try{$root=realpath(getcwd());if(!$root||basename($root)!=='anytoour.ru')throw new RuntimeException('root');require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION READ ONLY');$phase='current';
    $ids=mrg_q($db,'SELECT * FROM andromeda_hotel_identities ORDER BY supplier_namespace,external_hotel_id');$anchors=[];$native=[];$occupancy=[];foreach($ids as $r){$ns=(string)$r['supplier_namespace'];$ext=(string)$r['external_hotel_id'];if($ns==='andromeda_catalog')$anchors[$ext]=$r;else $native[$ns.'|'.mb_strtolower($ext,'UTF-8')]=$r;if($r['decision_status']==='accepted'&&$r['local_hotel_id']!==null)$occupancy[$ns.'|'.(int)$r['local_hotel_id']][]=$ext;}
    $obs=mrg_q($db,'SELECT supplier_namespace,external_hotel_id,country_id,hotel_name,observed_at_utc FROM andromeda_search_hotel_observations WHERE country_id IN (1,2,4,8,9,10,12,16) ORDER BY observed_at_utc DESC');foreach($obs as $r){if($r['supplier_namespace']==='andromeda_catalog'&&isset($anchors[(string)$r['external_hotel_id']])&&!isset($anchors[(string)$r['external_hotel_id']]['_latest_name']))$anchors[(string)$r['external_hotel_id']]['_latest_name']=(string)$r['hotel_name'];}
    $locals=[];$localsByCountry=[];foreach(mrg_q($db,'SELECT id,country_id,name,region_name,subregion_name,latitude,longitude,is_active FROM catalog_hotels WHERE country_id IN (1,2,4,8,9,10,12,16) AND is_active=1 ORDER BY country_id,id') as $h){$id=(int)$h['id'];$locals[$id]=$h;$localsByCountry[(int)$h['country_id']][]=$h;}
    $relation=[];$rReasons=[];foreach($manifest['relation_rows'] as $row){$g=mrg_relation_guard($row,$anchors,$locals,$native,$occupancy);$g['operator_key']=(string)$row['fact']['operator_key'];$g['native_hotel_id']=(string)$row['fact']['native_hotel_id'];$g['andromeda_hotel_id']=(string)$row['fact']['andromeda_hotel_id'];$relation[]=$g;foreach($g['reasons'] as $x)$rReasons[$x]=($rReasons[$x]??0)+1;}
    $anchorReviews=[];$aReasons=[];$seen=[];foreach($manifest['unresolved_rows'] as $row){$aid=(string)$row['fact']['andromeda_hotel_id'];if(isset($seen[$aid]))continue;$seen[$aid]=true;$a=$anchors[$aid]??null;if(!$a){$g=['safe'=>false,'reasons'=>['current_anchor_missing'],'candidate'=>null];}elseif($a['decision_status']==='accepted'||$a['local_hotel_id']!==null){$g=['safe'=>false,'reasons'=>['anchor_state_changed_since_dossier'],'candidate'=>null];}else{$country=(int)($a['country_id']??$row['fact']['country_id']??0);$a['country_id']=$country;$g=mrg_anchor_candidates($a,$localsByCountry,$occupancy);} $g['andromeda_hotel_id']=$aid;$anchorReviews[]=$g;foreach($g['reasons'] as $x)$aReasons[$x]=($aReasons[$x]??0)+1;}
    $db->exec('ROLLBACK');$phase='receipt';$safeRelations=array_values(array_filter($relation,fn($x)=>$x['safe']));$safeAnchors=array_values(array_filter($anchorReviews,fn($x)=>$x['safe']));$result=['operation_id'=>$op,'source_sha'=>$sha,'state'=>'completed_read_only','manifest_sha256'=>$manifestSha,'relation_reviewed'=>count($relation),'relation_safe_count'=>count($safeRelations),'relation_safe'=>$safeRelations,'relation_reason_counts'=>$rReasons,'unresolved_anchor_unique_reviewed'=>count($anchorReviews),'unresolved_anchor_safe_count'=>count($safeAnchors),'unresolved_anchor_safe'=>$safeAnchors,'unresolved_anchor_reason_counts'=>$aReasons,'all_relation_reviews'=>$relation,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true,'apply_manifest'=>false,'mandatory_before_write'=>['NEW immutable write operation','transaction CURRENT revalidation','manual/exclusion/conflict preservation','same-provider occupancy recheck','COMMIT','per-row readback','durable receipt']];$digest=mrg_write($dir,'result.json',$result);mrg_write($dir,'receipt.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'completed_read_only','result_sha256'=>$digest,'readback_verified'=>true,'database_writes'=>0,'supplier_calls'=>0,'no_replay'=>true]);echo json_encode(['relation_reviewed'=>count($relation),'relation_safe_count'=>count($safeRelations),'unresolved_anchor_unique_reviewed'=>count($anchorReviews),'unresolved_anchor_safe_count'=>count($safeAnchors)])."\n";
}catch(Throwable $e){if($db instanceof PDO&&$db->inTransaction())$db->rollBack();$digest=mrg_write($dir,'result.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'failed_read_only','phase'=>$phase,'error_class'=>get_class($e),'error_code'=>preg_replace('/[^A-Za-z0-9_.:-]+/','_',substr($e->getMessage(),0,160)),'database_writes'=>0,'supplier_calls'=>0,'no_replay'=>true]);mrg_write($dir,'receipt.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'failed_read_only','result_sha256'=>$digest,'readback_verified'=>true,'database_writes'=>0,'supplier_calls'=>0,'no_replay'=>true]);fwrite(STDERR,'GUARD_REVIEW_FAILED:'.$phase."\n");exit(2);}
