<?php
declare(strict_types=1);
/** MATCH-only CURRENT review of 8 retained direct Tourvisor->ANEX HOTELLIST identities. No provider calls/writes. */
const T8_OP='hotel-match-tv-anex-direct8-current-review-1971-20260917-v1';
const T8_SOURCE_RESULT_SHA='6d5b18584b31ac3b63774e547e5db2553d09aa8a2f31a7db18897a3ba4a4c76c';
const T8_SOURCE_RUN=35140146825;
const T8_MANIFEST=[
  37719=>[132075,1,'Posh Club By Sunrise Diamond Beach Resort Grand Select','POSH CLUB SUNRISE DIAMOND BEACH RESORT','ffc805e46b6d29b699d2999dffabb5ea022ef3aa0086c33ff70a0f11dd7a08d8','7ccf415030541e8d98e59ff786e8fc355d0e0a315ea1eae850e5dec3d019b9a6','known_qualifier_hold'],
  21696=>[1070,4,'Cesars Side','CESARS SIDE (EX.CESARS RESORT)','615584d50a66bfc9858791d58a9d6ec0cab3b486a476305a6acc9be4bc0af5c2','ac1efc8a648887ef62237b0cbc37716f4606b44a55eba926c43087ed8595701c',null],
  35319=>[1346,4,'Selectum Family Comfort Side','SELECTUM FAMILY COMFORT SIDE (EX. LYRA RESORT HOTEL)','4003923ecd151b8fc6edb51fc22d1e4000a3cc556cb62b4671484867f4769b4b','d98daa796e163d4149bd3de6724e7b320445a66380091785fd627d0fe8a7fd8a',null],
  35511=>[28581,4,'Ma Biche Kemer By Werde Hotels','MA BICHE KEMER BY WERDE HOTELS (EX. KIMEROS MA BICHE HOTEL & THALASSO)','4a356ca3c91762e872b583134ce442aae1650765965fa2f7473eeb86e656ccdc','a7a5f1947b8fa3660ccced8e6bd8b1a14135aabba0d63b23163a13a781317a70',null],
  31515=>[1501,4,'Selectum Family Resort Side','SELECTUM FAMILY RESORT SIDE (EX. SILENCE BEACH RESORT)','983282e25a24acf1c66fdb853e09f81494df4bcf404e0122f9f066fa083d79bc','421760c7ea914b3fe778edfc3ed13f5194eb80f77bd9ec6f54ba06bafba10759',null],
  15046=>[1217,4,'Adalya Artside Hotel','ADALYA ART SIDE (EX. GRAND HOTEL ARTSIDE)','563ddfbfd63cdcb96befe3758dd2d122186a7cc97402204ab7d8cbf996798632','6a51e4788133fa341052905da195fd50a2ad0519989df57e819c74dd14722aca',null],
  9384=>[35297,4,'Mary Hotel Alanya','MARY HOTELS ALANYA (EX. SIRIUS DELUXE)','854ae357ec9f4a7fcafcfb960f9bf269d7a21277009f21fc482b6b2a992773d7','f047048a7645d44c47825543b8537b912c98f9e74fafa650c5c7a667245f5ccc',null],
  35898=>[1221,4,'Megasaray Resort Side','MEGASARAY RESORT SIDE (EX. ASKA SIDE HOTEL)','aa97d50d6a8f23dc993807e800254bafd846bdf1f2456cd7cedb18724e417a93','19851330e1d2cdffa4ab6f9d44a6f01564d703e642da05734fb70f12b135cb88',null],
];
function t8_req(bool $ok,string $why):void{if(!$ok)throw new RuntimeException($why);}
function t8_json(array $x):string{return json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";}
function t8_write(string $p,array $x):string{$raw=t8_json($x);$f=@fopen($p,'x+b');t8_req(is_resource($f),'exclusive_output');try{t8_req(fwrite($f,$raw)===strlen($raw)&&fflush($f),'output_write');if(function_exists('fsync'))t8_req(fsync($f),'output_sync');rewind($f);t8_req(stream_get_contents($f)===$raw,'output_readback');}finally{fclose($f);}return hash('sha256',$raw);}
function t8_read(string $p,int $max=65536):array{t8_req(is_file($p)&&!is_link($p)&&realpath($p)===$p,'input_path');$raw=file_get_contents($p);t8_req(is_string($raw)&&strlen($raw)<=$max,'input_size');$x=json_decode($raw,true,64,JSON_THROW_ON_ERROR);t8_req(is_array($x),'input_shape');return$x;}
function t8_q(PDO $db,string $sql,array $args=[]):array{t8_req(preg_match('/^SELECT\b/i',$sql)===1,'select_only');$s=$db->prepare($sql);$s->execute(array_values($args));$r=$s->fetchAll(PDO::FETCH_ASSOC);t8_req(count($r)<100000,'query_budget');return$r;}
function t8_lower(string $s):string{if(function_exists('mb_strtolower'))return mb_strtolower($s,'UTF-8');return strtolower(strtr($s,['А'=>'а','Б'=>'б','В'=>'в','Г'=>'г','Д'=>'д','Е'=>'е','Ё'=>'ё','Ж'=>'ж','З'=>'з','И'=>'и','Й'=>'й','К'=>'к','Л'=>'л','М'=>'м','Н'=>'н','О'=>'о','П'=>'п','Р'=>'р','С'=>'с','Т'=>'т','У'=>'у','Ф'=>'ф','Х'=>'х','Ц'=>'ц','Ч'=>'ч','Ш'=>'ш','Щ'=>'щ','Ъ'=>'ъ','Ы'=>'ы','Ь'=>'ь','Э'=>'э','Ю'=>'ю','Я'=>'я']));}
function t8_key(string $s,bool $stripFormer=false):string{if($stripFormer)$s=preg_replace('/\s*\((?:ex|ех)\.?[^)]*\)\s*$/iu','',$s)??$s;return preg_replace('/[^\p{L}\p{N}]+/u','',t8_lower(trim($s)))??'';}
function t8_point(array $v):?array{foreach([['latitude','longitude'],['lat','lng'],['lat','lon']]as[$a,$b]){if(!is_numeric($v[$a]??null)||!is_numeric($v[$b]??null))continue;$x=(float)$v[$a];$y=(float)$v[$b];if(is_finite($x)&&is_finite($y)&&abs($x)<=90&&abs($y)<=180&&($x!=0||$y!=0))return[$x,$y];}return null;}
function t8_km(array $a,array $b):float{[$x,$y,$u,$v]=array_map('deg2rad',[$a[0],$a[1],$b[0],$b[1]]);$h=sin(($u-$x)/2)**2+cos($x)*cos($u)*sin(($v-$y)/2)**2;return 12742.0176*asin(sqrt(min(1.0,max(0.0,$h))));}
function t8_pending(PDO $db):array{$out=[];$total=0;foreach(['andromeda_catalog','operator_315','operator_342','operator_5']as$ns){$r=t8_q($db,"SELECT COUNT(*) n FROM andromeda_hotel_identities WHERE supplier_namespace=? AND decision_status='pending' AND local_hotel_id IS NULL",[$ns]);$out[$ns]=(int)$r[0]['n'];$total+=$out[$ns];}return[$out,$total];}
if(in_array('--self-test',$argv??[],true)){t8_req(count(T8_MANIFEST)===8,'manifest_count');t8_req(T8_MANIFEST[37719][6]==='known_qualifier_hold','posh_hold');foreach(T8_MANIFEST as$aid=>$v){t8_req($aid>0&&count($v)===7&&$v[0]>0&&in_array($v[1],[1,4],true),'manifest_row');t8_req(preg_match('/^[a-f0-9]{64}$/D',$v[4])===1&&preg_match('/^[a-f0-9]{64}$/D',$v[5])===1,'manifest_hash');}echo "PASS\n";exit;}
function t8_main():void{
 t8_req(PHP_SAPI==='cli'&&getenv('MATCH_OPERATION_ID')===T8_OP,'operation_guard');$sha=(string)getenv('MATCH_SOURCE_SHA');t8_req(preg_match('/^[a-f0-9]{40}$/D',$sha)===1,'source_guard');$dir=(string)getenv('HOME').'/.anytoour-match/operations/'.T8_OP;$reservation=t8_read($dir.'/reservation.json');t8_req(($reservation['operation_id']??'')===T8_OP&&($reservation['source_sha']??'')===$sha&&($reservation['state']??'')==='reserved_before_db_access'&&($reservation['retained_result_sha256']??'')===T8_SOURCE_RESULT_SHA,'reservation_guard');
 $out=['operation_id'=>T8_OP,'source_sha'=>$sha,'state'=>'failed_no_replay','retained_source_run'=>T8_SOURCE_RUN,'retained_result_sha256'=>T8_SOURCE_RESULT_SHA,'checked'=>count(T8_MANIFEST),'safe_candidates'=>[],'existing_same'=>[],'held'=>[],'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'samo_andromeda_calls'=>0,'booking_calls'=>0,'lead_calls'=>0,'no_replay'=>true];$db=null;$phase='bootstrap';ob_start();try{
  $root=realpath(getcwd());t8_req(is_string($root)&&basename($root)==='anytoour.ru','root_guard');$bp=$root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');t8_req(realpath($bp)===$bp&&!is_link($bp),'bootstrap_path');require_once$bp;$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');$phase='current_review';
  $ids=array_keys(T8_MANIFEST);$lids=array_values(array_map(static fn($x)=>(int)$x[0],T8_MANIFEST));$ph=implode(',',array_fill(0,count($ids),'?'));$pl=implode(',',array_fill(0,count($lids),'?'));
  $maps=t8_q($db,"SELECT anex_hotel_id,catalog_hotel_id,match_class,scope,approval_policy,source_row_digest,mapping_digest,enabled FROM anex_hotel_search_mappings WHERE anex_hotel_id IN ($ph) OR catalog_hotel_id IN ($pl) ORDER BY anex_hotel_id,catalog_hotel_id",array_merge($ids,$lids));$byA=[];$byT=[];foreach($maps as$m){if((int)$m['enabled']!==1)continue;$byA[(int)$m['anex_hotel_id']][]=$m;$byT[(int)$m['catalog_hotel_id']][]=$m;}
  $manual=[];foreach(t8_q($db,"SELECT anex_hotel_id FROM anex_hotel_decisions WHERE anex_hotel_id IN ($ph)",$ids)as$r)$manual[(int)$r['anex_hotel_id']]=true;
  $ex=[];foreach(t8_q($db,"SELECT anex_hotel_id,catalog_hotel_id FROM anex_review_pair_exclusions WHERE anex_hotel_id IN ($ph) OR catalog_hotel_id IN ($pl)",array_merge($ids,$lids))as$r)$ex[(int)$r['anex_hotel_id'].':'.(int)$r['catalog_hotel_id']]=true;
  $obs=[];foreach(t8_q($db,"SELECT anex_hotel_id,hotel_name,country_id,search_count FROM anex_search_hotel_observations WHERE anex_hotel_id IN ($ph)",$ids)as$r)$obs[(int)$r['anex_hotel_id']]=$r;
  $staging=[];foreach(t8_q($db,"SELECT anex_hotel_id,latitude,longitude FROM anex_hotels WHERE anex_hotel_id IN ($ph)",$ids)as$r)$staging[(int)$r['anex_hotel_id']]=$r;
  $hot=[];foreach(t8_q($db,"SELECT id,country_id,name,latitude,longitude,is_active FROM catalog_hotels WHERE id IN ($pl)",$lids)as$r)$hot[(int)$r['id']]=$r;
  foreach(T8_MANIFEST as$aid=>$v){[$lid,$country,$sourceName,$detailName,$detailSha,$linkSha,$forcedHold]=$v;$reasons=[];$same=false;foreach($byA[$aid]??[]as$m){if((int)$m['catalog_hotel_id']===$lid)$same=true;else$reasons[]='source_mapped_other';}if($same){$out['existing_same'][]=['anex_hotel_id'=>$aid,'catalog_hotel_id'=>$lid];continue;}foreach($byT[$lid]??[]as$m)if((int)$m['anex_hotel_id']!==$aid)$reasons[]='target_occupied_other';if(isset($manual[$aid]))$reasons[]='manual_decision_present';if(isset($ex[$aid.':'.$lid]))$reasons[]='pair_excluded';if(is_string($forcedHold)&&$forcedHold!=='')$reasons[]=$forcedHold;
    $o=$obs[$aid]??null;$h=$hot[$lid]??null;if(!$o)$reasons[]='current_observation_missing';else{if((int)$o['country_id']!==$country)$reasons[]='current_source_country_changed';if(t8_key((string)$o['hotel_name'])!==t8_key($sourceName))$reasons[]='current_source_name_changed';}
    if(!$h||(int)($h['is_active']??0)!==1)$reasons[]='target_inactive_or_missing';else{if((int)$h['country_id']!==$country)$reasons[]='target_country_changed';if(t8_key((string)$h['name'],true)!==t8_key($detailName,true))$reasons[]='target_name_changed_from_retained_detail';}
    $distance=null;$sp=t8_point($staging[$aid]??[]);$tp=$h?t8_point($h):null;if($sp&&$tp){$distance=t8_km($sp,$tp);if($distance>5)$reasons[]='coordinate_conflict_gt5km';}
    $row=['anex_hotel_id'=>$aid,'catalog_hotel_id'=>$lid,'country_id'=>$country,'current_source_name'=>$o['hotel_name']??null,'retained_source_name'=>$sourceName,'current_target_name'=>$h['name']??null,'retained_detail_name'=>$detailName,'current_search_count'=>$o? (int)$o['search_count']:null,'distance_km'=>$distance===null?null:round($distance,3),'detail_response_sha256'=>$detailSha,'operator_link_sha256'=>$linkSha,'retained_result_sha256'=>T8_SOURCE_RESULT_SHA];$reasons=array_values(array_unique($reasons));if($reasons){$row['reasons']=$reasons;$out['held'][]=$row;}else{$row['evidence_class']='direct_tourvisor_detail_operatorlink_hotellist_current_guarded';$out['safe_candidates'][]=$row;}
  }
  [$pb,$pt]=t8_pending($db);$db->commit();$out['pending_by_namespace']=$pb;$out['pending_total']=$pt;$out['safe_candidate_count']=count($out['safe_candidates']);$out['existing_same_count']=count($out['existing_same']);$out['held_count']=count($out['held']);$out['read_at_utc']=gmdate('c');$out['state']='completed_read_only';
 }catch(Throwable $e){try{if($db instanceof PDO&&$db->inTransaction())$db->rollBack();}catch(Throwable $x){}$out['reason']=$e->getMessage();$out['phase']=$phase;}finally{ob_end_clean();}
 $rh=t8_write($dir.'/result.json',$out);t8_write($dir.'/receipt.json',['operation_id'=>T8_OP,'source_sha'=>$sha,'state'=>$out['state'],'result_sha256'=>$rh,'readback_verified'=>hash('sha256',(string)file_get_contents($dir.'/result.json'))===$rh,'checked'=>$out['checked'],'safe_candidate_count'=>$out['safe_candidate_count']??0,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true]);echo json_encode($out,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n";exit($out['state']==='completed_read_only'?0:2);
}
t8_main();
