<?php
declare(strict_types=1);
require_once __DIR__.'/hotel_match_andromeda_name_geo_helper_v65.php';
require_once __DIR__.'/hotel_match_anex_effective_coverage.php';

const V65_OP='hotel-match-live234-andromeda-context-acquire-1971-20260926-v65';
const V65_SRC_OP='hotel-match-live-anex-missing-samo-router-refresh-1971-20260926-v36r';
const V65_SRC_SHA='cd9b6f18c049af27501b40d5490536f31d9b5fa595f3d4d7864a4a7f04587a58';
const V65_DAY='2026-09-26';
const V65_OPS=[5=>'operator_5',115=>'operator_115',315=>'operator_315',342=>'operator_342'];
const V65_HTTP_CAP=1600,V65_PRICE_CAP=1400,V65_PAGE_CAP=5,V65_MONTHLY_LIMIT=5000000;

function v65_need(bool $v,string $m):void{if(!$v)throw new RuntimeException($m);}
function v65_load(string $p):array{$v=json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);v65_need(is_array($v),'json_shape');return$v;}
function v65_q(PDO $db,string $sql,array $args=[]):array{$s=$db->prepare($sql);$s->execute(array_values($args));return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}
function v65_excluded(string $v):bool{return preg_match('/^(?:россия|абхазия|russia|russian federation|abkhazia)$/iu',trim($v))===1;}
function v65_chunks(array $ids):array{$ids=array_values(array_unique(array_map('strval',$ids)));sort($ids,SORT_NATURAL);$out=[];$cur=[];foreach($ids as$id){$x=[...$cur,$id];if($cur&&(count($x)>12||strlen(implode(',',$x))>300)){$out[]=$cur;$cur=[$id];}else$cur=$x;}if($cur)$out[]=$cur;return$out;}
function v65_cfg(string $root):array{foreach([$root.'/_preview/search3-anex-candidate/.andromeda-private.php',$root.'/v2/.andromeda-private.php'] as$p){if(!is_file($p)||is_link($p))continue;$x=require$p;if(is_array($x)&&($x['enabled']??false)===true&&($x['username']??'')!==''&&($x['password']??'')!==''&&($x['catalog_path']??'')!=='')return$x;}throw new RuntimeException('andromeda_private_config_missing');}
function v65_budget(string $private,int $seq,string $action):void{$p=$private.'/monthly-requests.json';$f=fopen($p.'.lock','c');v65_need($f!==false&&flock($f,LOCK_EX),'budget_lock');try{$m=gmdate('Y-m');$v=is_file($p)?v65_load($p):[];if(($v['month']??'')!==$m)$v=['month'=>$m,'reserved_requests'=>0,'monthly_limit'=>V65_MONTHLY_LIMIT,'scope'=>'this_integration'];$used=(int)($v['reserved_requests']??0);$lim=(int)($v['monthly_limit']??V65_MONTHLY_LIMIT);v65_need($lim===V65_MONTHLY_LIMIT&&$used<$lim,'monthly_quota');$v['reserved_requests']=$used+1;$v['last_match_operation']=V65_OP;$v['last_match_call']=$seq;$v['last_match_action']=$action;$tmp=$p.'.'.bin2hex(random_bytes(4));file_put_contents($tmp,json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR));chmod($tmp,0600);rename($tmp,$p);}finally{flock($f,LOCK_UN);fclose($f);}}
function v65_source(array $s):array{v65_need(($s['operation']??'')===V65_SRC_OP&&($s['state']??'')==='completed_read_only_v36_current_refresh','src_state');v65_need((int)$s['input_count']===234&&(int)$s['still_tv_anex_missing_samo_count']===234&&(int)$s['future_context_count']===176&&(int)$s['stale_only_count']===37&&(int)$s['no_future_context_count']===21&&(int)$s['batch_count']===100,'src_counts');foreach(['provider_http_calls','tourvisor_calls','samo_calls','andromeda_calls','anex_calls','database_writes','mapping_writes'] as$k)v65_need((int)($s[$k]??-1)===0,'src_zero_'.$k);$o=[];foreach($s['future_context']??[] as$r){$id=(int)($r['local_hotel_id']??0);v65_need($id>0&&!isset($o[$id])&&is_array($r['context']??null),'src_row');$o[$id]=$r;}v65_need(count($o)===176,'src_membership');return$o;}
function v65_current(PDO $db,array $src):array{$ids=array_keys($src);$ph=implode(',',array_fill(0,count($ids),'?'));$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION READ ONLY');try{$h=[];foreach(v65_q($db,"SELECT id,name,country_id,country_name,region_name,subregion_name,is_active FROM catalog_hotels WHERE id IN ($ph)",$ids) as$r)$h[(int)$r['id']]=$r;$a=[];foreach(v65_q($db,"SELECT hotel_id,alias FROM hotel_aliases WHERE hotel_id IN ($ph) ORDER BY hotel_id,id",$ids) as$r)$a[(int)$r['hotel_id']][]=(string)$r['alias'];$d=[];foreach(v65_q($db,'SELECT id,name,is_active FROM catalog_departures') as$r)$d[(int)$r['id']]=$r;$c=[];foreach(v65_q($db,'SELECT id,name,is_active FROM catalog_countries') as$r)$c[(int)$r['id']]=$r;$samo=[];foreach(v65_q($db,"SELECT local_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IN ($ph)",$ids) as$r)$samo[(int)$r['local_hotel_id']]=true;$cov=AnyTourMatchAnexEffectiveCoverage::fromPdo($db);$today=(new DateTimeImmutable('now',new DateTimeZone('Europe/Moscow')))->format('Y-m-d');v65_need($today===V65_DAY,'moscow_day_drift');$active=[];$skip=['already_samo'=>0,'lost_anex'=>0,'inactive'=>0,'stale'=>0,'dict_local'=>0];foreach($src as$id=>$r){$x=$h[$id]??null;$ctx=$r['context'];$dep=(int)($ctx['departure_id']??0);$country=(int)($ctx['country_id']??0);if(!$x||(int)$x['is_active']!==1||v65_excluded((string)$x['country_name'])){$skip['inactive']++;continue;}if(isset($samo[$id])){$skip['already_samo']++;continue;}$an=array_keys($cov['by_local'][$id]??[]);if(!$an){$skip['lost_anex']++;continue;}if((string)$ctx['departure_date']<$today){$skip['stale']++;continue;}if(!isset($d[$dep],$c[$country])||(int)$d[$dep]['is_active']!==1||(int)$c[$country]['is_active']!==1){$skip['dict_local']++;continue;}v65_need((int)$x['country_id']===$country,'country_context_drift');sort($an,SORT_NATURAL);$active[$id]=['hotel'=>$x,'aliases'=>$a[$id]??[],'direct_anex_ids'=>array_map('strval',$an),'departure_name'=>(string)$d[$dep]['name'],'country_name'=>(string)$c[$country]['name'],'context'=>$ctx];}$db->rollBack();return['active'=>$active,'skip'=>$skip];}catch(Throwable$e){if($db->inTransaction())$db->rollBack();throw$e;}}
function v65_self_test():void{$p=['1'=>['catalog_hotel_id'=>'1','names'=>['ARES CITY (EX. KAMI HOTEL)'],'town_key'=>'7','town_labels'=>['Кемер'],'star_key'=>'3']];$r=hms34_candidates(['name'=>'ARES CITY (EX. KAMI HOTEL)','region_name'=>'Кемер','subregion_name'=>''],[],$p);v65_need($r['mode']==='exact'&&(string)array_key_first($r['candidates'])==='1','candidate');$f=hms34_price_fact(['hotelKey'=>1,'operatorKey'=>315,'original'=>['hotelKey'=>8123,'operatorKey'=>315]],'315');v65_need(($f['native_operator_hotel_id']??'')==='8123','fact');v65_need(count(v65_chunks(range(1,25)))===3,'chunks');}

if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__){
 if(in_array('--self-test',$argv??[],true)){v65_self_test();echo"MATCH_V65_SELFTEST_OK\n";exit;}
 v65_need(($argv[1]??'')==='--execute','disabled');$root=(string)getenv('ANYTOUR_ROOT');$dir=(string)getenv('MATCH_OPERATION_DIR');$srcPath=(string)getenv('MATCH_SOURCE_RESULT');$srcSha=(string)getenv('MATCH_SOURCE_RESULT_SHA');$head=(string)getenv('MATCH_SOURCE_SHA');v65_need(is_dir($root)&&is_dir($dir)&&basename($dir)===V65_OP&&is_file($srcPath)&&$srcSha===V65_SRC_SHA&&hash_file('sha256',$srcPath)===$srcSha&&preg_match('/^[0-9a-f]{40}$/D',$head)===1,'scope');$res=v65_load($dir.'/reservation.json');v65_need(($res['operation']??'')===V65_OP&&($res['state']??'')==='reserved_before_provider','reservation');
 $calls=0;$prices=0;$access=false;$stop=null;$taskErrors=0;$out=[];
 try{$src=v65_source(v65_load($srcPath));require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$cur=v65_current(v2_data_db(),$src);$active=$cur['active'];v65_need($active!==[],'no_active');$cfg=v65_cfg($root);$private=dirname((string)$cfg['catalog_path']);$rawDir=$dir.'/evidence-private';mkdir($rawDir,0700,true);$app=dirname(__DIR__,2).'/app/integrations';require_once$app.'/andromeda-client.php';require_once$app.'/andromeda-transport.php';$last=0.0;$call=function(string$url,array$opts)use(&$calls,&$access,&$last,$private,$dir){$q=[];parse_str((string)parse_url($url,PHP_URL_QUERY),$q);$action=(string)($q['action']??'unknown');$seq=$calls+1;v65_need($seq<=V65_HTTP_CAP,'http_cap');v65_budget($private,$seq,$action);$calls=$seq;$access=true;hms34_json_file($dir.'/http-'.str_pad((string)$seq,4,'0',STR_PAD_LEFT).'-reserved.json',['operation'=>V65_OP,'seq'=>$seq,'action'=>$action,'state'=>'reserved_before_http']);$wait=1.05-(microtime(true)-$last);if($wait>0)usleep((int)ceil($wait*1e6));$t=new AnyTourAndromedaTransport(true);$last=microtime(true);return$t($url,$opts);};$login=new AnyTourAndromedaClient($call,true);$login->login((string)$cfg['username'],(string)$cfg['password']);$session=$login->privateSession();v65_need($session!==[],'login');
 $client=function()use($call,$session){$c=new AnyTourAndromedaClient($call,true);$c->restorePrivateSession($session);return$c;};$manifest=[];$saveRaw=function(string$n,array$v)use($rawDir,&$manifest){$raw=json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n";$p=$rawDir.'/'.$n.'.json';file_put_contents($p,$raw,LOCK_EX);$manifest[]=['file'=>basename($p),'sha256'=>hash('sha256',$raw),'bytes'=>strlen($raw)];};$town=$client()->catalog('townfrom');$saveRaw('townfrom',$town);$townRows=$town['TOWNFROM'];$depBind=[];foreach($active as$r)$depBind[$r['departure_name']]=null;foreach(array_keys($depBind) as$n){try{$depBind[$n]=hms34_unique_dict_id($townRows,[$n]);}catch(Throwable){$depBind[$n]=0;}}
 $states=[];$pairs=[];$bind=[];foreach($active as$id=>$r){$pd=(int)($depBind[$r['departure_name']]??0);if($pd<1){$bind[$id]=['state'=>'departure_unbound'];continue;}if(!isset($states[$pd])){$x=$client()->catalog('state',['TOWNFROMINC'=>$pd]);$saveRaw('state-'.$pd,$x);$states[$pd]=$x['STATE'];}try{$ps=hms34_unique_dict_id($states[$pd],[$r['country_name']]);}catch(Throwable){$ps=0;}if($ps<1){$bind[$id]=['state'=>'country_unbound','provider_departure_id'=>$pd];continue;}$key=$pd.'|'.$ps;if(!isset($pairs[$key])){$x=$client()->catalog('all',['TOWNFROMINC'=>$pd,'STATEINC'=>$ps]);$saveRaw('all-'.$pd.'-'.$ps,$x);$towns=hms34_town_labels($x['TOWNTO']);$hot=hms34_provider_rows($x['HOTELS'],$towns);$ops=[];foreach($x['OPERATORS'] as$o){$oid=(int)($o['id']??($o['operatorKey']??0));if(isset(V65_OPS[$oid]))$ops[$oid]=true;}$pairs[$key]=['hotels'=>$hot,'operators'=>$ops,'pd'=>$pd,'ps'=>$ps];}$bind[$id]=['state'=>'bound','key'=>$key,'provider_departure_id'=>$pd,'provider_state_id'=>$ps];}
 $plans=[];$groups=[];foreach($active as$id=>$r){$b=$bind[$id]??['state'=>'unbound'];$cand=['mode'=>'none','candidates'=>[],'total'=>0];if(($b['state']??'')==='bound')$cand=hms34_candidates($r['hotel'],$r['aliases'],$pairs[$b['key']]['hotels']);$plans[$id]=['target'=>$r,'binding'=>$b,'mode'=>$cand['mode'],'total'=>$cand['total'],'candidates'=>$cand['candidates'],'facts'=>[],'incomplete'=>false,'errors'=>[]];if(!$cand['candidates']||($b['state']??'')!=='bound')continue;foreach(array_keys(V65_OPS) as$op){if(!isset($pairs[$b['key']]['operators'][$op]))continue;$ctx=$r['context'];$gk=implode('|',[$b['provider_departure_id'],$b['provider_state_id'],$ctx['departure_date'],$ctx['nights'],$ctx['adults'],$ctx['children_count'],$ctx['child_ages_signature'],$op]);$groups[$gk]=($groups[$gk]??[])+['operator'=>$op,'pd'=>$b['provider_departure_id'],'ps'=>$b['provider_state_id'],'ctx'=>$ctx,'targets'=>[],'candidates'=>[]];$groups[$gk]['targets'][$id]=true;foreach(array_keys($cand['candidates']) as$cid)$groups[$gk]['candidates'][$cid]=true;}}
 ksort($groups,SORT_NATURAL);$tasks=[];foreach($groups as$g)foreach(v65_chunks(array_keys($g['candidates'])) as$chunk)$tasks[]=$g+['chunk'=>$chunk];$taskOut=[];foreach($tasks as$i=>$task){$n=$i+1;$op=(int)$task['operator'];$ctx=$task['ctx'];$req=array_fill_keys($task['chunk'],true);$seen=[];$pages=0;$pc=null;$err=null;$incomplete=false;$params=['TOWNFROMINC'=>(int)$task['pd'],'STATEINC'=>(int)$task['ps'],'CHECKIN_BEG'=>str_replace('-','',(string)$ctx['departure_date']),'CHECKIN_END'=>str_replace('-','',(string)$ctx['departure_date']),'NIGHTS_FROM'=>(int)$ctx['nights'],'NIGHTS_TILL'=>(int)$ctx['nights'],'ADULT'=>(int)$ctx['adults'],'CHILD'=>(int)$ctx['children_count'],'CURRENCYINC'=>643,'PACKETTYPE'=>0,'OPERATORS'=>(string)$op,'HOTELS'=>implode(',',$task['chunk']),'GROUP_BY'=>32];if((int)$ctx['children_count']>0){$ages=(string)$ctx['child_ages_signature'];if(!preg_match('/^[0-9]+(?:,[0-9]+)*$/D',$ages)||count(explode(',',$ages))!==(int)$ctx['children_count'])$err='child_age_shape';else$params['AGES']=$ages;}
   if($err===null)for($page=1;$page<=V65_PAGE_CAP;$page++){if($prices>=V65_PRICE_CAP){$stop='price_cap';break 2;}$prices++;$params['PAGE']=$page;hms34_json_file($dir.'/task-'.str_pad((string)$n,4,'0',STR_PAD_LEFT).'-p'.$page.'-reserved.json',['operation'=>V65_OP,'task'=>$n,'page'=>$page,'operator'=>$op,'state'=>'reserved_before_price']);try{$reply=$client()->price($params);}catch(Throwable$e){$m=preg_replace('/[^A-Za-z0-9_.:-]+/','_',hms34_cut($e->getMessage(),120));if(str_contains($m,'http_cap')||str_contains($m,'monthly_quota')){$stop=$m;break 2;}$err=$m;$taskErrors++;break;}$pages++;$pc=(int)($reply['PAGES_COUNT']??0);$raw=json_encode($reply,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);file_put_contents($rawDir.'/task-'.$n.'-p'.$page.'.json',$raw."\n",LOCK_EX);foreach($reply['PRICES']??[] as$row){if(!is_array($row))continue;$f=hms34_price_fact($row,(string)$op);if(!$f||!isset($req[$f['catalog_hotel_id']]))continue;$cid=$f['catalog_hotel_id'];$seen[$cid]=true;foreach(array_keys($task['targets']) as$tid)if(isset($plans[$tid]['candidates'][$cid]))$plans[$tid]['facts'][$cid][$op][]=$f;}if(array_diff_key($req,$seen)===[]||$pc===0||$page>=$pc)break;}
   if($err===null&&array_diff_key($req,$seen)!==[]&&$pc!==null&&$pc>0&&$pages>=V65_PAGE_CAP)$incomplete=true;foreach(array_keys($task['targets']) as$tid){if($incomplete)$plans[$tid]['incomplete']=true;if($err!==null)$plans[$tid]['errors'][]=$err;}$taskOut[]=['task'=>$n,'operator'=>$op,'candidate_count'=>count($task['chunk']),'pages'=>$pages,'pages_count'=>$pc,'seen'=>count($seen),'incomplete'=>$incomplete,'error'=>$err];}
 $nativeMap=[];foreach($plans as$p)foreach($p['facts'] as$cid=>$ops)foreach($ops as$op=>$facts){$ids=[];foreach($facts as$f)if(($f['native_operator_hotel_id']??null)!==null)$ids[$f['native_operator_hotel_id']]=true;if(count($ids)===1)$nativeMap[V65_OPS[(int)$op].'|'.array_key_first($ids)][$cid]=true;}$strict=0;$review=0;$hold=0;$dossiers=[];foreach($plans as$id=>$p){$cs=[];$strictIds=[];foreach($p['candidates'] as$cid=>$meta){$lanes=[];$laneCount=0;$collision=false;foreach(V65_OPS as$op=>$ns){$facts=$p['facts'][$cid][$op]??[];$ids=[];foreach($facts as$f)if(($f['native_operator_hotel_id']??null)!==null)$ids[$f['native_operator_hotel_id']]=true;$ids=array_keys($ids);sort($ids,SORT_NATURAL);$st=count($ids)===1?'single_native':(count($ids)>1?'ambiguous_native':'not_observed');if($st==='single_native'){$laneCount++;$collision=$collision||count($nativeMap[$ns.'|'.$ids[0]]??[])>1;}$lanes[$ns]=['state'=>$st,'native_ids'=>$ids,'facts'=>count($facts)];}$op5=$lanes['operator_5']['native_ids'];$an=$p['target']['direct_anex_ids'];$support='none';if(count($op5)===1&&count($an)===1)$support=$op5[0]===$an[0]?'support_equal':'support_different';elseif($op5||count($an)>1)$support='support_collision';$strong=$stop===null&&$laneCount>=2&&(($meta['retrieval']??'')==='exact_variant'||($meta['geo_relation']??'')==='direct_label_match')&&!$collision&&!$p['incomplete']&&!$p['errors'];if($strong)$strictIds[]=(string)$cid;$cs[]=['catalog_id'=>(string)$cid,'names'=>$meta['names'],'town_labels'=>$meta['town_labels'],'retrieval'=>$meta['retrieval'],'geo_relation'=>$meta['geo_relation'],'name_score'=>$meta['name_score'],'lane_count'=>$laneCount,'lanes'=>$lanes,'direct_anex_support'=>$support,'source_collision'=>$collision,'strict_multi_lane'=>$strong];}$status='review_no_strict_candidate';if(count($strictIds)===1){$status='strict_multi_lane_candidate';$strict++;}elseif(count($strictIds)>1){$status='hold_multiple_strict';$hold++;}elseif(($p['binding']['state']??'')!=='bound'||$p['total']===0||$stop!==null||$p['incomplete']||$p['errors']){$status='hold_insufficient_or_partial';$hold++;}else$review++;$dossiers[]=['local_hotel_id'=>$id,'hotel_name'=>$p['target']['hotel']['name'],'direct_anex_ids'=>$p['target']['direct_anex_ids'],'binding'=>$p['binding'],'candidate_mode'=>$p['mode'],'candidate_total'=>$p['total'],'status'=>$status,'strict_catalog_id'=>count($strictIds)===1?$strictIds[0]:null,'candidates'=>$cs,'safe_to_write_now'=>false];}
 usort($dossiers,fn($a,$b)=>$a['local_hotel_id']<=>$b['local_hotel_id']);$state=$stop===null?'completed_read_only':'completed_read_only_partial';$out=['operation'=>V65_OP,'state'=>$state,'reason'=>$stop,'source_sha'=>$head,'source_result_sha256'=>$srcSha,'input_future_count'=>count($src),'current_active_count'=>count($active),'current_skip_counts'=>$cur['skip'],'provider_http_calls'=>$calls,'andromeda_calls'=>$calls,'price_calls'=>$prices,'task_count'=>count($tasks),'completed_task_count'=>count($taskOut),'task_error_count'=>$taskErrors,'strict_multi_lane_candidate_count'=>$strict,'review_count'=>$review,'hold_count'=>$hold,'dossiers'=>$dossiers,'tasks'=>$taskOut,'tourvisor_calls'=>0,'direct_anex_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'safe_to_write_now'=>false];
 }catch(Throwable$e){$m=preg_replace('/[^A-Za-z0-9_.:-]+/','_',hms34_cut($e->getMessage(),160));$out=['operation'=>V65_OP,'state'=>$access?'terminal_failed_no_replay':'failed_before_provider_access','reason'=>$m,'source_sha'=>$head,'source_result_sha256'=>$srcSha,'provider_http_calls'=>$calls,'andromeda_calls'=>$calls,'price_calls'=>$prices,'tourvisor_calls'=>0,'direct_anex_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'safe_to_write_now'=>false];}
 $h=hms34_json_file($dir.'/result.json',$out);hms34_json_file($dir.'/receipt.json',['operation'=>V65_OP,'state'=>$out['state'],'result_sha256'=>$h,'readback_verified'=>hash_file('sha256',$dir.'/result.json')===$h,'provider_accessed'=>$access,'provider_http_calls'=>$calls,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>$access]);echo json_encode(array_intersect_key($out,array_flip(['state','reason','input_future_count','current_active_count','current_skip_counts','provider_http_calls','price_calls','task_count','completed_task_count','task_error_count','strict_multi_lane_candidate_count','review_count','hold_count'])),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";exit(in_array($out['state'],['completed_read_only','completed_read_only_partial'],true)?0:2);
}
