<?php
declare(strict_types=1);
require_once __DIR__.'/hotel_match_retained_candidates_write_v86.php';
const V90_OP='hotel-match-samo-live30-operator-join-audit-1971-20260928-v90';
const V90_V77_OP='hotel-match-live30-retained-native-union-1971-20260927-v77';
const V90_V77_SHA='d40fbe2e0240a5df194ac838376a3425a8f4e80f2426a757560fe369011107f7';
const V90_NS=['operator_5','operator_115','operator_315','operator_342'];
function v90_need(bool $b,string $m):void{if(!$b)throw new RuntimeException($m);}
function v90_text(mixed $v):string{return mb_strtolower(w76_text($v));}
function v90_main(array $argv):int{
 v90_need(($argv[1]??'')==='--execute','disabled');$root=(string)getenv('ANYTOUR_ROOT');$dir=(string)getenv('MATCH_OPERATION_DIR');$head=(string)getenv('MATCH_SOURCE_SHA');
 v90_need(is_dir($root)&&basename($root)==='anytoour.ru'&&is_dir($dir)&&basename($dir)===V90_OP&&preg_match('/^[a-f0-9]{40}$/D',$head),'scope');foreach(['result.json','receipt.json']as$f)v90_need(!file_exists($dir.'/'.$f),'no_replay');
 $ops=dirname($dir);$v77=v86_load($ops.'/'.V90_V77_OP.'/result.json',V90_V77_SHA,67108864);v90_need(($v77['state']??'')==='completed_retained_native_scan','v77_state');
 require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION READ ONLY');
 try{
  $all=w76_q($db,'SELECT * FROM andromeda_hotel_identities ORDER BY supplier_namespace,external_hotel_id LIMIT 50001');$cohort=w84_live_sources($root);$samoBefore=w84_samo_census($all,$cohort);$tv=w76_census($db);
  $src=[];$op=[];$acceptedSource=[];foreach($all as$r){$ns=(string)$r['supplier_namespace'];$n=(string)$r['external_hotel_id'];if($ns==='andromeda_catalog'){$src[$n][]=$r;if(($r['decision_status']??'')==='accepted'&&$r['local_hotel_id']!==null)$acceptedSource[$n]=true;}else$op[$ns][$n][]=$r;}
  $factsByCat=[];$catsByNative=[];foreach($v77['native_facts']??[]as$f){$ns=(string)($f['supplier_namespace']??'');$n=(string)($f['native_id']??'');$cat=(string)($f['catalog_id']??'');if(!in_array($ns,V90_NS,true)||$n===''||$cat==='')continue;$factsByCat[$cat][]=$f;$catsByNative[$ns.'|'.$n][$cat]=true;}
  $targetIds=[];$pre=[];
  foreach($cohort['source_ids']as$cat=>$seen){$cat=(string)$cat;if(isset($acceptedSource[$cat]))continue;$proofs=[];$holds=[];
   foreach($factsByCat[$cat]??[]as$f){$ns=(string)$f['supplier_namespace'];$n=(string)$f['native_id'];$key=$ns.'|'.$n;if(count($catsByNative[$key]??[])!==1){$holds[]='native_to_multiple_catalogs';continue;}$rows=$op[$ns][$n]??[];$accepted=array_values(array_filter($rows,fn($r)=>($r['decision_status']??'')==='accepted'&&$r['local_hotel_id']!==null));if(count($accepted)!==1)continue;$local=(int)$accepted[0]['local_hotel_id'];if($local<1)continue;$proofs[]=['namespace'=>$ns,'native_id'=>$n,'local_hotel_id'=>$local,'operator_identity_evidence_sha256'=>$accepted[0]['evidence_sha256'],'operator_identity_catalog_sha256'=>$accepted[0]['catalog_sha256'],'native_fact'=>$f];}
   $locals=array_values(array_unique(array_column($proofs,'local_hotel_id')));if(count($locals)>1)$holds[]='same_source_operator_proofs_disagree';$pre[$cat]=['catalog_id'=>$cat,'last_seen_epoch'=>$seen,'proofs'=>$proofs,'candidate_local_id'=>count($locals)===1?$locals[0]:null,'pre_holds'=>array_values(array_unique($holds))];if(count($locals)===1)$targetIds[$locals[0]]=true;
  }
  $ids=array_keys($targetIds);$hot=[];$manual=[];$excluded=[];$liveTv=[];if($ids){foreach(array_chunk($ids,250)as$c){$ph=implode(',',array_fill(0,count($c),'?'));foreach(w76_q($db,"SELECT id,name,country_name,region_name,subregion_name,category,is_active FROM catalog_hotels WHERE id IN ($ph)",$c)as$r)$hot[(int)$r['id']]=$r;foreach(w76_q($db,"SELECT catalog_hotel_id FROM anex_hotel_decisions WHERE catalog_hotel_id IN ($ph)",$c)as$r)$manual[(int)$r['catalog_hotel_id']]=true;foreach(w76_q($db,"SELECT catalog_hotel_id FROM anex_review_pair_exclusions WHERE catalog_hotel_id IN ($ph)",$c)as$r)$excluded[(int)$r['catalog_hotel_id']]=true;foreach(w76_q($db,"SELECT DISTINCT hotel_id FROM tour_operator_identity_observations WHERE hotel_id IN ($ph) AND last_seen_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 30 DAY)",$c)as$r)$liveTv[(int)$r['hotel_id']]=true;}}
  $rows=[];$safe=0;$proofCount=0;$conflicts=[];
  foreach($pre as$cat=>$e){$id=$e['candidate_local_id'];$why=$e['pre_holds'];$sourceRows=$src[$cat]??[];$source=count($sourceRows)===1?$sourceRows[0]:null;if(!$e['proofs'])$why[]='no_current_accepted_same_operator_identity';else$proofCount+=count($e['proofs']);
   if(count($sourceRows)!==1)$why[]='canonical_source_missing_or_duplicate';elseif(($source['decision_status']??'')==='accepted'&&$source['local_hotel_id']!==null){$why[]='already_accepted_after_census';}elseif(($source['decision_status']??'')!=='pending'||$source['local_hotel_id']!==null||!w76_evidence_valid($source))$why[]='canonical_source_not_pending_valid_null';
   $h=$id?($hot[$id]??null):null;if($id&&!$h)$why[]='target_missing';elseif($h&&(int)$h['is_active']!==1)$why[]='target_inactive';if($id&&isset($manual[$id]))$why[]='manual_target_protected';if($id&&isset($excluded[$id]))$why[]='excluded_target_protected';
   $sourceEv=$source&&w76_evidence_valid($source)?json_decode($source['evidence_json'],true):[];$sf=is_array($sourceEv)?($sourceEv['source']??[]):[];
   if($h&&is_array($sf)){$state=v90_text($sf['state']??'');$country=v90_text($h['country_name']??'');if($state!==''&&$country!==''&&$state!==$country)$why[]='country_conflict';$star=(int)($sf['starKey']??0);if($star>0&&(int)$h['category']>0&&$star!==(int)$h['category'])$why[]='category_conflict';}
   $why=array_values(array_unique($why));$status=$why?'hold':'ready_current';if(!$why)$safe++;else foreach($why as$w)$conflicts[$w]=($conflicts[$w]??0)+1;
   $rows[]=['catalog_id'=>$cat,'source_name'=>(string)($sf['name']??''),'candidate_local_id'=>$id,'target_name'=>$h['name']??null,'target_country'=>$h['country_name']??null,'target_category'=>$h['category']??null,'target_tv_live30'=>$id?isset($liveTv[$id]):false,'proof_count'=>count($e['proofs']),'proofs'=>$e['proofs'],'source_evidence_sha256'=>$source['evidence_sha256']??null,'source_catalog_sha256'=>$source['catalog_sha256']??null,'status'=>$status,'reasons'=>$why,'safe_to_write_now'=>$status==='ready_current'];
  }
  $db->rollBack();ksort($conflicts);$out=['operation'=>V90_OP,'state'=>'completed_read_only_samo_operator_join','source_sha'=>$head,'generated_at_utc'=>gmdate('c'),'provider_http_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'tv_current'=>$tv,'samo_current'=>$samoBefore,'unresolved_source_count'=>count($pre),'sources_with_any_exact_operator_proof'=>count(array_filter($pre,fn($x)=>!empty($x['proofs']))),'operator_proof_count'=>$proofCount,'ready_current_count'=>$safe,'hold_count'=>count($pre)-$safe,'hold_reason_counts'=>$conflicts,'rows'=>$rows,'no_replay'=>true];
 }catch(Throwable$e){if($db->inTransaction())$db->rollBack();$out=['operation'=>V90_OP,'state'=>'failed_read_only_samo_operator_join','source_sha'=>$head,'reason'=>preg_match('/^[a-z_]+$/D',$e->getMessage())?$e->getMessage():'audit_failed','provider_http_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true];}
 $sha=w76_save($dir.'/result.json',$out);w76_save($dir.'/receipt.json',['operation'=>V90_OP,'state'=>$out['state'],'source_sha'=>$head,'result_sha256'=>$sha,'provider_http_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true]);echo w76_json(array_diff_key($out,['rows'=>true]))."\n";return $out['state']==='completed_read_only_samo_operator_join'?0:2;
}
if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__)exit(v90_main($argv));
