<?php
declare(strict_types=1);
require_once __DIR__.'/hotel_match_retained93_primary_write_v84.php';
require_once __DIR__.'/hotel_match_live30_common4_gap_matrix_v1.php';
const M115_OP='hotel-match-mass-index-diagnostic-1971-20260928-v115';
const M115_NATIVE_SHA='d40fbe2e0240a5df194ac838376a3425a8f4e80f2426a757560fe369011107f7';
const M115_ACQ=['hotel-match-anexonly200-acquire-1971-20260928-v109'=>'aa0365674e2f57775cbc7c5f0ab7a2d0781fc2826febc0c55214a726ea0b75a4','hotel-match-anexonly-tail-acquire-1971-20260928-v112'=>'ecbba8c5c9dc03f9d4729aabefd0afa1dbfdc67828a66ff429ccb452aab678fd'];
function m115_need(bool$b,string$m):void{if(!$b)throw new RuntimeException($m);}
function m115_main(array$a):int{
 m115_need(($a[1]??'')==='--execute','disabled');$root=(string)getenv('ANYTOUR_ROOT');$dir=(string)getenv('MATCH_OPERATION_DIR');$head=(string)getenv('MATCH_SOURCE_SHA');m115_need(is_dir($root)&&is_dir($dir)&&basename($dir)===M115_OP,'scope');$ops=dirname($dir);foreach(['result.json','receipt.json']as$f)m115_need(!file_exists($dir.'/'.$f),'no_replay');
 require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$m=hmc4_execute(v2_data_db());$gap=[];$tv=[];foreach($m['rows']as$r){$id=(int)$r['tv_hotel_id'];$gap[$id]=$r['gap_bucket'];foreach([[13,'anex'],[18,'biblio'],[25,'funsun'],[43,'intourist']]as[$op,$k]){$l=$r['lanes'][$k];$ids=array_values(array_unique(array_merge($l['accepted_external_ids'],$l['saved_exact_external_ids'])));if(count($ids)===1)$tv[$id][$op][(string)$ids[0]][]=['kind'=>'matrix'];}}
 $acqAdded=[18=>0,25=>0,43=>0];foreach(M115_ACQ as$opn=>$sha){$x=w84_read($ops.'/'.$opn.'/result.json',$sha,33554432);foreach($x['edges']as$i=>$e){if(($e['link_state']??'')!=='captured_single_native'||count($e['positive_native_candidates']??[])!==1||w84_edge_reasons($e))continue;$id=(int)$e['tv_hotel_id'];$op=(int)$e['operator_id'];if(isset($gap[$id])){$tv[$id][$op][(string)$e['positive_native_candidates'][0]][]=['kind'=>'acq','op'=>$opn,'i'=>$i];if(isset($acqAdded[$op]))$acqAdded[$op]++;}}}
 $v=w84_read($ops.'/hotel-match-live30-retained-native-union-1971-20260927-v77/result.json',M115_NATIVE_SHA,67108864);$native=[];foreach($v['native_facts']as$f)$native[(string)$f['supplier_namespace']][(string)$f['native_id']][(string)$f['catalog_id']]=$f;
 $stats=['tv_hotels'=>count($tv),'tv_pairs'=>[13=>0,18=>0,25=>0,43=>0],'acq_added'=>$acqAdded,'native_zero'=>[18=>0,25=>0,43=>0],'native_one'=>[18=>0,25=>0,43=>0],'native_many'=>[18=>0,25=>0,43=>0],'raw_ok'=>[18=>0,25=>0,43=>0],'raw_fail'=>[18=>0,25=>0,43=>0],'examples'=>[]];$ns=[18=>'operator_115',25=>'operator_315',43=>'operator_342'];
 foreach($tv as$id=>$os)foreach($os as$op=>$xs)foreach($xs as$n=>$proofs){$stats['tv_pairs'][$op]++;if($op===13)continue;$cats=$native[$ns[$op]][$n]??[];$cnt=count($cats);if($cnt===0){$stats['native_zero'][$op]++;continue;}if($cnt>1){$stats['native_many'][$op]++;continue;}$stats['native_one'][$op]++;$cat=(string)array_key_first($cats);try{w84_raw($ops,$cats[$cat],$cat,$ns[$op],$n);$stats['raw_ok'][$op]++;if(count($stats['examples'])<30)$stats['examples'][]=['tv'=>$id,'op'=>$op,'native'=>$n,'cat'=>$cat,'gap'=>$gap[$id]];}catch(Throwable){$stats['raw_fail'][$op]++;}}
 $out=['operation'=>M115_OP,'state'=>'completed_mass_index_diagnostic','source_sha'=>$head,'generated_at_utc'=>gmdate('c'),'coverage_current'=>['total'=>$m['tv_live30_total'],'remaining'=>$m['live30_non_triple_total'],'buckets'=>$m['gap_bucket_counts']],'stats'=>$stats,'provider_http_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true];$sha=w76_save($dir.'/result.json',$out);w76_save($dir.'/receipt.json',['operation'=>M115_OP,'state'=>$out['state'],'result_sha256'=>$sha,'provider_http_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true]);echo w76_json($out)."\n";return 0;
}
if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__)exit(m115_main($argv));
