<?php
declare(strict_types=1);
if (!defined('FC_LIBRARY_ONLY')) define('FC_LIBRARY_ONLY', true);
require_once __DIR__ . '/hotel_match_global_tourvisor_rescue.php';
require_once __DIR__ . '/hotel_match_andromeda_star_bridge_review.php';

const HMPV8_OPERATION='hotel-match-post-v8-rescue-ensemble-1971-20260911-v1';
const HMPV8_CROSS_OPERATION='hotel-match-global-cross-provider-rescue-1971-20260911-v1';
const HMPV8_TV_OPERATION='hotel-match-global-tourvisor-rescue-1971-20260911-v1';
const HMPV8_STAR_OPERATION='hotel-match-andromeda-star-bridge-review-1971-20260911-v1';
const HMPV8_V8_OPERATION='hotel-match-anex-tourvisor-hotelcode-evidence-1971-20260911-v8';

function hmpv8_key(string $provider,string|int $external):string{return strtolower(trim($provider)).':'.trim((string)$external);}
function hmpv8_brand_tokens(array $pair):array{
    $drop=array_fill_keys(['annex','beach','garden','gardens','north','south','ex','former','formerly','old','name','by','villa','villas','palace','central','boutique','world'],true);
    $out=[];foreach(($pair['shared_tokens']??[]) as $t){$t=fc_norm(hmgcr_latin((string)$t));if($t!==''&&!isset($drop[$t]))$out[$t]=true;}return array_keys($out);
}
function hmpv8_pair_safe(array $row,bool $oppositeBridge):bool{
    $pair=$row['pair']??null;if(!is_array($pair)||!($pair['critical_ok']??false))return false;
    $distance=$row['distance_m']??null;if($distance!==null&&(float)$distance>5000.0)return false;
    $brand=count(hmpv8_brand_tokens($pair));$shared=(int)($pair['shared']??0);$exact=(bool)($pair['exact_bag']??false);$anchor=(bool)($pair['anchor_ok']??false);$ordered=(bool)($pair['ordered']??false);$place=(bool)($row['place_match']??false);$margin=(float)($row['score_margin']??0.0);$score=(float)($pair['score']??0.0);$reason=(string)($row['reason']??'');
    if(str_contains($reason,'single_token'))return $brand>=1&&$place&&$distance!==null&&(float)$distance<=80.0;
    if($exact){if($brand>=2&&($anchor||$ordered))return true;if($brand>=1&&($anchor||$ordered)&&($place||($distance!==null&&(float)$distance<=1000.0)||$oppositeBridge))return true;return false;}
    if(str_contains($reason,'no_geo'))return $oppositeBridge&&$brand>=3&&$score>=0.90&&$margin>=0.20&&($anchor||$ordered)&&(int)($pair['token_diff']??99)<=1;
    if(str_contains($reason,'high_overlap'))return $brand>=2&&$score>=0.80&&$margin>=0.15&&($anchor||$ordered)&&(int)($pair['token_diff']??99)<=2&&($place||($distance!==null&&(float)$distance<=1000.0));
    return false;
}
function hmpv8_validate_inputs(array $cross,array $tv,array $star,array $v8):void{
    if(($cross['status']??null)!=='completed'||($cross['operation_id']??null)!==HMPV8_CROSS_OPERATION||($cross['database_writes']??null)!==0||($cross['mapping_writes']??null)!==0||($cross['supplier_calls']??null)!==0||count($cross['prepared']??[])!==26)throw new RuntimeException('HMPV8_CROSS');
    if(($tv['status']??null)!=='completed'||($tv['operation_id']??null)!==HMPV8_TV_OPERATION||($tv['database_writes']??null)!==0||($tv['mapping_writes']??null)!==0||($tv['supplier_calls']??null)!==0||count($tv['prepared']??[])!==30)throw new RuntimeException('HMPV8_TV');
    if(($star['status']??null)!=='completed'||($star['operation_id']??null)!==HMPV8_STAR_OPERATION||($star['database_writes']??null)!==0||($star['mapping_writes']??null)!==0||($star['supplier_calls']??null)!==0||count($star['prepared']??[])!==3)throw new RuntimeException('HMPV8_STAR');
    if(($v8['status']??null)!=='completed'||($v8['operation_id']??null)!==HMPV8_V8_OPERATION||($v8['database_writes']??null)!==0||($v8['mapping_writes']??null)!==0||($v8['booking_calls']??null)!==0||($v8['search_continue_calls']??null)!==0||(int)($v8['queue_count']??-1)!==288||(int)($v8['matched_unique']??-1)!==0||count($v8['confirmed_full_path']??[])!==0||count($v8['strong_operator_link']??[])!==0||count($v8['conflicts']??[])!==0)throw new RuntimeException('HMPV8_V8');
}
function hmpv8_review(PDO $db,array $cross,array $tv,array $star,array $v8,string $operation=HMPV8_OPERATION):array{
    if($operation!==HMPV8_OPERATION)throw new RuntimeException('HMPV8_SCOPE');hmpv8_validate_inputs($cross,$tv,$star,$v8);$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION READ ONLY');
    try{
        $coverage=fc_coverage($db);[$hotels,$names,$strict,$broad,$places,$scope]=mbr_catalog($db);$shaCountry=fc_sha_countries($db);[$anexLocal,$andromedaLocal]=mbr_local_sets($db);$anIndex=hmgcr_build_index($anexLocal,$hotels,$names);$andIndex=hmgcr_build_index($andromedaLocal,$hotels,$names);$allSet=[];foreach(array_keys($hotels) as $id)$allSet[(int)$id]=true;$allIndex=hmgcr_build_index($allSet,$hotels,$names);
        $andClaims=[];foreach($db->query("SELECT external_hotel_id,local_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IS NOT NULL")->fetchAll(PDO::FETCH_ASSOC) as $r)$andClaims[(int)$r['local_hotel_id']][]=(string)$r['external_hotel_id'];$anClaims=[];foreach($db->query('SELECT anex_hotel_id,catalog_hotel_id FROM anex_hotel_search_mappings WHERE enabled=1')->fetchAll(PDO::FETCH_ASSOC) as $r)$anClaims[(int)$r['catalog_hotel_id']][]=(int)$r['anex_hotel_id'];foreach($db->query("SELECT anex_hotel_id,catalog_hotel_id FROM anex_hotel_decisions WHERE decision_status='accepted' AND catalog_hotel_id IS NOT NULL")->fetchAll(PDO::FETCH_ASSOC) as $r)$anClaims[(int)$r['catalog_hotel_id']][]=(int)$r['anex_hotel_id'];
        $manual=array_fill_keys(array_map('intval',$db->query('SELECT anex_hotel_id FROM anex_hotel_decisions')->fetchAll(PDO::FETCH_COLUMN)),true);$mapped=array_fill_keys(array_map('intval',$db->query('SELECT anex_hotel_id FROM anex_hotel_search_mappings WHERE enabled=1')->fetchAll(PDO::FETCH_COLUMN)),true);$excluded=[];foreach($db->query('SELECT anex_hotel_id,catalog_hotel_id FROM anex_review_pair_exclusions')->fetchAll(PDO::FETCH_ASSOC) as $r)$excluded[(int)$r['anex_hotel_id']][(int)$r['catalog_hotel_id']]=true;
        $andPending=[];foreach($db->query("SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='pending' AND local_hotel_id IS NULL")->fetchAll(PDO::FETCH_ASSOC) as $r)$andPending[(string)$r['external_hotel_id']]=$r;$latest=[];$andCount=[];foreach($db->query("SELECT * FROM andromeda_search_hotel_observations WHERE supplier_namespace='andromeda_catalog' ORDER BY observed_at_utc DESC,external_hotel_id")->fetchAll(PDO::FETCH_ASSOC) as $o){$id=(string)$o['external_hotel_id'];$andCount[$id]=($andCount[$id]??0)+1;if(!isset($latest[$id]))$latest[$id]=$o;}
        $staging=[];foreach($db->query('SELECT * FROM anex_hotels')->fetchAll(PDO::FETCH_ASSOC) as $s)$staging[(int)$s['anex_hotel_id']]=$s;$anObs=[];foreach($db->query('SELECT * FROM anex_search_hotel_observations ORDER BY search_count DESC,last_seen_utc DESC,anex_hotel_id')->fetchAll(PDO::FETCH_ASSOC) as $o){$id=(int)$o['anex_hotel_id'];if(!isset($anObs[$id]))$anObs[$id]=$o;}
        $allow=[];foreach($cross['prepared'] as $r)$allow[hmpv8_key((string)$r['provider'],$r['external_id'])]['cross']=$r;foreach($tv['prepared'] as $r)$allow[hmpv8_key((string)$r['provider'],$r['external_id'])]['tourvisor']=$r;foreach($star['prepared'] as $r)$allow[hmpv8_key((string)$r['provider'],$r['external_id'])]['star']=$r;
        $rows=[];$stats=['allow_sources'=>count($allow),'protected'=>0,'not_pending'=>0,'country_unknown'=>0,'target_changed'=>0,'promotion_guard_block'=>0,'source_conflict'=>0,'prepared'=>0,'prepared_anex'=>0,'prepared_andromeda'=>0,'prepared_live'=>0,'multi_source'=>0,'single_source'=>0,'collision_demoted'=>0];
        foreach($allow as $key=>$origins){[$provider,$external]=explode(':',$key,2);$valid=[];$live=false;$count=0;$country=0;
            if($provider==='andromeda'){$identity=$andPending[$external]??null;if(!is_array($identity)){$stats['not_pending']++;continue;}$obs=$latest[$external]??null;$country=(int)($obs['country_id']??0);if(!isset(HMGCR_CORE8[$country]))$country=(int)($shaCountry[$identity['catalog_sha256']]??0);if(!isset(HMGCR_CORE8[$country])){$stats['country_unknown']++;continue;}$source=hmgcr_andromeda_source($identity,$obs);$live=(int)($andCount[$external]??0)>0;$count=(int)($andCount[$external]??0);$sameClaims=$andClaims;$opIndex=$anIndex;}
            elseif($provider==='anex'){$aid=(int)$external;if(isset($manual[$aid])||isset($mapped[$aid])){$stats['protected']++;continue;}$stage=$staging[$aid]??[];$obs=$anObs[$aid]??[];$country=(int)($obs['country_id']??0);if(!isset(HMGCR_CORE8[$country]))$country=(int)(fc_country($stage['api_country']??'')??0);if(!isset(HMGCR_CORE8[$country])){$stats['country_unknown']++;continue;}$source=['names'=>array_values(array_unique(array_filter([(string)($obs['hotel_name']??''),(string)($stage['api_name']??''),(string)($stage['xml_name']??''),(string)($stage['xml_alternate_name']??'')],static fn($v)=>trim($v)!==''))),'places'=>array_values(array_unique(array_filter([(string)($stage['api_region']??''),(string)($stage['api_town']??'')],static fn($v)=>trim($v)!==''))),'latitude'=>$stage['latitude']??null,'longitude'=>$stage['longitude']??null];$live=!empty($obs);$count=(int)($obs['search_count']??0);$sameClaims=$anClaims;$opIndex=$andIndex;}
            else continue;
            foreach($origins as $origin=>$historic){$expected=(int)($historic['target_local_hotel_id']??0);$d=null;$opp=isset(($provider==='andromeda'?$anexLocal:$andromedaLocal)[$expected]);
                if($origin==='cross')$d=hmgcr_decide($source,$country,$opIndex,$hotels,$names,$sameClaims,$provider==='anex'?($excluded[(int)$external]??[]):[]);
                elseif($origin==='tourvisor')$d=hmgtr_decide($source,$country,$allIndex,$hotels,$names,$sameClaims,$provider==='anex'?($excluded[(int)$external]??[]):[]);
                elseif($origin==='star'&&$provider==='andromeda'){$s=hmasbr_source($identity,$obs??null);[$ids]=hmasbr_targets($broad,$country,$s['names']);if(count($ids)===1){$tid=(int)$ids[0];$t=$hotels[$tid]??null;if($t&&isset($anexLocal[$tid])&&!isset($andClaims[$tid])){$pair=hmgcr_best_pair($s['names'],$names[$tid]??[(string)$t['name']],$s['places'],[(string)$t['region_name'],(string)$t['subregion_name']]);$brand=count(hmpv8_brand_tokens($pair));if(($pair['critical_ok']??false)&&$brand>=1)$d=['bucket'=>'prepared','reason'=>'star_exact_opposite_bridge','target_local_hotel_id'=>$tid,'pair'=>$pair,'distance_m'=>null,'place_match'=>hmgcr_place($s['places'],[(string)$t['region_name'],(string)$t['subregion_name']])];}}}
                if(!is_array($d)||($d['bucket']??'')!=='prepared'||(int)($d['target_local_hotel_id']??0)!==$expected){$stats['target_changed']++;continue;}if($origin!=='star'&&!hmpv8_pair_safe($d,$opp)){$stats['promotion_guard_block']++;continue;}$valid[$expected][$origin]=$d;
            }
            if(!$valid)continue;if(count($valid)!==1){$stats['source_conflict']++;continue;}$target=(int)array_key_first($valid);$srcs=array_keys($valid[$target]);sort($srcs,SORT_STRING);$rows[$key]=['provider'=>$provider,'external_id'=>$external,'country_id'=>$country,'live'=>$live,'observation_count'=>$count,'target_local_hotel_id'=>$target,'target_name'=>$hotels[$target]['name']??null,'evidence_sources'=>$srcs,'evidence'=>$valid[$target],'bucket'=>'auto_accept','reason'=>count($srcs)>1?'post_v8_multi_source_current':'post_v8_single_source_current'];}
        $by=[];foreach($rows as $k=>$r)$by[$r['provider'].':'.$r['target_local_hotel_id']][]=$k;foreach($by as $ks)if(count($ks)>1)foreach($ks as $k){$rows[$k]['bucket']='needs_extra_evidence';$rows[$k]['reason']='same_provider_target_collision';$stats['collision_demoted']++;}
        $prepared=[];$blocked=[];foreach($rows as $r){if($r['bucket']==='auto_accept'){$prepared[]=$r;$stats['prepared']++;if($r['provider']==='anex')$stats['prepared_anex']++;else$stats['prepared_andromeda']++;if($r['live'])$stats['prepared_live']++;if(count($r['evidence_sources'])>1)$stats['multi_source']++;else$stats['single_source']++;}else$blocked[]=$r;}usort($prepared,static fn($a,$b)=>(($a['live']?0:1)<=>($b['live']?0:1))?:($b['observation_count']<=>$a['observation_count'])?:strcmp($a['provider'],$b['provider'])?:strcmp((string)$a['external_id'],(string)$b['external_id']));$db->commit();
        return ['status'=>'completed','operation_id'=>$operation,'mode'=>'post_v8_current_rescue_ensemble_read_only','database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'historical_operations_replayed'=>false,'coverage'=>$coverage,'catalog_scope'=>$scope,'v8'=>['queue_count'=>(int)$v8['queue_count'],'planned_slices'=>(int)($v8['supplier']['planned_slices']??0),'result_rows'=>array_sum(array_map(static fn($x)=>(int)($x['result_hotels']??0),$v8['searches']??[])),'matched_unique'=>(int)$v8['matched_unique']],'stats'=>$stats,'prepared'=>$prepared,'blocked'=>$blocked,'guards'=>['current_revalidation'=>true,'same_provider_occupancy'=>true,'pair_exclusions'=>true,'coordinate_conflict_auto_block_m'=>5000,'critical_qualifiers_are_guard_not_identity'=>true,'geography_structural_tokens_not_identity'=>true,'v8_direct_matches_required_for_v8_promotion'=>true]];
    }catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
}
if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__){fwrite(STDERR,"library_only: use guarded post-v8 workflow\n");exit(64);}
