<?php
declare(strict_types=1);
/** MATCH #1971: CURRENT read-only census of explicit Andromeda original.hotelKey/operatorKey evidence. */
const HMAP_OP='hotel-match-andromeda-original-native-census-1971-20260916-v1';
function j($v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
function putnew(string $p,$v):string{$raw=j($v)."\n";$f=@fopen($p,'x');if(!$f)throw new RuntimeException('durable_create_failed');try{if(fwrite($f,$raw)!==strlen($raw))throw new RuntimeException('durable_write_failed');fflush($f);}finally{fclose($f);}if(file_get_contents($p)!==$raw)throw new RuntimeException('durable_readback_failed');return hash('sha256',$raw);}
function dbpath(string $r):string{foreach([$r.'/data/db-v1.php',$r.'/v2/data/db-v1.php'] as $p)if(is_file($p))return $p;throw new RuntimeException('db_bootstrap_missing');}
function cols(PDO $d,string $t):array{$s=$d->query('SHOW COLUMNS FROM `'.str_replace('`','',$t).'`');$o=[];foreach($s->fetchAll(PDO::FETCH_ASSOC)?:[] as $r)$o[(string)$r['Field']]=true;return $o;}
function q(PDO $d,string $sql,array $p=[]):array{$s=$d->prepare($sql);$s->execute($p);return $s->fetchAll(PDO::FETCH_ASSOC)?:[];}
function posint($v):?string{if(!is_scalar($v))return null;$s=trim((string)$v);return preg_match('/^[1-9][0-9]{0,14}$/D',$s)?$s:null;}
function direct_key(array $a,array $keys):?string{foreach($keys as $k)if(array_key_exists($k,$a)&&($v=posint($a[$k]))!==null)return $v;return null;}
function original_pairs($v,string $path='evidence'):array{
  if(!is_array($v))return[];$out=[];
  foreach($v as $k=>$x){$ks=(string)$k;$p=$path.'.'.$ks;
    if(strcasecmp($ks,'original')===0 && is_array($x)){
      $h=direct_key($x,['hotelKey','hotel_key','hotelId','hotel_id']);
      $o=direct_key($x,['operatorKey','operator_key','operatorId','operator_id']);
      if($h!==null||$o!==null)$out[]=['path'=>$p,'hotel_key'=>$h,'operator_key'=>$o];
    }
    if(is_array($x))foreach(original_pairs($x,$p) as $z)$out[]=$z;
  }
  return $out;
}
function evidence($raw):?array{if(!is_string($raw)||trim($raw)==='')return null;try{$x=json_decode($raw,true,512,JSON_THROW_ON_ERROR);return is_array($x)?$x:null;}catch(Throwable){return null;}}
if(in_array('--self-test',$argv??[],true)){$x=['source'=>['original'=>['hotelKey'=>4158,'operatorKey'=>5]]];$p=original_pairs($x);if(count($p)!==1||$p[0]['hotel_key']!=='4158'||$p[0]['operator_key']!=='5'||$p[0]['path']!=='evidence.source.original')throw new RuntimeException('pair_test');if(original_pairs(['photo'=>['original'=>['PhotoId'=>495437]]])!==[])throw new RuntimeException('photo_test');echo "PASS\n";exit(0);}
$op=(string)getenv('OPERATION_ID');$sha=(string)getenv('MATCH_SOURCE_SHA');if($op!==HMAP_OP||!preg_match('/^[0-9a-f]{40}$/D',$sha))throw new RuntimeException('operation_guard');$root=(string)realpath(getcwd());if($root===''||basename($root)!=='anytoour.ru')throw new RuntimeException('root_guard');$base=rtrim((string)getenv('HOME'),'/').'/.anytoour-match/operations';if(!is_dir($base))throw new RuntimeException('operations_root_missing');$dir=$base.'/'.$op;if(!mkdir($dir,0700))throw new RuntimeException('operation_exists');putnew($dir.'/reservation.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'reserved_before_db_access','read_only'=>true,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);
$db=null;try{require_once dbpath($root);$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');$c=cols($db,'andromeda_hotel_identities');foreach(['supplier_namespace','external_hotel_id','local_hotel_id','decision_status','evidence_json'] as $need)if(!isset($c[$need]))throw new RuntimeException('identity_schema_missing_'.$need);
$rows=q($db,'SELECT supplier_namespace,external_hotel_id,local_hotel_id,decision_status,evidence_json FROM andromeda_hotel_identities ORDER BY supplier_namespace,external_hotel_id');$db->exec('ROLLBACK');
$pending=[];$pendingPairRows=0;$pendingBoth=0;$pendingPartial=0;$pathCounts=[];$operatorCounts=[];$acceptedSupport=[];$statusCounts=[];
foreach($rows as $r){$ns=(string)$r['supplier_namespace'];$st=(string)$r['decision_status'];$statusCounts[$st]=($statusCounts[$st]??0)+1;$ev=evidence($r['evidence_json']);if($ev===null)continue;$pairs=original_pairs($ev);if($pairs===[])continue;foreach($pairs as $p){$pathCounts[$p['path']]=($pathCounts[$p['path']]??0)+1;if($p['operator_key']!==null)$operatorCounts[$p['operator_key']]=($operatorCounts[$p['operator_key']]??0)+1;}
  if($st==='pending'&&$r['local_hotel_id']===null&&$ns==='andromeda_catalog'){
    $uniq=[];foreach($pairs as $p){$key=($p['hotel_key']??'').':'.($p['operator_key']??'').':'.$p['path'];$uniq[$key]=$p;}$pairs=array_values($uniq);$pendingPairRows++;$hasBoth=false;foreach($pairs as $p)if($p['hotel_key']!==null&&$p['operator_key']!==null){$hasBoth=true;break;}$hasBoth?$pendingBoth++:$pendingPartial++;
    $pending[]=['supplier_namespace'=>$ns,'external_hotel_id'=>(string)$r['external_hotel_id'],'pairs'=>$pairs];
  }
  if($st==='accepted'&&$r['local_hotel_id']!==null&&$ns!=='andromeda_catalog')foreach($pairs as $p)if($p['operator_key']!==null){$acceptedSupport[$p['operator_key']][$ns]=($acceptedSupport[$p['operator_key']][$ns]??0)+1;}
}
ksort($pathCounts);ksort($operatorCounts,SORT_NATURAL);ksort($acceptedSupport,SORT_NATURAL);foreach($acceptedSupport as &$m)ksort($m);unset($m);ksort($statusCounts);usort($pending,fn($a,$b)=>strcmp($a['external_hotel_id'],$b['external_hotel_id']));
$crosswalk=[];foreach($acceptedSupport as $opk=>$m){arsort($m);$names=array_keys($m);$top=$names[0]??null;$topn=$top!==null?$m[$top]:0;$second=$names[1]??null;$crosswalk[$opk]=['support'=>$m,'unanimous_namespace'=>count($m)===1&&$topn>=3?$top:null,'support_count'=>$topn,'ambiguous'=>count($m)>1];}
$result=['schema'=>'hotel-match-andromeda-original-native-census/1','operation_id'=>$op,'source_sha'=>$sha,'state'=>'completed_read_only','server_current'=>true,'identity_rows_examined'=>count($rows),'status_counts'=>$statusCounts,'pending_andromeda_with_original_rows'=>$pendingPairRows,'pending_with_complete_original_pair'=>$pendingBoth,'pending_with_partial_original_pair'=>$pendingPartial,'original_path_counts'=>$pathCounts,'original_operator_key_counts'=>$operatorCounts,'accepted_nonandromeda_operator_support'=>$acceptedSupport,'derived_operator_namespace_crosswalk'=>$crosswalk,'pending_original_candidates'=>$pending,'candidate_policy'=>'explicit nested original hotelKey/operatorKey only; no generic numeric/photo/path promotion; read-only evidence census','safe_to_write_now'=>false,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'booking_calls'=>0,'lead_calls'=>0,'no_replay'=>true];$digest=putnew($dir.'/result.json',$result);putnew($dir.'/receipt.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'completed_read_only','result_sha256'=>$digest,'readback_verified'=>hash('sha256',(string)file_get_contents($dir.'/result.json'))===$digest,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);echo j(['state'=>'completed_read_only','identity_rows_examined'=>count($rows),'pending_with_complete_original_pair'=>$pendingBoth,'pending_with_partial_original_pair'=>$pendingPartial,'operator_keys'=>array_keys($operatorCounts)])."\n";
}catch(Throwable $e){try{if($db instanceof PDO&&$db->inTransaction())$db->rollBack();}catch(Throwable){}$f=['operation_id'=>$op,'source_sha'=>$sha,'state'=>'failed_read_only','error_class'=>get_class($e),'error_message'=>$e->getMessage(),'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true];$digest=putnew($dir.'/failure.json',$f);putnew($dir.'/receipt.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'failed_read_only','failure_sha256'=>$digest,'readback_verified'=>true,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);fwrite(STDERR,"HMAP_FAILED ".$e->getMessage()."\n");exit(2);}
