<?php
declare(strict_types=1);

const FC_OPERATION = 'hotel-full-catalog-1759-20260911-v1';
const FC_POLICY = 'owner_exact_and_strong_20260908';
const FC_COUNTRIES = [1=>'Египет',2=>'Таиланд',4=>'Турция',8=>'Мальдивы',9=>'ОАЭ',10=>'Куба',12=>'Шри-Ланка',16=>'Вьетнам'];

function fc_json($v): string { return json_encode($v, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR); }
function fc_hash($v): string { return hash('sha256', is_string($v) ? $v : fc_json($v)); }
function fc_norm($v): string {
    $v=mb_strtolower(trim((string)$v),'UTF-8');
    $v=strtr($v,['ё'=>'е','é'=>'e','è'=>'e','ê'=>'e','á'=>'a','à'=>'a','ä'=>'a','â'=>'a','ö'=>'o','ô'=>'o','ü'=>'u','ú'=>'u','ç'=>'c','ş'=>'s','ğ'=>'g','ı'=>'i']);
    preg_match_all('/[\p{L}\p{N}]+/u',$v,$m); return implode(' ',$m[0]);
}
function fc_tokens($v,bool $broad=false): array {
    $v=preg_replace('/\s*\(\s*(?:ex|ех)\s*\.?\s+[^()]+\)\s*$/ui',' ',(string)$v);
    $generic=['hotel'=>1,'hotels'=>1,'отель'=>1,'отели'=>1];
    if($broad)$generic+=['resort'=>1,'resorts'=>1,'spa'=>1,'the'=>1,'and'=>1,'club'=>1,'apart'=>1,'aparthotel'=>1,'apartments'=>1,'apartment'=>1,'suite'=>1,'suites'=>1,'резорт'=>1,'ресорт'=>1,'спа'=>1,'клуб'=>1,'апартаменты'=>1];
    return array_values(array_filter(explode(' ',fc_norm($v)),static fn($x)=>$x!==''&&!isset($generic[$x])));
}
function fc_key($v,bool $broad=false,bool $bag=false): string { $t=fc_tokens($v,$broad); if($bag)sort($t,SORT_STRING); return implode(' ',$t); }
function fc_num($v): ?float { if($v===null||$v==='')return null;$x=(float)$v;return is_finite($x)&&$x!=0.0?$x:null; }
function fc_dist($a,$b,$c,$d): ?float {
    $p=[fc_num($a),fc_num($b),fc_num($c),fc_num($d)]; if(in_array(null,$p,true))return null;
    $p=array_map('deg2rad',$p);[$a,$b,$c,$d]=$p;$x=sin(($c-$a)/2)**2+cos($a)*cos($c)*sin(($d-$b)/2)**2;return 6371000*2*asin(min(1,sqrt($x)));
}
function fc_place(array $source,array $target): bool {
    $a=[];$b=[];foreach($source as $v){$n=fc_norm($v);if($n!=='')$a[$n]=1;}foreach($target as $v){$n=fc_norm($v);if($n!=='')$b[$n]=1;}return (bool)array_intersect_key($a,$b);
}
function fc_country($v): ?int {
    $n=fc_norm($v);$groups=[1=>['egypt','египет'],2=>['thailand','таиланд','тайланд'],4=>['turkey','turkiye','türkiye','турция'],8=>['maldives','мальдивы'],9=>['united arab emirates','uae','оаэ','эмираты'],10=>['cuba','куба'],12=>['sri lanka','sri-lanka','шри ланка'],16=>['vietnam','viet nam','вьетнам']];
    foreach($groups as $id=>$names)foreach($names as $name)if($n===fc_norm($name))return $id;return null;
}
function fc_evidence($raw): array { try{$v=json_decode((string)$raw,true,64,JSON_THROW_ON_ERROR);return is_array($v)?$v:[];}catch(Throwable $e){return [];} }
function fc_source(array $row): array { $e=fc_evidence($row['evidence_json']??'');$s=$e['source']??[];return is_array($s)?$s:[]; }
function fc_category(array $source): ?int {
    foreach(['category','star','stars','starName','star_name'] as $key){if(!array_key_exists($key,$source))continue;if(preg_match('/([1-5])/',(string)$source[$key],$m))return (int)$m[1];}return null;
}
function fc_write_once(string $path,array $v): void { $raw=fc_json($v);$f=@fopen($path,'x');if(!$f)throw new RuntimeException('operation_already_reserved');@chmod($path,0600);try{if(fwrite($f,$raw)!==strlen($raw)||!fflush($f))throw new RuntimeException('receipt_write');if(function_exists('fsync')&&!fsync($f))throw new RuntimeException('receipt_sync');}finally{fclose($f);} }
function fc_require_tables(PDO $db): void {
    $need=['catalog_countries','catalog_hotels','catalog_hotel_details','hotel_aliases','anex_hotels','anex_hotel_search_mappings','anex_hotel_decisions','anex_review_pair_exclusions','andromeda_hotel_identities'];$marks=implode(',',array_fill(0,count($need),'?'));
    $q=$db->prepare("SELECT TABLE_NAME,ENGINE FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME IN ($marks)");$q->execute($need);$got=$q->fetchAll(PDO::FETCH_KEY_PAIR);foreach($need as $t)if(strtoupper((string)($got[$t]??''))!=='INNODB')throw new RuntimeException('required_transactional_table_missing');
}
function fc_coverage(PDO $db): array {
    $anex=[];$q=$db->query("SELECT m.catalog_hotel_id FROM anex_hotel_search_mappings m LEFT JOIN anex_hotel_decisions d ON d.anex_hotel_id=m.anex_hotel_id WHERE m.enabled=1 AND m.scope='preview' AND m.approval_policy='".FC_POLICY."' AND d.anex_hotel_id IS NULL AND NOT EXISTS(SELECT 1 FROM anex_review_pair_exclusions x WHERE x.anex_hotel_id=m.anex_hotel_id AND x.catalog_hotel_id=m.catalog_hotel_id)");foreach($q->fetchAll(PDO::FETCH_COLUMN) as $id)$anex[(int)$id]=1;
    $q=$db->query("SELECT d.catalog_hotel_id FROM anex_hotel_decisions d WHERE d.decision_status='accepted' AND d.catalog_hotel_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM anex_review_pair_exclusions x WHERE x.anex_hotel_id=d.anex_hotel_id AND x.catalog_hotel_id=d.catalog_hotel_id)");foreach($q->fetchAll(PDO::FETCH_COLUMN) as $id)$anex[(int)$id]=1;
    $andr=[];$q=$db->query("SELECT DISTINCT local_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IS NOT NULL");foreach($q->fetchAll(PDO::FETCH_COLUMN) as $id)$andr[(int)$id]=1;$triple=count(array_intersect_key($anex,$andr));
    $links=(int)$db->query("SELECT COUNT(*) FROM anex_hotel_search_mappings m LEFT JOIN anex_hotel_decisions d ON d.anex_hotel_id=m.anex_hotel_id WHERE m.enabled=1 AND m.scope='preview' AND m.approval_policy='".FC_POLICY."' AND d.anex_hotel_id IS NULL AND NOT EXISTS(SELECT 1 FROM anex_review_pair_exclusions x WHERE x.anex_hotel_id=m.anex_hotel_id AND x.catalog_hotel_id=m.catalog_hotel_id)")->fetchColumn();$manual=(int)$db->query("SELECT COUNT(*) FROM anex_hotel_decisions WHERE decision_status='accepted' AND catalog_hotel_id IS NOT NULL")->fetchColumn();
    return ['anex_links'=>$links+$manual,'anex_unique_local'=>count($anex),'andromeda_unique_local'=>count($andr),'all_three'=>$triple,'anex_tv_only'=>count($anex)-$triple,'andromeda_tv_only'=>count($andr)-$triple,'exactly_two'=>count($anex)+count($andr)-2*$triple];
}
function fc_catalog(PDO $db): array {
    $q=$db->query('SELECT id,name FROM catalog_countries WHERE id IN (1,2,4,8,9,10,12,16) ORDER BY id FOR UPDATE');$seen=[];while($r=$q->fetch(PDO::FETCH_ASSOC)){$id=(int)$r['id'];if((FC_COUNTRIES[$id]??null)!==$r['name'])throw new RuntimeException('country_contract_changed');$seen[$id]=1;}if(count($seen)!==8)throw new RuntimeException('country_contract_changed');
    $q=$db->query('SELECT h.id,h.country_id,h.country_name,h.name,h.normalized_name,h.region_name,h.subregion_name,h.category,h.is_active,COALESCE(d.latitude,h.latitude) latitude,COALESCE(d.longitude,h.longitude) longitude FROM catalog_hotels h LEFT JOIN catalog_hotel_details d ON d.hotel_id=h.id WHERE h.country_id IN (1,2,4,8,9,10,12,16) AND h.is_active=1 ORDER BY h.country_id,h.id FOR UPDATE');
    $hotels=[];$strict=[];$broad=[];$names=[];$count=0;while($h=$q->fetch(PDO::FETCH_ASSOC)){if(++$count>50000)throw new RuntimeException('hotel_scope_limit');$id=(int)$h['id'];$c=(int)$h['country_id'];$hotels[$id]=$h;$names[$id]=[$h['name']];foreach([$h['name'],$h['normalized_name']] as $n){$k=fc_key($n);if($k!=='')$strict[$c][$k][$id]=1;$k=fc_key($n,true,true);if($k!=='')$broad[$c][$k][$id]=1;}}
    $q=$db->query('SELECT a.hotel_id,a.alias,a.normalized_alias,h.country_id FROM hotel_aliases a JOIN catalog_hotels h ON h.id=a.hotel_id WHERE h.country_id IN (1,2,4,8,9,10,12,16) AND h.is_active=1 ORDER BY h.country_id,a.hotel_id,a.id FOR UPDATE');$aliases=0;while($a=$q->fetch(PDO::FETCH_ASSOC)){if(++$aliases>100000)throw new RuntimeException('alias_scope_limit');$id=(int)$a['hotel_id'];$c=(int)$a['country_id'];foreach([$a['alias'],$a['normalized_alias']] as $n){$names[$id][]=$n;$k=fc_key($n);if($k!=='')$strict[$c][$k][$id]=1;$k=fc_key($n,true,true);if($k!=='')$broad[$c][$k][$id]=1;}}
    return [$hotels,$names,$strict,$broad,['countries'=>8,'hotels'=>$count,'aliases'=>$aliases]];
}
function fc_resolve(array $index,int $country,array $names,bool $broad): ?int { $targets=[];foreach($names as $n){$k=fc_key($n,$broad,$broad);if($k==='')continue;foreach(array_keys($index[$country][$k]??[]) as $id)$targets[(int)$id]=1;}return count($targets)===1?(int)array_key_first($targets):null; }
function fc_sha_countries(PDO $db): array {
    $tmp=[];$q=$db->query("SELECT i.catalog_sha256,h.country_id,COUNT(*) n FROM andromeda_hotel_identities i JOIN catalog_hotels h ON h.id=i.local_hotel_id WHERE i.supplier_namespace='andromeda_catalog' AND i.local_hotel_id IS NOT NULL AND h.country_id IN (1,2,4,8,9,10,12,16) GROUP BY i.catalog_sha256,h.country_id");while($r=$q->fetch(PDO::FETCH_ASSOC))$tmp[$r['catalog_sha256']][(int)$r['country_id']]=(int)$r['n'];$out=[];foreach($tmp as $sha=>$by){arsort($by);$ids=array_keys($by);if(count($ids)===1||$by[$ids[0]]>($by[$ids[1]]??0)*20)$out[$sha]=(int)$ids[0];}return $out;
}
function fc_reconcile(PDO $db,string $operation): array {
    fc_require_tables($db);$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET SESSION innodb_lock_wait_timeout=20');$before=fc_coverage($db);$committed=false;$writes=0;
    try{$db->beginTransaction();[$hotels,$names,$strict,$broad,$scope]=fc_catalog($db);
        $manual=array_fill_keys(array_map('intval',$db->query('SELECT anex_hotel_id FROM anex_hotel_decisions ORDER BY anex_hotel_id FOR UPDATE')->fetchAll(PDO::FETCH_COLUMN)),1);$existing=array_fill_keys(array_map('intval',$db->query('SELECT anex_hotel_id FROM anex_hotel_search_mappings ORDER BY anex_hotel_id FOR UPDATE')->fetchAll(PDO::FETCH_COLUMN)),1);$excluded=[];foreach($db->query('SELECT anex_hotel_id,catalog_hotel_id FROM anex_review_pair_exclusions ORDER BY anex_hotel_id,catalog_hotel_id FOR UPDATE')->fetchAll(PDO::FETCH_ASSOC) as $x)$excluded[(int)$x['anex_hotel_id']][(int)$x['catalog_hotel_id']]=1;
        $andAccepted=[];$andBridge=[];$q=$db->query("SELECT i.local_hotel_id,i.evidence_json,h.country_id FROM andromeda_hotel_identities i JOIN catalog_hotels h ON h.id=i.local_hotel_id WHERE i.supplier_namespace='andromeda_catalog' AND i.decision_status='accepted' AND i.local_hotel_id IS NOT NULL AND h.country_id IN (1,2,4,8,9,10,12,16) FOR UPDATE");while($r=$q->fetch(PDO::FETCH_ASSOC)){$target=(int)$r['local_hotel_id'];$andAccepted[$target]=1;$s=fc_source($r);foreach([$s['name']??'',$s['lName']??''] as $n){$k=fc_key($n,true,true);if($k!=='')$andBridge[(int)$r['country_id']][$k][$target]=1;}}
        $insert=$db->prepare("INSERT INTO anex_hotel_search_mappings(anex_hotel_id,catalog_hotel_id,match_class,scope,approval_policy,source_row_digest,mapping_digest,enabled) VALUES(?,?,'strong_candidate','preview',?,?,?,1)");$mapDigest=fc_hash([$operation,'full_saved_core8_current_db']);$anex=['staging'=>0,'eligible'=>0,'accepted'=>0,'strict'=>0,'broad_geo'=>0,'andromeda_bridge'=>0,'manual'=>0,'existing'=>0,'country_other'=>0,'ambiguous'=>0,'geo_conflict'=>0,'pair_excluded'=>0];$anRows=[];
        $q=$db->query('SELECT * FROM anex_hotels ORDER BY anex_hotel_id FOR UPDATE');while($s=$q->fetch(PDO::FETCH_ASSOC)){$anex['staging']++;$id=(int)$s['anex_hotel_id'];if(isset($manual[$id])){$anex['manual']++;continue;}if(isset($existing[$id])){$anex['existing']++;continue;}$country=fc_country($s['api_country']??'');if(!$country){$anex['country_other']++;continue;}$anex['eligible']++;$sourceNames=[$s['api_name']??'',$s['xml_name']??'',$s['xml_alternate_name']??''];$target=fc_resolve($strict,$country,$sourceNames,false);$rule=null;if($target!==null){$rule='strict';$anex['strict']++;}else{$candidate=fc_resolve($broad,$country,$sourceNames,true);if($candidate!==null){$h=$hotels[$candidate];$d=fc_dist($s['latitude']??null,$s['longitude']??null,$h['latitude'],$h['longitude']);$place=fc_place([$s['api_region']??'',$s['api_town']??''],[$h['region_name'],$h['subregion_name']]);if(($d!==null&&$d<=1000)||$place){$target=$candidate;$rule='broad_geo';$anex['broad_geo']++;}}}
            if($target===null){$bridge=[];foreach($sourceNames as $n){$k=fc_key($n,true,true);if($k!=='')foreach(array_keys($andBridge[$country][$k]??[]) as $x)$bridge[(int)$x]=1;}if(count($bridge)===1){$candidate=(int)array_key_first($bridge);$h=$hotels[$candidate]??null;if($h){$d=fc_dist($s['latitude']??null,$s['longitude']??null,$h['latitude'],$h['longitude']);if($d===null||$d<=5000){$target=$candidate;$rule='andromeda_bridge';$anex['andromeda_bridge']++;}}}}
            if($target===null){$anex['ambiguous']++;continue;}$h=$hotels[$target];$d=fc_dist($s['latitude']??null,$s['longitude']??null,$h['latitude'],$h['longitude']);if($d!==null&&$d>5000){$anex['geo_conflict']++;continue;}if(isset($excluded[$id][$target])){$anex['pair_excluded']++;continue;}$ev=['operation_id'=>$operation,'provider'=>'anex','rule'=>$rule,'anex_hotel_id'=>$id,'country_id'=>$country,'source_fingerprint'=>$s['source_fingerprint'],'names'=>array_values(array_filter($sourceNames)),'region'=>$s['api_region'],'town'=>$s['api_town'],'distance_m'=>$d===null?null:round($d,1),'target'=>$target];$digest=fc_hash($ev);$insert->execute([$id,$target,FC_POLICY,$digest,$mapDigest]);$anRows[$id]=[$target,$digest];$anex['accepted']++;$writes++;}
        $anexBridge=[];$q=$db->query("SELECT m.catalog_hotel_id,s.api_name,s.xml_name,s.xml_alternate_name,h.country_id FROM anex_hotel_search_mappings m LEFT JOIN anex_hotels s ON s.anex_hotel_id=m.anex_hotel_id JOIN catalog_hotels h ON h.id=m.catalog_hotel_id WHERE m.enabled=1 AND h.country_id IN (1,2,4,8,9,10,12,16) UNION ALL SELECT d.catalog_hotel_id,s.api_name,s.xml_name,s.xml_alternate_name,h.country_id FROM anex_hotel_decisions d LEFT JOIN anex_hotels s ON s.anex_hotel_id=d.anex_hotel_id JOIN catalog_hotels h ON h.id=d.catalog_hotel_id WHERE d.decision_status='accepted' AND h.country_id IN (1,2,4,8,9,10,12,16)");while($r=$q->fetch(PDO::FETCH_ASSOC))foreach([$r['api_name'],$r['xml_name'],$r['xml_alternate_name']] as $n){$k=fc_key($n,true,true);if($k!=='')$anexBridge[(int)$r['country_id']][$k][(int)$r['catalog_hotel_id']]=1;}
        $shaCountry=fc_sha_countries($db);$update=$db->prepare("UPDATE andromeda_hotel_identities SET local_hotel_id=?,decision_status='accepted',evidence_sha256=?,evidence_json=? WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=? AND decision_status='pending' AND local_hotel_id IS NULL AND evidence_sha256=?");$and=['pending'=>0,'accepted'=>0,'strict'=>0,'anex_bridge'=>0,'broad_geo'=>0,'country_unknown'=>0,'candidate_conflict'=>0,'category_conflict'=>0,'ambiguous'=>0];$andRows=[];
        $q=$db->query("SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='pending' AND local_hotel_id IS NULL ORDER BY external_hotel_id FOR UPDATE");while($r=$q->fetch(PDO::FETCH_ASSOC)){$and['pending']++;$prior=fc_evidence($r['evidence_json']);$s=$prior['source']??[];if(!is_array($s))$s=[];$country=$shaCountry[$r['catalog_sha256']]??null;if(!$country){$cand=array_map('intval',$prior['candidate_ids']??[]);$cc=[];foreach($cand as $x)if(isset($hotels[$x]))$cc[(int)$hotels[$x]['country_id']]=1;if(count($cc)===1)$country=(int)array_key_first($cc);}if(!$country||!isset(FC_COUNTRIES[$country])){$and['country_unknown']++;continue;}$sourceNames=[$s['name']??'',$s['lName']??''];$target=fc_resolve($strict,$country,$sourceNames,false);$rule=null;if($target!==null){$rule='strict';$and['strict']++;}else{$bridge=[];foreach($sourceNames as $n){$k=fc_key($n,true,true);if($k!=='')foreach(array_keys($anexBridge[$country][$k]??[]) as $x)$bridge[(int)$x]=1;}if(count($bridge)===1){$target=(int)array_key_first($bridge);$rule='anex_bridge';$and['anex_bridge']++;}}
            if($target===null){$candidate=fc_resolve($broad,$country,$sourceNames,true);if($candidate!==null){$g=$prior['geography']??[];$place=fc_place([$s['town']??'',$g['town']??'',$g['parent']??''],[$hotels[$candidate]['region_name'],$hotels[$candidate]['subregion_name']]);if($place){$target=$candidate;$rule='broad_geo';$and['broad_geo']++;}}}
            if($target===null){$and['ambiguous']++;continue;}$orig=array_map('intval',$prior['candidate_ids']??[]);if($orig&&$rule!=='anex_bridge'&&!in_array($target,$orig,true)){$and['candidate_conflict']++;continue;}$sourceCat=fc_category($s);$targetCat=$hotels[$target]['category']===null?null:(int)$hotels[$target]['category'];if($sourceCat&&$targetCat&&$sourceCat!==$targetCat){$and['category_conflict']++;continue;}$promotion=['operation_id'=>$operation,'source'=>'full_saved_catalog','rule'=>$rule,'country_id'=>$country,'target'=>$target,'source_category'=>$sourceCat,'target_category'=>$targetCat];$ev=['prior_evidence'=>$prior,'promotion'=>$promotion];$json=fc_json($ev);$hash=hash('sha256',$json);$update->execute([$target,$hash,$json,(string)$r['external_hotel_id'],$r['evidence_sha256']]);if($update->rowCount()!==1)throw new RuntimeException('andromeda_concurrent_change');$andRows[(string)$r['external_hotel_id']]=[$target,$hash];$and['accepted']++;$writes++;}
        $db->commit();$committed=true;
        $q=$db->prepare("SELECT catalog_hotel_id,source_row_digest,enabled FROM anex_hotel_search_mappings WHERE anex_hotel_id=? AND scope='preview' AND approval_policy=?");foreach($anRows as $id=>$expected){$q->execute([$id,FC_POLICY]);$v=$q->fetch(PDO::FETCH_ASSOC);if(!$v||(int)$v['catalog_hotel_id']!==$expected[0]||$v['source_row_digest']!==$expected[1]||(int)$v['enabled']!==1)throw new RuntimeException('anex_readback');}
        $q=$db->prepare("SELECT local_hotel_id,decision_status,evidence_sha256 FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=?");foreach($andRows as $id=>$expected){$q->execute([$id]);$v=$q->fetch(PDO::FETCH_ASSOC);if(!$v||(int)$v['local_hotel_id']!==$expected[0]||$v['decision_status']!=='accepted'||$v['evidence_sha256']!==$expected[1])throw new RuntimeException('andromeda_readback');}
        $after=fc_coverage($db);return ['status'=>'completed','operation_id'=>$operation,'scope'=>FC_COUNTRIES,'catalog_scope'=>$scope,'anex'=>$anex,'andromeda'=>$and,'accepted_total'=>$anex['accepted']+$and['accepted'],'database_writes'=>$writes,'readback_verified'=>true,'supplier_calls'=>0,'before'=>$before,'after'=>$after];
    }catch(Throwable $e){if(!$committed&&$db->inTransaction())$db->rollBack();return ['status'=>$committed?'committed_readback_failed':'failed_rolled_back','operation_id'=>$operation,'database_writes'=>$committed?$writes:0,'readback_verified'=>false,'supplier_calls'=>0,'reason'=>in_array($e->getMessage(),['required_transactional_table_missing','country_contract_changed','hotel_scope_limit','alias_scope_limit','andromeda_concurrent_change'],true)?$e->getMessage():'runtime_failure'];}
}
function fc_main(): array {
    $raw=file_get_contents('php://stdin',false,null,0,4097);$req=json_decode((string)$raw,true,16,JSON_THROW_ON_ERROR);if(($req['operation_id']??'')!==FC_OPERATION||!in_array($req['phase']??'',['apply','receipt'],true))throw new RuntimeException('request_scope');$root=realpath(getcwd());if(!$root||basename($root)!=='anytoour.ru')throw new RuntimeException('root');$config=require $root.'/_preview/search3-anex-candidate/.andromeda-private.php';$private=realpath(dirname($config['catalog_path']));if(!$private||strpos($private,$root.DIRECTORY_SEPARATOR)===0)throw new RuntimeException('private_state');$dir=$private.'/'.FC_OPERATION;
    if($req['phase']==='receipt'){if(is_file($dir.'/result.json'))return json_decode((string)file_get_contents($dir.'/result.json'),true,64,JSON_THROW_ON_ERROR);return ['status'=>is_file($dir.'/reservation.json')?'reserved_or_unknown':'not_started','operation_id'=>FC_OPERATION,'supplier_calls'=>0];}
    if(is_dir($dir)||!mkdir($dir,0700))throw new RuntimeException('operation_already_reserved');fc_write_once($dir.'/reservation.json',['operation_id'=>FC_OPERATION,'state'=>'reserved_before_database','scope'=>FC_COUNTRIES,'supplier_calls'=>0]);$helper=realpath($root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php'));if(!$helper||strpos($helper,$root.DIRECTORY_SEPARATOR)!==0)throw new RuntimeException('db_helper');require_once $helper;$db=v2_data_db();$result=fc_reconcile($db,FC_OPERATION);fc_write_once($dir.'/result.json',$result);return $result;
}
if(!defined('FC_LIBRARY_ONLY')){error_reporting(0);ob_start();try{$out=fc_main();}catch(Throwable $e){$out=['status'=>'failed','operation_id'=>FC_OPERATION,'reason'=>in_array($e->getMessage(),['operation_already_reserved'],true)?$e->getMessage():'runtime_failure','supplier_calls'=>0];}while(ob_get_level())ob_end_clean();echo fc_json($out),"\n";exit(in_array($out['status']??'', ['completed','empty'],true)?0:1);}
