<?php
declare(strict_types=1);

const D81_OP='hotel-match-december81154-samo-native-1971-20260920-v1';
const D81_DELTA_SHA='a6217f102e477f42a69b51cfbb009cf6efc438e343e8865aaea51bd5103e669a';
const D81_RETAINED_SHA='34c0f56d9640c0e29bc59d2c7355dad3728fe421e18db55e528eba013cb58e3b';
const D81_CATALOG_SHA='05a13bd6b8dd9821e630dc7cbe9ef7e55de70405e4eb37fad413bba36592c1ba';
const D81_LOCAL=81154;
const D81_ANEX=35406;
const D81_SAMO=2000073578;
const D81_OPERATOR=5;
const D81_STATE=126;
const D81_TOWNFROM=1;
const D81_CAP=2;
function d81_need(bool $b,string $s):void{if(!$b)throw new RuntimeException($s);}
function d81_raw(string $p,string $b):string{$f=fopen($p,'xb');d81_need(is_resource($f),'exclusive_file');try{d81_need(fwrite($f,$b)===strlen($b)&&fflush($f),'file_write');if(function_exists('fsync'))d81_need(fsync($f),'file_sync');}finally{fclose($f);}d81_need(file_get_contents($p)===$b,'file_readback');return hash('sha256',$b);}
function d81_save(string $p,array $a):string{return d81_raw($p,json_encode($a,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n");}
function d81_load(string $p,?string $sha=null):array{if($sha!==null)d81_need(hash_file('sha256',$p)===$sha,'input_hash');$a=json_decode((string)file_get_contents($p),true,128,JSON_THROW_ON_ERROR);d81_need(is_array($a),'input_shape');return$a;}
function d81_norm(string $s):string{$s=function_exists('mb_strtolower')?mb_strtolower(trim($s),'UTF-8'):strtolower(trim($s));return trim(preg_replace('/[^\p{L}\p{N}]+/u',' ',str_replace('ё','е',$s))??'');}
function d81_rows(PDO $db,string $sql,array $p=[]):array{$s=$db->prepare($sql);$s->execute(array_values($p));$r=$s->fetchAll(PDO::FETCH_ASSOC);d81_need(count($r)<=50000,'db_row_cap');return$r;}
function d81_bridge(array $rows,array $ctx):array{$native=[];$flags=[];$exact=[];
 foreach($rows as$r){if(!is_array($r)||(string)($r['hotelKey']??'')!==(string)D81_SAMO||(string)($r['operatorKey']??'')!==(string)D81_OPERATOR)continue;
  if((string)($r['checkIn']??'')!==date('d.m.Y',strtotime((string)$ctx['departure_date']))||(int)($r['nights']??-1)!==(int)$ctx['nights']||(int)($r['adult']??-1)!==(int)$ctx['adults']||(int)($r['child']??-1)!==(int)$ctx['children_count'])continue;
  $o=is_array($r['original']??null)?$r['original']:[];$n=(string)($o['hotelKey']??'');if(!preg_match('/^[1-9][0-9]*$/D',$n))continue;$native[$n]=true;$flag=array_key_exists('isOperatorHotelKey',$r)&&is_scalar($r['isOperatorHotelKey'])?(string)$r['isOperatorHotelKey']:'missing';$flags[$flag]=true;if($n===(string)D81_ANEX)$exact[]=$r;
 }
 $ns=array_keys($flags);sort($ns,SORT_STRING);$nv=array_keys($native);sort($nv,SORT_NUMERIC);
 $state=$exact===[]?'no_exact_native_anchor':(count($native)!==1?'native_conflict_hold':(($ns===['0']||$ns===[0])?'direct_canonical_native_bridge':'native_namespace_hold'));
 return['state'=>$state,'native_ids_observed'=>$nv,'namespace_flags_observed'=>$ns,'exact_fact_count'=>count($exact),'first_exact_fact'=>$exact[0]??null,'safe_to_write_now'=>false];}
if(($argv[1]??'')==='--self-test'){$c=['departure_date'=>'2026-10-20','nights'=>10,'adults'=>2,'children_count'=>0];$r=['hotelKey'=>D81_SAMO,'operatorKey'=>D81_OPERATOR,'checkIn'=>'20.10.2026','nights'=>10,'adult'=>2,'child'=>0,'isOperatorHotelKey'=>0,'original'=>['hotelKey'=>D81_ANEX]];d81_need(d81_bridge([$r],$c)['state']==='direct_canonical_native_bridge','bridge');$r['original']['hotelKey']=1;d81_need(d81_bridge([$r],$c)['state']==='no_exact_native_anchor','wrong_native');$r['original']['hotelKey']=D81_ANEX;$r['isOperatorHotelKey']=1;d81_need(d81_bridge([$r],$c)['state']==='native_namespace_hold','namespace');echo"MATCH_DECEMBER81154_NATIVE_SELFTEST_OK 3\n";exit(0);}

d81_need(PHP_SAPI==='cli'&&getenv('MATCH_OPERATION_ID')===D81_OP,'operation');$dir=rtrim((string)getenv('HOME'),'/').'/.anytoour-match/operations/'.D81_OP;d81_need(realpath((string)getenv('MATCH_OPERATION_DIR'))===$dir,'op_dir');$sha=(string)getenv('MATCH_SOURCE_SHA');d81_need(preg_match('/^[a-f0-9]{40}$/D',$sha)===1,'source');$res=d81_load($dir.'/reservation.json');d81_need(($res['operation_id']??'')===D81_OP&&($res['source_sha']??'')===$sha&&($res['state']??'')==='reserved_before_access','reservation');
$base=['operation_id'=>D81_OP,'source_sha'=>$sha,'local_hotel_id'=>D81_LOCAL,'anex_native_id'=>D81_ANEX,'samo_hotel_id'=>D81_SAMO,'samo_operator_id'=>D81_OPERATOR,'supplier_calls'=>0,'provider_calls'=>0,'tourvisor_calls'=>0,'direct_anex_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'safe_to_write_now'=>false,'no_replay'=>true];$calls=0;$last=0.0;$db=null;
try{
 d81_save($dir.'/execution-reservation.json',$base+['state'=>'started_before_access']);$delta=d81_load($dir.'/inputs/delta-result.json',D81_DELTA_SHA);$old=d81_load($dir.'/inputs/retained-result.json',D81_RETAINED_SHA);$cat=d81_load($dir.'/inputs/vietnam-catalog.json',D81_CATALOG_SHA);
 $targets=array_values(array_filter($delta['dossiers']??[],static fn($d)=>is_array($d)&&($d['state']??'')==='new_seed_missing_samo_edge_needs_evidence_dedupe'));d81_need(count($targets)===1&&(int)$targets[0]['local_hotel_id']===D81_LOCAL,'delta_target');$t=$targets[0];d81_need(in_array(D81_ANEX,array_map('intval',$t['anex_native_ids']??[]),true),'delta_native');$ctx=$t['preferred_context']??null;d81_need(is_array($ctx)&&(int)$ctx['departure_id']===1&&(int)$ctx['country_id']===16&&(string)$ctx['departure_date']==='2026-10-20'&&(int)$ctx['nights']===10&&(int)$ctx['adults']===2&&(int)$ctx['children_count']===0&&(string)$ctx['child_ages_signature']===''&&(int)$ctx['operator_id']===13&&(string)$ctx['source']==='user_search','delta_context');
 $hotels=array_values(array_filter($cat['HOTELS']??[],static fn($h)=>is_array($h)&&(int)($h['id']??0)===D81_SAMO));d81_need(count($hotels)===1,'catalog_candidate');$ch=$hotels[0];d81_need((int)($ch['stateKey']??0)===D81_STATE&&d81_norm((string)($ch['state']??''))===d81_norm('Вьетнам')&&d81_norm((string)($ch['townLName']??''))===d81_norm('Nha Trang')&&(string)($ch['star']??'')==='4'&&str_contains(d81_norm((string)($ch['name']??'')),'december'),'catalog_geo_name');$ops=array_values(array_filter($cat['OPERATORS']??[],static fn($o)=>is_array($o)&&(int)($o['id']??0)===D81_OPERATOR));d81_need(count($ops)===1&&d81_norm((string)($ops[0]['name']??''))===d81_norm('Anex Tour'),'operator_dictionary');
 $bindings=[];foreach($old['dossiers']??[]as$d)if(is_array($d)&&(int)($d['departure_id']??0)===1&&isset($d['samo_townfrom_id']))$bindings[(int)$d['samo_townfrom_id']]=true;d81_need(array_keys($bindings)===[D81_TOWNFROM],'townfrom_binding');
 require_once __DIR__.'/hotel_match_anex_effective_coverage.php';require_once dirname(__DIR__,2).'/app/integrations/andromeda-transport.php';require_once dirname(__DIR__,2).'/app/integrations/andromeda-client.php';$root=realpath(getcwd());d81_need(is_string($root)&&basename($root)==='anytoour.ru','root');require_once(is_file($root.'/data/db-v1.php')?$root.'/data/db-v1.php':$root.'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');$coverage=AnyTourMatchAnexEffectiveCoverage::fromPdo($db);$local=d81_rows($db,'SELECT * FROM catalog_hotels WHERE id=?',[D81_LOCAL]);$targetIds=d81_rows($db,'SELECT * FROM andromeda_hotel_identities WHERE local_hotel_id=? ORDER BY supplier_namespace,external_hotel_id',[D81_LOCAL]);$sourceIds=d81_rows($db,"SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=? ORDER BY local_hotel_id",[(string)D81_SAMO]);$dep=d81_rows($db,'SELECT id,name,is_active FROM catalog_departures WHERE id=1');$currentNative=array_map('intval',array_keys($coverage['by_local'][D81_LOCAL]??[]));sort($currentNative,SORT_NUMERIC);$pre=['local'=>$local,'target_identity_rows'=>$targetIds,'source_identity_rows'=>$sourceIds,'departure'=>$dep,'current_anex_native_ids'=>$currentNative,'catalog_raw'=>$ch,'context'=>$ctx];d81_save($dir.'/current-preflight.json',$pre+['safe_to_write_now'=>false]);$eligible=count($local)===1&&(int)$local[0]['is_active']===1&&(int)$local[0]['country_id']===16&&$targetIds===[]&&$sourceIds===[]&&in_array(D81_ANEX,$currentNative,true)&&count($dep)===1&&(int)$dep[0]['is_active']===1&&d81_norm((string)$dep[0]['name'])===d81_norm('Москва');$db->rollBack();$db=null;
 if(!$eligible){$result=$base+['state'=>'completed_current_hold_no_http','preflight'=>$pre,'provider_calls'=>0,'supplier_calls'=>0,'safe_to_write_now'=>false];}
 else{
  $lines=file('php://stdin',FILE_IGNORE_NEW_LINES);$u=trim((string)($lines[0]??''));$p=trim((string)($lines[1]??''));unset($lines);d81_need($u!==''&&$p!=='','credentials');$transport=new AnyTourAndromedaTransport(true,false);$wrapped=function(string $url,array $opts=[])use($transport,&$calls,&$last,$dir):array{parse_str((string)parse_url($url,PHP_URL_QUERY),$q);$action=(string)($q['action']??'');d81_need(in_array($action,['login','price'],true),'action');d81_need($calls<D81_CAP,'provider_cap');$wait=1.05-(microtime(true)-$last);if($wait>0)usleep((int)ceil($wait*1000000));$seq=++$calls;$stem=sprintf('%03d-%s',$seq,$action);$params=$q;foreach(['sid','username','password','nonce','created']as$k)unset($params[$k]);d81_save($dir.'/call-'.$stem.'-reservation.json',['operation_id'=>D81_OP,'seq'=>$seq,'action'=>$action,'params'=>$params,'state'=>'reserved_unknown_before_http','at_utc'=>gmdate('c')]);$last=microtime(true);$reply=$transport($url,$opts);if($action!=='login')d81_save($dir.'/raw-http-'.$stem.'.json',$reply);d81_save($dir.'/call-'.$stem.'-receipt.json',['seq'=>$seq,'action'=>$action,'status'=>$reply['status'],'body_sha256'=>hash('sha256',(string)$reply['body']),'state'=>'http_response_saved']);return$reply;};$client=new AnyTourAndromedaClient($wrapped,true);$client->login($u,$p);unset($u,$p);$params=['TOWNFROMINC'=>D81_TOWNFROM,'STATEINC'=>D81_STATE,'CHECKIN_BEG'=>'20261020','CHECKIN_END'=>'20261020','NIGHTS_FROM'=>10,'NIGHTS_TILL'=>10,'ADULT'=>2,'CHILD'=>0,'CURRENCYINC'=>643,'OPERATORS'=>(string)D81_OPERATOR,'HOTELS'=>(string)D81_SAMO,'PACKETTYPE'=>0,'PAGE'=>1];$price=$client->price($params);d81_need($calls===2,'exact_call_count');$bridge=d81_bridge($price['PRICES'],$ctx);$result=$base+['state'=>'completed_evidence','provider_calls'=>$calls,'supplier_calls'=>$calls,'query_params'=>$params,'catalog_candidate'=>$ch,'bridge'=>$bridge,'pages_count'=>$price['PAGES_COUNT'],'price_row_count'=>count($price['PRICES']),'safe_to_write_now'=>false];
 }
}catch(Throwable$e){if($db instanceof PDO&&$db->inTransaction())$db->rollBack();$reason=preg_match('/^[A-Za-z0-9_]+$/D',$e->getMessage())?$e->getMessage():'runtime_error';$result=$base+['state'=>'failed_no_replay','provider_calls'=>$calls,'supplier_calls'=>$calls,'reason'=>$reason,'error_class'=>get_class($e),'safe_to_write_now'=>false];}
$hash=d81_save($dir.'/result.json',$result);d81_save($dir.'/receipt.json',['operation_id'=>D81_OP,'source_sha'=>$sha,'state'=>$result['state'],'result_sha256'=>$hash,'readback_verified'=>hash_file('sha256',$dir.'/result.json')===$hash,'provider_calls'=>$result['provider_calls']??$calls,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true]);echo json_encode(['state'=>$result['state'],'provider_calls'=>$result['provider_calls']??$calls,'bridge_state'=>$result['bridge']['state']??null,'result_sha256'=>$hash],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)."\n";exit(str_starts_with((string)$result['state'],'completed_')?0:1);
