<?php
declare(strict_types=1);
/* MATCH-only server-CURRENT promotion. No supplier/Tourvisor/network access. */
const OPB_OP='hotel-match-operator-pending-anex-bridge-1971-20260915-v1';
const OPB_POLICY='owner_exact_and_strong_20260908';
const OPB_NS='operator_5';
function opb_json(array $x):string{return json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";}
function opb_write(string $file,array $x):string{$raw=opb_json($x);$f=@fopen($file,'x+b');if(!$f)throw new RuntimeException('exclusive_file');try{if(fwrite($f,$raw)!==strlen($raw)||!fflush($f))throw new RuntimeException('file_write');if(function_exists('fsync')&&!fsync($f))throw new RuntimeException('file_sync');rewind($f);if(stream_get_contents($f)!==$raw)throw new RuntimeException('file_readback');}finally{fclose($f);}return hash('sha256',$raw);}
function opb_query(PDO $db,string $sql,array $args=[]):array{$q=$db->prepare($sql);$q->execute($args);return $q->fetchAll(PDO::FETCH_ASSOC);}
function opb_tokens(string $s):array{$s=mb_strtolower($s,'UTF-8');$s=strtr($s,['ё'=>'е','é'=>'e','è'=>'e','ê'=>'e','á'=>'a','à'=>'a','ä'=>'a','â'=>'a','ö'=>'o','ô'=>'o','ü'=>'u','ú'=>'u','ç'=>'c','ş'=>'s','ğ'=>'g','ı'=>'i']);$s=preg_replace('/\s*\(\s*(?:ex|ех)\.?\s+[^)]*\)\s*$/u','',$s);preg_match_all('/[\p{L}\p{N}]+/u',$s,$m);$drop=['hotel'=>1,'hotels'=>1,'resort'=>1,'resorts'=>1,'spa'=>1,'the'=>1,'and'=>1,'by'=>1,'club'=>1,'suite'=>1,'suites'=>1,'apart'=>1,'apartment'=>1,'apartments'=>1,'отель'=>1,'спа'=>1];$out=[];foreach($m[0]??[] as $t)if(!isset($drop[$t]))$out[$t]=true;return array_keys($out);}
function opb_name_guard(array $names,string $local):bool{$lt=opb_tokens($local);if(!$lt)return false;$qual=['annex','beach','garden','gardens','north','south','pool','posh','aquamarine'];$lq=array_values(array_intersect($lt,$qual));sort($lq);$checked=0;foreach($names as $name){$name=trim((string)$name);if($name==='')continue;$t=opb_tokens($name);if(!$t)continue;$q=array_values(array_intersect($t,$qual));sort($q);if($q!==$lq||!array_intersect($t,$lt))return false;$checked++;}return $checked>0;}
function opb_distance(array $src,array $hotel):?float{$a=$src['latitude']??$src['lat']??null;$b=$src['longitude']??$src['lng']??$src['lon']??null;$c=$hotel['latitude']??null;$d=$hotel['longitude']??null;foreach([$a,$b,$c,$d] as $v)if(!is_numeric($v))return null;$a=(float)$a;$b=(float)$b;$c=(float)$c;$d=(float)$d;if(abs($a)>90||abs($c)>90||abs($b)>180||abs($d)>180||($a==0&&$b==0)||($c==0&&$d==0))return null;[$a,$b,$c,$d]=array_map('deg2rad',[$a,$b,$c,$d]);return 6371*2*asin(min(1,sqrt(sin(($c-$a)/2)**2+cos($a)*cos($c)*sin(($d-$b)/2)**2)));}
function opb_bridge(array $typed,string $native):array{
    if(($typed['schema']??'')!=='operator-original-price-bridge/1'||(string)($typed['source']['operator_key']??'')!=='5'||strcasecmp((string)($typed['source']['id']??''),$native)!==0)return ['ok'=>false,'reason'=>'typed_evidence_contract'];
    $ids=[];$names=[];$countries=[];
    foreach($typed['provider_bridges']??[] as $f){if(!is_array($f)||(string)($f['operator_key']??'')!=='5'||strcasecmp((string)($f['native_hotel_id']??''),$native)!==0||($f['action']??'')!=='price'||($f['is_operator_hotel_key']??true)!==false)return ['ok'=>false,'reason'=>'provider_bridge_contract'];$id=(string)($f['andromeda_hotel_id']??'');if(!preg_match('/^[1-9][0-9]{0,19}$/D',$id))return ['ok'=>false,'reason'=>'andromeda_id_contract'];$ids[$id]=true;$countries[(int)($f['country_id']??0)]=true;$names[]=(string)($f['hotel_name']??'');$names[]=(string)($f['original_name']??'');}
    if(!$ids||count($countries)!==1||!isset($countries[1])&&!isset($countries[4]))return ['ok'=>false,'reason'=>'bridge_country_or_empty'];
    return ['ok'=>true,'andromeda_ids'=>array_keys($ids),'country_id'=>(int)array_key_first($countries),'names'=>$names];
}
function opb_authority(PDO $db,int $aid,bool $hasReview):array{
    if($hasReview&&opb_query($db,'SELECT anex_hotel_id FROM anex_review_state WHERE anex_hotel_id=? FOR UPDATE',[$aid]))return ['ok'=>false,'reason'=>'anex_review_protected'];
    $dec=opb_query($db,'SELECT decision_status,catalog_hotel_id FROM anex_hotel_decisions WHERE anex_hotel_id=? FOR UPDATE',[$aid]);
    if($dec){if(count($dec)!==1||$dec[0]['decision_status']!=='accepted'||$dec[0]['catalog_hotel_id']===null)return ['ok'=>false,'reason'=>'anex_manual_protected'];$target=(int)$dec[0]['catalog_hotel_id'];if(opb_query($db,'SELECT anex_hotel_id FROM anex_review_pair_exclusions WHERE anex_hotel_id=? AND catalog_hotel_id=? FOR UPDATE',[$aid,$target]))return ['ok'=>false,'reason'=>'anex_pair_excluded'];return ['ok'=>true,'target'=>$target,'authority'=>'accepted_manual'];}
    $maps=opb_query($db,"SELECT catalog_hotel_id FROM anex_hotel_search_mappings WHERE anex_hotel_id=? AND enabled=1 AND scope='preview' AND approval_policy=? ORDER BY catalog_hotel_id FOR UPDATE",[$aid,OPB_POLICY]);$targets=[];foreach($maps as $m){$target=(int)$m['catalog_hotel_id'];if(opb_query($db,'SELECT anex_hotel_id FROM anex_review_pair_exclusions WHERE anex_hotel_id=? AND catalog_hotel_id=? FOR UPDATE',[$aid,$target]))continue;$targets[$target]=true;}
    if(count($targets)!==1)return ['ok'=>false,'reason'=>count($targets)>1?'anex_target_conflict':'anex_no_current_authority'];return ['ok'=>true,'target'=>(int)array_key_first($targets),'authority'=>'accepted_mapping'];
}
function opb_coverage(PDO $db):array{$a=[];foreach(opb_query($db,"SELECT m.catalog_hotel_id id FROM anex_hotel_search_mappings m LEFT JOIN anex_hotel_decisions d ON d.anex_hotel_id=m.anex_hotel_id WHERE m.enabled=1 AND m.scope='preview' AND m.approval_policy=? AND d.anex_hotel_id IS NULL AND NOT EXISTS(SELECT 1 FROM anex_review_pair_exclusions x WHERE x.anex_hotel_id=m.anex_hotel_id AND x.catalog_hotel_id=m.catalog_hotel_id)",[OPB_POLICY]) as $r)$a[(int)$r['id']]=true;foreach(opb_query($db,"SELECT d.catalog_hotel_id id FROM anex_hotel_decisions d WHERE d.decision_status='accepted' AND d.catalog_hotel_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM anex_review_pair_exclusions x WHERE x.anex_hotel_id=d.anex_hotel_id AND x.catalog_hotel_id=d.catalog_hotel_id)") as $r)$a[(int)$r['id']]=true;$d=[];foreach(opb_query($db,"SELECT DISTINCT local_hotel_id id FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IS NOT NULL") as $r)$d[(int)$r['id']]=true;return ['anex_unique_local'=>count($a),'andromeda_unique_local'=>count($d),'all_three'=>count(array_intersect_key($a,$d))];}
function opb_apply(string $dir,string $sourceSha):void{
    if(!is_file($dir.'/reservation.json'))throw new RuntimeException('reservation_missing');$res=json_decode(file_get_contents($dir.'/reservation.json'),true,32,JSON_THROW_ON_ERROR);if(($res['operation_id']??'')!==OPB_OP||($res['source_sha']??'')!==$sourceSha||($res['state']??'')!=='reserved_before_db_access')throw new RuntimeException('reservation_contract');
    $root=realpath(getcwd());if(!$root||basename($root)!=='anytoour.ru')throw new RuntimeException('root_guard');$db=null;$committed=false;$phase='bootstrap';
    try{require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET SESSION innodb_lock_wait_timeout=30');$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->beginTransaction();$phase='current_read';
        $need=['andromeda_hotel_identities','catalog_hotels','anex_hotel_search_mappings','anex_hotel_decisions','anex_review_pair_exclusions'];$eng=opb_query($db,'SELECT TABLE_NAME,ENGINE FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME IN ('.implode(',',array_fill(0,count($need),'?')).')',$need);$eng=array_column($eng,'ENGINE','TABLE_NAME');foreach($need as $t)if(strtoupper($eng[$t]??'')!=='INNODB')throw new RuntimeException('transactional_table_required');$opt=opb_query($db,"SELECT ENGINE FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='anex_review_state'");$hasReview=false;if($opt){if(strtoupper($opt[0]['ENGINE'])!=='INNODB')throw new RuntimeException('review_engine');$hasReview=(bool)opb_query($db,"SELECT COLUMN_NAME FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='anex_review_state' AND COLUMN_NAME='anex_hotel_id'");}
        $before=opb_coverage($db);$typed=opb_query($db,"SELECT external_hotel_id,evidence_sha256,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace=? AND decision_status='pending' AND local_hotel_id IS NULL ORDER BY external_hotel_id FOR UPDATE",[OPB_NS]);$holds=[];$candidateByAnd=[];$typedPlan=[];
        foreach($typed as $tr){$native=(string)$tr['external_hotel_id'];if(!preg_match('/^[1-9][0-9]{0,9}$/D',$native)){$holds[]=['native'=>$native,'reason'=>'invalid_anex_key'];continue;}$bridge=opb_bridge(json_decode((string)$tr['evidence_json'],true)?:[],$native);if(!$bridge['ok']){$holds[]=['native'=>$native,'reason'=>$bridge['reason']];continue;}$auth=opb_authority($db,(int)$native,$hasReview);if(!$auth['ok']){$holds[]=['native'=>$native,'reason'=>$auth['reason'],'andromeda_ids'=>$bridge['andromeda_ids']];continue;}$hotelRows=opb_query($db,'SELECT id,country_id,name,latitude,longitude,is_active FROM catalog_hotels WHERE id=? FOR UPDATE',[$auth['target']]);if(count($hotelRows)!==1||(int)$hotelRows[0]['is_active']!==1||(int)$hotelRows[0]['country_id']!==$bridge['country_id']){$holds[]=['native'=>$native,'reason'=>'target_country_or_activity_conflict'];continue;}$hotel=$hotelRows[0];if(!opb_name_guard($bridge['names'],(string)$hotel['name'])){$holds[]=['native'=>$native,'reason'=>'operator_name_or_qualifier_conflict'];continue;}$safeIds=[];foreach($bridge['andromeda_ids'] as $and){$rows=opb_query($db,"SELECT external_hotel_id,evidence_sha256,evidence_json,decision_status,local_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=? FOR UPDATE",[$and]);if(count($rows)!==1){$holds[]=['native'=>$native,'andromeda_id'=>$and,'reason'=>'andromeda_identity_missing'];continue;}$ar=$rows[0];if($ar['decision_status']!=='pending'||$ar['local_hotel_id']!==null){$holds[]=['native'=>$native,'andromeda_id'=>$and,'reason'=>'andromeda_current_state_protected'];continue;}$ev=json_decode((string)$ar['evidence_json'],true)?:[];$src=is_array($ev['source']??null)?$ev['source']:[];$geo=is_array($ev['geography']??null)?$ev['geography']:[];if(isset($src['stateKey'])&&(int)$src['stateKey']!==[1=>3,4=>5][$bridge['country_id']]){$holds[]=['native'=>$native,'andromeda_id'=>$and,'reason'=>'andromeda_country_conflict'];continue;}$distances=[];foreach([$src,$geo] as $g){$d=opb_distance($g,$hotel);if($d!==null)$distances[]=$d;}if($distances&&max($distances)>5){$holds[]=['native'=>$native,'andromeda_id'=>$and,'reason'=>'coordinate_conflict_gt5km'];continue;}$sourceNames=[(string)($src['name']??''),(string)($src['lName']??'')];if(array_filter($sourceNames,'strlen')&&!opb_name_guard($sourceNames,(string)$hotel['name'])){$holds[]=['native'=>$native,'andromeda_id'=>$and,'reason'=>'andromeda_name_or_qualifier_conflict'];continue;}$entry=['andromeda_id'=>$and,'target'=>(int)$auth['target'],'country_id'=>$bridge['country_id'],'native'=>$native,'authority'=>$auth['authority'],'old_sha'=>$ar['evidence_sha256'],'prior'=>$ev,'typed_old_sha'=>$tr['evidence_sha256']];if(isset($candidateByAnd[$and])&&$candidateByAnd[$and]['target']!==$entry['target']){$candidateByAnd[$and]['conflict']=true;$entry['conflict']=true;}$candidateByAnd[$and]=$entry;$safeIds[]=$and;}
            if($safeIds)$typedPlan[$native]=['target'=>(int)$auth['target'],'country_id'=>$bridge['country_id'],'andromeda_ids'=>$safeIds,'authority'=>$auth['authority'],'old_sha'=>$tr['evidence_sha256'],'prior'=>json_decode((string)$tr['evidence_json'],true)?:[]];
        }
        foreach($candidateByAnd as $and=>$c)if($c['conflict']??false){unset($candidateByAnd[$and]);$holds[]=['andromeda_id'=>$and,'reason'=>'cross_native_target_conflict'];}
        foreach($typedPlan as $native=>$tp){$kept=array_values(array_filter($tp['andromeda_ids'],fn($and)=>isset($candidateByAnd[$and])&&$candidateByAnd[$and]['target']===$tp['target']));if(!$kept)unset($typedPlan[$native]);else$typedPlan[$native]['andromeda_ids']=$kept;}
        $phase='promotion';$andWritten=[];$typedWritten=[];$upAnd=$db->prepare("UPDATE andromeda_hotel_identities SET local_hotel_id=?,decision_status='accepted',evidence_sha256=?,evidence_json=? WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=? AND decision_status='pending' AND local_hotel_id IS NULL AND evidence_sha256 <=> ?");foreach($candidateByAnd as $and=>$c){$promotion=['operation_id'=>OPB_OP,'rule'=>'price_original_exact_anex_native_current_authority','native_anex_hotel_id'=>$c['native'],'target_local_hotel_id'=>$c['target'],'authority'=>$c['authority'],'server_current'=>true,'coordinate_conflict_gt5km_blocked'=>true];$json=opb_json(['prior_evidence'=>$c['prior'],'promotion'=>$promotion]);$sha=hash('sha256',$json);$upAnd->execute([$c['target'],$sha,$json,$and,$c['old_sha']]);if($upAnd->rowCount()!==1)throw new RuntimeException('andromeda_concurrency_guard');$andWritten[$and]=['target'=>$c['target'],'sha'=>$sha,'native'=>$c['native']];}
        $upTyped=$db->prepare("UPDATE andromeda_hotel_identities SET local_hotel_id=?,decision_status='accepted',evidence_sha256=?,evidence_json=? WHERE supplier_namespace=? AND external_hotel_id=? AND decision_status='pending' AND local_hotel_id IS NULL AND evidence_sha256 <=> ?");foreach($typedPlan as $native=>$tp){$json=opb_json(['prior_evidence'=>$tp['prior'],'promotion'=>['operation_id'=>OPB_OP,'rule'=>'native_identity_promoted_with_exact_current_anex_authority','target_local_hotel_id'=>$tp['target'],'authority'=>$tp['authority'],'andromeda_ids'=>$tp['andromeda_ids'],'server_current'=>true]]);$sha=hash('sha256',$json);$upTyped->execute([$tp['target'],$sha,$json,OPB_NS,$native,$tp['old_sha']]);if($upTyped->rowCount()!==1)throw new RuntimeException('typed_concurrency_guard');$typedWritten[$native]=['target'=>$tp['target'],'sha'=>$sha];}
        $db->commit();$committed=true;$phase='post_commit_readback';$andRead=[];foreach($andWritten as $and=>$w){$r=opb_query($db,"SELECT local_hotel_id,decision_status,evidence_sha256 FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=?",[$and]);if(count($r)!==1||(int)$r[0]['local_hotel_id']!==$w['target']||$r[0]['decision_status']!=='accepted'||!hash_equals($w['sha'],(string)$r[0]['evidence_sha256']))throw new RuntimeException('andromeda_readback');$andRead[]=['andromeda_hotel_id'=>$and,'local_hotel_id'=>$w['target'],'native_anex_hotel_id'=>$w['native'],'evidence_sha256'=>$w['sha']];}$typedRead=[];foreach($typedWritten as $native=>$w){$r=opb_query($db,"SELECT local_hotel_id,decision_status,evidence_sha256 FROM andromeda_hotel_identities WHERE supplier_namespace=? AND external_hotel_id=?",[OPB_NS,$native]);if(count($r)!==1||(int)$r[0]['local_hotel_id']!==$w['target']||$r[0]['decision_status']!=='accepted'||!hash_equals($w['sha'],(string)$r[0]['evidence_sha256']))throw new RuntimeException('typed_readback');$typedRead[]=['native_anex_hotel_id'=>$native,'local_hotel_id'=>$w['target'],'evidence_sha256'=>$w['sha']];}$after=opb_coverage($db);$result=['operation_id'=>OPB_OP,'source_sha'=>$sourceSha,'state'=>'completed_committed','pending_operator5_examined'=>count($typed),'andromeda_promotions'=>count($andWritten),'typed_operator5_promotions'=>count($typedWritten),'holds'=>$holds,'andromeda_post_commit_readback'=>$andRead,'typed_post_commit_readback'=>$typedRead,'coverage_before'=>$before,'coverage_after'=>$after,'supplier_calls'=>0,'tourvisor_calls'=>0,'all_calls'=>0,'booking_calls'=>0,'no_replay'=>true];$hash=opb_write($dir.'/result.json',$result);opb_write($dir.'/receipt.json',['operation_id'=>OPB_OP,'source_sha'=>$sourceSha,'state'=>'completed_committed','result_sha256'=>$hash,'readback_verified'=>true,'post_commit_andromeda_rows'=>count($andRead),'post_commit_typed_rows'=>count($typedRead),'supplier_calls'=>0,'no_replay'=>true]);echo json_encode(['andromeda_promotions'=>count($andRead),'typed_promotions'=>count($typedRead),'holds'=>count($holds),'coverage_before'=>$before,'coverage_after'=>$after],JSON_UNESCAPED_SLASHES)."\n";
    }catch(Throwable $e){if(!$committed&&$db instanceof PDO&&$db->inTransaction())$db->rollBack();$state=$committed?'unknown_after_commit':'failed_before_commit';$failure=['operation_id'=>OPB_OP,'source_sha'=>$sourceSha,'state'=>$state,'phase'=>$phase,'reason'=>preg_match('/^[a-z0-9_:.-]+$/Di',$e->getMessage())?$e->getMessage():'sanitized_error','no_replay'=>true];if($committed)opb_write($dir.'/unknown.json',$failure);else{$hash=opb_write($dir.'/result.json',$failure);opb_write($dir.'/receipt.json',['operation_id'=>OPB_OP,'source_sha'=>$sourceSha,'state'=>$state,'result_sha256'=>$hash,'readback_verified'=>true,'database_writes'=>0,'supplier_calls'=>0,'no_replay'=>true]);}fwrite(STDERR,$state.':'.$phase."\n");exit(2);}
}
if(!defined('OPB_LIBRARY_ONLY')){$sha=getenv('MATCH_SOURCE_SHA')?:'';if((getenv('MATCH_OPERATION_ID')?:'')!==OPB_OP||!preg_match('/^[0-9a-f]{40}$/D',$sha))throw new RuntimeException('operation_environment');opb_apply(getenv('HOME').'/.anytoour-match/operations/'.OPB_OP,$sha);}