<?php
declare(strict_types=1);
const R35_OP='hotel-match-live-samo-missing-direct-anex-router-1971-20260925-v35';
const R35_POLICY='owner_exact_and_strong_20260908';
function r35_req(bool $ok,string $why):void{if(!$ok)throw new RuntimeException($why);}
function r35_q(PDO $db,string $sql,array $args=[]):array{$q=$db->prepare($sql);$q->execute(array_values($args));return $q->fetchAll(PDO::FETCH_ASSOC)?:[];}
function r35_json(string $path,array $v):string{$raw=json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";$f=fopen($path,'x+b');r35_req(is_resource($f),'open');r35_req(fwrite($f,$raw)===strlen($raw),'write');fflush($f);if(function_exists('fsync'))fsync($f);rewind($f);r35_req(stream_get_contents($f)===$raw,'readback');fclose($f);return hash('sha256',$raw);}
function r35_chunks(array $ids,int $n=500):array{$ids=array_values(array_unique(array_map('intval',$ids)));sort($ids,SORT_NUMERIC);return array_chunk($ids,$n);}
function r35_accepted_anex(PDO $db,array $ids):array{
  $out=[];foreach(r35_chunks($ids) as $chunk){if(!$chunk)continue;$ph=implode(',',array_fill(0,count($chunk),'?'));
    $maps=r35_q($db,"SELECT m.anex_hotel_id,m.catalog_hotel_id FROM anex_hotel_search_mappings m LEFT JOIN anex_hotel_decisions d ON d.anex_hotel_id=m.anex_hotel_id WHERE m.catalog_hotel_id IN ($ph) AND m.enabled=1 AND m.scope='preview' AND m.approval_policy=? AND d.anex_hotel_id IS NULL AND NOT EXISTS(SELECT 1 FROM anex_review_pair_exclusions x WHERE x.anex_hotel_id=m.anex_hotel_id AND x.catalog_hotel_id=m.catalog_hotel_id)",array_merge($chunk,[R35_POLICY]));
    foreach($maps as $r)$out[(int)$r['catalog_hotel_id']][]=(int)$r['anex_hotel_id'];
    $man=r35_q($db,"SELECT d.anex_hotel_id,d.catalog_hotel_id FROM anex_hotel_decisions d WHERE d.catalog_hotel_id IN ($ph) AND d.decision_status='accepted' AND NOT EXISTS(SELECT 1 FROM anex_review_pair_exclusions x WHERE x.anex_hotel_id=d.anex_hotel_id AND x.catalog_hotel_id=d.catalog_hotel_id)",$chunk);
    foreach($man as $r)$out[(int)$r['catalog_hotel_id']][]=(int)$r['anex_hotel_id'];
  }return$out;
}
function main():void{
  r35_req(PHP_SAPI==='cli'&&(string)getenv('MATCH_OPERATION_ID')===R35_OP,'operation');$sha=(string)getenv('MATCH_SOURCE_SHA');r35_req(preg_match('/^[0-9a-f]{40}$/D',$sha)===1,'sha');$input=(string)getenv('MATCH_INPUT_PATH');r35_req(is_file($input),'input');$in=json_decode((string)file_get_contents($input),true,64,JSON_THROW_ON_ERROR);r35_req(($in['operation']??'')==='hotel-match-business-live30-frontier-plan-1971-20260925-v33'&&($in['state']??'')==='completed_read_only_business_live30_frontier_plan','input_shape');
  r35_req(($in['target_set_sha256']??'')==='5001297e29a920acc2d565e45fec0e4d0a5b2244e0ba60a860941be882ad1c77','input_target_sha');
  $rows=array_values(array_filter($in['rows']??[],fn($x)=>is_array($x)&&($x['bucket']??'')==='tv_samo_missing_anex'));
  r35_req(count($rows)===777,'rows');$ids=array_map(fn($x)=>(int)$x['local_hotel_id'],$rows);r35_req(count(array_unique($ids))===777,'unique_ids');
  $dir=rtrim((string)getenv('HOME'),'/').'/.anytoour-match/operations/'.R35_OP;$res=json_decode((string)file_get_contents($dir.'/reservation.json'),true,32,JSON_THROW_ON_ERROR);r35_req(($res['operation_id']??'')===R35_OP&&($res['source_sha']??'')===$sha,'reservation');
  $root=realpath(getcwd());r35_req(is_string($root)&&basename($root)==='anytoour.ru','root');$dbp=$root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');require_once $dbp;$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$out=['operation_id'=>R35_OP,'source_sha'=>$sha,'state'=>'failed_no_replay','supplier_calls'=>0,'tourvisor_calls'=>0,'samo_calls'=>0,'andromeda_calls'=>0,'direct_anex_calls'=>0,'database_writes'=>0,'mapping_writes'=>0];
  try{
    $db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');$accepted=r35_accepted_anex($db,$ids);
    $samo=[];foreach(r35_chunks($ids) as $chunk){$ph=implode(',',array_fill(0,count($chunk),'?'));foreach(r35_q($db,"SELECT local_hotel_id,external_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IN ($ph)",$chunk) as $r)$samo[(int)$r['local_hotel_id']][]=(string)$r['external_hotel_id'];}
    $today=(new DateTimeImmutable('now',new DateTimeZone('Europe/Moscow')))->format('Y-m-d');$obs=[];foreach(r35_chunks($ids) as $chunk){$ph=implode(',',array_fill(0,count($chunk),'?'));$args=array_merge([$today],$chunk);$q=r35_q($db,"SELECT hotel_id,country_id,region_id,subregion_id,departure_id,departure_date,nights,adults,children_count,child_ages_signature,search_id,tour_id,operator_id,observed_at FROM tour_price_observations WHERE source='user_search' AND departure_date>=? AND hotel_id IN ($ph) ORDER BY hotel_id,observed_at DESC",$args);foreach($q as $r){$h=(int)$r['hotel_id'];if(!isset($obs[$h]))$obs[$h]=$r;}}
    $routed=[];$noFuture=[];$skippedAccepted=[];$skippedSamo=[];$groups=[];
    foreach($rows as $src){$h=(int)$src['local_hotel_id'];if(isset($accepted[$h])){$skippedAccepted[]=['tv_hotel_id'=>$h,'anex_ids'=>array_values(array_unique($accepted[$h]))];continue;}if(empty($samo[$h])){$skippedSamo[]=$h;continue;}if(!isset($obs[$h])){$noFuture[]=['tv_hotel_id'=>$h,'hotel_name'=>(string)($src['catalog_hotel']['name']??''),'samo_external_ids'=>$samo[$h]];continue;}$o=$obs[$h];$ctx=['tv_hotel_id'=>$h,'hotel_name'=>(string)($src['catalog_hotel']['name']??''),'samo_external_ids'=>$samo[$h],'departure_id'=>(int)$o['departure_id'],'country_id'=>(int)$o['country_id'],'region_id'=>$o['region_id']===null?null:(int)$o['region_id'],'subregion_id'=>$o['subregion_id']===null?null:(int)$o['subregion_id'],'departure_date'=>(string)$o['departure_date'],'nights'=>(int)$o['nights'],'adults'=>(int)$o['adults'],'children_count'=>(int)$o['children_count'],'child_ages_signature'=>(string)$o['child_ages_signature'],'search_id'=>(int)$o['search_id'],'tour_id'=>$o['tour_id']===null?null:(string)$o['tour_id'],'observed_operator_id'=>(int)$o['operator_id'],'observed_at'=>(string)$o['observed_at'],'safe_to_write_now'=>false];$routed[]=$ctx;$key=implode('|',[$ctx['departure_id'],$ctx['country_id'],$ctx['departure_date'],$ctx['nights'],$ctx['adults'],$ctx['children_count'],$ctx['child_ages_signature']]);$groups[$key][]=$h;}
    $batchPlan=[];ksort($groups,SORT_NATURAL);foreach($groups as $key=>$gids){sort($gids,SORT_NUMERIC);foreach(array_chunk($gids,30) as $i=>$part)$batchPlan[]=['context_key'=>$key,'batch_index'=>$i+1,'hotel_ids'=>$part,'hotel_count'=>count($part),'safe_to_write_now'=>false];}
    $db->rollBack();$out['state']='completed_read_only';$out['read_at_utc']=gmdate('c');$out['today_moscow']=$today;$out['input_count']=777;$out['current_accepted_anex_skip_count']=count($skippedAccepted);$out['current_samo_missing_skip_count']=count($skippedSamo);$out['routed_future_context_count']=count($routed);$out['no_future_context_count']=count($noFuture);$out['context_group_count']=count($groups);$out['batch_count']=count($batchPlan);$out['routed']=$routed;$out['no_future_context']=$noFuture;$out['skipped_current_accepted_anex']=$skippedAccepted;$out['skipped_current_samo_missing']=$skippedSamo;$out['batch_plan']=$batchPlan;
  }catch(Throwable $e){if($db->inTransaction())$db->rollBack();$out['reason']='read_failed';$out['error_class']=get_class($e);}
  $d=r35_json($dir.'/result.json',$out);r35_json($dir.'/receipt.json',['operation_id'=>R35_OP,'source_sha'=>$sha,'state'=>$out['state'],'result_sha256'=>$d,'readback_verified'=>true,'supplier_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true]);if($out['state']!=='completed_read_only')exit(2);
}
function selftest():void{r35_req(count(r35_chunks([3,1,1,2],2))===2,'chunks');echo "LIVE_SAMO_MISSING_DIRECT_ANEX_ROUTER_V35_OK\n";}
if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__){if(($argv[1]??'')==='--self-test'){selftest();exit(0);}main();}
