<?php
declare(strict_types=1);
error_reporting(0);ob_start();
const OP='hotel-match-post539-current-census-1971-20260912-v1';
function cc($v):?string{$s=mb_strtolower(trim((string)$v),'UTF-8');$s=strtr($s,['ё'=>'е','türkiye'=>'turkiye']);$s=preg_replace('/[\s_-]+/u',' ',$s);$m=['egypt'=>['египет','egypt'],'turkey'=>['турция','turkey','turkiye'],'thailand'=>['таиланд','thailand'],'uae'=>['оаэ','объединенные арабские эмираты','united arab emirates','uae'],'vietnam'=>['вьетнам','vietnam','viet nam'],'srilanka'=>['шри ланка','sri lanka'],'maldives'=>['мальдивы','maldives'],'cuba'=>['куба','cuba']];foreach($m as$k=>$xs)if(in_array($s,$xs,true))return$k;return null;}
function cols(PDO $db,string $table):array{$q=$db->query('SHOW COLUMNS FROM `'.$table.'`');return array_map('strval',$q->fetchAll(PDO::FETCH_COLUMN));}
function sourceCountry(array $row):?string{$raw=(string)($row['evidence_json']??'');if($raw==='')return null;$e=json_decode($raw,true);if(!is_array($e))return null;$id=(string)($row['external_hotel_id']??'');$stack=[$e];$found=[];$n=0;while($stack&&$n++<5000){$v=array_pop($stack);if(!is_array($v))continue;if(isset($v['state'])&&(isset($v['id'])||isset($v['hotelKey']))&&(string)($v['id']??$v['hotelKey'])===$id){$c=cc($v['state']);if($c)$found[$c]=true;}foreach($v as$k=>$x)if(is_array($x)&&!in_array((string)$k,['candidates','targets','local','hotels','offers'],true))$stack[]=$x;}return count($found)===1?array_key_first($found):null;}
function safeName($v):string{$s=trim((string)$v);if(mb_strlen($s,'UTF-8')>300||preg_match('/[<>\x00-\x1f]|oauth_token|authorization|bearer\s/i',$s))return'';return$s;}
$pdo=null;try{$root=realpath(getcwd());if(!$root||basename($root)!=='anytoour.ru')throw new RuntimeException('root');$helper=is_file($root.'/data/db-v1.php')?$root.'/data/db-v1.php':$root.'/v2/data/db-v1.php';require_once$helper;$pdo=v2_data_db();$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$pdo->exec('START TRANSACTION READ ONLY');
$mapCols=cols($pdo,'anex_hotel_search_mappings');$enabled=in_array('enabled',$mapCols,true)?' WHERE enabled=1':'';$maps=$pdo->query('SELECT anex_hotel_id,catalog_hotel_id'.(in_array('enabled',$mapCols,true)?',enabled':'').' FROM anex_hotel_search_mappings'.$enabled)->fetchAll(PDO::FETCH_ASSOC);$anexIds=[];$anexLocals=[];foreach($maps as$r){$anexIds[(int)$r['anex_hotel_id']]=true;$anexLocals[(int)$r['catalog_hotel_id']]=true;}
$decisionCols=cols($pdo,'anex_hotel_decisions');$decisionIds=[];$manualLocals=[];$dsel=['anex_hotel_id'];foreach(['catalog_hotel_id','local_hotel_id','decision','status','decision_status']as$c)if(in_array($c,$decisionCols,true))$dsel[]=$c;foreach($pdo->query('SELECT '.implode(',',$dsel).' FROM anex_hotel_decisions')->fetchAll(PDO::FETCH_ASSOC)as$r){$decisionIds[(int)$r['anex_hotel_id']]=true;$lid=$r['catalog_hotel_id']??$r['local_hotel_id']??null;$status=(string)($r['decision_status']??$r['decision']??$r['status']??'');if($lid!==null&&in_array(mb_strtolower($status,'UTF-8'),['accepted','approved','accept','approve'],true)){$anexLocals[(int)$lid]=true;$manualLocals[(int)$lid]=true;}}
$exCols=cols($pdo,'anex_review_pair_exclusions');$exIds=[];foreach($pdo->query('SELECT DISTINCT anex_hotel_id FROM anex_review_pair_exclusions')->fetchAll(PDO::FETCH_COLUMN)as$id)$exIds[(int)$id]=true;
$and=$pdo->query("SELECT supplier_namespace,external_hotel_id,local_hotel_id,decision_status,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog'")->fetchAll(PDO::FETCH_ASSOC);$andCounts=['accepted'=>0,'pending'=>0,'conflict'=>0,'other'=>0];$andLocals=[];$pendingCore=array_fill_keys(['egypt','turkey','thailand','uae','vietnam','srilanka','maldives','cuba','unknown'],0);foreach($and as$r){$s=(string)$r['decision_status'];if(isset($andCounts[$s]))$andCounts[$s]++;else$andCounts['other']++;if($s==='accepted'&&$r['local_hotel_id']!==null)$andLocals[(int)$r['local_hotel_id']]=true;if($s==='pending'&&$r['local_hotel_id']===null){$c=sourceCountry($r)??'unknown';$pendingCore[$c]=($pendingCore[$c]??0)+1;}}
$triple=count(array_intersect_key($anexLocals,$andLocals));$coverage=['anex_mapping_rows'=>count($maps),'anex_unique_local'=>count($anexLocals),'anex_manual_accepted_unique_local'=>count($manualLocals),'andromeda_status'=>$andCounts,'andromeda_unique_local'=>count($andLocals),'triple'=>$triple,'anex_tv_only'=>count($anexLocals)-$triple,'andromeda_tv_only'=>count($andLocals)-$triple,'exactly_two'=>(count($anexLocals)-$triple)+(count($andLocals)-$triple)];
$stage=[];foreach($pdo->query('SELECT anex_hotel_id FROM anex_hotels')->fetchAll(PDO::FETCH_COLUMN)as$id)$stage[(int)$id]=true;$obsCols=cols($pdo,'anex_search_hotel_observations');$sel=array_values(array_intersect(['anex_hotel_id','hotel_name','country_id','anex_country_id','search_count','last_seen_utc','last_checkin_from','last_checkin_to'], $obsCols));$obs=$pdo->query('SELECT '.implode(',',$sel).' FROM anex_search_hotel_observations ORDER BY search_count DESC,last_seen_utc DESC,anex_hotel_id')->fetchAll(PDO::FETCH_ASSOC);$unresolved=[];$absent=0;foreach($obs as$r){$id=(int)$r['anex_hotel_id'];if(isset($anexIds[$id])||isset($decisionIds[$id])||isset($exIds[$id]))continue;$in=isset($stage[$id]);if(!$in)$absent++;$unresolved[]=['anex_hotel_id'=>$id,'hotel_name'=>safeName($r['hotel_name']??''),'country_id'=>isset($r['country_id'])?(int)$r['country_id']:null,'anex_country_id'=>isset($r['anex_country_id'])?(int)$r['anex_country_id']:null,'search_count'=>(int)($r['search_count']??0),'last_seen_utc'=>$r['last_seen_utc']??null,'in_staging'=>$in];}
$pdo->exec('ROLLBACK');$out=['status'=>'completed','operation_id'=>OP,'generated_at_utc'=>gmdate('c'),'coverage'=>$coverage,'observed_unresolved_unprotected'=>count($unresolved),'observed_unresolved_absent_from_staging'=>$absent,'observed_unresolved_top'=>array_slice($unresolved,0,250),'andromeda_pending_core8_by_country'=>$pendingCore,'staging_anex_rows'=>count($stage),'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true];}catch(Throwable$e){if($pdo instanceof PDO&&$pdo->inTransaction())$pdo->rollBack();$out=['status'=>'failed','operation_id'=>OP,'safe_message'=>'post539_current_census_failed','database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true];}while(ob_get_level())ob_end_clean();echo 'POST539_CENSUS:'.json_encode($out,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";exit(($out['status']??'')==='completed'?0:2);
