<?php
declare(strict_types=1);
/** MATCH #1971: read-only bridge from immutable operation response hotelKey+original tuple evidence. */
const OP='hotel-match-andromeda-operation-original-bridge-1971-20260916-v1';
function js($v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
function putnew(string $p,$v):string{$raw=js($v)."\n";$f=@fopen($p,'x');if(!$f)throw new RuntimeException('durable_create_failed');try{if(fwrite($f,$raw)!==strlen($raw))throw new RuntimeException('durable_write_failed');fflush($f);}finally{fclose($f);}if(file_get_contents($p)!==$raw)throw new RuntimeException('durable_readback_failed');return hash('sha256',$raw);}
function pos($v):?string{if(!is_scalar($v))return null;$s=trim((string)$v);return preg_match('/^[1-9][0-9]{0,14}$/D',$s)?$s:null;}
function dbpath(string $r):string{foreach([$r.'/data/db-v1.php',$r.'/v2/data/db-v1.php'] as $p)if(is_file($p))return$p;throw new RuntimeException('db_bootstrap_missing');}
function cols(PDO $d,string $t):array{$s=$d->query('SHOW COLUMNS FROM `'.str_replace('`','',$t).'`');$o=[];foreach($s->fetchAll(PDO::FETCH_ASSOC)?:[] as $r)$o[(string)$r['Field']]=true;return$o;}
function q(PDO $d,string $sql,array $p=[]):array{$s=$d->prepare($sql);$s->execute($p);return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}
function tuple_walk($v,string $path='root'):array{if(!is_array($v))return[];$out=[];$h=pos($v['hotelKey']??$v['hotel_key']??null);$orig=$v['original']??null;if($h!==null&&is_array($orig)){$oh=pos($orig['hotelKey']??$orig['hotel_key']??null);$ok=pos($orig['operatorKey']??$orig['operator_key']??null);if($oh!==null&&$ok!==null&&$oh!==$h)$out[]=['andromeda_hotel_key'=>$h,'original_hotel_key'=>$oh,'original_operator_key'=>$ok,'object_path'=>$path];}foreach($v as $k=>$x)if(is_array($x))foreach(tuple_walk($x,$path.'.'.(string)$k) as $z)$out[]=$z;return$out;}
if(in_array('--self-test',$argv??[],true)){$x=['hotelKey'=>177152,'original'=>['hotelKey'=>4158,'operatorKey'=>5]];$t=tuple_walk($x);if(count($t)!==1||$t[0]['andromeda_hotel_key']!=='177152'||$t[0]['original_hotel_key']!=='4158'||$t[0]['original_operator_key']!=='5')throw new RuntimeException('tuple_test');if(tuple_walk(['hotelKey'=>1,'original'=>['PhotoId'=>2,'operatorKey'=>5]])!==[])throw new RuntimeException('photo_test');echo"PASS\n";exit(0);}
$op=(string)getenv('OPERATION_ID');$sha=(string)getenv('MATCH_SOURCE_SHA');if($op!==OP||!preg_match('/^[0-9a-f]{40}$/D',$sha))throw new RuntimeException('operation_guard');$root=(string)realpath(getcwd());if($root===''||basename($root)!=='anytoour.ru')throw new RuntimeException('root_guard');$base=rtrim((string)getenv('HOME'),'/').'/.anytoour-match/operations';if(!is_dir($base))throw new RuntimeException('operations_root_missing');$dir=$base.'/'.$op;if(!mkdir($dir,0700))throw new RuntimeException('operation_exists');putnew($dir.'/reservation.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'reserved_before_operation_files_and_db','read_only'=>true,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);
try{$tuples=[];$files=0;$decoded=0;$dirs=0;$it=new DirectoryIterator($base);foreach($it as $de){if($de->isDot()||!$de->isDir()||$de->getFilename()===$op)continue;$dirs++;$rit=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($de->getPathname(),FilesystemIterator::SKIP_DOTS));foreach($rit as $fi){if(!$fi->isFile()||strtolower($fi->getExtension())!=='json')continue;$size=$fi->getSize();if($size<=0||$size>25*1024*1024)continue;$files++;$raw=@file_get_contents($fi->getPathname());if(!is_string($raw)||$raw==='')continue;try{$x=json_decode($raw,true,512,JSON_THROW_ON_ERROR);}catch(Throwable){continue;}if(!is_array($x))continue;$decoded++;$rel=substr($fi->getPathname(),strlen($de->getPathname())+1);$digest=hash('sha256',$raw);foreach(tuple_walk($x) as $t){$k=$t['andromeda_hotel_key'].':'.$t['original_hotel_key'].':'.$t['original_operator_key'];$tuples[$k]['andromeda_hotel_key']=$t['andromeda_hotel_key'];$tuples[$k]['original_hotel_key']=$t['original_hotel_key'];$tuples[$k]['original_operator_key']=$t['original_operator_key'];$tuples[$k]['provenance'][]=['operation_id'=>$de->getFilename(),'file'=>$rel,'file_sha256'=>$digest,'object_path'=>$t['object_path']];}}}}
$db=null;require_once dbpath($root);$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');$ic=cols($db,'andromeda_hotel_identities');foreach(['supplier_namespace','external_hotel_id','local_hotel_id','decision_status'] as $n)if(!isset($ic[$n]))throw new RuntimeException('identity_schema_missing_'.$n);$ids=q($db,'SELECT supplier_namespace,external_hotel_id,local_hotel_id,decision_status FROM andromeda_hotel_identities ORDER BY supplier_namespace,external_hotel_id');$am=[];$ac=cols($db,'anex_hotel_search_mappings');if(isset($ac['anex_hotel_id'])&&isset($ac['catalog_hotel_id'])){$sel='SELECT anex_hotel_id,catalog_hotel_id'.(isset($ac['enabled'])?',enabled':'').' FROM anex_hotel_search_mappings';$am=q($db,$sel);} $db->exec('ROLLBACK');
$acceptedAnd=[];$pendingAnd=[];$native=[];$occupied=[];foreach($ids as $r){$ns=(string)$r['supplier_namespace'];$ext=(string)$r['external_hotel_id'];$local=isset($r['local_hotel_id'])&&$r['local_hotel_id']!==null?(int)$r['local_hotel_id']:null;$st=(string)$r['decision_status'];if($ns==='andromeda_catalog'){if($st==='accepted'&&$local!==null){$acceptedAnd[$ext]=$local;$occupied[$local][$ext]=true;}elseif($st==='pending'&&$local===null)$pendingAnd[$ext]=true;}elseif($st==='accepted'&&$local!==null)$native[$ns][$ext][$local]=true;}
foreach($am as $r){if(isset($r['enabled'])&&(int)$r['enabled']!==1)continue;$ext=(string)$r['anex_hotel_id'];$local=(int)$r['catalog_hotel_id'];if($local>0)$native['anex_hotel_search_mappings'][$ext][$local]=true;}
$operatorSupport=[];$tupleRows=[];foreach($tuples as $t){$a=$t['andromeda_hotel_key'];$o=$t['original_hotel_key'];$ok=$t['original_operator_key'];$matches=[];foreach($native as $ns=>$byExt)if(isset($byExt[$o]))foreach(array_keys($byExt[$o]) as $local)$matches[]=['namespace'=>$ns,'local_id'=>(int)$local];$uniq=[];foreach($matches as $m)$uniq[$m['namespace'].':'.$m['local_id']]=$m;$matches=array_values($uniq);if(isset($acceptedAnd[$a])){$al=$acceptedAnd[$a];$same=array_values(array_filter($matches,fn($m)=>$m['local_id']===$al));$nss=array_values(array_unique(array_map(fn($m)=>$m['namespace'],$same)));if(count($nss)===1)$operatorSupport[$ok][$nss[0]]=($operatorSupport[$ok][$nss[0]]??0)+1;}$tupleRows[]=$t+['current_andromeda_status'=>isset($acceptedAnd[$a])?'accepted':(isset($pendingAnd[$a])?'pending':'absent'),'native_matches'=>$matches];}
ksort($operatorSupport,SORT_NATURAL);foreach($operatorSupport as &$m)ksort($m);unset($m);$cross=[];foreach($operatorSupport as $ok=>$m){$sum=array_sum($m);$cross[$ok]=['support'=>$m,'namespace'=>(count($m)===1&&$sum>=3)?array_key_first($m):null,'support_count'=>$sum,'proven'=>count($m)===1&&$sum>=3];}
$prepared=[];$holds=[];$targetPending=[];foreach($tupleRows as $t){if($t['current_andromeda_status']!=='pending')continue;$ok=$t['original_operator_key'];$cw=$cross[$ok]??null;if(!is_array($cw)||$cw['proven']!==true){$holds['operator_crosswalk_unproven']=($holds['operator_crosswalk_unproven']??0)+1;continue;}$ns=$cw['namespace'];$o=$t['original_hotel_key'];$locals=array_keys($native[$ns][$o]??[]);if(count($locals)!==1){$holds['native_target_not_unique']=($holds['native_target_not_unique']??0)+1;continue;}$local=(int)$locals[0];$other=array_keys($occupied[$local]??[]);if($other!==[]){$holds['andromeda_target_occupied']=($holds['andromeda_target_occupied']??0)+1;continue;}$row=['andromeda_hotel_key'=>$t['andromeda_hotel_key'],'original_hotel_key'=>$o,'original_operator_key'=>$ok,'proven_native_namespace'=>$ns,'candidate_local_id'=>$local,'crosswalk_support_count'=>$cw['support_count'],'provenance'=>$t['provenance']];$prepared[]=$row;$targetPending[$local][]=$t['andromeda_hotel_key'];}
$final=[];foreach($prepared as $r){$idsAt=$targetPending[$r['candidate_local_id']]??[];if(count(array_unique($idsAt))>1){$holds['pending_target_collision']=($holds['pending_target_collision']??0)+1;continue;}$final[]=$r;}ksort($holds);usort($final,fn($a,$b)=>strcmp($a['andromeda_hotel_key'],$b['andromeda_hotel_key']));
$result=['schema'=>'hotel-match-andromeda-operation-original-bridge/1','operation_id'=>$op,'source_sha'=>$sha,'state'=>'completed_read_only','operation_dirs_scanned'=>$dirs,'json_files_scanned'=>$files,'json_files_decoded'=>$decoded,'unique_original_tuples'=>count($tuples),'tuple_rows'=>$tupleRows,'operator_namespace_support'=>$operatorSupport,'operator_namespace_crosswalk'=>$cross,'pending_guard_passed_prepared_count'=>count($final),'pending_guard_passed_prepared'=>$final,'hold_counts'=>$holds,'policy'=>'same-object Andromeda hotelKey + nested original hotelKey/operatorKey only; operator namespace crosswalk requires >=3 accepted same-local anchors and zero namespace disagreement; native target unique; accepted occupancy and pending-target collision veto','safe_to_write_now'=>false,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'booking_calls'=>0,'lead_calls'=>0,'no_replay'=>true];$digest=putnew($dir.'/result.json',$result);putnew($dir.'/receipt.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'completed_read_only','result_sha256'=>$digest,'readback_verified'=>hash('sha256',(string)file_get_contents($dir.'/result.json'))===$digest,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);echo js(['state'=>'completed_read_only','operation_dirs_scanned'=>$dirs,'json_files_decoded'=>$decoded,'unique_original_tuples'=>count($tuples),'operator_namespace_crosswalk'=>$cross,'pending_guard_passed_prepared_count'=>count($final),'hold_counts'=>$holds])."\n";
}catch(Throwable $e){try{if(isset($db)&&$db instanceof PDO&&$db->inTransaction())$db->rollBack();}catch(Throwable){}$f=['operation_id'=>$op,'source_sha'=>$sha,'state'=>'failed_read_only','error_class'=>get_class($e),'error_message'=>$e->getMessage(),'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true];$digest=putnew($dir.'/failure.json',$f);putnew($dir.'/receipt.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'failed_read_only','failure_sha256'=>$digest,'readback_verified'=>true,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);fwrite(STDERR,"HMAP_FAILED ".$e->getMessage()."\n");exit(2);}
