<?php
declare(strict_types=1);
putenv('MATCH_PROVIDER_GEO_TEST_LIBRARY=1');
putenv('MATCH_ACCEPTED_NAME_BRIDGE_TEST_LIBRARY=1');
require_once __DIR__.'/hotel_match_provider_geo_consensus_review.php';
require_once __DIR__.'/hotel_match_accepted_name_bridge_review.php';

const MPGA_OP='hotel-match-provider-geo-consensus-apply-1971-20260915-v1';
const MPGA_REVIEW_OP='hotel-match-provider-geo-consensus-review-1971-20260915-v1';
const MPGA_REVIEW_SHA256='711cab875ec00dc3edb055e805bcb069ca70f78b3609ad64bb078d3859456beb';
const MPGA_PLAN_COUNT=140;
const MPGA_POLICY='owner_exact_and_strong_20260908';

function mpga_json(array $v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";}
function mpga_write(string $file,array $v):string{$raw=mpga_json($v);$f=@fopen($file,'x+b');if(!$f)throw new RuntimeException('exclusive_file');try{if(fwrite($f,$raw)!==strlen($raw)||!fflush($f))throw new RuntimeException('write');if(function_exists('fsync')&&!fsync($f))throw new RuntimeException('sync');rewind($f);if(stream_get_contents($f)!==$raw)throw new RuntimeException('readback');}finally{fclose($f);}return hash('sha256',$raw);}
function mpga_review(string $path):array{$raw=@file_get_contents($path);if(!is_string($raw)||hash('sha256',$raw)!==MPGA_REVIEW_SHA256)throw new RuntimeException('review_hash');$r=json_decode($raw,true,96,JSON_THROW_ON_ERROR);if(!is_array($r)||($r['operation_id']??'')!==MPGA_REVIEW_OP||($r['state']??'')!=='completed_read_only'||($r['no_replay']??false)!==true||(int)($r['db_writes']??-1)!==0||(int)($r['mapping_writes']??-1)!==0||(int)($r['candidate_count']??-1)!==MPGA_PLAN_COUNT||count($r['candidates']??[])!==MPGA_PLAN_COUNT)throw new RuntimeException('review_contract');return$r;}
function mpga_plan(array $review):array{$out=[];foreach($review['candidates']??[] as $r){if(!is_array($r)||($r['supplier_namespace']??'')!=='andromeda_catalog'||($r['route']??'')!=='auto_accept_candidate')throw new RuntimeException('plan_row');$id=(string)($r['external_hotel_id']??'');$target=(int)($r['target']??0);$sha=(string)($r['evidence_sha256']??'');if(!preg_match('/^[1-9][0-9]{0,19}$/D',$id)||$target<=0||!preg_match('/^[0-9a-f]{64}$/D',$sha))throw new RuntimeException('plan_identity');if(isset($out[$id])&&(int)$out[$id]['target']!==$target)throw new RuntimeException('plan_conflict');$out[$id]=$r;}if(count($out)!==MPGA_PLAN_COUNT)throw new RuntimeException('plan_count');return$out;}
function mpga_name_guard(array $names,int $cid,array $anchors,int $target):array{$n=manb_select($names,$cid,$anchors);if(($n['route']??'')==='hard_conflict')return['ok'=>false,'reason'=>'accepted_name_anchor_conflict','name_route'=>$n];if(($n['route']??'')==='auto_accept_candidate'&&(int)($n['target']??0)!==$target)return['ok'=>false,'reason'=>'accepted_name_anchor_other_target','name_route'=>$n];return['ok'=>true,'name_route'=>$n];}
function mpga_coverage(PDO $db):array{$a=mpg_query($db,"SELECT DISTINCT m.catalog_hotel_id id FROM anex_hotel_search_mappings m WHERE m.enabled=1 AND m.scope='preview' AND m.approval_policy=? AND NOT EXISTS(SELECT 1 FROM anex_hotel_decisions d WHERE d.anex_hotel_id=m.anex_hotel_id) AND NOT EXISTS(SELECT 1 FROM anex_review_pair_exclusions x WHERE x.anex_hotel_id=m.anex_hotel_id AND x.catalog_hotel_id=m.catalog_hotel_id) UNION SELECT d.catalog_hotel_id id FROM anex_hotel_decisions d WHERE d.decision_status='accepted' AND d.catalog_hotel_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM anex_review_pair_exclusions x WHERE x.anex_hotel_id=d.anex_hotel_id AND x.catalog_hotel_id=d.catalog_hotel_id)",[MPGA_POLICY]);$d=mpg_query($db,"SELECT DISTINCT local_hotel_id id FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IS NOT NULL");$aa=array_map('intval',array_column($a,'id'));$dd=array_map('intval',array_column($d,'id'));return['anex_unique_local'=>count($aa),'andromeda_unique_local'=>count($dd),'all_three'=>count(array_intersect($aa,$dd))];}
function mpga_readback_ok(array $r,int $target):bool{$e=mcr_evidence((string)($r['evidence_json']??''));return($r['decision_status']??'')==='accepted'&&(int)($r['local_hotel_id']??0)===$target&&($e['match_promotion']['operation_id']??'')===MPGA_OP&&(int)($e['match_promotion']['target_local_hotel_id']??0)===$target&&($e['match_promotion']['review_result_sha256']??'')===MPGA_REVIEW_SHA256;}

if(getenv('MATCH_PROVIDER_GEO_APPLY_TEST_LIBRARY')==='1')return;
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
$op=(string)getenv('MATCH_OPERATION_ID');$sha=(string)getenv('MATCH_SOURCE_SHA');if($op!==MPGA_OP||!preg_match('/^[0-9a-f]{40}$/D',$sha))throw new RuntimeException('operation_or_source_guard');$home=(string)getenv('HOME');if($home==='')throw new RuntimeException('home');$dir=$home.'/.anytoour-match/operations/'.MPGA_OP;$reviewPath=$home.'/.anytoour-match/operations/'.MPGA_REVIEW_OP.'/result.json';$res=mcr_evidence((string)@file_get_contents($dir.'/reservation.json'));if(($res['operation_id']??'')!==MPGA_OP||($res['source_sha']??'')!==$sha||($res['state']??'')!=='reserved_before_db_access'||(int)($res['planned_rows']??-1)!==MPGA_PLAN_COUNT||($res['review_result_sha256']??'')!==MPGA_REVIEW_SHA256)throw new RuntimeException('reservation');$review=mpga_review($reviewPath);$plans=mpga_plan($review);$root=realpath(getcwd());if(!$root||basename($root)!=='anytoour.ru')throw new RuntimeException('root');require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET SESSION innodb_lock_wait_timeout=30');$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->beginTransaction();$committed=false;
try{
 $eng=array_column(mpg_query($db,"SELECT TABLE_NAME,ENGINE FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME IN ('andromeda_hotel_identities','catalog_hotels','hotel_aliases')"),'ENGINE','TABLE_NAME');foreach(['andromeda_hotel_identities','catalog_hotels','hotel_aliases'] as $t)if(strtoupper((string)($eng[$t]??''))!=='INNODB')throw new RuntimeException('transaction_table_'.$t);
 $core=[];foreach(mpg_query($db,'SELECT id,name FROM catalog_countries WHERE is_active=1 ORDER BY id') as $c)if(mcr_is_core8_name((string)$c['name']))$core[(int)$c['id']]=(string)$c['name'];if(count($core)<6)throw new RuntimeException('core8');$marks=implode(',',array_fill(0,count($core),'?'));
 $hotels=[];$forms=[];$scope=[];foreach(mpg_query($db,"SELECT id,country_id,country_name,region_id,region_name,subregion_id,subregion_name,name,category,latitude,longitude FROM catalog_hotels WHERE is_active=1 AND country_id IN ($marks) ORDER BY country_id,id",array_keys($core)) as $h){$id=(int)$h['id'];$hotels[$id]=$h;$forms[$id]=[(string)$h['name']];$cid=(int)$h['country_id'];$rid=(int)$h['region_id'];$sid=(int)$h['subregion_id'];if($rid>0)$scope[$cid]['region'][$rid][$id]=true;if($sid>0)$scope[$cid]['subregion'][$sid][$id]=true;}foreach(mpg_query($db,"SELECT a.hotel_id,a.alias FROM hotel_aliases a JOIN catalog_hotels h ON h.id=a.hotel_id WHERE h.is_active=1 AND h.country_id IN ($marks) ORDER BY a.hotel_id,a.id",array_keys($core)) as $a){$id=(int)$a['hotel_id'];if(isset($forms[$id]))$forms[$id][]=(string)$a['alias'];}
 $all=mpg_query($db,"SELECT external_hotel_id,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' ORDER BY external_hotel_id");$accepted=mpg_query($db,"SELECT i.external_hotel_id,i.local_hotel_id,i.evidence_json,h.country_id AS local_country_id,h.region_id AS local_region_id,h.subregion_id AS local_subregion_id FROM andromeda_hotel_identities i JOIN catalog_hotels h ON h.id=i.local_hotel_id AND h.is_active=1 WHERE i.supplier_namespace='andromeda_catalog' AND i.decision_status='accepted' AND i.local_hotel_id IS NOT NULL ORDER BY i.external_hotel_id");$country=msac_accepted_country_consensus($accepted,$all,$core);$geo=mpg_build_consensus($accepted);$nameAnchors=manb_build_anchors($accepted,$hotels);
 $pending=mpg_query($db,"SELECT supplier_namespace,external_hotel_id,local_hotel_id,decision_status,evidence_sha256,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='pending' AND local_hotel_id IS NULL ORDER BY external_hotel_id FOR UPDATE");$byId=[];foreach($pending as $r)$byId[(string)$r['external_hotel_id']]=$r;$before=mpga_coverage($db);$valid=[];$holds=[];
 foreach($plans as $id=>$plan){$cur=$byId[$id]??null;if(!$cur){$holds[]=['external_hotel_id'=>$id,'reason'=>'current_state_protected_or_missing'];continue;}if((string)$cur['evidence_sha256']!==(string)$plan['evidence_sha256']){$holds[]=['external_hotel_id'=>$id,'reason'=>'evidence_sha_changed'];continue;}$e=mcr_evidence((string)$cur['evidence_json']);$sk=mcr_state_key($e);if($sk===null||$sk!==(string)($plan['state_key']??'')||!isset($country['inferred'][$sk])){$holds[]=['external_hotel_id'=>$id,'reason'=>'state_country_consensus_changed'];continue;}$cid=(int)$country['inferred'][$sk]['country_id'];if($cid!==(int)($plan['country_id']??0)){$holds[]=['external_hotel_id'=>$id,'reason'=>'country_target_changed'];continue;}$allow=mpg_allowed_ids($e,$cid,$geo,$scope);if(($allow['status']??'')!=='ok'){$holds[]=['external_hotel_id'=>$id,'reason'=>'provider_geo_consensus_changed','status'=>$allow['status']??null];continue;}$sel=mpg_select(mcr_names($e),mcr_points($e),$allow['ids'],$hotels,$forms);if(($sel['route']??'')!=='auto_accept_candidate'||(int)($sel['target']??0)!==(int)$plan['target']){$holds[]=['external_hotel_id'=>$id,'reason'=>'candidate_changed','current_route'=>$sel['route']??null,'current_reason'=>$sel['reason']??null,'current_target'=>$sel['target']??null];continue;}$target=(int)$sel['target'];if(!isset($hotels[$target])||(int)$hotels[$target]['country_id']!==$cid){$holds[]=['external_hotel_id'=>$id,'reason'=>'target_country_or_activity_changed'];continue;}$ng=mpga_name_guard(mcr_names($e),$cid,$nameAnchors,$target);if(!($ng['ok']??false)){$holds[]=['external_hotel_id'=>$id,'reason'=>$ng['reason'],'name_route'=>$ng['name_route']??null];continue;}$valid[$id]=['cur'=>$cur,'evidence'=>$e,'target'=>$target,'selection'=>$sel,'state_country'=>$country['inferred'][$sk],'geo_anchors'=>$allow['anchors'],'name_guard'=>$ng['name_route']??null];}
 $up=$db->prepare("UPDATE andromeda_hotel_identities SET local_hotel_id=?,decision_status='accepted',evidence_sha256=?,evidence_json=? WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=? AND decision_status='pending' AND local_hotel_id IS NULL AND evidence_sha256 <=> ?");$written=[];
 foreach($valid as $id=>$x){$prior=$x['evidence'];if(isset($prior['match_promotion'])){$holds[]=['external_hotel_id'=>$id,'reason'=>'promotion_field_already_present'];continue;}$promotion=['operation_id'=>MPGA_OP,'rule'=>(string)$x['selection']['reason'],'target_local_hotel_id'=>(int)$x['target'],'review_operation_id'=>MPGA_REVIEW_OP,'review_result_sha256'=>MPGA_REVIEW_SHA256,'server_current_revalidated'=>true,'state_country_inference'=>$x['state_country'],'provider_geo_anchors'=>$x['geo_anchors'],'accepted_name_guard'=>$x['name_guard'],'coordinate_conflict_gt5km_blocked'=>true,'qualifiers_preserved'=>true,'distance_km'=>$x['selection']['distance_km']??null,'score'=>$x['selection']['score']??null,'margin'=>$x['selection']['margin']??null];$new=$prior;$new['match_promotion']=$promotion;$json=mpga_json($new);$newSha=hash('sha256',$json);$up->execute([(int)$x['target'],$newSha,$json,$id,$x['cur']['evidence_sha256']]);if($up->rowCount()!==1)throw new RuntimeException('concurrency_'.$id);$written[]=['external_hotel_id'=>$id,'target'=>(int)$x['target'],'new_sha'=>$newSha,'rule'=>$promotion['rule']];}
 $db->commit();$committed=true;$read=[];foreach($written as $w){$r=mpg_query($db,"SELECT external_hotel_id,local_hotel_id,decision_status,evidence_sha256,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=?",[$w['external_hotel_id']]);if(count($r)!==1||!mpga_readback_ok($r[0],(int)$w['target'])||(string)$r[0]['evidence_sha256']!==$w['new_sha'])throw new RuntimeException('post_commit_'.$w['external_hotel_id']);$read[]=['external_hotel_id'=>$w['external_hotel_id'],'local_hotel_id'=>(int)$r[0]['local_hotel_id'],'decision_status'=>$r[0]['decision_status'],'evidence_sha256'=>$r[0]['evidence_sha256'],'rule'=>$w['rule']];}$after=mpga_coverage($db);$rules=[];foreach($read as $r)$rules[$r['rule']]=($rules[$r['rule']]??0)+1;ksort($rules);
 $result=['schema'=>'hotel-match-provider-geo-consensus-apply/1','operation_id'=>MPGA_OP,'source_sha'=>$sha,'state'=>'completed_committed','server_current'=>true,'review_operation_id'=>MPGA_REVIEW_OP,'review_result_sha256'=>MPGA_REVIEW_SHA256,'planned'=>count($plans),'validated'=>count($valid),'written'=>count($read),'holds_count'=>count($holds),'holds'=>$holds,'written_by_rule'=>$rules,'coverage_before'=>$before,'coverage_after'=>$after,'post_commit_readback'=>$read,'supplier_calls'=>0,'tourvisor_calls'=>0,'external_calls'=>0,'booking_calls'=>0,'operator_5_writes'=>0,'mapping_writes'=>count($read),'no_replay'=>true,'completed_at'=>gmdate('c')];$hash=mpga_write($dir.'/result.json',$result);$raw=(string)file_get_contents($dir.'/result.json');$parsed=mcr_evidence($raw);$ok=hash('sha256',$raw)===$hash&&count($parsed['post_commit_readback']??[])===count($read);mpga_write($dir.'/receipt.json',['operation_id'=>MPGA_OP,'source_sha'=>$sha,'state'=>'completed_committed','result_sha256'=>$hash,'readback_verified'=>$ok,'planned'=>count($plans),'written'=>count($read),'holds_count'=>count($holds),'post_commit_rows'=>count($read),'operator_5_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'external_calls'=>0,'booking_calls'=>0,'no_replay'=>true,'completed_at'=>gmdate('c')]);if(!$ok)throw new RuntimeException('result_readback');echo mpga_json(['operation_id'=>MPGA_OP,'state'=>'completed_committed','planned'=>count($plans),'validated'=>count($valid),'written'=>count($read),'holds'=>count($holds),'written_by_rule'=>$rules,'coverage_before'=>$before,'coverage_after'=>$after,'result_sha256'=>$hash]);
}catch(Throwable $e){if(!$committed&&$db->inTransaction())$db->rollBack();if(!$committed&&!is_file($dir.'/failure.json'))mpga_write($dir.'/failure.json',['operation_id'=>MPGA_OP,'source_sha'=>$sha,'state'=>'rolled_back','error_class'=>get_class($e),'error'=>substr($e->getMessage(),0,300),'supplier_calls'=>0,'tourvisor_calls'=>0,'external_calls'=>0,'booking_calls'=>0,'db_writes'=>0,'no_replay'=>true,'failed_at'=>gmdate('c')]);throw $e;}
