<?php
declare(strict_types=1);
if (!defined('FC_LIBRARY_ONLY')) define('FC_LIBRARY_ONLY', true);
require_once __DIR__ . '/hotel_match_anex_andromeda_mutual_graph_review.php';

const HMALCR_OPERATION='hotel-match-anex-andromeda-local-consensus-review-1971-20260911-v1';

function hmalcr_other_claims(array $claims,int|string $self): array {
    return array_values(array_filter($claims,static fn($x)=>(string)$x!==(string)$self));
}
function hmalcr_source(array $row):array{
    return ['names'=>$row['names'],'places'=>$row['places'],'latitude'=>$row['latitude'],'longitude'=>$row['longitude']];
}
function hmalcr_review(PDO $db,string $operation=HMALCR_OPERATION):array{
    if($operation!==HMALCR_OPERATION)throw new RuntimeException('operation_scope');
    $db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION READ ONLY');
    try{
        $coverage=fc_coverage($db);$an=hmamgr_anex_rows($db);$and=hmamgr_andromeda_rows($db);$anIndex=hmamgr_index($an);$andIndex=hmamgr_index($and);$anLoc=hmadcrh_locality_common($an);$andLoc=hmadcrh_locality_common($and);
        [$hotels,$names]=mbr_catalog($db);$all=[];foreach(array_keys($hotels)as$id)$all[(int)$id]=true;$localIndex=hmgcr_build_index($all,$hotels,$names);
        $manual=array_fill_keys(array_map('intval',$db->query('SELECT anex_hotel_id FROM anex_hotel_decisions')->fetchAll(PDO::FETCH_COLUMN)),true);$excluded=[];foreach($db->query('SELECT anex_hotel_id,catalog_hotel_id FROM anex_review_pair_exclusions')->fetchAll(PDO::FETCH_ASSOC)as$r)$excluded[(int)$r['anex_hotel_id']][(int)$r['catalog_hotel_id']]=true;
        $anClaims=[];foreach($db->query('SELECT anex_hotel_id,catalog_hotel_id FROM anex_hotel_search_mappings WHERE enabled=1')->fetchAll(PDO::FETCH_ASSOC)as$r)$anClaims[(int)$r['catalog_hotel_id']][]=(int)$r['anex_hotel_id'];foreach($db->query("SELECT anex_hotel_id,catalog_hotel_id FROM anex_hotel_decisions WHERE decision_status='accepted' AND catalog_hotel_id IS NOT NULL")->fetchAll(PDO::FETCH_ASSOC)as$r)$anClaims[(int)$r['catalog_hotel_id']][]=(int)$r['anex_hotel_id'];
        $andClaims=[];foreach($db->query("SELECT external_hotel_id,local_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IS NOT NULL")->fetchAll(PDO::FETCH_ASSOC)as$r)$andClaims[(int)$r['local_hotel_id']][]=(string)$r['external_hotel_id'];
        $prepared=[];$bench=[];$near=[];$hard=[];$stats=['anex_rows'=>count($an),'andromeda_rows'=>count($and),'mutual_examined'=>0,'mutual_safe'=>0,'benchmark_same_local'=>0,'benchmark_consensus_same_target'=>0,'benchmark_consensus_expected_target'=>0,'new_one_side_examined'=>0,'new_neither_examined'=>0,'new_consensus_prepared'=>0,'new_consensus_one_side'=>0,'new_consensus_neither'=>0,'new_consensus_live'=>0,'local_disagreement'=>0,'local_insufficient'=>0,'existing_local_conflict'=>0,'manual_protected'=>0,'pair_exclusion_block'=>0,'target_occupancy_block'=>0];
        foreach($an as$aid=>$a){$f=hmamgr_choose($a,$and,$andIndex,$andLoc);if(($f['bucket']??'')!=='candidate')continue;$andId=(string)$f['target_id'];$b=$and[$andId]??null;if(!$b)continue;$rev=hmamgr_choose($b,$an,$anIndex,$anLoc);if(($rev['bucket']??'')!=='candidate'||(string)($rev['target_id']??'')!==(string)$aid)continue;$stats['mutual_examined']++;
            $validation=hmamgr_validation($a['local_ids'],$b['local_ids']);if($validation==='different_local'){$stats['existing_local_conflict']++;$hard[]=['anex_hotel_id'=>(int)$aid,'andromeda_external_id'=>$andId,'validation'=>$validation,'reason'=>'supplier_pair_existing_local_conflict'];continue;}$stats['mutual_safe']++;if($validation==='same_local')$stats['benchmark_same_local']++;elseif($validation==='neither_side')$stats['new_neither_examined']++;else$stats['new_one_side_examined']++;
            $country=(int)$a['country_id'];$da=hmgtr_decide(hmalcr_source($a),$country,$localIndex,$hotels,$names,[],$excluded[(int)$aid]??[]);$dbb=hmgtr_decide(hmalcr_source($b),$country,$localIndex,$hotels,$names,[],[]);
            $row=['anex_hotel_id'=>(int)$aid,'andromeda_external_id'=>$andId,'country_id'=>$country,'validation'=>$validation,'anex_local_ids'=>$a['local_ids'],'andromeda_local_ids'=>$b['local_ids'],'anex_live'=>$a['live'],'andromeda_live'=>$b['live'],'anex_observation_count'=>$a['observation_count'],'andromeda_observation_count'=>$b['observation_count'],'anex_names'=>$a['names'],'andromeda_names'=>$b['names'],'supplier_forward'=>$f,'supplier_reverse'=>$rev,'anex_local_resolution'=>$da,'andromeda_local_resolution'=>$dbb];
            if(($da['bucket']??'')!=='prepared'||($dbb['bucket']??'')!=='prepared'){$stats['local_insufficient']++;$row['reason']='dual_supplier_local_resolution_insufficient';$near[]=$row;continue;}$ta=(int)$da['target_local_hotel_id'];$tb=(int)$dbb['target_local_hotel_id'];if($ta!==$tb){$stats['local_disagreement']++;$row['reason']='dual_supplier_local_target_disagreement';$row['anex_target']=$ta;$row['andromeda_target']=$tb;$near[]=$row;continue;}$target=$ta;$row['target_local_hotel_id']=$target;$row['target_name']=$hotels[$target]['name']??null;$row['target_region']=$hotels[$target]['region_name']??null;$row['target_subregion']=$hotels[$target]['subregion_name']??null;
            if($validation==='same_local'){$stats['benchmark_consensus_same_target']++;$expected=(int)($a['local_ids'][0]??0);if($target===$expected)$stats['benchmark_consensus_expected_target']++;else{$stats['existing_local_conflict']++;$row['reason']='benchmark_consensus_disagrees_existing_local';$hard[]=$row;continue;}$row['reason']='benchmark_dual_supplier_consensus';$bench[]=$row;continue;}
            if($a['local_ids']&&!in_array($target,$a['local_ids'],true)||$b['local_ids']&&!in_array($target,$b['local_ids'],true)){$stats['existing_local_conflict']++;$row['reason']='consensus_disagrees_existing_one_side_local';$hard[]=$row;continue;}
            if(isset($manual[(int)$aid])){$stats['manual_protected']++;$row['reason']='anex_manual_decision_protected';$near[]=$row;continue;}if(isset($excluded[(int)$aid][$target])){$stats['pair_exclusion_block']++;$row['reason']='anex_pair_exclusion_protected';$near[]=$row;continue;}
            $otherAn=hmalcr_other_claims($anClaims[$target]??[],(int)$aid);$otherAnd=hmalcr_other_claims($andClaims[$target]??[],$andId);if($otherAn||$otherAnd){$stats['target_occupancy_block']++;$row['reason']='same_provider_target_occupied';$row['other_anex_claims']=$otherAn;$row['other_andromeda_claims']=$otherAnd;$near[]=$row;continue;}
            $row['reason']='dual_supplier_same_local_consensus';$prepared[]=$row;$stats['new_consensus_prepared']++;if($validation==='neither_side')$stats['new_consensus_neither']++;else$stats['new_consensus_one_side']++;if($a['live']||$b['live'])$stats['new_consensus_live']++;
        }
        usort($prepared,static fn($x,$y)=>(($y['anex_live']||$y['andromeda_live'])<=>($x['anex_live']||$x['andromeda_live']))?:($y['anex_observation_count']<=>$x['anex_observation_count'])?:($x['anex_hotel_id']<=>$y['anex_hotel_id']));$db->commit();
        return ['status'=>'completed','operation_id'=>$operation,'mode'=>'current_core8_mutual_supplier_to_local_consensus_read_only','database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'historical_operations_replayed'=>false,'coverage'=>$coverage,'stats'=>$stats,'prepared'=>$prepared,'benchmark'=>$bench,'hard_conflicts'=>$hard,'near'=>$near,'guards'=>['supplier_pair_recomputed_current'=>true,'both_suppliers_must_prepare_same_local_target'=>true,'existing_local_validation_only'=>true,'manual_decisions_protected'=>true,'pair_exclusions_protected'=>true,'same_provider_target_occupancy_protected'=>true,'coordinate_conflict_block_m'=>HMGTR_COORD_BLOCK_M,'critical_qualifiers_preserved'=>['ANNEX','BEACH','GARDEN','NORTH','SOUTH'],'stars_not_identity'=>true,'core8_only'=>true]];
    }catch(Throwable$e){if($db->inTransaction())$db->rollBack();throw$e;}
}
if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__){fwrite(STDERR,"library_only: use guarded local consensus workflow\n");exit(64);}
