<?php
declare(strict_types=1);
const D11_MAX_TV=90,D11_MAX_CONT=8;
function d11_need(bool $x,string $w):void{if(!$x)throw new RuntimeException($w);}
function d11_id(mixed $v):?string{$s=hmc_text($v,80);return preg_match('/^[1-9][0-9]{0,31}$/D',$s)?$s:null;}
function d11_write(string $p,string $raw):string{$f=@fopen($p,'x+b');d11_need(is_resource($f),'write_open');try{d11_need(fwrite($f,$raw)===strlen($raw)&&fflush($f),'write');if(function_exists('fsync'))d11_need(fsync($f),'sync');}finally{fclose($f);}return hash('sha256',$raw);}
function d11_raw(string $dir,string $name,array $v,array &$m):void{$raw=hmc_json($v)."\n";$file='raw-'.$name.'.json';$sha=d11_write($dir.'/'.$file,$raw);$m[]=['file'=>$file,'sha256'=>$sha,'bytes'=>strlen($raw)];}
function d11_urls_walk(mixed $v,array &$out,int $depth=0):void{if($depth>8)return;if(is_array($v)){foreach($v as$x)d11_urls_walk($x,$out,$depth+1);return;}if(!is_string($v))return;$u=hmc_url($v);if($u!==null)$out[$u]=true;}
function d11_urls(mixed $v):array{$o=[];d11_urls_walk($v,$o);$x=array_keys($o);sort($x,SORT_STRING);return array_slice($x,0,80);}
function d11_url_shape(string $u):string{$p=parse_url($u);if(!is_array($p))return'';return strtolower((string)($p['host']??'')).rtrim(strtolower((string)($p['path']??'')),'/');}
function d11_url_ids(string $u):array{$p=parse_url($u);if(!is_array($p))return[];$o=[];foreach(preg_split('~/+~',(string)($p['path']??''),-1,PREG_SPLIT_NO_EMPTY)?:[]as$x)if(preg_match('/^[1-9][0-9]{0,31}$/D',$x))$o[$x]=true;parse_str((string)($p['query']??''),$q);foreach($q as$k=>$v){if(!preg_match('/hotel|hotellist|hotelid|hotel_id|hotelcode|f4/i',(string)$k))continue;foreach((array)$v as$z)foreach(preg_split('/[,;]+/',(string)$z)?:[]as$x){$x=trim($x);if(preg_match('/^[1-9][0-9]{0,31}$/D',$x))$o[$x]=true;}}return array_keys($o);}
function d11_samo_row(array $r,array $ops):?array{$sid=d11_id($r['hotelKey']??null);$op=d11_id($r['operatorKey']??($r['original']['operatorKey']??null));if(!$sid||!$op||!isset($ops[$op]))return null;$orig=is_array($r['original']??null)?$r['original']:[];$urls=d11_urls($r);return['samo_hotel_id'=>$sid,'hotel_name'=>hmc_text($r['hotel']??'',300),'operator_family'=>$ops[$op]['family'],'samo_operator_id'=>$op,'native_operator_hotel_id'=>d11_id($orig['hotelKey']??null),'is_operator_hotel_key'=>isset($orig['isOperatorHotelKey'])&&is_scalar($orig['isOperatorHotelKey'])?(string)$orig['isOperatorHotelKey']:null,'urls'=>$urls,'url_shapes'=>array_values(array_unique(array_filter(array_map('d11_url_shape',$urls)))),'date'=>hmc_date($r['checkIn']??'',''),'nights'=>hmc_id($r['nights']??null),'room'=>hmc_text($r['room']??($r['roomName']??''),240),'meal'=>hmc_text($r['meal']??'',160)];}
function d11_tv_call(string $dir,string $path,array $params,string $name,int &$n,array &$m):array{d11_need(++$n<=D11_MAX_TV,'tv_cap');$r=v2_data_tv_get($path,$params);d11_raw($dir,$name,$r,$m);return$r;}
function d11_tv_wait(string $dir,int $sid,int &$n,array &$m,int &$seq):void{for($i=0;$i<30;$i++){sleep(2);$s=d11_tv_call($dir,'/tours/search/'.$sid.'/status',['operatorStatus'=>false],'tv-status-'.(++$seq),$n,$m);if(hmc_complete($s))return;}throw new RuntimeException('tv_timeout');}
function d11_tv_drain(string $dir,array $params,int &$n,array &$m):array{$seq=0;$start=d11_tv_call($dir,'/tours/search',$params,'tv-search-start',$n,$m);$sid=hmc_search_id($start);d11_need($sid!==null,'tv_search_id');d11_tv_wait($dir,$sid,$n,$m,$seq);$res=d11_tv_call($dir,'/tours/search/'.$sid,['limit'=>5000],'tv-results-0',$n,$m);$rows=hmc_tv_result_rows($res);$sig=hmc_tv_signatures($rows);$rounds=[['round'=>0]+$sig];for($r=1;$r<=D11_MAX_CONT;$r++){$c=d11_tv_call($dir,'/tours/search/'.$sid.'/continue',[],'tv-continue-'.$r,$n,$m);$req=hmc_request_count($c);d11_need($req!==null,'tv_continue_shape');if($req>0)d11_tv_wait($dir,$sid,$n,$m,$seq);$next=d11_tv_call($dir,'/tours/search/'.$sid,['limit'=>5000],'tv-results-'.$r,$n,$m);$merged=hmc_tv_merge_rows($rows,hmc_tv_result_rows($next));$ns=hmc_tv_signatures($merged);$rounds[]=['round'=>$r,'request_count'=>$req]+$ns;$same=$ns===$sig;$rows=$merged;$sig=$ns;if($req===0||$same)return['search_id'=>$sid,'rows'=>$rows,'rounds'=>$rounds,'fully_drained'=>true];}throw new RuntimeException('tv_continue_cap');}
function d11_tv_pairs(array $rows,array $ops):array{$out=[];foreach($rows as$h){if(!is_array($h)||!($hid=d11_id($h['id']??null)))continue;$name=hmc_text($h['name']??'',300);foreach((array)($h['tours']??[])as$t){if(!is_array($t))continue;$op=hmc_id($t['operator']??null);$tid=hmc_text($t['id']??($t['tourId']??''),220);if(!$op||$tid===''||!isset($ops[$op]))continue;$k=$hid.'|'.$ops[$op]['family'];if(!isset($out[$k]))$out[$k]=['tv_hotel_id'=>$hid,'hotel_name'=>$name,'operator_family'=>$ops[$op]['family'],'tv_operator_id'=>$op,'tour_id'=>$tid];}}return array_values($out);}
function d11_name(string $s):string{return hmc_norm(preg_replace('/\b(?:hotel|resort|spa|apart|apartment)\b/iu',' ',$s)??$s);}
function d11_join(array $samo,array $tv):array{$out=[];foreach($samo as$s){$cand=[];foreach($tv as$t){if($s['operator_family']!==$t['operator_family'])continue;$ids=[];$sh=[];foreach($t['detail_urls']as$u){foreach(d11_url_ids($u)as$x)$ids[(string)$x]=true;$z=d11_url_shape($u);if($z!=='')$sh[$z]=true;}$ev=[];if($s['native_operator_hotel_id']!==null&&isset($ids[$s['native_operator_hotel_id']]))$ev[]='native_id_in_operator_link';if(array_intersect($s['url_shapes'],array_keys($sh)))$ev[]='same_operator_url_path';if(!$ev&&d11_name($s['hotel_name'])!==''&&d11_name($s['hotel_name'])===d11_name($t['hotel_name']))$ev[]='exact_name_only';if($ev)$cand[]=['tv_hotel_id'=>$t['tv_hotel_id'],'tv_hotel_name'=>$t['hotel_name'],'tour_id'=>$t['tour_id'],'evidence'=>$ev,'detail_urls'=>$t['detail_urls']];}$strong=array_values(array_filter($cand,fn($c)=>in_array('native_id_in_operator_link',$c['evidence'],true)||in_array('same_operator_url_path',$c['evidence'],true)));$state=count($strong)===1?'direct_identity_candidate':(count($strong)>1?'ambiguous_direct_identity':($cand?'name_candidate_only':'no_tv_candidate'));$out[]=['samo_hotel_id'=>$s['samo_hotel_id'],'samo_hotel_name'=>$s['hotel_name'],'operator_family'=>$s['operator_family'],'native_operator_hotel_id'=>$s['native_operator_hotel_id'],'state'=>$state,'candidates'=>$strong?:$cand,'safe_to_write_now'=>false];}return$out;}
