<?php
declare(strict_types=1);
const D6C_OP='hotel-match-didim-direct6-current-1971-20260919-v1';
function d6c_need(bool $x,string $w):void{if(!$x)throw new RuntimeException($w);}
function d6c_write(string $p,array $v):string{$raw=json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n";$f=fopen($p,'xb');d6c_need(is_resource($f),'open');fwrite($f,$raw);fflush($f);if(function_exists('fsync'))fsync($f);fclose($f);return hash('sha256',$raw);}
function d6c_rows(PDO $db,string $sql,array $p=[]):array{$s=$db->prepare($sql);$s->execute($p);return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}
if(in_array('--self-test',$argv??[],true)){echo"DIDIM_DIRECT6_CURRENT_SELFTEST_OK\n";exit(0);}
$dir=(string)getenv('MATCH_OPERATION_DIR');$root=realpath((string)getenv('ANYTOUR_ROOT'));$v7=realpath((string)getenv('MATCH_V7_RESULT'));$v6=realpath((string)getenv('MATCH_V6_RESULT'));d6c_need(PHP_SAPI==='cli'&&is_dir($dir)&&basename($dir)===D6C_OP&&is_string($root),'runtime');d6c_need(is_string($v7)&&hash_file('sha256',$v7)==='1863e0cbac483965f859c1f00250939f77b114651e124f12e542b09de61a8947','v7');d6c_need(is_string($v6)&&hash_file('sha256',$v6)==='46653546e4ae294e7e4c9e5c5c685dd21294a5fa4f867d43a261f4acab42d87b','v6');
$a=json_decode((string)file_get_contents($v7),true,64,JSON_THROW_ON_ERROR);$b=json_decode((string)file_get_contents($v6),true,64,JSON_THROW_ON_ERROR);d6c_need(($a['state']??'')==='completed_read_only'&&($b['state']??'')==='completed_read_only','inputs');
$direct=[];foreach((array)$a['join']as$j){$native=(string)($j['native_operator_hotel_id']??'');if($native==='')continue;$hits=[];foreach((array)$a['details']as$d){if(($d['operator_family']??'')!==($j['operator_family']??''))continue;$ids=array_map('strval',(array)($d['operator_link_native_ids']??[]));if(in_array($native,$ids,true))$hits[]=$d;}if(count($hits)===1)$direct[(string)$j['samo_hotel_id']]=['samo_hotel_id'=>(string)$j['samo_hotel_id'],'samo_name'=>$j['samo_hotel_name'],'operator_family'=>$j['operator_family'],'native_operator_hotel_id'=>$native,'tv_hotel_id'=>(int)$hits[0]['tv_hotel_id'],'tv_name'=>$hits[0]['hotel_name'],'tour_id'=>$hits[0]['tour_id'],'operator_link_native_ids'=>array_map('strval',$hits[0]['operator_link_native_ids']),'detail_urls'=>$hits[0]['detail_urls']];}
d6c_need(count($direct)===6,'direct_count');$expected=['2000084121'=>80026,'2000060103'=>28782,'277755'=>9351,'2000060901'=>70825,'2000108960'=>132002,'2000085082'=>108146];foreach($expected as$s=>$t)d6c_need(($direct[$s]['tv_hotel_id']??0)===$t,'direct_pair_'.$s);
require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION READ ONLY');
$sources=array_keys($direct);$targets=array_values($expected);$sp=implode(',',array_fill(0,count($sources),'?'));$tp=implode(',',array_fill(0,count($targets),'?'));
$src=d6c_rows($db,"SELECT supplier_namespace,external_hotel_id,local_hotel_id,decision_status,catalog_sha256,evidence_sha256,created_at FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id IN ($sp) ORDER BY external_hotel_id",$sources);
$occ=d6c_rows($db,"SELECT supplier_namespace,external_hotel_id,local_hotel_id,decision_status FROM andromeda_hotel_identities WHERE local_hotel_id IN ($tp) ORDER BY local_hotel_id,supplier_namespace,external_hotel_id",$targets);
$hot=d6c_rows($db,"SELECT id,name,country_id,country_name,region_name,subregion_name,category,latitude,longitude,is_active FROM catalog_hotels WHERE id IN ($tp) ORDER BY id",$targets);
$guards=[];foreach(['anex_hotel_search_mappings','anex_hotel_decisions','anex_review_pair_exclusions']as$table)$guards[$table]=d6c_rows($db,"SELECT * FROM $table WHERE anex_hotel_id=35371 OR catalog_hotel_id=80026 ORDER BY anex_hotel_id,catalog_hotel_id");
$db->rollBack();$srcBy=[];foreach($src as$r)$srcBy[(string)$r['external_hotel_id']]=$r;$occBy=[];foreach($occ as$r)$occBy[(int)$r['local_hotel_id']][]=$r;$hotBy=[];foreach($hot as$r)$hotBy[(int)$r['id']]=$r;
$rows=[];$counts=[];foreach($direct as$s=>$proof){$t=$proof['tv_hotel_id'];$r=$srcBy[$s]??null;$state=$r===null?'source_absent':(($r['decision_status']==='accepted'&&(int)$r['local_hotel_id']===$t)?'already_accepted':(($r['decision_status']==='accepted')?'accepted_other_target_protected':(($r['decision_status']==='pending'&&$r['local_hotel_id']===null)?'pending_unassigned':'existing_state_protected')));$counts[$state]=($counts[$state]??0)+1;$rows[]=['proof'=>$proof,'current_source'=>$r,'target_hotel'=>$hotBy[$t]??null,'target_occupants'=>$occBy[$t]??[],'state'=>$state,'safe_to_write_now'=>false];}
$out=['operation'=>D6C_OP,'state'=>'completed_read_only','provider_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'direct_bridge_count'=>count($direct),'state_counts'=>$counts,'rows'=>$rows,'maya_anex_guards'=>$guards,'input_v7_sha256'=>'1863e0cbac483965f859c1f00250939f77b114651e124f12e542b09de61a8947','input_v6_sha256'=>'46653546e4ae294e7e4c9e5c5c685dd21294a5fa4f867d43a261f4acab42d87b'];$rh=d6c_write($dir.'/result.json',$out);d6c_write($dir.'/receipt.json',['operation'=>D6C_OP,'state'=>'completed_read_only','result_sha256'=>$rh,'provider_calls'=>0,'database_writes'=>0,'mapping_writes'=>0]);echo json_encode(['state'=>'completed_read_only','direct_bridge_count'=>6,'state_counts'=>$counts],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";
