<?php
declare(strict_types=1);
require_once __DIR__.'/hotel_match_anexonly200_plan_v108.php';
const M111_OP='hotel-match-anexonly-tail-plan-1971-20260928-v111';
const M111_ACQ_OP='hotel-match-anexonly200-acquire-1971-20260928-v109';
const M111_ACQ_SHA='aa0365674e2f57775cbc7c5f0ab7a2d0781fc2826febc0c55214a726ea0b75a4';
function m111_main(array$a):int{
 m108_need(($a[1]??'')==='--execute','disabled');$root=(string)getenv('ANYTOUR_ROOT');$dir=(string)getenv('MATCH_OPERATION_DIR');$head=(string)getenv('MATCH_SOURCE_SHA');m108_need(is_dir($root)&&basename($root)==='anytoour.ru'&&is_dir($dir)&&basename($dir)===M111_OP&&preg_match('/^[a-f0-9]{40}$/D',$head),'scope');foreach(['result.json','receipt.json']as$f)m108_need(!file_exists($dir.'/'.$f),'no_replay');
 $ops=dirname($dir);$ledger=w84_read($ops.'/'.M108_LEDGER_OP.'/result.json',M108_LEDGER_SHA,33554432);$done=w84_read($ops.'/'.M111_ACQ_OP.'/result.json',M111_ACQ_SHA,33554432);$used=array_fill_keys(array_map('intval',$done['scope_hotel_ids']??[]),true);m108_need(count($used)===200,'prior_scope');
 require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$m=hmc4_execute(v2_data_db());$cur=[];foreach($m['rows']as$r)$cur[(int)$r['tv_hotel_id']]=$r;$reqBy=[];foreach($ledger['requests']as$q)foreach($q['hotel_ids']as$id)$reqBy[(int)$id][]=$q;$rows=[];
 foreach($ledger['rows']as$r){$id=(int)$r['tv_hotel_id'];if(isset($used[$id])||($cur[$id]['gap_bucket']??'')!=='anex_only')continue;$missing=[];foreach([18,25,43]as$op)if(in_array($op,array_map('intval',$r['missing_operator_ids']??[]),true)&&empty($r['lanes'][(string)$op]['retained_exact']))$missing[]=$op;if(!$missing)continue;$freq=[];foreach($reqBy[$id]??[]as$q){$x=$q['context']??[];$dep=(int)($x['departureId']??0);$cid=(int)($x['countryId']??0);if($dep>0&&$cid>0)$freq[$dep.'|'.$cid]=($freq[$dep.'|'.$cid]??0)+1;}arsort($freq);$k=array_key_first($freq);if(!$k)continue;[$dep,$cid]=array_map('intval',explode('|',$k));$rows[]=['tv_hotel_id'=>$id,'hotel_name'=>$r['hotel_name'],'country_id'=>$cid,'country'=>$r['country'],'departure_id'=>$dep,'departure_date'=>'2026-10-22','nights'=>7,'adults'=>2,'children_count'=>0,'child_ages_signature'=>'','missing_operator_ids'=>$missing,'gap_bucket'=>'anex_only'];}
 usort($rows,fn($x,$y)=>[$x['country'],$x['tv_hotel_id']]<=>[$y['country'],$y['tv_hotel_id']]);m108_need(count($rows)>0&&count($rows)<=100,'tail_scope');$ids=array_column($rows,'tv_hotel_id');$countries=[];foreach($rows as$r)$countries[$r['country']]=($countries[$r['country']]??0)+1;
 $out=['operation'=>M111_OP,'state'=>'completed_read_only_anexonly_tail_plan','source_sha'=>$head,'generated_at_utc'=>gmdate('c'),'current_gap_counts'=>$m['gap_bucket_counts'],'prior_scope_excluded'=>count($used),'scope_count'=>count($rows),'scope_id_sha256'=>hash('sha256',json_encode($ids,JSON_UNESCAPED_SLASHES)),'country_counts'=>$countries,'tourvisor_account'=>'TOURVISOR_ANEX_JWT','operator_filter_sent'=>false,'continue_calls'=>0,'dates_calls'=>0,'provider_http_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'rows'=>$rows];$sha=w76_save($dir.'/result.json',$out);w76_save($dir.'/receipt.json',['operation'=>M111_OP,'state'=>$out['state'],'source_sha'=>$head,'result_sha256'=>$sha,'provider_http_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true]);echo w76_json(array_diff_key($out,['rows'=>true]))."\n";return 0;
}
if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__)exit(m111_main($argv));
