<?php
declare(strict_types=1);
const OP='hotel-match-antalya-samo-first-1971-20260919-v4';
function need(bool $x,string $w):void{if(!$x)throw new RuntimeException($w);}
function norm(string $s):string{$s=function_exists('mb_strtolower')?mb_strtolower($s,'UTF-8'):strtolower($s);$s=strtr($s,['ё'=>'е']);return trim(preg_replace('/[^\p{L}\p{N}]+/u',' ',$s)??'');}
function pos(mixed $v):?string{$s=is_scalar($v)?trim((string)$v):'';return preg_match('/^[1-9][0-9]{0,31}$/D',$s)?$s:null;}
function save(string $p,array $v):string{$b=json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n";$f=fopen($p,'xb');need(is_resource($f),'open');try{need(fwrite($f,$b)===strlen($b)&&fflush($f),'write');if(function_exists('fsync'))need(fsync($f),'sync');}finally{fclose($f);}return hash('sha256',$b);}
function rows(PDO $db,string $sql,array $p=[]):array{$s=$db->prepare($sql);$s->execute($p);return $s->fetchAll(PDO::FETCH_ASSOC)?:[];}
if(in_array('--self-test',$argv??[],true)){need(norm('Анталья')==='анталья','norm');need(pos('001')===null&&pos('8365')==='8365','id');echo "ANTALYA_SAMO_FIRST_SELFTEST_OK\n";exit;}
$dir=(string)getenv('MATCH_OPERATION_DIR');$raw=(string)getenv('MATCH_RAW_DIR');$root=realpath((string)getenv('ANYTOOUR_ROOT'));need(is_dir($dir)&&basename($dir)===OP&&is_dir($raw)&&is_string($root),'runtime');
$files=glob($raw.'/raw-*.json')?:[];need(count($files)===23,'raw_count');$catalog=null;$price=[];
foreach($files as$f){$d=json_decode((string)file_get_contents($f),true,128,JSON_THROW_ON_ERROR);if(isset($d['HOTELS'])&&isset($d['TOWNTO']))$catalog=$d;if(isset($d['PRICES']))$price[]=[$f,$d];}
need(is_array($catalog),'catalog');
$town=[];foreach($catalog['TOWNTO'] as$t){$id=(string)($t['id']??'');$labels=[];foreach(['name','lName','RegionName']as$k)if(isset($t[$k]))$labels[]=norm((string)$t[$k]);$town[$id]=$labels;}
$antalya=[];foreach($catalog['HOTELS']as$h){$id=pos($h['id']??null);if(!$id)continue;$tk=(string)($h['townKey']??'');$labels=$town[$tk]??[];$is=false;foreach($labels as$l)if($l==='анталья'||$l==='antalya'||str_contains($l,'анталья')){$is=true;break;}if($is)$antalya[$id]=['samo_hotel_id'=>$id,'name'=>$h['name']??$h['lName']??null,'town_key'=>$tk,'town_labels'=>$labels,'star'=>$h['star']??$h['starLName']??null];}
need(count($antalya)>0,'antalya_empty');
$observed=[];foreach($price as[$f,$d])foreach($d['PRICES']as$r){if(!is_array($r))continue;$sid=pos($r['hotelKey']??null);if(!$sid||!isset($antalya[$sid]))continue;$orig=is_array($r['original']??null)?$r['original']:[];$op=pos($r['operatorKey']??($orig['operatorKey']??null));$native=pos($orig['hotelKey']??null);$k=implode('|',[$sid,$op??'',$native??'']);$observed[$k]=['samo_hotel_id'=>$sid,'operator_id'=>$op,'native_hotel_id'=>$native,'is_operator_hotel_key'=>$orig['isOperatorHotelKey']??null,'source_file'=>basename($f),'source_sha256'=>hash_file('sha256',$f)];}
$dbf=is_file($root.'/data/db-v1.php')?$root.'/data/db-v1.php':$root.'/v2/data/db-v1.php';require_once$dbf;$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION READ ONLY');
$ids=array_keys($antalya);$ph=implode(',',array_fill(0,count($ids),'?'));$ident=rows($db,"SELECT supplier_namespace,external_hotel_id,local_hotel_id,decision_status,evidence_sha256 FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id IN ($ph)",$ids);$db->rollBack();
$by=[];foreach($ident as$r)$by[(string)$r['external_hotel_id']]=$r;$closed=[];$front=[];$conf=[];foreach($antalya as$id=>$h){$r=$by[$id]??null;if($r&&$r['decision_status']==='accepted'&&$r['local_hotel_id']!==null)$closed[]=$h+['local_hotel_id'=>(int)$r['local_hotel_id']];elseif($r&&$r['decision_status']==='conflict')$conf[]=$h+['current'=>$r];else$front[]=$h+['current'=>$r];}
$obsBy=[];foreach($observed as$o)$obsBy[$o['samo_hotel_id']][]=$o;foreach($front as&$h)$h['operator_evidence']=$obsBy[$h['samo_hotel_id']]??[];unset($h);
$out=['operation'=>OP,'state'=>'completed_read_only','provider_calls'=>0,'tourvisor_calls'=>0,'database_writes'=>0,'antalya_catalog_hotels'=>count($antalya),'retained_price_observations'=>count($observed),'accepted_closed'=>count($closed),'conflicts'=>count($conf),'missing_or_pending'=>count($front),'frontier_with_native'=>count(array_filter($front,fn($x)=>count(array_filter($x['operator_evidence'],fn($e)=>$e['native_hotel_id']!==null))>0)),'closed'=>$closed,'conflicts_rows'=>$conf,'frontier'=>$front];
$rh=save($dir.'/result.json',$out);save($dir.'/receipt.json',['operation'=>OP,'state'=>'completed_read_only','result_sha256'=>$rh,'provider_calls'=>0,'tourvisor_calls'=>0,'database_writes'=>0]);echo json_encode(['state'=>'completed_read_only','antalya_catalog_hotels'=>$out['antalya_catalog_hotels'],'accepted_closed'=>$out['accepted_closed'],'missing_or_pending'=>$out['missing_or_pending'],'frontier_with_native'=>$out['frontier_with_native'],'result_sha256'=>$rh],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n";
