<?php
declare(strict_types=1);
/** MATCH-only guarded one-row apply from strict public-operator exact-local evidence. */
const HMPEA_OP='hotel-match-public-operator-exact-local-apply-1971-20260917-v1';
const HMPEA_PREFLIGHT_SHA='088b27b9306f6d2cfcf7afad0accfd03f362541e9c70fc9d92228c556c82465b';
const HMPEA_NS='operator_342';
const HMPEA_EXTERNAL='27835';
const HMPEA_ANDROMEDA='2000073592';
const HMPEA_LOCAL=28649;
const HMPEA_COUNTRY=4;
const HMPEA_NAME='Taxim Town Hotel';
const HMPEA_GEO='Таксим';
const HMPEA_OPERATOR_SHA='eec3eadc1e4bd40710c7f9cdcac622cdd51ba57faa5e10d63c7b2c00d5652316';
const HMPEA_ANDROMEDA_SHA='6a368619ab60dfc489bea04a453eff2f1c8a30336437f442ca5b9f52f536442f';
const HMPEA_PUBLIC_URL='https://intourist.ru/info/turkey/stambul/taksim/hotel/taxim-town-hotel-taksim';
function hmpea_req(bool $ok,string $why):void{if(!$ok)throw new RuntimeException($why);}
function hmpea_json(array $x):string{return json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";}
function hmpea_write(string $p,array $x):string{$raw=hmpea_json($x);$f=@fopen($p,'x+b');hmpea_req(is_resource($f),'exclusive_output');try{hmpea_req(fwrite($f,$raw)===strlen($raw)&&fflush($f),'output_write');if(function_exists('fsync'))hmpea_req(fsync($f),'output_sync');rewind($f);hmpea_req(stream_get_contents($f)===$raw,'output_readback');}finally{fclose($f);}return hash('sha256',$raw);}
function hmpea_read(string $p,int $max=32768):array{hmpea_req(is_file($p)&&!is_link($p)&&realpath($p)===$p,'input_path');$raw=file_get_contents($p);hmpea_req(is_string($raw)&&strlen($raw)<=$max,'input_size');$x=json_decode($raw,true,64,JSON_THROW_ON_ERROR);hmpea_req(is_array($x),'input_shape');return$x;}
function hmpea_q(PDO $db,string $sql,array $args=[]):array{$s=$db->prepare($sql);$s->execute(array_values($args));$r=$s->fetchAll(PDO::FETCH_ASSOC);hmpea_req(count($r)<100000,'query_budget');return$r;}
function hmpea_protected($v,string $key='',int $depth=0):bool{if($depth>20)return true;$s=preg_match('/manual|exclude|exclusion|conflict|reject|review|protect/i',$key)===1;if(is_array($v)){if($s&&$v!==[])return true;foreach($v as$k=>$x)if(hmpea_protected($x,(string)$k,$depth+1))return true;return false;}if(!$s||$v===null)return false;if(is_bool($v))return$v;if(is_numeric($v))return(float)$v!=0;if(is_string($v))return!in_array(strtolower(trim($v)),['','false','none','no','null'],true);return true;}
function hmpea_lower(string $s):string{if(function_exists('mb_strtolower'))return mb_strtolower($s,'UTF-8');return strtolower(strtr($s,['А'=>'а','Б'=>'б','В'=>'в','Г'=>'г','Д'=>'д','Е'=>'е','Ё'=>'ё','Ж'=>'ж','З'=>'з','И'=>'и','Й'=>'й','К'=>'к','Л'=>'л','М'=>'м','Н'=>'н','О'=>'о','П'=>'п','Р'=>'р','С'=>'с','Т'=>'т','У'=>'у','Ф'=>'ф','Х'=>'х','Ц'=>'ц','Ч'=>'ч','Ш'=>'ш','Щ'=>'щ','Ъ'=>'ъ','Ы'=>'ы','Ь'=>'ь','Э'=>'э','Ю'=>'ю','Я'=>'я']));}
function hmpea_name_key(string $s):string{$s=preg_replace('/\s*\((?:ex|ех)\.?[^)]*\)\s*$/iu','',$s)??$s;$parts=preg_split('/[^\p{L}\p{N}]+/u',hmpea_lower(trim($s)),-1,PREG_SPLIT_NO_EMPTY);if(!is_array($parts))return'';$parts=array_values(array_filter($parts,static fn($x)=>$x!=='hotel'));return implode('',$parts);}
function hmpea_geo_key(string $s):string{return preg_replace('/[^\p{L}\p{N}]+/u','',hmpea_lower(trim($s)))??'';}
function hmpea_names(array $e):array{$src=is_array($e['source']??null)?$e['source']:$e;$out=[];foreach(['name','lName','hotel_name','hotelName','original_name']as$k){$v=$src[$k]??null;if(is_string($v)&&trim($v)!=='')$out[hmpea_name_key($v)]=trim($v);}return$out;}
function hmpea_bridge(array $e):?array{$b=$e['provider_bridges']??null;if(!is_array($b))return null;foreach($b as$x)if(is_array($x)&&(string)($x['andromeda_hotel_id']??'')===HMPEA_ANDROMEDA)return$x;return null;}
function hmpea_points($v,array &$o,int $d=0):void{hmpea_req($d<=32,'coordinate_depth');if(!is_array($v))return;$a=$v['latitude']??$v['lat']??null;$b=$v['longitude']??$v['lon']??$v['lng']??null;if(is_numeric($a)&&is_numeric($b)){$a=(float)$a;$b=(float)$b;if(is_finite($a)&&is_finite($b)&&abs($a)<=90&&abs($b)<=180&&($a!=0||$b!=0))$o[]=[$a,$b];}foreach($v as$x)if(is_array($x))hmpea_points($x,$o,$d+1);}
function hmpea_km(array $a,array $b):float{[$x,$y,$u,$v]=array_map('deg2rad',[$a[0],$a[1],$b[0],$b[1]]);$h=sin(($u-$x)/2)**2+cos($x)*cos($u)*sin(($v-$y)/2)**2;return 6371.0088*2*asin(sqrt(min(1.0,max(0.0,$h))));}
function hmpea_pending(PDO $db):array{$out=[];$total=0;foreach(['andromeda_catalog','operator_315','operator_342','operator_5']as$ns){$r=hmpea_q($db,"SELECT COUNT(*) n FROM andromeda_hotel_identities WHERE supplier_namespace=? AND decision_status='pending' AND local_hotel_id IS NULL",[$ns]);$out[$ns]=(int)$r[0]['n'];$total+=$out[$ns];}return[$out,$total];}
function hmpea_main():void{
 hmpea_req(PHP_SAPI==='cli'&&getenv('MATCH_OPERATION_ID')===HMPEA_OP,'operation_guard');$sha=(string)getenv('MATCH_SOURCE_SHA');hmpea_req(preg_match('/^[a-f0-9]{40}$/D',$sha)===1,'source_guard');$dir=(string)getenv('HOME').'/.anytoour-match/operations/'.HMPEA_OP;$res=hmpea_read($dir.'/reservation.json');hmpea_req(($res['operation_id']??'')===HMPEA_OP&&($res['source_sha']??'')===$sha&&($res['state']??'')==='reserved_before_db_access'&&($res['preflight_result_sha256']??'')===HMPEA_PREFLIGHT_SHA,'reservation_guard');
 $out=['operation_id'=>HMPEA_OP,'source_sha'=>$sha,'state'=>'failed_no_replay','no_replay'=>true,'preflight_result_sha256'=>HMPEA_PREFLIGHT_SHA,'planned_count'=>1,'supplier_calls'=>0,'tourvisor_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'post_commit_readback_verified'=>false];$db=null;$commitAttempt=false;$committed=false;$holds=[];$phase='bootstrap';ob_start();try{
  $root=realpath(getcwd());hmpea_req(is_string($root)&&basename($root)==='anytoour.ru','root_guard');$bp=$root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');hmpea_req(realpath($bp)===$bp&&!is_link($bp),'bootstrap_path');require_once$bp;$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET SESSION innodb_lock_wait_timeout=20');$db->exec('SET TRANSACTION ISOLATION LEVEL SERIALIZABLE');$db->beginTransaction();$phase='transaction_recheck';
  $eng=hmpea_q($db,"SELECT TABLE_NAME,ENGINE FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME IN ('andromeda_hotel_identities','catalog_hotels','hotel_aliases') ORDER BY TABLE_NAME");hmpea_req(count($eng)===3,'table_contract');foreach($eng as$t)hmpea_req(strtoupper((string)$t['ENGINE'])==='INNODB','nontransactional_table');
  $sr=hmpea_q($db,"SELECT local_hotel_id,decision_status,evidence_sha256,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace=? AND external_hotel_id=? FOR UPDATE",[HMPEA_NS,HMPEA_EXTERNAL]);if(count($sr)!==1)$holds[]='operator_row_missing_or_duplicate';$s=$sr[0]??null;$oe=[];$bridge=null;if($s){if((string)$s['decision_status']!=='pending'||$s['local_hotel_id']!==null)$holds[]='operator_not_pending_null';if(!hash_equals(HMPEA_OPERATOR_SHA,(string)$s['evidence_sha256']))$holds[]='operator_evidence_changed';try{$oe=json_decode((string)$s['evidence_json'],true,64,JSON_THROW_ON_ERROR);}catch(Throwable $x){$oe=[];$holds[]='operator_evidence_json';}if(!is_array($oe)){$oe=[];$holds[]='operator_evidence_shape';}if(hmpea_protected($oe))$holds[]='operator_protected';$bridge=hmpea_bridge($oe);if(!is_array($bridge))$holds[]='operator_native_bridge_missing';else{if((string)($bridge['andromeda_hotel_id']??'')!==HMPEA_ANDROMEDA)$holds[]='bridge_andromeda_changed';if((int)($bridge['country_id']??0)!==HMPEA_COUNTRY)$holds[]='bridge_country_changed';if(hmpea_name_key((string)($bridge['hotel_name']??''))!==hmpea_name_key(HMPEA_NAME))$holds[]='bridge_name_changed';}}
  $ar=hmpea_q($db,"SELECT local_hotel_id,decision_status,evidence_sha256,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=? FOR UPDATE",[HMPEA_ANDROMEDA]);if(count($ar)!==1)$holds[]='andromeda_row_missing_or_duplicate';$a=$ar[0]??null;$ae=[];if($a){if((string)$a['decision_status']!=='pending'||$a['local_hotel_id']!==null)$holds[]='andromeda_not_pending_null';if(!hash_equals(HMPEA_ANDROMEDA_SHA,(string)$a['evidence_sha256']))$holds[]='andromeda_evidence_changed';try{$ae=json_decode((string)$a['evidence_json'],true,64,JSON_THROW_ON_ERROR);}catch(Throwable $x){$ae=[];$holds[]='andromeda_evidence_json';}if(!is_array($ae)){$ae=[];$holds[]='andromeda_evidence_shape';}if(hmpea_protected($ae))$holds[]='andromeda_protected';if(!isset(hmpea_names($ae)[hmpea_name_key(HMPEA_NAME)]))$holds[]='andromeda_name_not_exact';}
  $key=hmpea_name_key(HMPEA_NAME);$matches=[];foreach(hmpea_q($db,"SELECT id,country_id,region_name,subregion_name,name,latitude,longitude FROM catalog_hotels WHERE is_active=1 AND country_id=? ORDER BY id",[HMPEA_COUNTRY])as$h){if(hmpea_name_key((string)$h['name'])===$key)$matches[(int)$h['id']]=$h;}foreach(hmpea_q($db,"SELECT a.hotel_id,a.alias FROM hotel_aliases a JOIN catalog_hotels h ON h.id=a.hotel_id WHERE h.is_active=1 AND h.country_id=? ORDER BY a.hotel_id,a.id",[HMPEA_COUNTRY])as$al){if(hmpea_name_key((string)$al['alias'])===$key&&!isset($matches[(int)$al['hotel_id']])){$h=hmpea_q($db,"SELECT id,country_id,region_name,subregion_name,name,latitude,longitude FROM catalog_hotels WHERE id=? AND is_active=1",[(int)$al['hotel_id']]);if(count($h)===1)$matches[(int)$al['hotel_id']]=$h[0];}}
  ksort($matches,SORT_NUMERIC);if(count($matches)!==1||!isset($matches[HMPEA_LOCAL]))$holds[]='exact_local_uniqueness_changed';$h=$matches[HMPEA_LOCAL]??null;if($h){if((int)$h['country_id']!==HMPEA_COUNTRY)$holds[]='target_country_changed';$g=hmpea_geo_key(HMPEA_GEO);if($g===''||($g!==hmpea_geo_key((string)$h['region_name'])&&$g!==hmpea_geo_key((string)$h['subregion_name'])))$holds[]='public_geo_not_exact_region_or_subregion';}
  if(hmpea_q($db,"SELECT external_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace=? AND decision_status='accepted' AND local_hotel_id=? AND external_hotel_id<>? FOR UPDATE",[HMPEA_NS,HMPEA_LOCAL,HMPEA_EXTERNAL]))$holds[]='operator_target_occupied';if(hmpea_q($db,"SELECT external_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id=? AND external_hotel_id<>? FOR UPDATE",[HMPEA_LOCAL,HMPEA_ANDROMEDA]))$holds[]='andromeda_target_occupied';
  $pts=[];hmpea_points($oe,$pts);hmpea_points($ae,$pts);$dist=[];if($pts){if(!$h||!is_numeric($h['latitude'])||!is_numeric($h['longitude']))$holds[]='target_coordinate_missing_for_source_points';else{$target=[(float)$h['latitude'],(float)$h['longitude']];foreach($pts as$p){$d=hmpea_km($p,$target);$dist[]=round($d,3);if($d>5)$holds[]='coordinate_conflict_gt5km';}}}
  $holds=array_values(array_unique($holds));hmpea_write($dir.'/precommit.json',['operation_id'=>HMPEA_OP,'source_sha'=>$sha,'state'=>'validated_before_commit','holds'=>$holds,'target'=>['supplier_namespace'=>HMPEA_NS,'external_hotel_id'=>HMPEA_EXTERNAL,'andromeda_hotel_id'=>HMPEA_ANDROMEDA,'local_hotel_id'=>HMPEA_LOCAL],'coordinate_distances_km'=>$dist,'no_replay'=>true]);
  if($holds){$db->rollBack();$out['state']='completed_no_write';$out['holds']=$holds;$out['committed_count']=0;}else{
   $oe['public_operator_exact_local_acceptance']=['operation_id'=>HMPEA_OP,'source_sha'=>$sha,'preflight_result_sha256'=>HMPEA_PREFLIGHT_SHA,'prior_operator_evidence_sha256'=>HMPEA_OPERATOR_SHA,'andromeda_hotel_id'=>HMPEA_ANDROMEDA,'andromeda_evidence_sha256'=>HMPEA_ANDROMEDA_SHA,'local_hotel_id'=>HMPEA_LOCAL,'country_id'=>HMPEA_COUNTRY,'official_operator_url'=>HMPEA_PUBLIC_URL,'official_operator_name'=>HMPEA_NAME,'official_operator_geo'=>HMPEA_GEO,'identity_chain'=>'operator_native_bridge + independent_operator_public_name_geo + exact_current_local_name_alias_geo','coordinate_distances_km'=>$dist,'transaction_time_guards_verified'=>true];$json=hmpea_json($oe);$newSha=hash('sha256',$json);$up=$db->prepare("UPDATE andromeda_hotel_identities SET local_hotel_id=?,decision_status='accepted',evidence_sha256=?,evidence_json=? WHERE supplier_namespace=? AND external_hotel_id=? AND decision_status='pending' AND local_hotel_id IS NULL AND evidence_sha256=?");$up->execute([HMPEA_LOCAL,$newSha,$json,HMPEA_NS,HMPEA_EXTERNAL,HMPEA_OPERATOR_SHA]);hmpea_req($up->rowCount()===1,'conditional_write_count');$commitAttempt=true;$db->commit();$committed=true;$phase='post_commit_readback';$rr=hmpea_q($db,"SELECT local_hotel_id,decision_status,evidence_sha256,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace=? AND external_hotel_id=?",[HMPEA_NS,HMPEA_EXTERNAL]);hmpea_req(count($rr)===1,'readback_count');$r=$rr[0];$re=json_decode((string)$r['evidence_json'],true,64,JSON_THROW_ON_ERROR);hmpea_req((int)$r['local_hotel_id']===HMPEA_LOCAL&&(string)$r['decision_status']==='accepted'&&hash_equals($newSha,(string)$r['evidence_sha256'])&&hash_equals($newSha,hash('sha256',(string)$r['evidence_json']))&&($re['public_operator_exact_local_acceptance']['operation_id']??'')===HMPEA_OP,'post_commit_mismatch');$out['state']='completed_committed';$out['committed_count']=1;$out['database_writes']=1;$out['mapping_writes']=1;$out['post_commit_readback_verified']=true;$out['readback']=['supplier_namespace'=>HMPEA_NS,'external_hotel_id'=>HMPEA_EXTERNAL,'andromeda_hotel_id'=>HMPEA_ANDROMEDA,'local_hotel_id'=>HMPEA_LOCAL,'decision_status'=>'accepted','evidence_sha256'=>$newSha];}
  [$pending,$total]=hmpea_pending($db);$out['post_pending_by_namespace']=$pending;$out['post_pending_total']=$total;$out['completed_at_utc']=gmdate('c');
 }catch(Throwable $x){if($db instanceof PDO&&$db->inTransaction())$db->rollBack();if($commitAttempt&&!$committed)$out['state']='unknown_commit_outcome_no_replay';elseif($committed)$out['state']='committed_readback_failed_no_replay';$out['error_phase']=$phase;$out['error_code']=preg_match('/^[a-z0-9_]{2,120}$/i',$x->getMessage())?$x->getMessage():'sanitized_failure';}while(ob_get_level())ob_end_clean();$dig=hmpea_write($dir.'/result.json',$out);hmpea_write($dir.'/receipt.json',['operation_id'=>HMPEA_OP,'source_sha'=>$sha,'state'=>$out['state'],'result_sha256'=>$dig,'readback_verified'=>!in_array($out['state'],['unknown_commit_outcome_no_replay','committed_readback_failed_no_replay'],true),'no_replay'=>true,'database_writes'=>$out['database_writes'],'mapping_writes'=>$out['mapping_writes'],'supplier_calls'=>0,'tourvisor_calls'=>0]);echo hmpea_json(['state'=>$out['state'],'committed_count'=>$out['committed_count']??0,'holds'=>$out['holds']??[],'post_pending_total'=>$out['post_pending_total']??null,'post_pending_by_namespace'=>$out['post_pending_by_namespace']??[],'post_commit_readback_verified'=>$out['post_commit_readback_verified'],'result_sha256'=>$dig]);if(!in_array($out['state'],['completed_committed','completed_no_write'],true))exit(2);
}
if(in_array('--self-test',$argv??[],true)){hmpea_req(hmpea_name_key('Taxim Town Hotel')==='taximtown','name');hmpea_req(hmpea_name_key('TAXIM TOWN')==='taximtown','target');hmpea_req(hmpea_geo_key('Таксим')==='таксим','geo');hmpea_req(hmpea_protected(['manual'=>true])&&!hmpea_protected(['conflict'=>false]),'protected');echo"4 exact-local apply self-tests PASS\n";exit;}
hmpea_main();
