<?php
declare(strict_types=1);
/** MATCH #1971: plan a non-replay fresh multi-operator acquisition over sealed non-ANEX held dossiers. */
const HMAP_OP='hotel-match-nonanex-multiop-acquisition-plan-1971-20260916-v1';
const HMAP_PARENT='hotel-match-received-nonanex-source-geo-current-1971-20260916-v5';
const HMAP_PARENT_SHA256='d4aa102e6e52e81fdf2116f4514aa28eaa9ed9fb3db99984d4434fead3a2d21b';
const HMAP_DAY='20260916';
const HMAP_CONSERVATIVE_TV_CAP=300;
function hmap_json(array $v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
function hmap_write(string $p,array $v):string{$raw=hmap_json($v)."\n";$f=@fopen($p,'x');if(!$f)throw new RuntimeException('durable_create_failed');try{if(fwrite($f,$raw)!==strlen($raw))throw new RuntimeException('durable_write_failed');fflush($f);}finally{fclose($f);}if(file_get_contents($p)!==$raw)throw new RuntimeException('durable_readback_failed');return hash('sha256',$raw);}
function hmap_db_path(string $r):string{foreach([$r.'/data/db-v1.php',$r.'/v2/data/db-v1.php']as $p)if(is_file($p))return $p;throw new RuntimeException('db_bootstrap_missing');}
function hmap_select(PDO $d,string $q,array $p=[]):array{$s=$d->prepare($q);$s->execute($p);return $s->fetchAll(PDO::FETCH_ASSOC)?:[];}
function hmap_decode(string $p):?array{$raw=@file_get_contents($p);if($raw===false||$raw==='')return null;try{$x=json_decode($raw,true,128,JSON_THROW_ON_ERROR);return is_array($x)?$x:null;}catch(Throwable){return null;}}
function hmap_protected($v,int $depth=0):bool{if($depth>12||!is_array($v))return false;foreach($v as $k=>$x){$lk=mb_strtolower((string)$k,'UTF-8');if(in_array($lk,['manual','manual_decision','excluded','exclusion','conflict','protected','rejected'],true)){if($x===true||$x===1||$x==='1')return true;if(is_string($x)&&trim($x)!==''&&!in_array(mb_strtolower(trim($x),'UTF-8'),['false','none','null','0'],true))return true;}if(is_array($x)&&hmap_protected($x,$depth+1))return true;}return false;}
function hmap_call_max($v,string $op,int $depth=0):int{if($depth>16||!is_array($v))return 0;$m=0;foreach($v as $k=>$x){$lk=strtolower((string)$k);if(is_scalar($x)&&is_numeric((string)$x)){if(str_contains($lk,'tourvisor')&&str_contains($lk,'call'))$m=max($m,(int)$x);elseif($lk==='client_invocations'&&(str_contains($op,'tourvisor')||str_contains($op,'tv-')||str_contains($op,'-tv-')||str_contains($op,'multiop')||str_contains($op,'provider')))$m=max($m,(int)$x);}if(is_array($x))$m=max($m,hmap_call_max($x,$op,$depth+1));}return $m;}
function hmap_history_pairs($v,string $op,array &$pairs,?int $local=null,?string $date=null,int $depth=0):void{if($depth>14||!is_array($v))return;if(!array_is_list($v)){foreach(['local_hotel_id','search_hotel_id','tourvisor_hotel_id','detail_hotel_id']as $k)if(isset($v[$k])&&is_numeric((string)$v[$k])&&(int)$v[$k]>0){$local=(int)$v[$k];break;}foreach(['date','target_date','search_date']as $k)if(isset($v[$k])&&is_scalar($v[$k])&&preg_match('/^2026-[0-9]{2}-[0-9]{2}$/D',trim((string)$v[$k]))){$date=trim((string)$v[$k]);break;}if($local!==null&&$date!==null)$pairs[$local][$date][$op]=true;}foreach($v as $x)if(is_array($x))hmap_history_pairs($x,$op,$pairs,$local,$date,$depth+1);}
if(in_array('--self-test',$argv??[],true)){$x=['tourvisor_calls'=>7,'nested'=>['client_invocations'=>9]];if(hmap_call_max($x,'hotel-match-tv-test')!==9)throw new RuntimeException('call_test');$p=[];hmap_history_pairs(['date'=>'2026-11-15','rows'=>[['local_hotel_id'=>123]]],'op',$p);if(!isset($p[123]['2026-11-15']['op']))throw new RuntimeException('pair_test');echo "hotel_match_nonanex_multiop_acquisition_plan_v1 self-test PASS\n";exit(0);}
$op=(string)getenv('OPERATION_ID');$sha=(string)getenv('MATCH_SOURCE_SHA');if($op!==HMAP_OP||!preg_match('/^[0-9a-f]{40}$/D',$sha))throw new RuntimeException('operation_guard');$root=(string)realpath(getcwd());if($root===''||basename($root)!=='anytoour.ru')throw new RuntimeException('root_guard');$base=rtrim((string)getenv('HOME'),'/').'/.anytoour-match/operations';if(!is_dir($base))throw new RuntimeException('operations_root_missing');$dir=$base.'/'.$op;if(!mkdir($dir,0700))throw new RuntimeException('operation_exists');hmap_write($dir.'/reservation.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'reserved_before_history_and_db_access','parent_operation'=>HMAP_PARENT,'read_only'=>true,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);
$db=null;try{
 $parentPath=$base.'/'.HMAP_PARENT.'/result.json';$parent=hmap_decode($parentPath);if($parent===null||($parent['state']??'')!=='completed_read_only'||(int)($parent['plan_count']??0)!==93)throw new RuntimeException('parent_result_invalid');if(hash('sha256',(string)file_get_contents($parentPath))!==HMAP_PARENT_SHA256)throw new RuntimeException('parent_result_hash_changed');$held=[];foreach($parent['rows']??[] as $r){if(!is_array($r)||($r['route']??'')!=='held')continue;$ok=(string)($r['operator_key']??'');if(!in_array($ok,['115','315','342'],true))continue;$native=(string)($r['native_hotel_id']??'');$local=(int)($r['local_hotel_id']??0);if($native!==''&&$local>0)$held[$ok.'|'.$native]=$r;}if(count($held)!==68)throw new RuntimeException('held_count_changed');
 $todayCalls=0;$operationCalls=[];$seen=[];$dirsScanned=0;$filesScanned=0;foreach(glob($base.'/*',GLOB_ONLYDIR)?:[] as $od){$bn=basename($od);if($bn===$op)continue;$dirsScanned++;$max=0;foreach(glob($od.'/*.json')?:[] as $fp){$name=basename($fp);if($name==='reservation.json')continue;$v=hmap_decode($fp);if($v===null)continue;$filesScanned++;$max=max($max,hmap_call_max($v,$bn));hmap_history_pairs($v,$bn,$seen);}if(str_contains($bn,HMAP_DAY)&&$max>0){$operationCalls[$bn]=$max;$todayCalls+=$max;}}ksort($operationCalls);
 require_once hmap_db_path($root);$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');$locals=array_values(array_unique(array_map(static fn($r)=>(int)$r['local_hotel_id'],$held)));$natives=array_values(array_unique(array_map(static fn($r)=>(string)$r['native_hotel_id'],$held)));$phL=implode(',',array_fill(0,count($locals),'?'));$catalog=[];foreach(hmap_select($db,"SELECT id,country_id,name,is_active FROM catalog_hotels WHERE id IN ($phL)",$locals) as $r)$catalog[(int)$r['id']]=$r;$countries=[];foreach(hmap_select($db,'SELECT id,name,slug FROM catalog_countries')as $r)$countries[(int)$r['id']]=['name'=>(string)$r['name'],'slug'=>(string)$r['slug']];$phN=implode(',',array_fill(0,count($natives),'?'));$ids=hmap_select($db,"SELECT supplier_namespace,external_hotel_id,local_hotel_id,decision_status,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace IN ('operator_115','operator_315','operator_342') AND external_hotel_id IN ($phN)",$natives);$db->exec('ROLLBACK');$by=[];foreach($ids as $r)$by[(string)$r['supplier_namespace'].'|'.(string)$r['external_hotel_id']][]=$r;
 $eligible=[];$routes=[];$groups=[];foreach($held as $d){$ok=(string)$d['operator_key'];$ns='operator_'.$ok;$native=(string)$d['native_hotel_id'];$local=(int)$d['local_hotel_id'];$holds=array_values(array_map('strval',is_array($d['holds']??null)?$d['holds']:[]));$cat=$catalog[$local]??null;$current=$by[$ns.'|'.$native]??[];$pending=false;$protected=false;$accepted=false;$other=false;foreach($current as $cr){$lid=$cr['local_hotel_id']===null?null:(int)$cr['local_hotel_id'];$st=(string)($cr['decision_status']??'');if($st==='pending'&&$lid===null)$pending=true;if($st==='accepted'&&$lid===$local)$accepted=true;if($lid!==null&&$lid!==$local)$other=true;try{$ev=json_decode((string)($cr['evidence_json']??''),true,128,JSON_THROW_ON_ERROR);if(is_array($ev)&&hmap_protected($ev))$protected=true;}catch(Throwable){}}
 $reason='eligible_fresh_multiop';if($cat===null||(int)($cat['is_active']??0)!==1)$reason='inactive_or_missing_target';elseif($accepted)$reason='already_mapped_same';elseif($other)$reason='current_native_other_local';elseif(!$pending)$reason='source_not_pending_null';elseif($protected)$reason='current_protected';elseif(count(array_diff($holds,['countrywide_exact_alias_not_unique_at_target']))>0)$reason='prior_non_name_hold';$routes[$reason]=($routes[$reason]??0)+1;$row=['route'=>$reason,'operator_key'=>$ok,'supplier_namespace'=>$ns,'native_hotel_id'=>$native,'andromeda_hotel_id'=>(string)($d['andromeda_hotel_id']??''),'local_hotel_id'=>$local,'local_hotel_name'=>$cat['name']??null,'country_id'=>$cat===null?null:(int)$cat['country_id'],'country_name'=>$cat===null?null:($countries[(int)$cat['country_id']]['name']??null),'country_slug'=>$cat===null?null:($countries[(int)$cat['country_id']]['slug']??null),'frequency'=>(int)($d['frequency']??0),'prior_holds'=>$holds,'previous_search_dates'=>array_keys($seen[$local]??[])];if($reason==='eligible_fresh_multiop'){$eligible[]=$row;$cid=(int)$cat['country_id'];$groups[$cid]['country_id']=$cid;$groups[$cid]['country_name']=$row['country_name'];$groups[$cid]['country_slug']=$row['country_slug'];$groups[$cid]['frequency']=($groups[$cid]['frequency']??0)+$row['frequency'];$groups[$cid]['rows'][]=$row;}}
 ksort($routes);$batch=[];foreach($groups as $cid=>$g){usort($g['rows'],static fn($a,$b)=>($b['frequency']<=>$a['frequency'])?:($a['local_hotel_id']<=>$b['local_hotel_id']));$unique=[];$top=[];foreach($g['rows'] as $r){$lid=$r['local_hotel_id'];if(isset($unique[$lid]))continue;$unique[$lid]=true;if(count($top)<30)$top[]=$r;}$batch[]=['country_id'=>$cid,'country_name'=>$g['country_name'],'country_slug'=>$g['country_slug'],'eligible_rows'=>count($g['rows']),'unique_local_count'=>count($unique),'frequency'=>$g['frequency'],'bounded_batch_count'=>count($top),'bounded_batch_frequency'=>array_sum(array_map(static fn($r)=>(int)$r['frequency'],$top)),'bounded_batch'=>$top];}usort($batch,static fn($a,$b)=>($b['bounded_batch_frequency']<=>$a['bounded_batch_frequency'])?:($b['unique_local_count']<=>$a['unique_local_count']));$remaining=max(0,HMAP_CONSERVATIVE_TV_CAP-$todayCalls);
 $result=['schema'=>'hotel-match-nonanex-multiop-acquisition-plan/1','operation_id'=>$op,'source_sha'=>$sha,'state'=>'completed_read_only','parent_operation'=>HMAP_PARENT,'held_input_count'=>count($held),'held_frequency'=>array_sum(array_map(static fn($r)=>(int)$r['frequency'],$held)),'eligible_count'=>count($eligible),'eligible_frequency'=>array_sum(array_map(static fn($r)=>(int)$r['frequency'],$eligible)),'route_counts'=>$routes,'country_batches'=>$batch,'history_operation_dirs_scanned'=>$dirsScanned,'history_json_files_scanned'=>$filesScanned,'same_day_tourvisor_calls_by_operation'=>$operationCalls,'same_day_tourvisor_calls_detected'=>$todayCalls,'conservative_daily_cap'=>HMAP_CONSERVATIVE_TV_CAP,'conservative_remaining_calls'=>$remaining,'max_one_batch_calls'=>39,'one_batch_quota_safe'=>$remaining>=39,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'booking_calls'=>0,'lead_calls'=>0,'safe_to_write_now'=>false,'no_replay'=>true];$digest=hmap_write($dir.'/result.json',$result);hmap_write($dir.'/receipt.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'completed_read_only','result_sha256'=>$digest,'readback_verified'=>hash('sha256',(string)file_get_contents($dir.'/result.json'))===$digest,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);echo hmap_json(['state'=>'completed_read_only','eligible_count'=>count($eligible),'eligible_frequency'=>$result['eligible_frequency'],'country_batches'=>array_map(static fn($b)=>['country_id'=>$b['country_id'],'country_name'=>$b['country_name'],'unique_local_count'=>$b['unique_local_count'],'frequency'=>$b['frequency'],'bounded_batch_count'=>$b['bounded_batch_count'],'bounded_batch_frequency'=>$b['bounded_batch_frequency']],$batch),'same_day_tourvisor_calls_detected'=>$todayCalls,'conservative_remaining_calls'=>$remaining,'one_batch_quota_safe'=>$remaining>=39])."\n";
}catch(Throwable $e){if($db instanceof PDO&&$db->inTransaction())$db->rollBack();$f=['operation_id'=>$op,'source_sha'=>$sha,'state'=>'failed_read_only','error_class'=>get_class($e),'error_sha256'=>hash('sha256',$e->getMessage()),'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true];$digest=hmap_write($dir.'/failure.json',$f);hmap_write($dir.'/receipt.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'failed_read_only','failure_sha256'=>$digest,'readback_verified'=>true,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);fwrite(STDERR,"HMAP_FAILED\n");exit(2);}
