<?php
declare(strict_types=1);
/* MATCH-only mass identity evidence. Queue is server-CURRENT read-only; provider phase never writes DB. */
const AME_OP='hotel-match-andromeda-operator-evidence-mass-1971-20260915-v1';
const AME_MAX_PRICE_CALLS=500;
function ame_json(array $v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";}
function ame_write(string $file,array $v):string{$raw=ame_json($v);$f=@fopen($file,'x+b');if(!$f)throw new RuntimeException('exclusive_file');try{if(fwrite($f,$raw)!==strlen($raw)||!fflush($f))throw new RuntimeException('write');if(function_exists('fsync')&&!fsync($f))throw new RuntimeException('sync');rewind($f);if(stream_get_contents($f)!==$raw)throw new RuntimeException('readback');}finally{fclose($f);}return hash('sha256',$raw);}
function ame_chunks(array $ids):array{$out=[];$part=[];foreach($ids as $id){$id=(string)$id;if(!preg_match('/^[1-9][0-9]{0,19}$/D',$id))throw new RuntimeException('target_id');if($part&&(count($part)>=30||strlen(implode(',',array_merge($part,[$id])))>300)){$out[]=$part;$part=[];}$part[]=$id;}if($part)$out[]=$part;return$out;}
function ame_native_fact(array $r,array $wanted,string $operator,int $country,string $request,string $response):?array{
    $id=(string)($r['hotelKey']??'');if(!isset($wanted[$id])||(string)($r['operatorKey']??'')!==$operator)return null;
    if(!array_key_exists('isOperatorHotelKey',$r)||!in_array($r['isOperatorHotelKey'],[0,'0'],true))return null;
    $native=$r['original']['hotelKey']??null;$name=$r['hotel']??null;$original=$r['original']['hotel']??null;
    if((!is_int($native)&&!is_string($native))||!preg_match('/^[A-Za-z0-9_.-]{1,32}$/D',(string)$native)||(string)$native==='0'||!is_string($name)||trim($name)===''||!is_string($original)||trim($original)==='')return null;
    if(preg_match('/roulette|fortuna|фортуна|рулетк|excursion|экскурсион/ui',$name.' '.$original))return null;
    return['operator_key'=>$operator,'native_hotel_id'=>(string)$native,'andromeda_hotel_id'=>$id,'country_id'=>$country,'hotel_name'=>mb_substr($name,0,512),'original_name'=>mb_substr($original,0,512),'town'=>is_string($r['town']??null)?mb_substr($r['town'],0,200):null,'operator_name'=>is_string($r['operator']??null)?mb_substr($r['operator'],0,200):null,'is_operator_hotel_key'=>false,'action'=>'price','request_sha256'=>$request,'response_sha256'=>$response,'source'=>'live_price_mass'];
}
function ame_queue():void{
    putenv('MATCH_TEST_LIBRARY=1');require_once __DIR__.'/hotel_match_live_residual_current_review.php';
    $op=(string)getenv('MATCH_OPERATION_ID');$sha=(string)getenv('MATCH_SOURCE_SHA');if($op!==AME_OP||!preg_match('/^[0-9a-f]{40}$/D',$sha))throw new RuntimeException('operation_environment');
    $home=(string)getenv('HOME');$dir=$home.'/.anytoour-match/operations/'.AME_OP;$res=mcr_evidence((string)@file_get_contents($dir.'/reservation.json'));if(($res['operation_id']??'')!==AME_OP||($res['source_sha']??'')!==$sha||($res['state']??'')!=='reserved_before_db_access')throw new RuntimeException('reservation');
    $root=realpath(getcwd());if(!$root||basename($root)!=='anytoour.ru')throw new RuntimeException('root');require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION READ ONLY');
    try{
        $core=[];foreach(mcr_query($db,'SELECT id,name FROM catalog_countries WHERE is_active=1 ORDER BY id') as $c)if(mcr_is_core8_name((string)$c['name']))$core[(int)$c['id']]=(string)$c['name'];if(count($core)<6)throw new RuntimeException('core8');
        $marks=implode(',',array_fill(0,count($core),'?'));$hotelCountry=[];foreach(mcr_query($db,"SELECT id,country_id FROM catalog_hotels WHERE is_active=1 AND country_id IN ($marks)",array_keys($core)) as $h)$hotelCountry[(int)$h['id']]=(int)$h['country_id'];
        $stateCounts=[];foreach(mcr_query($db,"SELECT external_hotel_id,local_hotel_id,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IS NOT NULL") as $r){$local=(int)$r['local_hotel_id'];if(!isset($hotelCountry[$local]))continue;$e=mcr_evidence((string)$r['evidence_json']);$sk=mcr_state_key($e);if($sk!==null)$stateCounts[(string)$sk][$hotelCountry[$local]]=($stateCounts[(string)$sk][$hotelCountry[$local]]??0)+1;}
        $stateCountry=[];foreach($stateCounts as $sk=>$counts){arsort($counts,SORT_NUMERIC);$cid=(int)array_key_first($counts);$sum=array_sum($counts);if(isset($core[$cid])&&$counts[$cid]>=2&&$counts[$cid]/$sum>=0.90)$stateCountry[$sk]=$cid;}
        $coreKeys=[];foreach($core as $cid=>$name)$coreKeys[mcr_country_key($name)]=$cid;
        $pending=mcr_query($db,"SELECT external_hotel_id,evidence_sha256,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='pending' AND local_hotel_id IS NULL ORDER BY external_hotel_id");$queue=[];$skipped=[];
        foreach($pending as $r){$id=(string)$r['external_hotel_id'];if(!preg_match('/^[1-9][0-9]{0,19}$/D',$id)){$skipped['invalid_id']=($skipped['invalid_id']??0)+1;continue;}$e=mcr_evidence((string)$r['evidence_json']);$sk=mcr_state_key($e);if($sk===null||!preg_match('/^[1-9][0-9]{0,9}$/D',(string)$sk)){$skipped['missing_state']=($skipped['missing_state']??0)+1;continue;}$cid=$stateCountry[(string)$sk]??null;$country=mcr_country_name($e);if($cid===null&&$country!==null)$cid=$coreKeys[mcr_country_key($country)]??null;if($cid===null||!isset($core[$cid])){$skipped['non_core_or_unresolved_country']=($skipped['non_core_or_unresolved_country']??0)+1;continue;}$names=mcr_names($e);$queue[]=['andromeda_hotel_id'=>$id,'state_key'=>(int)$sk,'country_id'=>(int)$cid,'country_name'=>$core[$cid],'frequency'=>mcr_frequency($e),'name'=>$names[0]??null,'evidence_sha256'=>(string)$r['evidence_sha256']];}
        usort($queue,fn($a,$b)=>(($b['frequency']??0)<=>($a['frequency']??0))?:strcmp($a['andromeda_hotel_id'],$b['andromeda_hotel_id']));$states=[];$freq=0;foreach($queue as $x){$states[(string)$x['state_key']]=($states[(string)$x['state_key']]??0)+1;$freq+=(int)$x['frequency'];}ksort($states,SORT_NATURAL);
        $result=['schema'=>'hotel-match-andromeda-operator-evidence-mass/1','operation_id'=>AME_OP,'source_sha'=>$sha,'state'=>'queue_completed_read_only','server_current'=>true,'pending_total'=>count($pending),'queue_count'=>count($queue),'frequency_sum'=>$freq,'states'=>$states,'skipped'=>$skipped,'queue'=>$queue,'db_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'booking_calls'=>0,'no_replay'=>true,'completed_at'=>gmdate('c')];$digest=ame_write($dir.'/queue.json',$result);ame_write($dir.'/queue-receipt.json',['operation_id'=>AME_OP,'source_sha'=>$sha,'state'=>'queue_completed_read_only','queue_sha256'=>$digest,'queue_count'=>count($queue),'db_writes'=>0,'no_replay'=>true]);$db->rollBack();echo ame_json(['state'=>$result['state'],'pending_total'=>count($pending),'queue_count'=>count($queue),'frequency_sum'=>$freq,'states'=>$states,'queue_sha256'=>$digest]);
    }catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw$e;}
}
function ame_run(string $queueFile,string $outDir):void{
    require_once __DIR__.'/../../app/integrations/andromeda-client.php';require_once __DIR__.'/../../app/integrations/andromeda-transport.php';
    $sha=(string)getenv('GITHUB_SHA');$attempt=(string)getenv('GITHUB_RUN_ATTEMPT');$res=json_decode((string)file_get_contents($outDir.'/reservation.json'),true,32,JSON_THROW_ON_ERROR);if(($res['operation_id']??'')!==AME_OP||($res['source_sha']??'')!==$sha||($res['state']??'')!=='reserved_before_db_access'||$attempt!=='1')throw new RuntimeException('reservation');
    $q=json_decode((string)file_get_contents($queueFile),true,64,JSON_THROW_ON_ERROR);if(($q['state']??'')!=='queue_completed_read_only'||($q['operation_id']??'')!==AME_OP||count($q['queue']??[])<100)throw new RuntimeException('queue_contract');
    $groups=[];$country=[];foreach($q['queue'] as $x){$id=(string)$x['andromeda_hotel_id'];$sk=(string)$x['state_key'];$groups[$sk][]=$id;$country[$id]=(int)$x['country_id'];}
    $operators=['5','315','342','115'];$facts=[];$pages=[];$calls=[];$seen=[];$priceCalls=0;$last=0.0;$responseDigest='';
    $transport=function(string $url,array $opts)use(&$calls,&$last,&$responseDigest):array{parse_str((string)parse_url($url,PHP_URL_QUERY),$qq);$action=(string)($qq['action']??'');if(!in_array($action,['login','price'],true))throw new RuntimeException('action');$wait=0.85-(microtime(true)-$last);if($wait>0)usleep((int)ceil($wait*1000000));$last=microtime(true);$i=count($calls);$calls[]=['action'=>$action,'status'=>null];$t=new AnyTourAndromedaTransport(true);$r=$t($url,$opts);$calls[$i]['status']=$r['status'];if($action==='price'){$responseDigest=hash('sha256',$r['body']);$calls[$i]['response_sha256']=$responseDigest;}return$r;};
    $client=new AnyTourAndromedaClient($transport,true);$client->login(getenv('ANDROMEDA_USERNAME')?:'',getenv('ANDROMEDA_PASSWORD')?:'');$session=$client->privateSession();
    foreach($groups as $sk=>$ids)foreach($operators as $op)foreach(ame_chunks($ids) as $chunk){$wanted=array_fill_keys($chunk,true);$resolved=[];for($page=1;$page<=2;$page++){if($priceCalls>=AME_MAX_PRICE_CALLS)throw new RuntimeException('price_budget');$params=['TOWNFROMINC'=>1,'STATEINC'=>(int)$sk,'CHECKIN_BEG'=>'20260922','CHECKIN_END'=>'20260928','NIGHTS_FROM'=>7,'NIGHTS_TILL'=>10,'ADULT'=>2,'CHILD'=>0,'CURRENCYINC'=>643,'OPERATORS'=>$op,'HOTELS'=>implode(',',$chunk),'GROUP_BY'=>32,'PACKETTYPE'=>0,'PAGE'=>$page];AnyTourAndromedaClient::validatePriceParams($params);$req=hash('sha256',ame_json($params));if(isset($seen[$req]))throw new RuntimeException('request_replay');$seen[$req]=true;$priceCalls++;$c=new AnyTourAndromedaClient($transport,true);$c->restorePrivateSession($session);$reply=$c->price($params);$valid=0;foreach($reply['PRICES'] as $row){$id=(string)($row['hotelKey']??'');$f=ame_native_fact($row,$wanted,$op,$country[$id]??0,$req,$responseDigest);if(!$f)continue;$key=$op.'|'.strtolower($f['native_hotel_id']).'|'.$f['andromeda_hotel_id'];$facts[$key]=$f;$resolved[$f['andromeda_hotel_id']]=true;$valid++;}$pages[]=['state_key'=>(int)$sk,'operator_key'=>$op,'page'=>$page,'params'=>$params,'hotel_count'=>count($chunk),'returned_rows'=>count($reply['PRICES']),'valid_rows'=>$valid,'resolved_count'=>count($resolved),'pages_count'=>$reply['PAGES_COUNT'],'request_sha256'=>$req,'response_sha256'=>$responseDigest];if(count($resolved)===count($wanted)||$page>=$reply['PAGES_COUNT'])break;}}
    $byOp=[];$covered=[];foreach($facts as $f){$byOp[$f['operator_key']]=($byOp[$f['operator_key']]??0)+1;$covered[$f['andromeda_hotel_id']]=true;}ksort($byOp,SORT_NATURAL);$result=['schema'=>'hotel-match-andromeda-operator-evidence-mass/1','operation_id'=>AME_OP,'source_sha'=>$sha,'state'=>'completed','queue_sha256'=>hash_file('sha256',$queueFile),'queue_count'=>count($q['queue']),'queue_frequency_sum'=>$q['frequency_sum']??null,'operators'=>$operators,'supplier_calls'=>count($calls),'price_calls'=>$priceCalls,'unique_pair_count'=>count($facts),'covered_andromeda_count'=>count($covered),'by_operator'=>$byOp,'pages'=>$pages,'facts'=>array_values($facts),'database_writes'=>0,'mapping_writes'=>0,'tourvisor_calls'=>0,'all_calls'=>0,'booking_calls'=>0,'no_replay'=>true,'completed_at'=>gmdate('c')];$digest=ame_write($outDir.'/result.json',$result);ame_write($outDir.'/receipt.json',['operation_id'=>AME_OP,'source_sha'=>$sha,'state'=>'completed','result_sha256'=>$digest,'readback_verified'=>hash_equals($digest,hash_file('sha256',$outDir.'/result.json')),'queue_count'=>count($q['queue']),'unique_pair_count'=>count($facts),'supplier_calls'=>count($calls),'database_writes'=>0,'no_replay'=>true]);echo ame_json(['state'=>'completed','queue_count'=>count($q['queue']),'unique_pairs'=>count($facts),'covered_andromeda'=>count($covered),'by_operator'=>$byOp,'price_calls'=>$priceCalls,'result_sha256'=>$digest]);
}
if(getenv('MATCH_AME_TEST_LIBRARY')==='1')return;
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}$mode=$argv[1]??'';if($mode==='queue')ame_queue();elseif($mode==='run')ame_run((string)($argv[2]??''),(string)($argv[3]??''));else throw new RuntimeException('mode');
