<?php
declare(strict_types=1);
const OP='hotel-match-coordinate-rescue-current-accept-1971-20260912-v1';
const POLICY='owner_coordinate_name_geo_rescue_20260912_v1';
function j($v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
function h($v):string{return hash('sha256',j($v));}
function save_once(string $path,array $data):void{$f=fopen($path,'x');if(!$f)throw new RuntimeException('receipt_exists');chmod($path,0600);$raw=j($data)."\n";fwrite($f,$raw);fflush($f);if(function_exists('fsync'))fsync($f);fclose($f);if(file_get_contents($path)!==$raw)throw new RuntimeException('receipt_readback');}
$plan=[
['anex_id'=>'29013','local_id'=>65057,'distance_m'=>4.20,'rule'=>'tight_rare_brand_coord_geo','search_count'=>49],
['anex_id'=>'32731','local_id'=>65057,'distance_m'=>4.20,'rule'=>'tight_rare_brand_coord_geo','search_count'=>49],
['anex_id'=>'480','local_id'=>316,'distance_m'=>192.59,'rule'=>'multi_token_coord_geo','search_count'=>40],
['anex_id'=>'20462','local_id'=>21679,'distance_m'=>27.17,'rule'=>'tight_rare_brand_coord_geo','search_count'=>39],
['anex_id'=>'1102','local_id'=>124,'distance_m'=>124.26,'rule'=>'multi_token_coord_geo','search_count'=>13],
['anex_id'=>'1656','local_id'=>465,'distance_m'=>245.91,'rule'=>'multi_token_coord_geo','search_count'=>9],
['anex_id'=>'28711','local_id'=>17483,'distance_m'=>5.22,'rule'=>'tight_rare_brand_coord_geo','search_count'=>6],
['anex_id'=>'21359','local_id'=>64895,'distance_m'=>216.47,'rule'=>'multi_token_coord_geo','search_count'=>1],
['anex_id'=>'30716','local_id'=>17414,'distance_m'=>3.46,'rule'=>'tight_rare_brand_coord_geo','search_count'=>1],
['anex_id'=>'32562','local_id'=>17414,'distance_m'=>3.46,'rule'=>'tight_rare_brand_coord_geo','search_count'=>1],
['anex_id'=>'33241','local_id'=>28649,'distance_m'=>6.25,'rule'=>'tight_joined_spelling_coord_geo','search_count'=>1],
['anex_id'=>'35115','local_id'=>28649,'distance_m'=>6.25,'rule'=>'tight_joined_spelling_coord_geo','search_count'=>1],
];
if(in_array('--self-test',$_SERVER['argv']??[],true)){if(count($plan)!==12)exit(2);$seen=[];foreach($plan as$r){if(isset($seen[$r['anex_id']]))exit(3);$seen[$r['anex_id']]=1;if($r['distance_m']>500)exit(4);}echo "MATCH coordinate rescue self-test PASS rows=12\n";exit;}
error_reporting(0);ob_start();$db=null;$dir=null;$commitAttempted=false;$committed=false;$written=[];$skipped=[];
try{
 if(PHP_SAPI!=='cli')throw new RuntimeException('cli_only');$root=realpath(getcwd());if(!$root||basename($root)!=='anytoour.ru')throw new RuntimeException('root');$home=realpath((string)getenv('HOME'));if(!$home)throw new RuntimeException('home');$base=$home.'/.anytoour-match/operations';if(!is_dir($base)&&!mkdir($base,0700,true))throw new RuntimeException('receipt_root');$dir=$base.'/'.OP;if(file_exists($dir)||!mkdir($dir,0700)){$dir=null;throw new RuntimeException('prior_operation_no_replay');}
 save_once($dir.'/reservation.json',['operation_id'=>OP,'status'=>'reserved_before_db_access','planned'=>12,'source'=>'reports/hotel-match-live106-coordinate-rescue-20260912.json','source_sha'=>'0566f020076ba2a478e8dd2d7983a5d0dceef53f','no_replay'=>true]);
 require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET SESSION innodb_lock_wait_timeout=10');$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->beginTransaction();
 $ins=$db->prepare('INSERT INTO anex_hotel_search_mappings(anex_hotel_id,catalog_hotel_id,match_class,scope,approval_policy,source_row_digest,mapping_digest,enabled) VALUES(?,?,?,?,?,?,?,1)');
 foreach($plan as$r){$aid=(string)$r['anex_id'];$lid=(int)$r['local_id'];$q=$db->prepare('SELECT id,is_active FROM catalog_hotels WHERE id=? FOR UPDATE');$q->execute([$lid]);$hotel=$q->fetch(PDO::FETCH_ASSOC);if(!$hotel||(int)$hotel['is_active']!==1){$skipped[]=$r+['reason'=>'target_inactive'];continue;}$q=$db->prepare('SELECT anex_hotel_id FROM anex_hotel_decisions WHERE anex_hotel_id=? LIMIT 1 FOR UPDATE');$q->execute([$aid]);$manual=(bool)$q->fetchColumn();$q=$db->prepare('SELECT anex_hotel_id FROM anex_review_pair_exclusions WHERE anex_hotel_id=? LIMIT 1 FOR UPDATE');$q->execute([$aid]);$excluded=(bool)$q->fetchColumn();if($manual||$excluded){$skipped[]=$r+['reason'=>'manual_or_exclusion'];continue;}$q=$db->prepare('SELECT anex_hotel_id,catalog_hotel_id,enabled FROM anex_hotel_search_mappings WHERE anex_hotel_id=? ORDER BY catalog_hotel_id FOR UPDATE');$q->execute([$aid]);$maps=$q->fetchAll(PDO::FETCH_ASSOC);if($maps){$exact=count($maps)===1&&(int)$maps[0]['enabled']===1&&(int)$maps[0]['catalog_hotel_id']===$lid;$skipped[]=$r+['reason'=>$exact?'already_exact':'current_mapping_conflict'];continue;}$proof=['operation_id'=>OP,'source'=>'coordinate_rescue_report','rule'=>$r['rule'],'anex_hotel_id'=>(int)$aid,'catalog_hotel_id'=>$lid,'distance_m'=>$r['distance_m'],'search_count'=>$r['search_count']];$sd=h($proof);$md=h(['anex_hotel_id'=>(int)$aid,'catalog_hotel_id'=>$lid,'scope'=>'preview','approval_policy'=>POLICY,'source_row_digest'=>$sd]);$ins->execute([(int)$aid,$lid,'coordinate_name_geo','preview',POLICY,$sd,$md]);if($ins->rowCount()!==1)throw new RuntimeException('insert_count');$written[]=$r+['mapping_digest'=>$md,'source_row_digest'=>$sd];}
 save_once($dir.'/precommit-intent.json',['operation_id'=>OP,'written'=>$written,'skipped'=>$skipped,'no_replay'=>true]);$commitAttempted=true;$db->commit();$committed=true;$db->exec('START TRANSACTION READ ONLY');foreach($written as$w){$q=$db->prepare('SELECT catalog_hotel_id,enabled,mapping_digest FROM anex_hotel_search_mappings WHERE anex_hotel_id=?');$q->execute([$w['anex_id']]);$x=$q->fetchAll(PDO::FETCH_ASSOC);if(count($x)!==1||(int)$x[0]['catalog_hotel_id']!==(int)$w['local_id']||(int)$x[0]['enabled']!==1||$x[0]['mapping_digest']!==$w['mapping_digest'])throw new RuntimeException('readback_anex');}$db->exec('ROLLBACK');$reasons=[];foreach($skipped as$s){$k=$s['reason'];$reasons[$k]=($reasons[$k]??0)+1;}ksort($reasons);$out=['status'=>'accepted','operation_id'=>OP,'planned'=>12,'written_count'=>count($written),'provider_counts'=>['anex'=>count($written)],'skipped_count'=>count($skipped),'skip_reasons'=>$reasons,'skipped'=>$skipped,'readback_verified'=>true,'database_writes'=>count($written),'mapping_writes'=>count($written),'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true];save_once($dir.'/result.json',$out);
}catch(Throwable$e){try{if($db instanceof PDO&&$db->inTransaction())$db->rollBack();}catch(Throwable$ignored){}$out=['status'=>$commitAttempted?'commit_outcome_requires_readback':'rolled_back_or_not_started','operation_id'=>OP,'safe_message'=>preg_match('/^[a-z0-9_]+$/D',$e->getMessage())?$e->getMessage():'guard_failure','commit_attempted'=>$commitAttempted,'commit_confirmed'=>$committed,'database_writes'=>$commitAttempted?null:0,'mapping_writes'=>$commitAttempted?null:0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true];if($dir&&is_dir($dir)&&!file_exists($dir.'/failure.json')){try{save_once($dir.'/failure.json',$out);}catch(Throwable$ignored){}}}
while(ob_get_level())ob_end_clean();echo 'MATCH_COORDINATE_RESCUE_ACCEPT:'.j($out).PHP_EOL;exit(($out['status']??'')==='accepted'?0:2);
