<?php
declare(strict_types=1);
/** MATCH #1971: immutable Turkey hotelIds-only Tourvisor multi-operator evidence pass. */
const OP='hotel-match-tv-multiop-targeted-turkey-1971-20260916-v1';
const DAY='2026-11-17';
const TARGETS=[32880=>17443,43984=>99257,37389=>69822,32355=>21838,45226=>163543,32742=>132803,44138=>53531,44139=>67042,12901=>1474,29332=>60388,10115=>2160,35319=>1346,15235=>47028,34804=>81578,26702=>1497,39875=>1071,37538=>1461,35898=>1221];
function js(array$v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
function wr(string$p,array$v):string{$b=js($v)."\n";$f=@fopen($p,'x');if(!$f)throw new RuntimeException('durable_create_failed');try{if(fwrite($f,$b)!==strlen($b))throw new RuntimeException('durable_write_failed');fflush($f);}finally{fclose($f);}if(file_get_contents($p)!==$b)throw new RuntimeException('durable_readback_failed');return hash('sha256',$b);}
function id($v):?int{if(is_bool($v)||!is_scalar($v))return null;$s=trim((string)$v);return preg_match('/^[1-9][0-9]{0,14}$/D',$s)?(int)$s:null;}
function text($v,int$m=240):string{if(!is_scalar($v))return'';$s=trim((string)(preg_replace('/\s+/u',' ',(string)$v)??''));return function_exists('mb_substr')?mb_substr($s,0,$m,'UTF-8'):substr($s,0,$m);}
function nm($v):string{if(is_scalar($v))return text($v);if(!is_array($v))return'';foreach(['name','fullName','russianName','title','label']as$k)if(isset($v[$k])&&text($v[$k])!=='')return text($v[$k]);return'';}
function dbp(string$r):string{foreach([$r.'/data/db-v1.php',$r.'/v2/data/db-v1.php']as$p)if(is_file($p))return$p;throw new RuntimeException('db_bootstrap_missing');}
function tvp(string$r):string{foreach([$r.'/data/tourvisor-client-v1.php',$r.'/v2/data/tourvisor-client-v1.php']as$p)if(is_file($p))return$p;throw new RuntimeException('tourvisor_client_missing');}
function q(PDO$d,string$s,array$p=[]):array{$x=$d->prepare($s);$x->execute($p);return$x->fetchAll(PDO::FETCH_ASSOC);}
function sid($v,int$d=0):?int{if($d>8)return null;if(is_array($v)){foreach($v as$k=>$x)if(is_string($k)&&preg_match('/^(?:search|request).*id$/i',$k)&&($n=id($x))!==null)return$n;foreach($v as$x)if(is_array($x)&&($n=sid($x,$d+1))!==null)return$n;}return null;}
function done($v,int$d=0):bool{if($d>8||!is_array($v))return false;if((int)($v['progress']??0)>=100)return true;if(in_array(strtolower(trim((string)($v['status']??''))),['complete','completed','done','ready'],true))return true;foreach($v as$x)if(is_array($x)&&done($x,$d+1))return true;return false;}
function flat($p):array{$r=$p;if(is_array($r)&&!array_is_list($r))foreach(['hotels','results','tours','items','data']as$k)if(isset($r[$k])&&is_array($r[$k])){$r=$r[$k];break;}if(!is_array($r))return[];$o=[];foreach($r as$row){if(!is_array($row))continue;if(isset($row['tours'])&&is_array($row['tours'])&&!isset($row['hotel'])){$h=$row;unset($h['tours']);foreach($row['tours']as$t)if(is_array($t)){if(!isset($t['hotel']))$t['hotel']=$h;$o[]=$t;}}elseif(is_array($row['hotel']??null))$o[]=$row;}return$o;}
function link_ev($v):array{$u=trim((string)$v);if($u==='')return['status'=>'missing'];$p=parse_url($u);if(!is_array($p)||strtolower((string)($p['scheme']??''))!=='https'||isset($p['user'])||isset($p['pass'])||!isset($p['host']))return['status'=>'invalid'];$keys=[];$nums=[];foreach(explode('&',(string)($p['query']??''))as$z){if($z==='')continue;[$a,$b]=array_pad(explode('=',$z,2),2,'');$k=strtolower(trim(urldecode($a)));if($k==='')continue;if(preg_match('/(?:token|jwt|auth|pass|password|secret|session|sid|cookie|signature|api[_-]?key)/i',$k))return['status'=>'secret_bearing','host'=>strtolower((string)$p['host']),'path'=>(string)($p['path']??'')];$keys[$k]=1;if(($n=id(trim(urldecode($b))))!==null)$nums[$k][$n]=1;}ksort($keys);ksort($nums);$nn=[];foreach($nums as$k=>$v){$a=array_keys($v);sort($a,SORT_NUMERIC);$nn[$k]=$a;}return['status'=>'safe','host'=>strtolower((string)$p['host']),'path'=>(string)($p['path']??''),'query_keys'=>array_keys($keys),'numeric_query'=>$nn];}
function fail(Throwable$e):string{$m=$e->getMessage();if(preg_match('/HTTP[ _]([45][0-9]{2})(?:\b|_)/i',$m,$x))return'tourvisor_http_'.$x[1];return in_array($m,['call_cap','search_id_missing','search_not_ready','no_focus','no_results','jwt_missing','client_missing'],true)?$m:'diagnostic_error';}
function tv(string$stage,string$path,array$p=[]):array{global$calls,$last;$last=$stage;if(rtrim($path,'/')==='/tours/search'&&(empty($p['hotelIds'])||isset($p['operatorIds'])))throw new RuntimeException('focused_multiop_guard');if($calls>=39)throw new RuntimeException('call_cap');$calls++;return v2_data_tv_get($path,$p);}
function pick(array$rows,array$focus):array{$by=[];foreach($rows as$r){$h=is_array($r['hotel']??null)?$r['hotel']:[];$o=is_array($r['operator']??null)?$r['operator']:[];$hid=id($h['id']??null);$oid=id($o['id']??null);$tid=id($r['id']??null);if(!$hid||!$oid||!$tid||!in_array($hid,$focus,true))continue;$k=$hid.'|'.$oid;if(!isset($by[$k]))$by[$k]=['tour_id'=>$tid,'hotel_id'=>$hid,'hotel_name'=>nm($h),'operator_id'=>$oid,'operator_name'=>nm($o)];}$first=[];$extra=[];$seen=[];foreach($by as$x){if(!isset($seen[$x['hotel_id']])){$seen[$x['hotel_id']]=1;$first[]=$x;}else$extra[]=$x;}return array_slice(array_merge($first,$extra),0,30);}
if(in_array('--self-test',$argv??[],true)){$p=['departureId'=>1,'countryId'=>4,'dateFrom'=>DAY,'dateTo'=>DAY,'nightsFrom'=>7,'nightsTo'=>7,'adults'=>2,'currency'=>'RUB','onlyCharter'=>false,'hotelIds'=>[10,20]];if(isset($p['operatorIds']))throw new RuntimeException('operator_filter_present');$e=link_ev('https://x.test/a?hotelCode=4158&adult=2');if(($e['numeric_query']['hotelcode'][0]??0)!==4158)throw new RuntimeException('link');echo"Turkey multiop self-test PASS\n";exit;}
$op=(string)getenv('OPERATION_ID');$sha=(string)getenv('MATCH_SOURCE_SHA');if($op!==OP||!preg_match('/^[0-9a-f]{40}$/D',$sha))throw new RuntimeException('operation_guard');$root=(string)realpath(getcwd());$base=rtrim((string)getenv('HOME'),'/').'/.anytoour-match/operations';if($root===''||basename($root)!=='anytoour.ru'||!is_dir($base))throw new RuntimeException('root_guard');$dir=$base.'/'.$op;if(!mkdir($dir,0700))throw new RuntimeException('operation_exists');wr($dir.'/reservation.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'reserved_before_db_and_tourvisor_access','credential_identifier'=>'TOURVISOR_JWT','date'=>DAY,'read_only'=>true,'no_replay'=>true]);
$calls=0;$last='current';$focus=[];$pr=['mapped'=>0,'manual'=>0,'excluded'=>0,'inactive'=>0];$rows=[];$searchId=null;$rate=false;$auth=false;$flat=[];$selected=[];
try{require_once dbp($root);$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');$map=[];foreach(q($db,'SELECT anex_hotel_id,catalog_hotel_id FROM anex_hotel_search_mappings')as$r)$map[(int)$r['anex_hotel_id']]=(int)$r['catalog_hotel_id'];$man=[];foreach(q($db,'SELECT anex_hotel_id FROM anex_hotel_decisions')as$r)$man[(int)$r['anex_hotel_id']]=1;$ex=[];foreach(q($db,'SELECT anex_hotel_id,catalog_hotel_id FROM anex_review_pair_exclusions')as$r)$ex[(int)$r['anex_hotel_id']][(int)$r['catalog_hotel_id']]=1;$active=[];foreach(q($db,'SELECT id FROM catalog_hotels WHERE country_id=4 AND is_active=1')as$r)$active[(int)$r['id']]=1;foreach(TARGETS as$a=>$l){if(isset($map[$a])){$pr['mapped']++;continue;}if(isset($man[$a])){$pr['manual']++;continue;}if(isset($ex[$a][$l])){$pr['excluded']++;continue;}if(!isset($active[$l])){$pr['inactive']++;continue;}$focus[$a]=$l;}$db->exec('ROLLBACK');if(!$focus)throw new RuntimeException('no_focus');
require_once tvp($root);if(!function_exists('v2_data_tv_get'))throw new RuntimeException('client_missing');if(trim((string)(getenv('TOURVISOR_JWT')?:''))===''&&!(defined('TOURVISOR_JWT')&&trim((string)TOURVISOR_JWT)!==''))throw new RuntimeException('jwt_missing');$p=['departureId'=>1,'countryId'=>4,'dateFrom'=>DAY,'dateTo'=>DAY,'nightsFrom'=>7,'nightsTo'=>7,'adults'=>2,'currency'=>'RUB','onlyCharter'=>false,'hotelIds'=>array_values($focus)];$s=tv('search_create','/tours/search',$p);$searchId=sid($s);if(!$searchId)throw new RuntimeException('search_id_missing');wr($dir.'/search-checkpoint.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'search_created_before_poll','search_id'=>$searchId,'date'=>DAY,'current_input_count'=>count($focus),'tourvisor_calls'=>$calls,'no_replay'=>true]);$st=[];foreach([8,12,15,15,15]as$w){sleep($w);$st=tv('search_status','/tours/search/'.$searchId.'/status',['operatorStatus'=>false]);if(done($st))break;}if(!done($st))throw new RuntimeException('search_not_ready');$flat=flat(tv('search_results','/tours/search/'.$searchId,['limit'=>500]));$selected=pick($flat,array_values($focus));if(!$selected)throw new RuntimeException('no_results');
foreach($selected as$x){sleep(4);try{$d=tv('tour_detail','/tours/'.$x['tour_id'],['currency'=>'RUB']);}catch(Throwable$e){$why=fail($e);if($why==='tourvisor_http_429'){$rate=true;break;}if(in_array($why,['tourvisor_http_401','tourvisor_http_403'],true)){$auth=true;break;}$rows[]=$x+['status'=>'detail_hold','reason'=>$why];continue;}$h=is_array($d['hotel']??null)?$d['hotel']:[];$o=is_array($d['operator']??null)?$d['operator']:[];$hid=id($h['id']??null);$oid=id($o['id']??null);if($hid!==$x['hotel_id']||$oid!==$x['operator_id']){$rows[]=$x+['status'=>'detail_hold','reason'=>'identity_mismatch'];continue;}$c=is_array($h['common']??null)?$h['common']:[];$rows[]=['tour_id'=>$x['tour_id'],'tourvisor_hotel_id'=>$hid,'tourvisor_hotel_name'=>nm($h),'operator_id'=>$oid,'operator_name'=>nm($o),'operator_link_evidence'=>link_ev($d['operatorLink']??null),'region'=>nm($h['region']??null),'subregion'=>nm($h['subRegion']??null),'latitude'=>$c['latitude']??($h['latitude']??null),'longitude'=>$c['longitude']??($h['longitude']??null),'status'=>'captured'];}
$status=$rate?'partial_rate_limited':($auth?'partial_auth_rejected':'completed');$res=['operation_id'=>$op,'source_sha'=>$sha,'status'=>$status,'date'=>DAY,'credential_identifier'=>'TOURVISOR_JWT','current_focus_count'=>count($focus),'pruned'=>$pr,'search_id'=>$searchId,'flattened_rows'=>count($flat),'unique_hotel_operator_selected'=>count($selected),'detail_rows'=>count($rows),'captured'=>count(array_filter($rows,fn($r)=>($r['status']??'')==='captured')),'operator_counts'=>array_count_values(array_map(fn($r)=>(string)($r['operator_id']??'unknown'),array_filter($rows,fn($r)=>($r['status']??'')==='captured'))),'tourvisor_calls'=>$calls,'last_stage'=>$last,'rows'=>$rows,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'booking_calls'=>0,'lead_calls'=>0,'no_replay'=>true];
}catch(Throwable$e){try{if(isset($db)&&$db instanceof PDO&&$db->inTransaction())$db->exec('ROLLBACK');}catch(Throwable$x){}$res=['operation_id'=>$op,'source_sha'=>$sha,'status'=>'blocked','reason'=>fail($e),'date'=>DAY,'current_focus_count'=>count($focus),'pruned'=>$pr,'search_id'=>$searchId,'tourvisor_calls'=>$calls,'last_stage'=>$last,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'booking_calls'=>0,'lead_calls'=>0,'no_replay'=>true];}
$rh=wr($dir.'/result.json',$res);wr($dir.'/receipt.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>$res['status'],'result_sha256'=>$rh,'readback_verified'=>hash('sha256',(string)file_get_contents($dir.'/result.json'))===$