<?php
declare(strict_types=1);
/* MATCH-only one-call Tourvisor operator dictionary capture. No search/detail/DB access. */
const HTOD_OP='hotel-match-tv-operator-dictionary-1971-20260915-v1';
function htod_json(array $x):string{return json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";}
function htod_write(string $path,array $x):string{$raw=htod_json($x);$f=@fopen($path,'x+b');if(!$f)throw new RuntimeException('exclusive_output');try{if(fwrite($f,$raw)!==strlen($raw)||!fflush($f))throw new RuntimeException('output_write');if(function_exists('fsync')&&!fsync($f))throw new RuntimeException('output_sync');rewind($f);if(stream_get_contents($f)!==$raw)throw new RuntimeException('output_readback');}finally{fclose($f);}return hash('sha256',$raw);}
function htod_anex(array $o):bool{return preg_match('/(?:^|\b)(?:anex|анекс)(?:\b|$)/ui',implode(' ',array_filter([$o['name']??null,$o['russianName']??null,$o['fullName']??null],'is_string')))===1;}
function htod_safe_operator(array $o):array{$id=filter_var($o['id']??null,FILTER_VALIDATE_INT);if($id===false||(int)$id<1)throw new RuntimeException('operator_id');$r=['id'=>(int)$id];foreach(['name','russianName','fullName'] as $k)if(is_string($o[$k]??null)&&trim($o[$k])!=='')$r[$k]=mb_substr(trim($o[$k]),0,180,'UTF-8');return $r;}
function htod_query(array $p):string{return http_build_query($p,'','&',PHP_QUERY_RFC3986);}
function htod_run():array{
    if(PHP_SAPI!=='cli'||(getenv('MATCH_OPERATION_ID')?:'')!==HTOD_OP||!preg_match('/^[0-9a-f]{40}$/D',getenv('MATCH_SOURCE_SHA')?:''))throw new RuntimeException('environment_guard');
    $sha=(string)getenv('MATCH_SOURCE_SHA');$home=rtrim((string)getenv('HOME'),'/');$opdir=$home.'/.anytoour-match/operations/'.HTOD_OP;$reservation=$opdir.'/reservation.json';
    if(!is_file($reservation)||is_link($reservation))throw new RuntimeException('reservation_missing');$r=json_decode((string)file_get_contents($reservation),true,32,JSON_THROW_ON_ERROR);
    if(($r['operation_id']??'')!==HTOD_OP||($r['source_sha']??'')!==$sha||($r['state']??'')!=='reserved_before_provider_access'||($r['max_http_calls']??null)!==1||($r['no_replay']??false)!==true)throw new RuntimeException('reservation_contract');
    $root=realpath($home.'/www/anytoour.ru');if(!$root||basename($root)!=='anytoour.ru')throw new RuntimeException('root_guard');
    $out=['operation_id'=>HTOD_OP,'source_sha'=>$sha,'state'=>'incomplete_read_only','endpoint'=>'/operators','params'=>['departureId'=>1,'countryId'=>1],'max_http_calls'=>1,'new_searches'=>0,'database_reads'=>0,'database_writes'=>0,'mapping_writes'=>0,'booking_calls'=>0,'no_replay'=>true];
    $phase='existing_client';
    try{
        $client=$root.(is_file($root.'/data/tourvisor-client-v1.php')?'/data/tourvisor-client-v1.php':'/v2/data/tourvisor-client-v1.php');if(!is_file($client)||is_link($client))throw new RuntimeException('existing_client_missing');
        $clientHash=hash_file('sha256',$client);if($clientHash!=='03764ec6732eb7a698b5090fee20675438db1fd43c5f26ae85b9c8c374d46167')throw new RuntimeException('existing_client_changed');require_once $client;$token=v2_data_tourvisor_token();if($token==='')throw new RuntimeException('token_missing');$out['existing_client_sha256']=$clientHash;$out['credential_source']='existing_server_TOURVISOR_JWT';
        $phase='operator_dictionary';$query=htod_query($out['params']);$url='https://api.tourvisor.ru/search/api/v1/operators?'.$query;$headers=[];$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>10,CURLOPT_TIMEOUT=>40,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_HTTPHEADER=>['Authorization: Bearer '.$token,'Accept: application/json'],CURLOPT_HEADERFUNCTION=>static function($c,$h)use(&$headers){$n=strlen($h);$a=explode(':',$h,2);if(count($a)===2&&preg_match('/^(retry-after|x-ratelimit[^:]*|ratelimit[^:]*)$/i',trim($a[0])))$headers[strtolower(trim($a[0]))]=trim($a[1]);return $n;}]);
        $out['request_sha256']=hash('sha256','/operators?'.$query);$raw=curl_exec($ch);$errno=curl_errno($ch);$status=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);$out['http_status']=$status;$out['response_sha256']=is_string($raw)?hash('sha256',$raw):null;$out['rate_headers']=$headers;$out['tourvisor_calls']=1;
        if($errno||!is_string($raw))throw new RuntimeException('network_stop_no_retry');if($status!==200)throw new RuntimeException('http_'.$status.'_stop_no_retry');if(isset($headers['retry-after']))throw new RuntimeException('retry_after_stop');foreach($headers as $k=>$v)if(str_contains($k,'remaining')&&ctype_digit($v)&&(int)$v<1)throw new RuntimeException('quota_exhausted');if(strlen($raw)>8*1024*1024)throw new RuntimeException('response_size');
        $doc=json_decode($raw,true,64,JSON_THROW_ON_ERROR);if(!is_array($doc))throw new RuntimeException('response_shape');$rows=array_is_list($doc)?$doc:($doc['operators']??$doc['data']??$doc['items']??null);if(!is_array($rows))throw new RuntimeException('operator_list_shape');$matches=[];foreach($rows as $row)if(is_array($row)&&htod_anex($row))$matches[]=htod_safe_operator($row);$uniq=[];foreach($matches as $m)$uniq[$m['id']]=$m;$matches=array_values($uniq);if(count($matches)!==1)throw new RuntimeException('anex_operator_ambiguous');
        $out['anex_operator']=$matches[0];$out['dictionary_row_count']=count($rows);$out['state']='completed_read_only';$out['outcome']='anex_operator_id_captured';
    }catch(Throwable $e){$out['state']='stopped_read_only_no_retry';$out['phase']=$phase;$out['reason']=preg_match('/^[A-Za-z0-9_]+$/D',$e->getMessage())?$e->getMessage():get_class($e);$out['tourvisor_calls']=$out['tourvisor_calls']??0;}
    $resultHash=htod_write($opdir.'/result.json',$out);htod_write($opdir.'/receipt.json',['operation_id'=>HTOD_OP,'source_sha'=>$sha,'state'=>$out['state'],'result_sha256'=>$resultHash,'readback_verified'=>hash_file('sha256',$opdir.'/result.json')===$resultHash,'tourvisor_calls'=>$out['tourvisor_calls']??0,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true]);return $out;
}
if(($argv[1]??'')==='--self-test'){$n=0;$c=static function($v)use(&$n){if(!$v)throw new RuntimeException('self_test');$n++;};$c(htod_anex(['name'=>'Anex']));$c(htod_anex(['russianName'=>'АНЕКС Тур']));$c(!htod_anex(['name'=>'Intourist']));$c(htod_safe_operator(['id'=>7,'name'=>'Anex'])===['id'=>7,'name'=>'Anex']);$c(htod_query(['departureId'=>1,'countryId'=>1])==='departureId=1&countryId=1');echo "$n operator dictionary tests PASS\n";exit;}
try{$r=htod_run();echo json_encode(['state'=>$r['state'],'anex_operator'=>$r['anex_operator']??null,'http_status'=>$r['http_status']??null,'rate_headers'=>$r['rate_headers']??[],'tourvisor_calls'=>$r['tourvisor_calls']??0],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";exit($r['state']==='completed_read_only'?0:2);}catch(Throwable $e){echo json_encode(['operation_id'=>HTOD_OP,'state'=>'failed_before_execution','error_class'=>get_class($e),'tourvisor_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true])."\n";exit(2);}
