<?php
declare(strict_types=1);
if (!defined('FC_LIBRARY_ONLY')) define('FC_LIBRARY_ONLY', true);
require_once __DIR__ . '/hotel_match_fuzzy_learned_geo_global_review.php';

const HMAF_OPERATION='hotel-match-anex-anchor-fuzzy-global-review-2333-20260914-v1';

function hmaf_review(PDO $db,string $operation=HMAF_OPERATION): array {
    if($operation!==HMAF_OPERATION)throw new RuntimeException('operation_scope');$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
    [$hotels,$names,$strict,$broad,$places,$scope]=mbr_catalog($db);$shaCountry=fc_sha_countries($db);
    $latest=[];$obsCount=[];foreach($db->query("SELECT * FROM andromeda_search_hotel_observations WHERE supplier_namespace='andromeda_catalog' ORDER BY observed_at_utc DESC,external_hotel_id")->fetchAll(PDO::FETCH_ASSOC) as $o){$id=(string)$o['external_hotel_id'];$obsCount[$id]=($obsCount[$id]??0)+1;if(!isset($latest[$id]))$latest[$id]=$o;}
    $anexLocal=[];$sql="SELECT m.catalog_hotel_id FROM anex_hotel_search_mappings m LEFT JOIN anex_hotel_decisions d ON d.anex_hotel_id=m.anex_hotel_id WHERE m.enabled=1 AND m.scope='preview' AND m.approval_policy='".FC_POLICY."' AND d.anex_hotel_id IS NULL AND NOT EXISTS(SELECT 1 FROM anex_review_pair_exclusions x WHERE x.anex_hotel_id=m.anex_hotel_id AND x.catalog_hotel_id=m.catalog_hotel_id) UNION SELECT d.catalog_hotel_id FROM anex_hotel_decisions d WHERE d.decision_status='accepted' AND d.catalog_hotel_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM anex_review_pair_exclusions x WHERE x.anex_hotel_id=d.anex_hotel_id AND x.catalog_hotel_id=d.catalog_hotel_id)";foreach($db->query($sql)->fetchAll(PDO::FETCH_COLUMN) as $id)$anexLocal[(int)$id]=1;
    $andAccepted=array_fill_keys(array_map('intval',$db->query("SELECT DISTINCT local_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IS NOT NULL")->fetchAll(PDO::FETCH_COLUMN)),1);
    $tokenIndex=[];foreach(array_keys($anexLocal) as $lid){if(!isset($hotels[$lid]))continue;$country=(int)$hotels[$lid]['country_id'];$seen=[];foreach($names[$lid]??[] as $n)foreach(hmfg_tokens((string)$n) as $t)$seen[$t]=1;foreach(array_keys($seen) as $t)$tokenIndex[$country][$t][$lid]=1;}
    $stats=['pending_examined'=>0,'no_unique_identity_examined'=>0,'candidate_pool'=>0,'ranked'=>0,'safe'=>0,'medium'=>0,'observed'=>0,'weak_tokens'=>0,'weak_score'=>0,'weak_margin'=>0,'category_conflict'=>0,'qualifier_conflict'=>0,'coordinate_conflict'=>0,'target_occupied'=>0,'country_unknown'=>0];$safe=[];$medium=[];$reasons=[];
    foreach($db->query("SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='pending' AND local_hotel_id IS NULL ORDER BY external_hotel_id")->fetchAll(PDO::FETCH_ASSOC) as $r){$external=(string)$r['external_hotel_id'];$obs=$latest[$external]??null;$prior=fc_evidence($r['evidence_json']??'');$src=$prior['source']??[];if(!is_array($src))$src=[];$geo=$prior['geography']??[];if(!is_array($geo))$geo=[];$country=(int)($obs['country_id']??0);if(!isset(MBR_CORE8[$country]))$country=(int)($shaCountry[$r['catalog_sha256']]??0);if(!isset(MBR_CORE8[$country])){$stats['country_unknown']++;continue;}$stats['pending_examined']++;
        $sourceNames=array_values(array_unique(array_filter([(string)($src['name']??''),(string)($src['lName']??''),(string)($obs['hotel_name']??'')],static fn($v)=>trim($v)!=='')));$strictIds=mbr_ids_for_names($strict,$country,$sourceNames,false);$broadIds=mbr_ids_for_names($broad,$country,$sourceNames,true);if(count($strictIds)!==0||count($broadIds)!==0)continue;$stats['no_unique_identity_examined']++;$oc=(int)($obsCount[$external]??0);if($oc>0)$stats['observed']++;
        $sourceTokenSet=[];foreach($sourceNames as $n)foreach(hmfg_tokens((string)$n) as $t)$sourceTokenSet[$t]=1;if(count($sourceTokenSet)<2){$stats['weak_tokens']++;$reasons['source_lt_2_significant_tokens']=($reasons['source_lt_2_significant_tokens']??0)+1;continue;}$votes=[];foreach(array_keys($sourceTokenSet) as $t)foreach(array_keys($tokenIndex[$country][$t]??[]) as $lid)$votes[(int)$lid]=($votes[(int)$lid]??0)+1;$pool=[];foreach($votes as $lid=>$n)if($n>=2)$pool[]=(int)$lid;if(!$pool){$reasons['no_anex_anchor_shared2_pool']=($reasons['no_anex_anchor_shared2_pool']??0)+1;continue;}$stats['candidate_pool']++;
        $rank=hmfg_rank($pool,$sourceNames,$names);$best=$rank[0]??null;if(!$best)continue;$stats['ranked']++;$second=$rank[1]['score']??0.0;$margin=$best['score']-$second;$lid=(int)$best['id'];$target=$hotels[$lid];if(isset($andAccepted[$lid])){$stats['target_occupied']++;$reasons['target_already_accepted_andromeda']=($reasons['target_already_accepted_andromeda']??0)+1;continue;}if(!hmlg_qualifiers_ok($sourceNames,$names[$lid]??[(string)$target['name']])){$stats['qualifier_conflict']++;$reasons['meaningful_qualifier_conflict']=($reasons['meaningful_qualifier_conflict']??0)+1;continue;}
        $coord=$src;if($obs)$coord+=$obs;$guard=mbr_target_guard($coord,$target);if($guard['coordinate_conflict']){$stats['coordinate_conflict']++;$reasons['coordinate_conflict_gt_5km']=($reasons['coordinate_conflict_gt_5km']??0)+1;continue;}$sourceCat=mbr_numeric_category($src);if($sourceCat===null&&$obs)$sourceCat=mbr_numeric_category($obs);$targetCat=$target['category']===null?null:(int)$target['category'];$catMismatch=$sourceCat!==null&&$targetCat!==null&&$sourceCat!==$targetCat;if($catMismatch){$stats['category_conflict']++;$reasons['numeric_star_guard_mismatch']=($reasons['numeric_star_guard_mismatch']??0)+1;continue;}
        $sourcePlaces=array_values(array_unique(array_filter([(string)($src['town']??''),(string)($geo['town']??''),(string)($geo['parent']??''),(string)($obs['region_name']??'')],static fn($v)=>trim($v)!=='')));$directGeo=fc_place($sourcePlaces,[(string)$target['region_name'],(string)$target['subregion_name']]);$base=['external_id'=>$external,'country_id'=>$country,'observation_count'=>$oc,'source_names'=>$sourceNames,'source_places'=>$sourcePlaces,'target'=>mbr_row_target($target),'best'=>$best,'second_score'=>round($second,6),'margin'=>round($margin,6),'direct_geo'=>(bool)$directGeo,'guard'=>$guard,'source_category'=>$sourceCat,'target_category'=>$targetCat,'evidence'=>'distinctive_fuzzy_name_plus_current_accepted_anex_local_anchor'];
        $safeRule=($best['shared']>=3&&$best['score']>=0.88&&$margin>=0.18)||($directGeo&&$best['shared']>=2&&$best['score']>=0.82&&$margin>=0.15);if($safeRule){$base['tier']='safe';$safe[]=$base;$stats['safe']++;continue;}if($best['shared']>=2&&$best['score']>=0.78&&$margin>=0.10){$base['tier']='medium';$medium[]=$base;$stats['medium']++;continue;}if($best['score']<0.78){$stats['weak_score']++;$reasons['weak_fuzzy_score']=($reasons['weak_fuzzy_score']??0)+1;}else{$stats['weak_margin']++;$reasons['insufficient_fuzzy_margin']=($reasons['insufficient_fuzzy_margin']??0)+1;}
    }
    $sort=static fn($a,$b)=>(int)$b['observation_count']<=>(int)$a['observation_count'] ?: $b['best']['score']<=>$a['best']['score'] ?: $b['margin']<=>$a['margin'] ?: strcmp($a['external_id'],$b['external_id']);usort($safe,$sort);usort($medium,$sort);arsort($reasons);
    return ['status'=>'completed','operation_id'=>$operation,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'historical_operations_replayed'=>false,'coverage'=>fc_coverage($db),'catalog_scope'=>$scope,'anex_anchor_locals'=>count($anexLocal),'stats'=>$stats,'blocked_reasons'=>$reasons,'safe_count'=>count($safe),'medium_count'=>count($medium),'safe'=>$safe,'medium'=>$medium];
}
