<?php
declare(strict_types=1);
const C55_OP='hotel-match-refresh55-direct-current-1971-20260919-v2';
function c55_need(bool $x,string $w):void{if(!$x)throw new RuntimeException($w);}
function c55_write(string $p,array $v):string{$b=json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n";$f=fopen($p,'xb');c55_need(is_resource($f),'open');fwrite($f,$b);fflush($f);if(function_exists('fsync'))fsync($f);fclose($f);return hash('sha256',$b);}
function c55_rows(PDO $db,string $q,array $p=[]):array{$s=$db->prepare($q);$s->execute(array_values($p));return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}
function c55_star(array $h):?int{foreach(['star','starLName','category']as$k)if(isset($h[$k])&&preg_match('/([1-5])/u',(string)$h[$k],$m))return(int)$m[1];return null;}
if(in_array('--self-test',$argv??[],true)){c55_need(c55_star(['starLName'=>'5*'])===5,'star');echo"REFRESH55_CURRENT_SELFTEST_OK\n";exit(0);}
$dir=(string)getenv('MATCH_OPERATION_DIR');$root=realpath((string)getenv('ANYTOUR_ROOT'));$detail=realpath((string)getenv('MATCH_DETAIL'));$router=realpath((string)getenv('MATCH_ROUTER'));$v1=realpath((string)getenv('MATCH_V1_DIR'));$v5=realpath((string)getenv('MATCH_V5_DIR'));
c55_need(PHP_SAPI==='cli'&&is_dir($dir)&&basename($dir)===C55_OP&&is_string($root)&&is_string($detail)&&hash_file('sha256',$detail)==='9d8be005458ca901dac8f94a7224662ae25833882dda2ed6687d184a660af034'&&is_string($router)&&hash_file('sha256',$router)==='3b189d1b7313eb85743a6d22be48aa7323725fe6fb57e8d47b6e5ea220b1cb8f'&&is_string($v1)&&is_string($v5),'runtime');
$d=json_decode((string)file_get_contents($detail),true,128,JSON_THROW_ON_ERROR);$r=json_decode((string)file_get_contents($router),true,128,JSON_THROW_ON_ERROR);$opmap=[13=>'5',18=>'115',25=>'315',43=>'342'];$canon=[13=>'anex',18=>'biblio_globus',25=>'funsun',43=>'intourist'];
$targets=[];foreach($r['rows']as$x)$targets[(int)$x['tv_hotel_id']]=$x['target'];$usage=[];foreach($d['edges']as$e){$op=$opmap[(int)$e['operator_id']];foreach((array)($e['positive_native_candidates']??[])as$t)$usage[$op.'|'.(string)$t][]=(int)$e['tv_hotel_id'];}
$facts=[];foreach([$v1,$v5]as$vd)foreach(glob($vd.'/raw-price-*.json')?:[]as$p){$j=json_decode((string)file_get_contents($p),true,64,JSON_THROW_ON_ERROR);foreach((array)($j['PRICES']??[])as$x){if(!is_array($x))continue;$o=is_array($x['original']??null)?$x['original']:[];$op=(string)($x['operatorKey']??($o['operatorKey']??''));$sid=(string)($x['hotelKey']??'');$nat=(string)($o['hotelKey']??'');if(preg_match('/^[1-9][0-9]*$/D',$op)&&preg_match('/^[1-9][0-9]*$/D',$sid)&&preg_match('/^[1-9][0-9]*$/D',$nat))$facts[$op.'|'.$nat][$sid]=['samo_hotel_id'=>$sid,'native_operator_hotel_id'=>$nat,'operator_id'=>$op,'is_operator_hotel_key'=>$o['isOperatorHotelKey']??null,'raw_sha256'=>hash_file('sha256',$p)];}}
$edges=[];foreach($d['edges']as$e){$tv=(int)$e['tv_hotel_id'];$opid=(int)$e['operator_id'];$op=$opmap[$opid];$hits=[];foreach((array)($e['positive_native_candidates']??[])as$t){$k=$op.'|'.(string)$t;if(count($usage[$k]??[])!==1)continue;foreach($facts[$k]??[]as$sid=>$f)$hits[$sid][]=['native_token'=>(string)$t,'fact'=>$f];}if(count($hits)!==1)continue;$sid=(string)array_key_first($hits);$edges[]=['samo_hotel_id'=>$sid,'tv_hotel_id'=>$tv,'operator_id'=>$opid,'operator'=>$canon[$opid],'native_proofs'=>$hits[$sid],'operator_link_sha256'=>$e['operator_link_sha256']??null,'hotel_name'=>$e['hotel_name']];}
c55_need(count($edges)===55,'edge55');$pairs=[];$sourceTargets=[];$targetSources=[];foreach($edges as$e){$k=$e['samo_hotel_id'].'|'.$e['tv_hotel_id'];$pairs[$k]['samo_hotel_id']=$e['samo_hotel_id'];$pairs[$k]['tv_hotel_id']=$e['tv_hotel_id'];$pairs[$k]['hotel_name']=$e['hotel_name'];$pairs[$k]['operator_proofs'][]=$e;$sourceTargets[$e['samo_hotel_id']][$e['tv_hotel_id']]=true;$targetSources[$e['tv_hotel_id']][$e['samo_hotel_id']]=true;}c55_need(count($pairs)===32,'pair32');
$catalogFiles=['Китай'=>['raw-catalog-0d4a7aaa20.json','5a6851b3462392f563c65ac13c28459261cbd58a4d437bb24115716995f4c560'],'Турция'=>['raw-catalog-13965a9cf6.json','564da2af9cb248a6860b1705285f106d4f022ffbbac36a7fcfe2630d91a74b39'],'Маврикий'=>['raw-catalog-490f3ae3b6.json','3278cf955d7fd87c9a5694783b1434c23c8ce94717b9b68dc86e5ecbe7b692ce'],'Танзания'=>['raw-catalog-b897da4c1b.json','b9b27238c1c980bbf5015ecf6f5c46bacada55251fcd0d92d373fa11bcd5e056'],'Шри-Ланка'=>['raw-catalog-bfa5c7498a.json','bbe38eacc0a64ab7adb4ab82d2c5d9dbf2a795f5d80d4e13c6f1c1a75aa5b63a'],'Египет'=>['raw-catalog-dfd0573e11.json','feecbab9f7cc6a6bb093ab5a744b2a843e79be6e4f570bd80b234661ac8b5755']];$src=[];foreach($catalogFiles as$country=>[$fn,$fh]){$p=$v1.'/'.$fn;c55_need(is_file($p)&&hash_file('sha256',$p)===$fh,'catalog_'.$country);$j=json_decode((string)file_get_contents($p),true,64,JSON_THROW_ON_ERROR);foreach((array)$j['HOTELS']as$h){$id=(string)($h['id']??'');if(isset($sourceTargets[$id]))$src[$id][]=['country'=>$country,'catalog_sha256'=>$fh,'hotel'=>$h];}}foreach($sourceTargets as$sid=>$x)c55_need(count($src[$sid]??[])===1,'source_catalog_'.$sid);
$sources=array_keys($sourceTargets);$tvIds=array_keys($targetSources);$nativeAnex=[];foreach($edges as$e)if($e['operator']==='anex')foreach($e['native_proofs']as$p)$nativeAnex[(string)$p['native_token']]=true;$sp=implode(',',array_fill(0,count($sources),'?'));$tp=implode(',',array_fill(0,count($tvIds),'?'));$np=$nativeAnex?implode(',',array_fill(0,count($nativeAnex),'?')):'0';
require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION READ ONLY');
$cur=c55_rows($db,"SELECT supplier_namespace,external_hotel_id,local_hotel_id,decision_status,catalog_sha256,evidence_sha256 FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id IN ($sp)",$sources);$occ=c55_rows($db,"SELECT external_hotel_id,local_hotel_id,decision_status FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IN ($tp)",$tvIds);$hot=c55_rows($db,"SELECT id,name,country_name,region_name,subregion_name,category,is_active FROM catalog_hotels WHERE id IN ($tp)",$tvIds);$maps=$nativeAnex?c55_rows($db,"SELECT * FROM anex_hotel_search_mappings WHERE anex_hotel_id IN ($np) OR catalog_hotel_id IN ($tp)",array_merge(array_keys($nativeAnex),$tvIds)):[];$dec=$nativeAnex?c55_rows($db,"SELECT * FROM anex_hotel_decisions WHERE anex_hotel_id IN ($np) OR catalog_hotel_id IN ($tp)",array_merge(array_keys($nativeAnex),$tvIds)):[];$exc=$nativeAnex?c55_rows($db,"SELECT * FROM anex_review_pair_exclusions WHERE anex_hotel_id IN ($np) OR catalog_hotel_id IN ($tp)",array_merge(array_keys($nativeAnex),$tvIds)):[];$db->rollBack();
$curBy=[];foreach($cur as$x)$curBy[(string)$x['external_hotel_id']]=$x;$occBy=[];foreach($occ as$x)$occBy[(int)$x['local_hotel_id']][]=$x;$hotBy=[];foreach($hot as$x)$hotBy[(int)$x['id']]=$x;$mapBy=[];foreach($maps as$x)if((int)($x['enabled']??1)===1)$mapBy[(string)$x['anex_hotel_id']][]=$x;$decP=[];foreach($dec as$x)$decP[(string)$x['anex_hotel_id'].'|'.(int)$x['catalog_hotel_id']]=true;$excP=[];foreach($exc as$x)$excP[(string)$x['anex_hotel_id'].'|'.(int)$x['catalog_hotel_id']]=true;
$rows=[];$counts=[];$safe=[];foreach($pairs as$p){$sid=$p['samo_hotel_id'];$tv=(int)$p['tv_hotel_id'];$curRow=$curBy[$sid]??null;$target=$hotBy[$tv]??null;$source=$src[$sid][0];$why=[];$state='candidate';if(count($sourceTargets[$sid])>1)$why[]='source_multi_target';if(count($targetSources[$tv])>1)$why[]='target_multi_source';if($source['country']!==($target['country_name']??null))$why[]='country_mismatch';if(!$target||(int)$target['is_active']!==1)$why[]='target_inactive';$ss=c55_star($source['hotel']);$ts=$target?((int)$target['category']?:null):null;if($ss!==null&&$ts!==null&&$ss!==$ts)$why[]='category_mismatch';$other=array_values(array_filter($occBy[$tv]??[],fn($x)=>(string)$x['external_hotel_id']!==$sid));if($other)$why[]='target_occupied_other_samo';
 foreach($p['operator_proofs']as$op){if($op['operator']!=='anex')continue;foreach($op['native_proofs']as$npf){$native=(string)$npf['native_token'];$mm=$mapBy[$native]??[];$exact=array_values(array_filter($mm,fn($x)=>(int)$x['catalog_hotel_id']===$tv));if(count($mm)!==1||count($exact)!==1)$why[]='anex_mapping_not_unique_exact';$pk=$native.'|'.$tv;if(isset($decP[$pk]))$why[]='anex_decision_present';if(isset($excP[$pk]))$why[]='anex_exclusion_present';}}
 if($curRow!==null){if($curRow['decision_status']==='accepted'&&(int)$curRow['local_hotel_id']===$tv)$state='already_accepted';elseif($curRow['decision_status']==='accepted')$why[]='source_accepted_other_target';elseif($curRow['decision_status']==='pending'&&$curRow['local_hotel_id']===null){}else$why[]='source_existing_protected_state';}
 if($state!=='already_accepted')$state=$why?'hold':'safe_candidate';$why=array_values(array_unique($why));$counts[$state]=($counts[$state]??0)+1;$row=['samo_hotel_id'=>$sid,'tv_hotel_id'=>$tv,'tv_name'=>$p['hotel_name'],'operator_proof_count'=>count($p['operator_proofs']),'operator_proofs'=>$p['operator_proofs'],'source_catalog'=>$source,'target'=>$target,'current_source'=>$curRow,'target_occupants'=>$occBy[$tv]??[],'hold_reasons'=>$why,'state'=>$state,'safe_to_write_now'=>false];$rows[]=$row;if($state==='safe_candidate')$safe[]=['samo_hotel_id'=>$sid,'tv_hotel_id'=>$tv,'catalog_sha256'=>$source['catalog_sha256']];}
$out=['operation'=>C55_OP,'state'=>'completed_read_only','provider_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'direct_edge_count'=>55,'unique_pair_count'=>32,'unique_source_count'=>count($sourceTargets),'unique_target_count'=>count($targetSources),'state_counts'=>$counts,'safe_candidate_count'=>count($safe),'safe_candidates'=>$safe,'rows'=>$rows];$rh=c55_write($dir.'/result.json',$out);c55_write($dir.'/receipt.json',['operation'=>C55_OP,'state'=>'completed_read_only','result_sha256'=>$rh,'provider_calls'=>0,'database_writes'=>0,'mapping_writes'=>0]);echo json_encode(['state_counts'=>$counts,'safe_candidate_count'=>count($safe),'result_sha256'=>$rh],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";
