<?php
declare(strict_types=1);
const M117E_OP='hotel-match-samo-live30-native-refresh-1971-20260928-v117e';
const M117E_OPS=[5=>true,115=>true,315=>true,342=>true];
function m117e_need(bool $b,string $s):void{if(!$b)throw new RuntimeException($s);}
function m117e_json(array $x):string{return json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n";}
function m117e_save(string $p,array $x):string{$s=m117e_json($x);$h=fopen($p,'x+b');m117e_need($h!==false,'exclusive');try{m117e_need(fwrite($h,$s)===strlen($s)&&fflush($h),'durable');if(function_exists('fsync'))m117e_need(fsync($h),'sync');}finally{fclose($h);}return hash('sha256',$s);}
function m117e_id(mixed $v):?string{if(!is_int($v)&&!is_string($v))return null;$s=(string)$v;return preg_match('/^[1-9][0-9]{0,31}$/D',$s)?$s:null;}
function m117e_fact(array $r):?array{$h=m117e_id($r['hotelKey']??null);$o=is_array($r['original']??null)?$r['original']:[];$op=m117e_id($r['operatorKey']??($o['operatorKey']??null));$n=m117e_id($o['hotelKey']??null);if(!$h||!$n||!$op||!isset(M117E_OPS[(int)$op]))return null;$oo=m117e_id($o['operatorKey']??null);if($oo!==null&&$oo!==$op)return null;return ['catalog_id'=>$h,'supplier_namespace'=>'operator_'.$op,'native_id'=>$n,'original_is_operator_key'=>is_scalar($o['isOperatorHotelKey']??null)?(string)$o['isOperatorHotelKey']:null];}
function m117e_walk(array $x,string $ptr,array &$facts,array &$contexts,int $depth=0):void{if($depth>32)return;if(($f=m117e_fact($x))!==null)$facts[]=$f+['json_pointer'=>$ptr];if(isset($x['TOWNFROMINC'],$x['STATEINC'])){$p=[];foreach(['TOWNFROMINC','STATEINC','CHECKIN_BEG','CHECKIN_END','NIGHTS_FROM','NIGHTS_TILL','ADULT','CHILD','AGES','CURRENCYINC','PACKETTYPE','OPERATORS','HOTELS','GROUP_BY','PAGE'] as $k)if(isset($x[$k])&&(is_int($x[$k])||(is_string($x[$k])&&strlen($x[$k])<=300&&preg_match('/^[0-9, -]+$/D',$x[$k]))))$p[$k]=$x[$k];$contexts[]=['json_pointer'=>$ptr,'params'=>$p];}foreach($x as $k=>$v)if(is_array($v))m117e_walk($v,$ptr.'/'.str_replace(['~','/'],['~0','~1'],(string)$k),$facts,$contexts,$depth+1);}
function m117e_shape(array $x,int $depth=0):array{$out=[];foreach(array_slice($x,0,35,true) as $k=>$v){$out[(string)$k]=is_array($v)?($depth<2&&!array_is_list($v)?m117e_shape($v,$depth+1):['type'=>'array','count'=>count($v)]):get_debug_type($v);}return $out;}
function m117e_main(array $a):int{
 if(($a[1]??'')==='--self-test'){$f=m117e_fact(['hotelKey'=>99,'operatorKey'=>315,'original'=>['operatorKey'=>315,'hotelKey'=>123]]);m117e_need(($f['native_id']??null)==='123'&&$f['catalog_id']==='99','test_positive');m117e_need(m117e_fact(['hotelKey'=>99,'operatorKey'=>315,'original'=>['operatorKey'=>342,'hotelKey'=>123]])===null,'test_operator_conflict');m117e_need(m117e_fact(['hotelKey'=>99,'operatorKey'=>315])===null,'test_no_original');m117e_need(m117e_fact(['hotelKey'=>99,'operatorKey'=>25,'original'=>['hotelKey'=>123]])===null,'test_no_tv_namespace');$f=[];$c=[];m117e_walk(['PRICES'=>[['hotelKey'=>99,'operatorKey'=>115,'original'=>['hotelKey'=>619604521]]],'params'=>['TOWNFROMINC'=>1,'STATEINC'=>5,'sid'=>'SECRET','CHECKIN_BEG'=>'20261001']],'',$f,$c);m117e_need(count($f)===1&&count($c)===1&&!str_contains(m117e_json($c),'SECRET'),'test_whitelist');echo "M77_SELF_TEST_OK\n";return 0;}
 m117e_need(($a[1]??'')==='--execute','disabled');$root=(string)getenv('ANYTOUR_ROOT');$dir=(string)getenv('MATCH_OPERATION_DIR');$sha=(string)getenv('MATCH_SOURCE_SHA');m117e_need(is_dir($root)&&!is_link($root)&&basename($root)==='anytoour.ru'&&is_dir($dir)&&!is_link($dir)&&basename($dir)===M117E_OP&&preg_match('/^[a-f0-9]{40}$/D',$sha)===1,'scope');$rv=json_decode((string)file_get_contents($dir.'/reservation.json'),true,32,JSON_THROW_ON_ERROR);m117e_need(($rv['operation']??'')===M117E_OP&&($rv['source_sha']??'')===$sha,'reservation');foreach(['execution-started.json','result.json','receipt.json'] as $n)m117e_need(!file_exists($dir.'/'.$n),'no_replay');m117e_save($dir.'/execution-started.json',['operation'=>M117E_OP,'source_sha'=>$sha]);
 $out=['operation'=>M117E_OP,'source_sha'=>$sha,'database_writes'=>0,'mapping_writes'=>0,'provider_http_calls'=>0,'no_replay'=>true];
 try{$cp=$root.'/_preview/search3-anex-candidate/.andromeda-private.php';m117e_need(is_file($cp)&&!is_link($cp),'config');$cfg=require $cp;m117e_need(is_array($cfg)&&is_string($cfg['catalog_path']??null),'catalog_path');$private=dirname($cfg['catalog_path']);$searches=$private.'/searches';m117e_need(is_dir($searches)&&!is_link($searches),'searches');$cut=time()-30*86400;$sources=[];$native=[];$ctx=[];$shapes=[];$files=0;$bytes=0;$pages=0;$offers=0;$bad=0;$partial=false;$seen=[];
 $consume=function(string $path,string $label,bool $isSearch)use(&$sources,&$native,&$ctx,&$shapes,&$files,&$bytes,&$pages,&$offers,&$bad,&$partial,&$seen,$cut):void{if(is_link($path)||!is_file($path))return;$sz=filesize($path);if(!$sz||$sz>16777216)return;if($files>=25000||$bytes+$sz>1073741824){$partial=true;return;}$files++;$bytes+=$sz;$raw=file_get_contents($path);$hash=hash('sha256',$raw);if(isset($seen[$hash]))return;$seen[$hash]=true;try{$x=json_decode($raw,true,64,JSON_THROW_ON_ERROR);}catch(Throwable){$bad++;return;}if(!is_array($x))return;$facts=[];$contexts=[];m117e_walk($x,'',$facts,$contexts);foreach($facts as $f){$key=$f['catalog_id'].'|'.$f['supplier_namespace'].'|'.$f['native_id'];if(!isset($native[$key]))$native[$key]=$f+['evidence'=>[]];if(count($native[$key]['evidence'])<3)$native[$key]['evidence'][]=['source_file'=>$label,'sha256'=>$hash,'json_pointer'=>$f['json_pointer']];}if(!$isSearch)return;$st=is_array($x['store']??null)?$x['store']:[];$sn=is_array($st['snapshot']??null)?$st['snapshot']:[];if(($sn['provider']??null)!=='andromeda'||!is_int($st['created_at']??null)||$st['created_at']<$cut||!is_array($sn['offers']??null))return;$pages++;if(count($shapes)<3)$shapes[]=['file'=>$label,'shape'=>m117e_shape($x)];foreach($sn['offers'] as $i=>$o){if(!is_array($o)||($o['supplier_namespace']??null)!=='andromeda_catalog'||($id=m117e_id($o['external_hotel_id']??null))===null)continue;$offers++;$sources[$id]=($sources[$id]??['catalog_id'=>$id,'observed_offers'=>0,'contexts'=>[]]);$sources[$id]['observed_offers']++;$wh=[];foreach(['hotel','operator','operator_ref','check_in','nights','adults','children'] as $k)if(isset($o[$k])&&is_scalar($o[$k])&&strlen((string)$o[$k])<=240)$wh[$k]=$o[$k];$candidate=['file'=>$label,'file_sha256'=>$hash,'created_at'=>$st['created_at'],'json_pointer'=>'/store/snapshot/offers/'.$i,'offer'=>$wh,'provider_requests'=>$contexts];$sig=hash('sha256',m117e_json($wh));if(count($sources[$id]['contexts'])<6)$sources[$id]['contexts'][$sig]=$candidate;}foreach($contexts as $c){$key=hash('sha256',m117e_json($c['params']));if(!isset($ctx[$key]))$ctx[$key]=$c+['file'=>$label,'sha256'=>$hash];}};
 foreach(new DirectoryIterator($searches) as $e){if($partial)break;if($e->isDot()||!$e->isFile()||$e->isLink()||!str_ends_with($e->getFilename(),'.json')||$e->getMTime()<$cut)continue;$consume($e->getPathname(),'searches/'.$e->getFilename(),true);}
 // v117b deliberately scans only current stored SAMO search files; historical operation raw was already covered by v77.\n require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();m117e_need($db instanceof PDO,'db');$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('START TRANSACTION READ ONLY');try{$ident=$db->query("SELECT supplier_namespace,external_hotel_id,local_hotel_id,decision_status,catalog_sha256,evidence_sha256 FROM andromeda_hotel_identities ORDER BY supplier_namespace,external_hotel_id")->fetchAll(PDO::FETCH_ASSOC);$hotels=$db->query('SELECT id,name,country_name,region_name,subregion_name,category,is_active FROM catalog_hotels WHERE id IN (SELECT DISTINCT local_hotel_id FROM andromeda_hotel_identities WHERE local_hotel_id IS NOT NULL)')->fetchAll(PDO::FETCH_ASSOC);$db->rollBack();}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}$accepted=[];foreach($ident as $i)if($i['supplier_namespace']==='andromeda_catalog'&&$i['decision_status']==='accepted'&&$i['local_hotel_id']!==null)$accepted[(string)$i['external_hotel_id']][(int)$i['local_hotel_id']]=true;$unmapped=0;foreach($sources as $id=>&$s){$s['contexts']=array_values($s['contexts']);$s['current_accepted_locals']=array_keys($accepted[(string)$id]??[]);if(!$s['current_accepted_locals'])$unmapped++;}unset($s);ksort($native,SORT_NATURAL);ksort($sources,SORT_NATURAL);$out+=['state'=>$partial?'partial_retained_native_scan':'completed_retained_native_scan','files_examined'=>$files,'bytes_examined'=>$bytes,'unique_file_hashes'=>count($seen),'invalid_json_files'=>$bad,'live30_page_files'=>$pages,'live30_offer_rows'=>$offers,'live30_catalog_sources'=>count($sources),'live30_unmapped_catalog_sources'=>$unmapped,'raw_native_facts'=>count($native),'native_facts'=>array_values($native),'source_frontier'=>array_values($sources),'provider_contexts'=>array_values($ctx),'current_identities'=>$ident,'current_mapped_hotels'=>$hotels,'search_state_shapes'=>$shapes,'generated_at_utc'=>gmdate('c')];
 }catch(Throwable $e){$out['state']='failed_retained_native_scan';$out['error_class']=get_class($e);$out['reason']=preg_match('/^[a-zA-Z0-9_]+$/D',$e->getMessage())?$e->getMessage():'read_failed';}
 $hash=m117e_save($dir.'/result.json',$out);m117e_save($dir.'/receipt.json',['operation'=>M117E_OP,'source_sha'=>$sha,'state'=>$out['state'],'result_sha256'=>$hash,'database_writes'=>0,'mapping_writes'=>0,'provider_http_calls'=>0,'no_replay'=>true]);echo m117e_json(array_filter($out,fn($x)=>!is_array($x)));return $out['state']==='completed_retained_native_scan'?0:2;
}
if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__)exit(m117e_main($argv));
