<?php
declare(strict_types=1);
/** A new file-only operation. It never runs any retained supplier operation. */
const MRF_OP='hotel-match-mass948-retained-files-1971-20260927-v1';
const MRF_PRIOR='292c8f40d5bc9164e638246fdafa7b5f7113646c1c1597edee9a89b9c1a62851';
function mrf_need(bool $v,string $why):void{if(!$v)throw new RuntimeException($why);}
function mrf_json(mixed $v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
function mrf_save(string $path,array $v):string{$raw=mrf_json($v)."\n";$f=@fopen($path,'x+b');mrf_need($f!==false,'exclusive_create');try{mrf_need(fwrite($f,$raw)===strlen($raw)&&fflush($f),'durable_write');if(function_exists('fsync'))mrf_need(fsync($f),'durable_sync');}finally{fclose($f);}return hash('sha256',$raw);}
function mrf_id(mixed $v):?string{if(!is_int($v)&&!is_string($v))return null;$s=(string)$v;return preg_match('/^[1-9][0-9]{0,21}$/D',$s)===1?$s:null;}
function mrf_hash(mixed $v):bool{return is_string($v)&&preg_match('/^[0-9a-f]{64}$/D',$v)===1;}
function mrf_fields(array $r):array{
 $out=[];foreach(['id','name','lName','hotel_name','hotelName','country','country_id','country_name','state','stateId','stateKey','stateLName','town','townId','townKey','townLName','region','regionId','regionKey','region_name','subregion_name','star','starId','starKey','category','latitude','longitude','lat','lon','lng','operatorKey','operator_key','operator_id','hotelKey','hotel_key','originalHotelId','original_hotel_id','external_hotel_id','supplier_namespace','catalog_id','catalog_hotel_id','local_hotel_id','tv_hotel_id']as$k){$x=$r[$k]??null;if(is_int($x)||is_float($x)||is_bool($x)||(is_string($x)&&strlen($x)<=1024))$out[$k]=$x;}
 foreach(['original','hotel','source']as$k)if(is_array($r[$k]??null)){$nested=$r[$k];unset($nested['original'],$nested['hotel'],$nested['source']);$out[$k]=mrf_fields($nested);}
 return$out;
}
function mrf_catalog_rows(array $x,string $fileSha,string $file):array{
 $p=$x['all']['payload']??[];$rows=[];$state=$x['all']['params']['STATEINC']??null;
 foreach(['HOTELS','TOWNS','TOWNTO','STATES','STARS']as$kind){foreach(($p[$kind]??[])as$i=>$r){if(!is_array($r)||mrf_id($r['id']??null)===null)continue;$rows[]=['kind'=>$kind,'row'=>mrf_fields($r),'stateinc'=>$state,'local_country_id'=>$x['local_country_id']??null,'file'=>$file,'file_sha256'=>$fileSha,'json_pointer'=>'/all/payload/'.$kind.'/'.$i];}}
 return$rows;
}
function mrf_read(string $p,int $max):array{mrf_need(is_file($p)&&!is_link($p),'file_missing_or_symlink');$n=filesize($p);mrf_need(is_int($n)&&$n>=2&&$n<=$max,'file_size');$raw=(string)file_get_contents($p);$x=json_decode($raw,true,128,JSON_THROW_ON_ERROR);mrf_need(is_array($x),'json_shape');return[$x,hash('sha256',$raw),strlen($raw)];}
function mrf_catalog(string $path):array{
 $paths=[$path];$countryDir=dirname($path).'/countries';if(is_dir($countryDir)&&!is_link($countryDir))foreach(glob($countryDir.'/*.json')?:[]as$p)if(!is_link($p))$paths[]=$p;$paths=array_values(array_unique($paths));sort($paths,SORT_STRING);mrf_need(count($paths)<=512,'catalog_file_cap');$files=[];$rows=[];$bytes=0;
 foreach($paths as$p){$name=($p===$path?'base/':'countries/').basename($p);try{[$x,$sha,$n]=mrf_read($p,134217728);$bytes+=$n;mrf_need($bytes<=536870912,'catalog_byte_cap');$got=mrf_catalog_rows($x,$sha,$name);$files[]=['file'=>$name,'sha256'=>$sha,'bytes'=>$n,'rows'=>count($got),'payload_keys'=>array_keys($x['all']['payload']??[]),'state'=>'read'];foreach($got as$r)$rows[]=$r;mrf_need(count($rows)<=300000,'catalog_row_cap');}catch(Throwable$e){$files[]=['file'=>$name,'state'=>'unreadable','error_class'=>get_class($e)];}}
 return['files'=>$files,'rows'=>$rows];
}
function mrf_allowed_op(string $op):bool{return preg_match('/^hotel-match-live30-common4-(?:acquire|continuation-acquire|continuation-resume)-1971-2026092[34]-[a-z0-9-]+$/D',$op)===1||preg_match('/^hotel-match-live942-tv-anex-refresh-1971-20260923-o[0-9]+-n[0-9]+-v2$/D',$op)===1||in_array($op,['hotel-match-samo-live30-common4-acquire-1971-20260924-v1','hotel-match-samo-business-live30-common4-acquire-1971-20260924-v2'],true);}
function mrf_edge(array $e,string $op,string $sha,int $i):?array{
 $ids=$e['positive_native_candidates']??null;if(!is_array($ids)||count($ids)!==1||mrf_id($ids[0]??null)===null)return null;$native=mrf_id($ids[0]);$ns=(string)($e['namespace']??'');$operator=(int)($e['operator_id']??0);$row=['source_operation'=>$op,'source_result_sha256'=>$sha,'source_edge_sha256'=>hash('sha256',mrf_json($e)),'json_pointer'=>'/edges/'.$i,'supplier_namespace'=>$ns,'operator_id'=>$operator,'external_hotel_id'=>$native,'safe_to_write_now'=>false];
 if(str_starts_with($op,'hotel-match-samo-')){$allowed=[5=>'operator_5',115=>'operator_115',315=>'operator_315',342=>'operator_342'];$cid=mrf_id($e['catalog_id']??null);if(($e['state']??'')!=='captured_single_native'||$cid===null||($allowed[$operator]??null)!==$ns)return null;return$row+['kind'=>'samo_operator','catalog_id'=>$cid];}
 $allowed=[13=>'anex',18=>'bgoperator',25=>'operator_315',43=>'operator_342'];$local=mrf_id($e['tv_hotel_id']??null);if(($e['state']??'')!=='detail_identity_verified'||($e['link_state']??'')!=='captured_single_native'||$local===null||($allowed[$operator]??null)!==$ns)return null;
 foreach(['operator_link_sha256','search_id_sha256','tour_id_sha256']as$k){if(!mrf_hash($e[$k]??null))return null;$row[$k]=$e[$k];}return$row+['kind'=>'tv_operator','tv_hotel_id'=>(int)$local,'operator_link_host'=>(string)($e['operator_link_host']??'')];
}
function mrf_operations(string $root):array{
 mrf_need(is_dir($root)&&!is_link($root),'operations_root');$files=[];$tv=[];$samo=[];$bytes=0;$ops=[];
 foreach(new DirectoryIterator($root)as$e)if(!$e->isDot()&&!$e->isLink()&&$e->isDir()&&mrf_allowed_op($e->getFilename()))$ops[]=$e->getFilename();sort($ops,SORT_STRING);mrf_need(count($ops)<=512,'operation_cap');
 foreach($ops as$op){try{[$r,$sha,$n]=mrf_read($root.'/'.$op.'/result.json',67108864);[$q,$qsha]=mrf_read($root.'/'.$op.'/receipt.json',1048576);$bytes+=$n;mrf_need($bytes<=536870912,'operation_bytes_cap');$states=['completed_read_only','completed_read_only_partial','terminal_day_changed_no_replay','terminal_quota_stop_no_replay','terminal_wrapper_timeout_salvaged_no_replay'];mrf_need(in_array($r['state']??'',$states,true)&&($q['state']??'')===($r['state']??null)&&($q['result_sha256']??'')===$sha,'terminal_receipt');mrf_need(($r['operation']??'')===$op,'source_operation');foreach(['database_writes','mapping_writes']as$k)mrf_need(($r[$k]??null)===0,'source_write_authority');if($r['state']==='terminal_wrapper_timeout_salvaged_no_replay')mrf_need(($q['salvaged_after_wrapper_timeout']??false)===true&&($q['no_replay']??false)===true,'salvage_receipt');if(!str_starts_with($op,'hotel-match-samo-'))mrf_need(($r['tourvisor_account']??'')==='TOURVISOR_ANEX_JWT','paid_account');$count=0;
 foreach(($r['edges']??[])as$i=>$e){if(!is_array($e))continue;$p=mrf_edge($e,$op,$sha,(int)$i);if($p===null)continue;if($p['kind']==='tv_operator')$tv[]=$p;else$samo[]=$p;$count++;}mrf_need(count($tv)+count($samo)<=100000,'edge_cap');$files[]=['operation'=>$op,'state'=>'verified_terminal','source_state'=>$r['state'],'result_sha256'=>$sha,'receipt_sha256'=>$qsha,'raw_edge_count'=>count($r['edges']??[]),'valid_single_edges'=>$count,'historical_provider_calls'=>$r['provider_calls']??$r['andromeda_calls']??null];
 }catch(Throwable$e){$files[]=['operation'=>$op,'state'=>'excluded_unverified','error_class'=>get_class($e),'error_code'=>preg_replace('/[^A-Za-z0-9_:-]+/','_',substr($e->getMessage(),0,80))];}}
 return['files'=>$files,'tv_edges'=>$tv,'samo_edges'=>$samo];
}
function mrf_offers(string $dir):array{
 mrf_need(is_dir($dir)&&!is_link($dir),'saved_search_dir');$seen=[];$files=0;$pages=0;$total=0;$invalid=0;$keys=[];
 foreach(new DirectoryIterator($dir)as$e){if($e->isDot()||$e->isLink()||!$e->isFile()||!str_ends_with($e->getFilename(),'.json'))continue;mrf_need(++$files<=10000,'saved_file_cap');try{[$x,$sha]=mrf_read($e->getPathname(),16777216);}catch(Throwable){$invalid++;continue;}$s=$x['store']??[];$p=$s['snapshot']??[];if(($p['provider']??'')!=='andromeda'||!is_int($s['created_at']??null)||$s['created_at']<time()-30*86400)continue;$pages++;foreach(($p['offers']??[])as$i=>$o){if(!is_array($o))continue;mrf_need(++$total<=500000,'saved_offer_cap');$row=mrf_fields($o);if($row===[])continue;$sig=hash('sha256',mrf_json($row));if(!isset($seen[$sig]))$seen[$sig]=['row'=>$row,'row_sha256'=>$sig,'file_sha256'=>$sha,'json_pointer'=>'/store/snapshot/offers/'.$i];foreach(array_keys($o)as$k)$keys[(string)$k]=true;}}
 return['files_examined'=>$files,'invalid_files'=>$invalid,'live_pages'=>$pages,'offer_rows_examined'=>$total,'offer_field_names'=>array_keys($keys),'unique_hotel_projections'=>array_values($seen)];
}
function mrf_test():int{$n=0;$c=function(bool $v)use(&$n){mrf_need($v,'selftest_'.$n);$n++;};$c(mrf_id('123')==='123');foreach([0,-1,'01','1.2',1.2,null,[]]as$v)$c(mrf_id($v)===null);$x=['all'=>['params'=>['STATEINC'=>4],'payload'=>['HOTELS'=>[['id'=>7,'name'=>'H','password'=>'secret']]]]];$rows=mrf_catalog_rows($x,str_repeat('a',64),'countries/4.json');$c(count($rows)===1&&$rows[0]['kind']==='HOTELS'&&!isset($rows[0]['row']['password']));$c(mrf_catalog_rows(['all'=>['payload'=>['HOTEL'=>[]]]],str_repeat('a',64),'x')===[]);$c(!mrf_allowed_op('../secrets'));$c(!mrf_allowed_op(MRF_OP));$op='hotel-match-live30-common4-continuation-acquire-1971-20260923-c35-n100-v1';$c(mrf_allowed_op($op));$e=['state'=>'detail_identity_verified','link_state'=>'captured_single_native','positive_native_candidates'=>[77],'namespace'=>'operator_315','operator_id'=>25,'tv_hotel_id'=>99,'operator_link_sha256'=>str_repeat('a',64),'search_id_sha256'=>str_repeat('b',64),'tour_id_sha256'=>str_repeat('c',64)];$c(mrf_edge($e,$op,str_repeat('d',64),0)['external_hotel_id']==='77');foreach(['operator_link_sha256','search_id_sha256','tour_id_sha256']as$k){$bad=$e;unset($bad[$k]);$c(mrf_edge($bad,$op,str_repeat('d',64),0)===null);}$bad=$e;$bad['operator_id']=13;$c(mrf_edge($bad,$op,str_repeat('d',64),0)===null);$bad=$e;$bad['positive_native_candidates']=[77,78];$c(mrf_edge($bad,$op,str_repeat('d',64),0)===null);$sop='hotel-match-samo-business-live30-common4-acquire-1971-20260924-v2';$s=['state'=>'captured_single_native','positive_native_candidates'=>[77],'namespace'=>'operator_315','operator_id'=>315,'catalog_id'=>123];$c(mrf_edge($s,$sop,str_repeat('e',64),0)['catalog_id']==='123');$s['namespace']='operator_5';$c(mrf_edge($s,$sop,str_repeat('e',64),0)===null);$safe=mrf_fields(['id'=>7,'token'=>'x','url'=>'https://x/?token=x','original'=>['hotelKey'=>77,'password'=>'x']]);$c(!isset($safe['token'])&&!isset($safe['url'])&&!isset($safe['original']['password'])&&$safe['original']['hotelKey']===77);$tmp=sys_get_temp_dir().'/mrf-'.bin2hex(random_bytes(6));try{$h=mrf_save($tmp,['a'=>1]);$c(hash_file('sha256',$tmp)===$h);$rejected=false;try{mrf_save($tmp,['b'=>2]);}catch(Throwable){$rejected=true;}$c($rejected);}finally{if(is_file($tmp))unlink($tmp);}return$n;}
if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__){
 if(($argv[1]??'')==='--self-test'){echo 'RETAINED_FILES_TESTS_OK '.mrf_test()."\n";exit;}
 mrf_need(($argv[1]??'')==='--execute','disabled');$root=(string)getenv('ANYTOUR_ROOT');$dir=(string)getenv('MATCH_OPERATION_DIR');$head=(string)getenv('MATCH_SOURCE_SHA');mrf_need(is_dir($root)&&!is_link($root)&&basename($root)==='anytoour.ru'&&is_dir($dir)&&!is_link($dir)&&basename($dir)===MRF_OP&&preg_match('/^[0-9a-f]{40}$/D',$head)===1,'runtime_scope');[$prior,$priorSha]=mrf_read(__DIR__.'/../../prior-context.json',83886080);mrf_need($priorSha===MRF_PRIOR&&($prior['state']??'')==='completed_read_only_mass948_context'&&count($prior['context']['rows']??[])===948,'prior_context');[$res]=mrf_read($dir.'/reservation.json',1048576);mrf_need(($res['operation']??'')===MRF_OP&&($res['source_sha']??'')===$head&&($res['state']??'')==='reserved_before_file_read','reservation');foreach(['execution-started.json','result.json','receipt.json']as$f)mrf_need(!file_exists($dir.'/'.$f),'terminal_no_replay');mrf_save($dir.'/execution-started.json',['operation'=>MRF_OP,'source_sha'=>$head,'db_access'=>false,'provider_http_calls'=>0]);
 $out=['operation'=>MRF_OP,'source_sha'=>$head,'prior_context_sha256'=>MRF_PRIOR,'scope_count'=>948,'db_access'=>false,'database_writes'=>0,'mapping_writes'=>0,'provider_http_calls'=>0,'safe_to_write_now'=>false,'no_replay'=>true];
 try{$config=$root.'/_preview/search3-anex-candidate/.andromeda-private.php';mrf_need(is_file($config)&&!is_link($config),'private_config');$c=require$config;mrf_need(is_array($c)&&is_string($c['catalog_path']??null),'catalog_path');$out['catalog']=mrf_catalog($c['catalog_path']);$out['retained']=mrf_operations(dirname($dir));$out['saved_offers']=mrf_offers(dirname($c['catalog_path']).'/searches');$out['state']='completed_read_only_mass948_retained_files';}catch(Throwable$e){$out['state']='failed_read_only_mass948_retained_files';$out['error_class']=get_class($e);$out['error_code']=preg_replace('/[^A-Za-z0-9_:-]+/','_',substr($e->getMessage(),0,120));}
 $out['generated_at_utc']=gmdate('c');$h=mrf_save($dir.'/result.json',$out);mrf_save($dir.'/receipt.json',['operation'=>MRF_OP,'source_sha'=>$head,'state'=>$out['state'],'result_sha256'=>$h,'readback_verified'=>hash_file('sha256',$dir.'/result.json')===$h,'db_access'=>false,'database_writes'=>0,'mapping_writes'=>0,'provider_http_calls'=>0,'no_replay'=>true]);echo mrf_json(['state'=>$out['state'],'catalog_rows'=>count($out['catalog']['rows']??[]),'tv_edges'=>count($out['retained']['tv_edges']??[]),'samo_edges'=>count($out['retained']['samo_edges']??[]),'saved_hotel_projections'=>count($out['saved_offers']['unique_hotel_projections']??[]),'error_code'=>$out['error_code']??null])."\n";exit($out['state']==='completed_read_only_mass948_retained_files'?0:2);
}
