<?php
declare(strict_types=1);
/** MATCH-only strict exact local resolver for sealed public operator evidence. READ ONLY. */
const HMPEL_OP='hotel-match-public-operator-exact-local-resolve-1971-20260917-v1';
const HMPEL_PREFLIGHT_SHA='804cb746a5e8957df35840ead3b19f6c9e9e4140a3ac303c58d8c67131f6354f';
const HMPEL_EVIDENCE_JSON=<<<'JSON'
[
{"ns":"operator_342","external_id":"549","andromeda_id":"2000034121","source_name":"Delphin Palace","source_geo":"Лара"},
{"ns":"operator_342","external_id":"651","andromeda_id":"2000098416","source_name":"Fifty Five Suite","source_geo":"Мармарис"},
{"ns":"operator_342","external_id":"655","andromeda_id":"190031","source_name":"Ramada Plaza by Wyndham Antalya","source_geo":"Анталия"},
{"ns":"operator_342","external_id":"743","andromeda_id":"3060","source_name":"Labranda Mares Hotel","source_geo":"Ичмелер"},
{"ns":"operator_342","external_id":"12135","andromeda_id":"175606","source_name":"Rixos Sharm El Sheikh (Nabq Bay)","source_geo":"Набк Бэй"},
{"ns":"operator_342","external_id":"12281","andromeda_id":"2000039701","source_name":"Ivy Cyrene Sharm (ex. Cyrene Sharm)","source_geo":"Рас-Насрани"},
{"ns":"operator_342","external_id":"17163","andromeda_id":"2000023232","source_name":"The Meretto Hotel Istanbul Old City","source_geo":"Султанахмет"},
{"ns":"operator_342","external_id":"18273","andromeda_id":"2000062084","source_name":"Raimond Hotel","source_geo":"Кумкапы"},
{"ns":"operator_342","external_id":"19652","andromeda_id":"67775","source_name":"Grand Emin Hotel","source_geo":"Йеникапы"},
{"ns":"operator_342","external_id":"21978","andromeda_id":"650","source_name":"Conrad Istanbul Bosphorus","source_geo":"Бешикташ"},
{"ns":"operator_342","external_id":"23547","andromeda_id":"182522","source_name":"Best Nobel Hotel","source_geo":"Сиркеджи"},
{"ns":"operator_342","external_id":"24278","andromeda_id":"2000072249","source_name":"Badawia Sharm Resort","source_geo":"Шарм-эль-Шейх"},
{"ns":"operator_342","external_id":"24891","andromeda_id":"2000057636","source_name":"Bodrium Otel & You Spa","source_geo":"Бодрум"},
{"ns":"operator_342","external_id":"24954","andromeda_id":"2000061716","source_name":"Le Meridien Bodrum Beach Resort","source_geo":"Бодрум"},
{"ns":"operator_342","external_id":"25728","andromeda_id":"2000052591","source_name":"Arabia Azur Hurgada","source_geo":"Хургада"},
{"ns":"operator_342","external_id":"27835","andromeda_id":"2000073592","source_name":"Taxim Town Hotel","source_geo":"Таксим"},
{"ns":"operator_342","external_id":"28164","andromeda_id":"2000071512","source_name":"Golden Gate","source_geo":"Топкапы"},
{"ns":"operator_342","external_id":"32987","andromeda_id":"2000086129","source_name":"The Norm Collection Door","source_geo":"Торба"},
{"ns":"operator_342","external_id":"36672","andromeda_id":"2000034136","source_name":"Green Maxx Hotel","source_geo":"Кадрие"},
{"ns":"operator_315","external_id":"19155","andromeda_id":"2000043232","source_name":"Domina Coral Bay King's Lake","source_geo":"Шейх Коаст"},
{"ns":"operator_315","external_id":"69721","andromeda_id":"175606","source_name":"Rixos Sharm El Sheikh (Adult Only 18+)","source_geo":"Набк"},
{"ns":"operator_315","external_id":"780677","andromeda_id":"2000062084","source_name":"Raimond","source_geo":"Кумкапы"}
]
JSON;
function hmpel_req(bool $ok,string $why):void{if(!$ok)throw new RuntimeException($why);}
function hmpel_json(array $x):string{return json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";}
function hmpel_write(string $p,array $x):string{$raw=hmpel_json($x);$f=@fopen($p,'x+b');hmpel_req(is_resource($f),'exclusive_output');try{hmpel_req(fwrite($f,$raw)===strlen($raw)&&fflush($f),'output_write');if(function_exists('fsync'))hmpel_req(fsync($f),'output_sync');rewind($f);hmpel_req(stream_get_contents($f)===$raw,'output_readback');}finally{fclose($f);}return hash('sha256',$raw);}
function hmpel_read(string $p,int $max=32768):array{hmpel_req(is_file($p)&&!is_link($p)&&realpath($p)===$p,'input_path');$raw=file_get_contents($p);hmpel_req(is_string($raw)&&strlen($raw)<=$max,'input_size');$x=json_decode($raw,true,64,JSON_THROW_ON_ERROR);hmpel_req(is_array($x),'input_shape');return$x;}
function hmpel_q(PDO $db,string $sql,array $args=[]):array{$s=$db->prepare($sql);$s->execute(array_values($args));$r=$s->fetchAll(PDO::FETCH_ASSOC);hmpel_req(count($r)<100000,'query_budget');return$r;}
function hmpel_protected($v,string $key='',int $depth=0):bool{if($depth>20)return true;$s=preg_match('/manual|exclude|exclusion|conflict|reject|review|protect/i',$key)===1;if(is_array($v)){if($s&&$v!==[])return true;foreach($v as$k=>$x)if(hmpel_protected($x,(string)$k,$depth+1))return true;return false;}if(!$s||$v===null)return false;if(is_bool($v))return$v;if(is_numeric($v))return(float)$v!=0;if(is_string($v))return!in_array(strtolower(trim($v)),['','false','none','no','null'],true);return true;}
function hmpel_lower(string $s):string{if(function_exists('mb_strtolower'))return mb_strtolower($s,'UTF-8');return strtolower(strtr($s,['А'=>'а','Б'=>'б','В'=>'в','Г'=>'г','Д'=>'д','Е'=>'е','Ё'=>'ё','Ж'=>'ж','З'=>'з','И'=>'и','Й'=>'й','К'=>'к','Л'=>'л','М'=>'м','Н'=>'н','О'=>'о','П'=>'п','Р'=>'р','С'=>'с','Т'=>'т','У'=>'у','Ф'=>'ф','Х'=>'х','Ц'=>'ц','Ч'=>'ч','Ш'=>'ш','Щ'=>'щ','Ъ'=>'ъ','Ы'=>'ы','Ь'=>'ь','Э'=>'э','Ю'=>'ю','Я'=>'я']));}
function hmpel_name_key(string $s):string{$s=preg_replace('/\s*\((?:ex|ех)\.?[^)]*\)\s*$/iu','',$s)??$s;$parts=preg_split('/[^\p{L}\p{N}]+/u',hmpel_lower(trim($s)),-1,PREG_SPLIT_NO_EMPTY);if(!is_array($parts))return'';$parts=array_values(array_filter($parts,static fn($x)=>$x!=='hotel'));return implode('',$parts);}
function hmpel_geo_key(string $s):string{return preg_replace('/[^\p{L}\p{N}]+/u','',hmpel_lower(trim($s)))??'';}
function hmpel_names(array $e):array{$src=is_array($e['source']??null)?$e['source']:$e;$out=[];foreach(['name','lName','hotel_name','hotelName','original_name']as$k){$v=$src[$k]??null;if(is_string($v)&&trim($v)!=='')$out[hmpel_name_key($v)]=trim($v);}return$out;}
function hmpel_bridge(array $e,string $aid):?array{$b=$e['provider_bridges']??null;if(!is_array($b))return null;foreach($b as$x)if(is_array($x)&&(string)($x['andromeda_hotel_id']??'')===$aid)return$x;return null;}
function hmpel_points($v,array &$o,int $d=0):void{hmpel_req($d<=32,'coordinate_depth');if(!is_array($v))return;$a=$v['latitude']??$v['lat']??null;$b=$v['longitude']??$v['lon']??$v['lng']??null;if(is_numeric($a)&&is_numeric($b)){$a=(float)$a;$b=(float)$b;if(is_finite($a)&&is_finite($b)&&abs($a)<=90&&abs($b)<=180&&($a!=0||$b!=0))$o[]=[$a,$b];}foreach($v as$x)if(is_array($x))hmpel_points($x,$o,$d+1);}
function hmpel_km(array $a,array $b):float{[$x,$y,$u,$v]=array_map('deg2rad',[$a[0],$a[1],$b[0],$b[1]]);$h=sin(($u-$x)/2)**2+cos($x)*cos($u)*sin(($v-$y)/2)**2;return 6371.0088*2*asin(sqrt(min(1.0,max(0.0,$h))));}
function hmpel_main():void{
 hmpel_req(PHP_SAPI==='cli'&&getenv('MATCH_OPERATION_ID')===HMPEL_OP,'operation_guard');$sha=(string)getenv('MATCH_SOURCE_SHA');hmpel_req(preg_match('/^[a-f0-9]{40}$/D',$sha)===1,'source_guard');$ev=json_decode(HMPEL_EVIDENCE_JSON,true,32,JSON_THROW_ON_ERROR);hmpel_req(is_array($ev)&&count($ev)===22,'evidence_count');
 $dir=(string)getenv('HOME').'/.anytoour-match/operations/'.HMPEL_OP;$res=hmpel_read($dir.'/reservation.json');hmpel_req(($res['operation_id']??'')===HMPEL_OP&&($res['source_sha']??'')===$sha&&($res['state']??'')==='reserved_before_db_access'&&($res['preflight_result_sha256']??'')===HMPEL_PREFLIGHT_SHA,'reservation_guard');
 $out=['operation_id'=>HMPEL_OP,'source_sha'=>$sha,'state'=>'failed_no_replay','no_replay'=>true,'preflight_result_sha256'=>HMPEL_PREFLIGHT_SHA,'checked_input_rows'=>22,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'safe_to_write_now'=>false];$db=null;$phase='bootstrap';ob_start();try{
  $root=realpath(getcwd());hmpel_req(is_string($root)&&basename($root)==='anytoour.ru','root_guard');$bp=$root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');hmpel_req(realpath($bp)===$bp&&!is_link($bp),'bootstrap_path');require_once$bp;$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');$phase='current_read';
  $eng=hmpel_q($db,"SELECT TABLE_NAME,ENGINE FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME IN ('andromeda_hotel_identities','catalog_hotels','hotel_aliases') ORDER BY TABLE_NAME");hmpel_req(count($eng)===3,'table_contract');foreach($eng as$t)hmpel_req(strtoupper((string)$t['ENGINE'])==='INNODB','nontransactional_table');
  $countries=[];$operator=[];$andromeda=[];
  foreach($ev as$e){$rr=hmpel_q($db,"SELECT local_hotel_id,decision_status,evidence_sha256,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace=? AND external_hotel_id=?",[$e['ns'],$e['external_id']]);hmpel_req(count($rr)===1,'operator_row_count');$r=$rr[0];$oe=json_decode((string)$r['evidence_json'],true,64,JSON_THROW_ON_ERROR);hmpel_req(is_array($oe),'operator_evidence_shape');$bridge=hmpel_bridge($oe,$e['andromeda_id']);hmpel_req(is_array($bridge),'native_bridge');$cid=(int)($bridge['country_id']??0);hmpel_req($cid>0,'country_id');$countries[$cid]=1;$operator[$e['ns'].'/'.$e['external_id']]=[$r,$oe,$bridge];$aa=hmpel_q($db,"SELECT local_hotel_id,decision_status,evidence_sha256,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=?",[$e['andromeda_id']]);hmpel_req(count($aa)===1,'andromeda_row_count');$ar=$aa[0];$ae=json_decode((string)$ar['evidence_json'],true,64,JSON_THROW_ON_ERROR);hmpel_req(is_array($ae),'andromeda_evidence_shape');$andromeda[$e['andromeda_id']]=[$ar,$ae];}
  $cids=array_keys($countries);$marks=implode(',',array_fill(0,count($cids),'?'));$hotels=[];$index=[];
  foreach(hmpel_q($db,"SELECT id,country_id,region_name,subregion_name,name,latitude,longitude,is_active FROM catalog_hotels WHERE is_active=1 AND country_id IN ($marks) ORDER BY id",$cids)as$h){$id=(int)$h['id'];$h['id']=$id;$h['country_id']=(int)$h['country_id'];$hotels[$id]=$h;$k=hmpel_name_key((string)$h['name']);if($k!=='')$index[$h['country_id']][$k][$id]=1;}
  foreach(hmpel_q($db,"SELECT a.hotel_id,a.alias,h.country_id FROM hotel_aliases a JOIN catalog_hotels h ON h.id=a.hotel_id WHERE h.is_active=1 AND h.country_id IN ($marks) ORDER BY a.hotel_id,a.id",$cids)as$a){$k=hmpel_name_key((string)$a['alias']);if($k!=='')$index[(int)$a['country_id']][$k][(int)$a['hotel_id']]=1;}
  $routes=[];$rows=[];$candidates=[];
  foreach($ev as$e){[$or,$oe,$bridge]=$operator[$e['ns'].'/'.$e['external_id']];[$ar,$ae]=$andromeda[$e['andromeda_id']];$cid=(int)$bridge['country_id'];$row=['supplier_namespace'=>$e['ns'],'external_hotel_id'=>$e['external_id'],'andromeda_hotel_id'=>$e['andromeda_id'],'source_name'=>$e['source_name'],'source_geo'=>$e['source_geo'],'route'=>null,'holds'=>[]];
   if((string)$or['decision_status']!=='pending'||$or['local_hotel_id']!==null)$row['holds'][]='operator_not_pending_null';if(hmpel_protected($oe))$row['holds'][]='operator_protected';if((string)$ar['decision_status']!=='pending'||$ar['local_hotel_id']!==null)$row['holds'][]='andromeda_not_pending_null';if(hmpel_protected($ae))$row['holds'][]='andromeda_protected';
   $publicKey=hmpel_name_key($e['source_name']);$bridgeKey=hmpel_name_key((string)($bridge['hotel_name']??''));if($publicKey===''||$publicKey!==$bridgeKey)$row['holds'][]='public_native_name_mismatch';$anames=hmpel_names($ae);if(!isset($anames[$publicKey]))$row['holds'][]='andromeda_name_not_exact';
   $ids=array_keys($index[$cid][$publicKey]??[]);sort($ids,SORT_NUMERIC);$row['exact_local_candidate_ids']=$ids;if(count($ids)!==1){$row['holds'][]=count($ids)===0?'no_unique_exact_local':'multiple_exact_local';$row['route']='no_strict_exact_local';$rows[]=$row;$routes[$row['route']]=($routes[$row['route']]??0)+1;continue;}
   $lid=(int)$ids[0];$h=$hotels[$lid];$row['local_candidate']=['id'=>$lid,'name'=>(string)$h['name'],'country_id'=>(int)$h['country_id'],'region_name'=>(string)$h['region_name'],'subregion_name'=>(string)$h['subregion_name']];$g=hmpel_geo_key($e['source_geo']);$rg=hmpel_geo_key((string)$h['region_name']);$sg=hmpel_geo_key((string)$h['subregion_name']);if($g===''||($g!==$rg&&$g!==$sg))$row['holds'][]='public_geo_not_exact_region_or_subregion';
   if(hmpel_q($db,"SELECT external_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace=? AND decision_status='accepted' AND local_hotel_id=? AND external_hotel_id<>? LIMIT 2",[$e['ns'],$lid,$e['external_id']]))$row['holds'][]='operator_target_occupied';if(hmpel_q($db,"SELECT external_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id=? AND external_hotel_id<>? LIMIT 2",[$lid,$e['andromeda_id']]))$row['holds'][]='andromeda_target_occupied';
   $target=[];if(is_numeric($h['latitude'])&&is_numeric($h['longitude'])){$la=(float)$h['latitude'];$lo=(float)$h['longitude'];if(is_finite($la)&&is_finite($lo)&&abs($la)<=90&&abs($lo)<=180&&($la!=0||$lo!=0))$target=[$la,$lo];}$pts=[];hmpel_points($oe,$pts);hmpel_points($ae,$pts);$ds=[];if($target)foreach($pts as$p){$d=hmpel_km($p,$target);$ds[]=round($d,3);if($d>5)$row['holds'][]='coordinate_conflict_gt5km';}$row['coordinate_distances_km']=$ds;
   $row['holds']=array_values(array_unique($row['holds']));if($row['holds']){$row['route']='exact_local_held';}else{$row['route']='strict_exact_local_candidate';$candidates[]=['supplier_namespace'=>$e['ns'],'external_hotel_id'=>$e['external_id'],'andromeda_hotel_id'=>$e['andromeda_id'],'local_hotel_id'=>$lid,'country_id'=>$cid,'source_name'=>$e['source_name'],'source_geo'=>$e['source_geo'],'operator_evidence_sha256'=>(string)$or['evidence_sha256'],'andromeda_evidence_sha256'=>(string)$ar['evidence_sha256']];}$rows[]=$row;$routes[$row['route']]=($routes[$row['route']]??0)+1;
  }
  $pending=[];foreach(['andromeda_catalog','operator_315','operator_342','operator_5']as$ns){$r=hmpel_q($db,"SELECT COUNT(*) n FROM andromeda_hotel_identities WHERE supplier_namespace=? AND decision_status='pending' AND local_hotel_id IS NULL",[$ns]);$pending[$ns]=(int)$r[0]['n'];}$db->exec('ROLLBACK');ksort($routes);$out['state']='completed_read_only';$out['route_counts']=$routes;$out['rows']=$rows;$out['strict_candidate_count']=count($candidates);$out['strict_candidates']=$candidates;$out['current_pending_counts']=$pending;$out['current_pending_total']=array_sum($pending);$out['read_at_utc']=gmdate('c');$out['transaction']='REPEATABLE READ / READ ONLY';
 }catch(Throwable $x){if($db instanceof PDO&&$db->inTransaction())$db->rollBack();$out['error_phase']=$phase;$out['error_code']=preg_match('/^[a-z_0-9]{3,120}$/D',$x->getMessage())?$x->getMessage():'sanitized_failure';}while(ob_get_level())ob_end_clean();$dig=hmpel_write($dir.'/result.json',$out);hmpel_write($dir.'/receipt.json',['operation_id'=>HMPEL_OP,'source_sha'=>$sha,'state'=>$out['state'],'result_sha256'=>$dig,'readback_verified'=>true,'no_replay'=>true,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0]);echo hmpel_json(['state'=>$out['state'],'route_counts'=>$out['route_counts']??[],'strict_candidate_count'=>$out['strict_candidate_count']??null,'current_pending_total'=>$out['current_pending_total']??null,'result_sha256'=>$dig]);if($out['state']!=='completed_read_only')exit(2);
}
if(in_array('--self-test',$argv??[],true)){hmpel_req(hmpel_name_key('Raimond Hotel')==='raimond','generic_hotel');hmpel_req(hmpel_name_key('Ivy Cyrene Sharm (ex. Cyrene Sharm)')==='ivycyrenesharm','former');hmpel_req(hmpel_geo_key('Шарм-эль-Шейх')==='шармэльшейх','cyrillic_lower');hmpel_req(hmpel_protected(['manual'=>true])&&!hmpel_protected(['conflict'=>false]),'protected');echo"4 exact-local resolver self-tests PASS\n";exit;}
hmpel_main();
