<?php
declare(strict_types=1);
if (!defined('FC_LIBRARY_ONLY')) define('FC_LIBRARY_ONLY', true);
require_once __DIR__ . '/hotel_match_andromeda_star_signal_bridge_review.php';
const HMLOC_OPERATION='hotel-match-live-observed-coordinate-review-2333-20260914-v1';
function hmloc_review(PDO $db,string $operation=HMLOC_OPERATION): array {
 if($operation!==HMLOC_OPERATION)throw new RuntimeException('operation_scope');$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);[$hotels,$names,$strict,$broad,$places,$scope]=mbr_catalog($db);$shaCountry=fc_sha_countries($db);
 $latest=[];$counts=[];foreach($db->query("SELECT * FROM andromeda_search_hotel_observations WHERE supplier_namespace='andromeda_catalog' ORDER BY observed_at_utc DESC,external_hotel_id")->fetchAll(PDO::FETCH_ASSOC) as $o){$id=(string)$o['external_hotel_id'];$counts[$id]=($counts[$id]??0)+1;if(!isset($latest[$id]))$latest[$id]=$o;}
 $byCountry=[];foreach($hotels as $lid=>$h){if(($h['latitude']??null)!==null&&($h['longitude']??null)!==null)$byCountry[(int)$h['country_id']][(int)$lid]=$h;}
 $stats=['observed_pending'=>0,'with_coordinates'=>0,'nearest_found'=>0,'within_1km'=>0,'within_250m'=>0,'safe'=>0,'medium'=>0,'qualifier_conflict'=>0,'star_mismatch'=>0,'weak_name'=>0,'far_nearest'=>0,'country_unknown'=>0];$safe=[];$medium=[];$reasons=[];
 foreach($db->query("SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='pending' AND local_hotel_id IS NULL ORDER BY external_hotel_id")->fetchAll(PDO::FETCH_ASSOC) as $r){$external=(string)$r['external_hotel_id'];$oc=(int)($counts[$external]??0);if($oc<1)continue;$obs=$latest[$external]??null;$e=fc_evidence($r['evidence_json']??'');$src=$e['source']??[];if(!is_array($src))$src=[];$country=(int)($obs['country_id']??0);if(!isset(MBR_CORE8[$country]))$country=(int)($shaCountry[$r['catalog_sha256']]??0);if(!isset(MBR_CORE8[$country])){$stats['country_unknown']++;continue;}$stats['observed_pending']++;
  $coord=$src;if($obs)$coord+=$obs;[$lat,$lon]=mbr_coord($coord);if($lat===null||$lon===null)continue;$stats['with_coordinates']++;
  $nearest=[];foreach($byCountry[$country]??[] as $lid=>$h){$d=fc_dist($lat,$lon,$h['latitude'],$h['longitude']);if($d!==null)$nearest[]=['id'=>(int)$lid,'distance_m'=>(int)round($d)];}usort($nearest,static fn($a,$b)=>$a['distance_m']<=>$b['distance_m']);$n=$nearest[0]??null;if(!$n)continue;$stats['nearest_found']++;if($n['distance_m']>1000){$stats['far_nearest']++;$reasons['nearest_gt_1km']=($reasons['nearest_gt_1km']??0)+1;continue;}$stats['within_1km']++;if($n['distance_m']<=250)$stats['within_250m']++;
  $lid=(int)$n['id'];$target=$hotels[$lid];$sourceNames=hmadb_source_names($e,$obs);$best=hmmto_best_pair($sourceNames,$names[$lid]??[(string)$target['name']]);if(!hmlg_qualifiers_ok($sourceNames,$names[$lid]??[(string)$target['name']])||!hmasb_numeric_qualifiers_ok((string)$best['source'],(string)$best['target'])){$stats['qualifier_conflict']++;$reasons['qualifier_conflict']=($reasons['qualifier_conflict']??0)+1;continue;}
  $sourceCat=mbr_numeric_category($src);if($sourceCat===null&&$obs)$sourceCat=mbr_numeric_category($obs);$targetCat=$target['category']===null?null:(int)$target['category'];$starMismatch=$sourceCat!==null&&$targetCat!==null&&$sourceCat!==$targetCat;if($starMismatch)$stats['star_mismatch']++;
  $second=$nearest[1]['distance_m']??null;$base=['external_id'=>$external,'observation_count'=>$oc,'country_id'=>$country,'source_names'=>$sourceNames,'coordinates'=>['lat'=>$lat,'lon'=>$lon],'target'=>mbr_row_target($target),'distance_m'=>$n['distance_m'],'second_nearest_distance_m'=>$second,'name_match'=>$best,'source_category'=>$sourceCat,'target_category'=>$targetCat,'star_mismatch'=>$starMismatch,'evidence'=>'live_observed_coordinates_nearest_catalog_plus_name'];
  $distanceMargin=$second===null?999999:$second-$n['distance_m'];$safeRule=$n['distance_m']<=250&&$distanceMargin>=300&&$best['score']>=0.72&&$best['shared']>=2&&(!$starMismatch||$best['score']>=0.94);if($safeRule){$base['tier']='safe';$safe[]=$base;$stats['safe']++;continue;}
  if($n['distance_m']<=500&&$distanceMargin>=150&&$best['score']>=0.65&&$best['shared']>=2&&!$starMismatch){$base['tier']='medium';$medium[]=$base;$stats['medium']++;continue;}$stats['weak_name']++;$reasons['coordinate_candidate_not_strong_enough']=($reasons['coordinate_candidate_not_strong_enough']??0)+1;
 }
 $sort=static fn($a,$b)=>(int)$b['observation_count']<=>(int)$a['observation_count'] ?: $a['distance_m']<=>$b['distance_m'] ?: strcmp($a['external_id'],$b['external_id']);usort($safe,$sort);usort($medium,$sort);arsort($reasons);
 return ['status'=>'completed','operation_id'=>$operation,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'coverage'=>fc_coverage($db),'stats'=>$stats,'blocked_reasons'=>$reasons,'safe_count'=>count($safe),'medium_count'=>count($medium),'safe'=>$safe,'medium'=>$medium];
}
