<?php
declare(strict_types=1);
require_once __DIR__.'/hotel_match_live30_common4_gap_matrix_v1.php';
require_once __DIR__.'/hotel_match_retained93_primary_write_v84.php';
const M119_OP='hotel-match-neither600-plan-1971-20260928-v119';
const M119_LEDGER_OP='hotel-match-request-ledger-1971-20260928-v93';
const M119_LEDGER_SHA='8da64bc3ac54d707d335b8808b171f46a02ba0464536681bc40b741136df935c';
function m119_need(bool$b,string$m):void{if(!$b)throw new RuntimeException($m);}
function m119_main(array$a):int{
 m119_need(($a[1]??'')==='--execute','disabled');$root=(string)getenv('ANYTOUR_ROOT');$dir=(string)getenv('MATCH_OPERATION_DIR');$head=(string)getenv('MATCH_SOURCE_SHA');m119_need(is_dir($root)&&basename($root)==='anytoour.ru'&&is_dir($dir)&&basename($dir)===M119_OP&&preg_match('/^[a-f0-9]{40}$/D',$head),'scope');foreach(['result.json','receipt.json']as$f)m119_need(!file_exists($dir.'/'.$f),'no_replay');
 $ledger=w84_read(dirname($dir).'/'.M119_LEDGER_OP.'/result.json',M119_LEDGER_SHA,33554432);m119_need(($ledger['state']??'')==='completed_read_only_request_ledger','ledger');require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$m=hmc4_execute(v2_data_db());m119_need(($m['state']??'')==='completed_read_only_common4_gap_matrix'&&($m['tv_live30_total']??0)===4399,'matrix');
 $cur=[];foreach($m['rows']as$r)$cur[(int)$r['tv_hotel_id']]=$r;$req=[];foreach($ledger['requests']as$q)foreach($q['hotel_ids']as$id)$req[(int)$id][]=$q;$rows=[];$noctx=0;$replay=0;
 foreach($ledger['rows']as$r){$id=(int)$r['tv_hotel_id'];if(($cur[$id]['gap_bucket']??'')!=='neither')continue;$missing=[];foreach([13,18,25,43]as$o)if(in_array($o,array_map('intval',$r['missing_operator_ids']??[]),true)&&empty($r['lanes'][(string)$o]['retained_exact']))$missing[]=$o;if(!$missing)continue;$freq=[];foreach($req[$id]??[]as$q){$x=$q['context']??[];$dep=(int)($x['departureId']??0);$cid=(int)($x['countryId']??0);if($dep>0&&$cid>0)$freq[$dep.'|'.$cid]=($freq[$dep.'|'.$cid]??0)+1;}arsort($freq);$k=array_key_first($freq);if(!$k){$noctx++;continue;}[$dep,$cid]=array_map('intval',explode('|',$k));$seen=false;foreach($req[$id]??[]as$q){$x=$q['context']??[];if((int)($x['departureId']??0)===$dep&&(int)($x['countryId']??0)===$cid&&($x['dateFrom']??'')==='2026-10-29'&&($x['dateTo']??'')==='2026-10-29'&&(int)($x['nightsFrom']??0)===7&&(int)($x['nightsTo']??0)===7&&(int)($x['adults']??0)===2&&($x['childs']??[])===[]){$seen=true;break;}}if($seen){$replay++;continue;}
  $rows[]=['tv_hotel_id'=>$id,'hotel_name'=>$r['hotel_name'],'country_id'=>$cid,'country'=>$r['country'],'departure_id'=>$dep,'departure_date'=>'2026-10-29','nights'=>7,'adults'=>2,'children_count'=>0,'child_ages_signature'=>'','missing_operator_ids'=>$missing,'gap_bucket'=>'neither'];
 }
 usort($rows,fn($a,$b)=>[$a['country'],$a['tv_hotel_id']]<=>[$b['country'],$b['tv_hotel_id']]);$eligible=count($rows);$rows=array_slice($rows,0,600);m119_need(count($rows)>=500&&count($rows)<=600,'scope_size');$ids=array_column($rows,'tv_hotel_id');m119_need(count($ids)===count(array_unique($ids)),'dup');$countries=[];foreach($rows as$r)$countries[$r['country']]=($countries[$r['country']]??0)+1;
 $out=['operation'=>M119_OP,'state'=>'completed_read_only_neither600_plan','source_sha'=>$head,'generated_at_utc'=>gmdate('c'),'current_gap_counts'=>$m['gap_bucket_counts'],'eligible_neither_new_context'=>$eligible,'excluded_no_context'=>$noctx,'excluded_exact_context_replay'=>$replay,'scope_count'=>count($rows),'scope_id_sha256'=>hash('sha256',json_encode($ids,JSON_UNESCAPED_SLASHES)),'country_counts'=>$countries,'tourvisor_account'=>'TOURVISOR_ANEX_JWT','operator_filter_sent'=>false,'continue_calls'=>0,'dates_calls'=>0,'provider_http_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'rows'=>$rows];$sha=w76_save($dir.'/result.json',$out);w76_save($dir.'/receipt.json',['operation'=>M119_OP,'state'=>$out['state'],'source_sha'=>$head,'result_sha256'=>$sha,'provider_http_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true]);echo w76_json(array_diff_key($out,['rows'=>true]))."\n";return 0;
}
if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__)exit(m119_main($argv));
