<?php
declare(strict_types=1);
/** MATCH #1971: targeted CURRENT-unresolved Tourvisor search retaining all operators. */
const HMM2_OP='hotel-match-tv-multiop-targeted-1971-20260916-v2-egypt';
const HMM2_DATE='2026-11-15';
const HMM2_TARGETS=[19226=>14140,37048=>97122,1361=>125,28396=>293,36906=>21636,780=>464,1771=>190,1655=>157782,30600=>129,37012=>83106,44562=>159,1772=>191,28563=>73342,30599=>159159,4131=>488,1328=>128,990=>162145,1769=>186,43850=>151784,45166=>148539,45249=>127294,45259=>143442,45330=>130621,29557=>73343];
const HMM2_SECRET_RE='/(?:token|jwt|auth|pass|password|secret|session|sid|cookie|signature|api[_-]?key)/i';
function h2_json(array$v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
function h2_write(string$p,array$v):string{$raw=h2_json($v)."\n";$f=@fopen($p,'x');if(!$f)throw new RuntimeException('durable_create_failed');try{if(fwrite($f,$raw)!==strlen($raw))throw new RuntimeException('durable_write_failed');fflush($f);}finally{fclose($f);}if(file_get_contents($p)!==$raw)throw new RuntimeException('durable_readback_failed');return hash('sha256',$raw);}
function h2_id($v):?int{if(is_bool($v)||!is_scalar($v))return null;$s=trim((string)$v);return preg_match('/^[1-9][0-9]{0,14}$/D',$s)?(int)$s:null;}
function h2_text($v,int$m=240):string{if(!is_scalar($v))return'';$s=trim((string)(preg_replace('/\s+/u',' ',(string)$v)??''));return function_exists('mb_substr')?mb_substr($s,0,$m,'UTF-8'):substr($s,0,$m);}
function h2_name($v):string{if(is_scalar($v))return h2_text($v);if(!is_array($v))return'';foreach(['name','fullName','russianName','title','label']as$k)if(isset($v[$k])&&h2_text($v[$k])!=='')return h2_text($v[$k]);return'';}
function h2_num($v):?float{if(!is_scalar($v)||!is_numeric((string)$v))return null;$x=(float)$v;return is_finite($x)?$x:null;}
function h2_db_path(string$r):string{foreach([$r.'/data/db-v1.php',$r.'/v2/data/db-v1.php']as$p)if(is_file($p))return$p;throw new RuntimeException('db_bootstrap_missing');}
function h2_tv_path(string$r):string{foreach([$r.'/data/tourvisor-client-v1.php',$r.'/v2/data/tourvisor-client-v1.php']as$p)if(is_file($p))return$p;throw new RuntimeException('tourvisor_client_missing');}
function h2_select(PDO$d,string$q,array$p=[]):array{$s=$d->prepare($q);$s->execute($p);return$s->fetchAll(PDO::FETCH_ASSOC);}
function h2_entities($v,array&$o,int$d=0):void{if($d>8||!is_array($v))return;if(!array_is_list($v)){if(($id=h2_id($v['id']??null))!==null&&($n=h2_name($v))!=='')$o[$id]=['id'=>$id,'name'=>$n];}foreach($v as$x)if(is_array($x))h2_entities($x,$o,$d+1);}
function h2_find(array$p,array$n):?array{$e=[];h2_entities($p,$e);foreach($e as$r){$s=function_exists('mb_strtolower')?mb_strtolower($r['name'],'UTF-8'):strtolower($r['name']);foreach($n as$q){$q=function_exists('mb_strtolower')?mb_strtolower($q,'UTF-8'):strtolower($q);if(str_contains($s,$q))return$r;}}return null;}
function h2_search_id($v,int$d=0):?int{if($d>8)return null;if(is_array($v)){foreach($v as$k=>$x)if(is_string($k)&&preg_match('/^(?:search|request).*id$/i',$k)&&($id=h2_id($x))!==null)return$id;foreach($v as$x)if(is_array($x)&&($id=h2_search_id($x,$d+1))!==null)return$id;}return null;}
function h2_complete($v,int$d=0):bool{if($d>8||!is_array($v))return false;if((int)($v['progress']??0)>=100)return true;if(in_array(strtolower(trim((string)($v['status']??''))),['complete','completed','done','ready'],true))return true;foreach($v as$x)if(is_array($x)&&h2_complete($x,$d+1))return true;return false;}
function h2_flatten($p):array{$r=$p;if(is_array($r)&&!array_is_list($r))foreach(['hotels','results','tours','items','data']as$k)if(isset($r[$k])&&is_array($r[$k])){$r=$r[$k];break;}if(!is_array($r))return[];$o=[];foreach($r as$row){if(!is_array($row))continue;if(isset($row['tours'])&&is_array($row['tours'])&&!isset($row['hotel'])){$h=$row;unset($h['tours']);foreach($row['tours']as$t)if(is_array($t)){if(!isset($t['hotel']))$t['hotel']=$h;$o[]=$t;}}elseif(is_array($row['hotel']??null))$o[]=$row;}return$o;}
function h2_search_params(int$dep,int$country,string$date,array$hotels):array{if(!$hotels||count($hotels)>30||count(array_unique($hotels))!==count($hotels))throw new RuntimeException('focus_guard');return['departureId'=>$dep,'countryId'=>$country,'dateFrom'=>$date,'dateTo'=>$date,'nightsFrom'=>7,'nightsTo'=>7,'adults'=>2,'currency'=>'RUB','onlyCharter'=>false,'hotelIds'=>array_values($hotels)];}
function h2_link($v):array{$url=trim((string)$v);if($url==='')return['status'=>'missing'];if(strlen($url)>4096)return['status'=>'invalid'];$u=parse_url($url);if(!is_array($u)||strtolower((string)($u['scheme']??''))!=='https'||isset($u['user'])||isset($u['pass'])||trim((string)($u['host']??''))==='')return['status'=>'invalid'];$keys=[];$nums=[];foreach(explode('&',(string)($u['query']??''))as$part){if($part==='')continue;[$rk,$rv]=array_pad(explode('=',$part,2),2,'');$k=strtolower(trim(urldecode($rk)));if($k==='')continue;if(preg_match(HMM2_SECRET_RE,$k))return['status'=>'secret_bearing','host'=>strtolower((string)$u['host']),'path'=>(string)($u['path']??'')];$keys[$k]=true;$v=trim(urldecode($rv));if(($id=h2_id($v))!==null)$nums[$k][$id]=true;}ksort($keys);ksort($nums);$n=[];foreach($nums as$k=>$ids){$x=array_keys($ids);sort($x,SORT_NUMERIC);$n[$k]=$x;}return['status'=>'safe','host'=>strtolower((string)$u['host']),'path'=>(string)($u['path']??''),'query_keys'=>array_keys($keys),'numeric_query'=>$n];}
function h2_failure(Throwable$e):string{$m=$e->getMessage();if(preg_match('/HTTP[ _]([45][0-9]{2})(?:\b|_)/i',$m,$x))return'tourvisor_http_'.$x[1];$a=['client_call_cap','moscow_departure_not_found','egypt_not_found','search_id_not_found','search_not_complete_bounded','no_current_unresolved_focus','no_unique_hotel_operator_tours','old_tourvisor_jwt_missing','tourvisor_client_contract_missing','db_bootstrap_missing','tourvisor_client_missing'];return in_array($m,$a,true)?$m:'diagnostic_error';}
function h2_call(string$stage,string$path,array$params=[]):array{global$calls,$lastStage;$lastStage=$stage;if(rtrim($path,'/')==='/tours/search'&&(!is_array($params['hotelIds']??null)||!$params['hotelIds']))throw new RuntimeException('focus_guard');if($calls>=39)throw new RuntimeException('client_call_cap');$calls++;return v2_data_tv_get($path,$params);}
function h2_poll(int$sid):array{sleep(8);$s=h2_call('search_status','/tours/search/'.$sid.'/status',['operatorStatus'=>false]);if(!h2_complete($s)){sleep(12);$s=h2_call('search_status','/tours/search/'.$sid.'/status',['operatorStatus'=>false]);}return$s;}
function h2_select_details(array$flat,array$focus,int$limit=30):array{$by=[];foreach($flat as$r){if(!is_array($r))continue;$h=is_array($r['hotel']??null)?$r['hotel']:[];$hid=h2_id($h['id']??null);$tid=h2_id($r['id']??null);$op=is_array($r['operator']??null)?$r['operator']:[];$oid=h2_id($op['id']??null);if($hid===null||$tid===null||$oid===null||!in_array($hid,$focus,true))continue;$k=$hid.'|'.$oid;if(!isset($by[$k]))$by[$k]=['tour_id'=>$tid,'search_hotel_id'=>$hid,'search_hotel_name'=>h2_name($h),'search_operator_id'=>$oid,'search_operator_name'=>h2_name($op)];}
    if(!$by)return[];$first=[];$extra=[];$seen=[];foreach($by as$x){$h=$x['search_hotel_id'];if(!isset($seen[$h])){$seen[$h]=true;$first[]=$x;}else$extra[]=$x;}return array_slice(array_merge($first,$extra),0,$limit);
}
if(in_array('--self-test',$argv??[],true)){$p=h2_search_params(1,1,'2026-11-15',[10,20]);if(isset($p['operatorIds'])||$p['hotelIds']!==[10,20]||$p['onlyCharter']!==false)throw new RuntimeException('multiop_contract_test');$l=h2_link('https://agent.example.test/tour?hotelId=4158&adult=2');if(($l['numeric_query']['hotelid'][0]??0)!==4158)throw new RuntimeException('link_test');$l=h2_link('https://agent.example.test/tour?hotelId=1&token=x');if(($l['status']??'')!=='secret_bearing')throw new RuntimeException('secret_test');$flat=[['id'=>1,'hotel'=>['id'=>10,'name'=>'A'],'operator'=>['id'=>5,'name'=>'X']],['id'=>2,'hotel'=>['id'=>10,'name'=>'A'],'operator'=>['id'=>6,'name'=>'Y']],['id'=>3,'hotel'=>['id'=>20,'name'=>'B'],'operator'=>['id'=>5,'name'=>'X']]];$s=h2_select_details($flat,[10,20],3);if(count($s)!==3||$s[0]['search_hotel_id']!==10||$s[1]['search_hotel_id']!==20)throw new RuntimeException('selection_test');echo"hotel_match_tv_multiop_targeted_v2 self-test PASS\n";exit(0);}
$op=(string)getenv('OPERATION_ID');$sha=(string)getenv('MATCH_SOURCE_SHA');if($op!==HMM2_OP||!preg_match('/^[0-9a-f]{40}$/D',$sha))throw new RuntimeException('operation_guard');$root=(string)realpath(getcwd());if($root===''||basename($root)!=='anytoour.ru')throw new RuntimeException('root_guard');$base=rtrim((string)getenv('HOME'),'/').'/.anytoour-match/operations';if(!is_dir($base))throw new RuntimeException('operations_root_missing');$dir=$base.'/'.$op;if(!mkdir($dir,0700))throw new RuntimeException('operation_exists');h2_write($dir.'/reservation.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'reserved_before_db_and_tourvisor_access','credential_identifier'=>'TOURVISOR_JWT','date'=>HMM2_DATE,'read_only'=>true,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'no_replay'=>true]);
$db=null;$calls=0;$lastStage='current';$rate=false;$auth=false;
try{require_once h2_db_path($root);$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');$mapped=[];foreach(h2_select($db,'SELECT anex_hotel_id,catalog_hotel_id FROM anex_hotel_search_mappings')as$r)$mapped[(int)$r['anex_hotel_id']]=(int)$r['catalog_hotel_id'];$manual=[];foreach(h2_select($db,'SELECT anex_hotel_id FROM anex_hotel_decisions')as$r)$manual[(int)$r['anex_hotel_id']]=true;$ex=[];foreach(h2_select($db,'SELECT anex_hotel_id,catalog_hotel_id FROM anex_review_pair_exclusions')as$r)$ex[(int)$r['anex_hotel_id']][(int)$r['catalog_hotel_id']]=true;$active=[];foreach(h2_select($db,'SELECT id,country_id,name FROM catalog_hotels WHERE country_id=1 AND is_active=1')as$r)$active[(int)$r['id']]=$r;$focus=[];$sourceByLocal=[];foreach(HMM2_TARGETS as$aid=>$local){if(isset($mapped[$aid])||isset($manual[$aid])||isset($ex[$aid][$local])||!isset($active[$local]))continue;$focus[$aid]=$local;$sourceByLocal[$local]=$aid;}$db->exec('ROLLBACK');if(!$focus)throw new RuntimeException('no_current_unresolved_focus');
    $lastStage='client_bootstrap';require_once h2_tv_path($root);if(!function_exists('v2_data_tv_get'))throw new RuntimeException('tourvisor_client_contract_missing');if(trim((string)(getenv('TOURVISOR_JWT')?:''))===''&&!(defined('TOURVISOR_JWT')&&trim((string)TOURVISOR_JWT)!==''))throw new RuntimeException('old_tourvisor_jwt_missing');$deps=h2_call('departures','/departures');$dep=h2_find($deps,['моск','moscow']);if($dep===null)throw new RuntimeException('moscow_departure_not_found');$countries=h2_call('countries','/countries',['departureId'=>$dep['id'],'onlyCharter'=>false,'onlyDirect'=>false]);$country=h2_find($countries,['егип','egypt']);if($country===null)throw new RuntimeException('egypt_not_found');$params=h2_search_params($dep['id'],$country['id'],HMM2_DATE,array_values($focus));$search=h2_call('search_create','/tours/search',$params);$sid=h2_search_id($search);if($sid===null)throw new RuntimeException('search_id_not_found');$status=h2_poll($sid);if(!h2_complete($status))throw new RuntimeException('search_not_complete_bounded');$payload=h2_call('search_results','/tours/search/'.$sid,['limit'=>500]);$flat=h2_flatten($payload);$selected=h2_select_details($flat,array_values($focus),30);if(!$selected)throw new RuntimeException('no_unique_hotel_operator_tours');
    $rows=[];$errors=0;foreach($selected as$s){sleep(4);try{$d=h2_call('tour_detail','/tours/'.$s['tour_id'],['currency'=>'RUB']);}catch(Throwable$e){$why=h2_failure($e);if($why==='tourvisor_http_429'){$rate=true;break;}if(in_array($why,['tourvisor_http_401','tourvisor_http_403'],true)){$auth=true;break;}$errors++;$rows[]=$s+['route'=>'detail_hold','reason'=>$why];continue;}$h=is_array($d['hotel']??null)?$d['hotel']:[];$tv=h2_id($h['id']??null);$opd=is_array($d['operator']??null)?$d['operator']:[];$oid=h2_id($opd['id']??null);$oname=h2_name($opd);if($tv!==$s['search_hotel_id']){$rows[]=$s+['route'=>'detail_hold','reason'=>'tourvisor_hotel_id_mismatch','detail_hotel_id'=>$tv];continue;}if($oid!==$s['search_operator_id']){$rows[]=$s+['route'=>'detail_hold','reason'=>'operator_id_mismatch','detail_operator_id'=>$oid];continue;}$link=h2_link($d['operatorLink']??'');$common=is_array($h['common']??null)?$h['common']:[];$rows[]=$s+['source_anex_id'=>$sourceByLocal[$tv]??null,'detail_hotel_id'=>$tv,'detail_hotel_name'=>h2_name($h),'detail_operator_id'=>$oid,'detail_operator_name'=>$oname,'region_name'=>h2_name($h['region']??null),'subregion_name'=>h2_name($h['subRegion']??null),'latitude'=>h2_num($h['latitude']??($common['latitude']??null)),'longitude'=>h2_num($h['longitude']??($common['longitude']??null)),'operator_link'=>$link,'route'=>(($link['status']??'')==='safe'?'operator_link_evidence_ready':'operator_identity_without_safe_link')];}
    $ops=[];$shapes=[];foreach($rows as$r){if(($r['route']??'')==='detail_hold')continue;$ok=(string)($r['detail_operator_id']??$r['search_operator_id']??'unknown');$ops[$ok]['operator_id']=$r['detail_operator_id']??$r['search_operator_id'];$ops[$ok]['operator_names'][$r['detail_operator_name']??$r['search_operator_name']??'']=true;$ops[$ok]['rows']=($ops[$ok]['rows']??0)+1;$l=$r['operator_link']??[];if(($l['status']??'')==='safe')foreach($l['numeric_query']??[]as$k=>$vals){$sk=$ok.'|'.$l['host'].'|'.$l['path'].'|'.$k;$shapes[$sk]['operator_id']=$r['detail_operator_id'];$shapes[$sk]['operator_name']=$r['detail_operator_name'];$shapes[$sk]['host']=$l['host'];$shapes[$sk]['path']=$l['path'];$shapes[$sk]['query_key']=$k;$shapes[$sk]['locals'][$r['detail_hotel_id']]=true;$shapes[$sk]['values'][implode(',',$vals)]=true;}}
    foreach($ops as&$x){$n=array_keys($x['operator_names']??[]);sort($n,SORT_STRING);$x['operator_names']=$n;}unset($x);ksort($ops,SORT_NATURAL);$shapeOut=[];foreach($shapes as$x){$shapeOut[]=['operator_id'=>$x['operator_id'],'operator_name'=>$x['operator_name'],'host'=>$x['host'],'path'=>$x['path'],'query_key'=>$x['query_key'],'local_count'=>count($x['locals']??[]),'distinct_value_sets'=>count($x['values']??[])];}usort($shapeOut,static fn($a,$b)=>($b['local_count']<=>$a['local_count'])?:strcmp((string)$a['operator_id'].'|'.$a['host'].'|'.$a['path'].'|'.$a['query_key'],(string)$b['operator_id'].'|'.$b['host'].'|'.$b['path'].'|'.$b['query_key']));$state=$rate?'partial_rate_limited':($auth?'partial_auth_rejected':'completed_read_only');$result=['schema'=>'hotel-match-tv-multiop-targeted/1','operation_id'=>$op,'source_sha'=>$sha,'state'=>$state,'credential_identifier'=>'TOURVISOR_JWT','date'=>HMM2_DATE,'current_input_count'=>count($focus),'current_focus_pairs'=>array_map(static fn($aid,$local)=>['anex_hotel_id'=>$aid,'local_hotel_id'=>$local],array_keys($focus),array_values($focus)),'search_id'=>$sid,'search_params_contract'=>['country'=>'Egypt','dateFrom'=>HMM2_DATE,'dateTo'=>HMM2_DATE,'nightsFrom'=>7,'nightsTo'=>7,'adults'=>2,'currency'=>'RUB','onlyCharter'=>false,'hotelIds_count'=>count($focus),'operator_filter'=>null],'flattened_rows'=>count($flat),'unique_hotel_operator_candidates'=>count($selected),'detail_rows'=>count($rows),'detail_errors'=>$errors,'rate_limited'=>$rate,'auth_rejected'=>$auth,'operator_counts'=>array_values($ops),'numeric_link_shapes'=>$shapeOut,'rows'=>$rows,'tourvisor_calls'=>$calls,'call_count_unit'=>'v2_data_tv_get invocations including failures','database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'booking_calls'=>0,'lead_calls'=>0,'safe_to_write_now'=>false,'no_replay'=>true];$digest=h2_write($dir.'/result.json',$result);h2_write($dir.'/receipt.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>$state,'result_sha256'=>$digest,'readback_verified'=>hash('sha256',(string)file_get_contents($dir.'/result.json'))===$digest,'tourvisor_calls'=>$calls,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'no_replay'=>true]);echo h2_json(['state'=>$state,'current_input_count'=>count($focus),'search_id'=>$sid,'flattened_rows'=>count($flat),'selected'=>count($selected),'detail_rows'=>count($rows),'operators'=>count($ops),'numeric_link_shapes'=>count($shapeOut),'tourvisor_calls'=>$calls])."\n";exit(0);
}catch(Throwable$e){if($db instanceof PDO&&$db->inTransaction())$db->rollBack();$why=h2_failure($e);$state=in_array($why,['tourvisor_http_429'],true)?'partial_rate_limited':(in_array($why,['tourvisor_http_401','tourvisor_http_403'],true)?'partial_auth_rejected':'failed_read_only');$f=['operation_id'=>$op,'source_sha'=>$sha,'state'=>$state,'reason'=>$why,'last_stage'=>$lastStage,'tourvisor_calls'=>$calls,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'no_replay'=>true];$digest=h2_write($dir.'/failure.json',$f);h2_write($dir.'/receipt.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>$state,'failure_sha256'=>$digest,'readback_verified'=>true,'tourvisor_calls'=>$calls,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'no_replay'=>true]);fwrite(STDERR,"HMM2_FAILED:$why\n");exit(2);}
