<?php
declare(strict_types=1);
const OP='hotel-match-tourvisor-passive-operator-intersection-1971-20260917-v1';
function req($v,string $m):void{if(!$v)throw new RuntimeException($m);} function q(PDO $d,string $s,array $a=[]):array{$p=$d->prepare($s);$p->execute(array_values($a));$r=$p->fetchAll(PDO::FETCH_ASSOC);req(count($r)<=50000,'row_budget');return$r;}
function norm($s):string{$s=trim((string)$s);if(function_exists('mb_strtolower'))$s=mb_strtolower($s,'UTF-8');else$s=strtolower($s);$s=str_replace('ё','е',$s);$s=preg_replace('/[^\p{L}\p{N}]+/u',' ',$s)??$s;return trim(preg_replace('/\s+/u',' ',$s)??$s);}
function forms($s):array{$n=norm($s);if($n==='')return[];$out=[$n=>1];$t=preg_split('/\s+/u',$n,-1,PREG_SPLIT_NO_EMPTY)?:[];$g=array_values(array_filter($t,fn($x)=>!in_array($x,['hotel','отель','resort','spa'],true)));if($g&&count($g)!==count($t))$out[implode(' ',$g)]=1;return array_keys($out);}
function is_protected($v,string $key='',int $d=0):bool{if($d>24)return true;if(is_array($v)){foreach($v as$k=>$x)if(is_protected($x,(string)$k,$d+1))return true;return false;}if(!preg_match('/manual|exclude|exclusion|conflict|reject|review|protect/i',$key))return false;if(is_bool($v))return$v;if(is_numeric($v))return(float)$v!==0.0;return is_string($v)&&!in_array(strtolower(trim($v)),['','false','none','no','null','0'],true);}
function hints($v,array &$h,array $path=[],int $d=0):void{if($d>24||!is_array($v))return;foreach($v as$k=>$x){$key=(string)$k;$p=$path;$p[]=$key;$pl=strtolower(implode('.',$p));if(is_array($x)){hints($x,$h,$p,$d+1);continue;}if(!is_scalar($x)||is_bool($x))continue;$s=trim((string)$x);if($s==='')continue;$kl=strtolower($key);if(in_array($kl,['country_id','countryid','countrykey'],true)&&ctype_digit($s))$h['countries'][(int)$s]=1;if(in_array($kl,['hotel_name','hotelname','source_name','sourcename','hotel_title','hoteltitle'],true)||($kl==='name'&&(str_contains($pl,'source')||str_contains($pl,'hotel')||str_contains($pl,'provider'))))$h['names'][$s]=1;if(in_array($kl,['latitude','lat'],true)&&is_numeric($s))$h['lat'][(string)(float)$s]=1;if(in_array($kl,['longitude','lon','lng'],true)&&is_numeric($s))$h['lon'][(string)(float)$s]=1;}}
function km(float $a,float $b,float $c,float $d):float{$r=6371.0;$p1=deg2rad($a);$p2=deg2rad($c);$dp=deg2rad($c-$a);$dl=deg2rad($d-$b);$x=sin($dp/2)**2+cos($p1)*cos($p2)*sin($dl/2)**2;return 2*$r*asin(min(1,sqrt($x)));}
function w(string $p,array $v):string{$j=json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";req(file_put_contents($p,$j,LOCK_EX)===strlen($j),'write_failed');return hash('sha256',$j);}
function selftest():void{req(norm('Grand  Hotel & SPA')==='grand hotel spa','norm');$h=['names'=>[],'countries'=>[],'lat'=>[],'lon'=>[]];hints(['provider_bridges'=>[['source_name'=>'Alpha Hotel','country_id'=>4]]],$h);req(isset($h['names']['Alpha Hotel'],$h['countries'][4]),'hints');req(is_protected(['manual_review'=>true]),'protect');echo "hotel_match_tourvisor_passive_operator_intersection_v1 self-test: PASS\n";}
if(in_array('--self-test',$argv??[],true)){selftest();exit(0);}
$sha=(string)getenv('MATCH_SOURCE_SHA');req(PHP_SAPI==='cli'&&(string)getenv('MATCH_OPERATION_ID')===OP&&preg_match('/^[a-f0-9]{40}$/D',$sha),'operation_guard');$dir=(string)getenv('HOME').'/.anytoour-match/operations/'.OP;$rv=json_decode((string)file_get_contents($dir.'/reservation.json'),true,32,JSON_THROW_ON_ERROR);req(($rv['state']??'')==='reserved_before_db_access'&&($rv['source_sha']??'')===$sha,'reservation');
$o=['operation_id'=>OP,'source_sha'=>$sha,'state'=>'failed_no_replay','database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'samo_andromeda_calls'=>0,'no_replay'=>true];$db=null;
try{$root=realpath(getcwd());req(is_string($root)&&basename($root)==='anytoour.ru','root');require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');
 $sem=['operator_315'=>25,'operator_342'=>43];$pending=q($db,"SELECT supplier_namespace,external_hotel_id,evidence_sha256,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace IN ('operator_315','operator_342') AND decision_status='pending' AND local_hotel_id IS NULL ORDER BY supplier_namespace,external_hotel_id");$o['pending_checked']=count($pending);
 $obsRows=q($db,"SELECT hotel_id,operator_id,country_id,hotel_name,region_name,subregion_name,latitude,longitude,observation_count,last_seen_at FROM tour_operator_identity_observations WHERE operator_id IN (25,43)");$obs=[];$hotelIds=[];foreach($obsRows as$r){$op=(int)$r['operator_id'];$id=(int)$r['hotel_id'];$obs[$op][$id]=$r;$hotelIds[$id]=1;}$o['passive_rows_considered']=count($obsRows);$o['passive_hotels_considered']=count($hotelIds);
 $cat=[];$idx=[];if($hotelIds){$ids=array_keys($hotelIds);foreach(array_chunk($ids,500)as$ch){$ph=implode(',',array_fill(0,count($ch),'?'));foreach(q($db,"SELECT id,country_id,name,normalized_name,region_name,subregion_name,latitude,longitude FROM catalog_hotels WHERE is_active=1 AND id IN ($ph)",$ch)as$c){$id=(int)$c['id'];$cat[$id]=$c;foreach(array_merge(forms($c['name']),forms($c['normalized_name']))as$f)$idx[(int)$c['country_id']][$f][$id]=1;}foreach(q($db,"SELECT a.hotel_id,a.alias,a.normalized_alias,h.country_id FROM hotel_aliases a JOIN catalog_hotels h ON h.id=a.hotel_id AND h.is_active=1 WHERE a.hotel_id IN ($ph)",$ch)as$a){$id=(int)$a['hotel_id'];foreach(array_merge(forms($a['alias']),forms($a['normalized_alias']))as$f)$idx[(int)$a['country_id']][$f][$id]=1;}}}
 $occupied=[];foreach(q($db,"SELECT supplier_namespace,external_hotel_id,local_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace IN ('operator_315','operator_342') AND decision_status='accepted' AND local_hotel_id IS NOT NULL")as$r)$occupied[(string)$r['supplier_namespace']][(int)$r['local_hotel_id']][]=(string)$r['external_hotel_id'];
 $cand=[];$reasons=[];foreach($pending as$r){$ns=(string)$r['supplier_namespace'];$tv=$sem[$ns];$e=json_decode((string)$r['evidence_json'],true,64,JSON_THROW_ON_ERROR);req(is_array($e),'evidence_shape');if(is_protected($e)){$reasons['protected']=($reasons['protected']??0)+1;continue;}$h=['names'=>[],'countries'=>[],'lat'=>[],'lon'=>[]];hints($e,$h);$names=array_keys($h['names']);$countries=array_map('intval',array_keys($h['countries']));sort($countries);if(!$names){$reasons['no_name']=($reasons['no_name']??0)+1;continue;}if(count($countries)!==1){$reasons[count($countries)?'ambiguous_country':'no_country']=($reasons[count($countries)?'ambiguous_country':'no_country']??0)+1;continue;}$country=$countries[0];$locals=[];foreach($names as$n)foreach(forms($n)as$f)foreach(array_keys($idx[$country][$f]??[])as$lid)if(isset($obs[$tv][$lid]))$locals[(int)$lid]=1;$lids=array_keys($locals);sort($lids,SORT_NUMERIC);if(count($lids)!==1){$reasons[count($lids)?'ambiguous_exact_observed_local':'no_exact_observed_local']=($reasons[count($lids)?'ambiguous_exact_observed_local':'no_exact_observed_local']??0)+1;continue;}$lid=(int)$lids[0];if(isset($occupied[$ns][$lid])&&!in_array((string)$r['external_hotel_id'],$occupied[$ns][$lid],true)){$reasons['target_occupied']=($reasons['target_occupied']??0)+1;continue;}$c=$cat[$lid];$dist=null;$lat=array_keys($h['lat']);$lon=array_keys($h['lon']);if(count($lat)===1&&count($lon)===1&&$c['latitude']!==null&&$c['longitude']!==null)$dist=km((float)$lat[0],(float)$lon[0],(float)$c['latitude'],(float)$c['longitude']);if($dist!==null&&$dist>5){$reasons['geo_over_5km']=($reasons['geo_over_5km']??0)+1;continue;}$ob=$obs[$tv][$lid];$cand[]=['supplier_namespace'=>$ns,'external_hotel_id'=>(string)$r['external_hotel_id'],'evidence_sha256'=>(string)$r['evidence_sha256'],'source_names'=>$names,'country_id'=>$country,'local_id'=>$lid,'local_name'=>(string)$c['name'],'tourvisor_operator_id'=>$tv,'observation_count'=>(int)$ob['observation_count'],'last_seen_at'=>(string)$ob['last_seen_at'],'distance_km'=>$dist===null?null:round($dist,3),'write_authority'=>false,'needs_independent_native_identity'=>true];}
 usort($cand,fn($a,$b)=>($b['observation_count']<=>$a['observation_count'])?:strcmp($a['supplier_namespace'].'/'.$a['external_hotel_id'],$b['supplier_namespace'].'/'.$b['external_hotel_id']));ksort($reasons);$db->exec('ROLLBACK');$o['state']='completed_read_only';$o['strict_candidates']=count($cand);$o['reason_counts']=$reasons;$o['candidates']=$cand;$o['read_at_utc']=gmdate('c');
}catch(Throwable $e){if($db instanceof PDO&&$db->inTransaction())$db->rollBack();$o['error_code']=preg_match('/^[a-z0-9_]{2,120}$/Di',$e->getMessage())?$e->getMessage():'sanitized_failure';$o['read_at_utc']=gmdate('c');}
$h=w($dir.'/result.json',$o);w($dir.'/receipt.json',['operation_id'=>OP,'source_sha'=>$sha,'state'=>$o['state'],'result_sha256'=>$h,'readback_verified'=>$o['state']==='completed_read_only','database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'samo_andromeda_calls'=>0,'no_replay'=>true]);echo json_encode(['state'=>$o['state'],'pending_checked'=>$o['pending_checked']??null,'passive_rows_considered'=>$o['passive_rows_considered']??null,'passive_hotels_considered'=>$o['passive_hotels_considered']??null,'strict_candidates'=>$o['strict_candidates']??null,'reason_counts'=>$o['reason_counts']??[],'candidates'=>$o['candidates']??[],'result_sha256'=>$h],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n";exit($o['state']==='completed_read_only'?0:2);
