<?php
declare(strict_types=1);
/** MATCH #1971 core8 direct operator-key evidence + CURRENT readback. No writes. */
const HM_COUNTRY='__MATCH_COUNTRY__';
const HM_DATE='__MATCH_DATE__';
const HM_OPERATION='__MATCH_OPERATION__';
const HM_NIGHTS=7;
const HM_PAGE_CAP=80;
const HM_HOTEL_CAP=6000;
function hm_fail(string $stage,string $reason,array $extra=[]):void{echo 'MATCH_CORE8_KEY_JSON:'.json_encode(array_merge(['status'=>'failed','stage'=>$stage,'reason'=>$reason,'operation_id'=>HM_OPERATION,'country'=>HM_COUNTRY,'date'=>HM_DATE,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls_unknown'=>false,'tourvisor_calls'=>0,'booking_calls'=>0,'lead_calls'=>0,'no_replay'=>true],$extra),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR).PHP_EOL;exit(2);}
function hm_text($v,int $max=200):string{if(!is_scalar($v))return'';$s=trim((string)(preg_replace('/\s+/u',' ',(string)$v)??''));return function_exists('mb_substr')?mb_substr($s,0,$max,'UTF-8'):substr($s,0,$max);}
function hm_country($v):?string{$s=mb_strtolower(trim((string)$v),'UTF-8');$s=str_replace(['ё','_','-'],['е',' ',' '],$s);$s=preg_replace('/\s+/u',' ',$s);$m=['egypt'=>['египет','egypt'],'turkey'=>['турция','turkey','türkiye','turkiye'],'thailand'=>['таиланд','thailand'],'uae'=>['оаэ','объединенные арабские эмираты','united arab emirates','uae'],'vietnam'=>['вьетнам','vietnam','viet nam'],'srilanka'=>['шри ланка','sri lanka'],'maldives'=>['мальдивы','maldives'],'cuba'=>['куба','cuba']];foreach($m as $k=>$a)if(in_array($s,$a,true))return $k;return null;}
function hm_norm($v):string{$s=mb_strtolower((string)$v,'UTF-8');$s=str_replace(['&','ё'],[' and ','е'],$s);preg_match_all('/[\p{L}\p{N}]+/u',$s,$m);$drop=['hotel'=>1,'hotels'=>1,'resort'=>1,'resorts'=>1,'spa'=>1,'the'=>1,'and'=>1,'by'=>1,'otel'=>1,'отель'=>1,'отели'=>1,'гостиница'=>1];$w=[];foreach($m[0] as $x)if(!isset($drop[$x]))$w[]=$x;sort($w,SORT_STRING);return implode(' ',$w);}
function hm_collect($node,array &$rows):void{if(!is_array($node))return;if(isset($node['operatorKey'],$node['hotelKey'],$node['hotel'])&&is_array($node['original']??null)&&isset($node['original']['hotelKey']))$rows[]=$node;foreach($node as $v)if(is_array($v))hm_collect($v,$rows);}
function hm_img(string $url):?array{if($url===''||!preg_match('~/([0-9]+)\.([0-9]+)\.([0-9]+)\.(?:jpe?g|png)(?:\?|$)~i',$url,$m))return null;return['operator'=>(int)$m[1],'anex'=>(int)$m[2],'andromeda'=>(int)$m[3]];}
function hm_select_in(PDO $db,string $sql,array $ids):array{if(!$ids)return[];$q=$db->prepare(str_replace('__IN__',implode(',',array_fill(0,count($ids),'?')),$sql));$q->execute(array_values($ids));return$q->fetchAll(PDO::FETCH_ASSOC);}
try{
 if(PHP_SAPI!=='cli'||!in_array(HM_COUNTRY,['egypt','turkey','thailand','uae','vietnam','srilanka','maldives','cuba'],true)||!preg_match('/^20\d\d-\d\d-\d\d$/D',HM_DATE)||!str_starts_with(HM_OPERATION,'hotel-match-anexkey-core8-mass-1971-'))hm_fail('bootstrap','unarmed');
 $root=realpath(getcwd());if(!$root||basename($root)!=='anytoour.ru')hm_fail('bootstrap','root');$preview=$root.'/_preview/search3-anex-candidate';$api=$preview.'/api-andromeda-search3-preview.php';if(!is_file($api))hm_fail('bootstrap','andromeda_runtime_missing');require_once$api;$anexPrivate=$preview.'/.anex-private.php';if(is_file($anexPrivate))require_once$anexPrivate;$private=$preview.'/.andromeda-private.php';if(!is_file($private))hm_fail('bootstrap','andromeda_private_missing');$cfg=require$private;if(!is_array($cfg))hm_fail('bootstrap','andromeda_config_invalid');require_once$root.'/config.php';require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
 $countries=$db->query('SELECT id,name FROM catalog_countries WHERE is_active=1')->fetchAll(PDO::FETCH_ASSOC);$countryRow=null;foreach($countries as$r)if(hm_country($r['name'])===HM_COUNTRY){$countryRow=$r;break;}if(!$countryRow)hm_fail('bootstrap','country_not_found');$countryId=(int)$countryRow['id'];$countryName=(string)$countryRow['name'];
 $app=is_file($preview.'/app/integrations/anex-search.php')?$preview.'/app/integrations':$root.'/app/integrations';foreach(['anex-search','anex-search-mapping-registry']as$f)require_once$app.'/'.$f.'.php';
 $criteria=['departureId'=>1,'countryId'=>$countryId,'dateFrom'=>HM_DATE,'dateTo'=>HM_DATE,'nightsFrom'=>HM_NIGHTS,'nightsTo'=>HM_NIGHTS,'adults'=>2,'childs'=>[],'currency'=>'RUB','meal'=>'','hotelIds'=>[],'regionIds'=>[],'subregionIds'=>[],'arrivalId'=>'','operatorIds'=>[],'hotelServices'=>[],'hotelTypes'=>[],'onlyDirect'=>false,'onlyCharter'=>false,'hotelCategory'=>'','hotelRating'=>'','priceFrom'=>'','priceTo'=>''];
 $token=trim((string)getenv('ANEX_API_TOKEN'));if($token===''&&defined('ANEX_API_TOKEN'))$token=trim((string)ANEX_API_TOKEN);if($token==='')hm_fail('anex','credential_missing');$client=new AnyTourAnexClient($token);$cache=[];$core=anytour_anex_search3_core($criteria);$q=$db->prepare('SELECT d.name departure_name,c.name country_name FROM catalog_departures d CROSS JOIN catalog_countries c WHERE d.id=? AND c.id=? AND d.is_active=1 AND c.is_active=1 LIMIT 1');$q->execute([1,$countryId]);$names=$q->fetch(PDO::FETCH_ASSOC);if(!$names)hm_fail('anex','dictionary_names_missing');$core['supplier_namespace']='anex_online';$core['departure_id']=anytour_anex_search3_dictionary_id(anytour_anex_search3_dictionary($client,'SearchTour_TOWNFROMS',[],$cache),[$names['departure_name']]);$core['destination_id']=anytour_anex_search3_dictionary_id(anytour_anex_search3_dictionary($client,'SearchTour_STATES',['TOWNFROMINC'=>$core['departure_id']],$cache),[$names['country_name']]);$dated=['TOWNFROMINC'=>$core['departure_id'],'STATEINC'=>$core['destination_id'],'CHECKIN_BEG'=>str_replace('-','',$core['checkin_begin']),'CHECKIN_END'=>str_replace('-','',$core['checkin_end']),'ADULT'=>2,'CHILD'=>0];$core['currency_id']=anytour_anex_search3_dictionary_id(anytour_anex_search3_dictionary($client,'SearchTour_CURRENCIES',$dated,$cache),['RUB','RUR','Рубль','Рубли','Руб']);$resolver=AnyTourAnexSearchMappingRegistry::fromPdo($db)->previewResolver();$ar=anytour_anex_search3_prices($client,$resolver,$core);$direct=[];foreach($ar['offers']??[]as$o){$h=$o['hotel']??[];$id=(string)($h['external_id']??'');if($id==='')continue;$direct[$id]=['name'=>hm_text($h['name']??''),'local_id'=>$h['local_id']??null];if(count($direct)>HM_HOTEL_CAP)hm_fail('anex','hotel_cap');}
 $req=['generation'=>1,'page'=>1,'params'=>$criteria,'andromeda_operator_ids'=>['5']];$saved=anytour_andromeda_search3_catalog($cfg,$req);$saved['excluded_operator_ids']=$cfg['excluded_operator_ids']??[];$base=anytour_andromeda_search3_params($req,$db,$saved);$budget=dirname((string)$cfg['catalog_path']);$transport=new AnyTourAndromedaTransport(true);$mk=static function()use($transport,$budget){return new AnyTourAndromedaClient(static function($url,$opts)use($transport,$budget){anytour_andromeda_search3_budget($budget);return$transport($url,$opts);},true);};$ac=$mk();$ac->login((string)$cfg['username'],(string)$cfg['password']);$session=$ac->privateSession();if(!$session)hm_fail('andromeda','session');
 $page=1;$pages=1;$bridges=[];$quarantine=[];$rawRows=0;do{if($page>HM_PAGE_CAP)hm_fail('andromeda','page_cap',['pages'=>$pages]);$p=$base;$p['PAGE']=$page;$pc=$page===1?$ac:$mk();if($page!==1)$pc->restorePrivateSession($session);$raw=$pc->price($p);$proj=AnyTourAndromedaNormalizer::page($raw,$p,'match-core8-key',1);$pages=(int)$proj['pages_count'];$rows=[];hm_collect($raw,$rows);$rawRows+=count($rows);foreach($rows as$r){if((int)($r['operatorKey']??0)!==5)continue;$aid=(int)($r['original']['hotelKey']??0);$did=(int)($r['hotelKey']??0);$name=hm_text($r['hotel']??'');if((int)($r['isOperatorHotelKey']??0)===1||$aid<=0||$did<=0){$quarantine[]=['andromeda_id'=>$did?:null,'anex_id'=>$aid?:null,'name'=>$name,'reason'=>(int)($r['isOperatorHotelKey']??0)===1?'operator_key_namespace':'missing_key'];continue;}$im=hm_img(hm_text($r['hotelImage']??'',500));$imageOk=$im!==null&&$im['operator']===5&&$im['anex']===$aid&&$im['andromeda']===$did;$d=$direct[(string)$aid]??null;$nameOk=$d!==null&&hm_norm($name)!==''&&hm_norm($name)===hm_norm($d['name']);$bridges[$did.'|'.$aid]=['andromeda_id'=>(string)$did,'anex_id'=>(string)$aid,'andromeda_name'=>$name,'direct_anex_name'=>$d['name']??null,'direct_anex_present'=>$d!==null,'direct_anex_local_hint'=>$d['local_id']??null,'name_exact_normalized'=>$nameOk,'image_pattern_verified'=>$imageOk,'hotel_url'=>hm_text($r['hotelUrl']??'',500),'town'=>hm_text($r['town']??''),'star'=>hm_text($r['star']??'')];if(count($bridges)>HM_HOTEL_CAP)hm_fail('andromeda','hotel_cap');}$page++;}while($page<=$pages);
 $byD=[];$byA=[];foreach($bridges as$b){$byD[$b['andromeda_id']][$b['anex_id']]=1;$byA[$b['anex_id']][$b['andromeda_id']]=1;}$confD=[];$confA=[];foreach($byD as$id=>$x)if(count($x)>1)$confD[$id]=array_keys($x);foreach($byA as$id=>$x)if(count($x)>1)$confA[$id]=array_keys($x);
 $aids=array_values(array_unique(array_column($bridges,'anex_id')));$dids=array_values(array_unique(array_column($bridges,'andromeda_id')));$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION READ ONLY');$maps=hm_select_in($db,'SELECT anex_hotel_id,catalog_hotel_id,enabled FROM anex_hotel_search_mappings WHERE anex_hotel_id IN (__IN__) ORDER BY anex_hotel_id,catalog_hotel_id',$aids);$dec=hm_select_in($db,'SELECT anex_hotel_id FROM anex_hotel_decisions WHERE anex_hotel_id IN (__IN__)',$aids);$exc=hm_select_in($db,'SELECT anex_hotel_id FROM anex_review_pair_exclusions WHERE anex_hotel_id IN (__IN__)',$aids);$and=hm_select_in($db,"SELECT external_hotel_id,local_hotel_id,decision_status,evidence_sha256,catalog_sha256 FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id IN (__IN__)",$dids);$db->exec('ROLLBACK');$mi=[];foreach($maps as$r)$mi[(string)$r['anex_hotel_id']][]=$r;$prot=[];foreach(array_merge($dec,$exc)as$r)$prot[(string)$r['anex_hotel_id']]=1;$ai=[];foreach($and as$r)$ai[(string)$r['external_hotel_id']]=$r;
 $outRows=[];$counts=[];foreach($bridges as$b){$aid=$b['anex_id'];$did=$b['andromeda_id'];$am=$mi[$aid]??[];$dr=$ai[$did]??null;$bucket='needs_more_evidence';$reason=[];$anchor=null;if(isset($confD[$did])||isset($confA[$aid])){$bucket='provider_one_to_many_conflict';$reason[]='provider_conflict';}elseif(isset($prot[$aid])){$bucket='protected_manual_or_exclusion';}elseif(!$b['direct_anex_present']){$bucket='direct_anex_not_in_same_day';}elseif(!$b['image_pattern_verified']&&!$b['name_exact_normalized']){$bucket='operator_key_lacks_secondary_corroboration';}elseif(count($am)>1){$bucket='current_anex_multiple_rows';}elseif($dr===null){$bucket='andromeda_identity_missing';}elseif((string)$dr['decision_status']==='conflict'){$bucket='current_andromeda_conflict';}else{$al=count($am)===1?(int)$am[0]['catalog_hotel_id']:null;$ae=count($am)===1?(int)$am[0]['enabled']:null;$dl=$dr['local_hotel_id']===null?null:(int)$dr['local_hotel_id'];$ds=(string)$dr['decision_status'];if($al!==null&&$ds==='accepted'&&$dl!==null&&$al!==$dl){$bucket='current_target_mismatch';}elseif($al!==null&&$ae===1&&$ds==='accepted'&&$dl===$al){$bucket='existing_exact_triple';$anchor=$al;}elseif($al!==null&&$ae===1&&$ds==='pending'&&$dl===null){$bucket='safe_missing_andromeda_side';$anchor=$al;}elseif($al===null&&$ds==='accepted'&&$dl!==null){$bucket='safe_missing_anex_side';$anchor=$dl;}else{$reason[]='insufficient_current_anchor';}}$counts[$bucket]=($counts[$bucket]??0)+1;$outRows[]=array_merge($b,['bucket'=>$bucket,'anchor_local_id'=>$anchor,'reason'=>$reason,'current_anex_rows'=>$am,'current_andromeda'=>$dr]);}
 ksort($counts);usort($outRows,fn($a,$b)=>[$a['bucket'],(int)$a['anex_id'],(int)$a['andromeda_id']]<=>[$b['bucket'],(int)$b['anex_id'],(int)$b['andromeda_id']]);echo 'MATCH_CORE8_KEY_JSON:'.json_encode(['status'=>'completed','operation_id'=>HM_OPERATION,'country'=>HM_COUNTRY,'country_id'=>$countryId,'country_name'=>$countryName,'date'=>HM_DATE,'pages'=>$pages,'raw_operator_rows'=>$rawRows,'direct_anex_hotels'=>count($direct),'bridges'=>count($bridges),'quarantine'=>count($quarantine),'provider_conflict_andromeda'=>count($confD),'provider_conflict_anex'=>count($confA),'counts'=>$counts,'rows'=>$outRows,'database_writes'=>0,'mapping_writes'=>0,'provider_calls'=>['andromeda_login'=>1,'andromeda_price_pages'=>$pages,'direct_anex'=>'one same-day normalized search plus dictionaries','tourvisor'=>0],'no_replay'=>true],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR).PHP_EOL;
}catch(Throwable$e){hm_fail('runtime',preg_match('/^[a-z0-9_]+$/i',$e->getMessage())?$e->getMessage():'provider_or_guard_failure',['exception_class'=>get_class($e)]);}
