<?php
declare(strict_types=1);
const OP='hotel-match-operator5-18819-public-apply-1971-20260917-v2';
const SOURCE_SHA='11f9256270ba1b6f64ce63787830e9857a2215348e8f19c3f91eb9ca2c79689f';
const HELD_SHA='ff6e6630ef9e4424d83fc89f736c15bb6822e2f73059499581c21ab0b0d499b6';
const ACCEPTED_SHA='1658318afe43b82491f84116c15714dab435c3fce311b4ab9459485d1e93eec9';
function rq($v,$m){if(!$v)throw new RuntimeException($m);}
function norm(string $s):string{$s=mb_strtoupper(trim($s),'UTF-8');$s=preg_replace('/\bEX\.?\s*/u',' ',$s);$s=preg_replace('/[^\pL\pN]+/u',' ',$s);$p=preg_split('/\s+/u',trim($s))?:[];return implode(' ',array_values(array_filter($p,fn($x)=>$x!==''&&$x!=='HOTEL')));}
function flags($v,string $path='',int $d=0):array{if($d>24||!is_array($v))return[];$o=[];foreach($v as$k=>$x){$p=$path===''?(string)$k:$path.'.'.$k;if(is_array($x)){$o+=flags($x,$p,$d+1);continue;}if(!preg_match('/manual|exclude|exclusion|conflict|reject|review|hold/i',$p))continue;if(is_bool($x)?$x:(is_numeric($x)?(float)$x!=0:(is_string($x)&&!in_array(mb_strtolower(trim($x),'UTF-8'),['','false','none','no','null','pending','unknown'],true))))$o[$p]=$x;}return$o;}
function km(float $a,float $o,float $b,float $p):float{$d1=deg2rad($b-$a);$d2=deg2rad($p-$o);$x=sin($d1/2)**2+cos(deg2rad($a))*cos(deg2rad($b))*sin($d2/2)**2;return 12742*asin(min(1,sqrt($x)));}
function one(PDO $db,string $sql,array $a=[]):array{$s=$db->prepare($sql);$s->execute($a);$r=$s->fetch(PDO::FETCH_ASSOC);rq(is_array($r),'row_missing');return$r;}
function all(PDO $db,string $sql,array $a=[]):array{$s=$db->prepare($sql);$s->execute($a);return$s->fetchAll(PDO::FETCH_ASSOC);}
$source=(string)getenv('MATCH_SOURCE_SHA');rq(getenv('MATCH_OPERATION_ID')===OP&&preg_match('/^[a-f0-9]{40}$/D',$source),'operation_guard');$dir=(string)getenv('HOME').'/.anytoour-match/operations/'.OP;$reservation=json_decode((string)file_get_contents($dir.'/reservation.json'),true,32,JSON_THROW_ON_ERROR);rq(($reservation['state']??'')==='reserved_before_public_evidence_and_db'&&($reservation['source_sha']??'')===$source,'reservation');$public=json_decode((string)file_get_contents($dir.'/public-evidence.json'),true,32,JSON_THROW_ON_ERROR);rq(($public['verified']??false)===true&&($public['native_hotel_id']??'')==='18819'&&($public['supplier']??'')==='ANEX','public_evidence');rq(preg_match('/^[a-f0-9]{64}$/D',(string)($public['page_sha256']??'')),'public_hash');rq(abs((float)($public['latitude']??0)-36.528713)<0.000001&&abs((float)($public['longitude']??0)-32.04812)<0.000001,'public_coords');
$out=['operation_id'=>OP,'source_sha'=>$source,'state'=>'failed_no_replay','database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'samo_andromeda_calls'=>0,'public_http_calls'=>1,'no_replay'=>true];$db=null;
try{$root=realpath(getcwd());rq(is_string($root)&&basename($root)==='anytoour.ru','root');require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL SERIALIZABLE');$db->beginTransaction();
$src=one($db,"SELECT supplier_namespace,external_hotel_id,local_hotel_id,decision_status,evidence_sha256,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace='operator_5' AND external_hotel_id='18819' FOR UPDATE");rq($src['decision_status']==='pending'&&$src['local_hotel_id']===null&&hash_equals(SOURCE_SHA,(string)$src['evidence_sha256']),'source_current');$ev=json_decode((string)$src['evidence_json'],true,64,JSON_THROW_ON_ERROR);rq(is_array($ev)&&flags($ev)===[],'source_protection');$s=$ev['source']??[];$b=$ev['provider_bridges'][0]??[];rq(is_array($s)&&is_array($b),'source_shape');rq((string)($s['native_hotel_id']??'')==='18819'&&(int)($s['country_id']??0)===4,'native_country');rq(norm((string)($s['name']??''))===norm('Grand Uysal Beach & Spa Hotel'),'native_name');rq((string)($b['andromeda_hotel_id']??'')==='118706','bridge_current');
$held=one($db,"SELECT local_hotel_id,decision_status,evidence_sha256,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id='118706' FOR UPDATE");rq($held['decision_status']==='pending'&&$held['local_hotel_id']===null&&hash_equals(HELD_SHA,(string)$held['evidence_sha256']),'held_current');
$accepted=one($db,"SELECT local_hotel_id,decision_status,evidence_sha256,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id='2000086116' FOR UPDATE");rq($accepted['decision_status']==='accepted'&&(int)$accepted['local_hotel_id']===56551&&hash_equals(ACCEPTED_SHA,(string)$accepted['evidence_sha256']),'accepted_authority');
$hotel=one($db,"SELECT id,country_id,name,category,region_name,subregion_name,latitude,longitude,is_active FROM catalog_hotels WHERE id=56551 FOR UPDATE");rq((int)$hotel['country_id']===4&&(int)$hotel['is_active']===1,'local_current');$aliases=all($db,"SELECT alias FROM hotel_aliases WHERE hotel_id=56551");$names=[norm((string)$hotel['name'])];foreach($aliases as$a)$names[]=norm((string)$a['alias']);rq(in_array(norm('Grand Uysal Beach & Spa Hotel'),$names,true),'local_alias');$dist=km((float)$public['latitude'],(float)$public['longitude'],(float)$hotel['latitude'],(float)$hotel['longitude']);rq($dist<=1.0,'public_geo');rq(norm((string)$public['hotel_name'])===norm('Grand Uysal Beach & Spa'),'public_name');rq(norm((string)$public['city'])===norm('Alanya'),'public_city');
$occupancy=all($db,"SELECT external_hotel_id,local_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace='operator_5' AND decision_status='accepted' AND local_hotel_id=56551 FOR UPDATE");rq(count($occupancy)===0,'operator_occupancy');
$ev['match_acceptance']=['operation_id'=>OP,'accepted_at_utc'=>gmdate('c'),'local_hotel_id'=>56551,'reason'=>'public_anex_native_objectcode_name_geo_plus_existing_local_authority','public_page_sha256'=>$public['page_sha256'],'public_native_hotel_id'=>'18819','public_giata_id'=>'26743','public_city'=>'Alanya','public_coordinate_distance_km'=>round($dist,4),'accepted_andromeda_authority'=>'2000086116','held_bridge_preserved'=>'118706'];$newJson=json_encode($ev,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);$newSha=hash('sha256',$newJson);$u=$db->prepare("UPDATE andromeda_hotel_identities SET local_hotel_id=56551,decision_status='accepted',evidence_json=?,evidence_sha256=? WHERE supplier_namespace='operator_5' AND external_hotel_id='18819' AND decision_status='pending' AND local_hotel_id IS NULL AND evidence_sha256=?");$u->execute([$newJson,$newSha,SOURCE_SHA]);rq($u->rowCount()===1,'conditional_update');$db->commit();$out['database_writes']=1;$out['mapping_writes']=1;
$rb=one($db,"SELECT local_hotel_id,decision_status,evidence_sha256,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace='operator_5' AND external_hotel_id='18819'");rq($rb['decision_status']==='accepted'&&(int)$rb['local_hotel_id']===56551&&hash_equals($newSha,(string)$rb['evidence_sha256']),'post_commit_source');$heldRb=one($db,"SELECT local_hotel_id,decision_status,evidence_sha256 FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id='118706'");rq($heldRb['decision_status']==='pending'&&$heldRb['local_hotel_id']===null&&hash_equals(HELD_SHA,(string)$heldRb['evidence_sha256']),'post_commit_held');$pending=all($db,"SELECT supplier_namespace,COUNT(*) c FROM andromeda_hotel_identities WHERE supplier_namespace IN ('andromeda_catalog','operator_315','operator_342','operator_5') AND decision_status='pending' AND local_hotel_id IS NULL GROUP BY supplier_namespace ORDER BY supplier_namespace");$out['state']='committed_verified';$out['mapping']=['supplier_namespace'=>'operator_5','external_hotel_id'=>'18819','local_hotel_id'=>56551,'new_evidence_sha256'=>$newSha,'public_page_sha256'=>$public['page_sha256'],'distance_km'=>round($dist,4)];$out['held_118706_preserved']=true;$out['pending_after']=$pending;
}catch(Throwable $e){if($db instanceof PDO&&$db->inTransaction())$db->rollBack();$out['error_code']=preg_match('/^[a-z_]{2,100}$/D',$e->getMessage())?$e->getMessage():'sanitized_failure';if($out['mapping_writes']===0)$out['state']='completed_no_write';}
$raw=json_encode($out,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";file_put_contents($dir.'/result.json',$raw,LOCK_EX);$h=hash('sha256',$raw);file_put_contents($dir.'/receipt.json',json_encode(['operation_id'=>OP,'source_sha'=>$source,'state'=>$out['state'],'result_sha256'=>$h,'readback_verified'=>true,'database_writes'=>$out['database_writes'],'mapping_writes'=>$out['mapping_writes'],'supplier_calls'=>0,'tourvisor_calls'=>0,'samo_andromeda_calls'=>0,'public_http_calls'=>1,'no_replay'=>true],JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT)."\n",LOCK_EX);echo json_encode(['state'=>$out['state'],'error_code'=>$out['error_code']??null,'mapping'=>$out['mapping']??null,'held_118706_preserved'=>$out['held_118706_preserved']??null,'pending_after'=>$out['pending_after']??[],'result_sha256'=>$h],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";if(!in_array($out['state'],['committed_verified','completed_no_write'],true))exit(2);
