<?php
declare(strict_types=1);
const S26_OP='hotel-match-refresh55-safe26-accept-1971-20260919-v1',S26_INPUT='3144fbbfe9a886bb94954d8a12147119172f570285ae7622edf2ffb8ed16657a';
require_once __DIR__.'/hotel_match_refresh55_safe26_accept_helpers_v1.php';
function s26_anex_proof(array $r):array{
 $hits=[];foreach((array)($r['operator_proofs']??[])as$p)if(is_array($p)&&($p['operator']??'')==='anex'&&(int)($p['operator_id']??0)===13)$hits[]=$p;
 s26_need(count($hits)===1,'anex_proof_count');$p=$hits[0];$n=(array)($p['native_proofs']??[]);s26_need(count($n)===1&&is_array($n[0]),'anex_native_proof_count');$native=(string)($n[0]['native_token']??'');$fact=(array)($n[0]['fact']??[]);
 s26_need(preg_match('/^[1-9][0-9]*$/D',$native)===1,'native_token');s26_need((string)($fact['samo_hotel_id']??'')===(string)$r['samo_hotel_id'],'fact_samo');s26_need((string)($fact['native_operator_hotel_id']??'')===$native,'fact_native');s26_need((string)($fact['operator_id']??'')==='5','fact_operator');return[$native,$p];
}
if(in_array('--self-test',$argv??[],true)){$x=['samo_hotel_id'=>'7','operator_proofs'=>[['operator'=>'anex','operator_id'=>13,'native_proofs'=>[['native_token'=>'11','fact'=>['samo_hotel_id'=>'7','native_operator_hotel_id'=>'11','operator_id'=>'5']]]]]];[$n,$p]=s26_anex_proof($x);s26_need($n==='11','self');echo"REFRESH55_SAFE26_ACCEPT_SELFTEST_OK\n";exit(0);}
$dir=(string)getenv('MATCH_OPERATION_DIR');$root=realpath((string)getenv('ANYTOUR_ROOT'));$ip=realpath((string)getenv('MATCH_INPUT_PATH'));$sha=(string)getenv('MATCH_SOURCE_SHA');s26_need(PHP_SAPI==='cli'&&is_dir($dir)&&basename($dir)===S26_OP&&is_string($root)&&is_string($ip)&&hash_file('sha256',$ip)===S26_INPUT&&preg_match('/^[a-f0-9]{40}$/D',$sha),'runtime');
$res=json_decode((string)file_get_contents($dir.'/reservation.json'),true,32,JSON_THROW_ON_ERROR);s26_need(($res['operation']??'')===S26_OP&&($res['source_sha']??'')===$sha&&($res['current_sha256']??'')===S26_INPUT&&(int)($res['max_mapping_writes']??0)===26,'reservation');
$input=json_decode((string)file_get_contents($ip),true,256,JSON_THROW_ON_ERROR);s26_need(($input['state']??'')==='completed_read_only'&&(int)($input['safe_candidate_count']??0)===26&&(int)($input['unique_pair_count']??0)===32,'input');$safe=[];$tvSeen=[];foreach((array)$input['rows']as$r){if(($r['state']??'')!=='safe_candidate')continue;$sid=(string)($r['samo_hotel_id']??'');$tv=(int)($r['tv_hotel_id']??0);s26_need(preg_match('/^[1-9][0-9]*$/D',$sid)===1&&$tv>0&&!isset($safe[$sid])&&!isset($tvSeen[$tv]),'safe_identity');[$native,$anexProof]=s26_anex_proof($r);s26_need(($r['current_source']??null)===null,'input_source_not_absent');$safe[$sid]=['row'=>$r,'tv'=>$tv,'native'=>$native,'anex_proof'=>$anexProof];$tvSeen[$tv]=true;}s26_need(count($safe)===26&&count($tvSeen)===26,'safe26');
require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');require_once $dir.'/payload/andromeda-hotel-resolver.php';require_once $dir.'/payload/anex-search-mapping-registry.php';$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$committed=false;$attempted=false;$writes=0;$base=['operation'=>S26_OP,'source_sha'=>$sha,'provider_calls'=>0,'no_replay'=>true,'input_current_sha256'=>S26_INPUT];
try{
 $db->exec('SET SESSION innodb_lock_wait_timeout=10');$db->exec('SET TRANSACTION ISOLATION LEVEL SERIALIZABLE');$db->beginTransaction();
 $all=s26_rows($db,'SELECT * FROM andromeda_hotel_identities ORDER BY supplier_namespace,external_hotel_id LIMIT 50001 FOR UPDATE');s26_need(count($all)<50001,'identity_cap');$idx=[];$before=[];foreach($all as$r){$k=$r['supplier_namespace'].':'.$r['external_hotel_id'];$idx[$k]=$r;$before[$k]=s26_hash($r);}
 $targets=array_values(array_map(fn($x)=>(int)$x['tv'],$safe));$natives=array_values(array_map(fn($x)=>(string)$x['native'],$safe));$tp=implode(',',array_fill(0,26,'?'));$np=implode(',',array_fill(0,26,'?'));
 $hot=s26_rows($db,"SELECT id,name,country_name,region_name,subregion_name,category,is_active FROM catalog_hotels WHERE id IN ($tp) FOR UPDATE",$targets);$hotBy=[];foreach($hot as$h)$hotBy[(int)$h['id']]=$h;
 $maps=s26_rows($db,"SELECT * FROM anex_hotel_search_mappings WHERE anex_hotel_id IN ($np) OR catalog_hotel_id IN ($tp) FOR UPDATE",array_merge($natives,$targets));$dec=s26_rows($db,"SELECT * FROM anex_hotel_decisions WHERE anex_hotel_id IN ($np) OR catalog_hotel_id IN ($tp) FOR UPDATE",array_merge($natives,$targets));$exc=s26_rows($db,"SELECT * FROM anex_review_pair_exclusions WHERE anex_hotel_id IN ($np) OR catalog_hotel_id IN ($tp) FOR UPDATE",array_merge($natives,$targets));
 $mapBy=[];foreach($maps as$m)if((int)($m['enabled']??1)===1)$mapBy[(string)$m['anex_hotel_id']][]=$m;$decP=[];foreach($dec as$x)$decP[(string)$x['anex_hotel_id'].'|'.(int)$x['catalog_hotel_id']]=true;$excP=[];foreach($exc as$x)$excP[(string)$x['anex_hotel_id'].'|'.(int)$x['catalog_hotel_id']]=true;$occ=[];foreach($all as$r)if($r['supplier_namespace']==='andromeda_catalog'&&$r['decision_status']==='accepted'&&$r['local_hotel_id']!==null)$occ[(int)$r['local_hotel_id']][]=$r;
 $plan=[];$skipped=[];foreach($safe as$sid=>$s){$review=$s['row'];$tv=(int)$s['tv'];$native=(string)$s['native'];$why=[];$cur=$idx['andromeda_catalog:'.$sid]??null;if($cur!==null)$why[]='source_appeared';$t=$hotBy[$tv]??null;$rt=(array)($review['target']??[]);$sc=(array)($review['source_catalog']??[]);$sh=(array)($sc['hotel']??[]);$country=(string)($sc['country']??'');if(!$t||(int)$t['is_active']!==1||(int)$t['id']!==$tv||(string)$t['country_name']!==$country||(string)$t['country_name']!==(string)($rt['country_name']??'')||(string)$t['name']!==(string)($rt['name']??'')||(int)$t['category']!==(int)($rt['category']??0))$why[]='target_drift';$star=(string)($sh['star']??'');if($star!==''&&preg_match('/^[1-5]$/D',$star)&&$t&&(int)$star!==(int)$t['category'])$why[]='category_mismatch';$mm=$mapBy[$native]??[];$exact=array_values(array_filter($mm,fn($x)=>(int)$x['catalog_hotel_id']===$tv));if(count($mm)!==1||count($exact)!==1)$why[]='anex_mapping_drift';$pair=$native.'|'.$tv;if(isset($decP[$pair]))$why[]='anex_decision';if(isset($excP[$pair]))$why[]='anex_exclusion';if(array_filter($occ[$tv]??[],fn($x)=>(string)$x['external_hotel_id']!==$sid))$why[]='target_occupied';if($why){$skipped[]=['samo_hotel_id'=>$sid,'tv_hotel_id'=>$tv,'reasons'=>$why];continue;}
  $catalogHash=(string)($sc['catalog_sha256']??'');s26_need(preg_match('/^[a-f0-9]{64}$/D',$catalogHash)===1,'catalog_hash');$e=['operation_id'=>S26_OP,'rule'=>'common4_saved_operatorlink_plus_samo_price_native_bridge','current_review_sha256'=>S26_INPUT,'samo_hotel_id'=>$sid,'tv_hotel_id'=>$tv,'native_anex_id'=>$native,'operator_proofs'=>$review['operator_proofs'],'source_catalog'=>$sc,'target'=>['name'=>$t['name'],'country_name'=>$t['country_name'],'region_name'=>$t['region_name'],'subregion_name'=>$t['subregion_name'],'category'=>(int)$t['category']],'anex_mapping_sha256'=>s26_hash($exact[0])];$ej=s26_json($e);$plan[$sid]=['tv'=>$tv,'native'=>$native,'catalog'=>$catalogHash,'eh'=>hash('sha256',$ej),'ej'=>$ej];}
 s26_need($plan!==[],'no_current_safe');s26_write($dir.'/capture.json',$base+['input_safe'=>26,'current_safe'=>count($plan),'skipped'=>$skipped,'identity_hashes'=>$before]);s26_write($dir.'/plan.json',$base+['writes'=>array_map(fn($x)=>['tv'=>$x['tv'],'native'=>$x['native'],'catalog'=>$x['catalog'],'evidence_sha256'=>$x['eh']],$plan),'skipped'=>$skipped]);
 foreach($plan as$sid=>$p){$s=$db->prepare("INSERT INTO andromeda_hotel_identities(supplier_namespace,external_hotel_id,local_hotel_id,decision_status,catalog_sha256,evidence_sha256,evidence_json) VALUES('andromeda_catalog',?,?,'accepted',?,?,?)");$s->execute([$sid,$p['tv'],$p['catalog'],$p['eh'],$p['ej']]);s26_need($s->rowCount()===1,'write_count');$writes++;}
 $after=s26_rows($db,'SELECT * FROM andromeda_hotel_identities ORDER BY supplier_namespace,external_hotel_id LIMIT 50001');$other=[];foreach($after as$r){$k=$r['supplier_namespace'].':'.$r['external_hotel_id'];if(!($r['supplier_namespace']==='andromeda_catalog'&&isset($plan[(string)$r['external_hotel_id']])))$other[$k]=s26_hash($r);}s26_need($other===$before,'other_rows_changed');s26_write($dir.'/pre-commit.json',$base+['writes_uncommitted'=>$writes,'skipped'=>$skipped,'prior_identities_preserved'=>count($before)]);$attempted=true;$db->commit();$committed=true;
 $db->exec('START TRANSACTION READ ONLY');$rr=s26_rows($db,"SELECT i.*,h.id AS existing_catalog_hotel_id FROM andromeda_hotel_identities i LEFT JOIN catalog_hotels h ON h.id=i.local_hotel_id WHERE i.decision_status IN ('accepted','rejected') ORDER BY i.supplier_namespace,i.external_hotel_id LIMIT 50001");$projection=[];$written=[];foreach($rr as$r){$projection[]=['supplier_namespace'=>$r['supplier_namespace'],'external_hotel_id'=>$r['external_hotel_id'],'decision_status'=>$r['decision_status'],'catalog_hotel_id'=>$r['local_hotel_id'],'existing_catalog_hotel_id'=>$r['existing_catalog_hotel_id']];if($r['supplier_namespace']==='andromeda_catalog'&&isset($plan[(string)$r['external_hotel_id']]))$written[(string)$r['external_hotel_id']]=$r;}s26_need(count($written)===$writes,'readback_count');$resolver=AnyTourAndromedaHotelResolver::fromRows($projection,s26_hash($projection));$anex=AnyTourAnexSearchMappingRegistry::fromPdo($db);foreach($plan as$sid=>$p){$w=$written[$sid];s26_need($w['decision_status']==='accepted'&&(int)$w['local_hotel_id']===$p['tv']&&$w['catalog_sha256']===$p['catalog']&&$w['evidence_sha256']===$p['eh']&&hash('sha256',$w['evidence_json'])===$p['eh'],'row_readback');$page=$resolver->apply(['provider'=>'andromeda','selection_enabled'=>false,'offers'=>[['provider'=>'andromeda','selection_enabled'=>false,'local_hotel_id'=>null,'supplier_namespace'=>'andromeda_catalog','external_hotel_id'=>$sid]]]);s26_need($page['offers'][0]['local_hotel_id']===$p['tv'],'resolver');s26_need($anex->resolve('anex_online',$p['native'],'preview')===$p['tv'],'anex_resolver');}$db->rollBack();
 $out=$base+['state'=>'committed_verified','committed_at_utc'=>gmdate('c'),'database_writes'=>$writes,'mapping_writes'=>$writes,'accepted_delta'=>$writes,'unique_samo_local_delta'=>$writes,'triple_delta'=>$writes,'input_safe'=>26,'skipped_count'=>count($skipped),'skipped'=>$skipped,'written_count'=>$writes,'written'=>array_map(fn($x)=>['tv_hotel_id'=>$x['tv'],'native_anex_id'=>$x['native'],'catalog_sha256'=>$x['catalog'],'evidence_sha256'=>$x['eh']],$plan),'prior_identities_preserved'=>count($before),'readback_verified'=>true];
}catch(Throwable $e){if($db instanceof PDO&&$db->inTransaction())$db->rollBack();$out=$base+['state'=>$committed?'committed_unverified':($attempted?'commit_outcome_unknown':'rolled_back_or_prewrite_failed'),'reason'=>preg_replace('/[^A-Za-z0-9_.:-]/','_',substr($e->getMessage(),0,140)),'database_writes'=>$committed?$writes:($attempted?null:0),'mapping_writes'=>$committed?$writes:($attempted?null:0),'writes_attempted'=>$writes,'readback_verified'=>false];}
$rh=s26_write($dir.'/result.json',$out);s26_write($dir.'/receipt.json',$base+['state'=>$out['state'],'result_sha256'=>$rh,'mapping_writes'=>$out['mapping_writes'],'database_writes'=>$out['database_writes'],'readback_verified'=>$out['readback_verified']]);echo s26_json(['state'=>$out['state'],'written_count'=>$out['written_count']??null,'skipped_count'=>$out['skipped_count']??null,'result_sha256'=>$rh,'reason'=>$out['reason']??null])."\n";exit(($out['state']??'')==='committed_verified'?0:2);
