<?php
declare(strict_types=1);
const LM_OP='hotel-match-live143-moscow-anex-samo-1971-20260919-v1',LM_FRONTIER_SHA='3c022aeef67301e6e24de1f78380e9252221ba933b964d4963e9a778a9686e64',LM_MAX_CALLS=180,LM_MAX_PRICE=150,LM_MAX_PAGES=8;
if(in_array('--self-test',$argv??[],true)){require_once __DIR__.'/hotel_match_live143_moscow_anex_samo_helpers_v1.php';lm_need(lm_id('8365')==='8365','id');$f=lm_fact(['hotelKey'=>190031,'operatorKey'=>5,'original'=>['hotelKey'=>8365,'isOperatorHotelKey'=>0]],'5');lm_need(($f['native_operator_hotel_id']??'')==='8365','fact');echo"LIVE143_MOSCOW_ANEX_SAMO_SELFTEST_OK\n";exit(0);}
if(PHP_SAPI!=='cli')exit(2);
$dir=(string)getenv('MATCH_OPERATION_DIR');$root=realpath((string)getenv('ANYTOUR_ROOT'));$input=realpath((string)getenv('MATCH_FRONTIER_PATH'));$sha=(string)getenv('MATCH_SOURCE_SHA');
if(!is_dir($dir)||basename($dir)!==LM_OP||!is_string($root)||!is_dir($root)||!is_string($input)||hash_file('sha256',$input)!==LM_FRONTIER_SHA||!preg_match('/^[a-f0-9]{40}$/D',$sha))throw new RuntimeException('runtime');
$res=json_decode((string)file_get_contents($dir.'/reservation.json'),true,32,JSON_THROW_ON_ERROR);if(($res['operation']??'')!==LM_OP||($res['state']??'')!=='reserved_before_provider_access')throw new RuntimeException('reservation');
require_once $dir.'/payload/hotel_match_live143_moscow_anex_samo_helpers_v1.php';require_once $dir.'/payload/andromeda-network-transport-failure.php';require_once $dir.'/payload/andromeda-transport.php';require_once $dir.'/payload/andromeda-client.php';
$front=json_decode((string)file_get_contents($input),true,128,JSON_THROW_ON_ERROR);lm_need(($front['state']??'')==='completed_read_only','frontier_state');
$rows=[];foreach((array)$front['frontier']as$x){if(($x['route']??'')!=='query_ready_user_seen_anex')continue;$c=$x['latest_future_anex_context']??null;if(!is_array($c)||(int)($c['departure_id']??0)!==1)continue;$rows[]=$x;}lm_need(count($rows)===143,'frontier143');
$ids=array_values(array_unique(array_map(fn($x)=>(int)$x['tv_hotel_id'],$rows)));sort($ids,SORT_NUMERIC);$ph=implode(',',array_fill(0,count($ids),'?'));
$dbf=is_file($root.'/data/db-v1.php')?$root.'/data/db-v1.php':$root.'/v2/data/db-v1.php';require_once$dbf;$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION READ ONLY');
$current=[];foreach(lm_rows($db,"SELECT id,name,country_id,country_name,region_id,region_name,subregion_id,subregion_name,is_active FROM catalog_hotels WHERE id IN ($ph)",$ids)as$h)$current[(int)$h['id']]=$h;
$aliases=[];foreach(lm_rows($db,"SELECT hotel_id,alias FROM hotel_aliases WHERE hotel_id IN ($ph)",$ids)as$a){$v=trim((string)$a['alias']);if($v!=='')$aliases[(int)$a['hotel_id']][]=$v;}
$closed=[];foreach(lm_rows($db,"SELECT external_hotel_id,local_hotel_id,decision_status FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IN ($ph)",$ids)as$r)$closed[(int)$r['local_hotel_id']][]=(string)$r['external_hotel_id'];$db->rollBack();
$active=[];$skipped=[];foreach($rows as$x){$id=(int)$x['tv_hotel_id'];$h=$current[$id]??null;if(!$h||(int)$h['is_active']!==1){$skipped[]=['tv_hotel_id'=>$id,'state'=>'inactive_or_missing'];continue;}if(isset($closed[$id])){$skipped[]=['tv_hotel_id'=>$id,'state'=>'already_accepted','samo_ids'=>$closed[$id]];continue;}$x['current_hotel']=$h;$x['current_aliases']=$aliases[$id]??[];$active[]=$x;}lm_need(count($active)>0,'all_closed');
$in=file('php://stdin',FILE_IGNORE_NEW_LINES);$user=trim((string)($in[0]??''));$pass=trim((string)($in[1]??''));unset($in);lm_need($user!==''&&$pass!=='','credentials');
$calls=0;$priceCalls=0;$manifest=[];$providerAccess=false;$reserve=function(string $kind,array $meta=[])use(&$calls,$dir){$calls++;lm_need($calls<=LM_MAX_CALLS,'call_cap');lm_write($dir.'/provider-calls.jsonl',json_encode(['seq'=>$calls,'kind'=>$kind,'at_utc'=>gmdate('c'),'meta'=>$meta],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",false);};
$aliasesByCountry=['Турция'=>['Турция','Turkey','Turkiye','Türkiye'],'Катар'=>['Катар','Qatar'],'Маврикий'=>['Маврикий','Mauritius'],'Египет'=>['Египет','Egypt'],'Вьетнам'=>['Вьетнам','Vietnam'],'Индия'=>['Индия','India'],'Тунис'=>['Тунис','Tunisia'],'Узбекистан'=>['Узбекистан','Uzbekistan'],'ОАЭ'=>['ОАЭ','Объединенные Арабские Эмираты','United Arab Emirates','UAE'],'Казахстан'=>['Казахстан','Kazakhstan']];
try{
 $providerAccess=true;$reserve('login');$cat=new AnyTourAndromedaClient(new AnyTourAndromedaTransport(false,false),true);$cat->login($user,$pass);unset($user,$pass);$session=$cat->privateSession();lm_need(is_array($session),'session');
 $reserve('catalog_townfrom');$tf=$cat->catalog('townfrom');lm_raw($dir,'catalog-townfrom',$tf,$manifest);$dep=lm_dict($tf['TOWNFROM'],['Москва','Moscow']);
 $reserve('catalog_state',['dep'=>$dep]);$st=$cat->catalog('state',['TOWNFROMINC'=>$dep]);lm_raw($dir,'catalog-state',$st,$manifest);
 $countries=[];foreach($active as$x)$countries[(string)$x['country_name']]=true;$catalogs=[];$stateIds=[];
 foreach(array_keys($countries)as$country){lm_need(isset($aliasesByCountry[$country]),'country_alias_'.$country);$sid=lm_dict($st['STATE'],$aliasesByCountry[$country]);$stateIds[$country]=$sid;$reserve('catalog_all',['country'=>$country,'state'=>$sid]);$all=$cat->catalog('all',['TOWNFROMINC'=>$dep,'STATEINC'=>$sid]);lm_raw($dir,'catalog-'.substr(hash('sha256',$country),0,10),$all,$manifest);$op=null;foreach((array)$all['OPERATORS']as$o){if((string)($o['id']??'')==='5'&&str_contains(lm_norm(lm_text($o['name']??($o['lName']??''),100)),'anex')){$op='5';break;}}lm_need($op==='5','anex_binding_'.$country);$catalogs[$country]=['provider'=>lm_provider((array)$all['HOTELS'],lm_towns((array)$all['TOWNTO'])),'operator_id'=>'5'];}
 $plans=[];$groups=[];$noCandidate=0;
 foreach($active as$x){$id=(int)$x['tv_hotel_id'];$country=(string)$x['country_name'];$target=$x['current_hotel'];$cand=lm_candidates($target,$x['current_aliases'],$catalogs[$country]['provider']);$cids=array_keys($cand['candidates']);$ctx=$x['latest_future_anex_context'];$key=implode('|',[$country,$ctx['departure_date'],(int)$ctx['nights'],(int)$ctx['adults'],(int)$ctx['children_count'],(string)$ctx['child_ages_signature']]);$plans[$id]=['tv_hotel_id'=>$id,'hotel_name'=>$target['name'],'country'=>$country,'region_name'=>$target['region_name'],'subregion_name'=>$target['subregion_name'],'anex_hotel_ids'=>array_map('strval',(array)$x['anex_hotel_ids']),'context'=>$ctx,'retrieval_mode'=>$cand['mode'],'candidates'=>$cand['candidates'],'candidate_ids'=>$cids,'facts'=>[],'group_key'=>$key];if(!$cids){$noCandidate++;continue;}$groups[$key]['country']=$country;$groups[$key]['context']=$ctx;$groups[$key]['targets'][]=$id;foreach($cids as$cid)$groups[$key]['candidate_ids'][$cid]=true;}
 foreach($groups as$gk=>&$g){$allIds=array_keys($g['candidate_ids']);sort($allIds,SORT_NATURAL);$g['chunks']=[];foreach(array_chunk($allIds,30)as$ci=>$chunk){$params=['TOWNFROMINC'=>$dep,'STATEINC'=>$stateIds[$g['country']],'CHECKIN_BEG'=>str_replace('-','',(string)$g['context']['departure_date']),'CHECKIN_END'=>str_replace('-','',(string)$g['context']['departure_date']),'NIGHTS_FROM'=>(int)$g['context']['nights'],'NIGHTS_TILL'=>(int)$g['context']['nights'],'ADULT'=>(int)$g['context']['adults'],'CHILD'=>(int)$g['context']['children_count'],'CURRENCYINC'=>643,'OPERATORS'=>'5','HOTELS'=>implode(',',$chunk),'PACKETTYPE'=>0,'PAGE'=>1];if((int)$g['context']['children_count']>0){$ages=(string)$g['context']['child_ages_signature'];lm_need(preg_match('/^[0-9]+(?:,[0-9]+)*$/D',$ages)===1&&count(explode(',',$ages))===(int)$g['context']['children_count'],'ages');$params['AGES']=$ages;}$needed=array_fill_keys($chunk,true);$seen=[];$pages=0;$pcnt=null;
   for($p=1;$p<=LM_MAX_PAGES;$p++){lm_need(++$priceCalls<=LM_MAX_PRICE,'price_cap');$params['PAGE']=$p;$reserve('price',['group'=>substr(hash('sha256',$gk),0,12),'chunk'=>$ci,'page'=>$p,'hotels'=>count($chunk)]);$cl=new AnyTourAndromedaClient(new AnyTourAndromedaTransport(true,false),true);$cl->restorePrivateSession($session);$reply=$cl->price($params);lm_raw($dir,'price-'.substr(hash('sha256',$gk),0,10).'-c'.$ci.'-p'.$p,$reply,$manifest);$pages++;$pcnt=(int)$reply['PAGES_COUNT'];foreach((array)$reply['PRICES']as$row){if(!is_array($row)||!($fact=lm_fact($row,'5')))continue;$sid=$fact['samo_hotel_id'];if(!isset($needed[$sid]))continue;$seen[$sid]=true;foreach($g['targets']as$tid)if(isset($plans[$tid]['candidates'][$sid]))$plans[$tid]['facts'][]=$fact;}if(!array_diff_key($needed,$seen)||$pcnt===0||$p>=$pcnt)break;}
   $g['chunks'][]=['candidate_ids'=>$chunk,'pages_read'=>$pages,'pages_count_reported'=>$pcnt,'seen_candidate_ids'=>array_keys($seen),'pagination_incomplete'=>(bool)(array_diff_key($needed,$seen)&&$pcnt!==null&&$pages<$pcnt)];
  }unset($g['candidate_ids']);}unset($g);
 $counts=[];$dossiers=[];foreach($plans as$p){$direct=[];$returned=[];$incomplete=false;if(isset($groups[$p['group_key']]))foreach($groups[$p['group_key']]['chunks']as$ch)if($ch['pagination_incomplete'])$incomplete=true;foreach($p['facts']as$f){$returned[$f['samo_hotel_id']]=true;if($f['native_operator_hotel_id']!==null&&in_array((string)$f['native_operator_hotel_id'],$p['anex_hotel_ids'],true))$direct[$f['samo_hotel_id']]=$f;}$state=!$p['candidate_ids']?'no_catalog_candidate':($incomplete?'pagination_hold':(!$returned?'not_returned_exact_context':(count($direct)===1?'direct_native_bridge':(count($direct)>1?'ambiguous_direct_bridge':'returned_without_native_match'))));$counts[$state]=($counts[$state]??0)+1;$dossiers[]=['tv_hotel_id'=>$p['tv_hotel_id'],'hotel_name'=>$p['hotel_name'],'country'=>$p['country'],'region_name'=>$p['region_name'],'subregion_name'=>$p['subregion_name'],'anex_hotel_ids'=>$p['anex_hotel_ids'],'context'=>$p['context'],'retrieval_mode'=>$p['retrieval_mode'],'queried_candidate_ids'=>$p['candidate_ids'],'returned_samo_ids'=>array_keys($returned),'direct_bridges'=>array_values($direct),'state'=>$state,'safe_to_write_now'=>false];}
 $mh=lm_json_file($dir.'/raw-manifest.json',['files'=>$manifest]);$result=['operation'=>LM_OP,'state'=>'completed_read_only','source_sha'=>$sha,'frontier_sha256'=>LM_FRONTIER_SHA,'input_live143'=>143,'current_active_targets'=>count($active),'current_skipped'=>count($skipped),'skipped'=>$skipped,'country_count'=>count($countries),'group_count'=>count($groups),'provider_calls'=>$calls,'price_calls'=>$priceCalls,'tourvisor_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'state_counts'=>$counts,'dossiers'=>$dossiers,'raw_manifest_sha256'=>$mh,'no_replay'=>true];
}catch(Throwable $e){if(isset($db)&&$db->inTransaction())$db->rollBack();$result=['operation'=>LM_OP,'state'=>$providerAccess?'terminal_failed_no_replay':'failed_before_provider_access','source_sha'=>$sha,'frontier_sha256'=>LM_FRONTIER_SHA,'reason'=>preg_replace('/[^A-Za-z0-9_.:-]/','_',lm_text($e->getMessage(),120)),'provider_calls'=>$calls,'price_calls'=>$priceCalls,'tourvisor_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>$providerAccess];if($manifest&&!file_exists($dir.'/raw-manifest.json'))$result['raw_manifest_sha256']=lm_json_file($dir.'/raw-manifest.json',['files'=>$manifest]);}
$rh=lm_json_file($dir.'/result.json',$result);lm_json_file($dir.'/receipt.json',['operation'=>LM_OP,'state'=>$result['state'],'result_sha256'=>$rh,'provider_calls'=>$result['provider_calls'],'price_calls'=>$result['price_calls'],'tourvisor_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'raw_manifest_sha256'=>$result['raw_manifest_sha256']??null,'no_replay'=>$result['no_replay']]);echo json_encode(['state'=>$result['state'],'active'=>$result['current_active_targets']??null,'groups'=>$result['group_count']??null,'provider_calls'=>$result['provider_calls'],'price_calls'=>$result['price_calls'],'state_counts'=>$result['state_counts']??null,'reason'=>$result['reason']??null],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";exit(($result['state']??'')==='completed_read_only'?0:2);
