<?php
declare(strict_types=1);
function hmd_detail_link(array $d):array{$urls=[];$walk=function(mixed $v,string $key='',int $depth=0)use(&$walk,&$urls):void{if($depth>7)return;if(is_array($v)){foreach($v as$k=>$x)$walk($x,(string)$k,$depth+1);return;}if(!is_string($v)||!preg_match('/(?:url|link)/i',$key))return;$u=trim($v);if($u===''||strlen($u)>2048)return;$p=parse_url($u);if(!is_array($p)||!in_array(strtolower((string)($p['scheme']??'')),['http','https'],true)||empty($p['host']))return;$urls[$u]=true;};$walk($d);$native=[];foreach(array_keys($urls)as$u){$p=parse_url($u);parse_str((string)($p['query']??''),$q);foreach($q as$k=>$v){if(!in_array(strtolower((string)$k),['hotellist','hotelcode','hotel_code','hotelid','hotel_id','hotelinc','hotel'],true))continue;foreach((array)$v as$item)foreach(preg_split('/[,;]+/',(string)$item)?:[]as$x)if(preg_match('/^[1-9][0-9]{0,12}$/D',trim($x)))$native[(int)trim($x)]=true;}}$ids=array_keys($native);sort($ids,SORT_NUMERIC);return['urls'=>array_slice(array_keys($urls),0,12),'native_ids'=>$ids];}
function hmd_tv_search_id(array $p):?int{foreach(['searchId','id']as$k){$n=hmd_id($p[$k]??null);if($n)return$n;}foreach($p as$v)if(is_array($v)){if($n=hmd_tv_search_id($v))return$n;}return null;}
function hmd_tv_complete(array $p):bool{if((int)($p['progress']??0)>=100)return true;if(in_array(hmd_norm(hmd_text($p['status']??'')),['complete','completed','done','ready'],true))return true;foreach($p as$v)if(is_array($v)&&hmd_tv_complete($v))return true;return false;}
function hmd_request_count(array $p):int{foreach(['requestCount','requestsCount','request_count']as$k)if(isset($p[$k])&&is_numeric($p[$k]))return max(0,(int)$p[$k]);foreach($p as$v)if(is_array($v)){if(($n=hmd_request_count($v))>0)return$n;}return 0;}
function hmd_tv_rows(array $p):array{if(array_is_list($p))return$p;foreach(['hotels','results','items','operators','regions']as$k)if(is_array($p[$k]??null))return$p[$k];return[];}
function hmd_tv_merge(array $acc,array $rows):array{$by=[];foreach($acc as$h)if(is_array($h)&&($id=hmd_id($h['id']??null)))$by[$id]=$h;foreach($rows as$h){if(!is_array($h)||!($id=hmd_id($h['id']??null)))continue;if(!isset($by[$id])){$by[$id]=$h;continue;}$base=$by[$id];$seen=[];$tours=[];foreach(array_merge((array)($base['tours']??[]),(array)($h['tours']??[]))as$t){if(!is_array($t))continue;$tid=hmd_text($t['id']??$t['tourId']??'',220);$key=$tid!==''?'id:'.$tid:'sha:'.hash('sha256',hmd_json($t));if(isset($seen[$key]))continue;$seen[$key]=true;$tours[]=$t;}foreach($h as$k=>$v)if($k!=='tours'&&(!array_key_exists($k,$base)||$base[$k]===null||$base[$k]===''))$base[$k]=$v;$base['tours']=$tours;$by[$id]=$base;}ksort($by,SORT_NUMERIC);return array_values($by);}
function hmd_tv_sig(array $rows):array{$hotels=[];$tours=[];foreach($rows as$h){if(!is_array($h)||!($hid=hmd_id($h['id']??null)))continue;$hotels[$hid]=true;foreach((array)($h['tours']??[])as$t)if(is_array($t)){if(($tid=hmd_text($t['id']??$t['tourId']??'',220))!=='')$tours[$hid.'|'.$tid]=true;}}return['hotels'=>count($hotels),'tours'=>count($tours)];}
function hmd_tv_quota(string $home,string $lane):int{$dir=rtrim($home,'/').'/.anytour-match/provider-quotas';if(!is_dir($dir)&&!mkdir($dir,0700,true)&&!is_dir($dir))throw new RuntimeException('tv_quota_dir');$p=$dir.'/tourvisor-owner-extra-1971-20260918-v1.json';$f=fopen($p,'c+');if(!$f)throw new RuntimeException('tv_quota_open');try{if(!flock($f,LOCK_EX))throw new RuntimeException('tv_quota_lock');$raw=stream_get_contents($f);$j=$raw!==''?json_decode($raw,true):[];$used=(int)($j['used']??0);if($used>=HMD_TV_EXTRA_CAP)throw new RuntimeException('tv_extra_cap');$used++;$lanes=is_array($j['lanes']??null)?$j['lanes']:[];$lanes[$lane]=(int)($lanes[$lane]??0)+1;$j=['operation'=>HMD_OP,'owner_authorized_extra'=>HMD_TV_EXTRA_CAP,'used'=>$used,'lanes'=>$lanes,'updated_at'=>gmdate('c')];ftruncate($f,0);rewind($f);fwrite($f,hmd_json($j));fflush($f);if(function_exists('fsync'))fsync($f);return$used;}finally{flock($f,LOCK_UN);fclose($f);}}
function hmd_tv_used(string $home):int{$p=rtrim($home,'/').'/.anytour-match/provider-quotas/tourvisor-owner-extra-1971-20260918-v1.json';if(!is_file($p))return 0;$j=json_decode((string)file_get_contents($p),true);return is_array($j)?(int)($j['used']??0):HMD_TV_EXTRA_CAP;}
function hmd_tv_qs(array $p):string{$parts=[];foreach($p as$k=>$v){if($v===null||$v==='')continue;if(is_bool($v))$v=$v?'true':'false';foreach(is_array($v)?$v:[$v]as$x){if($x===null||$x==='')continue;$parts[]=rawurlencode((string)$k).'='.rawurlencode((string)$x);}}return implode('&',$parts);}
function hmd_tv_get(string $token,string $home,string $lane,string $path,array $params=[]):array{hmd_tv_quota($home,$lane);$url='https://api.tourvisor.ru/search/api/v1'.$path;$qs=hmd_tv_qs($params);if($qs!=='')$url.='?'.$qs;$ch=curl_init($url);$body='';curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>false,CURLOPT_CONNECTTIMEOUT=>10,CURLOPT_TIMEOUT=>60,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_SSL_VERIFYPEER=>true,CURLOPT_SSL_VERIFYHOST=>2,CURLOPT_HTTPHEADER=>['Authorization: Bearer '.$token,'Accept: application/json'],CURLOPT_WRITEFUNCTION=>static function($unused,string $chunk)use(&$body):int{$body.=$chunk;return strlen($body)>HMD_TV_BODY_LIMIT?0:strlen($chunk);}]);$ok=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$errno=curl_errno($ch);curl_close($ch);if($errno||$ok===false)throw new RuntimeException('tv_transport_error');if($status===429)throw new RuntimeException('tv_429');if($status<200||$status>=300)throw new RuntimeException('tv_http_'.$status);$j=json_decode($body,true);if(!is_array($j))throw new RuntimeException('tv_shape');return$j;}
function hmd_tv_wait(string $token,string $home,string $lane,int $sid):void{for($i=0;$i<20;$i++){sleep(2);$s=hmd_tv_get($token,$home,$lane,'/tours/search/'.$sid.'/status',['operatorStatus'=>false]);if(hmd_tv_complete($s))return;}throw new RuntimeException('tv_search_timeout');}
function hmd_tv_fetch(string $token,string $home,string $lane,int $sid):array{return hmd_tv_rows(hmd_tv_get($token,$home,$lane,'/tours/search/'.$sid,['limit'=>10000]));}
function hmd_tv_drain(string $token,string $home,string $lane,array $params):array{$start=hmd_tv_get($token,$home,$lane,'/tours/search',$params);$sid=hmd_tv_search_id($start);if(!$sid)throw new RuntimeException('tv_search_id');hmd_tv_wait($token,$home,$lane,$sid);$union=hmd_tv_merge([],hmd_tv_fetch($token,$home,$lane,$sid));$sig=hmd_tv_sig($union);$rounds=[['round'=>0]+$sig];for($r=1;$r<=HMD_TV_MAX_CONTINUE;$r++){$before=$sig;$c=hmd_tv_get($token,$home,$lane,'/tours/search/'.$sid.'/continue',[]);$req=hmd_request_count($c);if($req>0)hmd_tv_wait($token,$home,$lane,$sid);$union=hmd_tv_merge($union,hmd_tv_fetch($token,$home,$lane,$sid));$sig=hmd_tv_sig($union);$added=($sig['hotels']-$before['hotels'])+($sig['tours']-$before['tours']);$rounds[]=['round'=>$r,'request_count'=>$req,'added'=>$added]+$sig;if($req===0||$added===0)return['search_id'=>$sid,'rows'=>$union,'rounds'=>$rounds,'fully_drained'=>true];}throw new RuntimeException('tv_continue_cap');}
function hmd_tv_anex_operator(string $token,string $home,string $lane,int $dep,int $country):int{$rows=hmd_tv_rows(hmd_tv_get($token,$home,$lane,'/operators',['departureId'=>$dep,'countryId'=>$country]));$hits=[];foreach($rows as$r){if(!is_array($r))continue;$id=hmd_id($r['id']??null);$n=hmd_norm(hmd_text($r['name']??''));if(!$id)continue;if(in_array(str_replace(' ','',$n),['anex','anextour','анекс','анекстур'],true))$hits[$id]=true;}if(count($hits)!==1)throw new RuntimeException('tv_anex_operator');return(int)array_key_first($hits);}
function hmd_mode_nights(array $rows):int{$c=[];foreach($rows as$r){$n=(int)($r['nights']??0);if($n>0)$c[$n]=($c[$n]??0)+(int)($r['obs']??1);}if(!$c)return 7;arsort($c,SORT_NUMERIC);return(int)array_key_first($c);}
