<?php
declare(strict_types=1);
/** MATCH #1971: CURRENT read-only Andromeda catalog pending exact sweep using accepted stateKey->local-country anchors. */
const OP='hotel-match-andromeda-pending-exact-current-1971-20260916-v4';
const CORE=[1,2,4,6,8,9,10,16];
function jj($v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
function putx(string $p,$v):string{$raw=jj($v)."\n";$f=@fopen($p,'x');if(!$f)throw new RuntimeException('durable_create_failed');try{if(fwrite($f,$raw)!==strlen($raw))throw new RuntimeException('durable_write_failed');fflush($f);}finally{fclose($f);}if(file_get_contents($p)!==$raw)throw new RuntimeException('durable_readback_failed');return hash('sha256',$raw);}
function dbp(string $r):string{foreach([$r.'/data/db-v1.php',$r.'/v2/data/db-v1.php']as$p)if(is_file($p))return$p;throw new RuntimeException('db_bootstrap_missing');}
function qq(PDO$d,string$q,array$p=[]):array{$s=$d->prepare($q);$s->execute($p);return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}
function ev($raw):array{if(!is_string($raw)||trim($raw)==='')return[];try{$x=json_decode($raw,true,512,JSON_THROW_ON_ERROR);return is_array($x)?$x:[];}catch(Throwable){return[];}}
function box(array$e):array{return is_array($e['source']??null)?$e['source']:$e;}
function sv($v):?string{if(!is_scalar($v))return null;$s=trim((string)$v);return$s===''?null:$s;}
function fi(array$a,array$ks):?string{foreach($ks as$k)if(array_key_exists($k,$a)&&($v=sv($a[$k]))!==null)return$v;return null;}
function iid($v):?int{$s=sv($v);return$s!==null&&preg_match('/^[1-9][0-9]{0,14}$/D',$s)?(int)$s:null;}
function num($v):?float{if(!is_scalar($v)||!is_numeric((string)$v))return null;$x=(float)$v;return is_finite($x)?$x:null;}
function nm(string$s):string{$s=mb_strtolower($s,'UTF-8');$s=preg_replace('/\b(?:hotel|resort|spa)\b/iu',' ',$s)??$s;$s=preg_replace('/[^\pL\pN]+/u',' ',$s)??$s;return trim(preg_replace('/\s+/u',' ',$s)??$s);}
function forms(?string$s):array{if($s===null||trim($s)==='')return[];$a=[];$former=[];if(preg_match_all('/\((?:\s*(?:ex\.?|former(?:ly)?)\s*[:.-]?\s*)([^)]{2,180})\)/iu',$s,$m))foreach($m[1]as$x)$former[]=(string)$x;$cur=preg_replace('/\((?:\s*(?:ex\.?|former(?:ly)?)\s*[:.-]?\s*)[^)]{2,180}\)/iu',' ',$s)??$s;foreach(array_merge([$cur],$former)as$x){$n=nm((string)$x);if($n!=='')$a[$n]=1;}return array_keys($a);}
function km($a,$b,$c,$d):?float{foreach([$a,$b,$c,$d]as$x)if($x===null)return null;$r=6371.0088;$p1=deg2rad($a);$p2=deg2rad($c);$dp=deg2rad($c-$a);$dl=deg2rad($d-$b);$h=sin($dp/2)**2+cos($p1)*cos($p2)*sin($dl/2)**2;return 2*$r*asin(min(1,sqrt($h)));}
if(in_array('--self-test',$argv??[],true)){if(forms('Megasaray Resort Side (EX. Aska Side Hotel)')!==['megasaray side','aska side'])throw new RuntimeException('forms');if(nm('Royal BEACH Hotel & Spa 2')!=='royal beach 2')throw new RuntimeException('norm');echo"PASS\n";exit;}
$op=(string)getenv('OPERATION_ID');$sha=(string)getenv('MATCH_SOURCE_SHA');if($op!==OP||!preg_match('/^[0-9a-f]{40}$/D',$sha))throw new RuntimeException('operation_guard');$root=(string)realpath(getcwd());$base=rtrim((string)getenv('HOME'),'/').'/.anytoour-match/operations';if(!$root||basename($root)!=='anytoour.ru'||!is_dir($base))throw new RuntimeException('root_guard');$dir=$base.'/'.$op;if(!mkdir($dir,0700))throw new RuntimeException('operation_exists');putx($dir.'/reservation.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'reserved_before_db_access','read_only'=>true,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);
$db=null;try{require_once dbp($root);$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');
$cat=qq($db,'SELECT id,country_id,country_name,region_id,region_name,subregion_id,subregion_name,name,category,latitude,longitude FROM catalog_hotels WHERE is_active=1 AND country_id IN (1,2,4,6,8,9,10,16) ORDER BY country_id,id');$byId=[];$idx=[];foreach($cat as$h){$id=(int)$h['id'];$cid=(int)$h['country_id'];$byId[$id]=$h;foreach(forms((string)$h['name'])as$f)$idx[$cid][$f][$id]=1;}
$acc=qq($db,"SELECT supplier_namespace,external_hotel_id,local_hotel_id,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IS NOT NULL");$pend=qq($db,"SELECT supplier_namespace,external_hotel_id,evidence_json,evidence_sha256,catalog_sha256 FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='pending' AND local_hotel_id IS NULL ORDER BY external_hotel_id");$db->exec('ROLLBACK');
$stateCountries=[];$stateAnchors=[];$occupied=[];foreach($acc as$r){$local=(int)$r['local_hotel_id'];$occupied[$local][(string)$r['external_hotel_id']]=1;if(!isset($byId[$local]))continue;$s=box(ev($r['evidence_json']??null));$state=iid(fi($s,['stateKey','state_id','countryKey']));if(!$state)continue;$cid=(int)$byId[$local]['country_id'];$stateCountries[$state][$cid]=1;$stateAnchors[$state][$cid]=($stateAnchors[$state][$cid]??0)+1;}
$cross=[];$crossReport=[];foreach($stateCountries as$state=>$cs){$ids=array_keys($cs);sort($ids,SORT_NUMERIC);$cnts=$stateAnchors[$state]??[];$anchors=array_sum($cnts);$ok=count($ids)===1&&$anchors>=2;$cross[$state]=$ok?(int)$ids[0]:null;$crossReport[]=['supplier_state_key'=>(int)$state,'local_country_candidates'=>$ids,'accepted_anchor_count'=>$anchors,'accepted_anchor_counts'=>$cnts,'mapped_local_country_id'=>$cross[$state],'usable'=>$ok];}usort($crossReport,fn($a,$b)=>$a['supplier_state_key']<=>$b['supplier_state_key']);
$out=[];$prepared=[];$counts=[];$states=[];foreach($pend as$r){$e=ev($r['evidence_json']??null);$s=box($e);$state=iid(fi($s,['stateKey','state_id','countryKey']));$name=fi($s,['name','hotelName','title']);$row=['supplier_namespace'=>'andromeda_catalog','external_hotel_id'=>(string)$r['external_hotel_id'],'supplier_state_key'=>$state,'local_country_id'=>$state!==null?($cross[$state]??null):null,'source_name'=>$name,'source_forms'=>forms($name),'candidate_local_id'=>null,'candidate_local_name'=>null,'route'=>null,'distance_km'=>null,'same_provider_occupancy'=>[],'evidence_sha256'=>$r['evidence_sha256']??null,'catalog_sha256'=>$r['catalog_sha256']??null];$states[$state??0]=($states[$state??0]??0)+1;$cid=$row['local_country_id'];if($state===null||$cid===null){$row['route']='hold_state_crosswalk_missing_or_ambiguous';$out[]=$row;$counts[$row['route']]=($counts[$row['route']]??0)+1;continue;}if($name===null||$row['source_forms']===[]){$row['route']='hold_source_name_missing';$out[]=$row;$counts[$row['route']]=($counts[$row['route']]??0)+1;continue;}$cand=[];foreach($row['source_forms']as$f)foreach(array_keys($idx[$cid][$f]??[])as$id)$cand[(int)$id]=1;$ids=array_keys($cand);sort($ids,SORT_NUMERIC);$row['countrywide_exact_candidate_ids']=$ids;if(count($ids)!==1){$row['route']=$ids?'hold_countrywide_exact_ambiguous':'hold_no_countrywide_exact';$out[]=$row;$counts[$row['route']]=($counts[$row['route']]??0)+1;continue;}$local=(int)$ids[0];$h=$byId[$local];$row['candidate_local_id']=$local;$row['candidate_local_name']=$h['name'];$occ=array_keys($occupied[$local]??[]);sort($occ,SORT_STRING);$row['same_provider_occupancy']=$occ;if($occ!==[]&&!in_array((string)$r['external_hotel_id'],$occ,true)){$row['route']='hold_same_provider_occupied';$out[]=$row;$counts[$row['route']]=($counts[$row['route']]??0)+1;continue;}$slat=num(fi($s,['latitude','lat','hotelLatitude']));$slon=num(fi($s,['longitude','lon','lng','hotelLongitude']));$d=km($slat,$slon,num($h['latitude']),num($h['longitude']));$row['source_coordinates']=['latitude'=>$slat,'longitude'=>$slon];$row['local_coordinates']=['latitude'=>num($h['latitude']),'longitude'=>num($h['longitude'])];$row['distance_km']=$d===null?null:round($d,3);if($d!==null&&$d>5){$row['route']='hold_coordinate_gt5km';$out[]=$row;$counts[$row['route']]=($counts[$row['route']]??0)+1;continue;}$row['route']='guard_passed_prepared';$prepared[]=$row;$out[]=$row;$counts[$row['route']]=($counts[$row['route']]??0)+1;}
ksort($counts);ksort($states);$res=['schema'=>'hotel-match-andromeda-pending-exact-current/4','operation_id'=>$op,'source_sha'=>$sha,'state'=>'completed_read_only','server_current'=>true,'pending_examined'=>count($pend),'accepted_anchor_rows'=>count($acc),'supplier_state_counts'=>$states,'state_crosswalk'=>$crossReport,'route_counts'=>$counts,'guard_passed_prepared_count'=>count($prepared),'guard_passed_prepared'=>$prepared,'rows'=>$out,'normalization'=>'exact current/former names; generic HOTEL/RESORT/SPA removed; country derived only from CURRENT accepted andromeda_catalog anchors; countrywide unique; same-provider occupancy and >5km hold','safe_to_write_now'=>false,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'booking_calls'=>0,'lead_calls'=>0,'no_replay'=>true];$dig=putx($dir.'/result.json',$res);putx($dir.'/receipt.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'completed_read_only','result_sha256'=>$dig,'readback_verified'=>hash('sha256',(string)file_get_contents($dir.'/result.json'))===$dig,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);echo jj(['state'=>'completed_read_only','pending_examined'=>count($pend),'state_crosswalk'=>$crossReport,'route_counts'=>$counts,'guard_passed_prepared_count'=>count($prepared)])."\n";
}catch(Throwable$e){try{if($db instanceof PDO&&$db->inTransaction())$db->rollBack();}catch(Throwable){}$f=['operation_id'=>$op,'source_sha'=>$sha,'state'=>'failed_read_only','error_class'=>get_class($e),'error_message'=>$e->getMessage(),'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true];$dig=putx($dir.'/failure.json',$f);putx($dir.'/receipt.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'failed_read_only','failure_sha256'=>$dig,'readback_verified'=>true,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);fwrite(STDERR,"V4_FAILED ".$e->getMessage()."\n");exit(2);}
