<?php
declare(strict_types=1);

const DPA_OP='hotel-match-december81154-pending-audit-1971-20260920-v1';
const DPA_INPUT_SHA='dffa9cbfd64c8d14104cfe28cffeb0b08acb3aeca17b12ee07f48ad860982d67';
const DPA_CATALOG_SHA='05a13bd6b8dd9821e630dc7cbe9ef7e55de70405e4eb37fad413bba36592c1ba';
const DPA_LOCAL=81154;
const DPA_ANEX=35406;
const DPA_SAMO='2000073578';
const DPA_COUNTRY=16;
function dpa_need(bool $b,string $s):void{if(!$b)throw new RuntimeException($s);}
function dpa_json(array $a):string{return json_encode($a,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";}
function dpa_save(string $p,array $a):string{$b=dpa_json($a);$f=fopen($p,'xb');dpa_need(is_resource($f),'exclusive_file');try{dpa_need(fwrite($f,$b)===strlen($b)&&fflush($f),'file_write');if(function_exists('fsync'))dpa_need(fsync($f),'file_sync');}finally{fclose($f);}dpa_need(file_get_contents($p)===$b,'file_readback');return hash('sha256',$b);}
function dpa_load(string $p,?string $sha=null):array{if($sha!==null)dpa_need(hash_file('sha256',$p)===$sha,'input_hash');$a=json_decode((string)file_get_contents($p),true,128,JSON_THROW_ON_ERROR);dpa_need(is_array($a),'input_shape');return$a;}
function dpa_norm(string $s):string{$s=function_exists('mb_strtolower')?mb_strtolower(trim($s),'UTF-8'):strtolower(trim($s));return trim(preg_replace('/[^\p{L}\p{N}]+/u',' ',str_replace('ё','е',$s))??'');}
function dpa_tokens(string $s):array{$out=[];foreach(explode(' ',dpa_norm($s))as$t)if($t!==''&&!in_array($t,['hotel','hotels','отель','resort','spa'],true))$out[$t]=true;return array_keys($out);}
function dpa_has_token(string $name,string $token):bool{return in_array(dpa_norm($token),dpa_tokens($name),true);}
function dpa_place(array $source,array $target):bool{$labels=[];foreach(['town','townLName']as$k){$v=dpa_norm((string)($source[$k]??''));if($v!=='')$labels[$v]=true;}foreach(['region_name','subregion_name']as$k){$v=dpa_norm((string)($target[$k]??''));if($v!==''&&isset($labels[$v]))return true;}return false;}
function dpa_rows(PDO $db,string $sql,array $p=[],int $cap=50000):array{$q=$db->prepare($sql);$q->execute(array_values($p));$r=$q->fetchAll(PDO::FETCH_ASSOC);dpa_need(count($r)<=$cap,'db_row_cap');return$r;}
function dpa_hash(array $a):string{return hash('sha256',json_encode($a,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));}
if(($argv[1]??'')==='--self-test'){$s=['town'=>'Нячанг','townLName'=>'Nha Trang','star'=>'4'];$h=['name'=>'DECEMBER HOTEL NHA TRANG','region_name'=>'Нячанг','subregion_name'=>'Нячанг - центр','category'=>4];dpa_need(dpa_has_token($h['name'],'December'),'token');dpa_need(dpa_place($s,$h),'place');$h['region_name']='Ханой';dpa_need(!dpa_place($s,$h),'place_negative');echo"MATCH_DECEMBER81154_PENDING_AUDIT_SELFTEST_OK 3\n";exit(0);}

dpa_need(PHP_SAPI==='cli'&&(string)getenv('MATCH_OPERATION_ID')===DPA_OP,'operation_guard');$dir=rtrim((string)getenv('HOME'),'/').'/.anytoour-match/operations/'.DPA_OP;dpa_need(realpath((string)getenv('MATCH_OPERATION_DIR'))===$dir,'operation_directory');$sha=(string)getenv('MATCH_SOURCE_SHA');dpa_need(preg_match('/^[a-f0-9]{40}$/D',$sha)===1,'source_sha');$reservation=dpa_load($dir.'/reservation.json');dpa_need(($reservation['operation_id']??'')===DPA_OP&&($reservation['source_sha']??'')===$sha&&($reservation['state']??'')==='reserved_before_db_read','reservation_guard');
$base=['operation_id'=>DPA_OP,'source_sha'=>$sha,'local_hotel_id'=>DPA_LOCAL,'anex_native_id'=>DPA_ANEX,'samo_hotel_id'=>DPA_SAMO,'supplier_calls'=>0,'provider_calls'=>0,'tourvisor_calls'=>0,'samo_calls'=>0,'andromeda_calls'=>0,'direct_anex_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'safe_to_write_now'=>false,'no_replay'=>true];$db=null;
try{
 dpa_save($dir.'/execution-reservation.json',$base+['state'=>'started_before_db_read']);$input=dpa_load($dir.'/input/previous-result.json',DPA_INPUT_SHA);$catalog=dpa_load($dir.'/input/vietnam-catalog.json',DPA_CATALOG_SHA);dpa_need(($input['state']??'')==='completed_current_hold_no_http'&&(int)($input['local_hotel_id']??0)===DPA_LOCAL&&(int)($input['anex_native_id']??0)===DPA_ANEX&&(string)($input['samo_hotel_id']??'')===DPA_SAMO,'prior_result_scope');$srcs=array_values(array_filter($catalog['HOTELS']??[],static fn($h)=>is_array($h)&&(string)($h['id']??'')===DPA_SAMO));dpa_need(count($srcs)===1,'catalog_source_unique');$source=$srcs[0];dpa_need((int)($source['stateKey']??0)===126&&(string)($source['star']??'')==='4','catalog_source_fact');
 require_once dirname(__DIR__,2).'/app/integrations/anex-search-mapping-registry.php';$root=realpath(getcwd());dpa_need(is_string($root)&&basename($root)==='anytoour.ru','root_guard');require_once(is_file($root.'/data/db-v1.php')?$root.'/data/db-v1.php':$root.'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);foreach(['andromeda_hotel_identities','anex_hotel_search_mappings','anex_hotel_decisions','anex_review_pair_exclusions','catalog_hotels']as$t){$e=dpa_rows($db,'SELECT ENGINE FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?',[$t]);dpa_need(count($e)===1&&strtoupper((string)$e[0]['ENGINE'])==='INNODB','table_engine');}$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');
 $clock=dpa_rows($db,'SELECT NOW() AS database_now,UTC_TIMESTAMP() AS utc_now,@@session.time_zone AS session_time_zone')[0];$target=dpa_rows($db,'SELECT * FROM catalog_hotels WHERE id=?',[DPA_LOCAL]);$sourceRows=dpa_rows($db,"SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=? ORDER BY created_at",[DPA_SAMO]);$targetRows=dpa_rows($db,'SELECT * FROM andromeda_hotel_identities WHERE local_hotel_id=? ORDER BY supplier_namespace,external_hotel_id',[DPA_LOCAL]);$manual=dpa_rows($db,'SELECT * FROM anex_hotel_decisions WHERE anex_hotel_id=? OR catalog_hotel_id=? ORDER BY id',[DPA_ANEX,DPA_LOCAL]);$excluded=dpa_rows($db,'SELECT * FROM anex_review_pair_exclusions WHERE anex_hotel_id=? OR catalog_hotel_id=? ORDER BY id',[DPA_ANEX,DPA_LOCAL]);$anexRows=dpa_rows($db,'SELECT * FROM anex_hotel_search_mappings WHERE anex_hotel_id=? OR catalog_hotel_id=? ORDER BY anex_hotel_id,catalog_hotel_id',[DPA_ANEX,DPA_LOCAL]);$anex=AnyTourAnexSearchMappingRegistry::fromPdo($db);$resolved=$anex->resolve('anex_online',(string)DPA_ANEX,'preview');
 $countryRows=dpa_rows($db,"SELECT * FROM catalog_hotels WHERE country_id=? AND is_active=1 AND (LOWER(name) LIKE '%december%' OR normalized_name LIKE '%december%') ORDER BY id",[DPA_COUNTRY],5000);$retrieved=[];foreach($countryRows as$h)if(dpa_has_token((string)($h['name']??''),'december')||dpa_has_token((string)($h['normalized_name']??''),'december'))$retrieved[]=$h;
 $db->rollBack();$db=null;$reasons=[];$pending=null;if(count($sourceRows)!==1)$reasons[]='source_occupancy_not_exactly_one';else{$pending=$sourceRows[0];if(($pending['decision_status']??'')!=='pending'||$pending['local_hotel_id']!==null)$reasons[]='source_not_unassigned_pending';$old=json_decode((string)($pending['evidence_json']??''),true);if(!is_array($old)||($old['source']['id']??null)!==2000073578||($old['reason']??'')!=='no_unique_name')$reasons[]='historical_pending_evidence_shape_changed';}
 if(count($target)!==1||(int)($target[0]['is_active']??0)!==1||(int)($target[0]['country_id']??0)!==DPA_COUNTRY)$reasons[]='target_inactive_or_country_conflict';$t=count($target)===1?$target[0]:[];if($targetRows!==[])$reasons[]='target_identity_occupied';if($resolved!==DPA_LOCAL)$reasons[]='anex_anchor_not_current_target';if($manual!==[])$reasons[]='manual_decision_present';if($excluded!==[])$reasons[]='pair_exclusion_present';if(count($retrieved)!==1||(int)($retrieved[0]['id']??0)!==DPA_LOCAL)$reasons[]='december_token_not_unique_target';if((int)($t['category']??0)!==4||(int)($source['star']??0)!==4)$reasons[]='actual_star_label_conflict';if(!dpa_place($source,$t))$reasons[]='direct_place_confirmation_missing';if(!dpa_has_token((string)($t['name']??''),'december'))$reasons[]='source_token_missing_from_target';
 $safe=$reasons===[];$result=$base+['state'=>'completed_read_only','clock'=>$clock,'source_catalog'=>$source,'source_identity_rows'=>$sourceRows,'source_identity_row_sha256'=>$pending?dpa_hash($pending):null,'target_rows'=>$target,'target_identity_rows'=>$targetRows,'current_anex_resolution'=>$resolved,'current_anex_rows'=>$anexRows,'current_manual_rows'=>$manual,'current_exclusion_rows'=>$excluded,'retrieval_token'=>'december','country_candidate_rows'=>$countryRows,'retrieved_token_candidates'=>$retrieved,'direct_place_confirmed'=>dpa_place($source,$t),'actual_star_agreement'=>(int)($t['category']??0)===4&&(int)($source['star']??0)===4,'safe_to_accept_pending_now'=>$safe,'acceptance_reasons'=>$reasons,'safe_to_write_now'=>false];
}catch(Throwable$e){if($db instanceof PDO&&$db->inTransaction())$db->rollBack();$reason=preg_match('/^[a-z0-9_]+$/D',$e->getMessage())?$e->getMessage():'database_or_runtime_error';$result=$base+['state'=>'failed_no_replay','reason'=>$reason,'error_class'=>get_class($e),'safe_to_accept_pending_now'=>false,'safe_to_write_now'=>false];}
$hash=dpa_save($dir.'/result.json',$result);dpa_save($dir.'/receipt.json',['operation_id'=>DPA_OP,'source_sha'=>$sha,'state'=>$result['state'],'result_sha256'=>$hash,'readback_verified'=>hash_file('sha256',$dir.'/result.json')===$hash,'supplier_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true]);echo dpa_json(['state'=>$result['state'],'safe_to_accept_pending_now'=>$result['safe_to_accept_pending_now']??false,'acceptance_reasons'=>$result['acceptance_reasons']??null,'retrieved_token_candidates'=>array_map(static fn($h)=>['id'=>$h['id']??null,'name'=>$h['name']??null,'region_name'=>$h['region_name']??null,'subregion_name'=>$h['subregion_name']??null,'category'=>$h['category']??null],$result['retrieved_token_candidates']??[]),'result_sha256'=>$hash]);exit($result['state']==='completed_read_only'?0:1);
