<?php
declare(strict_types=1);
if (!defined('FC_LIBRARY_ONLY')) define('FC_LIBRARY_ONLY', true);
require_once __DIR__ . '/hotel_match_provider_name_bridge_review.php';

const HMPNBA_OPERATION = 'hotel-match-provider-name-bridge-accept-2333-20260913-v1';

function hmpnba_accept(PDO $db,string $operation=HMPNBA_OPERATION): array {
    if($operation!==HMPNBA_OPERATION)throw new RuntimeException('operation_scope');
    $db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
    $before=fc_coverage($db);$written=[];$committed=false;
    try{
        $db->exec('SET SESSION innodb_lock_wait_timeout=20');$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->beginTransaction();
        [$hotels,$names,$strict,$broad,$places,$scope]=mbr_catalog($db);$shaCountry=fc_sha_countries($db);
        $latest=[];$counts=[];$lastSeen=[];foreach($db->query("SELECT * FROM andromeda_search_hotel_observations WHERE supplier_namespace='andromeda_catalog' ORDER BY observed_at_utc DESC,external_hotel_id FOR UPDATE")->fetchAll(PDO::FETCH_ASSOC) as $o){$id=(string)$o['external_hotel_id'];$counts[$id]=($counts[$id]??0)+1;if(!isset($latest[$id])){$latest[$id]=$o;$lastSeen[$id]=$o['observed_at_utc']??null;}}
        $anex=[];$mappingRows=$db->query("SELECT m.anex_hotel_id,m.catalog_hotel_id,h.api_name,h.xml_name,h.xml_alternate_name FROM anex_hotel_search_mappings m LEFT JOIN anex_hotels h ON h.anex_hotel_id=m.anex_hotel_id WHERE m.enabled=1 ORDER BY m.anex_hotel_id FOR UPDATE")->fetchAll(PDO::FETCH_ASSOC);
        $aobs=[];foreach($db->query("SELECT * FROM anex_search_hotel_observations ORDER BY search_count DESC,last_seen_utc DESC,anex_hotel_id FOR UPDATE")->fetchAll(PDO::FETCH_ASSOC) as $o){$id=(int)$o['anex_hotel_id'];if(!isset($aobs[$id]))$aobs[$id]=$o;}
        foreach($mappingRows as $r){$aid=(int)$r['anex_hotel_id'];$local=(int)$r['catalog_hotel_id'];if(!isset($hotels[$local]))continue;$country=(int)$hotels[$local]['country_id'];if(!isset(MBR_CORE8[$country]))continue;$src=array_values(array_unique(array_filter([(string)($r['api_name']??''),(string)($r['xml_name']??''),(string)($r['xml_alternate_name']??''),(string)($aobs[$aid]['hotel_name']??'')],static fn($v)=>trim($v)!=='')));foreach($src as $name){$key=hmpnb_key($name);if($key===''||count(explode(' ',$key))<2)continue;$anex[$country][$key][$local][$aid][]=$name;}}
        $pending=$db->query("SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='pending' AND local_hotel_id IS NULL ORDER BY external_hotel_id FOR UPDATE")->fetchAll(PDO::FETCH_ASSOC);
        $candidates=[];
        foreach($pending as $r){$external=(string)$r['external_hotel_id'];$o=$latest[$external]??null;$country=(int)($o['country_id']??0);if(!isset(MBR_CORE8[$country]))$country=(int)($shaCountry[$r['catalog_sha256']]??0);if(!isset(MBR_CORE8[$country]))continue;[$prior,$source,$sourceNames,$sourcePlaces,$sourceCategory,$coordSource]=mlp_source_context($r,$o);$locals=[];$matches=[];foreach($sourceNames as $sourceName){$key=hmpnb_key((string)$sourceName);if($key===''||count(explode(' ',$key))<2)continue;foreach($anex[$country][$key]??[] as $local=>$byAnex){foreach($byAnex as $aid=>$anexNames){foreach($anexNames as $anexName){if(hmpnb_critical((string)$sourceName)!==hmpnb_critical((string)$anexName))continue;$locals[(int)$local]=1;$matches[]=['source_name'=>(string)$sourceName,'anex_hotel_id'=>(int)$aid,'anex_name'=>(string)$anexName,'local_hotel_id'=>(int)$local,'identity_key'=>$key];}}}}if(!$matches||count($locals)!==1)continue;$local=(int)array_key_first($locals);$target=$hotels[$local];$targetCat=$target['category']===null?null:(int)$target['category'];if($sourceCategory!==null&&$targetCat!==null&&$sourceCategory!==$targetCat)continue;$guard=mbr_target_guard($coordSource,$target);if($guard['coordinate_conflict'])continue;$candidates[]=['row'=>$r,'external_id'=>$external,'country_id'=>$country,'local'=>$local,'source_names'=>$sourceNames,'source_places'=>$sourcePlaces,'source_category'=>$sourceCategory,'target'=>mbr_row_target($target),'guard'=>$guard,'matches'=>$matches,'observation_count'=>(int)($counts[$external]??0),'last_seen_utc'=>$lastSeen[$external]??null];}
        if(count($candidates)>10)throw new RuntimeException('candidate_scope_limit');
        $update=$db->prepare("UPDATE andromeda_hotel_identities SET local_hotel_id=?,decision_status='accepted',evidence_sha256=?,evidence_json=? WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=? AND decision_status='pending' AND local_hotel_id IS NULL AND evidence_sha256 <=> ?");
        foreach($candidates as $c){$prior=fc_evidence($c['row']['evidence_json']??'');$evidence=['prior_evidence'=>$prior,'promotion'=>['operation_id'=>$operation,'lane'=>'MATCH','rule'=>'exact_provider_provider_identity_unique_accepted_anex_local_category_guard','country_id'=>$c['country_id'],'target'=>$c['local'],'source_names'=>$c['source_names'],'source_places'=>$c['source_places'],'source_category'=>$c['source_category'],'target_record'=>$c['target'],'guard'=>$c['guard'],'matches'=>$c['matches'],'observation_count'=>$c['observation_count'],'last_seen_utc'=>$c['last_seen_utc'],'server_current'=>true]];$json=fc_json($evidence);$hash=hash('sha256',$json);$update->execute([$c['local'],$hash,$json,$c['external_id'],$c['row']['evidence_sha256']]);if($update->rowCount()!==1)throw new RuntimeException('concurrent_change');$written[]=['external_id'=>$c['external_id'],'local_hotel_id'=>$c['local'],'evidence_sha256'=>$hash,'matches'=>$c['matches']];}
        $db->commit();$committed=true;
        $q=$db->prepare("SELECT local_hotel_id,decision_status,evidence_sha256 FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=?");foreach($written as $w){$q->execute([$w['external_id']]);$a=$q->fetch(PDO::FETCH_ASSOC);if(!$a||(int)$a['local_hotel_id']!==(int)$w['local_hotel_id']||(string)$a['decision_status']!=='accepted'||!hash_equals((string)$w['evidence_sha256'],(string)$a['evidence_sha256']))throw new RuntimeException('post_commit_readback_failed');}
        return ['status'=>'completed','operation_id'=>$operation,'database_writes'=>count($written),'committed'=>true,'supplier_calls'=>0,'historical_operations_replayed'=>false,'catalog_scope'=>$scope,'coverage_before'=>$before,'coverage_after'=>fc_coverage($db),'accepted'=>$written,'readback_verified'=>true,'guards'=>['current_db_same_transaction'=>true,'pending_only'=>true,'unique_accepted_anex_local'=>true,'provider_provider_exact_identity'=>true,'critical_qualifiers_preserved'=>true,'category_guard'=>true,'coordinate_conflict_auto_block_m'=>5000,'max_candidates'=>10]];
    }catch(Throwable $e){if($db->inTransaction())$db->rollBack();return ['status'=>'failed','operation_id'=>$operation,'database_writes'=>$committed?count($written):0,'committed'=>$committed,'supplier_calls'=>0,'reason'=>$e->getMessage(),'readback_verified'=>false];}
}
