<?php
declare(strict_types=1);
/** MATCH-only strict alias+geo resolver for retained official public operator evidence. READ ONLY. */
const PAG_OP='hotel-match-public-operator-alias-geo-current-1971-20260917-v1';
const PAG_MANIFEST=[
 ['operator_342','549','2000034121','Delphin Palace','Лара'],
 ['operator_342','651','2000098416','Fifty Five Suite','Мармарис'],
 ['operator_342','655','190031','Ramada Plaza by Wyndham Antalya','Анталия'],
 ['operator_342','743','3060','Labranda Mares Hotel','Ичмелер'],
 ['operator_342','12135','175606','Rixos Sharm El Sheikh (Nabq Bay)','Набк Бэй'],
 ['operator_342','12281','2000039701','Ivy Cyrene Sharm (ex. Cyrene Sharm)','Рас-Насрани'],
 ['operator_342','17163','2000023232','The Meretto Hotel Istanbul Old City','Султанахмет'],
 ['operator_342','18273','2000062084','Raimond Hotel','Кумкапы'],
 ['operator_342','19652','67775','Grand Emin Hotel','Йеникапы'],
 ['operator_342','21978','650','Conrad Istanbul Bosphorus','Бешикташ'],
 ['operator_342','23547','182522','Best Nobel Hotel','Сиркеджи'],
 ['operator_342','24278','2000072249','Badawia Sharm Resort','Шарм-эль-Шейх'],
 ['operator_342','24891','2000057636','Bodrium Otel & You Spa','Бодрум'],
 ['operator_342','24954','2000061716','Le Meridien Bodrum Beach Resort','Бодрум'],
 ['operator_342','25728','2000052591','Arabia Azur Hurgada','Хургада'],
 ['operator_342','27835','2000073592','Taxim Town Hotel','Таксим'],
 ['operator_342','28164','2000071512','Golden Gate','Топкапы'],
 ['operator_342','32987','2000086129','The Norm Collection Door','Торба'],
 ['operator_342','36672','2000034136','Green Maxx Hotel','Кадрие'],
 ['operator_315','19155','2000043232',"Domina Coral Bay King's Lake",'Шейх Коаст'],
 ['operator_315','69721','175606','Rixos Sharm El Sheikh (Adult Only 18+)','Набк'],
 ['operator_315','780677','2000062084','Raimond','Кумкапы'],
];
function pag_req(bool $ok,string $why):void{if(!$ok)throw new RuntimeException($why);}
function pag_json(array $x):string{return json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";}
function pag_write(string $p,array $x):string{$raw=pag_json($x);$f=@fopen($p,'x+b');pag_req(is_resource($f),'exclusive_output');try{pag_req(fwrite($f,$raw)===strlen($raw)&&fflush($f),'output_write');if(function_exists('fsync'))pag_req(fsync($f),'output_sync');rewind($f);pag_req(stream_get_contents($f)===$raw,'output_readback');}finally{fclose($f);}return hash('sha256',$raw);}
function pag_read(string $p,int $max=65536):array{pag_req(is_file($p)&&!is_link($p)&&realpath($p)===$p,'input_path');$raw=file_get_contents($p);pag_req(is_string($raw)&&strlen($raw)<=$max,'input_size');$x=json_decode($raw,true,64,JSON_THROW_ON_ERROR);pag_req(is_array($x),'input_shape');return$x;}
function pag_q(PDO $db,string $sql,array $args=[]):array{pag_req(preg_match('/^(?:SELECT|SHOW)\b/i',$sql)===1,'select_only');$s=$db->prepare($sql);$s->execute(array_values($args));$r=$s->fetchAll(PDO::FETCH_ASSOC);pag_req(count($r)<100000,'query_budget');return$r;}
function pag_norm(string $s):string{$s=trim(mb_strtolower($s,'UTF-8'));$s=str_replace('ё','е',$s);$s=preg_replace('/[^\p{L}\p{N}]+/u',' ',$s)??$s;$s=preg_replace('/\s+/u',' ',$s)??$s;return trim($s);}
function pag_name_forms(string $s):array{$f=[pag_norm($s)];$cur=preg_replace('/\s*\((?:ex|ех)\.?[^)]*\)\s*$/iu','',$s);if(is_string($cur)&&trim($cur)!==trim($s))$f[]=pag_norm($cur);return array_values(array_unique(array_filter($f,fn($x)=>$x!=='')));}
function pag_bridge(array $e):?array{$bs=$e['provider_bridges']??null;if(!is_array($bs)||!isset($bs[0])||!is_array($bs[0]))return null;$b=$bs[0];$aid=(string)($b['andromeda_hotel_id']??'');$country=(int)($b['country_id']??0);$name=trim((string)($b['hotel_name']??''));return($aid!==''&&ctype_digit($aid)&&$country>0&&$name!=='')?['andromeda_id'=>$aid,'country_id'=>$country,'hotel_name'=>$name]:null;}
function pag_add(array &$idx,string $name,int $local,string $kind,string $ref):void{foreach(pag_name_forms($name) as$n){$idx[$n][$local][$kind][$ref]=true;}}
if(in_array('--self-test',$argv??[],true)){pag_req(count(PAG_MANIFEST)===22,'manifest_count');$k=[];foreach(PAG_MANIFEST as$r){pag_req(count($r)===5&&in_array($r[0],['operator_315','operator_342'],true)&&ctype_digit($r[1])&&ctype_digit($r[2]),'manifest_row');$z=$r[0].':'.$r[1];pag_req(!isset($k[$z]),'manifest_duplicate');$k[$z]=1;}pag_req(count(pag_name_forms('Ivy Cyrene Sharm (ex. Cyrene Sharm)'))===2,'former_form');echo "PASS\n";exit;}
function pag_main():void{
 pag_req(PHP_SAPI==='cli'&&getenv('MATCH_OPERATION_ID')===PAG_OP,'operation_guard');$sha=(string)getenv('MATCH_SOURCE_SHA');pag_req(preg_match('/^[a-f0-9]{40}$/D',$sha)===1,'source_guard');$dir=(string)getenv('HOME').'/.anytoour-match/operations/'.PAG_OP;$reservation=pag_read($dir.'/reservation.json');pag_req(($reservation['operation_id']??'')===PAG_OP&&($reservation['source_sha']??'')===$sha&&($reservation['state']??'')==='reserved_before_db_access','reservation_guard');
 $out=['operation_id'=>PAG_OP,'source_sha'=>$sha,'state'=>'failed_no_replay','manifest_count'=>count(PAG_MANIFEST),'strict_candidates'=>[],'holds'=>[],'already_resolved'=>[],'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'samo_andromeda_calls'=>0,'booking_calls'=>0,'lead_calls'=>0,'no_replay'=>true,'safe_to_write_now'=>false];$db=null;$phase='bootstrap';ob_start();try{
  $root=realpath(getcwd());pag_req(is_string($root)&&basename($root)==='anytoour.ru','root_guard');$bp=$root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');pag_req(realpath($bp)===$bp&&!is_link($bp),'bootstrap_path');require_once$bp;$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');$phase='schema';
  $tables=[];foreach(pag_q($db,"SELECT TABLE_NAME FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME IN ('hotel_aliases','catalog_hotels','anex_hotel_search_mappings','anex_search_hotel_observations','andromeda_hotel_identities')")as$r)$tables[(string)$r['TABLE_NAME']]=true;foreach(['hotel_aliases','catalog_hotels','anex_hotel_search_mappings','anex_search_hotel_observations','andromeda_hotel_identities']as$t)pag_req(isset($tables[$t]),'missing_'.$t);
  $phase='current_sources';$pending=[];$acceptedByNsLocal=[];$acceptedAuthority=[];$acceptedRows=pag_q($db,"SELECT supplier_namespace,external_hotel_id,local_hotel_id,decision_status,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace IN ('operator_315','operator_342','andromeda_catalog') AND (decision_status='pending' OR (decision_status='accepted' AND local_hotel_id IS NOT NULL))");foreach($acceptedRows as$r){$ns=(string)$r['supplier_namespace'];$ext=(string)$r['external_hotel_id'];$status=(string)$r['decision_status'];$local=$r['local_hotel_id']===null?null:(int)$r['local_hotel_id'];$e=json_decode((string)$r['evidence_json'],true);if(!is_array($e))$e=[];$b=pag_bridge($e);if($status==='pending'&&$local===null&&in_array($ns,['operator_315','operator_342'],true))$pending[$ns.':'.$ext]=['bridge'=>$b,'evidence'=>$e];if($status==='accepted'&&$local!==null){$acceptedByNsLocal[$ns][$local][]=$ext;if($ns==='andromeda_catalog'&&$b)$acceptedAuthority[$b['andromeda_id']]=['local_id'=>$local,'country_id'=>$b['country_id'],'external_id'=>$ext];}}
  $aliasIdx=[];$catalog=[];foreach(pag_q($db,"SELECT id,country_id,name,normalized_name,region_name,subregion_name,is_active FROM catalog_hotels WHERE is_active=1")as$h){$id=(int)$h['id'];$catalog[$id]=$h;pag_add($aliasIdx,(string)$h['name'],$id,'catalog_name','catalog:'.$id);}
  foreach(pag_q($db,"SELECT a.hotel_id,a.alias,a.normalized_alias,a.source FROM hotel_aliases a JOIN catalog_hotels h ON h.id=a.hotel_id AND h.is_active=1")as$a)pag_add($aliasIdx,(string)$a['alias'],(int)$a['hotel_id'],'hotel_alias',(string)$a['source']);
  foreach(pag_q($db,"SELECT m.anex_hotel_id,m.catalog_hotel_id,o.hotel_name FROM anex_hotel_search_mappings m JOIN anex_search_hotel_observations o ON o.anex_hotel_id=m.anex_hotel_id JOIN catalog_hotels h ON h.id=m.catalog_hotel_id AND h.is_active=1 WHERE m.enabled=1")as$a)pag_add($aliasIdx,(string)$a['hotel_name'],(int)$a['catalog_hotel_id'],'accepted_anex_observation','anex:'.(string)$a['anex_hotel_id']);
  foreach(pag_q($db,"SELECT supplier_namespace,external_hotel_id,local_hotel_id,evidence_json FROM andromeda_hotel_identities WHERE decision_status='accepted' AND local_hotel_id IS NOT NULL")as$a){$e=json_decode((string)$a['evidence_json'],true);if(!is_array($e))continue;$bs=$e['provider_bridges']??[];if(!is_array($bs))continue;foreach($bs as$b){if(!is_array($b))continue;$name=trim((string)($b['hotel_name']??''));if($name!=='')pag_add($aliasIdx,$name,(int)$a['local_hotel_id'],'accepted_identity_name',(string)$a['supplier_namespace'].':'.(string)$a['external_hotel_id']);}}
  $phase='resolve';$reasonCounts=[];foreach(PAG_MANIFEST as[$ns,$ext,$aidExpected,$publicName,$publicGeo]){$key=$ns.':'.$ext;$p=$pending[$key]??null;if(!$p){$out['already_resolved'][]=['supplier_namespace'=>$ns,'external_hotel_id'=>$ext,'andromeda_hotel_id'=>$aidExpected,'reason'=>'not_current_pending'];continue;}$reasons=[];$b=$p['bridge'];if(!$b){$reasons[]='current_bridge_missing';$country=0;$currentName='';$aid='';}else{$country=(int)$b['country_id'];$currentName=(string)$b['hotel_name'];$aid=(string)$b['andromeda_id'];if($aid!==$aidExpected)$reasons[]='andromeda_id_changed';if(!in_array(pag_norm($currentName),pag_name_forms($publicName),true))$reasons[]='current_source_name_changed';}
    $locals=[];$prov=[];foreach(pag_name_forms($publicName)as$form){foreach($aliasIdx[$form]??[]as$lid=>$kinds){$h=$catalog[(int)$lid]??null;if(!$h||(int)$h['country_id']!==$country)continue;$locals[(int)$lid]=true;foreach($kinds as$kind=>$refs)foreach(array_keys($refs)as$ref)$prov[(int)$lid][]=[$kind,$ref,$form];}}
    $candidateIds=array_keys($locals);sort($candidateIds,SORT_NUMERIC);if(count($candidateIds)===0)$reasons[]='no_exact_alias_local';elseif(count($candidateIds)>1)$reasons[]='ambiguous_exact_alias_local';$local=count($candidateIds)===1?(int)$candidateIds[0]:null;$h=$local!==null?($catalog[$local]??null):null;
    $geoOk=false;if($h){$g=pag_norm($publicGeo);foreach([(string)($h['region_name']??''),(string)($h['subregion_name']??'')]as$tg)if($g!==''&&$g===pag_norm($tg))$geoOk=true;if(!$geoOk)$reasons[]='public_geo_not_exact_target_region_or_subregion';if(!empty($acceptedByNsLocal[$ns][$local])&&!in_array($ext,$acceptedByNsLocal[$ns][$local],true))$reasons[]='same_namespace_target_occupied';}
    $auth=$aid!==''?($acceptedAuthority[$aid]??null):null;if($auth&&$local!==null&&(int)$auth['local_id']!==$local)$reasons[]='current_authority_conflicts_alias_target';
    $row=['supplier_namespace'=>$ns,'external_hotel_id'=>$ext,'andromeda_hotel_id'=>$aidExpected,'public_name'=>$publicName,'public_geo'=>$publicGeo,'current_source_name'=>$currentName,'country_id'=>$country,'candidate_local_id'=>$local,'candidate_name'=>$h['name']??null,'target_region_name'=>$h['region_name']??null,'target_subregion_name'=>$h['subregion_name']??null,'alias_provenance'=>$local!==null?($prov[$local]??[]):[],'current_authority'=>$auth];$reasons=array_values(array_unique($reasons));if($reasons){$row['reasons']=$reasons;$out['holds'][]=$row;foreach($reasons as$x)$reasonCounts[$x]=($reasonCounts[$x]??0)+1;}else{$row['evidence_class']='official_operator_public_name_geo_plus_unique_current_exact_alias';$out['strict_candidates'][]=$row;}}
  $db->exec('ROLLBACK');ksort($reasonCounts);$out['state']='completed_read_only';$out['current_pending_checked']=count(PAG_MANIFEST)-count($out['already_resolved']);$out['already_resolved_count']=count($out['already_resolved']);$out['strict_candidate_count']=count($out['strict_candidates']);$out['hold_count']=count($out['holds']);$out['reason_counts']=$reasonCounts;$out['read_at_utc']=gmdate('c');$out['transaction']='REPEATABLE READ / READ ONLY';
 }catch(Throwable $e){try{if($db instanceof PDO&&$db->inTransaction())$db->rollBack();}catch(Throwable $x){}$out['phase']=$phase;$out['error_code']=preg_match('/^[a-z0-9_]{2,120}$/D',$e->getMessage())?$e->getMessage():'sanitized_failure';}finally{ob_end_clean();}
 $rh=pag_write($dir.'/result.json',$out);pag_write($dir.'/receipt.json',['operation_id'=>PAG_OP,'source_sha'=>$sha,'state'=>$out['state'],'result_sha256'=>$rh,'readback_verified'=>hash('sha256',(string)file_get_contents($dir.'/result.json'))===$rh,'manifest_count'=>count(PAG_MANIFEST),'current_pending_checked'=>$out['current_pending_checked']??null,'strict_candidate_count'=>$out['strict_candidate_count']??null,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'samo_andromeda_calls'=>0,'no_replay'=>true]);echo json_encode(['state'=>$out['state'],'current_pending_checked'=>$out['current_pending_checked']??null,'already_resolved_count'=>$out['already_resolved_count']??null,'strict_candidate_count'=>$out['strict_candidate_count']??null,'hold_count'=>$out['hold_count']??null,'reason_counts'=>$out['reason_counts']??null,'result_sha256'=>$rh],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n";exit($out['state']==='completed_read_only'?0:2);
}
pag_main();
