<?php
declare(strict_types=1);
const MARK='MATCH_OLD_TV_HOTELIDS_JSON:';
function enc(array $x):string{return json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
function write_once(string $p,array $x):string{$s=enc($x)."\n";$f=@fopen($p,'x');if(!$f)throw new RuntimeException('durable_create_failed');fwrite($f,$s);fflush($f);fclose($f);if(file_get_contents($p)!==$s)throw new RuntimeException('durable_readback_failed');return hash('sha256',$s);}
function ident($v):?int{if(is_bool($v)||!is_scalar($v))return null;$s=trim((string)$v);return preg_match('/^[1-9][0-9]{0,11}$/D',$s)?(int)$s:null;}
function text($v):string{if(!is_scalar($v))return'';$s=trim((string)(preg_replace('/\s+/u',' ',(string)$v)??''));return function_exists('mb_substr')?mb_substr($s,0,160,'UTF-8'):substr($s,0,160);}
function name_of($v):string{if(is_scalar($v))return text($v);if(!is_array($v))return'';foreach(['name','fullName','russianName','title','label']as$k)if(isset($v[$k])&&text($v[$k])!=='')return text($v[$k]);return'';}
function norm(string $s):string{$s=str_replace(['Ё','ё','&'],['Е','е',' and '],$s);$s=function_exists('mb_strtolower')?mb_strtolower($s,'UTF-8'):strtolower($s);preg_match_all('/[\p{L}\p{N}]+/u',$s,$m);$d=['hotel'=>1,'resort'=>1,'spa'=>1,'the'=>1,'and'=>1,'отель'=>1,'спа'=>1];$o=[];foreach($m[0]as$t)if(!isset($d[$t]))$o[$t]=1;$r=array_keys($o);sort($r);return implode(' ',$r);}
function entities($v,array&$o,int$d=0):void{if($d>8||!is_array($v))return;if(!array_is_list($v)){if(($i=ident($v['id']??null))!==null&&($n=name_of($v))!=='')$o[$i]=['id'=>$i,'name'=>$n];}foreach($v as$x)if(is_array($x))entities($x,$o,$d+1);}
function find_entity(array$p,array$needles):?array{$o=[];entities($p,$o);foreach($o as$r){$n=function_exists('mb_strtolower')?mb_strtolower($r['name'],'UTF-8'):strtolower($r['name']);foreach($needles as$q){$q=function_exists('mb_strtolower')?mb_strtolower($q,'UTF-8'):strtolower($q);if(str_contains($n,$q))return$r;}}return null;}
function search_id($v,int$d=0):?int{if($d>8||!is_array($v))return null;foreach($v as$k=>$x)if(is_string($k)&&preg_match('/^(?:search|request).*id$/i',$k)&&($i=ident($x))!==null)return$i;foreach($v as$x)if(is_array($x)&&($i=search_id($x,$d+1))!==null)return$i;return null;}
function complete($v,int$d=0):bool{if($d>8||!is_array($v))return false;if((int)($v['progress']??0)>=100)return true;if(in_array(strtolower((string)($v['status']??'')),['complete','completed','done','ready'],true))return true;foreach($v as$x)if(is_array($x)&&complete($x,$d+1))return true;return false;}
function flatten($p):array{$r=$p;if(is_array($r)&&!array_is_list($r)){foreach(['hotels','results','tours','items','data']as$k)if(isset($r[$k])&&is_array($r[$k])){$r=$r[$k];break;}}if(!is_array($r))return[];$o=[];foreach($r as$row){if(!is_array($row))continue;if(isset($row['tours'])&&is_array($row['tours'])&&!isset($row['hotel'])){$h=$row;unset($h['tours']);foreach($row['tours']as$t)if(is_array($t)){if(!isset($t['hotel']))$t['hotel']=$h;$o[]=$t;}}elseif(is_array($row['hotel']??null))$o[]=$row;}return$o;}
function anex($v):bool{return in_array(norm(name_of($v)),['anex','anex tour','anextour','анекс','анекс тур'],true);}
function safe_url(string $u):?array{$p=parse_url($u);if(!is_array($p)||strtolower((string)($p['scheme']??''))!=='https')return null;$h=strtolower((string)($p['host']??''));if(!in_array($h,['agent.anextour.ru','online.anextour.ru','anextour.ru','www.anextour.ru'],true))return null;$q=[];parse_str((string)($p['query']??''),$q);$keep=[];foreach(['HOTELLIST','hotelCode','hotel','hotelId']as$k)if(isset($q[$k])&&ident($q[$k])!==null)$keep[$k]=(int)$q[$k];return['host'=>$h,'path'=>(string)($p['path']??''),'ids'=>$keep];}
function scalar_refs(array$r):array{$out=[];$walk=function($v,string$path,int$d)use(&$walk,&$out){if($d>5)return;if(is_array($v)){foreach($v as$k=>$x)$walk($x,$path.($path===''?'':'.').(string)$k,$d+1);return;}if(!is_scalar($v)||$v==='')return;$leaf=strtolower((string)preg_replace('/.*\./','',$path));if(!preg_match('/(?:id|key|ref|code|link|url|tour|offer|request|hotel)/',$leaf))return;$s=text($v);if(str_starts_with($s,'http')){$u=safe_url($s);if($u!==null)$out[$path]=$u;return;}if(preg_match('/^[A-Za-z0-9_.:-]{1,100}$/D',$s))$out[$path]=$s;};$walk($r,'',0);ksort($out);return array_slice($out,0,80,true);}
function tv(string$stage,string$path,array$params=[]):array{$GLOBALS['stage']=$stage;$GLOBALS['calls']++;return v2_data_tv_get($path,$params);}
function client_path(string$r):string{foreach([$r.'/data/tourvisor-client-v1.php',$r.'/v2/data/tourvisor-client-v1.php']as$p)if(is_file($p))return$p;throw new RuntimeException('tourvisor_client_missing');}
if(in_array('--self-test',$argv??[],true)){if(norm('ANEX TOUR')!=='anex tour')throw new RuntimeException('norm');echo"hotelids-probe PASS\n";exit;}
$op=(string)getenv('OPERATION_ID');$sha=(string)getenv('MATCH_SOURCE_SHA');$date=(string)getenv('MATCH_DATE');$countryName=(string)getenv('MATCH_COUNTRY');$rawIds=(string)getenv('MATCH_HOTEL_IDS');
if(!preg_match('/^hotel-match-old-tv-hotelids-1971-20260914-v1-(egypt|turkey)-[0-9]{4}-[0-9]{2}-[0-9]{2}$/D',$op)||!preg_match('/^[0-9a-f]{40}$/D',$sha)||!preg_match('/^2026-[0-9]{2}-[0-9]{2}$/D',$date))throw new RuntimeException('identity_guard');
$ids=[];foreach(explode(',',$rawIds)as$x)if(($i=ident($x))!==null)$ids[$i]=$i;$ids=array_values($ids);if(!$ids||count($ids)>30)throw new RuntimeException('hotel_ids_guard');
$root=(string)realpath(getcwd());if($root===''||basename($root)!=='anytoour.ru')throw new RuntimeException('root_guard');$base=rtrim((string)getenv('HOME'),'/').'/.anytoour-match/operations';$out=$base.'/'.$op;if(!is_dir($base)||!mkdir($out,0700))throw new RuntimeException('operation_exists');write_once($out.'/reservation.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'reserved_before_supplier_access','credential_identifier'=>'TOURVISOR_JWT','date'=>$date,'country'=>$countryName,'hotel_count'=>count($ids),'hotel_ids_sha256'=>hash('sha256',implode(',',$ids)),'read_only'=>true,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true]);
$GLOBALS['stage']='bootstrap';$GLOBALS['calls']=0;
try{
 require_once client_path($root);$dep=find_entity(tv('departures','/departures',['departureCountryId'=>1]),['моск','moscow']);if(!$dep)throw new RuntimeException('moscow_not_found');
 $country=find_entity(tv('countries','/countries',['departureId'=>$dep['id'],'onlyCharter'=>false,'onlyDirect'=>false]),$countryName==='Turkey'?['турц','turkey']:['егип','egypt']);if(!$country)throw new RuntimeException('country_not_found');
 $anex=find_entity(tv('operators','/operators',['departureId'=>$dep['id'],'countryId'=>$country['id']]),['anex','анекс']);if(!$anex)throw new RuntimeException('anex_not_found');
 $params=['departureId'=>$dep['id'],'countryId'=>$country['id'],'dateFrom'=>$date,'dateTo'=>$date,'nightsFrom'=>7,'nightsTo'=>7,'adults'=>2,'operatorIds'=>[$anex['id']],'hotelIds'=>$ids,'currency'=>'RUB','onlyCharter'=>false,'onlyDirect'=>false];
 $start=tv('search_start','/tours/search',$params);$sid=search_id($start);if(!$sid)throw new RuntimeException('search_id_not_found');
 try{tv('search_continue','/tours/search/'.$sid.'/continue');}catch(Throwable$e){if(!str_contains($e->getMessage(),'400'))throw$e;}
 $done=false;for($n=0;$n<3;$n++){sleep($n===0?8:10);$st=tv('search_status_'.($n+1),'/tours/search/'.$sid.'/status',['operatorStatus'=>false]);if(complete($st)){$done=true;break;}}if(!$done)throw new RuntimeException('search_not_complete_bounded');
 $rows=flatten(tv('search_results','/tours/search/'.$sid,['limit'=>500]));$wanted=array_fill_keys($ids,true);$hits=[];$seen=[];$missing=0;$opRows=0;
 foreach($rows as$r){$h=is_array($r['hotel']??null)?$r['hotel']:[];$hid=ident($h['id']??null);if($hid===null||!isset($wanted[$hid]))continue;if(!anex(is_array($r['operator']??null)?$r['operator']:[]))continue;$opRows++;$seen[$hid]=1;$refs=scalar_refs($r);$strict=[];foreach($refs as$path=>$v)if(is_array($v)&&isset($v['ids']))foreach($v['ids']as$k=>$i)$strict[]=['path'=>$path,'field'=>$k,'anex_hotel_id'=>$i];if(!$strict)$missing++;$hits[]=['tourvisor_hotel_id'=>$hid,'hotel_name'=>name_of($h),'row_keys'=>array_values(array_slice(array_keys($r),0,80)),'hotel_keys'=>array_values(array_slice(array_keys($h),0,80)),'refs'=>$refs,'strict_anex_ids'=>$strict];}
 $res=['operation_id'=>$op,'source_sha'=>$sha,'status'=>'completed','credential_identifier'=>'TOURVISOR_JWT','country'=>$country,'operator'=>$anex,'date'=>$date,'requested_hotel_count'=>count($ids),'returned_requested_hotels'=>count($seen),'anex_rows'=>$opRows,'identity_rows'=>count($hits)-$missing,'missing_strict_operator_identity'=>$missing,'rows'=>array_slice($hits,0,100),'tourvisor_calls'=>$GLOBALS['calls'],'last_stage'=>$GLOBALS['stage'],'database_writes'=>0,'mapping_writes'=>0,'raw_provider_bodies_recorded'=>false,'token_values_recorded'=>false,'no_replay'=>true];
}catch(Throwable$e){$m=$e->getMessage();$res=['operation_id'=>$op,'source_sha'=>$sha,'status'=>'blocked','credential_identifier'=>'TOURVISOR_JWT','blocked_stage'=>$GLOBALS['stage'],'reason'=>str_contains($m,'429')?'http_429':(str_contains($m,'400')?'http_400':'stage_error'),'sanitized_error'=>preg_replace('/[^A-Za-z0-9_.-]+/','_',substr($m,0,100)),'tourvisor_calls'=>$GLOBALS['calls'],'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true];}
$rh=write_once($out.'/result.json',$res);write_once($out.'/receipt.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>$res['status'],'result_sha256'=>$rh,'readback_verified'=>hash('sha256',(string)file_get_contents($out.'/result.json'))===$rh,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true]);echo MARK.enc($res)."\n";exit($res['status']==='completed'?0:2);
