<?php
declare(strict_types=1);
error_reporting(0);
const OPERATION_ID='hotel-match-former-name-reverse-review-1971-20260912-v18';
function norm_text($v): string {$v=mb_strtolower((string)$v,'UTF-8');$v=strtr($v,['ё'=>'е','é'=>'e','è'=>'e','ê'=>'e','á'=>'a','à'=>'a','ä'=>'a','â'=>'a','ö'=>'o','ô'=>'o','ü'=>'u','ú'=>'u','ç'=>'c','ş'=>'s','ğ'=>'g','ı'=>'i']);preg_match_all('/[\p{L}\p{N}]+/u',$v,$m);return implode(' ',$m[0]??[]);} 
function name_key($v): string {$parts=array_values(array_filter(explode(' ',norm_text($v)),static fn($x)=>$x!==''&&!in_array($x,['hotel','resort','spa'],true)));sort($parts,SORT_STRING);return implode(' ',$parts);} 
function aliases_for_name(string $v): array {$out=[$v];if(preg_match_all('/\(\s*(?:ex|ех)\s*\.?\s*([^)]{2,120})\)/iu',$v,$m))foreach($m[1] as $x)$out[]=trim((string)$x);$stripped=preg_replace('/\s*\(\s*(?:ex|ех)\s*\.?\s*[^)]{2,120}\)\s*/iu',' ',$v);if(is_string($stripped)&&trim($stripped)!=='')$out[]=trim($stripped);return array_values(array_unique($out));}
function coord_from_array(array $row): ?array {$lat=$lon=null;foreach(['lat','latitude','geo_lat','hotel_latitude'] as $k)if(isset($row[$k])&&is_numeric($row[$k])){$lat=(float)$row[$k];break;}foreach(['lon','lng','longitude','geo_lon','hotel_longitude'] as $k)if(isset($row[$k])&&is_numeric($row[$k])){$lon=(float)$row[$k];break;}return $lat!==null&&$lon!==null&&abs($lat)<=90&&abs($lon)<=180?[$lat,$lon]:null;}
function coord_from_nested($v): ?array {if(!is_array($v))return null;$c=coord_from_array($v);if($c)return $c;foreach($v as $x){$c=coord_from_nested($x);if($c)return $c;}return null;}
function km(array $a,array $b): float {$r=6371.0;$p1=deg2rad($a[0]);$p2=deg2rad($b[0]);$dp=deg2rad($b[0]-$a[0]);$dl=deg2rad($b[1]-$a[1]);$q=sin($dp/2)**2+cos($p1)*cos($p2)*sin($dl/2)**2;return 2*$r*asin(min(1,sqrt($q)));}
try{
 $root=realpath(getcwd());if(!$root||basename($root)!=='anytoour.ru')throw new RuntimeException('root');$dbHelper=is_file($root.'/data/db-v1.php')?$root.'/data/db-v1.php':$root.'/v2/data/db-v1.php';require_once $dbHelper;$preview=$root.'/_preview/search3-anex-candidate';$app=is_file($preview.'/app/integrations/anex-search-mapping-registry.php')?$preview.'/app/integrations':$root.'/app/integrations';require_once $app.'/anex-search-mapping-registry.php';$pdo=v2_data_db();$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->exec('START TRANSACTION READ ONLY');$registry=AnyTourAnexSearchMappingRegistry::fromPdo($pdo);
 $p=['anex_id'=>'32809','anex_name'=>'The Galataport Hotel.','andromeda_id'=>'2000064875','local_id'=>71266];$current=$registry->resolve('anex_online',$p['anex_id'],'preview');$andr=$pdo->prepare("SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=? LIMIT 2");$andr->execute([$p['andromeda_id']]);$ars=$andr->fetchAll(PDO::FETCH_ASSOC);$a=count($ars)===1?$ars[0]:null;$hotel=$pdo->prepare('SELECT * FROM catalog_hotels WHERE id=? LIMIT 1');$hotel->execute([$p['local_id']]);$h=$hotel->fetch(PDO::FETCH_ASSOC)?:null;$aliases=$pdo->prepare('SELECT alias FROM hotel_aliases WHERE hotel_id=? ORDER BY alias LIMIT 200');$aliases->execute([$p['local_id']]);$localAliases=array_map('strval',$aliases->fetchAll(PDO::FETCH_COLUMN));$dec=$pdo->prepare('SELECT * FROM anex_hotel_decisions WHERE anex_hotel_id=? LIMIT 50');$dec->execute([(int)$p['anex_id']]);$decisionRows=$dec->fetchAll(PDO::FETCH_ASSOC);$map=$pdo->prepare('SELECT * FROM anex_hotel_search_mappings WHERE anex_hotel_id=? LIMIT 50');$map->execute([(int)$p['anex_id']]);$mappingRows=$map->fetchAll(PDO::FETCH_ASSOC);$ex=$pdo->prepare('SELECT * FROM anex_review_pair_exclusions WHERE anex_hotel_id=? LIMIT 100');$ex->execute([(int)$p['anex_id']]);$exRows=$ex->fetchAll(PDO::FETCH_ASSOC);
 $candidateKey=name_key($p['anex_name']);$matchedAlias=null;if($h){foreach(array_merge(aliases_for_name((string)$h['name']),$localAliases) as $n)if($candidateKey!==''&&name_key($n)===$candidateKey){$matchedAlias=$n;break;}}
 $distance=null;$reason=[];$bucket='needs_extra_evidence';if($current!==null){$bucket='blocked';$reason[]='anex_mapping_now_exists';}elseif(!$a||($a['decision_status']??'')!=='accepted'||(int)($a['local_hotel_id']??0)!==(int)$p['local_id']){$bucket='blocked';$reason[]='andromeda_target_changed';}elseif(!$h||(int)($h['is_active']??0)!==1||(int)($h['country_id']??0)!==4){$bucket='blocked';$reason[]='local_target_invalid';}elseif(count($decisionRows)||count($mappingRows)||count($exRows)){$bucket='blocked';$reason[]='existing_anex_decision_mapping_or_exclusion';}elseif($matchedAlias===null){$reason[]='former_name_alias_not_confirmed';}else{$ev=[];try{$ev=json_decode((string)($a['evidence_json']??''),true,128,JSON_THROW_ON_ERROR);}catch(Throwable $e){}$sc=coord_from_nested($ev);$tc=coord_from_array($h);if($sc&&$tc){$distance=km($sc,$tc);if($distance>5){$bucket='blocked';$reason[]='coordinate_conflict_gt_5km';}}if($bucket==='needs_extra_evidence'&&($distance===null||$distance<=5)){$bucket='reverse_safe_candidate';$reason[]='explicit_ex_former_name_alias_plus_current_accepted_andromeda_plus_live_price_position';}}
 $pdo->exec('ROLLBACK');$out=['status'=>'completed','operation_id'=>OPERATION_ID,'bucket'=>$bucket,'anex_id'=>$p['anex_id'],'andromeda_id'=>$p['andromeda_id'],'target_local_id'=>$p['local_id'],'target_name'=>$h['name']??null,'matched_alias'=>$matchedAlias,'coordinate_distance_km'=>$distance===null?null:round($distance,3),'decision_rows'=>count($decisionRows),'mapping_rows'=>count($mappingRows),'exclusion_rows'=>count($exRows),'reasons'=>$reason,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true];
}catch(Throwable $e){if(isset($pdo)&&$pdo instanceof PDO&&$pdo->inTransaction())$pdo->rollBack();$out=['status'=>'failed','operation_id'=>OPERATION_ID,'safe_message'=>substr($e->getMessage(),0,160),'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true];}
echo 'MATCH_FORMER_REVERSE_JSON:'.json_encode($out,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES).PHP_EOL;exit(($out['status']??'')==='completed'?0:2);
