<?php
declare(strict_types=1);
const BP174_OP='hotel-match-search30-biblio174-provider-current-1971-20260921-v1';
const BP174_INPUT_SHA='4e798d1614f3eb90bc26b387944b23470d0800378b41d93bbb52f59a11899806';
function bp174_req(bool $ok,string $reason):void{if(!$ok)throw new RuntimeException($reason);}
function bp174_write(string $path,array $value):string{$raw=json_encode($value,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";$f=@fopen($path,'x+b');bp174_req(is_resource($f),'exclusive_output');bp174_req(fwrite($f,$raw)===strlen($raw),'short_write');fflush($f);if(function_exists('fsync'))fsync($f);fclose($f);return hash('sha256',$raw);}
function bp174_safe(Throwable $e):string{$m=$e->getMessage();return is_string($m)&&preg_match('/^[A-Za-z0-9_.:-]{1,96}$/D',$m)?$m:'sanitized_error';}
function bp174_selftest():void{bp174_req(strlen(BP174_INPUT_SHA)===64,'sha');echo "hotel-match-search30-biblio174-provider-current-v1: PASS\n";}
function bp174_main():void{
 bp174_req(PHP_SAPI==='cli'&&(string)getenv('MATCH_OPERATION_ID')===BP174_OP,'operation_guard');$source=(string)getenv('MATCH_SOURCE_SHA');bp174_req(preg_match('/^[0-9a-f]{40}$/D',$source)===1,'source_sha');
 $dir=rtrim((string)getenv('HOME'),'/').'/.anytoour-match/operations/'.BP174_OP;$rp=realpath($dir.'/reservation.json');$ip=realpath($dir.'/input.json');bp174_req(is_string($rp)&&is_string($ip)&&hash_file('sha256',$ip)===BP174_INPUT_SHA,'input_guard');
 $reservation=json_decode((string)file_get_contents($rp),true,32,JSON_THROW_ON_ERROR);bp174_req(($reservation['operation_id']??'')===BP174_OP&&($reservation['source_sha']??'')===$source&&($reservation['state']??'')==='reserved_before_db_access','reservation');
 $input=json_decode((string)file_get_contents($ip),true,256,JSON_THROW_ON_ERROR);bp174_req(($input['edge_count']??0)===174&&($input['unique_tv_hotels']??0)===174&&count($input['edges']??[])===174,'input_shape');bp174_req(($input['source_result_sha256']??'')==='76c740c4efbb95a2c2c44fd7fe69ecea30b5091c0e17dfec2bb4cf30da75cea2','result_binding');
 $ids=[];foreach($input['edges'] as $edge){$tv=(int)($edge['tv_hotel_id']??0);bp174_req($tv>0,'tv_id');$ids[$tv]=true;}bp174_req(count($ids)===174,'unique_targets');$targets=array_keys($ids);sort($targets,SORT_NUMERIC);
 $root=realpath(getcwd());bp174_req(is_string($root)&&basename($root)==='anytoour.ru','root');require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
 $out=['operation_id'=>BP174_OP,'source_sha'=>$source,'state'=>'failed_no_replay','reason'=>null,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'samo_calls'=>0,'direct_anex_calls'=>0,'no_replay'=>true];
 try{
  $db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');foreach(['andromeda_hotel_identities','catalog_hotels'] as $table){$q=$db->prepare('SELECT ENGINE FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?');$q->execute([$table]);bp174_req(strtoupper((string)$q->fetchColumn())==='INNODB','table_contract_'.$table);}
  $facts=[];$provider=[];foreach(array_chunk($targets,150) as $chunk){$ph=implode(',',array_fill(0,count($chunk),'?'));$q=$db->prepare("SELECT id,name,country_id,is_active FROM catalog_hotels WHERE id IN ($ph) ORDER BY id");$q->execute($chunk);foreach($q->fetchAll(PDO::FETCH_ASSOC) as $r)$facts[(int)$r['id']]=['name'=>(string)$r['name'],'country_id'=>$r['country_id']===null?null:(int)$r['country_id'],'is_active'=>(int)$r['is_active']];$q=$db->prepare("SELECT external_hotel_id,local_hotel_id,decision_status,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace='operator_115' AND local_hotel_id IN ($ph) ORDER BY local_hotel_id,external_hotel_id");$q->execute($chunk);foreach($q->fetchAll(PDO::FETCH_ASSOC) as $r){$tv=(int)$r['local_hotel_id'];$provider[$tv][]=['external_hotel_id'=>(string)$r['external_hotel_id'],'decision_status'=>(string)$r['decision_status'],'evidence_sha256'=>hash('sha256',(string)($r['evidence_json']??''))];}}
  $summary=['accepted_provider_present'=>0,'pending_provider_present'=>0,'conflict_or_mixed_provider_present'=>0,'no_provider_row'=>0,'provider_rows_total'=>0,'targets_with_multiple_provider_rows'=>0];$dossiers=[];foreach($targets as $tv){$rows=$provider[$tv]??[];$summary['provider_rows_total']+=count($rows);if(count($rows)>1)$summary['targets_with_multiple_provider_rows']++;$states=[];foreach($rows as $r)$states[$r['decision_status']]=true;if(!$rows)$class='no_provider_row';elseif(isset($states['accepted']))$class='accepted_provider_present';elseif(count($states)===1&&isset($states['pending']))$class='pending_provider_present';else $class='conflict_or_mixed_provider_present';$summary[$class]++;$dossiers[]=['tv_hotel_id'=>$tv,'target_fact'=>$facts[$tv]??null,'provider_rows'=>$rows,'classification'=>$class,'safe_to_write_now'=>false];}
  $db->commit();$out['state']='completed_read_only';$out['read_at_utc']=gmdate('c');$out['operator_namespace']='operator_115';$out['target_count']=174;$out['summary']=$summary;$out['dossiers']=$dossiers;
 }catch(Throwable $e){if($db->inTransaction())$db->rollBack();$out['reason']=bp174_safe($e);}
 $hash=bp174_write($dir.'/result.json',$out);bp174_write($dir.'/receipt.json',['operation_id'=>BP174_OP,'source_sha'=>$source,'state'=>$out['state'],'reason'=>$out['reason'],'result_sha256'=>$hash,'readback_verified'=>hash_file('sha256',$dir.'/result.json')===$hash,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'samo_calls'=>0,'direct_anex_calls'=>0,'no_replay'=>true]);echo json_encode(['state'=>$out['state'],'reason'=>$out['reason'],'summary'=>$out['summary']??null,'result_sha256'=>$hash],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n";exit($out['state']==='completed_read_only'?0:2);
}
if(($argv[1]??'')==='--self-test'){bp174_selftest();exit(0);}if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__)bp174_main();
