<?php
declare(strict_types=1);
const OP='hotel-match-passive-provider-exact-current-1971-20260917-v1';
function req($v,$m){if(!$v)throw new RuntimeException($m);} function q(PDO $d,string $s,array $a=[]):array{$p=$d->prepare($s);$p->execute(array_values($a));$r=$p->fetchAll(PDO::FETCH_ASSOC);req(count($r)<=100000,'row_budget');return$r;}
function norm(string $s):string{$s=mb_strtolower(trim($s),'UTF-8');$s=str_replace('ё','е',$s);$s=preg_replace('/[^\p{L}\p{N}]+/u',' ',$s)??$s;return trim(preg_replace('/\s+/u',' ',$s)??$s);}
function forms(string $s):array{$raw=trim($s);if($raw==='')return[];$variants=[$raw];$x=preg_replace('/\s*\((?:ex|ех)\.?[^)]*\)\s*$/iu','',$raw);if(is_string($x)&&trim($x)!==''&&trim($x)!==$raw)$variants[]=trim($x);$out=[];foreach($variants as$v){$n=norm($v);if($n==='')continue;$out[$n]=1;$t=preg_split('/\s+/u',$n,-1,PREG_SPLIT_NO_EMPTY)?:[];$g=array_values(array_filter($t,static fn($z)=>$z!=='hotel'&&$z!=='отель'));if($g&&count($g)!==count($t))$out[implode(' ',$g)]=1;}return array_keys($out);}
function prot($v,string $k='',int $d=0):bool{if($d>24)return true;if(is_array($v)){foreach($v as$kk=>$x)if(prot($x,(string)$kk,$d+1))return true;return false;}if(!preg_match('/manual|exclude|exclusion|conflict|reject|review|protect/i',$k))return false;if(is_bool($v))return$v;if(is_numeric($v))return(float)$v!=0.0;return is_string($v)&&!in_array(strtolower(trim($v)),['','false','none','no','null','0'],true);}
function bridge(array $e):?array{$b=$e['provider_bridges'][0]??null;if(!is_array($b))return null;$aid=trim((string)($b['andromeda_hotel_id']??''));$country=filter_var($b['country_id']??null,FILTER_VALIDATE_INT);$name=trim((string)($b['hotel_name']??''));if($aid===''||!ctype_digit($aid)||$country===false||(int)$country<=0||$name==='')return null;$lat=null;$lon=null;foreach(['latitude','lat']as$k)if(isset($b[$k])&&is_numeric($b[$k])){$lat=(float)$b[$k];break;}foreach(['longitude','lon','lng']as$k)if(isset($b[$k])&&is_numeric($b[$k])){$lon=(float)$b[$k];break;}return['andromeda_id'=>$aid,'country_id'=>(int)$country,'hotel_name'=>$name,'latitude'=>$lat,'longitude'=>$lon];}
function km(float $a,float $b,float $c,float $d):float{$r=6371.0;$p1=deg2rad($a);$p2=deg2rad($c);$dp=deg2rad($c-$a);$dl=deg2rad($d-$b);$x=sin($dp/2)**2+cos($p1)*cos($p2)*sin($dl/2)**2;return 2*$r*asin(min(1.0,sqrt($x)));}
function writej(string $p,array $v):string{$j=json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";$f=@fopen($p,'x+b');req(is_resource($f),'exclusive_output');try{req(fwrite($f,$j)===strlen($j)&&fflush($f),'write');if(function_exists('fsync'))req(fsync($f),'sync');rewind($f);req(stream_get_contents($f)===$j,'readback');}finally{fclose($f);}return hash('sha256',$j);}
function main():void{$sha=(string)getenv('MATCH_SOURCE_SHA');req(PHP_SAPI==='cli'&&getenv('MATCH_OPERATION_ID')===OP&&preg_match('/^[a-f0-9]{40}$/D',$sha),'guard');$dir=(string)getenv('HOME').'/.anytoour-match/operations/'.OP;$rv=json_decode((string)file_get_contents($dir.'/reservation.json'),true,32,JSON_THROW_ON_ERROR);req(($rv['state']??'')==='reserved_before_db_access'&&($rv['source_sha']??'')===$sha,'reservation');$o=['operation_id'=>OP,'source_sha'=>$sha,'state'=>'failed_no_replay','no_replay'=>true,'safe_to_write_now'=>false,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'samo_andromeda_calls'=>0];$db=null;
try{$root=realpath(getcwd());req(is_string($root)&&basename($root)==='anytoour.ru','root');require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');
$pending=q($db,"SELECT supplier_namespace,external_hotel_id,evidence_sha256,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace IN ('operator_315','operator_342') AND decision_status='pending' AND local_hotel_id IS NULL ORDER BY supplier_namespace,CAST(external_hotel_id AS UNSIGNED),external_hotel_id");
$accepted=q($db,"SELECT supplier_namespace,external_hotel_id,local_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace IN ('operator_315','operator_342') AND decision_status='accepted' AND local_hotel_id IS NOT NULL");$occupied=[];foreach($accepted as$r)$occupied[(string)$r['supplier_namespace']][(int)$r['local_hotel_id']][]=(string)$r['external_hotel_id'];
$parsed=[];$countries=[];$malformed=0;foreach($pending as$r){$e=json_decode((string)$r['evidence_json'],true,64,JSON_THROW_ON_ERROR);req(is_array($e),'evidence_shape');$b=bridge($e);if($b===null){$malformed++;continue;}$parsed[]=['namespace'=>(string)$r['supplier_namespace'],'external_id'=>(string)$r['external_hotel_id'],'sha'=>(string)$r['evidence_sha256'],'evidence'=>$e,'bridge'=>$b,'protected'=>prot($e)];$countries[$b['country_id']]=1;}
$idx=[];$hotels=[];$aliases=[];foreach(array_keys($countries)as$country){foreach(q($db,"SELECT id,country_id,name,normalized_name,region_name,subregion_name,latitude,longitude,is_active FROM catalog_hotels WHERE is_active=1 AND country_id=?",[(int)$country])as$h){$id=(int)$h['id'];$hotels[$id]=$h;foreach(array_merge(forms((string)$h['name']),forms((string)($h['normalized_name']??'')))as$f)$idx[(int)$country][$f][$id]=1;}}
if($hotels){foreach(array_chunk(array_keys($hotels),500)as$ch){$ph=implode(',',array_fill(0,count($ch),'?'));foreach(q($db,"SELECT hotel_id,alias,normalized_alias,source FROM hotel_aliases WHERE hotel_id IN ($ph)",$ch)as$a){$id=(int)$a['hotel_id'];$aliases[$id][]=$a;foreach(array_merge(forms((string)($a['alias']??'')),forms((string)($a['normalized_alias']??'')))as$f)$idx[(int)$hotels[$id]['country_id']][$f][$id]=1;}}}
$passive=[];foreach(q($db,"SELECT hotel_id,operator_id,MIN(first_seen_at) first_seen_at,MAX(last_seen_at) last_seen_at,SUM(observation_count) observation_count,COUNT(*) row_count FROM tour_operator_identity_observations WHERE operator_id IN (25,43) GROUP BY hotel_id,operator_id")as$r)$passive[(int)$r['operator_id']][(int)$r['hotel_id']]=['first_seen_at'=>(string)$r['first_seen_at'],'last_seen_at'=>(string)$r['last_seen_at'],'observation_count'=>(int)$r['observation_count'],'row_count'=>(int)$r['row_count']];
$reasons=[];$raw=[];$exactLocal=0;$passiveHits=0;$hold=static function(string $x)use(&$reasons){$reasons[$x]=($reasons[$x]??0)+1;};foreach($parsed as$p){if($p['protected']){$hold('pending_protected');continue;}$locals=[];foreach(forms($p['bridge']['hotel_name'])as$f)foreach(array_keys($idx[$p['bridge']['country_id']][$f]??[])as$id)$locals[(int)$id]=1;$ids=array_keys($locals);sort($ids,SORT_NUMERIC);if(count($ids)!==1){$hold(count($ids)===0?'no_unique_exact_local':'ambiguous_exact_local');continue;}$exactLocal++;$lid=(int)$ids[0];$h=$hotels[$lid]??null;if(!$h||((int)$h['country_id']!==$p['bridge']['country_id'])){$hold('target_country_mismatch');continue;}$tvop=$p['namespace']==='operator_315'?25:43;$obs=$passive[$tvop][$lid]??null;if($obs===null){$hold('no_passive_provider_on_local');continue;}$passiveHits++;$busy=array_values(array_filter($occupied[$p['namespace']][$lid]??[],static fn($x)=>$x!==$p['external_id']));if($busy){$hold('same_namespace_target_occupied');continue;}$dist=null;if($p['bridge']['latitude']!==null&&$p['bridge']['longitude']!==null&&$h['latitude']!==null&&$h['longitude']!==null){$dist=km((float)$p['bridge']['latitude'],(float)$p['bridge']['longitude'],(float)$h['latitude'],(float)$h['longitude']);if($dist>5.0){$hold('coordinate_over_5km');continue;}}$raw[]=['supplier_namespace'=>$p['namespace'],'external_hotel_id'=>$p['external_id'],'source_evidence_sha256'=>$p['sha'],'andromeda_hotel_id'=>$p['bridge']['andromeda_id'],'source_name'=>$p['bridge']['hotel_name'],'country_id'=>$p['bridge']['country_id'],'local_id'=>$lid,'local_name'=>(string)$h['name'],'region_name'=>$h['region_name'],'subregion_name'=>$h['subregion_name'],'distance_km'=>$dist===null?null:round($dist,3),'tourvisor_operator_id'=>$tvop,'passive_first_seen'=>$obs['first_seen_at'],'passive_last_seen'=>$obs['last_seen_at'],'passive_observation_count'=>$obs['observation_count'],'passive_row_count'=>$obs['row_count']];}
$usage=[];foreach($raw as$x)$usage[$x['supplier_namespace'].':'.$x['local_id']][]=$x['external_hotel_id'];$prepared=[];foreach($raw as$x){$k=$x['supplier_namespace'].':'.$x['local_id'];if(count(array_unique($usage[$k]))!==1){$hold('duplicate_target_same_namespace');continue;}$prepared[]=$x;}usort($prepared,static fn($a,$b)=>($b['passive_observation_count']<=>$a['passive_observation_count'])?:strcmp($a['supplier_namespace'].$a['external_hotel_id'],$b['supplier_namespace'].$b['external_hotel_id']));ksort($reasons);$db->exec('ROLLBACK');$o['state']='completed_read_only';$o['pending_total']=count($pending);$o['pending_parseable']=count($parsed);$o['pending_malformed']=$malformed;$o['passive_operator25_hotels']=count($passive[25]??[]);$o['passive_operator43_hotels']=count($passive[43]??[]);$o['unique_exact_local']=$exactLocal;$o['exact_local_with_passive_provider']=$passiveHits;$o['strict_prepared_count']=count($prepared);$o['reason_counts']=$reasons;$o['prepared']=$prepared;$o['read_at_utc']=gmdate('c');$o['transaction']='REPEATABLE READ / READ ONLY';}
catch(Throwable $e){if($db instanceof PDO&&$db->inTransaction())$db->rollBack();$o['error_code']=preg_match('/^[a-z_]{2,100}$/D',$e->getMessage())?$e->getMessage():'sanitized_failure';}$dig=writej($dir.'/result.json',$o);writej($dir.'/receipt.json',['operation_id'=>OP,'source_sha'=>$sha,'state'=>$o['state'],'result_sha256'=>$dig,'readback_verified'=>true,'no_replay'=>true,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'samo_andromeda_calls'=>0]);echo json_encode(['state'=>$o['state'],'pending_total'=>$o['pending_total']??null,'unique_exact_local'=>$o['unique_exact_local']??null,'exact_local_with_passive_provider'=>$o['exact_local_with_passive_provider']??null,'strict_prepared_count'=>$o['strict_prepared_count']??null,'reason_counts'=>$o['reason_counts']??[],'prepared'=>$o['prepared']??[],'result_sha256'=>$dig],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n";if($o['state']!=='completed_read_only')exit(2);}
if(in_array('--self-test',$argv??[],true)){req(forms('Romance Hotel')===['romance hotel','romance'],'forms');req(prot(['manual'=>true])&&!prot(['manual'=>false]),'prot');req(bridge(['provider_bridges'=>[['andromeda_hotel_id'=>'1','country_id'=>4,'hotel_name'=>'X']]])['country_id']===4,'bridge');echo "3 passive-provider self-tests PASS\n";exit(0);}main();
