<?php
declare(strict_types=1);
const M='MATCH_OLD_TV_JWT_STAGE_PROBE_JSON:';
function j(array $x):string{return json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
function w(string$p,array$x):string{$r=j($x)."\n";$f=@fopen($p,'x');if(!$f)throw new RuntimeException('durable_create_failed');fwrite($f,$r);fflush($f);fclose($f);if(file_get_contents($p)!==$r)throw new RuntimeException('durable_readback_failed');return hash('sha256',$r);}
function id($v):?int{if(is_bool($v)||!is_scalar($v))return null;$s=trim((string)$v);return preg_match('/^[1-9][0-9]{0,11}$/D',$s)?(int)$s:null;}
function txt($v):string{if(!is_scalar($v))return'';$s=trim((string)(preg_replace('/\s+/u',' ',(string)$v)??''));return function_exists('mb_substr')?mb_substr($s,0,200,'UTF-8'):substr($s,0,200);}
function nm($v):string{if(is_scalar($v))return txt($v);if(!is_array($v))return'';foreach(['name','fullName','russianName','title','label']as$k)if(isset($v[$k])&&txt($v[$k])!=='')return txt($v[$k]);return'';}
function norm($v):string{$s=str_replace(['Ё','ё','&'],['Е','е',' and '],(string)$v);$s=function_exists('mb_strtolower')?mb_strtolower($s,'UTF-8'):strtolower($s);preg_match_all('/[\p{L}\p{N}]+/u',$s,$m);$drop=['hotel'=>1,'resort'=>1,'spa'=>1,'the'=>1,'and'=>1,'отель'=>1,'спа'=>1];$o=[];foreach($m[0]as$t)if(!isset($drop[$t]))$o[$t]=1;$r=array_keys($o);sort($r);return implode(' ',$r);}
function entities($v,array&$o,int$d=0):void{if($d>8||!is_array($v))return;if(!array_is_list($v)){if(($i=id($v['id']??null))!==null&&($n=nm($v))!=='')$o[$i]=['id'=>$i,'name'=>$n];}foreach($v as$x)if(is_array($x))entities($x,$o,$d+1);}
function find_entity(array$p,array$needles):?array{$o=[];entities($p,$o);foreach($o as$r){$n=function_exists('mb_strtolower')?mb_strtolower($r['name'],'UTF-8'):strtolower($r['name']);foreach($needles as$q){$q=function_exists('mb_strtolower')?mb_strtolower($q,'UTF-8'):strtolower($q);if(str_contains($n,$q))return$r;}}return null;}
function search_id($v,int$d=0):?int{if($d>8||!is_array($v))return null;foreach($v as$k=>$x)if(is_string($k)&&preg_match('/^(?:search|request).*id$/i',$k)&&($i=id($x))!==null)return$i;foreach($v as$x)if(is_array($x)&&($i=search_id($x,$d+1))!==null)return$i;return null;}
function complete($v,int$d=0):bool{if($d>8||!is_array($v))return false;if((int)($v['progress']??0)>=100)return true;if(in_array(strtolower((string)($v['status']??'')),['complete','completed','done','ready'],true))return true;foreach($v as$x)if(is_array($x)&&complete($x,$d+1))return true;return false;}
function flatten($p):array{$r=$p;if(is_array($r)&&!array_is_list($r)){foreach(['hotels','results','tours','items','data']as$k)if(isset($r[$k])&&is_array($r[$k])){$r=$r[$k];break;}}if(!is_array($r))return[];$o=[];foreach($r as$row){if(!is_array($row))continue;if(isset($row['tours'])&&is_array($row['tours'])&&!isset($row['hotel'])){$h=$row;unset($h['tours']);foreach($row['tours']as$t)if(is_array($t)){if(!isset($t['hotel']))$t['hotel']=$h;$o[]=$t;}}elseif(is_array($row['hotel']??null))$o[]=$row;}return$o;}
function op_anex($v):bool{return in_array(norm(nm($v)),['anex','anex tour','anextour','анекс','анекс тур'],true);}
function link_id(string$u):?array{$p=parse_url($u);if(!is_array($p)||strtolower((string)($p['scheme']??''))!=='https')return null;$h=strtolower((string)($p['host']??''));$path=(string)($p['path']??'');$want=$h==='agent.anextour.ru'&&$path==='/search/tour'?'HOTELLIST':($h==='online.anextour.ru'&&in_array($path,['/search','/search/'],true)?'hotelCode':null);if($want===null)return null;$ids=[];foreach(explode('&',(string)($p['query']??''))as$q){[$k,$v]=array_pad(explode('=',$q,2),2,'');if(strcasecmp(rawurldecode($k),$want)===0&&($i=id(rawurldecode($v)))!==null)$ids[]=$i;}return count($ids)===1?['id'=>$ids[0],'field'=>$want]:null;}
function tv(string$stage,string$path,array$params=[]):array{$GLOBALS['stage']=$stage;$GLOBALS['calls']++;return v2_data_tv_get($path,$params);}
function tvpath(string$r):string{foreach([$r.'/data/tourvisor-client-v1.php',$r.'/v2/data/tourvisor-client-v1.php']as$p)if(is_file($p))return$p;throw new RuntimeException('tourvisor_client_missing');}
if(in_array('--self-test',$argv??[],true)){if(norm('ANEX Tour')!=='anex tour')throw new RuntimeException('norm');if((link_id('https://agent.anextour.ru/search/tour?HOTELLIST=123')['id']??0)!==123)throw new RuntimeException('link');echo"stage-probe PASS\n";exit;}
$op=(string)getenv('OPERATION_ID');$sha=(string)getenv('MATCH_SOURCE_SHA');$date=(string)(getenv('MATCH_DATE')?:'2026-10-28');if(!preg_match('/^hotel-match-old-tv-jwt-stage-probe-1971-20260914-v[0-9]+-[0-9]{4}-[0-9]{2}-[0-9]{2}$/D',$op)||!preg_match('/^[0-9a-f]{40}$/D',$sha))throw new RuntimeException('identity_guard');$root=(string)realpath(getcwd());if($root===''||basename($root)!=='anytoour.ru')throw new RuntimeException('root_guard');$base=rtrim((string)getenv('HOME'),'/').'/.anytoour-match/operations';$out=$base.'/'.$op;if(!is_dir($base)||!mkdir($out,0700))throw new RuntimeException('operation_exists');w($out.'/reservation.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'reserved_before_supplier_access','credential_identifier'=>'TOURVISOR_JWT','date'=>$date,'read_only'=>true,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true]);
$GLOBALS['stage']='bootstrap';$GLOBALS['calls']=0;
try{
 require_once tvpath($root);if(!function_exists('v2_data_tv_get'))throw new RuntimeException('client_missing');if(trim((string)(getenv('TOURVISOR_JWT')?:''))===''&&!(defined('TOURVISOR_JWT')&&trim((string)TOURVISOR_JWT)!==''))throw new RuntimeException('tourvisor_jwt_missing');
 $depPayload=tv('departures','/departures',['departureCountryId'=>1]);$dep=find_entity($depPayload,['моск','moscow']);if(!$dep)throw new RuntimeException('moscow_not_found');
 $countryPayload=tv('countries','/countries',['departureId'=>$dep['id'],'onlyCharter'=>false,'onlyDirect'=>false]);$country=find_entity($countryPayload,['егип','egypt']);if(!$country)throw new RuntimeException('egypt_not_found');
 $opPayload=tv('operators','/operators',['departureId'=>$dep['id'],'countryId'=>$country['id']]);$anex=find_entity($opPayload,['anex','анекс']);if(!$anex)throw new RuntimeException('anex_not_found');
 $s=tv('search_start','/tours/search',['departureId'=>$dep['id'],'countryId'=>$country['id'],'dateFrom'=>$date,'dateTo'=>$date,'nightsFrom'=>7,'nightsTo'=>7,'adults'=>2,'operatorIds'=>[$anex['id']],'currency'=>'RUB']);$sid=search_id($s);if(!$sid)throw new RuntimeException('search_id_not_found');
 try{tv('search_continue_1','/tours/search/'.$sid.'/continue');}catch(Throwable$e){if(!str_contains($e->getMessage(),'400'))throw$e;}
 sleep(8);$st=tv('search_status_1','/tours/search/'.$sid.'/status',['operatorStatus'=>false]);if(!complete($st)){sleep(10);$st=tv('search_status_2','/tours/search/'.$sid.'/status',['operatorStatus'=>false]);}
 if(!complete($st))throw new RuntimeException('search_not_complete_bounded');$payload=tv('search_results','/tours/search/'.$sid,['limit'=>500]);$rows=flatten($payload);$anexRows=0;$ids=[];$missing=0;foreach($rows as$r){$ov=is_array($r['operator']??null)?$r['operator']:[];if(!op_anex($ov))continue;$anexRows++;$h=is_array($r['hotel']??null)?$r['hotel']:[];$tvhid=id($h['id']??null);$u=txt($r['operatorLink']??($h['operatorLink']??''));if($u===''){$missing++;continue;}$li=link_id($u);if($li&&$tvhid)$ids[$li['id'].'|'.$tvhid]=['anex_hotel_id'=>$li['id'],'tourvisor_hotel_id'=>$tvhid,'tourvisor_hotel_name'=>nm($h),'identity_field'=>$li['field']];}
 $res=['operation_id'=>$op,'source_sha'=>$sha,'status'=>'completed','credential_identifier'=>'TOURVISOR_JWT','last_stage'=>$GLOBALS['stage'],'tourvisor_calls'=>$GLOBALS['calls'],'departure'=>$dep,'country'=>$country,'operator'=>$anex,'search_id_present'=>true,'flattened_rows'=>count($rows),'anex_operator_rows'=>$anexRows,'strict_operator_identities'=>array_values($ids),'strict_identity_count'=>count($ids),'missing_operator_link'=>$missing,'database_writes'=>0,'mapping_writes'=>0,'raw_provider_bodies_recorded'=>false,'token_values_recorded'=>false,'no_replay'=>true];
}catch(Throwable$e){$m=$e->getMessage();$reason=str_contains($m,'429')?'http_429':(str_contains($m,'401')||str_contains($m,'403')?'auth_rejected':(str_contains($m,'400')?'http_400':'stage_error'));$res=['operation_id'=>$op,'source_sha'=>$sha,'status'=>'blocked','credential_identifier'=>'TOURVISOR_JWT','blocked_stage'=>$GLOBALS['stage'],'reason'=>$reason,'sanitized_error'=>preg_replace('/[^A-Za-z0-9_.-]+/','_',substr($m,0,100)),'tourvisor_calls'=>$GLOBALS['calls'],'database_writes'=>0,'mapping_writes'=>0,'raw_provider_bodies_recorded'=>false,'token_values_recorded'=>false,'no_replay'=>true];}
$rh=w($out.'/result.json',$res);w($out.'/receipt.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>$res['status'],'result_sha256'=>$rh,'readback_verified'=>hash('sha256',(string)file_get_contents($out.'/result.json'))===$rh,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true]);echo M.j($res)."\n";exit($res['status']==='completed'?0:2);
