<?php
declare(strict_types=1);
const C55_OP='hotel-match-refresh55-direct-current-1971-20260919-v1';
function c55_need(bool $x,string $w):void{if(!$x)throw new RuntimeException($w);}
function c55_write(string $p,array $v):string{$b=json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n";$f=fopen($p,'xb');c55_need(is_resource($f),'open');fwrite($f,$b);fflush($f);if(function_exists('fsync'))fsync($f);fclose($f);return hash('sha256',$b);}
function c55_rows(PDO $db,string $q,array $p=[]):array{$s=$db->prepare($q);$s->execute(array_values($p));return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}
function c55_star(array $h):?int{foreach(['star','starLName','category']as$k)if(isset($h[$k])&&preg_match('/([1-5])/u',(string)$h[$k],$m))return(int)$m[1];return null;}
if(in_array('--self-test',$argv??[],true)){c55_need(c55_star(['starLName'=>'5*'])===5,'star');echo"REFRESH55_CURRENT_SELFTEST_OK\n";exit(0);}
$dir=(string)getenv('MATCH_OPERATION_DIR');$root=realpath((string)getenv('ANYTOUR_ROOT'));$detail=realpath((string)getenv('MATCH_DETAIL'));$router=realpath((string)getenv('MATCH_ROUTER'));$v1=realpath((string)getenv('MATCH_V1_DIR'));$v5=realpath((string)getenv('MATCH_V5_DIR'));
c55_need(PHP_SAPI==='cli'&&is_dir($dir)&&basename($dir)===C55_OP&&is_string($root)&&is_string($detail)&&hash_file('sha256',$detail)==='9d8be005458ca901dac8f94a7224662ae25833882dda2ed6687d184a660af034'&&is_string($router)&&hash_file('sha256',$router)==='3b189d1b7313eb85743a6d22be48aa7323725fe6fb57e8d47b6e5ea220b1cb8f'&&is_string($v1)&&is_string($v5),'runtime');
$d=json_decode((string)file_get_contents($detail),true,128,JSON_THROW_ON_ERROR);$r=json_decode((string)file_get_contents($router),true,128,JSON_THROW_ON_ERROR);$opmap=[13=>'5',18=>'115',25=>'315',43=>'342'];$canon=[13=>'anex',18=>'biblio_globus',25=>'funsun',43=>'intourist'];
$targets=[];foreach($r['rows']as$x)$targets[(int)$x['tv_hotel_id']]=$x['target'];$usage=[];foreach($d['edges']as$e){$op=$opmap[(int)$e['operator_id']];foreach((array)($e['positive_native_candidates']??[])as$t)$usage[$op.'|'.(string)$t][]=(int)$e['tv_hotel_id'];}
$facts=[];foreach([$v1,$v5]as$vd)foreach(glob($vd.'/raw-price-*.json')?:[]as$p){$j=json_decode((string)file_get_contents($p),true,64,JSON_THROW_ON_ERROR);foreach((array)($j['PRICES']??[])as$x){if(!is_array($x))continue;$o=is_array($x['original']??null)?$x['original']:[];$op=(string)($x['operatorKey']??($o['operatorKey']??''));$sid=(string)($x['hotelKey']??'');$nat=(string)($o['hotelKey']??'');if(preg_match('/^[1-9][0-9]*$/D',$op)&&preg_match('/^[1-9][0-9]*$/D',$sid)&&preg_match('/^[1-9][0-9]*$/D',$nat))$facts[$op.'|'.$nat][$sid]=['samo_hotel_id'=>$sid,'native_operator_hotel_id'=>$nat,'operator_id'=>$op,'is_operator_hotel_key'=>$o['isOperatorHotelKey']??null,'raw_sha256'=>hash_file('sha256',$p)];}}
$edges=[];foreach($d['edges']as$e){$tv=(int)$e['tv_hotel_id'];$opid=(int)$e['operator_id'];$op=$opmap[$opid];$hits=[];foreach((array)($e['positive_native_candidates']??[])as$t){$k=$op.'|'.(string)$t;if(count($usage[$k]??[])!==1)continue;foreach($facts[$k]??[]as$sid=>$f)$hits[$sid][]=['native_token'=>(string)$t,'fact'=>$f];}if(count($hits)!==1)continue;$sid=(string)array_key_first($hits);$edges[]=['samo_hotel_id'=>$sid,'tv_hotel_id'=>$tv,'operator_id'=>$opid,'operator'=>$canon[$opid],'native_proofs'=>$hits[$sid],'operator_link_sha256'=>$e['operator_link_sha256']??null,'hotel_name'=>$e['hotel_name']];}
c55_need(count($edges)===55,'edge55');$pairs=[];$sourceTargets=[];$targetSources=[];foreach($edges as$e){$k=$e['samo_hotel_id'].'|'.$e['tv_hotel_id'];$pairs[$k]['samo_hotel_id']=$e['samo_hotel_id'];$pairs[$k]['tv_hotel_id']=$e['tv_hotel_id'];$pairs[$k]['hotel_name']=$e['hotel_name'];$pairs[$k]['operator_proofs'][]=$e;$sourceTargets[$e['samo_hotel_id']][$e['tv_hotel_id']]=true;$targetSources[$e['tv_hotel_id']][$e['samo_hotel_id']]=true;}c55_need(count($pairs)===32,'pair32');
$catalogFiles=['Китай'=>['raw-catalog-0d4a7aaa20.json','5a6851b3462392f563c65ac13c28459261cbd58a4d437bb24115716995f4c560'],'Турция'=>['raw-catalog-13965a9cf6.json','564da2af9cb248a6860b1705285f106d4f022ffbbac36a7fcfe2630d91a74b39'],'Маврикий'=>['raw-catalog-490f3ae3b6.json','3278cf955d7fd87c9a5694783b1434c23c8ce94717b9b68dc86e5ecbe7b692ce'],'Танзания'=>['raw-catalog-b897da4c1b.json','b9b27238c1c980bbf5015ecf6f5c46bacada55251fcd0d92d373fa11bcd5e056'],'Шри-Ланка'=>['raw-catalog-bfa5c7498a.json','bbe38eacc0a64ab7adb4ab82d2c5d9dbf2a795f5d80d4e13c6f1c1a75aa5b63a'],'Египет'=>['raw-catalog-dfd0573e11.json','feecbab9f7cc6a6bb093ab5a744b2a843e79be6e4f570bd80b234661ac8b5755']];$src=[];foreach($catalogFiles as$country=>[$fn,$fh]){$p=$v1.'/'.$fn;c55_need(is_file($p)&&hash_file('sha256',$p)===$fh,'catalog_'.$country);$j=json_decode((string)file_get_contents($p),true,64,JSON_THROW_ON_ERROR);foreach((array)$j['HOTELS']as$h){$id=(string)($h['id']??'');if(isset($sourceTargets[$id]))$src[$id][]=['country'=>$country,'catalog_sha256'=>$fh,'hotel'=>$h];}}foreach($sourceTargets as$sid=>$x)c55_need(count($src[$sid]??[])===1,'source_catalog_'.$sid);
