<?php
declare(strict_types=1);
/** MATCH #1971: full core8 CURRENT read-only exact/former-name sweep of Andromeda pending/null identities. */
const HMAP_OP='hotel-match-andromeda-pending-exact-current-1971-20260916-v1';
const HMAP_CORE8=[1,2,4,6,8,9,10,16];
function js($v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
function putnew(string $p,$v):string{$raw=js($v)."\n";$f=@fopen($p,'x');if(!$f)throw new RuntimeException('durable_create_failed');try{if(fwrite($f,$raw)!==strlen($raw))throw new RuntimeException('durable_write_failed');fflush($f);}finally{fclose($f);}if(file_get_contents($p)!==$raw)throw new RuntimeException('durable_readback_failed');return hash('sha256',$raw);}
function dbpath(string $r):string{foreach([$r.'/data/db-v1.php',$r.'/v2/data/db-v1.php'] as $p)if(is_file($p))return $p;throw new RuntimeException('db_bootstrap_missing');}
function cols(PDO $d,string $t):array{$s=$d->query('SHOW COLUMNS FROM `'.str_replace('`','',$t).'`');$o=[];foreach($s->fetchAll(PDO::FETCH_ASSOC)?:[] as $r)$o[(string)$r['Field']]=true;return $o;}
function q(PDO $d,string $sql,array $p=[]):array{$s=$d->prepare($sql);$s->execute($p);return $s->fetchAll(PDO::FETCH_ASSOC)?:[];}
function sval($v):?string{if(!is_scalar($v))return null;$s=trim((string)$v);return $s===''?null:$s;}
function iid($v):?int{$s=sval($v);return $s!==null&&preg_match('/^[1-9][0-9]{0,14}$/D',$s)?(int)$s:null;}
function fnum($v):?float{if(!is_scalar($v)||!is_numeric((string)$v))return null;$x=(float)$v;return is_finite($x)?$x:null;}
function norm(string $s):string{$s=mb_strtolower($s,'UTF-8');$s=preg_replace('/\b(?:hotel|resort|spa)\b/iu',' ',$s)??$s;$s=preg_replace('/[^\pL\pN]+/u',' ',$s)??$s;return trim(preg_replace('/\s+/u',' ',$s)??$s);}
function forms(?string $s):array{if($s===null)return[];$s=trim($s);if($s==='')return[];$o=[];$former=[];if(preg_match_all('/\((?:\s*(?:ex\.?|former(?:ly)?)\s*[:.-]?\s*)([^)]{2,180})\)/iu',$s,$m))foreach($m[1] as $x)$former[]=(string)$x;$current=preg_replace('/\((?:\s*(?:ex\.?|former(?:ly)?)\s*[:.-]?\s*)[^)]{2,180}\)/iu',' ',$s)??$s;foreach(array_merge([$current],$former) as $x){$n=norm((string)$x);if($n!=='')$o[$n]=true;}return array_keys($o);}
function allowedEvidenceContainers(array $e):array{$out=[['path'=>'evidence','v'=>$e]];foreach(['source','provider','hotel','original','record','api','catalog','identity','input'] as $k)if(isset($e[$k])&&is_array($e[$k]))$out[]=['path'=>'evidence.'.$k,'v'=>$e[$k]];return $out;}
function extract(array $row,array $direct,array $evidenceKeys):array{foreach($direct as $k)if(array_key_exists($k,$row)&&($v=sval($row[$k]))!==null)return['value'=>$v,'path'=>'row.'.$k];$raw=$row['evidence_json']??null;if(!is_string($raw)||trim($raw)==='')return['value'=>null,'path'=>null];try{$e=json_decode($raw,true,512,JSON_THROW_ON_ERROR);}catch(Throwable){return['value'=>null,'path'=>null];}if(!is_array($e))return['value'=>null,'path'=>null];foreach(allowedEvidenceContainers($e) as $box)foreach($evidenceKeys as $k)if(array_key_exists($k,$box['v'])&&($v=sval($box['v'][$k]))!==null)return['value'=>$v,'path'=>$box['path'].'.'.$k];return['value'=>null,'path'=>null];}
function coord(array $row,string $kind):array{$latKeys=$kind==='source'?['latitude','lat','hotel_latitude','source_latitude']:['latitude','lat'];$lonKeys=$kind==='source'?['longitude','lon','lng','hotel_longitude','source_longitude']:['longitude','lon','lng'];$a=extract($row,$latKeys,$latKeys);$b=extract($row,$lonKeys,$lonKeys);return['lat'=>fnum($a['value']),'lon'=>fnum($b['value']),'lat_path'=>$a['path'],'lon_path'=>$b['path']];}
function km(?float $a,?float $b,?float $c,?float $d):?float{if($a===null||$b===null||$c===null||$d===null)return null;$r=6371.0088;$p1=deg2rad($a);$p2=deg2rad($c);$dp=deg2rad($c-$a);$dl=deg2rad($d-$b);$h=sin($dp/2)**2+cos($p1)*cos($p2)*sin($dl/2)**2;return 2*$r*asin(min(1,sqrt($h)));}
function firstExisting(array $c,array $names):?string{foreach($names as $n)if(isset($c[$n]))return$n;return null;}
if(in_array('--self-test',$argv??[],true)){if(forms('Megasaray Resort Side (EX. Aska Side Hotel)')!==['megasaray side','aska side'])throw new RuntimeException('forms_test');if(norm('ROYAL  BEACH HOTEL & SPA 2')!=='royal beach 2')throw new RuntimeException('qualifier_test');if(km(0,0,0,0)!==0.0)throw new RuntimeException('km_test');echo "PASS\n";exit(0);}
$op=(string)getenv('OPERATION_ID');$sha=(string)getenv('MATCH_SOURCE_SHA');if($op!==HMAP_OP||!preg_match('/^[0-9a-f]{40}$/D',$sha))throw new RuntimeException('operation_guard');$root=(string)realpath(getcwd());if($root===''||basename($root)!=='anytoour.ru')throw new RuntimeException('root_guard');$base=rtrim((string)getenv('HOME'),'/').'/.anytoour-match/operations';if(!is_dir($base))throw new RuntimeException('operations_root_missing');$dir=$base.'/'.$op;if(!mkdir($dir,0700))throw new RuntimeException('operation_exists');putnew($dir.'/reservation.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'reserved_before_db_access','read_only'=>true,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);
$db=null;try{require_once dbpath($root);$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');$ic=cols($db,'andromeda_hotel_identities');$cc=cols($db,'catalog_hotels');foreach(['supplier_namespace','external_hotel_id','local_hotel_id','decision_status'] as $need)if(!isset($ic[$need]))throw new RuntimeException('identity_schema_missing_'.$need);foreach(['id','country_id','name','is_active'] as $need)if(!isset($cc[$need]))throw new RuntimeException('catalog_schema_missing_'.$need);
$identitySelect=['supplier_namespace','external_hotel_id','local_hotel_id','decision_status'];foreach(['country_id','api_name','hotel_name','name','xml_name','source_name','region_name','subregion_name','latitude','longitude','lat','lon','lng','evidence_json','evidence_sha256','catalog_sha256'] as $x)if(isset($ic[$x]))$identitySelect[]=$x;$identitySelect=array_values(array_unique($identitySelect));$pending=q($db,'SELECT '.implode(',',array_map(fn($x)=>'`'.$x.'`',$identitySelect)).' FROM andromeda_hotel_identities WHERE decision_status=? AND local_hotel_id IS NULL ORDER BY supplier_namespace,external_hotel_id',['pending']);
$catalogSelect=['id','country_id','name'];foreach(['region_name','subregion_name','latitude','longitude','lat','lon','lng','aliases_json','former_names_json'] as $x)if(isset($cc[$x]))$catalogSelect[]=$x;$catalog=q($db,'SELECT '.implode(',',array_map(fn($x)=>'`'.$x.'`',$catalogSelect)).' FROM catalog_hotels WHERE is_active=1 AND country_id IN (1,2,4,6,8,9,10,16) ORDER BY country_id,id');
$accepted=q($db,'SELECT supplier_namespace,external_hotel_id,local_hotel_id FROM andromeda_hotel_identities WHERE decision_status=? AND local_hotel_id IS NOT NULL',['accepted']);$db->exec('ROLLBACK');
$catalogByCountry=[];$catalogById=[];$formIndex=[];foreach($catalog as $h){$id=(int)$h['id'];$cid=(int)$h['country_id'];$catalogById[$id]=$h;$catalogByCountry[$cid][$id]=true;$fs=forms((string)$h['name']);foreach(['aliases_json','former_names_json'] as $jk)if(isset($h[$jk])&&is_string($h[$jk])&&trim($h[$jk])!==''){try{$j=json_decode($h[$jk],true,512,JSON_THROW_ON_ERROR);if(is_array($j))foreach($j as $x)if(is_scalar($x))$fs=array_merge($fs,forms((string)$x));}catch(Throwable){}}foreach(array_values(array_unique($fs)) as $f)$formIndex[$cid][$f][$id]=true;}
$occupied=[];foreach($accepted as $r){$local=(int)$r['local_hotel_id'];if($local>0)$occupied[(string)$r['supplier_namespace']][$local][(string)$r['external_hotel_id']]=true;}
$out=[];$counts=[];$countryCounts=[];$examined=0;$core8=0;$prepared=[];foreach($pending as $r){$examined++;$ns=(string)$r['supplier_namespace'];$ext=(string)$r['external_hotel_id'];$name=extract($r,['api_name','hotel_name','source_name','xml_name','name'],['api_name','hotel_name','source_name','xml_name','name','title']);$country=extract($r,['country_id'],['country_id','state_id','stateKey','countryKey']);$cid=iid($country['value']);$row=['supplier_namespace'=>$ns,'external_hotel_id'=>$ext,'source_name'=>$name['value'],'source_name_path'=>$name['path'],'source_country_id'=>$cid,'source_country_path'=>$country['path'],'route'=>null,'candidate_local_id'=>null,'candidate_local_name'=>null,'source_forms'=>forms($name['value']),'distance_km'=>null,'same_provider_occupancy'=>[]];if($cid===null||!in_array($cid,HMAP_CORE8,true)){$row['route']='hold_country_missing_or_noncore';$out[]=$row;$counts[$row['route']]=($counts[$row['route']]??0)+1;continue;}$core8++;$countryCounts[$cid]=($countryCounts[$cid]??0)+1;if($name['value']===null||$row['source_forms']===[]){$row['route']='hold_source_name_missing';$out[]=$row;$counts[$row['route']]=($counts[$row['route']]??0)+1;continue;}$cand=[];foreach($row['source_forms'] as $f)foreach(array_keys($formIndex[$cid][$f]??[]) as $id)$cand[(int)$id]=true;$ids=array_keys($cand);sort($ids,SORT_NUMERIC);$row['countrywide_exact_candidate_ids']=$ids;if(count($ids)!==1){$row['route']=$ids===[]?'hold_no_countrywide_exact':'hold_countrywide_exact_ambiguous';$out[]=$row;$counts[$row['route']]=($counts[$row['route']]??0)+1;continue;}$local=(int)$ids[0];$h=$catalogById[$local];$row['candidate_local_id']=$local;$row['candidate_local_name']=$h['name'];$occ=array_keys($occupied[$ns][$local]??[]);sort($occ,SORT_STRING);$row['same_provider_occupancy']=$occ;if($occ!==[]&&!in_array($ext,$occ,true)){$row['route']='hold_same_provider_occupied';$out[]=$row;$counts[$row['route']]=($counts[$row['route']]??0)+1;continue;}$sc=coord($r,'source');$hc=coord($h,'catalog');$dist=km($sc['lat'],$sc['lon'],$hc['lat'],$hc['lon']);$row['source_coordinates']=$sc;$row['local_coordinates']=$hc;$row['distance_km']=$dist===null?null:round($dist,3);if($dist!==null&&$dist>5.0){$row['route']='hold_coordinate_gt5km';$out[]=$row;$counts[$row['route']]=($counts[$row['route']]??0)+1;continue;}$row['route']='guard_passed_prepared';$prepared[]=$row;$out[]=$row;$counts[$row['route']]=($counts[$row['route']]??0)+1;}
ksort($counts);ksort($countryCounts);usort($prepared,fn($a,$b)=>[$a['source_country_id'],$a['supplier_namespace'],$a['external_hotel_id']]<=>[$b['source_country_id'],$b['supplier_namespace'],$b['external_hotel_id']]);$result=['schema'=>'hotel-match-andromeda-pending-exact-current/1','operation_id'=>$op,'source_sha'=>$sha,'state'=>'completed_read_only','server_current'=>true,'pending_total_examined'=>$examined,'core8_pending_examined'=>$core8,'core8_country_counts'=>$countryCounts,'route_counts'=>$counts,'guard_passed_prepared_count'=>count($prepared),'guard_passed_prepared'=>$prepared,'rows'=>$out,'identity_columns'=>array_keys($ic),'catalog_columns'=>array_keys($cc),'normalization'=>'exact primary/former forms; generic HOTEL/RESORT/SPA removed; significant qualifiers/numeric tokens preserved; countrywide unique; same-provider occupancy and >5km coordinates hold','safe_to_write_now'=>false,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'booking_calls'=>0,'lead_calls'=>0,'no_replay'=>true];$digest=putnew($dir.'/result.json',$result);putnew($dir.'/receipt.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'completed_read_only','result_sha256'=>$digest,'readback_verified'=>hash('sha256',(string)file_get_contents($dir.'/result.json'))===$digest,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);echo js(['state'=>'completed_read_only','pending_total_examined'=>$examined,'core8_pending_examined'=>$core8,'guard_passed_prepared_count'=>count($prepared),'route_counts'=>$counts])."\n";
}catch(Throwable $e){try{if($db instanceof PDO&&$db->inTransaction())$db->rollBack();}catch(Throwable){}$f=['operation_id'=>$op,'source_sha'=>$sha,'state'=>'failed_read_only','error_class'=>get_class($e),'error_message'=>$e->getMessage(),'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true];$digest=putnew($dir.'/failure.json',$f);putnew($dir.'/receipt.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'failed_read_only','failure_sha256'=>$digest,'readback_verified'=>true,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);fwrite(STDERR,"HMAP_FAILED ".$e->getMessage()."\n");exit(2);}
