<?php
declare(strict_types=1);
error_reporting(0);
const OP='hotel-match-anex-native-sellable-bridge-review-1971-20260912-v1';
const IDS=[32610,14952,32611,30717,32577,31627];
function norm(string $v):string{$v=mb_strtolower($v,'UTF-8');$v=strtr($v,['ё'=>'е','é'=>'e','è'=>'e','ê'=>'e','á'=>'a','à'=>'a','ä'=>'a','â'=>'a','ö'=>'o','ô'=>'o','ü'=>'u','ú'=>'u','ç'=>'c','ş'=>'s','ğ'=>'g','ı'=>'i']);preg_match_all('/[\p{L}\p{N}]+/u',$v,$m);$drop=['hotel','hotels','resort','resorts','spa','otel','the','by'];return implode(' ',array_values(array_filter($m[0]??[],fn($x)=>!in_array($x,$drop,true))));}
function coords(array $r):?array{$lat=$lon=null;foreach(['lat','latitude','geo_lat','hotel_latitude','coord_lat'] as $k)if(isset($r[$k])&&is_numeric($r[$k])){$lat=(float)$r[$k];break;}foreach(['lon','lng','longitude','geo_lon','hotel_longitude','coord_lon'] as $k)if(isset($r[$k])&&is_numeric($r[$k])){$lon=(float)$r[$k];break;}return $lat!==null&&$lon!==null?[$lat,$lon]:null;}
function km(array $a,array $b):float{$r=6371.0;$p1=deg2rad($a[0]);$p2=deg2rad($b[0]);$dp=deg2rad($b[0]-$a[0]);$dl=deg2rad($b[1]-$a[1]);$q=sin($dp/2)**2+cos($p1)*cos($p2)*sin($dl/2)**2;return 2*$r*asin(min(1,sqrt($q)));}
function geo_ok(array $a,array $h):bool{$s=mb_strtolower(trim((string)($a['api_region']??'').' '.(string)($a['api_town']??'')),'UTF-8');$t=mb_strtolower(trim((string)($h['region_name']??'').' '.(string)($h['subregion_name']??'')),'UTF-8');$map=['стамбул'=>'istanbul','istanbul'=>'istanbul','лалели'=>'laleli','laleli'=>'laleli','фатих'=>'fatih','fatih'=>'fatih','кумкапы'=>'kumkapi','kumkapi'=>'kumkapi','беязыт'=>'beyazit','beyazit'=>'beyazit'];foreach($map as $x=>$c){if(str_contains($s,$x)&&str_contains($t,$x))return true;if(str_contains($s,$x)){foreach($map as $y=>$d)if($d===$c&&str_contains($t,$y))return true;}}return str_contains($s,'стамбул')&&(str_contains($t,'стамбул')||str_contains($t,'istanbul'));}
try{$root=realpath(getcwd());if(!$root||basename($root)!=='anytoour.ru')throw new RuntimeException('root');$db=is_file($root.'/data/db-v1.php')?$root.'/data/db-v1.php':$root.'/v2/data/db-v1.php';require_once $db;$preview=$root.'/_preview/search3-anex-candidate';$app=is_file($preview.'/app/integrations/anex-search-mapping-registry.php')?$preview.'/app/integrations':$root.'/app/integrations';require_once $app.'/anex-search-mapping-registry.php';$pdo=v2_data_db();$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->exec('START TRANSACTION READ ONLY');$reg=AnyTourAnexSearchMappingRegistry::fromPdo($pdo);
$ah=$pdo->prepare('SELECT * FROM anex_hotels WHERE anex_hotel_id=? LIMIT 2');$dec=$pdo->prepare('SELECT COUNT(*) FROM anex_hotel_decisions WHERE anex_hotel_id=?');$map=$pdo->prepare('SELECT COUNT(*) FROM anex_hotel_search_mappings WHERE anex_hotel_id=?');$ex=$pdo->prepare('SELECT COUNT(*) FROM anex_review_pair_exclusions WHERE anex_hotel_id=?');$andr=$pdo->prepare("SELECT COUNT(*) FROM andromeda_hotel_identities WHERE decision_status='accepted' AND local_hotel_id=?");
$hotels=$pdo->query('SELECT * FROM catalog_hotels WHERE is_active=1')->fetchAll(PDO::FETCH_ASSOC);$aliases=$pdo->query('SELECT hotel_id,alias FROM hotel_aliases')->fetchAll(PDO::FETCH_ASSOC);$by=[];foreach($hotels as $h){$n=norm((string)($h['name']??''));if($n!=='')$by[$n][(int)$h['id']]=$h;}foreach($aliases as $x){$n=norm((string)$x['alias']);$id=(int)$x['hotel_id'];if($n!==''&&isset($by[$n])===false){foreach($hotels as $h)if((int)$h['id']===$id){$by[$n][$id]=$h;break;}}elseif($n!==''&&isset($by[$n])&& !isset($by[$n][$id])){foreach($hotels as $h)if((int)$h['id']===$id){$by[$n][$id]=$h;break;}}}
$rows=[];$counts=['safe'=>0,'already_mapped'=>0,'blocked'=>0,'needs_extra'=>0];foreach(IDS as $id){$ah->execute([$id]);$aa=$ah->fetchAll(PDO::FETCH_ASSOC);$a=count($aa)===1?$aa[0]:null;$bucket='needs_extra';$why=[];$target=null;$dist=null;$cur=$reg->resolve('anex_online',(string)$id,'preview');if(!$a){$bucket='blocked';$why[]='anex_catalog_missing_or_ambiguous';}elseif($cur!==null){$bucket='already_mapped';$target=(int)$cur;$why[]='current_mapping_exists';}else{$dec->execute([$id]);$dn=(int)$dec->fetchColumn();$map->execute([$id]);$mn=(int)$map->fetchColumn();$ex->execute([$id]);$en=(int)$ex->fetchColumn();if($dn||$mn||$en){$bucket='blocked';$why[]='manual_mapping_or_exclusion_present';}else{$n=norm((string)$a['name']);$cand=array_values($by[$n]??[]);$bridged=[];foreach($cand as $h){$andr->execute([(int)$h['id']]);if((int)$andr->fetchColumn()>0)$bridged[]=$h;}if(count($bridged)!==1){$bucket='needs_extra';$why[]='accepted_andromeda_local_candidate_count_'.count($bridged);}else{$h=$bridged[0];$target=(int)$h['id'];$ac=coords($a);$hc=coords($h);if($ac&&$hc)$dist=km($ac,$hc);if($dist!==null&&$dist>5){$bucket='blocked';$why[]='coordinate_conflict_gt_5km';}elseif($dist!==null&&$dist<=1){$bucket='safe';$why[]='exact_name_plus_accepted_andromeda_bridge_plus_direct_coord';}elseif(geo_ok($a,$h)){$bucket='safe';$why[]='exact_name_plus_accepted_andromeda_bridge_plus_geo';}else{$bucket='needs_extra';$why[]='exact_bridge_but_geo_coord_incomplete';}}}}}$counts[$bucket]++;$rows[]=['anex_id'=>$id,'name'=>$a['name']??null,'api_region'=>$a['api_region']??null,'api_town'=>$a['api_town']??null,'current_local_id'=>$cur,'target_local_id'=>$target,'coord_distance_km'=>$dist===null?null:round($dist,3),'bucket'=>$bucket,'reasons'=>$why];}
$pdo->exec('ROLLBACK');$out=['status'=>'completed','operation_id'=>OP,'counts'=>$counts,'rows'=>$rows,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true];}catch(Throwable $e){if(isset($pdo)&&$pdo instanceof PDO&&$pdo->inTransaction())$pdo->rollBack();$out=['status'=>'failed','operation_id'=>OP,'reason'=>substr($e->getMessage(),0,180),'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true];}echo 'ANSB:'.json_encode($out,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";exit(($out['status']??'')==='completed'?0:2);
