<?php
declare(strict_types=1);
if (!defined('FC_LIBRARY_ONLY')) define('FC_LIBRARY_ONLY', true);
require_once __DIR__ . '/hotel_match_post_v8_rescue_ensemble.php';
require_once __DIR__ . '/hotel_match_global_coordinate_nearest_rescue.php';

const HMPA_OPERATION='hotel-match-post-v8-combined-accept-1971-20260911-v1';
const HMPA_POST_OPERATION='hotel-match-post-v8-rescue-ensemble-1971-20260911-v1';
const HMPA_COORD_OPERATION='hotel-match-global-coordinate-nearest-rescue-1971-20260911-v1';
const HMPA_MAX_WRITES=100;

function hmpa_require_transactional(PDO $db):void{
    $tables=['catalog_hotels','catalog_hotel_details','hotel_aliases','anex_hotel_search_mappings','anex_hotel_decisions','anex_review_pair_exclusions','anex_hotels','anex_search_hotel_observations','andromeda_hotel_identities','andromeda_search_hotel_observations'];$q=$db->prepare("SELECT ENGINE FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?");foreach($tables as $t){$q->execute([$t]);$e=$q->fetchColumn();if($e===false||strcasecmp((string)$e,'InnoDB')!==0)throw new RuntimeException('required_transactional_table:'.$t);}
}
function hmpa_merge_rows(array $postRows,array $coordRows):array{
    $out=[];foreach([['post',$postRows],['coordinate',$coordRows]] as [$origin,$rows])foreach($rows as $r){$provider=(string)($r['provider']??'');$external=(string)($r['external_id']??'');$target=(int)($r['target_local_hotel_id']??0);if(!in_array($provider,['anex','andromeda'],true)||$external===''||$target<1)throw new RuntimeException('allow_row_invalid');$k=hmpv8_key($provider,$external);if(isset($out[$k]['target'])&&(int)$out[$k]['target']!==$target)throw new RuntimeException('allow_source_target_conflict');$out[$k]['target']=$target;$out[$k][$origin]=$r;}return $out;
}
function hmpa_source_rows(array $post,array $coord):array{
    if(($post['status']??null)!=='completed'||($post['operation_id']??null)!==HMPA_POST_OPERATION||($post['database_writes']??null)!==0||($post['mapping_writes']??null)!==0||($post['supplier_calls']??null)!==0||count($post['prepared']??[])!==47)throw new RuntimeException('post_source_invalid');
    if(($coord['status']??null)!=='completed'||($coord['operation_id']??null)!==HMPA_COORD_OPERATION||($coord['database_writes']??null)!==0||($coord['mapping_writes']??null)!==0||($coord['supplier_calls']??null)!==0||count($coord['prepared']??[])!==24)throw new RuntimeException('coord_source_invalid');$out=hmpa_merge_rows($post['prepared'],$coord['prepared']);if(count($out)!==64)throw new RuntimeException('allow_union_count');return$out;
}
function hmpa_identity_counts(PDO $db):array{$o=['accepted'=>0,'pending'=>0,'conflict'=>0];foreach($db->query("SELECT decision_status,COUNT(*) n FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' GROUP BY decision_status")->fetchAll(PDO::FETCH_ASSOC) as$r){$s=(string)$r['decision_status'];if(isset($o[$s]))$o[$s]=(int)$r['n'];}return$o;}
function hmpa_coordinate_safe(array $d):bool{
    if(($d['bucket']??'')!=='prepared'||!is_array($d['pair']??null)||!($d['pair']['critical_ok']??false))return false;$reason=(string)($d['reason']??'');$distance=$d['distance_m']??null;if($distance===null||(float)$distance>5000.0)return false;if($reason==='coordinate_single_token_ultratight_place')return (int)($d['pair']['shared']??0)===1&&(bool)($d['place_match']??false)&&(float)$distance<=50.0&&count(hmpv8_brand_tokens($d['pair']))>=1;if($reason==='coordinate_two_token_nearest')return (int)($d['pair']['shared']??0)>=2&&(float)$distance<=250.0&&count(hmpv8_brand_tokens($d['pair']))>=2&&(($d['pair']['anchor_ok']??false)||($d['pair']['ordered']??false));if(str_contains($reason,'exact'))return hmpv8_pair_safe($d,false);return false;
}
function hmpa_accept(PDO $db,array $post,array $coord,string $operation=HMPA_OPERATION,int $maxWrites=HMPA_MAX_WRITES):array{
    if($operation!==HMPA_OPERATION)throw new RuntimeException('operation_scope');if($maxWrites<1||$maxWrites>HMPA_MAX_WRITES)throw new RuntimeException('write_scope_limit_config');$allow=hmpa_source_rows($post,$coord);$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);hmpa_require_transactional($db);$db->exec('SET SESSION innodb_lock_wait_timeout=20');$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$before=fc_coverage($db);$beforeIdentity=hmpa_identity_counts($db);$writtenAn=[];$writtenAnd=[];$stats=['allow_sources'=>count($allow),'protected'=>0,'not_pending'=>0,'country_unknown'=>0,'target_changed'=>0,'promotion_guard_block'=>0,'source_conflict'=>0,'target_collision'=>0,'planned'=>0,'planned_anex'=>0,'planned_andromeda'=>0,'written'=>0,'written_anex'=>0,'written_andromeda'=>0,'live_written'=>0,'multi_evidence_written'=>0];$skip=[];
    try{
        $db->beginTransaction();
        $db->query("SELECT external_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='pending' AND local_hotel_id IS NULL ORDER BY external_hotel_id FOR UPDATE")->fetchAll(PDO::FETCH_COLUMN);
        $db->query('SELECT anex_hotel_id FROM anex_hotel_decisions ORDER BY anex_hotel_id FOR UPDATE')->fetchAll(PDO::FETCH_COLUMN);$db->query('SELECT anex_hotel_id FROM anex_hotel_search_mappings ORDER BY anex_hotel_id FOR UPDATE')->fetchAll(PDO::FETCH_COLUMN);$db->query('SELECT anex_hotel_id,catalog_hotel_id FROM anex_review_pair_exclusions ORDER BY anex_hotel_id,catalog_hotel_id FOR UPDATE')->fetchAll(PDO::FETCH_ASSOC);$db->query('SELECT h.id FROM catalog_hotels h WHERE h.is_active=1 AND h.country_id IN (1,2,4,8,9,10,12,16) ORDER BY h.id FOR UPDATE')->fetchAll(PDO::FETCH_COLUMN);$db->query('SELECT a.id FROM hotel_aliases a JOIN catalog_hotels h ON h.id=a.hotel_id WHERE h.is_active=1 AND h.country_id IN (1,2,4,8,9,10,12,16) ORDER BY a.id FOR UPDATE')->fetchAll(PDO::FETCH_COLUMN);
        [$hotels,$names,$strict,$broad,$places,$scope]=mbr_catalog($db);$shaCountry=fc_sha_countries($db);[$anexLocal,$andromedaLocal]=mbr_local_sets($db);$anIndex=hmgcr_build_index($anexLocal,$hotels,$names);$andIndex=hmgcr_build_index($andromedaLocal,$hotels,$names);$allSet=[];foreach(array_keys($hotels) as$id)$allSet[(int)$id]=true;$allIndex=hmgcr_build_index($allSet,$hotels,$names);[$grid,$targetCoords]=hmgcn_grid($hotels);
        $andClaims=[];foreach($db->query("SELECT external_hotel_id,local_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IS NOT NULL")->fetchAll(PDO::FETCH_ASSOC)as$r)$andClaims[(int)$r['local_hotel_id']][]=(string)$r['external_hotel_id'];$anClaims=[];foreach($db->query('SELECT anex_hotel_id,catalog_hotel_id FROM anex_hotel_search_mappings WHERE enabled=1')->fetchAll(PDO::FETCH_ASSOC)as$r)$anClaims[(int)$r['catalog_hotel_id']][]=(int)$r['anex_hotel_id'];foreach($db->query("SELECT anex_hotel_id,catalog_hotel_id FROM anex_hotel_decisions WHERE decision_status='accepted' AND catalog_hotel_id IS NOT NULL")->fetchAll(PDO::FETCH_ASSOC)as$r)$anClaims[(int)$r['catalog_hotel_id']][]=(int)$r['anex_hotel_id'];
        $manual=array_fill_keys(array_map('intval',$db->query('SELECT anex_hotel_id FROM anex_hotel_decisions')->fetchAll(PDO::FETCH_COLUMN)),true);$mapped=array_fill_keys(array_map('intval',$db->query('SELECT anex_hotel_id FROM anex_hotel_search_mappings WHERE enabled=1')->fetchAll(PDO::FETCH_COLUMN)),true);$excluded=[];foreach($db->query('SELECT anex_hotel_id,catalog_hotel_id FROM anex_review_pair_exclusions')->fetchAll(PDO::FETCH_ASSOC)as$r)$excluded[(int)$r['anex_hotel_id']][(int)$r['catalog_hotel_id']]=true;
        $andPending=[];foreach($db->query("SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='pending' AND local_hotel_id IS NULL")->fetchAll(PDO::FETCH_ASSOC)as$r)$andPending[(string)$r['external_hotel_id']]=$r;$latest=[];$andCount=[];foreach($db->query("SELECT * FROM andromeda_search_hotel_observations WHERE supplier_namespace='andromeda_catalog' ORDER BY observed_at_utc DESC,external_hotel_id")->fetchAll(PDO::FETCH_ASSOC)as$o){$id=(string)$o['external_hotel_id'];$andCount[$id]=($andCount[$id]??0)+1;if(!isset($latest[$id]))$latest[$id]=$o;}$staging=[];foreach($db->query('SELECT * FROM anex_hotels')->fetchAll(PDO::FETCH_ASSOC)as$s)$staging[(int)$s['anex_hotel_id']]=$s;$anObs=[];foreach($db->query('SELECT * FROM anex_search_hotel_observations ORDER BY search_count DESC,last_seen_utc DESC,anex_hotel_id')->fetchAll(PDO::FETCH_ASSOC)as$o){$id=(int)$o['anex_hotel_id'];if(!isset($anObs[$id]))$anObs[$id]=$o;}
        $planned=[];
        foreach($allow as$key=>$a){[$provider,$external]=explode(':',$key,2);$expected=(int)$a['target'];$valid=[];$live=false;$obsCount=0;$country=0;
            if($provider==='andromeda'){$identity=$andPending[$external]??null;if(!is_array($identity)){$stats['not_pending']++;continue;}$obs=$latest[$external]??null;$country=(int)($obs['country_id']??0);if(!isset(HMGCR_CORE8[$country]))$country=(int)($shaCountry[$identity['catalog_sha256']]??0);if(!isset(HMGCR_CORE8[$country])){$stats['country_unknown']++;continue;}$source=hmgcr_andromeda_source($identity,$obs);$sameClaims=$andClaims;$opIndex=$anIndex;$live=(int)($andCount[$external]??0)>0;$obsCount=(int)($andCount[$external]??0);}
            else{$aid=(int)$external;if(isset($manual[$aid])||isset($mapped[$aid])){$stats['protected']++;continue;}$stage=$staging[$aid]??[];$obs=$anObs[$aid]??[];$country=(int)($obs['country_id']??0);if(!isset(HMGCR_CORE8[$country]))$country=(int)(fc_country($stage['api_country']??'')??0);if(!isset(HMGCR_CORE8[$country])){$stats['country_unknown']++;continue;}$source=['names'=>array_values(array_unique(array_filter([(string)($obs['hotel_name']??''),(string)($stage['api_name']??''),(string)($stage['xml_name']??''),(string)($stage['xml_alternate_name']??'')],static fn($v)=>trim($v)!==''))),'places'=>array_values(array_unique(array_filter([(string)($stage['api_region']??''),(string)($stage['api_town']??'')],static fn($v)=>trim($v)!==''))),'latitude'=>$stage['latitude']??null,'longitude'=>$stage['longitude']??null];$sameClaims=$anClaims;$opIndex=$andIndex;$live=!empty($obs);$obsCount=(int)($obs['search_count']??0);}
            if(isset($a['post'])){foreach(($a['post']['evidence_sources']??[])as$origin){$d=null;$opp=isset(($provider==='andromeda'?$anexLocal:$andromedaLocal)[$expected]);if($origin==='cross')$d=hmgcr_decide($source,$country,$opIndex,$hotels,$names,$sameClaims,$provider==='anex'?($excluded[(int)$external]??[]):[]);elseif($origin==='tourvisor')$d=hmgtr_decide($source,$country,$allIndex,$hotels,$names,$sameClaims,$provider==='anex'?($excluded[(int)$external]??[]):[]);elseif($origin==='star'&&$provider==='andromeda'){$s=hmasbr_source($identity,$obs??null);[$ids]=hmasbr_targets($broad,$country,$s['names']);if(count($ids)===1){$tid=(int)$ids[0];$t=$hotels[$tid]??null;if($t&&isset($anexLocal[$tid])&&!isset($andClaims[$tid])){$pair=hmgcr_best_pair($s['names'],$names[$tid]??[(string)$t['name']],$s['places'],[(string)$t['region_name'],(string)$t['subregion_name']]);if(($pair['critical_ok']??false)&&count(hmpv8_brand_tokens($pair))>=1)$d=['bucket'=>'prepared','reason'=>'star_exact_opposite_bridge','target_local_hotel_id'=>$tid,'pair'=>$pair,'distance_m'=>null,'place_match'=>hmgcr_place($s['places'],[(string)$t['region_name'],(string)$t['subregion_name']])];}}}if(is_array($d)&&($d['bucket']??'')==='prepared'&&(int)($d['target_local_hotel_id']??0)===$expected&&($origin==='star'||hmpv8_pair_safe($d,$opp)))$valid[$expected]['post:'.$origin]=$d;}}
            if(isset($a['coordinate'])){$d=hmgcn_decide($source,$country,$grid,$hotels,$names,$sameClaims,$provider==='anex'?($excluded[(int)$external]??[]):[]);if(($d['bucket']??'')==='prepared'&&(int)($d['target_local_hotel_id']??0)===$expected&&hmpa_coordinate_safe($d))$valid[$expected]['coordinate']=$d;}
            if(!$valid){$stats['promotion_guard_block']++;continue;}if(count($valid)!==1){$stats['source_conflict']++;continue;}$target=(int)array_key_first($valid);if($target!==$expected||!isset($hotels[$target])||(int)$hotels[$target]['country_id']!==$country){$stats['target_changed']++;continue;}$planned[$key]=['provider'=>$provider,'external_id'=>$external,'country_id'=>$country,'live'=>$live,'observation_count'=>$obsCount,'target'=>$target,'target_name'=>$hotels[$target]['name'],'evidence'=>$valid[$target],'source_names'=>$source['names'],'source_places'=>$source['places']];}
        $by=[];foreach($planned as$k=>$r)$by[$r['provider'].':'.$r['target']][]=$k;foreach($by as$ks)if(count($ks)>1)foreach($ks as$k){unset($planned[$k]);$stats['target_collision']++;}$stats['planned']=count($planned);foreach($planned as$r)$stats[$r['provider']==='anex'?'planned_anex':'planned_andromeda']++;if(count($planned)>$maxWrites)throw new RuntimeException('write_scope_limit');
        $insertAn=$db->prepare("INSERT INTO anex_hotel_search_mappings(anex_hotel_id,catalog_hotel_id,match_class,scope,approval_policy,source_row_digest,mapping_digest,enabled) VALUES(?,?,'strong_candidate','preview',?,?,?,1)");$mapDigest=fc_hash([$operation,'post_v8_combined_current_v1']);$updateAnd=$db->prepare("UPDATE andromeda_hotel_identities SET local_hotel_id=?,decision_status='accepted',evidence_sha256=?,evidence_json=? WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=? AND decision_status='pending' AND local_hotel_id IS NULL AND evidence_sha256 <=> ?");
        foreach($planned as$k=>$r){$target=(int)$r['target'];$ev=['operation_id'=>$operation,'lane'=>'MATCH','provider'=>$r['provider'],'external_id'=>$r['external_id'],'country_id'=>$r['country_id'],'target'=>$target,'target_name'=>$r['target_name'],'source_names'=>$r['source_names'],'source_places'=>$r['source_places'],'evidence_sources'=>array_keys($r['evidence']),'server_current'=>true,'post_source_operation'=>HMPA_POST_OPERATION,'coordinate_source_operation'=>HMPA_COORD_OPERATION];if($r['provider']==='anex'){$aid=(int)$r['external_id'];if(isset($manual[$aid])||isset($mapped[$aid])||isset($excluded[$aid][$target])){$stats['protected']++;continue;}$digest=fc_hash($ev);$insertAn->execute([$aid,$target,FC_POLICY,$digest,$mapDigest]);if($insertAn->rowCount()!==1)throw new RuntimeException('anex_insert_not_one:'.$aid);$writtenAn[$aid]=['target'=>$target,'source_row_digest'=>$digest,'mapping_digest'=>$mapDigest,'live'=>$r['live'],'multi'=>count($r['evidence'])>1];$mapped[$aid]=true;$anClaims[$target][$aid]=true;$stats['written_anex']++;}
            else{$external=(string)$r['external_id'];$cur=$andPending[$external]??null;if(!is_array($cur)){$stats['not_pending']++;continue;}$prior=fc_evidence($cur['evidence_json']??'');$json=fc_json(['prior_evidence'=>$prior,'promotion'=>$ev]);$sha=hash('sha256',$json);$old=$cur['evidence_sha256']??null;$updateAnd->execute([$target,$sha,$json,$external,$old]);if($updateAnd->rowCount()!==1)throw new RuntimeException('andromeda_cas_failed:'.$external);$writtenAnd[$external]=['target'=>$target,'evidence_sha256'=>$sha,'live'=>$r['live'],'multi'=>count($r['evidence'])>1];$andClaims[$target][$external]=true;$stats['written_andromeda']++;}
            $stats['written']++;if($r['live'])$stats['live_written']++;if(count($r['evidence'])>1)$stats['multi_evidence_written']++;}
        if($stats['written']>$maxWrites)throw new RuntimeException('write_scope_limit');$db->commit();
    }catch(Throwable$e){if($db->inTransaction())$db->rollBack();throw$e;}
    $ra=$db->prepare('SELECT catalog_hotel_id,source_row_digest,mapping_digest,enabled FROM anex_hotel_search_mappings WHERE anex_hotel_id=?');foreach($writtenAn as$id=>$x){$ra->execute([(int)$id]);$a=$ra->fetch(PDO::FETCH_ASSOC);if(!$a||(int)$a['catalog_hotel_id']!==$x['target']||(int)$a['enabled']!==1||!hash_equals($x['source_row_digest'],(string)$a['source_row_digest'])||!hash_equals($x['mapping_digest'],(string)$a['mapping_digest']))throw new RuntimeException('anex_readback:'.$id);$writtenAn[$id]['readback']='verified';}
    $rd=$db->prepare("SELECT local_hotel_id,decision_status,evidence_sha256 FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=?");foreach($writtenAnd as$id=>$x){$rd->execute([(string)$id]);$a=$rd->fetch(PDO::FETCH_ASSOC);if(!$a||(int)$a['local_hotel_id']!==$x['target']||$a['decision_status']!=='accepted'||!hash_equals($x['evidence_sha256'],(string)$a['evidence_sha256']))throw new RuntimeException('andromeda_readback:'.$id);$writtenAnd[$id]['readback']='verified';}
    $after=fc_coverage($db);$afterIdentity=hmpa_identity_counts($db);return['status'=>'committed_readback_verified','operation_id'=>$operation,'database_writes'=>$stats['written'],'mapping_writes'=>$stats['written'],'supplier_calls'=>0,'historical_operations_replayed'=>false,'stats'=>$stats,'anex_rows'=>$writtenAn,'andromeda_rows'=>$writtenAnd,'before'=>['coverage'=>$before,'identity'=>$beforeIdentity],'after'=>['coverage'=>$after,'identity'=>$afterIdentity],'post_commit_readback_verified'=>count($writtenAn)+count($writtenAnd)===$stats['written']];
}
