<?php
declare(strict_types=1);
const H6_OP='hotel-match-refresh55-hold6-adjudicate-1971-20260919-v2',H6_INPUT='3144fbbfe9a886bb94954d8a12147119172f570285ae7622edf2ffb8ed16657a';
function h6_need(bool $x,string $w):void{if(!$x)throw new RuntimeException($w);}
function h6_json(mixed $v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
function h6_write(string $p,array $v):string{$b=h6_json($v)."\n";$f=fopen($p,'xb');h6_need(is_resource($f),'open');h6_need(fwrite($f,$b)===strlen($b),'write');h6_need(fflush($f),'flush');if(function_exists('fsync'))h6_need(fsync($f),'sync');fclose($f);return hash('sha256',$b);}
function h6_rows(PDO $db,string $q,array $p=[]):array{$s=$db->prepare($q);$s->execute(array_values($p));return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}
function h6_norm(string $s):string{$s=strtoupper($s);$s=preg_replace('/\bHOTEL\b/u',' ',$s);$s=preg_replace('/[^\p{L}\p{N}]+/u',' ',$s);return trim((string)preg_replace('/\s+/u',' ',$s));}
function h6_anex(array $r):?array{foreach((array)($r['operator_proofs']??[])as$p)if(is_array($p)&&($p['operator']??'')==='anex'&&(int)($p['operator_id']??0)===13){$n=(array)($p['native_proofs']??[]);if(count($n)===1&&is_array($n[0]))return['native'=>(string)($n[0]['native_token']??''),'proof'=>$p];}return null;}
function h6_int(array $r):?array{foreach((array)($r['operator_proofs']??[])as$p)if(is_array($p)&&($p['operator']??'')==='intourist'&&(int)($p['operator_id']??0)===43){$n=(array)($p['native_proofs']??[]);if(count($n)===1&&is_array($n[0])&&(string)($n[0]['fact']['operator_id']??'')==='342')return['native'=>(string)($n[0]['native_token']??''),'proof'=>$p];}return null;}
function h6_pair_name(string $sid,string $source,string $target):bool{$a=h6_norm($source);$b=h6_norm($target);if($sid==='2000034436')return $a===$b.' ZANZIBAR';if($sid==='2000063032')return $a===$b;if($sid==='2000063023')return $a===$b;if($sid==='2000092639')return false;if($sid==='2000073081'||$sid==='2000089754')return $a===$b;return false;}
if(in_array('--self-test',$argv??[],true)){h6_need(h6_pair_name('2000034436','Fruit & Spice Wellness Resort Zanzibar','FRUIT & SPICE WELLNESS RESORT'),'fruit');h6_need(h6_pair_name('2000063032','White Paradise Zanzibar','WHITE PARADISE ZANZIBAR'),'white');h6_need(h6_pair_name('2000063023','Amani Boutique Hotel','AMANI BOUTIQUE'),'amani');h6_need(!h6_pair_name('2000092639','Amani Hotel Paje','AMANI BOUTIQUE'),'amani_comp');echo"REFRESH55_HOLD6_ADJUDICATE_V2_SELFTEST_OK\n";exit(0);}
$dir=(string)getenv('MATCH_OPERATION_DIR');$root=realpath((string)getenv('ANYTOUR_ROOT'));$ip=realpath((string)getenv('MATCH_INPUT_PATH'));$sha=(string)getenv('MATCH_SOURCE_SHA');h6_need(PHP_SAPI==='cli'&&is_dir($dir)&&basename($dir)===H6_OP&&is_string($root)&&is_string($ip)&&hash_file('sha256',$ip)===H6_INPUT&&preg_match('/^[a-f0-9]{40}$/D',$sha),'runtime');
$input=json_decode((string)file_get_contents($ip),true,256,JSON_THROW_ON_ERROR);$holds=[];foreach((array)$input['rows']as$r)if(($r['state']??'')==='hold')$holds[(string)$r['samo_hotel_id']]=$r;h6_need(count($holds)===6,'hold6');$expected=['2000034436'=>49104,'2000063032'=>69340,'2000063023'=>73924,'2000092639'=>73924,'2000073081'=>81391,'2000089754'=>150945];foreach($expected as$s=>$tv)h6_need(isset($holds[$s])&&(int)$holds[$s]['tv_hotel_id']===$tv,'expected_hold');
require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION READ ONLY');
try{$sources=array_keys($holds);$targets=array_values(array_unique($expected));$natives=[];foreach($holds as$r){$a=h6_anex($r);if($a&&preg_match('/^[1-9][0-9]*$/D',$a['native']))$natives[]=$a['native'];}$sp=implode(',',array_fill(0,count($sources),'?'));$tp=implode(',',array_fill(0,count($targets),'?'));$np=implode(',',array_fill(0,count($natives),'?'));
 $src=h6_rows($db,"SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id IN ($sp)",$sources);$srcBy=[];foreach($src as$x)$srcBy[(string)$x['external_hotel_id']]=$x;
 $occ=h6_rows($db,"SELECT supplier_namespace,external_hotel_id,local_hotel_id,decision_status,catalog_sha256,evidence_sha256 FROM andromeda_hotel_identities WHERE decision_status='accepted' AND local_hotel_id IN ($tp)",$targets);$occBy=[];foreach($occ as$x)$occBy[(int)$x['local_hotel_id']][]=$x;
 $maps=$natives?h6_rows($db,"SELECT * FROM anex_hotel_search_mappings WHERE anex_hotel_id IN ($np) OR catalog_hotel_id IN ($tp)",array_merge($natives,$targets)):[];$mapBy=[];foreach($maps as$x)if((int)($x['enabled']??1)===1)$mapBy[(string)$x['anex_hotel_id']][]=$x;
 $dec=$natives?h6_rows($db,"SELECT * FROM anex_hotel_decisions WHERE anex_hotel_id IN ($np) OR catalog_hotel_id IN ($tp)",array_merge($natives,$targets)):[];$exc=$natives?h6_rows($db,"SELECT * FROM anex_review_pair_exclusions WHERE anex_hotel_id IN ($np) OR catalog_hotel_id IN ($tp)",array_merge($natives,$targets)):[];$decP=[];foreach($dec as$x)$decP[(string)$x['anex_hotel_id'].'|'.(int)$x['catalog_hotel_id']]=true;$excP=[];foreach($exc as$x)$excP[(string)$x['anex_hotel_id'].'|'.(int)$x['catalog_hotel_id']]=true;
 $rows=[];$counts=['candidate_after_adjudication'=>0,'hold'=>0];foreach($holds as$sid=>$r){$tv=(int)$r['tv_hotel_id'];$source=(array)$r['source_catalog']['hotel'];$target=(array)$r['target'];$a=h6_anex($r);$i=h6_int($r);$native=$a['native']??null;$exactMaps=[];if($native!==null)$exactMaps=array_values(array_filter($mapBy[$native]??[],fn($x)=>(int)$x['catalog_hotel_id']===$tv));$sourceCurrent=$srcBy[$sid]??null;$targetOcc=array_values(array_filter($occBy[$tv]??[],fn($x)=>!($x['supplier_namespace']==='andromeda_catalog'&&(string)$x['external_hotel_id']===$sid)));$nameOk=h6_pair_name($sid,(string)($source['name']??''),(string)($target['name']??''));$countryOk=(string)($r['source_catalog']['country']??'')===(string)($target['country_name']??'');$categoryOk=(int)($source['star']??0)===(int)($target['category']??0);$pair=($native??'').'|'.$tv;$manual=($native!==null)&&(isset($decP[$pair])||isset($excP[$pair]));$state='hold';$why=(array)($r['hold_reasons']??[]);$rule=null;
   if(in_array($sid,['2000034436','2000063032'],true)&&$i!==null&&$nameOk&&$countryOk&&$categoryOk&&$sourceCurrent===null&&$targetOcc===[]){$state='candidate_after_adjudication';$rule='independent_intourist_direct_same_samo_source';$why=[];}
   elseif($sid==='2000063023'&&$a!==null&&$nameOk&&$countryOk&&$categoryOk&&$sourceCurrent===null&&$targetOcc===[]&&count($mapBy[$native]??[])===1&&count($exactMaps)===1&&!$manual){$comp=$holds['2000092639'];$compSource=(array)$comp['source_catalog']['hotel'];$compMismatch=(int)($compSource['star']??0)!==(int)($comp['target']['category']??0)&&!h6_pair_name('2000092639',(string)($compSource['name']??''),(string)($comp['target']['name']??''));if($compMismatch){$state='candidate_after_adjudication';$rule='pair_local_amani_exact_winner';$why=[];}}
   $counts[$state]++;$rows[]=['samo_hotel_id'=>$sid,'tv_hotel_id'=>$tv,'source_name'=>$source['name']??null,'target_name'=>$target['name']??null,'original_holds'=>$r['hold_reasons'],'state'=>$state,'adjudication_rule'=>$rule,'remaining_reasons'=>$why,'name_ok'=>$nameOk,'country_ok'=>$countryOk,'category_ok'=>$categoryOk,'current_source'=>$sourceCurrent,'target_occupants'=>$targetOcc,'anex_native_id'=>$native,'anex_enabled_mapping_count'=>$native===null?null:count($mapBy[$native]??[]),'anex_exact_mapping_count'=>count($exactMaps),'anex_pair_manual_or_exclusion'=>$manual,'intourist_direct_proof'=>$i,'operator_proofs'=>$r['operator_proofs'],'source_catalog'=>$r['source_catalog'],'target'=>$target,'safe_to_write_now'=>false];}
 $db->rollBack();$out=['operation'=>H6_OP,'source_sha'=>$sha,'state'=>'completed_read_only','input_sha256'=>H6_INPUT,'captured_at_utc'=>gmdate('c'),'provider_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'state_counts'=>$counts,'rows'=>$rows];$rh=h6_write($dir.'/result.json',$out);h6_write($dir.'/receipt.json',['operation'=>H6_OP,'state'=>$out['state'],'result_sha256'=>$rh,'provider_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'readback_verified'=>true]);echo h6_json(['state_counts'=>$counts,'result_sha256'=>$rh])."\n";}
catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
