<?php
declare(strict_types=1);

putenv('MATCH_STATE_ACCEPTED_COUNTRY_TEST_LIBRARY=1');
require_once __DIR__ . '/hotel_match_state_accepted_country_consensus.php';

const MCC_OP = 'hotel-match-coordinate-current-review-1971-20260915-v2';
const MCC_GRID = 0.02;

function mcc_json(array $v): string { return json_encode($v, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n"; }
function mcc_query(PDO $db,string $sql,array $args=[]): array { $q=$db->prepare($sql);$q->execute($args);return $q->fetchAll(PDO::FETCH_ASSOC); }
function mcc_write(string $file,array $v): string { $raw=mcc_json($v);$f=@fopen($file,'x+b');if(!$f)throw new RuntimeException('exclusive_file');try{if(fwrite($f,$raw)!==strlen($raw)||!fflush($f))throw new RuntimeException('write');if(function_exists('fsync')&&!fsync($f))throw new RuntimeException('sync');rewind($f);if(stream_get_contents($f)!==$raw)throw new RuntimeException('readback');}finally{fclose($f);}return hash('sha256',$raw); }
function mcc_valid_coord($lat,$lon): bool { return is_numeric($lat)&&is_numeric($lon)&&abs((float)$lat)<=90&&abs((float)$lon)<=180&&!((float)$lat===0.0&&(float)$lon===0.0); }
function mcc_bucket(float $lat,float $lon): string { return (string)floor($lat/MCC_GRID).':'.(string)floor($lon/MCC_GRID); }
function mcc_grid(array $hotels): array { $g=[];foreach($hotels as $id=>$h){if(!mcc_valid_coord($h['latitude']??null,$h['longitude']??null))continue;$g[(int)$h['country_id']][mcc_bucket((float)$h['latitude'],(float)$h['longitude'])][(int)$id]=true;}return$g; }
function mcc_neighbor_ids(int $cid,array $p,array $grid): array { $lat=(float)$p['latitude'];$lon=(float)$p['longitude'];$a=(int)floor($lat/MCC_GRID);$b=(int)floor($lon/MCC_GRID);$ids=[];for($x=$a-1;$x<=$a+1;$x++)for($y=$b-1;$y<=$b+1;$y++)foreach(array_keys($grid[$cid]["$x:$y"]??[]) as $id)$ids[(int)$id]=true;return array_map('intval',array_keys($ids)); }
function mcc_name_stats(array $sourceNames,array $localForms): array { $best=0.0;$exact=false;$qual=false;$bestPair=null;foreach($sourceNames as $s){if(mcr_norm((string)$s)==='')continue;foreach($localForms as $l){if(mcr_norm((string)$l)==='')continue;$score=mcr_score((string)$s,(string)$l);if($score>$best){$best=$score;$bestPair=[(string)$s,(string)$l];}if(mcr_norm((string)$s)===mcr_norm((string)$l)&&mcr_qualifier_ok((string)$s,(string)$l))$exact=true;if(mcr_qualifier_ok((string)$s,(string)$l))$qual=true;}}return['score'=>$best,'exact'=>$exact,'qualifier_ok'=>$qual,'best_pair'=>$bestPair]; }
function mcc_candidate(array $sourceNames,array $points,int $cid,array $hotels,array $forms,array $grid): array {
    if(!$points)return['route'=>'needs_extra_evidence','reason'=>'missing_coordinates'];
    if(!$sourceNames)return['route'=>'needs_extra_evidence','reason'=>'missing_substantive_name'];
    $candidateIds=[];foreach($points as $p)foreach(mcc_neighbor_ids($cid,$p,$grid) as $id)$candidateIds[$id]=true;
    if(!$candidateIds)return['route'=>'needs_extra_evidence','reason'=>'no_local_coordinate_neighbor'];
    $rank=[];
    foreach(array_keys($candidateIds) as $id){if(!isset($hotels[$id]))continue;$d=[];foreach($points as $p){$v=mcr_distance($p,$hotels[$id]);if($v!==null)$d[]=$v;}if(!$d)continue;$min=min($d);$max=max($d);if($max>5.0||$max>1.0)continue;$ns=mcc_name_stats($sourceNames,$forms[$id]??[(string)$hotels[$id]['name']]);$rank[$id]=['target'=>(int)$id,'distance_km'=>$min,'max_source_distance_km'=>$max]+$ns;}
    if(!$rank)return['route'=>'needs_extra_evidence','reason'=>'no_same_country_neighbor_within_1km'];
    uasort($rank,fn($a,$b)=>($a['distance_km']<=>$b['distance_km'])?:($b['score']<=>$a['score']));$ids=array_keys($rank);$best=$rank[$ids[0]];$second=isset($ids[1])?$rank[$ids[1]]:null;$gap=$second!==null?((float)$second['distance_km']-(float)$best['distance_km']):null;$exactIds=[];foreach($rank as $id=>$v)if(($v['exact']??false)&&($v['qualifier_ok']??false))$exactIds[(int)$id]=true;$best['exact_candidate_count']=count($exactIds);$best['second_distance_km']=$second['distance_km']??null;$best['distance_gap_km']=$gap;$best['nearby_candidate_count']=count($rank);
    if(!$best['qualifier_ok'])return['route'=>'needs_extra_evidence','reason'=>'coordinate_nearest_qualifier_conflict']+$best;
    if($best['exact']&&count($exactIds)===1&&$best['distance_km']<=1.0)return['route'=>'auto_accept_candidate','reason'=>'coordinate_supported_unique_exact_name']+$best;
    if($best['score']>=0.50&&$best['distance_km']<=0.50&&($second===null||$gap>=0.15))return['route'=>'auto_accept_candidate','reason'=>'coordinate_isolated_strong_name']+$best;
    if($best['score']>=0.34&&$best['distance_km']<=0.10&&($second===null||$gap>=0.25))return['route'=>'auto_accept_candidate','reason'=>'coordinate_tight_substantive_name']+$best;
    if($best['distance_km']<=0.05&&($second===null||$gap>=0.25))return['route'=>'needs_extra_evidence','reason'=>'coordinate_high_precision_name_too_weak']+$best;
    return['route'=>'needs_extra_evidence','reason'=>'coordinate_not_isolated_or_name_weak']+$best;
}

if(getenv('MATCH_COORDINATE_REVIEW_TEST_LIBRARY')==='1')return;
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
$op=(string)getenv('MATCH_OPERATION_ID');$sha=(string)getenv('MATCH_SOURCE_SHA');if($op!==MCC_OP||!preg_match('/^[0-9a-f]{40}$/D',$sha))throw new RuntimeException('operation_or_source_guard');$home=(string)getenv('HOME');if($home==='')throw new RuntimeException('home');$dir=$home.'/.anytoour-match/operations/'.MCC_OP;$res=mcr_evidence((string)@file_get_contents($dir.'/reservation.json'));if(($res['operation_id']??'')!==MCC_OP||($res['source_sha']??'')!==$sha||($res['state']??'')!=='reserved_before_db_access')throw new RuntimeException('reservation');$root=realpath(getcwd());if(!$root||basename($root)!=='anytoour.ru')throw new RuntimeException('root');require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION READ ONLY');
try{
    $core=[];foreach(mcc_query($db,'SELECT id,name FROM catalog_countries WHERE is_active=1 ORDER BY id') as $c)if(mcr_is_core8_name((string)$c['name']))$core[(int)$c['id']]=(string)$c['name'];if(count($core)<6)throw new RuntimeException('core8');$marks=implode(',',array_fill(0,count($core),'?'));
    $hotels=[];$forms=[];foreach(mcc_query($db,"SELECT id,country_id,country_name,region_id,region_name,subregion_id,subregion_name,name,category,latitude,longitude FROM catalog_hotels WHERE is_active=1 AND country_id IN ($marks) ORDER BY country_id,id",array_keys($core)) as $h){$id=(int)$h['id'];$hotels[$id]=$h;$forms[$id]=[(string)$h['name']];}foreach(mcc_query($db,"SELECT a.hotel_id,a.alias FROM hotel_aliases a JOIN catalog_hotels h ON h.id=a.hotel_id WHERE h.is_active=1 AND h.country_id IN ($marks) ORDER BY a.hotel_id,a.id",array_keys($core)) as $a){$id=(int)$a['hotel_id'];if(isset($forms[$id]))$forms[$id][]=(string)$a['alias'];}$grid=mcc_grid($hotels);
    $all=mcc_query($db,"SELECT external_hotel_id,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' ORDER BY external_hotel_id");$accepted=mcc_query($db,"SELECT i.external_hotel_id,i.local_hotel_id,i.evidence_json,h.country_id AS local_country_id FROM andromeda_hotel_identities i JOIN catalog_hotels h ON h.id=i.local_hotel_id AND h.is_active=1 WHERE i.supplier_namespace='andromeda_catalog' AND i.decision_status='accepted' AND i.local_hotel_id IS NOT NULL ORDER BY i.external_hotel_id");$cons=msac_accepted_country_consensus($accepted,$all,$core);$inferred=$cons['inferred'];
    $pending=mcc_query($db,"SELECT supplier_namespace,external_hotel_id,evidence_sha256,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='pending' AND local_hotel_id IS NULL ORDER BY external_hotel_id");$routes=[];$candidates=[];$reason=[];$withCoords=0;
    foreach($pending as $r){$e=mcr_evidence((string)$r['evidence_json']);$sk=mcr_state_key($e);if($sk===null||!isset($inferred[$sk]))continue;$points=mcr_points($e);if($points)$withCoords++;$sel=mcc_candidate(mcr_names($e),$points,(int)$inferred[$sk]['country_id'],$hotels,$forms,$grid);$item=array_merge(['supplier_namespace'=>'andromeda_catalog','external_hotel_id'=>(string)$r['external_hotel_id'],'evidence_sha256'=>(string)$r['evidence_sha256'],'state_key'=>$sk,'inferred_country_id'=>(int)$inferred[$sk]['country_id'],'frequency'=>mcr_frequency($e)],$sel);$routes[$item['route']][]=$item;$reason[$item['reason']]=($reason[$item['reason']]??0)+1;if($item['route']==='auto_accept_candidate')$candidates[]=$item;}
    foreach($routes as &$ls)usort($ls,fn($a,$b)=>(($b['frequency']??0)<=>($a['frequency']??0))?:strcmp((string)$a['external_hotel_id'],(string)$b['external_hotel_id']));unset($ls);usort($candidates,fn($a,$b)=>(($b['frequency']??0)<=>($a['frequency']??0))?:strcmp((string)$a['external_hotel_id'],(string)$b['external_hotel_id']));ksort($routes);ksort($reason);
    $result=['schema'=>'hotel-match-coordinate-current-review/2','operation_id'=>MCC_OP,'source_sha'=>$sha,'state'=>'completed_read_only','server_current'=>true,'transaction'=>'REPEATABLE READ READ ONLY','core8_countries'=>$core,'inferred_state_count'=>count($inferred),'accepted_andromeda_rows'=>count($accepted),'pending_andromeda_rows'=>count($pending),'pending_with_coordinates'=>$withCoords,'candidate_count'=>count($candidates),'candidates'=>$candidates,'route_counts'=>array_map('count',$routes),'reason_counts'=>$reason,'routes'=>$routes,'supplier_calls'=>0,'tourvisor_calls'=>0,'external_calls'=>0,'booking_calls'=>0,'db_writes'=>0,'mapping_writes'=>0,'operator_5_writes'=>0,'no_replay'=>true,'created_at'=>gmdate('c')];$hash=mcc_write($dir.'/result.json',$result);$raw=(string)file_get_contents($dir.'/result.json');$x=mcr_evidence($raw);if(hash('sha256',$raw)!==$hash||($x['state']??'')!=='completed_read_only'||($x['operation_id']??'')!==MCC_OP)throw new RuntimeException('result_readback');mcc_write($dir.'/receipt.json',['operation_id'=>MCC_OP,'source_sha'=>$sha,'state'=>'completed_read_only','result_sha256'=>$hash,'readback_verified'=>true,'no_replay'=>true,'created_at'=>gmdate('c')]);$db->rollBack();echo 'MATCH_COORDINATE_CURRENT_REVIEW_OK '.count($candidates)."\n";
}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw$e;}
