<?php
declare(strict_types=1);
/** MATCH #1971: CURRENT read-only reconciliation of v4 multi-operator native-id evidence. */
const HMNR_OP='hotel-match-tv-multiop-native-reconcile-1971-20260916-v1-egypt';
const HMNR_ROWS=[
 ['provider'=>'Biblioglobus','tv_operator_id'=>18,'local'=>159,'anex'=>44562,'kind'=>'f4','values'=>['102632942908']],
 ['provider'=>'Biblioglobus','tv_operator_id'=>18,'local'=>14140,'anex'=>19226,'kind'=>'f4','values'=>['102610157319']],
 ['provider'=>'Biblioglobus','tv_operator_id'=>18,'local'=>73342,'anex'=>28563,'kind'=>'f4','values'=>['102610163311']],
 ['provider'=>'Biblioglobus','tv_operator_id'=>18,'local'=>97122,'anex'=>37048,'kind'=>'f4','values'=>['102610227697','102610303345']],
 ['provider'=>'Biblioglobus','tv_operator_id'=>18,'local'=>151784,'anex'=>43850,'kind'=>'f4','values'=>['102610310057']],
 ['provider'=>'Biblioglobus','tv_operator_id'=>18,'local'=>129,'anex'=>30600,'kind'=>'f4','values'=>['102610180230']],
 ['provider'=>'Biblioglobus','tv_operator_id'=>18,'local'=>83106,'anex'=>37012,'kind'=>'f4','values'=>['102610227700']],
 ['provider'=>'Biblioglobus','tv_operator_id'=>18,'local'=>488,'anex'=>4131,'kind'=>'f4','values'=>['102647306711']],
 ['provider'=>'Biblioglobus','tv_operator_id'=>18,'local'=>464,'anex'=>780,'kind'=>'f4','values'=>['102632819833']],
 ['provider'=>'Biblioglobus','tv_operator_id'=>18,'local'=>21636,'anex'=>36906,'kind'=>'f4','values'=>['102625686106']],
 ['provider'=>'Fun&Sun','tv_operator_id'=>25,'local'=>125,'anex'=>1361,'kind'=>'hotels','values'=>['266454']],
 ['provider'=>'Fun&Sun','tv_operator_id'=>25,'local'=>293,'anex'=>28396,'kind'=>'hotels','values'=>['18688']],
 ['provider'=>'Intourist','tv_operator_id'=>43,'local'=>186,'anex'=>1769,'kind'=>'hotels','values'=>['25192']],
 ['provider'=>'Intourist','tv_operator_id'=>43,'local'=>190,'anex'=>1771,'kind'=>'hotels','values'=>['25958']],
];
function nr_json(array$v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
function nr_write(string$p,array$v):string{$raw=nr_json($v)."\n";$f=@fopen($p,'x');if(!$f)throw new RuntimeException('durable_create_failed');try{if(fwrite($f,$raw)!==strlen($raw))throw new RuntimeException('durable_write_failed');fflush($f);}finally{fclose($f);}if(file_get_contents($p)!==$raw)throw new RuntimeException('durable_readback_failed');return hash('sha256',$raw);}
function nr_db_path(string$r):string{foreach([$r.'/data/db-v1.php',$r.'/v2/data/db-v1.php']as$p)if(is_file($p))return$p;throw new RuntimeException('db_bootstrap_missing');}
function nr_select(PDO$d,string$q,array$p=[]):array{$s=$d->prepare($q);$s->execute($p);return$s->fetchAll(PDO::FETCH_ASSOC);}
function nr_pick(array$r,array$keys){$o=[];foreach($keys as$k)if(array_key_exists($k,$r))$o[$k]=$r[$k];return$o;}
function nr_norm($v):string{$s=mb_strtolower(trim((string)$v),'UTF-8');$s=preg_replace('/\b(?:hotel|resort|spa)\b/iu',' ',$s)??$s;$s=preg_replace('/[^\pL\pN]+/u',' ',$s)??$s;return trim(preg_replace('/\s+/u',' ',$s)??$s);}
function nr_variants(array$r):array{$o=[];foreach($r['values']as$v){$v=(string)$v;$o[]=['variant'=>'raw','value'=>$v];if($r['provider']==='Biblioglobus'&&preg_match('/^102([1-9][0-9]{8})$/D',$v,$m))$o[]=['variant'=>'strip_102_prefix','value'=>$m[1]];}return$o;}
if(in_array('--self-test',$argv??[],true)){$x=nr_variants(['provider'=>'Biblioglobus','values'=>['102610157319']]);if(($x[1]['value']??'')!=='610157319')throw new RuntimeException('suffix_test');if(nr_norm('TEST Hotel & Spa')!=='test')throw new RuntimeException('norm_test');echo"hotel_match_tv_multiop_native_reconcile_v1 self-test PASS\n";exit(0);}
$op=(string)getenv('OPERATION_ID');$sha=(string)getenv('MATCH_SOURCE_SHA');if($op!==HMNR_OP||!preg_match('/^[0-9a-f]{40}$/D',$sha))throw new RuntimeException('operation_guard');$root=(string)realpath(getcwd());if($root===''||basename($root)!=='anytoour.ru')throw new RuntimeException('root_guard');$base=rtrim((string)getenv('HOME'),'/').'/.anytoour-match/operations';if(!is_dir($base))throw new RuntimeException('operations_root_missing');$dir=$base.'/'.$op;if(!mkdir($dir,0700))throw new RuntimeException('operation_exists');nr_write($dir.'/reservation.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'reserved_before_db_access','read_only'=>true,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);
$db=null;try{require_once nr_db_path($root);$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');
 $tables=[];foreach(['andromeda_hotel_identities','catalog_hotels','anex_hotel_search_mappings','anex_hotel_decisions','anex_review_pair_exclusions']as$t){$q=$db->query('SHOW TABLES LIKE '.$db->quote($t));$tables[$t]=$q&&$q->fetchColumn()!==false;}foreach($tables as$t=>$ok)if(!$ok)throw new RuntimeException('missing_table_'.$t);
 $catalog=[];foreach(nr_select($db,'SELECT id,country_id,name,region_name,subregion_name FROM catalog_hotels WHERE id IN (159,14140,73342,97122,151784,129,83106,488,464,21636,125,293,186,190)')as$r)$catalog[(int)$r['id']]=$r;
 $mapped=[];foreach(nr_select($db,'SELECT anex_hotel_id,catalog_hotel_id FROM anex_hotel_search_mappings WHERE anex_hotel_id IN (44562,19226,28563,37048,43850,30600,37012,4131,780,36906,1361,28396,1769,1771)')as$r)$mapped[(int)$r['anex_hotel_id']]=(int)$r['catalog_hotel_id'];
 $manual=[];foreach(nr_select($db,'SELECT anex_hotel_id FROM anex_hotel_decisions WHERE anex_hotel_id IN (44562,19226,28563,37048,43850,30600,37012,4131,780,36906,1361,28396,1769,1771)')as$r)$manual[(int)$r['anex_hotel_id']]=true;
 $ex=[];foreach(nr_select($db,'SELECT anex_hotel_id,catalog_hotel_id FROM anex_review_pair_exclusions WHERE anex_hotel_id IN (44562,19226,28563,37048,43850,30600,37012,4131,780,36906,1361,28396,1769,1771)')as$r)$ex[(int)$r['anex_hotel_id']][(int)$r['catalog_hotel_id']]=true;
 $allVals=[];foreach(HMNR_ROWS as$r)foreach(nr_variants($r)as$v)$allVals[$v['value']]=true;$vals=array_keys($allVals);$ph=implode(',',array_fill(0,count($vals),'?'));
 $hits=nr_select($db,"SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace LIKE 'operator\\_%' AND external_hotel_id IN ($ph) ORDER BY supplier_namespace,external_hotel_id",$vals);
 $db->exec('ROLLBACK');
 $byExt=[];foreach($hits as$h)$byExt[(string)$h['external_hotel_id']][]=$h;$out=[];$cert=[];
 foreach(HMNR_ROWS as$r){$local=(int)$r['local'];$aid=(int)$r['anex'];$c=$catalog[$local]??[];$row=['provider'=>$r['provider'],'tv_operator_id'=>$r['tv_operator_id'],'link_field'=>$r['kind'],'local_hotel_id'=>$local,'local_hotel_name'=>$c['name']??null,'country_id'=>isset($c['country_id'])?(int)$c['country_id']:null,'region_name'=>$c['region_name']??null,'subregion_name'=>$c['subregion_name']??null,'source_anex_id'=>$aid,'source_current'=>['mapped_local_id'=>$mapped[$aid]??null,'manual_protected'=>isset($manual[$aid]),'pair_excluded'=>isset($ex[$aid][$local])],'observed_value_count'=>count($r['values']),'variants'=>[],'route'=>'no_registry_hit'];$same=[];$diff=[];$pending=[];
  foreach(nr_variants($r)as$v){$vr=$v+['registry_hits'=>[]];foreach($byExt[$v['value']]??[]as$h){$sl=$h['local_hotel_id']===null?null:(int)$h['local_hotel_id'];$status=(string)($h['decision_status']??'');$name='';foreach(['api_name','hotel_name','name','xml_name','source_name']as$nk)if(isset($h[$nk])&&trim((string)$h[$nk])!==''){$name=(string)$h[$nk];break;}$hit=nr_pick($h,['supplier_namespace','external_hotel_id','local_hotel_id','decision_status','country_id','api_name','hotel_name','name','xml_name','region_name','subregion_name']);$hit['source_name_best']=$name;$hit['normalized_name_match']=$name!==''&&isset($c['name'])&&nr_norm($name)===nr_norm($c['name']);$vr['registry_hits'][]=$hit;if($sl===$local&&$status==='accepted')$same[]=['variant'=>$v['variant'],'value'=>$v['value'],'namespace'=>$h['supplier_namespace'],'name_match'=>$hit['normalized_name_match']];elseif($sl===null)$pending[]=['variant'=>$v['variant'],'value'=>$v['value'],'namespace'=>$h['supplier_namespace'],'status'=>$status,'name_match'=>$hit['normalized_name_match']];else$diff[]=['variant'=>$v['variant'],'value'=>$v['value'],'namespace'=>$h['supplier_namespace'],'status'=>$status,'local_hotel_id'=>$sl,'name_match'=>$hit['normalized_name_match']];} $row['variants'][]=$vr;}
  if(isset($mapped[$aid]))$row['route']=$mapped[$aid]===$local?'source_already_mapped_same':'source_mapping_conflict';elseif(isset($manual[$aid]))$row['route']='source_manual_hold';elseif(isset($ex[$aid][$local]))$row['route']='source_pair_excluded';elseif(count($same)===1&&count($diff)===0&&count($r['values'])===1)$row['route']='cross_provider_same_local_accepted';elseif(count($same)>0)$row['route']='cross_provider_same_local_ambiguous';elseif(count($pending)>0&&count($diff)===0)$row['route']='registry_pending_candidate';elseif(count($diff)>0)$row['route']='registry_different_local_hold';$row['same_local_accepted']=$same;$row['pending_hits']=$pending;$row['different_local_hits']=$diff;$out[]=$row;
  foreach($same as$s){$k=$r['provider'].'|'.$s['variant'].'|'.$s['namespace'];$cert[$k]['provider']=$r['provider'];$cert[$k]['variant']=$s['variant'];$cert[$k]['namespace']=$s['namespace'];$cert[$k]['same_local_accepted_count']=($cert[$k]['same_local_accepted_count']??0)+1;$cert[$k]['locals'][$local]=true;$cert[$k]['name_matches']=($cert[$k]['name_matches']??0)+($s['name_match']?1:0);}
 }
 $certOut=[];foreach($cert as$x){$x['distinct_local_count']=count($x['locals']??[]);unset($x['locals']);$x['strong_transform_evidence']=$x['distinct_local_count']>=2;$certOut[]=$x;}usort($certOut,static fn($a,$b)=>($b['distinct_local_count']<=>$a['distinct_local_count'])?:strcmp($a['provider'].'|'.$a['variant'].'|'.$a['namespace'],$b['provider'].'|'.$b['variant'].'|'.$b['namespace']));
 $counts=[];foreach($out as$r)$counts[$r['route']]=($counts[$r['route']]??0)+1;ksort($counts);$prepared=array_values(array_filter($out,static fn($r)=>$r['route']==='cross_provider_same_local_accepted'));
 $result=['schema'=>'hotel-match-tv-multiop-native-reconcile/1','operation_id'=>$op,'source_sha'=>$sha,'state'=>'completed_read_only','server_current'=>true,'input_rows'=>count(HMNR_ROWS),'registry_hit_rows'=>count($hits),'route_counts'=>$counts,'transform_certificates'=>$certOut,'prepared_cross_provider_count'=>count($prepared),'prepared_cross_provider'=>$prepared,'rows'=>$out,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'booking_calls'=>0,'lead_calls'=>0,'safe_to_write_now'=>false,'no_replay'=>true];$digest=nr_write($dir.'/result.json',$result);nr_write($dir.'/receipt.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'completed_read_only','result_sha256'=>$digest,'readback_verified'=>hash('sha256',(string)file_get_contents($dir.'/result.json'))===$digest,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);echo nr_json(['state'=>'completed_read_only','registry_hit_rows'=>count($hits),'route_counts'=>$counts,'transform_certificates'=>$certOut,'prepared_cross_provider_count'=>count($prepared)])."\n";
}catch(Throwable$e){if($db instanceof PDO&&$db->inTransaction())$db->rollBack();$f=['operation_id'=>$op,'source_sha'=>$sha,'state'=>'failed_read_only','error_class'=>get_class($e),'error_sha256'=>hash('sha256',$e->getMessage()),'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true];$digest=nr_write($dir.'/failure.json',$f);nr_write($dir.'/receipt.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'failed_read_only','failure_sha256'=>$digest,'readback_verified'=>true,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);fwrite(STDERR,"HMNR_FAILED\n");exit(2);}
