<?php
declare(strict_types=1);
const OP='hotel-match-current-live-frequency-dossier-1971-20260917-v2';
function rq($v,$m){if(!$v)throw new RuntimeException($m);}
function q(PDO $d,string $s,array $a=[]):array{$p=$d->prepare($s);$p->execute(array_values($a));$r=$p->fetchAll(PDO::FETCH_ASSOC);rq(count($r)<=25000,'row_budget');return$r;}
function chunkq(PDO $d,string $pre,array $ids,string $post=')'):array{$o=[];foreach(array_chunk($ids,600) as$c){$ph=implode(',',array_fill(0,count($c),'?'));foreach(q($d,$pre.$ph.$post,$c)as$r)$o[]=$r;}return$o;}
function norm(string $s):string{$s=mb_strtoupper(trim($s),'UTF-8');$s=preg_replace('/\bEX\.?\s*/u',' ',$s);$s=preg_replace('/[^\pL\pN]+/u',' ',$s);$p=preg_split('/\s+/u',trim($s))?:[];return implode(' ',array_values(array_filter($p,fn($x)=>$x!==''&&$x!=='HOTEL')));}
function protectedEvidence($v,$k='',$d=0):bool{if($d>24)return true;if(is_array($v)){foreach($v as$k2=>$x)if(protectedEvidence($x,(string)$k2,$d+1))return true;return false;}if(!preg_match('/manual|exclude|exclusion|conflict|reject|review/i',$k))return false;if(is_bool($v))return$v;if(is_numeric($v))return(float)$v!=0;return is_string($v)&&!in_array(mb_strtolower(trim($v),'UTF-8'),['','false','none','no','null','pending'],true);}
function findv($v,array $keys,int $d=0){if($d>16||!is_array($v))return null;foreach($keys as$k)if(array_key_exists($k,$v)&&!is_array($v[$k])&&$v[$k]!==null&&trim((string)$v[$k])!=='')return$v[$k];foreach($v as$x)if(is_array($x)){ $r=findv($x,$keys,$d+1); if($r!==null)return$r; }return null;}
function sourceFields(array $e,string $ns):array{if(str_starts_with($ns,'operator_')&&isset($e['provider_bridges'][0])&&is_array($e['provider_bridges'][0])){$b=$e['provider_bridges'][0];return['name'=>trim((string)($b['hotel_name']??'')),'country'=>(int)($b['country_id']??0),'place'=>trim((string)($b['subregion_name']??$b['region_name']??$b['place']??'')),'lat'=>is_numeric($b['latitude']??null)?(float)$b['latitude']:null,'lon'=>is_numeric($b['longitude']??null)?(float)$b['longitude']:null];}$name=(string)(findv($e,['hotel_name','hotelName','source_hotel_name','supplier_hotel_name'])??'');if(trim($name)==='')$name=(string)(findv($e,['name'])??'');$lat=findv($e,['latitude','lat']);$lon=findv($e,['longitude','lon','lng']);return['name'=>trim($name),'country'=>(int)(findv($e,['country_id','countryId','source_country_id'])??0),'place'=>trim((string)(findv($e,['subregion_name','subregionName','region_name','regionName','resort_name','resortName','place','town_name','townName'])??'')),'lat'=>is_numeric($lat)?(float)$lat:null,'lon'=>is_numeric($lon)?(float)$lon:null];}
function distanceKm(?float $a,?float $o,?float $b,?float $p):?float{if($a===null||$o===null||$b===null||$p===null)return null;$d1=deg2rad($b-$a);$d2=deg2rad($p-$o);$x=sin($d1/2)**2+cos(deg2rad($a))*cos(deg2rad($b))*sin($d2/2)**2;return 12742*asin(min(1,sqrt($x)));}
$sha=(string)getenv('MATCH_SOURCE_SHA');rq(getenv('MATCH_OPERATION_ID')===OP&&preg_match('/^[a-f0-9]{40}$/D',$sha),'guard');$dir=(string)getenv('HOME').'/.anytoour-match/operations/'.OP;$rv=json_decode((string)file_get_contents($dir.'/reservation.json'),true,32,JSON_THROW_ON_ERROR);rq(($rv['state']??'')==='reserved_before_db_access'&&($rv['source_sha']??'')===$sha,'reservation');$db=null;$out=['operation_id'=>OP,'source_sha'=>$sha,'state'=>'failed_no_replay','database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'samo_andromeda_calls'=>0,'no_replay'=>true];
try{$root=realpath(getcwd());rq(is_string($root)&&basename($root)==='anytoour.ru','root');require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');
$pending=q($db,"SELECT supplier_namespace,external_hotel_id,evidence_sha256,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace IN ('andromeda_catalog','operator_315','operator_342','operator_5') AND decision_status='pending' AND local_hotel_id IS NULL ORDER BY supplier_namespace,external_hotel_id");
$freq=q($db,"SELECT hotel_id,COUNT(*) rows_total,COUNT(DISTINCT search_id) searches,MAX(observed_at) last_seen,COUNT(DISTINCT operator_id) operators FROM tour_price_observations WHERE observed_at>=UTC_TIMESTAMP()-INTERVAL 30 DAY GROUP BY hotel_id");$ids=array_values(array_unique(array_map(fn($x)=>(int)$x['hotel_id'],$freq)));rq(count($ids)>0&&count($ids)<10000,'live_id_budget');
$hotels=chunkq($db,"SELECT id,country_id,name,region_name,subregion_name,latitude,longitude FROM catalog_hotels WHERE is_active=1 AND id IN (",$ids);
$aliases=chunkq($db,"SELECT a.hotel_id,a.alias,h.country_id FROM hotel_aliases a JOIN catalog_hotels h ON h.id=a.hotel_id WHERE h.is_active=1 AND a.hotel_id IN (",$ids);
$occ=q($db,"SELECT supplier_namespace,local_hotel_id,COUNT(*) c FROM andromeda_hotel_identities WHERE supplier_namespace IN ('andromeda_catalog','operator_315','operator_342','operator_5') AND decision_status='accepted' AND local_hotel_id IS NOT NULL GROUP BY supplier_namespace,local_hotel_id");$db->exec('ROLLBACK');
$map=[];$byId=[];foreach($hotels as$h){$id=(int)$h['id'];$byId[$id]=$h;$k=(int)$h['country_id'].'|'.norm((string)$h['name']);if(!str_ends_with($k,'|'))$map[$k][$id]=1;}foreach($aliases as$a){$k=(int)$a['country_id'].'|'.norm((string)$a['alias']);if(!str_ends_with($k,'|'))$map[$k][(int)$a['hotel_id']]=1;}$fm=[];foreach($freq as$f)$fm[(int)$f['hotel_id']]=$f;$om=[];foreach($occ as$x)$om[(string)$x['supplier_namespace'].'|'.(int)$x['local_hotel_id']]=(int)$x['c'];
$c=['pending_total'=>count($pending),'live_local_ids'=>count($ids),'source_extractable'=>0,'unique_exact_name_country'=>0,'live_observed_candidate'=>0,'strict_geo_live'=>0,'name_live_needs_geo'=>0,'protected'=>0,'occupied'=>0,'coord_conflict_gt5km'=>0];$rows=[];
foreach($pending as$p){$e=json_decode((string)$p['evidence_json'],true,64,JSON_THROW_ON_ERROR);rq(is_array($e),'evidence_shape');$s=sourceFields($e,(string)$p['supplier_namespace']);if($s['name']===''||$s['country']<=0)continue;$c['source_extractable']++;$cand=array_keys($map[$s['country'].'|'.norm($s['name'])]??[]);if(count($cand)!==1)continue;$c['unique_exact_name_country']++;$id=(int)$cand[0];$f=$fm[$id]??null;$h=$byId[$id]??null;if(!$f||!$h)continue;$c['live_observed_candidate']++;$prot=protectedEvidence($e);if($prot)$c['protected']++;$occupied=($om[(string)$p['supplier_namespace'].'|'.$id]??0)>0;if($occupied)$c['occupied']++;$dist=distanceKm($s['lat'],$s['lon'],is_numeric($h['latitude'])?(float)$h['latitude']:null,is_numeric($h['longitude'])?(float)$h['longitude']:null);$place=norm($s['place']);$geo=$place!==''&&($place===norm((string)$h['region_name'])||$place===norm((string)$h['subregion_name']));$good=$dist!==null&&$dist<=1;$bad=$dist!==null&&$dist>5;if($bad)$c['coord_conflict_gt5km']++;$strict=!$prot&&!$occupied&&!$bad&&($good||$geo);if($strict)$c['strict_geo_live']++;elseif(!$prot&&!$occupied&&!$bad)$c['name_live_needs_geo']++;$rows[]=['supplier_namespace'=>(string)$p['supplier_namespace'],'external_hotel_id'=>(string)$p['external_hotel_id'],'source_name'=>$s['name'],'country_id'=>$s['country'],'source_place'=>$s['place']?:null,'candidate_local_id'=>$id,'candidate_name'=>(string)$h['name'],'candidate_region'=>$h['region_name'],'candidate_subregion'=>$h['subregion_name'],'distance_km'=>$dist===null?null:round($dist,3),'geo_name_match'=>$geo,'coord_le1km'=>$good,'coord_gt5km'=>$bad,'protected'=>$prot,'namespace_occupied'=>$occupied,'live_searches'=>(int)$f['searches'],'live_rows'=>(int)$f['rows_total'],'live_operators'=>(int)$f['operators'],'last_seen'=>$f['last_seen'],'classification'=>$strict?'strict_geo_live':((!$prot&&!$occupied&&!$bad)?'name_live_needs_geo':'held'),'source_evidence_sha256'=>(string)$p['evidence_sha256']];}
usort($rows,fn($a,$b)=>[$b['classification']==='strict_geo_live',$b['live_searches'],$b['live_rows']]<=>[$a['classification']==='strict_geo_live',$a['live_searches'],$a['live_rows']]);$out['state']='completed_read_only';$out['counts']=$c;$out['strict_geo_live']=array_values(array_filter($rows,fn($x)=>$x['classification']==='strict_geo_live'));$out['top_name_live_needs_geo']=array_slice(array_values(array_filter($rows,fn($x)=>$x['classification']==='name_live_needs_geo')),0,120);$out['read_at_utc']=gmdate('c');}catch(Throwable $e){if($db instanceof PDO&&$db->inTransaction())$db->rollBack();$out['error_code']=preg_match('/^[a-z_]{2,100}$/D',$e->getMessage())?$e->getMessage():'sanitized_failure';}
$raw=json_encode($out,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";file_put_contents($dir.'/result.json',$raw,LOCK_EX);$hash=hash('sha256',$raw);file_put_contents($dir.'/receipt.json',json_encode(['operation_id'=>OP,'source_sha'=>$sha,'state'=>$out['state'],'result_sha256'=>$hash,'readback_verified'=>true,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'samo_andromeda_calls'=>0,'no_replay'=>true],JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT)."\n",LOCK_EX);echo json_encode(['state'=>$out['state'],'error_code'=>$out['error_code']??null,'counts'=>$out['counts']??[],'strict_geo_live'=>array_slice($out['strict_geo_live']??[],0,30),'top_name_live_needs_geo'=>array_slice($out['top_name_live_needs_geo']??[],0,25),'result_sha256'=>$hash],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";if($out['state']!=='completed_read_only')exit(2);
