<?php
declare(strict_types=1);
const MARK='MATCH_OLD_TV_TOUR_DETAIL_JSON:';
function enc(array $x):string{return json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
function once(string$p,array$x):string{$s=enc($x)."\n";$f=@fopen($p,'x');if(!$f)throw new RuntimeException('durable_create_failed');fwrite($f,$s);fflush($f);fclose($f);if(file_get_contents($p)!==$s)throw new RuntimeException('durable_readback_failed');return hash('sha256',$s);}
function ident($v):?int{if(is_bool($v)||!is_scalar($v))return null;$s=trim((string)$v);return preg_match('/^[1-9][0-9]{0,20}$/D',$s)?(int)$s:null;}
function txt($v):string{if(!is_scalar($v))return'';$s=trim((string)(preg_replace('/\s+/u',' ',(string)$v)??''));return function_exists('mb_substr')?mb_substr($s,0,200,'UTF-8'):substr($s,0,200);}
function nm($v):string{if(is_scalar($v))return txt($v);if(!is_array($v))return'';foreach(['name','fullName','russianName','title','label']as$k)if(isset($v[$k])&&txt($v[$k])!=='')return txt($v[$k]);return'';}
function link_identity(string$u):?array{$p=parse_url($u);if(!is_array($p)||strtolower((string)($p['scheme']??''))!=='https')return null;$host=strtolower((string)($p['host']??''));$path=(string)($p['path']??'');$field=null;if($host==='agent.anextour.ru'&&$path==='/search/tour')$field='HOTELLIST';if($host==='online.anextour.ru'&&in_array($path,['/search','/search/'],true))$field='hotelCode';if($field===null)return null;$pairs=[];parse_str((string)($p['query']??''),$pairs);foreach($pairs as$k=>$v)if(strcasecmp((string)$k,$field)===0&&($i=ident($v))!==null)return['host'=>$host,'path'=>$path,'field'=>$field,'anex_hotel_id'=>$i];return null;}
function client_path(string$r):string{foreach([$r.'/data/tourvisor-client-v1.php',$r.'/v2/data/tourvisor-client-v1.php']as$p)if(is_file($p))return$p;throw new RuntimeException('tourvisor_client_missing');}
if(in_array('--self-test',$argv??[],true)){if((link_identity('https://online.anextour.ru/search?hotelCode=4158')['anex_hotel_id']??0)!==4158)throw new RuntimeException('link');echo"tour-detail-probe PASS\n";exit;}
$op=(string)getenv('OPERATION_ID');$sha=(string)getenv('MATCH_SOURCE_SHA');$raw=(string)getenv('MATCH_TOUR_IDS');if(!preg_match('/^hotel-match-old-tv-tour-detail-1971-20260914-v1-egypt$/D',$op)||!preg_match('/^[0-9a-f]{40}$/D',$sha))throw new RuntimeException('identity_guard');$ids=[];foreach(explode(',',$raw)as$x)if(($i=ident($x))!==null)$ids[$i]=$i;$ids=array_values($ids);if(!$ids||count($ids)>12)throw new RuntimeException('tour_ids_guard');
$root=(string)realpath(getcwd());if($root===''||basename($root)!=='anytoour.ru')throw new RuntimeException('root_guard');$base=rtrim((string)getenv('HOME'),'/').'/.anytoour-match/operations';$out=$base.'/'.$op;if(!is_dir($base)||!mkdir($out,0700))throw new RuntimeException('operation_exists');once($out.'/reservation.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'reserved_before_supplier_access','credential_identifier'=>'TOURVISOR_JWT','input_tour_count'=>count($ids),'tour_ids_sha256'=>hash('sha256',implode(',',$ids)),'read_only'=>true,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true]);
$calls=0;$rows=[];$blocked=[];
try{require_once client_path($root);foreach($ids as$tid){try{$calls++;$d=v2_data_tv_get('/tours/'.$tid,['currency'=>'RUB']);$link=txt($d['operatorLink']??'');$identity=$link!==''?link_identity($link):null;$h=is_array($d['hotel']??null)?$d['hotel']:[];$rows[]=['tour_id'=>(string)$tid,'tourvisor_hotel_id'=>ident($h['id']??null),'hotel_name'=>nm($h),'operator_name'=>nm($d['operator']??null),'operator_link_present'=>$link!=='','operator_identity'=>$identity,'top_keys'=>array_values(array_slice(array_keys($d),0,80))];}catch(Throwable$e){$m=$e->getMessage();$blocked[]=['tour_id'=>(string)$tid,'reason'=>str_contains($m,'429')?'http_429':(str_contains($m,'400')?'http_400':(str_contains($m,'404')?'http_404':'detail_error'))];if(str_contains($m,'429'))break;}}$barcelo=null;foreach($rows as$r)if(($r['tourvisor_hotel_id']??0)===37412){$barcelo=$r;break;}$res=['operation_id'=>$op,'source_sha'=>$sha,'status'=>'completed','credential_identifier'=>'TOURVISOR_JWT','tourvisor_calls'=>$calls,'detail_rows'=>count($rows),'strict_identity_rows'=>count(array_filter($rows,static fn($r)=>is_array($r['operator_identity']??null))),'blocked_rows'=>$blocked,'barcelo_control'=>$barcelo,'rows'=>$rows,'database_writes'=>0,'mapping_writes'=>0,'raw_provider_bodies_recorded'=>false,'token_values_recorded'=>false,'no_replay'=>true];}catch(Throwable$e){$res=['operation_id'=>$op,'source_sha'=>$sha,'status'=>'blocked','reason'=>'bootstrap_error','tourvisor_calls'=>$calls,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true];}
$rh=once($out.'/result.json',$res);once($out.'/receipt.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>$res['status'],'result_sha256'=>$rh,'readback_verified'=>hash('sha256',(string)file_get_contents($out.'/result.json'))===$rh,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true]);echo MARK.enc($res)."\n";exit($res['status']==='completed'?0:2);
