<?php
declare(strict_types=1);

const V38_OP='hotel-match-samo-registry-consensus-1971-20260925-v38';
const V38_FRONTIER_TOTAL=1737;
const V38_FRONTIER_SHA='5001297e29a920acc2d565e45fec0e4d0a5b2244e0ba60a860941be882ad1c77';
const V38_NS=['operator_5'=>5,'operator_115'=>115,'operator_315'=>315,'operator_342'=>342];
const V38_TV_DIRECT=['operator_315'=>true,'operator_342'=>true];

function v38_need(bool $v,string $m):void{if(!$v)throw new RuntimeException($m);}
function v38_json(mixed $v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
function v38_save(string $p,array $v):string{$raw=v38_json($v)."\n";$f=@fopen($p,'x+b');v38_need($f!==false,'exclusive_create');try{v38_need(fwrite($f,$raw)===strlen($raw)&&fflush($f),'durable_write');if(function_exists('fsync'))v38_need(fsync($f),'durable_sync');}finally{fclose($f);}return hash('sha256',$raw);}
function v38_load(string $p):array{$v=json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);v38_need(is_array($v),'json_shape');return$v;}
function v38_id(mixed $v):?string{$s=trim((string)$v);return preg_match('/^[1-9][0-9]{0,21}$/D',$s)===1?$s:null;}
function v38_int(mixed $v):?int{$s=v38_id($v);if($s===null||strlen($s)>9)return null;$n=(int)$s;return$n>0?$n:null;}
function v38_assoc(array $x):bool{return !array_is_list($x);}
function v38_excluded(string $v):bool{return preg_match('/^(?:россия|абхазия|russia|russian federation|abkhazia)$/iu',trim($v))===1;}
function v38_query(PDO $d,string $q,array $a=[]):array{$s=$d->prepare($q);$s->execute(array_values($a));return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}
function v38_ns(array $n):?string{$x=trim((string)($n['supplier_namespace']??$n['namespace']??''));$ok=array_fill_keys(array_merge(array_keys(V38_NS),['bgoperator','anex']),true);return isset($ok[$x])?$x:null;}
function v38_native(array $n):?string{$ids=$n['positive_native_candidates']??null;if(is_array($ids)&&count($ids)===1){$x=v38_id(array_values($ids)[0]??null);if($x!==null)return$x;}$state=(string)($n['link_state']??$n['state']??'');if(str_contains($state,'single_native')||isset($n['source_edge_sha256'])||isset($n['operator_link_sha256']))return v38_id($n['external_hotel_id']??null);return null;}
function v38_add(array &$dst,string $entity,string $ns,string $native,string $op,string $rsha,string $esha):void{$k=$entity.'|'.$ns.'|'.$native;if(!isset($dst[$k]))$dst[$k]=['entity'=>$entity,'namespace'=>$ns,'native_id'=>$native,'evidence'=>[]];$ek=$op.'|'.$rsha.'|'.$esha;if(!isset($dst[$k]['evidence'][$ek])&&count($dst[$k]['evidence'])<10)$dst[$k]['evidence'][$ek]=['operation'=>$op,'result_sha256'=>$rsha,'edge_sha256'=>$esha];}
function v38_walk(mixed $n,string $op,string $rsha,array &$tv,array &$samo,array &$stats,int $depth=0):void{
    if($depth>28||!is_array($n))return;
    if(v38_assoc($n)){$ns=v38_ns($n);$native=$ns!==null?v38_native($n):null;if($ns!==null&&$native!==null){$esha=hash('sha256',v38_json($n));$tvId=v38_int($n['tv_hotel_id']??null);if($tvId!==null&&isset(V38_TV_DIRECT[$ns])){v38_add($tv,(string)$tvId,$ns,$native,$op,$rsha,$esha);$stats['tv_edges_seen']++;}$cat=v38_id($n['catalog_id']??$n['andromeda_catalog_id']??null);if($cat!==null&&isset(V38_NS[$ns])){v38_add($samo,$cat,$ns,$native,$op,$rsha,$esha);$stats['samo_edges_seen']++;}}}
    foreach($n as $v)if(is_array($v))v38_walk($v,$op,$rsha,$tv,$samo,$stats,$depth+1);
}
function v38_scan(string $root):array{
    v38_need(is_dir($root)&&!is_link($root),'operations_root');$tv=[];$samo=[];$stats=['operation_dirs_examined'=>0,'result_files_parsed'=>0,'result_files_skipped_size'=>0,'tv_edges_seen'=>0,'samo_edges_seen'=>0];
    foreach(new DirectoryIterator($root) as $e){if($e->isDot()||$e->isLink()||!$e->isDir())continue;if(++$stats['operation_dirs_examined']>5000)throw new RuntimeException('operation_dir_cap');$op=$e->getFilename();if(!str_starts_with($op,'hotel-match-'))continue;$p=$e->getPathname().'/result.json';if(!is_file($p)||is_link($p))continue;$z=filesize($p);if($z===false||$z<2||$z>64*1024*1024){$stats['result_files_skipped_size']++;continue;}$raw=(string)file_get_contents($p);$rsha=hash('sha256',$raw);try{$r=json_decode($raw,true,512,JSON_THROW_ON_ERROR);}catch(Throwable){continue;}if(!is_array($r))continue;$stats['result_files_parsed']++;v38_walk($r,$op,$rsha,$tv,$samo,$stats);}
    foreach([$tv,$samo] as &$set)foreach($set as &$r)$r['evidence']=array_values($r['evidence']);unset($set,$r);return['tv'=>$tv,'samo'=>$samo,'stats'=>$stats];
}
function v38_frontier(array $f):array{
    v38_need(($f['operation']??'')==='hotel-match-business-live30-frontier-plan-1971-20260925-v33','frontier_op');v38_need(($f['state']??'')==='completed_read_only_business_live30_frontier_plan','frontier_state');v38_need((int)($f['non_full_triple_total']??0)===V38_FRONTIER_TOTAL,'frontier_total');v38_need(($f['target_set_sha256']??'')===V38_FRONTIER_SHA,'frontier_sha');$exp=['tv_samo_missing_anex'=>777,'tv_anex_missing_samo'=>234,'tv_only_missing_both'=>726];v38_need(($f['bucket_counts']??null)===$exp,'frontier_buckets');$out=[];foreach($f['rows']??[] as $r){if(!is_array($r))continue;$id=v38_int($r['local_hotel_id']??null);$b=(string)($r['bucket']??'');if($id!==null&&isset($exp[$b]))$out[$id]=$b;}v38_need(count($out)===V38_FRONTIER_TOTAL,'frontier_rows');return$out;
}
function v38_indexes(array $scan,array $frontier):array{
    $tvFp=[];$tvTargetNs=[];$srcNs=[];$srcFp=[];
    foreach($scan['tv'] as $e){$t=(int)$e['entity'];if(!isset($frontier[$t]))continue;$ns=$e['namespace'];$n=$e['native_id'];$tvFp[$ns.'|'.$n][$t]=true;$tvTargetNs[$t][$ns][$n]=true;}
    foreach($scan['samo'] as $e){$s=$e['entity'];$ns=$e['namespace'];$n=$e['native_id'];$srcNs[$s][$ns][$n]=true;$srcFp[$ns.'|'.$n][$s]=true;}
    return compact('tvFp','tvTargetNs','srcNs','srcFp');
}
function v38_ops(string $raw):array{preg_match_all('/hotel-match-[a-z0-9_.-]+/i',$raw,$m);$x=array_values(array_unique($m[0]??[]));sort($x,SORT_STRING);return array_slice($x,0,12);}
function v38_provenance(array $r):array{
    $raw=(string)($r['evidence_json']??'');$hash=(string)($r['evidence_sha256']??'');$valid=preg_match('/^[0-9a-f]{64}$/D',$hash)===1&&hash('sha256',$raw)===$hash;$ops=$valid?v38_ops($raw):[];$tv=false;$samo=false;
    foreach($ops as $op){$l=strtolower($op);if(str_contains($l,'samo')||str_contains($l,'retained-context')||str_contains($l,'andromeda'))$samo=true;if((str_contains($l,'live30-common4-acquire')||str_contains($l,'live30-common4-continuation')||str_contains($l,'common4-mass-current'))&&!str_contains($l,'samo'))$tv=true;}
    $class=!$valid?'invalid_evidence':($tv&&$samo?'mixed':($tv?'tv_live30':($samo?'samo_or_retained':'unknown')));return['evidence_valid'=>$valid,'class'=>$class,'operations'=>$ops,'evidence_sha256'=>$hash];
}
function v38_current(PDO $db,array $frontier):array{
    $db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION READ ONLY');try{
        $active=[];foreach(v38_query($db,"SELECT id,name,country_name,region_name,subregion_name,category,is_active FROM catalog_hotels WHERE is_active=1") as $r){$id=(int)$r['id'];if(isset($frontier[$id])&&!v38_excluded((string)$r['country_name']))$active[$id]=$r;}
        $registry=[];$catalogSource=[];$catalogTarget=[];$provCounts=[];
        foreach(v38_query($db,"SELECT supplier_namespace,external_hotel_id,local_hotel_id,decision_status,catalog_sha256,evidence_sha256,evidence_json FROM andromeda_hotel_identities ORDER BY supplier_namespace,external_hotel_id,local_hotel_id") as $r){$ns=(string)$r['supplier_namespace'];$ext=(string)$r['external_hotel_id'];if($ns==='andromeda_catalog'){$catalogSource[$ext][]=$r;if(($r['decision_status']??'')==='accepted'&&$r['local_hotel_id']!==null)$catalogTarget[(int)$r['local_hotel_id']][]=$r;continue;}if(!isset(V38_NS[$ns])||($r['decision_status']??'')!=='accepted'||$r['local_hotel_id']===null)continue;$p=v38_provenance($r);$provCounts[$p['class']]=($provCounts[$p['class']]??0)+1;$registry[$ns.'|'.$ext][]=['local_hotel_id'=>(int)$r['local_hotel_id'],'provenance'=>$p,'catalog_sha256'=>(string)($r['catalog_sha256']??'')];}
        $manual=[];foreach(v38_query($db,"SELECT DISTINCT catalog_hotel_id FROM anex_hotel_decisions WHERE catalog_hotel_id IS NOT NULL") as $r)$manual[(int)$r['catalog_hotel_id']]=true;$db->rollBack();ksort($provCounts);return compact('active','registry','catalogSource','catalogTarget','manual','provCounts');
    }catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw$e;}
}
function v38_resolve_lane(string $src,string $ns,array $idx,array $cur):array{
    $natives=array_keys($idx['srcNs'][$src][$ns]??[]);if(count($natives)!==1)return['state'=>$natives===[]?'source_namespace_missing':'source_namespace_multi_native','native_ids'=>$natives,'target'=>null,'tv_raw'=>false,'provenance'=>[]];$native=(string)$natives[0];$sources=array_keys($idx['srcFp'][$ns.'|'.$native]??[]);if(count($sources)!==1)return['state'=>'samo_fingerprint_source_collision','native_id'=>$native,'target'=>null,'source_count'=>count($sources),'tv_raw'=>false,'provenance'=>[]];$rows=$cur['registry'][$ns.'|'.$native]??[];$targets=[];$prov=[];foreach($rows as $r){$targets[(int)$r['local_hotel_id']]=true;$prov[]=$r['provenance'];}if(count($targets)!==1)return['state'=>$targets===[]?'registry_missing':'registry_target_collision','native_id'=>$native,'target'=>null,'target_count'=>count($targets),'tv_raw'=>false,'provenance'=>$prov];$target=(int)array_key_first($targets);$tvRaw=false;if(isset(V38_TV_DIRECT[$ns])){$rawTargets=array_keys($idx['tvFp'][$ns.'|'.$native]??[]);$tvRaw=count($rawTargets)===1&&(int)$rawTargets[0]===$target&&count($idx['tvTargetNs'][$target][$ns]??[])===1;}$tvProv=$tvRaw;foreach($prov as $p)if(($p['class']??'')==='tv_live30'||($p['class']??'')==='mixed')$tvProv=true;return['state'=>'registry_unique','native_id'=>$native,'target'=>$target,'tv_raw'=>$tvRaw,'tv_provenance'=>$tvProv,'provenance'=>$prov];
}
function v38_classify(string $src,array $idx,array $frontier,array $cur):array{
    $lanes=[];$targets=[];$tvProof=0;$n=0;$ambig=false;foreach(array_keys(V38_NS) as $ns){$r=v38_resolve_lane($src,$ns,$idx,$cur);$lanes[$ns]=$r;if($r['state']==='registry_unique'){$n++;$targets[(int)$r['target']][$ns]=true;if($r['tv_provenance'])$tvProof++;}elseif(!in_array($r['state'],['source_namespace_missing','registry_missing'],true))$ambig=true;}
    $t=array_keys($targets);$candidate=count($t)===1?(int)$t[0]:null;$base=$n===0?'consensus_0':($n===1?'consensus_1':'registry_'.$n.'plus_review');if(count($t)>1)$base='conflict_registry_targets';elseif($ambig&&$n>=2)$base='hold_lane_ambiguity';elseif($n>=2&&$tvProof>=1)$base='strict_cross_source_'.$n.'plus';
    $status=$base;$current='not_applicable';if($candidate!==null&&str_starts_with($base,'strict_cross_source_')){$srcRows=$cur['catalogSource'][$src]??[];$targetRows=$cur['catalogTarget'][$candidate]??[];$same=array_filter($srcRows,fn($r)=>(($r['decision_status']??'')==='accepted'&&(int)($r['local_hotel_id']??0)===$candidate));$otherSrc=array_filter($srcRows,fn($r)=>(($r['decision_status']??'')==='accepted'&&(int)($r['local_hotel_id']??0)!==$candidate));$otherTarget=array_filter($targetRows,fn($r)=>(string)($r['external_hotel_id']??'')!==$src);if(!isset($frontier[$candidate])){$current='outside_frontier';$status='hold_target_outside_frontier';}elseif($same){$current='already_resolved_same';$status='strict_already_resolved_same';}elseif($otherSrc){$current='source_occupied';$status='hold_source_occupied';}elseif($otherTarget){$current='target_samo_occupied';$status='hold_target_samo_occupied';}elseif(!isset($cur['active'][$candidate])){$current='target_inactive_or_excluded';$status='hold_target_inactive_or_excluded';}elseif(isset($cur['manual'][$candidate])){$current='manual_target_protected';$status='hold_manual_target';}else{$current='current_missing_bridge';$status='strict_cross_source_2plus_current_missing';}}
    return['andromeda_catalog_id'=>$src,'candidate_local_hotel_id'=>$candidate,'frontier_bucket'=>$candidate!==null?($frontier[$candidate]??null):null,'consensus_operator_count'=>$n,'tv_proof_operator_count'=>$tvProof,'status'=>$status,'base_status'=>$base,'current_state'=>$current,'lanes'=>$lanes,'safe_to_write_now'=>false];
}
function v38_execute(PDO $db,string $ops,array $frontierDoc,string $sourceSha):array{
    $frontier=v38_frontier($frontierDoc);$scan=v38_scan($ops);$idx=v38_indexes($scan,$frontier);$cur=v38_current($db,$frontier);$sources=array_keys($idx['srcNs']);sort($sources,SORT_NATURAL);$dist=['0'=>0,'1'=>0,'2'=>0,'3'=>0,'4'=>0];$status=[];$rows=[];$lift=['tv_samo_missing_anex'=>0,'tv_anex_missing_samo'=>0,'tv_only_missing_both'=>0];$strict=0;$registryReview=0;
    foreach($sources as $src){$r=v38_classify((string)$src,$idx,$frontier,$cur);$c=min(4,max(0,(int)$r['consensus_operator_count']));$dist[(string)$c]++;$status[$r['status']]=($status[$r['status']]??0)+1;if($r['status']==='strict_cross_source_2plus_current_missing'){$strict++;if(isset($lift[$r['frontier_bucket']]))$lift[$r['frontier_bucket']]++;}$registryReview+=str_starts_with($r['status'],'registry_')?1:0;if($c>0||str_starts_with($r['status'],'conflict_')||str_starts_with($r['status'],'hold_')||str_starts_with($r['status'],'strict_'))$rows[]=$r;}
    ksort($status);usort($rows,fn($a,$b)=>[$a['status'],$a['candidate_local_hotel_id']??PHP_INT_MAX,$a['andromeda_catalog_id']]<=>[$b['status'],$b['candidate_local_hotel_id']??PHP_INT_MAX,$b['andromeda_catalog_id']]);return['operation'=>V38_OP,'state'=>'completed_read_only_samo_registry_consensus','generated_at_utc'=>gmdate('c'),'source_sha'=>$sourceSha,'frontier_total'=>count($frontier),'frontier_target_sha256'=>V38_FRONTIER_SHA,'operation_scan'=>$scan['stats'],'samo_source_count'=>count($sources),'tv_raw_semantic_edges'=>count($scan['tv']),'samo_semantic_edges'=>count($scan['samo']),'registry_provenance_counts'=>$cur['provCounts'],'consensus_distribution'=>$dist,'candidate_status_counts'=>$status,'strict_cross_source_2plus_current_missing_count'=>$strict,'registry_2plus_review_count'=>$registryReview,'lift_potential_by_v33_bucket'=>$lift,'rows'=>$rows,'provider_http_calls'=>0,'tourvisor_calls'=>0,'samo_calls'=>0,'anex_calls'=>0,'andromeda_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'safe_to_write_now'=>false];
}
function v38_self_test():void{
    $idx=['tvFp'=>['operator_315|7'=>[100=>true]],'tvTargetNs'=>[100=>['operator_315'=>['7'=>true]]],'srcNs'=>['10'=>['operator_315'=>['7'=>true],'operator_342'=>['8'=>true]]],'srcFp'=>['operator_315|7'=>['10'=>true],'operator_342|8'=>['10'=>true]]];$p=['evidence_valid'=>true,'class'=>'unknown','operations'=>[],'evidence_sha256'=>str_repeat('a',64)];$cur=['registry'=>['operator_315|7'=>[['local_hotel_id'=>100,'provenance'=>$p]],'operator_342|8'=>[['local_hotel_id'=>100,'provenance'=>$p]]],'catalogSource'=>[],'catalogTarget'=>[],'active'=>[100=>['id'=>100]],'manual'=>[]];$r=v38_classify('10',$idx,[100=>'tv_only_missing_both'],$cur);v38_need($r['status']==='strict_cross_source_2plus_current_missing'&&$r['consensus_operator_count']===2&&$r['tv_proof_operator_count']===1,'strict');$cur['registry']['operator_342|8'][0]['local_hotel_id']=101;$r=v38_classify('10',$idx,[100=>'tv_only_missing_both',101=>'tv_only_missing_both'],$cur);v38_need($r['status']==='conflict_registry_targets','conflict');
}
if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__){if(in_array('--self-test',$argv??[],true)){v38_self_test();echo"MATCH_SAMO_REGISTRY_CONSENSUS_V38_SELFTEST_OK\n";exit;}v38_need(($argv[1]??'')==='--execute','disabled');$root=(string)getenv('ANYTOUR_ROOT');$dir=(string)getenv('MATCH_OPERATION_DIR');$ops=(string)getenv('MATCH_OPERATIONS_ROOT');$fp=(string)getenv('MATCH_FRONTIER_RESULT');$fsha=(string)getenv('MATCH_FRONTIER_RESULT_SHA');$sha=(string)getenv('MATCH_SOURCE_SHA');v38_need(is_dir($root)&&is_dir($dir)&&basename($dir)===V38_OP&&is_dir($ops)&&is_file($fp)&&preg_match('/^[0-9a-f]{64}$/D',$fsha)===1&&hash_file('sha256',$fp)===$fsha&&preg_match('/^[0-9a-f]{40}$/D',$sha)===1,'runtime_scope');$res=v38_load($dir.'/reservation.json');v38_need(($res['operation']??'')===V38_OP&&($res['state']??'')==='reserved_before_read_only_consensus','reservation');require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');try{$out=v38_execute(v2_data_db(),$ops,v38_load($fp),$sha);$h=v38_save($dir.'/result.json',$out);v38_save($dir.'/receipt.json',['operation'=>V38_OP,'state'=>$out['state'],'result_sha256'=>$h,'readback_verified'=>hash_file('sha256',$dir.'/result.json')===$h,'provider_accessed'=>false,'provider_http_calls'=>0,'database_writes'=>0,'mapping_writes'=>0]);echo v38_json(['state'=>$out['state'],'consensus_distribution'=>$out['consensus_distribution'],'candidate_status_counts'=>$out['candidate_status_counts'],'strict_cross_source_2plus_current_missing_count'=>$out['strict_cross_source_2plus_current_missing_count'],'registry_2plus_review_count'=>$out['registry_2plus_review_count'],'lift_potential_by_v33_bucket'=>$out['lift_potential_by_v33_bucket']])."\n";}catch(Throwable$e){$f=['operation'=>V38_OP,'state'=>'failed_read_only_samo_registry_consensus','reason'=>preg_replace('/[^A-Za-z0-9_.:-]+/','_',mb_substr($e->getMessage(),0,180,'UTF-8')),'provider_http_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'safe_to_write_now'=>false];$h=v38_save($dir.'/result.json',$f);v38_save($dir.'/receipt.json',['operation'=>V38_OP,'state'=>$f['state'],'result_sha256'=>$h,'readback_verified'=>true,'provider_accessed'=>false,'provider_http_calls'=>0,'database_writes'=>0,'mapping_writes'=>0]);fwrite(STDERR,$f['reason']."\n");exit(2);}}
