<?php
declare(strict_types=1);
require_once __DIR__.'/hotel_match_live30_common4_gap_matrix_v1.php';require_once __DIR__.'/hotel_match_retained93_primary_write_v84.php';
const M103_OP='hotel-match-newcontext-samoonly-final-plan-1971-20260928-v103';
const M103_LEDGER='8da64bc3ac54d707d335b8808b171f46a02ba0464536681bc40b741136df935c';
const M103_PLANS=['hotel-match-newcontext-samoonly200-plan-1971-20260928-v96'=>'4d4e0f8ea69c71d07a773f9063565f5ba51620c2290584647956928bfe5736c1','hotel-match-newcontext-samoonly-next200-plan-1971-20260928-v99'=>'17c8384a1d3fb59d2fe47f72409ac2e9f4c969166c450090f3079f93b5d31f9a','hotel-match-newcontext-samoonly-third200-plan-1971-20260928-v101'=>'c43a8aad8ef0653ce052cf4dc17fecedcde06d50784ccd6398009b6dc0b22f3d'];
function m103_need(bool$b,string$m):void{if(!$b)throw new RuntimeException($m);}
function m103_main(array$a):int{
 m103_need(($a[1]??'')==='--execute','disabled');$root=(string)getenv('ANYTOUR_ROOT');$dir=(string)getenv('MATCH_OPERATION_DIR');$head=(string)getenv('MATCH_SOURCE_SHA');m103_need(is_dir($root)&&basename($root)==='anytoour.ru'&&is_dir($dir)&&basename($dir)===M103_OP,'scope');foreach(['result.json','receipt.json']as$f)m103_need(!file_exists($dir.'/'.$f),'no_replay');$ops=dirname($dir);$l=w84_read($ops.'/hotel-match-request-ledger-1971-20260928-v93/result.json',M103_LEDGER,33554432);$used=[];
 foreach(M103_PLANS as$op=>$sha){$p=w84_read($ops.'/'.$op.'/result.json',$sha,16777216);foreach($p['rows']as$r)$used[(int)$r['tv_hotel_id']]=true;}m103_need(count($used)===600,'prior600');
 require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$m=hmc4_execute(v2_data_db());$cur=[];foreach($m['rows']as$r)$cur[(int)$r['tv_hotel_id']]=$r;$req=[];foreach($l['requests']as$q)foreach($q['hotel_ids']as$id)$req[(int)$id][]=$q;$rank=['Турция'=>1,'Таиланд'=>2,'Вьетнам'=>3,'Китай'=>4,'ОАЭ'=>5,'Египет'=>6,'Мальдивы'=>7,'Катар'=>8];$rows=[];
 foreach($l['rows']as$r){$id=(int)$r['tv_hotel_id'];if(isset($used[$id])||!isset($cur[$id])||($cur[$id]['gap_bucket']??'')!=='samo_only'||!in_array(13,array_map('intval',$r['missing_operator_ids']??[]),true)||!empty($r['lanes']['13']['retained_exact']))continue;$cids=[];foreach($req[$id]??[]as$q){$cid=(int)($q['context']['countryId']??0);if($cid)$cids[$cid]=($cids[$cid]??0)+1;}arsort($cids);$cid=(int)(array_key_first($cids)??0);if(!$cid)continue;$dup=false;foreach($req[$id]??[]as$q){$x=$q['context'];if((int)($x['departureId']??0)===1&&(int)($x['countryId']??0)===$cid&&($x['dateFrom']??'')==='2026-10-15'&&($x['dateTo']??'')==='2026-10-15'&&(int)($x['nightsFrom']??0)===7&&(int)($x['nightsTo']??0)===7&&(int)($x['adults']??0)===2&&($x['childs']??[])===[]){$dup=true;break;}}if($dup)continue;$missing=[];foreach([13,18,25,43]as$op)if(in_array($op,array_map('intval',$r['missing_operator_ids']??[]),true)&&empty($r['lanes'][(string)$op]['retained_exact']))$missing[]=$op;if(!in_array(13,$missing,true))continue;$rows[]=['tv_hotel_id'=>$id,'hotel_name'=>$r['hotel_name'],'country_id'=>$cid,'country'=>$r['country'],'departure_id'=>1,'departure_date'=>'2026-10-15','nights'=>7,'adults'=>2,'children_count'=>0,'child_ages_signature'=>'','missing_operator_ids'=>$missing,'gap_bucket'=>'samo_only','rank'=>$rank[$r['country']]??99];}
 usort($rows,fn($x,$y)=>[$x['rank'],$x['tv_hotel_id']]<=>[$y['rank'],$y['tv_hotel_id']]);foreach($rows as&$r)unset($r['rank']);unset($r);m103_need(count($rows)>0&&count($rows)<=200,'final_scope');$countries=[];foreach($rows as$r)$countries[$r['country']]=($countries[$r['country']]??0)+1;
 $out=['operation'=>M103_OP,'state'=>'completed_read_only_final_samoonly_plan','source_sha'=>$head,'generated_at_utc'=>gmdate('c'),'current_tv_total'=>$m['tv_live30_total'],'current_nontriple'=>$m['live30_non_triple_total'],'prior_scope_excluded'=>600,'scope_count'=>count($rows),'country_counts'=>$countries,'tourvisor_account'=>'TOURVISOR_ANEX_JWT','operator_filter_sent'=>false,'continue_calls'=>0,'dates_calls'=>0,'provider_http_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'rows'=>$rows];$sha=w76_save($dir.'/result.json',$out);w76_save($dir.'/receipt.json',['operation'=>M103_OP,'state'=>$out['state'],'source_sha'=>$head,'result_sha256'=>$sha,'provider_http_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true]);echo w76_json(array_diff_key($out,['rows'=>true]))."\n";return 0;
}
if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__)exit(m103_main($argv));
