<?php
declare(strict_types=1);
if (!defined('FC_LIBRARY_ONLY')) define('FC_LIBRARY_ONLY', true);
require_once __DIR__ . '/hotel_match_anex_andromeda_mutual_graph_review.php';

const HMACLR_OPERATION='hotel-match-anex-andromeda-cluster-local-review-1971-20260911-v1';
const HMACLR_COORD_BLOCK_M=5000.0;
const HMACLR_COORD_DIRECT_M=1000.0;
const HMACLR_MIN_ANCHORS=2;
const HMACLR_NO_GEO_ANCHORS=3;

function hmaclr_cluster(array $a,array $b):array{
    $names=array_values(array_unique(array_merge($a['names']??[],$b['names']??[])));
    $places=array_values(array_unique(array_filter(array_merge($a['places']??[],$b['places']??[]),static fn($v)=>trim((string)$v)!=='')));
    $latA=$a['latitude']??null;$lonA=$a['longitude']??null;$latB=$b['latitude']??null;$lonB=$b['longitude']??null;
    $supplierDistance=fc_dist($latA,$lonA,$latB,$lonB);$lat=null;$lon=null;
    if($supplierDistance!==null&&$supplierDistance<=HMACLR_COORD_DIRECT_M){$lat=((float)$latA+(float)$latB)/2.0;$lon=((float)$lonA+(float)$lonB)/2.0;}
    elseif($latA!==null&&$lonA!==null&&($latB===null||$lonB===null)){$lat=(float)$latA;$lon=(float)$lonA;}
    elseif($latB!==null&&$lonB!==null&&($latA===null||$lonA===null)){$lat=(float)$latB;$lon=(float)$lonB;}
    return ['names'=>$names,'places'=>$places,'latitude'=>$lat,'longitude'=>$lon,'supplier_distance_m'=>$supplierDistance===null?null:round((float)$supplierDistance,2)];
}
function hmaclr_local_anchors(array $a,array $b,array $target,array $targetNames):array{
    $tp=[(string)($target['region_name']??''),(string)($target['subregion_name']??'')];$shared=[];$details=[];
    foreach([['anex',$a],['andromeda',$b]] as[$provider,$s]){$p=hmgcr_best_pair($s['names'],$targetNames,$s['places'],$tp);$details[$provider]=$p;foreach(($p['shared_tokens']??[])as$t)$shared[(string)$t]=true;}
    return ['count'=>count($shared),'tokens'=>array_keys($shared),'pairs'=>$details];
}
function hmaclr_target_distances(array $a,array $b,array $target):array{
    $ta=fc_dist($a['latitude'],$a['longitude'],$target['latitude']??null,$target['longitude']??null);$tb=fc_dist($b['latitude'],$b['longitude'],$target['latitude']??null,$target['longitude']??null);
    return ['anex_m'=>$ta===null?null:round((float)$ta,2),'andromeda_m'=>$tb===null?null:round((float)$tb,2)];
}
function hmaclr_exact_fallback(array $cluster,int $country,array $index,array $hotels,array $names):array{
    [$exactIds]=hmgcr_source_candidate_ids($cluster['names'],$cluster['places'],$country,$index);$pool=[];
    foreach($exactIds as$id){$id=(int)$id;if(!isset($hotels[$id])||(int)$hotels[$id]['country_id']!==$country)continue;$target=$hotels[$id];$tp=[(string)$target['region_name'],(string)$target['subregion_name']];$pair=hmgcr_best_pair($cluster['names'],$names[$id]??[(string)$target['name']],$cluster['places'],$tp);if(!($pair['critical_ok']??false)||!($pair['exact_bag']??false)||(int)($pair['shared']??0)<HMACLR_NO_GEO_ANCHORS)continue;$pool[]=['target_local_hotel_id'=>$id,'target_name'=>$target['name'],'target_region'=>$target['region_name'],'target_subregion'=>$target['subregion_name'],'target_category'=>$target['category']===null?null:(int)$target['category'],'pair'=>$pair,'place_match'=>hmgcr_place($cluster['places'],$tp),'distance_m'=>null,'reason'=>'cluster_exact_3plus_no_geo'];}
    return count($pool)===1?['bucket'=>'prepared']+$pool[0]:['bucket'=>'near','reason'=>count($pool)>1?'cluster_exact_ambiguous':'cluster_local_insufficient','candidate_count'=>count($pool)];
}
function hmaclr_resolve(array $a,array $b,int $country,array $index,array $hotels,array $names):array{
    $cluster=hmaclr_cluster($a,$b);if($cluster['supplier_distance_m']!==null&&(float)$cluster['supplier_distance_m']>HMACLR_COORD_BLOCK_M)return ['bucket'=>'hard_conflict','reason'=>'supplier_coordinates_conflict_gt_5km','cluster'=>$cluster];
    $d=hmgtr_decide($cluster,$country,$index,$hotels,$names,[],[]);if(($d['bucket']??'')!=='prepared')$d=hmaclr_exact_fallback($cluster,$country,$index,$hotels,$names);if(($d['bucket']??'')!=='prepared')return $d+['cluster'=>$cluster];
    $target=(int)$d['target_local_hotel_id'];$t=$hotels[$target]??null;if(!$t)return ['bucket'=>'near','reason'=>'cluster_target_missing','cluster'=>$cluster];$tn=$names[$target]??[(string)$t['name']];$anchors=hmaclr_local_anchors($a,$b,$t,$tn);$dist=hmaclr_target_distances($a,$b,$t);
    foreach($anchors['pairs']as$p)if(!($p['critical_ok']??false))return ['bucket'=>'hard_conflict','reason'=>'cluster_supplier_local_qualifier_conflict','target_local_hotel_id'=>$target,'anchors'=>$anchors,'distances'=>$dist,'cluster'=>$cluster];
    foreach($dist as$meters)if($meters!==null&&(float)$meters>HMACLR_COORD_BLOCK_M)return ['bucket'=>'hard_conflict','reason'=>'cluster_supplier_local_coordinate_conflict_gt_5km','target_local_hotel_id'=>$target,'anchors'=>$anchors,'distances'=>$dist,'cluster'=>$cluster];
    $geo=(bool)($d['place_match']??false)||($dist['anex_m']!==null&&(float)$dist['anex_m']<=HMACLR_COORD_DIRECT_M)||($dist['andromeda_m']!==null&&(float)$dist['andromeda_m']<=HMACLR_COORD_DIRECT_M);$need=$geo?HMACLR_MIN_ANCHORS:HMACLR_NO_GEO_ANCHORS;
    if((int)$anchors['count']<$need)return ['bucket'=>'near','reason'=>$geo?'cluster_identity_anchors_lt_2':'cluster_no_geo_identity_anchors_lt_3','target_local_hotel_id'=>$target,'anchors'=>$anchors,'distances'=>$dist,'cluster'=>$cluster,'local_resolution'=>$d];
    return ['bucket'=>'prepared','reason'=>$geo?'cluster_supplier_union_direct_geo':'cluster_supplier_union_exact_no_geo','target_local_hotel_id'=>$target,'target_name'=>$t['name'],'target_region'=>$t['region_name'],'target_subregion'=>$t['subregion_name'],'anchors'=>$anchors,'distances'=>$dist,'cluster'=>$cluster,'local_resolution'=>$d];
}
function hmaclr_other(array $claims,int|string $self):array{return array_values(array_filter($claims,static fn($x)=>(string)$x!==(string)$self));}
function hmaclr_review(PDO $db,string $operation=HMACLR_OPERATION):array{
    if($operation!==HMACLR_OPERATION)throw new RuntimeException('operation_scope');$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION READ ONLY');
    try{$coverage=fc_coverage($db);$an=hmamgr_anex_rows($db);$and=hmamgr_andromeda_rows($db);$andIndex=hmamgr_index($and);$andLoc=hmadcrh_locality_common($and);[$hotels,$names]=mbr_catalog($db);$all=[];foreach(array_keys($hotels)as$id)$all[(int)$id]=true;$localIndex=hmgcr_build_index($all,$hotels,$names);
        $manual=array_fill_keys(array_map('intval',$db->query('SELECT anex_hotel_id FROM anex_hotel_decisions')->fetchAll(PDO::FETCH_COLUMN)),true);$excluded=[];foreach($db->query('SELECT anex_hotel_id,catalog_hotel_id FROM anex_review_pair_exclusions')->fetchAll(PDO::FETCH_ASSOC)as$r)$excluded[(int)$r['anex_hotel_id']][(int)$r['catalog_hotel_id']]=true;$anClaims=[];foreach($db->query('SELECT anex_hotel_id,catalog_hotel_id FROM anex_hotel_search_mappings WHERE enabled=1')->fetchAll(PDO::FETCH_ASSOC)as$r)$anClaims[(int)$r['catalog_hotel_id']][]=(int)$r['anex_hotel_id'];foreach($db->query("SELECT anex_hotel_id,catalog_hotel_id FROM anex_hotel_decisions WHERE decision_status='accepted' AND catalog_hotel_id IS NOT NULL")->fetchAll(PDO::FETCH_ASSOC)as$r)$anClaims[(int)$r['catalog_hotel_id']][]=(int)$r['anex_hotel_id'];$andClaims=[];foreach($db->query("SELECT external_hotel_id,local_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IS NOT NULL")->fetchAll(PDO::FETCH_ASSOC)as$r)$andClaims[(int)$r['local_hotel_id']][]=(string)$r['external_hotel_id'];
        $edges=[];$hard=[];$near=[];$stats=['anex_rows'=>count($an),'andromeda_rows'=>count($and),'supplier_edges_examined'=>0,'supplier_edges_safe'=>0,'cluster_local_prepared_raw'=>0,'benchmark_same_local'=>0,'benchmark_target_correct'=>0,'new_one_side_raw'=>0,'new_neither_raw'=>0,'new_live_raw'=>0,'manual_block'=>0,'pair_exclusion_block'=>0,'target_occupancy_block'=>0,'existing_local_conflict'=>0,'cluster_hard_conflict'=>0,'cluster_near'=>0,'uniqueness_demotions'=>0,'prepared'=>0,'prepared_one_side'=>0,'prepared_neither'=>0,'prepared_live'=>0];
        foreach($an as$aid=>$a){$pool=hmamgr_candidates($a,$and,$andIndex);foreach($pool as$andId=>$edge){$stats['supplier_edges_examined']++;if(($edge['route']??null)===null||$edge['route']==='coordinate_conflict')continue;$b=$and[$andId]??null;if(!$b)continue;$anchors=hmadcrh_identity_anchors($edge['pair'],$b,$andLoc);if((int)$anchors['identity_aligned']<2)continue;$validation=hmamgr_validation($a['local_ids'],$b['local_ids']);if($validation==='different_local'){$stats['existing_local_conflict']++;continue;}$stats['supplier_edges_safe']++;$d=hmaclr_resolve($a,$b,(int)$a['country_id'],$localIndex,$hotels,$names);$row=['anex_hotel_id'=>(int)$aid,'andromeda_external_id'=>(string)$andId,'country_id'=>(int)$a['country_id'],'validation'=>$validation,'anex_local_ids'=>$a['local_ids'],'andromeda_local_ids'=>$b['local_ids'],'anex_live'=>$a['live'],'andromeda_live'=>$b['live'],'anex_names'=>$a['names'],'andromeda_names'=>$b['names'],'supplier_edge'=>$edge,'supplier_identity_anchors'=>$anchors]+$d;
            if(($d['bucket']??'')==='hard_conflict'){$stats['cluster_hard_conflict']++;$hard[]=$row;continue;}if(($d['bucket']??'')!=='prepared'){$stats['cluster_near']++;$near[]=$row;continue;}$target=(int)$d['target_local_hotel_id'];$stats['cluster_local_prepared_raw']++;
            if($validation==='same_local'){$stats['benchmark_same_local']++;$expected=(int)($a['local_ids'][0]??0);if($target===$expected)$stats['benchmark_target_correct']++;else{$stats['existing_local_conflict']++;$row['reason']='benchmark_cluster_target_disagrees_existing_local';$hard[]=$row;continue;}$row['benchmark']=true;$edges[]=$row;continue;}
            if($a['local_ids']&&!in_array($target,$a['local_ids'],true)||$b['local_ids']&&!in_array($target,$b['local_ids'],true)){$stats['existing_local_conflict']++;$row['reason']='cluster_target_disagrees_one_side_local';$hard[]=$row;continue;}if(isset($manual[(int)$aid])){$stats['manual_block']++;$row['reason']='anex_manual_protected';$near[]=$row;continue;}if(isset($excluded[(int)$aid][$target])){$stats['pair_exclusion_block']++;$row['reason']='anex_pair_exclusion';$near[]=$row;continue;}$oa=hmaclr_other($anClaims[$target]??[],(int)$aid);$ob=hmaclr_other($andClaims[$target]??[],(string)$andId);if($oa||$ob){$stats['target_occupancy_block']++;$row['reason']='same_provider_target_occupied';$row['other_anex']=$oa;$row['other_andromeda']=$ob;$near[]=$row;continue;}$row['benchmark']=false;$edges[]=$row;if($validation==='neither_side')$stats['new_neither_raw']++;else$stats['new_one_side_raw']++;if($a['live']||$b['live'])$stats['new_live_raw']++;}}
        $byA=[];$byB=[];$byTarget=[];foreach($edges as$i=>$r){if($r['benchmark'])continue;$byA[$r['anex_hotel_id']][]=$i;$byB[$r['andromeda_external_id']][]=$i;$byTarget[(int)$r['target_local_hotel_id']][]=$i;}$demote=[];foreach([$byA,$byB,$byTarget]as$g)foreach($g as$idxs)if(count($idxs)>1)foreach($idxs as$i)$demote[$i]=true;$prepared=[];$bench=[];foreach($edges as$i=>$r){if($r['benchmark']){$bench[]=$r;continue;}if(isset($demote[$i])){$r['reason']='cluster_graph_not_one_to_one_unique';$near[]=$r;$stats['uniqueness_demotions']++;continue;}$prepared[]=$r;$stats['prepared']++;if($r['validation']==='neither_side')$stats['prepared_neither']++;else$stats['prepared_one_side']++;if($r['anex_live']||$r['andromeda_live'])$stats['prepared_live']++;}
        usort($prepared,static fn($x,$y)=>(($y['anex_live']||$y['andromeda_live'])<=>($x['anex_live']||$x['andromeda_live']))?:($x['anex_hotel_id']<=>$y['anex_hotel_id']));$db->commit();return ['status'=>'completed','operation_id'=>$operation,'mode'=>'current_core8_supplier_cluster_to_local_graph_read_only','database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'historical_operations_replayed'=>false,'coverage'=>$coverage,'stats'=>$stats,'prepared'=>$prepared,'benchmark'=>$bench,'hard_conflicts'=>$hard,'near'=>$near,'guards'=>['supplier_edges_recomputed_current'=>true,'supplier_locality_identity_anchors_min'=>2,'cluster_local_identity_anchors_min'=>2,'cluster_local_no_geo_anchors_min'=>3,'supplier_coordinate_conflict_block_m'=>HMACLR_COORD_BLOCK_M,'supplier_local_coordinate_conflict_block_m'=>HMACLR_COORD_BLOCK_M,'critical_qualifiers_must_agree_both_suppliers'=>true,'existing_local_validation_only'=>true,'one_to_one_supplier_and_local_uniqueness_required'=>true,'manual_pair_exclusion_occupancy_protected'=>true,'stars_not_identity'=>true,'core8_only'=>true]];
    }catch(Throwable$e){if($db->inTransaction())$db->rollBack();throw$e;}}
if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__){fwrite(STDERR,"library_only: use guarded cluster-local workflow\n");exit(64);}
