<?php
declare(strict_types=1);
require_once __DIR__.'/hotel_match_anex_effective_coverage.php';
const V33_OP='hotel-match-business-live30-frontier-plan-1971-20260925-v33';
function v33_need(bool $v,string $m):void{if(!$v)throw new RuntimeException($m);}
function v33_json(mixed $v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
function v33_save(string $p,array $v):string{$raw=v33_json($v)."\n";$f=@fopen($p,'x+b');v33_need($f!==false,'exclusive_create');try{v33_need(fwrite($f,$raw)===strlen($raw)&&fflush($f),'write');if(function_exists('fsync'))v33_need(fsync($f),'sync');}finally{fclose($f);}return hash('sha256',$raw);}
function v33_excluded(string $c):bool{return preg_match('/^(?:россия|абхазия|russia|russian federation|abkhazia)$/iu',trim($c))===1;}
function v33_bucket(bool $s,bool $a):string{return $s?($a?'full_triple':'tv_samo_missing_anex'):($a?'tv_anex_missing_samo':'tv_only_missing_both');}
function v33_run(PDO $db,int $cutTs,string $sourceSha):array{
 $db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION READ ONLY');
 try{
  $hotels=[];foreach($db->query("SELECT id,name,country_id,country_name,region_id,region_name,subregion_id,subregion_name,category,is_active FROM catalog_hotels WHERE is_active=1 ORDER BY id")->fetchAll(PDO::FETCH_ASSOC) as $r){$id=(int)$r['id'];if($id>0&&!v33_excluded((string)$r['country_name']))$hotels[$id]=$r;}
  $samo=[];foreach($db->query("SELECT DISTINCT local_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IS NOT NULL")->fetchAll(PDO::FETCH_COLUMN) as $id){$id=(int)$id;if(isset($hotels[$id]))$samo[$id]=true;}
  $cov=AnyTourMatchAnexEffectiveCoverage::fromPdo($db);$anex=[];foreach(($cov['by_local']??[]) as $id=>$set){$id=(int)$id;if(isset($hotels[$id])&&is_array($set)&&$set!==[])$anex[$id]=true;}
  $cut=gmdate('Y-m-d H:i:s',$cutTs);$q=$db->prepare('SELECT hotel_id,MAX(last_seen_at) m FROM tour_operator_identity_observations GROUP BY hotel_id HAVING m>=?');$q->execute([$cut]);$tv=[];foreach($q->fetchAll(PDO::FETCH_ASSOC) as $r){$id=(int)$r['hotel_id'];if(isset($hotels[$id]))$tv[$id]=true;}
  $counts=['tv_samo_missing_anex'=>0,'tv_anex_missing_samo'=>0,'tv_only_missing_both'=>0,'full_triple'=>0];$prio=['tv_samo_missing_anex'=>1,'tv_anex_missing_samo'=>2,'tv_only_missing_both'=>3,'full_triple'=>9];$rows=[];
  foreach(array_keys($tv) as $id){$b=v33_bucket(isset($samo[$id]),isset($anex[$id]));$counts[$b]++;if($b==='full_triple')continue;$h=$hotels[$id];$rows[]=['priority'=>$prio[$b],'bucket'=>$b,'local_hotel_id'=>$id,'has_samo'=>isset($samo[$id]),'has_direct_anex'=>isset($anex[$id]),'missing_samo'=>!isset($samo[$id]),'missing_direct_anex'=>!isset($anex[$id]),'catalog_hotel'=>['id'=>$id,'name'=>(string)$h['name'],'country_id'=>$h['country_id'],'country_name'=>$h['country_name'],'region_id'=>$h['region_id'],'region_name'=>$h['region_name'],'subregion_id'=>$h['subregion_id'],'subregion_name'=>$h['subregion_name'],'category'=>$h['category'],'is_active'=>(int)$h['is_active']]];}
  usort($rows,fn($a,$b)=>[$a['priority'],$a['local_hotel_id']]<=>[$b['priority'],$b['local_hotel_id']]);$keys=array_map(fn($r)=>$r['bucket'].'|'.$r['local_hotel_id'],$rows);$digest=hash('sha256',implode("\n",$keys)."\n");$db->rollBack();
  return ['operation'=>V33_OP,'state'=>'completed_read_only_business_live30_frontier_plan','generated_at_utc'=>gmdate('c'),'cutoff_utc'=>$cut,'source_sha'=>$sourceSha,'tv_live30_total'=>count($tv),'full_triple_total'=>$counts['full_triple'],'non_full_triple_total'=>count($rows),'bucket_counts'=>['tv_samo_missing_anex'=>$counts['tv_samo_missing_anex'],'tv_anex_missing_samo'=>$counts['tv_anex_missing_samo'],'tv_only_missing_both'=>$counts['tv_only_missing_both']],'priority_order'=>['tv_samo_missing_anex','tv_anex_missing_samo','tv_only_missing_both'],'target_set_sha256'=>$digest,'rows'=>$rows,'provider_http_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'safe_to_write_now'=>false];
 }catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
}
function v33_self_test():void{v33_need(v33_bucket(true,false)==='tv_samo_missing_anex','s');v33_need(v33_bucket(false,true)==='tv_anex_missing_samo','a');v33_need(v33_bucket(false,false)==='tv_only_missing_both','b');v33_need(v33_bucket(true,true)==='full_triple','f');}
if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__){
 if(in_array('--self-test',$argv??[],true)){v33_self_test();echo "MATCH_BUSINESS_LIVE30_FRONTIER_V33_SELFTEST_OK\n";exit;}
 v33_need(($argv[1]??'')==='--execute','disabled');$root=(string)getenv('ANYTOUR_ROOT');$dir=(string)getenv('MATCH_OPERATION_DIR');$sha=(string)getenv('MATCH_SOURCE_SHA');v33_need(is_dir($root)&&is_dir($dir)&&basename($dir)===V33_OP&&preg_match('/^[0-9a-f]{40}$/D',$sha)===1,'scope');$res=json_decode((string)file_get_contents($dir.'/reservation.json'),true,16,JSON_THROW_ON_ERROR);v33_need(($res['operation']??'')===V33_OP,'reservation');require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');
 try{$r=v33_run(v2_data_db(),time()-30*86400,$sha);$h=v33_save($dir.'/result.json',$r);v33_save($dir.'/receipt.json',['operation'=>V33_OP,'state'=>$r['state'],'result_sha256'=>$h,'readback_verified'=>hash_file('sha256',$dir.'/result.json')===$h,'provider_http_calls'=>0,'database_writes'=>0,'mapping_writes'=>0]);echo v33_json(['state'=>$r['state'],'tv_live30_total'=>$r['tv_live30_total'],'full_triple_total'=>$r['full_triple_total'],'non_full_triple_total'=>$r['non_full_triple_total'],'bucket_counts'=>$r['bucket_counts'],'target_set_sha256'=>$r['target_set_sha256']])."\n";}
 catch(Throwable $e){$f=['operation'=>V33_OP,'state'=>'failed_read_only_business_live30_frontier_plan','reason'=>preg_replace('/[^A-Za-z0-9_.:-]+/','_',mb_substr($e->getMessage(),0,140)),'provider_http_calls'=>0,'database_writes'=>0,'mapping_writes'=>0];$h=v33_save($dir.'/result.json',$f);v33_save($dir.'/receipt.json',['operation'=>V33_OP,'state'=>$f['state'],'result_sha256'=>$h,'readback_verified'=>true,'provider_http_calls'=>0,'database_writes'=>0,'mapping_writes'=>0]);fwrite(STDERR,$f['reason']."\n");exit(2);}
}
