<?php
declare(strict_types=1);
const LM_OP='hotel-match-refresh82-samo-native-1971-20260919-v3',LM_ROUTER_SHA='3b189d1b7313eb85743a6d22be48aa7323725fe6fb57e8d47b6e5ea220b1cb8f',LM_DETAIL_SHA='9d8be005458ca901dac8f94a7224662ae25833882dda2ed6687d184a660af034',LM_MAX_CALLS=100,LM_MAX_PRICE=90,LM_MAX_PAGES=8;
if(in_array('--self-test',$argv??[],true)){require_once __DIR__.'/hotel_match_refresh82_samo_native_helpers_v3.php';lm_need(lm_id('315')==='315','id');$f=lm_fact(['hotelKey'=>123,'operatorKey'=>315,'original'=>['hotelKey'=>834805]],'315');lm_need(($f['native_operator_hotel_id']??'')==='834805','fact');echo"REFRESH82_SAMO_NATIVE_SELFTEST_OK\n";exit(0);}
if(PHP_SAPI!=='cli')exit(2);
$dir=(string)getenv('MATCH_OPERATION_DIR');$root=realpath((string)getenv('ANYTOUR_ROOT'));$rp=realpath((string)getenv('MATCH_ROUTER'));$dp=realpath((string)getenv('MATCH_DETAIL'));$v1=realpath((string)getenv('MATCH_V1_DIR'));$sha=(string)getenv('MATCH_SOURCE_SHA');
if(!is_dir($dir)||basename($dir)!==LM_OP||!is_string($root)||!is_string($rp)||hash_file('sha256',$rp)!==LM_ROUTER_SHA||!is_string($dp)||hash_file('sha256',$dp)!==LM_DETAIL_SHA||!is_string($v1)||!is_dir($v1)||!preg_match('/^[a-f0-9]{40}$/D',$sha))throw new RuntimeException('runtime');
$res=json_decode((string)file_get_contents($dir.'/reservation.json'),true,32,JSON_THROW_ON_ERROR);if(($res['operation']??'')!==LM_OP||($res['state']??'')!=='reserved_before_provider_access')throw new RuntimeException('reservation');
require_once $dir.'/payload/hotel_match_refresh82_samo_native_helpers_v3.php';require_once $dir.'/payload/hotel_match_common4_operator_binding_v1.php';require_once $dir.'/payload/andromeda-network-transport-failure.php';require_once $dir.'/payload/andromeda-transport.php';require_once $dir.'/payload/andromeda-client.php';
$router=json_decode((string)file_get_contents($rp),true,128,JSON_THROW_ON_ERROR);$detail=json_decode((string)file_get_contents($dp),true,128,JSON_THROW_ON_ERROR);lm_need(($router['detail_needed_count']??0)===82&&($detail['attempted']??0)===82,'inputs82');
$tvCanon=[13=>'anex',18=>'biblio_globus',25=>'funsun',43=>'intourist'];$canonNs=['anex'=>'operator_5','biblio_globus'=>'operator_115','funsun'=>'operator_315','intourist'=>'operator_342'];$expected=['anex'=>'5','biblio_globus'=>'115','funsun'=>'315','intourist'=>'342'];
$det=[];foreach($detail['edges']as$e){$k=(int)$e['tv_hotel_id'].'|'.(int)$e['operator_id'];lm_need(($e['state']??'')==='detail_identity_verified'&&isset($tvCanon[(int)$e['operator_id']]),'detail_edge');$det[$k]=$e;}lm_need(count($det)===82,'det82');
$input=[];$ids=[];foreach($router['detail_needed']as$x){$hid=(int)$x['tv_hotel_id'];$op=(int)$x['tv_operator_id'];$k=$hid.'|'.$op;lm_need(isset($det[$k]),'pair_join');$ids[$hid]=true;$input[$k]=['router'=>$x,'detail'=>$det[$k],'canonical'=>$tvCanon[$op],'namespace'=>$canonNs[$tvCanon[$op]]];}
$ids=array_keys($ids);sort($ids,SORT_NUMERIC);$ph=implode(',',array_fill(0,count($ids),'?'));$dbf=is_file($root.'/data/db-v1.php')?$root.'/data/db-v1.php':$root.'/v2/data/db-v1.php';require_once$dbf;$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION READ ONLY');
$current=[];foreach(lm_rows($db,"SELECT id,name,country_name,region_name,subregion_name,is_active FROM catalog_hotels WHERE id IN ($ph)",$ids)as$h)$current[(int)$h['id']]=$h;$aliases=[];foreach(lm_rows($db,"SELECT hotel_id,alias FROM hotel_aliases WHERE hotel_id IN ($ph)",$ids)as$x){$v=trim((string)$x['alias']);if($v!=='')$aliases[(int)$x['hotel_id']][]=$v;}
$ns=array_values($canonNs);$nph=implode(',',array_fill(0,count($ns),'?'));$cur=lm_rows($db,"SELECT supplier_namespace,external_hotel_id,local_hotel_id,decision_status FROM andromeda_hotel_identities WHERE supplier_namespace IN ($nph) AND local_hotel_id IN ($ph)",array_merge($ns,$ids));$db->rollBack();$by=[];foreach($cur as$x)$by[$x['supplier_namespace'].'|'.(int)$x['local_hotel_id']][]=$x;
$active=[];$skipped=[];foreach($input as$k=>$x){$hid=(int)$x['router']['tv_hotel_id'];$h=$current[$hid]??null;$rows=$by[$x['namespace'].'|'.$hid]??[];if(!$h||(int)$h['is_active']!==1){$skipped[]=['key'=>$k,'state'=>'inactive'];continue;}if(array_filter($rows,fn($z)=>$z['decision_status']==='accepted')){$skipped[]=['key'=>$k,'state'=>'current_resolved'];continue;}if(array_filter($rows,fn($z)=>$z['decision_status']==='conflict')){$skipped[]=['key'=>$k,'state'=>'current_conflict'];continue;}$x['current_hotel']=$h;$x['current_aliases']=$aliases[$hid]??[];$active[$k]=$x;}lm_need($active!==[],'all_closed');
$in=file('php://stdin',FILE_IGNORE_NEW_LINES);$user=trim((string)($in[0]??''));$pass=trim((string)($in[1]??''));unset($in);lm_need($user!==''&&$pass!=='','credentials');
$calls=0;$priceCalls=0;$manifest=[];$providerAccess=false;$reserve=function(string $kind,array $meta=[])use(&$calls,$dir){$calls++;lm_need($calls<=LM_MAX_CALLS,'call_cap');lm_write($dir.'/provider-calls.jsonl',json_encode(['seq'=>$calls,'kind'=>$kind,'at_utc'=>gmdate('c'),'meta'=>$meta],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",false);};
$aliasesByCountry=['Танзания'=>['Танзания','Tanzania'],'Маврикий'=>['Маврикий','Mauritius'],'Китай'=>['Китай','China'],'Турция'=>['Турция','Turkey','Turkiye','Türkiye'],'Египет'=>['Египет','Egypt'],'Шри-Ланка'=>['Шри-Ланка','Шри Ланка','Sri Lanka']];
try{
 $providerAccess=true;$reserve('login');$cat=new AnyTourAndromedaClient(new AnyTourAndromedaTransport(false,false),true);$cat->login($user,$pass);unset($user,$pass);$session=$cat->privateSession();lm_need(is_array($session),'session');
 $files=['townfrom'=>['raw-catalog-townfrom.json','1d6865923bd54cf32e20b386419328636d684d530ed0ebfa313fc69788c2b661'],'state'=>['raw-catalog-state.json','6320370a38bc49c736f47b544b814ed6831a8b20d6d5e7e8fdd75436d1aa4aed'],'Китай'=>['raw-catalog-0d4a7aaa20.json','5a6851b3462392f563c65ac13c28459261cbd58a4d437bb24115716995f4c560'],'Турция'=>['raw-catalog-13965a9cf6.json','564da2af9cb248a6860b1705285f106d4f022ffbbac36a7fcfe2630d91a74b39'],'Маврикий'=>['raw-catalog-490f3ae3b6.json','3278cf955d7fd87c9a5694783b1434c23c8ce94717b9b68dc86e5ecbe7b692ce'],'Танзания'=>['raw-catalog-b897da4c1b.json','b9b27238c1c980bbf5015ecf6f5c46bacada55251fcd0d92d373fa11bcd5e056'],'Шри-Ланка'=>['raw-catalog-bfa5c7498a.json','bbe38eacc0a64ab7adb4ab82d2c5d9dbf2a795f5d80d4e13c6f1c1a75aa5b63a'],'Египет'=>['raw-catalog-dfd0573e11.json','feecbab9f7cc6a6bb093ab5a744b2a843e79be6e4f570bd80b234661ac8b5755']];
 $load=function(string $key)use($files,$v1){[$n,$h]=$files[$key];$p=$v1.'/'.$n;lm_need(is_file($p)&&hash_file('sha256',$p)===$h,'retained_'.$key);return json_decode((string)file_get_contents($p),true,64,JSON_THROW_ON_ERROR);};
 $tf=$load('townfrom');$st=$load('state');$dep=lm_dict($tf['TOWNFROM'],['Москва','Moscow']);$countries=[];foreach($active as$x)$countries[(string)$x['current_hotel']['country_name']]=true;$catalogs=[];$stateIds=[];$bindings=[];
 foreach(array_keys($countries)as$country){lm_need(isset($aliasesByCountry[$country]),'country_alias_'.$country);$sid=lm_dict($st['STATE'],$aliasesByCountry[$country]);$stateIds[$country]=$sid;$all=$load($country);$bind=hm_common4_resolve($all,'samo');foreach($expected as$cn=>$oid)lm_need((string)$bind[$cn]['provider_operator_id']===$oid,'operator_'.$cn.'_'.$country);$bindings[$country]=$bind;$catalogs[$country]=lm_provider((array)$all['HOTELS'],lm_towns((array)$all['TOWNTO']));}
 $plans=[];$groups=[];
 foreach($active as$k=>$x){$hid=(int)$x['router']['tv_hotel_id'];$country=(string)$x['current_hotel']['country_name'];$cand=lm_candidates($x['current_hotel'],$x['current_aliases'],$catalogs[$country]);$cids=array_keys($cand['candidates']);$opid=$expected[$x['canonical']];$date=(string)$x['router']['departure_date'];$nights=(int)$x['router']['nights'];$gk=implode('|',[$country,$opid,$date,$nights]);$native=array_map('strval',(array)($x['detail']['positive_native_candidates']??[]));$plans[$k]=['tv_hotel_id'=>$hid,'hotel_name'=>$x['current_hotel']['name'],'country'=>$country,'region_name'=>$x['current_hotel']['region_name'],'subregion_name'=>$x['current_hotel']['subregion_name'],'tv_operator_id'=>(int)$x['router']['tv_operator_id'],'canonical_operator'=>$x['canonical'],'samo_operator_id'=>$opid,'native_tokens'=>$native,'link_state'=>$x['detail']['link_state']??null,'operator_link_sha256'=>$x['detail']['operator_link_sha256']??null,'date'=>$date,'nights'=>$nights,'retrieval_mode'=>$cand['mode'],'candidates'=>$cand['candidates'],'candidate_ids'=>$cids,'facts'=>[],'group_key'=>$gk];if(!$cids)continue;$groups[$gk]['country']=$country;$groups[$gk]['operator_id']=$opid;$groups[$gk]['date']=$date;$groups[$gk]['nights']=$nights;$groups[$gk]['targets'][]=$k;foreach($cids as$cid)$groups[$gk]['candidate_ids'][$cid]=true;}
 $retainedPrice=['6b34d63513'=>['raw-price-6b34d63513-c0-p1.json','3a765b008309f3a7e52e05fd3983122d0f41e3705e072bde7898d06ac627d98c'],'1b2e9ad2d1'=>['raw-price-1b2e9ad2d1-c0-p1.json','fd3cca6e51cb34d3deb714be784ef0528281eccfb53935d35b36f459f3549fc9'],'d8bf7a5eb1'=>['raw-price-d8bf7a5eb1-c0-p1.json','6008da3e1eee3a680499bc16517f9ae887d8eb60ee19d1327f9337819985cd1c']];
foreach($groups as$gk=>&$g){$allIds=array_keys($g['candidate_ids']);sort($allIds,SORT_NATURAL);$g['chunks']=[];$prefix=substr(hash('sha256',$gk),0,10);
 if(isset($retainedPrice[$prefix])){lm_need(count($allIds)===3,'retained_group_shape_'.$prefix);[$fn,$fh]=$retainedPrice[$prefix];$pp=$v1.'/'.$fn;lm_need(is_file($pp)&&hash_file('sha256',$pp)===$fh,'retained_price_'.$prefix);$reply=json_decode((string)file_get_contents($pp),true,64,JSON_THROW_ON_ERROR);$seen=[];foreach((array)($reply['PRICES']??[])as$row){if(!is_array($row)||!($fact=lm_fact($row,$g['operator_id'])))continue;$sid=$fact['samo_hotel_id'];if(!in_array($sid,$allIds,true))continue;$seen[$sid]=true;foreach($g['targets']as$tid)if(isset($plans[$tid]['candidates'][$sid]))$plans[$tid]['facts'][]=$fact;}$pc=(int)($reply['PAGES_COUNT']??0);lm_need($pc<=1,'retained_price_not_terminal');$g['chunks'][]=['candidate_ids'=>$allIds,'pages_read'=>1,'pages_count_reported'=>$pc,'seen_candidate_ids'=>array_keys($seen),'pagination_incomplete'=>false,'retained_v1'=>true];unset($g['candidate_ids']);continue;}
 foreach(array_chunk($allIds,15)as$ci=>$chunk){$params=['TOWNFROMINC'=>$dep,'STATEINC'=>$stateIds[$g['country']],'CHECKIN_BEG'=>str_replace('-','',$g['date']),'CHECKIN_END'=>str_replace('-','',$g['date']),'NIGHTS_FROM'=>$g['nights'],'NIGHTS_TILL'=>$g['nights'],'ADULT'=>2,'CHILD'=>0,'CURRENCYINC'=>643,'OPERATORS'=>$g['operator_id'],'HOTELS'=>implode(',',$chunk),'PACKETTYPE'=>0,'PAGE'=>1];$needed=array_fill_keys($chunk,true);$seen=[];$pages=0;$pcnt=null;
  for($p=1;$p<=LM_MAX_PAGES;$p++){lm_need(++$priceCalls<=LM_MAX_PRICE,'price_cap');$params['PAGE']=$p;$reserve('price',['group'=>substr(hash('sha256',$gk),0,12),'chunk'=>$ci,'page'=>$p,'hotels'=>count($chunk)]);$cl=new AnyTourAndromedaClient(new AnyTourAndromedaTransport(true,false),true);$cl->restorePrivateSession($session);$reply=$cl->price($params);lm_raw($dir,'price-'.$prefix.'-c'.$ci.'-p'.$p,$reply,$manifest);$pages++;$pcnt=(int)($reply['PAGES_COUNT']??0);foreach((array)($reply['PRICES']??[])as$row){if(!is_array($row)||!($fact=lm_fact($row,$g['operator_id'])))continue;$sid=$fact['samo_hotel_id'];if(!isset($needed[$sid]))continue;$seen[$sid]=true;foreach($g['targets']as$tid)if(isset($plans[$tid]['candidates'][$sid]))$plans[$tid]['facts'][]=$fact;}if(!array_diff_key($needed,$seen)||$pcnt===0||$p>=$pcnt)break;}
  $g['chunks'][]=['candidate_ids'=>$chunk,'pages_read'=>$pages,'pages_count_reported'=>$pcnt,'seen_candidate_ids'=>array_keys($seen),'pagination_incomplete'=>(bool)(array_diff_key($needed,$seen)&&$pcnt!==null&&$pages<$pcnt),'retained_v1'=>false];}unset($g['candidate_ids']);}unset($g);
$counts=[];$dossiers=[];foreach($plans as$p){$direct=[];$returned=[];$incomplete=false;if(isset($groups[$p['group_key']]))foreach($groups[$p['group_key']]['chunks']as$ch)if($ch['pagination_incomplete'])$incomplete=true;foreach($p['facts']as$f){$returned[$f['samo_hotel_id']]=true;if($f['native_operator_hotel_id']!==null&&in_array((string)$f['native_operator_hotel_id'],$p['native_tokens'],true))$direct[$f['samo_hotel_id']]=$f;}$state=!$p['candidate_ids']?'no_catalog_candidate':($incomplete?'pagination_hold':(!$returned?'not_returned_exact_context':(count($direct)===1?'direct_native_bridge':(count($direct)>1?'ambiguous_direct_bridge':'returned_without_native_match'))));$counts[$state]=($counts[$state]??0)+1;$dossiers[]=['tv_hotel_id'=>$p['tv_hotel_id'],'hotel_name'=>$p['hotel_name'],'country'=>$p['country'],'tv_operator_id'=>$p['tv_operator_id'],'canonical_operator'=>$p['canonical_operator'],'samo_operator_id'=>$p['samo_operator_id'],'native_tokens'=>$p['native_tokens'],'link_state'=>$p['link_state'],'operator_link_sha256'=>$p['operator_link_sha256'],'date'=>$p['date'],'nights'=>$p['nights'],'retrieval_mode'=>$p['retrieval_mode'],'queried_candidate_ids'=>$p['candidate_ids'],'returned_samo_ids'=>array_keys($returned),'direct_bridges'=>array_values($direct),'state'=>$state,'safe_to_write_now'=>false];}
$mh=lm_json_file($dir.'/raw-manifest.json',['files'=>$manifest]);$result=['operation'=>LM_OP,'state'=>'completed_read_only','source_sha'=>$sha,'router_sha256'=>LM_ROUTER_SHA,'detail_sha256'=>LM_DETAIL_SHA,'input_edges'=>82,'current_active_edges'=>count($active),'current_skipped'=>count($skipped),'skipped'=>$skipped,'country_count'=>count($countries),'group_count'=>count($groups),'provider_calls'=>$calls,'price_calls'=>$priceCalls,'tourvisor_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'state_counts'=>$counts,'dossiers'=>$dossiers,'raw_manifest_sha256'=>$mh,'no_replay'=>true];
}catch(Throwable $e){if(isset($db)&&$db->inTransaction())$db->rollBack();$result=['operation'=>LM_OP,'state'=>$providerAccess?'terminal_failed_no_replay':'failed_before_provider_access','source_sha'=>$sha,'reason'=>preg_replace('/[^A-Za-z0-9_.:-]/','_',lm_text($e->getMessage(),120)),'provider_calls'=>$calls,'price_calls'=>$priceCalls,'tourvisor_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>$providerAccess];if($manifest&&!file_exists($dir.'/raw-manifest.json'))$result['raw_manifest_sha256']=lm_json_file($dir.'/raw-manifest.json',['files'=>$manifest]);}
$rh=lm_json_file($dir.'/result.json',$result);lm_json_file($dir.'/receipt.json',['operation'=>LM_OP,'state'=>$result['state'],'result_sha256'=>$rh,'provider_calls'=>$result['provider_calls'],'price_calls'=>$result['price_calls'],'tourvisor_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'raw_manifest_sha256'=>$result['raw_manifest_sha256']??null,'no_replay'=>$result['no_replay']]);echo json_encode(['state'=>$result['state'],'active'=>$result['current_active_edges']??null,'groups'=>$result['group_count']??null,'provider_calls'=>$result['provider_calls'],'price_calls'=>$result['price_calls'],'state_counts'=>$result['state_counts']??null,'reason'=>$result['reason']??null],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";exit(($result['state']??'')==='completed_read_only'?0:2);
