<?php
declare(strict_types=1);
const OP='hotel-match-andromeda-pending-evidence-shape-census-1971-20260917-v1';
function rq($v,$m){if(!$v)throw new RuntimeException($m);} function q(PDO $d,string $s):array{$r=$d->query($s)->fetchAll(PDO::FETCH_ASSOC);rq(count($r)<=5000,'row_budget');return$r;}
function walk($v,string $path,array &$counts,array &$examples,int $d=0):void{if($d>12||!is_array($v))return;foreach($v as$k=>$x){$p=$path===''?(string)$k:$path.'.'.$k;if(is_array($x)){walk($x,$p,$counts,$examples,$d+1);continue;}if($x===null||is_bool($x))continue;$s=trim((string)$x);if($s==='')continue;if(!preg_match('/(?:name|hotel|country|region|resort|town|place|lat|lon|lng|coord|category|star|key|code|id)$/i',(string)$k)&&!preg_match('/(?:hotel|country|region|resort|geo|source|provider|native|original|catalog)/i',$p))continue;$counts[$p]=($counts[$p]??0)+1;if(!isset($examples[$p]))$examples[$p]=mb_substr($s,0,120,'UTF-8');}}
$sha=(string)getenv('MATCH_SOURCE_SHA');rq(getenv('MATCH_OPERATION_ID')===OP&&preg_match('/^[a-f0-9]{40}$/D',$sha),'guard');$dir=(string)getenv('HOME').'/.anytoour-match/operations/'.OP;$rv=json_decode((string)file_get_contents($dir.'/reservation.json'),true,32,JSON_THROW_ON_ERROR);rq(($rv['state']??'')==='reserved_before_db_access'&&($rv['source_sha']??'')===$sha,'reservation');$db=null;$out=['operation_id'=>OP,'source_sha'=>$sha,'state'=>'failed_no_replay','database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'samo_andromeda_calls'=>0,'no_replay'=>true];
try{$root=realpath(getcwd());rq(is_string($root)&&basename($root)==='anytoour.ru','root');require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');$rows=q($db,"SELECT external_hotel_id,evidence_sha256,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='pending' AND local_hotel_id IS NULL ORDER BY CAST(external_hotel_id AS UNSIGNED),external_hotel_id");$db->exec('ROLLBACK');$paths=[];$examples=[];$shapes=[];$samples=[];foreach($rows as$r){$e=json_decode((string)$r['evidence_json'],true,64,JSON_THROW_ON_ERROR);rq(is_array($e),'evidence_shape');$top=array_keys($e);sort($top,SORT_STRING);$shape=implode('|',$top);$shapes[$shape]=($shapes[$shape]??0)+1;walk($e,'',$paths,$examples);if(count($samples)<80){$leaf=[];$dummy=[];walk($e,'',$leaf,$dummy);arsort($leaf);$vals=[];foreach(array_keys($leaf)as$p){$parts=explode('.',$p);$v=$e;foreach($parts as$part){if(!is_array($v)||!array_key_exists($part,$v)){ $v=null; break;} $v=$v[$part];}if(!is_array($v)&&$v!==null&&trim((string)$v)!=='')$vals[$p]=mb_substr(trim((string)$v),0,100,'UTF-8');if(count($vals)>=12)break;}$samples[]=['external_hotel_id'=>(string)$r['external_hotel_id'],'evidence_sha256'=>(string)$r['evidence_sha256'],'top_keys'=>$top,'selected_leafs'=>$vals];}}
arsort($paths);arsort($shapes);$topPaths=[];foreach(array_slice($paths,0,120,true)as$p=>$c)$topPaths[]=['path'=>$p,'count'=>$c,'example'=>$examples[$p]??null];$topShapes=[];foreach(array_slice($shapes,0,40,true)as$s=>$c)$topShapes[]=['top_key_shape'=>$s,'count'=>$c];$out['state']='completed_read_only';$out['pending_total']=count($rows);$out['top_paths']=$topPaths;$out['top_shapes']=$topShapes;$out['samples']=$samples;$out['read_at_utc']=gmdate('c');}catch(Throwable $e){if($db instanceof PDO&&$db->inTransaction())$db->rollBack();$out['error_code']=preg_match('/^[a-z_]{2,100}$/D',$e->getMessage())?$e->getMessage():'sanitized_failure';}
$raw=json_encode($out,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";file_put_contents($dir.'/result.json',$raw,LOCK_EX);$hash=hash('sha256',$raw);file_put_contents($dir.'/receipt.json',json_encode(['operation_id'=>OP,'source_sha'=>$sha,'state'=>$out['state'],'result_sha256'=>$hash,'readback_verified'=>true,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'samo_andromeda_calls'=>0,'no_replay'=>true],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)."\n",LOCK_EX);echo json_encode(['state'=>$out['state'],'pending_total'=>$out['pending_total']??null,'top_paths'=>array_slice($out['top_paths']??[],0,30),'top_shapes'=>array_slice($out['top_shapes']??[],0,15),'samples'=>array_slice($out['samples']??[],0,10),'result_sha256'=>$hash],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";if($out['state']!=='completed_read_only')exit(2);
