<?php
declare(strict_types=1);
const N31_OP='hotel-match-new31-samo-native-1971-20260920-v1';
const N31_INTAKE='3f7ffe8224ca0ca346fa24d00980ea46d54f9a7caf6ca2fd178c26995856695b';
const N31_OLD='34c0f56d9640c0e29bc59d2c7355dad3728fe421e18db55e528eba013cb58e3b';
const N31_CAP=100;
function n31_need(bool $b,string $s):void{if(!$b)throw new RuntimeException($s);}
function n31_raw(string $p,string $b):string{$f=fopen($p,'xb');n31_need(is_resource($f),'exclusive_file');try{n31_need(fwrite($f,$b)===strlen($b)&&fflush($f),'file_write');if(function_exists('fsync'))n31_need(fsync($f),'file_sync');}finally{fclose($f);}n31_need(file_get_contents($p)===$b,'file_readback');return hash('sha256',$b);}
function n31_save(string $p,array $a):string{return n31_raw($p,json_encode($a,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR)."\n");}
function n31_load(string $p,?string $sha=null):array{if($sha!==null)n31_need(hash_file('sha256',$p)===$sha,'input_hash');$a=json_decode((string)file_get_contents($p),true,128,JSON_THROW_ON_ERROR);n31_need(is_array($a),'input_shape');return$a;}
function n31_norm(string $s):string{$s=function_exists('mb_strtolower')?mb_strtolower(trim($s),'UTF-8'):strtr(strtolower(trim($s)),array_combine(preg_split('//u','АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ',-1,PREG_SPLIT_NO_EMPTY),preg_split('//u','абвгдеёжзийклмнопрстуфхцчшщъыьэюя',-1,PREG_SPLIT_NO_EMPTY)));return trim(preg_replace('/[^\p{L}\p{N}]+/u',' ',str_replace('ё','е',$s))??'');}
function n31_variants(string $s):array{$v=[$s];if(preg_match('/^(.+?)\s*\((?:EX\.?|FORMERLY|БЫВШ\.?)\s*([^)]*)\)/iu',$s,$m)){$v[]=$m[1];$v[]=$m[2];}$out=[];foreach($v as$x){$k=n31_norm($x);if($k!=='')$out[$k]=true;}return array_keys($out);}
function n31_tokens(string $s):array{$o=[];foreach(explode(' ',n31_norm($s))as$t)if(preg_match('/^.{2}/us',$t)===1&&!in_array($t,['hotel','hotels','отель','ex'],true))$o[$t]=true;return array_keys($o);}
function n31_rank(array $target,array $hotels):array{$variants=n31_variants((string)$target['name']);$tt=n31_tokens((string)$target['name']);$freq=[];$pool=[];
 foreach($hotels as$h){if(!is_array($h)||!preg_match('/^[1-9][0-9]*$/D',(string)($h['id']??'')))continue;$tok=[];$vs=[];foreach(['name','lName']as$k){if(!is_string($h[$k]??null))continue;foreach(n31_tokens($h[$k])as$t)$tok[$t]=true;foreach(n31_variants($h[$k])as$v)$vs[$v]=true;}$pool[(string)$h['id']]=['raw'=>$h,'tokens'=>array_keys($tok),'variants'=>array_keys($vs)];foreach($tok as$t=>$_)$freq[$t]=($freq[$t]??0)+1;}
 $out=[];foreach($pool as$id=>$p){$common=array_intersect($tt,$p['tokens']);$exact=(bool)array_intersect($variants,$p['variants']);if(!$exact&&count($common)<1)continue;$coverage=count($tt)?count($common)/count($tt):0;if(!$exact&&$coverage<0.34)continue;$score=$exact?1000.0:0.0;foreach($common as$t)$score+=1.0/($freq[$t]??1);$score+=10*$coverage;foreach(['region_name','subregion_name']as$g){$label=n31_norm((string)($target[$g]??''));if($label!==''&&in_array($label,[n31_norm((string)($p['raw']['town']??'')),n31_norm((string)($p['raw']['townLName']??''))],true))$score+=5;}$out[]=['samo_candidate_id'=>(string)$id,'catalog_raw'=>$p['raw'],'retrieval_exact_variant'=>$exact,'retrieval_score'=>$score];}
 usort($out,static fn($a,$b)=>[$b['retrieval_score'],$a['samo_candidate_id']]<=>[$a['retrieval_score'],$b['samo_candidate_id']]);return array_slice($out,0,3);}
function n31_dict(array $rows,string $name):?int{$ids=[];foreach($rows as$r)if(is_array($r)&&preg_match('/^[1-9][0-9]*$/D',(string)($r['id']??''))&&(n31_norm((string)($r['name']??''))===n31_norm($name)||n31_norm((string)($r['lName']??''))===n31_norm($name)))$ids[(int)$r['id']]=true;return count($ids)===1?(int)array_key_first($ids):null;}
function n31_bridge(array $rows,string $sid,array $anchors,array $c):array{$exact=[];$native=[];$flags=[];
 foreach($rows as$r){if(!is_array($r)||(string)($r['hotelKey']??'')!==$sid||(string)($r['operatorKey']??'')!=='5')continue;
  if((string)($r['checkIn']??'')!==date('d.m.Y',strtotime($c['departure_date']))||(int)($r['nights']??-1)!==(int)$c['nights']||(int)($r['adult']??-1)!==(int)$c['adults']||(int)($r['child']??-1)!==(int)$c['children_count'])continue;
  $o=is_array($r['original']??null)?$r['original']:[];$a=(string)($o['hotelKey']??'');if(!preg_match('/^[1-9][0-9]*$/D',$a))continue;$native[$a]=true;$flag=array_key_exists('isOperatorHotelKey',$r)&&is_scalar($r['isOperatorHotelKey'])?(string)$r['isOperatorHotelKey']:'missing';$flags[$flag]=true;
  if(in_array($a,array_map('strval',$anchors),true))$exact[]=['samo_hotel_id'=>$sid,'native_anex_id'=>$a,'is_operator_hotel_key_raw'=>$r['isOperatorHotelKey']??null,'namespace_flag_source'=>'PRICES[].isOperatorHotelKey','provider_row'=>$r];
 }
 $state=$exact===[]?'no_exact_native_anchor':(count($native)!==1?'native_conflict_hold':(array_keys($flags)===['0']||array_keys($flags)===[0]?'direct_canonical_native_bridge':'native_namespace_hold'));
 return['state'=>$state,'native_ids_observed'=>array_keys($native),'namespace_flags_observed'=>array_keys($flags),'first_exact_fact'=>$exact[0]??null,'exact_fact_count'=>count($exact),'safe_to_write_now'=>false];}
function n31_rows(PDO $db,string $sql,array $p=[]):array{$s=$db->prepare($sql);$s->execute(array_values($p));$r=$s->fetchAll(PDO::FETCH_ASSOC);n31_need(count($r)<=50000,'db_row_cap');return$r;}
if(($argv[1]??'')==='--self-test'){
 $h=['name'=>'GOAN HERITAGE'];$rank=n31_rank($h,[['id'=>2,'name'=>'OTHER HOTEL'],['id'=>3,'name'=>'Goan Heritage','lName'=>'Goan Heritage']]);n31_need(count($rank)===1&&$rank[0]['samo_candidate_id']==='3','rank');n31_need(in_array('catamaran',n31_variants('NEW (EX. CATAMARAN)'),true),'aliases');n31_need(in_array('family',n31_tokens('FAMILY SEA VIEW HOTEL'),true),'qualifier');n31_need(n31_dict([['id'=>5,'name'=>'Anex Tour']],'Anex Tour')===5,'operator');n31_need(n31_dict([['id'=>5,'name'=>'X'],['id'=>6,'name'=>'X']],'X')===null,'ambiguous_dict');
 $c=['departure_date'=>'2026-12-12','nights'=>11,'adults'=>2,'children_count'=>0];$r=['hotelKey'=>3,'operatorKey'=>5,'checkIn'=>'12.12.2026','nights'=>11,'adult'=>2,'child'=>0,'isOperatorHotelKey'=>0,'original'=>['hotelKey'=>99]];n31_need(n31_bridge([$r],'3',[99],$c)['state']==='direct_canonical_native_bridge','bridge');$r['isOperatorHotelKey']=1;n31_need(n31_bridge([$r],'3',[99],$c)['state']==='native_namespace_hold','namespace');$r['operatorKey']=4;n31_need(n31_bridge([$r],'3',[99],$c)['state']==='no_exact_native_anchor','foreign_operator');echo"MATCH_NEW31_NATIVE_SELFTEST_OK 8\n";exit(0);
}
n31_need(PHP_SAPI==='cli'&&getenv('MATCH_OPERATION_ID')===N31_OP,'operation');$dir=rtrim((string)getenv('HOME'),'/').'/.anytoour-match/operations/'.N31_OP;n31_need(realpath((string)getenv('MATCH_OPERATION_DIR'))===$dir,'op_dir');$sha=(string)getenv('MATCH_SOURCE_SHA');n31_need(preg_match('/^[a-f0-9]{40}$/D',$sha)===1,'source');$res=n31_load($dir.'/reservation.json');n31_need(($res['operation_id']??'')===N31_OP&&($res['source_sha']??'')===$sha&&($res['state']??'')==='reserved_before_access','reservation');
$base=['operation_id'=>N31_OP,'source_sha'=>$sha,'input_sha256'=>N31_INTAKE,'tourvisor_calls'=>0,'direct_anex_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'safe_to_write_now'=>false,'no_replay'=>true];$calls=0;$last=0.0;$db=null;$dossiers=[];$skipped=[];
try{
 n31_save($dir.'/execution-reservation.json',$base+['state'=>'started_before_access']);$in=n31_load($dir.'/inputs/intake.json',N31_INTAKE);$old=n31_load($dir.'/inputs/retained153.json',N31_OLD);$input=array_values(array_filter($in['dossiers'],static fn($d)=>($d['state']??'')==='new_missing_samo_edge_needs_evidence_dedupe'));n31_need(count($input)===31,'exact31');
 require_once __DIR__.'/hotel_match_anex_effective_coverage.php';require_once dirname(__DIR__,2).'/app/integrations/andromeda-transport.php';require_once dirname(__DIR__,2).'/app/integrations/andromeda-client.php';
 $root=realpath(getcwd());n31_need(is_string($root)&&basename($root)==='anytoour.ru','root');require_once(is_file($root.'/data/db-v1.php')?$root.'/data/db-v1.php':$root.'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');$coverage=AnyTourMatchAnexEffectiveCoverage::fromPdo($db);$bindings=[];
 foreach($old['dossiers']as$d){$dep=(int)$d['departure_id'];$bind=[(string)$d['departure_name'],(int)$d['samo_townfrom_id']];if(isset($bindings[$dep]))n31_need($bindings[$dep]===$bind,'retained_departure_conflict');$bindings[$dep]=$bind;}
 $active=[];foreach($input as$d){$id=(int)$d['local_hotel_id'];n31_need($id!==420,'protected_target');$h=n31_rows($db,'SELECT * FROM catalog_hotels WHERE id=?',[$id]);$ident=n31_rows($db,'SELECT * FROM andromeda_hotel_identities WHERE local_hotel_id=?',[$id]);$native=array_values(array_intersect(array_map('intval',$d['anex_native_ids']),array_map('intval',array_keys($coverage['by_local'][$id]??[]))));$c=$d['preferred_context'];$dep=(int)$c['departure_id'];$depRows=n31_rows($db,'SELECT id,name,is_active FROM catalog_departures WHERE id=?',[$dep]);
  if(count($h)!==1||(int)$h[0]['is_active']!==1||$ident!==[]||$native===[]||count($depRows)!==1||(int)$depRows[0]['is_active']!==1||!isset($bindings[$dep])||n31_norm($depRows[0]['name'])!==n31_norm($bindings[$dep][0])||(string)$h[0]['country_id']!==(string)$c['country_id']){$skipped[]=['local_hotel_id'=>$id,'state'=>'current_identity_or_departure_hold','saved_identity_rows'=>$ident,'safe_to_write_now'=>false];continue;}
  n31_need((int)$c['children_count']===0&&(string)$c['child_ages_signature']===''&&(string)$c['operator_id']==='13'&&(string)$c['source']==='user_search','context');$d['current_hotel']=$h[0];$d['current_anex_native_ids']=$native;$d['samo_townfrom_id']=$bindings[$dep][1];$active[]=$d;
 }$db->rollBack();n31_save($dir.'/current-preflight.json',['active'=>$active,'skipped'=>$skipped,'safe_to_write_now'=>false]);
 $make=function(bool $price=false)use(&$calls,&$last,$dir):AnyTourAndromedaClient{
  $t=new AnyTourAndromedaTransport($price,false);$wrapped=function(string $url,array $opts=[])use($t,&$calls,&$last,$dir):array{
   parse_str((string)parse_url($url,PHP_URL_QUERY),$q);$action=$q['action']??'';n31_need(in_array($action,['login','all','price'],true),'action');n31_need($calls<N31_CAP,'provider_cap');$wait=1.05-(microtime(true)-$last);if($wait>0)usleep((int)ceil($wait*1000000));$seq=++$calls;$stem=sprintf('%03d-%s',$seq,$action);$params=$q;foreach(['sid','username','password','nonce','created']as$k)unset($params[$k]);n31_save($dir.'/call-'.$stem.'-reservation.json',['operation_id'=>N31_OP,'seq'=>$seq,'action'=>$action,'params'=>$params,'state'=>'reserved_unknown_before_http','at_utc'=>gmdate('c')]);$last=microtime(true);$reply=$t($url,$opts);
   if($action!=='login'){n31_need(!isset($q['sid'])||!str_contains((string)$reply['body'],(string)$q['sid']),'session_echo_hold');n31_save($dir.'/raw-http-'.$stem.'.json',$reply);}n31_save($dir.'/call-'.$stem.'-receipt.json',['seq'=>$seq,'action'=>$action,'status'=>$reply['status'],'body_sha256'=>hash('sha256',(string)$reply['body']),'state'=>'http_response_saved']);return$reply;
  };return new AnyTourAndromedaClient($wrapped,true);
 };
 $catalogs=[];$plans=[];if($active!==[]){$lines=file('php://stdin',FILE_IGNORE_NEW_LINES);$u=trim((string)($lines[0]??''));$p=trim((string)($lines[1]??''));unset($lines);n31_need($u!==''&&$p!=='','credentials');$client=$make();$client->login($u,$p);unset($u,$p);$session=$client->privateSession();n31_need($session!==[],'session');
  foreach($active as$d){$dep=(int)$d['preferred_context']['departure_id'];$country=(string)$d['country_raw']['name'];$pk=$dep.'|'.$country;if(array_key_exists($pk,$catalogs))continue;$states=n31_load($dir.'/inputs/raw-state-d'.$dep.'.json');$state=n31_dict($states['STATE'],$country);if($state===null){$catalogs[$pk]=null;continue;}$fn='raw-catalog-'.substr(hash('sha256',$pk),0,12).'.json';if(is_file($dir.'/inputs/'.$fn))$all=n31_load($dir.'/inputs/'.$fn);else{$client=$make();$client->restorePrivateSession($session);$all=$client->catalog('all',['TOWNFROMINC'=>(int)$d['samo_townfrom_id'],'STATEINC'=>$state]);n31_save($dir.'/'.$fn,$all);}
   if(n31_dict($all['OPERATORS'],'Anex Tour')!==5){$catalogs[$pk]=null;continue;}$catalogs[$pk]=['state_id'=>$state,'raw'=>$all,'file'=>$fn];
  }
  foreach($active as$d){$id=(int)$d['local_hotel_id'];$c=$d['preferred_context'];$pk=(int)$c['departure_id'].'|'.$d['country_raw']['name'];$cat=$catalogs[$pk]??null;$out=['local_hotel_id'=>$id,'hotel_raw'=>$d['current_hotel'],'country_raw'=>$d['country_raw'],'context'=>$c,'samo_townfrom_id'=>$d['samo_townfrom_id'],'anex_native_ids'=>$d['current_anex_native_ids'],'candidate_attempts'=>[],'safe_to_write_now'=>false];
   if($cat===null){$out['state']='catalog_or_operator_unavailable';$dossiers[]=$out;continue;}$pool=array_values(array_filter($cat['raw']['HOTELS'],static fn($h)=>is_array($h)&&(string)($h['stateKey']??'')===(string)$cat['state_id']));$candidates=n31_rank($d['current_hotel'],$pool);$out['catalog_file']=$cat['file'];$out['state_id']=$cat['state_id'];$out['ranked_candidates']=$candidates;$out['state']=$candidates===[]?'no_catalog_candidate':'not_proven_in_exact_context';
   foreach($candidates as$can){$sid=$can['samo_candidate_id'];$params=['TOWNFROMINC'=>(int)$d['samo_townfrom_id'],'STATEINC'=>$cat['state_id'],'CHECKIN_BEG'=>str_replace('-','',$c['departure_date']),'CHECKIN_END'=>str_replace('-','',$c['departure_date']),'NIGHTS_FROM'=>(int)$c['nights'],'NIGHTS_TILL'=>(int)$c['nights'],'ADULT'=>(int)$c['adults'],'CHILD'=>0,'CURRENCYINC'=>643,'OPERATORS'=>'5','HOTELS'=>$sid,'PACKETTYPE'=>0,'PAGE'=>1];$client=$make(true);$client->restorePrivateSession($session);$reply=$client->price($params);$bridge=n31_bridge($reply['PRICES'],$sid,$d['current_anex_native_ids'],$c);$bridge['raw_http_file']=sprintf('raw-http-%03d-price.json',$calls);$bridge['requested_samo_id']=$sid;$bridge['pages_count_reported']=$reply['PAGES_COUNT'];$out['candidate_attempts'][]=$bridge;if($bridge['first_exact_fact']!==null){$out['state']=$bridge['state'];$out['bridge']=$bridge;break;}}
   n31_save($dir.'/dossier-'.$id.'.json',$out);$dossiers[]=$out;
  }unset($session);
 }
 $counts=[];foreach($dossiers as$d)$counts[$d['state']]=($counts[$d['state']]??0)+1;$result=$base+['state'=>'completed_read_only','input_count'=>31,'active_count'=>count($active),'skipped_count'=>count($skipped),'skipped'=>$skipped,'provider_calls'=>$calls,'state_counts'=>$counts,'dossiers'=>$dossiers];
}catch(Throwable $e){if($db&&$db->inTransaction())$db->rollBack();$reason=preg_match('/^[A-Za-z0-9_]+$/D',$e->getMessage())?$e->getMessage():'provider_or_runtime_error';$result=$base+['state'=>'terminal_failed_no_replay','reason'=>$reason,'error_class'=>get_class($e),'provider_calls'=>$calls,'completed_dossiers'=>$dossiers,'skipped'=>$skipped];}
$rh=n31_save($dir.'/result.json',$result);n31_save($dir.'/receipt.json',['operation_id'=>N31_OP,'state'=>$result['state'],'source_sha'=>$sha,'result_sha256'=>$rh,'provider_calls'=>$calls,'readback_verified'=>hash_file('sha256',$dir.'/result.json')===$rh,'tourvisor_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true]);echo json_encode(['state'=>$result['state'],'provider_calls'=>$calls,'state_counts'=>$result['state_counts']??null,'reason'=>$result['reason']??null,'result_sha256'=>$rh],JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR)."\n";exit($result['state']==='completed_read_only'?0:1);
