<?php
declare(strict_types=1);

const HM2_OP='hotel-match-state116-pending-anex-native-bridge-1971-20260916-v2';
const HM2_STATE='116'; const HM2_COUNTRY=12;
function h2j(array $v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";}
function h2w(string $p,array $v):string{$s=h2j($v);$f=@fopen($p,'x+b');if(!$f)throw new RuntimeException('durable_open');try{if(fwrite($f,$s)!==strlen($s)||!fflush($f))throw new RuntimeException('durable_write');if(function_exists('fsync')&&!fsync($f))throw new RuntimeException('durable_sync');rewind($f);if(stream_get_contents($f)!==$s)throw new RuntimeException('durable_readback');}finally{fclose($f);}return hash('sha256',$s);}
function h2db(string $r):string{foreach([$r.'/data/db-v1.php',$r.'/v2/data/db-v1.php']as$p)if(is_file($p))return$p;throw new RuntimeException('db_missing');}
function h2q(PDO $d,string $s,array $a=[]):array{$q=$d->prepare($s);$q->execute($a);return$q->fetchAll(PDO::FETCH_ASSOC)?:[];}
function h2e($s):array{try{$v=json_decode((string)$s,true,128,JSON_THROW_ON_ERROR);return is_array($v)?$v:[];}catch(Throwable){return[];}}
function h2src(array $e):array{return is_array($e['source']??null)?$e['source']:$e;}
function h2first(array $a,array $ks):?string{foreach($ks as$k)if(isset($a[$k])&&is_scalar($a[$k])&&trim((string)$a[$k])!=='')return trim((string)$a[$k]);return null;}
function h2manual($v):bool{if(!is_array($v))return false;foreach($v as$k=>$x){$k=mb_strtolower((string)$k,'UTF-8');if(in_array($k,['manual','manual_decision','excluded','exclusion','rejected','protected','pair_exclusion'],true)&&($x===true||$x===1||$x==='1'||(is_string($x)&&trim($x)!==''&&!in_array(mb_strtolower(trim($x),'UTF-8'),['false','none','no','0'],true))))return true;if(is_array($x)&&h2manual($x))return true;}return false;}
function h2norm(string $s):string{$s=mb_strtolower($s,'UTF-8');$s=strtr($s,['ё'=>'е','é'=>'e','è'=>'e','á'=>'a','à'=>'a','ä'=>'a','ö'=>'o','ü'=>'u','ç'=>'c','ş'=>'s','ğ'=>'g','ı'=>'i','ñ'=>'n']);$s=preg_replace('/\s*\(\s*(?:ex|ех)\.?\s+[^)]*\)\s*$/u',' ',$s)??$s;$s=preg_replace('/[^\p{L}\p{N}]+/u',' ',$s)??$s;return trim(preg_replace('/\s+/u',' ',$s)??$s);}
function h2tokens(string $s):array{$n=h2norm($s);if($n==='')return[];$g=['hotel','hotels','resort','resorts','spa','the','and','by','отель','спа'];return array_values(array_unique(array_diff(explode(' ',$n),$g)));}
function h2qual(string $s):array{$q=['annex','beach','garden','gardens','north','south','east','west','adult','adults','only','aqua','aquapark','aquamarine','pool','private'];$r=array_values(array_intersect(h2tokens($s),$q));sort($r,SORT_STRING);return$r;}
function h2nums(string $s):array{preg_match_all('/(?<!\p{L})\d+(?!\p{L})/u',h2norm($s),$m);$r=array_values(array_unique($m[0]??[]));sort($r,SORT_STRING);return$r;}
function h2name(?string $a,?string $b):array{if(!$a||!$b)return['ok'=>true,'reason'=>'name_missing_nonblocking'];$aq=h2qual($a);$bq=h2qual($b);if($aq!==$bq)return['ok'=>false,'reason'=>'meaningful_qualifier_conflict','source_qualifiers'=>$aq,'local_qualifiers'=>$bq];$an=h2nums($a);$bn=h2nums($b);if(($an||$bn)&&$an!==$bn)return['ok'=>false,'reason'=>'numeric_conflict','source_numbers'=>$an,'local_numbers'=>$bn];return['ok'=>true,'reason'=>'qualifier_numeric_compatible'];}
function h2num($v):?float{return is_scalar($v)&&is_numeric((string)$v)?(float)$v:null;}
function h2coords(array $e):array{$out=[];$ss=[];$s=h2src($e);if($s)$ss[]=['k'=>'source','v'=>$s];foreach(['geography','geo','coordinates']as$k)if(is_array($e[$k]??null))$ss[]=['k'=>$k,'v'=>$e[$k]];foreach($ss as$x){$v=$x['v'];$a=h2num($v['latitude']??$v['lat']??$v['hotelLatitude']??null);$b=h2num($v['longitude']??$v['lng']??$v['lon']??$v['hotelLongitude']??null);if($a!==null&&$b!==null&&abs($a)<=90&&abs($b)<=180&&!($a==0.0&&$b==0.0))$out[]=['kind'=>$x['k'],'lat'=>$a,'lon'=>$b];}return$out;}
function h2km(float$a,float$b,float$c,float$d):float{$r=6371.0088;$p1=deg2rad($a);$p2=deg2rad($c);$h=sin(deg2rad($c-$a)/2)**2+cos($p1)*cos($p2)*sin(deg2rad($d-$b)/2)**2;return 2*$r*asin(min(1,sqrt($h)));}
function h2state(array$e):string{$s=h2src($e);return(string)(h2first($s,['stateKey','state_id','countryKey'])??'');}
function h2bridges(array$e,string$native):array{$out=[];if(($e['schema']??'')!=='operator-original-price-bridge/1')return$out;$src=is_array($e['source']??null)?$e['source']:[];if((string)($src['operator_key']??'')!=='5'||(string)($src['id']??'')!==$native)return$out;foreach(($e['provider_bridges']??[])as$f){if(!is_array($f)||($f['action']??null)!=='price'||($f['is_operator_hotel_key']??true)!==false||(string)($f['operator_key']??'')!=='5')continue;$id=$f['andromeda_hotel_id']??null;if(is_scalar($id)&&preg_match('/^[1-9][0-9]{0,19}$/D',(string)$id))$out[(string)$id]=['request_sha256'=>$f['request_sha256']??null,'response_sha256'=>$f['response_sha256']??null,'original_name'=>$f['original_name']??null,'hotel_name'=>$f['hotel_name']??null];}return$out;}
if(in_array('--self-test',$argv??[],true)){$e=['schema'=>'operator-original-price-bridge/1','source'=>['operator_key'=>'5','id'=>'123'],'provider_bridges'=>[['andromeda_hotel_id'=>'2001','operator_key'=>'5','action'=>'price','is_operator_hotel_key'=>false]]];if(!isset(h2bridges($e,'123')['2001']))throw new RuntimeException('bridge_selftest');if(h2name('North Beach 2','South Beach 2')['ok'])throw new RuntimeException('name_selftest');echo"PASS\n";exit;}
$op=(string)getenv('OPERATION_ID');$sha=(string)getenv('MATCH_SOURCE_SHA');if($op!==HM2_OP||!preg_match('/^[0-9a-f]{40}$/D',$sha))throw new RuntimeException('operation_environment');$root=realpath(getcwd());$base=rtrim((string)getenv('HOME'),'/').'/.anytoour-match/operations';if(!$root||basename($root)!=='anytoour.ru'||!is_dir($base))throw new RuntimeException('root_guard');$dir=$base.'/'.$op;if(!mkdir($dir,0700))throw new RuntimeException('operation_exists_no_replay');h2w($dir.'/reservation.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'reserved_before_db_access','read_only'=>true,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);
$db=null;try{require_once h2db($root);$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');
$pending=[];foreach(h2q($db,"SELECT external_hotel_id,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='pending' AND local_hotel_id IS NULL ORDER BY external_hotel_id")as$r){$e=h2e($r['evidence_json']);if(h2state($e)!==HM2_STATE)continue;$pending[(string)$r['external_hotel_id']]=['row'=>$r,'evidence'=>$e];}
$nativeSupport=[];$typedRows=0;foreach(h2q($db,"SELECT external_hotel_id,decision_status,local_hotel_id,evidence_json,evidence_sha256 FROM andromeda_hotel_identities WHERE supplier_namespace='operator_5' ORDER BY external_hotel_id")as$r){$typedRows++;$native=(string)$r['external_hotel_id'];$e=h2e($r['evidence_json']);foreach(h2bridges($e,$native)as$aid=>$meta)if(isset($pending[$aid]))$nativeSupport[$aid][$native]=['typed_status'=>(string)$r['decision_status'],'typed_local'=>$r['local_hotel_id']===null?null:(int)$r['local_hotel_id'],'typed_evidence_sha256'=>(string)$r['evidence_sha256'],'bridge'=>$meta];}
$dec=[];foreach(h2q($db,'SELECT anex_hotel_id,catalog_hotel_id,decision_status FROM anex_hotel_decisions ORDER BY anex_hotel_id')as$r)$dec[(string)$r['anex_hotel_id']][]=$r;$maps=[];foreach(h2q($db,"SELECT anex_hotel_id,catalog_hotel_id,enabled,scope,approval_policy FROM anex_hotel_search_mappings WHERE enabled=1 AND scope='preview' ORDER BY anex_hotel_id,catalog_hotel_id")as$r)$maps[(string)$r['anex_hotel_id']][]=$r;$ex=[];foreach(h2q($db,'SELECT anex_hotel_id,catalog_hotel_id FROM anex_review_pair_exclusions ORDER BY anex_hotel_id,catalog_hotel_id')as$r)$ex[(string)$r['anex_hotel_id'].'|'.(int)$r['catalog_hotel_id']]=true;$review=[];$rt=h2q($db,"SELECT TABLE_NAME FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='anex_review_state'");if($rt){$cols=h2q($db,"SELECT COLUMN_NAME FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='anex_review_state'");$cn=array_column($cols,'COLUMN_NAME');if(in_array('anex_hotel_id',$cn,true))foreach(h2q($db,'SELECT anex_hotel_id FROM anex_review_state ORDER BY anex_hotel_id')as$r)$review[(string)$r['anex_hotel_id']]=true;}
$candidates=[];$nativeRoutes=[];foreach($nativeSupport as$aid=>$byNative){foreach($byNative as$native=>$sup){$locs=[];$reason=[];if(isset($review[$native]))$reason[]='review_state_protected';$ds=$dec[$native]??[];if($ds){foreach($ds as$d){if(($d['decision_status']??'')==='accepted'&&$d['catalog_hotel_id']!==null)$locs[(int)$d['catalog_hotel_id']]['manual_accepted']=true;else$reason[]='manual_nonaccepted_protected';}}else{foreach($maps[$native]??[]as$m)$locs[(int)$m['catalog_hotel_id']]['preview_mapping']=true;}
foreach(array_keys($locs)as$l)if(isset($ex[$native.'|'.$l])){unset($locs[$l]);$reason[]='pair_excluded';}
if($reason)$nativeRoutes[$aid][$native]=['route'=>'hold_native_protected','reasons'=>array_values(array_unique($reason)),'candidate_locals'=>array_map('intval',array_keys($locs))];elseif(count($locs)===1){$l=(int)array_key_first($locs);$candidates[$aid][$l][$native]=['support'=>$sup,'anex_sources'=>$locs[$l]];$nativeRoutes[$aid][$native]=['route'=>'native_to_unique_anex_local','candidate_local_id'=>$l,'sources'=>$locs[$l]];}elseif(count($locs)>1)$nativeRoutes[$aid][$native]=['route'=>'hold_native_multiple_anex_locals','candidate_locals'=>array_map('intval',array_keys($locs))];else$nativeRoutes[$aid][$native]=['route'=>'native_without_current_anex_local'];}}
$localIds=[];foreach($candidates as$byL)foreach(array_keys($byL)as$l)$localIds[(int)$l]=true;$hotels=[];if($localIds)foreach(h2q($db,'SELECT id,country_id,name,latitude,longitude,is_active FROM catalog_hotels WHERE id IN ('.implode(',',array_fill(0,count($localIds),'?')).') ORDER BY id',array_keys($localIds))as$h)$hotels[(int)$h['id']]=$h;$occupied=[];foreach(h2q($db,"SELECT external_hotel_id,local_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IS NOT NULL ORDER BY local_hotel_id,external_hotel_id")as$r)$occupied[(int)$r['local_hotel_id']][]=(string)$r['external_hotel_id'];$db->exec('ROLLBACK');
$rows=[];$counts=[];$clean=[];foreach($pending as$aid=>$p){$e=$p['evidence'];$s=h2src($e);$name=h2first($s,['name','hotelName','title']);$byL=$candidates[$aid]??[];$route='no_pending_anex_native_bridge';$target=null;$details=['native_routes'=>$nativeRoutes[$aid]??[]];if(h2manual($e))$route='hold_source_manual_or_protected';elseif(count($byL)>1){$route='hold_ambiguous_anex_local_targets';$details['candidate_local_ids']=array_map('intval',array_keys($byL));}elseif(count($byL)===1){$target=(int)array_key_first($byL);$h=$hotels[$target]??null;if(!$h||(int)$h['is_active']!==1||(int)$h['country_id']!==HM2_COUNTRY)$route='hold_target_country_or_activity';else{$others=array_values(array_filter($occupied[$target]??[],static fn($x)=>$x!==$aid));if($others){$route='hold_target_occupied_by_other_andromeda';$details['occupying_andromeda_ids']=$others;}else{$ng=h2name($name,(string)$h['name']);if(!$ng['ok']){$route='hold_'.$ng['reason'];$details['name_guard']=$ng;}else{$dist=[];foreach(h2coords($e)as$c){$la=h2num($h['latitude']);$lo=h2num($h['longitude']);if($la===null||$lo===null||abs($la)>90||abs($lo)>180||($la==0.0&&$lo==0.0))break;$dist[$c['kind']]=round(h2km($c['lat'],$c['lon'],$la,$lo),3);}if(array_filter($dist,static fn($d)=>$d>5.0)){$route='hold_coordinate_conflict_gt5km';$details['distances_km']=$dist;}else{$route='guard_passed_pending_anex_native_bridge';$details['distances_km']=$dist;$clean[]=['external_hotel_id'=>$aid,'source_name'=>$name,'local_hotel_id'=>$target,'local_name'=>(string)$h['name'],'native_support'=>$byL[$target],'distances_km'=>$dist];}}}}}
$counts[$route]=($counts[$route]??0)+1;$rows[]=['external_hotel_id'=>$aid,'source_name'=>$name,'candidate_local_id'=>$target,'route'=>$route,'details'=>$details];}
ksort($counts,SORT_STRING);$res=['operation_id'=>$op,'source_sha'=>$sha,'state'=>'completed_read_only','schema'=>'state116-pending-anex-native-bridge/1','sealed_state'=>HM2_STATE,'sealed_country_id'=>HM2_COUNTRY,'current_pending_state116'=>count($pending),'operator_5_rows_scanned'=>$typedRows,'state116_with_operator_5_originalkey'=>count($nativeSupport),'state116_with_current_anex_local'=>count($candidates),'route_counts'=>$counts,'prepared_count'=>count($clean),'prepared'=>$clean,'rows'=>$rows,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'booking_calls'=>0,'lead_calls'=>0,'safe_to_write_now'=>false,'no_replay'=>true];$dg=h2w($dir.'/result.json',$res);h2w($dir.'/receipt.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'completed_read_only','result_sha256'=>$dg,'readback_verified'=>true,'current_pending_state116'=>count($pending),'prepared_count'=>count($clean),'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);echo json_encode(['state'=>'completed_read_only','pending'=>count($pending),'operator_bridge'=>count($nativeSupport),'anex_local_bridge'=>count($candidates),'prepared_count'=>count($clean),'route_counts'=>$counts],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";
}catch(Throwable$e){try{if($db instanceof PDO&&$db->inTransaction())$db->rollBack();}catch(Throwable){}$f=['operation_id'=>$op,'source_sha'=>$sha,'state'=>'failed_read_only','error_class'=>get_class($e),'reason'=>preg_match('/^[a-z0-9_]+$/D',$e->getMessage())?$e->getMessage():'sanitized_error','database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true];$dg=h2w($dir.'/failure.json',$f);h2w($dir.'/receipt.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'failed_read_only','failure_sha256'=>$dg,'readback_verified'=>true,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);fwrite(STDERR,"STATE116_PENDING_ANEX_FAILED\n");exit(2);}