<?php
declare(strict_types=1);
require_once __DIR__.'/hotel_match_userseen2041_tv_provider_v1.php';
if(in_array('--self-test',$argv??[],true)){need(candidate(['tours'=>[['operator'=>13,'id'=>'123']]],'samo_only')['operator_id']===13,'cand');need(op_link(13,['operatorLink'=>'https://agent.anextour.ru/x?HOTELLIST=35371'])['link_state']==='captured_single_native','link');echo "M2041_SELFTEST_OK\n";exit(0);}
$dir=(string)getenv('MATCH_OPERATION_DIR');$root=realpath((string)getenv('ANYTOUR_ROOT'));$input=realpath((string)getenv('MATCH_INPUT_PATH'));$sha=(string)getenv('MATCH_SOURCE_SHA');
need(PHP_SAPI==='cli'&&is_dir($dir)&&basename($dir)===OP&&is_string($root)&&is_string($input)&&hash_file('sha256',$input)===INPUT_SHA&&preg_match('/^[a-f0-9]{40}$/D',$sha),'runtime');
$res=json_decode((string)file_get_contents($dir.'/reservation.json'),true,32,JSON_THROW_ON_ERROR);need(($res['operation']??'')===OP&&($res['state']??'')==='reserved_before_server_access','reservation');
$inp=json_decode((string)file_get_contents($input),true,128,JSON_THROW_ON_ERROR);need(($inp['target_count']??0)===2041&&count($inp['targets']??[])===2041,'input_count');
$base=['operation'=>OP,'source_sha'=>$sha,'input_sha256'=>INPUT_SHA,'input_count'=>2041,'provider_day'=>DAY,'owner_risk_comment'=>RISK_COMMENT,'database_writes'=>0,'mapping_writes'=>0,'safe_to_write_now'=>false,'no_replay'=>true];
$db=null;$provider=null;$cards=[];$batchMeta=[];$state='failed_before_provider_access';$reason=null;
try{
 require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');
 $ids=array_map(fn($x)=>(int)$x['tv_hotel_id'],$inp['targets']);$hot=[];$samo=[];
 foreach(array_chunk($ids,900)as$chunk){$ph=implode(',',array_fill(0,count($chunk),'?'));$q=$db->prepare("SELECT id,country_id,country_name,is_active FROM catalog_hotels WHERE id IN ($ph)");$q->execute($chunk);foreach($q->fetchAll(PDO::FETCH_ASSOC)?:[]as$h)$hot[(int)$h['id']]=$h;$q=$db->prepare("SELECT local_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IN ($ph)");$q->execute($chunk);foreach($q->fetchAll(PDO::FETCH_COLUMN)?:[]as$idv)$samo[(int)$idv]=true;}
 $db->rollBack();$db=null;$active=[];$preSkip=[];$protected=array_fill_keys(PROTECTED_IDS,true);
 foreach($inp['targets']as$x){$id=(int)$x['tv_hotel_id'];$h=$hot[$id]??null;if(isset($protected[$id])){$preSkip[]=['tv_hotel_id'=>$id,'state'=>'protected_no_acquisition'];continue;}if(!$h||(int)$h['is_active']!==1){$preSkip[]=['tv_hotel_id'=>$id,'state'=>'inactive_or_missing_current'];continue;}$country=trim((string)$h['country_name']);if(in_array($country,['Россия','Абхазия','Russia','Russian Federation','Abkhazia'],true)){$preSkip[]=['tv_hotel_id'=>$id,'state'=>'excluded_market_current'];continue;}$bucket=(string)$x['bucket'];if(isset($samo[$id])){$bucket=$bucket==='neither'?'samo_only':$bucket;if($bucket==='anex_only'){$preSkip[]=['tv_hotel_id'=>$id,'state'=>'became_both_current'];continue;}}$x['country_id']=(int)$h['country_id'];$x['country_name']=$country;$x['current_bucket']=$bucket;$active[]=$x;}
 need($active!==[],'no_active');savej($dir.'/current-preflight.json',$base+['state'=>'current_preflight_complete','active_count'=>count($active),'skipped_count'=>count($preSkip),'skipped'=>$preSkip]);
 $by=[];foreach($active as$x)$by[(int)$x['country_id']][]=$x;$tz=new DateTimeZone('Europe/Moscow');$from=(new DateTimeImmutable('tomorrow',$tz))->format('Y-m-d');$to=(new DateTimeImmutable('tomorrow +20 days',$tz))->format('Y-m-d');$provider=new Provider($root,$dir);$bi=0;
 foreach($by as$country=>$items)foreach(array_chunk($items,30)as$batch){$bi++;$want=array_map(fn($x)=>(int)$x['tv_hotel_id'],$batch);$params=['departureId'=>1,'countryId'=>(int)$country,'dateFrom'=>$from,'dateTo'=>$to,'nightsFrom'=>5,'nightsTo'=>14,'adults'=>2,'currency'=>'RUB','onlyCharter'=>false,'onlyDirect'=>false,'hotelIds'=>$want];$start=$provider->get('search_start','/tours/search',$params);$search=sid($start);need($search!==null,'search_id');$ready=false;$polls=0;for($i=0;$i<POLLS;$i++){sleep(3);$polls++;$st=$provider->get('search_status','/tours/search/'.$search.'/status',['operatorStatus'=>false]);if(complete($st)){$ready=true;break;}}
  if(!$ready){foreach($batch as$x)$cards[]=['tv_hotel_id'=>(int)$x['tv_hotel_id'],'name'=>$x['name'],'bucket'=>$x['current_bucket'],'country_id'=>(int)$country,'state'=>'search_not_ready_no_replay','search_id'=>$search];$batchMeta[]=['batch'=>$bi,'country_id'=>(int)$country,'requested'=>count($batch),'search_id'=>$search,'polls'=>$polls,'state'=>'not_ready'];continue;}
  $result=$provider->get('search_results','/tours/search/'.$search,['limit'=>10000]);$allowed=array_fill_keys($want,true);$found=[];foreach(rows($result)as$h){if(!is_array($h)||!($hid=id($h['id']??null))||!isset($allowed[$hid]))continue;$found[$hid]=$h;}
  foreach($batch as$x){$hid=(int)$x['tv_hotel_id'];$card=['tv_hotel_id'=>$hid,'name'=>$x['name'],'bucket'=>$x['current_bucket'],'country_id'=>(int)$country,'search_id'=>$search,'safe_to_write_now'=>false];if(!isset($found[$hid])){$card['state']='not_returned_current_window';$cards[]=$card;continue;}$card['state']='search_returned';$card['tour_count']=count((array)($found[$hid]['tours']??[]));$cand=candidate($found[$hid],$x['current_bucket']);if($cand===null){$card['detail_state']=$x['current_bucket']==='anex_only'?'not_needed_existing_anex':'no_relevant_common4_tour';$cards[]=$card;continue;}$op=(int)$cand['operator_id'];$tid=(string)$cand['tour_id'];$detail=$provider->get('tour_detail','/tours/'.rawurlencode($tid),['currency'=>'RUB'],true);if(($detail['_http_status']??200)===404){$card['detail_state']='stale_detail_404';$cards[]=$card;continue;}$rh=identity($detail,'hotel');$ro=identity($detail,'operator');$rt=(string)($detail['id']??($detail['tourId']??''));$card['detail_operator_id']=$op;$card['detail_tour_id']=$tid;$card['returned_hotel_id']=$rh;$card['returned_operator_id']=$ro;$card['returned_tour_id']=$rt;if($rh!==$hid||$ro!==$op||$rt!==$tid){$card['detail_state']='identity_mismatch';}else{$card['detail_state']='identity_verified';$card+=op_link($op,$detail);}$cards[]=$card;}
  $batchMeta[]=['batch'=>$bi,'country_id'=>(int)$country,'requested'=>count($batch),'returned'=>count($found),'search_id'=>$search,'polls'=>$polls,'state'=>'completed'];
 }
 $state='completed_read_only';
}catch(Throwable $e){if($db&&$db->inTransaction())$db->rollBack();$reason=$e instanceof RuntimeException?$e->getMessage():get_class($e);$state=$provider&&$provider->used>0?'terminal_failed_no_replay':'failed_before_provider_access';}
$counts=[];$links=[];foreach($cards as$c){$counts[$c['state']]=($counts[$c['state']]??0)+1;if(isset($c['link_state']))$links[$c['link_state']]=($links[$c['link_state']]??0)+1;}
$out=$base+['state'=>$state,'reason'=>$reason,'date_from'=>$from??null,'date_to'=>$to??null,'active_preflight_count'=>isset($active)?count($active):null,'preflight_skipped_count'=>isset($preSkip)?count($preSkip):null,'preflight_skipped'=>$preSkip??[],'batch_count'=>count($batchMeta),'provider_calls'=>$provider?->used??0,'provider_call_counts'=>$provider?->counts??[],'accounting_mode'=>$provider?->mode??null,'known_accounted_before'=>$provider?->accountedBefore??null,'known_accounted_after'=>$provider?->accountedAfter??null,'card_state_counts'=>$counts,'link_state_counts'=>$links,'cards'=>$cards,'batches'=>$batchMeta];
$dig=savej($dir.'/result.json',$out);savej($dir.'/receipt.json',$base+['state'=>$state,'result_sha256'=>$dig,'provider_calls'=>$out['provider_calls'],'accounting_mode'=>$out['accounting_mode'],'known_accounted_after'=>$out['known_accounted_after'],'card_state_counts'=>$counts,'link_state_counts'=>$links]);if($provider)$provider->finish($state,$dig);echo enc(['state'=>$state,'active'=>$out['active_preflight_count'],'skipped'=>$out['preflight_skipped_count'],'batches'=>$out['batch_count'],'calls'=>$out['provider_calls'],'accounting_mode'=>$out['accounting_mode'],'card_states'=>$counts,'links'=>$links,'result_sha256'=>$dig]);exit($state==='completed_read_only'?0:2);
