<?php
declare(strict_types=1);
/** MATCH-only mass CURRENT reconciliation snapshot. READ ONLY; no supplier client or mutation SQL. */
const HMFR_OP='hotel-match-frontier-current-reconcile-1971-20260917-v1';
const HMFR_INPUT='__SEALED_PAIR_MANIFEST_BASE64__';
function hmfr_require(bool $ok,string $why):void{if(!$ok)throw new RuntimeException($why);}
function hmfr_json(array $x):string{return json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";}
function hmfr_write(string $p,array $x):string{$raw=hmfr_json($x);$f=@fopen($p,'x+b');hmfr_require(is_resource($f),'exclusive_output');try{hmfr_require(fwrite($f,$raw)===strlen($raw)&&fflush($f),'output_write');if(function_exists('fsync'))hmfr_require(fsync($f),'output_sync');rewind($f);hmfr_require(stream_get_contents($f)===$raw,'output_readback');}finally{fclose($f);}return hash('sha256',$raw);}
function hmfr_read(string $p,int $max):array{hmfr_require(!is_link($p)&&realpath($p)===$p&&is_file($p),'input_path');$f=fopen($p,'rb');hmfr_require(is_resource($f),'input_open');try{$a=fstat($f);hmfr_require($a['nlink']===1&&$a['size']<=$max,'input_size');$raw=stream_get_contents($f,$max+1);$b=fstat($f);hmfr_require(is_string($raw)&&strlen($raw)===$a['size']&&$a['ino']===$b['ino']&&$a['mtime']===$b['mtime']&&$a['size']===$b['size'],'input_changed');}finally{fclose($f);}$x=json_decode($raw,true,64,JSON_THROW_ON_ERROR);hmfr_require(is_array($x),'input_shape');return$x;}
function hmfr_query(PDO $db,string $sql,array $args=[]):array{$q=$db->prepare($sql);$q->execute(array_values($args));$r=$q->fetchAll(PDO::FETCH_ASSOC);hmfr_require(count($r)<=150000,'query_row_budget');return$r;}
function hmfr_protected($v,string $key='',int $depth=0):bool{if($depth>20)return true;$s=preg_match('/manual|exclude|exclusion|conflict|reject|review|protect/i',$key)===1;if(is_array($v)){if($s&&$v!==[])return true;foreach($v as$k=>$x)if(hmfr_protected($x,(string)$k,$depth+1))return true;return false;}if(!$s)return false;if($v===null)return false;if(is_bool($v))return$v;if(is_numeric($v))return(float)$v!=0;if(is_string($v))return!in_array(strtolower(trim($v)),['','false','none','no','null'],true);return true;}
function hmfr_source(array $e):array{return is_array($e['source']??null)?$e['source']:$e;}
function hmfr_states(array $e):array{$s=hmfr_source($e);$out=[];foreach([$s['stateKey']??null,$s['state_key']??null,$e['stateKey']??null,$e['state_key']??null]as$v)if((is_int($v)||is_string($v))&&preg_match('/^[1-9][0-9]{0,9}$/D',(string)$v))$out[(string)$v]=true;$ids=array_map('strval',array_keys($out));sort($ids,SORT_STRING);return$ids;}
function hmfr_names(array $e):array{$s=hmfr_source($e);$out=[];foreach(['name','lName','hotel_name','hotelName','original_name']as$k){$v=$s[$k]??null;if(is_string($v)&&trim($v)!==''&&strlen($v)<=1024&&!preg_match('/[\x00-\x1f\x7f]/',$v))$out[trim($v)]=true;}$n=array_keys($out);sort($n,SORT_STRING);return$n;}
function hmfr_points($x,array &$out,int $depth=0):void{hmfr_require($depth<=32,'coordinate_depth');if(!is_array($x))return;$a=$x['latitude']??$x['lat']??null;$b=$x['longitude']??$x['lon']??$x['lng']??null;if(is_numeric($a)&&is_numeric($b)&&is_finite((float)$a)&&is_finite((float)$b)&&abs((float)$a)<=90&&abs((float)$b)<=180&&((float)$a!=0||(float)$b!=0))$out[]= [(float)$a,(float)$b];foreach($x as$v)if(is_array($v))hmfr_points($v,$out,$depth+1);}
function hmfr_geo(array $e):array{$s=hmfr_source($e);$keys=['townKey','town_key','town','townId','town_id','townToKey','townToId','regionKey','regionId','parentKey','parentId'];$out=[];foreach($keys as$k){$v=$s[$k]??null;if((is_string($v)||is_int($v))&&strlen((string)$v)<=128&&preg_match('/[\x00-\x1f\x7f]/',(string)$v)!==1)$out[$k]=(string)$v;}ksort($out);return$out;}
function hmfr_manifest(array $m):array{hmfr_require(($m['pair_audit_sha256']??'')==='d9ee55245c3bc442659d373ff280e773603da74c29e7301b0395abcfa457f1b6','pair_audit_pin');hmfr_require(($m['recovery_sha256']??'')==='73a6d537ed852e85bcf6601792a226f6a552ed9e7e690f64245297838ebc929c','recovery_pin');hmfr_require(($m['prior_current_result_sha256']??'')==='cbd3d25c9d1e75ae0871dbeb74f0b97f7b546021a1be2b5b8f4a8b80afe80183','prior_current_pin');hmfr_require(($m['pair_count']??0)===619&&($m['dossier_count']??0)===538,'population');hmfr_require(is_array($m['sources']??null)&&count($m['sources'])===538&&is_array($m['countries']??null)&&count($m['countries'])===8,'manifest_shape');$seen=[];foreach($m['sources']as$r){$id=$r['external_hotel_id']??null;hmfr_require(is_string($id)&&preg_match('/^[1-9][0-9]{0,19}$/D',$id)===1&&!isset($seen[$id]),'source_id');hmfr_require(preg_match('/^[a-f0-9]{64}$/D',(string)($r['evidence_sha256']??''))===1,'source_digest');hmfr_require(is_array($r['state_keys']??null)&&count($r['state_keys'])===1&&preg_match('/^[1-9][0-9]{0,9}$/D',(string)$r['state_keys'][0])===1,'source_state');hmfr_require(is_int($r['country_id'])&&isset($m['countries'][(string)$r['country_id']]),'source_country');$seen[$id]=$r;}return$seen;}
function hmfr_main():void{hmfr_require(PHP_SAPI==='cli'&&getenv('MATCH_OPERATION_ID')===HMFR_OP,'operation_guard');$sha=(string)getenv('MATCH_SOURCE_SHA');hmfr_require(preg_match('/^[a-f0-9]{40}$/D',$sha)===1,'source_guard');$raw=base64_decode(HMFR_INPUT,true);hmfr_require(is_string($raw),'manifest_encoding');$manifest=json_decode($raw,true,64,JSON_THROW_ON_ERROR);$selected=hmfr_manifest($manifest);$manifestSha=hash('sha256',$raw);$dir=(string)getenv('HOME').'/.anytoour-match/operations/'.HMFR_OP;$res=hmfr_read($dir.'/reservation.json',32768);hmfr_require(($res['operation_id']??'')===HMFR_OP&&($res['source_sha']??'')===$sha&&($res['state']??'')==='reserved_before_db_access'&&($res['manifest_sha256']??'')===$manifestSha,'reservation_guard');
 $db=null;$phase='configuration';$out=['operation_id'=>HMFR_OP,'source_sha'=>$sha,'state'=>'failed_no_replay','no_replay'=>true,'pair_count'=>619,'dossier_count'=>538,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'booking_calls'=>0,'lead_calls'=>0,'safe_to_write_now'=>false];ob_start();try{$root=realpath(getcwd());hmfr_require(is_string($root)&&basename($root)==='anytoour.ru','project_guard');$bp=$root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');hmfr_require(realpath($bp)===$bp&&!is_link($bp),'bootstrap_path');require_once$bp;$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$phase='current_read';$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');
  $eng=hmfr_query($db,"SELECT TABLE_NAME,ENGINE FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME IN ('andromeda_hotel_identities','catalog_hotels','hotel_aliases','catalog_countries')");hmfr_require(count($eng)===4,'table_contract');foreach($eng as$t){$t=array_change_key_case($t,CASE_LOWER);hmfr_require(strtoupper((string)$t['engine'])==='INNODB','nontransactional_table');}
  $extra=hmfr_query($db,"SELECT TABLE_NAME FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND (LOWER(TABLE_NAME) LIKE '%hotel%' OR LOWER(TABLE_NAME) LIKE '%identity%') AND LOWER(TABLE_NAME) REGEXP 'manual|exclu|decision|review' AND LOWER(TABLE_NAME) NOT LIKE 'anex_%'");hmfr_require(!$extra,'separate_protection_contract_requires_review');
  $countries=[];foreach(hmfr_query($db,'SELECT id,name FROM catalog_countries WHERE is_active=1 ORDER BY id')as$c)$countries[(string)$c['id']]=$c['name'];foreach($manifest['countries']as$cid=>$name)hmfr_require(($countries[(string)$cid]??null)===$name,'country_context_changed');$cids=array_map('intval',array_keys($manifest['countries']));$marks=implode(',',array_fill(0,count($cids),'?'));
  $hotels=[];foreach(hmfr_query($db,"SELECT id,country_id,country_name,region_id,region_name,subregion_id,subregion_name,name,category,latitude,longitude FROM catalog_hotels WHERE is_active=1 AND country_id IN ($marks) ORDER BY id",$cids)as$h){foreach(['id','country_id','region_id','subregion_id']as$k)$h[$k]=$h[$k]===null?null:(int)$h[$k];$hotels[(string)$h['id']]=$h;}
  $aliases=[];foreach(hmfr_query($db,"SELECT a.hotel_id,a.alias FROM hotel_aliases a JOIN catalog_hotels h ON h.id=a.hotel_id WHERE h.is_active=1 AND h.country_id IN ($marks) ORDER BY a.hotel_id,a.id",$cids)as$r)$aliases[(string)$r['hotel_id']][]=$r['alias'];
  $ids=array_keys($selected);$idMarks=implode(',',array_fill(0,count($ids),'?'));$sources=[];$missing=[];
  foreach(hmfr_query($db,"SELECT external_hotel_id,local_hotel_id,decision_status,evidence_sha256,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id IN ($idMarks) ORDER BY external_hotel_id",$ids)as$r){$id=(string)$r['external_hotel_id'];$e=json_decode((string)$r['evidence_json'],true,64,JSON_THROW_ON_ERROR);hmfr_require(is_array($e),'current_evidence_shape');$p=$selected[$id];$holds=[];$states=hmfr_states($e);if((string)$r['decision_status']!=='pending'||$r['local_hotel_id']!==null)$holds[]='not_current_pending_null';if(!is_string($r['evidence_sha256'])||!hash_equals($p['evidence_sha256'],$r['evidence_sha256']))$holds[]='source_digest_changed';if($states!==array_map('strval',$p['state_keys']))$holds[]='current_state_context_changed';if(hmfr_protected($e))$holds[]='current_protected_evidence';$pts=[];hmfr_points($e,$pts);$sources[$id]=['external_hotel_id'=>$id,'decision_status'=>(string)$r['decision_status'],'local_hotel_id'=>$r['local_hotel_id']===null?null:(int)$r['local_hotel_id'],'evidence_sha256'=>$r['evidence_sha256'],'evidence_bytes_sha256'=>hash('sha256',(string)$r['evidence_json']),'state_keys'=>$states,'names'=>hmfr_names($e),'geo'=>hmfr_geo($e),'points'=>$pts,'holds'=>array_values(array_unique($holds))];}
  foreach($ids as$id)if(!isset($sources[(string)$id]))$missing[]=(string)$id;
  $occupancy=[];$acceptedGeo=[];foreach(hmfr_query($db,"SELECT external_hotel_id,local_hotel_id,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IS NOT NULL ORDER BY external_hotel_id")as$r){$id=(string)$r['external_hotel_id'];$lid=(string)$r['local_hotel_id'];$occupancy[$lid][]=$id;$e=json_decode((string)$r['evidence_json'],true,64,JSON_THROW_ON_ERROR);hmfr_require(is_array($e),'accepted_evidence_shape');$acceptedGeo[]=['external_hotel_id'=>$id,'local_hotel_id'=>(int)$r['local_hotel_id'],'state_keys'=>hmfr_states($e),'geo'=>hmfr_geo($e)];}
  $out+=['manifest_sha256'=>$manifestSha,'pair_audit_sha256'=>$manifest['pair_audit_sha256'],'recovery_sha256'=>$manifest['recovery_sha256'],'prior_current_result_sha256'=>$manifest['prior_current_result_sha256'],'current_sources'=>$sources,'missing_current_ids'=>$missing,'current_local_hotels'=>$hotels,'current_aliases'=>$aliases,'current_occupancy'=>$occupancy,'accepted_geo_rows'=>$acceptedGeo,'current_countries'=>array_intersect_key($countries,$manifest['countries']),'read_at_utc'=>gmdate('c'),'transaction'=>'REPEATABLE READ / READ ONLY'];$db->exec('ROLLBACK');$out['state']='completed_read_only';
 }catch(Throwable $e){if($db instanceof PDO&&$db->inTransaction())$db->rollBack();$out['error_phase']=$phase;$out['error_code']=preg_match('/^[a-z_]{3,100}$/D',$e->getMessage())?$e->getMessage():'sanitized_failure';}while(ob_get_level())ob_end_clean();$digest=hmfr_write($dir.'/result.json',$out);hmfr_write($dir.'/receipt.json',['operation_id'=>HMFR_OP,'source_sha'=>$sha,'state'=>$out['state'],'result_sha256'=>$digest,'readback_verified'=>true,'no_replay'=>true,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0]);echo hmfr_json(['state'=>$out['state'],'result_sha256'=>$digest,'pair_count'=>$out['pair_count'],'dossier_count'=>$out['dossier_count']]);if($out['state']!=='completed_read_only')exit(2);}
if(in_array('--self-test',$argv??[],true)){$n=0;foreach([[['manual'=>true],true],[['source'=>['review'=>['status'=>'hold']]],true],[['conflict'=>false],false],[['excluded'=>0],false],[['name'=>'manual hotel'],false],[['source'=>['pair_exclusion'=>1]],true]]as[$x,$expect]){hmfr_require(hmfr_protected($x)===$expect,'protected_test');$n++;}hmfr_require(hmfr_states(['source'=>['stateKey'=>5],'state_key'=>'5'])===['5'],'state_test');$n++;hmfr_require(hmfr_names(['source'=>['name'=>'B','lName'=>'A']])===['A','B'],'name_test');$n++;$g=hmfr_geo(['source'=>['townKey'=>123,'token'=>'secret']]);hmfr_require($g===['townKey'=>'123'],'geo_allowlist');$n++;$pts=[];hmfr_points(['source'=>['lat'=>1,'lng'=>2,'secret'=>['lat'=>3,'lon'=>4]]],$pts);hmfr_require(count($pts)===2,'point_extract');$n++;$p=tempnam(sys_get_temp_dir(),'hmfr-');unlink($p);$h=hmfr_write($p,['ok'=>true]);hmfr_require($h===hash_file('sha256',$p),'durable_readback');unlink($p);$n++;echo "$n CURRENT reconcile self-tests PASS\n";exit;}
hmfr_main();
