<?php
declare(strict_types=1);
function lm_need(bool $x,string $w):void{if(!$x)throw new RuntimeException($w);}
function lm_text(mixed $v,int $max=512):string{if(!is_scalar($v))return'';$s=trim((string)$v);return function_exists('mb_substr')?mb_substr($s,0,$max,'UTF-8'):substr($s,0,$max);}
function lm_norm(string $v):string{$v=function_exists('mb_strtolower')?mb_strtolower(trim($v),'UTF-8'):strtolower(trim($v));$v=strtr($v,['ё'=>'е','&'=>' ','+'=>' ','_'=>' ','-'=>' ','’'=>"'"]);$v=preg_replace('/[^\p{L}\p{N}]+/u',' ',$v)??$v;return trim(preg_replace('/\s+/u',' ',$v)??$v);}
function lm_id(mixed $v):?string{$s=lm_text($v,64);return preg_match('/^[1-9][0-9]{0,31}$/D',$s)?$s:null;}
function lm_tokens(string $v):array{$g=['hotel'=>1,'hotels'=>1,'otel'=>1,'отель'=>1,'resort'=>1,'spa'=>1,'apart'=>1,'apartment'=>1,'the'=>1];$o=[];foreach(preg_split('/\s+/u',lm_norm($v),-1,PREG_SPLIT_NO_EMPTY)?:[]as$t)if(!isset($g[$t])&&(function_exists('mb_strlen')?mb_strlen($t,'UTF-8'):strlen($t))>=2)$o[$t]=true;$x=array_keys($o);sort($x,SORT_STRING);return$x;}
function lm_variants(string $name):array{$o=[];$add=function(string $s)use(&$o){$n=lm_norm($s);if($n!==''&&lm_tokens($n))$o[$n]=true;};$add($name);if(preg_match('/^(.+?)\s*\((?:EX\.?|FORMERLY|БЫВШ\.?)\s*[^)]*\)/iu',$name,$m))$add($m[1]);if(preg_match_all('/\((?:EX\.?|FORMERLY|БЫВШ\.?)\s*([^)]*)\)/iu',$name,$ms))foreach($ms[1]as$inside)foreach(preg_split('/[;|\/]+/u',(string)$inside)?:[]as$p)$add($p);return array_keys($o);}
function lm_overlap(array $a,array $b):array{$A=array_fill_keys($a,true);$B=array_fill_keys($b,true);$c=count(array_intersect_key($A,$B));$u=count($A+$B);return['common'=>$c,'jaccard'=>$u?$c/$u:0.0,'source_coverage'=>count($A)?$c/count($A):0.0,'target_coverage'=>count($B)?$c/count($B):0.0];}
function lm_geo(array $townLabels,array $target):string{$locals=array_filter([lm_text($target['region_name']??'',160),lm_text($target['subregion_name']??'',160)]);if(!$townLabels||!$locals)return'unknown';foreach($townLabels as$a){$a=lm_norm((string)$a);if($a==='')continue;foreach($locals as$b){$b=lm_norm($b);if($b!==''&&($a===$b||str_contains($a,$b)||str_contains($b,$a)))return'direct_label_match';}}return'unproven';}
function lm_towns(array $rows):array{$o=[];foreach($rows as$r){if(!is_array($r)||!($id=lm_id($r['id']??null)))continue;$l=[];foreach(['name','lName','label','title','region','regionName']as$k){$v=lm_text($r[$k]??'',180);if($v!=='')$l[$v]=true;}$o[$id]=array_keys($l);}return$o;}
function lm_provider(array $hotels,array $towns):array{$o=[];foreach($hotels as$h){if(!is_array($h)||!($id=lm_id($h['id']??null)))continue;$names=[];foreach(['name','lName']as$k){$v=lm_text($h[$k]??'',220);if($v!=='')$names[$v]=true;}if(!$names)continue;$tk=lm_id($h['townKey']??null);$o[$id]=['catalog_hotel_id'=>$id,'names'=>array_keys($names),'town_key'=>$tk,'town_labels'=>$tk?($towns[$tk]??[]):[],'star_key'=>lm_id($h['starKey']??null)];}return$o;}
function lm_candidates(array $target,array $aliases,array $provider):array{$names=[(string)$target['name']];foreach($aliases as$a)$names[]=(string)$a;$vars=[];$tok=[];foreach($names as$n){foreach(lm_variants($n)as$v)$vars[$v]=true;foreach(lm_tokens($n)as$t)$tok[$t]=true;}$freq=[];foreach($provider as$p)foreach($p['names']as$n)foreach(lm_tokens($n)as$t)$freq[$t]=($freq[$t]??0)+1;$rare=null;$rn=PHP_INT_MAX;foreach(array_keys($tok)as$t){$f=$freq[$t]??0;if($f>0&&$f<$rn){$rn=$f;$rare=$t;}}$exact=[];$rank=[];foreach($provider as$id=>$p){$best=['common'=>0,'jaccard'=>0.0,'source_coverage'=>0.0,'target_coverage'=>0.0];$ex=false;foreach($p['names']as$n){foreach(lm_variants($n)as$v)if(isset($vars[$v]))$ex=true;$s=lm_overlap(array_keys($tok),lm_tokens($n));if([$s['common'],$s['jaccard']]>[$best['common'],$best['jaccard']])$best=$s;}$row=$p+['name_score'=>$best,'geo_relation'=>lm_geo($p['town_labels'],$target)];if($ex){$row['retrieval']='exact_variant';$exact[$id]=$row;continue;}if($rare!==null&&in_array($rare,array_unique(array_merge(...array_map('lm_tokens',$p['names']))),true)&&$best['common']>=1&&$best['source_coverage']>=0.34){$row['retrieval']='rare_token_ranked';$rank[$id]=$row;}}$sort=function(&$a){uasort($a,function($x,$y){$gx=$x['geo_relation']==='direct_label_match'?1:0;$gy=$y['geo_relation']==='direct_label_match'?1:0;if($gx!==$gy)return$gy<=>$gx;$sx=$x['name_score']['source_coverage'];$sy=$y['name_score']['source_coverage'];if($sx!==$sy)return$sy<=>$sx;return$y['name_score']['jaccard']<=>$x['name_score']['jaccard'];});};if($exact){$sort($exact);return['mode'=>'exact','candidates'=>array_slice($exact,0,3,true)];}$rank=array_filter($rank,fn($x)=>$x['name_score']['source_coverage']>=0.45||$x['name_score']['jaccard']>=0.45);$sort($rank);return['mode'=>$rank?'rare_ranked':'none','candidates'=>array_slice($rank,0,3,true)];}
function lm_url(mixed $v):?string{$s=lm_text($v,2048);if(!preg_match('~^https?://~i',$s))return null;$p=parse_url($s);if(!is_array($p)||empty($p['host'])||isset($p['user'])||isset($p['pass']))return null;if(isset($p['query'])){parse_str((string)$p['query'],$q);foreach(array_keys($q)as$k)if(preg_match('/token|auth|pass|secret|session|cookie|signature|api[_-]?key/i',(string)$k))return null;}return$s;}
function lm_urls(mixed $v):array{$o=[];$walk=function($x,$d=0)use(&$walk,&$o){if($d>8)return;if(is_array($x)){foreach($x as$z)$walk($z,$d+1);return;}if(!is_string($x))return;$u=lm_url($x);if($u!==null)$o[$u]=true;};$walk($v);$x=array_keys($o);sort($x,SORT_STRING);return array_slice($x,0,100);}
function lm_fact(array $r,string $operatorId):?array{$sid=lm_id($r['hotelKey']??null);$op=lm_id($r['operatorKey']??($r['original']['operatorKey']??null));if(!$sid||$op!==$operatorId)return null;$orig=is_array($r['original']??null)?$r['original']:[];return['samo_hotel_id'=>$sid,'operator_id'=>$op,'native_operator_hotel_id'=>lm_id($orig['hotelKey']??null),'is_operator_hotel_key'=>isset($orig['isOperatorHotelKey'])&&is_scalar($orig['isOperatorHotelKey'])?(string)$orig['isOperatorHotelKey']:null,'urls'=>lm_urls($r)];}
function lm_write(string $p,string $raw,bool $exclusive=true):string{$f=@fopen($p,$exclusive?'x+b':'c+b');lm_need(is_resource($f),'write_open');try{if(!$exclusive)fseek($f,0,SEEK_END);lm_need(fwrite($f,$raw)===strlen($raw)&&fflush($f),'write');if(function_exists('fsync'))lm_need(fsync($f),'sync');}finally{fclose($f);}return hash('sha256',$raw);}
function lm_json_file(string $p,array $v):string{return lm_write($p,json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",true);}
function lm_raw(string $dir,string $name,array $v,array &$m):void{$file='raw-'.$name.'.json';$raw=json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n";$sha=lm_write($dir.'/'.$file,$raw,true);$m[]=['file'=>$file,'sha256'=>$sha,'bytes'=>strlen($raw)];}
function lm_rows(PDO $db,string $sql,array $p=[]):array{$s=$db->prepare($sql);$s->execute(array_values($p));return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}
function lm_dict(array $rows,array $aliases):int{$want=array_fill_keys(array_map('lm_norm',$aliases),true);$hits=[];foreach($rows as$r){if(!is_array($r)||!($id=lm_id($r['id']??null)))continue;$n=lm_norm(lm_text($r['name']??($r['lName']??''),200));if(isset($want[$n]))$hits[$id]=true;}lm_need(count($hits)===1,'dict_'.count($hits));return(int)array_key_first($hits);}
