<?php
/** MATCH #1971 read-only reverse target occupancy for sealed native operatorLink evidence. */
declare(strict_types=1);
const HM_OCC_OP='hotel-match-tv-operatorlink-target-occupancy-1971-20260915-v1';
function hmj(array $v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
function hmw(string $p,array $v):string{$r=hmj($v)."\n";$f=fopen($p,'x');if(!$f)throw new RuntimeException('create_failed');fwrite($f,$r);fflush($f);fclose($f);if((string)file_get_contents($p)!==$r)throw new RuntimeException('readback_failed');return hash('sha256',$r);}
function hmmany(PDO $db,string $q,array $p):array{$s=$db->prepare($q);$s->execute($p);return $s->fetchAll(PDO::FETCH_ASSOC);}
$sha=(string)getenv('MATCH_SOURCE_SHA');$parent=(string)getenv('PARENT_OPERATION_ID');$parentHash=(string)getenv('PARENT_RESULT_SHA256');
if(!preg_match('/^[0-9a-f]{40}$/',$sha)||!preg_match('/^[0-9a-f]{64}$/',$parentHash))throw new RuntimeException('guard');
$root=(string)realpath(getcwd());if($root===''||basename($root)!=='anytoour.ru')throw new RuntimeException('root_guard');
$base=rtrim((string)getenv('HOME'),'/').'/.anytoour-match/operations';$pr=$base.'/'.$parent.'/result.json';$pc=$base.'/'.$parent.'/receipt.json';
if(!is_file($pr)||!is_file($pc))throw new RuntimeException('parent_missing');$raw=(string)file_get_contents($pr);$src=json_decode($raw,true,512,JSON_THROW_ON_ERROR);$rec=json_decode((string)file_get_contents($pc),true,512,JSON_THROW_ON_ERROR);
if(hash('sha256',$raw)!==$parentHash||($rec['result_sha256']??'')!==$parentHash||($rec['readback_verified']??false)!==true||($src['examined']??0)!==9||($src['database_writes']??-1)!==0)throw new RuntimeException('parent_guard');
$dir=$base.'/'.HM_OCC_OP;if(file_exists($dir)||!mkdir($dir,0700))throw new RuntimeException('operation_exists');hmw($dir.'/reservation.json',['operation_id'=>HM_OCC_OP,'source_sha'=>$sha,'state'=>'reserved_before_db_access','parent_operation_id'=>$parent,'parent_result_sha256'=>$parentHash,'supplier_calls'=>0,'tourvisor_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true]);
$dbp=is_file($root.'/data/db-v1.php')?$root.'/data/db-v1.php':$root.'/v2/data/db-v1.php';require_once $dbp;$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');$rows=[];
try{foreach($src['rows'] as $r){$aid=(int)$r['anex_hotel_id'];$target=(int)$r['tourvisor_local_id'];$maps=hmmany($db,'SELECT * FROM anex_hotel_search_mappings WHERE catalog_hotel_id=? ORDER BY anex_hotel_id',[$target]);$occupants=[];foreach($maps as $m){$x=(int)($m['anex_hotel_id']??0);if($x>0)$occupants[]=$x;}$occupants=array_values(array_unique($occupants));$rows[]=['anex_hotel_id'=>$aid,'tourvisor_local_id'=>$target,'target_name'=>(string)($r['target_name']??''),'source_name'=>(string)($r['source_name']??''),'existing_same_target'=>(bool)($r['existing_same_target']??false),'reverse_anex_occupants'=>$occupants,'occupied_by_other'=>count(array_diff($occupants,[$aid]))>0,'manual_protected'=>(bool)($r['manual_protected']??false),'pair_excluded'=>(bool)($r['pair_excluded']??false),'source_country_id'=>$r['source_country_id']??null,'target_country_id'=>$r['target_country_id']??null,'coordinate_distance_km'=>$r['coordinate_distance_km']??null,'live_search_count'=>(int)($r['live_search_count']??0)];}$db->exec('ROLLBACK');}catch(Throwable $e){if($db->inTransaction())$db->exec('ROLLBACK');throw$e;}
$res=['operation_id'=>HM_OCC_OP,'source_sha'=>$sha,'status'=>'completed_read_only','parent_operation_id'=>$parent,'parent_result_sha256'=>$parentHash,'examined'=>count($rows),'rows'=>$rows,'supplier_calls'=>0,'tourvisor_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true];$rh=hmw($dir.'/result.json',$res);hmw($dir.'/receipt.json',['operation_id'=>HM_OCC_OP,'source_sha'=>$sha,'state'=>'completed_read_only','result_sha256'=>$rh,'readback_verified'=>hash('sha256',(string)file_get_contents($dir.'/result.json'))===$rh,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true]);echo hmj(['examined'=>count($rows)])."\n";
