<?php
declare(strict_types=1);
const L80_OP='hotel-match-live80-direct-accept-1971-20260919-v2',L80_CURRENT='c14ef2ad9650c85ccf3f98749e2bd4ddaa3c27532034d298c1384f1a22c16ddd',L80_LIVE='05ff5be9057a1485f07ee0f3a0ac12e2e8f74b21a81ed2f3d5556ba61e84bd47';\nrequire_once __DIR__.'/hotel_match_live80_direct_accept_helpers_v2.php';
if(in_array('--self-test',$argv??[],true)){l80_need(l80_star(['starLName'=>'4*'])===4,'star');echo"LIVE80_ACCEPT_SELFTEST_OK\n";exit(0);}
$dir=(string)getenv('MATCH_OPERATION_DIR');$root=realpath((string)getenv('ANYTOUR_ROOT'));$cp=realpath((string)getenv('MATCH_CURRENT_PATH'));$lp=realpath((string)getenv('MATCH_LIVE_PATH'));$cats=realpath((string)getenv('MATCH_CATALOG_DIR'));$sha=(string)getenv('MATCH_SOURCE_SHA');
l80_need(PHP_SAPI==='cli'&&is_dir($dir)&&basename($dir)===L80_OP&&is_string($root)&&is_string($cp)&&hash_file('sha256',$cp)===L80_CURRENT&&is_string($lp)&&hash_file('sha256',$lp)===L80_LIVE&&is_string($cats)&&preg_match('/^[a-f0-9]{40}$/D',$sha),'runtime');
$res=json_decode((string)file_get_contents($dir.'/reservation.json'),true,32,JSON_THROW_ON_ERROR);l80_need(($res['operation']??'')===L80_OP&&($res['source_sha']??'')===$sha,'reservation');
require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');require_once $dir.'/payload/andromeda-hotel-resolver.php';require_once $dir.'/payload/anex-search-mapping-registry.php';
$current=json_decode((string)file_get_contents($cp),true,128,JSON_THROW_ON_ERROR);$live=json_decode((string)file_get_contents($lp),true,128,JSON_THROW_ON_ERROR);l80_need(($current['safe_candidate_count']??0)===80,'safe80');
$safe=[];foreach((array)$current['rows']as$r)if(($r['state']??'')==='safe_candidate')$safe[(string)$r['samo_hotel_id']]=$r;l80_need(count($safe)===80,'safe_rows');
$liveBy=[];foreach((array)$live['dossiers']as$d)if(($d['state']??'')==='direct_native_bridge'&&count($d['direct_bridges']??[])===1)$liveBy[(string)$d['direct_bridges'][0]['samo_hotel_id']]=$d;l80_need(count($liveBy)===95,'live95');$catalog=l80_catalogs($cats,$safe);l80_need(count($catalog)===80,'catalog80');
$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$committed=false;$attempted=false;$writes=0;$base=['operation'=>L80_OP,'source_sha'=>$sha,'provider_calls'=>0,'no_replay'=>true];
try{
 $db->exec('SET SESSION innodb_lock_wait_timeout=10');$db->exec('SET TRANSACTION ISOLATION LEVEL SERIALIZABLE');$db->beginTransaction();
 $all=l80_rows($db,'SELECT * FROM andromeda_hotel_identities ORDER BY supplier_namespace,external_hotel_id LIMIT 50001 FOR UPDATE');l80_need(count($all)<50001,'identity_cap');$idx=[];$before=[];foreach($all as$r){$k=$r['supplier_namespace'].':'.$r['external_hotel_id'];$idx[$k]=$r;$before[$k]=l80_hash($r);}
 $targets=array_values(array_map(fn($r)=>(int)$r['tv_hotel_id'],$safe));$natives=array_values(array_map(fn($r)=>(string)$r['native_anex_id'],$safe));$tp=implode(',',array_fill(0,count($targets),'?'));$np=implode(',',array_fill(0,count($natives),'?'));
 $hot=l80_rows($db,"SELECT id,name,country_name,region_name,subregion_name,category,is_active FROM catalog_hotels WHERE id IN ($tp) FOR UPDATE",$targets);$hotBy=[];foreach($hot as$h)$hotBy[(int)$h['id']]=$h;
 $maps=l80_rows($db,"SELECT * FROM anex_hotel_search_mappings WHERE anex_hotel_id IN ($np) OR catalog_hotel_id IN ($tp) FOR UPDATE",array_merge($natives,$targets));$dec=l80_rows($db,"SELECT * FROM anex_hotel_decisions WHERE anex_hotel_id IN ($np) OR catalog_hotel_id IN ($tp) FOR UPDATE",array_merge($natives,$targets));$exc=l80_rows($db,"SELECT * FROM anex_review_pair_exclusions WHERE anex_hotel_id IN ($np) OR catalog_hotel_id IN ($tp) FOR UPDATE",array_merge($natives,$targets));
 $mapBy=[];foreach($maps as$m)if((int)($m['enabled']??1)===1)$mapBy[(string)$m['anex_hotel_id']][]=$m;$decP=[];foreach($dec as$x)$decP[(string)$x['anex_hotel_id'].'|'.(int)$x['catalog_hotel_id']]=true;$excP=[];foreach($exc as$x)$excP[(string)$x['anex_hotel_id'].'|'.(int)$x['catalog_hotel_id']]=true;$occ=[];foreach($all as$r)if($r['supplier_namespace']==='andromeda_catalog'&&$r['decision_status']==='accepted'&&$r['local_hotel_id']!==null)$occ[(int)$r['local_hotel_id']][]=$r;
 $plan=[];$skipped=[];foreach($safe as$sid=>$review){$tv=(int)$review['tv_hotel_id'];$native=(string)$review['native_anex_id'];$cur=$idx['andromeda_catalog:'.$sid]??null;$why=[];$rc=$review['current_source'];
   if($rc===null){if($cur!==null)$why[]='source_appeared';}elseif($cur===null||$cur['decision_status']!=='pending'||$cur['local_hotel_id']!==null||$cur['evidence_sha256']!==$rc['evidence_sha256']||$cur['catalog_sha256']!==$rc['catalog_sha256'])$why[]='pending_drift';
   $t=$hotBy[$tv]??null;if(!$t||(int)$t['is_active']!==1||(string)$t['country_name']!==$review['country'])$why[]='target_drift';elseif((int)$t['category']!==(int)$review['target']['category'])$why[]='category_drift';
   $cf=$catalog[$sid];$ss=l80_star($cf['hotel']);if($cf['country']!==$review['country'])$why[]='catalog_country';if($ss!==null&&$t&&$ss!==(int)$t['category'])$why[]='category_mismatch';
   $mm=$mapBy[$native]??[];$exact=array_values(array_filter($mm,fn($x)=>(int)$x['catalog_hotel_id']===$tv));if(count($mm)!==1||count($exact)!==1)$why[]='anex_mapping_drift';$pair=$native.'|'.$tv;if(isset($decP[$pair]))$why[]='anex_decision';if(isset($excP[$pair]))$why[]='anex_exclusion';
   if(array_filter($occ[$tv]??[],fn($x)=>(string)$x['external_hotel_id']!==$sid))$why[]='target_occupied';
   if($why){$skipped[]=['samo_hotel_id'=>$sid,'tv_hotel_id'=>$tv,'reasons'=>$why];continue;}
   $liveRow=$liveBy[$sid];$proof=$liveRow['direct_bridges'][0];$mapping=$exact[0];$e=['operation_id'=>L80_OP,'rule'=>'live_anex_mapping_plus_samo_price_native_bridge','inputs'=>['current'=>L80_CURRENT,'live'=>L80_LIVE],'samo_hotel_id'=>$sid,'tv_hotel_id'=>$tv,'native_anex_id'=>$native,'live_context'=>$liveRow['context'],'provider_fact'=>$proof,'source_catalog'=>['sha256'=>$cf['hash'],'name'=>$cf['hotel']['name']??($cf['hotel']['lName']??null),'town'=>$cf['hotel']['town']??null,'star'=>$ss,'country'=>$cf['country']],'target'=>['name'=>$t['name'],'country_name'=>$t['country_name'],'region_name'=>$t['region_name'],'subregion_name'=>$t['subregion_name'],'category'=>(int)$t['category']],'anex_mapping_sha256'=>l80_hash($mapping),'prior_source'=>$cur===null?null:['catalog_sha256'=>$cur['catalog_sha256'],'evidence_sha256'=>$cur['evidence_sha256']]];$ej=l80_json($e);$plan[$sid]=['mode'=>$cur===null?'insert':'update','tv'=>$tv,'native'=>$native,'catalog'=>$cf['hash'],'eh'=>hash('sha256',$ej),'ej'=>$ej,'prior'=>$cur];}
 l80_need($plan!==[],'no_safe');l80_write($dir.'/capture.json',$base+['input_safe'=>80,'current_safe'=>count($plan),'skipped'=>$skipped,'identity_hashes'=>$before]);l80_write($dir.'/plan.json',$base+['writes'=>array_map(fn($x)=>['mode'=>$x['mode'],'tv'=>$x['tv'],'native'=>$x['native'],'catalog'=>$x['catalog'],'evidence_sha256'=>$x['eh']],$plan),'skipped'=>$skipped]);
 foreach($plan as$sid=>$p){if($p['mode']==='insert'){$s=$db->prepare("INSERT INTO andromeda_hotel_identities(supplier_namespace,external_hotel_id,local_hotel_id,decision_status,catalog_sha256,evidence_sha256,evidence_json) VALUES('andromeda_catalog',?,?,'accepted',?,?,?)");$s->execute([$sid,$p['tv'],$p['catalog'],$p['eh'],$p['ej']]);}else{$q=$p['prior'];$s=$db->prepare("UPDATE andromeda_hotel_identities SET local_hotel_id=?,decision_status='accepted',catalog_sha256=?,evidence_sha256=?,evidence_json=? WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=? AND decision_status='pending' AND local_hotel_id IS NULL AND catalog_sha256=? AND evidence_sha256=? AND evidence_json=?");$s->execute([$p['tv'],$p['catalog'],$p['eh'],$p['ej'],$sid,$q['catalog_sha256'],$q['evidence_sha256'],$q['evidence_json']]);}l80_need($s->rowCount()===1,'write_count');$writes++;}
 $after=l80_rows($db,'SELECT * FROM andromeda_hotel_identities ORDER BY supplier_namespace,external_hotel_id LIMIT 50001');$other=[];foreach($after as$r){$k=$r['supplier_namespace'].':'.$r['external_hotel_id'];if(!isset($plan[(string)$r['external_hotel_id']])||$r['supplier_namespace']!=='andromeda_catalog')$other[$k]=l80_hash($r);}foreach($plan as$sid=>$p)unset($before['andromeda_catalog:'.$sid]);l80_need($other===$before,'other_rows_changed');
 l80_write($dir.'/pre-commit.json',$base+['writes_uncommitted'=>$writes,'skipped'=>$skipped,'prior_identities_preserved'=>count($before)]);$attempted=true;$db->commit();$committed=true;
 $db->exec('START TRANSACTION READ ONLY');$rr=l80_rows($db,"SELECT i.*,h.id AS existing_catalog_hotel_id FROM andromeda_hotel_identities i LEFT JOIN catalog_hotels h ON h.id=i.local_hotel_id WHERE i.decision_status IN ('accepted','rejected') ORDER BY i.supplier_namespace,i.external_hotel_id LIMIT 50001");$projection=[];$written=[];foreach($rr as$r){$projection[]=['supplier_namespace'=>$r['supplier_namespace'],'external_hotel_id'=>$r['external_hotel_id'],'decision_status'=>$r['decision_status'],'catalog_hotel_id'=>$r['local_hotel_id'],'existing_catalog_hotel_id'=>$r['existing_catalog_hotel_id']];if($r['supplier_namespace']==='andromeda_catalog'&&isset($plan[(string)$r['external_hotel_id']]))$written[(string)$r['external_hotel_id']]=$r;}l80_need(count($written)===$writes,'readback_count');
 $resolver=AnyTourAndromedaHotelResolver::fromRows($projection,l80_hash($projection));$anex=AnyTourAnexSearchMappingRegistry::fromPdo($db);foreach($plan as$sid=>$p){$w=$written[$sid];l80_need($w['decision_status']==='accepted'&&(int)$w['local_hotel_id']===$p['tv']&&$w['catalog_sha256']===$p['catalog']&&$w['evidence_sha256']===$p['eh']&&hash('sha256',$w['evidence_json'])===$p['eh'],'row_readback');$page=$resolver->apply(['provider'=>'andromeda','selection_enabled'=>false,'offers'=>[['provider'=>'andromeda','selection_enabled'=>false,'local_hotel_id'=>null,'supplier_namespace'=>'andromeda_catalog','external_hotel_id'=>$sid]]]);l80_need($page['offers'][0]['local_hotel_id']===$p['tv'],'resolver');l80_need($anex->resolve('anex_online',$p['native'],'preview')===$p['tv'],'anex_resolver');}$db->rollBack();
 $out=$base+['state'=>'committed_verified','committed_at_utc'=>gmdate('c'),'database_writes'=>$writes,'mapping_writes'=>$writes,'accepted_delta'=>$writes,'unique_samo_local_delta'=>$writes,'triple_delta'=>$writes,'input_safe'=>80,'skipped_count'=>count($skipped),'skipped'=>$skipped,'written_count'=>$writes,'written'=>array_map(fn($x)=>['tv_hotel_id'=>$x['tv'],'native_anex_id'=>$x['native'],'catalog_sha256'=>$x['catalog'],'evidence_sha256'=>$x['eh']],$plan),'prior_identities_preserved'=>count($before),'readback_verified'=>true];
}catch(Throwable $e){if($db instanceof PDO&&$db->inTransaction())$db->rollBack();$out=$base+['state'=>$committed?'committed_unverified':($attempted?'commit_outcome_unknown':'rolled_back_or_prewrite_failed'),'reason'=>preg_replace('/[^A-Za-z0-9_.:-]/','_',substr($e->getMessage(),0,140)),'database_writes'=>$committed?$writes:($attempted?null:0),'mapping_writes'=>$committed?$writes:($attempted?null:0),'writes_attempted'=>$writes,'readback_verified'=>false];}
$rh=l80_write($dir.'/result.json',$out);l80_write($dir.'/receipt.json',$base+['state'=>$out['state'],'result_sha256'=>$rh,'mapping_writes'=>$out['mapping_writes'],'database_writes'=>$out['database_writes'],'readback_verified'=>$out['readback_verified']]);echo l80_json(['state'=>$out['state'],'written_count'=>$out['written_count']??null,'skipped_count'=>$out['skipped_count']??null,'result_sha256'=>$rh,'reason'=>$out['reason']??null])."\n";exit(($out['state']??'')==='committed_verified'?0:2);
