<?php
declare(strict_types=1);
require_once __DIR__.'/hotel_match_retained_mass47_v94.php';
const M113_OP='hotel-match-anexonly-tail-samo-write-1971-20260928-v113';
const M113_ACQ_OP='hotel-match-anexonly-tail-acquire-1971-20260928-v112';
const M113_ACQ_SHA='ecbba8c5c9dc03f9d4729aabefd0afa1dbfdc67828a66ff429ccb452aab678fd';
const M113_PLAN_OP='hotel-match-anexonly-tail-plan-1971-20260928-v111';
const M113_PLAN_SHA='930350de662a0dccf872f7d6dc7185f014f22d9e48a14816b108cee0153c0696';
const M113_NATIVE_OP='hotel-match-live30-retained-native-union-1971-20260927-v77';
const M113_NATIVE_SHA='d40fbe2e0240a5df194ac838376a3425a8f4e80f2426a757560fe369011107f7';
function m113_need(bool$b,string$m):void{if(!$b)throw new RuntimeException($m);}
function m113_prepare(string$ops):array{
 $acq=w84_read($ops.'/'.M113_ACQ_OP.'/result.json',M113_ACQ_SHA,33554432);$plan=w84_read($ops.'/'.M113_PLAN_OP.'/result.json',M113_PLAN_SHA,33554432);$v=w84_read($ops.'/'.M113_NATIVE_OP.'/result.json',M113_NATIVE_SHA,67108864);
 m113_need(($acq['state']??'')==='completed_read_only'&&($acq['provider_calls']??0)>0&&($acq['database_writes']??-1)===0&&($plan['state']??'')==='completed_read_only_anexonly200_plan'&&($v['state']??'')==='completed_retained_native_scan','inputs');
 $names=[];foreach($plan['rows']as$r)$names[(int)$r['tv_hotel_id']]=$r['hotel_name'];$nidx=[];foreach($v['native_facts']as$f){$ns=(string)$f['supplier_namespace'];if(!in_array($ns,['operator_315','operator_342'],true))continue;$n=(string)$f['native_id'];$cat=(string)$f['catalog_id'];$nidx[$ns][$n][$cat]=$f;}
 $prior=[];foreach($v['current_identities']as$r)if($r['supplier_namespace']==='andromeda_catalog')$prior[(string)$r['external_hotel_id']]=$r;$group=[];$held=[];
 foreach($acq['edges']as$i=>$e){if(($e['link_state']??'')!=='captured_single_native'||count($e['positive_native_candidates']??[])!==1)continue;$op=(int)$e['operator_id'];$ns=$op===25?'operator_315':($op===43?'operator_342':'');if($ns==='')continue;$n=(string)$e['positive_native_candidates'][0];$cats=array_keys($nidx[$ns][$n]??[]);if(count($cats)!==1)continue;$cat=(string)$cats[0];$id=(int)$e['tv_hotel_id'];$why=w84_edge_reasons($e);if($why){$held[]=['local_hotel_id'=>$id,'catalog_id'=>$cat,'reasons'=>$why];continue;}
  try{$raw=w84_raw($ops,$nidx[$ns][$n][$cat],$cat,$ns,$n);}catch(Throwable){$held[]=['local_hotel_id'=>$id,'catalog_id'=>$cat,'reasons'=>['raw_samo_proof_missing']];continue;}
  $e['source_operation']=M113_ACQ_OP;$e['source_result_sha256']=M113_ACQ_SHA;$e['source_json_pointer']='/edges/'.$i;$e['source_edge_sha256']=w76_hash($acq['edges'][$i]);$k=$id.'|'.$cat;
  $group[$k]['id']=$id;$group[$k]['catalog_id']=$cat;$group[$k]['expected_name']=$names[$id]??null;$group[$k]['prior_scan']=$prior[$cat]??null;$group[$k]['prepare_holds']=[];$group[$k]['operator_facts'][$ns.'|'.$n]=['ns'=>$ns,'native'=>$n];$group[$k]['proofs'][]=['namespace'=>$ns,'native_id'=>$n,'tv'=>['kind'=>'fresh_tv_newcontext','row'=>$e],'samo'=>$raw,'samo_catalog_id'=>$cat];
 }
 $cand=[];foreach($group as$g){$g['operator_facts']=array_values($g['operator_facts']);if(!$g['prior_scan'])$g['prepare_holds'][]='canonical_source_not_pinned';$cand[]=$g;}m113_need(count($cand)+count($held)>0&&count($cand)<=20,'scope');
 return['captured_edge_count'=>count($cand),'candidates'=>$cand,'held'=>$held];
}
function m113_write(PDO$db,array$p,array$cohort,string$head,string$dir):array{
 m113_need(!$db->inTransaction()&&($cohort['complete']??false)===true&&count($p['candidates'])<=20,'writer_scope');$attempt=false;$committed=false;$sql=false;$rolled=false;$planned=[];$held=$p['held'];$already=[];$beforeC=null;$beforeS=null;
 try{
  foreach(['andromeda_hotel_identities','catalog_hotels','tour_operator_identity_observations','anex_hotel_decisions','anex_review_pair_exclusions']as$t){$x=w76_q($db,'SELECT ENGINE FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?',[$t]);m113_need(count($x)===1&&strtoupper($x[0]['ENGINE'])==='INNODB','nontransactional');}
  $db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET SESSION innodb_lock_wait_timeout=20');$db->exec('SET TRANSACTION ISOLATION LEVEL SERIALIZABLE');m113_need($db->beginTransaction(),'begin');
  $all=w76_q($db,'SELECT * FROM andromeda_hotel_identities ORDER BY supplier_namespace,external_hotel_id LIMIT 50001 FOR UPDATE');$before=w76_index($all);$c=['sources'=>[],'targets'=>[],'operators'=>[],'hotels'=>[],'live'=>[],'manual'=>[],'exclusions'=>[]];
  foreach($all as$r){$ns=$r['supplier_namespace'];$n=(string)$r['external_hotel_id'];if($ns==='andromeda_catalog'){$c['sources'][$n][]=$r;if($r['local_hotel_id']!==null)$c['targets'][(int)$r['local_hotel_id']][]=$r;}else$c['operators'][$ns][$n][]=$r;}
  $ids=array_values(array_unique(array_column($p['candidates'],'id')));if($ids){$ph=implode(',',array_fill(0,count($ids),'?'));foreach(w76_q($db,"SELECT id,name,country_id,country_name,region_name,subregion_name,category,is_active,latitude,longitude FROM catalog_hotels WHERE id IN ($ph) ORDER BY id FOR UPDATE",$ids)as$r)$c['hotels'][(int)$r['id']]=$r;foreach(w76_q($db,"SELECT hotel_id FROM tour_operator_identity_observations WHERE hotel_id IN ($ph) AND last_seen_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 30 DAY) ORDER BY hotel_id FOR UPDATE",$ids)as$r)$c['live'][(int)$r['hotel_id']]=true;foreach(w76_q($db,"SELECT catalog_hotel_id FROM anex_hotel_decisions WHERE catalog_hotel_id IN ($ph) FOR UPDATE",$ids)as$r)$c['manual'][(int)$r['catalog_hotel_id']]=true;foreach(w76_q($db,"SELECT catalog_hotel_id FROM anex_review_pair_exclusions WHERE catalog_hotel_id IN ($ph) FOR UPDATE",$ids)as$r)$c['exclusions'][(int)$r['catalog_hotel_id']]=true;}
  $beforeC=w76_census($db);$beforeS=w84_samo_census($all,$cohort);
  foreach($p['candidates']as$e){$d=m94_classify($e,$c,$cohort);$item=['local_hotel_id'=>$e['id'],'catalog_id'=>$e['catalog_id']]+$d;if($d['status']==='hold'){$held[]=$item;continue;}if($d['status']==='already'){$already[]=$item;continue;}$old=$c['sources'][$e['catalog_id']][0];$history=json_decode($old['evidence_json'],true);$ev=['operation_id'=>M113_OP,'rule'=>'one_exact_same_operator_raw_evidence','source_sha'=>$head,'acquisition_result_sha256'=>M113_ACQ_SHA,'native_result_sha256'=>M113_NATIVE_SHA,'source'=>$history['source'],'target'=>$c['hotels'][$e['id']],'proofs'=>$e['proofs'],'prior_evidence_json'=>$old['evidence_json'],'prior_evidence_sha256'=>$old['evidence_sha256'],'catalog_sha256_preserved'=>$old['catalog_sha256'],'required_exact_operators'=>1,'provider_http_calls'=>0];$raw=w76_json($ev);$key='andromeda_catalog|'.$e['catalog_id'];m113_need(!isset($planned[$key]),'duplicate_plan');$planned[$key]=['id'=>$e['id'],'cat'=>$e['catalog_id'],'name'=>$c['hotels'][$e['id']]['name'],'old'=>$old,'new_json'=>$raw,'new_sha'=>hash('sha256',$raw),'proof_count'=>count($e['proofs'])];}
  w76_save($dir.'/write-plan.json',['operation'=>M113_OP,'source_sha'=>$head,'rows'=>$planned,'held'=>$held,'already'=>$already,'coverage_before'=>$beforeC,'samo_before'=>$beforeS]);
  if(!$planned){$db->rollBack();return['state'=>'completed_no_new_writes','database_writes'=>0,'mapping_writes'=>0,'primary_samo_writes'=>0,'held'=>$held,'already'=>$already,'readback_verified'=>true,'coverage_before'=>$beforeC,'coverage_after'=>$beforeC,'samo_before'=>$beforeS,'samo_after'=>$beforeS];}
  $st=$db->prepare("UPDATE andromeda_hotel_identities SET local_hotel_id=?,decision_status='accepted',evidence_sha256=?,evidence_json=? WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=? AND decision_status='pending' AND local_hotel_id IS NULL AND catalog_sha256=? AND evidence_sha256=?");foreach($planned as$x){$sql=true;m113_need($st->execute([$x['id'],$x['new_sha'],$x['new_json'],$x['cat'],$x['old']['catalog_sha256'],$x['old']['evidence_sha256']])&&$st->rowCount()===1,'conditional_update');}
  w76_verify($before,$planned,w76_q($db,'SELECT * FROM andromeda_hotel_identities ORDER BY supplier_namespace,external_hotel_id LIMIT 50001'));w76_save($dir.'/commit-attempt.json',['operation'=>M113_OP,'state'=>'commit_attempt_no_replay','planned_writes'=>count($planned)]);$attempt=true;m113_need($db->commit(),'commit');$committed=true;
  $db->exec('START TRANSACTION READ ONLY');$after=w76_q($db,'SELECT * FROM andromeda_hotel_identities ORDER BY supplier_namespace,external_hotel_id LIMIT 50001');$rows=w76_verify($before,$planned,$after);$afterC=w76_census($db);$afterS=w84_samo_census($after,$cohort);$db->rollBack();return['state'=>'committed_readback_verified','commit_attempted'=>true,'commit_completed'=>true,'database_writes'=>count($planned),'mapping_writes'=>count($planned),'primary_samo_writes'=>count($planned),'rows'=>$rows,'held'=>$held,'already'=>$already,'readback_verified'=>true,'coverage_before'=>$beforeC,'coverage_after'=>$afterC,'samo_before'=>$beforeS,'samo_after'=>$afterS];
 }catch(Throwable$x){if($db->inTransaction())try{$rolled=$db->rollBack();}catch(Throwable){}$n=$committed?count($planned):(($attempt||($sql&&!$rolled))?null:0);return['state'=>$committed?'committed_readback_unconfirmed':($attempt?'commit_outcome_unknown_no_replay':($rolled?'rolled_back_no_writes':'failed_before_writer')),'reason'=>preg_match('/^[a-z_]+$/D',$x->getMessage())?$x->getMessage():'writer_failed','database_writes'=>$n,'mapping_writes'=>$n,'readback_verified'=>false,'held'=>$held,'already'=>$already,'coverage_before'=>$beforeC,'samo_before'=>$beforeS];}
}
function m113_main(array$a):int{
 m113_need(($a[1]??'')==='--execute','disabled');$root=(string)getenv('ANYTOUR_ROOT');$dir=(string)getenv('MATCH_OPERATION_DIR');$head=(string)getenv('MATCH_SOURCE_SHA');m113_need(is_dir($root)&&basename($root)==='anytoour.ru'&&is_dir($dir)&&basename($dir)===M113_OP&&preg_match('/^[a-f0-9]{40}$/D',$head),'scope');
 $rv=json_decode((string)file_get_contents($dir.'/reservation.json'),true,32,JSON_THROW_ON_ERROR);m113_need(($rv['operation']??'')===M113_OP&&($rv['maximum_writes']??0)===20&&($rv['provider_http_calls']??-1)===0,'reservation');foreach(['result.json','receipt.json','commit-attempt.json']as$f)m113_need(!file_exists($dir.'/'.$f),'no_replay');
 try{$p=m113_prepare(dirname($dir));$co=w84_live_sources($root);require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$out=m113_write(v2_data_db(),$p,$co,$head,$dir);}catch(Throwable$x){$out=['state'=>'failed_before_writer','reason'=>preg_match('/^[a-z_]+$/D',$x->getMessage())?$x->getMessage():'prepare_failed','database_writes'=>0,'mapping_writes'=>0,'readback_verified'=>false];}
 $out+=['operation'=>M113_OP,'source_sha'=>$head,'provider_http_calls'=>0,'new_operator_ids'=>0,'no_replay'=>true,'generated_at_utc'=>gmdate('c')];$sha=w76_save($dir.'/result.json',$out);w76_save($dir.'/receipt.json',['operation'=>M113_OP,'state'=>$out['state'],'source_sha'=>$head,'result_sha256'=>$sha,'database_writes'=>$out['database_writes'],'mapping_writes'=>$out['mapping_writes'],'readback_verified'=>$out['readback_verified'],'provider_http_calls'=>0,'no_replay'=>true]);echo w76_json(array_diff_key($out,['rows'=>true,'held'=>true,'already'=>true,'samo_before'=>true,'samo_after'=>true]))."\n";return in_array($out['state'],['committed_readback_verified','completed_no_new_writes'],true)?0:2;
}
if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__)exit(m113_main($argv));
