<?php
declare(strict_types=1);
if (!defined('FC_LIBRARY_ONLY')) define('FC_LIBRARY_ONLY', true);
require_once __DIR__ . '/hotel_match_fuzzy_learned_geo_global_review.php';

const HMDFG_OPERATION='hotel-match-direct-fuzzy-geo-global-review-2333-20260914-v1';

function hmdfg_place_similarity(string $a,string $b): float {
    $a=hmlg_place_key($a);$b=hmlg_place_key($b);if($a===''||$b==='')return 0.0;if($a===$b)return 1.0;
    $aa=array_values(array_unique(fc_tokens($a,true)));$bb=array_values(array_unique(fc_tokens($b,true)));$x=array_fill_keys($aa,true);$y=array_fill_keys($bb,true);$u=count($x+$y);$j=$u?count(array_intersect_key($x,$y))/$u:0.0;$m=max(strlen($a),strlen($b));$l=$m?1-levenshtein($a,$b)/$m:0.0;return max($j,$l*0.93);
}
function hmdfg_review(PDO $db,string $operation=HMDFG_OPERATION): array {
    if($operation!==HMDFG_OPERATION)throw new RuntimeException('operation_scope');$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
    [$hotels,$names,$strict,$broad,$places,$scope]=mbr_catalog($db);$shaCountry=fc_sha_countries($db);
    $latest=[];$obsCount=[];foreach($db->query("SELECT * FROM andromeda_search_hotel_observations WHERE supplier_namespace='andromeda_catalog' ORDER BY observed_at_utc DESC,external_hotel_id")->fetchAll(PDO::FETCH_ASSOC) as $o){$id=(string)$o['external_hotel_id'];$obsCount[$id]=($obsCount[$id]??0)+1;if(!isset($latest[$id]))$latest[$id]=$o;}
    $catalogPlaces=[];foreach($hotels as $lid=>$h){$c=(int)$h['country_id'];foreach([(string)$h['region_name'],(string)$h['subregion_name']] as $p){$k=hmlg_place_key($p);if($k!=='')$catalogPlaces[$c][$k]['ids'][(int)$lid]=1;$catalogPlaces[$c][$k]['labels'][$p]=1;}}
    $andAccepted=array_fill_keys(array_map('intval',$db->query("SELECT DISTINCT local_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IS NOT NULL")->fetchAll(PDO::FETCH_COLUMN)),1);
    $stats=['pending_examined'=>0,'no_unique_identity_examined'=>0,'place_match'=>0,'place_ambiguous'=>0,'candidate_pool'=>0,'ranked'=>0,'safe'=>0,'medium'=>0,'observed'=>0,'occupied_target'=>0,'qualifier_conflict'=>0,'coordinate_conflict'=>0,'weak_name'=>0,'weak_margin'=>0,'no_place_match'=>0,'country_unknown'=>0];$safe=[];$medium=[];$reasons=[];
    foreach($db->query("SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='pending' AND local_hotel_id IS NULL ORDER BY external_hotel_id")->fetchAll(PDO::FETCH_ASSOC) as $r){$external=(string)$r['external_hotel_id'];$obs=$latest[$external]??null;$e=fc_evidence($r['evidence_json']??'');$src=$e['source']??[];if(!is_array($src))$src=[];$geo=$e['geography']??[];if(!is_array($geo))$geo=[];$country=(int)($obs['country_id']??0);if(!isset(MBR_CORE8[$country]))$country=(int)($shaCountry[$r['catalog_sha256']]??0);if(!isset(MBR_CORE8[$country])){$stats['country_unknown']++;continue;}$stats['pending_examined']++;
        $sourceNames=array_values(array_unique(array_filter([(string)($src['name']??''),(string)($src['lName']??''),(string)($obs['hotel_name']??'')],static fn($v)=>trim($v)!=='')));$strictIds=mbr_ids_for_names($strict,$country,$sourceNames,false);$broadIds=mbr_ids_for_names($broad,$country,$sourceNames,true);if($strictIds||$broadIds)continue;$stats['no_unique_identity_examined']++;
        $sourcePlaces=array_values(array_unique(array_filter([(string)($src['town']??''),(string)($geo['town']??''),(string)($geo['parent']??''),(string)($obs['region_name']??'')],static fn($v)=>trim($v)!=='')));$placeRank=[];foreach($sourcePlaces as $sp)foreach($catalogPlaces[$country]??[] as $pk=>$meta){$score=hmdfg_place_similarity($sp,$pk);if($score>=0.72)$placeRank[]=['source'=>$sp,'target_key'=>$pk,'score'=>round($score,6),'ids'=>array_map('intval',array_keys($meta['ids']))];}usort($placeRank,static fn($a,$b)=>$b['score']<=>$a['score']);$bestPlace=$placeRank[0]??null;if(!$bestPlace){$stats['no_place_match']++;$reasons['no_direct_fuzzy_place_match']=($reasons['no_direct_fuzzy_place_match']??0)+1;continue;}$secondPlace=$placeRank[1]['score']??0.0;if($bestPlace['score']<0.84||($secondPlace>0&&$bestPlace['target_key']!==($placeRank[1]['target_key']??'')&&$bestPlace['score']-$secondPlace<0.10)){$stats['place_ambiguous']++;$reasons['weak_or_ambiguous_place_match']=($reasons['weak_or_ambiguous_place_match']??0)+1;continue;}$stats['place_match']++;
        $pool=$bestPlace['ids'];if(!$pool)continue;$stats['candidate_pool']++;$rank=hmfg_rank($pool,$sourceNames,$names);$best=$rank[0]??null;if(!$best)continue;$stats['ranked']++;$second=$rank[1]['score']??0.0;$margin=(float)$best['score']-$second;$lid=(int)$best['id'];$target=$hotels[$lid];if(isset($andAccepted[$lid])){$stats['occupied_target']++;$reasons['target_already_accepted_andromeda']=($reasons['target_already_accepted_andromeda']??0)+1;continue;}if(!hmlg_qualifiers_ok($sourceNames,$names[$lid]??[(string)$target['name']])){$stats['qualifier_conflict']++;$reasons['meaningful_qualifier_conflict']=($reasons['meaningful_qualifier_conflict']??0)+1;continue;}$coord=$src;if($obs)$coord+=$obs;$guard=mbr_target_guard($coord,$target);if($guard['coordinate_conflict']){$stats['coordinate_conflict']++;$reasons['coordinate_conflict_gt_5km']=($reasons['coordinate_conflict_gt_5km']??0)+1;continue;}
        $oc=(int)($obsCount[$external]??0);$base=['external_id'=>$external,'country_id'=>$country,'observation_count'=>$oc,'source_names'=>$sourceNames,'source_places'=>$sourcePlaces,'place_evidence'=>['source'=>$bestPlace['source'],'target_key'=>$bestPlace['target_key'],'score'=>$bestPlace['score'],'second_score'=>round($secondPlace,6)],'target'=>mbr_row_target($target),'best'=>$best,'second_name_score'=>round($second,6),'margin'=>round($margin,6),'guard'=>$guard,'evidence'=>'direct_fuzzy_place_plus_strong_fuzzy_hotel_identity'];
        if($best['score']>=0.84&&$best['shared']>=2&&$margin>=0.18){$base['tier']='safe';$safe[]=$base;$stats['safe']++;if($oc>0)$stats['observed']++;continue;}if($best['score']>=0.76&&$best['shared']>=2&&$margin>=0.10){$base['tier']='medium';$medium[]=$base;$stats['medium']++;continue;}if($best['score']<0.76||$best['shared']<2){$stats['weak_name']++;$reasons['weak_hotel_name_score']=($reasons['weak_hotel_name_score']??0)+1;}else{$stats['weak_margin']++;$reasons['insufficient_hotel_name_margin']=($reasons['insufficient_hotel_name_margin']??0)+1;}
    }
    $sort=static fn($a,$b)=>(int)$b['observation_count']<=>(int)$a['observation_count'] ?: $b['best']['score']<=>$a['best']['score'] ?: $b['margin']<=>$a['margin'] ?: strcmp($a['external_id'],$b['external_id']);usort($safe,$sort);usort($medium,$sort);arsort($reasons);
    return ['status'=>'completed','operation_id'=>$operation,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'historical_operations_replayed'=>false,'coverage'=>fc_coverage($db),'catalog_scope'=>$scope,'stats'=>$stats,'blocked_reasons'=>$reasons,'safe_count'=>count($safe),'medium_count'=>count($medium),'safe'=>$safe,'medium'=>$medium];
}
