<?php
declare(strict_types=1);
const HMSB_OPERATION='hotel-match-user-seen-common4-saved-andromeda-bridge-1971-20260918-v1';
const HMSB_LIMIT=100000;
const HMSB_EXCLUDED_COUNTRIES=[46=>true,47=>true];
function hmsb_rows(PDO $p,string $q,array $a=[]): array {$s=$p->prepare($q);$s->execute(array_values($a));$r=$s->fetchAll(PDO::FETCH_ASSOC)?:[];if(count($r)>HMSB_LIMIT)throw new RuntimeException('row_budget');return $r;}
function hmsb_norm(string $v): string {$v=mb_strtolower(trim($v),'UTF-8');$v=strtr($v,['ё'=>'е','&'=>' ','+'=>' ','_'=>' ','-'=>' ','’'=>"'",'`'=>"'"]);$v=preg_replace('/[^\p{L}\p{N}]+/u',' ',$v)??$v;return trim(preg_replace('/\s+/u',' ',$v)??$v);}
function hmsb_valid(string $n): bool {return $n!==''&&mb_strlen($n,'UTF-8')>=4;}
function hmsb_variants(string $name): array {$out=[];$add=function(string $v,string $why)use(&$out){$n=hmsb_norm($v);if(hmsb_valid($n))$out[$n][$why]=true;};$add($name,'full');if(preg_match('/^(.+?)\s*\((?:EX\.?|FORMERLY|БЫВШ\.?)[^)]*\)/iu',$name,$m))$add($m[1],'current');if(preg_match_all('/\((?:EX\.?|FORMERLY|БЫВШ\.?)\s*([^)]*)\)/iu',$name,$ms))foreach($ms[1] as $x)foreach(preg_split('/[;|\/]+/u',$x)?:[] as $p)$add($p,'former');$flat=[];foreach($out as $k=>$v){$x=array_keys($v);sort($x,SORT_STRING);$flat[$k]=$x;}return $flat;}
function hmsb_product(string $n): bool {$n=hmsb_norm($n);return (bool)preg_match('/^(?:fortuna|фортуна|roulette|рулетка|рулет)(?:\s|$)/u',$n);}
function hmsb_durable(string $path,array $v): string {$raw=json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n";$f=@fopen($path,'x+b');if(!$f)throw new RuntimeException('durable_exists');try{if(fwrite($f,$raw)!==strlen($raw)||!fflush($f))throw new RuntimeException('durable_write');if(function_exists('fsync')&&!fsync($f))throw new RuntimeException('durable_sync');rewind($f);if(stream_get_contents($f)!==$raw)throw new RuntimeException('durable_readback');}finally{fclose($f);}return hash('sha256',$raw);}
function hmsb_source_names(array $identity,array $obs): array {$names=[];foreach($obs as $o){$v=trim((string)($o['hotel_name']??''));if($v!=='')$names[$v]=true;}try{$e=json_decode((string)($identity['evidence_json']??''),true,64,JSON_THROW_ON_ERROR);$s=$e['source']??[];if(is_array($s))foreach(['name','lName','hotel_name'] as $k){$v=trim((string)($s[$k]??''));if($v!=='')$names[$v]=true;}}catch(Throwable $e){}return array_keys($names);}
if(in_array('--self-test',$argv??[],true)){if(!isset(hmsb_variants('SUN BAY (EX. SUN MARIS PARK)')['sun maris park'])||!hmsb_product('FORTUNA BODRUM')||hmsb_product('RIXOS'))throw new RuntimeException('self');echo"MATCH_SAVED_ANDROMEDA_BRIDGE_SELFTEST_OK\n";exit;}
$root=realpath((string)getenv('ANYTOUR_ROOT'));$opDir=(string)getenv('MATCH_OPERATION_DIR');$reg=realpath((string)getenv('MATCH_MAPPING_REGISTRY_PATH'));$sourceSha=(string)getenv('MATCH_SOURCE_SHA');if(!$root||$opDir===''||!is_string($reg)||!is_file($reg)||!preg_match('/^[a-f0-9]{40}$/D',$sourceSha)||is_dir($opDir)||!mkdir($opDir,0700,true))throw new RuntimeException('runtime_guard');hmsb_durable($opDir.'/reservation.json',['operation'=>HMSB_OPERATION,'state'=>'reserved_before_db_read','source_sha'=>$sourceSha,'provider_access'=>false,'no_replay'=>true]);require_once $reg;$dbf=is_file($root.'/data/db-v1.php')?$root.'/data/db-v1.php':$root.'/v2/data/db-v1.php';require_once $dbf;$pdo=v2_data_db();$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$pdo->exec('START TRANSACTION READ ONLY');
try{
 $registry=AnyTourAnexSearchMappingRegistry::fromPdo($pdo);$anex=[];foreach(hmsb_rows($pdo,'SELECT anex_hotel_id FROM anex_hotel_search_mappings UNION SELECT anex_hotel_id FROM anex_hotel_decisions') as $r){$x=$registry->resolve('anex_online',(string)$r['anex_hotel_id'],'preview');if(is_int($x)&&$x>0)$anex[$x]=true;}
 $and=[];foreach(hmsb_rows($pdo,"SELECT DISTINCT local_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IS NOT NULL") as $r)$and[(int)$r['local_hotel_id']]=true;
 $seen=[];foreach(hmsb_rows($pdo,"SELECT hotel_id,COUNT(*) rows_count,MAX(observed_at) last_seen FROM tour_price_observations WHERE source='user_search' GROUP BY hotel_id") as $r)$seen[(int)$r['hotel_id']]=['rows'=>(int)$r['rows_count'],'last'=>(string)$r['last_seen']];$ids=array_keys($seen);$ph=implode(',',array_fill(0,count($ids),'?'));
 $front=[];foreach(hmsb_rows($pdo,"SELECT id,country_id,country_name,region_name,subregion_name,name,is_active FROM catalog_hotels WHERE id IN ($ph)",$ids) as $h){$id=(int)$h['id'];$cid=(int)$h['country_id'];if((int)$h['is_active']!==1||isset(HMSB_EXCLUDED_COUNTRIES[$cid])||isset($anex[$id])||isset($and[$id])||hmsb_product((string)$h['name']))continue;$front[$id]=$h+['observation_rows'=>$seen[$id]['rows'],'last_observed_at'=>$seen[$id]['last']];}
 $fids=array_keys($front);$common=[];if($fids){$fh=implode(',',array_fill(0,count($fids),'?'));foreach(hmsb_rows($pdo,"SELECT DISTINCT hotel_id FROM tour_price_observations WHERE source='user_search' AND hotel_id IN ($fh) AND departure_date>=CURRENT_DATE AND operator_id IN(13,18,25,43)",$fids) as $r)$common[(int)$r['hotel_id']]=true;}$targets=array_intersect_key($front,$common);$countries=[];foreach($targets as $h)$countries[(int)$h['country_id']]=true;if(!$countries)throw new RuntimeException('no_targets');
 $cids=array_keys($countries);$cph=implode(',',array_fill(0,count($cids),'?'));$all=[];$index=[];foreach(hmsb_rows($pdo,"SELECT id,country_id,country_name,region_name,subregion_name,name,is_active FROM catalog_hotels WHERE is_active=1 AND country_id IN ($cph)",$cids) as $h){$id=(int)$h['id'];$all[$id]=$h;foreach(hmsb_variants((string)$h['name']) as $k=>$why)$index[(int)$h['country_id']][$k][$id]=true;}
 $pending=[];foreach(hmsb_rows($pdo,"SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='pending' AND local_hotel_id IS NULL ORDER BY external_hotel_id") as $r)$pending[(string)$r['external_hotel_id']]=$r;
 $obs=[];foreach(hmsb_rows($pdo,"SELECT external_hotel_id,country_id,hotel_name,region_name,observed_at_utc FROM andromeda_search_hotel_observations WHERE supplier_namespace='andromeda_catalog' ORDER BY observed_at_utc DESC") as $r){$ext=(string)$r['external_hotel_id'];if(isset($pending[$ext]))$obs[$ext][]=$r;}
 $raw=[];$reasonCounts=[];foreach($pending as $ext=>$identity){$os=$obs[$ext]??[];if(!$os){$reasonCounts['no_saved_observation']=($reasonCounts['no_saved_observation']??0)+1;continue;}$countrySet=[];$regions=[];foreach($os as $o){$cid=(int)($o['country_id']??0);if($cid>0)$countrySet[$cid]=true;$rn=hmsb_norm((string)($o['region_name']??''));if($rn!=='')$regions[$rn]=true;}if(count($countrySet)!==1){$reasonCounts['country_not_unanimous']=($reasonCounts['country_not_unanimous']??0)+1;continue;}$cid=(int)array_key_first($countrySet);if(!isset($countries[$cid]))continue;$hits=[];$matchKeys=[];foreach(hmsb_source_names($identity,$os) as $sn)foreach(hmsb_variants($sn) as $k=>$why)foreach(array_keys($index[$cid][$k]??[]) as $lid){if(isset($targets[$lid])){$hits[$lid]=true;$matchKeys[$lid][$k]=true;}}if(count($hits)!==1){$reasonCounts[count($hits)>1?'multiple_local_targets':'no_exact_target']=($reasonCounts[count($hits)>1?'multiple_local_targets':'no_exact_target']??0)+1;continue;}$lid=(int)array_key_first($hits);$h=$targets[$lid];$localPlaces=array_values(array_filter([hmsb_norm((string)$h['region_name']),hmsb_norm((string)$h['subregion_name'])]));$regKeys=array_keys($regions);$direct=array_values(array_intersect($localPlaces,$regKeys));$conflict=array_values(array_diff($regKeys,$localPlaces));if(!$direct||$conflict){$reasonCounts[$conflict?'saved_region_conflict':'no_direct_saved_region']=($reasonCounts[$conflict?'saved_region_conflict':'no_direct_saved_region']??0)+1;continue;}$keys=array_keys($matchKeys[$lid]);sort($keys,SORT_STRING);$raw[]=['external_hotel_id'=>$ext,'local_hotel_id'=>$lid,'country_id'=>$cid,'local_name'=>(string)$h['name'],'source_names'=>hmsb_source_names($identity,$os),'match_keys'=>$keys,'saved_regions'=>$regKeys,'matched_regions'=>$direct,'observation_rows'=>(int)$h['observation_rows'],'identity_evidence_sha256'=>(string)($identity['evidence_sha256']??'')];}
 $extToLocal=[];$localToExt=[];foreach($raw as $r){$extToLocal[$r['external_hotel_id']][$r['local_hotel_id']]=true;$localToExt[$r['local_hotel_id']][$r['external_hotel_id']]=true;}$safe=[];$oneToOneHolds=[];foreach($raw as $r){if(count($extToLocal[$r['external_hotel_id']])!==1||count($localToExt[$r['local_hotel_id']])!==1){$oneToOneHolds[]=$r;continue;}$safe[]=$r;}usort($safe,fn($a,$b)=>$b['observation_rows']<=>$a['observation_rows']?:$a['local_hotel_id']<=>$b['local_hotel_id']);$pdo->rollBack();ksort($reasonCounts);
 $result=['operation'=>HMSB_OPERATION,'status'=>'read_only_complete','source_sha'=>$sourceSha,'current_unresolved_real'=>count($front),'current_common4_residual'=>count($targets),'pending_identities_examined'=>count($pending),'pending_with_saved_observations'=>count($obs),'raw_candidate_count'=>count($raw),'safe_one_to_one_count'=>count($safe),'safe_candidates'=>$safe,'one_to_one_holds'=>array_slice($oneToOneHolds,0,200),'reason_counts'=>$reasonCounts,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0];
}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$result=['operation'=>HMSB_OPERATION,'status'=>'failed_read_only','reason'=>preg_replace('/[^a-z0-9_\-]/i','_',mb_substr($e->getMessage(),0,100)),'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0];}
$sha=hmsb_durable($opDir.'/result.json',$result);hmsb_durable($opDir.'/receipt.json',['operation'=>HMSB_OPERATION,'status'=>$result['status'],'result_sha256'=>$sha,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);echo json_encode($result,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";exit(($result['status']??'')==='read_only_complete'?0:2);
