<?php
declare(strict_types=1);
if (!defined('FC_LIBRARY_ONLY')) define('FC_LIBRARY_ONLY', true);
require_once __DIR__ . '/hotel_match_andromeda_duplicate_bridge_global_review.php';

const HMASB_OPERATION='hotel-match-andromeda-star-signal-bridge-review-2333-20260914-v1';

function hmasb_identity_numbers(string $v): array {
    $v=preg_replace('/\b[1-5]\s*(?:\*|★|stars?)\b/iu',' ',hmlg_latin($v)) ?? $v;
    $v=preg_replace('/\b(?:adult|adults|only)\s*\+?\s*(?:16|18|21)\+?\b/iu',' ',$v) ?? $v;
    preg_match_all('/\b([0-9]{1,2})\b/u',$v,$m);$out=[];foreach($m[1] as $n){$i=(int)$n;if($i>=1&&$i<=9)$out[$i]=1;}ksort($out);return array_map('intval',array_keys($out));
}
function hmasb_numeric_qualifiers_ok(string $a,string $b): bool { return hmasb_identity_numbers($a)===hmasb_identity_numbers($b); }
function hmasb_review(PDO $db,string $operation=HMASB_OPERATION): array {
    if($operation!==HMASB_OPERATION)throw new RuntimeException('operation_scope');$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
    [$hotels,$names,$strict,$broad,$places,$scope]=mbr_catalog($db);$shaCountry=fc_sha_countries($db);
    $latest=[];$obsCount=[];foreach($db->query("SELECT * FROM andromeda_search_hotel_observations WHERE supplier_namespace='andromeda_catalog' ORDER BY observed_at_utc DESC,external_hotel_id")->fetchAll(PDO::FETCH_ASSOC) as $o){$id=(string)$o['external_hotel_id'];$obsCount[$id]=($obsCount[$id]??0)+1;if(!isset($latest[$id]))$latest[$id]=$o;}
    $accepted=[];$tokenIndex=[];foreach($db->query("SELECT external_hotel_id,local_hotel_id,evidence_json FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IS NOT NULL ORDER BY external_hotel_id")->fetchAll(PDO::FETCH_ASSOC) as $r){$lid=(int)$r['local_hotel_id'];if(!isset($hotels[$lid]))continue;$country=(int)$hotels[$lid]['country_id'];$e=fc_evidence($r['evidence_json']??'');$ns=hmadb_source_names($e);if(!$ns)continue;$idx=count($accepted);$accepted[]=['external_id'=>(string)$r['external_hotel_id'],'local_id'=>$lid,'country_id'=>$country,'names'=>$ns,'places'=>hmadb_source_places($e)];$seen=[];foreach($ns as $n)foreach(hmfg_tokens($n) as $t)$seen[$t]=1;foreach(array_keys($seen) as $t)$tokenIndex[$country][$t][$idx]=1;}
    $stats=['pending_examined'=>0,'star_mismatch_candidates'=>0,'shared2_pool'=>0,'ranked'=>0,'safe'=>0,'medium'=>0,'observed'=>0,'numeric_qualifier_conflict'=>0,'meaningful_qualifier_conflict'=>0,'coordinate_conflict'=>0,'weak_identity'=>0,'weak_geo'=>0,'country_unknown'=>0];$safe=[];$medium=[];$reasons=[];
    foreach($db->query("SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='pending' AND local_hotel_id IS NULL ORDER BY external_hotel_id")->fetchAll(PDO::FETCH_ASSOC) as $r){$external=(string)$r['external_hotel_id'];$obs=$latest[$external]??null;$e=fc_evidence($r['evidence_json']??'');$src=$e['source']??[];if(!is_array($src))$src=[];$country=(int)($obs['country_id']??0);if(!isset(MBR_CORE8[$country]))$country=(int)($shaCountry[$r['catalog_sha256']]??0);if(!isset(MBR_CORE8[$country])){$stats['country_unknown']++;continue;}$stats['pending_examined']++;
        $sourceNames=hmadb_source_names($e,$obs);$strictIds=mbr_ids_for_names($strict,$country,$sourceNames,false);$broadIds=mbr_ids_for_names($broad,$country,$sourceNames,true);if(count($strictIds)!==0||count($broadIds)!==0)continue;
        $sourceCat=mbr_numeric_category($src);if($sourceCat===null&&$obs)$sourceCat=mbr_numeric_category($obs);if($sourceCat===null)continue;$tokens=[];foreach($sourceNames as $n)foreach(hmfg_tokens($n) as $t)$tokens[$t]=1;if(count($tokens)<2)continue;$votes=[];foreach(array_keys($tokens) as $t)foreach(array_keys($tokenIndex[$country][$t]??[]) as $idx)$votes[(int)$idx]=($votes[(int)$idx]??0)+1;$pool=[];foreach($votes as $idx=>$n)if($n>=2)$pool[]=(int)$idx;if(!$pool)continue;$stats['shared2_pool']++;
        $rank=[];foreach($pool as $idx){$a=$accepted[$idx];$best=['score'=>0.0,'shared'=>0,'jaccard'=>0.0,'lev'=>0.0,'source'=>'','accepted'=>''];foreach($sourceNames as $s)foreach($a['names'] as $t){[$score,$shared,$j,$lev]=hmfg_similarity($s,$t);if($score>$best['score']||($score===$best['score']&&$shared>$best['shared']))$best=['score'=>round($score,6),'shared'=>$shared,'jaccard'=>round($j,6),'lev'=>round($lev,6),'source'=>$s,'accepted'=>$t];}$rank[]=$best+['accepted_index'=>$idx,'accepted_external_id'=>$a['external_id'],'local_id'=>$a['local_id']];}usort($rank,static fn($a,$b)=>$b['score']<=>$a['score'] ?: $b['shared']<=>$a['shared'] ?: $a['local_id']<=>$b['local_id']);$best=$rank[0]??null;if(!$best)continue;$stats['ranked']++;$a=$accepted[(int)$best['accepted_index']];$lid=(int)$best['local_id'];$target=$hotels[$lid];$targetCat=$target['category']===null?null:(int)$target['category'];if($targetCat===null||$sourceCat===$targetCat)continue;$stats['star_mismatch_candidates']++;
        $second=0.0;foreach(array_slice($rank,1) as $x){if((int)$x['local_id']!==$lid){$second=(float)$x['score'];break;}}$margin=(float)$best['score']-$second;
        if(!hmlg_qualifiers_ok($sourceNames,$a['names'])){$stats['meaningful_qualifier_conflict']++;$reasons['meaningful_qualifier_conflict']=($reasons['meaningful_qualifier_conflict']??0)+1;continue;}if(!hmasb_numeric_qualifiers_ok((string)$best['source'],(string)$best['accepted'])){$stats['numeric_qualifier_conflict']++;$reasons['numeric_identity_qualifier_conflict']=($reasons['numeric_identity_qualifier_conflict']??0)+1;continue;}
        $coord=$src;if($obs)$coord+=$obs;$guard=mbr_target_guard($coord,$target);if($guard['coordinate_conflict']){$stats['coordinate_conflict']++;$reasons['coordinate_conflict_gt_5km']=($reasons['coordinate_conflict_gt_5km']??0)+1;continue;}$sourcePlaces=hmadb_source_places($e,$obs);$providerGeo=fc_place($sourcePlaces,$a['places']);$targetGeo=fc_place($sourcePlaces,[(string)$target['region_name'],(string)$target['subregion_name']]);$geo=$providerGeo||$targetGeo;
        $base=['external_id'=>$external,'country_id'=>$country,'observation_count'=>(int)($obsCount[$external]??0),'source_names'=>$sourceNames,'source_places'=>$sourcePlaces,'accepted_bridge_external_id'=>$a['external_id'],'accepted_bridge_names'=>$a['names'],'accepted_bridge_places'=>$a['places'],'target'=>mbr_row_target($target),'best'=>$best,'second_local_score'=>round($second,6),'margin'=>round($margin,6),'provider_geo_match'=>(bool)$providerGeo,'target_geo_match'=>(bool)$targetGeo,'guard'=>$guard,'source_category'=>$sourceCat,'target_category'=>$targetCat,'star_policy'=>'signal_not_identity_veto','evidence'=>'very_strong_same_provider_bridge_with_star_mismatch_annotation'];
        if($best['shared']>=3&&$best['score']>=0.96&&$margin>=0.18&&($geo||$best['score']>=0.99)){$base['tier']='safe';$safe[]=$base;$stats['safe']++;if($base['observation_count']>0)$stats['observed']++;continue;}if($best['shared']>=3&&$best['score']>=0.90&&$margin>=0.15&&$geo){$base['tier']='medium';$medium[]=$base;$stats['medium']++;continue;}if(!$geo){$stats['weak_geo']++;$reasons['star_mismatch_without_geo']=($reasons['star_mismatch_without_geo']??0)+1;}else{$stats['weak_identity']++;$reasons['star_mismatch_identity_not_strong_enough']=($reasons['star_mismatch_identity_not_strong_enough']??0)+1;}
    }
    $sort=static fn($a,$b)=>(int)$b['observation_count']<=>(int)$a['observation_count'] ?: $b['best']['score']<=>$a['best']['score'] ?: $b['margin']<=>$a['margin'] ?: strcmp($a['external_id'],$b['external_id']);usort($safe,$sort);usort($medium,$sort);arsort($reasons);
    return ['status'=>'completed','operation_id'=>$operation,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'historical_operations_replayed'=>false,'coverage'=>fc_coverage($db),'catalog_scope'=>$scope,'stats'=>$stats,'blocked_reasons'=>$reasons,'safe_count'=>count($safe),'medium_count'=>count($medium),'safe'=>$safe,'medium'=>$medium];
}
