<?php
declare(strict_types=1);
require_once __DIR__.'/hotel_match_residual_evidence_audit.php';
const HMREA_OPERATION='hotel-match-residual-evidence-accept-1971-20260913-v1';
function hmrea_norm(string $s):string{$s=mb_strtolower($s,'UTF-8');preg_match_all('/[\p{L}\p{N}]+/u',$s,$m);$drop=['hotel'=>1,'hotels'=>1,'отель'=>1,'resort'=>1,'spa'=>1,'laleli'=>1,'лалели'=>1];$o=[];foreach($m[0] as$x)if(!isset($drop[$x]))$o[]=$x;sort($o,SORT_STRING);return implode(' ',$o);}
function hmrea_dist($a,$b,$c,$d):?float{foreach([$a,$b,$c,$d]as$x)if(!is_numeric($x))return null;$a=deg2rad((float)$a);$c=deg2rad((float)$c);$dp=$c-$a;$dl=deg2rad((float)$d-(float)$b);$h=sin($dp/2)**2+cos($a)*cos($c)*sin($dl/2)**2;return 12742000*asin(min(1,sqrt($h)));}
function hmrea_rows(array $audit):array{$o=[];foreach($audit['rows']??[]as$r)$o[$r['provider'].'|'.$r['external_id']]=$r;return$o;}
function hmrea_validate(array $rows):void{
  foreach([['andromeda','116593',17541,36058],['andromeda','122823',17535,37182],['andromeda','243802',17543,34377]]as$m){[$p,$e,$t,$aid]=$m;$r=$rows[$p.'|'.$e]??null;if(!$r||(int)$r['target']['id']!==$t||!in_array($aid,array_map('intval',$r['accepted_anex_at_target']??[]),true))throw new RuntimeException('manifest_changed_'.$e);$src=$r['andromeda_current']['source']??[];$opp=null;foreach($r['opposite_anex']??[]as$x)if((int)$x['anex_hotel_id']===$aid)$opp=$x;if(!$opp)throw new RuntimeException('opposite_missing_'.$e);$sn=(string)($src['name']??'');$an=(string)($opp['stage']['api_name']??'');if(hmrea_norm($sn)===''||hmrea_norm($sn)!==hmrea_norm($an))throw new RuntimeException('name_changed_'.$e);if((int)($src['star']??0)!==(int)$r['target']['category'])throw new RuntimeException('category_changed_'.$e);
    if($e==='243802'){$d=hmrea_dist($opp['stage']['latitude']??null,$opp['stage']['longitude']??null,$r['target']['latitude']??null,$r['target']['longitude']??null);if($d===null||$d>1000)throw new RuntimeException('mosaic_geo_changed');}
    else{if(mb_stripos((string)($opp['stage']['api_town']??''),'Лалели',0,'UTF-8')===false||mb_stripos((string)($src['town']??''),'Фатих',0,'UTF-8')===false||(string)$r['target']['subregion_name']!=='Лалели')throw new RuntimeException('laleli_geo_changed_'.$e);}
  }
  $r=$rows['anex|30424']??null;if(!$r||(int)$r['target']['id']!==17617||!in_array('2000060795',array_map('strval',$r['accepted_andromeda_at_target']??[]),true))throw new RuntimeException('sarnic_manifest_changed');$opp=null;foreach($r['opposite_andromeda']??[]as$x)if((string)$x['external_hotel_id']==='2000060795')$opp=$x;if(!$opp)throw new RuntimeException('sarnic_opposite_missing');$n=mb_strtolower((string)($opp['source']['name']??''),'UTF-8');$ln=mb_strtolower((string)($opp['source']['lName']??''),'UTF-8');if(strpos($n,'sarnic')===false||strpos($n,'ottoman mansion')===false||strpos($ln,'sarnic')===false||strpos($ln,'ottoman mansion')===false||(int)($opp['source']['star']??0)!==4||(int)$r['target']['category']!==4)throw new RuntimeException('sarnic_former_name_changed');
}
function hmrea_counts(PDO$db):array{$o=['accepted'=>0,'pending'=>0,'conflict'=>0];foreach($db->query("SELECT decision_status,COUNT(*) n FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' GROUP BY decision_status")->fetchAll(PDO::FETCH_ASSOC)as$r){$s=(string)$r['decision_status'];if(isset($o[$s]))$o[$s]=(int)$r['n'];}return$o;}
function hmrea_accept(PDO$db):array{
  $audit=hmre_run($db);$rows=hmrea_rows($audit);hmrea_validate($rows);$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET SESSION innodb_lock_wait_timeout=20');$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$writes=0;$committed=false;$written=['anex'=>[],'andromeda'=>[]];
  try{$db->beginTransaction();$db->query('SELECT anex_hotel_id FROM anex_hotel_decisions ORDER BY anex_hotel_id FOR UPDATE')->fetchAll();$db->query('SELECT anex_hotel_id FROM anex_hotel_search_mappings ORDER BY anex_hotel_id FOR UPDATE')->fetchAll();$db->query("SELECT external_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' ORDER BY external_hotel_id FOR UPDATE")->fetchAll();$before=fc_coverage($db);$ib=hmrea_counts($db);
    $manual=array_fill_keys(array_map('intval',$db->query('SELECT anex_hotel_id FROM anex_hotel_decisions')->fetchAll(PDO::FETCH_COLUMN)),true);$existing=array_fill_keys(array_map('intval',$db->query('SELECT anex_hotel_id FROM anex_hotel_search_mappings')->fetchAll(PDO::FETCH_COLUMN)),true);$excluded=[];foreach($db->query('SELECT anex_hotel_id,catalog_hotel_id FROM anex_review_pair_exclusions')->fetchAll(PDO::FETCH_ASSOC)as$x)$excluded[(int)$x['anex_hotel_id']][(int)$x['catalog_hotel_id']]=true;
    $anLocal=[];foreach($db->query("SELECT anex_hotel_id,catalog_hotel_id FROM anex_hotel_search_mappings WHERE enabled=1 AND scope='preview'")->fetchAll(PDO::FETCH_ASSOC)as$x)$anLocal[(int)$x['catalog_hotel_id']][(int)$x['anex_hotel_id']]=true;foreach($db->query("SELECT anex_hotel_id,catalog_hotel_id FROM anex_hotel_decisions WHERE decision_status='accepted' AND catalog_hotel_id IS NOT NULL")->fetchAll(PDO::FETCH_ASSOC)as$x)$anLocal[(int)$x['catalog_hotel_id']][(int)$x['anex_hotel_id']]=true;
    $adLocal=[];foreach($db->query("SELECT external_hotel_id,local_hotel_id FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IS NOT NULL")->fetchAll(PDO::FETCH_ASSOC)as$x)$adLocal[(int)$x['local_hotel_id']][(string)$x['external_hotel_id']]=true;
    $q=$db->prepare("SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=?");$upd=$db->prepare("UPDATE andromeda_hotel_identities SET local_hotel_id=?,decision_status='accepted',evidence_sha256=?,evidence_json=? WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=? AND decision_status='pending' AND local_hotel_id IS NULL AND evidence_sha256 <=> ?");
    foreach([['116593',17541,36058,'name_plus_provider_geo_plus_category'],['122823',17535,37182,'name_plus_provider_geo_plus_category'],['243802',17543,34377,'name_plus_opposite_provider_coordinates']]as$m){[$e,$t,$aid,$rule]=$m;$q->execute([$e]);$cur=$q->fetch(PDO::FETCH_ASSOC);if(!$cur||(string)$cur['decision_status']!=='pending'||$cur['local_hotel_id']!==null||isset($adLocal[$t])||!isset($anLocal[$t][$aid]))throw new RuntimeException('andromeda_current_guard_'.$e);$prior=hmre_json($cur['evidence_json']??'');$ev=['prior_evidence'=>$prior,'promotion'=>['operation_id'=>HMREA_OPERATION,'review_operation'=>HMRE_OPERATION,'lane'=>'MATCH','rule'=>$rule,'target'=>$t,'opposite_anex_hotel_id'=>$aid,'server_current'=>true]];$json=json_encode($ev,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);$hash=hash('sha256',$json);$upd->execute([$t,$hash,$json,$e,$cur['evidence_sha256']]);if($upd->rowCount()!==1)throw new RuntimeException('andromeda_concurrent_'.$e);$written['andromeda'][$e]=['target'=>$t,'evidence_sha256'=>$hash];$writes++;}
    $id=30424;$t=17617;$did='2000060795';if(isset($manual[$id])||isset($existing[$id])||isset($excluded[$id][$t])||isset($anLocal[$t])||!isset($adLocal[$t][$did]))throw new RuntimeException('sarnic_current_guard');$ev=['operation_id'=>HMREA_OPERATION,'review_operation'=>HMRE_OPERATION,'lane'=>'MATCH','provider'=>'anex','rule'=>'explicit_former_name_opposite_provider','anex_hotel_id'=>$id,'target'=>$t,'opposite_andromeda_id'=>$did,'server_current'=>true];$digest=hash('sha256',json_encode($ev,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR));$md=hash('sha256',HMREA_OPERATION.'|residual-evidence');$ins=$db->prepare("INSERT INTO anex_hotel_search_mappings(anex_hotel_id,catalog_hotel_id,match_class,scope,approval_policy,source_row_digest,mapping_digest,enabled) VALUES(?,?,'strong_candidate','preview',?,?,?,1)");$ins->execute([$id,$t,'human_reviewed',$digest,$md]);if($ins->rowCount()!==1)throw new RuntimeException('sarnic_insert');$written['anex'][$id]=['target'=>$t,'source_row_digest'=>$digest,'mapping_digest'=>$md];$writes++;
    if($writes!==4)throw new RuntimeException('write_count');$db->commit();$committed=true;
    $qa=$db->prepare('SELECT catalog_hotel_id,source_row_digest,mapping_digest,enabled FROM anex_hotel_search_mappings WHERE anex_hotel_id=?');foreach($written['anex']as$id=>$x){$qa->execute([$id]);$r=$qa->fetch(PDO::FETCH_ASSOC);if(!$r||(int)$r['catalog_hotel_id']!==$x['target']||(int)$r['enabled']!==1||!hash_equals($x['source_row_digest'],(string)$r['source_row_digest']))throw new RuntimeException('anex_readback');}$qd=$db->prepare("SELECT local_hotel_id,decision_status,evidence_sha256 FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id=?");foreach($written['andromeda']as$id=>$x){$qd->execute([$id]);$r=$qd->fetch(PDO::FETCH_ASSOC);if(!$r||(int)$r['local_hotel_id']!==$x['target']||(string)$r['decision_status']!=='accepted'||!hash_equals($x['evidence_sha256'],(string)$r['evidence_sha256']))throw new RuntimeException('andromeda_readback');}
    return['status'=>'completed','operation_id'=>HMREA_OPERATION,'database_writes'=>4,'mapping_writes'=>4,'planned'=>['anex'=>1,'andromeda'=>3],'supplier_calls'=>0,'tourvisor_calls'=>0,'committed'=>true,'readback_verified'=>true,'coverage_before'=>$before,'coverage_after'=>fc_coverage($db),'identity_before'=>$ib,'identity_after'=>hmrea_counts($db),'written'=>$written,'no_replay'=>true];
  }catch(Throwable$e){if($db->inTransaction())$db->rollBack();return['status'=>'failed','operation_id'=>HMREA_OPERATION,'reason'=>$e->getMessage(),'database_writes'=>$committed?'unknown':0,'mapping_writes'=>$committed?'unknown':0,'supplier_calls'=>0,'tourvisor_calls'=>0,'committed'=>$committed,'readback_verified'=>false,'no_replay'=>true];}
}
