<?php
declare(strict_types=1);
const S34_OP='hotel-match-common4-saved-samo-name34-current-1971-20260919-v1';
const S34_INPUT_SHA='75331e97a1d677e3b57e15d475d98a77aafeab16889377805dcee6daed00e372';
const S34_RESULT_SHA='fd0fcf1a6d6c8db5a1b0d3cb95b91c53c62c683e845c3eca6470ff70c9d9c0a4';
const S34_NS=['funsun'=>'operator_315','intourist'=>'operator_342'];
function s34_req(bool $x,string $m):void{if(!$x)throw new RuntimeException($m);}
function s34_norm(string $s):string{$s=mb_strtolower($s,'UTF-8');$s=preg_replace('/\([^)]*\)/u',' ',$s);$s=str_replace(['&','ё','й'],[' and ','е','и'],$s);$s=preg_replace('/\b(?:hotel|hotels|resort|resorts|spa|the|and)\b/ui',' ',$s);$s=preg_replace('/[^\p{L}\p{N}]+/u',' ',$s);return trim(preg_replace('/\s+/u',' ',$s));}
function s34_forms(string $s):array{$out=[];$parts=[$s];if(preg_match_all('/\((?:\s*(?:ex\.?|ех\.?)\s*)?([^()]*)\)/ui',$s,$m))foreach($m[1]as$v)$parts[]=$v;$main=preg_replace('/\([^)]*\)/u',' ',$s);$parts[]=$main;foreach($parts as$v){$n=s34_norm((string)$v);if($n!==''&&mb_strlen($n,'UTF-8')>=4)$out[$n]=true;}return array_keys($out);}
function s34_source_objects(mixed $x,array &$out):void{if(!is_array($x))return;if(isset($x['source'])&&is_array($x['source']))$out[]=$x['source'];foreach($x as$k=>$v)if(is_array($v)&&$k!=='source')s34_source_objects($v,$out);}
function s34_names(array $row):array{$out=[];$j=json_decode((string)($row['evidence_json']??''),true);if(!is_array($j))return[];$src=[];s34_source_objects($j,$src);foreach($src as$s)foreach(['name','lName','hotel_name','hotelName']as$k)if(isset($s[$k])&&is_scalar($s[$k]))foreach(s34_forms((string)$s[$k])as$n)$out[$n]=true;return array_keys($out);}
function s34_write(string $p,array $x):string{$raw=json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";$f=@fopen($p,'x+b');s34_req(is_resource($f),'exclusive_output');fwrite($f,$raw);fflush($f);if(function_exists('fsync'))fsync($f);fclose($f);return hash('sha256',$raw);}
function s34_selftest():void{s34_req(in_array('ares city',s34_forms('ARES CITY (EX. KAMI HOTEL)'),true),'former_form');$row=['evidence_json'=>json_encode(['proof'=>['source'=>['id'=>'7','name'=>'ARES CITY','lName'=>'KAMI HOTEL']]])];$n=s34_names($row);s34_req(in_array('ares city',$n,true)&&in_array('kami',$n,true),'source_names');echo"hotel-match-common4-saved-samo-name34-current-v1: PASS\n";}
function s34_main():void{
 s34_req(PHP_SAPI==='cli'&&(string)getenv('MATCH_OPERATION_ID')===S34_OP,'operation_guard');$sha=(string)getenv('MATCH_SOURCE_SHA');s34_req(preg_match('/^[0-9a-f]{40}$/D',$sha)===1,'source_sha');$dir=rtrim((string)getenv('HOME'),'/').'/.anytoour-match/operations/'.S34_OP;$rp=realpath($dir.'/reservation.json');$ip=realpath($dir.'/input.json');s34_req(is_string($rp)&&is_string($ip)&&hash_file('sha256',$ip)===S34_INPUT_SHA,'input_guard');$res=json_decode((string)file_get_contents($rp),true,64,JSON_THROW_ON_ERROR);s34_req(($res['operation_id']??'')===S34_OP&&($res['source_sha']??'')===$sha&&($res['state']??'')==='reserved_before_db_access','reservation');$in=json_decode((string)file_get_contents($ip),true,128,JSON_THROW_ON_ERROR);s34_req(($in['source_result_sha256']??'')===S34_RESULT_SHA&&count($in['edges']??[])===39&&(int)($in['unique_tv_hotels']??0)===34,'input_shape');
 $root=realpath(getcwd());s34_req(is_string($root)&&basename($root)==='anytoour.ru','root');require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$out=['operation_id'=>S34_OP,'source_sha'=>$sha,'source_result_sha256'=>S34_RESULT_SHA,'state'=>'failed_no_replay','database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'samo_calls'=>0,'no_replay'=>true];
 try{$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');$engine=$db->query("SELECT ENGINE FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='andromeda_hotel_identities'")->fetchColumn();s34_req(strtoupper((string)$engine)==='INNODB','table_contract');$q=$db->prepare('SELECT supplier_namespace,external_hotel_id,local_hotel_id,decision_status,evidence_json,evidence_sha256 FROM andromeda_hotel_identities WHERE supplier_namespace=? ORDER BY external_hotel_id LIMIT 250001');$index=[];$namespaceCounts=[];$parseable=[];foreach(S34_NS as$op=>$ns){$q->execute([$ns]);$rows=$q->fetchAll(PDO::FETCH_ASSOC)?:[];s34_req(count($rows)<=250000,'namespace_row_budget');$namespaceCounts[$ns]=count($rows);$parseable[$ns]=0;foreach($rows as$r){$names=s34_names($r);if($names)$parseable[$ns]++;foreach($names as$n)$index[$ns][$n][]=['external_hotel_id'=>(string)$r['external_hotel_id'],'local_hotel_id'=>$r['local_hotel_id']===null?null:(int)$r['local_hotel_id'],'decision_status'=>(string)$r['decision_status'],'evidence_sha256'=>(string)$r['evidence_sha256'],'matched_saved_name'=>$n];}}
  $dossiers=[];$counts=['unique_saved_name_candidate'=>0,'multiple_saved_name_candidates'=>0,'no_saved_same_operator_name_candidate'=>0];foreach($in['edges']as$e){$op=(string)$e['operator'];$ns=S34_NS[$op]??null;s34_req($ns!==null,'operator');$cand=[];foreach(s34_forms((string)$e['hotel_name'])as$n)foreach($index[$ns][$n]??[]as$r)$cand[$r['external_hotel_id'].'|'.($r['local_hotel_id']??'null').'|'.$r['decision_status']]=$r;$cand=array_values($cand);$status=count($cand)===0?'no_saved_same_operator_name_candidate':(count($cand)===1?'unique_saved_name_candidate':'multiple_saved_name_candidates');$counts[$status]++;$dossiers[]=['tv_hotel_id'=>(int)$e['tv_hotel_id'],'hotel_name'=>(string)$e['hotel_name'],'operator'=>$op,'supplier_namespace'=>$ns,'operator_link_native_tokens'=>$e['operator_link_native_tokens'],'saved_samo_name_candidates'=>$cand,'candidate_count'=>count($cand),'status'=>$status,'safe_to_write_now'=>false];}
  $db->commit();$out['state']='completed_read_only';$out['read_at_utc']=gmdate('c');$out['namespace_row_counts']=$namespaceCounts;$out['namespace_rows_with_source_names']=$parseable;$out['classification_counts']=$counts;$out['dossiers']=$dossiers;
 }catch(Throwable $e){if($db->inTransaction())$db->rollBack();$m=$e->getMessage();$out['reason']=preg_match('/^[A-Za-z0-9_:.-]+$/D',$m)?$m:'sanitized_error';}
 $h=s34_write($dir.'/result.json',$out);s34_write($dir.'/receipt.json',['operation_id'=>S34_OP,'source_sha'=>$sha,'state'=>$out['state'],'result_sha256'=>$h,'readback_verified'=>hash_file('sha256',$dir.'/result.json')===$h,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'samo_calls'=>0,'no_replay'=>true]);echo json_encode(['state'=>$out['state'],'reason'=>$out['reason']??null,'namespace_row_counts'=>$out['namespace_row_counts']??null,'classification_counts'=>$out['classification_counts']??null,'result_sha256'=>$h],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n";exit($out['state']==='completed_read_only'?0:2);
}
if(($argv[1]??'')==='--self-test'){s34_selftest();exit(0);}if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__)s34_main();
