<?php
declare(strict_types=1);
const N10_OP='hotel-match-live10-nonmoscow-current-1971-20260919-v1',N10_INPUT='cc893fcd88ae42355b04e4a07502968e0f6a0c3e0b26467c03e803e0bd6669a5';
function n10_need(bool $x,string $w):void{if(!$x)throw new RuntimeException($w);}
function n10_write(string $p,array $v):string{$raw=json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n";$f=fopen($p,'xb');n10_need(is_resource($f),'open');fwrite($f,$raw);fflush($f);if(function_exists('fsync'))fsync($f);fclose($f);return hash('sha256',$raw);}
function n10_rows(PDO $db,string $sql,array $p=[]):array{$s=$db->prepare($sql);$s->execute(array_values($p));return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}
function n10_star(array $h):?int{foreach(['star','starLName','category']as$k)if(isset($h[$k])&&preg_match('/([1-5])/u',(string)$h[$k],$m))return(int)$m[1];return null;}
if(in_array('--self-test',$argv??[],true)){n10_need(n10_star(['star'=>'3'])===3,'star');echo"NONMOSCOW10_CURRENT_SELFTEST_OK\n";exit(0);}
$dir=(string)getenv('MATCH_OPERATION_DIR');$root=realpath((string)getenv('ANYTOUR_ROOT'));$ip=realpath((string)getenv('MATCH_INPUT_PATH'));$cd=realpath((string)getenv('MATCH_CATALOG_DIR'));n10_need(PHP_SAPI==='cli'&&is_dir($dir)&&basename($dir)===N10_OP&&is_string($root)&&is_string($ip)&&hash_file('sha256',$ip)===N10_INPUT&&is_string($cd),'runtime');
$in=json_decode((string)file_get_contents($ip),true,128,JSON_THROW_ON_ERROR);n10_need(($in['state']??'')==='completed_read_only','input');
$direct=[];foreach((array)$in['dossiers']as$d){if(($d['state']??'')!=='direct_native_bridge')continue;n10_need(count($d['direct_bridges']??[])===1,'direct_one');$b=$d['direct_bridges'][0];$sid=(string)$b['samo_hotel_id'];$direct[$sid]=['samo_hotel_id'=>$sid,'native_anex_id'=>(string)$b['native_operator_hotel_id'],'tv_hotel_id'=>(int)$d['tv_hotel_id'],'tv_name'=>$d['hotel_name'],'country'=>$d['country'],'departure_id'=>$d['departure_id'],'departure_name'=>$d['departure_name'],'context'=>$d['context'],'provider_fact'=>$b];}n10_need(count($direct)===10,'direct10');
$facts=[];foreach(glob($cd.'/raw-catalog-*.json')?:[]as$p){$j=json_decode((string)file_get_contents($p),true,64,JSON_THROW_ON_ERROR);foreach((array)$j['HOTELS']as$h){$sid=(string)($h['id']??'');if(!isset($direct[$sid]))continue;$f=['name'=>$h['name']??($h['lName']??null),'town'=>$h['town']??null,'star'=>n10_star($h),'raw_catalog_sha256'=>hash_file('sha256',$p)];if(isset($facts[$sid])){n10_need($facts[$sid]['name']===$f['name']&&$facts[$sid]['town']===$f['town']&&$facts[$sid]['star']===$f['star'],'catalog_fact_drift_'.$sid);$facts[$sid]['raw_catalog_sha256']=array_values(array_unique(array_merge((array)$facts[$sid]['raw_catalog_sha256'],[$f['raw_catalog_sha256']])));}else{$f['raw_catalog_sha256']=[$f['raw_catalog_sha256']];$facts[$sid]=$f;}}}n10_need(count($facts)===10,'facts10');
$sources=array_keys($direct);$targets=array_values(array_map(fn($x)=>$x['tv_hotel_id'],$direct));$natives=array_values(array_map(fn($x)=>$x['native_anex_id'],$direct));$sp=implode(',',array_fill(0,10,'?'));$tp=implode(',',array_fill(0,10,'?'));$np=implode(',',array_fill(0,10,'?'));
require_once $root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION READ ONLY');
$src=n10_rows($db,"SELECT supplier_namespace,external_hotel_id,local_hotel_id,decision_status,catalog_sha256,evidence_sha256,created_at FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND external_hotel_id IN ($sp)",$sources);$occ=n10_rows($db,"SELECT supplier_namespace,external_hotel_id,local_hotel_id,decision_status FROM andromeda_hotel_identities WHERE supplier_namespace='andromeda_catalog' AND decision_status='accepted' AND local_hotel_id IN ($tp)",$targets);$hot=n10_rows($db,"SELECT id,name,country_name,region_name,subregion_name,category,is_active FROM catalog_hotels WHERE id IN ($tp)",$targets);$maps=n10_rows($db,"SELECT * FROM anex_hotel_search_mappings WHERE anex_hotel_id IN ($np) OR catalog_hotel_id IN ($tp)",array_merge($natives,$targets));$dec=n10_rows($db,"SELECT * FROM anex_hotel_decisions WHERE anex_hotel_id IN ($np) OR catalog_hotel_id IN ($tp)",array_merge($natives,$targets));$exc=n10_rows($db,"SELECT * FROM anex_review_pair_exclusions WHERE anex_hotel_id IN ($np) OR catalog_hotel_id IN ($tp)",array_merge($natives,$targets));$db->rollBack();
$srcBy=[];foreach($src as$x)$srcBy[(string)$x['external_hotel_id']]=$x;$occBy=[];foreach($occ as$x)$occBy[(int)$x['local_hotel_id']][]=$x;$hotBy=[];foreach($hot as$x)$hotBy[(int)$x['id']]=$x;$mapBy=[];foreach($maps as$x)if((int)($x['enabled']??1)===1)$mapBy[(string)$x['anex_hotel_id']][]=$x;$decP=[];foreach($dec as$x)$decP[(string)$x['anex_hotel_id'].'|'.(int)$x['catalog_hotel_id']]=true;$excP=[];foreach($exc as$x)$excP[(string)$x['anex_hotel_id'].'|'.(int)$x['catalog_hotel_id']]=true;
$rows=[];$safe=[];$counts=[];foreach($direct as$sid=>$p){$tv=$p['tv_hotel_id'];$native=$p['native_anex_id'];$cur=$srcBy[$sid]??null;$t=$hotBy[$tv]??null;$why=[];$state='candidate';if(!$t||(int)$t['is_active']!==1||(string)$t['country_name']!==$p['country'])$why[]='target_country_or_active';$ss=$facts[$sid]['star'];if($ss!==null&&$t&&(int)$t['category']!==$ss)$why[]='category_mismatch';$mm=$mapBy[$native]??[];$exact=array_values(array_filter($mm,fn($x)=>(int)$x['catalog_hotel_id']===$tv));if(count($mm)!==1||count($exact)!==1)$why[]='anex_mapping_not_unique_exact';$pair=$native.'|'.$tv;if(isset($decP[$pair]))$why[]='anex_decision';if(isset($excP[$pair]))$why[]='anex_exclusion';if(array_filter($occBy[$tv]??[],fn($x)=>(string)$x['external_hotel_id']!==$sid))$why[]='target_occupied_other_samo';if($cur!==null){if($cur['decision_status']==='accepted'&&(int)$cur['local_hotel_id']===$tv)$state='already_accepted';elseif($cur['decision_status']==='accepted')$why[]='source_accepted_other_target';elseif(!($cur['decision_status']==='pending'&&$cur['local_hotel_id']===null))$why[]='source_existing_protected_state';}if($state!=='already_accepted')$state=$why?'hold':'safe_candidate';$counts[$state]=($counts[$state]??0)+1;$row=['proof'=>$p,'source_catalog'=>$facts[$sid],'current_source'=>$cur,'target'=>$t,'target_occupants'=>$occBy[$tv]??[],'current_anex_mapping'=>$exact,'hold_reasons'=>$why,'state'=>$state,'safe_to_write_now'=>false];$rows[]=$row;if($state==='safe_candidate')$safe[]=['samo_hotel_id'=>$sid,'native_anex_id'=>$native,'tv_hotel_id'=>$tv];}
$out=['operation'=>N10_OP,'state'=>'completed_read_only','provider_calls'=>0,'database_writes'=>0,'mapping_writes'=>0,'input_direct10'=>10,'state_counts'=>$counts,'safe_candidate_count'=>count($safe),'safe_candidates'=>$safe,'rows'=>$rows,'input_result_sha256'=>N10_INPUT];$rh=n10_write($dir.'/result.json',$out);n10_write($dir.'/receipt.json',['operation'=>N10_OP,'state'=>'completed_read_only','result_sha256'=>$rh,'provider_calls'=>0,'database_writes'=>0,'mapping_writes'=>0]);echo json_encode(['state'=>'completed_read_only','state_counts'=>$counts,'safe_candidate_count'=>count($safe)],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";
