<?php
declare(strict_types=1);error_reporting(0);ob_start();
const OP='hotel-match-core8-current-bulk-reconcile-1971-20260912-v2';
function nt($v):string{$s=mb_strtolower(trim((string)$v),'UTF-8');$s=strtr($s,['ё'=>'е','é'=>'e','è'=>'e','ê'=>'e','á'=>'a','à'=>'a','ä'=>'a','â'=>'a','ö'=>'o','ô'=>'o','ü'=>'u','ú'=>'u','ç'=>'c','ş'=>'s','ğ'=>'g','ı'=>'i','&'=>' and ']);preg_match_all('/[\p{L}\p{N}]+/u',$s,$m);$drop=['hotel','hotels','resort','resorts','spa','otel','отель','отели','гостиница','the','by'];return implode(' ',array_values(array_filter($m[0]??[],static fn($x)=>$x!==''&&!in_array($x,$drop,true))));}
function vars($v):array{$s=trim((string)$v);if($s==='')return[];$a=[$s];if(preg_match_all('/\(\s*(?:ex|ех)\s*\.?\s*([^)]{2,180})\)/iu',$s,$m))foreach($m[1]as$x)$a[]=trim((string)$x);$z=preg_replace('/\s*\(\s*(?:ex|ех)\s*\.?\s*[^)]{2,180}\)\s*/iu',' ',$s);if(is_string($z)&&trim($z)!=='')$a[]=trim($z);$o=[];foreach($a as$x){$n=nt($x);if($n!==''&&mb_strlen($n,'UTF-8')>=3)$o[$n]=true;}return array_keys($o);}
function coord(array$r):?array{$lat=$lon=null;foreach(['latitude','lat','geo_lat','hotel_latitude','coord_lat']as$k)if(isset($r[$k])&&is_numeric($r[$k])){$lat=(float)$r[$k];break;}foreach(['longitude','lon','lng','geo_lon','hotel_longitude','coord_lon']as$k)if(isset($r[$k])&&is_numeric($r[$k])){$lon=(float)$r[$k];break;}return $lat!==null&&$lon!==null?[$lat,$lon]:null;}
function km(array$a,array$b):float{$r=6371.0;$p1=deg2rad($a[0]);$p2=deg2rad($b[0]);$dp=deg2rad($b[0]-$a[0]);$dl=deg2rad($b[1]-$a[1]);$q=sin($dp/2)**2+cos($p1)*cos($p2)*sin($dl/2)**2;return 2*$r*asin(min(1,sqrt($q)));}
function countryClass($v):?string{$n=nt($v);$m=['egypt'=>['египет','egypt'],'turkey'=>['турция','turkey','türkiye','turkiye'],'thailand'=>['таиланд','thailand'],'uae'=>['оаэ','объединенные арабские эмираты','united arab emirates','uae'],'vietnam'=>['вьетнам','vietnam'],'srilanka'=>['шри ланка','sri lanka'],'maldives'=>['мальдивы','maldives'],'cuba'=>['куба','cuba']];foreach($m as$c=>$xs)foreach($xs as$x){$q=nt($x);if($n===$q||str_contains($n,$q))return$c;}return null;}
function providerCountry(array$a):array{$keys=['api_country','api_country_name','country_name','country','api_state_name','state_name','api_state','state','destination_country','destination_name'];foreach($keys as$k)if(array_key_exists($k,$a)&&trim((string)$a[$k])!=='')return[$k,trim((string)$a[$k]),countryClass($a[$k])];return[null,null,null];}
function geoTokens($v):array{$s=nt($v);$map=['стамбул'=>'istanbul','istanbul'=>'istanbul','анталия'=>'antalya','antalya'=>'antalya','кемер'=>'kemer','kemer'=>'kemer','аланья'=>'alanya','alanya'=>'alanya','сиде'=>'side','side'=>'side','белек'=>'belek','belek'=>'belek','лалели'=>'laleli','laleli'=>'laleli','фатих'=>'fatih','fatih'=>'fatih','султанахмет'=>'sultanahmet','sultanahmet'=>'sultanahmet','таксим'=>'taksim','taksim'=>'taksim','хургада'=>'hurghada','hurghada'=>'hurghada','шарм'=>'sharm','sharm'=>'sharm','сома'=>'soma','soma'=>'soma','сафага'=>'safaga','safaga'=>'safaga','набк'=>'nabq','nabq'=>'nabq','дубай'=>'dubai','dubai'=>'dubai','фуджейра'=>'fujairah','fujairah'=>'fujairah','пхукет'=>'phuket','phuket'=>'phuket','паттайя'=>'pattaya','pattaya'=>'pattaya','фукуок'=>'phuquoc','phu quoc'=>'phuquoc','нячанг'=>'nhatrang','nha trang'=>'nhatrang','дананг'=>'danang','da nang'=>'danang','хошимин'=>'hochiminh','ho chi minh'=>'hochiminh','берувела'=>'beruwala','beruwala'=>'beruwala','бентота'=>'bentota','bentota'=>'bentota','хиккадува'=>'hikkaduwa','hikkaduwa'=>'hikkaduwa','гавана'=>'havana','havana'=>'havana','каир'=>'cairo','cairo'=>'cairo'];$o=[];foreach($map as$k=>$c)if(str_contains($s,nt($k)))$o[$c]=true;return array_keys($o);}
function geoScore(array$a,array$h):int{$s=geoTokens(((string)($a['api_region']??$a['region_name']??'')).' '.((string)($a['api_town']??$a['town_name']??'')));$t=geoTokens(((string)($h['region_name']??'')).' '.((string)($h['subregion_name']??'')));return count(array_intersect($s,$t));}
function meaningful($n):int{return count(array_filter(explode(' ',nt($n)),static fn($x)=>mb_strlen($x,'UTF-8')>=3));}
$pdo=null;try{$root=realpath(getcwd());if(!$root||basename($root)!=='anytoour.ru')throw new RuntimeException('root');$db=is_file($root.'/data/db-v1.php')?$root.'/data/db-v1.php':$root.'/v2/data/db-v1.php';require_once$db;$pdo=v2_data_db();$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->exec('START TRANSACTION READ ONLY');
$hot=[];$byName=[];$countryCounts=[];foreach($pdo->query('SELECT * FROM catalog_hotels WHERE is_active=1')->fetchAll(PDO::FETCH_ASSOC)as$h){$cc=countryClass($h['country_name']??'');if($cc===null)continue;$id=(int)$h['id'];$h['_cc']=$cc;$hot[$id]=$h;$countryCounts[$cc]=($countryCounts[$cc]??0)+1;foreach(vars($h['name']??'')as$n)$byName[$n][$id]=true;}foreach($pdo->query('SELECT hotel_id,alias FROM hotel_aliases')->fetchAll(PDO::FETCH_ASSOC)as$x){$id=(int)$x['hotel_id'];if(!isset($hot[$id]))continue;foreach(vars($x['alias']??'')as$n)$byName[$n][$id]=true;}
$mapped=[];foreach($pdo->query('SELECT DISTINCT anex_hotel_id FROM anex_hotel_search_mappings')->fetchAll(PDO::FETCH_COLUMN)as$x)$mapped[(int)$x]=1;$dec=[];foreach($pdo->query('SELECT DISTINCT anex_hotel_id FROM anex_hotel_decisions')->fetchAll(PDO::FETCH_COLUMN)as$x)$dec[(int)$x]=1;$ex=[];foreach($pdo->query('SELECT DISTINCT anex_hotel_id FROM anex_review_pair_exclusions')->fetchAll(PDO::FETCH_COLUMN)as$x)$ex[(int)$x]=1;
$bridge=[];foreach($pdo->query("SELECT local_hotel_id,COUNT(*) c FROM andromeda_hotel_identities WHERE decision_status='accepted' AND local_hotel_id IS NOT NULL GROUP BY local_hotel_id")->fetchAll(PDO::FETCH_ASSOC)as$x)$bridge[(int)$x['local_hotel_id']]=(int)$x['c'];
$all=$pdo->query('SELECT * FROM anex_hotels')->fetchAll(PDO::FETCH_ASSOC);$columns=$all?array_keys($all[0]):[];$fieldUsage=[];$safe=[];$counts=['protected'=>0,'known_noncore_provider'=>0,'provider_country_mismatch'=>0,'no_exact'=>0,'coord_blocked'=>0,'ambiguous'=>0,'needs_extra'=>0];$reasons=[];
foreach($all as$a){$aid=(int)($a['anex_hotel_id']??0);if($aid<=0)continue;if(isset($mapped[$aid])||isset($dec[$aid])||isset($ex[$aid])){$counts['protected']++;continue;}[$cf,$cr,$cc]=providerCountry($a);if($cf!==null)$fieldUsage[$cf]=($fieldUsage[$cf]??0)+1;if($cr!==null&&$cc===null){$counts['known_noncore_provider']++;continue;}$name=(string)($a['api_name']??$a['name']??'');$ids=[];$matched=[];foreach(vars($name)as$n)foreach(array_keys($byName[$n]??[])as$id){$ids[(int)$id]=1;$matched[(int)$id][]=$n;}if(!$ids){$counts['no_exact']++;continue;}$ac=coord($a);$eval=[];foreach(array_keys($ids)as$id){$h=$hot[$id];if($cc!==null&&$h['_cc']!==$cc){$counts['provider_country_mismatch']++;continue;}$hc=coord($h);$dist=($ac&&$hc)?km($ac,$hc):null;if($dist!==null&&$dist>5){$counts['coord_blocked']++;continue;}$geo=geoScore($a,$h);$uniqName=count(array_keys($byName[($matched[$id][0]??'')]??[]));$tokens=meaningful($matched[$id][0]??$name);$and=$bridge[$id]??0;$score=0;if($dist!==null&&$dist<=0.25)$score+=120;elseif($dist!==null&&$dist<=1)$score+=100;elseif($dist!==null&&$dist<=5)$score+=20;if($cc!==null&&$h['_cc']===$cc)$score+=45;if($geo>=2)$score+=60;elseif($geo===1)$score+=35;if($and>0)$score+=10;if($uniqName===1)$score+=15;$eval[]=['id'=>$id,'h'=>$h,'dist'=>$dist,'geo'=>$geo,'cc'=>$cc,'country_raw'=>$cr,'country_field'=>$cf,'uniqName'=>$uniqName,'tokens'=>$tokens,'and'=>$and,'score'=>$score];}
if(!$eval){$counts['needs_extra']++;continue;}usort($eval,fn($x,$y)=>$y['score']<=>$x['score'] ?: (($x['dist']??999999)<=>($y['dist']??999999)));$b=$eval[0];$s=$eval[1]??null;$margin=$b['score']-($s['score']??0);$rule=null;if($b['dist']!==null&&$b['dist']<=1)$rule='exact_alias_plus_coord';elseif($b['cc']!==null&&$b['uniqName']===1&&$b['tokens']>=2)$rule='same_country_unique_exact';elseif($b['cc']!==null&&$b['geo']>=1)$rule='same_country_exact_plus_geo';elseif($b['cc']===null&&$b['geo']>=2&&$b['uniqName']===1)$rule='strong_geo_unique_exact';if($rule===null||($s!==null&&$margin<25)){$counts['ambiguous']++;$counts['needs_extra']++;continue;}$reasons[$rule]=($reasons[$rule]??0)+1;$h=$b['h'];$safe[]=['anex_id'=>$aid,'anex_name'=>$name,'provider_country_field'=>$b['country_field'],'provider_country_raw'=>$b['country_raw'],'provider_country_class'=>$b['cc'],'api_region'=>$a['api_region']??null,'api_town'=>$a['api_town']??null,'target_local_id'=>(int)$h['id'],'target_name'=>$h['name'],'target_country'=>$h['country_name'],'target_country_class'=>$h['_cc'],'region'=>$h['region_name']??null,'subregion'=>$h['subregion_name']??null,'coordinate_distance_km'=>$b['dist']===null?null:round($b['dist'],3),'geo_score'=>$b['geo'],'unique_exact_name_count'=>$b['uniqName'],'meaningful_token_count'=>$b['tokens'],'accepted_andromeda_bridge_count'=>$b['and'],'score'=>$b['score'],'margin'=>$margin,'reason'=>$rule,'matched_normalizations'=>array_values(array_unique($matched[(int)$h['id']]??[]))];}
$pdo->exec('ROLLBACK');usort($safe,fn($a,$b)=>$b['score']<=>$a['score']);$out=['status'=>'completed','operation_id'=>OP,'anex_columns'=>$columns,'provider_country_field_usage'=>$fieldUsage,'catalog_anex_rows'=>count($all),'core8_active_hotels'=>count($hot),'core8_country_counts'=>$countryCounts,'counts'=>$counts,'safe_count'=>count($safe),'reason_counts'=>$reasons,'safe_rows'=>$safe,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true];}catch(Throwable$e){if($pdo instanceof PDO&&$pdo->inTransaction())$pdo->rollBack();$out=['status'=>'failed','operation_id'=>OP,'safe_message'=>substr($e->getMessage(),0,180),'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true];}while(ob_get_level())ob_end_clean();echo 'CORE8_BULK_V2:'.json_encode($out,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";exit(($out['status']??'')==='completed'?0:2);
