<?php
declare(strict_types=1);
const D7_OP='hotel-match-didim-tv-details-retained-1971-20260919-v1',D7_MAX=20;
function d7_need(bool $x,string $w):void{if(!$x)throw new RuntimeException($w);}
function d7_write(string $p,array $v):string{$raw=hmc_json($v)."\n";$f=@fopen($p,'x+b');d7_need(is_resource($f),'write_open');try{d7_need(fwrite($f,$raw)===strlen($raw)&&fflush($f),'write');if(function_exists('fsync'))d7_need(fsync($f),'sync');}finally{fclose($f);}return hash('sha256',$raw);}
function d7_urls(mixed $v):array{$o=[];$walk=function($x,$d=0)use(&$walk,&$o){if($d>8)return;if(is_array($x)){foreach($x as$z)$walk($z,$d+1);return;}if(!is_string($x))return;$u=hmc_url($x);if($u!==null)$o[$u]=true;};$walk($v);$x=array_keys($o);sort($x,SORT_STRING);return array_slice($x,0,80);}
function d7_shape(string $u):string{$p=parse_url($u);return is_array($p)?strtolower((string)($p['host']??'')).rtrim(strtolower((string)($p['path']??'')),'/'):'';}
function d7_ids(string $u):array{$p=parse_url($u);if(!is_array($p))return[];$o=[];foreach(preg_split('~/+~',(string)($p['path']??''),-1,PREG_SPLIT_NO_EMPTY)?:[]as$x)if(preg_match('/^[1-9][0-9]{0,31}$/D',$x))$o[$x]=true;parse_str((string)($p['query']??''),$q);foreach($q as$k=>$v){if(!preg_match('/hotel|hotellist|hotelid|hotel_id|hotelcode|f4/i',(string)$k))continue;foreach((array)$v as$z)foreach(preg_split('/[,;]+/',(string)$z)?:[]as$x){$x=trim($x);if(preg_match('/^[1-9][0-9]{0,31}$/D',$x))$o[$x]=true;}}return array_keys($o);}
function d7_name(string $s):string{return hmc_norm(preg_replace('/\b(?:hotel|resort|spa|apart|apartment)\b/iu',' ',$s)??$s);}
if(in_array('--self-test',$argv??[],true)){require_once __DIR__.'/hotel_match_operator_fingerprint_room_evidence_v1.php';require_once __DIR__.'/hotel_match_tv_samo_common4_full_drain_v1.php';d7_need(hmc_id(['id'=>43])===43,'nested_op');d7_need(d7_ids('https://x/hotel/834805')===['834805'],'path_id');echo"DIDIM_TV_DETAILS_SELFTEST_OK\n";exit(0);}
$dir=(string)getenv('MATCH_OPERATION_DIR');$root=realpath((string)getenv('ANYTOUR_ROOT'));$sha=(string)getenv('MATCH_SOURCE_SHA');d7_need(PHP_SAPI==='cli'&&is_dir($dir)&&basename($dir)===D7_OP&&is_string($root)&&preg_match('/^[a-f0-9]{40}$/D',$sha),'runtime');
$res=json_decode((string)file_get_contents($dir.'/reservation.json'),true,32,JSON_THROW_ON_ERROR);d7_need(($res['operation']??'')===D7_OP&&($res['state']??'')==='reserved_before_provider_access','reservation');
require_once $root.'/config.php';require_once $dir.'/payload/hotel_match_operator_fingerprint_room_evidence_v1.php';require_once $dir.'/payload/hotel_match_tv_samo_common4_full_drain_v1.php';require_once $dir.'/payload/tourvisor-client-v1.php';
$rp=realpath((string)getenv('MATCH_V6_RESULT'));$tp=realpath((string)getenv('MATCH_TV_RESULTS'));$op=realpath((string)getenv('MATCH_TV_OPERATORS'));
d7_need(is_string($rp)&&hash_file('sha256',$rp)==='46653546e4ae294e7e4c9e5c5c685dd21294a5fa4f867d43a261f4acab42d87b','v6_result');d7_need(is_string($tp)&&hash_file('sha256',$tp)==='316b777b31511c0c4c74109b7da7379a361c0d105945aa12ce94e01641302e13','tv_results');d7_need(is_string($op)&&hash_file('sha256',$op)==='bc1342448a088efe716961275c9ea983025403a7b7410e8aeb44344e33450e25','tv_ops');
$v6=json_decode((string)file_get_contents($rp),true,64,JSON_THROW_ON_ERROR);$tv=json_decode((string)file_get_contents($tp),true,64,JSON_THROW_ON_ERROR);$ops=json_decode((string)file_get_contents($op),true,64,JSON_THROW_ON_ERROR);d7_need(($v6['state']??'')==='completed_read_only'&&($v6['route']['resort']??'')==='Дидим','v6_state');
$map=hmc_operator_map(hmc_rows($ops,['operators','items','results']));$by=[];foreach(['anex','biblio','funsun','intourist']as$f){d7_need(isset($map['unique'][$f]),'op_'.$f);$by[(string)$map['unique'][$f]['id']]=$f;}
$pairs=[];foreach(hmc_tv_result_rows($tv)as$h){if(!is_array($h)||!($hid=hmc_id($h['id']??null)))continue;$hn=hmc_text($h['name']??'',300);foreach((array)($h['tours']??[])as$t){if(!is_array($t)||!($oid=hmc_id($t['operator']??null)))continue;$family=$by[(string)$oid]??null;$tid=hmc_text($t['id']??($t['tourId']??''),220);if($family===null||$tid==='')continue;$k=$hid.'|'.$family;if(!isset($pairs[$k]))$pairs[$k]=['tv_hotel_id'=>(string)$hid,'hotel_name'=>$hn,'operator_family'=>$family,'tv_operator_id'=>(string)$oid,'tour_id'=>$tid];}}
$pairs=array_values($pairs);d7_need(count($pairs)>0&&count($pairs)<=D7_MAX,'pair_count');
$calls=0;$manifest=[];$details=[];foreach($pairs as$i=>$p){d7_need(++$calls<=D7_MAX,'detail_cap');$d=v2_data_tv_get('/tours/'.rawurlencode($p['tour_id']),['currency'=>'RUB']);$name='raw-tv-detail-'.($i+1).'.json';$manifest[]=['file'=>$name,'sha256'=>d7_write($dir.'/'.$name,$d),'bytes'=>filesize($dir.'/'.$name)];$urls=d7_urls($d);$ids=[];foreach($urls as$u)foreach(d7_ids($u)as$x)$ids[$x]=true;$details[]=$p+['detail_urls'=>$urls,'operator_link_native_ids'=>array_keys($ids)];}
$join=[];foreach((array)$v6['samo_live']as$s){$cand=[];foreach($details as$d){if(($s['operator_family']??'')!==$d['operator_family'])continue;$ev=[];$native=(string)($s['native_operator_hotel_id']??'');if($native!==''&&in_array($native,$d['operator_link_native_ids'],true))$ev[]='native_id_in_operator_link';$ss=array_filter(array_map('d7_shape',(array)($s['urls']??[])));$ds=array_filter(array_map('d7_shape',$d['detail_urls']));if(array_intersect($ss,$ds))$ev[]='same_operator_url_path';if(!$ev&&d7_name((string)$s['hotel_name'])===d7_name($d['hotel_name']))$ev[]='exact_name_only';if($ev)$cand[]=['tv_hotel_id'=>$d['tv_hotel_id'],'tv_hotel_name'=>$d['hotel_name'],'tour_id'=>$d['tour_id'],'evidence'=>$ev,'detail_urls'=>$d['detail_urls']];}$strong=array_values(array_filter($cand,fn($x)=>in_array('native_id_in_operator_link',$x['evidence'],true)||in_array('same_operator_url_path',$x['evidence'],true)));$state=count($strong)===1?'direct_identity_candidate':(count($strong)>1?'ambiguous_direct_identity':($cand?'name_candidate_only':'no_tv_candidate'));$join[]=['samo_hotel_id'=>$s['samo_hotel_id'],'samo_hotel_name'=>$s['hotel_name'],'operator_family'=>$s['operator_family'],'native_operator_hotel_id'=>$s['native_operator_hotel_id'],'state'=>$state,'candidates'=>$strong?:$cand,'safe_to_write_now'=>false];}
$counts=[];foreach($join as$j)$counts[$j['state']]=($counts[$j['state']]??0)+1;$mh=d7_write($dir.'/raw-manifest.json',['files'=>$manifest]);$out=['operation'=>D7_OP,'state'=>'completed_read_only','source_v6_result_sha256'=>'46653546e4ae294e7e4c9e5c5c685dd21294a5fa4f867d43a261f4acab42d87b','tourvisor_search_calls'=>0,'tourvisor_detail_calls'=>$calls,'pair_count'=>count($pairs),'details'=>$details,'join_state_counts'=>$counts,'join'=>$join,'raw_manifest_sha256'=>$mh,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true];$rh=d7_write($dir.'/result.json',$out);d7_write($dir.'/receipt.json',['operation'=>D7_OP,'state'=>'completed_read_only','result_sha256'=>$rh,'tourvisor_search_calls'=>0,'tourvisor_detail_calls'=>$calls,'raw_manifest_sha256'=>$mh,'database_writes'=>0,'mapping_writes'=>0,'no_replay'=>true]);echo hmc_json(['state'=>'completed_read_only','pairs'=>count($pairs),'detail_calls'=>$calls,'join_state_counts'=>$counts])."\n";
