<?php
declare(strict_types=1);
/** MATCH #1971: CURRENT read-only reconciliation of completed Turkey-A Biblio f4 evidence. */
const HMTA_OP='hotel-match-tv-multiop-turkey-a-native-reconcile-1971-20260916-v1';
const HMTA_ROWS=[
 ['provider'=>'Biblioglobus','tv_operator_id'=>18,'local'=>2160,'anex'=>10115,'kind'=>'f4','values'=>['102616635295']],
 ['provider'=>'Biblioglobus','tv_operator_id'=>18,'local'=>996,'anex'=>11756,'kind'=>'f4','values'=>['102618352274']],
 ['provider'=>'Biblioglobus','tv_operator_id'=>18,'local'=>5535,'anex'=>14812,'kind'=>'f4','values'=>['102610091672']],
];
function j(array $v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
function putnew(string $p,array $v):string{$raw=j($v)."\n";$f=@fopen($p,'x');if(!$f)throw new RuntimeException('durable_create_failed');try{if(fwrite($f,$raw)!==strlen($raw))throw new RuntimeException('durable_write_failed');fflush($f);}finally{fclose($f);}if(file_get_contents($p)!==$raw)throw new RuntimeException('durable_readback_failed');return hash('sha256',$raw);}
function dbpath(string $r):string{foreach([$r.'/data/db-v1.php',$r.'/v2/data/db-v1.php'] as $p)if(is_file($p))return $p;throw new RuntimeException('db_bootstrap_missing');}
function sel(PDO $d,string $q,array $p=[]):array{$s=$d->prepare($q);$s->execute($p);return $s->fetchAll(PDO::FETCH_ASSOC);}
function norm($v):string{$s=mb_strtolower(trim((string)$v),'UTF-8');$s=preg_replace('/\b(?:hotel|resort|spa)\b/iu',' ',$s)??$s;$s=preg_replace('/[^\pL\pN]+/u',' ',$s)??$s;return trim(preg_replace('/\s+/u',' ',$s)??$s);}
function variants(array $r):array{$o=[];foreach($r['values'] as $v){$v=(string)$v;$o[]=['variant'=>'raw','value'=>$v];if($r['provider']==='Biblioglobus'&&preg_match('/^102([1-9][0-9]{8})$/D',$v,$m))$o[]=['variant'=>'strip_102_prefix','value'=>$m[1]];}return $o;}
function pick(array $r,array $ks):array{$o=[];foreach($ks as $k)if(array_key_exists($k,$r))$o[$k]=$r[$k];return $o;}
if(in_array('--self-test',$argv??[],true)){if((variants(['provider'=>'Biblioglobus','values'=>['102616635295']])[1]['value']??'')!=='616635295')throw new RuntimeException('suffix_test');if(norm('ELYSEE RIVE HOTEL & SPA')!=='elysee rive')throw new RuntimeException('norm_test');echo "PASS\n";exit(0);}
$op=(string)getenv('OPERATION_ID');$sha=(string)getenv('MATCH_SOURCE_SHA');if($op!==HMTA_OP||!preg_match('/^[0-9a-f]{40}$/D',$sha))throw new RuntimeException('operation_guard');$root=(string)realpath(getcwd());if($root===''||basename($root)!=='anytoour.ru')throw new RuntimeException('root_guard');$base=rtrim((string)getenv('HOME'),'/').'/.anytoour-match/operations';if(!is_dir($base))throw new RuntimeException('operations_root_missing');$dir=$base.'/'.$op;if(!mkdir($dir,0700))throw new RuntimeException('operation_exists');putnew($dir.'/reservation.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'reserved_before_db_access','read_only'=>true,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);
$db=null;try{require_once dbpath($root);$db=v2_data_db();$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->exec('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');
$catalog=[];foreach(sel($db,'SELECT id,country_id,name,region_name,subregion_name FROM catalog_hotels WHERE id IN (2160,996,5535)') as $r)$catalog[(int)$r['id']]=$r;
$mapped=[];foreach(sel($db,'SELECT anex_hotel_id,catalog_hotel_id FROM anex_hotel_search_mappings WHERE anex_hotel_id IN (10115,11756,14812)') as $r)$mapped[(int)$r['anex_hotel_id']]=(int)$r['catalog_hotel_id'];
$manual=[];foreach(sel($db,'SELECT anex_hotel_id FROM anex_hotel_decisions WHERE anex_hotel_id IN (10115,11756,14812)') as $r)$manual[(int)$r['anex_hotel_id']]=true;
$ex=[];foreach(sel($db,'SELECT anex_hotel_id,catalog_hotel_id FROM anex_review_pair_exclusions WHERE anex_hotel_id IN (10115,11756,14812)') as $r)$ex[(int)$r['anex_hotel_id']][(int)$r['catalog_hotel_id']]=true;
$vals=[];foreach(HMTA_ROWS as $r)foreach(variants($r) as $v)$vals[$v['value']]=true;$vals=array_keys($vals);$ph=implode(',',array_fill(0,count($vals),'?'));
$hits=sel($db,"SELECT * FROM andromeda_hotel_identities WHERE supplier_namespace LIKE 'operator\\_%' AND external_hotel_id IN ($ph) ORDER BY supplier_namespace,external_hotel_id",$vals);$db->exec('ROLLBACK');
$by=[];foreach($hits as $h)$by[(string)$h['external_hotel_id']][]=$h;$out=[];$cert=[];
foreach(HMTA_ROWS as $r){$local=(int)$r['local'];$aid=(int)$r['anex'];$c=$catalog[$local]??[];$row=['provider'=>$r['provider'],'tv_operator_id'=>$r['tv_operator_id'],'link_field'=>$r['kind'],'local_hotel_id'=>$local,'local_hotel_name'=>$c['name']??null,'country_id'=>isset($c['country_id'])?(int)$c['country_id']:null,'region_name'=>$c['region_name']??null,'subregion_name'=>$c['subregion_name']??null,'source_anex_id'=>$aid,'source_current'=>['mapped_local_id'=>$mapped[$aid]??null,'manual_protected'=>isset($manual[$aid]),'pair_excluded'=>isset($ex[$aid][$local])],'variants'=>[],'route'=>'no_registry_hit'];$same=[];$diff=[];$pending=[];
foreach(variants($r) as $v){$vr=$v+['registry_hits'=>[]];foreach($by[$v['value']]??[] as $h){$sl=$h['local_hotel_id']===null?null:(int)$h['local_hotel_id'];$status=(string)($h['decision_status']??'');$name='';foreach(['api_name','hotel_name','name','xml_name','source_name'] as $nk)if(isset($h[$nk])&&trim((string)$h[$nk])!==''){$name=(string)$h[$nk];break;}$hit=pick($h,['supplier_namespace','external_hotel_id','local_hotel_id','decision_status','country_id','api_name','hotel_name','name','xml_name','region_name','subregion_name']);$hit['source_name_best']=$name;$hit['normalized_name_match']=$name!==''&&isset($c['name'])&&norm($name)===norm($c['name']);$vr['registry_hits'][]=$hit;if($sl===$local&&$status==='accepted')$same[]=['variant'=>$v['variant'],'value'=>$v['value'],'namespace'=>$h['supplier_namespace'],'name_match'=>$hit['normalized_name_match']];elseif($sl===null)$pending[]=['variant'=>$v['variant'],'value'=>$v['value'],'namespace'=>$h['supplier_namespace'],'status'=>$status,'name_match'=>$hit['normalized_name_match']];else$diff[]=['variant'=>$v['variant'],'value'=>$v['value'],'namespace'=>$h['supplier_namespace'],'status'=>$status,'local_hotel_id'=>$sl,'name_match'=>$hit['normalized_name_match']];}$row['variants'][]=$vr;}
if(isset($mapped[$aid]))$row['route']=$mapped[$aid]===$local?'source_already_mapped_same':'source_mapping_conflict';elseif(isset($manual[$aid]))$row['route']='source_manual_hold';elseif(isset($ex[$aid][$local]))$row['route']='source_pair_excluded';elseif(count($same)===1&&count($diff)===0)$row['route']='cross_provider_same_local_accepted';elseif(count($same)>0)$row['route']='cross_provider_same_local_ambiguous';elseif(count($pending)>0&&count($diff)===0)$row['route']='registry_pending_candidate';elseif(count($diff)>0)$row['route']='registry_different_local_hold';$row['same_local_accepted']=$same;$row['pending_hits']=$pending;$row['different_local_hits']=$diff;$out[]=$row;foreach($same as $s){$k=$s['variant'].'|'.$s['namespace'];$cert[$k]['variant']=$s['variant'];$cert[$k]['namespace']=$s['namespace'];$cert[$k]['same_local_accepted_count']=($cert[$k]['same_local_accepted_count']??0)+1;$cert[$k]['locals'][$local]=true;$cert[$k]['name_matches']=($cert[$k]['name_matches']??0)+($s['name_match']?1:0);}}
$certOut=[];foreach($cert as $x){$x['distinct_local_count']=count($x['locals']??[]);unset($x['locals']);$x['strong_transform_evidence']=$x['distinct_local_count']>=2;$certOut[]=$x;}$counts=[];foreach($out as $r)$counts[$r['route']]=($counts[$r['route']]??0)+1;ksort($counts);$prepared=array_values(array_filter($out,fn($r)=>$r['route']==='cross_provider_same_local_accepted'));
$result=['schema'=>'hotel-match-tv-multiop-turkey-a-native-reconcile/1','operation_id'=>$op,'source_sha'=>$sha,'state'=>'completed_read_only','source_evidence_run'=>35072117847,'source_result_sha256'=>'488d796ccb70dd8e62f18a667990684746029cef4fd26b871e72e0fb16e52485','server_current'=>true,'input_rows'=>count(HMTA_ROWS),'registry_hit_rows'=>count($hits),'route_counts'=>$counts,'transform_certificates'=>$certOut,'prepared_cross_provider_count'=>count($prepared),'prepared_cross_provider'=>$prepared,'rows'=>$out,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'booking_calls'=>0,'lead_calls'=>0,'safe_to_write_now'=>false,'no_replay'=>true];$digest=putnew($dir.'/result.json',$result);putnew($dir.'/receipt.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'completed_read_only','result_sha256'=>$digest,'readback_verified'=>hash('sha256',(string)file_get_contents($dir.'/result.json'))===$digest,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);echo j(['state'=>'completed_read_only','registry_hit_rows'=>count($hits),'route_counts'=>$counts,'prepared_cross_provider_count'=>count($prepared)])."\n";
}catch(Throwable $e){if($db instanceof PDO&&$db->inTransaction())$db->rollBack();$f=['operation_id'=>$op,'source_sha'=>$sha,'state'=>'failed_read_only','error_class'=>get_class($e),'error_sha256'=>hash('sha256',$e->getMessage()),'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true];$digest=putnew($dir.'/failure.json',$f);putnew($dir.'/receipt.json',['operation_id'=>$op,'source_sha'=>$sha,'state'=>'failed_read_only','failure_sha256'=>$digest,'readback_verified'=>true,'database_writes'=>0,'mapping_writes'=>0,'supplier_calls'=>0,'tourvisor_calls'=>0,'no_replay'=>true]);fwrite(STDERR,"HMTA_FAILED\n");exit(2);}
