<?php
declare(strict_types=1);
const LAC_OPERATION='int-andromeda-local-profile-acquire-4191-source320-20261001-v1';
const LAC_PLAN_OPERATION='int-andromeda-local-profile-plan-4191-20261001-v2';
const LAC_PLAN_SHA='a2306ab97e596b5df3d3eb54e85948c0e69a29237a9e96d697017db1cd902988';
const LAC_BATCH='local4191-source320-20261001';
const LAC_INTERVAL_MS=550;
function lac_need(bool $v,string $r):void{if(!$v)throw new RuntimeException($r);}
function lac_file(string $p,int $max):string{$b=is_file($p)&&!is_link($p)&&realpath($p)===$p&&filesize($p)>0&&filesize($p)<=$max?file_get_contents($p):false;lac_need(is_string($b),'private_file');return $b;}
function lac_json(array $v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
function lac_save(string $p,array $v):void{$b=lac_json($v)."\n";lac_need(!file_exists($p)&&!is_link($p)&&strlen($b)<=65536,'private_output');$f=fopen($p,'x');lac_need(is_resource($f),'private_output');try{lac_need(chmod($p,0600)&&fwrite($f,$b)===strlen($b)&&fflush($f),'private_output');if(function_exists('fsync'))lac_need(fsync($f),'private_flush');}finally{fclose($f);}}
function lac_scope(array $p):array{
 lac_need(($p['schema_version']??null)===1&&($p['operation_id']??null)===LAC_PLAN_OPERATION&&is_array($p['rows']??null)&&count($p['rows'])===366,'plan_contract');
 $counts=[];$scope=[];$seen=[];
 foreach($p['rows'] as $r){lac_need(is_array($r)&&is_int($r['anytourHotelId']??null)&&$r['anytourHotelId']>0&&is_string($r['state']??null)&&!isset($seen[$r['anytourHotelId']]),'plan_row');$seen[$r['anytourHotelId']]=1;$s=$r['state'];$counts[$s]=($counts[$s]??0)+1;if($s!=='SOURCE_MISSING')continue;
  $own=$r['anytourHotelId'];$local=$r['localHotelId']??null;lac_need(is_int($local)&&$local>0&&is_string($r['expectedProfileSha256']??null)&&preg_match('/^[a-f0-9]{64}$/D',$r['expectedProfileSha256'])===1&&is_int($r['expectedRevision']??null)&&$r['expectedRevision']>=1&&is_string($r['expectedAliasSha256']??null)&&preg_match('/^[a-f0-9]{64}$/D',$r['expectedAliasSha256'])===1,'source_row');
  $scope[$own]=['own'=>$own,'local'=>$local,'profileSha'=>$r['expectedProfileSha256'],'revision'=>$r['expectedRevision'],'aliasSha'=>$r['expectedAliasSha256']];
 }
 ksort($counts);lac_need($counts===['D1_OVERLAP_HELD'=>10,'RETAINED_DELTA_PREPARED'=>36,'SOURCE_MISSING'=>320]&&count($scope)===320,'plan_counts');ksort($scope,SORT_NUMERIC);return $scope;
}
function lac_preflight(PDO $db,array $scope):void{
 $ids=array_keys($scope);$marks=implode(',',array_fill(0,count($ids),'?'));$q=$db->prepare("SELECT h.id,h.profile_sha256,h.revision,h.is_active,s.external_key,s.source_sha256,s.acquired_via FROM anytour_hotels h JOIN anytour_hotel_sources s ON s.anytour_hotel_id=h.id AND s.namespace='anytour_local_id' WHERE h.id IN ($marks) ORDER BY h.id");$q->execute($ids);$rows=$q->fetchAll(PDO::FETCH_ASSOC);lac_need(count($rows)===320,'current_scope');
 foreach($rows as $r){$own=(int)$r['id'];$e=$scope[$own]??null;lac_need(is_array($e)&&(int)$r['is_active']===1&&(int)$r['external_key']===$e['local']&&(int)$r['revision']===$e['revision']&&hash_equals($e['profileSha'],(string)$r['profile_sha256'])&&($r['acquired_via']??null)==='canonical_local_alias_v1'&&hash_equals($e['aliasSha'],(string)$r['source_sha256']),'current_drift');}
}
function lac_main(array $argv):int{
 lac_need(PHP_SAPI==='cli'&&$argv===[(string)($argv[0]??''),'--acquire-source320'],'disabled');
 $home=(string)getenv('HOME');$root=(string)getenv('ANYTOUR_ROOT');$dir=(string)getenv('LOCAL_PROFILE_ACQUIRE_DIR');$head=(string)getenv('LOCAL_PROFILE_SOURCE_SHA');$control=(string)getenv('LOCAL_PROFILE_CONTROL_SHA');
 lac_need($root===$home.'/www/anytoour.ru'&&realpath($root)===$root&&realpath($dir)===$dir&&dirname($dir)===$home.'/.anytoour-int-executor'&&basename($dir)===LAC_OPERATION&&preg_match('/^[a-f0-9]{40}$/D',$head)===1&&preg_match('/^[a-f0-9]{40}$/D',$control)===1,'runtime_scope');
 $reservation=json_decode(lac_file($dir.'/reservation.json',65536),true,32,JSON_THROW_ON_ERROR);lac_need(($reservation['operation_id']??null)===LAC_OPERATION&&($reservation['source_sha']??null)===$head&&($reservation['mode']??null)==='local-profile-acquire-4191','reservation');lac_need(!file_exists($dir.'/local-acquire-receipt.json'),'no_replay');
 $planPath=$home.'/.anytoour-int-executor/'.LAC_PLAN_OPERATION.'/local-plan.json';$bytes=lac_file($planPath,32*1024*1024);lac_need(hash_equals(LAC_PLAN_SHA,hash('sha256',$bytes)),'plan_digest');$private=json_decode($bytes,true,512,JSON_THROW_ON_ERROR);lac_need(is_array($private),'plan_json');$scope=lac_scope($private);
 $bootstrap=$root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');lac_need(is_file($bootstrap)&&!is_link($bootstrap)&&realpath($bootstrap)===$bootstrap,'bootstrap');if(is_file($root.'/config.php'))require_once $root.'/config.php';$_SERVER['DOCUMENT_ROOT']=$root;require_once $bootstrap;require_once dirname(__DIR__,2).'/v2/data/tourvisor-client-v1.php';require_once dirname(__DIR__,2).'/v2/data/hotel-details-v1.php';
 putenv('TOURVISOR_HTTP_MAX_ATTEMPTS=1');$db=v2_data_db();lac_need($db->getAttribute(PDO::ATTR_DRIVER_NAME)==='mysql','mysql_required');lac_preflight($db,$scope);
 $save=$db->prepare("INSERT INTO catalog_hotel_details (hotel_id,status,source_hash,country_id,region_id,subregion_id,name,category,rating,hotel_type,description,address,place,phone,site,build_info,repair_info,square_info,latitude,longitude,primary_image_url,images_json,infrastructure_json,meals_json,services_json,room_types,raw_json,fetched_at,last_error) VALUES (:hotel_id,'success',:source_hash,:country_id,:region_id,:subregion_id,:name,:category,:rating,:hotel_type,:description,:address,:place,:phone,:site,:build_info,:repair_info,:square_info,:latitude,:longitude,:primary_image_url,:images_json,:infrastructure_json,:meals_json,:services_json,:room_types,:raw_json,:fetched_at,NULL) ON DUPLICATE KEY UPDATE status='success',source_hash=VALUES(source_hash),country_id=VALUES(country_id),region_id=VALUES(region_id),subregion_id=VALUES(subregion_id),name=VALUES(name),category=VALUES(category),rating=VALUES(rating),hotel_type=VALUES(hotel_type),description=VALUES(description),address=VALUES(address),place=VALUES(place),phone=VALUES(phone),site=VALUES(site),build_info=VALUES(build_info),repair_info=VALUES(repair_info),square_info=VALUES(square_info),latitude=VALUES(latitude),longitude=VALUES(longitude),primary_image_url=VALUES(primary_image_url),images_json=VALUES(images_json),infrastructure_json=VALUES(infrastructure_json),meals_json=VALUES(meals_json),services_json=VALUES(services_json),room_types=VALUES(room_types),raw_json=VALUES(raw_json),fetched_at=VALUES(fetched_at),last_error=NULL");
 $up=$db->prepare("UPDATE catalog_hotels SET country_id=COALESCE(:country_id,country_id),country_name=COALESCE(:country_name,country_name),region_id=COALESCE(:region_id,region_id),region_name=COALESCE(:region_name,region_name),subregion_id=COALESCE(:subregion_id,subregion_id),subregion_name=COALESCE(:subregion_name,subregion_name),name=COALESCE(:name,name),normalized_name=COALESCE(:normalized_name,normalized_name),search_key=COALESCE(:search_key,search_key),category=COALESCE(:category,category),rating=COALESCE(:rating,rating),hotel_type=COALESCE(:hotel_type,hotel_type),latitude=COALESCE(:latitude,latitude),longitude=COALESCE(:longitude,longitude),primary_image_url=COALESCE(:primary_image_url,primary_image_url),image_updated_at=IF(:primary_image_url_2 IS NOT NULL,:fetched_at,image_updated_at),last_seen_at=GREATEST(last_seen_at,:fetched_at),synced_at=:fetched_at,is_active=1 WHERE id=:hotel_id");
 $ins=$db->prepare("INSERT INTO catalog_hotels (id,country_id,country_name,region_id,region_name,subregion_id,subregion_name,name,normalized_name,search_key,slug,category,rating,hotel_type,latitude,longitude,primary_image_url,image_updated_at,is_active,first_seen_at,last_seen_at,synced_at) VALUES (:hotel_id,:country_id,:country_name,:region_id,:region_name,:subregion_id,:subregion_name,:name,:normalized_name,:search_key,NULL,:category,:rating,:hotel_type,:latitude,:longitude,:primary_image_url,:fetched_at,1,:fetched_at,:fetched_at,:fetched_at)");
 $fail=$db->prepare("INSERT INTO catalog_hotel_details (hotel_id,status,fetched_at,last_error) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE status=VALUES(status),fetched_at=VALUES(fetched_at),last_error=VALUES(last_error)");
 $success=$notFound=$failed=$catalogInserted=$detailWrites=0;$last=0.0;
 foreach($scope as $e){$elapsed=(microtime(true)-$last)*1000;if($last>0&&$elapsed<LAC_INTERVAL_MS)usleep((int)((LAC_INTERVAL_MS-$elapsed)*1000));$last=microtime(true);$id=$e['local'];$now=gmdate('Y-m-d H:i:s');
  try{$payload=v2_data_tv_get('/hotels/'.$id);$hotel=v2_hotel_detail_object($payload);if($hotel===null||(int)($hotel['id']??0)!==$id)throw new RuntimeException('hotel detail payload identity mismatch');$d=v2_hotel_detail_normalized($hotel);if(($d['generic_product']??false)===true)throw new RuntimeException('generic product held');
   $raw=lac_json($hotel);$save->execute(['hotel_id'=>$id,'source_hash'=>hash('sha256',$raw),'country_id'=>$d['country_id'],'region_id'=>$d['region_id'],'subregion_id'=>$d['subregion_id'],'name'=>$d['name'],'category'=>$d['category'],'rating'=>$d['rating'],'hotel_type'=>$d['hotel_type'],'description'=>$d['description'],'address'=>$d['address'],'place'=>$d['place'],'phone'=>$d['phone'],'site'=>$d['site'],'build_info'=>$d['build'],'repair_info'=>$d['repair'],'square_info'=>$d['square'],'latitude'=>$d['latitude'],'longitude'=>$d['longitude'],'primary_image_url'=>$d['primary_image_url'],'images_json'=>$d['images_json'],'infrastructure_json'=>$d['infrastructure_json'],'meals_json'=>$d['meals_json'],'services_json'=>$d['services_json'],'room_types'=>$d['room_types'],'raw_json'=>$raw,'fetched_at'=>$now]);$detailWrites++;
   $name=$d['name'];$country=$d['country_name'];$norm=$name===null?null:mb_strtolower(preg_replace('/\s+/u',' ',trim($name))??trim($name));$search=$name===null?null:mb_strtolower(preg_replace('/\s+/u',' ',trim(implode(' ',array_filter([$name,$country,$d['region_name'],$d['subregion_name']]))))??$name);
   $args=['hotel_id'=>$id,'country_id'=>$d['country_id'],'country_name'=>$country,'region_id'=>$d['region_id'],'region_name'=>$d['region_name'],'subregion_id'=>$d['subregion_id'],'subregion_name'=>$d['subregion_name'],'name'=>$name,'normalized_name'=>$norm,'search_key'=>$search,'category'=>$d['category'],'rating'=>$d['rating'],'hotel_type'=>$d['hotel_type'],'latitude'=>$d['latitude'],'longitude'=>$d['longitude'],'primary_image_url'=>$d['primary_image_url'],'primary_image_url_2'=>$d['primary_image_url'],'fetched_at'=>$now];$up->execute($args);
   if($up->rowCount()===0&&$d['country_id']!==null&&$country!==null&&$name!==null&&$norm!==null&&$search!==null){$ia=$args;unset($ia['primary_image_url_2']);try{$ins->execute($ia);$catalogInserted++;}catch(PDOException $x){if((string)$x->getCode()!=='23000')throw $x;}}
   $success++;
  }catch(Throwable $x){$msg=mb_substr(str_replace(["\r","\n"],' '),0,0);$msg=mb_substr(str_replace(["\r","\n"],' ',$x->getMessage()),0,1000);$status=str_contains($x->getMessage(),'HTTP 404')?'not_found':'failure';$fail->execute([$id,$status,$now,$msg]);$detailWrites++;if($status==='not_found')$notFound++;else $failed++;}
 }
 $attempts=v2_data_tv_http_attempt_count();lac_need($attempts===$success+$notFound+$failed&&$attempts<=320,'attempt_count');
 $receipt=['schema_version'=>1,'state'=>'completed_acquisition','operation_id'=>LAC_OPERATION,'source_sha'=>$head,'control_source_sha'=>$control,'batch'=>LAC_BATCH,'private_plan_sha256'=>LAC_PLAN_SHA,'requested_profiles'=>320,'d1_excluded'=>10,'http_attempts'=>$attempts,'success'=>$success,'not_found'=>$notFound,'failed'=>$failed,'catalog_detail_writes'=>$detailWrites,'catalog_hotel_inserts'=>$catalogInserted,'profile_writes'=>0,'mapping_writes'=>0,'schema_writes'=>0,'rate_interval_ms'=>LAC_INTERVAL_MS];lac_save($dir.'/local-acquire-receipt.json',$receipt);echo lac_json($receipt)."\n";return 0;
}
if(PHP_SAPI==='cli'&&realpath((string)($argv[0]??''))===__FILE__){try{exit(lac_main($argv));}catch(Throwable){fwrite(STDERR,"local_profile_acquire_failed_no_replay\n");exit(2);}}
