<?php
declare(strict_types=1);
const LPS_OPERATION='int-andromeda-local-profile-apply-4191-source320-20261001-v1';
const LPS_PLAN_OPERATION='int-andromeda-local-profile-plan-4191-20261001-v2';
const LPS_PLAN_SHA='a2306ab97e596b5df3d3eb54e85948c0e69a29237a9e96d697017db1cd902988';
const LPS_BATCH='local4191-source320-apply-20261001';
const LPS_FIELDS=['description','primaryImage','images','address','place','build','repair','square','hotelInformation.infrastructure','hotelInformation.services','hotelInformation.meals','hotelInformation.roomTypes'];
function lps_need(bool $v,string $r):void{if(!$v)throw new RuntimeException($r);}
function lps_file(string $p,int $max):string{$b=is_file($p)&&!is_link($p)&&realpath($p)===$p&&filesize($p)>0&&filesize($p)<=$max?file_get_contents($p):false;lps_need(is_string($b),'private_file');return $b;}
function lps_json(array $v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
function lps_save(string $p,array $v):void{$b=lps_json($v)."\n";lps_need(!file_exists($p)&&!is_link($p)&&strlen($b)<=65536,'private_output');$f=fopen($p,'x');lps_need(is_resource($f),'private_output');try{lps_need(chmod($p,0600)&&fwrite($f,$b)===strlen($b)&&fflush($f),'private_output');if(function_exists('fsync'))lps_need(fsync($f),'private_flush');}finally{fclose($f);}}
function lps_scope(array $p):array{
 lps_need(($p['schema_version']??null)===1&&($p['operation_id']??null)===LPS_PLAN_OPERATION&&is_array($p['rows']??null)&&count($p['rows'])===366,'plan_contract');$counts=[];$scope=[];$seen=[];
 foreach($p['rows'] as $r){lps_need(is_array($r)&&is_int($r['anytourHotelId']??null)&&$r['anytourHotelId']>0&&is_string($r['state']??null)&&!isset($seen[$r['anytourHotelId']]),'plan_row');$seen[$r['anytourHotelId']]=1;$s=$r['state'];$counts[$s]=($counts[$s]??0)+1;if($s!=='SOURCE_MISSING')continue;$own=$r['anytourHotelId'];$local=$r['localHotelId']??null;lps_need(is_int($local)&&$local>0&&is_string($r['expectedProfileSha256']??null)&&preg_match('/^[a-f0-9]{64}$/D',$r['expectedProfileSha256'])===1&&is_int($r['expectedRevision']??null)&&$r['expectedRevision']>=1&&is_string($r['expectedAliasSha256']??null)&&preg_match('/^[a-f0-9]{64}$/D',$r['expectedAliasSha256'])===1,'source_row');$scope[$own]=['anytourHotelId'=>$own,'localHotelId'=>$local,'fields'=>LPS_FIELDS,'expectedProfileSha256'=>$r['expectedProfileSha256'],'expectedRevision'=>$r['expectedRevision'],'expectedAliasSha256'=>$r['expectedAliasSha256']];}
 ksort($counts);lps_need($counts===['D1_OVERLAP_HELD'=>10,'RETAINED_DELTA_PREPARED'=>36,'SOURCE_MISSING'=>320]&&count($scope)===320,'plan_counts');ksort($scope,SORT_NUMERIC);return $scope;
}
function lps_main(array $argv):int{
 lps_need(PHP_SAPI==='cli'&&$argv===[(string)($argv[0]??''),'--apply-source320'],'disabled');$home=(string)getenv('HOME');$root=(string)getenv('ANYTOUR_ROOT');$dir=(string)getenv('LOCAL_PROFILE_APPLY_DIR');$head=(string)getenv('LOCAL_PROFILE_SOURCE_SHA');$control=(string)getenv('LOCAL_PROFILE_CONTROL_SHA');
 lps_need($root===$home.'/www/anytoour.ru'&&realpath($root)===$root&&realpath($dir)===$dir&&dirname($dir)===$home.'/.anytoour-int-executor'&&basename($dir)===LPS_OPERATION,'runtime_scope');$reservation=json_decode(lps_file($dir.'/reservation.json',65536),true,32,JSON_THROW_ON_ERROR);lps_need(($reservation['operation_id']??null)===LPS_OPERATION&&($reservation['source_sha']??null)===$head&&($reservation['mode']??null)==='local-profile-apply-source320-4191','reservation');lps_need(!file_exists($dir.'/local-source320-apply-receipt.json'),'no_replay');
 $salvage=json_decode(lps_file($home.'/.anytoour-int-executor/int-andromeda-local-profile-acquire-salvage-4191-source320-20261001-v1/local-acquire-salvage-receipt.json',65536),true,32,JSON_THROW_ON_ERROR);lps_need(is_array($salvage)&&($salvage['state']??null)==='salvaged_verified'&&($salvage['repaired_details']??null)===320&&($salvage['readback_verified']??null)===true,'salvage_receipt');
 $bytes=lps_file($home.'/.anytoour-int-executor/'.LPS_PLAN_OPERATION.'/local-plan.json',32*1024*1024);lps_need(hash_equals(LPS_PLAN_SHA,hash('sha256',$bytes)),'plan_digest');$private=json_decode($bytes,true,512,JSON_THROW_ON_ERROR);lps_need(is_array($private),'plan_json');$expected=lps_scope($private);
 $bootstrap=$root.(is_file($root.'/data/db-v1.php')?'/data/db-v1.php':'/v2/data/db-v1.php');lps_need(is_file($bootstrap)&&!is_link($bootstrap)&&realpath($bootstrap)===$bootstrap,'bootstrap');$_SERVER['DOCUMENT_ROOT']=$root;require_once $bootstrap;require_once dirname(__DIR__,2).'/v2/data/anytour-profile-enrichment-v1.php';$db=v2_data_db();$owner=new AnyTourProfileEnrichmentV1($db);$through=gmdate('Y-m-d H:i:s');
 $profileWrites=$provWrites=$profilesUpdated=$fieldsUpdated=$selectedTotal=0;$fieldCounts=[];$chunkNo=0;
 foreach(array_chunk($expected,AnyTourProfileEnrichmentV1::MAX_BATCH,true) as $chunk){$chunkNo++;$scope=array_values(array_map(static fn(array $r):array=>array_intersect_key($r,array_flip(['anytourHotelId','localHotelId','fields'])),$chunk));$plan=$owner->plan(count($scope),$through,$scope,true);lps_need(($plan['status']??null)==='prepared_read_only'&&($plan['writes']??null)===0&&($plan['supplierCalls']??null)===0,'fresh_plan');$selected=$plan['selected']??[];lps_need(is_array($selected),'selected_shape');
  foreach($selected as $item){$own=$item['anytourHotelId']??null;lps_need(is_int($own)&&isset($chunk[$own])&&($item['localHotelId']??null)===$chunk[$own]['localHotelId']&&($item['expectedProfileSha256']??null)===$chunk[$own]['expectedProfileSha256']&&($item['expectedRevision']??null)===$chunk[$own]['expectedRevision']&&($item['expectedAliasSha256']??null)===$chunk[$own]['expectedAliasSha256'],'fresh_plan_identity');}
  $selectedTotal+=count($selected);if($selected===[])continue;$applied=$owner->apply(LPS_OPERATION.'_b'.$chunkNo,count($scope),$through,(string)$plan['planSha256'],$scope,true);lps_need(($applied['status']??null)==='committed_verified'&&($applied['supplierCalls']??null)===0&&($applied['mappingWrites']??null)===0&&($applied['legacyWrites']??null)===0,'apply_contract');$profilesUpdated+=(int)$applied['profilesUpdated'];$profileWrites+=(int)$applied['profileWrites'];$provWrites+=(int)$applied['provenanceWrites'];$fieldsUpdated+=(int)$applied['fieldsFilled'];foreach(($applied['fieldCounts']??[]) as $k=>$v)$fieldCounts[$k]=($fieldCounts[$k]??0)+(int)$v;
 }
 ksort($fieldCounts);lps_need($profilesUpdated===$profileWrites&&$profilesUpdated===$provWrites&&$profilesUpdated===$selectedTotal,'apply_totals');
 $receipt=['schema_version'=>1,'state'=>'committed_verified','operation_id'=>LPS_OPERATION,'source_sha'=>$head,'control_source_sha'=>$control,'batch'=>LPS_BATCH,'private_plan_sha256'=>LPS_PLAN_SHA,'requested_profiles'=>320,'selected_profiles'=>$selectedTotal,'profiles_updated'=>$profilesUpdated,'fields_updated'=>$fieldsUpdated,'field_counts'=>$fieldCounts,'profile_writes'=>$profileWrites,'provenance_writes'=>$provWrites,'supplier_calls'=>0,'provider_http_calls'=>0,'mapping_writes'=>0,'legacy_writes'=>0,'schema_writes'=>0,'readback_verified'=>true];lps_save($dir.'/local-source320-apply-receipt.json',$receipt);echo lps_json($receipt)."\n";return 0;
}
if(PHP_SAPI==='cli'&&realpath((string)($argv[0]??''))===__FILE__){try{exit(lps_main($argv));}catch(Throwable){fwrite(STDERR,"local_profile_source320_apply_failed_no_replay\n");exit(2);}}
