

/* donor:search3-summary-cta.js @ e5baf32f455cdb0aa1a704964f28e5efbebf57ff */
(function(){'use strict';
let relayoutTimer=0;
/* @include behavior/lead/note.js */
function ensureWithNote(){ensure();ensureLeadNote()}
function root(){return document.getElementById('selectedTour')}
function syncFlightHeading(r){if(!r)return;const strong=r.querySelector('.tour-flights .section-heading strong'),hint=r.querySelector('.tour-flights .section-heading span'),review=r.classList.contains('search3-final-review');if(strong)strong.textContent=review?'Рейсы':'Выберите рейс';if(hint)hint.textContent=review?'Выбранный перелёт':'Сравните время, багаж и доплату — цена тура обновится автоматически'}
function ensureFlightContinue(){const r=root(),box=r&&r.querySelector('.tour-flights');if(!box)return;let action=box.querySelector('.search3-flight-continue');if(!action){action=document.createElement('div');action.className='search3-flight-continue';action.innerHTML='<button type="button" class="primary">Далее: итог тура</button>';box.appendChild(action)}action.hidden=false;action.querySelector('button').textContent=r.classList.contains('search3-final-review')?'Изменить рейс':'Далее: итог тура';syncFlightHeading(r)}
function enterReview(){const r=root();if(!r)return;r.classList.add('search3-final-review');ensureFlightContinue();window.dispatchEvent(new CustomEvent('v2:booking-review',{detail:{}}));const target=r.querySelector('.search3-final-sections,.search3-lead-shell,.lead-form');if(target)target.scrollIntoView({behavior:'smooth',block:'start'})}
function exitReview(){const r=root();if(!r)return;r.classList.remove('search3-final-review');ensureFlightContinue();const flights=r.querySelector('.tour-flights');if(flights)flights.scrollIntoView({behavior:'smooth',block:'start'})}
function relayout(){if(window.Search3BookingSummary&&typeof window.Search3BookingSummary.syncLayout==='function')window.Search3BookingSummary.syncLayout()}
function relayoutSoon(){if(relayoutTimer)clearTimeout(relayoutTimer);relayoutTimer=setTimeout(function(){relayoutTimer=0;relayout()},0)}
function afterPaint(fn){if(typeof requestAnimationFrame==='function')requestAnimationFrame(function(){setTimeout(fn,0)});else setTimeout(fn,0)}
function emitLeadEntry(active,source){setTimeout(function(){window.dispatchEvent(new CustomEvent('search3:lead-entry',{detail:{active:!!active,source:source||'summary'}}))},0)}
function ensureBack(r,entry){if(!r)return null;let back=r.querySelector('.search3-lead-back');if(!back){back=document.createElement('button');back.type='button';back.className='search3-lead-back';back.textContent='← Вернуться к туру';const shell=r.querySelector('.search3-lead-shell');if(shell)r.insertBefore(back,shell);else r.appendChild(back)}back.hidden=!entry;return back}
function isolateRootChildren(r,entry){if(!r)return;const keep=new Set(['search3-lead-back','search3-lead-shell']);Array.from(r.children).forEach(node=>{const allowed=Array.from(keep).some(cls=>node.classList&&node.classList.contains(cls));if(entry&&!allowed){if(node.dataset.search3LeadIsolated!=='1'){node.dataset.search3LeadIsolated='1';node.style.setProperty('display','none','important')}}else if(!entry&&node.dataset.search3LeadIsolated==='1'){delete node.dataset.search3LeadIsolated;node.style.removeProperty('display')}})}
function syncLeadVisibility(r,form){const review=r&&r.classList.contains('search3-final-review'),entry=r&&r.classList.contains('search3-lead-entry');ensureBack(r,entry);isolateRootChildren(r,entry);if(review&&!entry)form.style.setProperty('display','none','important');else form.style.removeProperty('display');relayoutSoon()}
function ensure(){const r=root(),summary=r&&r.querySelector('.search3-booking-summary'),form=r&&r.querySelector('.lead-form');if(!summary||!form)return;let actions=summary.querySelector('.search3-summary-actions');if(!actions){actions=document.createElement('div');actions.className='search3-summary-actions';actions.innerHTML='<button type="button" class="search3-summary-submit">Перейти к заявке</button><p>Перед отправкой проверьте выбранный тур и рейс.</p>';summary.appendChild(actions)}const active=r.classList.contains('search3-final-review'),entry=r.classList.contains('search3-lead-entry');form.classList.toggle('search3-has-summary-submit',active&&!entry);syncLeadVisibility(r,form);const sent=form.dataset.sent==='1';const sending=form.dataset.search3LeadState==='sending';const button=actions.querySelector('.search3-summary-submit');if(button){button.disabled=sent||sending;button.textContent=sent?'Заявка отправлена':sending?'Отправляем…':'Перейти к заявке'}actions.hidden=!active||entry;}
function enterLead(source){const r=root(),form=r&&r.querySelector('.lead-form');if(!r||!form)return false;r.classList.add('search3-lead-entry');ensure();emitLeadEntry(true,source||'summary');afterPaint(function(){relayoutSoon();try{form.scrollIntoView({behavior:'smooth',block:'start'})}catch(e){try{form.scrollIntoView()}catch(_){}}const phone=form.querySelector('input[name="phone"]');if(phone){try{phone.focus({preventScroll:true})}catch(e){try{phone.focus()}catch(_){}}}});return true}
function leaveLead(){const r=root();if(!r)return;r.classList.remove('search3-lead-entry');isolateRootChildren(r,false);ensure();emitLeadEntry(false,'back');afterPaint(function(){relayoutSoon();const summary=r.querySelector('.search3-booking-summary');if(summary){try{summary.scrollIntoView({behavior:'smooth',block:'start'})}catch(e){try{summary.scrollIntoView()}catch(_){}}}const button=summary&&summary.querySelector('.search3-summary-submit');if(button){try{button.focus({preventScroll:true})}catch(e){try{button.focus()}catch(_){}}}})}
window.addEventListener('v2:flight-selected',()=>setTimeout(ensureFlightContinue,0));
window.addEventListener('v2:booking-review',()=>setTimeout(()=>{syncFlightHeading(root());ensureWithNote()},0));
['v2:lead-started','v2:lead-success','v2:lead-error','search3:lead-entry'].forEach(name=>window.addEventListener(name,()=>setTimeout(ensure,0)));
window.addEventListener('v2:tour-selected',()=>{const r=root();if(r){r.classList.remove('search3-final-review','search3-lead-entry');isolateRootChildren(r,false)}setTimeout(()=>{syncFlightHeading(r);ensureWithNote()},0)});
document.addEventListener('click',e=>{const summaryButton=e.target&&e.target.closest&&e.target.closest('#selectedTour .search3-summary-submit');if(summaryButton){e.preventDefault();enterLead('summary');return}const back=e.target&&e.target.closest&&e.target.closest('#selectedTour .search3-lead-back');if(back){e.preventDefault();leaveLead();return}const flight=e.target&&e.target.closest&&e.target.closest('#selectedTour .search3-flight-continue button');if(!flight)return;e.preventDefault();const r=root();if(r&&r.classList.contains('search3-final-review'))exitReview();else enterReview()});
window.Search3SummaryCta={ensure,enterLead,leaveLead,isolateRootChildren,version:8};
})();
