/* Minimal selected-tour review and lead navigation. */
(function(){'use strict';
function root(){return document.getElementById('selectedTour')}
function soon(fn){setTimeout(fn,0)}
function emit(active,source){soon(()=>window.dispatchEvent(new CustomEvent('search3:lead-entry',{detail:{active,source}})))}
function ensureFlightContinue(){const r=root(),flights=r&&r.querySelector('.tour-flights');if(!flights)return null;let action=flights.querySelector('.search3-flight-continue');if(!action){action=document.createElement('div');action.className='search3-flight-continue';action.innerHTML='<button type="button" class="primary">Далее: итог тура</button>';flights.appendChild(action)}action.hidden=false;const button=action.querySelector('button'),label=r.classList.contains('search3-final-review')?'Изменить рейс':'Далее: итог тура';if(button&&button.textContent!==label)button.textContent=label;return button}
function ensureBack(r,entry){let back=r.querySelector('.search3-lead-back');if(!back){back=document.createElement('button');back.type='button';back.className='search3-lead-back';back.textContent='← Вернуться к туру';const shell=r.querySelector('.search3-lead-shell');shell?r.insertBefore(back,shell):r.appendChild(back)}back.hidden=!entry;return back}
function isolateRootChildren(r,entry){if(!r)return;Array.from(r.children).forEach(node=>{const keep=node.classList&&(node.classList.contains('search3-lead-back')||node.classList.contains('search3-lead-shell'));if(entry&&!keep&&node.dataset.search3LeadIsolated!=='1'){node.dataset.search3LeadIsolated='1';node.style.setProperty('display','none','important')}else if(!entry&&node.dataset.search3LeadIsolated==='1'){delete node.dataset.search3LeadIsolated;node.style.removeProperty('display')}})}
function ensure(){const r=root(),summary=r&&r.querySelector('.search3-booking-summary'),form=r&&r.querySelector('.lead-form');if(!summary||!form)return;let actions=summary.querySelector('.search3-summary-actions');if(!actions){actions=document.createElement('div');actions.className='search3-summary-actions';actions.innerHTML='<button type="button" class="search3-summary-submit">Перейти к заявке</button>';summary.appendChild(actions)}const review=r.classList.contains('search3-final-review'),entry=r.classList.contains('search3-lead-entry');ensureBack(r,entry);isolateRootChildren(r,entry);if(review&&!entry)form.style.setProperty('display','none','important');else form.style.removeProperty('display');const button=actions.querySelector('.search3-summary-submit'),sent=form.dataset.sent==='1';if(button){button.disabled=sent;button.textContent=sent?'Заявка отправлена':'Перейти к заявке'}actions.hidden=!review||entry}
function enterReview(){const r=root();if(!r)return;r.classList.add('search3-final-review');ensureFlightContinue();ensure();window.dispatchEvent(new CustomEvent('v2:booking-review',{detail:{}}));const target=r.querySelector('.search3-lead-shell,.lead-form');if(target)target.scrollIntoView({behavior:'smooth',block:'start'})}
function exitReview(){const r=root();if(!r)return;r.classList.remove('search3-final-review');ensureFlightContinue();ensure();const flights=r.querySelector('.tour-flights');if(flights)flights.scrollIntoView({behavior:'smooth',block:'start'})}
function enterLead(source){const r=root(),form=r&&r.querySelector('.lead-form');if(!r||!form)return false;r.classList.add('search3-lead-entry');ensure();emit(true,source||'summary');soon(()=>{form.scrollIntoView({behavior:'smooth',block:'start'});const phone=form.querySelector('input[name="phone"]');if(phone)phone.focus({preventScroll:true})});return true}
function leaveLead(){const r=root();if(!r)return;r.classList.remove('search3-lead-entry');isolateRootChildren(r,false);ensure();emit(false,'back');soon(()=>{const summary=r.querySelector('.search3-booking-summary'),button=summary&&summary.querySelector('.search3-summary-submit');if(summary)summary.scrollIntoView({behavior:'smooth',block:'start'});if(button)button.focus({preventScroll:true})})}
window.addEventListener('v2:flight-selected',()=>soon(ensureFlightContinue));
['v2:booking-review','v2:lead-started','v2:lead-success','v2:lead-error','search3:lead-entry'].forEach(name=>window.addEventListener(name,()=>soon(ensure)));
window.addEventListener('v2:tour-selected',()=>{const r=root();if(r){r.classList.remove('search3-final-review','search3-lead-entry');isolateRootChildren(r,false)}soon(()=>{ensureFlightContinue();ensure()})});
document.addEventListener('click',event=>{const target=event.target&&event.target.closest;if(!target)return;if(event.target.closest('#selectedTour .search3-summary-submit')){event.preventDefault();enterLead('summary')}else if(event.target.closest('#selectedTour .search3-lead-back')){event.preventDefault();leaveLead()}else if(event.target.closest('#selectedTour .search3-flight-continue button')){event.preventDefault();const r=root();r&&r.classList.contains('search3-final-review')?exitReview():enterReview()}});
window.Search3SummaryCta={ensure,enterLead,leaveLead,isolateRootChildren,version:9};
})();
