/* Private formatters for the booking summary and selected services. */
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function text(v){if(v==null)return'';if(typeof v==='string'||typeof v==='number')return String(v);if(Array.isArray(v))return v.map(text).filter(Boolean).join(', ');for(const k of ['russianName','fullRussianName','name','title','value','text']){const s=text(v[k]);if(s)return s;}return'';}
function people(t){const p=[];if(t&&t.adults)p.push(t.adults+' взр.');if(t&&t.childs)p.push(t.childs+' дет.');return p.join(' + ')||'—';}
function place(t){const h=t&&t.hotel||{};return [text(h.country),text(h.region),text(h.subRegion)].filter(Boolean).join(', ')||'—';}
function placeholder(segment){if(!segment||typeof segment!=='object')return false;const number=String(segment.number||'').replace(/\s+/g,'').toUpperCase();return /000$/.test(number)&&String((segment.departure||{}).time||'')==='00:00'&&String((segment.arrival||{}).time||'')==='00:00';}
function segments(variant){return variant?[].concat(Array.isArray(variant.forward)?variant.forward:[],Array.isArray(variant.backward)?variant.backward:[]).filter(Boolean):[];}
function supplierFlightLabel(variant,emptyLabel){if(!variant)return emptyLabel||'Рейс уточняется';const labels=segments(variant).map(segment=>[text(segment.company),placeholder(segment)?'рейс уточняется':text(segment.number)].filter(Boolean).join(' '));return Array.from(new Set(labels.filter(Boolean))).join(' · ')||'Рейс уточняется';}
function flightBaggage(variant){return Array.from(new Set(segments(variant).map(segment=>{const raw=segment.baggage,missing=raw===null||raw===undefined||raw==='',zero=!missing&&Number(raw)===0,bag=missing||(placeholder(segment)&&zero)?'багаж уточняется':zero?'без багажа':'багаж '+text(raw)+' кг',carry=text(segment.carryOn);return bag+' · ручная кладь '+(carry&&carry!=='0'?carry:'уточняется');}))).join('; ');}
